### ISSUE TITLE
filterVlan returns 0 for role when there is no match

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1006]
We call filterVlan like the following:

```
my ($result, $role) = $this->filterVlan('NodeInfoForAutoReg', $switch, $switch_port, $mac, $node_info, $conn_type, $user_name, $ssid, $radius_request);
```

Therefore we assign 0 to the role when there is no match.
Unfortunately we have code that looks for $role and tries to use it.

Better to return undef if there is not match.

**Comment by jrouzierinverse** [comment]
FIx in commit 2938cee1f98ad67f3d4043407ec4750e54a46057
