### ISSUE TITLE
the project can not solve the chinese

### ISSUE THREAD

**Issue by echotor** [inverse-inc/packetfence#1007]
I add a role with chinese, but it can not show the chinese, should I handle it?

**Comment by julsemaan** [comment]
I don't think creating a role with anything else than standard ascii characters is a good idea.

**Comment by echotor** [comment]
But if I need to use chinese, is there something should I need to do?

**Comment by julsemaan** [comment]
This is not at all in our roadmap and will most likely never be.

If you absolutely need to have it, then you can add support for it.

I can tell you in advance, this is a bad idea. There is just nothing in PacketFence that was designed to handle chinese characters
