### ISSUE TITLE
pfcmd service pf start needs redis_cache

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1009]
But redis_cache is started by pfcmd service pf start

:chicken: :egg: 

redis_cache should be in another init script or started independently from pfcmd

**Comment by dwlfrth** [comment]
following

**Comment by jrouzierinverse** [comment]
Fixed in commit 4bf2e2d4d46ef6f69f58b29b87d824a807fb1af3

**Comment by julsemaan** [comment]
I looked at the commit and it doesn't seem to show the status of the redis_cache service

As this almost the most important service of packetfence, one would expect seeing if its running

**Comment by jrouzierinverse** [comment]
Fixed in commit f507bf34fe899e17575ca832d65ef017d033999d
