### ISSUE TITLE
While I load config file, but the char show is not right. For non-latin1 char, they are not right.

### ISSUE THREAD

**Issue by echotor** [inverse-inc/packetfence#1011]
I think the reason is template, They solve without currect encoding.
should I solve it?

**Comment by echotor** [comment]
I want to handle the character with utf8 in system, how I config and change in the system?

**Comment by echotor** [comment]
After setting the form and template in some files, but web show in no-correct charset sometime and show in correct charset other time. This is why?
I want to they can show in always UTF8 charset, how should I config and change?

**Comment by julsemaan** [comment]
The bug tracker is for issues only.

Please use the mailing list for help in configuration
