### ISSUE TITLE
pfqueue doesn't want to die

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1016]
I am not able to establish the conditions in which it happens but when restarting PacketFence, it happens that pfqueue doesn't want to die and pfcmd waits the full minute.

Doing a ps shows the process is still running

Doing a `pkill -9 pfqueue` kills it properly and unblocks pfcmd

**Comment by jrouzierinverse** [comment]
Can you provide the log file?

**Comment by jrouzierinverse** [comment]
FIxed in commit 5324c1293999988d3804a1b54cec2fd88b243e9e
