### ISSUE TITLE
Have redis_cache and pfconfig show in pfcmd service listing

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1017]

**Comment by dwlfrth** [comment]
following

**Comment by julsemaan** [comment]
Should we really, they aren't part of the 'official' pf managed processes

**Comment by julsemaan** [comment]
Now that we can manage each service individually using systemctl, this doesn't sound relevant anymore.

Any objections to closing this ?

**Comment by jrouzierinverse** [comment]
Nope
