### ISSUE TITLE
No timeout set when reading from OMAPI socket

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1024]
There is not timeout set when reading from the OMAPI.

pfdhcplistener can wait indefinitly

**Comment by jrouzierinverse** [comment]
What should be the default timeout?

**Comment by louismunro** [comment]
Short.
A few seconds at most.

If the answer comes much later than, say five seconds it’s probably better to fail.

## 

Louis Munro
lmunro@inverse.ca  ::  www.inverse.ca 
+1.514.447.4918 x125  :: +1 (866) 353-6153 x125
Inverse inc. :: Leaders behind SOGo (www.sogo.nu) and PacketFence (www.packetfence.org)

**Comment by julsemaan** [comment]
I would even say a second

Anything else slower than should go through the iplog
