### ISSUE TITLE
To reduce circular dependencies move shared resources to a seperate namespace.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1039]
All constants will be moved to pf::constants
All pfconfig resources will be moved to pf::config

**Comment by julsemaan** [comment]
This is more a meta issue, I think @jrouzierinverse started a bit of work on this.

I don't see much point keeping this opened, @jrouzierinverse do you agree to close ?

**Comment by jrouzierinverse** [comment]
This is more of a on going maintenance task than a bug so I will close.
