### ISSUE TITLE
pfdhcplistener status is bogus in the web admin

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1040]
In the web admin, pfdhcplistener is only listed once, even if multiple dhcplistener are configured. This is fine but if one is going down, the pfdhcplistener entry still state as "Started". The only way to see if all the pfdhcplistener are started would be to use the command line 'service packetfence status'.

Solutions:
- List all of the pfdhcplistener in the status page with their own status
- Keep only one entry but if one is down, it should not report as "Started"
- Fancy listing with a + sign beside pfdhcplistener to list all of the configured ones along with their status

**Comment by jrouzierinverse** [comment]
This will require a bit more work than I expected.
I will move this to 5.7
