### ISSUE TITLE
pfdhcplistener logger not reporting right PID

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1044]
Dec 04 14:48:30 pfdhcplistener(4798) INFO: pfdhcplistener_eth1.110 starting and writing 4803 to /usr/local/pf/var/run/pfdhcplistener_eth1.110.pid (pf::services::util::createpid)

**Comment by jrouzierinverse** [comment]
Fixed in commit 80c5fa3f0117039360feff0768a04dffc684c193
