### ISSUE TITLE
Support the utf8 coding

### ISSUE THREAD

**Issue by echotor** [inverse-inc/packetfence#1046]
I find that it does not support the utf-8 character coding, so I make a patch for the version 5.4.
The need thing to do is below:
1、change the character coding of mysql from latin to utf8
2、use the patch file to fix
I hope that you can accept this suggestion.

[Uploading patch.txt…]()

**Comment by echotor** [comment]
How I upload the patch file? I can not upload the patch file in this.

**Comment by echotor** [comment]
diff --git a/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication.pm b/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication.pm
index 5c0b373..3eab568 100644
--- a/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication.pm
+++ b/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication.pm
@@ -17,8 +17,10 @@ use HTTP::Status qw(:constants is_error is_success);
 use Moose;
 use namespace::autoclean;
 use POSIX;
+use utf8;

 use Log::Log4perl qw(get_logger);
+use pf::util;
 use pf::authentication;
 use pfappserver::Form::Config::Authentication;

@@ -44,7 +46,7 @@ sub index :Path :Args(0) :AdminRole('USERS_SOURCES_READ') {
     my $external_types = availableAuthenticationSourceTypes('external');
     my $exclusive_types = availableAuthenticationSourceTypes('exclusive');
     my $form = pfappserver::Form::Config::Authentication->new(ctx => $c,
-                                                   init_object => {sources => $sources});
- ```
                                                init_object => {sources => utf8_decoder $sources});
  ```
  
   $form->process();
  
   $c->stash(
  diff --git a/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication/Source.pm b/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication/Source.pm
  index 5170408..5be4909 100644
  --- a/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication/Source.pm
  +++ b/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication/Source.pm
  @@ -17,10 +17,12 @@ use HTTP::Status qw(:constants is_error is_success);
  use Moose;
  use namespace::autoclean;
  use POSIX;
  +use utf8;
  
  use pf::ConfigStore::Authentication;
  
  use pf::authentication;
  +use pf::util;
  use pfappserver::Form::Config::Authentication::Source;
  use pfappserver::Form::Config::Authentication::Rule;

@@ -123,7 +125,7 @@ sub read :Chained('object') :PathPart('read') :Args(0) :AdminRole('USERS_SOURCES
             my @attrs = map { $_->name } $c->stash->{source}->meta->get_all_attributes();
             @obj{@attrs} = @{$c->stash->{source}}{@attrs};
         }
-        $form = $form->new(ctx => $c, init_object => \%obj);
-        $form = $form->new(ctx => $c, init_object => utf8_decoder \%obj);
       $form->process();
       $c->stash->{form} = $form;
       $c->stash->{template} = 'authentication/source/read.tt' unless ($c->stash->{template});
  @@ -172,7 +174,7 @@ sub update :Chained('object') :PathPart('update') :Args(0) :AdminRole('USERS_SOU
       my %obj;
       my @attrs = map { $_->name } $source->meta->get_all_attributes();
       @obj{@attrs} = @{$source}{@attrs};
-        $form->process( ctx => $c, init_object => \%obj);
- ```
     $form->process( ctx => $c, init_object => utf8_decoder \%obj);
   $c->stash->{action_uri} = $c->uri_for($self->action_for('update'), [$form->value->{id}]);
   $c->stash->{form} = $form;
   $c->stash->{template} = 'authentication/source/read.tt';
  ```
  
  @@ -302,7 +304,7 @@ sub rule_read :Chained('rule_object') :PathPart('read') :Args(0) :AdminRole('USE
   }
  
   $form = pfappserver::Form::Config::Authentication::Rule->new(ctx => $c,
-                                                         init_object => $c->stash->{rule},
- ```
                                                      init_object => utf8_decoder($c->stash->{rule}),
                                                    source_type => $c->stash->{source}->{type},
                                                    attrs => $c->stash->{source}->available_attributes());
  ```
  
   $form->process;
  diff --git a/html/pfappserver/lib/pfappserver/View/HTML.pm b/html/pfappserver/lib/pfappserver/View/HTML.pm
  index 9b41c46..ce631cd 100644
  --- a/html/pfappserver/lib/pfappserver/View/HTML.pm
  +++ b/html/pfappserver/lib/pfappserver/View/HTML.pm
  @@ -10,6 +10,7 @@ use Template::AutoFilter;
  use Template::AutoFilter::Parser;
  
  **PACKAGE**->config(
-    ENCODING    => 'UTF-8',
   TEMPLATE_EXTENSION => '.tt',
   PRE_PROCESS => 'macros.inc',
   FILTERS => {
  diff --git a/html/pfappserver/pfappserver.psgi b/html/pfappserver/pfappserver.psgi
  index c0c4942..f22dbab 100644
  --- a/html/pfappserver/pfappserver.psgi
  +++ b/html/pfappserver/pfappserver.psgi
  @@ -1,5 +1,6 @@
  use strict;
  use warnings;
  +use utf8;
  
  use pfappserver;

diff --git a/lib/pf/Authentication/Source/LDAPSource.pm b/lib/pf/Authentication/Source/LDAPSource.pm
index 6dd3e22..541c5b1 100644
--- a/lib/pf/Authentication/Source/LDAPSource.pm
+++ b/lib/pf/Authentication/Source/LDAPSource.pm
@@ -417,7 +417,7 @@ sub ldap_filter_for_conditions {
       foreach my $condition (@{$conditions}) {
           my $str;
           my $operator = $condition->{'operator'};
-          my $value = escape_filter_value($condition->{'value'});
- ```
       my $value = utf8_decoder escape_filter_value($condition->{'value'});
     my $attribute = $condition->{'attribute'};
  
     if ($operator eq $Conditions::EQUALS) {
  ```
  
  diff --git a/lib/pf/CHI.pm b/lib/pf/CHI.pm
  index a0591b2..d59dd75 100644
  --- a/lib/pf/CHI.pm
  +++ b/lib/pf/CHI.pm
  @@ -27,6 +27,7 @@ use DBI;
  use Scalar::Util qw(tainted reftype);
  use pf::log;
  use Log::Any::Adapter;
  +use utf8;
  Log::Any::Adapter->set('Log4perl');
  
  my @PRELOADED_CHI_DRIVERS;
  @@ -163,7 +164,7 @@ sub setDBIDriverParams {
   $storage->{dbh} = sub {
       my ($db,$host,$port,$user,$pass) = @{$dbi}{qw(db host port user pass)};
       return DBI->connect( "dbi:mysql:dbname=$db;host=$host;port=$port",
-        $user, $pass, { RaiseError => 0, PrintError => 0 } );
-        $user, $pass, { RaiseError => 0, PrintError => 0, mysql_enable_utf8 => 1 } );
   }
  }

diff --git a/lib/pf/config/cached.pm b/lib/pf/config/cached.pm
index dd7dcbc..f46a00a 100644
--- a/lib/pf/config/cached.pm
+++ b/lib/pf/config/cached.pm
@@ -279,6 +279,7 @@ use POSIX::2008;
 use Data::Swap();
 use Data::Structure::Util qw(unbless);
 use base qw(pf::IniFiles);
+use utf8;

 our $CACHE;
diff --git a/lib/pf/db.pm b/lib/pf/db.pm
index eac32de..d0f19d1 100644
--- a/lib/pf/db.pm
+++ b/lib/pf/db.pm
@@ -101,7 +101,7 @@ sub db_connect {
     # TODO database prepared statements are disabled by default in dbd::mysql
     # we should test with them, see http://search.cpan.org/~capttofu/DBD-mysql-4.013/lib/DBD/mysql.pm#DESCRIPTION
     $mydbh = DBI->connect( "dbi:mysql:dbname=$db;host=$host;port=$port",
-        $user, $pass, { RaiseError => 0, PrintError => 0, mysql_auto_reconnect => 1 } );
- ```
     $user, $pass, { RaiseError => 0, PrintError => 0, mysql_auto_reconnect => 1, mysql_enable_utf8 => 1 } );
  ```
  
   # make sure we have a database handle
   if ($mydbh) {
  diff --git a/lib/pf/util.pm b/lib/pf/util.pm
  index ffc7c7f..b4d8c93 100644
  --- a/lib/pf/util.pm
  +++ b/lib/pf/util.pm
  @@ -32,6 +32,7 @@ use NetAddr::IP;
  use File::Temp;
  use Date::Parse;
  use Crypt::OpenSSL::X509;
  +use Encode;
  
  our ( %local_mac );

@@ -67,6 +68,7 @@ BEGIN {
         safe_file_update
         fix_file_permissions
         strip_username
-        utf8_decoder
   );
  }

@@ -1095,6 +1097,40 @@ sub strip_username {
     return $username;
 }

+sub utf8_decoder {
-    my $obj = shift;
  +
-    eval { my %h = %$obj; };
-    if (! $@) {
-        for my $k (keys %$obj) {
-            my $v = $obj->{$k};
-            $obj->{$k} = utf8_decoder($v);
-        }
-        return $obj;
-    }
-    elsif (ref $obj eq 'ARRAY') {
-        undef $@;
-        my $len = @$obj;
-        for my $idx (0 .. $len-1) {
-            $obj->[$idx] = utf8_decoder($obj->[$idx]);
-        }
-        return $obj;
-    }
-    elsif (ref $obj eq q{}) {
-        undef $@;
-        try {
-                return decode('UTF-8', $obj);
-        }
-        catch {
-                return $obj;
-        }
-    }
-    else {
-        undef $@;
-        return $obj;
-    }
  +}
  +
  =back
  
  =head1 AUTHOR

**Comment by louismunro** [comment]
Please create a pull request.
