### ISSUE TITLE
Reevaluate access is messing with node modify from the admin GUI

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1056]
If you try to change the role or anything of a node with an open locationlog, pf::enforcement::_should_we_reassign_vlan will call fetchVlanForNode with the info of that opened locationlog messing with the change you are attempting to do...

**Comment by fdurand** [comment]
Can you check if 3d22d952520ba45249cbce2254e0ec7a191b9d34 fix the issue ?

**Comment by dwlfrth** [comment]
Fixed by PR #1060
