### ISSUE TITLE
Could not write namespace config::Cluster to L2 cache ! This is bad

### ISSUE THREAD

**Issue by rayidi** [inverse-inc/packetfence#1063]
Hello,

I've successfully installed PacketFence on CentOs 6.7x64, but when I'm starting packetfence using `service packetfence restart` its giving me the following error.

`[root@PacketFence ~]# service packetfence restart
Restarting PacketFence...service|command
carbon-cache|already stopped
carbon-relay|already stopped
collectd|already stopped
dhcpd|already stopped
haproxy|already stopped
httpd.aaa|already stopped
httpd.admin|already stopped
httpd.graphite|already stopped
httpd.portal|already stopped
httpd.proxy|already stopped
httpd.webservices|already stopped
iptables|already stopped
p0f|already stopped
pfbandwidthd|already stopped
pfdetect|already stopped
pfdns|already stopped
pfmon|already stopped
pfqueue|already stopped
pfsetvlan|already stopped
radiusd-acct|already stopped
radiusd|already stopped
radsniff3|already stopped
redis_queue|already stopped
snmptrapd|already stopped
snort|already stopped
statsd|already stopped
suricata|already stopped
keepalived|already stopped
Could not write namespace config::PfDefault to L2 cache ! This is bad.
Could not write namespace config::Documentation to L2 cache ! This is bad.
Could not write namespace config::Cluster to L2 cache ! This is bad.
Could not write namespace config::Pf to L2 cache ! This is bad.
Could not write namespace interfaces to L2 cache ! This is bad.
Could not write namespace config::Network to L2 cache ! This is bad.
Could not write namespace config::Authentication to L2 cache ! This is bad.
Could not write namespace config::Switch to L2 cache ! This is bad.
Could not write namespace config::Domain to L2 cache ! This is bad.
Could not write namespace resource::fqdn to L2 cache ! This is bad.
Could not write namespace config::AdminRoles to L2 cache ! This is bad.
Could not write namespace config::ApacheFilters to L2 cache ! This is bad.
Could not write namespace config::Authentication to L2 cache ! This is bad.
Could not write namespace resource::authentication_config_hash to L2 cache ! This is bad.
Could not write namespace resource::authentication_lookup to L2 cache ! This is bad.
Could not write namespace resource::authentication_sources to L2 cache ! This is bad.
Could not write namespace config::Profiles to L2 cache ! This is bad.
Could not write namespace resource::guest_self_registration to L2 cache ! This is bad.
Could not write namespace config::BillingTiers to L2 cache ! This is bad.
Could not write namespace config::Cluster to L2 cache ! This is bad.
Could not write namespace config::Pf to L2 cache ! This is bad.
Could not write namespace resource::CaptivePortal to L2 cache ! This is bad.
Could not write namespace resource::Database to L2 cache ! This is bad.
Could not write namespace resource::fqdn to L2 cache ! This is bad.
Could not write namespace config::Pfdetect to L2 cache ! This is bad.
Could not write namespace interfaces to L2 cache ! This is bad.
Could not write namespace interfaces::listen_ints to L2 cache ! This is bad.
Could not write namespace interfaces::dhcplistener_ints to L2 cache ! This is bad.
Could not write namespace interfaces::ha_ints to L2 cache ! This is bad.
Could not write namespace interfaces::internal_nets to L2 cache ! This is bad.
Could not write namespace interfaces::inline_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::vlan_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::monitor_int to L2 cache ! This is bad.
Could not write namespace interfaces::management_network to L2 cache ! This is bad.
Could not write namespace interfaces::portal_ints to L2 cache ! This is bad.
Could not write namespace interfaces::inline_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_isolation_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_registration_nets to L2 cache ! This is bad.
Could not write namespace resource::cluster_servers to L2 cache ! This is bad.
Could not write namespace resource::cluster_hosts to L2 cache ! This is bad.
Could not write namespace config::Documentation to L2 cache ! This is bad.
Could not write namespace config::Domain to L2 cache ! This is bad.
Could not write namespace resource::domain_dns_servers to L2 cache ! This is bad.
Could not write namespace config::Firewall_SSO to L2 cache ! This is bad.
Could not write namespace config::FloatingDevices to L2 cache ! This is bad.
Could not write namespace config::Network to L2 cache ! This is bad.
Could not write namespace interfaces to L2 cache ! This is bad.
Could not write namespace interfaces::listen_ints to L2 cache ! This is bad.
Could not write namespace interfaces::dhcplistener_ints to L2 cache ! This is bad.
Could not write namespace interfaces::ha_ints to L2 cache ! This is bad.
Could not write namespace interfaces::internal_nets to L2 cache ! This is bad.
Could not write namespace interfaces::inline_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::vlan_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::monitor_int to L2 cache ! This is bad.
Could not write namespace interfaces::management_network to L2 cache ! This is bad.
Could not write namespace interfaces::portal_ints to L2 cache ! This is bad.
Could not write namespace interfaces::inline_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_isolation_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_registration_nets to L2 cache ! This is bad.
Could not write namespace config::PKI_Provider to L2 cache ! This is bad.
Could not write namespace config::PfDefault to L2 cache ! This is bad.
Could not write namespace config::Pf to L2 cache ! This is bad.
Could not write namespace resource::CaptivePortal to L2 cache ! This is bad.
Could not write namespace resource::Database to L2 cache ! This is bad.
Could not write namespace resource::fqdn to L2 cache ! This is bad.
Could not write namespace config::Pfdetect to L2 cache ! This is bad.
Could not write namespace interfaces to L2 cache ! This is bad.
Could not write namespace interfaces::listen_ints to L2 cache ! This is bad.
Could not write namespace interfaces::dhcplistener_ints to L2 cache ! This is bad.
Could not write namespace interfaces::ha_ints to L2 cache ! This is bad.
Could not write namespace interfaces::internal_nets to L2 cache ! This is bad.
Could not write namespace interfaces::inline_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::vlan_enforcement_nets to L2 cache ! This is bad.
Could not write namespace interfaces::monitor_int to L2 cache ! This is bad.
Could not write namespace interfaces::management_network to L2 cache ! This is bad.
Could not write namespace interfaces::portal_ints to L2 cache ! This is bad.
Could not write namespace interfaces::inline_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_isolation_nets to L2 cache ! This is bad.
Could not write namespace interfaces::routed_registration_nets to L2 cache ! This is bad.
Could not write namespace config::Profiles to L2 cache ! This is bad.
Could not write namespace FilterEngine::Profile to L2 cache ! This is bad.
Could not write namespace resource::URI_Filters to L2 cache ! This is bad.
Could not write namespace config::Provisioning to L2 cache ! This is bad.
Could not write namespace config::RadiusFilters to L2 cache ! This is bad.
Could not write namespace FilterEngine::RadiusScopes to L2 cache ! This is bad.
Could not write namespace config::Realm to L2 cache ! This is bad.
Could not write namespace config::Scan to L2 cache ! This is bad.
Could not write namespace config::Switch to L2 cache ! This is bad.
Could not write namespace resource::default_switch to L2 cache ! This is bad.
Could not write namespace resource::switches_ranges to L2 cache ! This is bad.
Could not write namespace config::Violations to L2 cache ! This is bad.
Could not write namespace FilterEngine::Violation to L2 cache ! This is bad.
Could not write namespace resource::accounting_triggers to L2 cache ! This is bad.
Could not write namespace resource::bandwidth_expired_violations to L2 cache ! This is bad.
Could not write namespace config::VlanFilters to L2 cache ! This is bad.
Could not write namespace FilterEngine::VlanScopes to L2 cache ! This is bad.
Could not write namespace config::Wmi to L2 cache ! This is bad.
Could not write namespace resource::array_test to L2 cache ! This is bad.
Could not write namespace resource::reverse_fqdn to L2 cache ! This is bad.
httpd.admin|not started
redis_queue|start
Checking configuration sanity...
Could not write namespace config::PfDefault to L2 cache ! This is bad.
Could not write namespace config::Documentation to L2 cache ! This is bad.
Could not write namespace config::Cluster to L2 cache ! This is bad.
Could not write namespace config::PfDefault to L2 cache ! This is bad.
Could not write namespace config::Documentation to L2 cache ! This is bad.
Could not write namespace config::Cluster to L2 cache ! This is bad.
unable to connect to database: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) at /usr/local/pf/lib/pf/version.pm line 42`

# Here are my installation process
`rpm -Uvh http://packetfence.org/downloads/PacketFence/RHEL6/`uname -i`/RPMS/packetfence-release-1-2.centos6.noarch.rpm
yum install --enablerepo=packetfence packetfence`

Also I'm unable to access the admin panel.
Please help me.

**Comment by julsemaan** [comment]
This means your database is not running which looks pretty normal since you just installed.

The bug tracker is for bugs only.

Please use the mailing list for help with configuration issues.
