### ISSUE TITLE
Network configure file read and handle error 

### ISSUE THREAD

**Issue by echotor** [inverse-inc/packetfence#1065]
In version 5.5.2.
In line 287 of file ./lib/pf/dhcp/processor.pm, it get data from variable inline_nets, and compare $dhcp->{'src_ip'} with $_->{'gateway'}. But there is a error in it.

```
 "Use of uninitialized value in string eq at /usr/local/pf/lib/pf/dhcp/processor.pm line 287."
I follow the question and find that the answer is in file pfconfig::namespaces::interfaces::inline_nets.
The function which handle the network.conf is below:
sub build {
    my ($self)         = @_;
    my %ConfigNetworks = %{ $self->{network_config} };
    my @inline_nets    = ();
    foreach my $network ( keys %ConfigNetworks ) {
        my $type = $ConfigNetworks{$network}{type};
        if ( pfconfig::namespaces::config::Network::is_network_type_inline($type) ) {
            my $inline_obj = new Net::Netmask( $network, $ConfigNetworks{$network}{'netmask'} );
            push @inline_nets, $inline_obj;
        }
    }
    return \@inline_nets;
}

push @inline_nets, $inline_obj;
```

But there is not a 'gateway' attribution in inline_obj.

Why is it?

**Comment by julsemaan** [comment]
This looks like a configuration issue.

Most likely that you haven't configured the gateway in this network...

Please use the mailing list for configuration issues before reporting bugs on this tracker

**Comment by echotor** [comment]
I log the variable '@inline_nets' in line 287 of file ./lib/pf/dhcp/processor.pm, the result is:
Dec 15 10:29:21 pfqueue(18556) INFO: [mac:80:82:87:02:90:56] 192.168.243.0/24 (pf::dhcp::processor::parse_dhcp_request)
this contain no 'gateway' info.
but there is 'gateway' info in our network.conf, like this:

```
[192.168.243.0]
dns=192.168.6.2
dhcp_start=192.168.243.10
gateway=192.168.243.1
domain-name=xxx.sankuai.info
nat_enabled=enabled
named=enabled
dhcp_max_lease_time=86400
fake_mac_enabled=disabled
dhcpd=enabled
dhcp_end=192.168.243.246
type=xxx
netmask=255.255.255.0
dhcp_default_lease_time=86400
```

I think this is a bug in the code. I hope you can detect and test your code about this.

**Comment by julsemaan** [comment]
You do seem to be right
@dwlfrth what do you think ?

**Comment by dwlfrth** [comment]
@tianhunzhixin You are right. For the moment, code has been updated not to trigger an error due to the undefined value, but a rework of the inline mode will probably make that part either relevant, or being removed.

**Comment by julsemaan** [comment]
Given the inline mode refactor has been postponed again, I will point this to the 7.1 milestone

**Comment by dwlfrth** [comment]
We will close the issue since
1. It is related to an error message that have been removed
2. It "requires" a rework of the inline mode.
Since there is no problem coming from this one, it will be addressed at the moment of the possible inline rework.

If I'm wrong, please reopen and explain.
