### ISSUE TITLE
Display error on the portal when AUP is not checked

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1068]
It will be nice to have an error displayed on the web page when we submit the form saying that the AUP is not checked.

**Comment by cgx** [comment]
And consequently, enabling the submit button even if the AUP checkbox is not checked ..

**Comment by jrouzierinverse** [comment]
This seems to be no longer an issue.

**Comment by julsemaan** [comment]
Thats right, this was filed prior to the portal frontend revamp and was fixed by it.
