### ISSUE TITLE
pfdns crash when you send a crafted query

### ISSUE THREAD

**Issue by tottikm** [inverse-inc/packetfence#1082]
When you create a craft dns query under a network segment where pf is responsible to manage the dns services, pfdns crash and can create a DOS scenario for the system. I will attach the details through the e-mail system, this bug had been confirmed and tested in version 4.3.

**Comment by louismunro** [comment]
This looks like a library version problem. 
This bug does not exist in the currently provided libraries from the PacketFence repository.

Please try with the following:

```
perl-Net-DNS-Nameserver-0:0.65-5.el6.x86_64
perl-Net-DNS-0:0.65-5.el6.x86_64
```
