### ISSUE TITLE
Twitter OAuth source: Create local account not working

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1085]
Can't create local account since we do not have the email address.
https://github.com/inverse-inc/packetfence/blob/packetfence-5.5.2/html/captive-portal/lib/captiveportal/PacketFence/Controller/Oauth2.pm#L206

Maybe we can look at Twitter returning us the email account.

**Comment by julsemaan** [comment]
![image](https://cloud.githubusercontent.com/assets/3857942/12068337/2b7f0bfc-afd9-11e5-92f5-b9af7779a000.png)

https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558
