### ISSUE TITLE
httpd.graphite - DB configuration

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1091]
By default, httpd.graphite configuration will use $Config{'monitoring'}{'db_host'} as a db host, which is fine in a standalone / db-hosted server deployment.

https://github.com/inverse-inc/packetfence/blob/packetfence-5.5.2/lib/pf/services/manager/httpd_graphite.pm#L51

If DB server is hosted somewhere else, two different settings need to be changed.

It is bogus in the sense that when creatin the DBs, we assume they are on the same host.

Need to rethink

**Comment by louismunro** [comment]
I can take care of it.

**Comment by louismunro** [comment]
Mmm. I see what you mean. 
The question in the end is: do we want to have two separate configuration items.
One for the pf database and one for pf_graphite.

If we don't (which I admit is simpler) then we should get rid of [monitoring] db_host and port.

**Comment by jrouzierinverse** [comment]
I noticed the configuration also assumes the two different databases must have the same username and password.

Personally I would prefer a one set database connections attributes for the pf and pf_graphite database.

However if it is make sense to have separate databases for pf and pf_graphite.

Then I would prefer the following logic

Default to the database.\* attributes  if the monitoring.\* attributes are blank.
And by default leave monitoring.\* blank.

```
 $tags{'db_host'}              = $Config{'monitoring'}{'db_host'} || $Config{'database'}{'host'}
 $tags{'db_pass'}              = $Config{'monitoring'}{'db_port'} || $Config{'database'}{'port'}
 $tags{'db_user'}              = $Config{'monitoring'}{'db_user} || $Config{'database'}{'user'};
 $tags{'db_pass'}              = $Config{'monitoring'}{'db_pass} || $Config{'database'}{'pass'};
```

This will allow us to move pf_graphite to a separate database server if we ever really need to but at the same time by default assume they always use a single db.

I will implement that logic later today unless anyone has any objections.

**Comment by dwlfrth** [comment]
That logic would be the best IMO.
One thing tho, all "monitoring" values are defined in the default so that "OR" would never really be used...

**Comment by dwlfrth** [comment]
And we should make sure that if we take the host from "monitoring", we take the rest of the "monitoring" section and not one value from one configuration and another from the other... that can create a mess...

**Comment by jrouzierinverse** [comment]
Ok

**Comment by dwlfrth** [comment]
That commit does not address the second concern I mentionned

**Comment by jrouzierinverse** [comment]
My question is if the other fields are blank then what should we do?
Add code in the checkup to display the error.

**Comment by dwlfrth** [comment]
Kind of...
We should check if a monitoring DB is configured, if yes, check that port, user and pass are also configured and use them. If not, display an error.
But we should cover the case where someone set a $Config{'monitoring'}{'db_user'} without an host, and that user is different than the "database""user"

**Comment by jrouzierinverse** [comment]
Sorry I did not see your second comment before pushing.

Derek the behavior is documented of what happens if you do not defined a value in the monitoring section.

Do you think that is enough?

**Comment by dwlfrth** [comment]
I think it can still lead to misconfiguration or "leftovers". We can leave it as is but a check would be better IMO.
