### ISSUE TITLE
SwitchGroup - Add new member is buggy

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1094]
You cannot add a member to a switch group while you are creating it, is this on purpose?

You need to first create the group without members and add members after the creation.

**Comment by julsemaan** [comment]
Yes this is on purpose, since its not the group that keeps track of its members but the members that keep track of the group.

Because of that, it needs to be saved before any members can be pointed to it.

One point is, the error message and the ergonomy is bad, I'll make it more user friendly.

**Comment by jrouzierinverse** [comment]
Fixed in a8a2ae1e80f841c878ff655fb2b34f1fd5079b5c
