### ISSUE TITLE
Duplicate pop up when cloning a switch.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1103]
![image](https://cloud.githubusercontent.com/assets/193997/12156272/fd1eecbe-b497-11e5-83c1-e0108c1fc303.png)

**Comment by louismunro** [comment]
This happens on Firefox 43.0.1 on OSX 10.12

**Comment by louismunro** [comment]
Only when cloning a range (e.g. 10.0.0.0/16)

**Comment by julsemaan** [comment]
Is it possible you clicked twice on clone ?

**Comment by louismunro** [comment]
Nope. 
I can reproduce it at will.

**Comment by louismunro** [comment]
Also happens in Chrome 47.

**Comment by julsemaan** [comment]
Does it happen in IE6 ?

**Comment by jrouzierinverse** [comment]
Yes and in Netscape 4.8 also

**Comment by louismunro** [comment]
Nothing happens in IE 6.

**Comment by louismunro** [comment]
Lynx is working fine for me.

**Comment by julsemaan** [comment]
Just tried it on Linux on the following browsers : 
Chrome Version 47.0.2526.106 (64-bit) 
Firefox 43.0

And it works fine

I am on the following commit right now : 1f400adb6fa91355c90f42982c0967ab82658bbb

**Comment by louismunro** [comment]
Then I guess you need to drop linux and use OS X like the rest of us civilized folks.
That way you can enjoy the same bugs as everyone.
It's good for morale and team building.

**Comment by julsemaan** [comment]
I think I prefer going to Windows Vista and IE8

That should allow me to enjoy bugs we've never thought of before

**Comment by jrouzierinverse** [comment]
I cannot replicate this either

**Comment by jrouzierinverse** [comment]
Until we can find a reliable way to replicate this let us put it on hold.

**Comment by louismunro** [comment]
I'll actually close it.
I will reopen if it reoccurs and I can replicate it reliably.
