### ISSUE TITLE
Radius audit log does not display

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1104]
![image](https://cloud.githubusercontent.com/assets/193997/12157159/cb529324-b49d-11e5-9baa-055b52a5d4c7.png)

**Comment by rouzier** [comment]
Can you provide a log entry?

**Comment by fdurand** [comment]
On devel fresh install i am not able to reproduce

**Comment by louismunro** [comment]
Can no longer reproduce either.
Closing.
