### ISSUE TITLE
Admin : Violation status column cannot be removed from node view

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1107]
In the administration interface, the new violation status column cannot be removed and cannot be sorted.

All the other columns have those two features, so one would expect it for that one too

**Comment by julsemaan** [comment]
Same goes for violation name

**Comment by julsemaan** [comment]
Also item for discussion : those two columns should be at the left of the role.

Everybody is used to having the role as the last column for quick reference.

**Comment by julsemaan** [comment]
Just realised one thing, those columns are not shown in the normal node view.

IMO they should be shown but this can wait

**Comment by jrouzierinverse** [comment]
This was by design will go away when we have a separate page for searching violations.
