### ISSUE TITLE
PacketFence detecting himself in inline after authentication on the portal

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1111]
Jan 07 11:30:26 httpd.portal(17246) ERROR: [mac:94:db:c9:38:8f:0b] WARNING ! Unknown switch(es) 172.21.149.1 (pf::SwitchFactory::instantiate)

**Comment by jrouzierinverse** [comment]
Fixed by 17a118d44536e8102f92508da7203a7978740017
