### ISSUE TITLE
pf::dhcp::parse_dhcp_request Is still referring attributes that do not exists

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1115]
Jan 07 16:13:18 pfqueue(31456) ERROR: [mac:84:38:38:79:be:86] Use of uninitialized value in string eq at /usr/local/pf/lib/pf/dhcp/processor.pm line 310.

**Comment by jrouzierinverse** [comment]
@dwlfrth I fixed the error that caused the "Use of uninitialized value in string" issue.
However you still need to review the code to see if it is still needed.
I moved this issue to 5.7

**Comment by dwlfrth** [comment]
Good move, it was spamming all over the place.
Will check for "ramification" for next release
