### ISSUE TITLE
Error each time we receive a dhcp request

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1117]
Jan 08 10:26:18 pfqueue(12499) WARN: [mac:00:03:c6:1d:9a:97] Use of uninitialized value $args in anonymous hash ({}) at /usr/local/pf/lib/pf/util/webapi.pm line 29.
 (pf::util::webapi::add_mac_to_log_context)
Jan 08 10:26:18 pfqueue(12499) ERROR: [mac:00:03:c6:1d:9a:97] Use of uninitialized value $args in anonymous hash ({}) at /usr/local/pf/lib/pf/util/webapi.pm line 29.
 (pf::util::webapi::add_mac_to_log_context)

**Comment by jrouzierinverse** [comment]
Fixed in 6ec7fcec57b5eaaf0f99e3f95d1ed063ee297fd9
