### ISSUE TITLE
Provisonning (Apple/Android)

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1119]
Issue with the profile we provide in provisionning, 

On an apple devices, (peap configuration) you have to provide your username/password twice, once when you install the profile and once when you want to connect to the network.

On android devices, (peap) you need to renconfigure your network and adding identity/password when trying to connect to a network that was autoconfigured.

**Comment by louismunro** [comment]
What is the issue? 
You are less than clear...
