### ISSUE TITLE
Admin : Bug in Users page

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1121]
In the admin the user details modal stops working when doing the following : 
- Search for a user
- Click on the details of that user
- Go in his devices and select one of his devices
- Modify an attribute of the device and click save
- Then click close on the user
- Then try to reopen the user details
- You can't switch tabs in the user details modal now

Happens on Chrome + Firefox on Windows + Ubuntu

**Comment by jrouzierinverse** [comment]
I am unable replicate this.
Were there any additional steps that were done before this?
Did you search using Advanced or  Simple search?
Did you visit other sections in the admin before doing this?
Did you use pagination?

**Comment by julsemaan** [comment]
For the record : 

Were there any additional steps that were done before this?
- No just direct access to users page
  Did you search using Advanced or Simple search?
- Simple search with the following 'ngh'
  Did you visit other sections in the admin before doing this?
- The Node page
  Did you use pagination?
- No (this is on 5.5.2)

**Comment by jrouzierinverse** [comment]
I see the double loading in packetfence 5.5.2.
However I am able to click on the tabs.
It seems to be fixed in devel.
Can you verify if it is fixed devel.
I will dig to see what fixed the issue so I can place it in maintenance.

**Comment by jrouzierinverse** [comment]
Julien were you able to replicate this in devel?

**Comment by julsemaan** [comment]
Just tried it and I am not.

Seems it was fixed between 5.5 and 5.6

Closing
