### ISSUE TITLE
We need the ability to assign arbitrary LDAP attributes values to RADIUS reply.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1124]
FreeRADIUS allows the LDAP module to get the value of any arbitrary LDAP attribute and return it in an attribute in the reply.

PacketFence ought to allow us to do the same so that we can configure everything in a single place and not have part of the configuration in the rlm_ldap module and part in the PF auth sources.

**Comment by fdurand** [comment]
Support added in 10.1
