### ISSUE TITLE
pfqueue: Doesn't seems to reconnect to redis if that one goes down

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1125]
If redis goes down and then comes back up, pfqueue seems to no longer be able to connect and process the queues.

**Comment by jrouzierinverse** [comment]
When testing I do not see this behavior.
Do you have any log entries like the following.
"Could not connect to Redis server at 127.0.0.1:6380"

**Comment by dwlfrth** [comment]
Nope

**Comment by jrouzierinverse** [comment]
Was pfqueue also killed by the OOM killer?

**Comment by dwlfrth** [comment]
Nope

**Comment by jrouzierinverse** [comment]
Can I see the logs for the pfdhcplistener?

**Comment by jrouzierinverse** [comment]
From looking at the logs it seem to happen in a long running process.
I notice the underlying c library hi-redis had an issue disconnection not being detected at times.
I will work on updating the hi-redis library for Redis::Fast

**Comment by jrouzierinverse** [comment]
I just noticed the perl module Redis::Fast recently upgraded to use the latest version of hi-redis.
Let me build a new module and see if that will help.

**Comment by julsemaan** [comment]
Seems this has helped since we never saw the issue again
