### ISSUE TITLE
RADIUS log : Can't search without putting a date and time in the fields

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1130]
In the RADIUS log, try to search  :
'Is a Phone' 'is' 'Zammit'

It requires to add a start and end date.

It should search for all records when none is set.

Also, putting only a date in the start and end field asks to input a time. It should consider the whole days.

**Comment by jrouzierinverse** [comment]
This is by design.
It was done to avoid full table scans when searching against non-indexed fields.

**Comment by julsemaan** [comment]
Then a default value should be there

**Comment by jrouzierinverse** [comment]
Fixed this by using a different approach.

9b92818d2d1d62232375f41eeb2063e81c50031b
91b63ee1eacf89b9f483151921ebe8385b7582c8
8292bee6beb8e18a84d18481c0884d77c6bf45c8
