### ISSUE TITLE
RADIUS log : A lot of fields cannot be searched

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1134]
The following fields cannot be searched correctly : 
- MAC Address (is '01:23:45:67:89:12')
- IP Address (is not '')
- Computer name (is 'not-zammits-pc')

**Comment by jrouzierinverse** [comment]
Please check to see if your date range is valid.

**Comment by julsemaan** [comment]
It is

**Comment by louismunro** [comment]
![image](https://cloud.githubusercontent.com/assets/193997/12273477/060db756-b934-11e5-82e6-44e256340bc4.png)

**Comment by julsemaan** [comment]
![image](https://cloud.githubusercontent.com/assets/3857942/12273499/1b61b13e-b934-11e5-842f-e11546e9807a.png)

**Comment by julsemaan** [comment]
Caused by the fact the time is not the same on the server and on the endpoint device.

Can't really be addressed fast but I will open another issue so that then end date is not necessary meaning the server will search up to now (or without an end limit)
