### ISSUE TITLE
RADIUS log : displayed columns should be configurable

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1138]
We should be able to add/remove columns in the RADIUS log like we do in nodes so that we can quickly see an element that interests us.

For instance, right now we can't see the role or VLAN that was returned in the overall view which would be of an interest for admins

**Comment by jrouzierinverse** [comment]
5.7?

**Comment by julsemaan** [comment]
Well, I would say this is more than a nice to have IMO because since this is a troubleshooting tool, you should be able to refine your search.

If we think about an environment where we'll have thousands of requests per day and we're looking for a pattern that occurred, we'll need a way to refine.

We could make it 'all' by default since it is more likely we will want to refine with a second parameter than we'll want to add more to our query

**Comment by julsemaan** [comment]
Stuff for the new admin, lets stop living in the past

**Comment by cgx** [comment]
Role is present, but I can't see the VLAN. Is it missing?

**Comment by julsemaan** [comment]
We don't record the VLAN in the audit log right now

We should see if this should be recorded for display or if looking at the RADIUS attributes details is enough for now

**Comment by julsemaan** [comment]
Columns are now configurable in the new admin
