### ISSUE TITLE
Multiple Called-Station-Id in the radius request cause issue.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1142]
Jan 13 10:44:24 httpd.aaa(3423) WARN: [mac:00:80:64:ae:f1:59] $VAR1 = {
          'NAS-Port-Type' => 'Ethernet',
          'Proxy-State' => '0x3634',
          'Service-Type' => 'Call-Check',
          'Calling-Station-Id' => '00:80:64:ae:f1:59',
          'Called-Station-Id' => [
                                   'f8:66:f2:af:d6:87',
                                   'F8-66-F2-AF-D6-87'
                                 ],
          'FreeRADIUS-Client-IP-Address' => '172.26.62.9',
          'Message-Authenticator' => '0x9e02bd957c87a93c131ca639f5d97bbe',
          'User-Name' => '008064aef159',
          'User-Password' => '008064aef159',
          'NAS-IP-Address' => '172.24.237.128',
          'NAS-Port' => '50507',
          'NAS-Port-Id' => 'GigabitEthernet5/0/7',
          'Framed-MTU' => '1500'
        };
 (pf::radius::extractApMacFromRadiusRequest)

**Comment by louismunro** [comment]
What happens to the audit log when that is the case?
