### ISSUE TITLE
Fingerbank Combination display

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1148]
When you have 10 combination the L10 is display after the L1, instead of having L1, L2, etc

![screenshot from 2016-01-14 11 53 17](https://cloud.githubusercontent.com/assets/9321079/12330931/75d2bdc0-bab5-11e5-9e91-7b171c1f3b03.png)

**Comment by jrouzierinverse** [comment]
The quick way to do this without changing how local ids are created.
Is to register a collation function like nsort (natural sort).

http://search.cpan.org/~ishigaki/DBD-SQLite-1.48/lib/DBD/SQLite.pm#COLLATION_FUNCTIONS

**Comment by jrouzierinverse** [comment]
After a discussion with @whitx doing a natural sort may slow down the search.
The alternative solution is to change how local ids are created but that will require changes in the fingerbank library.

**Comment by julsemaan** [comment]
Changing the format in the local library would not make it possible to catch all cases as we can't add a dozen of 0s in prefixes to help out the display. IMO, the database user should be in charge of ordering those as he wishes.

**Comment by julsemaan** [comment]
Now that we've put MySQL as an available backend, it makes things even more complicated as it doesn't seem the DBD collate solution applies to it.

I'll have to leave it on the ice for now
