### ISSUE TITLE
Display x nodes by page

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1149]
The number of nodes you choose to display doesn't save. As soon as you refreshed the page, it is going back to 25 by page.

**Comment by whitx** [comment]
Also, we need to wider the field where the number of displayed nodes is. If you select 1000, you don't see the last digit. This can make you unsure if you selected 100 or 1000 nodes to be displayed.

**Comment by julsemaan** [comment]
You have to be confident and believe in yourself.

jk, these are two good points. The first one is a bit harder to fix but the second is an easy one

**Comment by whitx** [comment]
First point have been fix, for the second it seems to happen on Chrome for Linux only for what I tested.
