### ISSUE TITLE
Fresh Installation of 5.6.0 Fails

### ISSUE THREAD

**Issue by hooray4me** [inverse-inc/packetfence#1152]
Fresh installation of 5.6.0 on Ubuntu 12.04 precise fails.
freeradius-ldap
freeradius-postgresql
freeradius-mysql
freeradius-krb5

Any Ideas?
![image](https://cloud.githubusercontent.com/assets/12399138/12356182/cac53806-bb66-11e5-9b73-178b9734cde5.png)

![image](https://cloud.githubusercontent.com/assets/12399138/12356187/ceea013c-bb66-11e5-80ef-38c886ff3575.png)

**Comment by louismunro** [comment]
Yes, and I think it’s all my fault…

Try this:

# apt-get update

# apt-get install libfreeradius2 freeradius*

Let me know if it helps.

## 

Louis Munro
lmunro@inverse.ca  ::  www.inverse.ca 
+1.514.447.4918 x125  :: +1 (866) 353-6153 x125
Inverse inc. :: Leaders behind SOGo (www.sogo.nu) and PacketFence (www.packetfence.org)

**Comment by hooray4me** [comment]
The installation completed. However, once I rebooted and went thru the configurator options, the services refuse to start. Upon a reboot nothing works.

**Comment by louismunro** [comment]
Please post the output from 
`service packetfence start`

**Comment by jrouzierinverse** [comment]
Could you see if https://github.com/inverse-inc/packetfence/commit/4c37dcea325f162a5589a4dda04be2efa52ad122.diff
will work.
