### ISSUE TITLE
Support VLAN interfaces that are named other than ethX.YYY

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1156]
Right now, VLAN interfaces absolutely need to be called ethX.YYY .

Otherwise when edited through the admin, it break the configuration file

We should add :
- A checkbox to define if it is a VLAN interface
- Which physical interface it is tied to

I'm tagging this as a question since I'm not sure if this is worth it and if we should just say that VLAN interfaces absolutely need to be named according to our convention (which is shared by a large part of the Linux community)

**Comment by louismunro** [comment]
That convention goes out the window in RHEL7 and others.
NICs no longer have names starting in eth.

Better start thinking about this....

**Comment by julsemaan** [comment]
We were able to keep creating the interfaces with suffixing '.XYZ' so lets close that.

Sounds like too much work for what it will provide
