### ISSUE TITLE
pfcmd configreload may not be reloading all the config files into the cache

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1157]

**Comment by julsemaan** [comment]
details ?

**Comment by jrouzierinverse** [comment]
pfcmd configreload is not updating the cache (I am not talking about 
pfconfig) for the config files which causing problem with the gui.

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)
