### ISSUE TITLE
Unable to match MAC address to IP

### ISSUE THREAD

**Issue by joaodomingues** [inverse-inc/packetfence#1164]
Hi,
My Packetfence is generally working fine, but with some phones, namely of WIKO brand I can't register. This happens only with some devices, we have a few handsets and one registers ok, the other two seldom register...
In my packetfence.log I have this:
Jan 22 11:34:48 httpd.portal(9573) WARN: [mac:unknown] Unable to match MAC address to IP '172.27.254.83' (pf::iplog::ip2mac)
Jan 22 11:34:48 httpd.portal(9573) INFO: [mac:unknown] Instantiate profile default (pf::Portal::ProfileFactory::_from_profile)

Thank you,

João Domingues

**Comment by julsemaan** [comment]
Hi,

Please use the mailing list for help with configuration

**Comment by joaodomingues** [comment]
Hi,
may you at least give me a clue? About configuration itself or more exactly where to look for it.

Thaks,

João Domingues

**Comment by julsemaan** [comment]
As I said, please use the mailing list, it is made exactly for this and you will get help from the whole community.

This bug tracker is for confirmed bugs and to track small features.
