### ISSUE TITLE
Collectd mis-configuration

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1170]
[error] memcached plugin: Instance "centos6-oc.jr.inverse.ca" could not connect to daemon.

**Comment by edhil** [comment]
Same issue on Debian. 
Seems that in the files /usr/local/pf/conf/monitoring/collectd.conf.debian and  /usr/local/pf/conf/monitoring/collectd.conf.rhel the following line shoud be commented out: 
LoadPlugin memcached
