### ISSUE TITLE
'trigger' table have 'vid' column as PRIMARY KEY with default NULL

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1185]
As per http://dev.mysql.com/doc/refman/5.7/en/create-table.html

>  A PRIMARY KEY is a unique index where all key columns must be defined as NOT NULL. If they are not explicitly declared as NOT NULL, MySQL declares them so implicitly (and silently). A table can have only one PRIMARY KEY. The name of a PRIMARY KEY is always PRIMARY, which thus cannot be used as the name for any other kind of index.

By running in a 'strict' mode, it will create an error

**Comment by louismunro** [comment]
Does not actually make any sense to have a key indexing "NULL"...

**Comment by dwlfrth** [comment]
Indeed...

**Comment by julsemaan** [comment]
The trigger table was removed
