### ISSUE TITLE
The field IP Address is not being populated in the Radius Audit Log

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1188]
Even if the IP is available when you click on the node.

**Comment by fdurand** [comment]
The ip come from a radius attribute not from the iplog, so if there is no attribute that contain the ip then the ip will be blank.

**Comment by whitx** [comment]
Would it l generate load to much if we going to extract it from the iplog? In my opinion we should either remove the field from the main view or populate it.

**Comment by louismunro** [comment]
My two cents:
It’s called RADIUS audit log.

It a record of what was in a RADIUS Packet.
If there's an IP in the packet, it goes in the log.
Otherwise, the field is NULL.

**Comment by louismunro** [comment]
Not a bug.
