### ISSUE TITLE
add pfcmd command to clear all namespaces at once

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1193]
Self explanatory. :+1:

**Comment by whitx** [comment]
??? pfcmd pfconfig reload ??? if we are talking about pfconfig namespaces, which would make sense

**Comment by julsemaan** [comment]
I think @zaymitte is talking about a real clear (so removing all keys from CHI)

**Comment by lzammit** [comment]
@julsemaan :+1:

**Comment by jrouzierinverse** [comment]
Which namespaces cache or pfconfig?

**Comment by lzammit** [comment]
bin/pfcmd cache \* clear
bin/pfcmd cache all clear

**Comment by jrouzierinverse** [comment]
Now that is Self explanatory :bowtie:

**Comment by julsemaan** [comment]
Sounds like a quicky to do for @jrouzierinverse
