### ISSUE TITLE
Admin GUI: Services page should ask for a confirmation before stopping / restarting service

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1194]
Just in case you are browsing that page and accidentally click a button (on a mobile per example).

**Comment by julsemaan** [comment]
Stuff for the new admin

**Comment by cgx** [comment]
We now have *protected services* that can't be stopped. That will keep the Web admin alive. Otherwise, I don't think a confirmation is required for the other services.
