### ISSUE TITLE
Saved search for users are not working

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1195]
The saved search for users (not searching a person name in nodes, really searching a user in the users tab) is broken.
The search can be saved but it cannot be used afterwards

To replicate : 
- Open 'Users'
- Search for 'zaymitte'
- Save the search and name it 'nachos'
- Try to use the nachos search
- The search doesn't trigger

**Comment by jrouzierinverse** [comment]
I am looking into it

**Comment by louismunro** [comment]
> When you gaze into the abyss, 
> the abyss also gazes into you...

**Comment by jrouzierinverse** [comment]
![image](https://cloud.githubusercontent.com/assets/2727473/13020438/61967ffe-d1a3-11e5-9293-89186050d386.png)

**Comment by louismunro** [comment]
https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjN28makvPKAhXDWT4KHdCNCRUQjRwIBw&url=https%3A%2F%2Flebowskifest.com%2Fshop%2Fnihilist-shirt&psig=AFQjCNGnI5xy_ecVtQsk-g5fwckvXA9PlQ&ust=1455397983123831
