### ISSUE TITLE
Log file permissions set incorrectly for logrotate

### ISSUE THREAD

**Issue by ianbmacdonald** [inverse-inc/packetfence#1214]
Installed PacketFence 5.7.0 for Debian/Wheezy and am now receiving the following cron error due to permission settings

/etc/cron.daily/logrotate:
error: error opening /usr/local/pf/logs/collectd.log: Permission denied
error: error opening /usr/local/pf/logs/console.log: Permission denied
error: error opening /usr/local/pf/logs/httpd.admin.log: Permission denied
error: error opening /usr/local/pf/logs/pfdhcplistener.log: Permission denied
error: error opening /usr/local/pf/logs/pfdns.log: Permission denied
error: error opening /usr/local/pf/logs/pfmon.log: Permission denied
error: error opening /usr/local/pf/logs/pfqueue.log: Permission denied
error: error opening /usr/local/pf/logs/portal_error_log: Permission denied
error: error opening /usr/local/pf/logs/statsd.log: Permission denied
error: error opening /usr/local/pf/logs/httpd.aaa.access: Permission denied
error: error opening /usr/local/pf/logs/httpd.admin.access: Permission denied
error: error opening /usr/local/pf/logs/httpd.graphite.access: Permission denied
error: error opening /usr/local/pf/logs/httpd.portal.access: Permission denied
error: error opening /usr/local/pf/logs/httpd.webservices.access: Permission denied
error: error opening /usr/local/pf/logs/httpd.aaa.error: Permission denied
error: error opening /usr/local/pf/logs/httpd.admin.error: Permission denied
error: error opening /usr/local/pf/logs/httpd.graphite.error: Permission denied
error: error opening /usr/local/pf/logs/httpd.portal.error: Permission denied
error: error opening /usr/local/pf/logs/httpd.webservices.error: Permission denied
error: error opening /usr/local/pf/logs/httpd.admin.catalyst: Permission denied
error: error opening /usr/local/pf/logs/httpd.portal.catalyst: Permission denied
run-parts: /etc/cron.daily/logrotate exited with return code 1

**Comment by julsemaan** [comment]
Can you provide the permissions of the log files using : 
`ls -lah /usr/local/pf/logs/`

**Comment by julsemaan** [comment]
No news, good news
