### ISSUE TITLE
Remove email as a mandatory field from the SMS auth source

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1225]

**Comment by dwlfrth** [comment]
Not sure where this "issue" is coming from but as far as I remember, email is the "standard" PID and this is why we ask for it.

**Comment by julsemaan** [comment]
The portal rework will fix this as it makes it so its the phone that is used as a PID

**Comment by dwlfrth** [comment]
Makes so much sense, don't know what else to add

**Comment by jrouzierinverse** [comment]
Can you config the source on which field to use as the PID?

**Comment by julsemaan** [comment]
You can configure the portal module to determine it yes.
