### ISSUE TITLE
Key listing sets are not cleaned in CHI::Driver::Redis

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1231]
The set that keeps track of the keys per namespace is never cleaned up so when the keys of the namespace expire, they are left in place in the listing set.

This leads to a leak that makes the redis process get bigger and bigger over time and leads to high disk latency when forking to dump.

**Comment by julsemaan** [comment]
Found the bug.

The Redis driver we use for CHI, keeps a set of all the current keys so they are faster to list.

The elements of this set never expire and are only removed if we explicitly delete a key which we almost never do as we let them expire.

**Comment by julsemaan** [comment]
Bug opened with the library maintainers.
https://rt.cpan.org/Public/Bug/Display.html?id=112760

**Comment by julsemaan** [comment]
Added new rewritten driver in 3abff6b5588af62cf501a706669a0accbaa4cf24

Awaiting testing to put it in the maintenance and close the issue

**Comment by julsemaan** [comment]
PR on the driver repo : https://github.com/rentrak/chi-driver-redis/pull/7

**Comment by jrouzierinverse** [comment]
This has been fixed
