### ISSUE TITLE
Strip whitespace from email input

### ISSUE THREAD

**Issue by jglamine** [inverse-inc/packetfence#1235]
When registering with an email address, strip leading and trailing white-space from the input. This is helpful for mobile users with keyboards which add a space to the end of words (such as swiftkey).

Expected behavior:
Enter "example@gmail.com ". The form submits successfully.

Actual behavior:
Enter "example@gmail.com ". The form shows a validation error about invalid email address.

**Comment by julsemaan** [comment]
Please let us know which version you are using.

Adjustments have been made to the input fields so they behave better with mobile devices.

**Comment by jglamine** [comment]
Thanks for the quick response. I'm using 5.6.1.

**Comment by julsemaan** [comment]
The template has been reworked in 5.7

Here it is if you want to add it manually : 
https://github.com/inverse-inc/packetfence/blob/devel/html/captive-portal/templates/guest.html

**Comment by julsemaan** [comment]
No answer. Assuming my solution worked...
