### ISSUE TITLE
Cannot bind to LDAP after ~15 minutes of inactivity

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1248]
After approximatly 15 minutes, the CHI cache object is not able to bind but is still considered valid leading to all LDAP failing : 

```
Mar 17 14:32:15 httpd.aaa(8891) ERROR: [mac:94:0f:0f:68:3d:77] [inverse] Unable to bind with cn=zaymitte,cn=users,dc=zammit,dc=corp on 1.2.3.4:389 (pf::Authentication::Source::LDAPSource::preMatchProcessing)
```

**Comment by jrouzierinverse** [comment]
Fixes was fixed by 0586b44c2fe5eea726ca5575ff09a3219d2aa9f0 and 937d2c9519c330e23713b05f1cad35400c118a28
