### ISSUE TITLE
PacketFence services dont start all

### ISSUE THREAD

**Issue by ngongue** [inverse-inc/packetfence#1249]
Hi please I have an issue with my packetfence setup on CentOS 6 for Packetfence 5.7. When I run the command 
# service packetfence restart

I get this output

**Syntax error on line 146 of /usr/local/pf/conf/httpd.conf.d/httpd.portal:
$parms->add_config() has failed: ServerAdmin takes one argument, The email address of the server administrator at /usr/lib64/perl5/vendor_perl/Apache2/PerlSections.pm line 215.\n**
httpd.portal|not started
dhcpd|start
**Syntax error on line 88 of /usr/local/pf/conf/httpd.conf.d/httpd.webservices:
$parms->add_config() has failed: ServerAdmin takes one argument, The email address of the server administrator at /usr/lib64/perl5/vendor_perl/Apache2/PerlSections.pm line 215.\n**
httpd.webservices|not started
pfmon|start
p0f|start
Starting carbon-cache (instance a)
carbon-cache|start
Starting carbon-relay (instance a)
carbon-relay|start
collectd|start
statsd|start
radsniff3|start
Syntax error on line 73 of /usr/local/pf/conf/httpd.conf.d/httpd.graphite:
**$parms->add_config() has failed: ServerAdmin takes one argument, The email address of the server administrator at /usr/lib64/perl5/vendor_perl/Apache2/PerlSections.pm line 215.\n**

Plz for solve this issue

**Comment by louismunro** [comment]
That looks like a configuration issue, not a bug.
Use the mailing for help with that.
