### ISSUE TITLE
Tree view in portal module does not display properly

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1257]
When viewing the tree view of the Portal Modules It become mixed up with list view.

How to replicate (On chrome for Mac OSX)
- Click on Portal Modules
- Click on Tree View

![image](https://cloud.githubusercontent.com/assets/2727473/13929835/846d88be-ef72-11e5-9295-078b0161279e.png)

![image](https://cloud.githubusercontent.com/assets/2727473/13929819/71fe8fde-ef72-11e5-9e95-43f10aad2afe.png)

**Comment by julsemaan** [comment]
I'll need the output of the javascript console as I can't replicate on Chrome on Ubuntu 

Most likely a bootstrap error

**Comment by jrouzierinverse** [comment]
This is not happening anymore
