### ISSUE TITLE
Removing an element in chzn-select doesn't always put it back in the available choice

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1263]
In the SMS authentication source, we have all the selected carriers when the page loads that are in the selected part of chzn-select along with the unselected ones that can be displayed when we click on it.

If I was to add a carrier from the unselected list and remove it after, it will be put back into the available unselected carriers.

If I was to remove a carrier from the ones that were already selected and displayed on the page load, it doesn't go in the unselected carriers that are available

**Comment by jrouzierinverse** [comment]
Maybe we should upgrade chosen.js

**Comment by dwlfrth** [comment]
@jrouzierinverse get in touch with @julsemaan to see what is the issue
