### ISSUE TITLE
Relevance of pfcmd-old.pl

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1272]
I think now should be the time to drop it.

What do you guys think ?

**Comment by jrouzierinverse** [comment]
Kill it with fire!

**Comment by louismunro** [comment]
Nuke it from orbit.

It’s the only way to be safe...

**Comment by julsemaan** [comment]
fixed via 636ee2f1e6d57ec5820164b70d2e72c493ce639f
