### ISSUE TITLE
[CentOS 7]access duration in billing tiers is not clickable

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1277]
You need to tab to be able to type in the case 'Access Duration' tested on Chrome/Firefox(Ubuntu)

**Comment by julsemaan** [comment]
Not able to replicate on Chrome/Firefox on Ubuntu

**Comment by julsemaan** [comment]
Bump !

**Comment by whitx** [comment]
It is still happening for me on both browser,  everything is clickable expect this case.

**Comment by julsemaan** [comment]
on CentOS 7 ?

**Comment by jrouzierinverse** [comment]
This is because of version of HTML::FormHandler that is used.
We should move the same version we have for centos 6.
Which is perl-HTML-FormHandler-0.40013

**Comment by fdurand** [comment]
Fixed
