### ISSUE TITLE
RADIUS audit log RADIUS trace is not displayed properly

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1281]
![image](https://cloud.githubusercontent.com/assets/3857942/14147724/a7b9a588-f66a-11e5-948d-748f811f7c0a.png)

Latest devel ca28b61cf2e259236c21e708d8e6cc2b947bca80
On Chrome on Linux
Using CentOS 6.6

**Comment by jrouzierinverse** [comment]
The format of the request changed from freeradius 2 to 3.
Would need to cleanup the data before we display it.

**Comment by jrouzierinverse** [comment]
Can you send me a dump of your radius_audit_log?

**Comment by extrafu** [comment]
@jrouzierinverse From your typical UPS deliveries, it seems like you're used at handling dumps ;-)

**Comment by jrouzierinverse** [comment]
@extrafu I can send you a dump also if you want.

**Comment by extrafu** [comment]
Make sure you gzip it first.

**Comment by julsemaan** [comment]
Dump sent to @jamaisse
