### ISSUE TITLE
WLC Web auth documentation in Network Devices guide has to be updated

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1283]
With the change on the portalUrl, all the documentation related to web auth has been outdated

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc#web-auth

**Comment by julsemaan** [comment]
my bad, I looked at the WLC and it wasn't updated, so I assumed everything wasn't :)

Let's change the title
