### ISSUE TITLE
A runtime error in the dispatcher is not catched by pf::log

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1284]
Example : 
The following line in dispatcher.pm : 

```
foreach my $key (keys %{$req->param}) {
```

If $req->param returns undef, this creates an error of casting undef to a hash but that error is never displayed in httpd.portal.error nor packetfence.log

**Comment by jrouzierinverse** [comment]
The issue seems to be in lib/pf/web/externalportal.pm not the dispatcher

**Comment by julsemaan** [comment]
The code that makes it break is in externalportal.pm but its running inside the dispatcher modperl execution.

IMO, we would put that code in dispatcher.pm and it would break too.

**Comment by jrouzierinverse** [comment]
I agree it would most likely break in either case.
I put that as a note to myself so when I pick back up this issue I will remember where in the code and not look in the wrong place again

**Comment by jrouzierinverse** [comment]
I can replicated the error not being placed into log/packetfence.log but I do see the error in httpd.portal.error.

**Comment by jrouzierinverse** [comment]
Is it good enough if the error is in httpd.portal.error?

**Comment by julsemaan** [comment]
In my case it was in neither of them.

Can you give me the test you made so I try it on my install and see if it outputs

**Comment by julsemaan** [comment]
Tried your patch and it doesn't throw the error.

But I sent you another patch via e-mail that replicates the exact behavior I am seeing

**Comment by jrouzierinverse** [comment]
After digging deeper I found at what point in our code things go wrong.

In pf::Portal::Session after we instantiate the CGI::Session object.
Any dies afterwards do not get logged and apache always return a 200.

Since now I am venturing into other people's code I would prefer to stop and tackle a more important bug then try and fix this one.

**Comment by dwlfrth** [comment]
Replace cgi session by PacketFence something sessionish

**Comment by dwlfrth** [comment]
Bye now
