### ISSUE TITLE
802.1x PEAP local account documentation is outdated

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1286]
The documentation for the EAP local account is outdated in the admin guide since it now goes through a redis flag

Must be fixed for v6

**Comment by louismunro** [comment]
Removed the redis flag.
Will update documentation to reflect the new policy.

**Comment by julsemaan** [comment]
This hasn't been addressed.

Documentation for local accounts is still outdated

**Comment by louismunro** [comment]
Not sure what you are talking about.
It looks up to date to me.
