### ISSUE TITLE
Logging in with an invalid username says wrong message

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1287]
Logging in with a username that doesn't exist in any source displays `Unable to validate credentials for the moment`

**Comment by julsemaan** [comment]
Additionnal details, this was when the SQL source was the only one available for Internal login

**Comment by jrouzierinverse** [comment]
Can you please provide your conf/authentication.conf since I cannot replicate it

**Comment by jrouzierinverse** [comment]
Can you also provides the log files of this happening.
