### ISSUE TITLE
configurator: starting services after configuration is failing

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1291]
`Mar 31 13:38:46 pfcmd.pl(2736) INFO: Instantiate profile default (pf::Portal::ProfileFactory::_from_profile)
Mar 31 13:38:55 pfcmd.pl(2736) FATAL: Eval went very, very wrong:

{
  my $isa_check_for_cachedConfig = ${$_[1]->{"\$isa_check_for_cachedConfig"}};
  my $default_for_pfconfigNamespace = ${$_[1]->{"\$default_for_pfconfigNamespace"}};
  my $_QUOTED = ${$_[1]->{"\$_QUOTED"}};
  no warnings 'closure';
  sub pf::ConfigStore::new {
package Method::Generate::Constructor;
BEGIN {
  $^H = "1794";
  ${^WARNING_BITS} = "\377\377\377\377\377\377\377\377\377\377\377\377\377";
  %^H = (
  );
}
    my $class = shift;
    $class = ref($class) if ref($class);
    if ($class ne "pf::ConfigStore") {
      if ($Moo::MAKERS{$class}) {
        Moo->_constructor_maker_for($class,"pf::ConfigStore");
        return $class->new(@_);
      } elsif ($INC{"Moose.pm"} and my $meta = Class::MOP::get_metaclass_by_name($class)) {
        return $meta->new_object($class->BUILDARGS(@_));
      }
    }
    my $args;
    if ( scalar @_ == 1 ) {
        unless ( defined $_[0] && ref $_[0] eq 'HASH' ) {
            die "Single parameters to new() must be a HASH ref"
                ." data => ". $_[0] ."\n";
        }
        $args = { %{ $_[0] } };
    }
    elsif ( @_ % 2 ) {
        die "The new() method for $class expects a hash reference or a key/value list."
                . " You passed an odd number of arguments\n";
    }
    else {
        $args = {@_};
    }
    my $new = bless({}, $class);;
    if (exists $args->{"cachedConfig"}) {
      do {
  local $Method::Generate::Accessor::CurrentAttribute = {    init_arg => "cachedConfig",
    name     => "cachedConfig",
    step     => "isa check",
  };
  local $Method::Generate::Accessor::OrigSigDie = $SIG{__DIE__};
  local $SIG{**DIE**} = &Method::Generate::Accessor::_SIGDIE;
$isa_check_for_cachedConfig->($args->{"cachedConfig"})}
;
      $new->{"cachedConfig"} = $args->{"cachedConfig"};
    }
    if (exists $args->{"configFile"}) {
      $new->{"configFile"} = $args->{"configFile"};
    }
    if (exists $args->{"default_section"}) {
      $new->{"default_section"} = $args->{"default_section"};
    }
    $new->{"pfconfigNamespace"} = (
      exists $args->{"pfconfigNamespace"}
       ? $args->{"pfconfigNamespace"}
       : $default_for_pfconfigNamespace->($new)
    );
    return $new;
  }
  $_QUOTED->[3] = &pf::ConfigStore::new
}
1;

Insecure dependency in require while running setgid at (eval 3732) line 5.
BEGIN failed--compilation aborted at (eval 3732) line 5.
 (Sub::Quote::unquote_sub)`

**Comment by dwlfrth** [comment]
[root@pancakeFence2 ~]# rpm -qa packetfence
packetfence-6.0.0-0.20160331.el6.noarch

**Comment by jrouzierinverse** [comment]
can you provide the output of the following commands.
ls -la /usr/local/pf/bin/pfcmd

**Comment by jrouzierinverse** [comment]
Is this on centos 6 or 7

**Comment by dwlfrth** [comment]
[root@pancakeFence2 pf]# ls -la /usr/local/pf/bin/pfcmd
-rwsr-sr-x 1 root root 6376 Mar 31 00:11 /usr/local/pf/bin/pfcmd

**Comment by dwlfrth** [comment]
CentOS6

**Comment by jrouzierinverse** [comment]
I understand what is happening now.
Since we are running in setgid/setuid mode the sticky bit is set on the pfcmd binary.
Perl automatically turns on tainting.

So the problem we had earlier with tainting we have to deal with it.

**Comment by julsemaan** [comment]
Mr W can you try again with e2bf4a5c62d3dee2c12881d6bd05684fff0c145e

That should be fixed. Will also try it

**Comment by jrouzierinverse** [comment]
Found the real issue causing the tainting problem fixed in 4a2dad355323859fb7d72f1723257ba220df2aeb.
