### ISSUE TITLE
FreeRADIUS jams on dynamic clients on every requests

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1296]
Using latest devel f81f495c3f10f291c541171c69f69b496986699f

FreeRADIUS debug output :
http://pastebin.com/YFFfZzeH

FreeRADIUS is completely unusable right now. Needs a fix ASAP...

**Comment by louismunro** [comment]
Seems related to the contents of the Calling-Station-Id.
Can you run radsniff with -x and post the contents of the attributes?

**Comment by dwlfrth** [comment]
Facing this issue too.
radius is spinning at 100% without doing anything

**Comment by dwlfrth** [comment]
Seems to occur when a request is coming from an unknown network equipment.

**Comment by louismunro** [comment]
Should now be fixed with e57af774e7530cb73b2489b4f0d6c9cf22a50372
Please test and confirm.

**Comment by dwlfrth** [comment]
Seems to be fixed

**Comment by julsemaan** [comment]
Reoccured this morning in my test environment.

Takes 100% of the CPU and raddebug doesn't output anything

**Comment by louismunro** [comment]
I don't believe you.

**Comment by dwlfrth** [comment]
Doesn't seems to be the same behavior if it is still occuring...

**Comment by julsemaan** [comment]
Not able to replicate it anymore
