### ISSUE TITLE
Falling back to MAB after a suplicant failure will unregister device

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1297]
Our previous behavior was to unreg only wireless user when they would fallback from 802.1x to MAB.

Now, we unreg wired dot1x users as well.

This means that a supplicant failure (unfortunatly common on Mac OSX) will unregister the device and make it lose connectivity access.

Our previous behavior was to keep its access (again only for wired) until the device hit its unreg date since it is safe to assume the machine will get rebooted at some point and the supplicant be back online (Zammit law)

I think we should go back to that behavior as it will lead to unexpected connectivity loss for wired users.

We can add the wired MAB fallback unreg filter in the examples but I don't think we should ship it by default.

This is the line that is causing the issue : 
https://github.com/inverse-inc/packetfence/blob/devel/conf/vlan_filters.conf.defaults#L35

**Comment by fdurand** [comment]
I am agree to revert back to the previous flow

**Comment by julsemaan** [comment]
fixed via 1a5505e6f59fb445e9da0766946de98e493f0d1c
