### ISSUE TITLE
RAM usage is concerning

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1301]
With the latest internal reports from @fdurand I think we should spend time profiling our RAM usage before releasing v6.

There may _\- read is -_ be place for optimization

**Comment by julsemaan** [comment]
Found one of the problems
#1303

**Comment by julsemaan** [comment]
Another one
#1304

**Comment by jrouzierinverse** [comment]
Another #1308

**Comment by julsemaan** [comment]
I thought @jrouzierinverse was the one in charge of digging the memory issue :P

**Comment by jrouzierinverse** [comment]
Yes I am at the moment most of the things I found does not reduce memory by a lot and requires a lot of time to fix.
I am focusing my time to fix bugs at the moment.
I do have an approach that may be able to quickly reduce memory by some and it does not require a lot of effort on my part but I would need prefer to fix bugs at the moment.

**Comment by jrouzierinverse** [comment]
Some good news on this front I was able to reduce the portal httpd process by at least 20 megabytes.
I wrote a script to help migrate all auto exported functions to export_ok.
However it would need be tested thoroughly to ensure that everything was done correctly.

Since it is one of those huge commits we should push this to 6.1 to avoid delaying the 6.0 release.

**Comment by jrouzierinverse** [comment]
For those who are interested the script is here.

https://github.com/inverse-inc/packetfence/blob/feature/no_export/addons/dev-helpers/no_export.sh

**Comment by tribut** [comment]
On 6.0.1 (Debian jessie) when I click `Update Fingerbank DB` in `Fingerbank Settings` two of the webservices httpd processes start hogging memory after a few seconds (4GB and 1G resp.). Do you need help reproducing this or is this a known issue?
Possibly related to #1303.

**Comment by julsemaan** [comment]
@tribut 
Due to the enormous size of the Fingerbank database, updating it uses a pretty good amount of RAM.
But, this should last for ~1-2 minutes and be released afterwards.
Also, pfqueue should be the one doing the update and not the webservices.

I've opened #1452 for this matter.
Can you post pfqueue.log and packetfence.log on this other issue. Will also try to replicate tomorrow.

**Comment by julsemaan** [comment]
That's a never ending fight but we're back to an acceptable usage

Closing
