### ISSUE TITLE
if there is a ipv6 dns in resolv.conf then pfconfig will not start (centos 7)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1302]

**Comment by julsemaan** [comment]
Who uses IPv6 anyway.

Thats like witchcraft

**Comment by julsemaan** [comment]
Not able to replicate on CentOS 6 and no access to a good CentOS 7
Can you provide the logs and output of the start

**Comment by fdurand** [comment]
getpeername(14, 0x5b27a60, [256])       = -1 ENOTCONN (Transport endpoint is not connected)
sendto(14, "\335\30\1\0\0\1\0\0\0\0\0\0 fe80::26a4:3cff:feb"..., 50, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 50
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)
getpeername(11, 0x5b27b20, [256])       = -1 ENOTCONN (Transport endpoint is not connected)
sendto(11, "\335\30\1\0\0\1\0\0\0\0\0\0 fe80::26a4:3cff:feb"..., 50, 0, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 50
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)
getpeername(14, 0x5b27b50, [256])       = -1 ENOTCONN (Transport endpoint is not connected)
sendto(14, "\335\30\1\0\0\1\0\0\0\0\0\0 fe80::26a4:3cff:feb"..., 50, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 50
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)
select(16, [11 14], NULL, NULL, {5, 0}) = 0 (Timeout)

**Comment by fdurand** [comment]
I have to disable ipv6 to make it works

**Comment by julsemaan** [comment]
@fdurand do we take care of this in packaging to remove the interface in resolv.conf ipv6 or do we try to handle it in the code ?

**Comment by fdurand** [comment]
yes fixed in 65ac905170b5abf318c9cce6fff6072a8823df33 btw when we pass the configurator it set to no the NM_CONTROLLED.

**Comment by julsemaan** [comment]
but when you install the package will pfconfig be able to start ?
Otherwise the admin and pfcmd won't usable

**Comment by fdurand** [comment]
yes pfconfig start and httpd.admin too

**Comment by julsemaan** [comment]
![image](https://cloud.githubusercontent.com/assets/3857942/14300772/b4982428-fb60-11e5-99eb-930da5673389.png)
