### ISSUE TITLE
pfmon fingerbank update process takes *a lot* of RAM

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1303]
The process updates the fingerbank DB which is pretty large so uses a lot of RAM which is never released back to the OS (good old perl).

The update process should either be forked off pfmon, sent to the webservices or we should find a way to reduce the RAM usage of the updates (not sure how without putting our hands in LWP)

**Comment by jrouzierinverse** [comment]
There is a way to tell perl to return memory to the OS.
`undef $big_variable;`

**Comment by julsemaan** [comment]
Already fixed via an API call since it was necessary for the admin interface

Try it and it does work so I will do it anyway for good practices

**Comment by julsemaan** [comment]
fixed by d750777eb95d2d3e5686972ee20183855bb5f565
