### ISSUE TITLE
Squeezed portal menu on small netbook computer

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1307]
The menu appears squeezed in comparison to the screen size

Computer resolution : 1024x600

Screenshot : 
![image](https://cloud.githubusercontent.com/assets/3857942/14252531/cdfeb32a-fa55-11e5-988e-769ba660b035.png)

**Comment by julsemaan** [comment]
Using the meta viewport tag doesn't fix this

Can you look into it.

Thanks !

**Comment by cgx** [comment]
Does it fix the problem on mobiles?

**Comment by julsemaan** [comment]
It does fix it on mobile yes
