### ISSUE TITLE
[CentOS7] Cannot change lease time via admin interface

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1309]
ERROR: Caught exception in pfappserver::Controller::Config::Networks->update "Can't call method "fif" on an undefined value at /usr/share/perl5/vendor_perl/HTML/FormHandler/Validate.pm line 266." (pfappserver::PacketFence::Controller::Root::end)

**Comment by julsemaan** [comment]
don't forget to tag v6 and put the PacketFence-6 milestone

**Comment by fdurand** [comment]
All the forms like that are not clickable

![capture du 2016-04-06 13 27 47](https://cloud.githubusercontent.com/assets/1553962/14326338/83619fe2-fbfb-11e5-98c0-de67548a1b2f.png)

**Comment by jrouzierinverse** [comment]
This is because of version of HTML::FormHandler that is used.
We should move the same version we have for centos 6.
Which is perl-HTML-FormHandler-0.40013

**Comment by fdurand** [comment]
Fixed
