### ISSUE TITLE
ssl_mutex causing httpd.admin and httpd.portal to fail to start

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1312]
On CentOS6, fresh install, httpd.admin cannot start and complain about ssl_mutex already exists

[Mon Apr 04 13:55:04 2016] [error](17)File exists: Cannot create SSLMutex with file `/usr/local/pf/var/ssl_mutex'
Configuration Failed

Seems to be related to CentOS7 support.

**Comment by fdurand** [comment]
Fixed in 7df1ed3456ea39bc23650c47c7207e54335a5871
