### ISSUE TITLE
portal: "guest signup" is bringing to email registration rather than method choice

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1319]
When clicking 'guest signup' on the portal, it is bringing me directly to email authentication (skipping the choice for either SMS, email, sponsor)

**Comment by julsemaan** [comment]
dumb question : Do you have the other sources available in your portal profile ?

are you using the default portal modules or have you added customization ?

**Comment by dwlfrth** [comment]
No sources defined in profile.conf so using all authentication sources configured.
Using default module

Will show you tomorrow

**Comment by julsemaan** [comment]
fixed by d83ed1670de911d035d047f016ea2ca17593eee2
