### ISSUE TITLE
Email registration: Template not send translated

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1322]
I've a portal portal in french and the email sent for to activate the access is in English.

**Comment by jrouzierinverse** [comment]
This is a new feature not a bug.
We would need to consider how to incorporate this in PacketFence.

**Comment by marksokol82** [comment]
I see that it has been removed from 6.4 milestone. Has this enhancement been implemented in 6.3? This is an important feature, for with different language packages all is translated except for the email registration, and users cannot understand the email. Thanks!
