### ISSUE TITLE
Upgrade guide - missing changes related to update to FreeRADIUS 3

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1323]
All the config changed and without manually changing the files, the old ones will be kept making FreeRADIUS impossible to start.

Also, the certificate path has been changed. We need to add a note on that in the upgrade guide

**Comment by louismunro** [comment]
Sure. There is no question that we need to add a section on it.
I propose we recommend moving out or deleting all of the old raddb.

All those opposed, say "aye".

**Comment by julsemaan** [comment]
That and also the confs in /usr/local/pf/conf/radiusd
`find /usr/local/pf/conf/radiusd/ ! -name '*.example' -delete`

**Comment by louismunro** [comment]
We should not have to do that if the files were properly marked as config in the packaging.
Anyway, I'll test it and make the required changes/document.

**Comment by julsemaan** [comment]
Let's say I changed my server cert path for FreeRADIUS which is far from uncommon, the eap.conf will not be upgraded.

We don't lose anything documenting these and I'm sure it will prevent headaches for some

**Comment by louismunro** [comment]
Well, that argument is also true for any file marked as "confignoreplace".
Not saying I won't mention then in the documentation.
Just saying I am not sure there is any need to do anything more than mention that care should be taken to merge .rpmnew files.

**Comment by louismunro** [comment]
TODO.

**Comment by julsemaan** [comment]
That is done
