### ISSUE TITLE
Error on every accounting packet

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1325]
Tue Apr  5 13:33:32 2016 : Error: rlm_perl: An error occurred while processing the accounting RPC request: Can't use string ("2") as an ARRAY ref while "strict refs" in use at /usr/local/pf/raddb//mods-config/perl/packetfence.pm line 351.

**Comment by louismunro** [comment]
Can't seem to reproduce it right now.
Damn thing refuses to fail.
Let me know when you have it happening again and I'll come over to your house...

**Comment by whitx** [comment]
Can confirm same issue [CentOS7]

**Comment by julsemaan** [comment]
Note to self, I have a fix, just forgot to put it in devel
