### ISSUE TITLE
End of configurator failled (Unknow for each services but all started) - Centos 7

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1327]
![capture du 2016-04-05 15 05 58](https://cloud.githubusercontent.com/assets/1553962/14294632/0754e730-fb40-11e5-83c7-3b71151093d1.png)

**Comment by fdurand** [comment]
![capture du 2016-04-13 17 11 31](https://cloud.githubusercontent.com/assets/1553962/14509556/decd3388-019a-11e6-8962-8fd3119b9899.png)

**Comment by fdurand** [comment]
Now it just do nothing

**Comment by louismunro** [comment]
Confirmed. The configurator just seems to ignore the "start services" button.

**Comment by jrouzierinverse** [comment]
I am on it

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by fdurand** [comment]
Restart over and over and over ....

![capture du 2016-04-19 10 11 59](https://cloud.githubusercontent.com/assets/1553962/14642139/4e7ccfa6-0617-11e6-8eb3-2bcfc595b781.png)

**Comment by louismunro** [comment]
Fixed in 6.0.
