### ISSUE TITLE
Sponsor registration 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1328]
When I validate the activation it doesn't work:

does not have permission to sponsor a user

Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] database query failed with: Duplicate entry '0' for key 'PRIMARY' (errno: 1062) (pf::db::db_query_execute)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] violation not added, MAC 0 is invalid! trigger useragent::401 (pf::violation::violation_trigger)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] violation not added, MAC 0 is invalid! trigger useragent::600 (pf::violation::violation_trigger)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] violation not added, MAC 0 is invalid! trigger useragent::5 (pf::violation::violation_trigger)
Apr 05 16:03:37 httpd.webservices(5685) INFO: [mac:unknown] violation not added, MAC 0 is invalid! trigger internal::new_dhcp_info (pf::violation::violation_trigger)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] [94:db:c9:38:8f:0b] Activation code sent to email email2@inverse.ca from email1@gmail.com successfully verified.  for activation type: sponsor (pf::activation::validate_code)
Apr 05 16:03:37 httpd.portal(5672) ERROR: [mac:0] unable to read password file '/usr/local/pf/conf/admin.conf' (pf::Authentication::Source::HtpasswdSource::authenticate)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] [Inverse-AD] Authentication successful for lzammit (pf::Authentication::Source::LDAPSource::authenticate)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] Authentication successful for 'lzammit' in source Inverse-AD (AD) (pf::authentication::authenticate)
Apr 05 16:03:37 httpd.portal(5672) INFO: [mac:0] Successfully authenticated lzammit/172.20.20.247/0 (captiveportal::PacketFence::Controller::Authenticate::authenticationLogin)

**Comment by julsemaan** [comment]
It doesn't say that it matches a rule.

Do you have an 'administration' rules that marks the user as sponsor ?

**Comment by lzammit** [comment]
Yes:

Authenticating against Inverse-AD
  Authentication FAILED against Inverse-AD (Invalid login or password)
  Matched against Inverse-AD for 'authentication' rules
    set_access_duration : 1h
    set_role : default
  Matched against Inverse-AD for 'administration' rules
    mark_as_sponsor : 1

**Comment by julsemaan** [comment]
fixed via 17640f1de4535b24ae1aa79b1345f0fd859421d0
