### ISSUE TITLE
Portal profile filter issue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1338]
Set a ssid filter to baguettefence , save the portal, edit the portal then ssid will be HASH(0x7ff48995b280)

**Comment by jrouzierinverse** [comment]
Centos 6 or Centos 7

**Comment by fdurand** [comment]
Centos 7

**Comment by jrouzierinverse** [comment]
This is because of version of HTML::FormHandler that is used.
We should move the same version we have for centos 6.
Which is perl-HTML-FormHandler-0.40013

**Comment by fdurand** [comment]
Fixed
