### ISSUE TITLE
radius audit log: returning REJECT role (-1) add an "Accept" (GREEN) entry

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1340]
It should add a DENY (red) entry

**Comment by jrouzierinverse** [comment]
Can you put the radius log entry that should have been a reject.

**Comment by dwlfrth** [comment]
http://pastebin.com/4qsFCW7w

**Comment by jrouzierinverse** [comment]
Can you please also paste the database entry.

**Comment by jrouzierinverse** [comment]
Can you make sure you have the most up to date https://github.com/inverse-inc/packetfence/blob/devel/conf/radiusd/packetfence.example being applied in your configuration.

**Comment by dwlfrth** [comment]
Was testing with the daily package installed 5 minutes earlier, so I guess I had it.

**Comment by jrouzierinverse** [comment]
Are they the same?
diff conf/radiusd/packetfence-tunnel conf/radiusd/packetfence-tunnel.example
diff  conf/radiusd/packetfence conf/radiusd/packetfence.example

**Comment by jrouzierinverse** [comment]
Since I do not know is your setup was an upgrade or a clean install I just want to make sure.

**Comment by jrouzierinverse** [comment]
Fixed by 301b70112b71e816855ea69b0afe98de45fb6f78 and 6e5ff3435ac93459e87117aafee2bec4633eccda
