### ISSUE TITLE
Chckconfig error on el7

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1341]
While using chkconfig --list on el7 the following error message appear

Note: This output shows SysV services only and does not include native
     systemd services. SysV configuration data might be overridden by native
     systemd configuration.

```
 If you want to list systemd services use 'systemctl list-unit-files'.
 To see services enabled on particular target use
 'systemctl list-dependencies [target]'.
```

**Comment by julsemaan** [comment]
fixed via #1342
