### ISSUE TITLE
Searching by 'Source Switch IP' starts with x.y.z returns duplicate entries

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1345]
Using 5.5.2 - could not replicate on 6.0-devel since that search is broken (see #1344)

Searching for 'Source Switch IP' starts with '172.208.154' will return multiple results per MAC address while searching for 'Source Switch IP' equals '172.208.154.116' will return one row per MAC.

Only one locationlog and iplog are open for the nodes that appear as duplicate.

DB dump available on demand.

**Comment by jrouzierinverse** [comment]
Dump please

**Comment by julsemaan** [comment]
Dump sent

**Comment by julsemaan** [comment]
Update on that one ?

**Comment by jrouzierinverse** [comment]
Fixed in 6753920d3155b45c9dfcf6db281c56d641f2d2e7 1021362f5121be5a682a3b79d585d23c5a9a75ab
