### ISSUE TITLE
"I don't have a PIN" SMS option on pre-reg isn't working

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1353]
When on a pre-reg portal profile, clicking the "I don't have a PIN" option leave us on the same page.

**Comment by julsemaan** [comment]
does it work on normal reg ?

**Comment by dwlfrth** [comment]
It is

**Comment by dwlfrth** [comment]
Let's debug all together shall we

Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] hitting handler with URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) (pf::web::dispatcher::handler)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] instantiating new pf::web::filter (pf::web::filter::new)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) is properly handled and should now continue to the captive-portal / Catalyst (pf::web::dispatcher::handler)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] hitting handler with URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) (pf::web::dispatcher::handler)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] instantiating new pf::web::filter (pf::web::filter::new)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:[undef]] URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) is properly handled and should now continue to the captive-portal / Catalyst (pf::web::dispatcher::handler)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] instantiating new pf::Portal::Session object (pf::Portal::Session::new)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] using session id 'CGI=HASH(0x7f1a51312240)' (pf::Portal::Session::_initialize)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Remote Address is 172.20.20.113 but no further hints of client IP in HTTP Headers (pf::Portal::Session::_resolveIp)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using OMAPI (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='Default', key='HASH(0x7f1a496b5478)', cache='RawMemory', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache set for namespace='Default', key='{"encoding":null,"reconnect":"60","server":"127.0.0.1:6379"}', size=1, expires='never', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='omapi', key='172.20.20.113', cache='Redis', time='4ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using SQL 'iplog' table (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Viewing an 'iplog' table entry for the following IP address '172.20.20.113' (pf::iplog::_view_by_ip)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Database statements not prepared, preparing... (pf::db::db_query_execute)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Preparing pf::iplog database queries (pf::iplog::iplog_db_prepare)
Apr 11 16:00:00 httpd.portal(3909) WARN: [mac:unknown] Unable to match MAC address to IP '172.20.20.113' (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Database statements not prepared, preparing... (pf::db::db_query_execute)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Preparing pf::node database queries (pf::node::node_db_prepare)
Apr 11 16:00:00 httpd.portal(3909) INFO: [mac:unknown] Instantiate profile default (pf::Portal::ProfileFactory::_from_profile)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] instantiating new pf::Portal::Profile object (pf::Portal::Profile::new)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Authorized locale(s) are en_US (pf::Portal::Session::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] locale from the browser is en_US (pf::Portal::Session::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Setting locale to en_US (pf::Portal::Session::_initializeI18n)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _client_ip : 172.20.20.113 (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:00 httpd.portal(3909) WARN: [mac:unknown] Use of uninitialized value $value in concatenation (.) or string at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Model/Portal/Session.pm line 243.
 (captiveportal::PacketFence::Model::Portal::Session::__ANON__)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _grant_url :  (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _destination_url : http://www.packetfence.org/ (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _client_mac : 0 (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _profile : pf::Portal::Profile=HASH(0x7f1a4f44cd68) (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='Default', key='HASH(0x7f1a5138e2c0)', cache='RawMemory', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache set for namespace='Default', key='{"DataColName":"a_session","IdColName":"id","TableName":"sessions","encoding":null,"reconnect":"60","server":"127.0.0.1:6379"}', size=1, expires='never', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache set for namespace='httpd.portal', key='03a4e99b4c353187df67e1a0e73a19c5', size=1228, expires='6h', cache='Redis', time='1ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Remote Address is 172.20.20.113 but no further hints of client IP in HTTP Headers (captiveportal::PacketFence::Model::Portal::Session::_build_clientIp)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using OMAPI (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='omapi', key='172.20.20.113', cache='Redis', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using SQL 'iplog' table (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:unknown] Viewing an 'iplog' table entry for the following IP address '172.20.20.113' (pf::iplog::_view_by_ip)
Apr 11 16:00:00 httpd.portal(3909) WARN: [mac:unknown] Unable to match MAC address to IP '172.20.20.113' (pf::iplog::ip2mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] invalid MAC: empty (pf::util::valid_mac)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='Default', key='HASH(0x7f1a5141ecc8)', cache='RawMemory', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='httpd.portal', key='session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] Authorized locale(s) are de_DE, en_US, es_ES, fr_FR, fr_CA, he_IL, it_IT, nl_NL, pl_PL, pt_BR (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] locale from the browser is en_US (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] locale from the browser en is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] Language locale from the browser en_US is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] Language locale from the browser en is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] prefered user languages are en_US (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] Setting locale to en_US (captiveportal::PacketFence::Controller::Root::setupLanguage)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='Default', key='HASH(0x7f1a5140f7f8)', cache='RawMemory', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='httpd.portal', key='user_session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:00 httpd.portal(3909) WARN: [mac:0] Use of uninitialized value in string eq at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 69.
 (captiveportal::PacketFence::Controller::Root::setupDynamicRouting)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_billing_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_login_policy is using sources : local,file1 (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_oauth_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources :  (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_guest_policy is using sources : email,sms,sponsor,null (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources : email,sms,sponsor,null (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_saml_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources :  (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Destination is : http://www.packetfence.org/ (captiveportal::PacketFence::DynamicRouting::Application::process_destination_url)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='Default', key='HASH(0x7f1a51447f38)', cache='RawMemory', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache set for namespace='Default', key='{"server":"127.0.0.1:6380"}', size=1, expires='never', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /status/billing (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /billing.\* (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /logout (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /access (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] invalid MAC: empty (pf::util::valid_mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Database statements not prepared, preparing... (pf::db::db_query_execute)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Preparing pf::violation database queries (pf::violation::violation_db_prepare)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy+default_guest_policy (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy+default_guest_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache set for namespace='httpd.portal', key='user_session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', size=30, expires='6h', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache set for namespace='httpd.portal', key='expires:90ffcd0a8ed590c8266957173e4f0c1d4377843a', size=24, expires='6h', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] hitting handler with URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) (pf::web::dispatcher::handler)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] instantiating new pf::web::filter (pf::web::filter::new)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) is properly handled and should now continue to the captive-portal / Catalyst (pf::web::dispatcher::handler)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] hitting handler with URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) (pf::web::dispatcher::handler)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] instantiating new pf::web::filter (pf::web::filter::new)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] URI '/captive-portal' (URL: https://172.21.110.2/captive-portal) is properly handled and should now continue to the captive-portal / Catalyst (pf::web::dispatcher::handler)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] instantiating new pf::Portal::Session object (pf::Portal::Session::new)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] using session id 'CGI=HASH(0x7f1a53207718)' (pf::Portal::Session::_initialize)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Remote Address is 172.20.20.113 but no further hints of client IP in HTTP Headers (pf::Portal::Session::_resolveIp)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using OMAPI (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='omapi', key='172.20.20.113', cache='Redis', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using SQL 'iplog' table (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Viewing an 'iplog' table entry for the following IP address '172.20.20.113' (pf::iplog::_view_by_ip)
Apr 11 16:00:02 httpd.portal(3909) WARN: [mac:unknown] Unable to match MAC address to IP '172.20.20.113' (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) INFO: [mac:unknown] Instantiate profile default (pf::Portal::ProfileFactory::_from_profile)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] instantiating new pf::Portal::Profile object (pf::Portal::Profile::new)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Authorized locale(s) are en_US (pf::Portal::Session::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] locale from the browser is en_US (pf::Portal::Session::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Setting locale to en_US (pf::Portal::Session::_initializeI18n)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _client_ip : 172.20.20.113 (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:02 httpd.portal(3909) WARN: [mac:unknown] Use of uninitialized value $value in concatenation (.) or string at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Model/Portal/Session.pm line 243.
 (captiveportal::PacketFence::Model::Portal::Session::__ANON__)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _grant_url :  (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _destination_url : http://www.packetfence.org/ (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _client_mac : 0 (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Adding session parameter from dispatcher session to Catalyst session : _profile : pf::Portal::Profile=HASH(0x7f1a513f3588) (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='Default', key='HASH(0x7f1a531cdb10)', cache='RawMemory', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] cache set for namespace='httpd.portal', key='57325ce37ffad97199a68b2e42e2ea80', size=1228, expires='6h', cache='Redis', time='38ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Remote Address is 172.20.20.113 but no further hints of client IP in HTTP Headers (captiveportal::PacketFence::Model::Portal::Session::_build_clientIp)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using OMAPI (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] cache get for namespace='omapi', key='172.20.20.113', cache='Redis', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Trying to match MAC address to IP '172.20.20.113' using SQL 'iplog' table (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:unknown] Viewing an 'iplog' table entry for the following IP address '172.20.20.113' (pf::iplog::_view_by_ip)
Apr 11 16:00:02 httpd.portal(3909) WARN: [mac:unknown] Unable to match MAC address to IP '172.20.20.113' (pf::iplog::ip2mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] invalid MAC: empty (pf::util::valid_mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='httpd.portal', key='session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Authorized locale(s) are de_DE, en_US, es_ES, fr_FR, fr_CA, he_IL, it_IT, nl_NL, pl_PL, pt_BR (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] locale from the browser is en_US (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] locale from the browser en is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Language locale from the browser en_US is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Language locale from the browser en is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] prefered user languages are en_US (captiveportal::PacketFence::Controller::Root::getLanguages)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting locale to en_US (captiveportal::PacketFence::Controller::Root::setupLanguage)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='httpd.portal', key='user_session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) WARN: [mac:0] Use of uninitialized value in string eq at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 69.
 (captiveportal::PacketFence::Controller::Root::setupDynamicRouting)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_billing_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_login_policy is using sources : local,file1 (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_oauth_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources :  (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_guest_policy is using sources : email,sms,sponsor,null (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources : email,sms,sponsor,null (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Module default_policy+default_registration_policy+default_saml_policy is using sources :  (captiveportal::Role::MultiSource::_build_sources)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Building Authentication Choice module using sources :  (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Choice::BUILD)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Destination is : http://www.packetfence.org/ (captiveportal::PacketFence::DynamicRouting::Application::process_destination_url)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache get for namespace='Default', key='HASH(0x7f1a53213af8)', cache='RawMemory', time='0ms': HIT (CHI::Driver::_log_get_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /status/billing (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /billing.\* (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /logout (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Checking if /captive-portal matches /access (captiveportal::Role::Routed::path_method)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] invalid MAC: empty (pf::util::valid_mac)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy+default_guest_policy (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy+default_guest_policy (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Executing current module from session default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::ModuleManager::execute_child)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Setting current module id : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::current_module_id)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Database statements not prepared, preparing... (pf::db::db_query_execute)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Preparing pf::activation database queries (pf::activation::activation_db_prepare)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Previous : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_, Current module : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::_render)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Previous : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_, Current module : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::_render)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Rendering content-with-choice.html (captiveportal::PacketFence::DynamicRouting::Application::render)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Previous : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_, Current module : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::_render)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] Previous : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_, Current module : default_policy+default_registration_policy+default_guest_policy+_DYNAMIC_MODULE_sms_ (captiveportal::PacketFence::DynamicRouting::Application::_render)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache set for namespace='httpd.portal', key='user_session:90ffcd0a8ed590c8266957173e4f0c1d4377843a', size=30, expires='6h', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
Apr 11 16:00:02 httpd.portal(3909) DEBUG: [mac:0] cache set for namespace='httpd.portal', key='expires:90ffcd0a8ed590c8266957173e4f0c1d4377843a', size=24, expires='6h', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
