### ISSUE TITLE
SMS: Captive-portal exception in Provisioning.pm line 61

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1354]
Got the following error after validating an SMS code.

Caught exception in captiveportal::Controller::Root->dynamic_application "Can't call method "id" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Provisioning.pm line 61."

**Comment by julsemaan** [comment]
already fixed in db7c274b0bc5bd266e101f5063a3c03e0a1ea43b
