### ISSUE TITLE
Radius Audit Log: Profile is not logged

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1355]
Apr 11 15:59:50 httpd.portal(13296) INFO: [mac:unknown] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)
Apr 11 15:59:50 httpd.portal(13296) INFO: [mac:4c:7c:5f:81:8d:23] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)
Apr 11 15:59:50 httpd.portal(13296) INFO: [mac:4c:7c:5f:81:8d:23] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)

<img width="829" alt="capture d ecran 2016-04-11 a 16 02 49" src="https://cloud.githubusercontent.com/assets/5261214/14440653/e525f096-fffe-11e5-9ccf-52d9a2680d91.png">

**Comment by jrouzierinverse** [comment]
Louis Just fixed this in devel

**Comment by lzammit** [comment]
Still present in the latest build.

No Profile and no Reason. Tested with returning VLAN -1.

**Comment by louismunro** [comment]
I am @louismunro and I approved this message.

**Comment by lzammit** [comment]
It's the same issue for an succeed or failed authentication.

**Comment by dwlfrth** [comment]
Issue should be read "RADIUS Audit Log: Missing informations" since more than the profile is missing...
Just tried with a REJECT (-1) and the "reason" field is empty and IMO it should be the same as the "Reply-Message"

**Comment by dwlfrth** [comment]
"Wi-Fi Network SSID" is not populated neither

**Comment by dwlfrth** [comment]
I think a "N/A" or something should be displayed in the case the info is not available.

**Comment by jrouzierinverse** [comment]
This has been fixed reopen if there are still problems
