### ISSUE TITLE
Debian7 Update, packages not updates

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1361]
The following packages have been kept back:
   fingerbank (2.1.1-1 => 2.2.0-1)
   freeradius (2.2.10 => 3.0.11)
   freeradius-krb5 (2.2.10 => 3.0.11)
   freeradius-ldap (2.2.10 => 3.0.11)
   freeradius-mysql (2.2.10 => 3.0.11)
   freeradius-postgresql (2.2.10 => 3.0.11)
   freeradius-utils (2.2.10 => 3.0.11)
   packetfence (5.7.0 => 6.0.0-201604120046)
   packetfence-config (5.7.0 => 6.0.0-201604120046)
   packetfence-redis-cache (5.7.0 => 6.0.0-201604120046)

**Comment by whitx** [comment]
Need to do: apt-get dist-upgrade

**Comment by whitx** [comment]
Unpacking freeradius-config (from .../freeradius-config_3.0.11_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/freeradius-config_3.0.11_amd64.deb (--unpack):
 trying to overwrite '/etc/freeradius/huntgroups', which is also in package freeradius 3.0.11
Errors were encountered while processing:
 /var/cache/apt/archives/freeradius-config_3.0.11_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by whitx** [comment]
Same error when trying to install it by hand

**Comment by whitx** [comment]
Need to use --force-overwrite to install the package manually

**Comment by whitx** [comment]
After installing this package manually, have the following issue while upgrading.

> invoke-rc.d: initscript freeradius, action "force-reload" failed.
> dpkg: error processing freeradius-ldap (--configure):
>  subprocess installed post-installation script returned error exit status 1

Happens with 

freeradius-ldap
freeradius-mysql
freeradius-rest
freeradius-redis
freeradius-krb5
freeradius-postgresql

**Comment by fdurand** [comment]
Fixed by freeradius packaging
