### ISSUE TITLE
Debian7 after update radius issue

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1362]
read_file '/usr/local/pf/raddb/mods-enabled/eap' - sysopen: No such file or directory at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 1233.
 failed!

The eap module is not existing in raddb/mods-enabled

**Comment by louismunro** [comment]
how did you start radius? 
That file is generated from a template in conf/radiusd/.

**Comment by whitx** [comment]
While starting PacketFence, so bin/pfcmd service radiusd start,
If I try to start it by himself I have the following error:
Unable to open file "raddb//sql/mysql/packetfence.conf": No such file or directory

**Comment by louismunro** [comment]
Did you move raddb to raddb2 prior to upgrading?

**Comment by whitx** [comment]
No, redoing the process atm

**Comment by fdurand** [comment]
Fixed with freeradius packaging
