### ISSUE TITLE
RADIUS Audit Log Hours selection

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1364]
You need to press the arrow or type the hour in the upper box. if you type it in the the on in the screenshot, it does not take in account what you enter.

![screenshot from 2016-04-12 14 19 09](https://cloud.githubusercontent.com/assets/9321079/14470803/8f53d5be-00b9-11e6-99a9-491b6fe488a5.png)

**Comment by extrafu** [comment]
What's the status on this?

**Comment by jrouzierinverse** [comment]
Still looking at this
