### ISSUE TITLE
Cluster active active: Sync doesn't seem to work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1366]
ERROR : Failed to sync file : /usr/local/pf/conf/ssl/server.crt . malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at /usr/local/pf/lib/pf/api/jsonrpcclient.pm line 122.

INFO : Synching file : /usr/local/pf/conf/ssl/server.key
ERROR : Failed to sync file : /usr/local/pf/conf/ssl/server.key . malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at /usr/local/pf/lib/pf/api/jsonrpcclient.pm line 122.

INFO : Synching file : /usr/local/pf/conf/ssl/server.pem
ERROR : Failed to sync file : /usr/local/pf/conf/ssl/server.pem . malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at /usr/local/pf/lib/pf/api/jsonrpcclient.pm line 122.

**Comment by julsemaan** [comment]
webservices API user and password most likely misconfigured on the master server or a typo in the user/pass on the sync command line

**Comment by julsemaan** [comment]
This seems to have occured through a problem listing the dynamic cluster namespaces from the DB while control files where still there on the filesystem.

Made a patch to list the dynamic namespaces by using both the DB and the control files
