### ISSUE TITLE
Mobile phones inline are being sent to network detection sporadically after being registered

### ISSUE THREAD

**Issue by simongottschlag** [inverse-inc/packetfence#1367]
Hi,

We are seeing issue with mobile phones (mainly iPhones) where they are sent to the network detection page sporadically ("Sorry! Your network should be enabled within a minute or two. If is is not reboot your computer.").

We are using PacketFence 5.2.2 (ZEN) in combination with HP MSM775zl where the clients are conntected to PacketFence inline layer 3 (L3).

We are not seeing these issues with computers.

@fdurand

**Comment by julsemaan** [comment]
This is for an old version and doesn't contain much debugging details.

Please discuss this matter on the mailing list.
