### ISSUE TITLE
Sync in active active Fingerbank conf file issue

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1372]
┌─[✗]─[cluster-test-2]─[/usr/local/pf]-$
└──╼  /usr/local/pf/bin/cluster/sync --as-master
INFO : Synching cluster with this node as the configuration master
Synching storage : pf::ConfigStore::Domain
Synching storage : pf::ConfigStore::Pf
Synching storage : pf::ConfigStore::Cluster
Synching storage : pf::ConfigStore::DhcpFilters
Synching storage : pf::ConfigStore::BillingTiers
Synching storage : pf::ConfigStore::Scan
Synching storage : pf::ConfigStore::Realm
Synching storage : pf::ConfigStore::ApacheFilters
Synching storage : pf::ConfigStore::Firewall_SSO
Synching storage : pf::ConfigStore::Violations
Synching storage : pf::ConfigStore::Authentication
Synching storage : pf::ConfigStore::Provisioning
Synching storage : pf::ConfigStore::FloatingDevice
Synching storage : pf::ConfigStore::VlanFilters
Synching storage : pf::ConfigStore::Switch
Synching storage : pf::ConfigStore::RadiusFilters
Synching storage : pf::ConfigStore::PKI_Provider
Synching storage : pf::ConfigStore::AdminRoles
Synching storage : pf::ConfigStore::SwitchGroup
Synching storage : pf::ConfigStore::Network
Synching storage : pf::ConfigStore::PortalModule
Synching storage : pf::ConfigStore::WMI
Synching storage : pf::ConfigStore::Pfdetect
Synching storage : pf::ConfigStore::Profile
Synching storage : pf::ConfigStore::DNS_Filters
INFO : Synching file /usr/local/pf/conf/ssl/server.crt to cluster members
INFO : Memory configuration is not valid anymore for key config::Pf(cluster-test-2.inverse) in local cached_hash
INFO : Calling distant_download_configfile on cluster-test-3.inverse
INFO : Synching file /usr/local/pf/conf/ssl/server.key to cluster members
INFO : Calling distant_download_configfile on cluster-test-3.inverse
INFO : Synching file /usr/local/pf/conf/ssl/server.pem to cluster members
INFO : Calling distant_download_configfile on cluster-test-3.inverse
INFO : Synching file /usr/local/pf/conf/pfconfig.conf to cluster members
INFO : Calling distant_download_configfile on cluster-test-3.inverse
INFO : Synching file /usr/local/pf/conf/iptables.conf to cluster members
INFO : Calling distant_download_configfile on cluster-test-3.inverse
INFO : Synching file /usr/local/fingerbank/conf/fingerbank.conf to cluster members
INFO : Calling distant_download_configfile on cluster-test-3.inverse
ERROR : Failed to call distant_download_configfile . Config file /usr/local/fingerbank/conf/fingerbank.conf doesn't exist at /usr/local/pf/lib/pf/api.pm line 650.

INFO : Synching file /usr/local/fingerbank/db/fingerbank_Local.db to c

**Comment by julsemaan** [comment]
Would need that file created empty by the packaging

**Comment by dwlfrth** [comment]
https://github.com/fingerbank/perl-client/commit/5f511cbd3efc266253b41be8858e7a747b645026 should take care of it.

Still need to handle Debian... @fdurand ?

**Comment by dwlfrth** [comment]
Let me know how you see implementation (created at install time or at packaging time...).
I'd like to be standard in both dist.

**Comment by dwlfrth** [comment]
And if possible, handled at package time would be preferable.

**Comment by julsemaan** [comment]
That would be my opinion too.

**Comment by dwlfrth** [comment]
As discussed with @fdurand , it will take place at install time
https://github.com/fingerbank/perl-client/commit/2bcb555dea4d210f3905f50262c499f9c4317178

Missing Debian part (of course)

**Comment by extrafu** [comment]
@fdurand Has it been completed and tested?
