### ISSUE TITLE
Statistics collection affects response times negatively

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1375]
The statistics collection through statsd and carbon cache uses a lot of I/O on the server and affects timings negatively.

More than 2 times more RADIUS requests can be processed without collecting stats.

This seems to occur once an installation reaches a certain maturity as seek times for the whisper DBs get higher. On a fresh install, the seek times seem to be much lower meaning the iowait is small.

I personally think we are over-collecting stats and that we are starting to use statsd as a profiling tool instead of a tool to analyse statistics.

In previous testing, I saw a difference of a few milliseconds between the real code timing and the stats shown in graphite. I believe we need to use this to time the critical operations of PacketFence and not every subroutine as this seems to add an unnecessary overhead. Especially for stats that we do not really consult (like all the queries from the DB that are logged)

We already have tools like NYTProf to profile our code so I would opt to reduce the stats collected through statsd. We have to think about the overhead of collecting stats (creation of the udp packet, creating the socket to send it and all the post-processing that occurs in the 3-5 different processes for the monitoring).

Unless someone has an objection, I will start reducing the number of stats we collect so that the footprint of the collection doesn't affect the timings anymore.

**Comment by louismunro** [comment]
I object strenuously.
Let's talk.

**Comment by julsemaan** [comment]
Update.

I have reduced the amount of statsd calls that were made and the issue is still there (although less present).
I also set `MAX_UPDATES_PER_SECOND = 100` in carbon.conf to reduce I/O
For 29641 packets (dhcp + acct + peap + http), there have been 65000 statsd packets to statsd which is as low as we can go I think

Load was a bit lower but the timings were still almost as bad as with the full stats in place

**Comment by julsemaan** [comment]
Another note, carbon-cache on idle without any load being sent to it starts doing disk traffic. Probably a lot of write per seconds as the flush process starts taking a fair share of CPU after that.

**Comment by jrouzierinverse** [comment]
Julien reduce the default sample_rate in pf::StatsD::Timer from .25 to 
.10 see if that improves performance

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by julsemaan** [comment]
As I said, the number of packets sent doesn't seem to be the issue as I stripped almost all the calls to Statsd except the ones I found useful (mwahahaha I am the mighty code deleter) without much success.

Will try it now to be sure and will post results

**Comment by julsemaan** [comment]
So the conclusion computed by the experts here leads to think that this was the post 7 days rotation of all whisper DBs data for the amount of stats we want to retain.

#1380 lowers the amount of stats (thus DB) we will keep by default and @louismunro will craft us a new storage schema strategy that should do additional miracles

Will stress test the solutions tomorrow

**Comment by julsemaan** [comment]
Putting the whisper dbs on another virtual disk (so the same physical) has fixed the issue.

Now, not sure if its because of the LVM or because of a per second limit on each partition but it fixes it.

Will document it in 'Performance optimization' in the admin guide

**Comment by julsemaan** [comment]
« fixed » by a95f9a89afda380434d2430b62989ded1bab38c8
