### ISSUE TITLE
httpd.portal: Undefined subroutine iptables_update_set

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1376]
Getting following error while trying to reach the portal.
Tested under CentOS6 new installation of April 14 packages.
Not getting the error all of the time... sometimes it works, sometimes not...

Apr 14 11:41:08 httpd.portal(3379) ERROR: [mac:00:25:d3:86:8e:2f] Caught exception in captiveportal::Controller::Root->setupDynamicRouting "Undefined subroutine &pf::ipset::iptables_update_set called at /usr/local/pf/lib/pf/node.pm line 879." (captiveportal::PacketFence::Controller::Root::end)
Apr 14 11:41:08 httpd.portal(3379) ERROR: [mac:00:25:d3:86:8e:2f] Caught exception in captiveportal::Controller::Root->dynamic_application "Can't call method "execute" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 122." (captiveportal::PacketFence::Controller::Root::end)

**Comment by julsemaan** [comment]
Try 864d48c ?

**Comment by dwlfrth** [comment]
One of you guys should remove the import...

**Comment by jrouzierinverse** [comment]
Done

**Comment by dwlfrth** [comment]
AHah lovely !
https://github.com/inverse-inc/packetfence/commit/081b241dfd2db2df57172c6d55edd5b898ab18f4

**Comment by dwlfrth** [comment]
![screen shot 2016-04-14 at 12 30 21](https://cloud.githubusercontent.com/assets/633234/14535641/be46165a-023c-11e6-9e1b-763cad1c38e3.png)
