### ISSUE TITLE
pfdhcplistener doesn't work on a monitor interface

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1377]
Since this commit 33e5be2e29993e5b4cbc9f6510677066a5ff903c pfdhcplistener is not able to listen on monitor interface.

**Comment by jrouzierinverse** [comment]
Would a monitor interface only have vlan tagged packets?
Also are there other cases where we would want to monitor vlan packets?

**Comment by dwlfrth** [comment]
Will wait for freeradius-dhcp implementation

**Comment by dwlfrth** [comment]
@dwlfrth fix your shits

**Comment by dwlfrth** [comment]
Attempt at fix. Please reopen if does not work
