### ISSUE TITLE
pfcmd checkup is unable to open certificates for expiration date validation

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1379]
Looks like pfcmd checkup is unable to open both RADIUS and HTTPD certificates to check for expiration date.

CentOS6 new installation with 20160414 packages.

WARNING - Cannot open the following certificate /usr/local/pf/conf/ssl/server.crt
WARNING - Cannot open the following certificate /usr/local/pf/raddb/certs/server.crt

**Comment by louismunro** [comment]
Do the files exist?

**Comment by dwlfrth** [comment]
Ahh crap ! Does it need to exists ?

**Comment by julsemaan** [comment]
Did you install PacketFence ?

**Comment by louismunro** [comment]
All right, all right....
Permissions then? 

(trying to delay the inevitable...)

**Comment by dwlfrth** [comment]
rpm -qa packetfence
packetfence-1.2

Yep, it's there.

**Comment by louismunro** [comment]
Do we really need those files? 
No, really?

**Comment by louismunro** [comment]
Did you reboot?

**Comment by dwlfrth** [comment]
Can someone come help me with my food. Not really sure how to use a spoon

**Comment by julsemaan** [comment]
1.2 is still in BETA, please install 0.7.1-a75f23

**Comment by dwlfrth** [comment]
On a related (retarded ?) note: http://serverfault.com/questions/769357/recovering-from-a-rm-rf

**Comment by louismunro** [comment]
That's a joke, right? 
He's just pulling people's legs...

**Comment by louismunro** [comment]
Anyway, strace has the answer, I am sure...

**Comment by dwlfrth** [comment]
Probably as much as your questions ;)

**Comment by julsemaan** [comment]
strace rm -fr /

Just tried it, machine is not responding.
Is it because its loading the certs in memory now ?

**Comment by dwlfrth** [comment]
Yes, that's the whole purpose of this issue @julsemaan

**Comment by dwlfrth** [comment]
[root@pancakeFence1 pf]# bin/pfcmd checkup
Checking configuration sanity...
WARNING - Cannot open the following certificate /usr/local/pf/conf/ssl/server.crt
WARNING - Cannot open the following certificate /usr/local/pf/raddb/certs/server.crt
[root@pancakeFence1 pf]# ll /usr/local/pf/conf/ssl/
total 12
-rw-r--r-- 1 root root 1639 Apr 14 11:18 server.crt
-rw-r--r-- 1 root root 1708 Apr 14 11:18 server.key
-rw-r--r-- 1 root root 3347 Apr 14 11:18 server.pem
[root@pancakeFence1 pf]# ll /usr/local/pf/raddb/certs/
total 152
-rw-r--r-- 1 root root 4423 Apr 14 11:18 01.pem
-rw-r--r-- 1 root root 4400 Apr 14 11:18 02.pem
-rwxr-xr-x 1 pf   pf   2706 Apr 14 00:25 bootstrap
-rw-r--r-- 1 pf   pf   1432 Apr 14 00:25 ca.cnf
-rw-r--r-- 1 root root 1256 Apr 14 11:18 ca.der
-rw-r--r-- 1 root root 1708 Apr 14 11:18 ca.key
-rw-r--r-- 1 root root 1757 Apr 14 11:18 ca.pem
-rw-r--r-- 1 pf   pf   1103 Apr 14 00:25 client.cnf
-rw-r--r-- 1 root root 4400 Apr 14 11:18 client.crt
-rw-r--r-- 1 root root 1045 Apr 14 11:18 client.csr
-rw-r--r-- 1 root root 1708 Apr 14 11:18 client.key
-rw-r--r-- 1 root root 2581 Apr 14 11:18 client.p12
-rw-r--r-- 1 root root 3636 Apr 14 11:18 client.pem
-rw-r--r-- 1 root root  424 Apr 14 11:18 dh
-rw-r--r-- 1 root root  229 Apr 14 11:18 index.txt
-rw-r--r-- 1 root root   21 Apr 14 11:18 index.txt.attr
-rw-r--r-- 1 root root   21 Apr 14 11:18 index.txt.attr.old
-rw-r--r-- 1 root root  120 Apr 14 11:18 index.txt.old
-rw-r--r-- 1 pf   pf   4462 Apr 14 00:25 Makefile
-rw-r--r-- 1 pf   pf    138 Apr 14 00:25 passwords.mk
-rw-r--r-- 1 pf   pf   8444 Apr 14 00:25 README
-rw-r--r-- 1 root root    3 Apr 14 11:18 serial
-rw-r--r-- 1 root root    3 Apr 14 11:18 serial.old
-rw-r--r-- 1 pf   pf   1125 Apr 14 00:25 server.cnf
-rw-r--r-- 1 root root 4423 Apr 14 11:18 server.crt
-rw-r--r-- 1 root root 1062 Apr 14 11:18 server.csr
-rw-r--r-- 1 root root 1704 Apr 14 11:18 server.key
-rw-r--r-- 1 root root 2589 Apr 14 11:18 server.p12
-rw-r--r-- 1 root root 3659 Apr 14 11:18 server.pem
-rw-r--r-- 1 root root 3636 Apr 14 11:18 user@example.org.pem
-rw-r--r-- 1 pf   pf    708 Apr 14 00:25 xpextensions
[root@pancakeFence1 pf]# bin/pfcmd sendreporttozammitcorpanalysisinfrastructure
unknown command sendreporttozammitcorpanalysisinfrastructure

**Comment by extrafu** [comment]
Regarding the serverfault article, can we also recover wiped chroots with that?

**Comment by julsemaan** [comment]
ask @whitx

**Comment by dwlfrth** [comment]
Yep fixed it on my side.
Was about to commit

**Comment by dwlfrth** [comment]
Can @julsemaan confirm that it fixes issue related to the rm -rf ?

**Comment by julsemaan** [comment]
@dwlfrth still waiting for the certs to be loaded in memory...

Will test the fix right after

**Comment by dwlfrth** [comment]
#waitforit
