### ISSUE TITLE
raddb messed up after an upgrade

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1385]
This have been tested on CentOS6
New install of 5.7 and then upgrading to 6.

Looks like https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L587 is not working properly

![screen shot 2016-04-15 at 13 54 47](https://cloud.githubusercontent.com/assets/633234/14570471/6636b380-0312-11e6-9743-594d57972696.png)

**Comment by dwlfrth** [comment]
NO THE FILE DOESN'T EXISTS but hey... do we really need it ?

**Comment by dwlfrth** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L588 should probably be read
if [ $1 -eq 1 ]; then

**Comment by jrouzierinverse** [comment]
According to here it should be like so 

http://www.ibm.com/developerworks/library/l-rpm2/

if [ "$1" = "2" ];then
fi

**Comment by jrouzierinverse** [comment]
Let see if c955cd66219983df07a2d8df7514cc1aafc2637e fixes the problem

**Comment by louismunro** [comment]
I'll rebuild the package and let you know as soon as that's done.

**Comment by louismunro** [comment]
Should be fixed by 66cb3d20762e2866ad9f620aa8d162425e1ee367

**Comment by dwlfrth** [comment]
Seems to be working fine now.
Although, unsure about the chosen name... "raddb2" seems a bit... "generic"
I'd go with "raddb-pre6" or something like that...

**Comment by louismunro** [comment]
"A rose by any other name..."
Call it whatever you want.
Ok, I'll do that.

**Comment by julsemaan** [comment]
Reopening temporarily while I test the new detection mechanism as the other one will break after 6.0

Will close once tested

**Comment by julsemaan** [comment]
Works fine with the new way
