### ISSUE TITLE
Apache AAA call timing stat is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1391]
Now that we are using the REST module, the stat freeradius__main__postauth is meaningless.

My idea would be to time pf::api::radius_rest_authorize but that won't count any connection latency.

Unless there is a better option @louismunro ?

**Comment by louismunro** [comment]
There is no better option, short of patching FR's rest module.

**Comment by julsemaan** [comment]
I shall do that then
