### ISSUE TITLE
CentOS 7 : Fail to start radsniff on boot

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1392]
radsniff doesn't want to start on boot.

Starting it again through a full `service packetfence restart` or using `pfcmd service radsniff start` works

```
Apr 18 12:48:59 pf-c7-1 sudo[2568]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/radsniff -d /usr/local/pf/raddb/ -D
Apr 18 12:48:59 pf-c7-1 pfcmd[2320]: radsniff: Failed opening pcap handle (stdin): truncated dump file; tried to read 4 file header b
Apr 18 12:48:59 pf-c7-1 pfcmd[2320]: radsniff|not started
```

**Comment by julsemaan** [comment]
I may have found it.

I updated the package before rebooting (classic update procedure IMO)

@fdurand is it possible the `chkconfig mariadb on` is done on update as well ?
If that is the case, then it should only be done on install as it has good chances to break active/active clusters

**Comment by julsemaan** [comment]
Previous message was in the wrong issue. Forget it

**Comment by julsemaan** [comment]
Also, did some progress, it seems that on every service packetfence restart it does that.

Starting with `pfcmd service pf start` or `pfcmd service radsniff start` works.

So it seems it is an issue when it is started from systemd

**Comment by louismunro** [comment]
It may be a timeout.
Try increasing the time allowed to packetfence to start all services.

**Comment by julsemaan** [comment]
No because the services after it start fine.

Also, there is an explicit error related to the pcap handle so I would doubt it

**Comment by louismunro** [comment]
Ok then.
Did you ask @dwlfrth if he had the files by any chance?

**Comment by dwlfrth** [comment]
Let me check my rm -rf history.

**Comment by louismunro** [comment]
Can you post the error please?

**Comment by julsemaan** [comment]
Its in the description of the issue :)

Unless @dwlfrth did some rm -fr on github

**Comment by dwlfrth** [comment]
Let me check my 'rm -rf' history real quick

**Comment by louismunro** [comment]
It works for me.
You are probably making stuff up to look important...
