### ISSUE TITLE
CentOS 7 : MariaDB starts even though it is not in the startup services

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1393]
Even though I did `chkconfig mariadb off` approximatly 8 times, mariadb still starts on boot.

Grepping and finding mariadb in /etc/systemd doesn't give me anything.

tag:sheetfilesarentgettingwiped

**Comment by julsemaan** [comment]
I may have found it.

I updated the package before rebooting (classic update procedure IMO)

@fdurand is it possible the `chkconfig mariadb on` is done on update as well ?
If that is the case, then it should only be done on install as it has good chances to break active/active clusters

**Comment by dwlfrth** [comment]
Have you tried doing it 9 times ? It solved it on my end

**Comment by julsemaan** [comment]
never 8 without 9 as they say at ZammitCorp

**Comment by fdurand** [comment]
Fixes by 8ae61bd32f7880602d0e1edf7eae7bd385915f66
