### ISSUE TITLE
RADIUS audit log: Missing fields

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1395]
This is a more "generic" issue related to https://github.com/inverse-inc/packetfence/issues/1355.

Some fields still seems to be missing.
Example: In the case of a Access-Reject, the "Reason" field of the "Node information" tab should be populated by the RADIUS Reply-Message IMO.

**Comment by dwlfrth** [comment]
Putted 6.1 since it is not a show stopper but should be considered once 6 is out.

**Comment by jrouzierinverse** [comment]
Derek is this still an issue?

**Comment by dwlfrth** [comment]
I will double check during my next tests

**Comment by jrouzierinverse** [comment]
ping

**Comment by fdurand** [comment]
I think done since we use rest for mac auth (https://github.com/inverse-inc/packetfence/issues/1724)

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/commit/5c249bd02a28312709378208967aa6edb79e8a62
https://github.com/inverse-inc/packetfence/commit/8abac53415bde861656b8188712b35ff440b9337
https://github.com/inverse-inc/packetfence/commit/eece988057b40e11bd846923da795800d5633fd5
