### ISSUE TITLE
If there are two processes of p0f or more

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1400]
When you do: service packetfence stop

Shutting down PacketFence...service|command
keepalived|already stopped
httpd.graphite|already stopped
radsniff|already stopped
statsd|already stopped
collectd|already stopped
carbon-relay|already stopped
carbon-cache|already stopped
pfbandwidthd|already stopped
pfdetect|already stopped
Insecure dependency in kill while running with -T switch at /usr/local/pf/lib/pf/services/manager.pm line 546.

**Comment by jrouzierinverse** [comment]
This will be done in the next release

**Comment by jrouzierinverse** [comment]
Fixed by 7b39bbf8b5d47c18a4abc7456719ee058946fd25
