### ISSUE TITLE
`cluster.conf` not marked as configuration file

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#1405]
Congratulations on the new release. Upgrading from `5.7.0` appears to have worked as described.

However, it seems `cluster.conf` is not listed as a conffile on Debian, so it is silently replaced during the upgrade. This might be intentional to prevent a partly upgraded node from interfering with the cluster(?), but it was surprising for me at least.

**Comment by julsemaan** [comment]
That was not intentional.

We'll make sure it isn't in future releases

**Comment by julsemaan** [comment]
@fdurand can you take a look at the debian packaging for this.
