### ISSUE TITLE
"add Switch Group" produces broken Webpage (in Firefox)

### ISSUE THREAD

**Issue by hopatzel** [inverse-inc/packetfence#1416]
Hi,

trying to add an Switch Group with Firefox as browser shows a somehow "broken" Page, that looks like "old style plain html with absurde layout".
![packetfence_add_switch_groups](https://cloud.githubusercontent.com/assets/12498055/14741772/fcd8a844-0898-11e6-9c58-edf9af6e8004.png)

**Comment by hopatzel** [comment]
forgot to mention: setting up a new packetfence-ZEN-6.0.0 VM

**Comment by julsemaan** [comment]
Does it do it every time or from time to time ?

Can you provide the output (screenshot) of the dev console of the browser (Right-click, Inspect, Console tab)

Also, provide your OS version + browser
