### ISSUE TITLE
Services order have precedence in startup even if a service is required by another to start.

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1423]
We have a configurable order of services when it comes to start them.
We also have the ability to specify if a service is required for another to start.

If a service (let's call it "potatoes") requires another service (let's call it "tomatoes") to start, and if startup order of "potatoes" is 3 and service order of "tomatoes" is 4, "potatoes" will try to start first (or will just won't start since "tomatoes" is not started yet)

**Comment by julsemaan** [comment]
That throws out the question then, should we stop using the precedence and remove it completely in favor of ordering the services using only the startup order.

That may make it simpler as well.

**Comment by dwlfrth** [comment]
Stop throwing things at me.

I think we should not... That may introduce problems; since order is configurable, someone may go ahead and play with it and break services startup dependancies...

IMO, we should definitely keep the "dependsOn" notion but just move it before the service needing it (not honouring the order if it is a dependancy)

**Comment by louismunro** [comment]
I would remove it.
Dependency is easier to screw up than service ordering.

**Comment by dwlfrth** [comment]
I don't see how it is "easier" to screw up things with dependancies since they are hardcoded in the different service managers...
If Bob goes into the code, remove dependancy and it screw things up... it is it's fault
If Bob goes into the configuration, modify an order because he easily can and may not be aware of the impact, that change screw things up, it is something different...

I think "dependsOn", both for service startup and stopping, is a plus.

**Comment by louismunro** [comment]
The code to handle dependencies is far more complex that just sorting the services based on a key.
It has been broken in the past.

**Comment by julsemaan** [comment]
I'm heart broken between the two choices in fact.

And @monsieurW is right about the "if you tamper with configuration, you shouldn't make the services 'crash'"

status quo I guess since its already there and was used

**Comment by jrouzierinverse** [comment]
We could use the following module to calculate the dependencies and the inverse of the dependencies. 

http://search.cpan.org/~adamk/Algorithm-Dependency-1.110/lib/Algorithm/Dependency.pm

**Comment by fdurand** [comment]
Systemd manage that now
