### ISSUE TITLE
PacketFence 6 never starts

### ISSUE THREAD

**Issue by eLvErDe** [inverse-inc/packetfence#1427]
Hello,

It seems to get stuck right after radsniff:

> root@pf:~# strace /usr/local/pf/bin/pfcmd service pf start 2>/tmp/log
> service|command
> httpd.admin|already started
> Checking configuration sanity...
> WARNING - Rule 'sponsor rule catchall' does not have any configured class. Defaulting to 'authentication'
> WARNING - Rule 'file1 rule admins' does not have any configured class. Defaulting to 'authentication'
> WARNING - Rule 'email rule catchall' does not have any configured class. Defaulting to 'authentication'
> WARNING - invalid parameter billing_engine for profile default
> WARNING - invalid parameter mandatory_fields for profile default
> iptables|already started
> redis_queue|already started
> httpd.aaa|already started
> radiusd-acct|already started
> radiusd|already started
> pfqueue|already started
> pfdns|already started
> pfdhcplistener_eth1|already started
> pfdhcplistener_eth0|already started
> httpd.parking|already started
> httpd.portal|already started
> dhcpd|already started
> httpd.webservices|already started
> pfmon|already started
> p0f|already started
> pfbandwidthd|already started
> carbon-cache|already started
> carbon-relay|already started
> collectd|already started
> statsd|start
> radsniff|start

Can you help me to figure out what's going on ?

Thanks,

**Comment by dwlfrth** [comment]
Please use the "packetfence-users" mailing-list for this kind of matters.
http://packetfence.org/support/index.html

Thanks :)
