### ISSUE TITLE
Cannot customize logo in v6 portal

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1430]
Seems there is no logo in the new portal.

For retro-compatibility and to prevent customizing the template only for the logo, it should be in the layout.

**Comment by cgx** [comment]
PacketFence's terrible logo no longer appears on the portal so it can't be customize. Very difficult to integrate some unknown logo into a default template. We'll need to create new templates for this kind of requirement.

**Comment by julsemaan** [comment]
Its just that almost all the customers have their own logo so that would mean creating a custom template for everyone.

We could replace the big current module icon by the logo if the user desires to based on a config parameter
