### ISSUE TITLE
Rethinking the X to restart the portal process

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1431]
The `X` to restart the portal process is missing an alt message like 'Restart from beginning'.

Also, not sure the `X` is the right icon for the process of restarting.

**Comment by cgx** [comment]
Suggestion?

**Comment by julsemaan** [comment]
Only account we could think of was the refresh icon but it may not even be good enough.

Which icon set do we use ?

**Comment by cgx** [comment]
[Google's Material Icons](https://design.google.com/icons/).

**Comment by julsemaan** [comment]
replay looks like the one we needs IMO
