### ISSUE TITLE
Timeout in systemd service file too short

### ISSUE THREAD

**Issue by MarieHo** [inverse-inc/packetfence#1433]
Hello,
we are experiencing some issues with packetfence installed from DEBIAN repositories.
It seems at the first start the timeout specified in systemd file is too short, here is what we can see in systemd status:

> ● packetfence.service - PacketFence Service
>    Loaded: loaded (/lib/systemd/system/packetfence.service; enabled)
>    Active: failed (Result: timeout) since Wed 2016-04-27 08:57:54 UTC; 2s ago
>   Process: 953 ExecStart=/usr/local/pf/bin/pfcmd service pf start (code=killed, signal=TERM)

We launched startup command using time: time /usr/local/pf/bin/pfcmd.pl service pf start
Here is the output:

```
[...]
radsniff|start
[ most of time is lost between these two lines]
httpd.graphite|start

real    12m23.111s
user    0m44.612s
sys 0m1.596s
```

Obivously the "TimeoutStartSec=180s" specified in "/lib/systemd/system/packetfence.service" is not enough.

packtfence.log show that both service took normal time to start but I have no clue what's happening between them:

> Apr 27 09:03:16 pfcmd.pl(1470) INFO: Daemon radsniff took 0.044 seconds to start. (pf::services::manager::launchService)
> Apr 27 09:14:44 pfcmd.pl(1470) INFO: Daemon httpd.graphite took 0.030 seconds to start. (pf::services::manager::launchService)

After the first start it's a lot faster and complete startup now fits into the 180s frame.
Here is the time for the second start:

```
time systemctl start packetfence

real    1m6.068s
user    0m0.000s
sys 0m0.000s
```

Thank you

**Comment by julsemaan** [comment]
@whitx his initial startup took 12 minutes so putting 300s won't help much :)

I think we need to figure out why graphite takes so long to start on the first start

**Comment by whitx** [comment]
I was thinking of just put it higher for slower machines, but yeah you are right

**Comment by julsemaan** [comment]
Issue here is the long startup of httpd.graphite

@louismunro is there something we can do around that ?

**Comment by louismunro** [comment]
Not sure it's specifically a graphite problem
It may be that graphite is among the last service to start and there is not enough memory left by then and/or load is high after starting all the other services.

Temporarily you could disable the timeout in the systemd unit file.

**Comment by julsemaan** [comment]
We have fully reworked the services so this isn't relevant anymore
