### ISSUE TITLE
Accounting reports MACs are oddly formatted

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1437]
Look closely and you will notice MACs like e8::3:9::35::5:0:

![screen shot 2016-04-27 at 3 44 03 pm](https://cloud.githubusercontent.com/assets/193997/14865901/f64111b6-0c8e-11e6-8e79-d193e520d92d.png)

**Comment by julsemaan** [comment]
Anyway, 2 weeks after a deployment that page is not accessible anymore so who cares ?
