### ISSUE TITLE
Null auth and BlackHole portal modules are broken

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1439]
It's impossible to create a portal module using either Null auth or Blackhole.

![screen shot 2016-04-28 at 10 14 18 am](https://cloud.githubusercontent.com/assets/193997/14888821/08e039be-0d2a-11e6-8380-44c9c8b13ac7.png)

Logs follow:

```
Apr 28 10:10:53 httpd.admin(677) INFO: Config::PortalModule::Authentication::Null (pfappserver::Base::Controller::Crud::view)
Apr 28 10:10:53 httpd.admin(677) ERROR: Caught exception in pfappserver::Controller::Config::PortalModule->view "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/html/pfappserver/lib/pfappserver/Form/Config/PortalModule/Authentication.pm line 71." (pfappserver::PacketFence::Controller::Root::end)
```

**Comment by jrouzierinverse** [comment]
The Null auth part was already fixed by @julsemaan in 2731bf8e3ed3878dbf8898d5d65a08583dc87f35.
The blackhole was fix by me in beb6f86f9578a28fdabc552ee1b9a0d419da42dc
