### ISSUE TITLE
CentOS 7: not listing perl as a dependency

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1443]
On a CentOS fresh install, perl isn't there.

We should list it as a dependency in our spec file

**Comment by jrouzierinverse** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L101

It is listed maybe there is a problem with the version

**Comment by julsemaan** [comment]
Here is the output

```
--> Finished Dependency Resolution
Error: Package: freeradius-3.0.11-25.1.x86_64 (packetfence-devel)
           Requires: /bin/perl
Error: Package: freeradius-utils-3.0.11-25.1.x86_64 (packetfence-devel)
           Requires: /bin/perl
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by louismunro** [comment]
I fought with that long enough and then decided to just tell people to install it.
I believe @fdurand came up with a better solution though.

**Comment by jrouzierinverse** [comment]
That is a different problem.

freeradius-3.0.11-25.1.x86_64 is requiring the executable /bin/perl.
Which is not provided by any package.

This is a packaging issue with freeradius not with PacketFence

**Comment by jrouzierinverse** [comment]
Spoke to the man himself @fdurand he has to push his fix in devel repo.

**Comment by fdurand** [comment]
Did the fix in freeradius.spec:

%{?filter_setup:
%filter_from_requires \/bin\/perl/d
%filter_setup
}

**Comment by julsemaan** [comment]
So our main man @fdurand did his magic I guess ?

Can we close this ?

**Comment by fdurand** [comment]
Yes, fixed in stable repo, just need to update devel repo
