### ISSUE TITLE
"Available memory" graph does not take swap into account

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#1451]
Was wondering why my pf instance was reacting very sluggish and discovered it had been swapping a lot (see https://github.com/inverse-inc/packetfence/issues/1301#issuecomment-216051437). There is no way to discover this problem on the dashboard view. It would be helpful to somehow indicate the amount of swap used otherwise the "available memory" graph is misleading.

**Comment by fdurand** [comment]
Added swap graph in the admin since 6.5
