### ISSUE TITLE
Fingerbank database update not going to pfqueue

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1452]
The Fingerbank database update doesn't seem to be done through pfqueue although it should (info taken from #1301) reported by @tribut :

> On 6.0.1 (Debian jessie) when I click Update Fingerbank DB in Fingerbank Settings two of the webservices` httpd processes start hogging memory after a few seconds (4GB and 1G resp.). Do you need help reproducing this or is this a known issue?
> Possibly related to #1303.

**Comment by tribut** [comment]
Logs, as requested:

`packetfence.log`:

```
May 01 19:45:29 httpd.webservices(59915) INFO: [mac:unknown] Sending fingerbank component update to local queue. (pf::api::fingerbank_update_component)
```

`pfqueue.log`:

```
May 01 19:46:42 pfqueue(81597) INFO: [mac:unknown] Synching file /usr/local/fingerbank/db/fingerbank_Upstream.db to cluster members (pf::cluster::sync_files)
May 01 19:46:42 pfqueue(81597) INFO: [mac:unknown] Calling distant_download_configfile on zaunkoenig (pf::cluster::api_call_each_server)
May 01 19:46:42 pfqueue(81597) INFO: [mac:unknown] Successfully updated Upstream database (pf::fingerbank::_update_fingerbank_component)
May 01 19:46:42 pfqueue(81597) INFO: [mac:unknown] email regarding 'PF Alert: (erlkoenig) Fingerbank - update-upstream-db status' sent to [obfuscated]@stunet.tu-freiberg.de (pf::config::util::pfmailer)
```

`ps aux --sort -rss|head -3`:

```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
pf        59915  0.1 26.2 3255792 1523660 ?     S    17:50   0:09 /usr/sbin/apache2 -f /usr/local/pf/var/conf/httpd.conf.d/httpd.webservices -Ddebian
pf        81843  1.2 11.4 1081800 662384 ?      S    19:46   0:09 /usr/sbin/apache2 -f /usr/local/pf/var/conf/httpd.conf.d/httpd.webservices -Ddebian
```

The other node has the same log entries except with the node names switched. Only when I restart `httpd.webservices` the processes return to about 500M virtual, 150M resident.

**Comment by julsemaan** [comment]
Should by fixed by 55d832060f1a0845342274ce2832ba44c8d025a5

Please apply the maintenance using:
`# /usr/local/pf/addons/pf-maint.pl`

Then restart PacketFence and try again.

We'll close this when you confirm its fixed

**Comment by tribut** [comment]
Seems to be fixed, can't reproduce anymore. Thanks.

**Comment by julsemaan** [comment]
You're welcome !
