### ISSUE TITLE
Installation on Ubuntu and Debian not working - Dependencies

### ISSUE THREAD

**Issue by Themercee** [inverse-inc/packetfence#1462]
I try to install it on debian and ubuntu from the installation on the website. I add the source packet.list and the gpg key to the source.list.d folder .

When I run `apt-get install packetfence` , I get a error message telling me unmet dependencies.

![screenshot from 2016-05-06 09-18-53](https://cloud.githubusercontent.com/assets/6720140/15074288/1dd50a3c-136c-11e6-8b41-fdca4a514fd5.png)

Debian is on Jessie and Ubuntu on 16.04 (I know it is not support for the moment, but debian is supposed to be).

EDIT: I try to change the repository to `deb http://inverse.ca/downloads/PacketFence/ubuntu/ jessie jessie` instead and I get the same result with less dependencies missing

Hope to help, because this is a serious issue if people can't install it :/

**Comment by fdurand** [comment]
I just retry it and it works.
So what i did:
echo 'deb http://inverse.ca/downloads/PacketFence/debian jessie jessie' > /etc/apt/sources.list.d/packetfence.list
apt-key adv --keyserver keys.gnupg.net --recv-key 0x810273C4
apt-get update
apt-get install packetfence

**Comment by Themercee** [comment]
Ok, that's weird. I will try to look further into it and give you feedback. Thanks to have tried it!

**Comment by erlaan** [comment]
I hade same problem as Themercee. 

 http://inverse.ca/downloads/PacketFence/debian wheezy wheezy' 
When you add that to your source list then it's broken package but if you change wheezy wheezy to jessie jessie as fdurand did say. it working to install. That fixed my problem.

**Comment by glascopfcta** [comment]
I am able to use the repo for centos, and it works well, however, it is not working for ubuntu

**Comment by louismunro** [comment]
To be expected.
We don't package for Ubuntu anymore (since PF 6.0).

**Comment by glascopfcta** [comment]
Thank you immensely louismunro!

**Comment by glascopfcta** [comment]
louismunro, I would like to understand this. Are you saying that you do not provide the packages after PF 6.0 for Debian 8.0(Ubuntu 16.04)? So, with this, I would need to compile it and gather the dependencies my self?

**Comment by whitx** [comment]
We do provide the packages for Debian 8.X/CentOS 7.X for PacketFence version superior to 6.0, not for Ubuntu anymore.

**Comment by glascopfcta** [comment]
Thank you whitx!

**Comment by ghost** [comment]
Was there any particular reason for the end of life on support for Ubuntu? GNU distributions are a dime a dozen, to be sure, but Ubuntu is rather popular.

**Comment by julsemaan** [comment]
@Viusing 

Ubuntu was end of lifed because maintaining it required a lot of resources and was a packaging pain to do.

We still have Debian if you need a .deb distro

**Comment by ghost** [comment]
I went with CentOS instead. Everything works beautifully.
