### ISSUE TITLE
[deb8-pk6] Cannot change lease time via admin interface 

### ISSUE THREAD

**Issue by riban** [inverse-inc/packetfence#1484]
Just like this bug: https://github.com/inverse-inc/packetfence/issues/1309

Experience is the same for Debian 8 

I'm using the libhtml-formhandler-perl from inverse.ca repo
ii  libhtml-formhandler-perl                                 1:0.40019-1                all          HTML forms using Moose

httpd.admin(26718) ERROR: Caught exception in pfappserver::Controller::Config::Networks->update "Can't call method "fif" on an undefined value at /usr/share/perl5/HTML/FormHandler/Validate.pm line 266." (pfappserver::PacketFence::Controller::Root::end)

**Comment by julsemaan** [comment]
Is this still relevant ?

That bug (and the one you refer) seem long gone

**Comment by julsemaan** [comment]
Will close it, re-open if needed

**Comment by qehs244** [comment]
Jan 29 16:42:42 packet httpd_admin: httpd.admin(1062) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::Networks->update "Can't call method "fif" on an undefined value at /usr/share/perl5/HTML/FormHandler/Validate.pm line 266." (pfappserver::PacketFence::Controller::Root::end)

still here in PF 7.4 on debian Jessie clean install
