### ISSUE TITLE
Some strings missing from transifex

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#1497]
Some strings used in the captive portal (such as "Submit" and "Authentication") are not available to be translated in transifex even though they are passed through `i18n()`.

**Comment by julsemaan** [comment]
New file was uploaded yesterday. Looks good on my end now.

**Comment by tribut** [comment]
Still missing some strings, for example "Submit" (used [here](https://github.com/inverse-inc/packetfence/blob/devel/html/captive-portal/templates/signin.html#L25)).

**Comment by tribut** [comment]
This seems to be also be true for some string in pfappserver, such as "Registration must happen before [_1]." and "Once authenticated the access will be valid for [_1] [_2]." (from `html/pfappserver/lib/pfappserver/Model/User.pm`).

**Comment by jrouzierinverse** [comment]
This was fixed by 713db2260e091df839800d04a01ed9e381ff766c and 1cfd5d3f58eb6986cd4ba4a93870d87b142142e8
