### ISSUE TITLE
HASH(0x7fcfb7cf2040) value on Portail profil Filter after saving

### ISSUE THREAD

**Issue by piellick** [inverse-inc/packetfence#1503]
Hello,
when i try to add filter on a portail profil, after saving the option. My value is remplaced by SSID and HASH(0x7fcfb7cf2040) .

I'm on Packetfilter 6.0.2 and after somes checks with "oeufdur" on IRC, i have the good "HTML-FormHandler" packet : 

apt-cache search HTML-FormHandler libhtml-formhandler-model-dbic-perl - base class that holds DBIC model role libhtml-formhandler-perl - HTML forms using Moose root@packetfence:~# apt-cache show libhtml-formhandler-model-dbic-perl Package: libhtml-formhandler-model-dbic-perl Version: 0.29-1

![filters](https://cloud.githubusercontent.com/assets/18485789/15676796/faff1b02-2747-11e6-8dd5-b0d38c1274b3.PNG)
apt-cache show libhtml-formhandler-perl Package: libhtml-formhandler-perl Version: 1:0.40019-1 Architecture: all Maintainer: root root@jessiedeb.inverse.local Installed-Size: 1201

**Comment by piellick** [comment]
another exemple:

on profiles.conf : 

[interne_DR7]
filter=ssid:HASH(0x7fcfb7ffe530),ssid:HASH(0x7fcfb7fdf0f8),network:192.168.15.0/24
block_interval=10m
sources=ad_dr7_cnrs_fr
logo=/common/cnrs_interne.png
description=portail_interne_DR7
filter_match_style=all
reuse_dot1x_credentials=enabled

ON WEB UI : 
![filters2](https://cloud.githubusercontent.com/assets/18485789/15679373/f3ce085c-2751-11e6-930e-7e209b291f37.PNG)

On configuration file, last filter is OK not on the WEB UI after reloading page.

![filters3](https://cloud.githubusercontent.com/assets/18485789/15679457/363d47e8-2752-11e6-80a1-383eb829f314.PNG)

**Comment by jrouzierinverse** [comment]
Can you verify if you do not have another HTML::Formhandler installed?

**Comment by piellick** [comment]
from my aptitude cache : 
``
root@packetfence:/usr/local/pf/conf# apt-cache search Formhandler
libhtml-formhandler-model-dbic-perl - base class that holds DBIC model role
libhtml-formhandler-perl - HTML forms using Moose

``

`
apt-cache show libhtml-formhandler-model-dbic-perl
Package: libhtml-formhandler-model-dbic-perl
Version: 0.29-1
Installed-Size: 131
Maintainer: Debian Perl Group <pkg-perl-maintainers@lists.alioth.debian.org>
Architecture: all
Provides: libhtml-formhandler-traitfor-model-dbic-perl
Depends: perl, libdbix-class-perl (>= 0.08250), libdbix-class-resultset-recursiveupdate-perl, libhtml-formhandler-perl (>= 0.40016), libmoose-perl (>= 2.0007), libnamespace-autoclean-perl
Description-en: base class that holds DBIC model role
 HTML::FormHandler::Model::DBIC and
 HTML::FormHandler::TraitFor::Model::DBIC provide an interface between
 HTML::FormHandler and DBIx::Class.
 .
 This interface is available as a regular class or as a Moose role.  It
 will save form fields automatically to the database.
Description-md5: 75d85d3cf3314a0371956f9d2e215e73
Homepage: https://metacpan.org/release/HTML-FormHandler-Model-DBIC
Tag: devel::lang:perl, devel::library, implemented-in::perl
Section: perl
Priority: optional
Filename: pool/main/libh/libhtml-formhandler-model-dbic-perl/libhtml-formhandler-model-dbic-perl_0.29-1_all.deb
Size: 31186
MD5sum: 4b2bc3af863df4c81a6d4ffd82551024
SHA1: b172d2a39a50c5128268aaff257b42bb18da4654
SHA256: b616b3f9d4a9e5f5d1e5196565ee87be499f6edab0bd550a01b6adb3d423b475
`

``
root@packetfence:/usr/local/pf/conf# apt-cache show libhtml-formhandler-perl
Package: libhtml-formhandler-perl
Version: 1:0.40019-1
Architecture: all
Maintainer: root root@jessiedeb.inverse.local
Installed-Size: 1201
Depends: perl, libaliased-perl, libclass-load-perl (>= 0.06), libdata-clone-perl, libdatetime-format-strptime-perl, libdatetime-perl, libemail-valid-perl, libfile-sharedir-perl, libhtml-tree-perl (>= 3.23), libjson-perl, libmoose-perl (>= 2.0007), libmoosex-getopt-perl (>= 0.16), libmoosex-types-common-perl, libmoosex-types-loadableclass-perl (>= 0.006), libmoosex-types-perl (>= 0.20), libnamespace-autoclean-perl (>= 0.09), libsub-exporter-perl, libsub-name-perl, libtry-tiny-perl
Homepage: https://metacpan.org/release/HTML-FormHandler
Priority: optional
Section: perl
Filename: pool/jessie/libh/libhtml-formhandler-perl/libhtml-formhandler-perl_0.40019-1_all.deb
Size: 440358
SHA256: d59bfe5cda2d1eb80513a77bbeb348bbe442a59d90172a7182c542d745d060b3
SHA1: aa32ee048abd1d6cc7eec9392703546a8bc86896
MD5sum: 2d14e36c81c8fb2d5c60a6094140f8ac
Description: HTML forms using Moose
 [enter your description here]
 .
 This description was automagically extracted from the module by dh-make-perl.
Description-md5: 245c1b18ece1f7b95d52334b5fc3af96

Package: libhtml-formhandler-perl
Version: 0.40057-1
Installed-Size: 1272
Maintainer: Debian Perl Group pkg-perl-maintainers@lists.alioth.debian.org
Architecture: all
Depends: perl, libaliased-perl, libclass-load-perl, libdata-clone-perl, libdatetime-format-strptime-perl, libdatetime-perl, libemail-valid-perl, libfile-sharedir-perl, libhtml-tree-perl, libjson-perl, liblist-allutils-perl (>= 0.07), libmoose-perl, libmoosex-getopt-perl, libmoosex-types-common-perl, libmoosex-types-loadableclass-perl, libmoosex-types-perl, libnamespace-autoclean-perl, libsub-exporter-perl, libsub-name-perl, libtry-tiny-perl
Description-en: form handler written in Moose
 HTML::FormHandler maintains a clean separation between form construction and
 form rendering. It allows you to define your forms and fields in a number of
 flexible ways. Although it provides renderers for HTML, you can define custom
 renderers for any kind of presentation.
Description-md5: 74e127d23c66c54781109528e606a36c
Homepage: https://metacpan.org/release/HTML-FormHandler
Tag: devel::lang:perl, devel::library, implemented-in::perl
Section: perl
Priority: optional
Filename: pool/main/libh/libhtml-formhandler-perl/libhtml-formhandler-perl_0.40057-1_all.deb
Size: 462744
MD5sum: 76df88bc5e0fa165484b4cf93ac0195c
SHA1: c9c45965456f94b55eaa09e9e5a51f5e5f437350
SHA256: f430f6a07f037d8e8c49c1787f49d32c6f9b7f7c6191a12f0b1aa435c1da5d20
``
