### ISSUE TITLE
When user goes to device registration page when it is disabled the application is never created

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1505]
May 31 11:21:17 httpd.portal(30015) ERROR: [mac:unknown] Caught exception in captiveportal::View::HTML->process "Can't call method "render" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/View/HTML.pm line 19." (Catalyst::finalize)

**Comment by julsemaan** [comment]
Are you taking care of it or should I take it ?

**Comment by jrouzierinverse** [comment]
I will
