### ISSUE TITLE
Unable to detect network connectivity 

### ISSUE THREAD

**Issue by asoufiane** [inverse-inc/packetfence#1514]
Hi,

When the user authenticate this error message appear "Unable to detect network connectivity Try restarting your web browser or opening a new tab to see if your access has been succesfully enabled",
and the siwtch cannot map the user to vlan service,until i force the port to down/up.

Best regards,
Soufiane

**Comment by extrafu** [comment]
Use the mailing list - this is a configuration problem.

**Comment by qqdog1114** [comment]
Hi,

I also encountered the same problem. I don't know which setting is wrong or which logs should I check?

**Comment by jbryan211** [comment]
I'm having the same issue, what troubleshooting steps should be performed?
