### ISSUE TITLE
French translation on portail profil

### ISSUE THREAD

**Issue by piellick** [inverse-inc/packetfence#1515]
Hello,
i selected fr_FR for my portail profil and langage is a MIX between french and english as you can see, It is normal ?

![bug_fr](https://cloud.githubusercontent.com/assets/18485789/15774317/0d775c5a-297c-11e6-8979-4b60917d6847.PNG)
![bug_fr2](https://cloud.githubusercontent.com/assets/18485789/15774319/0d7ea136-297c-11e6-8b0a-61f295371aa2.PNG)
![bug_fr3](https://cloud.githubusercontent.com/assets/18485789/15774318/0d7ab062-297c-11e6-8ea0-79c22a33735c.PNG)

**Comment by julsemaan** [comment]
We are currently missing translation strings in version 6.

They have been uploaded into our translation system but still haven't been translated.

You can either wait for us to complete the translation or help out:
https://packetfence.org/support/faq/article/how-to-translate-packetfence-in-another-language.html

**Comment by piellick** [comment]
hi,
i made a request over transifex, waiting or validation to start helping us.

**Comment by piellick** [comment]
hi, i saw that french translation is done ? how can i use it ? wait for packetfence 6.1 or download .PO files ?

thanks.

**Comment by whitx** [comment]
It will be integrated with 6.1, else you can do the following, download the po file and execute this from your cli:
for TRANSLATION in de en es fr he_IL it nl pl_PL pt_BR; do
/usr/bin/msgfmt conf/locale/$TRANSLATION/LC_MESSAGES/packetfence.po \
--output-file conf/locale/$TRANSLATION/LC_MESSAGES/packetfence.mo
done

**Comment by piellick** [comment]
Thanks, have you an idee of when 6.1 will be avalaible  ?

**Comment by julsemaan** [comment]
Closing that, 6.1 has been released a long time ago
