### ISSUE TITLE
api_key is not taken into account in fingerbank settings

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1519]
Fingerbank settings does not validate the api_key, you need to manually add it by hand at the moment.

**Comment by julsemaan** [comment]
Not sure I understand, are you saying the key isn't validated or that you're unable to configure it via the web admin ?

**Comment by whitx** [comment]
Not configurable from the webadmin

**Comment by julsemaan** [comment]
well I certainly can configure it :)

![image](https://cloud.githubusercontent.com/assets/3857942/15826272/ecebb2a0-2bd4-11e6-85da-ad51840c1cff.png)

**Comment by whitx** [comment]
The fingerbank package 2.2.1 is not present for CentOS6 (debian?)

**Comment by julsemaan** [comment]
@fdurand is looking into it.

Please close once packages have been synced to all the repos

**Comment by whitx** [comment]
fixed in devel
