### ISSUE TITLE
Search nodes Page ignores Display Number from second Page

### ISSUE THREAD

**Issue by hopatzel** [inverse-inc/packetfence#1527]
If one changes the number of displayed Nodes (eg from 25 to 200) the first page Shows the 200 nodes. but clicking on "2" there are only 25 to be seen and These are the 2nd 25 of the first page, as if the 25 would be in place again, the "Display XXX entries per page still showing 200.

**Comment by jrouzierinverse** [comment]
This has been fixed in devel will be in the next release.
