### ISSUE TITLE
portal preview: MAC used to preview

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1530]
Now that we are proxying the portal preview in the webadmin, it takes the computer MAC address we are using to preview.
That may cause some "issues" depending on the status of that node in the PacketFence node table.

See my last comment on PR #1473 
"Now proxying using the MAC address of the device we are previewing with...
Which means, if the device I am accessing the admin interface to preview the portal profiles is registered, I will hit the "Sorry your network is being enabled ..."
We should use a "proxied mac address / ip address" which will not be part of the 'nodes' and for which we will not keep a session."

**Comment by julsemaan** [comment]
+1

**Comment by fdurand** [comment]
Before we rewite the x-forwarded-for header to match the management ip address.
The idea now is to add a new header and if this header exist then use the fake mac address.
