### ISSUE TITLE
Admin - nodes : Modifying a node resets the search results

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1533]
Modifying the node resets the search results even though the search stays there.

Reproduce:
Search : Node MAC - is - c8:bc:c8:8d:08:ff
Click on the node to edit it.
Change the role and save the node
Now the search results have been reset to the default ones even though the search query is still displayed

**Comment by jrouzierinverse** [comment]
Unable to replicate in devel

**Comment by julsemaan** [comment]
Tested and devel is fixed but still there in maintenance/6.0

Are you aware of which commit fixes this as it would need to go in the maintenance

**Comment by jrouzierinverse** [comment]
No I will look and see how easy it is to back port.

**Comment by whitx** [comment]
I think you looking for fc0555b5be52eb0afdcdaf40fc6b37be76f2371c

**Comment by jrouzierinverse** [comment]
Picked and pushed
