### ISSUE TITLE
Right on multiple logs file and logrotate are wrong

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1537]
We add the executable permissions on somes logs files and on the logrotate conf file, this should not be the case (RHEL packaging only, debian is fine, move the 775 to 770)

**Comment by julsemaan** [comment]
770 won't remove the executable bit.

I think you are looking for : 0665 / rw-rw-r

**Comment by extrafu** [comment]
rw-rw-r is 664 ;-)

**Comment by julsemaan** [comment]
Would have been nice if you would have done an error too to continue the fail chain.

God we miss @lzammit
