### ISSUE TITLE
RANDOM Application error : Caught exception in captiveportal::Controller::Root->dynamic_application

### ISSUE THREAD

**Issue by piellick** [inverse-inc/packetfence#1542]
Hy everyone,

on a fresh install from today (debian 8U4 / PF 6.0.3) in inline mode, after created a profil portail i have this error when i try to load my portal on a web browser : 

`Application error : Caught exception in captiveportal::Controller::Root->dynamic_application "Can't call method "execute" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 122."`

It's random ....not at eatch time ....

**Comment by piellick** [comment]
From packetfence.log

First try error (16:11:40) second try it's work (16:12:47) : 

```
Jun 10 16:11:40 httpd.portal(1608) INFO: [mac:unknown] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)
Jun 10 16:11:40 httpd.portal(1608) INFO: [mac:38:59:f9:14:62:37] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)
Jun 10 16:11:40 httpd.portal(1608) INFO: [mac:38:59:f9:14:62:37] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)
Jun 10 16:11:40 httpd.portal(1608) INFO: [mac:38:59:f9:14:62:37] Updating node user_agent with useragent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0' (captiveportal::PacketFence::DynamicRouting::Application::process_user_agent)
Jun 10 16:11:40 httpd.portal(1608) INFO: [mac:38:59:f9:14:62:37] Static User-Agent lookup data initialized (pf::useragent::_init)
Jun 10 16:11:40 httpd.portal(1608) ERROR: [mac:38:59:f9:14:62:37] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( * ) FROM device me WHERE ( name IS NULL )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
 (captiveportal::PacketFence::Controller::Root::end)
Jun 10 16:11:40 httpd.portal(1608) ERROR: [mac:38:59:f9:14:62:37] Caught exception in captiveportal::Controller::Root->dynamic_application "Can't call method "execute" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 122." (captiveportal::PacketFence::Controller::Root::end)
Jun 10 16:12:47 httpd.portal(2251) INFO: [mac:unknown] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)
Jun 10 16:12:47 httpd.portal(2251) INFO: [mac:38:59:f9:14:62:37] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)
Jun 10 16:12:47 httpd.portal(2251) INFO: [mac:38:59:f9:14:62:37] Instantiate profile DR07_WIFI_INTERNE (pf::Portal::ProfileFactory::_from_profile)

```

**Comment by julsemaan** [comment]
Does this happen while you were configuring the portal or after you've finished doing it ?

**Comment by piellick** [comment]
...it's random ..I did not remember if this bug showed up before i configured portails profiles.

**Comment by julsemaan** [comment]
Are you still experiencing it on a regular basis or is this something that occurred at some point and isn't anymore ?

**Comment by piellick** [comment]
no it's append every time and for each portail profil. I need to reload portail web page and after it works.

**Comment by piellick** [comment]
I you want a debug output .. just ask me wich log file i need to put on the issue.

**Comment by piellick** [comment]
I hope this error stack could help ..still crash at the first loading of each portal.
`
Jun 14 11:21:11 httpd.portal(6361) ERROR: [mac:38:59:f9:14:62:37] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD:                   :SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( * ) FROM device me WHERE ( nam                   e IS NULL )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369 (captiveportal::PacketFence::Controller::Root::end)`
`

`Jun 14 11:21:11 httpd.portal(6361) ERROR: [mac:38:59:f9:14:62:37] Caught exception in captiveportal::Controller::Root->dynamic_a                   pplication "Can't call method "execute" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence                   /Controller/Root.pm line 122." (captiveportal::PacketFence::Controller::Root::end)``

**Comment by julsemaan** [comment]
Seems the error you found for the Fingerbank database would be related.

Can you try this (no need to give the output unless there are errors):
sqlite3 /usr/local/fingerbank/db/fingerbank_Upstream.db

> SELECT COUNT( \* ) FROM device me WHERE ( name IS NULL )

sqlite3 /usr/local/fingerbank/db/fingerbank_Local.db

> SELECT COUNT( \* ) FROM device me WHERE ( name IS NULL )

Then provide the output of the following: 
`grep 'database disk image is malformed' /usr/local/pf/logs/FILE_WHERE_YOU_FOUND_THE_ERROR`

Then provide pfmon.log (using pastebin or any other service you like)

Thanks !

**Comment by riban** [comment]
Hi, 

I am also having the same issue after the recent update. 

Jun 14 16:11:59 httpd.portal(27345) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM device me WHERE ( name = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
 (captiveportal::PacketFence::Controller::Root::end)
Jun 14 16:11:59 httpd.portal(27345) ERROR: [mac:84:3a:4b:8e:92:40] Caught exception in captiveportal::Controller::Root->dynamic_application "Can't call method "execute" on an undefined value at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm line 122." (captiveportal::PacketFence::Controller::Root::end)

Here is the output you requested. 

Jun 14 16:11:52 pfqueue(27076) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:11:55 pfqueue(27074) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:11:55 pfqueue(27075) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:11:57 pfqueue(27078) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:13:35 pfqueue(27080) ERROR: [mac:90:68:c3:4c:6d:f1] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT me.id, me.dhcp_fingerprint_id, me.dhcp6_fingerprint_id, me.user_agent_id, me.created_at, me.updated_at, me.device_id, me.version, me.dhcp_vendor_id, me.dhcp6_enterprise_id, me.score, me.mac_vendor_id, me.submitter_id FROM combination me WHERE ( id = ? )"] at /usr/local/pf/lib/fingerbank/Source/LocalDB.pm line 232
Jun 14 16:13:45 pfqueue(27081) ERROR: [mac:10:93:e9:5d:da:d0] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM mac_vendor me WHERE ( mac = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:14:29 pfqueue(27078) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:16:00 pfqueue(27081) ERROR: [mac:90:68:c3:4c:6d:f1] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT me.id, me.dhcp_fingerprint_id, me.dhcp6_fingerprint_id, me.user_agent_id, me.created_at, me.updated_at, me.device_id, me.version, me.dhcp_vendor_id, me.dhcp6_enterprise_id, me.score, me.mac_vendor_id, me.submitter_id FROM combination me WHERE ( id = ? )"] at /usr/local/pf/lib/fingerbank/Source/LocalDB.pm line 232
Jun 14 16:16:15 pfqueue(27080) ERROR: [mac:10:93:e9:5d:da:d0] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM mac_vendor me WHERE ( mac = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:16:25 pfqueue(27081) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
Jun 14 16:18:24 pfqueue(27079) ERROR: [mac:90:68:c3:4c:6d:f1] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT me.id, me.dhcp_fingerprint_id, me.dhcp6_fingerprint_id, me.user_agent_id, me.created_at, me.updated_at, me.device_id, me.version, me.dhcp_vendor_id, me.dhcp6_enterprise_id, me.score, me.mac_vendor_id, me.submitter_id FROM combination me WHERE ( id = ? )"] at /usr/local/pf/lib/fingerbank/Source/LocalDB.pm line 232
Jun 14 16:18:30 pfqueue(27080) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369

Here is the output you requested:

SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> SELECT COUNT(*) FROM device me WHERE (name is NULL)
   ...> ;
Error: database disk image is malformed

SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> 
sqlite> SELECT COUNT(*) FROM device me WHERE ( name IS NULL )
   ...> ;
0
sqlite> 

## here is a sample of pfqueue.log 

pfqueue.log:Jun 14 16:16:25 pfqueue(27081) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
pfqueue.log:Jun 14 16:18:24 pfqueue(27079) ERROR: [mac:90:68:c3:4c:6d:f1] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT me.id, me.dhcp_fingerprint_id, me.dhcp6_fingerprint_id, me.user_agent_id, me.created_at, me.updated_at, me.device_id, me.version, me.dhcp_vendor_id, me.dhcp6_enterprise_id, me.score, me.mac_vendor_id, me.submitter_id FROM combination me WHERE ( id = ? )"] at /usr/local/pf/lib/fingerbank/Source/LocalDB.pm line 232
pfqueue.log:Jun 14 16:18:30 pfqueue(27080) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
pfqueue.log:Jun 14 16:18:45 pfqueue(27081) ERROR: [mac:10:93:e9:5d:da:d0] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM mac_vendor me WHERE ( mac = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
pfqueue.log:Jun 14 16:20:25 pfqueue(27079) ERROR: [mac:84:3a:4b:8e:92:40] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM dhcp_fingerprint me WHERE ( value = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369
pfqueue.log:Jun 14 16:20:49 pfqueue(27079) ERROR: [mac:90:68:c3:4c:6d:f1] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT me.id, me.dhcp_fingerprint_id, me.dhcp6_fingerprint_id, me.user_agent_id, me.created_at, me.updated_at, me.device_id, me.version, me.dhcp_vendor_id, me.dhcp6_enterprise_id, me.score, me.mac_vendor_id, me.submitter_id FROM combination me WHERE ( id = ? )"] at /usr/local/pf/lib/fingerbank/Source/LocalDB.pm line 232
pfqueue.log:Jun 14 16:21:16 pfqueue(27078) ERROR: [mac:10:93:e9:5d:da:d0] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( \* ) FROM mac_vendor me WHERE ( mac = ? )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369

There is nothing really in pfmon.log - 

Just this: 

') (pf::iplog::rotate)
Jun 14 16:23:44 pfmon(27154) INFO: getting violations triggers for accounting cleanup (pf::accounting::acct_maintenance)
Jun 14 16:23:44 pfmon(27154) INFO: processed 0 violations during violation maintenance (1465935824.66199 1465935824.66288)  (pf::violation::violation_maintenance)
Jun 14 16:23:45 pfmon(27154) INFO: Rotated '4' entries from iplog_history to iplog_archive (start: '1465935825', end: '1465935825') (pf::iplog::rotate)

**Comment by piellick** [comment]
hi, yes database problem :+1: 

```
 sqlite3 /usr/local/fingerbank/db/fingerbank_Local.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> SELECT COUNT( * ) FROM device me WHERE ( name IS NULL );
0
```

```
qlite3 /usr/local/fingerbank/db/fingerbank_Upstream.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> SELECT COUNT( * ) FROM device me WHERE ( name IS NULL );
Error: database disk image is malformed
```

```
grep 'database disk image is malformed' /usr/local/pf/logs/packetfence.log
Jun 15 09:43:31 httpd.portal(5289) ERROR: [mac:38:59:f9:14:62:37] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: database disk image is malformed [for Statement "SELECT COUNT( * ) FROM device me WHERE ( name IS NULL )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 369

```

My pfmon.log => http://pastebin.com/sxvTh4Ms

**Comment by rbm108** [comment]
I also encounter the same error. It occurs on redirection to the captive portal. I found that refreshing the page usually fixes it (at which point the registration continues without a hitch). The problem with refreshing is, that it's not always possible, as the redirect/registration often pops up in a separate wrapper window, that doesn't have any buttons (and doesn't take Cmd+R/F5).

I'd be most grateful for a fix or a workaround.

**Comment by julsemaan** [comment]
Alright, so it seems the DB image in the fingerbank package would be bad since I can't find you in the fingerbank users.

Could you confirm that you did not configure a Fingerbank key in PacketFence by checking that /usr/local/fingerbank/conf/fingerbank.conf is empty.

My current wild guess is that the database inside the Debian package is corrupted.

Provide the output of the following : 
`# dpkg -l | grep fingerbank`

Now, to try to fix this.
In PacketFence, go in 'Configuration -> Fingerbank/Settings'
Follow the onboarding procedure (works with your Github account) and configure your key in PacketFence.
When you configured your key, go back into 'Configuration -> Fingerbank/Settings' and at the top of the page click 'Update Fingerbank DB'. Wait for it to complete (you'll receive an e-mail confirming it) and make sure it succeeded.

Now, test a query again and make sure it succeeds:
sqlite3 /usr/local/fingerbank/db/fingerbank_Upstream.db
`SELECT COUNT( * ) FROM device me WHERE ( name IS NULL )`

If the above worked than we are on the right way to solve your issue. For good measure and to make sure everything is cleaned, we will clear the Fingerbank cache + restart the processes that use it.

```
# /usr/local/pf/bin/pfcmd cache fingerbank clear
# /usr/local/pf/bin/pfcmd service httpd.portal restart
# /usr/local/pf/bin/pfcmd service pfqueue restart
```

@rbm108 - same thing should be applicable for you as well if you are running Debian. Otherwise I'm not on the right track to fix the issue you're having

**Comment by riban** [comment]
fingerbank.conf is empty. (We don't use it yet)

dpkg -l | grep fingerbank 
ii  fingerbank                                               2.2.1-1                    all          fingerbank

When I did what you suggested my query returned with '0' this time instead of invalid. 

Do I need to keep fingerbank? am I able to deconfigure it now? It would be a preference to not have it setup since it requires personal accounts to maintain.

**Comment by riban** [comment]
Sorry I should make it clear what you suggested worked, after adding finger bank api and updating the db.

**Comment by rbm108** [comment]
I signed up to Fingerbank, configured the key, updated DB and the world is a happy place again. Thanks for the speedy response!

**Comment by julsemaan** [comment]
@rbm108 and @riban  - do you use Debian ? If so, is it 7 or 8 ?

**Comment by piellick** [comment]
i will do same ...i'am on Debian8u5

**Comment by rbm108** [comment]
Julien, I'm on Debian 8.5

**Comment by julsemaan** [comment]
@fdurand 

Seems to be extremelly likely the database is corrupted in the Debian 8 package

Could you repackage fingerbank-2.2.1 and push it to the Debian repo

**Comment by piellick** [comment]
I click to "update  fingerbank DB but nothing ...except :

`Jun 15 17:06:55 httpd.webservices(1634) INFO: [mac:unknown] Sending fingerbank component update to local queue. (pf::api::fingerbank_update_component)`

It's possible to run the update over CLI to débug ?

on web interface i have "Succès ! La requête de mise à jour pour Fingerbank a été correctement envoyée à la BD source. Un courriel sera envoyé concernant le status" .....it's sending to my email from github account ? I Receipts nothing.

**Comment by rbm108** [comment]
I received an email when the update finished:

Successfully updated file '/usr/local/fingerbank/db/fingerbank_Upstream.db'

**Comment by julsemaan** [comment]
It would be possible that your queue workers are dead or something is going wrong.

Check /usr/local/pf/logs/pfqueue.log for any errors and that pfqueue is alive

You can run it manually using the following : 

```
# cd /usr/local/fingerbank
# make init-db-upstream
```

Then enter your key when prompted. It will take a few minutes to complete.

**Comment by julsemaan** [comment]
You can also check /usr/local/fingerbank/logs/fingerbank.log for errors

**Comment by riban** [comment]
I'm on deb 8 as well.

**Comment by piellick** [comment]
it's work, after 5minutes ... no message no information on CLI ..but it's work  :)

**Comment by julsemaan** [comment]
@piellick - perfect !

@fdurand has fixed the issue on the packaging side so this issue does not re-occur again.

Closing
