### ISSUE TITLE
violation cannot apply tp users

### ISSUE THREAD

**Issue by asoufiane** [inverse-inc/packetfence#1544]
Hi,

When i create the violation to check the firewall if enabled or not, he can't automatically assigned to user, and violation cannot detect if the firewall is enabled or not.
Any idea please

**Comment by louismunro** [comment]
Here's one: please use the mailing list.
The issues are for known bugs.

**Comment by asoufiane** [comment]
can you please share with me the mailing list to view if The issues are for known bugs.
For information i have the version 6.0.1
