### ISSUE TITLE
Provide OAuth support for Instagram, Snapchat and Pinterest

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#1548]
OAuth might not be relevant for all (like Snapchat), but you get the idea!

**Comment by julsemaan** [comment]
Snapshat login using naughty pictures (sent to lzammit@inverse.ca)
Instagram could be a picture of your diner (turkey sandwich grants you more time)

**Comment by extrafu** [comment]
Epic.

**Comment by jrouzierinverse** [comment]
Snapchat has no oauth api.

https://www.instagram.com/developer/authentication/

https://developers.pinterest.com/docs/getting-started/introduction/

**Comment by dwlfrth** [comment]
Develop one

**Comment by jrouzierinverse** [comment]
Uhhhh no!

**Comment by julsemaan** [comment]
This was done and merged.
