### ISSUE TITLE
Do not autoload Module Pluggable at startup

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1556]
To reduce the time to start run pfcmd.
Delay the autoloading of Module Pluggable until the modules are needed.

**Comment by jrouzierinverse** [comment]
Related to #1553

**Comment by julsemaan** [comment]
@jrouzierinverse 

What should we do about this ?
Close, or assign it a milestone ?

**Comment by jrouzierinverse** [comment]
This is no longer needed since we addressed it the httpd.admin startup issue.
