### ISSUE TITLE
WLC & Violation

### ISSUE THREAD

**Issue by riban** [inverse-inc/packetfence#1562]
When a violation is triggered or manually applied (via nodes configuration page) packetfence reports it applies the ACL (according to the guide Isolation_Access_Only). However the WLC does not either receive this message or apply the ACL. 

Here is the log info from packetfence 

Jun 15 11:43:07 httpd.aaa(31270) INFO: [mac:84:3a:4b:8e:92:40](10.4.0.17) Added role Isolation_Access_Only to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)

Here is the WLC in debug mode: 

http://pastebin.com/jXiBVTQ8

**Comment by riban** [comment]
This maybe of some use. 

When a user first connects to the captive portal the ACL and URL redirect works. Here is what the radius server sends to the WLC. 

(10)   Cisco-AVPair += "url-redirect-acl=Pre-Auth-For-WebRedirect"
(10)   Cisco-AVPair += "url-redirect=https://domain.com/cepc09f2e"

Here is what happens after registration 
Airespace-ACL-Name = "Authorize_any"
(5)   Airespace-ACL-Name = "Isolation_Access_Only"

Authorize_any & Isolation_Access_Only do not work as they do not get applied. Also if a violation is triggered or applied the URL redirect is also not supplied to the WLC via radius. For example the p2p.html page if a p2p file sharing trigger happens.

**Comment by julsemaan** [comment]
This seems like a configuration issue.

Please use the mailing list to discuss this

Re-open should we discover its a real bug
