### ISSUE TITLE
Unregister the fake mac before going to the portal preview

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1569]

**Comment by julsemaan** [comment]
Not sure we should unregister it unconditionally as this might cause issues when testing violations for example.

Also not sure about the relevance of doing this, I like the fake MAC behaving like a real device, that helps testing things from here when doing a deployment.

My 2 cents.

**Comment by julsemaan** [comment]
We should "officially" state on what we want to do for this

**Comment by jrouzierinverse** [comment]
I think we should close this issue

**Comment by julsemaan** [comment]
I think I agree
