### ISSUE TITLE
"Cluster state" messes up pid files

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#1587]
I've recently upgraded from 6.0 to 6.1.1 (Debian 8). Packetfence starts fine, `pfcmd service pf status` shows all services as green and orange.

When I open the "Cluster state" page in the backend, almost all services (except carbon-_, radiusd_, redis_queue) are shown as "stopped". The services are all still running though. `pfcmd` now shows a lot of red services as well and trying to restart them produces a lot of errors due to already used sockets.

**Comment by julsemaan** [comment]
Wow, that is weird since that page uses the exact same logic as pf status...

Can you tell us if it 'breaks' the PID files on all servers or on specific ones ?

**Comment by tribut** [comment]
After opening the page, I get lots of red in `pfcmd service pf status` on both nodes.

**Comment by julsemaan** [comment]
Patch made and cherry-picked to maintenance/6.1

Can you apply the patch manually or run `/usr/local/pf/addons/pf-maint.pl` and confirm it fully fixed it.

Opened #1589 for the underlying issue of this.

**Comment by tribut** [comment]
After applying 395ed7da90b250ae663616ddf940e16efd952fe4 I cannot reproduce the issue. Thanks.
