### ISSUE TITLE
Cisco Switch Documentation Update

### ISSUE THREAD

**Issue by eriroley** [inverse-inc/packetfence#1588]
In my testing, I determined that some critical information was missing from the documentation as it relates to implementation on cisco switches.
This was tested on a C3560 switch running SW Version 12.2(55)SE4

Problem encountered: when disconnecting a registered device and then connecting another device _to the same port_ within a short period of time (Assumed to be within the authentication timer period) the port immediately was put into an error-disable state because of a switch-level security violation.
The following (sanitised) can be seen in the syslog output of the switch:
`%AUTHMGR-5-SECURITY_VIOLATION: Security violation on the interface FastEthernet0/5, new MAC address (MACADDRESS) is seen.AuditSessionID  Unassigned
%PM-4-ERR_DISABLE: security-violation error detected on Fa0/5, putting Fa0/5 in err-disable state`

Resolution: Add the following line to each port config:
`authentication violation replace`

Associated Cisco Documentation can be found at http://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3560/software/release/12-2_55_se/command/reference/3560_cr/cli1.html#wp11888832

**Comment by julsemaan** [comment]
Seems like you are right IMO.

Unless someone steps in with arguments against it, I'll change it in our official docs
