### ISSUE TITLE
Weird content of "switch mac"

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#1591]
![screenshot from 2016-06-29 19-32-18](https://cloud.githubusercontent.com/assets/719105/16462216/82bae1c6-3e30-11e6-98a1-0318282e8f90.png)

My guess is this is the output of gettext("").

Packetfence 6.1.1 on Debian 8.

**Comment by julsemaan** [comment]
Your guess seems to be right.

Will look into it

**Comment by tribut** [comment]
Fixed by 4988fb36137718f4ba37b38efa297dfb5a0a78ae
