### ISSUE TITLE
pfdetect queue: Do not start if pfdetect is not started

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1593]
Do we really need to spawn a (or whatever configured number of) pfqueue for pfdetect if pfdetect is not running ?

**Comment by julsemaan** [comment]
+1

**Comment by jrouzierinverse** [comment]
This can be done however if pfdetect goes from disabled -> enabled or enabled -> disabled, pfqueue must be restarted to ensure the pfdetect worker is started or stopped.
If that is ok then yes this can be done quickly.
If not then I would need to add some type of polling to the pfqueue master to pickup on configuration changes.

**Comment by julsemaan** [comment]
I'd say it would be OK for pfqueue to be restarted, it should use the isManaged sub of pfdetect since it contains custom logic. And we need to document the pfqueue restart in the admin guide in places where we enable pfdetect

**Comment by dwlfrth** [comment]
As @julsemaan says...
Also, on pfdetect parsers configuration, pfdetect needs to be restarted...
