### ISSUE TITLE
Packetfence cannot start, apache2 xml2enc_module is missing

### ISSUE THREAD

**Issue by kdeb881** [inverse-inc/packetfence#1595]
Hi!
I tried to install the packetfence but i stucked here:

$> service packetfence restart
apache2: Syntax error on line 31 of /usr/local/pf/var/conf/httpd.conf.d/httpd.admin: Cannot load /usr/lib/apache2/modules/mod_xml2enc.so into server: /usr/lib/apache2/modules/mod_xml2enc.so: cannot open shared object file: No such file or directory

$> cat /etc/debian_version
7.11

$> dpkg --list | grep -i apache2

ii  apache2                                         2.2.22-13+deb7u6
ii  apache2-mpm-prefork                             2.2.22-13+deb7u6
ii  apache2-prefork-dev                             2.2.22-13+deb7u6
ii  apache2-utils                                   2.2.22-13+deb7u6
ii  apache2.2-bin                                   2.2.22-13+deb7u6
ii  apache2.2-common                                2.2.22-13+deb7u6
ii  libapache2-mod-apreq2                           2.13-1+b2
ii  libapache2-mod-evasive                          1.10.1-1
ii  libapache2-mod-perl2                            2.0.7-3
ii  libapache2-mod-proxy-html                       3.0.1-1.1
ii  libapache2-mod-qos                              10.8-1
ii  libapache2-mod-wsgi                             3.3-4+deb7u1
ii  libapache2-reload-perl                          0.12-1
ii  libapache2-request-perl                         2.13-1+b2

Any solution for this?

**Comment by extrafu** [comment]
Yes, use the mailing list for such questions.
