### ISSUE TITLE
A violation can be created with an impossible metadefender trigger id

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1601]
All values are discreet and proposed through dropdown menu.
"Enter the trigger ID" box should be hidden in that specific case.

**Comment by dwlfrth** [comment]
- html/pfappserver/root/violation/view.tt
- html/pfappserver/root/static/admin/config/violation.js

**Comment by julsemaan** [comment]
Not sure it should be hidden. Our usual mentality (good or not?) is to allow advanced configuration for the user. This way, should another trigger ID be available it can be used without touching the codebase or upgrading to a newer version that has it.

My 2 cents

**Comment by dwlfrth** [comment]
Need to add validation to triggers in PacketFence (globally)

**Comment by julsemaan** [comment]
We can address this with the violations rework

**Comment by extrafu** [comment]
Closing that issue, Metadefender Cloud is set to be removed.
