### ISSUE TITLE
Admin: Refreshing the node page clears the search widgets

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1622]
When the page loads it defaults to 'Node MAC', then I selected 'VoIP' and the widget gets put there properly.

![image](https://cloud.githubusercontent.com/assets/3857942/16850728/7b6af588-49ce-11e6-8f5f-7e8b00710e9a.png)

Then, refreshing the page resets the widget to a text field

![image](https://cloud.githubusercontent.com/assets/3857942/16850743/88250fde-49ce-11e6-8943-5a1d4f4eb1a7.png)

It should either put the right widget there or go back to 'Node MAC'

**Comment by jrouzierinverse** [comment]
Unable to replicate please provide additional details

**Comment by julsemaan** [comment]
Not sure how I can explain it any other way than it is in the issue.

Come by ZammitCorp and I'll show you

**Comment by jrouzierinverse** [comment]
It looks like it is happening only on your browser/os combo.

**Comment by julsemaan** [comment]
You're right.

Happening on Firefox on Ubuntu.
Was able to have @ziceo replicate it in Firefox on Mac OSX
I would assume Firefox on Windows also does that

Question would be, do we want to have a JS hack for that only for that browser.

**Comment by jrouzierinverse** [comment]
Yes because if change the first field being displayed all browser will have this behavior.
