### ISSUE TITLE
LDAP TLS is broken

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1624]
Looks like TLS support broke at some point.

On CentOS 6, running 6.2.1 LDAP sources configured with STARTSSL fail all requests with : 

```
Jul 15 09:39:29 pftest(8263) ERROR: [ldapX] TLS already started (pf::Authentication::Source::LDAPSource::_connect)
```

**Comment by jrouzierinverse** [comment]
connection caching.

**Comment by louismunro** [comment]
I suspected that. 
We'll have to work around it somehow.

**Comment by julsemaan** [comment]
maintenance ?

**Comment by louismunro** [comment]
It definitely should be in maintenance, for all of the 6.x releases.
