### ISSUE TITLE
p0f does not start

### ISSUE THREAD

**Issue by ghost** [inverse-inc/packetfence#1628]
Hi, 
I have just finished installing PacketFence with the "Configurator" web page (the configuration is clean, I did not manually edit the configuration files). But on the last page, when I clicked on "Start PacketFence", all the services start except p0f. 
When I do "/usr/local/pf/bin/pfcmd service p0f start" in command line, I have this result: 

```
Checking configuration sanity...
[-] PROGRAM ABORT : Unexpected statement in line 1.
Location : config_parse_line(), readfp.c:308
p0f|not started
```

The error would come from the file "readfp.c" from p0f package, which is started by the "p0f.pm" file in PF (if I'm not mistaken).

I use PacketFence 6.2.1 on Debian 8.5 Jessie, the version of p0f is the inverse.ca repository version (3.06b-2 0)

**Comment by julsemaan** [comment]
Please provide the content of :
`/usr/local/fingerbank/conf/fingerbank-p0f.fp`

Also the output of the following : 
`dpkg -l | grep fingerbank`

**Comment by ghost** [comment]
```
> cat /usr/local/fingerbank/conf/fingerbank-p0f.fp
Invalid key

> dpkg -l | grep fingerbank
ii  fingerbank                                               2.2.2-1                              all          fingerbank

```

**Comment by ghost** [comment]
I apologize I just figured it was a mistake on my part. I wrote the wrong Fingerbank API key during the install. 
Thanks anyway.

**Comment by julsemaan** [comment]
No problem,

I'll still open the bug on fingerbank as on failure it shouldn't have touched the existing file
