### ISSUE TITLE
radiusd service manager reads all switches

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1629]
In order to detect whether or not a CLI radiusd process should be started, the service manager goes through all the switches. In a 5000 switches environment that can take ~30-40 seconds.

This is also called when doing the status which makes the status last almost a minute (sometimes more when system is loaded)

We need to either : 
1. Make the CLI access service start depend on a flag in pf.conf services
2. Pre-load all switches from pfconfig in the manager (will save the cost of 5000 communications through the socket)
3. Not look at the MAC addresses while searching for the condition of starting the radiusd-cli process

**Comment by julsemaan** [comment]
Option 2 was selected as it took a non-noticeable time to preload them all

**Comment by jrouzierinverse** [comment]
If the speed is still not enough.
Another option is to calculate this is in a child of pfconfig::namespaces::config::Switch.
So this would be only calculated once and you reduce the IO talking to pfconfig.
