### ISSUE TITLE
pvsetvlan typo "swicth"

### ISSUE THREAD

**Issue by mcide** [inverse-inc/packetfence#1630]
PF ZEN 6.2.1 

/usr/local/pf/sbin/pfsetvlan
Line 1117:

my $role =  $role_obj->fetchRoleForNode({mac => $mac, node_info => node_attributes($mac), **swicth** => $switch, ifIndex => $switch_port, connection_type => $WIRED_SNMP_TRAPS, profile => pf::Portal::ProfileFactory->instantiate($mac)});

This typo cause errors in /usr/local/pf/lib/pf/role.pm :
if( $args->{'switch'}->supportsMABFloatingDevices .....

**Comment by jrouzierinverse** [comment]
Thank you for reporting this.
If you have not fixed it already in your install.
You can do so by apply the patch using the following commands.

```
cd /usr/local/pf
curl 
https://github.com/inverse-inc/packetfence/commit/ee4937dda0c38f0287e087a2763b09c82794ca6e.diff > ee4937dda0c38f0287e087a2763b09c82794ca6e.diff

patch -p1 < ee4937dda0c38f0287e087a2763b09c82794ca6e.diff

```

**Comment by julsemaan** [comment]
Required in maintenance ?

**Comment by dwlfrth** [comment]
Reclosing since have been added to maintenance branches
