### ISSUE TITLE
Traffic logging of authenticated users?

### ISSUE THREAD

**Issue by information-security** [inverse-inc/packetfence#1636]
I'm new to pf so pardon me if I'm misunderstanding something.
I just recently setup PF Zen in inline mode on VMs. I'd like to have user traffic being logged in a format like below preferably in a database rather than log files.

username, Src_addr (NAT address if applicable), dst_addr, URL(if applicable),protocol (udp, tcp), DateTime,duration, up (traffic uploaded), down (traffic downloaded)

Above formatting is mostly for knowing what user accessed what destination ip/url in what date&time. I couldn't find anywhere in UI and in code to configure pf for this purpose so I thought to ask it here before start coding it. If you guys don't have this logging already developed or in development please direct me to the correct module that is needed to be modified.

Thanks

**Comment by extrafu** [comment]
Please use the mailing list for such questions. Thanks!
