### ISSUE TITLE
deltarpm support in packetfence repositories

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1649]
Supporting deltarpm in the creation of repositories could save tremendous amount of bandwidth. I'm thinking more precisely for fingerbank packages, which are ~133mb.

Note that main repositories support this feature, which can reduce download time and size by up to 80%.

More information here:https://github.com/rpm-software-management/createrepo_c/wiki/dprms

**Comment by tlaurion** [comment]
@louismunro : Would that make sense to create deltarpm at release time?

**Comment by louismunro** [comment]
closed won't fix.
I have no interest in fixing this.
We should rather fix fingerbank if that is the real issue.

**Comment by tlaurion** [comment]
The interest was in reducing bandwidth requirements while leveraging a little higher disk IO to reassemble the packets from binaries differences. It is possible to activate this easily for CentOS by installing deltarpm. 

The thing is that this possibility is not offered through our repositories. I understand that it is not a current need.

**Comment by julsemaan** [comment]
It would be nice for Fingerbank packages though. Let's see how that can integrate with its packaging.

Opened issue in Fingerbank perl client repo:
https://github.com/fingerbank/perl-client/issues/27
