### ISSUE TITLE
inline: ipset traffic shaping set is being removed on dhcp release

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1651]
Have a node with a PF-iL2_IDx set assigned, renew the node dhcp lease, the PF-iL2_IDx set is no longer assigned.

**Comment by julsemaan** [comment]
@fdurand 

Could we look into this and see if its still accurate with pfdhcp and pfipset

**Comment by julsemaan** [comment]
@fdurand confirmed this is working fine now

**Comment by fdurand** [comment]
Didn't see this issue with my latest inline test
