### ISSUE TITLE
Broken link on packetfence.org

### ISSUE THREAD

**Issue by connection-reset** [inverse-inc/packetfence#1657]
Hi,

on your [Community Support](https://packetfence.org/support/index.html#/community) page is a link to the FAQ further down in the sentence "consult the FAQ for previously answered questions". That link points to https://packetfence.org/support/english/nc/support/faq.html which does not exist:

```

TYPO3 logo
Page Not Found

Reason: Segment "english" was not a keyword for a postVarSet as expected on page with id=498.
TYPO3 is an open source content management system. To maintain the quality of the system and to improve it, please help us by donating. TYPO3 CMS. Copyright © 1998-2011 Kasper Skårhøj. Extensions are copyright of their respective owners. Go to http://typo3.com/ for details. TYPO3 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions. Obstructing the appearance of this notice is prohibited by law.
```

The link in the menu points to https://packetfence.org/support/faq.html and works fine.

**Comment by julsemaan** [comment]
@cgx 

I'm not a big pro of TYPO3 and would likely put our whole site down if I even start thinking of changing a link in a page :)

Can you adjust the link. I just tested this issue and its still there

**Comment by cgx** [comment]
Done. Thanks!
