### ISSUE TITLE
CentOS 7: joining domain is not working properly. Realmd?

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1661]
From the GUI, joining the domain deson't finish properly. (loading line fills and then nothing happens)

/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:20:13 httpd.admin(30994) INFO: Memory configuration is not valid anymore for key config::Domain in local cached_hash (pfconfig::cached::is_valid)
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:22:20 httpd.admin(30994) INFO: domain join : Failed to join domain: failed to lookup DC info for domain 'inverse.local' over rpc: {Device Timeout} The specified I/O operation on %hs was not completed before the time-out period expired.
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:23:45 httpd.admin(30994) INFO: Hard expiring resource : config::Domain (pfconfig::manager::expire)
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:23:45 httpd.admin(30994) INFO: Expiring child resource resource::domain_dns_servers. Master resource is config::Domain (pfconfig::manager::expire)
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:23:45 httpd.admin(30994) INFO: Hard expiring resource : resource::domain_dns_servers (pfconfig::manager::expire)
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:21:14 httpd.admin(21876) INFO: Memory configuration is not valid anymore for key config::Domain in local cached_hash (pfconfig::cached::is_valid)
/usr/local/pf/logs/httpd.admin.log-20160817.gz:Aug 16 11:23:21 httpd.admin(21876) INFO: domain join : Failed to join domain: failed to lookup DC info for domain 'inverse.local' over rpc: The remote network is not reachable by the transport.

/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:11 pfcmd.pl(31264) INFO: Expiring child resource resource::domain_dns_servers. Master resource is config::Domain (pfconfig::manager::expire)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:11 pfcmd.pl(31264) INFO: Hard expiring resource : resource::domain_dns_servers (pfconfig::manager::expire)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:11 pfcmd.pl(31262) INFO: Memory configuration is not valid anymore for key config::Domain (pfconfig::manager::is_valid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:11 pfcmd.pl(31264) INFO: Memory configuration is not valid anymore for key config::Domain in local cached_hash (pfconfig::cached::is_valid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:11 pfcmd.pl(31262) INFO: Memory configuration is not valid anymore for key config::Domain in local cached_hash (pfconfig::cached::is_valid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31262) WARN: Problem trying to run command: LANG=C sudo ip netns add INVERSE called from manager::winbindd_child::build_namespaces. Child exited with non-zero value 1 (pf::util::pf_run)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31262) WARN: Problem trying to run command: LANG=C sudo ip link add INVERSE-a type veth peer name INVERSE-b called from manager::winbindd_child::build_namespaces. Child exited with non-zero value 2 (pf::util::pf_run)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31262) WARN: Problem trying to run command: LANG=C sudo ip link set INVERSE-a netns INVERSE called from manager::winbindd_child::build_namespaces. Child exited with non-zero value 1 (pf::util::pf_run)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31262) WARN: Problem trying to run command: LANG=C sudo ip netns exec INVERSE route add default gw 169.254.0.2 dev INVERSE-a called from manager::winbindd_child::build_namespaces. Child exited with non-zero value 7 (pf::util::pf_run)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31264) INFO: Daemon winbindd-INVERSE.conf took 0.106 seconds to start. (pf::services::manager::launchService)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:12 pfcmd.pl(31262) INFO: Daemon winbindd-INVERSE.conf took 0.117 seconds to start. (pf::services::manager::launchService)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:46 httpd.portal(31306) INFO: [mac:[undef]] Memory configuration is not valid anymore for key config::Pf in local cached_hash (pfconfig::cached::is_valid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:46 httpd.portal(31306) INFO: [mac:[undef]] Instantiate a new iptables modification method. pf::ipset (pf::inline::get_technique)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:48 httpd.portal(29909) INFO: [mac:[undef]] Instantiate a new iptables modification method. pf::ipset (pf::inline::get_technique)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:20:48 httpd.portal(29909) INFO: [mac:[undef]] Instantiate a new iptables modification method. pf::ipset (pf::inline::get_technique)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:21:12 pfcmd.pl(31264) WARN: winbindd-INVERSE.conf timed out trying to start (pf::services::manager::postStartCleanup)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:26 pfcmd.pl(31511) INFO: pidof -x winbindd-INVERSE.conf returned 31451 (pf::services::manager::pidFromFile)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:26 pfcmd.pl(31511) INFO: verifying process 31451 (pf::services::manager::removeStalePid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:26 pfcmd.pl(31511) INFO: pidof -x winbindd-INVERSE.conf returned 31451 (pf::services::manager::pidFromFile)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) WARN: Problem trying to run command: LANG=C sudo kill -0 31451 >/dev/null 2>&1 called from (eval). Child exited with non-zero value 1 (pf::util::pf_run)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: removing stale pid file /usr/local/pf/var/run/INVERSE/winbindd.pid (pf::services::manager::removeStalePid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: pidof -x httpd.admin returned 21875 (pf::services::manager::pidFromFile)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: verifying process 21875 (pf::services::manager::removeStalePid)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: pidof -x httpd.admin returned 21875 (pf::services::manager::pidFromFile)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: pidof -x httpd.admin returned 21875 (pf::services::manager::pidFromFile)
/usr/local/pf/logs/packetfence.log-20160817.gz:Aug 16 11:22:27 pfcmd.pl(31511) INFO: Instantiate profile default (pf::Portal::ProfileFactory::_from_profile)

Joining domain with realm suite worked out of the box (not in chroot though)
yum install realmd
realm join INVERSE.local -U administrator --client-software=winbind

Should we go in that direction?

**Comment by whitx** [comment]
+1 this issue happens a lot while joining RHEL7 machines to a domain, using realmd seems the way to go, as long as we can still do multi domains

**Comment by julsemaan** [comment]
@bigzaym got the same issue on CentOS 7

Adding proper labels

**Comment by dariuskoissi** [comment]
j'ai le meme probleme sur centos 7

**Comment by HeroesLament** [comment]
I'm getting almost this exact same error, I think due to the netns provisioning. For clarification, fiberfarm is my local domain, and 172.16.0.10 is the domain controller. 

[root@packetfence01 ~]# ip netns exec fiberfarm ping 172.16.0.10
PING 172.16.0.10 (172.16.0.10) 56(84) bytes of data.
^C
--- 172.16.0.10 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

[root@packetfence01 ~]#

I'm not SUPER familiar with network namespaces, but something seems wrong here.

**Comment by lzammit** [comment]
It must be a configuration issue.

Which PF version are you running ?

Thanks,
