### ISSUE TITLE
Cisco WLC: Handle failover of primary WLC for MAC based switches

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1665]
Since in a cluster of WLC, there is no VIP configured, when we configure the controllerIp for MAC based switches in PacketFence, if the main WLC fails, the Disconnect messages are lost.

If we remove the controllerIp, the code is not smart enough to find the WLC that is currently associated to the AP (latest RADIUS request received / locationlog info)

When dealing with a MAC based switch configuration and there is no controllerIp defined, we should look at the locationlog to find the controller IP address

**Comment by extrafu** [comment]
Out of curiosity, why not always use the info from the location log? Too slow? If we can avoid the OP in specifying parameters he shouldn't have to with no performance downside, let's opt in for this approach.

**Comment by julsemaan** [comment]
I also think we should use the locationlog info as well while still honoring the controllerIp if there.

Makes no sense to send a deauthentication to a MAC address...

**Comment by julsemaan** [comment]
Seems that the switch overlay in the SwitchFactory should be handling that issue but from what I saw it only populates upon receiving a RADIUS request from that AP and isn't retroactive after you remove controllerIp from an AP config.

Will test that theory but looks like it shouldn't be necessary to do that, we just need to be aware that removing a controllerIp from the configuration requires a new RADIUS request to happen for the controller to be properly detected

**Comment by julsemaan** [comment]
Switch overlay will handle that case.
