### ISSUE TITLE
pfcmd node add not working and no error

### ISSUE THREAD

**Issue by ccaaajf** [inverse-inc/packetfence#1677]
If I use "pfcmd node add" with a pid of an new user the add command fails silently. This should at least produce an error.

Packetfence version 6.2.1

Cheers Andy

**Comment by jrouzierinverse** [comment]
Can you provide an example command?
Also is there any errors in the /usr/local/pf/logs/packetfence.log

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by ccaaajf** [comment]
Hi James,

Thanks for the quick response.

Command was:
`/usr/local/pf/bin/pfcmd node add C8:FF:28:B5:BB:67 status="unreg" pid="no_user" computername="TEST"`

no_user doesn't exist but the command line doesn't complain or error.

Error in /usr/local/pf/logs/packetfence.log:
`Aug 26 23:04:38 pfcmd.pl(11548) INFO: database query failed with: Cannot add or update a child row: a foreign key constraint fails (`pf`.`node`, CONSTRAINT`0_57`FOREIGN KEY (`pid`) REFERENCES`person`(`pid`) ON DELETE CASCADE ON UPDATE CASCADE) (errno: 1452) (pf::db::db_query_execute)`

Cheers Andy.

**Comment by jrouzierinverse** [comment]
Thanks Andy I will look into this.

**Comment by jrouzierinverse** [comment]
You apply the patch by doing the following.

```
cd /usr/local/pf

curl https://github.com/inverse-inc/packetfence/commit/f531141.diff> f531141.diff

patch -p1 f531141.diff

```

**Comment by jrouzierinverse** [comment]
This is in maintenance
