### ISSUE TITLE
Advanced profile filter has 2 fields to fill

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1678]
![advanced](https://cloud.githubusercontent.com/assets/9321079/18056770/53ff1f8e-6ddb-11e6-9fe2-787671d2959f.png)

**Comment by whitx** [comment]
Bump still on devel

**Comment by jrouzierinverse** [comment]
Fixed in 12e7e47c50570c4880802aa7f84bc885743eb223
