### ISSUE TITLE
Admin nodes: Provide entries count when performing search

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1683]
When performing a search or viewing nodes, it would be useful to see the amount of nodes that are currently displayed.

**Comment by brgerig** [comment]
Not currently displayed, but the total number of nodes that match the query. So, although 20 nodes are currently displayed (by default), there could be hundreds that match. Currently the only way (that I know of) to find out how many there are is to click through all of the pages until I get to the last one, or go build the query by hand in the database.

**Comment by jrouzierinverse** [comment]
We removed the total node count since it made displaying the node page very slow.

Can revisit this issue after we move to using SQL::Abstract::More for the query building for the node page

**Comment by dwlfrth** [comment]
ref: 6897

**Comment by julsemaan** [comment]
We'd have to see if we do it in the new admin using the Unified API

Its not in the plans now, but lets state on this after 8.0

**Comment by jrouzierinverse** [comment]
As this is a known performance issue i am closing this.
