### ISSUE TITLE
OpenVAS does not work

### ISSUE THREAD

**Issue by apkt** [inverse-inc/packetfence#1703]
OpenVAS integration is supported however the process fails since the 
OpenVAS-CLI executable 'omp' is either not installed or cannot be installed.
Cannot install OpenVAS-CLI or OpenVAS since there is a dependency conflict with PacketFence WMI

**Comment by tlaurion** [comment]
To reproduce on CentOS7:
wget -q -O - http://www.atomicorp.com/installers/atomic |sh
yum install openvas

```

Error: Package: perl-Net-WMIClient-0.62-0.x86_64 (@packetfence)
           Requires: libasync_wmi_lib.so.0()(64bit)
           Removing: wmi-1.3.14-5.1.x86_64 (@packetfence)
               libasync_wmi_lib.so.0()(64bit)
           Obsoleted By: openvas-smb-1.0.1-0.2.el7.art.x86_64 (atomic)
               Not found
           Available: wmi-1.3.14-4.el7.art.x86_64 (atomic)
               libasync_wmi_lib.so.0()(64bit)

```

**Comment by julsemaan** [comment]
@fdurand 

Anything we can do about this?

**Comment by fdurand** [comment]
We need to get rid of the wmi package.
pfwmi should be the solution to bypass this issue.

**Comment by julsemaan** [comment]
I guess its currently safe to say we can land pfwmi in 8.1 so I'll leave that as-is and we move it if needed

**Comment by becchett** [comment]
Dear Inverse developers,  are there any news about this issue ? 
Are there any other free alternatives ?
Thanks 
Enrico

**Comment by extrafu** [comment]
@becchett Have a look at https://github.com/inverse-inc/packetfence/pull/3814

It'll be included in v8.3 coming up in early January.

**Comment by becchett** [comment]
Dear Extrafu, 
let me tell you if I I hunderstand this issue ... now I've one Centos 7 to run PF 8.2.1 and another virtual m achine with Centos7 for running OpenVas/greenbone. In this scenario may I install some dependencies or I've to wait PF-8.3 ??  
thanks again ... really fast !!
Enrico

**Comment by extrafu** [comment]
I said it's coming in v8.3 so obviously you'll have to wait.

**Comment by becchett** [comment]
In caso of PF and OpenVas  run in two separate servers just to understand, in the PF server will it be necessary to install some Openvas packages ?
In this case, are you planning to update the "installation guide" in the "20.1.2 OpenVAS" section, indicating which ones should be added?
Thanks 
Enrico

**Comment by nqb** [comment]
See the pull request regarding OpenVAS integration : #3814 

The doc will be update.
