### ISSUE TITLE
UPGRADE guide about html/pfappserver/root/admin/configuration.tt

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1712]
There is no instruction that the html/pfappserver/root/admin/configuration.tt has changed, when upgrading, it did not get replaced but moved to a .orig. That cause the EAP method section to not be visible from the admin interface.

**Comment by julsemaan** [comment]
This looks more like a file that was placed there by the maintenance script.

Was this on RHEL or Debian ?
