### ISSUE TITLE
PF 6.3: nodes view shows online/offline status of all devices as unknown

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1714]
Bug:
-All nodes have an "Online/Offline" status  of "unknown".
-If one sorts them by "Online/Offline" status, the result is an empty page.

Errors in httpd.admin.error.log:
INFO: database query failed with: Unknown column 'node.online' in 'order clause' (errno: 1054) (pf::db::db_query_execute)

To reproduce:
-yum update --enable-repo=packetfence-devel
-git latest commit applied to pf tree is 0f4e33bbc9187a80439a9e7521180639304122b2
-latest db/upgrade-X.X.X-X.Y.Z.sql commit id is 744669de3977b460ba49399869af6f881f4cb2bf

**Comment by julsemaan** [comment]
Looks like 6.3 worthy to me...

**Comment by jrouzierinverse** [comment]
This has been fixed in fc8528b20235fb6f6c196aa3b96eb7b1d84fc23a

**Comment by julsemaan** [comment]
This should be in maintenance ('+1 patch release')

**Comment by jrouzierinverse** [comment]
Done
