### ISSUE TITLE
Ports from Juniper EX2200 Switches

### ISSUE THREAD

**Issue by Kahzan** [inverse-inc/packetfence#1721]
Ports from Juniper EX2200 Switches are not displayed correctly in the Locationtab of a Node.
Packetfence Version 6.2.1 

![location](https://cloud.githubusercontent.com/assets/22498365/18989409/22aca7b8-870c-11e6-858a-1b47f0f1df9f.PNG)
![radius_log_entry](https://cloud.githubusercontent.com/assets/22498365/18989408/22a8e920-870c-11e6-8f11-26399a3b358c.PNG)

**Comment by julsemaan** [comment]
Caused by the limitation of the MySQL column.

Opinion needed... do we make the column bigger or do we strip the interface name in the Juniper ?

**Comment by Kahzan** [comment]
I think the column should be bigger. At least 1 character. Because nearly every information of the interface name is needed. For example: "ge-1/0/45" tells me the interface is a Gigabit interface ("ge-") and it belongs to Node 1 ("1/") of a Virtual Chassis and Channel 0 ("0/"). And at last, the Interface has the physical portnumber 45. I hope this explains it well enough (English is not my native language). For further information I suggest to read the interface naming convention from Juniper:

https://www.juniper.net/documentation/en_US/junos14.1/topics/concept/interfaces-interface-naming-overview.html

**Comment by jrouzierinverse** [comment]
This was changed in 6.3 to a varchar(20) do you think that is big enough?

**Comment by julsemaan** [comment]
So @fdurand  wasn't crazy then, we did change it.
It seems I'm the one who's losing it as I did the change but didn't update anything...

@jrouzierinverse 20 will be enough for that case as it can't go higher than 9 (maybe 10 when they have a stack of more than 10 switchs)

One thing I've noted is I didn't alter the size of locationlog_history which I'll adjust now but that won't affect the working behavior of PF, just the archiving.

So we can consider this fixed from 6.3 then
