### ISSUE TITLE
pfqueue stats: Outstanding Task Counters isn't accurate

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1726]
If pfqueue goes down for awhile and redis-queue still gets jobs inserted, when pfqueue clears its backlog, the 'Outstanding Task Counters' isn't accurate where it still shows pending items even though the queue is completely empty.

![image](https://cloud.githubusercontent.com/assets/3857942/19000679/cd1ecbe0-8711-11e6-99bf-2075f1e32ef9.png)

Steps to replicate:
1. Kill pfqueue
2. Send a lot of DHCP packets
3. Watch the queue fill up to 10000+ for around 10 minutes
4. Start pfqueue
5. Stop pfdhcplistener after ~1-2 minutes
6. Wait for queue to clear and look at counter

Other engineers (including THE engineer @lzammit) can confirm this was also seen in non-testing circumstances pre-6.3 and we also saw negative counters showing up in 'Outstanding Task Counters'

**Comment by extrafu** [comment]
What's the status on this?

**Comment by extrafu** [comment]
What's the status on this?

**Comment by jrouzierinverse** [comment]
I am not able to replicate this in my environment

**Comment by extrafu** [comment]
@julsemaan Can you reproduce the issue for @jrouzierinverse ? 

You have some unmatched skills for replaying pcap of DHCP traffic.

**Comment by dwlfrth** [comment]
![north-korea-kim-jong-un-computer-640x360](https://cloud.githubusercontent.com/assets/633234/20113200/5e70c584-a5bd-11e6-94a3-35f7c14a7a1e.jpg)

**Comment by extrafu** [comment]
Is that a WiFi piano?

**Comment by julsemaan** [comment]
No that's @lzammit trying his new bluetooth keyboard with his cousins

**Comment by dwlfrth** [comment]
@jrouzierinverse see what you can do and get it fixed ?

**Comment by lzammit** [comment]
Fixed
