### ISSUE TITLE
captive-portal-template: hide sponsor email from guest register form

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#1742]
Hi,
I would like to configure a default sponsor email for each portal module and hide this info or autocomplete in the guest access registration form of the captive portal.
How could I configure it? I have taken a look to signin.html and it looks like it shows a textbox for every fileds.keyed item but I do not see where this fields are configured.
Greetings.

**Comment by louismunro** [comment]
Hi @rokkhan,
Github issues are for bugs and missing features.
Configuration help has it's place, on the mailing list.
