### ISSUE TITLE
Debian Jessie Package broken

### ISSUE THREAD

**Issue by OddJobBob** [inverse-inc/packetfence#1743]
The latest Debian Jessie AMDx64 package produces the following error when installing:

> The following packages have unmet dependencies:
>  packetfence : Depends: libnet-cisco-mse-rest-perl which is a virtual package.
>                Depends: libcatalyst-view-csv-perl which is a virtual package.

These packages do not appear to be available for install.

**Comment by fdurand** [comment]
Give a try please.

**Comment by OddJobBob** [comment]
Awesome, that works again.
Thanks for the rapid response.

**Comment by OddJobBob** [comment]
Looks like I spoke too soon. The install completes but the admin gui never starts, possibly as a result of these libs being missing.
/var/log/daemon.log contains:

```
Oct  6 15:32:31 packetfence pfcmd[14924]: AH00526: Syntax error on line 132 of /usr/local/pf/var/conf/httpd.conf.d/httpd.admin:
Oct  6 15:32:31 packetfence pfcmd[14924]: Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick module) (@INC contains: /usr/local/fingerbank/lib /usr/local/pf/html/captive-portal/lib /usr/local/pf/lib /usr/local/pf/html/pfappserver/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl . /etc/apache2) at /usr/local/pf/html/pfappserver/lib/pfappserver/Model/Node/Tab/MSE.pm line 22.\nBEGIN failed--compilation aborted at /usr/local/pf/html/pfappserver/lib/pfappserver/Model/Node/Tab/MSE.pm line 22.\nCompilation failed in require at /usr/share/perl5/Catalyst/Utils.pm line 308.\nCompilation failed in require at (eval 2) line 2.\n
Oct  6 15:32:31 packetfence pfcmd[14924]: httpd.admin|not started

```

**Comment by julsemaan** [comment]
@fdurand 

Was did (re)looked at ?

**Comment by fdurand** [comment]
Should be ok now, i just rebuild the 6.3.0 release with the missing perl module in debian/control
