### ISSUE TITLE
PacketFence should only process DHCPREQUESTS and DHCPACKS?

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1747]
UDP Reflector should be launched to neglect discovers/offers (server port 67 <-> dhcp client port 68) and only receive client's confirmation (ACKS) of the accepted lease sent to server port 68  from dhcp client port 67](https://www.linux.com/blog/troubleshooting-connection-problems-tcpdump-dhcp).

If I understand well, the behavior of UDP reflector and ip helpers would then be the same and the choice between the two tools would not be linked to the difference of behavior.

Actual [recommended](https://packetfence.org/doc/PacketFence_Administration_Guide.html#_dhcp_remote_sensor) line:
`C:\udp-reflector\udp_reflector.exe -s pcap0:67 -d 192.168.1.5:767 -b 25000`

What if:
`C:\udp-reflector\udp_reflector.exe -s pcap0:68 -d 192.168.1.5:767 -b 25000`

What do you think?

**Comment by tlaurion** [comment]
Erratum
`UDP Reflector should be launched to neglect discovers/offers (server port 67 <-> dhcp client port 68) and only receive client's confirmation (ACKS) of the accepted lease sent to server port 68 from dhcp client port 67](https://www.linux.com/blog/troubleshooting-connection-problems-tcpdump-dhcp).`

We should capture only DHCPREQUESTS for hostnames (0.0.0.0.68 -> 255.255.255.255.67) and DHCPACK (server:67 -> client:68) for confirmations t the source, but udp reflector does not permit bpf filters. It only permits selection of a port (src and dst is not differenciated), for which 67 is the best selection in that case.

We could limit processing by limiting processing to DHCPREQUEST and DHCPACK [here](https://github.com/inverse-inc/packetfence/blob/b4e859549f8bea0e2174b545fd9c405b9f178f88/conf/pf.conf.defaults#L66).

**Comment by tlaurion** [comment]
[Confirmation](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/dhcp/processor.pm#L219) that fingerbank only processes DHCPREQUEST, the rest is used for logging purposes.

[Exception](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/dhcp/processor.pm#L394) is if PacketFence is a DHCP server, for which we force an update on DHCPACK.

Confirmation: we seem to only need DHCPREQUEST and DHCPACK [here](https://github.com/inverse-inc/packetfence/blob/b4e859549f8bea0e2174b545fd9c405b9f178f88/conf/pf.conf.defaults#L66) if we do not care about logging.

**Comment by tlaurion** [comment]
Interesting [post on DHCP BPF masks](https://www.zabbix.com/forum/showthread.php?t=52986). I'm testing the outcome of it.

**Comment by louismunro** [comment]
In russian?

**Comment by tlaurion** [comment]
Indeed.

**Comment by tlaurion** [comment]
udp reflector is actually a pcap filter, for which -s parameter after the ":" is appended to "udp and port" string.

There is no validation for input so the following hack works:
./udp_reflector -s pcap5:"67 and ( udp[247:4] = 0x63350103 or udp[247:4] = 0x63350105)" -d 172.20.120.82:3200 

According to the russian post and the outcome being tested:

```
DHCPREQUEST = udp[247:4] = 0x63350103
DHCPACK = udp[247:4] = 0x63350105
```

Correction: 
We use similar masks to [prepare our filters](https://github.com/inverse-inc/packetfence/blob/dbdd2b1a9bd278ce6fd6ee3d42d53eeef702a188/lib/pf/util/dhcp.pm#L347), which are actually more intuitive.

Where:
"udp[250:1] = 0x0y"

and y=

```
# Validating mandatory option for DHCP
    # Option 53: DHCP Message Type (RFC2132)
    #    Value   Message Type
    #    -----   ------------
    #      1     DHCPDISCOVER
    #      2     DHCPOFFER
    #      3     DHCPREQUEST
    #      4     DHCPDECLINE
    #      5     DHCPACK
    #      6     DHCPNAK
    #      7     DHCPRELEASE
    #      8     DHCPINFORM
```

So our bpf would be, to catch DHCPREQUEST(3) or DHCPACK(5):
`(udp[250:1] = 0x3) OR (udp[250:1] = 0x5)`

**Comment by julsemaan** [comment]
I believe we should change our pcap filter (in PF) to only listen for REQUEST + ACK which should remove the decoding cost of OFFERs and DISCOVERs

The biggest cost there is in that process is not transporting or receiving the packets on the network but its all the black magic we do with those packets.

If we ignore the packet before it enters pfdhcplistener we should be golden

**Comment by julsemaan** [comment]
I'm sure the russian how-to makes you install a back-door through that pcap filter

**Comment by tlaurion** [comment]
Capturing with udp port 68 only takes into consideration clients talking with servers. If relays are desired, the capture needs to be done with port 67 and was fixed as the defaults in DHCP Forwarder project.

See https://github.com/inverse-inc/packetfence-dhcp-forwarder/
