### ISSUE TITLE
Sometimes pf::Redis crashes when PacketFence try to update the upstream fingerbank

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1749]

**Comment by fdurand** [comment]
Oct 06 12:09:04 pfqueue(118412) ERROR: [mac:unknown] [sadd] ERR Protocol error: invalid multibulk length,  at /usr/lib64/perl5/vendor_perl/Redis/Fast.pm line 213.
Redis::Fast::**ANON**('Redis::Fast=SCALAR(0xe3f50c8)', 'dhcp_vendor-', 1452, 1468, 1472, 1506, 1507, 1508, 1512, ...) called at /usr/local/pf/lib/fingerbank/Redis.pm line 64
fingerbank::Redis::fill_from_map('fingerbank::Redis=HASH(0xe417b18)') called at /usr/local/pf/lib/fingerbank/Redis.pm line 81
fingerbank::Redis::update_from_api() called at /usr/local/pf/lib/pf/fingerbank.pm line 54
pf::fingerbank::**ANON**() called at /usr/local/pf/lib/pf/fingerbank.pm line 272
pf::fingerbank::_update_fingerbank_component('Redis combination map', 'CODE(0x7b2e088)') called at /usr/local/pf/lib/pf/fingerbank.pm line 56
pf::fingerbank::__ANON__() called at /usr/local/pf/lib/pf/api.pm line 1093
pf::api::fingerbank_update_component('pf::api', 'email_admin', 0, 'action', 'update-redis-db') called at /usr/local/pf/lib/pf/api/can_fork.pm line 62
eval {...} called at /usr/local/pf/lib/pf/api/can_fork.pm line 62
pf::api::can_fork::notify('pf::api::can_fork=HASH(0xdf93d48)', 'fingerbank_update_component', 'email_admin', 0, 'action', 'update-redis-db') called at /usr/local/pf/lib/pf/task/api.pm line 35
pf::task::api::doTask('pf::task::api', 'ARRAY(0xdd2e6f0)') called at /usr/local/pf/lib/pf/pfqueue/consumer/redis.pm line 95
eval {...} called at /usr/local/pf/lib/pf/pfqueue/consumer/redis.pm line 94
eval {...} called at /usr/local/pf/lib/pf/pfqueue/consumer/redis.pm line 89
pf::pfqueue::consumer::redis::process_next_job('pf::pfqueue::consumer::redis=HASH(0xa5adbf0)') called at /usr/local/pf/sbin/pfqueue line 302
main::process_queue('pf::pfqueue::consumer::redis=HASH(0xa5adbf0)') called at /usr/local/pf/sbin/pfqueue line 253
eval {...} called at /usr/local/pf/sbin/pfqueue line 251
main::_run_task('Queue:general', 'CODE(0xa35b320)', 'HASH(0xa394fe0)') called at /usr/local/pf/sbin/pfqueue line 229

**Comment by jrouzierinverse** [comment]
The reason for this is that we are sending too much information to redis a time.
The task that does the loading needs to batch it's request.

**Comment by jrouzierinverse** [comment]
The issue is in fingerbank not packetfence.

**Comment by jrouzierinverse** [comment]
fingerbank/perl-client#20 need to be fixed in order for this to be closed.

**Comment by jrouzierinverse** [comment]
This cannot be a patch +1 release

**Comment by jrouzierinverse** [comment]
This has been fixed in fingerbank
