### ISSUE TITLE
pf::enforcement::_vlan_reevaluation

### ISSUE THREAD

**Issue by rumo20** [inverse-inc/packetfence#1750]
I use web auth function with an WLC 5500. Since upgrading to version 6.3.0 packetfence did not re-evaluation my vlan. 
In packetfence.log it stuck's here:

httpd.portal(2778) INFO: [mac:xx:xx:xx:xx:xx:xx] switch port is (x.x.x.x) ifIndex 13 connection type: WiFi MAC Auth (pf::enforcement::_vlan_reevaluation)

If I reconnect my client to the wifi, everything works fine

**Comment by extrafu** [comment]
Use the mailing list.
