### ISSUE TITLE
iplog rotation: Should specify a minor version of perl-DBI in packaging

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1754]
Running PacketFence 6.0.1-1
Was running perl-DBI-1.609-4.el6.x86_64

encountered following error

Oct 11 09:27:02 pfmon(4263) ERROR: Error running task iplog rotation: DBD driver has not implemented the AutoCommit attribute at /usr/local/pf/lib/pf/db.pm line 348.
 (main::_runtask)

Updated to latest PacketFence repo available version of perl-DBI (perl-DBI-1.616-1.of.el6.x86_64)

Fixed the issue.

We should make sure to specify a minimal version of perl-DBI dependancy in packaging

https://github.com/inverse-inc/packetfence/blob/packetfence-6.3.0/addons/packages/packetfence.spec#L120

**Comment by dwlfrth** [comment]
Standby...
Looks like the error may come to the query not being processed quickly enough...

**Comment by jrouzierinverse** [comment]
I believe this is an issue where the database connection is dropped during the transaction.

**Comment by dwlfrth** [comment]
No issue related to packaging.
Transaction taking too much time due to too many entries.

**Comment by jrouzierinverse** [comment]
The real issue is lack of indexing on the iplog history table.
