### ISSUE TITLE
"detect" and "suricata_event" violation triggers should be clearer

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1758]
Administration guide specifies under security_onion section that:

```
Configuration of a new violation can use the following trigger types:

Type: detect
Triggers ID: The IDS triggered rule ID

Type: suricata_event
Trigger ID: The rule class of the triggered IDS alert
```

That isn't true. Snort and Suricata output, when in alert type, in the native form:
`07/28/2015-09:09:59.431113  [**] [1:2221002:1] SURICATA HTTP request field missing colon [**] [Classification: Generic Protocol Command Decode] [Priority: 3] {TCP} 10.220.10.186:44196 -> 199.167.22.51:8000`

When under SecurityOnion, the format of the original changes to this:
`Oct 07 15:23:40 pfdetect(11814) INFO: alert received: 'Oct  7 14:23:40 idsman01 securityonion_ids: 14:23:40 pid(24921)  Alert Received: 0 1 policy-violation idshalls01-eth0-7 {2016-10-07 14:23:39} 21 173773 {ET P2P Vuze BT UDP Connection} 10.6.198.173 24.122.228.33 17 10600 65344 1 2010140 6 92 92`

Proposed alternatives:
- "detect" keyword should change to something clearer like: SID (Snort ID for Snort, or Signature ID by [Suricata](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Meta-settings))
- "suricata_event" should change to something like ids_rule_text or something similiar

For sure, one cannot use detect in when using SecurityOnion

**Comment by julsemaan** [comment]
> For sure, one cannot use detect in when using SecurityOnion

That isn't (at least shouldn't be) true

One can use detect trigger in security onion.

Its just that the case you saw wasn't working because of a regression in the violation API which was fixed in all v6 maintenances

Still your idea of changing detect -> sid is good but it should be suricata_sid

**Comment by tlaurion** [comment]
I validated the behavior with https://github.com/inverse-inc/packetfence/compare/fix/security_onion_parser_unit_test and other parsers and you're right.
- "detect" keyword tries to match on what the parsers have extracted as a unified numerical SIDs ($data->{sid})
- "suricata_event"  keyword tries to match on what the parsers have extracted as a unified description ($data->{descr})

detect keyword -> unified_ids_sid?
suricata_event -> unified_ids_message?

**Comment by julsemaan** [comment]
Unified ids sid doesn't sound really clear to me if I put myself in the hands of an administrator.

Sounds more obvious to have suricata or snort in those name so its clearer even if its not semantically right.

**Comment by julsemaan** [comment]
Closed won't fix or was this addressed in some way ?

**Comment by tlaurion** [comment]
I understood that this was more of a clarification need then a need to change anything. Let's clarify a bit more before closing then:

I still believe that it would be clearer if:
- detect -> sid (people familiar with IDS will know what an sid is) or ids_numerical_id, or ids_id. You said earlier that it should be suricata_sid. Any reason why snort is not considered here?
- suricata_event -> ids_event_description (As i understood it, it is more then just extracted categories but could be literally any text that could match in the alert having triggered and being processed for a violation.

**Comment by julsemaan** [comment]
Assigning 7.3 on this so we address or close it
