### ISSUE TITLE
radiusd cannot open the following certificate since upgrade to 6.3.0

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#1762]
Hi,
I have recently upgrade from packetfence 6.2.1 ot 6.3.0 and now radiusd service is not starting.

It says "cannot open the following certificate". Certificates where generated with packetfence-pki and worked with 6.2.1 version.

[root@SLX00012040 ssl]# /usr/local/pf/bin/pfcmd service radiusd restart
service|command
radiusd|already stopped
radiusd-acct|already stopped
httpd.admin|already started
Checking configuration sanity...
WARNING - Cannot open the following certificate %%install_dir%%/conf/ssl/tls_certs/atari.eroski.es.pem
radiusd-acct|not started
radiusd|not started

**Comment by rokkhan** [comment]
Radiusd logs says that the file does not exists but it does:

Fri Oct 14 19:35:39 2016 : Error: Unable to check file "%%install_dir%%/conf/ssl/tls_certs/atari.eroski.es.key": No such file or directory

[root@SLX00012040 tls_certs]# pwd
/usr/local/pf/conf/ssl/tls_certs
[root@SLX00012040 tls_certs]# ls -altr
total 24
-rw-r--r-- 1 pf pf 1249 ago 22 17:55 Thanatos_CA.pem
-rw-r--r-- 1 pf pf 2481 ago 22 18:09 atari.eroski.es.p12
-rw-r--r-- 1 pf pf 1828 ago 22 18:11 atari.eroski.es.key
-rw-r--r-- 1 pf pf 1513 ago 22 18:23 atari.eroski.es.pem
drwxr-xr-x 2 pf pf 4096 ago 22 18:48 .
drwxr-xr-x 3 pf pf 4096 oct  5 23:07 ..

**Comment by whitx** [comment]
it seems the %%install_dir%% variable was not replace properly, I will try to reproduce this, for now can you just try to replace %%install_dir%% by /usr/local/pf/ in the file /usr/local/pf/conf/radiusd/eap.conf then do bin/pfcmd configreload hard and bin/pfcmd service radiusd restart.

**Comment by rokkhan** [comment]
It worked!

[root@SLX00012040 radiusd]# /usr/local/pf/bin/pfcmd service radiusd restart
service|command
radiusd|stop
radiusd-acct|stop
httpd.admin|already started
Checking configuration sanity...
radiusd-acct|start
radiusd|start

**Comment by whitx** [comment]
I was able to reproduce your issue, let me get back to you on this

**Comment by whitx** [comment]
We modified the conf/radiusd/eap.conf to use TemplateToolkit instead of the old templating we had, you should have a file conf/radiusd/eap.conf.rpmnew if you are using a RHEL based system, if you are using a debian, apt doesn't allow to do the same kind of manipulation. 

In the later case you can copy the conf/radiusd/eap.conf.example to replace eap.conf and then modify manually your certificate paths in the new config file.

I will add a note in the UPGRADE guide concerning this file.

**Comment by rokkhan** [comment]
It worked! Thanks.
