### ISSUE TITLE
Fingerbank Settings not showing after upgrade to 6.3.0

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#1763]
Hi,
I have recently upgraded my PF from 6.2.1 to 6.3.0 and was trying to move fingerbank database to mysql following the steps described in upgrade procedure.

I have created the database pf_fingerbank and verified that pf user has rights to use the database, but when I try to configure the database settings in the  web administration interface I get this error: "Error! An error occured while contacting the server. Please try again later." 

Taking a look to http.admin.access logs says something about an API key but I don´t know where to configure it.

Oct 14 19:54:00 httpd.admin(2380) WARN: Fingerbank API key is not configured. Running with limited features (pfappserver::PacketFence::Controller::Config::Fingerbank::Settings::check_for_api_key)

Installed fingerbank version is 
[root@SLX00012040 logs]# rpm -qa | grep fingerbank
fingerbank-3.0.0-4.1.noarch
If I do a yum update fingerbank says that there no packages to update.

**Comment by rokkhan** [comment]
It worked!

[root@SLX00012040 radiusd]# /usr/local/pf/bin/pfcmd service radiusd restart
service|command
radiusd|stop
radiusd-acct|stop
httpd.admin|already started
Checking configuration sanity...
radiusd-acct|start
radiusd|start

**Comment by whitx** [comment]
API key is a feature for customers with support contracts. Fingerbank is running but you don't have access to options.

**Comment by julsemaan** [comment]
hum, @whitx that's totally wrong !!

Fingerbank API keys are available to anyone, but you must register with a valid Github account and your hourly requests are limited.

Just head to 'Configuration->Fingerbank->Settings' and board your server to fingerbank and it should work

**Comment by whitx** [comment]
Yep my bad, on the other hand you can do:
wget https://github.com/inverse-inc/packetfence/commit/1e2d91204fdcc400041bd1ad6d9658cf2f7d31e8.diff
patch -p1 < 1e2d91204fdcc400041bd1ad6d9658cf2f7d31e8.diff
This should correct your issue of accessing the page.

**Comment by rokkhan** [comment]
Hi,

I was using fingerbank previously without any API key or registering in github. 

Do I have to configure a github account to use mysql engine as database? 
I can not open "Configuration->Fingerbank->Settings" I get "Error! An error occured while contacting the server. Please try again later." error.

Where do it have to run the wget and patch commands? at /usr/local/pf?

**Comment by whitx** [comment]
Yes you would need to run command from /usr/local/pf, also the file name will be the full commit id, not only the 8 first characters.

**Comment by rokkhan** [comment]
It worked! Thanks a lot.
