### ISSUE TITLE
packetfence.service: control process exited, code=exited status=255

### ISSUE THREAD

**Issue by beckyboo123** [inverse-inc/packetfence#1766]
Hi guys,
I have just installed PacketFence on to a clean system and i seem to be having a few issues getting going.
All seemed to be okay until I left the WebGUI over night and when I returned I could not access it again.
I rebooted the server (CentOS) and found that I could not start the packetfence service again.
It comes back with this error:

> Could not write namespace config::Documentiation to L2 cache!
> Could not write namespace config::Cluster to L2 cache!
> Could not write namespace config::PfDefault to L2 cache!
> unable to connect to database: Access denied for user 'pf'@'localhost' (using pas...ne 42.
> packetfence.service: control process exited, code=exited status=255
> Failed to start PacketFence Service.

Can anyone help with this? 
I'm sorry if this isn't the place to be asked this but I am new to PacketFence and I don't want to have to give up on it before I've even started!

Thank you :)

**Comment by julsemaan** [comment]
Hi,

Please use the mailing list for such questions.

Thanks
