### ISSUE TITLE
log stack trace

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#1774]

**Comment by julsemaan** [comment]
This doesn't really mean anything...

**Comment by jrouzierinverse** [comment]
To you 😏

**Comment by julsemaan** [comment]
The bug tracker is not a to-do list...

Stuff should be meaningful to more than 1 person in order to be placed on our public bug tracking system

**Comment by jrouzierinverse** [comment]
This is a new feature that was discussed already.

**Comment by dwlfrth** [comment]
I have to agree with @julsemaan. We should avoid opening issues without a description.

Let's say that you jump on something more important and that one is being forgotten and then in a year we want to review opened issues, we come across that one and we say... wow, what does that mean ? Is it fixed or what ?
Having a documentation can also help evaluate the "amount of work" and impact of an issue / feature.

I think that yes, issues must at least have a description and should not only be here to "track".

**Comment by jrouzierinverse** [comment]
I agree 100%

However I was not ask to add a description for the issue.
Nobody here are mind readers.
A comment should either ask for clarification or give direction either it is just noise.

**Comment by extrafu** [comment]
Review and merge please.
