### ISSUE TITLE
device-registration: 'Null' source type should not be used

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1784]
Device registration module uses `captiveportal::PacketFence::Controller::Authenticate::authenticateLogin` to authenticate a user.

`https://github.com/inverse-inc/packetfence/blob/packetfence-6.3.0/html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm#L102`

We should not allow the use of a configured 'Null' source for this kind of scenario.

Current ugly fix:

Right after
`https://github.com/inverse-inc/packetfence/blob/packetfence-6.3.0/html/captive-portal/lib/captiveportal/PacketFence/Controller/Authenticate.pm#L106`

add

`
if ( $request->{'match'} eq "device-registration" ) {
    my @indexes_to_delete = grep { $sources[$_]->{'type'} eq 'Null' } 0..$#sources;
    @indexes_to_delete = reverse(@indexes_to_delete);
    foreach my $index ( @indexes_to_delete ) {
        splice(@sources, $index, 1);
    }
}
`

And change

`https://github.com/inverse-inc/packetfence/blob/packetfence-6.3.0/html/captive-portal/lib/captiveportal/PacketFence/Controller/Authenticate.pm#L163`

by

`if ($c->request->{'match'} =~ "activate/email" || $c->request->{'match'} =~ "device-registration") {`

**Comment by dwlfrth** [comment]
@dwlfrth check if still an issue, and if yes, apply ugly fix

**Comment by julsemaan** [comment]
Re-opening to track cherry-picking in maintenance/7.0 once this fix is confirmed as working with the 7.1 testing

**Comment by dwlfrth** [comment]
Run its course
