### ISSUE TITLE
pfdhcplistener takes a minute to die

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1791]
When receiving the kill signal from pfcmd, it takes about a minute to die (for each interface).

To clarify, the process itself isn't dying and its not pfcmd that isn't detecting the process exited.

Requires stracing and stuff.

**Comment by jrouzierinverse** [comment]
I quickly tried to replicate this and I was not able to.
Please provide additional information on how to replicate this.

My test 

```
./sbin/pfdhcplistener -i eth8 -d
strace -p $(cat var/run/pfdhcplistener_eth8.pid)
```

In a separate screen

```
kill <PID> $(cat var/run/pfdhcplistener_eth8.pid)
```

**Comment by jrouzierinverse** [comment]
I think I found the problem the pid file is not deleted.

**Comment by julsemaan** [comment]
That seemed to be related to active/active at first but I can't replicate it on 6.4 so lets consider this fixed for now
