### ISSUE TITLE
Pfdetect Regex Parser : Sagan?

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1805]
Just a quick note to have your insights on Sagan, which is a syslog parser, that replicates Snort/Suricata rule system and dependencies, and outputs in unified2, as snort and suricata. This means that Barnyard2 manages the [output to syslog](https://groups.google.com/forum/#!topic/security-onion/MgarbwDirEQ).

Intro: 
https://quadrantsec.com/about/blog/what_the_sagan_log_analysis_engine_is...and_what_it_is_not/

What that means to us is that we could have Sagan do what we aim to do with syslogs and listen for certain types of logs, and have Sagan's rule system as regex parsers we are planning to develop and extend, do the job for us.  **Sagan is a log normalizer** permitting us to look at logs in an unified way, _with rules specifying in what we are interested in._ 

The output we would have to deal with would be the same as the actual Snort/Suricata, already dealt with the syslog parser and detect [plugin](https://github.com/inverse-inc/packetfence/blob/fix/security_onion_parser_unit_test/t/unittest/detect/parser/snort.t):
```
is($result->{events}->{detect}, "2221002");
is($result->{events}->{suricata_event}, "SURICATA HTTP request field missing colon");
```
detect refers to SID.
suricata_event refers to MSG, shared between suricata and snort.
[This should be clearer.](https://github.com/inverse-inc/packetfence/issues/1758)

Here some examples:
Snort rule parsers: https://github.com/beave/sagan-rules/blob/master/snort.rules
TrendMicro amlware found: https://github.com/beave/sagan-rules/blob/master/trendmicro.rules
Yubikey errors: https://github.com/beave/sagan-rules/blob/master/yubikey.rules
Tripwire problems: https://github.com/beave/sagan-rules/blob/master/tripwire.rules
Linux-Kernel Problems: https://github.com/beave/sagan-rules/blob/master/linux-kernel.rules

What that would mean for us is that we would have:
- Configure Sagan configuration file to include rule files corresponding to the vendors the client have deployed.
- Listen externally for syslogs, redirect those syslogs to Sagan[ through FIFO](https://wiki.quadrantsec.com/bin/view/Main/SaganInstall#7_Configuring_the_syslog_ng_rsys)
- Create violation triggers on specific SIDs (with events detect) or suricata_event events (part of the MSG)<
- Deploy PulledPork, since flowbits logic also exists in Sagan rules. This means that correlation rules or more complex rules will validate some prerequisites by triggering a flobit (but not raising an alert) and that those dependencies need to be respected. It's PulledPork job to do that.

We would need to deploy:
- PulledPork ( resolve rule dependencies and deal with rules updates)
- Sagan
- Barnyard2 (Deal with unified2 output)

**Comment by extrafu** [comment]
I like the idea...

Could we also potentially drop pfdetect and simply use Sagan + its script execution capability?

Call a meeting to discuss this further.

**Comment by tlaurion** [comment]
It is possible to use Sagan [to launch external processes](https://wiki.quadrantsec.com/bin/view/Main/SaganHOWTO#Configuration_with_external_prog) on rule matching to output alert content (action response)

It can give it's output in two modes. The first is really similar to what pfdetect actually parse and extracts it's information from (named: alert mode):

```
[**] [5000075] [SSH] Authentication success [**]
[Classification: successful-user] [Priority: 3]
2010-04-28 12:46:10 10.222.0.55:38559 -> 10.222.0.1:22 auth info
```

The second mode (named : parsable)

```
ID:5000075
Message:[SSH] Authentication success
Classification:successful-user
Priority:3
Date:2010-04-28
Time:12:46:10
Source:10.222.0.55
Source Port:38559
Destination:10.222.0.1
Destination Port:22
Facility:auth
Syslog Priority:info
Syslog message: sshd[9091]: Accepted keyboard-interactive/pam for exampleuser from 10.222.0.55 port 38559 ssh2 
```

Right now, what is provided to the detect parser is Snort log, which is of the following [format](https://github.com/inverse-inc/packetfence/blob/devel/t/unittest/detect/parser/snort.t):
`07/28/2015-09:09:59.431113  [**] [1:2221002:1] SURICATA HTTP request field missing colon [**] [Classification: Generic Protocol Command Decode] [Priority: 3] {TCP} 10.220.10.186:44196 -> 199.167.22.51:8000`

**Comment by tlaurion** [comment]
First iteration could be to feed detect parser with actual snort alert output.
Second iteration could be to replace the detect parser engine.

**Comment by tlaurion** [comment]
Conclusions of the meeting:

Sagan will not be used as a syslog receiver. Creating rules is more difficult in Snort format, and testing them would be more complex then to test a regex against a string.

For the moment, we need to be able to create search strings that we want to have violations from, as a quick way to debug stuff and easily expendable. If we see that we want to be able to create violations on more and more stuff that Sagan also covers, we could reconsider.
