### ISSUE TITLE
Configurator: Satus on the services doesn't work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1811]
![capture d ecran 2016-11-09 a 10 09 27](https://cloud.githubusercontent.com/assets/5261214/20142984/0b2e01f4-a665-11e6-9f8f-f5c406ca1d86.png)
<img width="937" alt="capture d ecran 2016-11-09 a 09 58 36" src="https://cloud.githubusercontent.com/assets/5261214/20142985/0b305008-a665-11e6-871f-0dfc6e9c73d5.png">
<img width="1279" alt="capture d ecran 2016-11-09 a 09 58 24" src="https://cloud.githubusercontent.com/assets/5261214/20142983/0b2d93fe-a665-11e6-87eb-66265db6eac0.png">

**Comment by lzammit** [comment]
Does the same error on Safari and Chrome.

**Comment by jrouzierinverse** [comment]
Can you attach the following files logs/httpd.admin.catalyst logs/httpd.admin.log
