### ISSUE TITLE
Condition AutoRegistration in radius audit log is not working properly

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1812]
If you set the condition 'Auto Registration' with 'is/matches' as an operator and 'no/yes' as a value no results are coming back. Look on a request in 'details' they are wrote like that.

**Comment by jrouzierinverse** [comment]
The actual values in the radius_audit_log.auto_reg seems to be either or N, Y 
To get your query to put the value N in the text field.

A previous issues #1132, #1133 normalized the display of Is phone and Auto Registration to yes and no. 

I propose one of two solutions.

Display whatever the value is in the database (This is fast)
or 
Do like we do in the node search have a dynamic drop down with all the possible values for the field.
