### ISSUE TITLE
Data type for is_phone/auto_reg is not good in radius_audit_log table

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1815]
We have few different data type for those fields, it should be standardize.

> select DISTINCT auto_reg from radius_audit_log;
+----------+
| auto_reg |
+----------+
| 0        |
| 1        |
| N        |
+----------+

> select DISTINCT is_phone from radius_audit_log;
+----------+
| is_phone |
+----------+
| N        |
| 1        |
+----------+

We should have either 0 and 1 or N and Y, but not a mixup of both.

**Comment by jrouzierinverse** [comment]
After this is normalized I could do the same thing like in nodes and have dynamic search/ops fields.

**Comment by fdurand** [comment]
Fixed by c0f751a8aedff890181054fdf537f2717910aff2
