### ISSUE TITLE
Joining a domain will sometimes return a 500 even though it suceeded

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1821]
Seems related to #1818 as I was able to replicate it once and captured the following body 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@packetfence.packetfence.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

Which matches the one in #1818.

Let's fix #1818 and we'll see if this can still be replicated

**Comment by jrouzierinverse** [comment]
Logs???

**Comment by jrouzierinverse** [comment]
If this has the same error in the logs then it is 100% the same problem.
I would mark this as a duplicate of #1818

**Comment by julsemaan** [comment]
There is no log at all (other than the usual info lines while joining) so that's why I didn't confirm it as a duplicate but still didn't want to invest time into looking into it just yet in the event we had another case of lost log lines in our Apache processes.

**Comment by jrouzierinverse** [comment]
I have to ask to make all bases were covered.
DId you check both the httpd.admin.log and httpd.admin.catalyst log for errors.

**Comment by julsemaan** [comment]
All checked up, no error to report there except a line `NT_STATUS_UNSUCESSFUL` but it shows up on the second attempt (that works) too so it doesn't look like its tied to the underlying issue

**Comment by julsemaan** [comment]
Installed a fresh environment and replicated the exact same parameters as me and @ziceo used while getting the issue and it worked fine.

Looks like it may have been tied to #1818 

If anybody is able to replicate it using latest devel, please re-open

Otherwise, lets pop the :champagne:
