### ISSUE TITLE
Packetfence 6.3.0 not staring installed on centos 7

### ISSUE THREAD

**Issue by anandhc** [inverse-inc/packetfence#1833]
Dear All,

OS : Centos7 64 bit
Packet Fence 6.3.0

I installed Packetfence 6.3.0 on centos 7 usinh the yum repo provided in the Website. I t installed everything without dependency error . But when start the packet fence it tool long time and started with error.It showing mysql.socket error and name space   

[root@logsrv ~]# journalctl -xe 
Nov 15 18:46:28 logsrv pfcmd[12313]: [1479215788.52464] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:28 logsrv pfcmd[12313]: [1479215788.62565] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:28 logsrv pfcmd[12313]: [1479215788.72671] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:28 logsrv pfcmd[12313]: [1479215788.8276] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:28 logsrv pfcmd[12313]: [1479215788.92848] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.02938] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.13017] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.23107] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.33197] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.43282] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.5337] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.63456] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.73547] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.83643] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:29 logsrv pfcmd[12313]: [1479215789.93736] Failed to connect to config service for namespace interfaces::management_network, retrying
Nov 15 18:46:30 logsrv pfcmd[12313]: [1479215790.03825] Failed to connect to config service for namespace interfaces::management_network, retrying

But I can able login to the mysql server with user pf and password packet. I created the Database pf.

Bye
[root@logsrv ~]# mysql -p -u $user pf 
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 10
Server version: 5.5.50-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| pf                 |
| test               |
+--------------------+
5 rows in set (0.06 sec)

MariaDB [(none)]> 

Though it gives error.
What could the reason. I have not made any changed in the config files, 
mysqld_safe A mysqld process already exists

What should be the problem. DO i need to create db for pf manually or it will start automatically.

Thanks and Regards
Muruganandan.C

**Comment by julsemaan** [comment]
Once PacketFence starts haproxy that error will disapear.

Next time, please use the mailing list for such questions
