### ISSUE TITLE
Shouldn't be able to start 2 pfmon processes at the same time

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1834]
Right now we can do it and it doesn't really make sense as the second one will overwrite the PID file of the first one and the first one will never be managed by PF anymore.

Depending on the size of the fix, this should likely go in the maintenance IMO

**Comment by jrouzierinverse** [comment]
Fix by c3871e981f3927e3f714a1a0dab462b963d4f02d

**Comment by jrouzierinverse** [comment]
Also in maintenance
