### ISSUE TITLE
hostname not viewed on list of node

### ISSUE THREAD

**Issue by richardsith** [inverse-inc/packetfence#1835]
my lab is so made:

network 1.1.253.0/24 (Management)
network 1.1.20.0/24 (Endpoint)

1 VM with PacketFence (1.1.253.10) in inline enforcement
1 VM with Windows AD DS (1.1.253.1)
1 VM with Windows DHCP Server (1.1.253.3 + 1.1.20.1)
n. endpoint (1.1.20.xx)

on PacketFence I see endpoint with its own hostname, but the server it's present just MAC address why it's possible to report their hostname and eventually its domain?

![screen shot 2016-11-15 at 16 15 39](https://cloud.githubusercontent.com/assets/9977215/20315604/da51a92e-ab5e-11e6-846e-6d7a1ca8d5b0.png)

 the network interface are configured in this way

![screen shot 2016-11-14 at 22 52 31](https://cloud.githubusercontent.com/assets/9977215/20315864/c5ccfc96-ab5f-11e6-9a3b-73788fdf15e2.png)

**Comment by julsemaan** [comment]
The bug tracker is exclusively for bugs

Please use the mailing list for configuration questions
