### ISSUE TITLE
Packet fence 6.3.0 on centos 7 packetfence not startting 

### ISSUE THREAD

**Issue by anandhc** [inverse-inc/packetfence#1842]
I have been working to install Packet Fence 6.3.0 on Centos 7 I have used yum repo to install. Everthing looks fine but its not starting 
Mariadb is running 
haproxy running
Freeradius is ruuning

Its give and error
Nov 17 19:50:03 logsrv pfcmd: [1479392403.41025] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:03 logsrv pfcmd: [1479392403.5113] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:03 logsrv pfcmd: [1479392403.61233] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:03 logsrv pfcmd: [1479392403.71338] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:03 logsrv pfcmd: [1479392403.81439] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:03 logsrv pfcmd: [1479392403.91547] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.0165] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.11756] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.21862] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.31959] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.42054] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.52145] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.62233] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.72329] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.82435] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:04 logsrv pfcmd: [1479392404.92538] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.02631] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.12728] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.2283] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.32923] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.43018] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.53117] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.63215] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.7332] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.83429] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:05 logsrv pfcmd: [1479392405.93523] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:06 logsrv pfcmd: [1479392406.0362] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:06 logsrv pfcmd: [1479392406.13719] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:06 logsrv pfcmd: [1479392406.2382] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:06 logsrv pfcmd: [1479392406.33918] Failed to connect to config service for namespace resource::URI_Filters, retrying
Nov 17 19:50:06 logsrv pfcmd: [1479392406.44008] Failed to connect to config service for namespace resource::URI_Filters, retrying

So what would be reason for this message. I am tired searching the reason .Ihave reinstalled db server.
Please help out.

Thanks and Regards

Muruganandan.C

**Comment by louismunro** [comment]
USE THE MAILING LIST.
