### ISSUE TITLE
sAMAccountName is present twice as a condition

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1844]
While adding a condition for AD sources, sAMAccountName is available twice to be added.

**Comment by jrouzierinverse** [comment]
Unable to replicate.

**Comment by jrouzierinverse** [comment]
Spoke to @whitx closing

**Comment by jrouzierinverse** [comment]
The issue was when an AD specific attribute is used as the username attribute it will get repeated multiple in the list.
