### ISSUE TITLE
Inline L3: Duplicate locationlog entries are opened

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1847]
The locationlog of Inline L3 open twice with the exact same informations (http://pastebin.com/0q4Ct0Au)

That doesn't seem to be happening every time though and might be a race condition.

I'd like to provide more details to point to the issue, can one of the Inline wizards point me to details that could be required ?

**Comment by dwlfrth** [comment]
@dwlfrth check real quick, otherwise push to 7.1 (eventually close won't fix)

**Comment by dwlfrth** [comment]
@julsemaan, can you check if it is still an issue. I remember I fixed a locationlog double entry thing for v7.
If you can't, I'll dig in...

**Comment by julsemaan** [comment]
Saw that on a customer site which isn't on v7 and I don't have an L3 inline setup to replicate.

**Comment by dwlfrth** [comment]
Probably related to duplicate DHCP requests
- Two pfdhcplistener running at the same time
- Receiving DHCP packets in double ...

Will close for now. Reopen if it happens again

**Comment by jrouzierinverse** [comment]
In 7.0 pfdhcplistener move to a parent-child style of service and does not allow multiple pfdhcplistener services to be ran at the same time.
So it highly unlikely that pfdhcplistener can receive double DHCP packets in 7.0.

If this was opened for packetfence prior to 7.0 it is possible for pfdhcplistener to receive double DHCP packets.
