### ISSUE TITLE
Admin: Double nodes still showing up when there is a duplicate locationlog

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1848]
There is two issues with this, first, the duplicate inline L3 locationlog (see #1847) and second we are still showing duplicate records when there are duplicate locationlogs (this issue is for the latest).

I believe we should address this duplicate locationlog issue directly in the admin so that we stop having this recurring problem to show double nodes when there are duplicate locationlogs.

![image](https://cloud.githubusercontent.com/assets/3857942/20431911/a8910a70-ad6a-11e6-8f93-9bc26e7c97e0.png)

![image](https://cloud.githubusercontent.com/assets/3857942/20431880/74cfaf70-ad6a-11e6-9649-bc301a0743b4.png)

P.S. : This is on 6.3

**Comment by hughneale** [comment]
Seeing this issue too on PF 6.2

**Comment by dwlfrth** [comment]
@jrouzierinverse check to make sure a node is only displayed once even if there is more than one locationlog opened

**Comment by dwlfrth** [comment]
@jrouzierinverse please look and backport for 7.x

**Comment by dwlfrth** [comment]
@jrouzierinverse Status ?
