### ISSUE TITLE
dhcp processor: Possible race condition when doing RSSO

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1857]
RSSO (do_sso) call should fork to avoid blocking process of dhcp packets.

**Comment by julsemaan** [comment]
That sounds good. I actually do it on a setup to prevent slow SSO from backlogging the queue

Shall we process to adding it in devel and in the maintenance ?

Fix is ultra simple (just adding a flag to the subroutine declaration)

**Comment by julsemaan** [comment]
Well I see a lot of people have a strong opinion around this issue...

**Comment by dwlfrth** [comment]
Let's do this
