### ISSUE TITLE
Admin: Removal of pf::config::cached causes extreme latency in switches page

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1871]
Using a configuration file with 3130 sections and going in 'Configuration->Switches' causes one httpd.admin process to use a full CPU to parse the file for more than 2 minutes and the user is waiting for that parsing.

At the end of those two minutes, the browser gives up for obvious reasons.

We need to be able to support that amount of switches configured in PacketFence (as this is extracted from a production setup) whether we use a cache in the middle of that specific file or by another mean.

Trying it with curl produces a result after 2 minutes and the response is loaded successfully.
```
time curl 'https://172.20.20.109:1443/config/switch?_=1480431892963' -H 'Host: 172.20.20.109:1443' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: https://172.20.20.109:1443/admin/configuration' -H 'Cookie: CGISESSION=35367b9898df0fff5916643dbee4cc8595924041; pfappserver_session=0f5860335bc69e93a61ff0b0d8453fa8bc1d8bf5' -H 'Connection: keep-alive' --insecure
........output truncated.........
real    2m11.140s
user    0m0.055s
sys     0m0.034s
```

IMO, we should aim for a load time of max 10 seconds for a file that big

**Comment by jrouzierinverse** [comment]
Can you tell me the version of Config::IniFiles you have?

**Comment by julsemaan** [comment]
perl-Config-IniFiles-2.88-7.1.noarch

**Comment by julsemaan** [comment]
@jrouzierinverse 

Is this a correct version ? I don't see a more recent version in our repos

**Comment by jrouzierinverse** [comment]
This has been fixed with the issue with the realms. Please verify

**Comment by julsemaan** [comment]
Yes bye-bye latency.

Less than 10 seconds now, so great success
