### ISSUE TITLE
RHEL7 distributes lasso-2.5.1 but not lasso-perl-2.5.1

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1873]
If you do a yum update of a RHEL7, lasso-2.5.1 will try to update but since lasso-perl-2.5.1 doesn't exist on their repo, that causes a dependency problem that blocks the update.

Looks like we'll need to package 2.5.1 with the perl bindings to get rid of that.

**Comment by jrouzierinverse** [comment]
This should not be a +1 patch since it deals with packaging

**Comment by julsemaan** [comment]
but should be dealt with prior to PF 6.5

So although that won't be cherry-picked into maintenance, that should be dealt with in our repos prior to our next release.

Unless we add another milestone for that

**Comment by julsemaan** [comment]
Updated packages copied into the RHEL7 devel repo

Will install the nightly tomorrow and if it succeeds, I'll push them into stable

**Comment by julsemaan** [comment]
Updated+tested in the stable repo

**Comment by julsemaan** [comment]
Updated the release number to 100 and pushed to stable + devel

If the dependency problem arises, do:
```
# yum update lasso\* --disablerepo=* --enablerepo=packetfence
```

And then proceed with whatever wasn't working before
