### ISSUE TITLE
Admin: Saving a realm doesn't commit changes in the config

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1874]
realm.conf.defaults content
```
[DEFAULT]

[LOCAL]

[NULL]
```

realm.conf is an empty file

I go in the admin, in 'Configuration->Realm' edit the NULL realm and assign it the domain 'inverseinc' which exists in domain.conf

Then I save, all signs point to a successful commit:
```
Nov 29 11:05:43 httpd.admin(16686) INFO: Hard expiring resource : config::Realm (pfconfig::manager::expire)
Nov 29 11:05:43 httpd.admin(16686) INFO: Changes successfully commited in the configuration (pfappserver::Base::Controller::Crud::Config::_commitChanges)
Nov 29 11:05:44 httpd.admin(16686) INFO:  (pfappserver::Base::Controller::Crud::view)
```

Admin also shows a success:
```
Success! Section NULL successfully modified in the configuration
```

But the configuration file is not changed and stays empty (realm.conf)

**Comment by julsemaan** [comment]
Just tested and same goes for the domains

**Comment by julsemaan** [comment]
Firewall SSO are also bugged

Most of the configuration in the admin cannot be modified.

@jrouzierinverse could you provide input on this as it seems related to pf::config::cached removal

**Comment by jrouzierinverse** [comment]
I fixed this is devel

**Comment by jrouzierinverse** [comment]
Please verify

**Comment by julsemaan** [comment]
Firewall SSO is fixed but not realms

Maybe related to the fact there is a realm.conf.defaults ?

**Comment by jrouzierinverse** [comment]
This is fixed however there is an issue with Authentication Sources

**Comment by julsemaan** [comment]
realms are indeed fixed with the latest fix.

@jrouzierinverse:
Do you want to keep this issue open for auth sources or you'll open a new one for it ?

**Comment by jrouzierinverse** [comment]
This has been fixed please verify

**Comment by julsemaan** [comment]
Not sure what was the bug with the auth sources you were having so I can't assert the fix, but I was able to edit them so on my end, there is no issue
