### ISSUE TITLE
Installing Packetfence on Ubuntu

### ISSUE THREAD

**Issue by mohitbakshi23** [inverse-inc/packetfence#1881]
Hi ,

I am installing packetfence on Ubuntu, as prerequisites i have installed isc-dhcp-server, freeradius, mysql,apache. But when i try to install the packetfence using "apt-get install packetfence". It throws with the error "E: Unable to correct problems, you have held broken packages.". Please help me installing packetfence on ubuntu.

I am also attaching the screenshot of the error.
![screenshot 55](https://cloud.githubusercontent.com/assets/22557152/20829969/7e21b786-b8a4-11e6-933e-c7a62fcdc8e7.png)

**Comment by julsemaan** [comment]
Thats because we don't support Ubuntu anymore.

If you need a Debian based distro, use Debian, otherwise use CentOS7/RHEL7

**Comment by Mohit2345** [comment]
I have installed the packetfence on centos 7. But  I am not able to access the configurator web page. When i try to access it via https://192.168.19.185:1443,  it says unable to connect.

Please help me resolve this.

**Comment by louismunro** [comment]
Iptables?
This issue is closed.
Use the mailing list please.
