### ISSUE TITLE
pfmon: register_task second parameter (interval) is not expired on configuration change

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1898]
If interval for a maintenance job is changed in configuration, a simple configreload does not change it in pfmon.
pfmon needs to be restarted.

The fix should be part of a "rewrite" of pfmon.

**Comment by jrouzierinverse** [comment]
A quick test show that it does pick up the changes.
However I think the behavior you are seeing is the process is sleeping while you changed the value.
In order for the process to see the new interval it must wait for the previous interval to expire.

**Comment by dwlfrth** [comment]
Use documentation and contextual help to instruct user to restart pfmon on some changes.
