### ISSUE TITLE
Web interface doesn't start 

### ISSUE THREAD

**Issue by Mohit2345** [inverse-inc/packetfence#1905]
I have installed the packetfence on centos 7. But I am not able to access the configurator web page. When i try to access it via https://192.168.19.185:1443, it says unable to connect.
 
I tried checking whether the server is listening to port 1443, but when i run the command 
"netstat -tan|grep 1443" , it returns nothing.

Please help me resolve this.

**Comment by julsemaan** [comment]
Please use the mailing list for issues like these
