### ISSUE TITLE
LinkedIn Oauth2 source can not be saved

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1909]
Dec 16 11:48:27 httpd.admin(7855) ERROR: Caught exception in pfappserver::Controller::Config::Authentication::Source->update "Attribute (state) does not pass the type constraint because: Validation failed for 'Str' with value undef at accessor pf::Authentication::Source::LinkedInSource::state (defined at /usr/local/pf/lib/pf/Authentication/Source/LinkedInSource.pm line 29)

**Comment by jrouzierinverse** [comment]
Fixed by 947efc7ed50fcde2e1e0f31468aef0610017871e
