### ISSUE TITLE
p0f won't stat

### ISSUE THREAD

**Issue by vherrlein** [inverse-inc/packetfence#1912]
Dear All,

I installed the latest Packetfence from the inverse-inc repo by following the admin guide (https://packetfence.org/doc/PacketFence_Administration_Guide.html#_software_installation)

However after fixing issues regarding dependencies for the httpd.admin and httpd.portal, now the p0f service won't start without any error logs.

The fingerbank API Key is valid, issue #1628  doesn't correspond.

Thank you in advance for your help.

Details:
* Virtual machine, LXC
* Debian Jessie 8.6
* Packetfence 6.4.0

Commands:
* `# /usr/local/pf/bin/pfcmd service p0f start`

> Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
service|command
httpd.admin|already started
Checking configuration sanity...
[-] PROGRAM ABORT : Unexpected statement in line 1.
         Location : config_parse_line(), readfp.c:308
p0f|not started

* `# cat /usr/local/fingerbank/conf/fingerbank-p0f.fp`

> You are currently under rate-limiting. Currently, only the perl library should be rate-limited. If you aren't using it, post to the Fingerbank mailing list.

* `# dpkg -l | grep fingerbank`
> ii  fingerbank                                               3.0.1-1                    all          fingerbank

* `# /usr/local/pf/bin/pfcmd service pf start`
> Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
service|command
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
httpd.admin|start
Checking configuration sanity...
iptables|start
redis_queue|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
httpd.aaa|start
radiusd-acct|start
radiusd|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
pfqueue|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
pfdns|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
pfdhcplistener_eth1|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
pfdhcplistener_eth0|start
httpd.parking|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
httpd.portal|start
dhcpd|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
httpd.webservices|start
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
pfmon|start
[-] PROGRAM ABORT : Unexpected statement in line 1.
         Location : config_parse_line(), readfp.c:308
p0f|not started
Starting carbon-cache (instance a)
carbon-cache|start
Starting carbon-relay (instance a)
carbon-relay|start
collectd|start
statsd|start
radsniff|start
httpd.graphite|start

**Comment by vherrlein** [comment]
It seems that I've an issue with my fingerbank account.
I had to make a new one for a new API key.
After dowloading and overwritten the **fingerbank-p0f.fp** from the fingerbank site to /usr/local/fingerbank/conf folder then updated the **API key** in **/usr/local/fingerbank/conf/fingerbank.conf** file; the installation could be done from the assistant.

**Comment by julsemaan** [comment]
This isn't really normal, the file shouldn't be updated on the FS unless the download succeded.

Either the Debian package has the wrong config file or the lib is not handling the limit gracefully for p0f

Will look into it Monday

**Comment by julsemaan** [comment]
Confirmed and linked to fingerbank/perl-client#24

**Comment by julsemaan** [comment]
Fixed in fingerbank 3.0.2
