### ISSUE TITLE
Node Import Bug

### ISSUE THREAD

**Issue by xnih** [inverse-inc/packetfence#1913]
When importing via a CSV, if the owner you are assigning them to hasn't already imported devices before it fails to import them.

CSV file, 284 devices, all the same user, never imported anything before, file format:
mac, owner email, guest, 2018-01.01 00:00
284 skipped.

Take owner out, import a single entry by putting a "Default Owner" in the GUI, imports fine, then reimport the 284 record file, imports fine.

Tried this twice so far, in both cases, if the owner email address is not already in the DB somewhere (I assume) it fails.  Do a single import and put the owner in via the gui, works fine to reimport the file again afterwards.  To me I shouldn't have to do this twice to make it work.  This is with 6.4.

**Comment by julsemaan** [comment]
Looks indeed like a bug to me and I believe this was reported at some point.

Will require some investigation

**Comment by julsemaan** [comment]
@xnih 

If you apply the maintenance using:
```
# /usr/local/pf/addons/pf-maint.pl
```

You will be able to get the patch that fixes this.
