### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by resolvecomputing** [inverse-inc/packetfence#1914]
I am trying to install packetfence on a Centos system. When I execute the command as mentioned in the manual, I get the following error message. On visiting the website mentioned in the URL i find that the directory missing. 

# yum install --enablerepo=packetfence packet fence

Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager

google-chrome                                                                                                           |  951 B  00:00:00     

http://inverse.ca/downloads/PacketFence/RHEL7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

Trying other mirror.

To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

 One of the configured repositories failed (PacketFence Repository),

 and yum doesn't have enough cached data to continue. At this point the only

 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working

        upstream. This is most often useful if you are using a newer

        distribution release than is supported by the repository (and the

        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then

        just ignore the repository until you permanently enable it again or use

        --enablerepo for temporary usage:

            yum-config-manager --disable packetfence

     4. Configure the failing repository to be skipped, if it is unavailable.

        Note that yum will try to contact the repo. when it runs most commands,

        so will have to try and fail each time (and thus. yum will be be much

        slower). If it is a very temporary problem though, this is often a nice

        compromise:

            yum-config-manager --save --setopt=packetfence.skip_if_unavailable=true

failure: repodata/repomd.xml from packetfence: [Errno 256] No more mirrors to try.

http://inverse.ca/downloads/PacketFence/RHEL7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by julsemaan** [comment]
This seems to be because the variable for the release name makes it point to RHEL7Server instead of RHEL7

Edit `/etc/yum.repos.d/packetfence.repo` and change the `baseurl` under the `packetfence` section to:
http://inverse.ca/downloads/PacketFence/RHEL7/x86_64

Then do:
```
# yum clean all --enablerepo=*
# yum install packetfence --enablerepo=packetfence
```

@fdurand:
Could we get a symlink in our repos for RHEL7Server ?
Seems that with RHEL 7.3 / CentOS 7.3 this is now how `$releasever` is expanded

**Comment by fdurand** [comment]
Done

**Comment by julsemaan** [comment]
Everything was fixed
