### ISSUE TITLE
mod_evasive : cannot open shared object file

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1917]
Saw on a CentOS 7 with latest updates.

`Description: failed to start (exit status 0) -- /usr/local/pf/bin/pfcmd: httpd: Syntax error on line 229 of /usr/local/pf/var/conf/httpd.conf.d/httpd.portal: Cannot load modules/mod_evasive20.so into server: /etc/httpd/modules/mod_evasive20.so: cannot open shared object file: No such file or directory`

The actual mod_evasive20.so is replaced by mod_evasive24.so. Tried to replace it in the httpd template file but another error showed up about the command used with mod_evasive.

Didn't push the debugging further.

**Comment by jrouzierinverse** [comment]
Fixed in 9f4239ae2bac357461518fe8cb53409cb0f54d11.
It will not hurt being a +1 patch release however it will not automatically fix the problem since it will update the conf/httpd.conf.d/httpd.portal.tt.example

**Comment by dwlfrth** [comment]
Last commit is not fixing the issue.
Was able to replace the module name but there's something with the command used along with mod_evasive that seems to be different with the new module.

**Comment by jrouzierinverse** [comment]
Fix with  9f4239a and 1af8c141f8905539bfca14ed8f4ba954be59d7fa please verify.

**Comment by jrouzierinverse** [comment]
Bump
