### ISSUE TITLE
Error editing the LinkedIn Oauth2 source

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1921]
Error! An error occured while contacting the server. Please try again later.

Dec 20 15:01:34 httpd.admin(29249) ERROR: Caught exception in pfappserver::Controller::Config::Authentication::Source->update "Attribute (state) does not pass the type constraint because: Validation failed for 'Str' with value undef at accessor pf::Authentication::Source::LinkedInSource::state (defined at /usr/local/pf/lib/pf/Authentication/Source/LinkedInSource.pm line 29) line 4.
        pf::Authentication::Source::LinkedInSource::state('pf::Authentication::Source::LinkedInSource=HASH(0x7f23765c93e8)', undef) called at /usr/local/pf/html/pfappserver/lib/pfappserver/Model/Authentication/Source.pm line 57
        pfappserver::Model::Authentication::Source::update('pfappserver::Model::Authentication::Source', 'LinkedIn', 'pf::Authentication::Source::LinkedInSource=HASH(0x7f23765c93e8)', 'HASH(0x7f2360dd5158)') called at /usr/local/pf/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Authentication/Source.pm line 160
        pfappserver::PacketFence::Controller::Config::Authentication::Source::update('pfappserver::Controller::Config::Authentication::Source=HASH(...', 'pfappserver=HASH(0x7f23767bf050)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
        Catalyst::Action::execute('Moose::Meta::Class::__ANON__::SERIAL::44=HASH(0x7f23763c5cf8)', 'pfappserver::Controller::Config::Authentication::Source=HASH(...', 'pfappserver=HASH(0x7f23767bf050)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50
        Class::MOP::Method::Wrapped::__ANON__('Moose::Meta::Class::__ANON__::SERIAL::44=HASH(0x7f23763c5cf8)', 'pfappserver::Controller::Config::Authentication::Source=HASH(...', 'pfappserver=HASH(0x7f23767bf050)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 91
        Moose::Meta::Class::__ANON__::SERIAL::44::execute('Moose::Meta::Class::__ANON__::SERIAL::44=HASH(0x7f23763c5cf8)', 'pfappserver::Controller::Config::Authentication::Source=HASH(...', 'pfappserver=HASH(0x7f23767bf050)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1735

**Comment by jrouzierinverse** [comment]
This has been fixed in 947efc7ed50fcde2e1e0f31468aef0610017871e please verify
