### ISSUE TITLE
Sincronizacion packetfence with active directory

### ISSUE THREAD

**Issue by makedime** [inverse-inc/packetfence#1924]
Hello everyone

I have the packetfence configured according to the administration guide manual at the following points:

- Out of band (VLAN Enforcement)
- Freeradius configuration
- Source authentication AD
- Scripts PowerShell Active Directory Integration
- network devices with switch HP procurve 2610 with 802.1x
- Portal profiles
- Portal modules

Initially everything works fine, I can log in a desktop, I stay in the registration vlan, and through the captive portal I can authenticate with a domain account and stay in the normal vlan.
 
My problem is, always that I create a new user in active directory, or make a change to any other user, those changes do not work well through the local login on the desktop.
 
This seems like a configuration problem in the synchronization of the packetfence with the Active directory.
 
This problem happens only in the login of the desktops, In the authentication through the captive portal works fine, when I create a new user I can soon of the authentication with that user and pass from the registration vlan to the normal vlan
 
In the logs “httpd.webservice.access” and “packetfence.log” it seems to me that the synchronization between packetfence and AD is being done well through the web service at least I have no errors in the logs.
 
Can someone give me a clue how to solve this problem??

**Comment by extrafu** [comment]
Please use the mailing list for questions like that.
