### ISSUE TITLE
pf::radius::accounting isn't called anymore during accounting

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1932]
The core accounting code pf::radius::accounting isn't called anymore since we've switched to REST

This breaks accounting violations and RADIUS floating devices

Reverting back to the module packetfence instead of rest restore the correct behavior

**Comment by fdurand** [comment]
b5e83c74c9f6e64a40f8ca7ab0a5e25270c87e39

**Comment by julsemaan** [comment]
Not really sure it fixes it, the same type of issue seems to be there in handle_accounting_metadata
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/api.pm#L1380

I think we should always call pf::radius::accounting when calling radius_rest_accounting like the old behavior and not have it conditional and hidden in handle_accounting_metadata
