### ISSUE TITLE
external portal: Bogus "synchronize_locationlog" call

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1937]
`pf::web::externalportal::handle` calls `synchronize_locationlog` with a signature that does not handle the "connection_subtype" which lead to bogus entries in locationlog

https://github.com/inverse-inc/packetfence/blob/packetfence-6.4.0/lib/pf/web/externalportal.pm#L129

https://github.com/inverse-inc/packetfence/blob/packetfence-6.4.0/lib/pf/Switch.pm#L2979

**Comment by julsemaan** [comment]
This seems like it affects versions prior to 6.4

Any good reason not to cherry-pick it in prior maintenance branches ?

**Comment by dwlfrth** [comment]
Because it can't be applied as-is on versions prior to 6.4 due to the pf::externalportal class refactor.

Will do a patch for maintenance

**Comment by dwlfrth** [comment]
After quick lookup, prior to 6.4 are not affected. It was already fixed.

**Comment by julsemaan** [comment]
![image](https://cloud.githubusercontent.com/assets/3857942/21611642/ab3df27e-d19b-11e6-87ff-4e6d2ba6b327.png)
