### ISSUE TITLE
EAP-TLS unit tests (and maybe the source in general) is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1941]
When running t/unittest/authentication.t, some eap-tls source tests are failing:
```
not ok 15 - match tls source rule all conditions
#   Failed test 'match tls source rule all conditions'
#   at t/unittest/authentication.t line 123.
#     Structures begin differing at:
#          $got = undef
#     $expected = ARRAY(0x76852e0)
not ok 16 - Source id ref is found
#   Failed test 'Source id ref is found'
#   at t/unittest/authentication.t line 142.
#          got: undef
#     expected: 'tls_all'
not ok 17 - match tls_any source rule any conditions
#   Failed test 'match tls_any source rule any conditions'
#   at t/unittest/authentication.t line 146.
#     Structures begin differing at:
#          $got = undef
#     $expected = ARRAY(0x79f9a80)
not ok 18 - Source id ref is found
#   Failed test 'Source id ref is found'
#   at t/unittest/authentication.t line 165.
#          got: undef
#     expected: 'tls_any'
not ok 19 - match tls_any source rule any conditions
#   Failed test 'match tls_any source rule any conditions'
#   at t/unittest/authentication.t line 169.
#     Structures begin differing at:
#          $got = undef
#     $expected = ARRAY(0x79b37b8)
not ok 20 - Source id ref is found
#   Failed test 'Source id ref is found'
#   at t/unittest/authentication.t line 188.
#          got: undef
#     expected: 'tls_any'
```

Reverting d601a8d9c005c89a2995fed255cc73b8249f088e against the latest devel makes all these tests pass.

Trying to figure out whether the tests were faulty at the beginning or if fix broke EAP-TLS matching as a whole

NOTE: d601a8d9c005c89a2995fed255cc73b8249f088e was cherry-picked to the maintenance. If it proves to be the issue, it needs to be reverted or a corrective commit needs to be added to all maintenance branches where this was applied

**Comment by julsemaan** [comment]
b51a5a0b0df76614b7e91b8d08991972ef83082f should fix it but I'm not that confortable with the authentication matching wizardry.

Probably better if @jrouzierinverse can confirm the fix I did doesn't break the goal of the initial fix before its put in the maintenance

**Comment by jrouzierinverse** [comment]
I am not comfortable with the authentication matching wizardry either.

The real problem is I forgot to add the username to parameter list in the tests.
However your changes does not break anything in devel.
No real reason to back them out.

**Comment by julsemaan** [comment]
Adding the username to the tests did it

Reverted the patch and testing a 'no match' and all the other proper matches works
