### ISSUE TITLE
domain join: Should not update DNS records

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1947]
Most of the time, when doing a domain join through PacketFence, DNS update fails (which, at the time same saves us from some trouble). The issue comes when the DNS update succeed. It will update the PacketFence servers record on the AD with the bogus chroots IP address (169....).

We should avoid trying to update DNS record on domain join.

**Comment by nqb** [comment]
In Samba 4.7.1, the `net ads join` command supports the option `--no-dns-updates`.

**Comment by nqb** [comment]
Another option we can use directly in `smb.conf` file is `allow dns updates = disabled`

**Comment by julsemaan** [comment]
The second option seems good to me and simpler than upgrading samba

**Comment by nqb** [comment]
CentOS 7 provides Samba 4.7.1, sorry if my comment was unclear.

**Comment by julsemaan** [comment]
second option still seems simpler IMO since it doesn't require us to bump up the requirement for the samba version

**Comment by nqb** [comment]
Debian 8.11 provides Samba 4.2.14 with `allow dns updates = disabled` but not `--no-dns-updates` : ite missa est.

**Comment by nqb** [comment]
After few tests, I guess that `allow dns updates = disabled` is an option related to Samba 4 DC when its works as a DNS server. That option seems not applicable in our case (when doing `net ads join`). 

We must use `--no-dns-updates` option. However, this option has been added by Red Hat on its Samba packages (see [7.3 Release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.3_release_notes/#idm140113933333680)). This option is not part of the Samba project. We need to find a solution for Debian.

Tested workaround to avoid DNS updates: if`/etc/hosts` doesn't contain an entry that **starts** with a FQDN, `net ads join` will not perform DNS update (see below).
```
# will try to perform DNS update for foo.example.com if possible
10.0.0.1 foo.example.com foo

# will fail trying to perform DNS update
10.0.0.1 foo foo.example.com
```

**Comment by nqb** [comment]
`--no-dns-updates` is available in Debian Stretch. This issue can be fixed.

**Comment by rcmcdonald91** [comment]
Any update on this issue? Is it something that can be fixed?

**Comment by rcmcdonald91** [comment]
Fixable?
