### ISSUE TITLE
Sources condition for current time does not allow a date

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1953]
As things stand, one can define a rule for an authorization source based on the current time, but the time can only be expressed as HH:MM.

It would be useful to be able to specify rules based on the date.
Clients often request special authorization during (e.g.) summer, holidays etc.

**Comment by jrouzierinverse** [comment]
@louismunro did #1969 fix the issue?

**Comment by dwlfrth** [comment]
@louismunro said it's fixed
