### ISSUE TITLE
Portal: Option to force (and hide) SMS mobile provider

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1958]
We should find a way to 'hardcode' the provider for the user based on an admin requirement.

Ex: A home made SMTP interface which should handle all requests

User shouldn't have the option to choose a mobileprovider and the server should select it automatically.

Now, only little question is, should this be in the source (by leaving only 1 provider) or a configuration of the portal module where you could force a provider

**Comment by dwlfrth** [comment]
We should also maybe review the way to manage the SMS providers
