### ISSUE TITLE
Enabled to edit a portal profile under Debian

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1964]
When we click on a portal profile to edit it, if there a filter defined then we have this error:

Jan 18 15:04:35 httpd.admin(23245) ERROR: Caught exception in pfappserver::Controller::Config::Profile->view "Can't use string ("ssid:Boby") as a HASH ref while "strict refs" in use at /usr/share/perl5/HTML/FormHandler/InitResult.pm line 124." (pfappserver::PacketFence::Controller::Root::end)

**Comment by jrouzierinverse** [comment]
libhtml-formhandler-perl
Needs to be upgraded 0.40019

**Comment by jrouzierinverse** [comment]
Fixed the version in commit  dbfeaf6c4a98ffc84f3d6327846104fb3cbf271c
