### ISSUE TITLE
Phone number is not cleaned during the SMS pre-registration process

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1966]
Once you do pre-registration with the SMS source you end up like this:

Created account (123) 456-789

Details :

Nom d'utilisateur : (123) 456-789
Mot de passe : orbeaupscua
Courriel : email@domain.com
set_role : guest
set_access_duration : 1D

**Comment by whitx** [comment]
Tested at the moment and that does not happen with devel.
