### ISSUE TITLE
Radius disconnect doesn't work on the Ruckus switch module

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1971]
The deauthentication doesn't work if we send the accounting session ID:

#Fetching the acct-session-id
    my $dynauth = node_accounting_dynauth_attr($mac);

    $logger->debug("deauthenticate $mac using RADIUS Disconnect-Request deauth method");
    return $self->radiusDisconnect(
        $mac, { 'Acct-Session-Id' => $dynauth->{'acctsessionid'}, 'User-Name' => $dynauth->{'username'} },

The solution that works:

#Fetching the acct-session-id
    my $dynauth = node_accounting_dynauth_attr($mac);

    $logger->debug("deauthenticate $mac using RADIUS Disconnect-Request deauth method");
    return $self->radiusDisconnect(
    $mac, { 'User-Name' => $dynauth->{'username'} },

@dwlfrth suggested that we do check the ruckus version to keep the old deauth way for older Ruckus ZoneDirector.

**Comment by extrafu** [comment]
Status on this?

**Comment by jrouzierinverse** [comment]
@dwlfrth which versions of ruckus do we need to support with the old way of doing things?

**Comment by digitalair** [comment]
Hello. 
We are seeing this now with a ZD3000 ver 9.13 and PacketFence 7.2
[Radius Disconnect Example Ruckus ZD3000 ver 9.13.zip](https://github.com/inverse-inc/packetfence/files/1363169/Radius.Disconnect.Example.Ruckus.ZD3000.ver.9.13.zip)
