### ISSUE TITLE
Configurator: Services always showing as starting

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1972]
When starting services in the configurator, they always show as 'Starting' even though calls to the admin process occur and succeed.

They just don't seem to be processed.

When all services are started, it will tell you its done and redirect you to the admin so that part works.
The part that doesn't work is while its starting, its not updating the status of the started services on the page

To replicate:
- Stop packetfence from pfcmd
- Remove currently-at
- Start admin
- Go through configurator
- Start services at the end
- Look at things not being updated

**Comment by jrouzierinverse** [comment]
I am assuming this is for centos 7?

**Comment by julsemaan** [comment]
this is correct

**Comment by jrouzierinverse** [comment]
This is fixed by a15392cf632a6dcc628fa9db01a54f3bf18a63bf
