### ISSUE TITLE
Admin: can't display any page

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#1976]
I've got upgrade my dev machine.

I've done:

- redis-cli FLUSHALL
- restart pfconfig
- restart packetfence

Jan 23 15:42:20 httpd.admin(2340) ERROR: Caught exception in pfappserver::Controller::Config::Switch->begin "Can't locate object method "addToLoadedConfigs" via package "pf::IniFiles" at /usr/local/pf/lib/pf/config/cached.pm line 379." (pfappserver::PacketFence::Controller::Root::end)

Jan 23 16:04:23 httpd.admin(3283) ERROR: Caught exception in pfappserver::Controller::Config::Switch->list "Can't locate object method "HasChanged" via package "pf::config::cached" at /usr/local/pf/lib/pf/ConfigStore.pm line 105." (pfappserver::PacketFence::Controller::Root::end)

**Comment by whitx** [comment]
bin/pfcmd cache configfiles clear

**Comment by jrouzierinverse** [comment]
We should handle this in upgrade path or this could cause some problems when people upgrade.
