### ISSUE TITLE
admin GUI: Graph to represent online/offline endpoints

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1981]
That was being offered in a previous version of PacketFence but have been removed due to the online/offline refactor.

Would be great to reintegrate such graphic.

ref: 6894

**Comment by julsemaan** [comment]
I think this will be addressed in 8.0 in the new dashboard

**Comment by extrafu** [comment]
@satkunas Can you do this and put it in the main dashboard? (Status > Overview > Dashboard)

**Comment by satkunas** [comment]
@julsemaan @extrafu what **was** an endpoint? Is this referring to a node? Or an upstream radius server? Or something else?

**Comment by extrafu** [comment]
Yes, endpoint == node

There's already a online/offline "report" available from the Node module of PacketFence.

**Comment by extrafu** [comment]
Can we close this one?

**Comment by julsemaan** [comment]
It should be closed automagically whenever #3113 gets merged since @satkunas referenced it
