### ISSUE TITLE
admin GUI: Node search pagination

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#1982]
We were able to see the last page of a node search result listing. It have been removed for performances issues.

Would be great to reintegrate it.

ref: 6897

**Comment by julsemaan** [comment]
I'll assign @cgx which is redoing the node page in the new admin

He can analyse whether or not this will be performance efficient but I doubt it will be

**Comment by cgx** [comment]
I've discussed this issue with @jrouzierinverse. He needs to do some tests.

**Comment by jrouzierinverse** [comment]
I am closing this as this will not be done.
