### ISSUE TITLE
Debian 8: Can't locate Net/Syslog.pm in @INC

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1984]
Error in packetfence.log with devel installed as of today:

`Couldn't require pf::firewallsso::PaloAlto : Can't locate Net/Syslog.pm in @INC (you may need to install the Net::Syslog module)
`

**Comment by jrouzierinverse** [comment]
This has been added to the obs please update the debian repo.
libnet-syslog-perl_0.04

**Comment by tlaurion** [comment]
Have we mispelled?
@jrouzierinverse 
https://github.com/inverse-inc/packetfence/blob/devel/debian/control#L132

It seems that we don't need "Net::Syslogd" (no reference) but need "Net::Syslog"
