### ISSUE TITLE
Dependency Issue on CentOS 7.3 with EPEL Repository

### ISSUE THREAD

**Issue by markuspachali** [inverse-inc/packetfence#2009]
Hi all,

I've noticed a dependency issue on CentOS 7.3 when also the EPEL repository is installed and activated.
On a fresh installed CentOS 7.3 there are some conflicting dependencies between the EPEL and the packetfence repository. After running "yum update && yum install packetfence" I got the following error:

--> Finished Dependency Resolution
Error: Package: collectd-disk-5.6.1-14.1.x86_64 (packetfence)
           Requires: collectd(x86-64) = 5.6.1-14.1
           Available: collectd-5.5.0-14.2.x86_64 (packetfence)
               collectd(x86-64) = 5.5.0-14.2
           Available: collectd-5.6.1-14.1.x86_64 (packetfence)
               collectd(x86-64) = 5.6.1-14.1
           Installing: collectd-5.7.1-1.el7.x86_64 (epel)
               collectd(x86-64) = 5.7.1-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

If I try to install with "--skip-broken" yum told me, that there are 589 packages canceled because of dependency issues.

Based on that amount of issues it seems not safe for me to disable EPEL just for the installation of packetfence and enable it again after the installation is done. The next yum update with EPEL enabled will probably crash the whole installation.

Is there any way to run a packetfence installation with also EPEL repository enabled?  Having a system running without EPEL is very hard because there a some very useful tools included.

Best regards,
Markus

**Comment by louismunro** [comment]
We don't recommend you install anything else on the PacketFence system.
It's not really the place to host your personal blog or other software.

Alternatively, you can pin rpms to a specific version.
