### ISSUE TITLE
"Error! An error condition has occured. See server side logs for details." on dhcp network page

### ISSUE THREAD

**Issue by maria2027** [inverse-inc/packetfence#2011]
on /admin/configuration#configuration/interfaces, click on "default network: x.x.x.x", then Save.

Boom, error :-(
If I change dhcp_start= in networks.conf, it will change back after reboot.

Debian Jessie, pf  6.5.0-1 with pf-maint.pl executed.

**Comment by julsemaan** [comment]
This was more an issue for the mailing list than for Github
