### ISSUE TITLE
SSID not showing in the node list

### ISSUE THREAD

**Issue by jeff-cook** [inverse-inc/packetfence#2015]
When viewing the node list (and showing the SSID column) the SSID column is empty.  I can see the SSID details in the node details under Info and Location, so I know the information is with in PacketFence.  Also the SSIDs does show correctly in the Reports module.

**Comment by jrouzierinverse** [comment]
Which version of packetfence are you running?

**Comment by jeff-cook** [comment]
We are running 6.3.0

**Comment by jrouzierinverse** [comment]
This has been fixed in current releases.
