### ISSUE TITLE
WMI error : "Couldn't render template "node/tab_process.tt: file error - node/tab_process.tt: not found""

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2025]
To replicate:

1. Add a wmi "Scan Engine"
1.  Select Firewall and Antivirus
1. Add scanner to Portal Profile
1. Have a Windows machine generate some DHCP traffic in a reachable PF VLAN (We need that machine to be tagged as a Windows machine per FingerBank)
1. Go to "node" in Admin GUI, select Windows corresponding MAC, go to WMI Rules tab, click "Run scan for XYZ FireWall"
1. Voila.

If there is an error connecting to that machine, we hit the generation of tab_process from a template that doesn't exist: "node/tab_process.tt"

**Comment by julsemaan** [comment]
This means #1771 wasn't fixed properly

**Comment by whitx** [comment]
It seems to happen only when there is no IP in the IPlog for this device, I'll have a look at it
