### ISSUE TITLE
PacketFence 6.5.0 on fresh Debian Jessie install.

### ISSUE THREAD

**Issue by yawor** [inverse-inc/packetfence#2027]
Hi,

I've stumbled upon some issues when trying to install and run PacketFence 6.5.0 on Debian Jessie.

First of all, package installation when through without errors. But after installation the packetfence service could not start. By checking journal I've found that PF could not find `Switch.pm` module. I was able to fix that by installing `libswitch-perl` package (maybe it should be added as a dependency?).

But I still can't access admin panel at port 1443 to go through the configuration wizard because packetfence service exits with following error:
```
Feb 16 18:26:06 cp pfcmd[1637]: FATAL - please define exactly one management interface
Feb 16 18:26:06 cp pfcmd[1637]: WARNING - internal network(s) not defined!
Feb 16 18:26:06 cp pfcmd[1637]: FATAL - Unable to connect to your database. Please verify your connection settings in conf/pf.conf and make sure that it is started.
Feb 16 18:26:06 cp pfcmd[1637]: WARNING - networks.conf is empty but services.dhcpd is enabled. Disable it to remove this warning.
Feb 16 18:26:06 cp pfcmd[1637]: FATAL - Cannot connect to database to check schema version: unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/pf/version.pm line 42.
Feb 16 18:26:06 cp systemd[1]: packetfence.service: control process exited, code=exited status=255
Feb 16 18:26:07 cp systemd[1]: Failed to start PacketFence Service.
Feb 16 18:26:07 cp systemd[1]: Unit packetfence.service entered failed state.
```
I don't have pf user and database yet because I wasn't able to run the configuration wizard yet.

**Comment by lievenm** [comment]
The problem is systemd killing the httpd.admin service because the others give errors. Start it yourself with 'pfcmd service httpd.admin start'
