### ISSUE TITLE
Configurator requires a radius interface to be defined

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2035]
![image](https://cloud.githubusercontent.com/assets/193997/23218014/0afbeada-f8e9-11e6-9ffd-1f165d9c905d.png)

Even if we don't want or need one.

**Comment by julsemaan** [comment]
I took the liberty to do a fix for this given the annoying nature of the bug:
efa8597d57b31dbd2cbdafd63066c16c3f86b3af

@fdurand, can you confirm that the fix won't break what you intended to do and close the issue after

**Comment by dwlfrth** [comment]
Fixed
