### ISSUE TITLE
pf-mariadb - mysqld spawner

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2046]
If you kill that process it will try to restart an new mysqld_safe process in a loop:

Feb 24 16:52:04 superfence.inverse.local mariadb[14091]: MariaDB is not alive
Feb 24 16:52:04 superfence.inverse.local mariadb[14091]: Starting MySQL with command: mysqld_safe --defaults-file=/usr/local/pf/var/conf/mariadb.conf
Feb 24 16:52:05 superfence.inverse.local mariadb[14091]: 170224 16:52:05 mysqld_safe A mysqld process already exists
Feb 24 16:52:06 superfence.inverse.local mariadb[14091]: Failed starting with mode: standalone
Feb 24 16:52:06 superfence.inverse.local mariadb[14091]: MariaDB is not alive
Feb 24 16:52:06 superfence.inverse.local mariadb[14091]: Starting MySQL with command: mysqld_safe --defaults-file=/usr/local/pf/var/conf/mariadb.conf
Feb 24 16:52:07 superfence.inverse.local mariadb[14091]: 170224 16:52:07 mysqld_safe A mysqld process already exists

**Comment by julsemaan** [comment]
Did you kill `pfmariadb` or `pfmariadb - mysql spawner` ?
With -9 or gracefully ?

**Comment by louismunro** [comment]
I can confirm this one.
killing the pfmariadb - mysql spawner with signal 11 leaves mysqld_safe running.

**Comment by julsemaan** [comment]
check if edadf97c8726e145f3191f6a235ac24b017c556f fixes it

On my side I was able to get it to work without any issue

**Comment by julsemaan** [comment]
Zayme said its ok now
