### ISSUE TITLE
Unable to connect to controllers using SSH 

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2049]
Due to tied file handles in logging all deauthentication that relies on SSH fails.

Example error message in logs:

Feb 27 14:48:21 pfqueue(22445) ERROR: [mac:c8:f7:33:11:75:b5] Unable to connect to 10.9.64.43 using SSH. Failed with Failed to get first prompt at /usr/local/pf/lib/pf/Switch/Trapeze.pm line 142

**Comment by dwlfrth** [comment]
Do not backport since we gonna leverage on systemd capabilities.
@jrouzierinverse remove trapper
