### ISSUE TITLE
Read-only mode admin warning

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2052]
This is what it looks like:
![image](https://cloud.githubusercontent.com/assets/3857942/23382598/cd4a38aa-fd10-11e6-9bfd-f212f20f80b7.png)

I'd suggest we make it a bit prettier from a styling perspective as it seems a bit rough

**Comment by jrouzierinverse** [comment]
What does prettier mean? Any suggestions?

**Comment by julsemaan** [comment]
A static warning would fit better (IMO) at the bottom instead of the top of the page

And the rounded corners without any margin on the element make it look out of place (still IMO)

**Comment by jrouzierinverse** [comment]
Being out of place is a not a bug  it's a feature.
How else would someone notice it?

**Comment by julsemaan** [comment]
What I meant was that it would be a better fit at the bottom. That's it

If that is good enough and I'm the only one that find its lacking a bit of polishing, we'll just go ahead and close it

**Comment by julsemaan** [comment]
@lzammit opened #2168 to discuss it in the new admin
