### ISSUE TITLE
iptables service doesn't reload rules using systemd unit

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2058]
When starting/stopping the packetfence-iptables unit, it doesn't remove or add any of the rules

For example, stop the services (rules are still there)

Then add a rule in iptables.conf and start it and the new rule will not be there

**Comment by louismunro** [comment]
Pish, posh, who needs firewalls anyway...

All right, I'll take a look.

**Comment by louismunro** [comment]
Yes, it does reload rules. 
At least for me it does.
I'll have to look at your system.
Calling this as a Zammitbug for now.

**Comment by julsemaan** [comment]
Zayme rebooted my machine and everything started working

Jokes aside, it was a missing chain in my iptables.conf which made my pre-systemd rules stay there forever and ever
