### ISSUE TITLE
Pfconfig: two processes after a brand new install

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2063]
[root@superfence ~]# ps -edf | grep pfconfig
pf        1540     1  0 09:49 ?        00:00:04 pfconfig
root      2614  2529  0 09:58 pts/4    00:00:00 grep --color=auto pfconfig
root     20526     1  0 09:48 ?        00:00:00 pfconfig

[root@superfence ~]# systemctl status packetfence-config
● packetfence-config.service - PacketFence Config Service
   Loaded: loaded (/usr/lib/systemd/system/packetfence-config.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-03-01 09:49:56 EST; 8min ago
 Main PID: 1540 (pfconfig)
   CGroup: /packetfence.slice/packetfence-base.slice/packetfence-config.service
           └─1540 pfconfig

Mar 01 09:50:46 superfence.inverse.local pfconfig[1540]: Unknown key config::Pf;captiveportalUnknown key resource::guest_self_r...che !
Mar 01 09:51:02 superfence.inverse.local pfconfig[1540]: Unknown key config::Pf;captiveportalUnknown key resource::guest_self_r...che !
Mar 01 09:51:02 superfence.inverse.local pfconfig[1540]: Could not write namespace interfaces::inline_enforcement_nets to L2 cache !
Mar 01 09:51:04 superfence.inverse.local pfconfig[1540]: Could not write namespace config::Pfqueue to L2 cache !
Mar 01 09:51:29 superfence.inverse.local pfconfig[1540]: Could not write namespace resource::accounting_triggers to L2 cache !
Mar 01 09:51:44 superfence.inverse.local pfconfig[1540]: Could not write namespace FilterEngine::Violation to L2 cache !
Mar 01 09:55:29 superfence.inverse.local pfconfig[1540]: Could not write namespace config::Provisioning to L2 cache !
Mar 01 09:58:13 superfence.inverse.local pfconfig[1540]: Could not write namespace config::Firewall_SSO to L2 cache !
Mar 01 09:58:13 superfence.inverse.local pfconfig[1540]: Could not write namespace config::Scan to L2 cache !
Mar 01 09:58:13 superfence.inverse.local pfconfig[1540]: Could not write namespace FilterEngine::DhcpScopes to L2 cache !
Hint: Some lines were ellipsized, use -l to show in full.

The pfconfig that runs with PF is the one managed by systemd

**Comment by julsemaan** [comment]
Found zis in zi zpek file:
https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L759

@louismunro, could you confirm if this whole dance is still necessary with systemd

BTW, rebooting would fix the issue so I'm adding the zammitbug label

**Comment by julsemaan** [comment]
@louismunro 

Bump, can you check my comment above and see if you're ok with removing the line I pointed
