### ISSUE TITLE
The Proper behavior for the regex parser rule matching and ip <=> mac translation failure

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2068]
Scenario:

If a rule's regex matches a line but the iplog translation failed which of the following behaviors are prefered?

1. Skip the all the actions for that rule
1. Send undef in place of the mac or ip
1. Send an empty string in place of the mac or ip
1. Only send the actions that do not require the missing field in this case ip and mac.
1. Or something else..

**Comment by julsemaan** [comment]
I would say 4 and a warning in the logs for the actions that can't be sent

**Comment by jrouzierinverse** [comment]
Any other thoughts?

**Comment by jrouzierinverse** [comment]
Had a conversation with @louismunro and @fdurand they both prefer 1 (with it logging of course).
Since it will be easier to debug.

**Comment by julsemaan** [comment]
As they say in China:
Nah prahbem

**Comment by dwlfrth** [comment]
@jrouzierinverse "do that real quick"
