### ISSUE TITLE
Domains configuration succeeds but GUI is unhappy

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2071]
Configuring an AD domain in the GUI seems to succeed (chroots created, systemd starts winbind).

Nevertheless the GUI seems to indicate it failed with "an error occured":

![image](https://cloud.githubusercontent.com/assets/193997/23568189/748dee18-0027-11e7-9dbf-a679e3893a8b.png)

**Comment by louismunro** [comment]
A reload does show the domain as correctly configured though.

**Comment by julsemaan** [comment]
Could you provide the output of httpd.admin.error and httpd.admin.log before you go to ZammitLand ?

**Comment by louismunro** [comment]
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177.
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177.
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177.
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177.
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177, <DATA> line 1003.
[Fri Mar  3 15:25:52 2017] -e: Warning: Log message argument #1 undefined at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50.
[Fri Mar  3 15:25:52 2017] -e: Use of uninitialized value in join or string at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender.pm line 177.
Created symlink from /etc/systemd/system/packetfence.target.wants/packetfence-winbindd.service to /usr/lib/systemd/system/packetfence-winbindd.service.
**DNS update failed: NT_STATUS_INVALID_PARAMETER**


So probably just the DNS update failing.

**Comment by julsemaan** [comment]
even when the dns update fails, it should return anyway as it fails 90% of the time

I'll take a look into this

**Comment by julsemaan** [comment]
Works on my machine

Closed won't fix

**Comment by julsemaan** [comment]
@louismunro, is this something you can replicate

Didn't hear complains about it in the latest devel

**Comment by dwlfrth** [comment]
@louismunro check and "close" ;)

**Comment by louismunro** [comment]
Still present in my testing environment.

**Comment by whitx** [comment]
I am able to replicate it, on debian only, will look into it

**Comment by julsemaan** [comment]
You know what they say about Debian

**Comment by dwlfrth** [comment]
Black and yellow ?
https://www.youtube.com/watch?v=UePtoxDhJSw

**Comment by whitx** [comment]
This is a timeout issue in the browser, will need to be worked on for 7.1. At the moment we could try a reload of the page just before the timeout happens (2min). The domains joins in itself works fine.

**Comment by louismunro** [comment]
After looking at it with ZammitCorp's International Man of Mystery, this looks related to my testing environment being dog slow. 
It might not even affect people in the real world.
At most a documentation item telling people to reload if it fails would do it.
