### ISSUE TITLE
Packaging for govendor and golang

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2073]
We need to package go and govendor to aid to make easier to develop and install.

**Comment by julsemaan** [comment]
Had that discussion with @louismunro last week and we concluded that we shouldn't package it and instead used the techniques shown in the demo to fetch the proper version directly from the go download site.

We could re-address this in a brainstorm this week and I'll play devils advocate while @louismunro is meeting the pope and going to ZammitLand

I have nothing against it myself but my understanding was that it was an unwanted in our packaging system

**Comment by jrouzierinverse** [comment]
My major concern I have is since it is not automatically installed.
It adds an extra step when someone first applies patches from the maintenance branch.

**Comment by julsemaan** [comment]
He would need its go environment setup properly and to compile the binaries after applying the maintenance branch so I'm not sure the current maintenance branch way of doing this should apply 1:1 

We should instead opt for a way to push the binaries as well as source patches. This way, if someone doesn't have custom in his binaries, he can use them without having to recompile the binary himself.

We definitively need to sit down and establish the patching strategy for our Golang services but I'd way for @louismunro's input as well

**Comment by dwlfrth** [comment]
Discuss later for "Go best practices"

**Comment by dwlfrth** [comment]
We need a copy

**Comment by julsemaan** [comment]
Moving to 8.1

**Comment by julsemaan** [comment]
Created a script on pfbuilder to mirror the dependencies via govendor and runs nightly
