### ISSUE TITLE
haproxy: had to remove the chroot

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2078]
To use the external-check command to monitor MariaDB, I had to remove the chroot option in haproxy.

This doesn't seem like it is mandatory and acts as a safety net in case of an haproxy vulnerability

I git blamed it and it points to the initial commit of haproxy by @fdurand 

Anybody (especially @fdurand) objects to the removal of that option ?

**Comment by fdurand** [comment]
Not against.

**Comment by julsemaan** [comment]
Was removed
