### ISSUE TITLE
Need to update Net::SSH2

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2083]
Had issues with Juniper switches and Net::SSH2

Everything was connecting fine and all commands were accepted but the commands weren't actually sent to the switch.

Fixed it by updating Net::SSH2 to 0.63

We should update it in our repos as well

**Comment by extrafu** [comment]
I *think* that was also affecting us for Extricom equipment - @louismunro and @whitx could confirm.

**Comment by julsemaan** [comment]
Lets put it on standby then since one is at ZammitLand and the other one at XlaxLand

**Comment by dwlfrth** [comment]
Missing signature on package

**Comment by louismunro** [comment]
I can't confirm or deny.
I have one client using Juniper but only for Wireless Controllers and 0.45 seems to work for them.

**Comment by julsemaan** [comment]
Signature should be fixed now, will have to confirm with a new install or upgrade

**Comment by julsemaan** [comment]
Just tested and it works. This is fixed now
