### ISSUE TITLE
Nodes not assigned to user when using Authentication::Password module

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#2091]
I have created an Authentication::Password module using a local httpaswd file as source to login guest users.
The users are logged in succesfully but the nodes are not assigned to username configured in the portal module, all nodes are assigned to default user.

**Comment by rokkhan** [comment]
Is there anyone else having this issue?

**Comment by rokkhan** [comment]
any update?

**Comment by julsemaan** [comment]
will try to replicate and look into it shortly

**Comment by rokkhan** [comment]
thanks a lot!! please feel free to ask any test or info
greetings

2017-05-24 14:33 GMT+02:00 Julien Semaan <notifications@github.com>:

**Comment by dwlfrth** [comment]
Looking at it

**Comment by dwlfrth** [comment]
It worked just fine on my side.
Created an htpasswd file with the corresponding authentication source.
Used the username from that file on the PacketFence captive-portal and matched the configured rule.
PacketFence management GUI shows my device sa registered with the username from the file.

Please advise

**Comment by julsemaan** [comment]
@rokkhan 

Are you willing to troubleshoot this with us

Otherwise, we'll close this
