### ISSUE TITLE
Login attempts limit are not zeroed when the device has been deregistered

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#2092]
When i deregister a node the login attempts limit are not reseted so I always get an error saying that login attempts limit have been reached and I can not re-register the device again.

**Comment by jrouzierinverse** [comment]
The login attempts are tied to the portal session based off the mac which will expire in 6 hours.
We would need to look into how to handle this use case more elegantly.

**Comment by rokkhan** [comment]
Is there anyway to reset this attempts manually?

**Comment by julsemaan** [comment]
@jrouzierinverse 

Can you provide input on this and close it afterwards

**Comment by jrouzierinverse** [comment]
This has been fixed by using the block_interval
