### ISSUE TITLE
Mariadb Read-Only: mac authentication not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2095]
Controller: Ruckus
Device: IPhone registered
Method: Radius mac-authentication
Mariadb mode: read-only

I've registered a device and apply the read-only mode on mariadb.

MariaDB [(none)]> FLUSH TABLES WITH READ LOCK;
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> SET GLOBAL read_only = 1;
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> SELECT @@global.read_only;
+--------------------+
| @@global.read_only |
+--------------------+
|                  1                |
+--------------------+
1 row in set (0.00 sec)

Once the RO was applied, I reconnected the device and I got that error:

Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] handling radius autz request: from switch_ip => (10.0.0.14), connection_type => Wireless-802.11-NoEAP,switch_mac => (50:a7:33:71:cf:bc), mac => [11:22:33:44:55:66], port => 0, username => "11:22:33:44:55:66", ssid => ZamOpen-7 (pf::radius::authorize)
Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)
Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] Connection type is WIRELESS_MAC_AUTH. Getting role from node_info (pf::role::getRegisteredRole)
Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] Username was defined "11:22:33:44:55:66" - returning role 'default' (pf::role::getRegisteredRole)
Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] PID: "lzammit", Status: reg Returned VLAN: (undefined), Role: default (pf::role::fetchRoleForNode)
Mar 15 14:33:59 httpd.aaa(3049) INFO: [mac:11:22:33:44:55:66] (10.0.0.14) Added VLAN 20 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Mar 15 14:33:59 httpd.aaa(3049) ERROR: [mac:11:22:33:44:55:66] database query failed with non retryable error: The MariaDB server is running with the --read-only option so it cannot execute this statement (errno: 1290) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?] (pf::dal::db_execute)
Mar 15 14:33:59 httpd.aaa(3049) ERROR: [mac:11:22:33:44:55:66] radius authorize failed with error: Can't locate object method "error" via package "logger" (perhaps you forgot to load "logger"?) at /usr/local/pf/lib/pf/radius.pm line 304.
 (pf::api::radius_authorize)
Mar 15 14:33:59 httpd.aaa(3049) WARN: [mac:11:22:33:44:55:66] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 48.
 (pf::radius::rest::format_response)
Mar 15 14:33:59 httpd.aaa(3049) WARN: [mac:11:22:33:44:55:66] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
 (pf::radius::rest::format_response)

**Comment by extrafu** [comment]
@jrouzierinverse Fix these ASAP as they come.

**Comment by lzammit** [comment]
Same error:

Mar 15 15:03:13 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] handling radius autz request: from switch_ip => (10.0.0.14), connection_type => Wireless-802.11-NoEAP,switch_mac => (50:a7:33:71:cf:bc), mac => [78:4f:43:33:45:f6], port => 0, username => "78:4f:43:33:45:f6", ssid => ZamOpen-7 (pf::radius::authorize)
Mar 15 15:03:15 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)
Mar 15 15:03:15 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Connection type is WIRELESS_MAC_AUTH. Getting role from node_info (pf::role::getRegisteredRole)
Mar 15 15:03:15 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Username was defined "78:4f:43:33:45:f6" - returning role 'default' (pf::role::getRegisteredRole)
Mar 15 15:03:15 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] PID: "lzammit", Status: reg Returned VLAN: (undefined), Role: default (pf::role::fetchRoleForNode)
Mar 15 15:03:15 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] (10.0.0.14) Added VLAN 20 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Mar 15 15:03:15 httpd.aaa(5244) ERROR: [mac:78:4f:43:33:45:f6] database query failed with non retryable error: The MariaDB server is running with the --read-only option so it cannot execute this statement (errno: 1290) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?] (pf::dal::db_execute)
Mar 15 15:03:15 httpd.aaa(5244) ERROR: [mac:78:4f:43:33:45:f6] Cannot save 78:4f:43:33:45:f6 error (500) (pf::radius::authorize)

Please close if you are sure that it's fixed and let me know when I can test it, thanks.

**Comment by jrouzierinverse** [comment]
Those errors are expected in readonly mode.
Are there any errors anywhere else such as the radius.log

**Comment by lzammit** [comment]
Ok, here the radius.log:

Wed Mar 15 15:13:12 2017 : Info: rlm_sql (sql): Closing connection (7): Hit idle_timeout, was idle for 597 seconds
Wed Mar 15 15:13:12 2017 : Info: rlm_sql (sql): Closing connection (6): Hit idle_timeout, was idle for 597 seconds
Wed Mar 15 15:13:12 2017 : Info: rlm_sql (sql): Opening additional connection (8), 1 of 64 pending slots used
Wed Mar 15 15:13:12 2017 : ERROR: (1) sql: ERROR: rlm_sql_mysql: ERROR 1290 (The MariaDB server is running with the --read-only option so it cannot execute this statement): HY000
Wed Mar 15 15:13:12 2017 : Info: Need 2 more connections to reach min connections (3)
Wed Mar 15 15:13:12 2017 : Info: rlm_sql (sql): Opening additional connection (9), 1 of 63 pending slots used
Wed Mar 15 15:13:12 2017 : ERROR: (1) sql_reject: ERROR: rlm_sql_mysql: ERROR 1290 (The MariaDB server is running with the --read-only option so it cannot execute this statement): HY000
Wed Mar 15 15:13:12 2017 : Auth: (1) Rejected in post-auth: [78:4f:43:33:45:f6] (from client 10.0.0.14 port 0 cli 78:4f:43:33:45:f6)

I am not able to reproduce it for sone reason.

**Comment by jrouzierinverse** [comment]
Is the device not being registered or are you just seeing errors in the log?

**Comment by lzammit** [comment]
I'm trying to connect my device to an open SSID and I got kicked:

Wed Mar 15 16:36:21 2017 : Info: rlm_rest (rest): Closing connection (9): Hit idle_timeout, was idle for 2990 seconds
Wed Mar 15 16:36:21 2017 : Info: rlm_rest (rest): Closing connection (10): Hit idle_timeout, was idle for 2990 seconds
Wed Mar 15 16:36:21 2017 : Info: rlm_rest (rest): Opening additional connection (11), 1 of 64 pending slots used
Wed Mar 15 16:36:21 2017 : Info: Need 2 more connections to reach min connections (3)
Wed Mar 15 16:36:21 2017 : Info: rlm_rest (rest): Opening additional connection (12), 1 of 63 pending slots used
Wed Mar 15 16:36:21 2017 : Info: rlm_sql (sql): Closing connection (11): Hit idle_timeout, was idle for 2990 seconds
Wed Mar 15 16:36:21 2017 : Info: rlm_sql (sql): Closing connection (10): Hit idle_timeout, was idle for 2990 seconds
Wed Mar 15 16:36:21 2017 : Info: rlm_sql (sql): Opening additional connection (12), 1 of 64 pending slots used
Wed Mar 15 16:36:21 2017 : ERROR: (3) sql: ERROR: rlm_sql_mysql: ERROR 1290 (The MariaDB server is running with the --read-only option so it cannot execute this statement): HY000
Wed Mar 15 16:36:21 2017 : Info: Need 2 more connections to reach min connections (3)
Wed Mar 15 16:36:21 2017 : Info: rlm_sql (sql): Opening additional connection (13), 1 of 63 pending slots used
Wed Mar 15 16:36:21 2017 : ERROR: (3) sql_reject: ERROR: rlm_sql_mysql: ERROR 1290 (The MariaDB server is running with the --read-only option so it cannot execute this statement): HY000
Wed Mar 15 16:36:21 2017 : Auth: (3) Rejected in post-auth: [78:4f:43:33:45:f6] (from client 10.0.0.14 port 0 cli 78:4f:43:33:45:f6)

That device is registered

**Comment by lzammit** [comment]
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] handling radius autz request: from switch_ip => (10.0.0.14), connection_type => Wireless-802.11-NoEAP,switch_mac => (50:a7:33:71:cf:bc), mac => [78:4f:43:33:45:f6], port => 0, username => "78:4f:43:33:45:f6", ssid => ZamOpen-7 (pf::radius::authorize)
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Instantiate profile ZamOpen (pf::Portal::ProfileFactory::_from_profile)
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Connection type is WIRELESS_MAC_AUTH. Getting role from node_info (pf::role::getRegisteredRole)
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] Username was defined "78:4f:43:33:45:f6" - returning role 'default' (pf::role::getRegisteredRole)
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] PID: "lzammit", Status: reg Returned VLAN: (undefined), Role: default (pf::role::fetchRoleForNode)
Mar 15 16:36:21 httpd.aaa(5244) INFO: [mac:78:4f:43:33:45:f6] (10.0.0.14) Added VLAN 20 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Mar 15 16:36:21 httpd.aaa(5244) ERROR: [mac:78:4f:43:33:45:f6] database query failed with non retryable error: The MariaDB server is running with the --read-only option so it cannot execute this statement (errno: 1290) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?] (pf::dal::db_execute)
Mar 15 16:36:21 httpd.aaa(5244) ERROR: [mac:78:4f:43:33:45:f6] Cannot save 78:4f:43:33:45:f6 error (500) (pf::radius::authorize)

**Comment by jrouzierinverse** [comment]
Can you check 7fb8d537034fa97e9da79311ec7700dda19aa626 to see if that helps?

**Comment by jrouzierinverse** [comment]
Can this be closed?

**Comment by lzammit** [comment]
Fixed.
