### ISSUE TITLE
Network Devices Configuration Guide Meraki Webauth errors.

### ISSUE THREAD

**Issue by bekuhn-isd535** [inverse-inc/packetfence#2096]
I'm not sure where documentation issues go, so please point me to the appropriate place if this is wrong...

In Section 5.15.1 RFC5176 configuration for Meraki APs, the Meraki configuration shows Walled Garden as disabled.  Meraki APs don't use a registration ACL and use the Walled Garden feature instead.  In order to get this working, Walled Garden needs to be enabled and access to the IP running the PF Portal needs to be enabled.  Meraki's documentation for integrating with Cisco ISE explains this, and following that guide got it working for me on PF.

https://documentation.meraki.com/MR/Encryption_and_Authentication/Central_Web_Authentication_(CWA)_with_Cisco_ISE

Also, the configuration guide should show the need to enable "External Portal Enforcement" for this configuration.  Without that checked, the radius server does not send the Cisco AV Pair with the portal URL.

This is not mentioned on the Cisco WLC portion of the configuration guide as well and should be.

**Comment by julsemaan** [comment]
Will need to review the Meraki documentation
