### ISSUE TITLE
Radius in Read Only mode outputting the SQL insert error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2109]
We have that on every radius request received if the Mariadb Read Only enabled:

Mar 22 12:36:18 httpd.aaa(7812) ERROR: [mac:94:db:c9:38:8f:0b] database query failed with non retryable error: The MariaDB server is running with the --read-only option so it cannot execute this statement (errno: 1290) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?] (pf::dal::db_execute)
Mar 22 12:36:18 httpd.aaa(7812) ERROR: [mac:94:db:c9:38:8f:0b] Cannot save 94:db:c9:38:8f:0b error (500) (pf::radius::authorize)

What should we do ?

Can we just not display the mysql request that failed ?

**Comment by jrouzierinverse** [comment]
Since this will happen on every insert/update in the database I would like to reduce the noise in the logs.

Do you think not displaying the sql and changing the logging level to warn with a short message should be sufficient?

Or log nothing since this is "normal" behavior in readonly mode.

**Comment by louismunro** [comment]
Log a warning.
There must be some way to tell that the query failed when looking at the logs.

**Comment by julsemaan** [comment]
I concur

**Comment by louismunro** [comment]
I double concur and raise you.

**Comment by lzammit** [comment]
Who wants to do it❓

**Comment by julsemaan** [comment]
I shall propose @lzammit

**Comment by lzammit** [comment]
tu shall rien du tout toi!

**Comment by julsemaan** [comment]
All those in favor @lzammit doing it, raise your hand

**Comment by julsemaan** [comment]
:hand:

**Comment by whitx** [comment]
:hand:

**Comment by louismunro** [comment]
✊

**Comment by jrouzierinverse** [comment]
Fixed by 78ba58e065cc2278c38ac03c57edc01f1f7ab5d3 zammit can you verify?

**Comment by lzammit** [comment]
Looks ok:

Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] database query failed with: The MariaDB server is running with the --read-only option so it cannot execute this statement (errno: 1290) (pf::db::db_query_execute)
Mar 22 16:36:20 httpd.aaa(20341) WARN: [mac:11:22:33:44:55:66] Database issue: attempting to update a readonly database (pf::db::db_query_execute)
Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] handling radius autz request: from switch_ip => (172.20.110.250), connection_type => Wireless-802.11-NoEAP,switch_mac => (08:cc:68:3c:f4:60), mac => [11:22:33:44:55:66], port => 1, username => "94dbc9388f0b", ssid => ZamOpen (pf::radius::authorize)
Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] Instantiate profile ZamOpen (pf::Connection::ProfileFactory::_from_profile)
Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] is of status unreg; belongs into registration VLAN (pf::role::getRegistrationRole)
Mar 22 16:36:20 httpd.aaa(20341) WARN: [mac:11:22:33:44:55:66] Use of uninitialized value $ifDesc in concatenation (.) or string at /usr/local/pf/lib/pf/locationlog.pm line 411.
 (pf::locationlog::locationlog_synchronize)
Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] sync locationlog with ifDesc  (pf::locationlog::locationlog_synchronize)
Mar 22 16:36:20 httpd.aaa(20341) INFO: [mac:11:22:33:44:55:66] (172.20.110.250) Added VLAN 147 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Mar 22 16:36:20 httpd.aaa(20341) WARN: [mac:11:22:33:44:55:66] Attempting to update a readonly database (pf::dal::db_execute)
Mar 22 16:36:20 httpd.aaa(20341) ERROR: [mac:11:22:33:44:55:66] Cannot save 11:22:33:44:55:66 error (500) (pf::radius::authorize)
