### ISSUE TITLE
hostapd/Openwrt with Multiple SSIDs on same vlan Bug

### ISSUE THREAD

**Issue by abel408** [inverse-inc/packetfence#2110]
When 2 SSID's are configured and a node connects to both SSIDs and put into the same vlan, networking breaks and they are given a self assigned IP.

Here is a use case for the bug:

- OpenWRT AP has two SSIDs. SSID A and SSID B. Both of these SSIDs communicate with the freeradius server and packetfence to determine the role of the node.
- User A connects to SSID A and is applied the role "Staff" and put into VLAN 50.
- User A disconnects to SSID A and connects to SSID B. Packetfence sees that user is registered with the "Staff" role and returns VLAN 50.
- Something happens here that completely breaks networking for the SSID. The AP itself does not lose networking and nodes are still able to see and connect to the SSID, but the node receives an immediate deauth and a self assigned IP. All other nodes are also unable to receive networking. If Wifi is restarted on the AP, networking works again.

This behavior only happens when there are multiple SSIDs that could potentially host the same VLAN.

Here is the log on OpenWRT:
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 RADIUS: VLAN ID 50
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 IEEE 802.11: authenticated
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 RADIUS: stopped accounting session 588F75DB-00000078
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 IEEE 802.11: associated (aid 12)
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.460000] device vlan50 entered promiscuous mode
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.460000] breth0.50: port 1(vlan50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.470000] breth0.50: port 1(vlan50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.480000] breth0.50: port 1(vlan50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.480000] device wlan0.50 entered promiscuous mode
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.490000] breth0.50: port 2(wlan0.50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.490000] breth0.50: port 2(wlan0.50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.500000] breth0.50: port 2(wlan0.50) entered forwarding state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.520000] device wlan0.50 left promiscuous mode
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.520000] breth0.50: port 2(wlan0.50) entered disabled state
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.530000] device vlan50 left promiscuous mode
Tue Jan 31 15:27:46 2017 kern.info kernel: [79642.540000] breth0.50: port 1(vlan50) entered disabled state
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 RADIUS: starting accounting session 588F75DB-00000078
Tue Jan 31 15:27:46 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 WPA: pairwise key handshake completed (RSN)
Tue Jan 31 15:27:50 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 IEEE 802.11: disassociated
Tue Jan 31 15:27:50 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 RADIUS: stopped accounting session 588F75DB-00000078
Tue Jan 31 15:27:51 2017 daemon.info hostapd: wlan0-1: STA a0:99:9b:1a:7e:51 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

**Comment by abel408** [comment]
Not to be impatient, but has anyone taken a look at this?

**Comment by julsemaan** [comment]
This is not really a PacketFence bug, more an OpenWRT/hostapd bug so it won't get much traction here...
