### ISSUE TITLE
Radius fail mac authentication/dot1x

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2120]
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] handling radius autz request: from switch_ip => (172.20.110.250), connection_type => Wireless-802.11-EAP,switch_mac => (08:cc:68:3c:f4:60), mac => [94:db:c9:38:8f:0b], port => 1, username => "lzammit", ssid => ZamSecure (pf::radius::authorize)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Instantiate profile ZamSecure (pf::Connection::ProfileFactory::_from_profile)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Found authentication source 'Inverse-AD' for realm 'null' (pf::config::util::get_realm_authentication_source)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Found authentication source 'Inverse-AD' for realm 'null' (pf::config::util::filter_authentication_sources)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Realm 'null' authentication source 'Inverse-AD' is part of the available connection profile authentication sources. Using it as the only authentication source. (pf::config::util::filter_authentication_sources)
Mar 24 11:20:10 httpd.aaa(28534) WARN: [mac:94:db:c9:38:8f:0b] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match2)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Using sources Inverse-AD for matching (pf::authentication::match2)
Mar 24 11:20:10 httpd.aaa(28534) INFO: [mac:94:db:c9:38:8f:0b] Matched rule (Staff) in source Inverse-AD, returning actions. (pf::Authentication::Source::match)
Mar 24 11:20:10 httpd.aaa(28534) ERROR: [mac:94:db:c9:38:8f:0b] radius authorize failed with error: Undefined subroutine &pf::registration::called called at /usr/local/pf/lib/pf/registration.pm line 40.
 (pf::api::radius_authorize)
Mar 24 11:20:10 httpd.aaa(28534) WARN: [mac:94:db:c9:38:8f:0b] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 48.
 (pf::radius::rest::format_response)
Mar 24 11:20:10 httpd.aaa(28534) WARN: [mac:94:db:c9:38:8f:0b] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.

**Comment by jrouzierinverse** [comment]
Fixed by 98ada7426aaa316d7ac8faf714bc988ae80ab3f0

**Comment by lzammit** [comment]
I got a new one:

Mar 24 11:36:41 httpd.aaa(11729) ERROR: [mac:94:db:c9:38:8f:0b] radius authorize failed with error: Undefined subroutine &pf::radius::finalize_node_registration called at /usr/local/pf/lib/pf/radius.pm line 311.

**Comment by jrouzierinverse** [comment]
Fix in 89ff9884f25d65a5ae77d89b90756f14a96f6d6d

**Comment by lzammit** [comment]
802.1x works. Fixed.
