### ISSUE TITLE
Fingerbank: issue during db importation in the configurator

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2121]
Systemd kills the fingerbank process when started by the admin at the end of the configurator.

**Comment by lzammit** [comment]
still the same after the fix

**Comment by lzammit** [comment]
Issue where packetfence-mariadb is restart during the services start. @louismunro will take care of that.

**Comment by louismunro** [comment]
@lzammit can you confirm it's been fixed?
Close the issue if it is.

**Comment by extrafu** [comment]
Bump!

**Comment by lzammit** [comment]
It's working! ⚙️ 👍
