### ISSUE TITLE
Error while doing a passthrough lookup of itunes.apple.com

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2123]
When adding itunes.apple.com as a passthrough and querying pfdns about it, it generates the following error:
```
Mar 27 11:16:18 pfdns(20608) FATAL: Can't locate object method "encode" via package "Net::DNS::RR::CNAME" at /usr/lib64/perl5/vendor_perl/Net/DNS/Packet.pm line 212.
 (Net::DNS::Packet::encode)
```

**Comment by julsemaan** [comment]
This behavior doesn't exist on maintenance 6.5 with the same domain

@jrouzierinverse, could you see if this can be related to the new ipset cache ?

**Comment by jrouzierinverse** [comment]
Ok

**Comment by jrouzierinverse** [comment]
Not able to replicate.
Most likely a packaging issue.
Run the following command ```rpm -qa | grep perl-Net-DNS``` and let me know what is the output.

**Comment by julsemaan** [comment]
```
# rpm -qa | grep perl-Net-DNS
perl-Net-DNS-0.78-3.2.x86_64
```

**Comment by jrouzierinverse** [comment]
Was there any other error prior to that error
