### ISSUE TITLE
Use of uninitialized value $ifDesc in packetence.log

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2125]
Mar 27 14:31:48 httpd.aaa(10208) WARN: [mac:78:4f:43:33:45:f6] Use of uninitialized value $ifDesc in concatenation (.) or string at /usr/local/pf/lib/pf/locationlog.pm line 411.

**Comment by jrouzierinverse** [comment]
Fixed in 0a50d66c0b2d030b536ff4ca0012deea9b54b877
