### ISSUE TITLE
Domain: 'Save and join' doesn't save but it joins

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2126]
As reported verbally by @zammitcorp's CEO

**Comment by julsemaan** [comment]
Should be fixed by f1cebd91f1c205ed1336ef5696c5039d8e7f61bc

Can @lzammit honor this issue with a confirmation ?

**Comment by Skywalker-11** [comment]
I had the same problem and the commit fixed it after a restart of the server

**Comment by lzammit** [comment]
Thank you @Skywalker-11, once I will have a sane dev box I will test it.

**Comment by lzammit** [comment]
working!
