### ISSUE TITLE
Syslog regex parser not triggering the violation

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2127]
Here my config and steps:

/usr/local/pf/conf/pfdetect.conf

[suricata]
status=enabled
type=regex
path=/usr/local/pf/var/suricata

[suricata rule Kazaa]
action0=trigger_violation: mac, $mac, tid, $sid, type, detect
ip_mac_translation=enabled
last_if_match=disabled

[root@superfence pf]# echo "02/26/2017-14:29:00.524309  [**] [1:2000340:10] ET P2P Kaaza Media desktop p2pnetworking.exe Activity [**] [Classification: Potential Corporate Privacy Violation] [Priority: 1] {UDP} 173.194.7.75:443 -> 172.20.20.95:46742" > /usr/local/pf/var/suricata

Mar 27 15:14:30 pfdetect(27829) INFO: alert received: '02/26/2017-14:29:00.524309  [**] [1:2000340:10] ET P2P Kaaza Media desktop p2pnetworking.exe Activity [**] [Classification: Potential Corporate Privacy Violation] [Priority: 1] {UDP} 173.194.7.75:443 -> 172.20.20.95:46742
' (main::_run_detector)
Mar 27 15:14:30 pfdetect(27829) INFO: Parser id suricata : Matched rule 'Kazaa' : preparing action spec 'trigger_violation: mac, $mac, tid, $sid, type, detect' (pf::detect::parser::regex::prepAction)

[1100006]
trigger=suricata_event::ET P2P,detect::200340
actions=email_admin,reevaluate_access,log

[root@superfence pf]# ps -edf | grep pfqueue
pf       28129     1  2 15:14 ?        00:00:02 pfqueue
pf       28140 28129  0 15:14 ?        00:00:00 pfqueue - Queue:general
pf       28141 28129  0 15:14 ?        00:00:00 pfqueue - Queue:general
pf       28142 28129  0 15:14 ?        00:00:00 pfqueue - Queue:general
pf       28143 28129  0 15:14 ?        00:00:00 pfqueue - Queue:general
pf       28144 28129  0 15:14 ?        00:00:00 pfqueue - Delayed:general
pf       28145 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfdhcplistener
pf       28146 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfdhcplistener
pf       28147 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfdhcplistener
pf       28148 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfdhcplistener
pf       28149 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfdetect
pf       28150 28129  0 15:14 ?        00:00:00 pfqueue - Queue:pfsnmp
root     28160 28029  0 15:15 pts/1    00:00:00 grep --color=auto pfqueue

I run the test:

02/26/2017-14:29:00.524309  [**] [1:2000340:10] ET P2P Kaaza Media desktop p2pnetworking.exe Activity [**] [Classification: Potential Corporate Privacy Violation] [Priority: 1] {UDP} 173.194.7.75:443 -> 172.20.20.95:46742

Result:

 Click to see actions for - 02/26/2017-14:29:00.524309 [**] [1:2000340:10] ET P2P Kaaza Media desktop p2pnetworking.exe Activity [**] [Classification: Potential Corporate Privacy Violation] [Priority: 1] {UDP} 173.194.7.75:443 -> 172.20.20.95:46742
- Kazaa : trigger_violation('mac', '94:db:c9:38:8f:0b', 'tid', '2000340', 'type', 'detect')

**Comment by jrouzierinverse** [comment]
I am able to trigger the api call.
Looking to see if the problem is with something else.

**Comment by lzammit** [comment]
Working fine!
