### ISSUE TITLE
pfdns child processes will respawn additional child processes after being signaled to die

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2129]

**Comment by julsemaan** [comment]
Details on how to replicate this ? Or will you fix it yourself ?

**Comment by julsemaan** [comment]
On a side note, this commit should have fixed it a couple of weeks ago

https://github.com/inverse-inc/packetfence/commit/f908f2be8a1498569ef65026d75b569880f9c5c8

**Comment by jrouzierinverse** [comment]
I am not able to replicate it every time just sending a kill signal to pfdns seems to trigger it.

**Comment by julsemaan** [comment]
pfdns parent or one of the child ?

**Comment by jrouzierinverse** [comment]
parent

**Comment by jrouzierinverse** [comment]
I will have a fix in about 15 minutes
