### ISSUE TITLE
Admin: Disable/hide save buttons when in read-only

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2132]
As it was discussed in the internal team meeting, the create/update/delete features of the admin should be hidden or disabled when the DB is in read-only mode

We should also have an option to override this and get the full admin after showing the user a warning.

Short discussion with @dwlfrth led to the following idea:
- Save buttons are hidden when in read-only
- Top banner says something like 'Some functionalities have been disabled, click here to re-enable them'
- Upon clicking on the re-enable, we show a warning saying unexpected behavior may occur
- Upon acceptance of the warning, we re-enable the options (we could store that setting in the session so its user-specific so help-desk people don't start messing up stuff)

**Comment by jrouzierinverse** [comment]
The ability to operate in the mode should be an admin role.

**Comment by jrouzierinverse** [comment]
In my opinion this will touch a lot of different places.
So we should wait until 7.1  for this particular feature.

**Comment by julsemaan** [comment]
Given I wasn't there when you guys discussed it in the scope of 7.0, let's discuss this tomorrow during the meeting

**Comment by dwlfrth** [comment]
For v7, only the warning message will be changed.
Disabling / Enabling buttons should come together and that will be part of 7.1

**Comment by dwlfrth** [comment]
Use admin permissions (downgrade CRUD)

**Comment by jrouzierinverse** [comment]
Can this be closed?

**Comment by dwlfrth** [comment]
I think last time we discussed it, we wanted to have CRUD rights being used to add/remove buttons.
AFAIK, it is not in place so I'm not sure it should be closed.
@julsemaan might have a different point of view

**Comment by jrouzierinverse** [comment]
It is was already fixed by 0b0f2ac8a175aafb42acd823a44b22b4c0a9f871 that is why I am asking.

**Comment by julsemaan** [comment]
I guess it can be closed as  0b0f2ac addresses it
