### ISSUE TITLE
radiusd fails to start because of a DB unavailability on reboot

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2133]
Since the service starts too quickly, haproxy didn't detect yet which server should be alive

Should we:
- Ignore DB failures during radiusd startup
- Wait until the DB is available before starting radiusd

**Comment by dwlfrth** [comment]
Check for time delay for RADIUS to connect to MySQL on startup

**Comment by louismunro** [comment]
Before FreeRADIUS 3 we allowed connections to the database to fail during radiusd startup.
We could just revert to that behaviour.
