### ISSUE TITLE
carbon: clusters of more than 2 servers are missing some metrics

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2137]
I believe me and @louismunro talked about it a while ago but in clusters of more than 2 servers some metrics are missing from the dashboards since the carbon replication factor is set to 2 and that graphite doesn't seem to be able to poll from the other servers in order to get a view of all the datapoints.

We should either:
- Set the carbon replication factor to the cluster size so all servers have all metrics and can offer a proper view of the dashboard (that I can do)
- Fix the graphite polling from the other servers to get a complete view of all the metrics (that I have no clue how it even works)

**Comment by louismunro** [comment]
That's actually a known graphite bug.
The solution would be to package a newer release.

**Comment by julsemaan** [comment]
Or in the meanwhile set the replication factor to the cluster size for 7.0

What do you prefer @louismunro, play with graphite packaging or I do a quick fix on the replication factor ?

**Comment by louismunro** [comment]
We need the quick fix anyway.
Even if I package the current best graphite release, the nodes can only show data they have.
So it has to be sent to enough nodes to survive the loss of some of them.
For a three node cluster it's simpler to send to all three.

If it were a seven nodes cluster I would say 3-4 is good enough.
Graphite (with the fix) does not need all the data to be on every node.
It does need to be able to get that data from somewhere though.

So, </rant off> we should send to every node for now.

**Comment by julsemaan** [comment]
quickfix on the way

@louismunro, do you want to keep this opened for the graphite packaging or do I open another issue ?

**Comment by julsemaan** [comment]
quickfix done in 749f54b

**Comment by louismunro** [comment]
Please open another issue.
That fix is less urgent than the quickfix.
