### ISSUE TITLE
Is DRBD tracking in graphs still relevant ?

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2138]
Given our official DB cluster stack is now MariaDB Galera cluster, I'm not sure its relevant to offer graphs about DRBD by default since they will always be empty.

They could be there, but hidden and could be enabled via a config parameter

**Comment by louismunro** [comment]
Not relevant as far as I am concerned.
The metric can still exist. It does not have to be part of the dashboard though.
I'll remove it.

**Comment by dwlfrth** [comment]
i agree

**Comment by louismunro** [comment]
Fixed in 5d7f2b3491b8d55edbf57fd68beab22656fded06.

**Comment by julsemaan** [comment]
Config parameter or simply remove the graph and its data can be accessed via the graphite admin ?

**Comment by extrafu** [comment]
I would go for the latter.

**Comment by louismunro** [comment]
That's what I did.
