### ISSUE TITLE
Shutdown of server is long af

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2140]
The shutdown of a server is extremely long and hangs on the stop of the iptables and pfconfig service

Given the server is shutting down, that's all the info I have for now.

Seems to be something related to the stopping order where we might have a service missing.

I'll investigate further

**Comment by tlaurion** [comment]
Interestingly, after having created journald required directory for log persistence, I do not see shutdown hangs.

I followed this [procedure](https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1) to debug systemd

One can :
- modify /etc/grub/default with above proposed boot options 
- regenerate grub config with `grub2-mkconfig -o /boot/grub2/grub.cfg`


[Observations](https://framadrop.org/r/ST7j2iprjA#hLTnDmc1NnQVV5ENW+0hz1Ycd0hkcU1jvuHH5K1m+Xw=):
- there are oom_killer actions being taken after swapoff is activated by systemd. It seems that this service is called with shutdown before all packetfence services are being gracefully shut down.

**Comment by tlaurion** [comment]
@louismunro hypothesis was that this behavior could have been linked to chroot being mounted outside of systemd.

This [trace](https://framadrop.org/r/wD6Z2-dAtr#LmTQf1mElX6XouxICdeUb2iGAT3bQM6Xc0r7e1qVf/o=) is without having AD configured with devel's 20170330 packages. Same happens: most packetfence-* services get oom'ed but packetfence-iptables that waits. swapoff should not be called before PacketFence services are stopped.

**Comment by tlaurion** [comment]
Amazing. This is a[ known bug](https://bugzilla.redhat.com/show_bug.cgi?id=1031158) of systemd for which no fix has been pushed upstream. They have been poked. We are alone in the world to still have this issue?!?!

**Comment by julsemaan** [comment]
bim, for once, its not @lzammit fault

**Comment by tlaurion** [comment]
So here is what is seen.

Swap gets swapoff'ed before the services are cleanly stopped, packetfence-iptables tries to reach killed service until timeout is reached, where packetfence-iptables is stopped and  where the server gets rebooted. 

A per PF workaround would be:
- grep swap /var/log/dmesg |grep "dead -> active"
```
[    1.995413] systemd[1]: dev-dm\x2d1.swap changed dead -> active
[    1.995495] systemd[1]: dev-cl-swap.swap changed dead -> active
[    1.995550] systemd[1]: dev-disk-by\x2did-dm\x2dname\x2dcl\x2dswap.swap changed dead -> active
[    1.995616] systemd[1]: dev-disk-by\x2did-dm\x2duuid\x2dLVM\x2dXOAK7DHxMdmQCrNdwWE3Pt836Q9pHYSGyrO9ycCGeIYavzbamVWNKMaVUMLf1NWZ.swap changed dead -> active
[    1.995678] systemd[1]: dev-disk-by\x2duuid-6509e6e1\x2daf2d\x2d4d23\x2d9ebd\x2da9aa8801e658.swap changed dead -> active
```
- create /etc/systemd/system/swap.target with the following content:
```
[Unit]
Description=Swap
Documentation=man:systemd.special(7)
After=dev-disk-by\x2duuid-6509e6e1\x2daf2d\x2d4d23\x2d9ebd\x2da9aa8801e658.swap dev-dm1.swap dev-disk-by\x2did-dm\x2duuid\x2dLVM\x2dXOAK7DHxMdmQCrNdwWE3Pt836Q9pHYSGyrO9ycCGeIYavzbamVWNKMaVUMLf1NWZ.swap dev-disk-by\x2did-dm\x2dname\x2dcl\x2dswap.swap dev-cl-swap.swap dev-dm\x2d1.swap
```

**Comment by dwlfrth** [comment]
Need documentation in best practices and remove milestone. We will leave the issue opened for further reference
