### ISSUE TITLE
Should we prevent journald from logging to wall ?

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2141]
When a launch command for systemd has STDERR output like in the case of packetfence-iptables connecting to the DB, it will send it to the wall and pollute any SSH session.

This doesn't seem like a valid behavior to me, but hey I could be wrong, some people might like having an unusable shell because a process went foobar

**Comment by lzammit** [comment]
edit /etc/systemd/journald.conf
ForwardToWall=no
systemctl restart systemd-journald

**Comment by julsemaan** [comment]
@louismunro 
@fdurand 

Should we do an ugly sed and restart of journald in the packetfence package or should we address it differently ?
