### ISSUE TITLE
rsyslog rate limiting causing potential issues

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2144]
rsyslog is configured to rate-limit processes that log too much messages per second.

In our case, in large scale environments that could have debug activated, it will start discarding messages

I believe we should stop this from happening so we don't scratch our heads too much while troubleshooting a problem in a production environment

**Comment by julsemaan** [comment]
Its now disabled in rsyslog (018e0080c78279dfe6271321859415ca2cfde904) but it also needs to be disabled in journald systemd config

@louismunro knows about it. We can close it when he completes the journald systemd config

**Comment by louismunro** [comment]
Disabled in journald in d6ca92eef1788a4e6d2bbb9a349659ae8b40c5c8
