### ISSUE TITLE
Ability to assign VLAN ID from a pool

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2147]
Ability to create a VLAN pool and assign VLANs based of that pool for a given PacketFence role

**Comment by fdurand** [comment]
Something like that ? https://github.com/inverse-inc/packetfence/compare/feature/vlan_pool

**Comment by dwlfrth** [comment]
Bim ! Exactly !
I knew it was making me think of something ! ;)

**Comment by louismunro** [comment]
I also wrote some code for a client that assigns VLANs from a pool.
It had the advantage of always sending the devices for a given user to the same pool so that all devices for e.g. @lzammit would share a subnet.

I can find that code if you want.

**Comment by dwlfrth** [comment]
I also have custom code for three different clients. Just though it would be benefit to add that as a PacketFence feature.

**Comment by dwlfrth** [comment]
Pressed enter too quickly !
We should find the best implementation and put it in place.

**Comment by louismunro** [comment]
How about a framework to implement VLAN pools?
RubyOnPools?

**Comment by jrouzierinverse** [comment]
Or GoinPools

**Comment by julsemaan** [comment]
I'd go with RebootPools in honor of @lzammit 

I'll let you guess what happens when you assign a VLAN from that pool

**Comment by fdurand** [comment]
Fixed by #2675
