### ISSUE TITLE
PF admin: can not select the radius deauth method on a switch

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2151]
check the title

**Comment by whitx** [comment]
Actually only SNMP can be selected

**Comment by whitx** [comment]
Actually all chzn-select seems broken everywhere

**Comment by dwlfrth** [comment]
Related to #1263

**Comment by julsemaan** [comment]
I'm able to use it using the latest devel now

@lzammit, check if its good for you

**Comment by cgx** [comment]
Fixed by 1dbced9.
