### ISSUE TITLE
Configurator, unable to select an enforcement method (debian)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2152]
Starting from the first step of the configurator, even if i click on one of the 3 enforcement method, i am not able to go in the second step.

Error: GET https://172.20.20.152:1443/static/app/jquery.js  404

**Comment by cgx** [comment]
Configurator has been modified for the new frontend structure yet.

**Comment by cgx** [comment]
Configurator has been updated (9fd0077f749f5a2639ae6d6af594ab3d2063baef). Next step: fixing the Debian packaging.
