### ISSUE TITLE
Add labels for the Icons menu items to make easier to write help.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2158]
I think it would help to have some labels for the new icons.

Since it can make giving instructions on how to navigate the Admin a bit more difficult.

For instance I want to instruct someone how modify their Parking setting.

So instead of saying 

Go to Configuration> Advanced Configuration> Device Parking

Now we have to say
Go to Configuration
Then click on the (Some explanation of how the Icon look)
Then go to Device Parking

What are your thoughts?

**Comment by cgx** [comment]
Already discussed a few times in the meetings. We should have done at least one of them in English .. 

Tooltips are coming up!

**Comment by jrouzierinverse** [comment]
I already put Tooltips there.

**Comment by cgx** [comment]
You're quick!

**Comment by dwlfrth** [comment]
Fixed
