### ISSUE TITLE
rsyslog complains about the ~ to stop the actions

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2159]
Seems the ~ to stop an action is deprecated in rsyslog

We should change this to stop like the following warning says:
```
Mar 30 14:09:46 localhost rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
```

**Comment by louismunro** [comment]
I tried that originally and then rsyslog was unhappy about something else which I now forget but should be obvious so I will leave it as an exercise to the reader.
I am willing to live with the warning.

**Comment by julsemaan** [comment]
I'm just affraid that our behavior could change when rsyslog decides to just ignore this method

Not that it can happen soon but given this is a new config, I'd make it clean right away

But then again, if it was causing you some issues, we can leave it aside

I'll take a quick look into it and we'll leave it aside if it can't be quickly adjusted
