### ISSUE TITLE
PF admin: Time selectors are on two lines instead of one

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2167]
Was this intended ? Seemed better when it was on a single line

![image](https://cloud.githubusercontent.com/assets/3857942/24551749/af3fda3c-15f1-11e7-94e5-a6d285c82dcc.png)

**Comment by cgx** [comment]
I've asked @jrouzierinverse yesterday to replace this widget by a select input.

**Comment by julsemaan** [comment]
Actually, this was in devel, just not in the version we currently use given the builds were broken

Was done in 892ba98cc16665a4b3f376827fcb6e031c494c05 by @jrouzierinverse yesterday

**Comment by cgx** [comment]
Splendid 🐩
