### ISSUE TITLE
PF admin: When the admin is in RO, Read-Only message breaks the top section

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2168]
<img width="1276" alt="capture d ecran 2017-03-31 a 09 35 08" src="https://cloud.githubusercontent.com/assets/5261214/24552717/8ae3d504-15f5-11e7-9133-1517028e52b2.png">

**Comment by cgx** [comment]
I suggest we put a visual indicator in the top navbar. Make the background color red for example.

**Comment by dwlfrth** [comment]
Also add "documentation" on read-only mode

**Comment by cgx** [comment]
Can't find the documentation. Does it exist? 😨

**Comment by julsemaan** [comment]
It does but its in the clustering guide instead of being in the admin guide:
https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Clustering_Guide.asciidoc#quorum-behavior
