### ISSUE TITLE
CaptivePortal error on install

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2171]
While installing PacketFence the following error happens:

Argument "20s" isn't numeric in division (/) at /usr/local/pf/lib/pfconfig/namespaces/resource/CaptivePortal.pm line 33.

Seems to be good after a configrelaod

**Comment by julsemaan** [comment]
I'll check that today, could be something in the loading sequence of the pfconfig namespace

**Comment by julsemaan** [comment]
That is because of the rename of trapping into fencing.

During a normal upgrade, this won't happen because in the upgrade notes, the user should do 'pfcmd pfconfig clear_backend' and restart pfconfig after the package update
