### ISSUE TITLE
PF Admin: Connection profile preview doesn't work

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2177]
The portal profile currently gives out 400 bad requests on my setup.

Its configured with a management interface + portal (so in webauth mode, no registration/isolation)

I'm trying the preview on the default connection profile (the only one I have)

Following error appears in httpd.admin.error:
```
Mar 31 15:05:29 localhost httpd_admin_err: [Fri Mar 31 15:05:29.912883 2017] [proxy_http:error] [pid 18332] [client 172.20.20.251:49544] AH01083: error parsing URL //: Invalid host/port, referer: https://172.20.155.47:1443/admin/configuration
```

**Comment by jrouzierinverse** [comment]
Fixed by f643bffab418f7935505b2a936900d955da15f9c

**Comment by dwlfrth** [comment]
@julsemaan can you test this

**Comment by dwlfrth** [comment]
Comment here to say yeah or neah

**Comment by julsemaan** [comment]
yeah
