### ISSUE TITLE
PF Admin: template preview button has light foreground on light background

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2178]
Minor issue, the preview button of an HTML template in the connection profile has a light icon on a light background which makes the icon almost invisible

![image](https://cloud.githubusercontent.com/assets/3857942/24565648/1dcfb5da-1624-11e7-8560-266c5c0e3f64.png)

The preview icon is the first of the 3 icons at the right of each template row

**Comment by whitx** [comment]
on it

**Comment by whitx** [comment]
fixed by 1dedeccb39a40bcce0126fc179422d419ec9a818
