### ISSUE TITLE
PF Admin: Switch group tabs are on 2 lines

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2179]
Due to the additional tab it has, the switch group modal tabs are on 2 lines

Would probably need to make the modal a tiny bit larger or the tabs a tiny bit less large

Or just totally something else that a CSS guru would do

![image](https://cloud.githubusercontent.com/assets/3857942/24565725/886da906-1624-11e7-8584-bce151238fc4.png)

**Comment by jrouzierinverse** [comment]
Fixed bye ffc91b9c1e671b8cb016c1348f1f36f8fcf96ad4
