### ISSUE TITLE
PF Admin: required fields don't have the required icon (!)

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2180]
All the required fields used to have an exclamation mark icon next to their label

Its not there anymore, was this intentional ?

Before admin polish:
![image](https://cloud.githubusercontent.com/assets/3857942/24565835/fe788828-1624-11e7-8ce0-b299b5af7131.png)

After admin polish:
![image](https://cloud.githubusercontent.com/assets/3857942/24565854/0f8c6206-1625-11e7-9d71-5b785af6f0b4.png)

**Comment by cgx** [comment]
@whitx did fixed the templates. We should probably fix the Form::Handler widgets too.
