### ISSUE TITLE
PF Admin: Disable save button while section is saving

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2181]
This wasn't introduced in the new admin but I believe its been there for too long and we should address it.

When you save a section that comes from pf.conf (ex: System Configuration->Services) and it takes a lot of time to save, you don't have any feedback that the action was sent and you can still click Save

That could lead a user to click the Save multiple time thinking stuff isn't happening

**Comment by jrouzierinverse** [comment]
Fixed by 110c661d664e11431068b5f541a2f86f954963f7
