### ISSUE TITLE
PF Admin: Change the "favicon"

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2184]
Since we started to use Catalyst, we never changed the favicon.
We could change it to be more "personalized" ;)

**Comment by julsemaan** [comment]
I suggest we do a contest for the next favicon

Here is my suggestion
![image](https://cloud.githubusercontent.com/assets/3857942/24579418/32c86d3e-16c3-11e7-8bd1-38b63b57cc59.png)

**Comment by louismunro** [comment]
Do it, but whenever. 
No pressure.
