### ISSUE TITLE
:nail_care: Question: caddy services config files

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2185]
Currently the caddy services config files have one with .example and one without

We should decide whether or not we should put those in .example and consider them as config files in packaging

I propose putting them in .example and having them set as %config so they end up in rpmsave and not rpmnew

**Comment by louismunro** [comment]
.examples all the things.

**Comment by julsemaan** [comment]
Fixed by 40916561c44b43e2a6335bb0d7fcc9d0827fe73b and d316adfe636fc11caca27a69f301970a1f87592d

**Comment by louismunro** [comment]
Good trick: reopening and closing issues.
Makes it look as though you are working hard...
:grin:

**Comment by julsemaan** [comment]
You got it ;)

**Comment by julsemaan** [comment]
Fixed in devel
