### ISSUE TITLE
Role migration from db with to-7.0-roles-conf.pl create UTF8 roles.conf

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2190]
When you create a role in the web admin:

[root@superfence pf]# file conf/roles.conf
conf/roles.conf: ISO-8859 text

Once you run the role db script importation:

[root@superfence pf]# file conf/roles.conf
conf/roles.conf: UTF-8 Unicode text

The file display the accent correctly but not displayed properly in the web admin.

**Comment by julsemaan** [comment]
I guess we could fix this by forcing the encoding of the configuration files like the encoding is forced in the DB

IMO, its not worth too much time but I may be wrong

**Comment by julsemaan** [comment]
Zayme cares so much about international characters, I'd say we could call him Mr. Worldwide

![image](https://cloud.githubusercontent.com/assets/3857942/24627213/f89fd8d4-1881-11e7-95e2-cc690754e4e3.png)

**Comment by dwlfrth** [comment]
Should review encoding (db and configuration files)

**Comment by dwlfrth** [comment]
![49604ea7adb6bf79829206f4cc2e70b57b971fe0433483211656875df894f232](https://cloud.githubusercontent.com/assets/633234/24719014/24a3008e-1a06-11e7-99d7-31e60b1218a3.jpg)

**Comment by dwlfrth** [comment]
Check on what happen when we change encoding and see the right way to go.

**Comment by julsemaan** [comment]
Tagging 8.1 so we state on UTF-8 roles
