### ISSUE TITLE
pfsnmp workers default amount

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2194]
The default amount of pfsnmp workers seems low for a typical deployment of port-sec

Should a switch reboot, it will receive a lot of trap and the only worker will be overloaded

I suggest we up this amount to the default we have in pfsetvlan (4)

**Comment by jrouzierinverse** [comment]
I agree

**Comment by jrouzierinverse** [comment]
Fixed by 8315f1082d181a0cffd88ac111da56f4b8b04eb9
