### ISSUE TITLE
Queue status page should provide a view of the cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2195]
Currently the Queue status page only provides a view of the current server

We should aim to provide a view of the queues on all servers

**Comment by dwlfrth** [comment]
@jrouzierinverse

**Comment by jrouzierinverse** [comment]
Should we have two pages for the local view and one for the cluster?

 Kind of like this.

![image](https://user-images.githubusercontent.com/2727473/29420030-ca47917a-833e-11e7-9677-61036fd8c873.png)

Or just one page that shows all clustered members stats.

Also on the cluster display do we display stats per cluster or combined.

# Example of queue per cluster

## Member 1.1.1.1
### Queue Counts
|queue|count|
|---|---|
|general|0|
|pfdhcplistener|0|

### Outstanding Task Counters
|queue| name| count|
|---|---|---|
| general              | api:echo                       |          0 |
| general              | api:echo_fork                  |          0 |
| general              | api:trigger_violation          |        110 |

## Member 1.1.1.2
### Queue Counts
|Name|Count|
|---|---|
|general|0|
|pfdhcplistener|0|

### Outstanding Task Counters
| queue| name| count|
|---|---|---|
| general              | api:echo                       |          0 |
| general              | api:echo_fork                  |          0 |
| general              | api:trigger_violation          |        110 |
...

# Example of merge view

## Queue Counts
|member|queue|count|
|---|---|---|
|1.1.1.1|general|0|
|1.1.1.2|general|0|
|1.1.1.1|pfdhcplistener|0|
|1.1.1.2|pfdhcplistener|0|


## Outstanding Task Counters
|member| queue| name| count|
|---|---|---|---|
|1.1.1.1| general              | api:echo                       |          0 |
|1.1.1.2| general              | api:echo                       |          0 |
|1.1.1.1| general              | api:echo_fork                  |          0 |
|1.1.1.2| general              | api:echo_fork                  |          0 |
|1.1.1.1| general              | api:trigger_violation          |        110 |
|1.1.1.2| general              | api:trigger_violation          |        110 |
...

**Comment by julsemaan** [comment]
I'd vote for queue per cluster personally

**Comment by julsemaan** [comment]
Will be in a separate «page»
