### ISSUE TITLE
Adding a role in Admin Interface creates it in roles.conf but doesn't make it available in sources

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2201]
Adding a role in Admin Interface creates it in roles.conf but doesn't make it available in sources

To reproduce:
1. Create a new role from Admin interface. See that it is present in roles.conf. It is also shown in the availables roles.
1. Attempt to add it in a source's rule. Older roles are presented, but not the new ones. The role is not in database under node_category.

**Comment by julsemaan** [comment]
Node categories aren't working correctly right now because our schema still runs on 6.5.9 and node_category can only be updated on 7.0.0+ since it needs an index that is only present there.

Put your schema to 7.0.0 and try again:
insert into pf_version values(99999, '7.0.0')

**Comment by julsemaan** [comment]
I'll switch the schema version to 7.0.0 so that this doesn't happen again before we release

**Comment by extrafu** [comment]
@julsemaan Should @jrouzierinverse take care of it?

**Comment by julsemaan** [comment]
schema was updated, so this can be closed
