### ISSUE TITLE
pfsnmp should discard switchport traps if its already working on it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2204]
pfsnmp is currently handling all the traps that come from a switch+switchport even though he is currently working on the switchport. This means that in certain codepaths (floating devices in my case) it caused an endless SNMP configuration loop since the initial process was closing the interface which generated a down trap, which then generated a reconfiguration which resulted into starting back the process from scratch (getting port-sec trap)

From what me and @jrouzierinverse remember, pfsetvlan was controlling this by discarding the traps of a switch+switchport while it was already working on it

We need to bring this logic into pfsnmp

**Comment by jrouzierinverse** [comment]
Try 7b3e6e836d1b5248ac9ab00071225a57bb84ccb0 and let me know if it fixed it

**Comment by julsemaan** [comment]
Is it possible you forgot to push it to github ?

The commit doesn't seem to be there

**Comment by jrouzierinverse** [comment]
That is why you get paid the big bucks

**Comment by jrouzierinverse** [comment]
Try 1d0bbb5179d2372ec4ef512279618c87aae53591

**Comment by julsemaan** [comment]
Seems there is a compilation error in the pfsnmp task module because of this line:
```
my $lock = $switch->getExclusiveLockForScope("ifindex" : $trap->{trapIfIndex}, 1);
```

Not sure if it should be a concatenation or if it attempts to perform some wizardry I don't undertand

**Comment by julsemaan** [comment]
I've replaced the error above by a concatenation and it compiles:
```
my $lock = $switch->getExclusiveLockForScope("ifindex:" . $trap->{trapIfIndex}, 1);
```

And tried it again without success for the initial issue though

**Comment by jrouzierinverse** [comment]
Fix in c45ed878b668eaf86ed19f4c0eae116b1ddbcdde.
Please review

**Comment by julsemaan** [comment]
Doesn't even seem to compile:
```
# perl -c -Ilib /usr/local/pf/lib/pf/task/pfsnmp.pm
Global symbol "$switch" requires explicit package name at /usr/local/pf/lib/pf/task/pfsnmp.pm line 959.
Global symbol "$trap" requires explicit package name at /usr/local/pf/lib/pf/task/pfsnmp.pm line 959.
/usr/local/pf/lib/pf/task/pfsnmp.pm had compilation errors.
```

Something I don't have ? Or something I'm doing wrong ?

**Comment by jrouzierinverse** [comment]
My error fixed has been push

**Comment by julsemaan** [comment]
Seems to be doing the exact same thing

**Comment by julsemaan** [comment]
We receive an up trap while reconfiguring the port from what I can see and this triggers the reconfiguration of the port again

**Comment by jrouzierinverse** [comment]
The rewrite of pfsetvlan to use pfqueue was not matching the exact behavior of pfsetvlan.

In the initial rewrite attempt the parsing and handling thread pools were merged into a single task.

With these latest set of changes the task of parsing and handling are now two separate tasks.

This design allows filtering of task before being handled (which is why it was probably done in the first place).

Currently the same queue is used for parsing and handling.

This may need to change if we see that the parsing is blocking the handling.

Please retry

**Comment by julsemaan** [comment]
Still doing the same thing

Any configuration I should adjust so your changes are fully taken in consideration

**Comment by julsemaan** [comment]
Actually its a bit different, now after 4-5 times of doing the loop of configure/deconfigure, it stops and leaves the port in a half and half state

**Comment by julsemaan** [comment]
where half and half is the port configured for floating and not for floating

**Comment by jrouzierinverse** [comment]
Half and Half goes great with coffee.
![image](https://cloud.githubusercontent.com/assets/2727473/24925046/faf7b5f4-1ec4-11e7-8b6b-2da9ac5b7793.png)

Let's try having a separate queue for parsing to better mimic pfsetvlan.

**Comment by julsemaan** [comment]
This seems to actually have done the trick !!!!

I'll close and re-open if needed

**Comment by julsemaan** [comment]
Actually it wasn't fixed... my bad, I had an old pfsetvlan running so its back to not working state.

But, good news, the issue has been found!

pfsnmp is victim of its speed of action

Given pfsetvlan took about 3 seconds to start processing a trap it received, it was creating a race condition not to wait that 3 second after receiving the trap

By making the snmptrapd handler sleep 3 seconds before inserting in the queue, it is now working

That handler is single threaded so we can't put the sleep there, @jrouzierinverse will find the best place to put it

I'll also look up what is the sweet number for sleeping and update this thread

**Comment by julsemaan** [comment]
Seems 2 seconds is enough

**Comment by jrouzierinverse** [comment]
I made the delay two seconds let me know if we can close this issue.

**Comment by julsemaan** [comment]
fixaide
