### ISSUE TITLE
Role isn't saved in the DB when doing 802.1x autoreg

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2205]
A role being assigned to a device is shown under Auditing->( specific node) details-> Node Information (RADIUS logs), but not under Auditing->node-> info (DB stored information), where the "Role" drop down menu shows "No role" instead of selecting the actual role being applied. The category_id is not saved in the database for that node.

Replication:
1. Create a role
1. In a source, assign that role from authentication.
1. In the test switch, assign a VLAN ID to that role
1. In a connection profile, click "Automatically register devices", and make sure the previous source is used.
1. Connect with test device. Note MAC.
1. Connect to pf db, 'select * from node where mac="aa:bb:cc:dd:ee:ff"  \G' and note that "category_id: NULL"

**Comment by tlaurion** [comment]
@lzammit replicated this bug on his setup.

**Comment by julsemaan** [comment]
The issue is that the role isn't saved in the DB when doing 802.1x autoreg

I'll dig into it

**Comment by julsemaan** [comment]
It also happens independently from whether or not its a new role

**Comment by julsemaan** [comment]
Seems the DAL node object doesn't replicate the magic behavior of node_modify to assign a category_id using the category field

Will check with @jrouzierinverse

**Comment by julsemaan** [comment]
@jrouzierinverse will do a proper fix to bring the magic to the DAL node object

**Comment by jrouzierinverse** [comment]
Fixed by e2d8d8939abcf43eef81f0d84557e80fedd564c0
Please verify

**Comment by tlaurion** [comment]
fixed by ba7e7ba57b75180b6ab9c2f34b235ef4e48cebe2

**Comment by lzammit** [comment]
Fixaide
