### ISSUE TITLE
Recent renaming of pf::api methods can cause some pfqueue api task to fail after upgrade

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2206]
If there are old jobs in the redis job queue such as process_dhcp (which was renamed to process_dhcpv4) after an upgrade.
It will fail with an error like ```Can't locate object method "process_dhcp" via package "pf::api"```

How should we take care of it.

* Have them flush redis queue as part of the upgrade process.
* Create aliases for the old api methods that were renamed.

**Comment by extrafu** [comment]
I vote for KISS - flush the queues.

**Comment by jrouzierinverse** [comment]
![image](https://cloud.githubusercontent.com/assets/2727473/24684426/f35ba3d8-1973-11e7-80c4-8bb7b3e55c4a.png)

**Comment by extrafu** [comment]
Clearly @lzammit

**Comment by dwlfrth** [comment]
I agree with @extrafu ... updating a system "usually also means" flush the queue and much more ;)

**Comment by julsemaan** [comment]
I agree with @dwlfrth who agrees with @extrafu who clearly go that idea from @lzammit

**Comment by jrouzierinverse** [comment]
Fixed by 82755046df8481c0d7222fcc00f3e3530bbde8ea
