### ISSUE TITLE
pfqueue: Variable "%TRAP_HANDLERS" is not imported

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2208]
Apr  5 09:38:52 superfence pfqueue: WARN pfqueue(22346): Variable "%TRAP_HANDLERS" is not imported at /usr/local/pf/lib/pf/task/pfsnmp.pm line 138.
 (Module::Pluggable::Object::_require)
Apr  5 09:38:52 superfence pfqueue: Variable "%TRAP_HANDLERS" is not imported at /usr/local/pf/lib/pf/task/pfsnmp.pm line 138.
Apr  5 09:38:52 superfence pfqueue: Variable "%TRAP_HANDLERS" is not imported at /usr/local/pf/lib/pf/task/pfsnmp.pm line 144.
Apr  5 09:38:52 superfence pfqueue: Couldn't require pf::task::pfsnmp : Global symbol "%TRAP_HANDLERS" requires explicit package name at /usr/local/pf/lib/pf/task/pfsnmp.pm line 144.
Apr  5 09:38:52 superfence pfqueue: Compilation failed in require at (eval 1896) line 2.
Apr  5 09:38:52 superfence pfqueue: at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
Apr  5 09:38:52 superfence pfqueue: WARN pfqueue(22346): Variable "%TRAP_HANDLERS" is not imported at /usr/local/pf/lib/pf/task/pfsnmp.pm line 144.
 (Module::Pluggable::Object::_require)
Apr  5 09:38:52 superfence pfqueue: WARN pfqueue(22346): Couldn't require pf::task::pfsnmp : Global symbol "%TRAP_HANDLERS" requires explicit package name at /usr/local/pf/lib/pf/task/pfsnmp.pm line 144.
Compilation failed in require at (eval 1896) line 2.
 at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
 (Carp::carp)

**Comment by jrouzierinverse** [comment]
This was fixed in devel
