### ISSUE TITLE
[pfqueue] <defunct> PF 6.4

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2212]
[root@PacketFence pf]# ps -edf | grep pfque
root 15671 1 0 10:56 ? 00:00:00 pfqueue
root 15674 15671 0 10:56 ? 00:00:01 pfqueue - Queue:general
root 15675 15671 0 10:56 ? 00:00:02 pfqueue - Queue:general
root 15676 15671 0 10:56 ? 00:00:01 pfqueue - Queue:general
root 15677 15671 0 10:56 ? 00:00:02 pfqueue - Queue:general
root 15678 15671 0 10:56 ? 00:00:01 pfqueue - Queue:pfdhcplistener
root 15679 15671 0 10:56 ? 00:00:01 pfqueue - Queue:pfdhcplistener
root 15680 15671 0 10:56 ? 00:00:01 pfqueue - Queue:pfdhcplistener
root 15681 15671 0 10:56 ? 00:00:01 pfqueue - Queue:pfdhcplistener
root 15801 15680 0 10:57 ? 00:00:00 [pfqueue] <defunct>
root 15805 15679 0 10:57 ? 00:00:00 [pfqueue] <defunct>
root 15811 15678 0 10:57 ? 00:00:00 [pfqueue] <defunct>
root 15819 15681 0 10:57 ? 00:00:00 [pfqueue] <defunct>
root 21388 15675 0 11:57 ? 00:00:00 pfqueue - Queue:general

**Comment by jrouzierinverse** [comment]
Any errors in the pfqueue.log?

**Comment by jrouzierinverse** [comment]
Fix by e478d4f6b87c9aa409742c81fac145088a3df0c4 and push to maintenance
