### ISSUE TITLE
service stops create garbage log lines

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2217]
When stopping a service, it prints out an invalid log line.

Seems to be for all packetfence services

```
Apr  7 09:49:39 act-pass-1 packetfence: INFO pfcmd.pl(26099): Stopping haproxy with pid 25004 (pf::services::manager::stopService)
Apr  7 09:49:39 act-pass-1 packetfence: INFO pfcmd.pl(26099): child exited with value %d
0 (pf::services::manager::stopService)
```

Issue is on the second line

**Comment by louismunro** [comment]
You mean %d is not a valid exit code?
That's unpossible....

**Comment by julsemaan** [comment]
Well I think its a valid exit code on ZammitOS

They actually display the exit codes in hexa instead of that good old base 10 because its just so cool
