### ISSUE TITLE
pfcmd reports radiusd services started when they fail

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2218]
pfcmd can report radiusd services as successfully started when they have not yet finished starting.

As such there exists the risk that they will fail to start successfully and so the user will believe they are started when they are in fact not.

The fix is to add a syntax check in the unit file.
Already done on RHEL, working on it in Debian packaging.

**Comment by julsemaan** [comment]
This is actually a duplicate of #2118

This is generalized in all our services

**Comment by louismunro** [comment]
Well, systemd cannot be wrong.
Therefore you *must* be wrong.
Sigh...
I'll see what I can do.
Miracles at 8, film at 11.

**Comment by louismunro** [comment]
Fixed in 5d70ab176aae3e99093a.
This does not solve it for other services.
It's only a fix to prevent an invalid radiusd configuration from reporting as "started".
