### ISSUE TITLE
logging: MAC address prefix was removed when going to syslog

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2220]
The MAC address that prefixes all the log lines in PacketFence isn't there anymore since we've move to syslog to manage our logging

We should add this back as the MAC was removed from all logging messages since it was in the prefix

**Comment by louismunro** [comment]
We used to log through pf::log::fileappender.
That was (I believe) responsible for adding the MAC.
We now log through Log::Dispatch::Syslog.

So I think what we need is to extend Log::Dispatch::Syslog to add the MAC.

**Comment by louismunro** [comment]
Mmm, good try but no.
I don't see what the pf::log::fileappender code has to do with this.
The answer could be in pf::log itself.

**Comment by louismunro** [comment]
@jrouzierinverse can you please take a look and tell me where I got lost in the weeds?

**Comment by julsemaan** [comment]
It was in the configuration of Log4Perl itself I believe

log4perl.appender.PFQUEUE.layout.ConversionPattern     = %d{MMM dd HH:mm:ss} %X{proc}(%X{tid}) %p: [mac:%X{mac}] %m (%M)%n

**Comment by louismunro** [comment]
Good catch.
I was looking at the top level log.conf.example which does not have that pattern.

**Comment by louismunro** [comment]
I'll take care of it today.
