### ISSUE TITLE
/bin/pfcmd checkup is called before regenerating configurations, resulting in the same error even after having applied a good configuration change

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2221]
It takes two` bin/pfcmd service radiusd restart ` to actually apply a change.

Replicate:

1. Start with a clean conf.
2. Do a bad change (point to a file that doesn't exist)
3. `/usr/local/pf/bin/pfcmd service radiusd restart`(it will fail)
4. do `systemctl reset-failed`
5. Change to clean state.
6. `/usr/local/pf/bin/pfcmd service radiusd restart`
7. It will still fail at "Checking configuration sanity..."

**Comment by julsemaan** [comment]
![image](https://cloud.githubusercontent.com/assets/3857942/24815080/ea00d594-1ba1-11e7-8d84-d736e7c58e93.png)

**Comment by louismunro** [comment]
No intention of fixing this by 7.0.
It's been there for a long time.
It will have to wait until at least 7.1.

**Comment by dwlfrth** [comment]
Need to review the "checkup" flow
