### ISSUE TITLE
When performing a CoA, we should open a locationlog entry with the new role

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2222]
While doing WebAuth and a CoA, after the registration, if there is no VLAN number for the new role, the reevaluate_access is not trigger. This issue is only for CoA and not for radiusDisconnect.

**Comment by whitx** [comment]
Apr 10 14:25:31 httpd.portal(31786) INFO: [mac:xx:06:f4] Connection type is WIRELESS_MAC_AUTH. Getting role from node_info (pf::role::getRegisteredRole)
Apr 10 14:25:31 httpd.portal(31786) INFO: [mac:xx:06:f4] Username was defined "xx:06:f4" - returning role 'guest' (pf::role::getRegisteredRole)
Apr 10 14:25:31 httpd.portal(31786) INFO: [mac:xx:06:f4] PID: "guest", Status: reg Returned VLAN: (undefined), Role: guest (pf::role::fetchRoleForNode)
Apr 10 14:25:31 httpd.portal(31786) WARN: [mac:xx:06:f4] No parameter guestVlan found in conf/switches.conf for the switch 10.0.0.1 (pf::Switch::getVlanByName)
Apr 10 14:25:31 httpd.portal(31786) DEBUG: [mac:xx:06:f4] No reassignment required. (pf::enforcement::_should_we_reassign_vlan)
Apr 10 14:25:31 httpd.portal(31786) DEBUG: [mac:xx:06:f4] Rendering release.html (captiveportal::PacketFence::DynamicRouting::Application::render)

**Comment by dwlfrth** [comment]
Verify locationlog opening on CoA
