### ISSUE TITLE
webadmin: Misleading icons

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2224]
Should we change the icons for
- Portal (hand)
- System configuration (DB / Stockage / Pancake stack)

**Comment by louismunro** [comment]
Yes.

**Comment by louismunro** [comment]
The System configuration icon is the one usually associated with "Database/Storage".
If it was just some unknown icon it would be one thing, but in this case it is actually misleading as it would seem to indicate something it isn't.

**Comment by dwlfrth** [comment]
@whitx will suggest some suggestions

**Comment by julsemaan** [comment]
I suggest this for the advanced portal configuration:
http://fontawesome.io/icon/list-alt/

It kinda looks like a browser with our portal

**Comment by whitx** [comment]
I also like http://fontawesome.io/icon/sitemap and http://fontawesome.io/icon/pencil-square-o/
For systems configuration http://fontawesome.io/icon/cogs/ was used.

**Comment by julsemaan** [comment]
cogs ++ for system configuration

As for portal, I think there won't be a perfect answer, here they are ordered in my preference:
1. list-alt
2. sitemap
3. pencil-square-o

**Comment by whitx** [comment]
Maybe @extrafu and the magnificent @lzammit could give us their thinking, others also obviously.

**Comment by dwlfrth** [comment]
My suggestion: 
![32c86d3e-16c3-11e7-8bd1-38b63b57cc59](https://cloud.githubusercontent.com/assets/633234/24966301/8b8c34c8-1f74-11e7-8034-362de7061e44.png)

Otherwise, I'd say as @julsemaan

**Comment by julsemaan** [comment]
I'd second @dwlfrth, since the saddening day this was rejected as our favicon, I've been thinking about other usages this could have, this seems like the perfect one.

Nothing expresses more 'captive portal' like a line-up of naked people

**Comment by lzammit** [comment]
Portal: fa-list-alt 

System config: fa-cogs

**Comment by whitx** [comment]
Alright will go for list-alt atm, could be changed anyway.

**Comment by whitx** [comment]
Fixed by 9893d057769f26902b21af7a96e82f0102e28eb5

**Comment by louismunro** [comment]
No it can't (be changed).
While it's technically easy, we should not change the icons once users have gotten used to them.
Not outside of a major release. 

Which is why it matters to get them right.

**Comment by dwlfrth** [comment]
as @louismunro said, you don't change that kind of thing once the user is used to it.
UX rule # 42

**Comment by whitx** [comment]
Yeah I meant for pre release.

**Comment by dwlfrth** [comment]
There is no such thing as "pre release"

**Comment by julsemaan** [comment]
Agree with @louismunro and @dwlfrth, if we change it, we'll have to decide in the next 2-3 days

And on a sadder note, let's have a minute of silence for the great logo that lost the popularity contest for a second time this week

**Comment by louismunro** [comment]
Ahhh, don't cry...
I am doing a Kickstarter to design the new ZammitCorp World Logo.
We'll have a design competition.
I hear Massimo Vignelli will apply.

**Comment by julsemaan** [comment]
Wow, bringing back the dead, that's ZammitCorp level

**Comment by louismunro** [comment]
😈

**Comment by louismunro** [comment]
Didn't think anyone would notice....

**Comment by dwlfrth** [comment]
There is nothing wrong with it...
https://github.com/zammitcorp

**Comment by julsemaan** [comment]
I'd have to agree the current design is pretty good

Maybe we could tag it on the front-head of the guy on the current logo
