### ISSUE TITLE
reusedot1x: need to force the source in the realm config to get authenticated

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2225]
If you specify the reusedot1x for a secure portal profile, you need to specify and force a source to get authenticated or you get the error No matching rules for your username. PacketFence 6.X

**Comment by julsemaan** [comment]
as I discussed with @dwlfrth, this is not a bug but a feature

See #1543 for details about it

**Comment by dwlfrth** [comment]
"resuse"
![aebkv](https://cloud.githubusercontent.com/assets/633234/24966797/f2a21136-1f75-11e7-9c0c-7092b8cf2cba.jpg)
