### ISSUE TITLE
VoIP detection: LLDP lookup enhancement

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2227]
Currently, 'httpd.aaa' process will query the switch over SNMP to get the lldpLocPortDesc table (all the switch ports) to be able to match if there is a phone connected to the switch port. That query occurs everytime a device plugs in to detect whether or not PacketFence should take the VoIP workflow.

On a 24 - 48 switch, it can be acceptable but it is another story with a stack of 10 48 ports switches.

Getting the lldpLocPortDesc table for 480 ports at each request only to check whether or not it is matching an ifIndex does not make sense, thinking that this table only change if a new switch is added to the stack or if the switch get replaced.

Solution:
 * Have a 'pfmon' job that will cache the lldpLocPortDesc table
 * Modify the VoIP detection flow to use the cached data
 * 'pfmon' will cache only for switches that have VoIP LLDP detection / VoIP CDP detection enabled
 * Add a new button in the switch config to allow invalidation of switch cache

**Comment by dwlfrth** [comment]
itd also be cool if this cache had the ifname
and the gui looked to see if there was an ifname entry and showed that instead of the ifindex number

**Comment by julsemaan** [comment]
Well the ifdesc is now part of the locationlog so it should just be inserted there instead as it is part of the display as well

**Comment by dwlfrth** [comment]
It has been discussed not to handle cache invalidation through httpd.aaa. Therefore following points are removed from implementation in favor of manuel invalidation on a per switch basis
 * Caching will also keep the uptime (1.3.6.1.2.1.1.3.0) of the switch along with the ifNumber (.1.3.6.1.2.1.2.1) as "invalidity" keys.
 * 'httpd.aaa' will check switch uptime along with ifNumber value at each request and will invalidate the cache if uptime if lower or ifNumber changed
