### ISSUE TITLE
pfqueue in admin: outstanding tasks are tracked for all snmp switch+port+trap combination

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2229]
The outstanding tasks are being tracked for absolutely all the switch+port+trap type combinations which will lead to an implosion of the page

Tracking tasks counters makes sense for API tasks but not really for pfsnmp tasks.

I would suggest we simply do not track any other task than the ones from pf::api

Screenshot of admin:
![image](https://cloud.githubusercontent.com/assets/3857942/24969653/72e713ba-1f7f-11e7-8b2c-c5222653bf3c.png)

**Comment by jrouzierinverse** [comment]
I think it may be interesting to see which switches have traps being processed.

However there are multiple ways to handle this.
Here are some choice.

* Do not show counters there are zero.
* Only show particular types counters like only the api counters and person_lookup.
* Have two views of counters simple and extended.
* Have a click to see more link

**Comment by julsemaan** [comment]
I vote for the first one since the amount of counters would be equal to the amount of switchports X 3 or 4

**Comment by jrouzierinverse** [comment]
Fixed by 02f212b3c1954d36eb0b1d88f57fc5c9a3c170f5
