### ISSUE TITLE
portal preview is b0rken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2232]
IP address is set to 0.0.0.0 when using portal preview

![image](https://cloud.githubusercontent.com/assets/3857942/24979206/5b4977ee-1fa1-11e7-8dfe-0ea5218b9f0d.png)

**Comment by jrouzierinverse** [comment]
Is clustering enabled?

**Comment by julsemaan** [comment]
nope

**Comment by julsemaan** [comment]
Found the issue, its related to a fresh install

Will push a fix shortly
