### ISSUE TITLE
Report/quick search are broken

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#2233]
Title says it all.
Go in Reports > Operating System.

Click on any entries to issue a quick search. We switch to the right module but we get endless spinning, no data.

**Comment by extrafu** [comment]
Sames in Connection > Types and SSIDs.

**Comment by extrafu** [comment]
Same in Bandwidth consumers.

Looks like it's broken everywhere.

**Comment by jrouzierinverse** [comment]
I am unable to replicate

**Comment by extrafu** [comment]
@jrouzierinverse Come see me my friend
