### ISSUE TITLE
Duplicate searches can be created

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2237]
It's possible to create duplicate searches in auditing, users and nodes.
You can have multiple searches of the same name but different query parameters too.

**Comment by dwlfrth** [comment]
Saved searches

**Comment by dwlfrth** [comment]
Check for existing while saving but don't enforce in DB

**Comment by jrouzierinverse** [comment]
Fixed by 5581c1c9b674f470b5858cea7d891e534230dc2a
