### ISSUE TITLE
pfmon on active/active node 2-n spams with logs and eats my CPU

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2240]
pfmon spams the log with 
```
Apr 12 21:20:18 unicorn2 pfmon[3096]: DEBUG pfmon(3096): Reload configuration with status 0 (main::reload_config)
Apr 12 21:20:18 unicorn2 pfmon[3096]: DEBUG pfmon(3096): Awake from pause (main::waitforit)
```

And it eats my CPU as fast as I eat my turkey sandwiches and that my friends is fast as f*ck
```
 3096 pf        20   0  636572 158856   8660 R  79.8  3.2  10:22.71 pfmon
  394 root      20   0       0      0      0 R  62.9  0.0  13:31.71 kworker/u4:31
  575 root      20   0  217160 111536 111160 R  32.1  2.3   5:03.57 systemd-journal
```

Makes my machine laggy laggy and not work good

**Comment by extrafu** [comment]
@lzammit It is impossible that somethings beats you at turkey-eating speed.

**Comment by julsemaan** [comment]
Should be fixed by 720c731f6d65cfdd958297f3426f5c56f49f3ce3

@lzammit please check

**Comment by extrafu** [comment]
I stand corrected, @julsemaan is faster at fixing bugs that you are at eating your turkey sandwiches.

**Comment by dwlfrth** [comment]
Golden Zayme
