### ISSUE TITLE
Local documentation browser

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2241]
Now that we ship the documentation in HTML in the admin, we should provide a simple menu that allows to open any of the guides that are on the server

Tagging for 7.0 but could be postponed

**Comment by cgx** [comment]
I'll add the links to the top navbar, under the "info" menu.

**Comment by julsemaan** [comment]
There are a lot of other guides though that can be relevant

Most of the quick guides could be useful to be browsed directly on the setup

That's why I was suggesting the idea of a browser

Still the 3 links are nice but IMO we should have something more complete

**Comment by cgx** [comment]
What do you mean? A modal with an iframe? A sidenav with an iframe? You can add links to more guides in the meantime.

**Comment by julsemaan** [comment]
There are about 15-20 guides I think so that might be too much to display in this small space

I was thinking about a dedicated page where all guides would be listed and you could click on any of them to open it in a new tab

**Comment by cgx** [comment]
Oh. Well, feel free to rollback my commit and add a new page to the webadmin. I'll pimp it up once it's integrated. Thanks!

**Comment by julsemaan** [comment]
With the load-testing and my customers, I won't have time to get that done by the end of the day so let's forget it.

I'll make sure the links in the menu are at least valid

**Comment by julsemaan** [comment]
Current links in the menu are valid, will see if I have time to create a page before the end of the day, otherwise it will be left out of 7.0
