### ISSUE TITLE
obfuscated placeholders

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2242]
As I discussed with @whitx, the placeholders we have in PacketFence that go with an obfuscated field should be displayed as '*****' then when you hover on the password button it shows you the placeholder value.

Right now the placeholders for obfuscated values are gone which obfuscates information that could be useful (like the cluster shared secret)

**Comment by whitx** [comment]
Fixed by a11c6cf23f58279fa0beb317a102d30b08e207fc and bddf9daaa9c2981e73644b94eb0a0e7961431c0b
