### ISSUE TITLE
Obfuscated does not work in modal

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2243]
The obfuscated field with ability to show the password on mouseover, does not work while you are in a modal.

**Comment by jrouzierinverse** [comment]
Fixed by 6680d5f60a793d43433f77fc01af755e324329a3 2a1bd7bcdf59901d3f7e2355f55b9bd4f16b7dbd

**Comment by lzammit** [comment]
Tested, it's working.
