### ISSUE TITLE
Rollback method missing from pf/iniFile.pm

### ISSUE THREAD

**Issue by LCBLondon** [inverse-inc/packetfence#2244]
On line 160 from _pf/ConfigStore/Authentication.pm_ method Rollback id called.
However, this method does not exist in _pf/iniFile.pm_

I noticed it because the owner for the file _conf/Authentication.conf_ was not right on my system and got error: _Error! Can't locate object method "Rollback" ..._  when trying to make a change for an authentication source and saving it.

Changing owner back to _pf_ for the _conf/Authentication.conf_  file fixed my issue (cause it could save the file and did not have to call Rollback) but I believe something is not right either in _Authentication.pm_ (wrong method called) or _iniFile.pm_ (method missing)

**Comment by jrouzierinverse** [comment]
Thank you for the report. I fixed this in devel and the fix will be included in the next release.

**Comment by extrafu** [comment]
Then close it?
