### ISSUE TITLE
"No space on device" problem related to "/usr/local/pf/var/graphite" and fingerbank folder

### ISSUE THREAD

**Issue by maria2027** [inverse-inc/packetfence#2246]
Hi there !

How could I possibly clean up the graphite folder ?
Is eating all my space.
Also /usr/local/fingerbank/db is quite large (~5.5 GB).
I see there some "fingerbank_Upstream.db_20170415_101342" and "fingerbank_Upstream.db_20170416_101330". 
Is safe to erase the old file ?

Thank you !

**Comment by julsemaan** [comment]
The bug tracker is for bugs only.

Use the mailing list for these kind of questions
