### ISSUE TITLE
We now have two advanced configuration sections

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2248]
We have an "Advanced Configuration" Section, and a "System configuration > Main Configuration > Advanced" subsection.

Either we rename one to "Very, very Advanced Configuration" or we rename the "Advanced Configuration" to "Network Configuration"....

**Comment by julsemaan** [comment]
I vote for the second

**Comment by louismunro** [comment]
Ahhhh.... I would have liked to work on a product that has "Stupendously advanced configuration"...

**Comment by julsemaan** [comment]
I know, but @zammitcorp already trademarked that for its competing NAC product (PacketZayme)

**Comment by dwlfrth** [comment]
Let's do the second ! We, at ZaymytheCaurpe, don't like to infringe our own copywrite
