### ISSUE TITLE
Date is there twice in PacketFence log lines

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2250]
Its there at the beginning of the line, then after the process name

Likely a left-over of the Log4Perl config

**Comment by louismunro** [comment]
It's to make very, very sure you saw it.
Can you handle it? 
I'm having fun with the build system right now...

**Comment by louismunro** [comment]
If not, then I'll take a look later.

**Comment by julsemaan** [comment]
Yep, once I'm done with load testing and I have my VM back online I'll do it
