### ISSUE TITLE
Ubiquiti switch modules are named Ubiquity

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2254]
Seems like a bad typo to me unless they renamed themselves at some point.

The name of the company is Ubiquiti Networks so we should rename the modules Ubiquiti instead of Ubiquity

Also implies an upgrade note to rename them in switches.conf

**Comment by louismunro** [comment]
Your are confused.
Ubiquity Networks is actually a ZammitCorp Holding subsidiary.

**Comment by mholttech** [comment]
@louismunro you are right about Ubiquity Networks however the actual code is in reference to the Ubiquiti Edgeswitch v1.7 where they introduce a lot of the 802.1x features so @julsemaan is correct about the typo

**Comment by julsemaan** [comment]
fixed by #2293
