### ISSUE TITLE
Saving a node with an unregdate higher then 2038 gives weird error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2269]
![capture d ecran 2017-04-24 a 15 34 29](https://cloud.githubusercontent.com/assets/5261214/25355120/8ee0b87c-2903-11e7-8759-e9b1cc8b71f3.png)

Nothing in the httpd.admin logs

Happens on 6.5.1

I am the great Zayme president of Zaymebabwé

**Comment by extrafu** [comment]
Looks all good to me!

**Comment by dwlfrth** [comment]
@jrouzierinverse do quick fix for this one and backport it.
We will discuss on change format in database afterward and the impact of it.

**Comment by jrouzierinverse** [comment]
Fixed by 58ed2028d473e3454ab27bf30f702be8ad303390
