### ISSUE TITLE
Radius not listening to Management IP in Webauth with one interface

### ISSUE THREAD

**Issue by simongottschlag** [inverse-inc/packetfence#2271]
Using PacketFence version 7, one interface with one IP and webauth. When radius is added to the interface, it never listens to 1812 / 1813 on that IP. When removing radius from the interface, it actually starts.

Not sure why, but my solution was just to remove radius from it.

**Comment by julsemaan** [comment]
Was the interface already of the type 'Management' ?

**Comment by dwlfrth** [comment]
Related to #2284

**Comment by julsemaan** [comment]
This was a dup of #2612 and was fixed
