### ISSUE TITLE
load images webgui over https instead of http

### ISSUE THREAD

**Issue by kkplein** [inverse-inc/packetfence#2272]
I noticed that in 7.0, images are still loaded over http, while the rest is loaded via https. For a security-related piece of software such as packetfence, it would be much nicer if everything was https, resulting in a nice green browser-padlock.
Hope this is the right place to report this.

**Comment by louismunro** [comment]
It is.
Assigned to self.

**Comment by kkplein** [comment]
Hmm I found #1517 about the same issue, but for me, graphite is still http on port 9000...

**Comment by louismunro** [comment]
#1517 caused some issues I believe and was later reverted.
Images over http was better than no images...

**Comment by kkplein** [comment]
true :-)

**Comment by julsemaan** [comment]
Best thing would be to use port 1443 with a specific location for graphite so that SSL warnings previously accepted for host:1443 are still good for graphite images

We could also reverse proxy to 9000 for a location in the admin process

**Comment by kkplein** [comment]
:-) Super for the quick fix!

**Comment by louismunro** [comment]
Feel free to try it on a 7.0 install if you want.
It should not eat your dog or anything.
