### ISSUE TITLE
Documentation: Adjust WLC web-auth reg ACL

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2275]
Reported by a user...

He had to put:
permit any DNS
permit DNS any

Instead of just the 1st one
Makes sense to allow traffic both ways anyway

Need to adjust the screenshot in the doc

**Comment by fdurand** [comment]
It depend how you configure the direction of your rule. By default it's an in direction so "permit any DNS" is enought.

**Comment by julsemaan** [comment]
User reported that rule wasn't enough after doing the config on a WLC version 8.2.151.0

Wondering if it might be a change in the new version

**Comment by dwlfrth** [comment]
@julsemaan enjoy

**Comment by julsemaan** [comment]
fixed by 4ec34f8
