### ISSUE TITLE
When a saved search has a long name, the little garbage icon placement is off

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2276]
See the line 'Kenworth-Navigation...'

![image](https://cloud.githubusercontent.com/assets/3857942/25451232/777f9b66-2a8f-11e7-9870-5db5d652cc85.png)

**Comment by cgx** [comment]
What browser do you use? Long titles properly span multiple lines on my instance of Chrome:

![screen shot 2017-05-01 at 10 56 59 am](https://cloud.githubusercontent.com/assets/1088448/25582810/11f448c4-2e5d-11e7-87a2-c1d9e364d859.png)

**Comment by julsemaan** [comment]
Wasn't on my computer, but it was on Chrome

I actually just replicated it using Chrome on my PC and the same search name as my customer used

**Comment by cgx** [comment]
Try setting the CSS attribute "white-space" to "normal" on the parent `<li>` and let me know if it resolves the issue.

**Comment by julsemaan** [comment]
@cgx 

Didn't do it unfortunately
