### ISSUE TITLE
Mobile UI appears off

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2279]
Mobile UI appears to be a bit off in ZEN 7.0.

![screenshot_2017-04-27-20-31-29](https://cloud.githubusercontent.com/assets/382007/25512309/597bd6d0-2b92-11e7-977a-438160e0579d.png)

**Comment by julsemaan** [comment]
Not sure the v7 admin was ever designed to be used in a mobile phone

Maybe @cgx can confirm ?

**Comment by cgx** [comment]
The question is: Do we want the Web admin to be accessible from a mobile?

**Comment by julsemaan** [comment]
IMO no, maybe other folks have a different opinion
