### ISSUE TITLE
Mac authentication using  HP switch 

### ISSUE THREAD

**Issue by prashantlohar** [inverse-inc/packetfence#2281]
Hello,
I am using this NAC for MAC authentication in the network. 
I am working on the mac authentication with HP5130 and HP5940 switches. Switches have comware 5 and 7 both kind of firmwares. In this network i have multiple vlans and i want to authenticate enduser by mac registration.
so please help me.

**Comment by prashantlohar** [comment]
hello,
         i am working on the mac authentication with HP5130 and HP5940 switches. Switches have comware 5 and 7 both kind of firmwares. In this network i have multiple vlans and i want to authenticate enduser by mac registration. 
so please help me.

**Comment by extrafu** [comment]
Use the mailing list.
