### ISSUE TITLE
"dynamic" unregistration date no longer seems to work from admin GUI

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2285]
Ability to set a "dynamic" unregistration date (0-07-01) which was dynamically computing the year (current year if not past, next year if past... every July 1st) throws an error from perl-Time-Piece in the admin GUI authentication source rule creation.

That unregistration date format is working from the portal

**Comment by jrouzierinverse** [comment]
Fixed in b04050a6bb3091fb52ada69b4789e2820ff7803c

**Comment by dwlfrth** [comment]
@jrouzierinverse backport the commit and close the issue
