### ISSUE TITLE
dynamic access duration representation no longer works

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2286]
When defining access durations in the admin interface, the dynamic access duration configuration section no longer live update the "exemple" based on configuration.

![screen shot 2017-04-28 at 13 18 34 2](https://cloud.githubusercontent.com/assets/633234/25539482/63c2e86c-2c15-11e7-8e1a-f4679aa69c55.png)

**Comment by dwlfrth** [comment]
Should we cherry-pick this commit ?

**Comment by cgx** [comment]
Cherry-pick to *maintenance/7.0*? Of course.

**Comment by dwlfrth** [comment]
what about 6.5.1 and 6.5.0 ?

**Comment by cgx** [comment]
The bug is related to the changes in 7.0.

**Comment by dwlfrth** [comment]
You are right ;) my bad ahah !

**Comment by cgx** [comment]
Go back to bed please. 😴  🤒
