### ISSUE TITLE
CoA with Aruba Instant and PacketFence 7

### ISSUE THREAD

**Issue by simongottschlag** [inverse-inc/packetfence#2291]
I've had some issues getting CoA working with with Aruba Instant but after doing the following changes, it seems to be working:

Aruba Instant 6.5.1.0-4.3.1.0_57768 (IAP-325 as master)
PacketFence 7

Aruba Instant configuration:
1. To get radius accounting to working
Networks > [Network Name] > WLAN Settings > Primary usage: [v] Employee

2. To get CoA working
Networks > [Network Name] > Security > MAC Authentication: Enabled
Networks > [Network Name] > Security > Delimiter character: \<empty\>
Networks > [Network Name] > Security > Uppercase support: Disabled
* Make sure RFC 3576 is enabled on the authentication server configuration

PacketFence configuration:
```
--- /usr/local/pf/lib/pf/Switch/Aruba.pm_bak    2017-05-03 16:14:22.083696715 +0200
+++ /usr/local/pf/lib/pf/Switch/Aruba.pm        2017-05-03 16:15:13.628155187 +0200
@@ -481,12 +481,13 @@
         my $acctsessionid = node_accounting_current_sessionid($mac);
         my $node_info = node_attributes($mac);
         # transforming MAC to the expected format 00-11-22-33-CA-FE
-        $mac = uc($mac);
-        $mac =~ s/:/-/g;
+        $mac = lc($mac);
+        $mac =~ s/://g;

         # Standard Attributes
         my $attributes_ref = {
             'Calling-Station-Id' => $mac,
+            'User-Name' => $mac,
             'NAS-IP-Address' => $send_disconnect_to,
             'Acct-Session-Id' => $acctsessionid,
         };
```
Restart pfqueue: /usr/local/pf/bin/pfcmd service pfqueue restart

**Comment by whitx** [comment]
Interesting, we do not have IAP to test it here, we just need to make sure this does not affect a standard Aruba controller.

**Comment by simongottschlag** [comment]
Hi,

Maybe we should create a separate configuration for Aruba Instant?

For your information:
I had a lot of issues with Apple's CNA (Captive Network Assistant) for iOS (iPhone, iPad and iPod). It just wouldn't pop-up when you chose the wireless network. It was a two part problem, where the first solution was to use the latest version (6.5.2.0) or else the Aruba Instant Captive portal didn't even work. When that was solved, the second problem was that I had configured the DNS record pointing to PacketFence as a CNAME like this:
(cname) guestportal.example.com -> packetfence.example.com
(a-record) packetfence.example.com -> 192.168.0.20

For some reason, when choosing the External Captive Portal in Aruba Instant, you can't be using a CNAME. After a lucky guess, I changed the guestportal.example.com from a cname to an a-record and pointed it to the IP (192.168.0.20) and it started working.

**Comment by julsemaan** [comment]
We would have to try to get out hands on an IAP to get this properly tested and get our recipe right.

I'll leave this aside for now

**Comment by bramwittendorp** [comment]
I can confirm this works on the IAP 305 from Aruba.

**Comment by bunzlCH** [comment]
@julsemaan We have a spare IAP-205 if you like to test it, let me know
