### ISSUE TITLE
Add the possibility to change the SMS pin code length via the WEB admin

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2294]
Right now there is no easy way to change the pin code length.

**Comment by julsemaan** [comment]
I'd also add the ability to prevent mixing letters and numbers and just having numbers for easy PIN codes

**Comment by julsemaan** [comment]
And also probably remove the limitation of PIN codes being unique for SMS as it doesn't make much sense for that case IMO

**Comment by extrafu** [comment]
We should also have an option so the PIN can always be "zayme"

**Comment by dwlfrth** [comment]
As @julsemaan  no need to be unique since there should be a match between PIN and MAC address

**Comment by dwlfrth** [comment]
"On est pas l'Pentagone" - @lzammit

**Comment by dwlfrth** [comment]
Only digits, variable length configurable in the SMS source itself
