### ISSUE TITLE
Connection profile preview stuck on only showing the 'Default' profile

### ISSUE THREAD

**Issue by apkt** [inverse-inc/packetfence#2295]
Selecting 'Preview' for ANY defined profile on the admin GUI 'Connection Profile' tab displays the 'Default' Connection Profile regardless of the configuration of the specific profile being selected.

**Comment by julsemaan** [comment]
Not able to replicate it here

What OS are you running and what version of PacketFence ?

**Comment by louismunro** [comment]
Fixed in maintenance I believe.
See e0f96ae99dd5f134feb223f24e3e96c8dd322068.

**Comment by julsemaan** [comment]
Closing, pretty sure @louismunro found it

Re-open if his proposed patch doesn't fix it
