### ISSUE TITLE
Rules under a source can not be moved anymore

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2298]
If you try to drag and drop a rule it won't move.

Tested under chrome and firefox.

**Comment by julsemaan** [comment]
Milestone should be +1 patch release given it should be cherry-picked in maintenance

Also, added zammitbug label since we didn't yet confirm that rebooting doesn't fix the issue

**Comment by dwlfrth** [comment]
@cgx poke :) any idea ?

**Comment by julsemaan** [comment]
Also affects CSV node import

**Comment by julsemaan** [comment]
This will need to be cherry-picked in the maintenance branch.

Now given we're now minimizing JS, I assume it won't cherry-pick cleanly.

Could you provide instructions on how to regenerate the JS files after the cherry-pick ?

**Comment by cgx** [comment]
`grunt dist` 👍
