### ISSUE TITLE
admin: fuzzyness with popup menu

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2300]
When using a popup menu with submenu in the admin interface, it is configured to open "bottom direction". That creates a display fuzzyness that I can barely explain !

<img width="1141" alt="screen shot 2017-05-05 at 09 36 37" src="https://cloud.githubusercontent.com/assets/633234/25747706/69619596-3176-11e7-95b4-e600f058f340.png">

**Comment by dwlfrth** [comment]
Was it only affecting v7 + ?
Should we backport to maintenance ?

**Comment by cgx** [comment]
Technically the problem exists in prior versions but it was rarely happening because of the very large left sidebar.

**Comment by dwlfrth** [comment]
![1ohqzp](https://cloud.githubusercontent.com/assets/633234/25757287/e44deaae-3197-11e7-8d44-11f0aeba7912.jpg)
