### ISSUE TITLE
Admin: auth rules conditions fields have gone smaller

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2312]
## How it was:
![image](https://cloud.githubusercontent.com/assets/3857942/25864162/6acf7e5e-34bc-11e7-9e55-c69fc7e75d11.png)

## How it is now:
![image](https://cloud.githubusercontent.com/assets/3857942/25864317/fe9fe380-34bc-11e7-9c96-5d6f38cd1457.png)

**Comment by cgx** [comment]
Postmortem explanation: I changed the Bootstrap grid from the default 12 columns to 18 columns.
