### ISSUE TITLE
SCSS settings + colors are getting wiped on each update

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2317]
Should get the packaging to rpmsave them

**Comment by dwlfrth** [comment]
Add and upgrade section in the admin guide to instruct how to rregenerate CSS if custom on upgrade

**Comment by cgx** [comment]
Grab this [section](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Developers_Guide.asciidoc#presentation) from the developer's guide.

**Comment by dwlfrth** [comment]
In which section of the `Administration Guide` that should be added ?

**Comment by dwlfrth** [comment]
In which section of the `Administration Guide` that should be added ?

**Comment by dwlfrth** [comment]
Which files should be "saved" by packaging ?
Generated files ?
SCSS files ?
Both ?

**Comment by dwlfrth** [comment]
@cgx could advise

**Comment by dwlfrth** [comment]
As per @cgx 

- html/common/scss/*
- html/common/styles.css*

**Comment by dwlfrth** [comment]
Should be fixed by

- `d820d4db22ee50b06ff6b8c76441ad230d89a534`
- `79b89713cd8a1460d3611d115dcb179f02e43eb2`
