### ISSUE TITLE
Missing dependencies on Debian

### ISSUE THREAD

**Issue by tribut** [inverse-inc/packetfence#2318]
We recently upgraded our packetfence install (running Debian jessie) to 7.0 and it seems it is missing  dependencies on these packages:

 * libclass-xsaccessor-perl
 * libbsd-resource-perl

Both prevent packetfence from starting when not installed.

**Comment by julsemaan** [comment]
@fdurand 

Would this still be relevant ?

I would assume that in almost a year we had time to add those :)

**Comment by fdurand** [comment]
Fixed
