### ISSUE TITLE
CSS and JS statements inline in templates

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2333]
Some CSS and JS statements are inline inside in the templates. They should be moved to their specific files so that the errors given by Content-Security-Policy disappear.

EX: inside of html/pfappserver/root/admin/wrapper.tt:
- "height: 32px"
- "var labels = { "Cannot Load C ...."

**Comment by tlaurion** [comment]
To replicate:

In httpd.admin.tt, add the following in the VirtualHost section to produce the same errors:
`Header set Content-Security-Policy-Report-Only: "default-src 'self' https://[% vhost %]:[% ports.admin %];"`

And restart httpd.admin service

**Comment by tlaurion** [comment]
Diff for the portal: https://github.com/inverse-inc/packetfence/pull/2336

My environment can be used if needed?

**Comment by cgx** [comment]
`'self'` matches the current origin. Specifying the vhost should not be necessary, right?

**Comment by tlaurion** [comment]
tested both templates: you are absolutely right: it gives the same result.

**Comment by tlaurion** [comment]
Next steps would be:

1. For both of the following files, replace "Content-Security-Policy-Report-Only" by "Content-Security-Policy" so that the prohibited content is actually blocked.
1. For the admin, replace in the code:
"default-src 'self';" by "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';") under /usr/local/pf/html/pfappserver/lib/pfappserver.pm
1. For the portal, replace "default-src 'self';" by "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' $captive_portal_network_detection_ip; style-src 'self';" under /usr/local/pf/html/captive-portal/lib/captiveportal.pm

**Comment by cgx** [comment]
Best effort for CSP support is in the latest release.
