### ISSUE TITLE
httpd.portal could have all it's TLS section supressed

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2334]
Since TLS is terminated at HAProxy

**Comment by dwlfrth** [comment]
Simply remove configuration from httpd.portal

**Comment by jrouzierinverse** [comment]
We expose the status of the server via tls 

/modstatus

**Comment by jrouzierinverse** [comment]
Do we want to remove this all together or do we want allow haproxy handle the SSL termination for this resource also.

**Comment by jrouzierinverse** [comment]
Moving this to 7.3 to provide more to test impact of /modstatus and collectd

**Comment by dwlfrth** [comment]
Make modstatus listens on http

**Comment by julsemaan** [comment]
@jrouzierinverse, still relevant for 7.4 ?

**Comment by extrafu** [comment]
Bump @jrouzierinverse - close if not relevant anymore.

**Comment by julsemaan** [comment]
Its still relevant to do it but I think that might be a bit tight for 7.4 so postponing to 8.0 might be the way to go. @jrouzierinverse can confirm

**Comment by extrafu** [comment]
Bumped to v8

**Comment by fdurand** [comment]
Fixed by 35d79c8a189596fa560892978b81b6eedeb4f9b1
