### ISSUE TITLE
authentication: Too large scoping of authentication sources

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2338]
When calling `pf::authentication::authenticate` without specifying a source array, all configured authentication source (except the "exclusive" ones) are used.
Since we match on a first hit based, some authentication sources do not have any specific" logic to return a "TRUE" for authenticate and we might wrongly authenticate.

ie. Email source which is provided by default

**Comment by dwlfrth** [comment]
TODO: Need to evaluate side-effects

**Comment by dwlfrth** [comment]
Should also address #1784

**Comment by julsemaan** [comment]
Re-opening to track cherry-picking in maintenance/7.0 once this fix is confirmed as working with the 7.1 testing

**Comment by dwlfrth** [comment]
Are we OK to cherry-pick ?

**Comment by julsemaan** [comment]
Yes, I'll let you create the commit from the PR so I don't steal your credit

**Comment by extrafu** [comment]
"too large" like in Zayme's large?

**Comment by dwlfrth** [comment]
Should this be backported only to 7.X or 6.X too ?

**Comment by julsemaan** [comment]
I'd say as long as it cherry-picks without conflict in 6.x + 7.x

**Comment by dwlfrth** [comment]
Cherry-picked from 6.0 to 7.0
