### ISSUE TITLE
Merge documentation guides and create example sections

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#2341]
Actually:
- The [ZEN guide](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFenceZEN_Installation_Guide.asciidoc) has been exploded in [inline](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Inline_Deployment_Quick_Guide_ZEN.asciidoc) and [out of band](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Out-of-Band_Deployment_Quick_Guide_ZEN.asciidoc) guides. 
- Some overlapping documentation exists under the admin guide and ZEN guides. 

Merging Proposition:
1. Assumptions for network configuration and IP addresses and VLAN IDs should be unified in the Admin guide and ZEN guide. The original [ZEN guide](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFenceZEN_Installation_Guide.asciidoc) should be used as a base.
1. The admin guide should be stripped of it's examples. Those should be moved to specific sections and referenced instead of being duplicated.
1. The Zen guide content should be introduced to the end of the Admin guide in an "Example" section, and refer to ZEN only as a pre-section, referring to the importation of the virtual machine. The rest of the documentation covers most used configuration (dot1x with AD and a 2960). Inline and out of band sections should also be splitted instead of duplicating the whole guides. 

Examples sections:
1. "Dot1x for Active Directory" example should be placed after the configurator part as a configuration path and include all required steps. Those should be reevaluated to reflect PF7 ( role should be created first, domains created after, etc) and are already present in the Zen guide.

**Comment by extrafu** [comment]
Done - will be pushed.
