### ISSUE TITLE
Default ip4log cleanup settings set the expiration to 1 month

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2343]
Seems that the new pfmon introduced a change in logic where before the rotation window was used as the cleanup window if rotation was disabled. Now the rotation window only affects the job when the rotation is enabled (which makes sense)

But, that means if you have rotation disabled, we keep 1 month worth of ips in ip4log_history which in a lot of cases will lead to issues.

I suggest the following settings in the pfmon.conf.defaults:
- rotation still disabled
- rotation window: 1 day
- cleanup window: 1 week

This means we'll cleanup all entries older than 1 week with our default settings and they won't be rotated through tables

**Comment by dwlfrth** [comment]
I agree
