### ISSUE TITLE
Impossible to preview an email template

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2344]
Previewing an email template in the connection profile files tab results in the following error:
![image](https://cloud.githubusercontent.com/assets/3857942/26421798/5820b6e4-4095-11e7-93e7-cec91c956956.png)

Not even sure that should have been available in the first place.

We should do one of the following:
- Remove the preview button for the email templates
- Fix it and make sure it previews fine (with the fake data and all of that)

**Comment by dwlfrth** [comment]
Second option should be the one to take

**Comment by julsemaan** [comment]
@jrouzierinverse, have place in your to-do for that one ?

**Comment by jrouzierinverse** [comment]
Fixed by 22f7a422b2e35e5b6f99c4805394ff386c6bbcbc

**Comment by jrouzierinverse** [comment]
How far back do we want to put this in maintenance?

**Comment by julsemaan** [comment]
Email templates were put into that directory in 6.5 so just doing 6.5+7.0 will be enough

**Comment by jrouzierinverse** [comment]
Done
