### ISSUE TITLE
LDAP authentication source cache match key

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2346]
The key used to cache a match when querying an LDAP authentication source should be review and adjusted to match the  configured rule it matches. The cache would then be on a "per rule" basis and would avoid keeping in cache a result that was computed for an old rule.

**Comment by dwlfrth** [comment]
@jrouzierinverse

**Comment by jrouzierinverse** [comment]
What should be the key of the cached value.
I was thinking the source id, rule id, and the ldap filter.

**Comment by dwlfrth** [comment]
Sounds good !
