### ISSUE TITLE
Admin: Invalidating cache of a switch redirects to a page with the JSON response

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2354]
One would expect a success message to show up in the original page.

Tested on Chrome + Firefox on Ubuntu

![image](https://cloud.githubusercontent.com/assets/3857942/26472025/52759a1a-4172-11e7-95b7-f0314e23a024.png)

**Comment by dwlfrth** [comment]
Seems to be related to new JS files not being generated on build time.
Will have a discussion with @cgx for the best way to proceed

**Comment by dwlfrth** [comment]
Fixed by f9ad4559acbc87c6e2e30922162011c3b98cc686
