### ISSUE TITLE
monit scripts: shouldn't enable pfmon check on nodes 2 to n

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2357]
Right now, if you select active-active in the monit scripts, it leaves the pfmon check for nodes that aren't the default management node (first one). Our scripts should ensure that pfmon isn't monitored when generating the config on the nodes other than the management

**Comment by dwlfrth** [comment]
@julsemaan  Check for pfmon running on all of server but no tasks should be spawned. If not, open a different issue.

**Comment by julsemaan** [comment]
Confirmed the issue is that pfmon isn't starting on nodes 2 to n

Opened #2360 to track it
