### ISSUE TITLE
pfmon isn't started on nodes 2 to n of a cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2360]
To replicate:
* Build a cluster
* Start pfmon on all servers
* Realize its not starting on any servers other than the first one

Will put '+1 patch release' as I'm not sure if this was supposed to be started on 7.0

**Comment by dwlfrth** [comment]
It was working before the rework of pfmon (in v6) so it needs to be working on v7.
We aim at having all services running no matter on which node, but not "processing" or "spawning" task if they are not "the one"

**Comment by dwlfrth** [comment]
This have been lost...

https://github.com/inverse-inc/packetfence/commit/b4f58f6e20d3a6e6980b7c15f0b537c2b5410243#diff-8df3366c5071049b47d8b089f4a34db3

**Comment by dwlfrth** [comment]
Status on this ?
ETA ?

**Comment by jrouzierinverse** [comment]
Already Fixed by da3363614ac564731da9fe5ce9dcdce15411732e

**Comment by dwlfrth** [comment]
Mark it as "closed" and backport since it is milestone "+1"
