### ISSUE TITLE
Sponsor Registration: No option to cancel the registration

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2363]
Let's say the email is not sent to the sponsor.

There is not option to retry your sponsor registration.

The mighty @dwlfrth said it could create a undesired effect where the smart user could potentially spam the sponsor.

What will be the best way to handle such case.

PS: I know there is a 30 mins timeout on the sponsored code link

**Comment by julsemaan** [comment]
Technically, you can by clicking the restart button in the portal

But we could put a button like in SMS registration to make it more obvious

**Comment by lzammit** [comment]
No it does not, when you click on the restart button, you can see the registration choice but if you click  on the sponsor registration you end up on the same page saying that you access will be enable when the sponsor will grant it.

**Comment by julsemaan** [comment]
@lzammit what you describe is an open issue, see #2356

If you wait 5 seconds, the pending page will go back to sponsor registration

**Comment by julsemaan** [comment]
After discussing with the master, fixing #2356 will make him happy
