### ISSUE TITLE
oauth2 authentication does not use HTTPS_PROXY environment variable

### ISSUE THREAD

**Issue by pmos69** [inverse-inc/packetfence#2364]
Troublesome if packetfence can only access the internet through a proxy.

**Comment by fdurand** [comment]
Not sure that HTTPS_PROXY will be enough. When you do oauth2 the device itself must be able to reach the oauth login web page and if you have a proxy then the proxy must be configured on the device too.

**Comment by pmos69** [comment]
That's correct, but in out-of-band deployments packetfence connectivity and client connectivity are separate issues.
PacketFence does not need to be connected to the pre-registration VLAN used by connecting devices (and sometimes can't be).

**Comment by pmos69** [comment]
Thanks. That's correct.
In my case the issue involved the fact that the default gateway of packetfence was not in the pre-registration-vlan used by the clients but the management network, and that network was behind a proxy.
