### ISSUE TITLE
Admin: no confirmation on services 'Restart All'

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2365]
Lets say we give the STATUS admin role to some help desk guy and he accidently clicks that button by accident, he will be restarting the whole PacketFence services.

A simple confirmation would prevent Zammit's help desk cousin from putting the whole setup down

**Comment by jrouzierinverse** [comment]
That is a regression it was there before!

**Comment by julsemaan** [comment]
@lzammit must have removed it at some point, he's always the one to blame anyway

**Comment by dwlfrth** [comment]
Will it be part of 7.1 ?
ETA ?

**Comment by jrouzierinverse** [comment]
I was wrong it was only the stop had the confirmations

**Comment by dwlfrth** [comment]
@jrouzierinverse PLEASE ADVISE

**Comment by dwlfrth** [comment]
@jraby SUP !

**Comment by jraby** [comment]
oui oui vas y.
