### ISSUE TITLE
admin / distributed cache: "Can't call method "get_info" on an undefined value"

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2367]
`May 30 15:31:46 pancakeFence1 httpd_admin: httpd.admin(14215) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::Switch->invalidate_cache "Can't call method "get_info" on an undefined value at /usr/local/pf/lib/CHI/Driver/DBI.pm line 45." (pfappserver::PacketFence::Controller::Root::end)`

Steps to reproduce:
- Install PacketFence
- Go through Configurator
- Starts PacketFence services from the Configurator at the end of the steps
- In the webadmin, go in the switches configuration, click one and try to invalidate the cache

It seems to affect the distributed cache which relies on the `CHI::Driver::DBI`.

Was able to solve the issue by simply restarting PacketFence services `(/usr/local/pf/bin/pfcmd service pf restart)`

**Comment by jrouzierinverse** [comment]
Try 968db00f7ab443e2c208c1ea4040b510f8848051 to see if it fixes it

**Comment by dwlfrth** [comment]
This seems to be working.
Closing the issue.
Fixed with https://github.com/inverse-inc/packetfence/commit/968db00f7ab443e2c208c1ea4040b510f8848051

**Comment by dwlfrth** [comment]
Should we backport this or not ?

**Comment by jrouzierinverse** [comment]
No

**Comment by dwlfrth** [comment]
Not even in maintenance for 7.0 ?

**Comment by julsemaan** [comment]
IMO, we could do maintenance/7.0 although new installs (which this affects mainly) will not have this patch since it won't be part of any RPM package.

**Comment by dwlfrth** [comment]
Cherry-picked in maintenance/7.0
