### ISSUE TITLE
VLAN Enforcement

### ISSUE THREAD

**Issue by DRFP** [inverse-inc/packetfence#2390]
Hi,

Im trying to implement VLAN Enforcement on my environment but im having some troubles....

I have to interfaces eth0 that connects to the internet and eth1.

On the interface eth1 i have 3 VLANs, VLAN 10 for registration, VLAN 20 for Isolation, and VLAN 30 is none.

When a user try to register on VLAN10 he cant go throught the internet. Please help me.

**Comment by whitx** [comment]
This is a bug tracking system, for bugs.

Please use the mailing list for support.
