### ISSUE TITLE
DHCP Option 82 information not available from node info

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2396]
While it's possible to get the DHCP Option 82 information from the auditing section, it would make sense to also be able to get it from the node information.

**Comment by jrouzierinverse** [comment]
In what scenarios would you want to use it?

**Comment by julsemaan** [comment]
Well I guess it provides a better integration when people use Option82 as well as enforcement and they can see everything in the node view instead of alt-tabbing between different sections of the admin to view infos for the same device

**Comment by jrouzierinverse** [comment]
Should we just have it in a Node tab

**Comment by julsemaan** [comment]
Yeah exactly

**Comment by louismunro** [comment]
+1
