### ISSUE TITLE
We've lost a few english to english translations

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2402]
We've lost some of the translations that go from a keyword in english to a full sentence:

Ex:
help: provide info
register: not allowed to register
release: enabling network
release: reopen browser
scan: scan in progress

I'm wild guessing the translations were updated just before the release of 7.1 so we all missed it in our testing

Would be good to release 7.1.1 with the right translations once its fixed

**Comment by cgx** [comment]
Blame Mr. @fdurand (21f8e9884f74ba77462eb952e877d3ba980dc24f)!

**Comment by whitx** [comment]
Fixed by 528148d
