### ISSUE TITLE
iptables: catch all the dns traffic from the registration network

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2407]
It will be nice to catch the dns traffic in the registration network and forward it to pfdns.

It will solve the issue in Layer2 where the devices are  configured with a static dns entry.

**Comment by julsemaan** [comment]
It would seem you really **really** want this as you opened #2381 that says the exact same thing 11 days ago

**Comment by dwlfrth** [comment]
Closed, won't fix since it's a duplicate of #2381 AKA Zammitbug

**Comment by lzammit** [comment]
Ok.
