### ISSUE TITLE
DHCP broadcast packets should not be handled by all servers in a cluster

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2408]
Currently, all pfdhcplistener processes handle packets.
We should be treating broadcast requests differently from unicast ones.

**Comment by julsemaan** [comment]
Re-opening to track cherry-picking in maintenance

**Comment by dwlfrth** [comment]
Wait for 7.2 release then cherry-pick if it does not blow up

**Comment by dwlfrth** [comment]
@louismunro

**Comment by dwlfrth** [comment]
@julsemaan cherrypick

**Comment by julsemaan** [comment]
Cherry-picked in maintenance/7.0 + 7.1

**Comment by dwlfrth** [comment]
Should this now be closed as well ?

**Comment by julsemaan** [comment]
Yes me forgot to close
