### ISSUE TITLE
Pfqueue counters show a count of 0 although queue is full

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2420]
Seen on 7.1, stop pfqueue, let it fill up, do an 'LLEN Queue:pfdhcplistener' and see some numbers.
Go in PacketFence, see everything still at 0. The graph is populated with the right numbers, just the counters are all 0

Its a 3 node cluster

**Comment by dwlfrth** [comment]
`pfcmd pfqueue stats`

**Comment by julsemaan** [comment]
Just tried pfcmd pfqueue stats shows fine but nothing shows in the admin (all counter empty)

Also tried it on a standalone server and issue is the same

**Comment by jrouzierinverse** [comment]
Fixed by 12f41d64c0f64bc268667b5ef816381b7a76a709

**Comment by julsemaan** [comment]
What about my best buddies the maintenance branches, I think they'd like to get some of that commit love

**Comment by jrouzierinverse** [comment]
Pushed to maintenance/7.0 maintenance/7.1
