### ISSUE TITLE
Unable to correctly install from Debian package : 

### ISSUE THREAD

**Issue by nyaenas** [inverse-inc/packetfence#2423]
Upon installing PacketFence on a Debian 8.6 virtual machine (on VMware), i get hundreds of errors that say : 
`Couldn't write namespace ... to L2 Cache!`
![l2cache](https://user-images.githubusercontent.com/26124894/27433409-e8af204e-5754-11e7-967f-500451ed2d45.png)

Afterwards I can't seem to reach the configurator, as the httpd admin service consistently fails.
Other people have had the same issue in the past, but i haven't been able to find a sloution that works in my case too.

Thank you in advance for your advices and help.

**Comment by extrafu** [comment]
Use the mailing list.
