### ISSUE TITLE
adding a node though DAL doesn't keep the logic of node_add

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2424]
Adding a node through DAL (lib/pf/dal/node.pm) like in the RADIUS flow doesn't replicate the logic that is in node_add

Issues I've noted (may be others):
- Doesn't populate the detect_date anymore (we'll need to think about what to do with the nodes that have an empty detect_date)
- Doesn't trigger internal::node_discovered anymore

**Comment by julsemaan** [comment]
@jrouzierinverse said he'll take a look

**Comment by jrouzierinverse** [comment]
Fixed by 31d3c07895af7e0b906dd3f7f01ef2e618c09012 780ce682c02729ba34ca4cab88d856b2610f55a5 de00808866a615967890a103729be60c3decee27

This is also pushed to maintenance
