### ISSUE TITLE
New Authentication source: memberof filter does not work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2431]
If you create a AD source and you add a rule that target a specific AD group it does not match any more.

When you remove the memberof filter on the source, it matches correctly.

**Comment by jrouzierinverse** [comment]
Can you send me the authentication.conf that caused that issue

**Comment by dwlfrth** [comment]
@lzammit get debug info

**Comment by jrouzierinverse** [comment]
Fixed by c6e957e9b91db034acdf30a3878cc55afb528157 d4ca3591983abebb671c5f116e4e98995a9cf61f

**Comment by dwlfrth** [comment]
Will wait to have acknowledgement that the issue is fixed before closing it.

**Comment by lzammit** [comment]
I will test today and close. Thanks.

**Comment by lzammit** [comment]
Working, tested with authentication rule on memberof and also administration rule on memberof
