### ISSUE TITLE
trigger_violation is used for non violation events

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2432]
trigger_violation is used in the webservices to treat just about any kind of event.
It makes it harder to debug actual violations since the logs will show trigger_violations for events which have nothing to do with a violation.

We should have a trigger_event (or something like it) that is called for what is not an actual violation so that we can tell just by looking at the logs when a violation should be triggered.

**Comment by dwlfrth** [comment]
Event handler notion
