### ISSUE TITLE
httpd.admin segfault because of perl-Net-SSH2-0.63-6.1

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2435]
I've installed a brand new pf 7.1 on a new server and the httpd.admin segfault.

I've downgrade net-ssh package and the admin starts.

yum downgrade perl-Net-SSH2 --enablerepo=packetfence
---> Package perl-Net-SSH2.x86_64 0:0.45-5.2 will be a downgrade
---> Package perl-Net-SSH2.x86_64 0:0.63-6.1 will be erased

**Comment by louismunro** [comment]
I have temporarily removed the perl-Net-SSH2.x86_64 0:0.63-6.1 package from our repository until this is better understood and fixed.
It was preventing new installations from starting the configurator.

**Comment by julsemaan** [comment]
That package shouldn't be in the stable repos and should only have been there on the next release as it required adjustments in our codebase

**Comment by louismunro** [comment]
Marked as ZammitBug then ;-)
Even better, since it has a ZammitFix...

**Comment by fowleryomi** [comment]
Is there any fix to this bug? I currently have same. httpd.portal and pfdns will not start.

![image](https://user-images.githubusercontent.com/15961505/40802286-192cfb3a-650d-11e8-95e8-abcc74084365.png)
