### ISSUE TITLE
internal::node_discovered is triggered when node hasn't been created in DB

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2436]
This violation is getting triggered even though the node already existed as the DAL is saying the node was created although it wasn't 

@jrouzierinverse has a theory where the upsert says its created when actually nothing was updated (no attribute changed during the update)

**Comment by jrouzierinverse** [comment]
Should be fixed by c7ad5811f36940953b7ac2bc812f2ddf51859e3c waiting for verification from @julsemaan

**Comment by julsemaan** [comment]
No complaints from the user so I guess this should be good

**Comment by jrouzierinverse** [comment]
I will close when I put in maint
