### ISSUE TITLE
when reusedot1xCredentials is set, it always puts "username" as the PID

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2437]
Came from this commit
https://github.com/inverse-inc/packetfence/commit/cfbddecb40026680cbca66c9b62c0c30f79366a9

I'm not sure why it sets the PID to the literal string "username", probably needs to fetch the username in the session instead of something like this

Please fix so I can go back to eating turkey sandwiches

**Comment by lzammit** [comment]
Hello, @dwlfrth 

Please call me if you need details

Yes hello

**Comment by jrouzierinverse** [comment]
Please put in maintenance

**Comment by dwlfrth** [comment]
Cherry-picked to 

- `maintenance 6.5`
- `maintenance 7.0`
- `maintenance 7.1`
