### ISSUE TITLE
npm broken on RHEL and CentOS

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2438]
The packaged version of npm no longer works.

The error when trying to install any package looks like the following:

```
# npm install -g grunt-cli
npm ERR! Linux 3.10.0-514.21.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! failed to fetch from registry: https://registry.npmjs.org/grunt-cli
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

```

The current workaround is to install a newer version of nodejs.
It's available at https://nodejs.org/en/download/

We should at the very least update the developer documentation to indicate this is now required.

**Comment by dwlfrth** [comment]
There are a couple of "developer documentation" that are missing here and there.
I think that either we should revisit our `Developers Guide` or add a `Developers` section to the `Administration Guide`

**Comment by dwlfrth** [comment]
#2317

**Comment by dwlfrth** [comment]
For 7.2: add documentation
For 7.3: 

- move from `statsd` to `statssite`
- remove node dependency and instruct to use node js for assets

**Comment by louismunro** [comment]
I have repackaged the latest (6.11) version of node.
It's in our devel repos.
It would fix this issue.

Is it too late for 7.2?

**Comment by dwlfrth** [comment]
I personally do not think it is too late for v7.2

https://www.youtube.com/watch?v=lL2ZwXj1tXM

**Comment by louismunro** [comment]
Then I shall close this issue.
The new package fixes it.
