### ISSUE TITLE
Potential issue while restarting processes

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2439]
It seems that the killmode and the way we kill processes via systemd kill only the parent, which is supposed to kill their childs. Sometimes it does appear that the parent do not do as expected. This will block a process in a state with a new parent and old childs. Have to manually kill the childs.

Have seen it happen with apache processes.

**Comment by dwlfrth** [comment]
What are we doing with this one ?
Still ETA 7.2 ?

**Comment by whitx** [comment]
The "easy" fix is to comment the killmode/execstop/killsignal in the systemd service file, the bug doesn't seems to appear anymore, but this could be to aggressive. 
I have made the change only on the admin process for my testing. We should wait a bit imo and @louismunro might have more insight.

**Comment by louismunro** [comment]
The actual proper fix involves the KillMode.
I have a pull request waiting for signor @dwlfrth 's approval.
