### ISSUE TITLE
SSL certificates expiration monitoring

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2444]
Due to the impact that an expired SSL certificate could have on a PacketFence setup, it would be great to have a monitoring / alerting job that take care of checking the validity of it.

**Comment by extrafu** [comment]
Quick spec:

1. pfmon should check for expired certificates 2 times per day

1. it should check for RADIUS, Apache/haproxy certificates

1. starting T - 30 days, it should send an email to the PacketFence administrator if the certificates are about to expire

1. a nice plus would be to point the users to renewal instructions

1. if the certificates are expired, it should say so in an email

**Comment by julsemaan** [comment]
I believe we already have something like this shipped in the «best-practices» scripts:
https://github.com/inverse-inc/packetfence-monitoring-scripts/blob/master/scripts/check-certs.sh

This brings back the matter on whether or not we should :shit: :ship: PacketFence with Monit and our scripts by default or at least have it in our Administration Guide so almost all production setups have it whether they've been built by Inverse, by ZammitCorp, or by Bobbé

**Comment by dwlfrth** [comment]
💩

**Comment by lzammit** [comment]
⛵️

**Comment by dwlfrth** [comment]
🚢
