### ISSUE TITLE
Users: login remaining isn't displayed correctly in admin interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2450]
Create a user with login remaining = 4, its properly created with the right amount of logins in the database but doesn't display when viewing the user.

Not sure it only affects 7.2-devel so I'll put +1 patch release

**Comment by jrouzierinverse** [comment]
Fixed in 5b9b59d3329fc5ca8f3106364e6eefa8cbccd070 will close after I push to maint

**Comment by jrouzierinverse** [comment]
Done
