### ISSUE TITLE
Dashboard: Missing 'Apache AAA call timing'

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2451]
For some reason, I seem to be having absolutely no data in this graph

Will need to investigate why and confirm with others

**Comment by louismunro** [comment]
Some reason indeed: 
`Jul 04 16:39:10 pf-julien.inverse carbon-cache[22819]: 04/07/2017 16:39:10 :: [console] "[Errno 13] Permission denied: '/usr/local/pf/var/graphite/whisper/stats/timers/pf-julien_inverse/pf__api__radius_rest_authorize/timing'"`

**Comment by louismunro** [comment]
You have some old directories in the var/graphite/whisper (more than a year old).
I suggest deleting everything under var/graphite/whisper and letting carbon recreate them with the proper permissions.

**Comment by julsemaan** [comment]
You and your logs, I'm sure they lie, like everything all the logs in PacketFence.

I'll try this tomorrow and close if its the case

**Comment by julsemaan** [comment]
@louismunro was right, the permissions were messed up in my whisper directory
