### ISSUE TITLE
Configurator: Fingerbank does not import correctly

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2455]
Output of the command was : perl -I/usr/local/fingerbank/lib -Mfingerbank::DB_Factory -e 'my () = fingerbank::DB_Factory->instantiate(type => "MySQL", schema => "Upstream")->initialize_from_sqlite("/usr/local/fingerbank/db/fingerbank_Upstream.db") ; exit 1 if( != 200)'
Log4perl: Seems like no initialization happened. Forgot to call init()?
ERROR 1008 (HY000) at line 1: Can't drop database 'pf_fingerbank'; database doesn't exist
make: *** [init-mysql] Error 1

**Comment by julsemaan** [comment]
tried it this morning with the same build and it worked.

@lzammit will try again and let us know

**Comment by lzammit** [comment]
Because I need to wait until the import is finish before restarting packetfence-mariadb. It may takes a while.
