### ISSUE TITLE
clustering doc: webservices configuration

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2458]
At step 3.5.1 of the `PacketFence Clustering Guide`, it ask to use the administration GUI to set up a webservices username / password combination. At that point of configuration, database is running in read-only mode which makes the administration GUI configuration saving unavailable.

Options:
- Have the ability to save that one and only configuration parameter even in read-only mode;
- Modifiy documentation to set the webservices username / password combination manually in pf.conf and reload the configurations;

**Comment by dwlfrth** [comment]
In read-only mode mode, flat-file configurations should be allowed to be saved

**Comment by dwlfrth** [comment]
Exclude:

- switches
- roles
- violations

**Comment by jrouzierinverse** [comment]
This will be done via documentation.
This could not be fixed using a simple regex and there were a few edge cases that we did not consider.
