### ISSUE TITLE
Syslog parsers section in the admin should be in 'Integration'

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2467]
Right now this section is in 'Compliance' but it would be a better fit in 'Integration' since the goal of that section is to receive events from external systems

**Comment by julsemaan** [comment]
Since its @extrafu and @whitx that organized the menus, I'd like their confirmation that this makes sense before proceeding to changing this

**Comment by extrafu** [comment]
I agree that "Syslog Parsers" should be moved to Integration.

**Comment by whitx** [comment]
Yeah make sense. I'll make the change
