### ISSUE TITLE
New Authentication: No Error output if it can not save the rule.

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2468]
I've created two rules names catchall. One with the type Authentication the other one with Administration.

There is no error displayed, it says:

Success! Section Inverse-AD successfully modified in the configuration

**Comment by dwlfrth** [comment]
@jrouzierinverse can you look at this so we can get the 7.2 release out please :)

**Comment by jrouzierinverse** [comment]
Fixed by b2e22fa7fa7c8f9555fbcd9cb69dbfb139eabba3

**Comment by lzammit** [comment]
Works! Thanks!
