### ISSUE TITLE
The generic switch type is selectable from the GUI.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2470]
It's possible to configure a switch of type "Generic" from the GUI.

That switch will never work for anything.
It should not be exposed as it's misleading.

**Comment by julsemaan** [comment]
It actually does work and some of my customers even do use it.

It reacts like Switch.pm and accepts wired + wireless RADIUS

**Comment by louismunro** [comment]
My bad.
I had a look at the Switch.pm instead of Generic.pm.
Silly me...
