### ISSUE TITLE
Configreload bug 7.2

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2475]
Argument "40s" isn't numeric in division (/) at /usr/local/pf/lib/pfconfig/namespaces/resource/CaptivePortal.pm line 33.

**Comment by dwlfrth** [comment]
This will wait after 7.2 release since it does not affect the solution and too short in time for testing possible impacts. It is a one time only error message being displayed.

**Comment by julsemaan** [comment]
Reopening to cherry-pick this in maintenance once we validate there are no side effects of this

**Comment by dwlfrth** [comment]
@julsemaan PR

**Comment by julsemaan** [comment]
Just realized that this needs to wait for the 7.3 testing as it wasn't part of 7.2

So we need to cherry-pick d622690 once 7.3 is released

**Comment by julsemaan** [comment]
Cherry-picked up to maintenance 7.0 as only 7+ was reported as affected
