### ISSUE TITLE
admin gui: High MySQL resources consumption on the node page

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2479]
Related to #2329

Having a setup with around 10 000 nodes and 166 000 opened locationlogs (yes I know... that's huge but still) makes the node tab unusable. MySQL was skying high at 300-400% trying to fetch records.

We might need to adjust the query...

**Comment by dwlfrth** [comment]
I mentioned that this is somehow related to #2329 because reverting this PR was leading to a bunch of duplicate nodes but it was listing and MySQL was not eating all the available resources

**Comment by jrouzierinverse** [comment]
The issue is the combination #2329 and multiple loactionlog entries.
Given the fact there are so many loactionlog my for each node.
MySQL is choking when try to filter them out.

**Comment by jrouzierinverse** [comment]
This query will close all the locationlog entries expect for the one with the highest start time and or id.
 
```sql
UPDATE locationlog AS l1 
LEFT JOIN locationlog AS l2 
  ON l1.mac = l2.mac AND (l1.start_time < l2.start_time or (l1.start_time = l2.start_time AND  l1.id< l2.id)) 
SET l1.end_time = NOW() 
WHERE l2.mac IS NOT NULL AND l1.end_time IS NULL ; 
```

**Comment by dwlfrth** [comment]
Closing since we hit a "limitation" in the query processing due to abnormally high bogus data
