### ISSUE TITLE
ssl-certificates.conf and certificates are not sync in cluster

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2482]
Should we sync certificates files and the actual conf file for haproxy?

At the moment if you want to change the certificate for haproxy, you have to copy over the certificates in all 3 servers and change manually the config in each of them.

**Comment by whitx** [comment]
Talks about the certificate store feature are related to this.

**Comment by dwlfrth** [comment]
The best would be to have a PacketFence certificate store

**Comment by extrafu** [comment]
Related to #3169

**Comment by nqb** [comment]
Fixed by #3988. If you manage all your certificates from webadmin, they are synced in a cluster.
