### ISSUE TITLE
Juniper 802.1x De-Auth Via RADIUS

### ISSUE THREAD

**Issue by juliovalcarcel** [inverse-inc/packetfence#2488]
Would it be possible to enable RADIUS based deauthentication for all EX switches?

In https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Juniper.pm#L48 it says you don't enable 802.1x because you can't write to the SNMP OID. Instead of adding commands for clearing dot1x couldn't you use RADIUS CoA like is being done in https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Juniper/EX2200.pm#L169 ?

Or is there something I am missing?

I ask because I am trying to use this with an EX4300 series Juniper and it doesn't have the same command syntax as the EX2200/EX4200's so the MAB floating device commands in the EX2200.pm's enableMABFloatingDevice wouldn't work.

**Comment by julsemaan** [comment]
I don't believe all EX switches support CoA which is why the new module was added.

Are you using floating devices ? Because otherwise it doesn't matter if the commands do work or not ?

**Comment by julsemaan** [comment]
No answer so closing, reopen if you want to provide the requested details
