### ISSUE TITLE
Net::Telnet cause Job for packetfence-httpd.admin.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#2494]
Hi all,

I'm using PF since version 5. Now I'm trying to migrate config to CentOS 7 running PF 7.0.2 

uname -a
Linux serverXXX 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

The httpd.admin service refuses to start, it complains about a segfault in libnss_files-2.17.so

# /usr/local/pf/bin/pfcmd service httpd.admin start 
service|command
Job for packetfence-httpd.admin.service failed because the control process exited with error code. See "systemctl status packetfence-httpd.admin.service" and "journalctl -xe" for details.
httpd.admin|not started

Here is the output of log messages:

Jul 18 14:18:50 serverXXX kernel: /usr/sbin/httpd[20408]: segfault at 7efe40606e70 ip 00007efe40606e70 sp 00007fff2f8af268 error 14 in libnss_files-2.17.so[7efe472b5000+c000]
Jul 18 14:18:50 serverXXX abrt-hook-ccpp: Process 20408 (httpd) of user 0 killed by SIGSEGV - dumping core
Jul 18 14:18:51 serverXXX abrt-hook-ccpp: Failed to create core_backtrace: dwfl_getthread_frames failed: No DWARF information found
Jul 18 14:18:51 serverXXX abrt-hook-ccpp: /var/spool/abrt is 1489797841 bytes (more than 1279MiB), deleting 'ccpp-2017-07-18-14:18:18-20315'
Jul 18 14:18:51 serverXXX abrt-server: Lock file '.lock' is locked by process 20435
Jul 18 14:18:51 serverXXX systemd: packetfence-httpd.admin.service: main process exited, code=dumped, status=11/SEGV
Jul 18 14:18:51 serverXXX kill: kill: cannot find process ""
Jul 18 14:18:51 serverXXX systemd: packetfence-httpd.admin.service: control process exited, code=exited status=1
Jul 18 14:18:51 serverXXX systemd: Failed to start PacketFence Administration  Apache HTTP Server.
Jul 18 14:18:51 serverXXX systemd: Unit packetfence-httpd.admin.service entered failed state.
Jul 18 14:18:51 serverXXX systemd: packetfence-httpd.admin.service failed. 

After some debug, I realize that the problem is related to perl-Net-Telnet-3.03-19.el7.noarch.
I can’t understand why, because I create a script in the same server, using module Net::Telnet to connect to a switch and works great!

Has anyone experienced something similar?

Thank you in advance

Gustavo.

**Comment by louismunro** [comment]
Upgrade to 7.2.
IIRC there was a library issue affecting 7.0 that you may be hitting.

**Comment by gustavoortega** [comment]
Sorry, i am using 7.2, not 7.0.2

**Comment by louismunro** [comment]
Ahh, well that's different then.
reopening.

**Comment by louismunro** [comment]
Let me see if I can replicate it.

**Comment by julsemaan** [comment]
That's the issue I fought with this morning.

There is indeed an issue between mod_perl + Net::Telnet

None of our built-in modules "use" Net::Telnet anymore as they require it instead now.

So you probably have a custom switch module lying around that has a 'use Net::Telnet' in it and you need to change that to be a 'require Net::Telnet' close to where its being used.

Use this commit as an example of what to do in your custom module:
https://github.com/inverse-inc/packetfence/commit/7eec689b7e9e0990532e48163ff9e2a592783a6c#diff-ed64ce69c883cf794d282a0dc0ad81a6

And the following to find it:
```
# grep -r Net::Telnet /usr/local/pf/lib/pf/Switch/
```

**Comment by louismunro** [comment]
Right. 
I can indeed confirm that changing any "require Net::Telnet" to "use" breaks the admin.
The solution is to not do that...

Since that is fixed in our latest released code I feel we can close the issue.

**Comment by gustavoortega** [comment]
Thanks!!!
It´s work!!!!
Regards, Gustavo.
