### ISSUE TITLE
Billing tier template has 'Pouet pouet' in it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2497]
Most likely a leftover because I don't think a 'pouet pouet billing tier' is a real thing

**Comment by louismunro** [comment]
Hold on.
Just going to register pouetpouet.io.

**Comment by dwlfrth** [comment]
@cgx :)
bc207b7d18cd8cd2ee4fd8da407dc9716becc371

**Comment by cgx** [comment]
Could have been more embarrassing.
