### ISSUE TITLE
multi options input widget: Choice no longer available when removed

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2511]
Title is not really clear, I conquer. If you add an option to a multiple options input widget, then remove it, you can't add it back unless you reload the page.

<img width="420" alt="screen shot 2017-07-21 at 11 24 59" src="https://user-images.githubusercontent.com/633234/28470312-5f2d7ca2-6e07-11e7-8796-9ab1a002ccb1.png">

<img width="406" alt="screen shot 2017-07-21 at 11 25 11" src="https://user-images.githubusercontent.com/633234/28470321-644c6fc2-6e07-11e7-9cc8-406fad89631e.png">

<img width="536" alt="screen shot 2017-07-21 at 11 25 28" src="https://user-images.githubusercontent.com/633234/28470336-69b69b86-6e07-11e7-968a-19289fd82000.png">

**Comment by cgx** [comment]
Fixed by e9d6284.
