### ISSUE TITLE
 pfsetvlan segfault crashed

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#2515]
Hi, i am using PacketFence 7.2 and we have problems with pfsetvlan service.
We are migrating from PF 5.7 where this functionality works ok.

**uname -a**
Linux serverXXX 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**cat /etc/redhat-release**
CentOS Linux release 7.3.1611 (Core)

The daemon starts for a few seconds and then died with this messages:

**/var/log/messages**
Jul 24 17:06:26 packetserver systemd: Starting PacketFence pfsetvlan service...
Jul 24 17:06:31 packetserver systemd: Started PacketFence pfsetvlan service.
Jul 24 17:06:32 packetserver 07@: pfsetvlan(4) INFO: [mac:[undef]] finished (main::cleanupAfterThread)
Jul 24 17:06:33 packetserver kernel: pfsetvlan[1312]: segfault at 8 ip 00007f6c637b64ee sp 00007f6c54da5b50 error 4 in Syslog.so[7f6c637b5000+3000]
Jul 24 17:06:33 packetserver systemd: packetfence-pfsetvlan.service: main process exited, code=killed, status=11/SEGV
Jul 24 17:06:33 packetserver systemd: Unit packetfence-pfsetvlan.service entered failed state.
Jul 24 17:06:33 packetserver systemd: packetfence-pfsetvlan.service failed.
Jul 24 17:06:33 packetserver systemd: packetfence-pfsetvlan.service holdoff time over, scheduling restart.
Jul 24 17:06:33 packetserver systemd: Starting PacketFence pfsetvlan service...
Jul 24 17:06:39 packetserver systemd: Started PacketFence pfsetvlan service.
Jul 24 17:06:40 packetserver : pfsetvlan(3) ERROR: [mac:[undef]] modify of node 00:11:22:33:44:55 failed (pf::node::node_register)
Jul 24 17:06:47 packetserver ▒▒: pfsetvlan(5) ERROR: [mac:[undef]] modify of node 00:11:22:12:23:55 failed (pf::node::node_register)
Jul 24 17:06:49 packetserver kernel: pfsetvlan[1463]: segfault at 8 ip 00007fccef51d4ee sp 00007fcce130db50 error 4 in Syslog.so[7fccef51c000+3000]
Jul 24 17:06:53 packetserver systemd: packetfence-pfsetvlan.service: main process exited, code=killed, status=11/SEGV
Jul 24 17:06:53 packetserver systemd: Unit packetfence-pfsetvlan.service entered failed state.
Jul 24 17:06:53 packetserver systemd: packetfence-pfsetvlan.service failed.
Jul 24 17:06:53 packetserver abrt-server: Interpreter crashed, but no packaged script detected: 'pfsetvlan'
Jul 24 17:06:53 packetserver systemd: packetfence-pfsetvlan.service holdoff time over, scheduling restart.
Jul 24 17:06:53 packetserver systemd: Starting PacketFence pfsetvlan service...

**/usr/local/pf/logs/packetfence.log**
/usr/local/pf/logs/packetfence.log:Jul 24 17:08:19 packetserver packetfence: pfsetvlan(1) ERROR: [mac:[undef]] modify of node 00:11:22:12:23:55 failed (pf::node::node_register)
/usr/local/pf/logs/packetfence.log:Jul 24 17:08:19 packetserver packetfence: pfsetvlan(1) ERROR: [mac:[undef]] auto-registration of node 00:11:22:12:23:55 failed (main::node_update_PF)

Thanks a lot, we're trying not to rollback
Gustavo.

**Comment by louismunro** [comment]
pfsetvlan is deprecated. It's functionality has been included in pfqueue.
Disabled pfsetvlan (making sure that snmptrapd is enabled) and try again.

**Comment by dwlfrth** [comment]
Since `pfsetvlan` is, as @louismunro said, deprecated, I will go ahead and close this issue since it is not a "development" issue.
If you need any more help or guidance, please use the mailing-list.

Cheers ! 🍻

**Comment by gustavoortega** [comment]
Thanks
I do that Louis told me and now i see all activity do it by pfqueue.

But, i have more than 12000 nodes and nobody have location log

The log now show:
Jul 24 19:21:33 packetserver pfqueue: pfqueue(24737) ERROR: [mac:00:11:22:12:23:55] modify of node 00:11:22:12:23:55 failed (pf::node::node_register)
Jul 24 19:21:33 packetserver pfqueue: pfqueue(24737) ERROR: [mac:00:11:22:12:23:55] auto-registration of node 00:11:22:12:23:55 failed (pf::task::pfsnmp::node_update_PF)

**Comment by dwlfrth** [comment]
Please continue this thread in the mailing-list since Github issue main purpose is development.
