### ISSUE TITLE
PF trying to connect to Switch Group

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#2516]
Hi, i am using PacketFence 7.2.

**Linux serverXXX 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**
**CentOS Linux release 7.3.1611 (Core)**

I see these errors in pfmon.log.
I think that PF should not be trying to connect to a Switch Group.
Is this a bug?

/usr/local/pf/logs/pfmon.log:Jul 25 09:20:26 packetfenceserver pfmon: pfmon(6546) ERROR: [mac:unknown] error creating SNMP v2c read connection to **group Cisco2960**: Unable to resolve the UDP/IPv4 address "" (pf::Switch::connectRead)

Thank you very much, Gustavo.

**Comment by dwlfrth** [comment]
Hello @gustavoortega ,
It is a bug and I will address it.
Thanks!
