### ISSUE TITLE
Accented characters support for users fields

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#2519]
I am using an a google-based oauth authentication source and have enabled the automatic account creation for it. When the account is created and the first and last-names are imported into packetfence, if these users have accented characters in google, there seems to be an issue adding them to the local database.  Please see the image below for the imported user

![image](https://user-images.githubusercontent.com/10575320/28624706-52baf5d4-71f0-11e7-8ecf-5601019955b6.png)

This seems to be related to some utf-8 conversion being lost somewhere in the path. But it seems that the issue is more general with even manually created users having errors with accented characters. The user below was created manually on PF's creation screen.

![image](https://user-images.githubusercontent.com/10575320/28627415-25820924-71f8-11e7-9439-a60fc0de5617.png)

Is there support for UTF-8 / non-ascii7 characters?

**Comment by louismunro** [comment]
I can confirm this is present in 7.2.

**Comment by louismunro** [comment]
Looks like the issue is at insertion time.
If I manually insert accented characters in the DB they show up correctly in the GUI.

**Comment by garci66** [comment]
Hi Louis,
There seems to be two issues. One is inserting utf-8 characters through the GUI. That I solved by following some suggestions in the mailing list as modifying the mysql connection parameters to force UTF8:

in /usr/local/pf/lib/pf/db.pm

```
$mydbh = DBI->connect( "dbi:mysql:dbname=$db;host=$host;port=$port",
$user, $pass, { RaiseError => 0, PrintError => 0, mysql_enable_utf8 => 1 } );
```

(Added the `mysql_enable_utf8 => 1` part)

This let me add users with accented names through the GUI. But my users coming through OAuth still show the wrongly encoded names.

If you seem the "corruption" seems double in the case of the Oauth user which would be expected from two UTF-8 failed encodings. Now, the Oauth added users are only "singly-corrupted" as shown below:

![image](https://user-images.githubusercontent.com/10575320/28637826-32c01650-7219-11e7-9e79-842002f0fb93.png)

(I deleted the previous user and re-created it).

**Comment by dwlfrth** [comment]
Need to address schema in UTF-8 (major related)

**Comment by dwlfrth** [comment]
Having same kind of issue (where users details are populated through LDAP lookup) and modifying the `person` schema from latin1 to utf8 does not help.

Doing different tests with different parts of code and it seems like the issue is more in the rendering part (admin / portal / ...) than the inserting part...

**Comment by dwlfrth** [comment]
@jrouzierinverse: it seems to be exactly the kind of issue I was facing

**Comment by nqb** [comment]
Some news on this issue (in 8.1.9):
1. If I insert accented characters from GUI for a user, I get bad display in GUI and same result in DB;
2. If I sync a LDAP user with accented characters in a LDAP attribute, I get bad display too in GUI.

For 2., I put the word "Société" in LDAP company attribute.

If I use `ldapsearch` to get value of this attribute, I get a base64 value:

`company:: U29jacOpdMOp`

If I dump content of `$info` var just before https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Authentication/Source/LDAPSource.pm#L574, I get following display in log:` 'company' => 'Société'`. Accented characters are encoded in UTF8 in log file.

**Comment by julsemaan** [comment]
Not sure we can switch to a UTF-8 schema that easily.

Perhaps we could convert what we get in the DB on the input and output.

Otherwise, that will have to wait for a major release
