### ISSUE TITLE
Missing information on Nodes View

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#2520]
Hi, i am using PacketFence 7.2, running on CentOS Linux release 7.3.1611 (Core)

I noticed two things thats works on PacketFence 5.7, the previous version we were using until last week.

In Nodes View:

1- **Status "Online/Offline" is always "unknown"** for computers in VLAN enforcement. I assure myself that these computers have their corresponding location log open. (green arrow)
It seems to works only for those devices in Inline enforcement.

2- In a node view, in the Location tab, **there is no information about the vlan id.** Only it is showing Switch IP and Port number (ifIndex) (red arrow)

Thanks a lot, Gustavo.

![image](https://user-images.githubusercontent.com/5921963/28672012-d684c8c6-72b4-11e7-86da-8d565d3595bd.png)

**Comment by jrouzierinverse** [comment]
Gustavo the node status "Online/Offline" is only available when there are radius accounting entry for the mac.
When a node status is unknown that mean there is no radius accounting entry.

**Comment by jrouzierinverse** [comment]
I added the vlan to the Location Tab in the commit e7f169eab981e5ffd172bf12de81eacb20e728d3.
