### ISSUE TITLE
node search with date filter returns empty result set

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#2521]
On Packetfence 7.1 (ZEN), when using the "nodes" page and trying to search for nodes "online between" with any date ranges, an empty response is sent (no nodes found, when clearly there should be some) and the UI is half broken as shown below:

![image](https://user-images.githubusercontent.com/10575320/28684341-654ba26c-72da-11e7-86d4-1dfa045c8697.png)

Looking at the response from the search query, the following is returned:

```
                            <td><span class="label">Project-Id-Version: 7.0.0
POT-Creation-Date: YEAR-MO-DA HO:MI+ZONE
PO-Revision-Date: 2017-04-19 11:56-0400
Last-Translator: Inverse inc. &lt;info@inverse.ca&gt;
Language-Team: English
Language: en
MIME-Version: 1.0
Content-Type: text/plain; charset=ASCII
Content-Transfer-Encoding: 8bit
Plural-Forms: nplurals=2; plural=(n != 1);
</span></td>
```

(this is as a response to this query:)
```
online_date.start=2017-07-20&online_date.end=2017-07-27&start=&end=&all_or_any=all&per_page=25
```

If instead I use the "detected between" fields, it works as expected:
![image](https://user-images.githubusercontent.com/10575320/28684470-e853e656-72da-11e7-9c7c-7203de2af0b2.png)

Seems to be very easily reproducible.

**Comment by garci66** [comment]
Additionally, when I search for "nodes detected" "today" (which I expect none), the response is "correct" :

![image](https://user-images.githubusercontent.com/10575320/28684535-214a379e-72db-11e7-991c-c4ed99c885b7.png)

So the problem seems only with "online between"  search.

**Comment by julsemaan** [comment]
@jrouzierinverse interested into looking into this one since you're the node tab expert :) ?
