### ISSUE TITLE
Custom reports: Time-ranges selector

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#2522]
(Based on 7.1 ZEN, couldn't yet check on 7.2) - When creating a custom report, if there is a date_field defined, a selector is presented to the user where he can define a start and stop date/time ranges as shown below:

![image](https://user-images.githubusercontent.com/10575320/28694200-b01eab44-72fe-11e7-8b36-912010aa2af1.png)

It would be very helpful if additionally/optionally, we could have "time-ranges" selectors, such as "last 5 minutes", "last hour", "last day", etc... just as we have for "regular" reports except that it would be great to add a few "hourly granularities" as well (5 minute, 15 minutes, 1 hour, 12 hours). 

In particular, I created a custom report that shows all the hosts and their total traffic, similar to what the pie-chart does but I get the shorter-time granularity, and, if needed, I get to see additional fields as chosen (if the user is already in violation, etc).

(Not sure how to tag an issue with the "enhancement" label)

**Comment by julsemaan** [comment]
It will be in PF 8.1
