### ISSUE TITLE
LLDP detection for Snom phones, regexp not matching mac address

### ISSUE THREAD

**Issue by cmammoli** [inverse-inc/packetfence#2524]
I, I'm testing voip device detection with Cisco 2960X and Snom phones and noticed the phone didn't get detected (only DHCP fingerprinting worked):

Jul 31 12:30:47 srvpf packetfence_httpd.aaa: httpd.aaa(3493) INFO: [mac:00:04:13:24:fa:59] Could not find any IP phones through discovery protocols for ifIndex 10101 (pf::Switch::getPhonesDPAtIfIndex)

After some digging I traced the issue to the regexp 

```
                if ($portIdResult->{"$oid_lldpRemPortId.$CISCO::DEFAULT_LLDP_REMTIMEMARK.$lldpPort.$lldpRemIndex"}
                        =~ /^0x([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})$/i) {
                    push @phones, lc("$1:$2:$3:$4:$5:$6");

```

in  /usr/local/pf/lib/pf/Switch/Cisco/Catalyst_2950.pm

Snom phones report  LLDP-MIB::lldpRemPortId.0."." in the following format:
`iso.0.8802.1.1.2.1.4.1.1.7.0.1.22 = STRING: "00041324FA59:P1"
`
So you have to take into account the missing 0x at the start and the phone port at the end

--- Catalyst_2950.pm    2017-07-31 13:25:14.948608640 +0200
+++ Catalyst_2950.pm.orig       2017-07-31 13:24:50.964513181 +0200
@@ -1125,7 +1125,7 @@
                 );
                 next if (!defined($portIdResult));
                 if ($portIdResult->{"$oid_lldpRemPortId.$CISCO::DEFAULT_LLDP_REMTIMEMARK.$lldpPort.$lldpRemIndex"}
-                        =~ /^(?:0x)?([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})(?::..)?$/i) {
+                        =~ /^0x([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})$/i) {
                     push @phones, lc("$1:$2:$3:$4:$5:$6");
                 }
             }

**Comment by fdurand** [comment]
It looks good to me.
Can you do a pull request with this change and also can you have a look to other switches modules (like Brocade.pm) who use the same regex in the getPhonesLLDPAtIfIndex function.

**Comment by cmammoli** [comment]
Done, sorry for the mess I did (1st PR on github)
