### ISSUE TITLE
duplicate locationlog entries

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2527]
The battle of the duplicate locationlog entries needs to end.

Here are some solutions.

1. Treat locationlog entries like iplog entries. 
   * Where there can only be only one locationlog entry.
   * The primary key is the mac address.
   * A trigger moves the older locationlog entries to a history table.

2. Have a pfmon job cleanup stale locationlog entries. (This would be less than ideal)

3. Fix the root cause of the duplicate entries.

**Comment by julsemaan** [comment]
I'd go with option 1 and 3 where we address option 3 ASAP and aim to do option 1 in a near future

**Comment by jrouzierinverse** [comment]
So
* Option 1 for 7.4
* Option 3 for 7.3

**Comment by fdurand** [comment]
Multiples locationlog happened to me today because of undefined voip in the node table.

**Comment by jrouzierinverse** [comment]
Ok
