### ISSUE TITLE
We need a realm admin_local by default

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2529]
If you want to be able to login without a domain name via 802.1x and be able to login with a local source on the admin, you need to add a non existing domain and default to not be associated with any sources.

Create a admin_local and the code that goes with to try every auth source while trying to authenticate via the admin interface.

**Comment by dwlfrth** [comment]
Child of #2538

**Comment by dwlfrth** [comment]
Closing since will be handled in a different way with #2538
