### ISSUE TITLE
httpd.portal: Customizable max requests in haproxy

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2535]
- Add the ability to enable/disable the max requests limit.
- Add the ability to change the value of max requests

**Comment by julsemaan** [comment]
What are max requests ?

**Comment by dwlfrth** [comment]
The maximum number of requests a device can do before returning the 403 / whatnot error.

**Comment by dwlfrth** [comment]
-_-

d6243a4d0a248f03dbd7c68299eb590ba4ee31e3

**Comment by julsemaan** [comment]
Here ya go
