### ISSUE TITLE
reuseDot1x: Security concern

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2536]
It was discussed that a security concern was present in the reuseDot1x feature:
https://github.com/inverse-inc/packetfence/issues/1543

Since the modification of the behavior to address #1543, we sometime hit some corner cases where reuseDot1x does not "do" "what we want".

A patch have been created to address part of it but it might recreate the security concern:
https://github.com/inverse-inc/packetfence/commit/08bceade40de253e33cd5803e4c149a27d07eed1

What should we do ?

**Comment by fdurand** [comment]
I have another approach.
The weird thing is that we can test a username on a source that is not define on the connection profile.
Let's discuss that tomorrow.

**Comment by dwlfrth** [comment]
Child of #2538
