### ISSUE TITLE
Realm: Allow to have multiple sources

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2538]
We should allow to have multiple sources for a realm like in the case of computer auth + user auth for the same realm

**Comment by dwlfrth** [comment]
Check with @fdurand on what we do in regards of sources/realms

**Comment by fdurand** [comment]
Started to work on it in this branch https://github.com/inverse-inc/packetfence/tree/feature/advanced_realm

**Comment by dwlfrth** [comment]
If there is no realm in a source, all realm should be able to use it.
