### ISSUE TITLE
Delete a violation config from the admin gui will not remove it from the class table.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2539]
When we delete a violation config from the admin gui, this config is still present in the class table and continue to trigger violation.

**Comment by jrouzierinverse** [comment]
We need to consider what behaviours we want in different use scenarios.

**Comment by jrouzierinverse** [comment]
I think this should be only be included in the next release and not a patch release since it will change the behavior of violation handling.
