### ISSUE TITLE
Problem with custom "parseTrap" function

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#2549]
Hi, i am using PacketFence 7.2.

> Linux serverXXX 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> CentOS Linux release 7.3.1611 (Core)

We made a custom switch module for Alcatel Switchs, we are using snmp links trap.
We found that our custom function "parseTrap" is being ignored. (see LucentOS6450SEG.pm attach)
[LucentOS6450SEG.pm.txt](https://github.com/inverse-inc/packetfence/files/1222926/LucentOS6450SEG.pm.txt)

We found a temporary fix, it is based on modify one line in the "getIfIndexFromTrap" function from the Switch module (/usr/local/pf/lib/pf/Switch.pm)
**Removed Line**  `my @indexes = $self->findTrapVarWithBase($variables,".1.3.6.1.2.1.2.2.1.1.");`
**Added Line** `my @indexes = $self->findTrapVarWithBase($variables,".1.3.6.1.2.1.2.2.1.1");`

(without the final dot)

Because we see that out trap link string, for example is:

> 2017-08-14|16:02:27|UDP: [10.81.0.4]:161->[10.11.11.10]:162|0.0.0.0|BEGIN TYPE 0 END TYPE BEGIN SUBTYPE 0 END SUBTYPE BEGIN VARIABLEBINDINGS .1.3.6.1.2.1.1.3.0 = Timeticks: (163902400) 18 days, 23:17:04.00|.1.3.6.1.6.3.1.1.4.1.0 = OID: .1.3.6.1.6.3.1.1.5.4|**.1.3.6.1.2.1.2.2.1.1** = INTEGER: 3013|.1.3.6.1.2.1.2.2.1.7 = INTEGER: up(1)|.1.3.6.1.2.1.2.2.1.8 = INTEGER: up(1) END VARIABLEBINDINGS

My question is if we can generate a custom regex within our specific module, as we try to do, so we do not have to modify switch.pm, which affects all of the computers.

Thank you very much, Gustavo.

**Comment by jrouzierinverse** [comment]
Hello Gustavo,

There was a change in how we deal with traps in pf::Switch.

Traps are now pushed to a queue instead of read from a log file.

Also the function used to parse the trap data is normalizeTrap instead of parseTrap.

By default link up and link down traps are now handled for all switch. (With your fix)
