### ISSUE TITLE
SMS registration: Pin code field not in numeric

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2552]
`<input type="number">`

Since we put the pin code as numbers.

**Comment by dwlfrth** [comment]
Unsure about the behavior of different browsers and devices.
Will have to find the best way to approach this.

**Comment by cgx** [comment]
This is standard HTML 5. Browsers that don't support type *number* fall back to using a standard *text* input.

**Comment by dwlfrth** [comment]
The thing with the `number` type is that some browsers add a little up/down arrow to be used to increase or decrease the value. I'm not sure we really want that ?

What about the `telephone` type. That would allow only numbers and will instruct the device to present a digit based keyboard.

**Comment by cgx** [comment]
Using *tel* is a good idea. However, we can also [hide the steppers of an number input using CSS](https://css-tricks.com/snippets/css/turn-off-number-input-spinners/).

**Comment by dwlfrth** [comment]
I think I'd go with `telephone` since the purpose of modifying the input type is really to ease data entering for end user on a mobile device. IMO

**Comment by cgx** [comment]
With the number type, mobile devices also end up with a keypad .. Both options are good!

**Comment by dwlfrth** [comment]
@cgx, can you double-check commit (basically for CSS)
https://github.com/inverse-inc/packetfence/commit/7891f80b29c3c760b0f5f3e29eb14f95b46bf12e

**Comment by cgx** [comment]
Improved with 26ecc88 and a568c30.
