### ISSUE TITLE
syslog: *.debug messages are unhandled in our rsyslog config

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2554]
All the *.debug messages sent to syslog (pfsso does it) are going into /dev/null 

We should make those messages follow the normal log path

**Comment by louismunro** [comment]
Considering the way packetfence.rsyslog is current written all messages regardless of their loglevel are sent to the file for their process.

The missing debug messages were due to the missing section for pfsso, not the level itself.

**Comment by julsemaan** [comment]
@louismunro 

In that case we'll all good
