### ISSUE TITLE
pfsso times out on Accounting read

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2561]
The library we are using layeh.com/radius has an issue where if its not able to authenticate the packet received for some reason (it looks like it has a bug about it too), it will continue reading data from the wire although the packet has been completely read. This generates timeout errors in the log although the SSO actually completed fine.

I suggest:
1. We fork the lib and fix it dirty for now by not looking at the message authenticator in the reply
1. Find out what is going on with the authentication method of the lib
1. Provide a fix to layeh.com/radius
1. Reintegrate the official lib once our fix is accepted

One other issue is that the lib has gone through a rewrite and its API changed a lot so having to maintain a fork might be necessary for now

**Comment by ghost** [comment]
While I am unaware of any bugs in the authentication check of the radius package version that you are using, I would recommend aiming to upgrade to the latest revision. The API changes were done to make working with the library safer; all use of `interface{}` has been removed.

Please let me know if I can be of any help.

**Comment by julsemaan** [comment]
@bontibon 

Thanks for your input, @louismunro did a bit more digging yesterday and found that [IsAuthentic doesn't validate the authenticity of an accounting response](https://github.com/layeh/radius/blob/5dff33772d86f0c1d4d9d79bc09018ad3a227dd5/packet.go#L131) packets and always returns false in the version of the lib we're using

Upgrading to the latest library version is an option but given the large API changes there are, we prefered to monkey patch it for now

I think the real fix will likely be to try out the new version of the lib if accounting packets are properly validated now

**Comment by julsemaan** [comment]
Lets reopen and tag 7.4 for cleaner fix
