### ISSUE TITLE
pfdns: "Allow on registration" domain option does not work for CNAME records

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2562]
If the SRV request for the "_msdcs" returns a CNAME in lieu of an A record, pfdns is not in position to handle it.

**Comment by dwlfrth** [comment]
Having unclear behaviors..
Will continue testing and possibly postpone this to pfdns rewrite in golang

**Comment by julsemaan** [comment]
@dwlfrth clearly abandoned his investigation.

Closing and we'll open a new one if we need

**Comment by dwlfrth** [comment]
Still testing !
