### ISSUE TITLE
admin GUI: Can't change the status of a violation if changing from a state to the default state

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2569]
We ship PacketFence with `enabled=N` of the `[default]` section in `conf/violations.conf.default`.

How to reproduce:
If you want to disable a violation that is shipped as `enabled=Y` by default, change will not work. The other way around works.

**Comment by jrouzierinverse** [comment]
Fixed by 70dc8c33cc0f28e39fdc48868d9801f007a3f805

**Comment by dwlfrth** [comment]
You know what they say :)

<img width="776" alt="screen shot 2017-06-27 at 12 54 57" src="https://user-images.githubusercontent.com/633234/29641523-fd6f6ed6-8831-11e7-927a-ca3c03997453.png">

**Comment by dwlfrth** [comment]
And it's already there !

**Comment by dwlfrth** [comment]
We can no longer trust the tools :(

**Comment by jrouzierinverse** [comment]
Which tools?
