### ISSUE TITLE
packaging: "mariadb" mask

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2570]
Packaging is "masking" the default `mariadb` service.

https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L595

https://github.com/inverse-inc/packetfence/blob/devel/debian/packetfence.preinst#L61

Shouldn't we also "daemon-reload" systemd ?

`Warning: mariadb.service changed on disk. Run 'systemctl daemon-reload' to reload units.`

**Comment by louismunro** [comment]
We do it in the post install already.
Not sure it's worth doing before and after.

**Comment by louismunro** [comment]
Question answered?
