### ISSUE TITLE
Error trying to test ldap authentication source on PF 7.2

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#2574]
Hi,
I am moving from pf 6.5.1 to 7.2. I have just installed the new version using the OVA file and I am trying to configure the authentication sources I already had in the previous version.

I have configured an LDAP source that is working on PF 6.5.1 but when I clikc on TEST to verify that the server is able to connect to ldap server I get a white page with this error message "{"status_msg":"Unexpected error. See server-side logs for details."} ".

I have taken a look to server logs but I am unable to locate error log.

Thanks in advance.

**Comment by julsemaan** [comment]
@rokkhan 

I noticed no feedback was given, I'm assuming its working now given the large time this was opened, reopen it if needed
