### ISSUE TITLE
radiusd service not starting on PF 7.2

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence#2578]
I can not start radiusd service on PF 7.2 but packetfence logs show like it has started without any problems:

Aug 25 16:27:12 SLX00012040 packetfence: INFO pfcmd.pl(10671): Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Aug 25 16:27:20 SLX00012040 packetfence: INFO pfcmd.pl(10671): Connecting to MySQL database (pfconfig::backend::mysql::_get_db)
Aug 25 16:27:27 SLX00012040 packetfence: INFO pfcmd.pl(10671): Daemon radiusd-acct took 4.481 seconds to start. (pf::services::manager::launchService)
Aug 25 16:27:32 SLX00012040 packetfence: INFO pfcmd.pl(10671): Daemon radiusd-auth took 4.608 seconds to start. (pf::services::manager::launchService)

I get this error if I try to start manually:

 /usr/local/pf/bin/pfcmd service radiusd start
service|command
Checking configuration sanity...
WARNING - unknown configuration parameter general.dnsservers if you added the parameter yourself make sure it is present in conf/documentation.conf
Job for packetfence-radiusd-acct.service failed because the control process exited with error code. See "systemctl status packetfence-radiusd-acct.service" and "journalctl -xe" for details.
**radiusd-acct|not started**
Job for packetfence-radiusd-auth.service failed because the control process exited with error code. See "systemctl status packetfence-radiusd-auth.service" and "journalctl -xe" for details.
**radiusd-auth|not started**

 systemctl status packetfence-radiusd-acct.service
● packetfence-radiusd-acct.service - PacketFence FreeRADIUS multi-protocol accounting server
   Loaded: loaded (/usr/lib/systemd/system/packetfence-radiusd-acct.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2017-08-25 16:30:49 UTC; 37s ago
     Docs: man:radiusd(8)
           man:radiusd.conf(5)
           http://wiki.freeradius.org/
           http://networkradius.com/doc/
  Process: 10957 ExecStartPre=/usr/sbin/radiusd -d /usr/local/pf/raddb -n acct -Cxm -lstdout (code=exited, status=1/FAILURE)
  Process: 10952 ExecStartPre=/usr/local/pf/bin/pfcmd service radiusd generateconfig (code=exited, status=0/SUCCESS)

Aug 25 16:30:49 SLX00012040 radiusd[10957]: -x            Turn on additional debugging (-xx gives more debugging).
Aug 25 16:30:49 SLX00012040 systemd[1]: packetfence-radiusd-acct.service: control process exited, code=exited status=1
Aug 25 16:30:49 SLX00012040 systemd[1]: Failed to start PacketFence FreeRADIUS multi-protocol accounting server.
Aug 25 16:30:49 SLX00012040 systemd[1]: Unit packetfence-radiusd-acct.service entered failed state.
Aug 25 16:30:49 SLX00012040 systemd[1]: packetfence-radiusd-acct.service failed.
Aug 25 16:30:49 SLX00012040 systemd[1]: packetfence-radiusd-acct.service holdoff time over, scheduling restart.
Aug 25 16:30:49 SLX00012040 systemd[1]: start request repeated too quickly for packetfence-radiusd-acct.service
Aug 25 16:30:49 SLX00012040 systemd[1]: Failed to start PacketFence FreeRADIUS multi-protocol accounting server.
Aug 25 16:30:49 SLX00012040 systemd[1]: Unit packetfence-radiusd-acct.service entered failed state.
Aug 25 16:30:49 SLX00012040 systemd[1]: packetfence-radiusd-acct.service failed.

**Comment by louismunro** [comment]
That's a support/configuration issue (unless you can show otherwise).
Please use the mailing list for that.
