### ISSUE TITLE
pfqueue: database query failed with: MySQL server has gone away (errno: 2006), will try again (pf::db::db_query_execute)

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2580]
Tons of "database query failed with: MySQL server has gone away (errno: 2006), will try again (pf::db::db_query_execute)" from the pfqueue processes.

**Comment by dwlfrth** [comment]
Check with @julsemaan on how NOT to replay a PCAP

**Comment by julsemaan** [comment]
Instructions provided

**Comment by dwlfrth** [comment]
Bump, we need a fix / decision by the end of the day

**Comment by jrouzierinverse** [comment]
I am still trying to replicate in my environment.

**Comment by dwlfrth** [comment]
Ok then we need to take the decision on whether or not it is included in 7.3. We already past-schedule

**Comment by jrouzierinverse** [comment]
Should we close this since we were never able to replicate it.

**Comment by julsemaan** [comment]
Lets close and we'll reopen if necessary
