### ISSUE TITLE
CentOS 7: There is a chkconfig mysql script that tries to start

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2581]
The MariaDB package we ship has an old-style init.d script that is enabled in chkconfig by default and can start a mysqld_safe process

We need to disable it in our packaging to make sure it doesn't start at all

`chkconfig mysql off`

**Comment by louismunro** [comment]
Eh? 
We already do a systemctl mask mariadb.

**Comment by julsemaan** [comment]
Yep, but that doesn't seem to disable the /etc/rc.d/init.d/mysql service

Do a chkconfig --list on a PF system and you shall see

**Comment by louismunro** [comment]
Looking into it. 
This will require repackaging MariaDB and adding a "chkconfig mariadb off" to PacketFence to be on the safe side.

**Comment by louismunro** [comment]
Fixed in 79b4d67a6247bc6018222e90bfc907a3cc7af36d
