### ISSUE TITLE
Status page: we are stripping the username + realm for local accounts 

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2588]
For example if you would use an email address that is a local account on PF, that would strip the username and prevent authentication to be correct.

Potential fix would be to have the local source declare it doesn't want a stripped username.
Not sure if it would work but it technically should

**Comment by dwlfrth** [comment]
Given the short time remaining before 7.3 release, and considering there is no "all-around" (quick) fix for this one, we push it to 7.4

This needs to be addressed by reworking the way we interact with authentication sources. The decision to strip a username from its realm or not should be taken on a per basis depending of the username and realm, not before being given to the authentication mechanism.
