### ISSUE TITLE
codebase: Authentication sources Form duplication

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2605]
- html/pfappserver/lib/pfappserver/Form/Config/Source/
- html/pfappserver/lib/pfappserver/Form/Config/Authentication/Source/

**Comment by julsemaan** [comment]
@jrouzierinverse, is this still relevant, looks like #2611 already took care of this but before closing I'd like a confirmation

**Comment by jrouzierinverse** [comment]
Not relevant should close
