### ISSUE TITLE
FreeRADIUS: Segfault in syslog.so

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2607]
FreeRADIUS is segfaulting in syslog.so when using `packetfence-multi-domain.pm` module with undefined values

`kernel: radiusd[28886]: segfault at 8 ip 00007f671f1ca4ee sp 00007f66ccff6520 error 4 in Syslog.so[7f671f1c9000+3000]`

**Comment by dwlfrth** [comment]
Some insights in `packetfence.log`:

```
WARN packetfence-multi-domain.pm(2615): Use of uninitialized value $RAD_REQUEST{"Realm"} in hash elemen
t at /usr/local/pf/raddb/mods-config/perl/packetfence-multi-domain.pm line 64.
 (main::authorize)
Sep  3 20:38:25 pfa packetfence: ERROR packetfence-multi-domain.pm(2615): Accessing hash config::Realm with undef key. Caller : main::au
thorize. (pfconfig::cached_hash::FETCH)
Sep  3 20:38:25 pfa packetfence: ERROR packetfence-multi-domain.pm(2615): Accessing hash config::Realm with undef key. Caller : main::au
thorize. (pfconfig::cached_hash::FETCH)
```

**Comment by dwlfrth** [comment]
Related to #2601, #2603

**Comment by dwlfrth** [comment]
Cherry-picked to
- `maintenance/7.2`
- `maintenance/7.1`
- `maintenance/7.0`
- `maintenance/6.5`
- `maintenance/6.4`
- `maintenance/6.3`

**Comment by lzammit** [comment]
Seems the backported patch in 6.3, 6.4 and 6.5 still has cases where it core dumps.

Tested with the following file and it worked fine:
https://github.com/inverse-inc/packetfence/blob/a5ffaede947669ef5a75df57a245b67ea0037d19/raddb/mods-config/perl/packetfence-multi-domain.pm

@julsemaan will do the rest

**Comment by jrouzierinverse** [comment]
As mentioned before Syslog.so is not thread safe so the solution is don't use it.
So if log4perl is configured to use the Syslog logger then there will always be a chance where this happen.

**Comment by jrouzierinverse** [comment]
Also compare conf/log.conf.d/rlm_perl.conf conf/log.conf.d/rlm_perl.conf.example

**Comment by julsemaan** [comment]
6.5 isn't using syslog logging but the backported fix created a case where the realm can be undef and that causes freeradius to segfault outside of syslog.

**Comment by jrouzierinverse** [comment]
Then this should is a new issue not related to syslog.so
Then a new issue should be created to avoid confusion later.

**Comment by julsemaan** [comment]
I've adjusted it in the maintenance branches so I'll reclose that
