### ISSUE TITLE
portal preview: Page not found on billing form submission

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2608]
Getting a "Page not found" from Catalyst when trying to submit the billing form for confirmation (the one that interact with the payment gateway)

**Comment by dwlfrth** [comment]
Prefixing `/portal_preview` to the `/billing/[% billing.id %]/verify` action URL fixes it (but of course, breaks it in the actual portal).
Should be handled to work in both

**Comment by julsemaan** [comment]
@jrouzierinverse 

Update on this?

**Comment by jrouzierinverse** [comment]
Since the billing providers are redirecting the browsers there is no straight forward fix.

**Comment by jrouzierinverse** [comment]
We have a similar issue with the OAuth providers.

**Comment by jrouzierinverse** [comment]
How do you think we should solve this?
I would just have a warning say Billing and OAuth providers will not work as expected in the preview.

**Comment by jrouzierinverse** [comment]
Won't fix
