### ISSUE TITLE
Multiple LDAP servers should be configurable from the GUI

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2616]
We already support multiple LDAP servers in the LDAP source.
It would be nice if it was user discoverable, for example by having each server on one line with a + button.

**Comment by julsemaan** [comment]
+1 petabillion

**Comment by dwlfrth** [comment]
Code is already supporting this. Just need to add the GUI option.
Also add a "roundrobin" option.

**Comment by nqb** [comment]
@satkunas, do you think it possible to have this feature for 9.2 ?
