### ISSUE TITLE
Location log insertion bug

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2618]
From a fresh PacketFence 7.3 install, when PF receives a radius request:

Sep 12 10:48:04 superfence packetfence_httpd.aaa: httpd.aaa(5495) WARN: [mac:aa:bb:cc:dd:ee] Argument "yes" isn't numeric in numeric ne (!=) at /usr/local/pf/lib/pf/locationlog.pm line 411.
 (pf::locationlog::locationlog_synchronize)
Sep 12 10:48:04 superfence packetfence_httpd.aaa: httpd.aaa(5495) WARN: [mac:aa:bb:cc:dd:ee] Argument "no" isn't numeric in numeric ne (!=) at /usr/local/pf/lib/pf/locationlog.pm line 411.

**Comment by jrouzierinverse** [comment]
Fixed by aa86e8716663a267147f26dbe601b831b8e903d2

**Comment by lzammit** [comment]
Fixed
