### ISSUE TITLE
question: enabled vs disabled CSP headers in the 7.3

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2627]
Seems the CSP headers brought more breaking changes than expected (at least in my tests)

Lets discuss in the next meeting whether we should ship them disabled for 7.3 and aim to enable them by default in 7.4 instead as I'm pretty sure we'll find CSP related issues post 7.3 release considering the amount of pages we have in the admin

**Comment by julsemaan** [comment]
we said:

- [ ] CSP disabled for 7.3 then reenabled in devel right after
- [ ] Split portal + admin CSP parameter
- [ ] Add way to whitelist resources

**Comment by dwlfrth** [comment]
Disable right before building process

**Comment by dwlfrth** [comment]
Disable it by default for 7.3. If we want to test CSP header in 7.3 release cycle, enable it manually
