### ISSUE TITLE
admin: Users/Create access-level undesirable select box

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2628]
Seems the set access-level select box isn't the right size and sticks even if I select something else I want to assign (like a role)

Screens:
![image](https://user-images.githubusercontent.com/3857942/30345620-cca4297a-97d3-11e7-96b5-52298b373d1e.png)
![image](https://user-images.githubusercontent.com/3857942/30345630-dd08d0f4-97d3-11e7-8049-8fc913b32336.png)

This is with CSP headers disabled

**Comment by jrouzierinverse** [comment]
The issue is with this line https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static/admin/common.js#L168.
@cgx do you remember why it was done?

**Comment by cgx** [comment]
@jrouzierinverse does removing the width fixes the issue? It is necessary when the select field is inside a modal.

**Comment by jrouzierinverse** [comment]
It does in non modals.

**Comment by julsemaan** [comment]
Undesirable select box still there.

Kind of like Zammit sticking here
