### ISSUE TITLE
Admin: Prevent DB denial of service via queries

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2630]
As most of the @inverse-inc/packetfence team knows, the admin is home of a lot of CPU and I/O intensive queries that can bring a setup down if the tables grow a lot or have dirty data in them (like Zayme's panties).

An admin requesting to view a report on accounting or more recently searching nodes with doubled locationlog entries results in a long running query. If that admin clicks multiple times on the report or search because its taking too long, then he effectively brings the database down by sending that query multiple times.

We should:

- [ ] Have a timeout (even if its high like 5 minutes) on the admin interface requests so that those long running queries get eventually killed without the need to connect to MySQL and kill the queries manually
- [ ] Establish the acceptable amount of rows in the different tables for proper operation (locationlog, radacct, radacct_log, etc) and warn if it goes beyond that threshold. (*decide if built-into PF or via best practices scripts*)
- [ ] Track **all** the SQL related issues we have in a best-practices script (voip flag not being yes/no, radacct tables containing entries that haven't been closed, etc) so proper actions can be taken
- [ ] Track the current queries running in MySQL and warn when queries have been running longer than for X amount of time

Not sure if we should aim to have this in 7.3 so putting +1 for now and we'll discuss during the next team meeting

**Comment by louismunro** [comment]
I'd like to add that for any fix we should get into the habit of adding a new test that ensures there is no later regression....

**Comment by jrouzierinverse** [comment]
The query timeout could be added fairly easily.

We could combine max_statement_time and mysql_init_command

Would have to decide if this should be done for just the admin or for all services.

Additional information.

https://mariadb.com/kb/en/library/aborting-statements/
http://search.cpan.org/~capttofu/DBD-mysql-4.023/lib/DBD/mysql.pm#Class_Methods

**Comment by julsemaan** [comment]
Not sure it should be global to the application since some maintenance tasks may require long running queries (then again we'd have to see whether they should)
