### ISSUE TITLE
device_registration.allowed_devices does not pass the checkup

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#2639]
Brand new 7.2.9-0.20170914 install on CentOS 7.

I get this error: 

Checking configuration sanity...
WARNING - unknown configuration parameter device_registration.allowed_devices if you added the parameter yourself make sure it is present in conf/documentation.conf

**Comment by whitx** [comment]
I fixed that yesterday(it was not removed from documentation.conf and pf.conf.default), you probably have some device_registration parameters in your pf.conf. They should be removed

**Comment by jrouzierinverse** [comment]
I do not see it there either I will close it.

**Comment by dwlfrth** [comment]
Close won't fix (don't even exist)
