### ISSUE TITLE
CSP headers: deprecated directive

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2643]
Firefox complains about a deprecated directive:
```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.
```

I guess we should follow its advice ?

**Comment by jrouzierinverse** [comment]
We should use both according to this post

https://stackoverflow.com/questions/30023608/how-to-use-frame-src-and-child-src-in-firefox-and-other-browsers
