### ISSUE TITLE
Adding a EAPTLS source breaks admin login

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2644]
If you add an EAPTLS source you are not able to login on the admin interface via the source local. No logs, no nothing. Only error message on the admin interface "Error! Unexpected error. See server-side logs for details." No logs anywhere about that.

Example of the source which is causing issue:

[tt]
set_access_level_action=
description=test
type=EAPTLS

[tt rule base]
action0=set_role=default
match=all
class=authentication
action1=set_access_duration=12h
description=lul

**Comment by jrouzierinverse** [comment]
The issue was that any non internal sources caused a problem and the error was not properly logged.
