### ISSUE TITLE
httpd.proxy fail to start after configuring proxy interception.

### ISSUE THREAD

**Issue by tottikm** [inverse-inc/packetfence#2655]
Description: In PF 7.2 zen version updated httpd.proxy fails to start after configure the proxy interception feature. The reason is because the template in /usr/local/pf/conf/httpd.proxy.tt does not have a directive to load the proxy_connect_module directive.

To fix this, should be added the lines,
for the DEBIAN section,
 <IfModule !mod_proxy_connect.c>
    LoadModule proxy_connect_module /usr/lib/apache2/modules/mod_proxy_connect.so
 </IfModule>
 for the RHEL section, 
<IfModule !mod_proxy_connect.c>
    LoadModule proxy_connect_module modules/mod_proxy_connect.so
 </IfModule>

Probably will be good to patch /usr/local/pf/conf/httpd.proxy.tt.example too.

LABELS: Type: Bug Priority:Medium Affects:Proxy Interception feature.

Tested in last Packefence Zen VM, updated through pf-maint.pl script in addons.

Juan Valencia

**Comment by julsemaan** [comment]
@fdurand, would you be able to confirm this ?

**Comment by fdurand** [comment]
Yes i confirm, this module has been removed when we used template toolkit to generate the config.

**Comment by fdurand** [comment]
Closed by 2d58994115ef4101eada39f1a57e6bade3e7987c
