### ISSUE TITLE
fingerbank: Refactor perl lib to integrate v2

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2656]
@julsemaan please document

**Comment by julsemaan** [comment]
Documented it in our private wiki, but the principle would be to integrate a PacketFence targeted version of the collector with our perl lib and support the 2nd version of the API

**Comment by julsemaan** [comment]
Also, highly doubt this can be shipped for 7.4, so pushing the target to 8.0 although we could reevaluate it at some point if a miracle occurs

**Comment by julsemaan** [comment]
This is done, but forgot to get it closed via PR #2844
