### ISSUE TITLE
portal: Email activation unregdate race condition Fingerbank lookup

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2663]
This is a race condition that occurs when a user activates his access via the email link.

At the same time he activates it, if his user agent changes in the DB, it triggers a Fingerbank lookup in pfqueue.

In some rare conditions, the node_modify in pf::fingerbank overwrites what node_modify in the catalyst controller of email has written.

**Comment by dwlfrth** [comment]
@julsemaan document

**Comment by julsemaan** [comment]
This requires a fix through pf::dal for 7.x and one via SQL::Abstract::More for 6.x

@jrouzierinverse has those fixes and both were tested with success, the 7.x by @louismunro and 6.x by me

**Comment by julsemaan** [comment]
@jrouzierinverse could you put your fixes in the maintenance branches, I'd go back up to 6.0 IMO

Once done, also mention one of the 6.x and one of the 7.x commit IDs here for manual patching please

**Comment by jrouzierinverse** [comment]
Done and pushed to maintenance branches
