### ISSUE TITLE
Move to DAL

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2668]
To better control queries we should move to the pf::dal (PacketFence Data Access Layer if you want to fancy) framework.

This will allow rewrite queries before sending them to the database which will be needed for the multi tenant feature.

**Comment by dwlfrth** [comment]
@jrouzierinverse document

**Comment by jrouzierinverse** [comment]
To better control queries we should move to the pf::dal  (PacketFence Data Access Layer if you want to fancy) framework.

This will allow rewrite queries before sending them to the database which will be needed for the multi tenant feature.
