### ISSUE TITLE
(+) and (-) can not be seen in new authentication rule is created

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#2678]
When screen resolution is less than 1423xXXX the two add and remove buttons are not visibles.
![image](https://user-images.githubusercontent.com/32487258/31514925-60ef2b62-af61-11e7-860d-8b0d26e65bf2.png)

The problem can be solved by reducing the left margin or the size of the box on the right.

**Comment by julsemaan** [comment]
Work on 2nd margin and make + and - buttons appear on the left

**Comment by jrouzierinverse** [comment]
I quickly looked at the second margin I would need help from that @cgx.

**Comment by cheiy** [comment]
Another Possible Solution (After setup)
Edit the .css file that provides styling to the page, i.e, styles.css found under the /usr/local/pf/html/pfappserver/root/static/css/ folder by adding margin-right:30px to the form-horizontal .control-group definition. Please see attached modified style.css - you may copy it to the path after performing a backup of the existing one (just in case).
[styles.zip](https://github.com/inverse-inc/packetfence/files/1431039/styles.zip)
