### ISSUE TITLE
Wrong size of the Actions:Access Level box

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#2679]
The "chosen-choices" field is to small (12x29 instead of 210x29)
![image](https://user-images.githubusercontent.com/32487258/31515972-0cfeb582-af65-11e7-876f-a922fe9d8adf.png)

**Comment by cgx** [comment]
Should be fixed with a518a1d.

**Comment by extrafu** [comment]
@TomInverse and @lzammit Please test and close.

**Comment by TomInverse** [comment]
Tested and fixed.

**Comment by lzammit** [comment]
Works.
