### ISSUE TITLE
switch.overlay CHI namespace should use distributed storage

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2681]
Given all servers handle authentication but only store the MAC->controller association locally. If you're unlucky enough and clients on an AP only does requests on servers other than the management server, then CoA won't be working.

Adding the following to chi.conf fixed that issue for me, IMO should be a default:
```
[namespace switch.overlay]
storage=distributed
```

**Comment by jrouzierinverse** [comment]
This could be a +1 milestone

**Comment by julsemaan** [comment]
@jrouzierinverse I'm hesitating because applying the maintenance would break deauth until you receive a new request from all the APs of the network even if you don't use a cluster

**Comment by julsemaan** [comment]
Jazzed with @dwlfrth and its not a maintenance behavior to have deauth broken until a new request is received from the AP because storage was switched.

Shall this bug serve as documentation and configuration be adjusted by who needs it for 7.4 and below
