### ISSUE TITLE
RADIUS: User-Name is always normalized in accounting

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2688]
The User-Name attribute is always normalized to a column delimited MAC address when it looks like one so that we can unique index on it or the actual 802.1x username.

This has the downside of tampering with the username and when we use it in the CoA or Disconnect (ex: Ruckus), it doesn't have the expected format on the controller.

Discussed with @fdurand and we will add a column to track the pristine value of User-Name and use it for pf::node::node_accounting_dynauth_attr

Will come up with a patch for the Ruckus so we patch 7.0 - 7.3 as this will require a schema change so it won't be possible to get the real fix in the maintenance

**Comment by julsemaan** [comment]
Created branch fix/ruckus-deauth-7.0-7.3 for the Ruckus, we may need to patch other modules.

I'll cherry-pick that to maint once its confirmed as working

**Comment by fdurand** [comment]
fixed in 230669d50a3a084fe2b261cdb82dbe568b66c2e9

**Comment by julsemaan** [comment]
Cherry-picked 230669d in devel for 7.4

Then cherry-picked 1ba4dad809ccfe71d681d10167c6793287618648 in the 7.0-7.3 maintenance branches
