### ISSUE TITLE
DAL rework: Portal Preview fake node isn't created if ! exist

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2698]
If you have a fresh install of PF and don't have 00:11:22:33:44:55 as a node, then previewing the portal doesn't work since the node isn't found.

Tried it on devel, and the node gets created if it doesn't exist before doing the preview so that seems like a regression

**Comment by julsemaan** [comment]
This can actually be extended to any node visiting the portal that hasn't been created yet, like in the case of email activation done from a device that isn't the one you use on the portal

**Comment by jrouzierinverse** [comment]
Fixed by 0b8e55143812f2cc1b0024fcffb772c5e6896307
