### ISSUE TITLE
DAL rework: Cannot view user in admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2701]
To replicate:
* Go in admin
* Navigate to Users
* Click on the "admin" user
* Says "Error! Item(s) not found"

Nothing interesting outputted in the logs

**Comment by jrouzierinverse** [comment]
Fixed by e08d2b438dadbe5003ff23a022f8006f6182a56c

**Comment by julsemaan** [comment]
fix confirmed
