### ISSUE TITLE
DAL rework: Node with empty MAC gets created

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2704]
It happened to me twice since I started testing it where a node with an empty MAC gets created in my DB even if I delete it.

Couldn't find relevant log entries by digging into it.

We should have a protection in pf::dal::node that checks its a valid MAC before inserting

**Comment by jrouzierinverse** [comment]
Fixed by 0b8e55143812f2cc1b0024fcffb772c5e6896307
