### ISSUE TITLE
Webservices password with space prevents radiusd startup

### ISSUE THREAD

**Issue by miken32** [inverse-inc/packetfence#2706]
Putting a space in the web services password results in an invalid configuration file for radiusd. For example, setting the password to "First Second Third" results in errors like this:

    /usr/local/pf/raddb/radiusd.conf[81]: Syntax error: Expected comma after 'First': Second Third

I just quoted the password in the `radiusd.conf` template to prevent this problem:

    rpc_pass   = "%%rpc_pass%%"

But the substitution code should be updated to quote values as necessary.

**Comment by julsemaan** [comment]
fixed by 47c1f4c
