### ISSUE TITLE
DAL rework: admin password web interface can not be set to 'admin'

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2708]
In the configurator, you can not put the admin password to 'admin'

Oct 20 14:52:07 testing-c7 httpd_admin: httpd.admin(1489) WARN: [mac:unknown] Error while changing the password of admin (pfappserver::Model::DB::resetUserPassword)
Oct 20 14:52:15 testing-c7 httpd_admin: httpd.admin(1527) WARN: [mac:unknown] Error while changing the password of admin (pfappserver::Model::DB::resetUserPassword)
Oct 20 14:53:00 testing-c7 httpd_admin: httpd.admin(1529) WARN: [mac:unknown] Error while changing the password of admin (pfappserver::Model::DB::resetUserPassword)

I tried with DerekIsTheMostBeautiful and it works.

**Comment by jrouzierinverse** [comment]
Fixed

**Comment by julsemaan** [comment]
confirmed as fixed
