### ISSUE TITLE
DAL rework: pfqueue error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2710]
Oct 20 15:51:38 testing-c7 pfqueue: pfqueue(5111) ERROR: [mac:unknown] Undefined subroutine &pf::dal::node::is_success called at /usr/local/pf/lib/pf/dal/node.pm line 110.
 (pf::api::can_fork::notify)

**Comment by jrouzierinverse** [comment]
Fixed by 836c98be8fd22541c10e7d06dc15b29d0c362ad7
