### ISSUE TITLE
DAL rework: 802.1x autoreg request not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2711]
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) INFO: [mac:94:db:c9:38:8f:0b] handling radius autz request: from switch_ip => (10.0.0.14), connection_type => Wireless-802.11-EAP,switch_mac => (50:a7:33:71:cf:b9), mac => [94:db:c9:38:8f:0b], port => 2, username => "lzammit", ssid => ZamSecure (pf::radius::authorize)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) INFO: [mac:94:db:c9:38:8f:0b] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) INFO: [mac:94:db:c9:38:8f:0b] Found authentication source(s) : 'local,file1,Inverse-AD' for realm 'null' (pf::config::util::filter_authentication_sources)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) INFO: [mac:94:db:c9:38:8f:0b] Using sources local, file1, Inverse-AD for matching (pf::authentication::match2)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) ERROR: [mac:94:db:c9:38:8f:0b] radius authorize failed with error: Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/Authentication/Source/SQLSource.pm line 92.
 (pf::api::radius_authorize)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) WARN: [mac:94:db:c9:38:8f:0b] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 48.
 (pf::radius::rest::format_response)
Oct 20 16:15:09 testing-c7 packetfence_httpd.aaa: httpd.aaa(4886) WARN: [mac:94:db:c9:38:8f:0b] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
 (pf::radius::rest::format_response)

**Comment by jrouzierinverse** [comment]
Could be fixed by 81208f7a6157bd9c1644e87657549ad5679c82ec and 174fcb8b40added7ab6c18609a0aadf0ccff69a2

**Comment by jrouzierinverse** [comment]
Rerun your tests

**Comment by lzammit** [comment]
Fixaide!
