### ISSUE TITLE
Can't update unregistered node in the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2713]
Related to #2703 and its failing at a later stage where it can't save the node because of another issue related to the unregdate

Here is the log:
```
Oct 23 14:26:35 localhost httpd_admin: httpd.admin(2306) ERROR: [mac:unknown] Trying to save a NULL value in a non nullable field node.unregdate (pf::dal::validate_field)
Oct 23 14:26:35 localhost httpd_admin: httpd.admin(2306) ERROR: [mac:unknown] Unable to modify node '94:db:c9:38:85:5b (pf::node::node_modify)
```

**Comment by jrouzierinverse** [comment]
This is not a new issue it happens in devel.
The question is how should we handle 'empty' unreg when saving a node.

**Comment by julsemaan** [comment]
The root non-nullable probably happens in devel, but that issue was that I updated an unregistered node in the admin and it threw that error.

**Comment by julsemaan** [comment]
I'll try to replicate in latest package to see if its still an issue and will provide more details around replication

**Comment by julsemaan** [comment]
Alright, so I was able to replicate it as described where if you update an existing unregistered node in the admin, it will fail with the errors described above

**Comment by julsemaan** [comment]
This also affects node creation with the exact same error:

```
Oct 24 11:06:01 localhost httpd_admin: httpd.admin(2527) ERROR: [mac:unknown] Trying to save a NULL value in a non nullable field node.unregdate (pf::dal::validate_field)
Oct 24 11:06:01 localhost httpd_admin: httpd.admin(2527) ERROR: [mac:unknown] Unable to modify node '12:34:56:78:90:12 (pf::node::node_modify)
Oct 24 11:06:01 localhost httpd_admin: httpd.admin(2527) ERROR: [mac:unknown] modify of node 12:34:56:78:90:12 failed (pf::node::node_register)
```

**Comment by julsemaan** [comment]
I was able to replicate in devel so I'll move this out of the DAL project but it should be taken care of anyway

**Comment by jrouzierinverse** [comment]
This is fixed

**Comment by extrafu** [comment]
@julsemaan Fixed? If so, please close.

**Comment by julsemaan** [comment]
Yes it is
