### ISSUE TITLE
DAL rework: issue in DHCP processor

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2715]
Getting this error in pfqueue related to DHCP processing:

```
Oct 23 15:09:02 localhost pfqueue: pfqueue(2782) ERROR: [mac:00:0c:29:54:d9:f1] Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/dhcp/processor.pm line 139.
```

Not anything else outputed in the log for that process so can't give much more details

**Comment by jrouzierinverse** [comment]
This is fixed by ef473d219da9148286e03f44f1e05e38e53df627
