### ISSUE TITLE
DAL rework: Empty devices list for user

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2718]
When looking at a user details, no devices are listed under the 'Devices' tab

![screen shot 2017-10-23 at 16 03 57](https://user-images.githubusercontent.com/633234/31910537-d1f360fa-b80b-11e7-9c94-ee9575246e9f.png)

**Comment by jrouzierinverse** [comment]
Fixed by 18e8b7baaf2f57494bf57129712ddcbeba77215a
