### ISSUE TITLE
DAL rework: Can't create user from admin GUI

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2720]
Title says it all.

`Oct 23 16:10:57 pancakeFence1 httpd_admin: httpd.admin(12163) ERROR: [mac:unknown] Trying to save a NULL value in a non nullable field person.pid (pf::dal::validate_field)`

**Comment by jrouzierinverse** [comment]
Fixed by e08d2b438dadbe5003ff23a022f8006f6182a56c

**Comment by dwlfrth** [comment]
Not fixed.
Do not close issue unless **you tested them and it is fixed**

**Comment by jrouzierinverse** [comment]
It was fixed by this f18e0483b4b4092359d7a6faa7fd1b718be39440
