### ISSUE TITLE
DAL rework: Can't display list of violations for a device

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2721]
Title says it all

`Oct 23 16:13:35 pancakeFence1 httpd_admin: httpd.admin(12163) ERROR: [mac:unknown] Database query failed with non retryable error: Unknown column 'v.id' in 'field list' (errno: 1054) [SELECT `v`.`id`, `v`.`start_date`, `c`.`description`, `v`.`vid`, `v`.`status` FROM violation INNER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( `mac` = ? ) ORDER BY `start_date` DESC]{de:ad:be:ef:42:42} (pf::dal::db_execute)`

**Comment by dwlfrth** [comment]
Probably related to #2719

**Comment by jrouzierinverse** [comment]
Fixed by f476e6772b351520f45271b0d9fd8a0d3bc65c18
