### ISSUE TITLE
DAL rework: Can't display list of violations for a user

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2722]
Title says it all

`Oct 23 16:31:08 pancakeFence1 httpd_admin: httpd.admin(12312) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'mac' in field list is ambiguous (errno: 1052) [SELECT `id`, `mac`, `vid`, `start_date`, `release_date`, `status`, `ticket_ref`, `notes` FROM violation LEFT OUTER JOIN node ON ( `violation`.`mac` = `node`.`mac` ) LEFT OUTER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( `pid` = ? ) ORDER BY `start_date` DESC]{default} (pf::dal::db_execute)`

**Comment by jrouzierinverse** [comment]
Fixed by fbcbab0130f5b9f2b2a469e8eb4cfb457138ef64

**Comment by dwlfrth** [comment]
It misses the "Description" along with the "release date"

![screen shot 2017-10-23 at 16 54 22](https://user-images.githubusercontent.com/633234/31912725-d9cf0eee-b812-11e7-89b3-a5587db17c45.png)

**Comment by jrouzierinverse** [comment]
Fixed by e054105bde2f070261c67c47ef6eb45d04534403 and 9a6de0b6527cac329c9eb0a694b4b9c76e913c3d

Any old violations will not show the release date since it was not being set properly
