### ISSUE TITLE
DAL rework: Custom reports does not seems to work

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2723]
Title says it all

`Oct 23 16:39:13 pancakeFence1 httpd_admin: httpd.admin(12383) INFO: [mac:unknown] $VAR1 = {
          'search' => {
                        'type' => undef
                      },
          'page' => 1,
          'per_page' => undef
        };
 (pfappserver::PacketFence::Controller::DynamicReport::_search)
Oct 23 16:39:13 pancakeFence1 httpd_admin: httpd.admin(12383) ERROR: [mac:unknown] Can't prepare database statements for Report. Sub pf::Report::Report_db_prepare does not exist (pf::db::db_query_execute)
Oct 23 16:39:13 pancakeFence1 httpd_admin: httpd.admin(12383) ERROR: [mac:unknown] Can't prepare database statements for Report. Sub pf::Report::Report_db_prepare does not exist (pf::db::db_query_execute)`

**Comment by jrouzierinverse** [comment]
Strange since this does used the pf::dal

**Comment by jrouzierinverse** [comment]
Sorry I think I know the issue

**Comment by jrouzierinverse** [comment]
I cannot replicate

**Comment by dwlfrth** [comment]
Probably an issue already in devel.
Will move custom reports to DAL

**Comment by jrouzierinverse** [comment]
Fixed by 0f5a92545ea16a599ff77d7f9fc21f01d77003d3
