### ISSUE TITLE
pfmon: Issue with radius audit log cleanup not working

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2724]
I've just seen an issue on PF 6.5.1 where the RADIUS audit log cleanup task of pfmon wasn't doing its thing and was just sitting there doing nothing.

The process was alive and when stracing it, it showed it was pausing and never "unpaused" in the 5 minutes I was watching it.

After killing that process, it got back into a working state, doing the cleanup every 60 seconds as it was configured to do.

Configuration of the task uses the defaults that were shipped in 6.5.1 (1 day retention, 60s interval, 100 items at a time, 10s timeout)

**Comment by julsemaan** [comment]
Got this same issue with the nodes_maintenance task

**Comment by julsemaan** [comment]
The process was hung pausing and wasn't respecting the 1 minute interval to run the job

**Comment by jrouzierinverse** [comment]
Did it happen for 6.5.1?

**Comment by julsemaan** [comment]
Sorry, forgot to mention, the second case was on 7.3 but had the exact same behavior as the problem seen on 6.5.1

**Comment by julsemaan** [comment]
I just got the same issue on a 7.2

Showed it to @jrouzierinverse and he will investigate

**Comment by jrouzierinverse** [comment]
Can you try 4ca7ff7b50d1b57c868b2c57f4c8a8e08683deb7

**Comment by jrouzierinverse** [comment]
You showed two different issues.
* A child process was not waking up (pause was not returning).
* A child process was waking up but not doing any work.
The commit 4ca7ff7 solves the first.

The other issue is mostly likely because of the database was set in readonly mode and it never got reset for some reason.

**Comment by jrouzierinverse** [comment]
Should we close this and just reopen a new issue when we see it again?

**Comment by julsemaan** [comment]
Sure
