### ISSUE TITLE
DAL rework: Too generic error messages

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2727]
When doing an operation from the admin UI and an error comes from the database, it most of the time give the "Unexpected error, see server side logs for details" error.

When possible, it should give the error so that the user is able to resolve it without having to dig in the logs.

**Comment by dwlfrth** [comment]
Example: create a node without an unregistration date
`Oct 24 11:34:47 pancakeFence1 httpd_admin: httpd.admin(2467) ERROR: [mac:unknown] Trying to save a NULL value in a non nullable field node.unregdate (pf::dal::validate_field)`

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
This no longer happens
