### ISSUE TITLE
DAL rework: Errors with violations

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2728]
ERROR log statements when triggering a violation from the admin UI to a node

`Oct 24 11:38:09 pancakeFence1 httpd_admin: httpd.admin(2478) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'vid' in field list is ambiguous (errno: 1052) [SELECT `id`, `mac`, `vid`, `start_date`, `release_date`, `status`, `ticket_ref`, `notes` FROM violation INNER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( ( `mac` = ? AND `status` = ? AND `vid` = ? ) ) LIMIT ? OFFSET ?]{de:ad:be:ef:42:42, open, 1100001, 1, 0} (pf::dal::db_execute)
Oct 24 11:38:09 pancakeFence1 httpd_admin: httpd.admin(2478) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'vid' in field list is ambiguous (errno: 1052) [SELECT `id`, `mac`, `vid`, `start_date`, `release_date`, `status`, `ticket_ref`, `notes` FROM violation INNER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( ( `mac` = ? AND `status` = ? ) ) ORDER BY `start_date` DESC]{de:ad:be:ef:42:42, open} (pf::dal::db_execute)`

Also, unable to release the violation from the admin UI (Error! An error occurred while closing the violation.)

`Oct 24 11:40:36 pancakeFence1 httpd_admin: httpd.admin(2478) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'vid' in field list is ambiguous (errno: 1052) [SELECT `id`, `mac`, `vid`, `start_date`, `release_date`, `status`, `ticket_ref`, `notes` FROM violation INNER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( `id` = ? ) LIMIT ? OFFSET ?]{1, 1, 0} (pf::dal::db_execute)`

**Comment by dwlfrth** [comment]
**MIGHT** be related to #2726

**Comment by jrouzierinverse** [comment]
Fixed by 14af4b40ed2ccfe49333cdc64c4b0f5ff80f8395
