### ISSUE TITLE
DAL rework: Sponsor auth_log entry isn't set to completed

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2729]
If you perform sponsor authentication, the auth_log entry is never set to completed.

This used to work on this branch before the latest changes so there seems to have been a regression

**Comment by jrouzierinverse** [comment]
I cannot replicate

**Comment by julsemaan** [comment]
@jrouzierinverse will use my setup to replicate

Probably some sort of Zammitbug

**Comment by jrouzierinverse** [comment]
Fixed by c1921c19d95173b8c3960ab5662c8f2f95c4a4db
