### ISSUE TITLE
DAL rework: Impossible to create a node in the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2730]
To replicate:
* Go in the admin in Nodes->Create
* Attempt to create MAC 00:11:22:33:44:55 with role default
* Click create
* Get the error

Logs:
```
Oct 25 11:06:03 localhost httpd_admin: httpd.admin(2516) ERROR: [mac:unknown] Trying to save a NULL value in a non nullable field node.unregdate (pf::dal::validate_field)
Oct 25 11:06:03 localhost httpd_admin: httpd.admin(2516) ERROR: [mac:unknown] modify of node 00:11:22:33:44:55 failed (pf::node::node_register)
```

Seems related to #2713 but doesn't occur on devel and only occurs on the DAL branch so it seems specific to its changes versus #2713

**Comment by jrouzierinverse** [comment]
Fixed by 50f5bf5ce49f39307a9ec6d96c69a6b0e8b73f4c
