### ISSUE TITLE
DAL rework: Sending email does not work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2734]
Oct 27 09:00:17 testing-c7 packetfence_httpd.portal: httpd.portal(7511) ERROR: [mac:78:4f:43:33:45:f6] Can't send email to 'zammitludovic@gmail.com' :'SMTP Failed to connect to mail server: Connection refused at /usr/share/perl5/vendor_perl/MIME/Lite.pm line 3036.' (pf::config::util::send_mime_lite)

**Comment by jrouzierinverse** [comment]
Please verify your email settings.

**Comment by lzammit** [comment]
My bad, code 12
