### ISSUE TITLE
Multitenancy: queries related to DHCP should update node for all tenants

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2746]
When receiving a DHCP packet, the computername should be updated for the node attached to all tenants since all the "versions" of that node should reflect that information.

Same goes when performing the Fingerbank lookup

Actually, it might be easier to detect it based on the fields that are being updated. So the following fields should always be updated for all tenants:
 * computername
 * last_arp
 * last_dhcp
 * dhcp_fingerprint
 * dhcp6_fingerprint
 * dhcp_vendor
 * dhcp6_enterprise
 * device_type
 * device_class
 * device_version
 * device_score

**Comment by jrouzierinverse** [comment]
This may need to be readdressed later.
As someone can be in theory be in two different networks and each network have a different tenant.

**Comment by jrouzierinverse** [comment]
Ignore previous comment

**Comment by julsemaan** [comment]
> As someone can be in theory be in two different networks and each network have a different tenant.

Only Zammit would be able to do that
