### ISSUE TITLE
Multitenancy: tenant ID should be displayed in node index

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2747]
In the admin when viewing nodes, we indeed see all the nodes of all the tenants but there is no way to identify which tenant each one belongs to. We should add that column and have it displayed by default

**Comment by jrouzierinverse** [comment]
As discussed we may want to rework the unique id of a node.

**Comment by jrouzierinverse** [comment]
Should we close this?

**Comment by julsemaan** [comment]
I guess we can, its going to be addressed in the new admin anyway
