### ISSUE TITLE
Multitenancy: viewing a node details always shows the node of the default tenant

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2750]
To replicate:
- Have a node owned by a tenant other than the default tenant
- Try to view its details from the admin
- You'll see the node of the default tenant

**Comment by jrouzierinverse** [comment]
Fixed

**Comment by jrouzierinverse** [comment]
Please verify

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
This has been fixed
