### ISSUE TITLE
Multitenancy: deauthentication of a node should use the proper locationlog

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2753]
Right now when a node is unregistered via pfmon or via other means, the locationlog that will be taken is the one of the default tenant.

We need to scope it properly

**Comment by jrouzierinverse** [comment]
Fixed by 0ceb84e4666917973a98c2d05bb4d8aca1cf884a and 0ceb84e4666917973a98c2d05bb4d8aca1cf884a

**Comment by extrafu** [comment]
Should be closed?
