### ISSUE TITLE
Multitenancy: RADIUS local account authentication is totally broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2755]
Seems that the work in 9796be6810a03b6b04fb294cd73ec477111d2baa has totally broken the local authentication for FreeRADIUS as the queries will not pass syntax checks due to PacketFence-Tenant-Id being always undefined...

This should either be reverted so we can get packages built or fixed and tested properly

**Comment by jrouzierinverse** [comment]
This should be fixed

**Comment by extrafu** [comment]
@julsemaan Should be closed?
