### ISSUE TITLE
Add SSO support for Juniper srx firewalls

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#2763]
SSO for Juniper SRX Firewalls is not supported.
It would be nice if it was.

**Comment by brucehubbert** [comment]
Adding my 2cents on this as well. We would love to see support for SRX in 8.2

**Comment by extrafu** [comment]
Most of the code is ready: https://github.com/inverse-inc/packetfence/pull/2842

**Comment by wayne1g** [comment]
May I check what maybe the plan to add this feature? Has a release/timing been assigned?

**Comment by fdurand** [comment]
oups it's already in 8.2. Forgot to close the issue.
