### ISSUE TITLE
webauth url redirect acl

### ISSUE THREAD

**Issue by aday048** [inverse-inc/packetfence#2770]
I have encountered an issue with there Cisco Foreign WLC does not send url-redirect-acl to the Cisco Anchor controller when the ACL ID = 0

Packetfence/Freeradius is using this ID therefore does not allow the solution of MAC Filtering Radius NAC to work with an anchor controller when using registration with redirect.

Can you please either advise or modify the ACL ID.

Please see https://www.cisco.com/c/en/us/td/docs/wireless/controller/8-2/config-guide/b_cg82/b_cg82_chapter_0111010.pdf (Page 2)

Thanks

**Comment by julsemaan** [comment]
I don't really get it....

If you look at the RADIUS response, you should clearly see that PacketFence returns the **name** of the ACL and not an ID so it doesn't look like this really applies unless I'm missing something

**Comment by aday048** [comment]
Hi, Thanks for getting back to me so promptly. I have been working on this solution for sometime now. The redirecturl gets transferred across to the anchor controller but not the url-redirect-acl which is why I am assuming it ID is 0. Especially when finding that link I sent in the initial message

**Comment by julsemaan** [comment]
I don't get why you are assuming that

PacketFence **does not return the ID of the ACL** but instead returns the name of the ACL which you can easily see if you perform a packet capture on either the server or the WLC

If the WLC is bugged and maps it incorrectly to ID=0, then upgrade your WLC code to a version without the issue or create another ACL with another name so it maps it to whatever it needs.

**Comment by aday048** [comment]
Did what you said by creating an additional ACL name and it worked. Thanks you
