### ISSUE TITLE
Admin: 2 new charts/reports

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2772]
I was forced to sit through another NAC product demo and they had two reports (and pie charts):

- Top reasons for authentication failures
- Top users with most authentications

Might be nice to have in PF!

**Comment by extrafu** [comment]
👍

**Comment by extrafu** [comment]
@satkunas Get your hands more dirty!

**Comment by veedubbs** [comment]
If it helps, the product I saw did both of these as "top 10".

**Comment by fdurand** [comment]
i can't imagine the trauma, are you ok ?

**Comment by veedubbs** [comment]
I'll survive, but I'll need counseling.

**Comment by fdurand** [comment]
Yeah i can imagine ....
![hrpu3vivopal](https://user-images.githubusercontent.com/1553962/32762454-5d8209de-c8c7-11e7-9de5-1229401f426b.jpg)

**Comment by satkunas** [comment]
@veedubbs Do you recall how the "top 10" report for each was laid out? Better yet, do you have any screenshots?

**Comment by veedubbs** [comment]
I'm hoping to be able to grab some screenshots tomorrow...

**Comment by veedubbs** [comment]
Sorry @satkunas, I wasn't able to get screenshots.  I recall it was something very similar to the current reports in PF; for example, the SSIDs report (a simple pie chart with a table):


![pf](https://user-images.githubusercontent.com/382007/33040670-67412614-ce01-11e7-888b-5c3b9170961c.JPG)
