### ISSUE TITLE
npm broken on Debian 8

### ISSUE THREAD

**Issue by Sisu25** [inverse-inc/packetfence#2775]
Hello
I get the following error message :

root@bla:/usr/local/pf/html/common# npm install
npm WARN package.json packetfence-captive-portal@ No description
npm WARN package.json packetfence-captive-portal@ No repository field.
npm WARN package.json packetfence-captive-portal@ No README data
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})

> node-sass@4.6.1 install /usr/local/pf/html/common/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! node-sass@4.6.1 install: `node scripts/install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the node-sass@4.6.1 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/pf/html/common
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/pf/html/common/npm-debug.log
npm ERR! not ok code 0

If I install the latest version of node. js. it works but the statsd service won't start.

Nov 14 09:54:23 bla pfcmd[6395]: statsd|config generated
Nov 14 09:54:23 bla systemd[1]: Started PacketFence Statsd service.
Nov 14 09:54:23 bla nodejs[6482]: util.js:976
Nov 14 09:54:23 bla nodejs[6482]: throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'function');
Nov 14 09:54:23 bla nodejs[6482]: ^
Nov 14 09:54:23 bla nodejs[6482]: TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function
Nov 14 09:54:23 bla nodejs[6482]: at Object.inherits (util.js:976:11)
Nov 14 09:54:23 blanodejs[6482]: at Object.<anonymous> (/usr/local/pf/lib/Etsy/statsd/lib/config.js:33:6)
Nov 14 09:54:23 bla nodejs[6482]: at Module._compile (module.js:641:30)
Nov 14 09:54:23 bla nodejs[6482]: at Object.Module._extensions..js (module.js:652:10)
Nov 14 09:54:23 bla nodejs[6482]: at Module.load (module.js:560:32)
Nov 14 09:54:23 bla nodejs[6482]: at tryModuleLoad (module.js:503:12)
Nov 14 09:54:23 bla nodejs[6482]: at Function.Module._load (module.js:495:3)
Nov 14 09:54:23 bla nodejs[6482]: at Module.require (module.js:585:17)
Nov 14 09:54:23 bla nodejs[6482]: at require (internal/module.js:11:18)
Nov 14 09:54:23 bla nodejs[6482]: at Object.<anonymous> (/usr/local/pf/lib/Etsy/statsd/stats.js:5:14)
Nov 14 09:54:23 bla systemd[1]: packetfence-statsd.service: main process exited, code=exited, status=1/FAILURE
Nov 14 09:54:23 bla systemd[1]: Unit packetfence-statsd.service entered failed state.
Nov 14 09:54:24 bla systemd[1]: packetfence-statsd.service holdoff time over, scheduling restart.
Nov 14 09:54:24 bla systemd[1]: Stopping PacketFence Statsd service...

Thank you for your help

**Comment by julsemaan** [comment]
@fdurand our Debian king, is there anything we could do on our end or is this just a result of bad packaging updates ?

**Comment by cgx** [comment]
The best is still to install one of the [official packages](https://nodejs.org/en/download/package-manager/).

**Comment by Sisu25** [comment]
Hi
You can install Node. js 8 on Debian 8 and npm works  but you have after problem with 
the  Statsd service

With Node. js 6  everything works

**Comment by julsemaan** [comment]
Seems the resolution is in the comments, closing
