### ISSUE TITLE
LDAP Authentication sources > hierarchy browser

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#2778]
When adding rules and conditions in an LDAP/AD-based authentication source, it can be hard to a day-to-day user to figure out what the DN of a group can be when a condition on "memberOf" (or any other condition based on LDAP key/value pairs).

We should reuse the source's bind information (IP, DN, password) and provide a tree view interface to users so they can navigate in the LDAP hierarchy and find the DN they are interested in.

This can be tricky to implement efficiently as some LDAP servers expose *a lot* of data.

**Comment by fdurand** [comment]
Done
