### ISSUE TITLE
Authentication sources > Password of the day

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#2779]
If would be nice to have an authentication source "Password of the day".

Forget for now how it can be done in PacketFence using just cronjobs and htpasswd files and just think about a simple interface for it:

- you specify when the password expires
- you specify who should receive the password of the day (list of email addresses, because there could be many persons)
- you could ask for additional info (full name, email address, etc.)
- you add rules/conditions if relevant
- etc.

**Comment by julsemaan** [comment]
+1
