### ISSUE TITLE
Make the aup_text file editable in webinterface

### ISSUE THREAD

**Issue by chrkoe** [inverse-inc/packetfence#2781]
Could you please add a wysiwyg editor to edit the /usr/local/pf/html/captive-portal/templates/aup_text.html file.
It would be nice if there is also the option to add new files for different languages.

**Comment by julsemaan** [comment]
You can add files for different languages by using the following standard:
`aup_text.fr.html`

Which will apply a template for all french speaking users

As for a WYSIWYG editor, it would be nice, but a fairly large feature to develop which I don't think will be in our roadmap anytime soon

**Comment by chrkoe** [comment]
Thank you for your reply.
I already knew the procedure to add the files manually.
What I wanted is the option to add and edit the files in the GUI.

As you already mentioned this will be not developed in the near future.

**Comment by julsemaan** [comment]
You can add and edit (the text) of the files in the GUI via "Configuration->Policies and Access Control->Connection Profiles" and then edit the profile you need, then go in the "Files"

**Comment by chrkoe** [comment]
Okay, I think this should work. Thank you!
