### ISSUE TITLE
Guest Portal validate_phone_number check not work

### ISSUE THREAD

**Issue by Sisu25** [inverse-inc/packetfence#2783]
The telephone field is not checked by /usr/local/pf/pf/lib/pf/web/util. pm in the Guest Portal

You can enter everything and will be sent without error message

 e. g.

hello@test@erre and will be sent to "hello@test@erre"@mobileprovider".

Thanks for help

**Comment by julsemaan** [comment]
Seems like the validation is missing from:
html/captive-portal/lib/captiveportal/PacketFence/Form/Authentication.pm

Where we should add proper validation on the field `fields[telephone]`

**Comment by julsemaan** [comment]
This has been fixed + merged
