### ISSUE TITLE
Admin: Multiple 'Device Type' options in Nodes tab

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2789]
Running 7.3.0 and I see multiple 'Device Type' options in the Nodes search page:

![device_type](https://user-images.githubusercontent.com/382007/33088557-89c18de8-ceb3-11e7-9f23-127b0ba169d6.JPG)

**Comment by julsemaan** [comment]
@satkunas said he's bored and needs more bugfixes :)
