### ISSUE TITLE
Switch Groups view under Nodes...

### ISSUE THREAD

**Issue by ghost** [inverse-inc/packetfence#2791]
When viewing switches under Nodes and then Switch Groups on the left hand column it shows the Switch ID.  I'd like the ability to be able to have that show the Switch Description if at all possible.  It would save a lot of back and forth time trying to figure out what switch is what when troubleshooting client issues.

**Comment by julsemaan** [comment]
What we could do is display the description next to the switch ID for visual help.

The search would still be on the switch ID as that's what is stored in the DB but at least the pre-built searches would show the description

**Comment by julsemaan** [comment]
It has @satkunas written all over it :)
