### ISSUE TITLE
systemd notify does not return properly

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2792]
Experienced with `packetfence-mariadb`.

systemd does not mark the service as started

**Comment by Sisu25** [comment]
Have the same Problem with packetfence-dhcpd

**Comment by fdurand** [comment]
There is new mariadb packages i did to support systemd

**Comment by julsemaan** [comment]
Should we pin it in the Debian spec then ?

**Comment by fdurand** [comment]
The packages are already in the debian jessie repo, so a:
apt-get install --reinstall mariadb
should fix the issue.

**Comment by julsemaan** [comment]
@fdurand 

Should we increment the version number and pin it in case a user updates PF without updating the whole OS ?

**Comment by fdurand** [comment]
Yes of course, let me rebuild Mariadb

**Comment by fdurand** [comment]
Done

**Comment by julsemaan** [comment]
That can be closed, @fdurand fixed the debian packaging
