### ISSUE TITLE
Sometimes it fail when pf do sudo systemctl show -p MainPID packetfence-pfqueue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2810]
[root@pf pf]# bin/pfcmd service pfqueue restart
service|command
pfqueue|already stopped
Checking configuration sanity...
WARNING - internal network(s) not defined!
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in scalar chomp at /usr/local/pf/lib/pf/services/manager.pm line 260.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in split at /usr/local/pf/lib/pf/services/manager.pm line 261.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager.pm line 262.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in scalar chomp at /usr/local/pf/lib/pf/services/manager.pm line 260.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in split at /usr/local/pf/lib/pf/services/manager.pm line 261.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $pid in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager.pm line 262.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $state in scalar chomp at /usr/local/pf/lib/pf/services/manager.pm line 441.
[Wed Nov 29 13:06:56 2017] pfcmd.pl: Use of uninitialized value $state in split at /usr/local/pf/lib/pf/services/manager.pm line 442.
pfqueue|not started

[root@pf pf]# sudo systemctl show -p MainPID packetfence-pfqueue
MainPID=0
[root@pf pf]# su - pf
-sh-4.2$ sudo systemctl show -p MainPID packetfence-pfqueue
MainPID=0
[root@pf pf]# systemctl restart packetfence-pfqueue
[root@pf pf]# sudo systemctl show -p MainPID packetfence-pfqueue
MainPID=25144

**Comment by julsemaan** [comment]
@fdurand 

Is this still relevant ?

**Comment by fdurand** [comment]
No i don't think so
