### ISSUE TITLE
Admin: httpd.admin service restart button is a different color than the rest

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2816]
Running version 7.3.0 and the httpd.admin service has a yellow restart button, while other restart buttons are black.

Maybe it's on purpose, maybe not...?  But it caught my eye.

![services](https://user-images.githubusercontent.com/382007/33613052-28b0fe76-d999-11e7-864e-e52516ea366e.JPG)

**Comment by jrouzierinverse** [comment]
Yes it is on purpose because restarting the admin can cause you to lose your connection to the admin.
