### ISSUE TITLE
LDAP login broken on portal and potentially other places 

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2819]
Seems to be related to #2614 since that the last PR that performed changes on the subroutine where its broken:

![image](https://user-images.githubusercontent.com/3857942/33674468-aaa5d192-da7d-11e7-9cb6-cf727e2e6f2f.png)

That's on the latest devel

**Comment by jrouzierinverse** [comment]
Fixed by d4263e3ed968506bea0bc51ef44694e7b3f66da1

**Comment by extrafu** [comment]
@julsemaan Can you confirm it's fixed?

**Comment by julsemaan** [comment]
Will confirm it during my 7.4 tests
