### ISSUE TITLE
Default user is set for a device when the device hit another time the portal (inline case)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2825]
A device register on the captive portal and the pid is set to the username and the unregistration date is set to 1 year.
The day after it reconnect on the network and because his ip changed it hit the portal one more time but this time because the pid is not in the session PacketFence take the default pid and save it for the device.

**Comment by julsemaan** [comment]
As a side note, this could also happen in webauth that is using an HTML form release
