### ISSUE TITLE
VMware Deploy OVA Version 7.3.0 - Manifest Error

### ISSUE THREAD

**Issue by antoniotvr** [inverse-inc/packetfence#2826]
Hi.

At work we have vSphere version 6.5.0.

When I try do deploy ova I obtain an error in manifest validation, and then I cannot go on with deploy.

Is this solution tested with this version of VMware?

Best regards

**Comment by julsemaan** [comment]
We currently have issues with importing the ZEN in vCenter, that might be what you're hitting.

See the following issue for details: #2306

**Comment by antoniotvr** [comment]
Hi.

Thank you for the reply.

I’ve already read that thread but the solution seems not working or anyway
tricky.

It is possible to deploy older version of packetfence zen appliance to test
it?

Thank you


Il giorno mar 12 dic 2017 alle 14:35 Julien Semaan <notifications@github.com>
ha scritto:

**Comment by julsemaan** [comment]
All the versions of the ZEN are available here:
https://sourceforge.net/projects/packetfence/files/PacketFence%20ZEN/

Versions before 7.0 could work better since the manifest was changed at that moment

**Comment by antoniotvr** [comment]
Ok perfect, thank you
