### ISSUE TITLE
Firewall SSO + device status

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2846]
We should not send a start when the status of the device is unreg.

**Comment by sbodeen** [comment]
I'm seeing the same results with my copy of PacketFence 7.3.  When PacketFence sees a device is active on the network, if it had previously been registered an auth record is sent to our Fortigate regardless of whether it has an active registration or not.  The end result is that once a device is registered it will have permanent access to the Internet through our firewall.  When the registration period is over, PacketFence shouldn't be adding an auth record to the firewall.

**Comment by fdurand** [comment]
Fixes by cce9250856bcc19afb0203e558cb7e6dc95fc0d5

**Comment by sbodeen** [comment]
The above code for **go/firewallsso/base.go** and **lib/pf/firewallsso.pm** doesn't resolve the problem of sending a start message to the firewall when the status of the device is unregistered.

**Comment by julsemaan** [comment]
@sbodeen 

Its weird because it fixed it in all the environments we've tried it in.

Did you recompile the golang binary after applying the patch?

**Comment by sbodeen** [comment]
I have not done that.  I'm fairly new to PacketFence and wasn't aware of that.  I'll give it a try and report back.  This is the only thing holding us back from making the jump from v6.4 to 7.3.

**Comment by sbodeen** [comment]
Thank you for the help.  I've recompiled and the firewall sso is working as expected.
