### ISSUE TITLE
nessus6 scan but not return any results to skip other page and how can I know scan success or fail.

### ISSUE THREAD

**Issue by jynvch** [inverse-inc/packetfence#2851]
Hi,

As tittle said,I use the version packetfence-zen-7.3.0 and try to use scanner before guest register network . I find the scan process is running but not time display and it was run one by one to request to scan and nerver stop . It is so bad that I dont know why is this . for detail , I add a scan engines  and  next to add this in the configuration->connection profiles  :default . I want to know how can I do to resolve this problem ,and how can I know the scan success or fail . I would like to beg for something help . Thank you very much.

Greetings
lujunjie

**Comment by julsemaan** [comment]
@lujunjiecs 

This bug tracker is for development issues only and confirmed bugs.

For general help please use the mailing list
