### ISSUE TITLE
Issue with services at the end of the configurator.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2856]
At the end of the configurator, PacketFence is waiting for services like pfsetvlan to start even if the service is not enable to start.
![end_conf](https://user-images.githubusercontent.com/1553962/34679513-36edc79a-f464-11e7-9a80-4d0cf386e475.png)
![status](https://user-images.githubusercontent.com/1553962/34679547-50c25046-f464-11e7-8610-0cefe9350a59.png)

**Comment by jrouzierinverse** [comment]
Just in devel?

**Comment by fdurand** [comment]
Yes, devel package from this night.

**Comment by julsemaan** [comment]
I got the same issue on devel

**Comment by extrafu** [comment]
I also got the same issue. This prevents the configurator from completing properly.
