### ISSUE TITLE
DHCP OMAPI: Constantly freezing under high load in clusters

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2857]
This has been happening for a while where under very high load, the OMAPI socket would freeze.

Seems to be tied to active/active clusters since standalone and active/passive don't have that behavior, at least from what I know.

Pointing the OMAPI to the second server of the cluster (using its IP in the OMAPI section), the OMAPI has stopped freezing from my current tests.

In order to do this, I had to:
* Make the OMAPI config manually (its not enabled if not pointing on localhost). [see here](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/services/manager/dhcpd.pm#L232)
* Open port 7911 on the right interface in iptables

Suggestions for the future would be:
- [ ] Enable the OMAPI even if we're not pointing on localhost
- [ ] Add a commented line for opening port 7911 in iptables.conf
- [ ] Create a best-practices checkup script that will provide instructions to workaround this issue when running a cluster

Doing the first 2 ones for 7.4 would be nice since they are simple

**Comment by extrafu** [comment]
Should we close this bug as we're moving towards pfdhcp? It's always possible for folks using an older release to use their Google-fu skills and find this bug for some {pers,ins}piration.

**Comment by julsemaan** [comment]
@extrafu I do agree, it doesn't make sense to put more work into something that we'll be replacing anyway
