### ISSUE TITLE
ipset cache: Use cross-process datastore

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2860]
Right now the datastore used by pf::ipset_cache is in-memory.

Since the consumers of that cache are now all multi-processes (pfqueue and pfdns), it would be more effective to have this cache distributed across all the processes by using the Redis datastore through pf::CHI

**Comment by julsemaan** [comment]
As a note, it would likely be useful to flush the ipset cache during the start/restart of iptables since the sets are emptied at that moment. Will need to validate if this is necessary, buts its something to keep in mind

**Comment by extrafu** [comment]
@fdurand Is this bug relevant with the pfipset code?

**Comment by jrouzierinverse** [comment]
Should we still keep this if we have the pfipsetd?

**Comment by julsemaan** [comment]
We'd have to see if we implement the cache directly in pfipsetd so that it fixes this one so that its centralized into the right place

**Comment by julsemaan** [comment]
ipset_cache isn't in use anymore so this isn't relevant
