### ISSUE TITLE
Node save produce weird admin interface

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2864]
![node_save](https://user-images.githubusercontent.com/1553962/34691599-1011a0ac-f48b-11e7-896b-a80a4f5ef4a3.png)

**Comment by fdurand** [comment]
Firefox and chrome

**Comment by julsemaan** [comment]
Getting the same behavior when applying batch actions to nodes

**Comment by extrafu** [comment]
@cgx Maybe you can have a quick look at that one?

**Comment by jrouzierinverse** [comment]
The issue is CSP related turn off it magically works again.

**Comment by extrafu** [comment]
@lzammit Please test and close if all good.

**Comment by extrafu** [comment]
@lzammit Bump.

**Comment by lzammit** [comment]
Fixed!
