### ISSUE TITLE
Action selection list is hidden (Source rules)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2865]
![action](https://user-images.githubusercontent.com/1553962/34691735-92e20936-f48b-11e7-8b74-6ff57be98ee5.png)

**Comment by jrouzierinverse** [comment]
This seems to be an issue with the chzn widget.

**Comment by cgx** [comment]
Yes, that [6 year-old issue](http://bit.ly/2mH4MVm).
