### ISSUE TITLE
Portal Modules -> Tree view is empty

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2866]
![module](https://user-images.githubusercontent.com/1553962/34725123-f937ec2c-f51d-11e7-906f-93ad232ebb8f.png)

**Comment by julsemaan** [comment]
Seems to be our best friends (the CSP headers in case you forgot about them)

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://172.20.155.47:1443 blob:”). Source: 
var data = JSON.parse('[{\"children\":[.... configuration:1
```

This brings back "zi question" of enabling/disabling the CSP headers for our next release.

I guess we can chat about it in the next meeting
