### ISSUE TITLE
Packaging: Disabling selinux without rebooting seems to be failing

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2867]
Seems that disabling selinux via `setenforce 0` doesn't disable selinux anymore.

Looking at `sestatus`:
```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          disabled
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

Tried to do `setenforce 0` again and the sestatus output stayed unchanged

We should likely adjust the documentation

**Comment by extrafu** [comment]
I'll look into this.

**Comment by extrafu** [comment]
That behaviour is normal.
Look at the current mode: "permissive".
If you want to completely disable selinux, you must reboot the box after modifying /etc/sysconfig/selinux.

If you need help in rebooting boxes, please talk to @lzammit . He's the kingpin in this matter.
