### ISSUE TITLE
one of haproxy's child can die and not be re-spawned by the master process 

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2875]
I've seen this a few times where the haproxy process that handles the portal dies and isn't respawned by its parent process (/usr/sbin/haproxy-systemd-wrapper)

We should try to investigate the issue and add monitoring on a localhost port for the portal frontend though monit

**Comment by extrafu** [comment]
@fdurand Please review the PR fixing this issue and merge/close.

**Comment by julsemaan** [comment]
#3016 should address this in a better way.

Now there should only be 2 childs of the haproxy wrapper and all of them are related to the portal

I tried to kill -11 both of them, one resulted in a service stop (which would be caught by monit) and the other just made the wrapper exit but the other process serving HTTP stayed there and the portal was still working
