### ISSUE TITLE
Our version of Net::Nessus::REST is missing methods

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2877]
Probably the contributor who send us the Nessus6 patch had a more recent version of the library since its missing the get_scanner_id which isn't in the latest CPAN version but is in their repo.

Can my best buddy @fdurand look at this

Here is the GitHub repo:
https://github.com/guillomovitch/Net-Nessus-REST

If its not fixed, I'll cry like a baby in your office until its fixed

**Comment by fdurand** [comment]
New perl lib has been uploaded in the repo, a yum update perl-Net-Nessus-REST --enablerepo=packetfence should fix it.

**Comment by julsemaan** [comment]
We can close this in that case
