### ISSUE TITLE
Portal preview: Using OAuth redirects to wrong domain

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2882]
When doing the oauth flow and pressing on "login" after accepting the AUP, I get redirected to https://1.2.3.4:1443/portal_preview/o/oauth2/auth?bunch-of-params...

Instead it should have been https://facebook.com/o/oauth2/auth

So it seems like the URL rewriting done in the portal preview is rewriting a bit too much stuff

**Comment by extrafu** [comment]
Please put in maintenance too.

**Comment by julsemaan** [comment]
Since the fix is in a .example and the issue isn't high impact, I didn't cherry pick it

Anyone has a problem with that, he can complain to @lzammit
