### ISSUE TITLE
A management user can override an account that was not created by him. 

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#2883]
Let say you assign the admin role to a user like that:
![admin_role](https://user-images.githubusercontent.com/1553962/34844603-073c092a-f6e0-11e7-9025-fc1e03e55a39.png)

Then this user will be able to override an already created user by checking "Username (PID) overwrite".

**Comment by extrafu** [comment]
@fdurand Get feedback on the patch and close if all set.

**Comment by fdurand** [comment]
Patch applied and it has been confirmed that it fixed the issue.
