### ISSUE TITLE
Violation: Issue triggering a generic violation the first time for a node

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2890]
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) INFO: [mac:unknown] grace expired on violation 1300000 for node 54:26:96:d9:c8:b3 (pf::violation::violation_add)
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) INFO: [mac:unknown] violation 1300000 added for 54:26:96:d9:c8:b3 (pf::violation::violation_add)
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) INFO: [mac:unknown] executing action 'reevaluate_access' on class 1300000 (pf::action::action_execute)
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) INFO: [mac:unknown] re-evaluating access (manage_vopen called) (pf::enforcement::reevaluate_access)
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) INFO: [mac:unknown] is currentlog connected at (10.0.0.14) ifIndex 0 guest (pf::enforcement::_should_we_reassign_vlan)
Jan 12 16:35:35 superfence httpd_admin: httpd.admin(17970) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->triggerViolation "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/lib/CHI/Driver/DBI.pm line 43." (pfappserver::PacketFence::Controller::Root::end)

If I re-trigger the same violation it says that it exist already and displays it:

Jan 12 16:36:04 superfence httpd_admin: httpd.admin(17947) INFO: [mac:unknown] violation 1300000 already exists for 54:26:96:d9:c8:b3, not adding again (pf::violation::violation_add)

**Comment by julsemaan** [comment]
Couldn't replicate that issue, pretty much like @lzammit 

That seems like the DB handle for CHI that is an empty string and I can't see how this can happen.

**Comment by extrafu** [comment]
Should we close it? Or remove it out of v7.4?

**Comment by jrouzierinverse** [comment]
I would say close it we can alway reopen it if we see this again.

**Comment by extrafu** [comment]
Closing for now.

**Comment by cmammoli** [comment]
It happens for if I try to do any of theese:

Restart switchport:
Jan 29 11:52:00 srvpf httpd_admin: httpd.admin(2125) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->restart_switchport "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/lib/CHI/Driver/DBI.pm line 43." (pfappserver::PacketFence::Controller::Root::end)

Bull unregister:
Jan 29 11:52:18 srvpf httpd_admin: httpd.admin(4681) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->bulk_deregister "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/lib/CHI/Driver/DBI.pm line 43." (pfappserver::PacketFence::Controller::Root::end)

Set a node to unregistered:
Jan 29 11:52:37 srvpf httpd_admin: httpd.admin(2125) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->update "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/lib/CHI/Driver/DBI.pm line 43." (pfappserver::PacketFence::Controller::Root::end)

**Comment by cmammoli** [comment]
This is with debug enabled:

Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:[undef]] (Re)Connecting to MySQL (pid: 28442) (pf::db::db_connect)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:[undef]] connected (pf::db::db_connect)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='Default', key='inreadonly', cache='RawMemory', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] not checking db handle, it has been less than 30 sec from last connection (pf::db::is_old_connection_good)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] not checking db handle, it has been less than 30 sec from last connection (pf::db::is_old_connection_good)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] No wsrep provider so considering wsrep as healthy (pf::db::db_wsrep_healthy)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache set for namespace='Default', key='inreadonly', size=1, expires='5s', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='Default', key='HASH(0x555e329d7298)', cache='RawMemory', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache set for namespace='Default', key='{"encoding":null,"reconnect":"60","server":"127.0.0.1:6379"}', size=1, expires='never', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:124eb2e7dfa483170770149e0e0d89b212c64914', cache='Redis', time='1ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='session:124eb2e7dfa483170770149e0e0d89b212c64914', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='Default', key='inreadonly', cache='RawMemory', time='0ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->restart_switchport "Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/pf/lib/CHI/Driver/DBI.pm line 43, <DATA> line 1003." (pfappserver::PacketFence::Controller::Root::end)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:124eb2e7dfa483170770149e0e0d89b212c64914', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:124eb2e7dfa483170770149e0e0d89b212c64914', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:124eb2e7dfa483170770149e0e0d89b212c64914', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache set for namespace='httpd.admin', key='expires:124eb2e7dfa483170770149e0e0d89b212c64914', size=24, expires='1d', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
Jan 29 12:32:09 srvpf httpd_admin: httpd.admin(28373) DEBUG: [mac:unknown] cache set for namespace='httpd.admin', key='session:124eb2e7dfa483170770149e0e0d89b212c64914', size=259, expires='1d', cache='Redis', time='0ms' (CHI::Driver::_log_set_result)
