### ISSUE TITLE
Node: Can not change a role for registered node using the inline L2 mode

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2894]
When I try to change the role of a registered node I have the error:

Jan 15 13:34:46 superfence httpd_admin: httpd.admin(20121) ERROR: [mac:unknown] Unable to modify node '00:11:22:33:44:55' (pf::node::node_modify)

**Comment by extrafu** [comment]
@fdurand Had a chance to look at it?

**Comment by fdurand** [comment]
Looks good to me.
