### ISSUE TITLE
IOS Provisioner: does not display the downloadable profile

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2898]
Jan 15 17:13:38 superfence httpd_portal: 172.145.25.12 127.0.0.1 - - [15/Jan/2018:17:13:38 -0500] "superfence.inverse.ca" "GET /wireless-profile.mobileconfig HTTP/1.1" 200 6259 "https://superfence.inverse.ca/captive-portal?destination_url=http://captive.apple.com/hotspot-detect.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202" 54140

I can see the profile but if I click to download it, it does not work.

Looks like it's a portal issue ?

**Comment by julsemaan** [comment]
Anything else in the other logs ?

**Comment by lzammit** [comment]
Bug related to the iOS 11.2.2 where it doest not ask the authorization to display the profile setting to install the wireless profile on the 'splash page'.

Works on safari.

**Comment by lzammit** [comment]
![1](https://user-images.githubusercontent.com/5261214/34990181-204489ea-fa93-11e7-91c1-02fa5182af9d.png)
![2](https://user-images.githubusercontent.com/5261214/34990182-20519162-fa93-11e7-9bc0-2cae1f2db9c4.png)

**Comment by extrafu** [comment]
What's the status update on this bug?

**Comment by julsemaan** [comment]
We have the choice between leaving it as is or use an OS version check for the impacted version (11.2) and warn the user about that behavior.

Not a bug we seem to be able to fix from our side as it seems to be bugged in the iOS itself.
Couldn't find anything on Apple's forums though, so unsure about how we should proceed.

**Comment by extrafu** [comment]
I would say we push it to v8 for now. Perhaps it's a temporary issue on OS X.

**Comment by julsemaan** [comment]
@lzammit tried it again, now it interprets the profile as html

I will check that the content type is correct

**Comment by julsemaan** [comment]
Content type is the same as it was before

I tried adjusting the filename + content type + whether or not its sent as an attachment and we get consistent results of having the file interpreted as HTML when used in the portal popup.

I will make a check in the provisioning for iOS 11.2 and above and show a clear warning to the user for those versions that the provisioning needs to happen inside a real browser

**Comment by julsemaan** [comment]
Just pushed a commit to address it via user instructions, will move to +1 patch release so we follow a potential fix from Apple

**Comment by lzammit** [comment]
Fixed with a message saying that you have to do the provisioning on Safari.
