### ISSUE TITLE
Admin: Cannot add/remove columns in node view

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2901]
In the nodes tab, adding/removing columns to display doesn't do anything

No error in the browser console, CSP headers are disabled

Tried on Firefox and Chrome, both on Ubuntu

**Comment by cgx** [comment]
Can't reproduce. Notice that the table is updated only once you click outside the columns menu.

**Comment by julsemaan** [comment]
@cgx 

Yes that is how I tried it.

I'll give it another try using the latest package and see if its still a thing

**Comment by julsemaan** [comment]
Was able to replicate with @cgx 

He said he'll look into it

**Comment by cgx** [comment]
Fix with f5da894
