### ISSUE TITLE
Release date not inserted in pf::violation::violation_add

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#2912]
https://github.com/inverse-inc/packetfence/blob/76cd472b0068aa36b5cdcfa2c15eb509cae688bc/lib/pf/violation.pm#L439

Line should read:

`release_date => $data{release_date},`

**Comment by julsemaan** [comment]
You do seem right, that seems like a copy/paste issue during the DAL refactor

You want to get that fixed into devel and cherry-pick in maintenance/7.4 ?
