### ISSUE TITLE
Database Query Failed error in PF7.4

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#2915]
Seen in logs/packetfence.log on a customer standalone server:

`Jan 29 14:15:27 t7packetfence pfqueue: pfqueue(27121) ERROR: [mac:unknown] Database query failed with non retryable error: Deadlock found when trying to get lock; try restarting transaction (errno: 1213) [UPDATE node SET last_dhcp = ? WHERE ( node.mac = ? )]{2018-01-29 14:15:27, 3c:2e:ff:a8:e2:13} (pf::dal::db_execute) Jan 29 14:15:27 t7packetfence pfqueue: pfqueue(27121) ERROR: [mac:unknown] Unable to modify node '3c:2e:ff:a8:e2:13 (pf::node::node_modify)`

**Comment by julsemaan** [comment]
@jrouzierinverse 

Could you look into this for an eventual 7.4.1 early next week

**Comment by julsemaan** [comment]
@jrouzierinverse and @TomInverse 

Is this still relevant ?

**Comment by jrouzierinverse** [comment]
This has been fixed by 9ba969416580bc3a7c86c8644004e35c8706f6e1
