### ISSUE TITLE
Database schema incorrect - new installation

### ISSUE THREAD

**Issue by jimmyc06** [inverse-inc/packetfence#2927]
Installing a clean version of Packetfence 7.4.0 on a clean Debian 8.x server generates 'Database schema version 7.3.9 does not match installed version 7.4.0' error, causing PacketFence services not to start.
![error1](https://user-images.githubusercontent.com/35770978/35805212-3a0b8e80-0a7b-11e8-99e4-b9291d7d92a4.PNG)

Using the script mentioned in the upgrade guide obviously does not work as this is a clean installation:
![error2](https://user-images.githubusercontent.com/35770978/35805213-3a22fb10-0a7b-11e8-899f-87e07e74ccbc.PNG)

**Comment by julsemaan** [comment]
This is really weird, seems the Debian package used the wrong version of the schema file.

I'll need @fdurand to help me troubleshoot this, as far as I can see the schema files are all right in the stable release and RHEL packages were tested successfully.

**Comment by julsemaan** [comment]
I discussed with @fdurand 

The Debian stable package needed to be cleared after the initial package was incorrect. Since it wasn't, then the current Debian package uses the wrong schema version.

@fdurand told me he'll clear out the packages and build the 7.4.0 package again

**Comment by fdurand** [comment]
Repo has been updated.
