### ISSUE TITLE
Screen shows duplicates after clicking on logo

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#2930]
Admin page becomes bugged and shows duplicates:

![pf-screen-bug](https://user-images.githubusercontent.com/36165527/35869667-aa3d650e-0b2d-11e8-8ebb-20b1a071de88.png)

Steps to reproduce:
1) Click on "Status"
2) Click on PacketFence Logo

This can be seen in the page's Element -> Console:
![packetfence-bug](https://user-images.githubusercontent.com/36165527/35869792-fd7187a0-0b2d-11e8-9e9b-7aac651c527d.png)

Allan

**Comment by julsemaan** [comment]
@jrouzierinverse 

Can you check if this is still accurate, I believe its not anymore since we've disabled CSP headers but lets just make sure the issue is gone and lets close

**Comment by jrouzierinverse** [comment]
The CSP headers are disabled for the admin right now let me check in maintenance.
