### ISSUE TITLE
SSO: WatchGuard should be centralized (maybe all SSO)

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2932]
Since the WatchGuard module only supports a single SSO RADIUS client, the management IP must be used.

But, when using a cluster, if another member sends the SSO using the VIP and doesn't have it, then the SSO is lost in no man's land.

We should consider centralizing the SSO to the management node

**Comment by extrafu** [comment]
@julsemaan Might be good to do a quick guide like one of these for WatchGuard: https://github.com/inverse-inc/packetfence/tree/v8-documentation-rework/docs/firewall

**Comment by julsemaan** [comment]
We don't have access to a WatchGuard unfortunately, even the user of the module who initially requested it isn't using it anymore but uses that same module with another product.

When @jrouzierinverse did the code, he found a document (its in #1851). We could always "steal" that doc to create our guide but we won't be able to confirm it works.
