### ISSUE TITLE
EAP-TLS source isn't considered as internal source

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2938]
That means that when we compute the sources for autoreg, it will never be considered since it doesn't have the realm attribute.

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/commit/75bb9ad6eedd5fd7d9b6b6e79ffd2e1008d9391c#diff-3f630266319ebf870a2a9fbd50e184d7

**Comment by julsemaan** [comment]
Doesn't seem to be in the maintenance though but I could be wrong

**Comment by julsemaan** [comment]
At least, didn't see it available this morning

**Comment by julsemaan** [comment]
Its in maintenance 7.4 and 7.3 now
