### ISSUE TITLE
pfdns: Looks like there is any issue when node doesn't exist

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2941]
So using pfdns, I tried to test it locally (on the server itself) to see if passthroughs would work.

Doing that caused pfdns to die:
```
Feb 09 14:22:17 pf-julien.inverse pfdns[32381]: ERROR pfdns database query returned sql: no rows in result set
```

To replicate:
```
# nslookup android.clients.google.com 172.21.156.1
```

Where 172.21.156.1 is the IP address of a registration interface

**Comment by satkunas** [comment]
@julsemaan I'm unable to reproduce fully.

I see the following entries in logs/pfdns.log, but it doesn't die on me.

```Apr 16 10:58:18 packetfence pfdns: ERROR pfdns database query returned sql: no rows in result set
Apr 16 10:58:18 packetfence pfdns: ERROR pfdns database query returned sql: no rows in result set
Apr 16 10:58:18 packetfence pfdns: Returned portal for MAC  with IP 192.168.56.102
Apr 16 10:58:18 packetfence pfdns: 192.168.56.102 - [16/Apr/2018:10:58:18 -0400] "A IN android.clients.google.com. udp 44 false 512" NOERROR qr,aa,rd 60 13.702456ms
```

**Comment by julsemaan** [comment]
Must have been addressed without the commit pointing to this then

**Comment by julsemaan** [comment]
Was able to replicate the issue by performing an nslookup against the management IP address using a passthrough:
```
nslookup vidange.com 172.20.155.47
```

Where vidange.com is a valid passthrough and 172.20.155.47 is the management IP address of the server

**Comment by julsemaan** [comment]
Now fixed with the latest devel
