### ISSUE TITLE
Fingerbank v8 pending items

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2946]
Following the merge of #2844, these are the elements that require attention prior to the release:

- [x] Have the endpoint PATCH validate if a modification was done to the endpoint instead of always calling the update hooks
- [x] Decide on what to do with the current device_type and device_class data in the DB (destroy it, attempt to migrate it, etc)
- [x] Before v8 release, sync fingerbank.inverse.ca accounts created after V2 launch on api.fingerbank.org
-- Script is done, migrated users up to April 18th, needs to be done on the day of the release
- [x] Handle re-sending sync packets in the collector (for which we got no ACK)
- [x] Consider not restoring the IP database of the collector if its older than X time
- [x] Forget the attributes of an endpoint when detecting a change in the DHCP vendor
- [x] Add support to synchronize the deletion of an endpoint (needed for point above)
- [x] Analyse what happens when the API is unavailable (status quo with previous data should be kept)
- [x] Perform tests with the collector having tens of thousands of endpoints and observe its behavior (persistence, sync latency, etc)
- [x] As @julsemaan feared, the gob encoder for each endpoint becomes a large memory consumer so we need to pool the gob encoders/decoders for the endpoints
- [x] Optimize the JSON decoding after loading the endpoints from a file or from a sync
- [x] Have the lock on an endpoint data expire after a few seconds to prevent deadlocks
- [x] Have the collector listen on 767 when used with PacketFence
- [x] Have the package update delete everything from the fingerbank cache
- [x] Have the packetfence collector use a specific user agent in the event we want to perform filtering on it on the server
- [x] ~~Potentially populate the collector from the data that is stored in the PacketFence database~~

**Comment by extrafu** [comment]
I think it's time to wrap this up!

**Comment by julsemaan** [comment]
Created the following issue for the last remaining point:
https://git.inverse.ca/inverse/fingerbank-collector/issues/20

**Comment by julsemaan** [comment]
Will perform the final user base sync in the next hours

**Comment by julsemaan** [comment]
All done, closing
