### ISSUE TITLE
http.admin: Tenant id error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2947]
Feb 13 09:56:09 testing-c7 httpd_admin[12039]: httpd.admin(12039) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'tenant_id' cannot be null (errno: 1048) [INSERT INTO `radius_nas` ( `tenant_id`, `nasname`, `shortname`, `secret`, `description`, `config_timestamp`, `start_ip`, `end_ip`, `range_length` ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `config_timestamp` = VALUES( config_timestamp ), `description` = VALUES( description ), `end_ip` = VALUES( end_ip ), `nasname` = VALUES( nasname ), `range_length` = VALUES( range_length ), `secret` = VALUES( secret ), `shortname` = VALUES( shortname ), `start_ip` = VALUES( start_ip ), `tenant_id` = VALUES( tenant_id )]{NULL, 172.20.145.93, 172.20.145.93, NjgyMWU5NWIzMDFlMDlkNjM2NzU0NDE2, 172.20.145.93 (PacketFence), 1518533769741870, 2887029085, 2887029085, 1} (pf::dal::db_execute)

**Comment by lzammit** [comment]
Fresh devel PF:

[root@testing-c7 pf]# rpm -qa packetfence
packetfence-7.4.9-0.201802080001.el7.noarch

**Comment by jrouzierinverse** [comment]
What were you doing when this error happened?

**Comment by lzammit** [comment]
Openning the web admin, I just did:

journalctl -fx

**Comment by jrouzierinverse** [comment]
This has been fixed

**Comment by extrafu** [comment]
@julsemaan Should be closed?

**Comment by julsemaan** [comment]
I guess we can close if @jrouzierinverse said its fixed and reopen if necessary
