### ISSUE TITLE
Pfqueue with inline mode

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2949]
After successfully registering with my laptop I got that in the logs:

Feb 13 16:34:10 testing-c7 pfqueue: pfqueue(27506) INFO: [mac:78:4f:43:33:45:f6] Removing parking actions for 94:db:c9:38:8f:0b - 172.21.146.10 (pf::parking::remove_parking_actions)
Feb 13 16:34:10 testing-c7 pfqueue: pfqueue(27506) ERROR: [mac:78:4f:43:33:45:f6] malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "\x{15}\x{3}\x{1}\x{0}...") at /usr/local/pf/lib/pf/api/jsonrestclient.pm line 144.
 (pf::api::can_fork::notify)
Feb 13 16:34:10 testing-c7 pfdhcp: 2018/02/13 16:34:10 http: TLS handshake error from [::1]:36976: tls: first record does not look like a TLS handshake
Feb 13 16:34:24 testing-c7 pfdhcp: 2018/02/13 16:34:24 http: TLS handshake error from [::1]:37110: tls: first record does not look like a TLS handshake
Feb 13 16:34:24 testing-c7 pfqueue: pfqueue(27506) INFO: [mac:78:4f:43:33:45:f6] Removing parking actions for 94:db:c9:38:8f:0b - 172.21.146.10 (pf::parking::remove_parking_actions)
Feb 13 16:34:24 testing-c7 pfqueue: pfqueue(27506) ERROR: [mac:78:4f:43:33:45:f6] malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "\x{15}\x{3}\x{1}\x{0}...") at /usr/local/pf/lib/pf/api/jsonrestclient.pm line 144.
 (pf::api::can_fork::notify)
Feb 13 16:34:39 testing-c7 pfqueue: pfqueue(27506) INFO: [mac:78:4f:43:33:45:f6] Removing parking actions for 94:db:c9:38:8f:0b - 172.21.146.10 (pf::parking::remove_parking_actions)
Feb 13 16:34:39 testing-c7 pfqueue: pfqueue(27506) ERROR: [mac:78:4f:43:33:45:f6] malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "\x{15}\x{3}\x{1}\x{0}...") at /usr/local/pf/lib/pf/api/jsonrestclient.pm line 144.
 (pf::api::can_fork::notify)
Feb 13 16:34:39 testing-c7 pfdhcp: 2018/02/13 16:34:39 http: TLS handshake error from [::1]:37254: tls: first record does not look like a TLS handshake
Feb 13 16:34:52 testing-c7 pfqueue: pfqueue(27512) INFO: [mac:78:4f:43:33:45:f6] Removing parking actions for 94:db:c9:38:8f:0b - 172.21.146.10 (pf::parking::remove_parking_actions)
Feb 13 16:34:52 testing-c7 pfdhcp: 2018/02/13 16:34:52 http: TLS handshake error from [::1]:37362: tls: first record does not look like a TLS handshake
Feb 13 16:34:52 testing-c7 pfqueue: pfqueue(27512) ERROR: [mac:78:4f:43:33:45:f6] malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "\x{15}\x{3}\x{1}\x{0}...") at /usr/local/pf/lib/pf/api/jsonrestclient.pm line 144.
 (pf::api::can_fork::notify)

**Comment by julsemaan** [comment]
That will be fixed when #2784 is merged

**Comment by julsemaan** [comment]
#2784 was merged
