### ISSUE TITLE
provisioner unit tests are broken by fingerbank

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#2954]
It seems that 
* unittest/provisioner/mobileconfig.t
* unittest/provisioner.t
Are broken by the fingerbank integration

**Comment by jrouzierinverse** [comment]
I upgraded my fingerbank package so I am not sure what else may be needed.

**Comment by julsemaan** [comment]
Hum that is weird, I had them passing on my machine before asking for the merge of the branch.

I'll replicate it and update the Fingerbank package if necessary today

**Comment by julsemaan** [comment]
My bad actually, I was using the previous DB with the old device names so that is why it was passing on my machine.

Adjusted the device names in 1a2c82401d75d9c8d1f6651d12f4c7995d0e3774 and the 2 unit tests should be passing.

I'll get a build going and re-open if that still fails there
