### ISSUE TITLE
Web Admin: Violations Select doesn't display all the actions if the name is too long

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#2962]
![violation action choices](https://user-images.githubusercontent.com/36165527/36429077-a53203ba-161f-11e8-9722-da43b7f1ffc6.png)

In violations.conf:
```
[1100007]
trigger=device::1
actions=autoreg,reevaluate_access,log
enabled=Y
window=
access_duration=12h
```

**Comment by julsemaan** [comment]
seems related to #3053

**Comment by extrafu** [comment]
Should @cgx look into this instead?

**Comment by julsemaan** [comment]
If he has time for it, sure
