### ISSUE TITLE
Meraki Switches: Support for VoIP seems to be there now

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2977]
The Meraki switches now seem to have support for VoIP in a similar way to the Cisco Catalyst series.

So using the Catalyst 2960 module, we can perform VoIP on these.

Only thing is the LLDP/CDP detection isn't currently working.

We should see if the information is exposed by the Meraki switches via SNMP and use it if possible

**Comment by extrafu** [comment]
@julsemaan Haven't we added that recently? I recall customer deployments involving Meraki + VoIP.
