### ISSUE TITLE
Monitoring of the redis queues via monit

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2981]
We should check if we could monitor the redis queues for any backlogging via monit or via our monitoring scripts

**Comment by julsemaan** [comment]
This could be added into pfstats, I'll add @satkunas with me on that issue to see if that could be collected via that

**Comment by extrafu** [comment]
@satkunas Please add this to the stats to produce.

**Comment by julsemaan** [comment]
@satkunas 

I don't see this in #3113 

Is work for this underway ?

**Comment by satkunas** [comment]
@julsemaan no it's not. I'll need to schedule a quick conversation with you to clarify this.

**Comment by julsemaan** [comment]
Sure, let me know when

**Comment by julsemaan** [comment]
Moving to 8.1
