### ISSUE TITLE
packetfence-netdata fails to start through pf service scripts

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#2985]
**`netdata` fails to start through service scripts**
  * /usr/local/pf/# `bin/pfcmd service netdata start|restart`

> Mar  3 04:44:13 packetfence packetfence: ERROR pfcmd.pl(13663): pf::services::manager::netdata=HASH(0xad005b0)->name died or has failed to start (pf::services::manager::postStartCleanup)
 
**`netdata` starts manually, but produces several errors**
 *  /usr/local/pf# `/usr/sbin/netdata -P /run/netdata/netdata.pid -D -c /usr/local/pf/var/conf/monitoring/netdata.conf`

> 2018-03-03 04:39:06: netdata ERROR: Failed to open pidfile '/run/netdata/netdata.pid'. (errno 2, No such file or directory)
> 2018-03-03 04:39:06: netdata ERROR: Cannot chown '/run/netdata/netdata.pid' to 988:986 (errno 2, No such file or directory)
> 2018-03-03 04:39:06: netdata ERROR: HEALTH [packetfence]: cannot open health file: /var/lib/netdata/health/health-log.db.old (errno 2, No such file or directory)
> 2018-03-03 04:39:06: netdata ERROR: Health configuration cannot open directory '/usr/local/pf/var/conf/monitoring/health.d'. (errno 13, Permission denied)
> 2018-03-03 04:39:06: netdata ERROR: STATSD configuration cannot open directory '/usr/local/pf/var/conf/monitoring/statsd.d'. (errno 13, Permission denied)
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: Cannot open plugins directory '/etc/netdata/custom-plugins.d'. (errno 2, No such file or directory)
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/fping.plugin' disconnected.
> 2018-03-03 04:39:06: netdata ERROR: child pid 13313 exited with code 1. (errno 9, Bad file descriptor)
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/fping.plugin' exited with error code 1. Disabling it.
> 2018-03-03 04:39:06: python.d ERROR: plugin: main: [Errno 13] Permission denied: '/usr/local/pf/var/conf/monitoring/python.d.conf'
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/python.d.plugin : read failed.
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/python.d.plugin' disconnected.
> 2018-03-03 04:39:06: netdata ERROR: child pid 13311 exited with code 1. (errno 9, Bad file descriptor)
> 2018-03-03 04:39:06: netdata ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' exited with error code 1. Disabling it.
> 2018-03-03 04:39:06: node.d.plugin: ERROR: Cannot read configuration file /usr/local/pf/var/conf/monitoring/node.d.conf: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d.conf', using internal defaults.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: Cannot load module's stiebeleltron config from /usr/local/pf/var/conf/monitoring/node.d/stiebeleltron.conf exception: Error: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d/stiebeleltron.conf', using internal defaults.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: Cannot load module's snmp config from /usr/local/pf/var/conf/monitoring/node.d/snmp.conf exception: Error: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d/snmp.conf', using internal defaults.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: Cannot load module's sma_webbox config from /usr/local/pf/var/conf/monitoring/node.d/sma_webbox.conf exception: Error: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d/sma_webbox.conf', using internal defaults.
> 2018-03-03 04:39:07: charts.d: WARNING: ap: configuration file '/usr/local/pf/var/conf/monitoring/charts.d/ap.conf' not found. Using defaults.
> 2018-03-03 04:39:07: charts.d: WARNING: ap: command 'iw' is not found in /root/gospace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: Cannot load module's named config from /usr/local/pf/var/conf/monitoring/node.d/named.conf exception: Error: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d/named.conf', using internal defaults.
> 2018-03-03 04:39:07: charts.d: ERROR: ap: module's 'ap' check() function reports failure.
> 2018-03-03 04:39:07: charts.d: WARNING: apcupsd: configuration file '/usr/local/pf/var/conf/monitoring/charts.d/apcupsd.conf' not found. Using defaults.
> 2018-03-03 04:39:07: charts.d: WARNING: apcupsd: command 'apcaccess' is not found in /root/gospace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
> 2018-03-03 04:39:07: charts.d: ERROR: apcupsd: module's 'apcupsd' check() function reports failure.
> 2018-03-03 04:39:07: charts.d: WARNING: nut: configuration file '/usr/local/pf/var/conf/monitoring/charts.d/nut.conf' not found. Using defaults.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: Cannot load module's fronius config from /usr/local/pf/var/conf/monitoring/node.d/fronius.conf exception: Error: EACCES: permission denied, open '/usr/local/pf/var/conf/monitoring/node.d/fronius.conf', using internal defaults.
> 2018-03-03 04:39:07: charts.d: WARNING: nut: command 'upsc' is not found in /root/gospace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
> 2018-03-03 04:39:07: charts.d: ERROR: nut: module's 'nut' check() function reports failure.
> 2018-03-03 04:39:07: charts.d: WARNING: opensips: configuration file '/usr/local/pf/var/conf/monitoring/charts.d/opensips.conf' not found. Using defaults.
> 2018-03-03 04:39:07: node.d.plugin: ERROR: named: local: Got HTTP code 302, failed to get data.
> 2018-03-03 04:39:07: charts.d: WARNING: opensips: command 'opensipsctl' is not found in /root/gospace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
> 2018-03-03 04:39:07: charts.d: ERROR: opensips: module's 'opensips' check() function reports failure.
> 2018-03-03 04:39:07: netdata ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/charts.d.plugin' disconnected.
> 2018-03-03 04:39:07: netdata ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 13305) does not generate useful output but it reports success (exits with 0). Will not start it again - it is disabled.. (errno 9, Bad file descriptor)
> 2018-03-03 04:39:07: netdata ERROR: Cannot read ECC memory errors directory '/sys/devices/system/edac/mc' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfsd' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfs' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PROCFILE: Cannot open file '/proc/spl/kstat/zfs/arcstats' (errno 2, No such file or directory)
> 2018-03-03 04:39:07: netdata ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/node.d.plugin' disconnected.
> 2018-03-03 04:39:07: netdata ERROR: child pid 13310 killed by signal 15. (errno 9, Bad file descriptor)
> 2018-03-03 04:39:07: netdata ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' exited with error code -1. Disabling it.`

**Comment by fdurand** [comment]
Probably because you didn't installed devel with the packages.
Can you di that: https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L621

**Comment by satkunas** [comment]
@fdurand this worked.

Is there a reason why it didn't `usermod` when I ran `sh addons/dev-helpers/centos-chroot/install-packages-from-spec.sh` ?

**Comment by fdurand** [comment]
No idea , ask @jrouzierinverse  for that.

**Comment by julsemaan** [comment]
Running the sources usually means doing any packaging job manually or to upgrade the environment using yum and then resetting the changes done in /usr/local/pf using git.

Since all the logic is in the spec and not the Makefile, then that means currently these changes can only be done by a package manager (yum, apt-get).

**Comment by extrafu** [comment]
Should be fixed by now since the spec file was changed. See https://github.com/inverse-inc/packetfence/commit/f1f4def1394376802166d492ecc7a90c7293e1f1#diff-6e30adfa26e7298beca9691931007918
