### ISSUE TITLE
Could not render admin templates

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#2986]
Error seen at top of **any** page: 
> Couldn't render template "admin/status.tt: file error - admin/status.tt: not found"

File perms:
> [root@packetfence pf]# find . | grep "admin/status.tt"
> ./html/pfappserver/root/admin/status.tt
> [root@packetfence pf]# ls -laZ html/pfappserver/root/admin/status.tt 
> -rw-r--r-- pf pf ?                                html/pfappserver/root/admin/status.tt

Output seen in logs when restarting the service:
> Mar  3 05:33:12 packetfence httpd_admin_err: [Sat Mar 03 05:33:12.225327 2018] [mpm_prefork:notice] [pid 16196] AH00170: caught SIGWINCH, shutting down gracefully
> Mar  3 05:33:27 packetfence httpd_admin_err: [Sat Mar 03 05:33:27.933412 2018] [ssl:warn] [pid 20444] AH01909: RSA certificate configured for packetfence.satkunas.com:443 does NOT include an ID which matches the server name
> Mar  3 05:33:39 packetfence httpd_admin_err: [Sat Mar  3 05:33:39 2018] pfappserver.pm: Cannot determine desired terminal width, using default of 80 columns
> Mar  3 05:33:40 packetfence httpd_admin_err: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::a00:27ff:fed5:be68. Set the 'ServerName' directive globally to suppress this message
> Mar  3 05:33:40 packetfence httpd_admin_err: [Sat Mar 03 05:33:40.626921 2018] [ssl:warn] [pid 20444] AH01909: RSA certificate configured for packetfence.satkunas.com:443 does NOT include an ID which matches the server name
> Mar  3 05:33:40 packetfence httpd_admin_err: [Sat Mar 03 05:33:40.729612 2018] [mpm_prefork:notice] [pid 20444] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.16.3 configured -- resuming normal operations
> Mar  3 05:33:40 packetfence httpd_admin_err: [Sat Mar 03 05:33:40.729724 2018] [core:notice] [pid 20444] AH00094: Command line: '/usr/sbin/httpd -f /usr/local/pf/var/conf/httpd.conf.d/httpd.admin -D FOREGROUND -D rhel'

**Comment by fdurand** [comment]
It's normal, admin/status.tt was for graphite but it has been removed,
@lzammit @cgx and me have to work on it.

**Comment by satkunas** [comment]
@fdurand is `httpd.admin` now broken? Or is there an alternative way to access it?

**Comment by cgx** [comment]
Only the status/dashboard is broken.

**Comment by extrafu** [comment]
I think @julsemaan just fixed it - correct?

**Comment by julsemaan** [comment]
Correct, didn't notice this was the same issue as #2989 

So this is fixed
