### ISSUE TITLE
pfstats service script listed but not available

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#2987]
**pfstats** service script iis listed but not available from bin/pfcmd

`# bin/pfcmd service pfstats status`
> Usage:
>     pfcmd service <service>
>     [start|stop|restart|status|generateconfig|updatesystemd]
>     [--ignore-checkup]
> 
>       stop/stop/restart specified service
>       status returns PID of specified PF daemon or 0 if not running.
> 
>       --ignore-checkup will start the requested services even if the checkup fails
> 
>     Services managed by PacketFence:
> 
>       haproxy          | haproxy daemon
>       httpd.aaa        | Apache AAA webservice
>       httpd.admin      | Apache Web admin
>       httpd.collector  | Apache Collector daemon
>       httpd.dispatcher | Captive portal dispatcher
>       httpd.parking    | Apache Parking Portal
>       httpd.portal     | Apache Captive Portal
>       httpd.proxy      | Apache Proxy Interception
>       httpd.webservices| Apache Webservices
>       iptables         | PacketFence firewall rules
>       keepalived       | Virtual IP management
>       netdata          | Monitoring service
>       pf               | all services that should be running based on your config
>       pfbandwidthd     | A pf service to monitor bandwidth usages
>       pfdetect         | PF snort alert parser
>       pfdhcp           | dhcpd daemon
>       pfdhcplistener   | PF DHCP monitoring daemon
>       pfdns            | DNS daemon
>       pfipset          | IPSET daemon
>       pffilter         | PF conditions filtering daemon
>       pfmon            | PF monitoring daemon
>       pfqueue          | PF queueing service
>       pfsetvlan        | PF VLAN isolation daemon
>       pfstats          | PF statistics daemon
>       radiusd          | FreeRADIUS daemon
>       radsniff         | radsniff daemon
>       redis_ntlm_cache | Redis for the NTLM cache
>       redis_queue      | Redis for pfqueue
>       routes           | manage static routes
>       snmptrapd        | SNMP trap receiver daemon
>       winbindd         | Winbind daemon

**Comment by fdurand** [comment]
Fixed by https://github.com/inverse-inc/packetfence/commit/f1fb0e29d22f582409f2a010b98ca14391cf83d5

**Comment by satkunas** [comment]
@fdurand this worked. Thanks!
