### ISSUE TITLE
pfstats pointer and connection errors seen in logs

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#2988]
* `pfstats` daemon frequently seg faults and restarts constantly.

> Mar  3 05:42:15 packetfence pfstats: panic: runtime error: invalid memory address or nil pointer dereference
> Mar  3 05:42:15 packetfence pfstats: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x61f597]
> Mar  3 05:42:15 packetfence pfstats: goroutine 34 [running]:
> Mar  3 05:42:15 packetfence pfstats: github.com/inverse-inc/packetfence/go/log.LoggerWContext(0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200a4140, 0xc42020f93b)
> Mar  3 05:42:15 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/log/log.go:128 +0x37
> Mar  3 05:42:15 packetfence pfstats: main.gauge.Send(0xc42020f900, 0x43, 0x696b00, 0x8fb040)
> Mar  3 05:42:15 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:53 +0x103
> Mar  3 05:42:15 packetfence pfstats: main.forward(0x79d0e0, 0xc42024a000)
> Mar  3 05:42:15 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:218 +0x5c2
> Mar  3 05:42:15 packetfence pfstats: created by main.main
> Mar  3 05:42:15 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:356 +0x789
> Mar  3 05:42:15 packetfence /usr/local/pf/bin/pfstats[21267]: t=2018-03-03T05:42:15-0500 lvl=eror msg="write udp 127.0.0.1:51946->127.0.0.1:8125: write: connection refused" pid=21267
> Mar  3 05:42:15 packetfence /usr/local/pf/bin/pfstats[21267]: t=2018-03-03T05:42:15-0500 lvl=info msg="Starting stats server" pid=21267

* Rebuilding w/ go produces no errors during compile

`[root@packetfence go]# make pfstats`
> cd stats && \
>         go build && \
>         cd - && \
>         mv stats/stats pfstats
> /root/gospace/src/github.com/inverse-inc/packetfence/go

`[root@packetfence go]# mv pfstats /usr/local/pf/bin/`
> mv: overwrite ‘/usr/local/pf/bin/pfstats’? y

`[root@packetfence go]# service packetfence-pfstats restart`
> Redirecting to /bin/systemctl restart packetfence-pfstats.service

`[root@packetfence go]# service packetfence-pfstats status`
> Redirecting to /bin/systemctl status packetfence-pfstats.service
> ● packetfence-pfstats.service - PacketFence Stats daemon
>    Loaded: loaded (/usr/lib/systemd/system/packetfence-pfstats.service; disabled; vendor preset: disabled)
>    Active: active (running) since Sat 2018-03-03 05:46:02 EST; 4s ago
>   Process: 21667 ExecStartPre=/bin/rm -fr /usr/local/pf/var/run/collectd-unixsock (code=exited, status=0/SUCCESS)
>  Main PID: 21669 (pfstats)
>    CGroup: /packetfence.slice/packetfence-pfstats.service
>            └─21669 /usr/local/pf/bin/pfstats
> 
> Mar 03 05:46:03 packetfence pfstats[21628]: main.forward(0x0, 0x0)
> Mar 03 05:46:03 packetfence pfstats[21628]: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:199 +0x78
> Mar 03 05:46:03 packetfence pfstats[21628]: created by main.main
> Mar 03 05:46:03 packetfence pfstats[21628]: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:356 +0x789
> Mar 03 05:46:02 packetfence systemd[1]: Unit packetfence-pfstats.service entered failed state.
> Mar 03 05:46:02 packetfence systemd[1]: packetfence-pfstats.service failed.
> Mar 03 05:46:02 packetfence systemd[1]: Starting PacketFence Stats daemon...
> Mar 03 05:46:02 packetfence systemd[1]: Started PacketFence Stats daemon.
> Mar 03 05:46:02 packetfence /usr/local/pf/bin/pfstats[21669]: t=2018-03-03T05:46:02-0500 lvl=eror msg="write udp 127.0.0.1:40767->127.0.0.1:8125: write: connection refused" pid=21669
> Mar 03 05:46:02 packetfence /usr/local/pf/bin/pfstats[21669]: t=2018-03-03T05:46:02-0500 lvl=info msg="Starting stats server" pid=21669

**Comment by fdurand** [comment]
Do you have the issue when netdata is running ?

**Comment by satkunas** [comment]
@fdurand I'm still seeing the following in the logs even with netdata running (this is during a `service restart`):

> Mar  3 14:10:13 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=info msg="Caught signal terminated: shutting down." pid=27625
> Mar  3 14:10:13 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:13 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:13 packetfence pfstats: panic: runtime error: invalid memory address or nil pointer dereference
> Mar  3 14:10:13 packetfence pfstats: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x64b7f8]
> Mar  3 14:10:13 packetfence pfstats: goroutine 73 [running]:
> Mar  3 14:10:13 packetfence pfstats: main.forward(0x0, 0x0)
> Mar  3 14:10:13 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:199 +0x78
> Mar  3 14:10:13 packetfence pfstats: created by main.main
> Mar  3 14:10:13 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:356 +0x789
> Mar  3 14:10:13 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:13 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:14 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:15 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:16 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:17 packetfence /usr/local/pf/bin/pfstats[27625]: t=2018-03-03T14:10:13-0500 lvl=crit msg="Accept error: accept unix /usr/local/pf/var/run/collectd-unixsock: use of closed network connection" pid=27625
> Mar  3 14:10:22 packetfence /usr/local/pf/bin/pfstats[27741]: t=2018-03-03T14:10:22-0500 lvl=info msg="Starting stats server" pid=27741

**Comment by jrouzierinverse** [comment]
Is this still can issue?

**Comment by julsemaan** [comment]
@satkunas 

Can we close this ?

**Comment by extrafu** [comment]
@satkunas Please close the issue if no longer relevant.
