### ISSUE TITLE
Mobile Iron provisionner error in packetfence.log

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#2991]
Found in packetfence.log, with Mobile Iron provisionner:
`Feb 22 15:41:46 pf1 packetfence_httpd.webservices: httpd.webservices(2383) ERROR: [mac:ac:37:43:4a:7a:44] Database query failed with non retryable error: Cannot add or update a child row: a foreign key constraint fails (`pf`.`violation`, CONSTRAINT `0_61` FOREIGN KEY (`vid`) REFERENCES `class` (`vid`) ON DELETE CASCADE ON UPDATE CASCADE) (errno: 1452) [INSERT INTO `violation` ( `mac`, `notes`, `release_date`, `start_date`, `status`, `ticket_ref`, `vid`) VALUES ( ?, ?, ?, ?, ?, ?, ? )]{, NULL, 0, , open, NULL, 112} (pf::dal::db_execute)`

-----------

**Comment by jrouzierinverse** [comment]
This should be fixed by 645a7fece9b4e5a7ec639496b3596bcba06e3fb3.
I push a fixed in maintenance
