### ISSUE TITLE
Updating max nodes per user for role doesnt update the DB

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#2997]
On packetfence 7.4, updating the max nodes per user for a role updates the roles.conf file but the node_category table is not updated. This seems to occur for existing nodes. Creating a new node writes the correct value to the DB but not on update.

The problem occurs regardless of changing the setting through the GUI or editing the roles.conf file directly and calling the pfcmd command to reload the config. 

Its extremely simple to reproduce. Just modify the max number of nodes for a role.

**Comment by julsemaan** [comment]
Could you provide the output of httpd.admin.log while you're performing this change so we can pinpoint the error.

Thanks!

**Comment by garci66** [comment]
See here for the log:

`
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Hard expiring resource : config::Roles (pfconfig::manager::expire)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Connecting to MySQL database (pfconfig::backend::mysql::_get_db)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] OK (pf::ConfigStore::commit)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] commiting via Roles configstore (pf::ConfigStore::Roles::commit)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID REJECT (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID alumnos (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID it-staff (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID default (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID equiposnewman (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID voice (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID invitados (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID gaming (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID profesores (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID personal (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Inserting/updating role with ID guest (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) ERROR: [mac:unknown] Cannot save nodecategory (role) in the database. (pf::nodecategory::nodecategory_upsert)
Mar 13 10:42:32 wifi httpd_admin: httpd.admin(2239) INFO: [mac:unknown] Changes successfully commited in the configuration (pfappserver::Base::Controller::Crud::Config::_commitChanges)
^C
`

The DB remains unchanged. Let me know if there is anything else I can provide.
