### ISSUE TITLE
RADIUS_Audit_log: Audit tab does not show entries properly

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3000]
In devel, the Auditing tab only shows one entry:
![image](https://user-images.githubusercontent.com/36165527/37232757-5426d9f8-23be-11e8-98a7-5b89f4ed13d2.png)

There should be more since I was doing tests.

**Comment by julsemaan** [comment]
This could be caused by the fact that entries aren't always assigned a tenant ID.

On my testing environment, I have a bunch of entries that have the tenant ID 0 and they aren't displayed in that view

**Comment by jrouzierinverse** [comment]
As @julsemaan explained this is expected behavior.
We should close this issue as it would be addressed in the newer admin.

**Comment by extrafu** [comment]
@julsemaan Should be closed?

**Comment by julsemaan** [comment]
yep
