### ISSUE TITLE
Admin: Batch clearing node violation is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3010]
When clearing the violations on nodes, it doesn't work

To replicate:
- Open admin and go in nodes tab
- Open a violation on a node
- Then "check" the box to select the node
- Execute the action "Clear violation"
- Comtemplate error in log:
```
Mar 14 11:23:36 httpd.admin(16024) ERROR: Database query failed with non retryable error: Unknown column 'c.description' in 'field list' (errno: 1054) [SELECT `id`, `start_date`, `c`.`description`, `violation`.`vid`, `status` FROM violation INNER JOIN class ON ( `violation`.`vid` = `class`.`vid` ) WHERE ( ( `mac` = ? AND `status` = ? AND `violation`.`tenant_id` = ? ) ) ORDER BY `start_date` DESC]{94:db:c9:38:85:5b, open, 1} (pf::dal::db_execute)
```
- And violation isn't closed

**Comment by jrouzierinverse** [comment]
Fixed by 8dd96318cfcc510e0dc88f1c1db03a0ff5f87d0b and pushed in maintenance/7.4
