### ISSUE TITLE
Web admin Audit log: No radius request login with EAP-TLS

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3011]
![screen shot 2018-03-15 at 8 26 25 am](https://user-images.githubusercontent.com/5261214/37463102-95394528-282a-11e8-80d9-98b5c810a6dd.png)

**Comment by jrouzierinverse** [comment]
This has been fixed in devel please verify

**Comment by julsemaan** [comment]
Can you point to the commit ?

I didn't see anything related to the EAP-TLS. I recall something around the 802.1x RADIUS audit log entries not being recorded at all because they used tenant ID 0, but nothing around data missing inside the entry

**Comment by jrouzierinverse** [comment]
Sorry you are right.

**Comment by jrouzierinverse** [comment]
It looks like the request is not being copied in the tunnel.

https://github.com/inverse-inc/packetfence/blob/devel/conf/radiusd/eap.conf.example#L918

The question is do we copy request to the tunnel.

copy_request_to_tunnel = yes

**Comment by julsemaan** [comment]
I don't believe there is an inner tunnel in EAP-TLS although I may be wrong.

Were you able to replicate the problem and fix it with that change ?

**Comment by extrafu** [comment]
EAP-TLS is definitively not tunneled - EAP-{PEAP,TTLS,FAST} are.

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
@lzammit says it works
