### ISSUE TITLE
pfstats runtime error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3017]
Details:
* Using most recent `devel` branch.
* Error occurs regardless of the contents of `conf/stats.conf`, or whether there's a `file=...` directive in the configuration file, or not.
* `bin/pfcmd pfconfig show config::Stats` successfully displays the contents of `conf/stats.conf`
* `bin/pfcmd pfconfig reload` has no effect.

The error appears to be coming from:

https://github.com/inverse-inc/packetfence/blob/642c0598b14d282378ec29018e8a54924b2d94a4/go/stats/main.go#L345

Tail from `logs/pfstats.log`, seen immediately after (re)starting pfstats:

> Mar 17 10:36:00 packetfence pfstats: panic: runtime error: invalid memory address or nil pointer dereference
> Mar 17 10:36:00 packetfence pfstats: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x575657]
> Mar 17 10:36:00 packetfence pfstats: goroutine 34 [running]:
> Mar 17 10:36:00 packetfence pfstats: github.com/inverse-inc/packetfence/go/log.LoggerWContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> Mar 17 10:36:00 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/log/log.go:128 +0x37
> Mar 17 10:36:00 packetfence pfstats: main.tailFile(0xbea367d421eb625d, 0x6c81d0, 0x9254e0, 0x0, 0x0, 0xc4200ad490, 0x9, 0x0, 0x0, 0x0, ...)
> Mar 17 10:36:00 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:407 +0x4e
> Mar 17 10:36:00 packetfence pfstats: created by main.main
> Mar 17 10:36:00 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:388 +0x628

**Comment by satkunas** [comment]
@julsemaan @jrouzierinverse I've worked out the issue. I'll post an update to fix this in a future PR.

**Comment by jrouzierinverse** [comment]
Can this be closed?

**Comment by satkunas** [comment]
@jrouzierinverse yes, closing...
