### ISSUE TITLE
Portal preview: Issue with redirect at the end

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3020]
The redirect to /access at the end of the portal preview redirects to the http protocol and omits the `portal_preview` prefix, resulting in this:
![image](https://user-images.githubusercontent.com/3857942/37567697-f8ed871e-2aa0-11e8-85bd-47f746a86e9f.png)

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
Working on it
