### ISSUE TITLE
pfconfigdriver fails when key includes double-quote(s)

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3021]
**WORKS** `conf/stats.conf`:
```
[metric 1]
type=mysql_query
statsd_type=gauge
statsd_ns=sample
mysql_query=select 1
interval=60s
```
```
[metric '1']
type=mysql_query
statsd_type=gauge
statsd_ns=sample
mysql_query=select 1
interval=60s
```

**FAILS** `conf/stats.conf`:
```
[metric "1"]
type=mysql_query
statsd_type=gauge
statsd_ns=sample
mysql_query=select 1
interval=60s
```

Error Log seen after restarting `pfstats` in `logs/pfstats.log`:

> Mar 18 14:28:18 packetfence pfstats: panic: invalid character '=' looking for beginning of value
> Mar 18 14:28:18 packetfence pfstats: goroutine 1 [running]:
> Mar 18 14:28:18 packetfence pfstats: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeJsonInterface(0x7c5e60, 0xc4202141b0, 0xc420250130, 0x7, 0x7, 0x6acaa0, 0xc420262020)
> Mar 18 14:28:18 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:174 +0x1c8
> Mar 18 14:28:18 packetfence pfstats: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeInterface(0x7c5e60, 0xc4202141b0, 0x7246ae, 0x4, 0xc420250130, 0x7, 0x7, 0x6acaa0, 0xc420262020)
> Mar 18 14:28:18 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:160 +0x9d
> Mar 18 14:28:18 packetfence pfstats: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocket(0x7c5e60, 0xc4202141b0, 0x7c4b00, 0xc4202680e0, 0x0, 0x0)
> Mar 18 14:28:18 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:251 +0x407
> Mar 18 14:28:18 packetfence pfstats: main.main()
> Mar 18 14:28:18 packetfence pfstats: /root/gospace/src/github.com/inverse-inc/packetfence/go/stats/main.go:343 +0x597

**Comment by jrouzierinverse** [comment]
Try this b2cfb2d09b4c95626d7433a4a8baaaf4afed1572

**Comment by jrouzierinverse** [comment]
Spoke to @julsemaan my commit did not work.

**Comment by julsemaan** [comment]
I iterated over @jrouzierinverse and that should be fixed now:
9d113870febf833ba06185fe4d1067c7f8e0b104

Note that my commit is built on top of @jrouzierinverse's commit so apply both patches or rebase against the latest devel

**Comment by julsemaan** [comment]
@satkunas 

Can we close this now ?
