### ISSUE TITLE
Auditing: Selecting last hour doesn't pick the right timezone

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3022]
The last hour of the auditing tab should have started using the timezone of the server but even if the server local time is set to CDT (America/Chicago), the timezone that is used for the 'last hour' is the Eastern timezone even though the user (browser) and server are both in America/Chicago

**Comment by jrouzierinverse** [comment]
It using the timezone in general.timezone please verify if that timezone is set to EST.

**Comment by julsemaan** [comment]
Ah yes, that would be it I think, let me try that

**Comment by jrouzierinverse** [comment]
In the configurator maybe we should set the timezone to the current timezone of the server when setting it up.

**Comment by julsemaan** [comment]
Yes that was my thought going through this, lets open a separate issue for that one

This is fixed now by the configuration
