### ISSUE TITLE
Configurator: Should set the timezone in the configurator

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3025]
Title says it all!

**Comment by jrouzierinverse** [comment]
It would be best if the the default is set to the current timezone of the server.

**Comment by julsemaan** [comment]
Then we could ship it empty in pf.conf.defaults and when its empty pfconfig could populate it from the timezone of the server

Sounds legit ?

**Comment by jrouzierinverse** [comment]
I was more thinking leave as EST but in the configurator display it as the current timezone of the server.
Both solutions solves the problem which ever approach you think is easiest to do as you assigned to yourself.

**Comment by julsemaan** [comment]
fixed it via f833c38568905535b83dd30eb62fcfb0f0ad9131

Took the approach of shipping an empty timezone in pf.conf.defaults, then pfconfig populates it with the local timezone when its empty.
