### ISSUE TITLE
DHCP option 82: Non ascii hostname is inserted in the DB

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3033]
Prior to 7.4, a non-ascii hostname would be inserted as blank in the database but now its inserted as funny characters (not as funny as me though).

We would need to validate that the hostname is ascii or at least strip non ascii characters from it

**Comment by julsemaan** [comment]
@jrouzierinverse 

I recall we discussed a fix around this, was it done ?

**Comment by jrouzierinverse** [comment]
Yes it was done
