### ISSUE TITLE
Cors config directive causing failed start w/ api-frontend

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3042]
https://github.com/inverse-inc/packetfence/blob/84db46df139dcc4ba200b20db0ce9fa692a79516/conf/caddy-services/api.conf.example#L15

Logs:

> Mar 26 12:31:36 packetfence systemd[1]: Starting PacketFence API frontend Service...
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Activating privacy features... done.
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configuration set log level: INFO
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configuration set log level: INFO
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configured statsd protocol: udp
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configured prefix: api
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configured statsd protocol: udp
> Mar 26 12:31:36 packetfence pfhttpd[24363]: Using configured prefix: api-proxy
> Mar 26 12:31:36 packetfence api-frontend[24363]: t=2018-03-26T12:31:36-0400 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=24363 PfconfigObject=hash_element|config::Pf;webservices
> Mar 26 12:31:36 packetfence api-frontend[24363]: t=2018-03-26T12:31:36-0400 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=24363 PfconfigObject=element|config::AdminRoles
> Mar 26 12:31:36 packetfence api-frontend[24363]: t=2018-03-26T12:31:36-0400 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=24363 PfconfigObject=hash_element|config::Pf;database
> Mar 26 12:31:36 packetfence pfhttpd[24363]: 2018/03/26 12:31:36 no action found for directive 'cors' with server type 'http' (missing a plugin?)
> Mar 26 12:31:36 packetfence systemd[1]: Started PacketFence API frontend Service.
> Mar 26 12:31:36 packetfence systemd[1]: packetfence-api-frontend.service: main process exited, code=exited, status=1/FAILURE
> Mar 26 12:31:36 packetfence systemd[1]: Unit packetfence-api-frontend.service entered failed state.
> Mar 26 12:31:36 packetfence systemd[1]: packetfence-api-frontend.service failed.
> Mar 26 12:31:37 packetfence systemd[1]: packetfence-api-frontend.service holdoff time over, scheduling restart.
> Mar 26 12:31:37 packetfence systemd[1]: start request repeated too quickly for packetfence-api-frontend.service
> Mar 26 12:31:37 packetfence systemd[1]: Failed to start PacketFence API frontend Service.
> Mar 26 12:31:37 packetfence systemd[1]: Unit packetfence-api-frontend.service entered failed state.
> Mar 26 12:31:37 packetfence systemd[1]: packetfence-api-frontend.service failed.

**Comment by satkunas** [comment]
Commenting out the following lines in `conf/caddy-services/api.conf` fixes the issue:

```
  #cors /api/v1 {
  #  allowed_headers Authorization,Content-Type
  #}
```

**Comment by julsemaan** [comment]
Can you try with the newest and greatest pfhttpd in place, it should be working fine

**Comment by julsemaan** [comment]
The newest code contains the cors module so that is fixed.

Otherwise, reopen it
