### ISSUE TITLE
Web Admin: Can not delete the default 192.168.1.0/24 switch

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3044]
When you try to delete the default switch:

Mar 26 16:53:51 testing-c7 httpd_admin: httpd.admin(2103) ERROR: [mac:unknown] Database query failed with non retryable error: Column 'tenant_id' cannot be null (errno: 1048) [INSERT INTO `radius_nas` ( `tenant_id`, `nasname`, `shortname`, `secret`, `description`, `config_timestamp`, `start_ip`, `end_ip`, `range_length` ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `config_timestamp` = VALUES( config_timestamp ), `description` = VALUES( description ), `end_ip` = VALUES( end_ip ), `nasname` = VALUES( nasname ), `range_length` = VALUES( range_length ), `secret` = VALUES( secret ), `shortname` = VALUES( shortname ), `start_ip` = VALUES( start_ip ), `tenant_id` = VALUES( tenant_id )]{NULL, 172.20.145.93, 172.20.145.93, YzY0NWM5NDk3MTUxZThmZTc3MDAxNjQ1, 172.20.145.93 (PacketFence), 1522097631872252, 2887029085, 2887029085, 1} (pf::dal::db_execute)
Mar 26 16:53:51 testing-c7 httpd_admin: httpd.admin(2103) INFO: [mac:unknown] Changes successfully commited in the configuration (pfappserver::Base::Controller::Crud::Config::_commitChanges)

**Comment by jrouzierinverse** [comment]
Fixed by bfb4c18b7b2d25b6f692bf35eb55688c6ead2c08

**Comment by lzammit** [comment]
Still there, the only debug that I can get:

Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] cache get for namespace='Default', key='inreadonly', cache='RawMemory', time='0ms': MISS (expired) (CHI::Driver::_log_get_result)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] not checking db handle, it has been less than 30 sec from last connection (pf::db::is_old_connection_good)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] not checking db handle, it has been less than 30 sec from last connection (pf::db::is_old_connection_good)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] No wsrep provider so considering wsrep as healthy (pf::db::db_wsrep_healthy)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] cache set for namespace='Default', key='inreadonly', size=1, expires='5s', cache='RawMemory', time='0ms' (CHI::Driver::_log_set_result)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) TRACE: [mac:unknown] Memory configuration is still valid for key config::Pf in local cached_hash (pfconfig::cached::is_valid)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:4400495c54e0d1c8cb1bf8279f23578502658a71', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:4400495c54e0d1c8cb1bf8279f23578502658a71', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Mar 28 13:03:29 testing-c7 httpd_admin: httpd.admin(15084) DEBUG: [mac:unknown] cache get for namespace='httpd.admin', key='expires:4400495c54e0d1c8cb1bf8279f23578502658a71', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)

**Comment by extrafu** [comment]
The path to delete the switch is invalid:

Mar 28 15:28:00 localhost httpd_admin_access: 172.20.20.50 - - [28/Mar/2018:15:28:00 -0400] "GET /config/switch/192.168.1.0%2F24/delete?_=1522265258907 HTTP/1.1" 404 619 1156 15632 "https://172.20.100.2:1443/admin/configuration" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "172.20.100.2:1443"

Note that 404.
