### ISSUE TITLE
PF8 : Unable to access local users creation.

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#3052]
On Users / Create access / 
Error! An error occured while contacting the server. Please try again later.
In both Simple and Advanced

**Comment by extrafu** [comment]
That's the error we get from the logs:

==> httpd.admin.log <==
Mar 28 12:10:04 localhost httpd_admin: httpd.admin(26411) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::User->create "Can't use string ("default") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pfappserver/Base/Form/Authentication/Action.pm line 192." (pfappserver::PacketFence::Controller::Root::end)
