### ISSUE TITLE
PF Admin: Associated Realms field to small for Authentication sources

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3053]
If you have more than 2 realms configured or a long realm, It will mask the others selected.

**Comment by extrafu** [comment]
Should @cgx look into this instead?

**Comment by julsemaan** [comment]
If @cgx  looks at #2962, he'll fix this at the same time

**Comment by julsemaan** [comment]
I'm not sure e3fcf8b fixes that because this one was problematic for realms and not auth sources.

I'll check that out

**Comment by julsemaan** [comment]
Confirmed that the realm field of the auth sources expands properly and we can see all the realms
