### ISSUE TITLE
PF admin: Can not create a local user

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3055]
If you try to create a local user you will get that error:

Error! An error occured while contacting the server. Please try again later.

logs/httpd.admin.log:

Mar 28 15:36:27 testing-c7 httpd_admin: httpd.admin(4829) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::User->create "Can't use string ("default") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pfappserver/Base/Form/Authentication/Action.pm line 192." (pfappserver::PacketFence::Controller::Root::end)

**Comment by extrafu** [comment]
Isn't that a dupe of #3052 ?

**Comment by lzammit** [comment]
![f002e4b8cb9ca3f30a08bfe82f5ddd7c](https://user-images.githubusercontent.com/5261214/38053322-c6991126-32a1-11e8-8cb1-e792ad06fc59.jpg)
