### ISSUE TITLE
Delayed violations aren't working in 7.4+

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3056]
When triggering a delayed violation, it puts a release_date of "0000-00-00 00:00:00" and then in violation_maintenance, it ignores those.

Not sure if it should be set to NULL or to the date it should run, but the current value doesn't work

**Comment by jrouzierinverse** [comment]
Have you tested this with the latest maintenance I fixed an issue with that recently.

**Comment by julsemaan** [comment]
Yes I think you're right:
b144a00cd63c15524249be206a8fbadb30302f54

Let me test it in lab, I doubt the deployment had the latest maint since its not us that built it

**Comment by julsemaan** [comment]
It is indeed fixed, closing
