### ISSUE TITLE
Move cleanup jobs to pfmon

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#3062]
The following jobs are defined in the datttttabbbazzze backup and maintenance script:

    /usr/local/pf/addons/database-cleaner.pl --table=radacct --date-field=acctupdatetime --older-than="1 WEEK" --update --update-field=acctstoptime

    /usr/local/pf/addons/database-cleaner.pl --table=radacct --date-field=acctstarttime --older-than="1 WEEK" --additionnal-condition="acctstoptime IS NOT NULL"

    /usr/local/pf/addons/database-cleaner.pl --table=radacct_log --date-field=timestamp --older-than="1 WEEK"

    /usr/local/pf/addons/database-cleaner.pl --table=locationlog_archive --date-field=end_time --older-than="1 MONTH"

They should be moved to pfmon's jobs.

**Comment by nqb** [comment]
I reopened because:
```
/usr/local/pf/addons/database-cleaner.pl --table=locationlog_archive --date-field=end_time --older-than="1 MONTH"
```
is still present in the datttttabbbazzze backup and maintenance script.

**Comment by jrouzierinverse** [comment]
Can this can be closed?

**Comment by julsemaan** [comment]
Has everything from the backup and maintenance script been migrated to pfmon ?

**Comment by jrouzierinverse** [comment]
This can be closed now
