### ISSUE TITLE
API service calls are broken

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#3063]
While:

  curl -s http://127.0.0.1:8080/api/v1/service/netdata/status
{"alive":1,"enabled":1,"managed":1,"pid":"24240"}

works, these don't:

  curl -s http://127.0.0.1:8080/api/v1/service/netdata/stop
  curl -s http://127.0.0.1:8080/api/v1/service/netdata/start
  curl -s http://127.0.0.1:8080/api/v1/service/netdata/restart

**Comment by jrouzierinverse** [comment]
This expected try  
curl -s -X POST http://127.0.0.1:8080/api/v1/service/netdata/stop

**Comment by extrafu** [comment]
You're right, not enough ☕️
