### ISSUE TITLE
V8: pfdns in cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3064]
We need to ensure that pfdhcp will return all the IP addresses on which a pfdns is running for proper load distribution of the DNS traffic.

**Comment by fdurand** [comment]
The code shuffle it :dancer: : https://github.com/inverse-inc/packetfence/blob/devel/go/dhcp/utils.go#L170

**Comment by julsemaan** [comment]
It is shuffled indeed, closing this
