### ISSUE TITLE
(V7) pfdns: leaks memory

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3076]
The perl DNS server leaks memory and the childs never experience a restart so systems with high uptime will have childs that consume a lot of RAM

**Comment by extrafu** [comment]
Perl DNS server?

**Comment by julsemaan** [comment]
Well our current production DNS server

**Comment by extrafu** [comment]
Oh, I misread v7 bug.

**Comment by julsemaan** [comment]
fixed in the 7.x maintenance branches
