### ISSUE TITLE
Admin: No confirmation when deleting an interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3084]
When deleting a VLAN interface in the admin, there is no delete confirmation.

Making it easy for someone to delete this by mistake and put the service down

![image](https://user-images.githubusercontent.com/3857942/38325715-d45b047a-3811-11e8-940f-b6cd5d57c9eb.png)

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
Working on it
