### ISSUE TITLE
Search in Auditing log without enter a start and end time

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#3091]
Hi,

I think it would be better to remove the requirement for enter a start and end time for searching in the Auditing logs of Packetfence. 

=> Error! Start date not provided

Greetings
Tobias

**Comment by julsemaan** [comment]
Doing so would generate queries that are heavy on the server in large scale environments and potentially cause unnecessary load on the server and in worst cases impact negatively the service
