### ISSUE TITLE
REALMS: Realms configuration can not be saved

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3092]
I have seen that on PacketFence 7.4:

Apr  5 08:27:54 packetfence httpd_admin: httpd.admin(18471) ERROR: [mac:unknown] Unable to commit changes to file please run '/usr/local/pf/bin/pfcmd fixpermissions' and try again (pf::ConfigStore::commit)
Apr  5 08:27:54 packetfence httpd_admin: httpd.admin(18471) INFO: [mac:unknown] Unable to commit changes to file please run '/usr/local/pf/bin/pfcmd fixpermissions' and try again

Fix:

chown pf.pf /usr/local/pf/conf/realm.conf

**Comment by julsemaan** [comment]
P.S. @bigzayme this was a +1 since its a bug for the maintenance branch
