### ISSUE TITLE
inline pfdns: isolation lookups don't work

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3094]
If I put a device in isolation while being in inline, it successfully isolates it but pfdns returns weird records.

Doing an nslookup on cnn.com returns IP addresses 192.30.252.153 and 192.30.252.154 which aren't even related to pfdns

The end result still works where the portal is displayed but the host in it is still cnn.com so any TLS won't work with that so we need to address it

**Comment by fdurand** [comment]
If a violation was open then it never returned the portal ip.
Fixed in 43dc4c81b2f316a4821ca1fce0ecd20f87943b88

**Comment by julsemaan** [comment]
Should be fixed by a626b65d81b52bd8df0dc3378aace7c8e4feb29e
