### ISSUE TITLE
PF8 Users: Error while creating a new user

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3096]
I get this error when I click on "Create" on the **USERS** page:
![image](https://user-images.githubusercontent.com/36165527/38439598-36b4c57a-39ac-11e8-8134-e7e97cc22ee7.png)

Log in httpd.admin.log:
```
Apr  6 14:49:22 localhost httpd_admin: httpd.admin(1978) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::User->create "Can't use string ("default") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pfappserver/Base/Form/Authentication/Action.pm line 192." (pfappserver::PacketFence::Controller::Root::end)
```

**Comment by extrafu** [comment]
Works for me with yesterday and today's builds.

Are you sure you ran:

  yum install --enablerepo=packetfence-devel packetfence packetfence-config

followed by:

  cd /usr/local/pf
  ./bin/pfcmd service pf restart

?

**Comment by atran-inverse** [comment]
Yes, you are right. After running that command, I can create users.

I am closing this issue.

**Comment by atran-inverse** [comment]
Fixed in the most recent build
