### ISSUE TITLE
Aerohive MAC Authentication: Deauth issue

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3098]
It looks like the preferred deauth method for the MAC auth is the deauth method for the Web auth with the web form release:

Apr  6 16:50:20 testing-c7 packetfence_httpd.portal: httpd.portal(28289) INFO: [mac:78:4f:43:33:45:f6] Releasing device (captiveportal::PacketFence::DynamicRouting::Module::Root::release)
Apr  6 16:50:20 testing-c7 packetfence_httpd.portal: httpd.portal(28289) INFO: [mac:78:4f:43:33:45:f6] User default has authenticated on the portal. (Class::MOP::Class:::after)
Apr  6 16:50:20 testing-c7 packetfence_httpd.portal: httpd.portal(28289) INFO: [mac:78:4f:43:33:45:f6] (172.20.20.78) supports web form release. Will use this method to authenticate (captiveportal::PacketFence::DynamicRouting::Module::Root::handle_web_form_release)

Even though I specified RADIUS as the deauth method.

When I do a reevaluate access, it works as expected.

**Comment by julsemaan** [comment]
I have confirmed that the web form will only kick in when your session has the external portal flag.

This is a side effect of testing the web-auth + the MAC auth with the same device in a short period of time.
