### ISSUE TITLE
service start issues

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3099]
Using latest `devel` branch.

`git log`:
> commit 5399e6d4dda21c9f8b74b0d4f926ffd2f3633673
> Author: Julien Semaan <jul.semaan@gmail.com>
> Date:   Fri Apr 6 17:22:56 2018 -0400
> 
>     fix wording

Output from `bin/pfcmd service pf restart`:
> Couldn't require pf::api::unifiedapiclient : pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Compilation failed in require at (eval 1509) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> Couldn't require pf::services::manager::iptables : Attempt to reload pf/api/unifiedapiclient.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/ipset.pm line 48.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/ipset.pm line 48.
> Compilation failed in require at /usr/local/pf/lib/pf/node.pm line 95.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/node.pm line 95.
> Compilation failed in require at /usr/local/pf/lib/pf/action.pm line 25.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/action.pm line 25.
> Compilation failed in require at /usr/local/pf/lib/pf/class.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/class.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/violation_config.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation_config.pm line 21.
> Compilation failed in require at /usr/local/pf/lib/pf/violation.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/iptables.pm line 58.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/iptables.pm line 58.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> Compilation failed in require at (eval 1063) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> Couldn't require pf::services::manager::tc : Attempt to reload pf/iptables.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> Compilation failed in require at (eval 2058) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> service|command
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> api-frontend|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> etcd|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> fingerbank-collector|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> haproxy-db|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> haproxy-portal|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.aaa|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.admin|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.collector|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.dispatcher|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.parking|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.portal|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.proxy|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> httpd.webservices|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> keepalived|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> netdata|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfbandwidthd|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfdetect|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfdhcp|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfdhcplistener|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfdns|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pffilter|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfipset|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfmon|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfperl-api|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfqueue|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfsso|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> pfstats|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> radiusd-acct|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> radiusd-auth|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> radsniff|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> redis_ntlm_cache|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> redis_queue|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> routes|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> snmptrapd|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> winbindd|already stopped
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Can't locate object method "new" via package "pf::ipset" at /usr/local/pf/lib/pf/inline.pm line 77.

> ==> logs/packetfence.log <==
> Apr  6 17:40:48 packetfence packetfence: WARN pfcmd.pl(7273): Couldn't require pf::api::unifiedapiclient : pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Compilation failed in require at (eval 1509) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
>  (Carp::carp)
> Apr  6 17:40:50 packetfence packetfence: WARN pfcmd.pl(7273): Couldn't require pf::services::manager::iptables : Attempt to reload pf/api/unifiedapiclient.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/ipset.pm line 48.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/ipset.pm line 48.
> Compilation failed in require at /usr/local/pf/lib/pf/node.pm line 95.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/node.pm line 95.
> Compilation failed in require at /usr/local/pf/lib/pf/action.pm line 25.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/action.pm line 25.
> Compilation failed in require at /usr/local/pf/lib/pf/class.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/class.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/violation_config.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation_config.pm line 21.
> Compilation failed in require at /usr/local/pf/lib/pf/violation.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/iptables.pm line 58.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/iptables.pm line 58.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> Compilation failed in require at (eval 1063) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
>  (Carp::carp)
> Apr  6 17:40:50 packetfence packetfence: WARN pfcmd.pl(7273): Couldn't require pf::services::manager::tc : Attempt to reload pf/iptables.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> Compilation failed in require at (eval 2058) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
>  (Carp::carp)

> ==> logs/pfconfig.log <==
> Apr  6 17:40:51 packetfence pfconfig: pfconfig(1165) ERROR: [mac:[undef]] Can not load namespace resource::unified_api_system_user Read the following message for details:  (pfconfig::manager::get_namespace)
**[repeat many times]**

> ==> logs/packetfence.log <==
> Apr  6 17:40:51 packetfence packetfence: WARN pfcmd.pl(7273): Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
>  (pf::services::manager::pid)
**[repeat many times]**

> ==> logs/packetfence.log <==
> Apr  6 17:40:58 packetfence packetfence: WARN pfcmd.pl(7273): Callback for pthread_atfork() died (ignored): pfconfig::cached_scalar doesn't define a STORE method at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
>  (pf::services::manager::pid)
> Apr  6 17:40:58 packetfence packetfence: ERROR pfcmd.pl(7273): Initialization of iptables modification method failed: Attempt to reload pf/ipset.pm aborted.
> Compilation failed in require at (eval 2203) line 2.
> BEGIN failed--compilation aborted at (eval 2203) line 2. (pf::inline::catch {...} )
> Apr  6 17:40:58 packetfence packetfence: FATAL pfcmd.pl(7273): Can't locate object method "new" via package "pf::ipset" at /usr/local/pf/lib/pf/inline.pm line 77.
>  (pf::inline::get_technique)

**Comment by jrouzierinverse** [comment]
Fixed by 67738ed0d4837c6de53bcbe79454f5be6286cbb9

**Comment by satkunas** [comment]
Using latest `devel` branch:

> commit 67738ed0d4837c6de53bcbe79454f5be6286cbb9
> Author: James Rouzier <jrouzier@inverse.ca>
> Date:   Sat Apr 7 19:33:53 2018 -0400
> 
>     Empty STORE

Output from bin/pfcmd service pf restart:

> Couldn't require pf::api::unifiedapiclient : Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Compilation failed in require at (eval 1509) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> Couldn't require pf::services::manager::iptables : Attempt to reload pf/api/unifiedapiclient.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/ipset.pm line 48.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/ipset.pm line 48.
> Compilation failed in require at /usr/local/pf/lib/pf/node.pm line 95.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/node.pm line 95.
> Compilation failed in require at /usr/local/pf/lib/pf/action.pm line 25.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/action.pm line 25.
> Compilation failed in require at /usr/local/pf/lib/pf/class.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/class.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/violation_config.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation_config.pm line 21.
> Compilation failed in require at /usr/local/pf/lib/pf/violation.pm line 32.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/violation.pm line 32.
> Compilation failed in require at /usr/local/pf/lib/pf/iptables.pm line 58.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/iptables.pm line 58.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
> Compilation failed in require at (eval 1063) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> Couldn't require pf::services::manager::tc : Attempt to reload pf/iptables.pm aborted.
> Compilation failed in require at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
> Compilation failed in require at (eval 2058) line 2.
>  at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
> service|command
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> Callback for pthread_atfork() died (ignored): Can't use an undefined value as a HASH reference at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 53.
> read_file '/usr/local/pf/conf/unified_api_system_pass' - sysopen: No such file or directory at /usr/local/pf/lib/pfconfig/namespaces/resource/unified_api_system_user.pm line 25.

**Comment by julsemaan** [comment]
latest devel works fine on my dev machine and from what I can tell on my machine running the builds.

The problematic line has something to do with the new API system user which you probably need to generate using:
```
# cd /usr/local/pf
# make conf/unified_api_system_pass
```

Then, you probably need to restart packetfence-config if you didn't after pulling since there is a new pfconfig resource.

Let me know if that helps

**Comment by satkunas** [comment]
@julsemaan that works, thank you.
