### ISSUE TITLE
Dashboard uptime not always rounded

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3103]
Google Chrome Version 65.0.3325.146 (Official Build) (64-bit)

![screenshot from 2018-04-09 13-19-37](https://user-images.githubusercontent.com/3904468/38512318-ef305b02-3bf8-11e8-98b7-fe17d8d95170.png)

**Comment by cgx** [comment]
I dropped the custom counters and now rely on netdata's svg badges (0f25466).
