### ISSUE TITLE
Portal: AUP page style seems to be off

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3109]
![image](https://user-images.githubusercontent.com/3857942/38557706-dadf264e-3c9b-11e8-8784-2232def85b43.png)

The AUP used to be scrollable, not sure if we still want that.

Also, the "I accept the terms" isn't centered, not sure if that was intended

**Comment by cgx** [comment]
What browser do you use? It looks fine on Chrome.

**Comment by julsemaan** [comment]
I use Firefox 59.0.2 on Ubuntu 16.04

**Comment by cgx** [comment]
Restart httpd.portal.
