### ISSUE TITLE
Portal: review organization of the release page

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3110]
This one is not really a real glitch, just found the placement odd.

@cgx can state whether or not its pretty:
![image](https://user-images.githubusercontent.com/3857942/38558500-5c4261b8-3c9e-11e8-88c1-e69b61867180.png)

**Comment by cgx** [comment]
I moved the alerts above the title, but when the template also contain an alert, the result is awkward, as in your screenshot. I will rollback this change.
