### ISSUE TITLE
Dashboard: Some metrics seem out of place

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3114]
There are a bunch of red metrics at the top of the dashboard, not sure what they are for and even if they should be there

![image](https://user-images.githubusercontent.com/3857942/38575554-ad3c7c72-3cc9-11e8-853e-2dd7fba7c7ca.png)

**Comment by cgx** [comment]
Those are the alerts as reported by netdata.

**Comment by julsemaan** [comment]
Don't we want to style this differently ?

And potentially put them in a container of alerts so its clearer these are alerts ?

**Comment by cgx** [comment]
You might want to check `/netdata/127.0.0.1/api/v1/alarms` for an explanation of the *ok* alerts!?

**Comment by julsemaan** [comment]
@cgx 

Are we creating some sort of container for the alerts to make it clear what that it, and potentially contain them in a white card ?

**Comment by cgx** [comment]
I prefer to keep the alerts "floating" above the charts. Maybe I can add an icon to emphase warnings and errors.

**Comment by julsemaan** [comment]
@cgx 

I believe you adjusted the errors, can we close this or are there additional adjustments to be done on the alerts ?

**Comment by cgx** [comment]
I'm done unless someone has a suggestion for a better display.

**Comment by julsemaan** [comment]
I think we can call it a day as far as the issue here
