### ISSUE TITLE
Pfmon: Inline accounting dal error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3120]
Apr 12 09:32:46 lobby pfmon: pfmon(8586) ERROR: [mac:unknown] Error running task inline_accounting_maintenance: [SQL::Abstract::__ANON__] Fatal: -and => \$scalar makes little sense, use -and => [ \$scalar, \%rest_of_conditions ] instead at /usr/local/pf/lib/pf/dal.pm line 937.

**Comment by julsemaan** [comment]
Assigned +1 since I'm guessing 7.4 would be affected by this, @jrouzierinverse can confirm while doing the fix
