### ISSUE TITLE
pfconfig doesn't flush key after removed from conf

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3121]
**Steps to reproduce:**

Create `conf/stats.conf` with:
```
[metric 'test1']
type=api
```
`bin/pfcmd pfconfig reload`
`bin/pfcmd pfconfig show config::Stats`:
```
$VAR1 = {
    'metric \'test1\'' => {
        'type' => 'api',
    }
};
```
Empty and replace the contents of `conf/stats.conf` with:
```
[metric 'test2']
type=api
```
`bin/pfcmd pfconfig reload`
`bin/pfcmd pfconfig show config::Stats`:
```
$VAR1 = {
    'metric \'test1\'' => {
        'type' => 'api',
    },
    'metric \'test2\'' => {
        'type' => 'api',
    }
};
```
**Note that test1 no longer exists in the conf, but it still exists in pfconfig.**

**Expected behaviour:** 
`'metric \'test1\''` should be flushed and removed from pfconfig.
`bin/pfcmd pfconfig show config::Stats`:
```
$VAR1 = {
    'metric \'test2\'' => {
        'type' => 'api',
    }
};
```
**Additional Notes:**
`bin/pfcmd pfconfig clear_backend` between conf modifications does not appear to correct this issue.

**Comment by julsemaan** [comment]
My wild guess is that the time isn't right on your machine when it boots and pfconfig starts which causes issues when reloading the config.

I'll try to replicate it in lab but I think that it won't be removing a key that won't work, its any change you're doing on your stats configuration file

**Comment by julsemaan** [comment]
Just tested in lab removing a section and it works fine

**Comment by jrouzierinverse** [comment]
Maybe part of the issue is timestamp check will fail if time ever goes backwards and the control file changes or is restored to an older timestamp version for some reason.

To avoid that scenario it would be better to check for if timestamp to equal instead of greater or equal.
So in other words instead if this
```perl
if ( $memory_timestamp >= $file_timestamp ) {
```
this
```perl
if ( $memory_timestamp == $file_timestamp ) {
```
https://github.com/inverse-inc/packetfence/blob/devel/lib/pfconfig/cached.pm#L248

**Comment by julsemaan** [comment]
The thing is that memorized_at contains the time at which it was read, not the time of the filesystem timestamp when it was read.

I don't really see why a server should be able to go back in time without the services requiring to be restarted. In this case, if packetfence-config was restarted, it would fix it. We require a server to be restarted when changing a timezone, I believe the same logic would apply to a large time change.

We're not in Men In Black:
https://www.youtube.com/watch?v=zaSZE194D4I

One thing we could do if this is really hurting is have pfconfig detect it went back in time during each request by comparing the current time with the time of the last request.

When detecting that, it would clear out all of its control files to force the clients to request their configuration again.

**Comment by satkunas** [comment]
It's not a timezone issue. I emptied `/conf/stats,conf` restarted `packetfence-config` and all the previous metrics were removed, except there's 1 artifact still remaining.  I abstracted the metric below as `[metric test2]` above. I'm unable to empty/clear it:

```
$VAR1 = {
          'metric \'total dhcp leases remaining on enp0s8\'' => {
                                                                  'statsd_ns' => 'source.packetfence.dhcp_leases_enp0s8',
                                                                  'api_path' => '/api/v1/dhcp/stats/enp0s8',
                                                                  'api_compile' => '$[0].free',
                                                                  'statsd_type' => 'gauge',
                                                                  'api_method' => 'GET',
                                                                  'type' => 'api',
                                                                  'interval' => '60s'
                                                                }
        };
```

**Comment by julsemaan** [comment]
Not timezone, more like time issue. I've seen the issue a lot when you boot a virtual machine, it picks up the wrong time from the host, then ntpd fixes the time by bringing it back to the correct one but packefence-config was started with a date later than now.

When doing changes to the config, are you doing:
```
/usr/local/pf/bin/pfcmd configreload hard
```

And its normal that you get that metric even though the file is empty, remember that we're generating some metrics automagically based on the list of the interfaces offering DHCP

**Comment by satkunas** [comment]
@julsemaan I've located the non-"artifact" in `lib/pfconfig/namespaces/config/Stats.pm`. 

Closing this issue.
