### ISSUE TITLE
Dashboard: most sections are still empty

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3122]
This is more of a meta issue so we don't mistakenly forget this before the release but only the first tab of the dashboard has graphs now

RADIUS, authentication and endpoints are still empty

**Comment by cgx** [comment]
I'll commit new stuff today.

**Comment by julsemaan** [comment]
New stuff was added, I think @fdurand is doing the last tab (portal)

@fdurand 

Can you confirm if all the metrics are there for the release ?

**Comment by fdurand** [comment]
Yes it is but let says if the httpd.portal.access file is empty then you will not have any graph.
In fact netdata must be restarted after some activity on PacketFence

**Comment by julsemaan** [comment]
sections not empty anymore
