### ISSUE TITLE
Netdata statsd timing metrics are inacurate

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3124]
Won't re-explain everything here, I opened this issue on netdata:
firehol/netdata#3630

**Comment by julsemaan** [comment]
@fdurand 

The netdata team addressed the concern in the latest codebase

We have the choice between using their latest codebase or patching the package we have with this: https://patch-diff.githubusercontent.com/raw/firehol/netdata/pull/3649.diff

**Comment by fdurand** [comment]
Centos Package ok, just need to upload it on the repo.

**Comment by fdurand** [comment]
Debian package ready too. I have updated the devel repo.

**Comment by julsemaan** [comment]
Confirmed its fixed
