### ISSUE TITLE
pfdns: Adding/removing a passthrough requires to restart pfdns

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3127]
To replicate (172.21.156.1 is the registration IP):
- Perform: nslookup zammitcorp.com 172.21.156.1
-- Resolves to the registration IP
- Add zammitcorp.com as a passthrough
- Perform: nslookup zammitcorp.com 172.21.156.1
-- Will still resolve as the registration IP
- Restart pfdns
- Perform: nslookup zammitcorp.com 172.21.156.1
-- Now resolves to the real zammitcorp.com IP

I thought that limitation of having to restart pfdns went away with the new Golang based pfdns. If it didn't then we should add a note in the fencing section about restarting it

**Comment by fdurand** [comment]
Probably because we initialize the passthrough list when we start the pfdns.
@julsemaan If we add a goroutine that fetch pfconfig for the passthrough list each 15s ?

**Comment by julsemaan** [comment]
We could use the pfconfig pool inside pfdns since its a caddy plugin, it wouldn't be too hard to put it into that.

But, at this stage, I think that documenting it is not a regression and we address hot-reload in 8.1

I will do the documentation adjustment

**Comment by julsemaan** [comment]
I've adjusted documentation.conf

Lets address this properly in 8.1
