### ISSUE TITLE
LDAP: 7.4 versus 8.0 catchall rule is much slower

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3130]
After performing load testing, 802.1x EAP-PEAP was discovered to be slower by about 25 millisecond.

Performed profiling and found that LDAPSource.match_rule is much slower in 8.0 as it spends much more time performing LDAP calls than before.

Showed it to @jrouzierinverse and he said he will investigate

**Comment by jrouzierinverse** [comment]
Were you using a fresh 7.4 install or did you apply maintenance?

**Comment by julsemaan** [comment]
Applied the maintenance on 7.4 and the latency kicks in.

From what I can tell the LDAP source on 7.4 was bugged and didn't do some LDAP calls so we can't really fix the added latency.
