### ISSUE TITLE
API confusion(s)

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3131]
I'm attempting to make an API request using the unifiedapi client, as I don't know of another way to test API requests without skipping the access token that's req'd when using curl:

```
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/inverse-inc/packetfence/go/log"
	"github.com/inverse-inc/packetfence/go/unifiedapiclient"
	"os"
	"time"
)

var ctx context.Context

var raw json.RawMessage

func main() {
	d := time.Now().Add(500 * time.Millisecond)
	ctx, cancel := context.WithDeadline(context.Background(), d)
	ctx = log.LoggerNewContext(ctx)
	defer cancel()

	var err error

	apiclient := unifiedapiclient.NewFromConfig(ctx)
	if len(os.Args) < 2 {
		fmt.Println("Error: Endpoint URL required\nUsage: " + os.Args[0] + " /api/v1/endpoint")
		os.Exit(0)
	}

	fmt.Println("GETing: " + os.Args[1])

	err = apiclient.Call(ctx, "GET", os.Args[1], &raw)
	if err != nil {
		fmt.Println("Error: " + err.Error())
		return
	}

	var prettyJSON bytes.Buffer
	error := json.Indent(&prettyJSON, raw, "", "\t")
	if error != nil {
		fmt.Println("JSON parse error: ", error)
		os.Exit(1)
	}
	fmt.Println("Response:", string(prettyJSON.Bytes()))

}
```

I make a request to /translations:

`./apiget /api/v1/translations/`
> GETing: /api/v1/translations/
> Error: Error body doesn't follow the Unified API standard, couldn't extract the error message from it.

Error seen in logs:

> ==> logs/packetfence.log <==
> Apr 16 18:00:40 packetfence pfhttpd: 16/Apr/2018:18:00:40 -0400 [ERROR 502 /api/v1/translations/] dial tcp 127.0.0.1:8080: connect: connection refused

I have nothing listening on `tcp/8080`...

So what's using `tcp/8080`?
`ag "8080" conf/`
>conf/systemd/packetfence-pfperl-api.service
> 9:ExecStart=/usr/local/pf/sbin/pfperl-api prefork -m production -l http://127.0.0.1:8080 --pid-file /usr/local/pf/var/run/pfperl-api.pid

It appears that service `pfperl-api` is what now listens on 8080 (`pfunified_api` appears to be deprecated). 

A `packetfence-pfperl-api.service` unit file exists in `conf/systemd`, but it's not in `/etc/systemd/system/packetfence.target.wants/`

`locate packetfence-pfperl-api.service`
> /usr/local/pf/conf/systemd/packetfence-pfperl-api.service
> /usr/local/pf/debian/packetfence-pfperl-api.service

`ls -la /etc/systemd/system/packetfence.target.wants | grep pfperl`
>[empty]

`sh addons/enable_systemd.sh` does not install `packetfence-pfperl-api.service`. Bug? Intentional?

I'm not sure how to proceed.
  - Having an easier way to perform API req's without needing to utilize an access token would be helpful.
  - Knowing whether I should be using `pfunified_api` or `pfperl-api` for backend would help.

**Comment by jrouzierinverse** [comment]
Try these following commands to reload the packetfence service files.
```bash
\cp /usr/local/pf/conf/systemd/packetfence* /usr/lib/systemd/system/
systemctl daemon-reload
```

**Comment by jrouzierinverse** [comment]
Please close it bug if it works
