### ISSUE TITLE
Captive Portal: AUP displays the whole AUP at once.

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3137]
It will be nice we could put a button to go directly to the submit button because on small like iPhone it could be long to reach it when you have a huge AUP.

Maybe another design that make the user not scroll down the whole AUP.

**Comment by julsemaan** [comment]
I +1 @lzammit comment, its not really what the users are used to.

Its always been in some kind of container that would be scrollable

I see the point where it would improve the chances of the user reading it

My personal favorite for a T&C acceptance is something like this:
![image](https://user-images.githubusercontent.com/3857942/38929865-c29aba4e-42db-11e8-8d2f-a4af546ac96f.png)

And when you would click on the T&C link it opens them in some sort of modal.
That would mean the T&C would be back on the same page as the other fields

But then again, I'm terrible in UX design and it might be too late for such a big change so going with the scrollable container might be the right thing at this point
