### ISSUE TITLE
Web Admin: Registering a node without a role shows a successful registration 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3139]
If you try to register a node with the action button and there is no role assign to it will display:

Success! 1 node(s) were registered.

But in reality, it's not doing anything which is good, but I think we should display an error like:

Node does not have any role...

**Comment by jrouzierinverse** [comment]
This is an old behavior we should look what changing would mean.

**Comment by jrouzierinverse** [comment]
Spoke to Julien about this and he mentioned that there sometimes good reasons to allow no roles on a node.
Will move to 8.3
