### ISSUE TITLE
Dashboard: Excessive amount of alerts for disk full

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3142]
I have a few domains configured which creates quite a few mount points on my machine.

My disk is almost full, I'm happy the netdata alerts are there to tell me, but there are about 100 alerts that go on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on...

![image](https://user-images.githubusercontent.com/3857942/38931679-fbc0c812-42e1-11e8-880c-5fd281129478.png)

**Comment by fdurand** [comment]
Looks that netdata check all the mounted fs.
Need to check if it's possible to disable the check on /chroots/...

**Comment by julsemaan** [comment]
@fdurand 

Was this addressed so we close this ?

**Comment by julsemaan** [comment]
Now I don't get any more alerts when my disk is close to being full

**Comment by julsemaan** [comment]
Actually scratch my previous comment, the alerts show but I'm still getting them for the chroots though...
