### ISSUE TITLE
pfdhcp: a DHCPINFORM triggers a DHCPNAK which causes the client to lose its IP

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3146]
If a client sends a DHCPINFORM, pfdhcp sends a NAK which causes the client to loses its IP address.

Reading through what a DHCPINFORM is used for, it seems we should probably just leave it unanswered

@fdurand can likely confirm

**Comment by fdurand** [comment]
It's suppose to return a DHCP Ack: http://www.ietf.org/rfc/rfc2131.txt or nothing.
I prefer the ack because we can return additional options.

**Comment by julsemaan** [comment]
It seems that if we don't send an ACK then that may delay the initialization of the client so lets send an ACK
