### ISSUE TITLE
i18n: Most of the new services don't have their translation

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3157]
In system configuration -> services you can see a lot of missing translations

**Comment by cgx** [comment]
Can you see them on [transifex](https://www.transifex.com/inverse/packetfence/viewstrings/#en/pfappserver)?

**Comment by julsemaan** [comment]
They seem to be there

**Comment by julsemaan** [comment]
@jrouzierinverse 

Update on this?

**Comment by jrouzierinverse** [comment]
Somehow I missed it.

**Comment by extrafu** [comment]
@cgx Anything to do for transifex after @jrouzierinverse's commit? I could finish the translation.

**Comment by cgx** [comment]
The source strings were pushed to transifex.
