### ISSUE TITLE
Inconsistent location of service binaries

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3160]
The following service binaries are in /usr/local/pf/bin
- pfhttpd
- pfdhcp
- pfdns
- pfstats

While we have the following in /usr/local/pf/sbin
- pfbandwidthd
- pfconfig
- pfdetect
- pfdhcplistener
- pffilter
- pf-mariadb
- pfmon
- pfperl-api
- pfqueue
- radsniff-wrapper
- winbindd-wrapper

**Comment by julsemaan** [comment]
Don't really think this is something we should address for 8.0 given the tight deadline we have to release
