### ISSUE TITLE
http portal error in httpd.portal.access file

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3161]
Looks that the order matter in /etc/rsyslog.d/packetfence.conf.

If we have that:

```
if $syslogtag contains "httpd_portal" then
  -/usr/local/pf/logs/httpd.portal.access
& stop

if $syslogtag contains "httpd_portal_err" then
  -/usr/local/pf/logs/httpd.portal.error
& stop
```
Then the first contition will catch http_portal and http_portal_error and all the logs will be in the file /httpd.portal.access

**Comment by jrouzierinverse** [comment]
Fixed by a3ac3ade55ba57b5b73b6440160dead75f266a4f
