### ISSUE TITLE
PFDNS: issue with domain name resolved from the system

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3162]
Commands to reproduce:

[root@testing-c7 pf]# nslookup accounts.youtube.com 172.22.145.1
;; connection timed out; trying next origin
Server:		172.22.145.1
Address:	172.22.145.1#53

** server can't find accounts.youtube.com: NXDOMAIN

Apr 19 16:21:17 testing-c7 pfdns[18960]: ERROR pfdns database query returned sql: no rows in result set
Apr 19 16:21:17 testing-c7 pfdns[18960]: 19/Apr/2018:16:21:17 -0400 [PANIC accounts.youtube.com. A] plugin/pfdns/pfdns.go:532 - runtime error: invalid memory address or nil pointer dereference
Apr 19 16:21:22 testing-c7 pfdns[18960]: ERROR pfdns database query returned sql: no rows in result set
Apr 19 16:21:22 testing-c7 pfdns[18960]: 19/Apr/2018:16:21:22 -0400 [PANIC accounts.youtube.com. A] plugin/pfdns/pfdns.go:532 - runtime error: invalid memory address or nil pointer dereference
Apr 19 16:21:27 testing-c7 pfdns[18960]: ERROR pfdns database query returned sql: no rows in result set
Apr 19 16:21:27 testing-c7 pfdns[18960]: 19/Apr/2018:16:21:27 -0400 [PANIC accounts.youtube.com. A] plugin/pfdns/pfdns.go:532 - runtime error: invalid memory address or nil pointer dereference
Apr 19 16:21:32 testing-c7 pfdns[18960]: ERROR pfdns database query returned sql: no rows in result set
Apr 19 16:21:32 testing-c7 pfdns[18960]: 172.22.145.1 :  passthrough
Apr 19 16:21:32 testing-c7 pfdns[18960]: 172.22.145.1 - [19/Apr/2018:16:21:32 -0400] "A IN accounts.youtube.com.localdomain. udp 50 false 512" NXDOMAIN qr,rd,ra 126 88.213988ms

**Comment by jrouzierinverse** [comment]
This has been fixed please try the newest release.

**Comment by lzammit** [comment]
Fixed.
