### ISSUE TITLE
Reports' topsponsor has no order by

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3166]
Either the SQL query is missing an `ORDER BY`, or the report title is misleading - in which case it should read `report_latestsponsor_sql`:

https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/pfcmd/report.pm#L366

```
    $report_statements->{'report_topsponsor_sql'} = get_db_handle()->prepare(qq [
        SELECT email,count(*) as sponsor
        FROM email_activation limit 25;
    ]);
```

**Comment by satkunas** [comment]
Furthermore, table does not exist on `prod-pf`, I'm unsure if this is because it's running an earlier version, or the table creation was missed:

`ERROR 1146 (42S02): Table 'pf.email_activation' doesn't exist`

**Comment by julsemaan** [comment]
I think this table doesn't exist since a long long time

Probably a forgotten cleanup
