### ISSUE TITLE
Certificate Management via Webinterface

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#3169]
Hi,

it would be nice to manage the Certificates for the Webinterface and Radius Server via Webinterface.

Greetings
Tobias

**Comment by julsemaan** [comment]
Its a good idea, we've talked about it a few times here where we would have a certificate storage system editable via the GUI, then we could assign certificates to RADIUS, haproxy, the admin from there

I'll put 8.1 on it although I doubt we'll have time to address it by then
