### ISSUE TITLE
Issue with dashboard in latest devel package

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3171]
![image](https://user-images.githubusercontent.com/3857942/39136549-7bc2d95a-46e9-11e8-8d65-aa853724a98c.png)

```
[root@localhost pf]# rpm -qa | grep packetfence
packetfence-release-1.2-7.el7.noarch
packetfence-pfcmd-suid-7.4.9-0.201804231035.el7.x86_64
packetfence-config-7.4.9-0.201804231035.el7.noarch
packetfence-7.4.9-0.201804231035.el7.noarch
packetfence-ntlm-wrapper-7.4.9-0.201804231035.el7.x86_64
```

**Comment by julsemaan** [comment]
my bad, I did a zammiterie

**Comment by cgx** [comment]
We'll start calling them *semaanerie* ;)

**Comment by julsemaan** [comment]
I do have a recent tendency to open useless Github issues.

At least that serves as a constant test to know if Github issues still work :)
