### ISSUE TITLE
Dashboard: Radius data title not showing

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3180]
I think it's because the title is too big.

<img width="373" alt="screen shot 2018-04-24 at 3 09 09 pm" src="https://user-images.githubusercontent.com/5261214/39208659-a37371ba-47d1-11e8-8054-05811dd6e5bc.png">

**Comment by julsemaan** [comment]
Seeing the same behavior when viewing the system graphs for a cluster

**Comment by julsemaan** [comment]
@cgx or @fdurand 

Can one of you look into this?

Is there anything we can do other than making the graphs one by line when the screen is too small ?

**Comment by julsemaan** [comment]
As discussed verbally with @cgx, the solution will likely be to bring back the multiple servers into a single graph which can't be done for 8.0

Now, we'll have to decide whether or not we present them one on each row or leave the status quo

**Comment by julsemaan** [comment]
@cgx will perform a test to split it on multiple lines for smaller screens.

You knwo what they say about small screens?

**Comment by cgx** [comment]
Fixed with 4dbcb31.
