### ISSUE TITLE
DAL: pfqueue issue

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3182]
Cluster of 3 nodes, I got that in the log after getting the registration vlan. I don't know if it's related or not.

It appears that I can connect on the db manually.

Apr 24 15:13:48 cluster2 pfqueue: pfqueue(9069) FATAL: [mac:78:4f:43:33:45:f6] unable to connect to database: Can't connect to MySQL server on '127.0.0.1' (4 "Interrupted system call") at /usr/local/pf/lib/pf/dal.pm line 70.
 (pf::db::db_connect)
Apr 24 15:13:48 cluster2 pfqueue: pfqueue(9069) ERROR: [mac:78:4f:43:33:45:f6] unable to connect to database: Can't connect to MySQL server on '127.0.0.1' (4 "Interrupted system call") at /usr/local/pf/lib/pf/dal.pm line 70.

**Comment by jrouzierinverse** [comment]
Can you attach the logs for mysql

**Comment by lzammit** [comment]
Sure:

[mariadb_error.log](https://github.com/inverse-inc/packetfence/files/1944537/mariadb_error.log)

**Comment by jrouzierinverse** [comment]
Can you also send what happened before that error.

**Comment by lzammit** [comment]
I send the packetfence.log via email.

Thanks,

**Comment by julsemaan** [comment]
@jrouzierinverse and @lzammit 

We need to sort this one out ASAP

**Comment by extrafu** [comment]
@jrouzierinverse and @lzammit what's the status on this?

**Comment by lzammit** [comment]
Need more test because @jrouzierinverse says that he was not able to find the root cause of that issue.

**Comment by extrafu** [comment]
After verbal discussions with @lzammit (where he spitted coffee on himself) I'm lowering priority of this one.

**Comment by julsemaan** [comment]
No way to replicate it so we'll close that

@lzammit can reopen if needed
