### ISSUE TITLE
Multiples issues on debian

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3189]
`Apr 25 11:34:25 fabiane apache2[6234]: Can't locate pfappserver/Authentication/Store/PacketFence.pm in @INC (you may need to install the pfappserver::Authentication::Store::PacketFence module) (@INC contains: /usr/local/fingerbank/lib /usr/local/pf/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl . /etc/apache2) at /usr/share/perl5/Catalyst.pm line 3253.\n\tCatalyst::setup_plugins('pfappserver', 'ARRAY(0x55d64c2d94e8)') called at /usr/share/perl5/Catalyst.pm line 1164\n\tCatalyst::setup('pfappserver') called at /usr/local/pf/lib/pfappserver.pm line 370\n\trequire pfappserver.pm called at (eval 2) line 2\n\teval 'require pfappserver' called at /usr/local/pf/lib/pfappserver.pm line 0\nCompilation failed in require at (eval 2) line 2.\n`

`Apr 25 11:47:47 fabiane apache2[7917]: Can't locate captiveportal/DynamicRouting/Module/URL.pm in @INC (you may need to install the captiveportal::DynamicRouting::Module::URL module) (@INC contains: /usr/local/pf/html/pfappserver/lib /usr/local/fingerbank/lib /usr/local/pf/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl . /etc/apache2) at /usr/local/pf/html/pfappserver/lib/pfappserver/Form/Config/PortalModule/URL.pm line 17.\nBEGIN failed--compilation aborted at /usr/local/pf/html/pfappserver/lib/pfappserver/Form/Config/PortalModule/URL.pm line 17.\nCompilation failed in require at /usr/share/perl5/Catalyst/Utils.pm line 308.\nCompilation failed in require at (eval 2) line 2.\n`

` packetfence: FATAL pfcmd.pl(8943): Can't locate captiveportal/DynamicRouting/Application.pm in @INC (you may need to install the captiveportal::DynamicRouting::Application module) (@INC contains: /usr/local/pf/conf /usr/local/pf/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl) at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 1173.`

**Comment by julsemaan** [comment]
Wild guess, this is because of the new symlinks that were put in place.

@jrouzierinverse Could you check that one out ?

**Comment by fdurand** [comment]
Fixes by b5e813bd6b856fed9df10713fdf669523e2b99c7
