### ISSUE TITLE
OpenAPI spec: issues with autogen DAL models

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3190]
The autogenerated DAL paths seem to be lacking schemas when looking at the rendered spec

Looking at the radius_audit_log, there isn't a schema for the response nor for the body to POST when creating it

**Comment by julsemaan** [comment]
@jrouzierinverse 

Was this fixed by the commits in #3191 ?

**Comment by jrouzierinverse** [comment]
It was fixed by that
