### ISSUE TITLE
OpenAPI spec: Looking at the search of a DAL resource fails

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3191]
I clicked on "POST /tenants/search" and it spins and never displays anything

Getting this error in at the top:
![image](https://user-images.githubusercontent.com/3857942/39263204-7f7da0fa-488f-11e8-8e97-dc273cc3efcf.png)

**Comment by jrouzierinverse** [comment]
Fixed by f0e90bf25827a1f8fd50805eadac36f188dd65e4, 8a099431d57a303c45457aa1f2569ae5df0e2c68, ee1d9f632277381906d70e5e2dc2210a495d2322
