### ISSUE TITLE
Dashboard: When a chart isn't found, "ugly" error shows

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3197]
Since when we restart netdata there are good ods we may be missing some charts and not having them empty, it may make sense to show the pretty "No data found" when the chart isn't found since that would be common in a fully working environment

![image](https://user-images.githubusercontent.com/3857942/39275706-2e0b19ee-48b4-11e8-9259-a3d4f57d008d.png)

**Comment by extrafu** [comment]
I suggest we show @lzammit face instead.

**Comment by julsemaan** [comment]
Good idea, that way the user would really be clueless but happy at the same time with such a friendly face

**Comment by cgx** [comment]
Should already be fixed by 3b34182. I'll need to look at your environment.

**Comment by julsemaan** [comment]
@cgx 

I was actually seeing the pretty warning but at some point it stopped showing

Maybe another semaanrie, who knows :)

**Comment by extrafu** [comment]
So we close?

**Comment by julsemaan** [comment]
Lets close and address it if we see it again. It may be an isolated issue or a semaanrie/zammiterie
