### ISSUE TITLE
API spec: DAL resource path parameter isn't listed as a parameter

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3198]
For example, if you take GET /radius_audit_log/{radius_audit_log_id}, the radius_audit_log_id URL parameter isn't declared so its impossible to set it through the UI when trying API calls

Problematic:
![image](https://user-images.githubusercontent.com/3857942/39306663-c6f9723e-492e-11e8-881b-a776b8f1a460.png)

What is expected:
![image](https://user-images.githubusercontent.com/3857942/39306719-ea32bc24-492e-11e8-8089-83a3ed48d82a.png)

**Comment by jrouzierinverse** [comment]
OK I will fix that

**Comment by jrouzierinverse** [comment]
Fixed by 484b3cd7685b86c25f2e3cab9b76a8fba8584eeb 104afa1f39b461adbac0cbff5b0e7e83ba39725c
