### ISSUE TITLE
Unknow certificate authorithy (from portal)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3203]
httpd.portal(15164) ERROR: [mac:10:1f:74:b2:f6:a5] Error while communicating with the Fingerbank collector. 500 Can't connect to 127.0.0.1:4723 (certificate verify failed) (pf::fingerbank::endpoint_attributes)

**Comment by julsemaan** [comment]
maybe old fingerbank-4.0.0 package ?

**Comment by fdurand** [comment]
Need to add SSL_verify_mode => 0x00 there https://github.com/fingerbank/perl-client/blob/master/lib/fingerbank/Collector.pm#L51

**Comment by fdurand** [comment]
Fixed by https://github.com/fingerbank/perl-client/commit/ead117a1d04b330e17645f0f9aaf9dc83b39cf00
