### ISSUE TITLE
haproxy-db only listen on ipv6 (debian)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3208]
https://github.com/inverse-inc/packetfence/blob/devel/conf/haproxy-db.conf.example#L40 allow only to listen on ipv6. Change it by 127.0.0.1:3306 fix it.

**Comment by julsemaan** [comment]
probably your localhost entry in your hosts file only contains ipv6 addresses ?

**Comment by fdurand** [comment]
It contain both:
```

127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
