### ISSUE TITLE
Admin Role does not have permission to modify node role when a role is specified in Allowed Node Roles field

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3217]
In the web admin, Configuration -> System Configuration -> Admin Access, a new admin role was created with a role specified under Allowed node roles:
![image](https://user-images.githubusercontent.com/36165527/39597219-a6906034-4ee2-11e8-81c7-2f8656b8a33d.png)

When a user belonging in this admin role tries to assign the role to a node, PF gives an error when clicking on Save:
![image](https://user-images.githubusercontent.com/36165527/39597306-f5dcb188-4ee2-11e8-896f-a1cb3c5edb1c.png)

All actions for Nodes are defined: 
![image](https://user-images.githubusercontent.com/36165527/39597404-3f5e5280-4ee3-11e8-98f3-8b010f8725f6.png)

**Comment by julsemaan** [comment]
This should go in the maintenance 7 + 8

**Comment by julsemaan** [comment]
@atran-inverse said this is still an issue currently on 7.2 with the commit that was done.

Is there another commit ?

**Comment by jrouzierinverse** [comment]
yup and it is pushed
