### ISSUE TITLE
pfsnmp and pfsnmp_parsing are getting slow

### ISSUE THREAD

**Issue by gustavoortega** [inverse-inc/packetfence#3219]
Hi, actually i using PacketFence 7.3 and have problems with pfqueue, more specifically with pfsnmp and pfsnmp_parsing.
We set 8 workers for each one and everythings works ok (the queue is on zero counter and the cpu load is using all cores), but after some hours, the cpu load went to a minimum value and the queue increments to 4000. 
At this situation we have a lot of delay between a trap arrived and packetfence doing something (update locationlog, set vlan, etc.)

If a restart pfqueue service, everything seems to work ok again (cpu load increase, queueu goes to zero), but after some hours, again we have the same situation with delay.

Can you help me?

Thanks a lot, Gustavo.

**Here is my pfqueue.conf**
```
[pfqueue]
workers=55
[queue general]
workers=8
has_delayed_queue=enabled
delayed_queue_batch=100
delayed_queue_sleep=100
delayed_queue_workers=1
[queue pfdhcplistener]
workers=8
[queue pfdetect]
workers=5
[queue pfsnmp]
workers=16
[queue pfsnmp_parsing]
workers=16
```

**Comment by jrouzierinverse** [comment]
There was an issue with the queue getting stuck this was fixed in 
maintenance.
You can apply maintenance by running the command perl addons/pf-maint.pl.

**Comment by gustavoortega** [comment]
Good day and thanks for answering.
Could you explain me a little more specifically (step by step) about what I should do to correct this problem.
My environment is production. Could this affect it with a microcut?

Thank you very much.
