### ISSUE TITLE
pfstats will never timeout on a RADIUS source

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3224]
Similar to this issue: #3207 

The context sent here:
https://github.com/inverse-inc/packetfence/blob/devel/go/stats/main.go#L95

Should contain a deadline, otherwise that will never return if a packet is lost along the way at some point

**Comment by julsemaan** [comment]
Restarting pfstats would fix this, thus marking this as a zammitbug

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/go/stats/main.go#L231

**Comment by julsemaan** [comment]
I'm not sure but I think that if you hit the deadline once, the context is canceled and will never cancel again since the deadline is set right when the program starts instead of where RADIUS is being called

Also, the deadline will always be in the past since its set on startup and not on usage so my wild guess is that it will cause issues

**Comment by julsemaan** [comment]
fixed by a00275f7fcb17b84dec2e7d62864c031981d8fde

**Comment by fdurand** [comment]
Need to be fixed for eduroam source too.

**Comment by julsemaan** [comment]
Here we go:
dac1d52e01ac4e6b241746bbd0843c0b37cb7245
