### ISSUE TITLE
Enter on login pages causes password to be displayed

### ISSUE THREAD

**Issue by brgerig** [inverse-inc/packetfence#3229]
PacketFence Version 8.0.0
OS: Windows
Browser: Chrome, Firefox, IE

Behavior: On login pages (both captive portal and status page), pressing the Enter key while in the password field causes the password to be shown in plain-text.

Expected behavior: Pressing Enter in password field should submit form.

**Comment by julsemaan** [comment]
I thought this was addressed in another issue raised by @lzammit (but can't seem to find the issue...)

Lets look into it
