### ISSUE TITLE
Netdata python plugin process uses more than 3GB of RAM

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3230]
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                    
9228 netdata   20   0 3548340 3.142g   1864 S   3.7 55.4 246:54.82 python                                                                                                                                                                    


# ps -edf | grep 9228
netdata   9228 13950  5 May08 ?        04:06:57 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
```

**Comment by fdurand** [comment]
https://github.com/firehol/netdata/issues/3817

**Comment by julsemaan** [comment]
It seems netdata has made official the workaround in netdata/netdata#4185 and netdata 1.11.0 is available.

We could try to use 1.11 to have an official unpatched version of netdata

**Comment by extrafu** [comment]
Good idea! Let's make it happen for v8.3.

**Comment by ipkpjersi** [comment]
Somehow, I'm getting this issue in Netdata v1.35.0-161-gf44e0c3c1 on Ubuntu 22.04:

3182.63 Mb /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 

ps -edf | grep 1531659
netdata  1531659 1531210  1 14:40 ?        00:00:02 /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

3.182G so basically the same 3.1G as OP.

**Comment by julsemaan** [comment]
@ipkpjersi 

This isn't the bug repository for Netdata, this is PacketFence (a product that does use netdata itself).

You should post your issue there: https://github.com/netdata/netdata
