### ISSUE TITLE
An ldap source defined with multiples ip addresses is not supported by pfstats

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3234]
If an ldap source is defined with host = 192.168.0.7,192.168.0.76 then pfstat will log that:
May 14 10:29:32 srvpf /usr/local/pf/bin/pfstats[2069]: t=2018-05-14T10:29:32+0200 lvl=eror msg="Error connecting to LDAP source: LDAP Result Code 200 \"Network Error\": dial tcp: lookup 192.168.0.7,192.168.0.76: no such host" pid=2069
And an alert will be triggered in the dashboard.

**Comment by extrafu** [comment]
How about if it is space-separated? That's how it works for virtually all LDAP-based libraires, OpenLDAP-backed or not. If it works space-separated, we should update the doc/sample, not try to fix a broken provided value.
