### ISSUE TITLE
Improper device_score sort on /nodes

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3249]
The API endpoint `/api/v1/nodes?cursor=0&limit=25&sort=device_score` sorts using a `string`, rather than an `int`.

Where `9.00` > `89.00`

**Comment by jrouzierinverse** [comment]
Device score is a string in the table.
So either we change the field to a float or leave it as is.
@julsemaan Any preference?

**Comment by julsemaan** [comment]
The version can actually be text so we can't change it to a number unfortunately

**Comment by jrouzierinverse** [comment]
device_version or device_score

**Comment by julsemaan** [comment]
Sorry my bad, read it too quickly, device score can actually be an int

**Comment by jrouzierinverse** [comment]
Float or int?

**Comment by julsemaan** [comment]
Right now in Fingerbank its limited to being an int so I'd say we go with consistency across them

**Comment by jrouzierinverse** [comment]
Fixed by 0319a7ffad57c99bc95ba6d5b2d3a54113cb3b75.
Run the following sql command to your db to fix.
```sql
ALTER TABLE node
    MODIFY device_score int DEFAULT NULL;
```
