### ISSUE TITLE
pfappserver API updates

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3265]
This issue is used to track changes needed in the unified API to provide endpoints for the pfappserver.

**Comment by satkunas** [comment]
The following endpoints are needed, for single actions.
 * POST
 * by MAC only (no PID)

- [x] clear violation
- [x] register node
- [x] deregister node
- [x] reevalutate access
- [x] restart switchport
- [x] apply role
- [x] apply bypass role
- [x] apply violation

**Comment by satkunas** [comment]
The following endpoints are needed, for bulk actions.
 * POST
 * by MAC array only (no PID)
 * response returns array of success/errors in same index as request

- [x] clear violation
- [x] register node
- [x] deregister node
- [x] reevalutate access
- [x] restart switchport
- [x] apply role
- [x] apply bypass role
- [x] apply violation

**Comment by satkunas** [comment]
@jrouzierinverse endpoints needed, please update!

**Comment by satkunas** [comment]
@jrouzierinverse the response on the following endpoint returns an empty "{}". 

PATCH /api/v1/node/{mac}

A status of either "success", "failed", or "skipped" is needed here.

**Comment by satkunas** [comment]
Nodes search sort not working on the following keys:

URL Ref: /api/v1/nodes?cursor=0&limit=10&fields=[snipped]&sort=[key]

- locationlog.connection_type

**Comment by satkunas** [comment]
- [x] Error when attempting to join `ip6log.ip` field in nodes endpoint: https://packetfence:9999/api/v1/nodes?cursor=0&limit=10&fields=status,online,mac,pid,ip4log.ip,ip6log.ip,device_manufacturer,locationlog.connection_type,locationlog.session_id&sort=mac

**Comment by satkunas** [comment]
The following node searches have issues:

URL Ref: POST https://packetfence:9999/api/v1/nodes/search

Fails (500 response code): 
- `{op: "and", values: [{op: "or", values: [{field: "online", op: "not_equals", value: "off"}]}]}`
- `{op: "and", values: [{op: "or", values: [{field: "online", op: "not_equals", value: "on"}]}]}`

Returns unexpected invalid (mixed) results:
- `{op: "and", values: [{op: "or", values: [{field: "online", op: "equals", value: "on"}]}]}`

Works as expected (no issue):
- `{op: "and", values: [{op: "or", values: [{field: "online", op: "equals", value: "off"}]}]}`

**Comment by satkunas** [comment]
`ALLOWED_JOIN_FIELDS` missing ability to JOIN `violation` and/or `violation_name`

**Comment by jrouzierinverse** [comment]
ip6log.ip was added

**Comment by satkunas** [comment]
> ip6log.ip was added

confirmed to be working, thanks @jrouzierinverse

**Comment by jrouzierinverse** [comment]
Fix issue with online

**Comment by satkunas** [comment]
> Fix issue with online

@jrouzierinverse My tests don't confirm this. can you define the following payloads to filter online/offline nodes?

Online:
 * `{op: "and", values: [{op: "or", values: [{field: "online", op: "?", value: "?"}]}]}`

Offline:
 * `{op: "and", values: [{op: "or", values: [{field: "online", op: "?", value: "?"}]}]}`

**Comment by jrouzierinverse** [comment]
Sorry since online is virtual column it only makes sense to support ops not_equals/equals with values on/off/unknown.

I will provide better error handling when exception are given.

**Comment by jrouzierinverse** [comment]
Done

**Comment by jrouzierinverse** [comment]
Can we close this issue @satkunas

**Comment by satkunas** [comment]
The following sort keys are not functioning w/ `/api/v1/nodes/search`: 
- violations.open_vid
- violations.open_count

**Comment by jrouzierinverse** [comment]
FIxed

**Comment by satkunas** [comment]
`PATCH /api/v1/node/00:0b:82:01:fc:42` returns empty response `{}`. Status [success|error|skipped] needed.

**Comment by satkunas** [comment]
Missing individual node actions (seeing 404):

* /api/v1/node/[mac]/reevaluate_access
* /api/v1/node/[mac]/restart_switchport

**Comment by satkunas** [comment]
Need API endpoint for Custom Reports

https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Installation_Guide.asciidoc#custom-reports

- [x] GETter for all custom reports (eg: GET /config/reports)
- [x] GETter for single custom report (eg: GET /config/report/authentications)
- [x] SETter for adding a new custom reports (eg: PUT /config/reports)
- [x] SETter for editing an existing custom report (eg: PATCH /config/report/authentications)
- [x] SETter to delete an existing report (eg: DELETE /config/reports/authentications)
- [x] GETter to execute/paginate/limit an existing report

**Comment by satkunas** [comment]
- [x] PATCH /api/v1/node/00:01:02:03:04:05 with `unregdate: null` does not clear previous defined unregdate.

**Comment by jrouzierinverse** [comment]
You cannot set it to null if you want to clear it set it to "0000-00-00 00:00:00"

**Comment by extrafu** [comment]
@satkunas / @jrouzierinverse Can we close that issue?

**Comment by extrafu** [comment]
@satkunas / @jrouzierinverse I need an answer if we can close that issue.

**Comment by jrouzierinverse** [comment]
From my view point yes.

**Comment by extrafu** [comment]
Ok, so I close it.
