### ISSUE TITLE
The api frontend authorization layer is incomplete

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3268]
Currently the api frontend handles the authorization however it cannot handle the following cases.

For instance if a users only has NODES_READ access he cannot perform a search.

**Comment by jrouzierinverse** [comment]
Should this be included in 8.1 or 8.2?

**Comment by extrafu** [comment]
8.2 is ok unless the effort to fix this is minimal.

**Comment by jrouzierinverse** [comment]
A generalized solution that will work in all cases will be non trivial in my mind.
Unless @julsemaan has any simple solutions to this issue.

**Comment by julsemaan** [comment]
If we would be sticking to the semantics of the HTTP verbs, there shouldn't be cases where that would fail.

The main issue here is that we're POSTing data to get data, so the proper verb should have been GET in this case even though there is a request body.

We can have a special case for the "POST search" or make the search a GET since we're getting data and not creating data through the HTTP call

**Comment by jrouzierinverse** [comment]
When looking into the various solutions to the problem.

Using GET has the following limitations.

Approach | Limitation
----------| ----------
Payload in body  |  the XMLHttpRequestobject does not support it.
Payload encoded has a query parameter | There is a size limit of 2083 characters for the path in URL so will fail for really big searches.
Payload exploded in a query parameters | There is a size limit of 2083 characters for the path in URL so will fail for really big searches.

Using a POST for the search has none of the above limitations.

**Comment by julsemaan** [comment]
I have no issues keeping the POST and creating a remap hash for those special cases

**Comment by julsemaan** [comment]
We'll need to state on what we do about this, lets keep it for 8.2 since we'll be in feature freeze in a few hours

**Comment by jrouzierinverse** [comment]
Leave it for 8.2 since it only affects the preview.

We would need to decide how we deal with special cases like search and sub collections/ resource like /user/${mac}/ nodes.

**Comment by jrouzierinverse** [comment]
I am moving this to 9.1 since we removed or handled all the special case in devel.

**Comment by julsemaan** [comment]
The special cases have all been handled AFAIK. @jrouzierinverse can we close this ?

**Comment by jrouzierinverse** [comment]
Yes
