### ISSUE TITLE
Auditing: Last 30 minutes sets an end date

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3280]
In the auditing report, if we select "Last 30 minutes", it sets both the start and the end date while before it set only the start date.

Its pretty inconvenient to have it set both since new RADIUS requests that occur after the click on this button don't get shown.

This seems to be only for 8.0, 7.4 and before behave the proper way (i.e. without setting the end date)

**Comment by julsemaan** [comment]
@jrouzierinverse 

This would be nice to fix since its annoying to clear the end date everytime we select a time range

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
It will be done today

**Comment by jrouzierinverse** [comment]
Fix by 645b696b0076ec8b958074343cd0b75d0d07e19d
