### ISSUE TITLE
Radius can't read server.key

### ISSUE THREAD

**Issue by BackToTheFuture1955** [inverse-inc/packetfence#3281]
I am running CentOS 7 with version 8.0. I generated the certs and added them to the tls_certificate folder, changed paths in eap.conf and chown pf:pf /usr/local/pf/conf/ssl/tls_certs/*
When I try and restart radiusd it does not come back up. I tailed /var/log/messages and I am getting a permission denied for server.key from radiusd. I even did a chmod 777 without luck. SELinux is set to disabled, so I can't think of anything else that would cause this.

**Comment by fdurand** [comment]
Use the mailling list for config issue.
