### ISSUE TITLE
Profile filter, impossible to define a time period that has a comma in it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3284]
Perl's Time::Period supports setting multiple time periods in the same condition by separating them with a comma but when its done, it breaks the filters that are a comma delimited field

**Comment by julsemaan** [comment]
Example of a problematic 
```
wd {1 3 5 7} min {0-29}, wd {2 4 6} min {30-59}
```

**Comment by jrouzierinverse** [comment]
Which I maintenance branch put this in?

**Comment by jrouzierinverse** [comment]
Double up the comma.
wd {1 3 5 7} min {0-29},, wd {2 4 6} min {30-59}

**Comment by julsemaan** [comment]
I would go with the sevens and 8 if it applies easily to all the sevens
