### ISSUE TITLE
Load issue when accounting is enabled

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3294]
When having the accounting enabled with about 90K rows in radacct and 950K in radacct_log, the queries are putting an enormous load on the MySQL server.

Guessing its related to a missing index like in #3293 and #3292 

Disabling the recording of the accounting in the MySQL tables fixed it on the problematic environment

**Comment by julsemaan** [comment]
Hitting this issue on another environment

We need to address this, @jrouzierinverse have you reviewed the SQL statements that were modified to make the accounting tenant aware in 8.0 ?

**Comment by julsemaan** [comment]
We seem to be lacking indexes on the tenant_id column in radacct and radacct_log

The environment that was problematic had RADIUS complaining of timeouts in the rest module which would indicate the stored procs aren't the issue and would make sense that the SQL calls in httpd.aaa are causing issues since they're likely scoped to a tenant by default and there is no index on that column

**Comment by julsemaan** [comment]
Put an attempted fix in f7cd044 for 8.1

Its not backportable in the maintenance since its a schema change.

@jrouzierinverse, would it be possible to unscope the queries in pf::accounting so they aren't tenant aware to fix the issue for 8.0 ?

**Comment by jrouzierinverse** [comment]
Adding an index on just tenant_id will not fix the issue since all the tenants are the same.
It will still do a full scan anyways since all the tenants are the same.
We should remove the index until we know what it is causing the slowness.

**Comment by julsemaan** [comment]
@lzammit will provide a big dump to @jrouzierinverse

**Comment by extrafu** [comment]
@jrouzierinverse Please make sure you got the test data from @lzammit and test your fix. If all is fine, close that issue.

**Comment by jrouzierinverse** [comment]
Can we close this?
