### ISSUE TITLE
Configurator : can't continue wizard with default password

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3307]
In Step 5 Administration, instructions say : 

> Please note that if you do not change the password, the default one is admin

If you leave password fields empty and click on `Continue`, you get following error :  

> Error! Please verify your configuration. 

### Expected result

Clicking on `Continue` without changing admin password works.

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
Fixed by removing the text
