### ISSUE TITLE
LDAP source shuffle help message

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3318]
![image](https://user-images.githubusercontent.com/3857942/41556931-1c6c8fe4-730a-11e8-8550-51194a34cc81.png)

Not sure exactly what it means

**Comment by extrafu** [comment]
And also, ldap -> LDAP

**Comment by jrouzierinverse** [comment]
Any suggestions on verbiage?

**Comment by cgx** [comment]
My suggestion: *Randomly choose LDAP server to query*
