### ISSUE TITLE
Project ID translation shown for AD rule field

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3324]
As seen in the screenshot below:
![image](https://user-images.githubusercontent.com/3857942/41618308-c97724c6-73d0-11e8-99e8-512ccda803dd.png)

To replicate, create a new AD source, before saving, create a new authentication rule, and add a condition

**Comment by jrouzierinverse** [comment]
Fixed by 48b68cb3146a0d8f49a04e3fe68eb497776b2b28
