### ISSUE TITLE
Authentication source, cannot see the +/- buttons for conditions

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3325]
As seen in the screenshot below:
![image](https://user-images.githubusercontent.com/3857942/41618353-f1aa6304-73d0-11e8-9d90-3d1bf5633836.png)

I can't get to see the buttons to add/remove conditions.
Even if I resize the window they always stay hidden

**Comment by jrouzierinverse** [comment]
Which source is this?

**Comment by julsemaan** [comment]
the ad source

**Comment by jrouzierinverse** [comment]
The problem seems to be that of the conditions of the AD source is an empty string.
This only happens when creating a new source.
