### ISSUE TITLE
The virtual service pf is shown in the services page

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3329]
In the admin interface, go in Status->Services, and the pf service is there:

![image](https://user-images.githubusercontent.com/3857942/41662006-13b08f26-746e-11e8-825e-88db264fc895.png)

**Comment by fdurand** [comment]
Fixes by https://github.com/inverse-inc/packetfence/commit/1af90081aa08e8196da4d752368f381b6adbe1df
