### ISSUE TITLE
Audit Log opens wrong node info

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#3336]
Hi,

I have this Issue since PF v8.0.1. (We upgraded from 7.2 to 8.0.1 yesterday)

If I click an the Mac Adress in the auditlog, the Node info for that mac adress should open.
But most time a wrong node info opens... 
I click on 00:17:c8:08:76:64 but pf shows the info from 00:25:45:93:23:b0
--

**Comment by julsemaan** [comment]
I think that may be some caching issue in the browser

@jrouzierinverse, would it be possible to not have caching enabled when viewing a node in the audit log. I've seen cases where you would change a node, reopen it and it would show the previous state cached in the browser

**Comment by Venice-89** [comment]
Indeed, I load the site klick on a mac address and the correct node infos open.
I click on the next mac address the node info from the mac before opens again.

If I reload the auditlog page I click an a mac the correct node info opens.

I use the Chrome browser but same issue with firefox.

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
I see the problem it should be fixed today
