### ISSUE TITLE
web admin : access to new web interface with Firefox

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3350]
With packetfence-8.0.9-0.201806260000.el7.noarch and Firefox 60.0.2, I get following error when trying to log on new web interface with my admin account : 
> A networking error occured. Is the API server running?

In Developper tools, I see that my self-signed certificate is responsible for that error : 
![bug_api](https://user-images.githubusercontent.com/10830260/41935352-5d40d7de-7957-11e8-8c21-2e84544a136c.png)

but Firefox doesn't display me a warning message to add an exception regarding this certificate.

I guess that using 9999 port in place of 1443 disturb Firefox.

With Chromium 67.0.3396.62, I can not reproduce this issue, all is working fine.

**Comment by julsemaan** [comment]
My wild guess would be to have a reverse proxy for the API on port 1443 so that way it uses the same SSL approbation rules as the admin interface

**Comment by cgx** [comment]
The only way to make it work without any code change is to manually visit the API URL in Firefox (port 9999) and add an exception for the certificate. This is the same procedure for accessing the Web admin on port 1443 when using a self-signed certificate.

I think we need to go with @julsemaan suggestion and proxy the connections to the API as we do for the Netdata API.

**Comment by julsemaan** [comment]
@fdurand will create the reverse proxy, then @cgx will adjust the code to call the reverse proxy instead

**Comment by nqb** [comment]
works as expected.
