### ISSUE TITLE
Multiple Server Installation - Backup/Restore.

### ISSUE THREAD

**Issue by pizu** [inverse-inc/packetfence#3353]
Hi,

I am going to install multiple servers with packetfence v8.0.1, mixed between VMs & Physical servers, is it possible to synchronize the authentication sources/roles/sso firewalls and roles in the sso's only? or if we take a sql backup, can we restore between servers? I have tried the sql restore and it's always defaulting :(

**Comment by julsemaan** [comment]
This is not a bug nor a development issue, please use the mailing list for such questions
