### ISSUE TITLE
The generated assets for the admin can no longer be updated via pfmaint

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3354]
Since we do not check in the generated admin assets anymore.
We need a way to get the latest assets from pfmaint.

**Comment by julsemaan** [comment]
We could use a similar method as what we do with the golang binaries

**Comment by jrouzierinverse** [comment]
It may make more sense to use a tarball of all the generated files.
To avoid having to add all the generated files to pf-maint.pl script every time we add a new file.

**Comment by julsemaan** [comment]
Makes sense, what I meant was more to generate the files and distribute them through inverse.ca/downloads and have them signed using our key

**Comment by extrafu** [comment]
Since the new GUI isn't official, I suggest we bump that issue for 8.2.

**Comment by julsemaan** [comment]
That issue affects the current admin I believe, @cgx and @jrouzierinverse can correct me if I'm wrong

**Comment by cgx** [comment]
@julsemaan, indeed. The current admin and the portal's CSS.

**Comment by julsemaan** [comment]
The assets of the new admin can be updated
