### ISSUE TITLE
New Admin sneak peek doesn't work on debian

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3367]
Clicking on the link New Admin Sneak Peek give a blank page on Debian.

In the log:

Jun 29 15:02:27 fabian8 httpd_admin_access[10633]: 172.20.20.67 - - [29/Jun/2018:15:02:27 -0400] "GET /static/alt/css/app.64c468878e19955310c6542998823f69.css HTTP/1.1" 404 541 576 193 
....

The file is here: /usr/local/pf/html/pfappserver/root/static.alt/dist/css/app.64c468878e19955310c6542998823f69.css

**Comment by cgx** [comment]
Looks like this [symlink](https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static/alt) is not packaged.

**Comment by nqb** [comment]
In build logs : 
```
/usr/bin/install: omitting directory 'html/pfappserver/root/static/alt'
[..]
```
