### ISSUE TITLE
(web admin) Report that relates MAC addresses or users to DNS queries made by them

### ISSUE THREAD

**Issue by MuriloCalegari** [inverse-inc/packetfence#3384]
Hi,

PacketFence already has a DNS logging feature in pfdns.log, but it often looks quite overpopulated with maybe thousands of DNS queries and redirects to CP, making it quite difficult to identify which websites were visited by some users.
Here in Brazil we are obligated to have a relation of what websites users are accessing in a specific time. It would be a great feature to have a custom report in web admin interface that would filter all DNS queries made by some user in a specific time range. Of course, this report could be highly protected by some sort of super admin account.

Hope you can address this feature!

Best Regards,

Murilo

**Comment by fdurand** [comment]
It has been added in PacketFence 9.1.0
