### ISSUE TITLE
Have a stats.conf.defaults

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3388]
Similarly to our other configuration files that ship with sections defined in our official codebase, we should have a defaults file for stats.conf so if a user needs to modify/add something its in an overload file

**Comment by jrouzierinverse** [comment]
The need for this will go away with the merge of pfstats and pfmon we could close this.

**Comment by julsemaan** [comment]
Not sure when that will happen though given its probably pretty far down the R&D pipe with all the other more important stuff.

Having stats.conf.defaults would take an hour to put in place and would make things easier to configure
