### ISSUE TITLE
pfdetect in 8.10 can't compile regex that validates OK in the UI

### ISSUE THREAD

**Issue by giannidaprile** [inverse-inc/packetfence#3390]
The following regex extracts MAC and IP from a syslog message using named captures, non-greedy matching:

.*\ ip\ (?<ip>.*)?\ .*\ mac\ (?<mac>.*)?\ -.*

pfdetect fails to start with:

panic: regexp: Compile(`.*\ ip\ (?<ip>.*)?\ .*\ mac\ (?<mac>.*)?\ -.*`): error parsing regexp: invalid or unsupported Perl syntax: `(?<`

Probably a side effect of pfdetect being written in golang vs perl the UI code .

**Comment by giannidaprile** [comment]
Cound just be a documentation issue.

Using golang notation works in both the UI and pfdetect:

.*\ ip\ (?P<ip>.*)?\ .*\ mac\ (?P<mac>.*)?\ -.*

See:
https://github.com/google/re2/wiki/Syntax

**Comment by giannidaprile** [comment]
My bad, Examples are being messed up by markup.  Resubmitting with with code blocks:

The following regex extracts MAC and IP from a syslog message using named captures, non-greedy matching:

`.*\ ip\ (?<ip>.*)?\ .*\ mac\ (?<mac>.*)?\ -.*`

pfdetect fails to start with:

panic: regexp: Compile(.*\ ip\ (?<ip>.*)?\ .*\ mac\ (?<mac>.*)?\ -.*): error parsing regexp: invalid or unsupported Perl syntax: (?<

Probably a side effect of pfdetect being written in golang vs perl the UI code .

Cound just be a documentation issue.

Using golang notation works in both the UI and pfdetect:

Cound just be a documentation issue.

Using golang notation works in both the UI and pfdetect:

`.*\ ip\ (?P<ip>.*)?\ .*\ mac\ (?P<mac>.*)?\ -.*`

See:
https://github.com/google/re2/wiki/Syntax

**Comment by julsemaan** [comment]
@giannidaprile 

You're 100% correct, the re2 syntax should be used now

@jrouzierinverse will proceed to adjust our documentation and the upgrade guide

**Comment by jrouzierinverse** [comment]
The real answer to this is to use re::engine::RE2 to test the regex.
