### ISSUE TITLE
"make vendor" fails on devel

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3394]
Failing with:
```
# make vendor
npm install
npm WARN pfappserver@7.0.0 No description
npm WARN pfappserver@7.0.0 No repository field.
npm WARN pfappserver@7.0.0 No license field.
bower ace-builds#1.3.x         EINVRES Request to https://bower.herokuapp.com/packages/ace-builds failed with 502
make: *** [vendor] Error 1
```

If I visit the URL, it outputs the following:
```
This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io
```

I did then update bower to 1.8.4 and it started working again.

So, my guess is that we should but bower >= 1.8.4 in package.json but I just wanted to check with @cgx that it won't break anything for the new admin

**Comment by cgx** [comment]
@julsemaan We don't use bower in the new admin 👍
