### ISSUE TITLE
References to PacketFence_Administration_Guide still exist

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#3401]
New cluster running 8.1 and under **Configuration --> Network Configuration --> Network Settings --> DHCP option82**, the help icon points to the PacketFence_Administration_Guide and gives a 404:

https://<ip-address>:1443/static/doc/PacketFence_Administration_Guide.html#_dhcp_option_82

Assuming it should point towards the PacketFence_Installation_Guide?

Haven't come across it anywhere else...

**Comment by julsemaan** [comment]
You're 100% right

**Comment by julsemaan** [comment]
Fixed in devel and in maintenance
