### ISSUE TITLE
Network Interfaces are not displayed from the web gui

### ISSUE THREAD

**Issue by mickaelidf** [inverse-inc/packetfence#3402]
Hi,

I installed packetfence  8.1.0  but there is not network interface displayed from the web gui.

![issue_not_network_interfaces displayed](https://user-images.githubusercontent.com/41395012/42972737-c30aed5a-8bb0-11e8-89e2-6acccd0ea1db.PNG)

 Can you help to fix this issue ?

Thanks ahead for your help.
Micky

**Comment by julsemaan** [comment]
Can you provide the content of httpd.admin.log and httpd.admin.error

Thanks

**Comment by mickaelidf** [comment]
Hi,
Attached the two files : 
[Uploading httpd.admin.error.txt…]()
[httpd.admin.log](https://github.com/inverse-inc/packetfence/files/2215363/httpd.admin.log)

Thanks

**Comment by fdurand** [comment]
Not enough memory on the system:
Jul 19 23:48:47 packetfence httpd_admin: httpd.admin(5347) WARN: [mac:unknown] Problem trying to run command: LANG=C sudo ip -4 -o link show  called from (eval). OS Error: Ne peut allouer de la m\E9moire (pf::util::pf_run)

**Comment by mickaelidf** [comment]
Hi,
Great thank for your feeback.
I will add more memory on the system.

**Comment by mickaelidf** [comment]
Now i can see the network interfaces! 
![network_interfaces displayed_after_add_more_memory](https://user-images.githubusercontent.com/41395012/43089398-c8c6e676-8ea4-11e8-8cbb-0aa7a85a6649.PNG)
I suggest to follow the Minimum Hardware Requirements 

https://packetfence.org/doc/PacketFence_Installation_Guide.html
