### ISSUE TITLE
DHCPDECLINE doesn't make the IP unavailable in the pool

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3408]
Making the DHCP server offering it over and over to the device which will constantly decline it.

The IP should be excluded from the pool if we receive a DHCPDECLINE for it

**Comment by julsemaan** [comment]
Current fixes:
48e7a28439253f50a70270b31caf13100ff3e017
d384ca0df5010a5fa7ada3d0556a2287f41e16b4

**Comment by julsemaan** [comment]
it has been backported to 8.1 but the first commit doesn't cleanly patch on maintenance/8.0

Will see with @fdurand for this

**Comment by julsemaan** [comment]
@fdurand 

Did you put the commits for this issue in maintenance/8.0 ?

If so, then we can close this

**Comment by fdurand** [comment]
yes it's in maintenance/8.0
