### ISSUE TITLE
device-registration URL not valid

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3409]
The following 'device-registration' URL returns a `Page not found`

https://github.com/inverse-inc/packetfence/blob/48e7a28439253f50a70270b31caf13100ff3e017/docs/PacketFence_Installation_Guide.asciidoc#L1835

**Comment by julsemaan** [comment]
This is because the device registration isn't enabled

**Comment by nqb** [comment]
Agree with @julsemaan, I didn't reproduce that issue.

**Comment by satkunas** [comment]
Perhaps the docs should be clarified to include this condition.

**Comment by julsemaan** [comment]
Just below this paragraph it says "As from PacketFence 7.3 and onwards you need to create a device registration profile and associate it with the connection profile."

@satkunas, feel free to reword it into something clearer if needed
