### ISSUE TITLE
inaccurate reports/operating systems device type count

### ISSUE THREAD

**Issue by tgrandey** [inverse-inc/packetfence#3411]
Running Version: PacketFence 8.0.1
Browsers Used (same results):
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Firefox Quantum Version 61.0.1 (64-bit)

NOTE: Split out this unfixed bug 1a from issue #3251

Description:
Bug 1a) In the admin portal, under REPORTS/Operating Systems, the pie chart and associated data table reflect wildly inaccurate counts for most device type descriptions (e.g. showing a count of 3 for "Cisco IP Phone", when the NODES search page shows well over 125 nodes of this device type). Increasing the time frame selection (from 7d default to 90d max) does not improve this inaccuracy.

**Comment by jrouzierinverse** [comment]
I don't think this relevant anymore.

**Comment by jrouzierinverse** [comment]
Do you think this can be closed?

**Comment by jrouzierinverse** [comment]
@julsemaan 
Could this be closed? I don't think it is relevant anymore.

**Comment by julsemaan** [comment]
We would need to see if it applies to the new admin. AFAIK, the report logic hasn't changed but I maybe wrong so that could still apply

**Comment by satkunas** [comment]
More information is be needed in order to assess the discrepancy.  Closing.
