### ISSUE TITLE
web admin : enable/disable connection profile

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3412]
Option to enable or disable a connection is not obvious :

![screenshot from 2018-07-25 08-21-10](https://user-images.githubusercontent.com/10830260/43200476-b6e8cde4-8fe3-11e8-81ac-21044cb2ec2e.png)

When I see this setting, I'm not sure if my profile is enabled or disabled.

My proposal : simply change description to "Profile is enabled".

I think we can also remove useless comment "If profile is disabled it will not used" which is, however, obvious.

**Comment by extrafu** [comment]
👍

**Comment by julsemaan** [comment]
+1

**Comment by satkunas** [comment]
"Enable Profile"
