### ISSUE TITLE
configurator : improve database step

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3413]
As report by users in mailing list : 
- https://www.mail-archive.com/packetfence-users%40lists.sourceforge.net/msg15490.html
- https://www.mail-archive.com/packetfence-users%40lists.sourceforge.net/msg15491.html

when you have to set up root password of the pf database, configurator leads to confusion.

If you haven't define previously your root password (most cases) for the pf database, you need to follow this steps : 
1. Click on `Test` button in "Enter the MySQL root account credentials" section
1. Type your root password in pop-up window then click on `Save` button
1. Retype your root password in "Enter the MySQL root account credentials" section
1. Click on `Test` button

We need to simplify this process. We can take inspiration from other softwares that do the same thing.

My first proposal : 
1. Use a second button to set up the root password. We need to keep the `Test` button
1. Auto-fill password field in "Enter the MySQL root account credentials" section with password typed in pop-up window
1. Test directly new root password : user doesn't need to click on the `Test` button

**Comment by julsemaan** [comment]
I agree with points 1 and 2 of the proposal. Not with the auto-test of the root password though, if we auto-populate it from the popup, there is no point in testing it.

Then I'd suggest maybe not showing the test button if we test that password-less access works, then showing the test button after the user sets up the credentials.

But then I suck in UX so my opinion here should be taken with a grain of salt

**Comment by nqb** [comment]
This step has been improved by new configurator.
