### ISSUE TITLE
Cant login to Packetfence

### ISSUE THREAD

**Issue by hiranuk** [inverse-inc/packetfence#3414]
Hi 

I have managed to install packetfence on oracle virtual box. When i run it it load up to a login prompt i have entered the login username and password as it shows on the setup guide but it keeps coming up with error with usernamne or password. Also it says i should browse to it IP in order to configure, but when i do i get "page cannot displayed" im not sure why the web GUI is not loading. Thanks

![2018-07-25 15_59_10-10 0 2 15](https://user-images.githubusercontent.com/41695279/43210451-120dcc22-9027-11e8-8216-a37fb8bce7f3.png)

**Comment by nqb** [comment]
- For login prompt, are you sure you use the correct keyboard layout ? Try to write password in Login field.
- For GUI access, you can't access to 10.0.2.15 from your host. You need to define a forwarded port (like 14443) to your guest host (10.0.2.15:1443). Then you can point your browser to https://localhost:14443

**Comment by hiranuk** [comment]
Hi Thanks yes it seems to be set to US keyboard and not UK. I can now login from the VM command line but still cannot login through the wed GUI. I have set the port forward.

![2018-07-25 16_53_40-10 0 2 15](https://user-images.githubusercontent.com/41695279/43212366-b278e0c6-902b-11e8-8f5e-6f1e06336643.png)
![2018-07-25 16_50_42-10 0 2 15](https://user-images.githubusercontent.com/41695279/43212371-b5f361b8-902b-11e8-8fe7-1d81c7fb7062.png)
