### ISSUE TITLE
Cannot login to packetfence / portforward

### ISSUE THREAD

**Issue by hiranuk** [inverse-inc/packetfence#3415]
Hi i can now login to packet fence form the VM command line but still cannot login to its GUI. I tried port forward but still no luck. Thanks

![2018-07-25 16_53_40-10 0 2 15](https://user-images.githubusercontent.com/41695279/43212485-fa29d93e-902b-11e8-8c9e-3be85da90c73.png)
![2018-07-25 16_50_42-10 0 2 15](https://user-images.githubusercontent.com/41695279/43212490-fc1034f0-902b-11e8-949f-be0980399f55.png)

**Comment by nqb** [comment]
Host IP should be : 127.0.0.1.

Leave Guest IP empty.

**Comment by hiranuk** [comment]
Hi Thanks. I have tried that but still i cannot get the login GUI. I also cannot ping 10.0.2.15 can anyone tell me what that IP is ? as my Router is set to DHCP and gives out a different range, shouldn't packetfence be picking up an IP from my router?.

On the VM login after i login there is  command line, do i need to configure anything there? before the web GUI is accessible.  Thanks

![2018-07-26 08_59_03-10 0 2 15](https://user-images.githubusercontent.com/41695279/43249577-f8eaca60-90b2-11e8-8b56-385cb550cfd6.png)

**Comment by hiranuk** [comment]
do i need to setup the portforward in the virtual box properties as well?

![2018-07-26 09_38_09-10 0 2 16](https://user-images.githubusercontent.com/41695279/43251498-fd221e1c-90b7-11e8-8689-38b18e7afd1f.png)

**Comment by nqb** [comment]
@hiranuk 

This bug tracker is for development issues only and confirmed bugs.

For general help please use the mailing list
