### ISSUE TITLE
Feature Request: Chart the percentages of guest registration methods

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#3416]
We are interested in getting easy visibility into how guests register for access on our network.  I know under **Other Reports** there are reports/lists of recent email- and SMS-based registrations.  Might it be a good idea to have a pie chart showing the percentage of each method?

For example, we only allow email and SMS (via Twilio).  We would find it helpful having a pie chart showing 80% of guest access was granted via SMS and 20% was granted via email, etc, etc...

Just a thought...

**Comment by veedubbs** [comment]
Oh!  Also, presumably the charts would only account for guest registrations that were verified.

**Comment by julsemaan** [comment]
It does sound nice to have.

Would be a good fit on the home dashboard as well

We could also have one that shows all the different sources that we used. The auth_log contains all that info
