### ISSUE TITLE
Wrong IPSET entries are being created for a DNS query for some bypassed domains

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#3417]
### Packetfence 8.1.0

For a setup with vlan-enforcement, some DNS queries coming to pfdns from the registration vlan are somehow being proxied to the upstream DNS and back to the client without the response being added to the proper ipset.

I was looking at #3396 and added some spew debugging as well as merged the patches suggested in the thread and I came to the following conclusion:

Actually, a different response is being added to the IPSET. And its the response coming from the "LocalResolver" method. Its response is being used to populate the IPSET filter but its never sent upstream. Instead, the pfdns plugin is let through to the next plugin (proxy, as specified in the pfdns.conf) which then issues another request, for the same domain, but the response might be different.

In my case in particular, since the domains I'm trying to whitelist are the google OAuth ones, the response is pretty much ALWAYS different. As such, the client will probably receive a DNS response that doesn't match what was installed in the IPSET.

I believe that for all the cases where we got an answer from the LocalResolver, we should populate the response record and not continue in the plugin chain (like it happens, for example, for the portal address)

**Comment by garci66** [comment]
I did a quick "fix" by using the response from the LocalResolver and it seems to be ok. I don't have a great knowledge of go or coredns / pfdns, but I think my change below seems to be workable:

```
        // Passthrough bypass
        for k, v := range pf.FqdnPort {
                if k.MatchString(state.QName()) {
                        answer, err := pf.LocalResolver(state)
                        fmt.Printf("[pid %d] about to spew answer\n", os.Getpid())
                        spew.Dump(answer)
                        if err != nil {
                                fmt.Println("Local resolver error with the following error" + err.Error())
                        } else {
                                for _, ans := range append(answer.Answer, answer.Extra...) {
                                        switch ansb := ans.(type) {
                                        case *dns.A:
                                                for _, valeur := range v {
                                                        if err := pf.SetPassthrough(ctx, "passthrough", ansb.A.String(), valeur, false); err != nil {
                                                                fmt.Println("Not able to contact Unified API to adjust passthroughs", err)
                                                        }
                                                }
                                        }
                                }
                                fmt.Printf("[pid %d] %s : %s passthrough - with direct local response\n", os.Getpid(), srcIP, mac)
                                w.WriteMsg(answer)
                                return 0, nil
                        }
                        fmt.Printf("[pid %d] %s : %s passthrough\n", os.Getpid(), srcIP, mac)
                        return pf.Next.ServeDNS(ctx, w, r)
                }
        }

```

(my Printf strings have os.Getpid since I was trying to correlate the output to what I was seeing in strace. I dont think they are needed now). I kept the proxy passthrough in case the LocalResolver would fail. Not sure what the ideal / correct option would be though. Probably fail towards the client as well.

**Comment by fdurand** [comment]
Yes it's a good idea, but just a note, if the LocalResolver fail then imo we should return the portal.

**Comment by julsemaan** [comment]
@fdurand 

I think if the resolve of the passthroughs fail it should return a DNS failure, not an unexpected DNS record

**Comment by garci66** [comment]
@julsemaan I agree returning the DNS failure is probably the best. Local resolver is returning a separate error code but not an error record ?

In either case, I don't think we should pass on to the proxy. 

The issue will probably be mitigated in larger deployments as more and more users login the ipset cache will be comprehensive enough that it covers most of the ips used by Google / Facebook -in my case I use this for oauth-. But out of correctness we should add to the ipset whatever we return in DNS and not something else.

**Comment by garci66** [comment]
Im proposing a PR with the discussed fixes to PFDNS. Im testing it on my system but seems to be ok so far.

**Comment by extrafu** [comment]
@fdurand and @julsemaan Should that go in the maintenance (for v.8.0) too?

**Comment by julsemaan** [comment]
I believe it should since its actually fixing a bug

I'll let @fdurand confirm before we put it in

**Comment by fdurand** [comment]
Pushed in maintenance
