### ISSUE TITLE
Installing packetfence VMware 5.5.0

### ISSUE THREAD

**Issue by hiranuk** [inverse-inc/packetfence#3418]
Hi 

I would like to install packetfence on VMware 5.5.0 i see that there is a "ZEN" version of install which is preconfigured. My question is the download is 1.3gb and once i install in on VMware is that it? or do i need to still configure more? the attached pdf is the setup guide, can anyone tell me "would i need to follow the guide from page 9 onwards" or would all of that be configured in this ZEN package?

Thanks

[PacketFence_Installation_Guide.pdf](https://github.com/inverse-inc/packetfence/files/2231544/PacketFence_Installation_Guide.pdf)

**Comment by nqb** [comment]
@hiranuk 

This bug tracker is for development issues only and confirmed bugs.

For general help please use the mailing list

**Comment by nqb** [comment]
gc
