### ISSUE TITLE
Issue with captive-portal not opening on Samsung 

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3419]
Its been a while we have complaints about the portal not opening automatically on Samsung devices.

After an intense debugging session, it was found that the Samsung devices check connectivitycheck.gstatic.com for the quality of the internet access. Now if they get a 302 out of this, they will consider the internet access to be inexistent and prevent any other action to be done on the wireless (including opening the captive portal). Although this is the absolute complete opposite of the Android doc.

When I added connectivitycheck.gstatic.com to the passthroughs, then, the device detected network access and opened the captive portal.

Other (non Samsung) Android devices were tested as well and were working with this passthrough so it seems like a valid solution.

Since passthroughs are only good for when PF performs the enforcement (DNS enforcement, registration, isolation, inline), then this won't work with web-auth unless the domain (or its IP) can be whitelisted.

Not sure how this can fit in our codebase

**Comment by julsemaan** [comment]
As an update, this has caused issues with other Android devices.

So an idea would be that we could have a feature where we would resolve connectivitycheck.gstatic.com as a passthrough only for devices manufactured by Samsung (OUI map). Using Fingerbank isn't really an option since we might not have seen DHCP or HTTP for this device.

It would be nice to use the DNS filters for this but from what I saw, they don't have access to the node_info nor to the MAC address of the device.

It would be nice to make it have access to the MAC and MAC vendor and then have this as a DNS filter

**Comment by IfesNV** [comment]
Hi julsemaan,

I was recommended to use the following DNS Filter and it has worked for me in Samsung smartphones better than adding "connectivitycheck.gstatic.com" to passthroughs, since it is now also working with HSTS-enabled websites.

[www_google_com]
filter = qname
operator = regex
value = www.google.com

[1:www_google_com]
scope = registration _**(Or dnsenforcement)**_
answer = $qname 30 IN A 127.0.0.1
rcode = NOERROR

When "connectivitycheck.gstatic.com" was added to passthroughs, there could be an issue where pages weren't being correctly redirected.

**Comment by julsemaan** [comment]
@IfesNV 

We've had internal discussions about exactly this.

In the case above, the "perfect" solution was to have connectivity.gstatic.com resolve correctly but only for Samsung devices. This passed thorough testing with most Android manufacturers after this logic was put in place.

And one downside of this DNS filter is that if people open http://www.google.com (in the case their device doesn't have popup capability), then this will create a connection error since it will point www.google.com to their local device.

**Comment by MuriloCalegari** [comment]
@julsemaan 

We've got PFsense in our environment and its Captive Portal works perfectly in any device. Maybe it is possible to replicate its mechanisms...

**Comment by julsemaan** [comment]
I was able to generate a DNS filter that resolves the name correctly only for Samsung OUI devices

Tested and it works correctly on a Samsung Galaxy A8 that had exactly this issue.

**Comment by MuriloCalegari** [comment]
Hi @julsemaan , how can we update our environment with this code?

**Comment by julsemaan** [comment]
Applying the maintenance beginning tomorrow, then performing a configreload and a full restart of the services

**Comment by MuriloCalegari** [comment]
Do I have to manually edit/create files just like your commit and then run update-samsung-dns-filter.sh? Or is there a command that performs the maintenance automatically?

**Comment by julsemaan** [comment]
Run:
```
# yum install git
# /usr/local/pf/addons/pf-maint.pl
```

**Comment by MuriloCalegari** [comment]
Hi @julsemaan,

I have some strong reasons to believe that scope = dnsenforcement might be broken. Is it possible that you take a look if it is working? I've tested with some other DNS filters and they won't work if scope = dnsenforcement, but they work if scope = inline (but that's not appropriate for all case scenarios).

We've got PacketFence in Inline mode.

**Comment by julsemaan** [comment]
I've pushed a DNS filter for the inline scope as well in devel and the 8.0/8.1 maintenance branches
