### ISSUE TITLE
Captive portal radius

### ISSUE THREAD

**Issue by hiranuk** [inverse-inc/packetfence#3420]
Hi
I have not got a reply from the mailing list so i am posing here. Im sorry but i would be very great full if anyone can help. I think i am close to achieving what i need, but just need to be pointed in the right direction on what to configure on packetfence or which chapter i should read on the user pdf user guide.

I have installed packetfence using the ZEN preconfigured version on VMware. Can anyone tell me what i need to configure as i don't think i need to configure everything that is shown on the pdf user guide.

Let me explain what i am trying to achieve.

I have a number of Draytek 2862Ln model firewall routers in various shops up and down the country. I want to configure a guest wifi on all those routers. the Draytek Routers has an option for "captive portal" and "MAC authentication".  The idea is if a customer goes to 1 shop and connects to the guest wifi on the draytek they will see a splash screen asking them to login using facebook or google and then they will have internet access. 

If they then went to another shop they would simply connect to the guest wifi and have internet access they would not need to enter their facebook or google details again as their MAC address of their wireless client will have been captured by Packetfence when they previously connected at the other shop.

I have attached screenshots of the Draytek Web GUI. I think i just need to enter the packet fence server IP and thats it.  The problem is what do i need to configure on Packetfence GUI.? captive portal ? or radius? or both?

Thanks in advance.

 Hiran

![2018-07-26 16_39_18-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43281194-f94f9cbc-910a-11e8-903a-ba2dd694097e.png)
![2018-07-26 16_39_36-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43281195-f972e442-910a-11e8-8f49-29ad123f70d2.png)
![2018-07-26 16_39_49-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43281196-f98cf332-910a-11e8-9965-dcce7da79a9c.png)
![2018-07-26 16_40_15-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43281197-f9ad4b96-910a-11e8-96dd-bd411cf0386e.png)
![2018-07-26 16_40_43-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43281198-f9ca2b8a-910a-11e8-8d6d-13eeff72b289.png)

**Comment by julsemaan** [comment]
The bug tracker is for development issues and confirmed bugs only.

If you need help for configuration, this goes in the mailing list.

If you need immediate help, then contact Inverse (http://inverse.ca/)
