### ISSUE TITLE
Can the unregdate field be searchable?

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#3424]
Use case is:

Our helpdesk is ran by students and I believe these helpdesk workers occasionally 'help out their bro' and either push the unregdate date out _far_ into the future or simply leave it blank so a device never unregisters.  This is fairly harmless, but still something I like to keep an eye on.  A couple of times a year I like to search for these oddities and fix them....and irritate the evil-doers!!  I currently search for this directly in the database.

Could the unregdate field searchable in the GUI....OR....put some tags on each Node screen showing the Admin user, action performed and time/date of the action?

Thanks!

**Comment by julsemaan** [comment]
I can't believe students would actually do this ;)

As for a solution, it would be to have a range search in the advanced search tab like for online and detection.

Not sure if this will be done in the current admin interface, but probably @satkunas can add it in the new admin while replicating the date search feature

**Comment by satkunas** [comment]
I've just finished implementing this in the new (alt) Admin > Report / Node / Unregistered (Active)

![screenshot from 2018-07-30 16-26-46](https://user-images.githubusercontent.com/3904468/43421785-bfe4f7fc-9415-11e8-892f-c8dd37992827.png)

**Comment by satkunas** [comment]
> Could the unregdate field searchable in the GUI....OR....put some tags on each Node screen showing the Admin user, action performed and time/date of the action?

It's currently not do-able in the nodes view, neither new or old admin. 

We will be extending the search criteria in the node view to include dates on some columns, depending on which criteria we think is most useful. Since it's now mentioned here it should make the cut :)

A historical/audit log on admin actions has been mentioned in the past, but it's currently not on our todo.
