### ISSUE TITLE
pf-maint.pl doesn't take *_proxy environment variables into account

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3425]
As title says.

Steps to reproduce:
```console
# export http_proxy=http://1.1.1.1:3142
# export https_proxy=http://1.1.1.1:3142

# with use Data::Dumper; print Dumper($ua); at line 217
# ./pf-maint.pl 
[..]
'no_proxy' => [],
[..]
'proxy' => {
             'http' => 'http://1.1.1.1:3142',
             'https' => 'http://1.1.1.1:3142'
},
[..]

# yum info perl-libwww-perl.noarch 
[..]
Version     : 6.07
Release     : 4.2
[..]
From repo   : packetfence

```
I didn't see any traffic going to 1.1.1.1 on port 3142.

https://metacpan.org/pod/release/MSCHILLI/libwww-perl-6.07/lib/LWP/UserAgent.pm#Proxy-attributes

**Comment by julsemaan** [comment]
I think its just a matter of installing a lib.

@fdurand knows which since I believe he has a recipe to do the maintenance through a socks proxy

**Comment by nqb** [comment]
@julsemaan 

I think you are right. On Debian 8, I see traffic going to 1.1.1.1 on port 3142.

On Debian, we use libwww-perl 6.08.1 provided by Debian official repos.

**Comment by nqb** [comment]
On CentOS, if I downgrade to `perl-libwww-perl-6.05-2.el7.noarch` (CentOS official repos), I see traffic going to 1.1.1.1 port 3142.

**Comment by nqb** [comment]
LWP package on CentOS 7 (6.07) doesn't use CONNECT method when dealing with HTTPS sites. Not the case in Debian with LWP package 6.08.

By adding this to `pf-maint.pl`:
```
# to use SSL with proxy
$ENV{PERL_NET_HTTPS_SSL_SOCKET_CLASS} = "Net::SSL";
$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0;
```
It works on both distros.

**Comment by nqb** [comment]
Only: `$ENV{PERL_NET_HTTPS_SSL_SOCKET_CLASS} = "Net::SSL";` is necessary.

See https://metacpan.org/pod/Net::HTTPS#ENVIRONMENT for that topic.

**Comment by julsemaan** [comment]
I couldn't get it to use the proxy until I downgraded perl-libwww-perl-6.05-2.el7

So #3857 should take care of this

**Comment by nqb** [comment]
Workaround for a one shot:
```
HTTPS_PROXY=http://pf.domain.lan:80 \
HTTP_PROXY=http://pf.domain.lan:80 \
PERL_NET_HTTPS_SSL_SOCKET_CLASS='Net::SSL' \
PERL_LWP_SSL_VERIFY_HOSTNAME=0 \
pf-maint.pl
```

**Comment by julsemaan** [comment]
Zammit got an issue with this today on 10.2 and had to use @nqb's workaround. I will need to investigate what happened

**Comment by julsemaan** [comment]
Issue was between the keyboard and the chair
