### ISSUE TITLE
is packetfence a centralised server software?

### ISSUE THREAD

**Issue by hiranuk** [inverse-inc/packetfence#3427]
Hi

I have a quick question please. If i have 10 shops 1 of them is a Head office the other 9 are client shops. All 10 of them have a Draytek Router that allow radius MAC authentication for guest wifi. They have a field that state "external captive portal IP". Can anyone tell me is packetfecne a centralised server software wherby it would only need to be installed at head office and then client sites would simple talk to it? or do all the client sites also need to have packetfecnet installed on a machine?.

**Comment by julsemaan** [comment]
This bug tracker is for **bugs** and tracking development issues, **not** for q&a and configuration questions.
