### ISSUE TITLE
Can't locate object method "starttls" via package "MIME::Lite::SMTP"

### ISSUE THREAD

**Issue by MiCRoPhoBIC** [inverse-inc/packetfence#3430]
Fresh install of PF 8.1 in Debian 8.
I have configured for e-mail alerting external SMTP server (to port 587) with STARTTLS option enabled,  and I'm not receiving e-mails. The error in the log is: 

`Jul 31 13:16:33 hostname packetfence_httpd.webservices: httpd.webservices(20070) ERROR: [mac:xx:xx:xx:b5:c8:xx] Can't send email to 'xxxxx.xxxxxxx@xxxxxxx.xxx' :'Can't locate object method "starttls" via package "MIME::Lite::SMTP" at /usr/local/pf/lib/pf/config/util.pm line 553.' (pf::config::util::send_mime_lite)`

**Comment by nqb** [comment]
On CentOS 7 or Debian 8, I didn't see any `starttls` method in `MIME::Lite::SMTP` package or in `MIME::Lite` package.

I think this method is part of `Net::SMTP` package.

**Comment by nqb** [comment]
This issue seems to be still presents in 9.0.1 but we lost logs maybe due to new API call.

**Comment by nqb** [comment]
@jrouzierinverse,

I'm not able to send an email using StartTLS method on PacketFence v12.
If I configured Alerting section like this:

```
[alerting]
smtpserver=mail.example.com
smtp_encryption=starttls
smtp_username=USER
smtp_password=PASSWORD
smtp_verifyssl=disabled
```

Before I installed `libauthen-sasl-cyrus-perl` on Debian 11, I got this error:

```
Can't send email to 'REDACTED' :'No SASL mechanism found at /usr/share/perl5/Authen/SASL.pm line 77.
```

Once package is installed, I got this error:

```console
# perl -I/usr/local/pf/lib_perl/lib/perl5 -I/usr/local/pf/lib -Mpf::config::util -e "pf::config::util::send_email('guest_local_account_creation', 'nqb@foo.fr', 'Subject', {'Test'}, {})"
' (pf::config::util::send_mime_lite)[1530800]: pfqueue(1530800) ERROR: [mac:unknown] Can't send email to 'REDACTED' :'SMTP auth() command failed: No such file or directorymail.example.com Hello [172.30.12.7]
```

**Comment by jrouzierinverse** [comment]
This seemed to be a configuration issue on the email server.
Can you provide me access to the machine?

**Comment by jrouzierinverse** [comment]
This is a library issue we should install Authen::SASL::XS or force the use of the Authen::SASL::PERL I will look into which would be the best option.

**Comment by nqb** [comment]
It looks like `libauthen-sasl-cyrus-perl` was causing the issue. After removal and restart of `pfqueue`, it started to work again.

I'm not able to figure out why I got `No SASL mechanism found at /usr/share/perl5/Authen/SASL.pm line 77.` at some point but I'm sure `libauthen-sasl-cyrus-perl` was not installed at that time. Perhaps it was necessary to restart `pfqueue`.

I'm closing this issue for now and I will reopen if this weird behavior appears again.
