### ISSUE TITLE
Can't restart services from the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3439]
As reported by a user, if we restart all the services via the admin GUI, then it just kills the services and never comes back.

Still need to replicate it in lab, no errors in the logs.

**Comment by MiCRoPhoBIC** [comment]
I observed the same behavior, so I started to restart them only from the console.

**Comment by julsemaan** [comment]
Issue is actually that the pfcmd process is spawned in the same control-group as the httpd.admin processes and then when systemd stop the service unit, it kills all the processes of that control-group including pfcmd, will need to adjust the behavior of the httpd.admin unit file

**Comment by julsemaan** [comment]
This is fixed in devel, cherry-picked it in the maintenance for eventual packaging of 8.1.1

In order to get the fix right now, follow the following instructions:
```
# cd /usr/local/pf
# curl https://raw.githubusercontent.com/inverse-inc/packetfence/da06ce86eca57e06fcd2b11e4a35a55eb7617586/conf/systemd/packetfence-httpd.admin.service > /usr/lib/systemd/system/packetfence-httpd.admin.service
# systemctl daemon-reload
```
