### ISSUE TITLE
Create Nodes HTTP error - unable to manually create nodes

### ISSUE THREAD

**Issue by abgoble** [inverse-inc/packetfence#3440]
Packetfence 8.1.0 (Upgraded from a fresh install of 8.0.1)
3 Server Active-Active Cluster (CENTOS)

When the 'Create' link on the Nodes Tab is clicked in the web GUI, an "Error! An error occured while contacting the server. Please try again later." occurs for admin  and node-manager users.

httpd.admin.log:Aug  6 11:01:22 iso-gate-01 httpd_admin: httpd.admin(6313) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->create "Can't locate object method "roles" via package "pfappserver::Form::Node::Create::Import" at /usr/local/pf/lib/pfappserver/Form/Node/Create/Import.pm line 123." (pfappserver::PacketFence::Controller::Root::end)

httpd.admin.access:Aug  6 11:01:22 iso-gate-01 httpd_admin_access: 144.38.xx.xx - - [06/Aug/2018:11:01:22 -0600] "GET /node/create?_=1533571084056 HTTP/1.1" 500 2125 620 198028 "https://gate.dixie.edu:1443/admin/nodes" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36" "gate.dixie.edu:1443"

**Comment by satkunas** [comment]
It's possible that it was already fixed in this commit: https://github.com/inverse-inc/packetfence/commit/0e6dc7e25d975aa840375b42b7fea143b784cbe0

See the addition on line 15

**Comment by abgoble** [comment]
Yes, that fixed it.
