### ISSUE TITLE
Prevent haproxy emergency syslog messages

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3442]
When haproxy cannot find a backend it logs emergency messages which end up in all the opened sessions.

This can be alarming for an admin restarting services while it shouldn't be.

Sample of message:
```
Message from syslogd@portal at Aug  7 08:23:43 ...
 haproxy[24439]:backend 10.10.3.3-backend has no server available!
```

We should have this log only to file

**Comment by nqb** [comment]
+1
