### ISSUE TITLE
Put api-fronted.access log in the same compress routine as other logs

### ISSUE THREAD

**Issue by IfesNV** [inverse-inc/packetfence#3444]
We've made a system that is constantly using PacketFence API. For now, the api-frontend.acess logs in /pf/logs already has more than 400,000 lines (and increasing), resulting in a 70 MB+ file that is not being compressed as other logs. Could become an issue where the system runs out of space.

**Comment by julsemaan** [comment]
According to the [syslog config](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/constants/syslog.pm#L91), the log lines should be put in /usr/local/pf/logs/httpd.api-frontend.access, then in our [logrotate configuration](https://github.com/inverse-inc/packetfence/blob/devel/packetfence.logrotate#L20), its rotating them daily and performing compression.

**Comment by julsemaan** [comment]
I'm guessing this was an old 8.0 issue since we've reworked the syslog config since then in 8.1 and addressed it in the maintenance branch as well.

I'll close this
