### ISSUE TITLE
802.1x Autoreg: We can not put the Max node per user to 1

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3446]
If I put the Max node per user to 1 it says it already registered but if I put it to 2 it works.

In Mac authentication, it allows the users to register two devices.

**Comment by julsemaan** [comment]
I'm not sure I properly understand the issue.

Does putting it to 1 makes it so you can register 2 devices in MAC auth?

**Comment by fdurand** [comment]
Let's say you set 1 in the role, then the first connection will be ok but on the second one PacketFence check how many devices are reg for the pid and it return 1.
In the code the test is 1 < 1 so it return false.
So to fix it you need to set 2 if you want to make it work.

```
            $nb_nodes = node_pid($pid, $category_info->{'category_id'});
            $max_for_category = $category_info->{'max_nodes_per_pid'};
            if ( $max_for_category == 0 || $nb_nodes < $max_for_category ) {
                return $FALSE;
            }
```

**Comment by julsemaan** [comment]
I don't think that would be the right way to go.

The current code expects that the device is unregistered and that you're requesting to get a slot in the available devices to register.

Now the autoreg via 802.1x should first see if the device is already registered, if it is, then it shouldn't try to check is max nodes reached. If its not registered, then it should call is max node reached to try to get one of the available slots
