### ISSUE TITLE
[security] domain join: logs contain clear-text credentials

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3448]
When you declare a new Active Directory Domain in PacketFence's config and try to join it, on CentOS 7, you can see clear-text credentials used in `/var/log/secure`.

**Comment by julsemaan** [comment]
@nqb 

You can look at this if you have time

**Comment by nqb** [comment]
Related to the use of `sudo`: all commands run by `pf` through `sudo` appeared in `/var/log/secure`
