### ISSUE TITLE
Disable SSLv3 on web servers for POODLE

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#345]
[This is a copy of issue 0001866 in mantis] 
Ref: http://packetfence.org/bugs/view.php?id=1866

SSLv3 is enabled by default in Apache config files. Not a best common practice with POODLE on the loose.

SSLv3 is being deprecated by all vendors as it is unfixable.
We should remove support for it. 
Our default install should strive for security by default when practical. If the PF admin wants SSLv2 he should enable it.

**Comment by dwlfrth** [comment]
See PR https://github.com/inverse-inc/packetfence/pull/344 for resolution

**Comment by louismunro** [comment]
Ready for testing, reassigning to whitx.

**Comment by whitx** [comment]
I didn't encounter any strange behavior, tried to connect to portal/admin with 5 differents browsers(IE, FF, Chrom, Opera, Safari). Concerning proxy passtrough, I add them but it didn't go through, it just bring me to the captive portal login page.

**Comment by louismunro** [comment]
Please configure a proxy passthrough and test that the passthrough works.

**Comment by whitx** [comment]
Tested with passthrough/proxy_passthrough, expected behavior
