### ISSUE TITLE
etcd: lack of documentation for detecting + resolving split-brains

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3451]
In some cases, the etcd clusters can have issues where they are in split brains.

We should document the cases where they can be in split-brains and also how to resolve it

**Comment by julsemaan** [comment]
How I currently resolve the split brains:
```
On all servers
# systemctl stop packetfence-etcd

Then, on all servers again
# rm -fr /usr/local/pf/var/etcd/*

All servers again start fresh at the same time
# systemctl start packetfence-etcd
```

**Comment by nqb** [comment]
@julsemaan : you can use `feature/doc-cluster` branch and edit PR #3383

**Comment by julsemaan** [comment]
I think @fdurand was reconsidering the usage of etcd so this might never hit the official doc.

Wanted at least to document it in an issue

Time will tell if we need to put this in the docs

**Comment by jrouzierinverse** [comment]
To avoid using the wrong wording in the documentation for etcd.

There are no 'split brains' in etcd (in PacketFence yes but not etcd).
However there could however be a network partition.
Which should be resolved automatically one the network partition is fixed.
Your current procedure is what etcd recommends for a 'Failure during bootstrapping'

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/failures.md

**Comment by julsemaan** [comment]
we've dropped etcd
