### ISSUE TITLE
Permission denied: exec of '/usr/local/pf/html/parking/cgi-bin/release.pl' failed

### ISSUE THREAD

**Issue by MiCRoPhoBIC** [inverse-inc/packetfence#3460]
Debian 8, new PF 8.1 installation:

httpd.parking.error:

`Aug 13 12:29:40 hostname httpd_parking_err: [Mon Aug 13 12:29:40.229609 2018] [cgi:error] [pid 4257] [client 10.xx.xx.xx:50651] AH01215: (13)Permission denied: exec of '/usr/local/pf/html/parking/cgi-bin/release.pl' failed, referer: http://www.msftconnecttest.com/index.html
`
Execute permissions are missing for some of the .pl files ?

```
ls -alh /usr/local/pf/html/parking/cgi-bin/release.pl
-rw-r--r-- 1 pf pf 1.3K Jul  9 22:53 /usr/local/pf/html/parking/cgi-bin/release.pl
```

```
 ls -lahR /usr/local/pf/html|grep .pl$
-rw-r--r-- 1 pf pf  455 Jul  9 22:53 captive_portal_cgi.pl
-rw-r--r-- 1 pf pf 1.7K Jul  9 22:53 captive_portal_create.pl
-rw-r--r-- 1 pf pf 1.3K Jul  9 22:53 captive_portal_fastcgi.pl
-rw-r--r-- 1 pf pf 1.8K Jul  9 22:53 captive_portal_server.pl
-rw-r--r-- 1 pf pf  704 Jul  9 22:53 captive_portal_test.pl
-rw-r--r-- 1 pf pf 1.3K Jul  9 22:53 release.pl
-rwxr-xr-x 1 pf pf  450 Jul  9 22:53 pfappserver_cgi.pl
-rwxr-xr-x 1 pf pf 1.7K Jul  9 22:53 pfappserver_create.pl
-rwxr-xr-x 1 pf pf 1.2K Jul  9 22:53 pfappserver_fastcgi.pl
-rwxr-xr-x 1 pf pf 1.8K Jul  9 22:53 pfappserver_server.pl
-rwxr-xr-x 1 pf pf  690 Jul  9 22:53 pfappserver_test.pl
```

**Comment by julsemaan** [comment]
I'll look into this

**Comment by julsemaan** [comment]
It seems the debian packaging lacks what is needed to make this file executable.

PacketFence 8.1 on CentOS 7 works fine

Will see how to fix the Debian packaging with @fdurand

**Comment by MiCRoPhoBIC** [comment]
What about the others .pl script (captive_portal*) ?
Shouldn't they also have +x flags ?

**Comment by julsemaan** [comment]
These are there mainly for development purposes in CLI, so having to call them with "perl whatever.pl" is fine for those.

I've also cherry-picked this in maintenance/8.1 for an eventual 8.1.1
