### ISSUE TITLE
NODE import problem in 8.1.0 by Import.pm

### ISSUE THREAD

**Issue by ag-guvenlik** [inverse-inc/packetfence#3467]
/chroots/MyDOMAIN/usr/local/pf/html/pfappserver/lib/pfappserver/Form/Node/Create/Import.pm

in 8.1.0 version, in the above file there is not any line below(But there is in 8.0.1 in line 20):
 "# Form select options
has 'roles' => ( is => 'ro' );"

For this reason import page can not be displayed, when you add  this line and reboot  than import pages works properly.

**Comment by julsemaan** [comment]
This was already fixed in the maintenance branch

**Comment by julsemaan** [comment]
Actually, I may be wrong, its been a few times this issue has been raised, but seems like 132918394c8062a452b5a843be5a81667636d8ce hasn't been put into maintenance/8.0

@jrouzierinverse can you see if this is relevant or not for maintenance/8.0 ?

**Comment by jrouzierinverse** [comment]
Not relevent
