### ISSUE TITLE
LC_CTYPE breaks installation on debian/ubuntu

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#347]
Seen with a client, LC_CTYPE=en_US.UTF-8 breaks installation because the post install script tries to access the following files: 

/usr/share/locale/en_US.UTF-8/LC_MESSAGES/coreutils.mo
/usr/share/locale/en_US.utf8/LC_MESSAGES/coreutils.mo
/usr/share/locale/en_US/LC_MESSAGES/coreutils.m
/usr/share/locale/en.UTF-8/LC_MESSAGES/coreutils.mo
/usr/share/locale/en.utf8/LC_MESSAGES/coreutils.mo
/usr/share/locale/en/LC_MESSAGES/coreutils.mo
/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo
/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo
/usr/share/locale/en_US/LC_MESSAGES/libc.mo
/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo
/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo
/usr/share/locale/en/LC_MESSAGES/libc.mo

Perhaps we should temporarily override the LC_CTYPE in the post install script (i.e. LC_CTYPE=C)?

**Comment by julsemaan** [comment]
Should be assigned to 4.7 IMO

**Comment by cgx** [comment]
@louismunro: on which distro? Maybe it's simply a matter of automating the installation of the locale?

**Comment by louismunro** [comment]
Wouldn't we end up having to support installing all locales?
This was on Debian 7.

**Comment by cgx** [comment]
I don't think so. Try running `dpkg-reconfigure locales`.

**Comment by whitx** [comment]
Tried to install PF-devel on debian 7, with/without exporting the local LC_CTYPE=en_US.UTF-8, installation ended up correctly with an access to the configurator.
