### ISSUE TITLE
802.1x autoreg doesn't seem to populate portal and source of person

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3471]
When doing 802.1x autoreg, the portal (connection profile) and source attribute used to be updated.

Seems its not anymore

**Comment by julsemaan** [comment]
Seems this is an 8.1 only issue as getRegisteredRole doesn't compute roles for EAP connections after this commit:

https://github.com/inverse-inc/packetfence/commit/c709f5ab6fa06b2268f032d0d8b2fc23bcc2b20a#diff-a3043573fe42ea7beff2d06e06915d8cR418

**Comment by julsemaan** [comment]
@nqb 

Can you test the patch on the problematic setup and report the result here.

If its working fine, then we'll put that in the maintenance

**Comment by nqb** [comment]
@julsemaan : it works as expected !
