### ISSUE TITLE
ZEN-USB not available any more for 8.1.0 ?

### ISSUE THREAD

**Issue by f1iqf** [inverse-inc/packetfence#3478]
Hi,

The ZEN USB link from https://packetfence.org/download.html#/zen is 404.
Only the OVF is available for 8.1.0
Could not find it on sourceforge either.

What is the correct link ? Or was it discontinued ?

Thank you very much in advance,
Nicolas

**Comment by fdurand** [comment]
The file has been uploaded on sourceforge. https://sourceforge.net/projects/packetfence/files/PacketFence%20ZEN/8.1.0/
