### ISSUE TITLE
Adding ip4log.ip field to node search in API results in unoptimized query

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3480]
If we add the ip4log.ip field to a node search in the API, then it performs a join where the condition is a subselect resulting in an almost 
Results in the following select:
```
SELECT `node`.`mac`, `node`.`computername`, `ip4log`.`ip` AS `ip4log.ip`, `node`.`device_class`, `node`.`device_type` FROM node LEFT OUTER JOIN ip4log ON ( `ip4log`.`ip` = ( SELECT `ip` FROM `ip4log` WHERE `mac` = `node`.`mac` AND `tenant_id` = `node`.`tenant_id`  ORDER BY `start_time` DESC LIMIT 1 ) ) LIMIT 101 OFFSET 0;
```

We need to optimize this query so it can run on DBs with at least half a million nodes

**Comment by julsemaan** [comment]
I chatted with @satkunas about the issue as well, he will provide input.

My personal idea for now would be to split this into 2 queries, one to find the nodes and its attributes, the second to populate the ip4log.ip field for the 100 rows that we'll find.

But I'm sure there is some special SQL stuff we could do to keep this in a single query.

**Comment by julsemaan** [comment]
with @satkunas we got the following query which seems to provide the same results

```
SELECT   node.mac,  node.computername,  ip4log.ip,  node.device_class,  node.device_type FROM node LEFT JOIN (  SELECT   *  FROM ip4log  WHERE tenant_id=1  ORDER BY start_time DESC  LIMIT 18446744073709551615 ) AS ip4log ON (node.mac = ip4log.mac AND node.tenant_id=1) where node.mac="34:23:ba:37:19:81" GROUP BY ip4log.mac;
```

**Comment by jrouzierinverse** [comment]
Found the issue with the join we had similar issue in the admin node page it never got ported over to the api.

Will fix in devel and maint

```sql
SELECT `node`.`mac`,
       `node`.`computername`,
       `ip4log`.`ip` AS `ip4log.ip`,
       `node`.`device_class`,
       `node`.`device_type`
FROM node
LEFT OUTER JOIN ip4log ON (`ip4log`.`ip` =
                             (SELECT `ip`
                              FROM `ip4log`
                              WHERE `mac` = `node`.`mac`
                                AND `tenant_id` = `node`.`tenant_id`
                              ORDER BY `start_time` DESC
                              LIMIT 1) AND
                            `ip4log`.`tenant_id` = `node`.`tenant_id`
                            )
LIMIT 101
OFFSET 0;
```

**Comment by MuriloCalegari** [comment]
Hi,

We're very heavy users of PacketFence's GET Node API, will this change the answer for the query at all? 

Regards,

Murilo Calegari de Souza

**Comment by jrouzierinverse** [comment]
No this was an issue where adding a constraint allowed the correct index 
to be used.
