### ISSUE TITLE
Fresh Debian 8 install : web configurator errors

### ISSUE THREAD

**Issue by f1iqf** [inverse-inc/packetfence#3481]
Hello :)
After a fresh packetfence 8.1 install on debian 8, the web configurator was throwing errors at anything done using the GUI.

In httpd.admin.log:
httpd_admin: httpd.admin(4794) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::Roles->create "Cannot open /usr/local/pf/logs/httpd.admin.audit.log  at /usr/local/pf/lib/pfappserver/Model/Audit.pm line 45." (pfappserver::PacketFence::Controller::Root::end)

A quick investigation let to see that the file /usr/local/pf/logs/httpd.admin.audit.log was missing, and it had to be created manualy (with the pf/pf rights) for the web gui to work.

Not a big problem, but might need to be addressed in a future patch for the interface to be able to create the file if missing.

Best regards,
Nicolas

**Comment by MiCRoPhoBIC** [comment]
Most probably the same issue as: #3469 and/or #3216

**Comment by julsemaan** [comment]
@MiCRoPhoBIC is correct, closing the issue, refer to #3469 for resolution
