### ISSUE TITLE
Optimize the VoIP detection using SNMP

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3486]
Currently, if a device isn't considered a phone, we will poll the switch using SNMP everytime that device connects until its detected as a phone (which will never happen for workstations).

This makes us extremely dependent to SNMP at all times.

An idea me and @fdurand have brainstormed is that for every successful lookup in the CDP/LLDP tables, we cache the result (success or failure) for 24 hours (or more) so that we do not constantly poll the switch for devices we haven't detected as a phone. The cache key would be "$switch_ip-$ifIndex-$mac" to take into account movement to another switch or switchport where CDP would be enabled (but not in the first port).

**Comment by satkunas** [comment]
MySQL supports `CREATE EVENT` since 8.0. This can be used to automatically expire records without the need for external polling.

https://dev.mysql.com/doc/refman/8.0/en/create-event.html

```sql
alter table radcheck add column ts_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE EVENT expireuser
ON SCHEDULE EVERY 12 HOUR
DO
DELETE FROM radcheck 
WHERE TIMESTAMPDIFF(DAY, ts_create , NOW()) > 7
;
```

```sql
SET GLOBAL event_scheduler = ON; 
```

**Comment by julsemaan** [comment]
We already have a switch scoped cache that is distributed using CHI and MySQL so I'm not sure we'd really need to introduce a new recipe for that

**Comment by jrouzierinverse** [comment]
Should the cache expiration time be configurable per switch or the global value in chi.conf?

**Comment by julsemaan** [comment]
Global value of chi.conf should be fine for the first iteration.
