### ISSUE TITLE
Amazon IoT devices causing unnecessary load on PF

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3487]
Just had an issue in some large student environment where people are coming in with a lot of Amazon IoT devices (Alexa stuff, Fire TV stick, etc).

These devices perform non-stop "GET /kindle-wifi/wifistub.html" without ever stopping causing high load on haproxy and causing a lot of traffic (and system interrupts).

The following VLAN filter denies Amazon devices on the registration network:
```
[amazon_devices]
filter = fingerbank_info.device_name
operator = fingerbank::device_is_a
value = 15664

[deny_unreg_firetv:amazon_devices]
scope = RegistrationRole
role = REJECT
```

We'll have to see if we ship this as a best practice or in our defaults, most of the Amazon devices don't have a browser to view the portal anyway

**Comment by satkunas** [comment]
This appears to be a wifi probe.

http://www.mobileread.mobi/forums/showthread.php?t=237799#8

Perhaps hosting `81ce4465-7167-4dcb-835b-dcc9e44c112a ` locally (non-SSL) would alleviate the load and still allow Kindle and Amazon devices to connect?
