### ISSUE TITLE
LDAP bind error : add more explicit output

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3496]
As discussed with @julsemaan, sometimes, when there is a little bit of LDAP trafic and a new authentication against an LDAP/AD source is made, you can see this output in `packetfence.log`:
```
Aug 14 14:43:39 pf02 packetfence_httpd.aaa: httpd.aaa(1938) ERROR: [mac:11:11:11:11:11:11] Error binding 'Connection reset by peer' (pf::LDAP::bind)
Aug 14 15:02:38 pf02 packetfence_httpd.aaa: httpd.aaa(1938) ERROR: [mac:11:11:11:11:11:11] Error binding 'Connection reset by peer' (pf::LDAP::bind)                                                                            
```
But LDAP authentication is working. That behavior is caused by a timeout of an old LDAP connection, replaced by a new LDAP connection.

For unaware admins, this can lead to misunderstanding. Julien's proposal:
- set error level to WARN in place of ERROR
- write one log line before and after this message to say that a new connection will be made

**Comment by jrouzierinverse** [comment]
Will take care of it.
