### ISSUE TITLE
roles : add default value for "Max nodes per user"

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3497]
Currently, when you create a new role, you have to specify two mandatory fields:
- Name
- Max nodes per user

Most of the time, admins will use 0 as value for "Max nodes per user" which means unlimited nodes per user.

My proposal:
- set 0 as default value for "Max nodes per user"
- improve help message for that option:
  - currently: "The maximum number of nodes a user having this role can register."
  - proposal: "The maximum number of nodes a user having this role can register. A number of 0 means unlimited number of devices."

**Comment by julsemaan** [comment]
@nqb 

You can look at this if you have time

**Comment by jrouzierinverse** [comment]
Fixed by 0ec4ba92ee0c7c3b9d8f7d3758fc2ba7e545e8d4
