### ISSUE TITLE
monit : started by pfcmd

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3499]
I notice that when using `pfcmd service pf stop` with `monit` stopped, `monit` will be start.

Steps to reproduce:
- `systemctl stop monit`
- `pfcmd service pf stop`
- `systemctl status monit` : monit has started

I didn't find any relevant information on systemd logs:
- `journalctl -b`
- `systemctl status monit`
- `systemd-cgls`

As discussed with @julsemaan, that issue is caused by `monit`'s systemd depends. It depends from `multi-user.target`. We need to change the way `monit` is managed by `systemd`,

**Comment by nqb** [comment]
Possible workaround: disable `monit` before shutting down `pf`

**Comment by julsemaan** [comment]
We need to brainstorm on how we're going to handle this

**Comment by fdurand** [comment]
I am not able to replicate it.
Can you give the result of : systemctl get-default

**Comment by julsemaan** [comment]
This isn't relevant anymore since we integrated monit directly in PF
