### ISSUE TITLE
PF8.1 : modified email account_creation template not used

### ISSUE THREAD

**Issue by Grisambre** [inverse-inc/packetfence#3503]
Hi :)

This is not an urgent problem... Using PF8.1 on Debian 8.11.

I am using a captive portal "default" for which I customized of 3 files, using the web GUI : 
emails/emails-guest_local_account_creation.html
aup_text.html
layout.html

The files I modified where stored by PF in html/captive-portal/profile-templates/default
aup_text.html and layout are actualy used by the system ; however, when sending an activation email (Twilio source), the new one is not used, only the one in "html/captive-portal/templates". If I modify this template however (in the template folder), it is sent to the new users.

So it appears the custom emails/emails-guest_local_account_creation.html is never used even if present (and created by the web gui). Linux file rights seem identical to the other modified files, despite "Preview" mode beeing fine from the GUI.

Thank you in advance !
Nicolas

**Comment by extrafu** [comment]
Still relevant?

**Comment by jrouzierinverse** [comment]
Yes still relevant.

**Comment by jrouzierinverse** [comment]
Fixed by e198bc149b349b6d0eea76c1b71008e58292f41a.
