### ISSUE TITLE
Translate port ID on Info page

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#3504]
Currently, on the **Info** tab the port shows the generic SNMP number:

![info-port](https://user-images.githubusercontent.com/382007/44561394-3da4d100-a71a-11e8-870e-eca78c31e4aa.PNG)

But on the **Location** tab, it shows the more useful (actual) port number:

![location-port](https://user-images.githubusercontent.com/382007/44561397-42698500-a71a-11e8-94db-79fbe10f24e3.PNG)

Can the **Info** tab show the actual port number as well?

**Comment by nqb** [comment]
Hello @veedubbs, what switch/AP module do you use ? Is it specific to that switch/AP module ?

**Comment by veedubbs** [comment]
@nqb This specific switch is using the HP::Procurve_5400 switch module.  As it truly is a 5400 model, I went ahead and changed the switch type to Aruba::5400 as a test, and the problem still exists (I'm not sure if I had to refresh anything after doing so...(I didn't)).

Does that help?  Or do you need more detail?

**Comment by julsemaan** [comment]
Its actually because we only show the ifIndex column in the info tab but we show the ifDesc as well in the location tab.

Easy to add, probably just laziness from the person who coded the feature. I know that, because its me :)

**Comment by julsemaan** [comment]
@nqb 

You can look at this if you have time

**Comment by julsemaan** [comment]
After looking into it, it seems that the description is displayed in the node view summary in the latest release.

Is this still an issue on your deployment ? Otherwise I'll close this.

**Comment by veedubbs** [comment]
It is no longer an issue in my environment.  Thanks!
