### ISSUE TITLE
Backslash in usernames in Reports section is shown as "=5C"

### ISSUE THREAD

**Issue by MiCRoPhoBIC** [inverse-inc/packetfence#3508]
In the following reports:
Top Authentication Failures
Top Authentication Successes

Authenticated wired 802.1x domain users (DOMAIN\user.name) and local computer users (.\administrator) are displayed with "=5C" instead of backslash in front of their username. Following the username link also doesn't work because the username in the link is also not correct (in Users sections they are correct - DOMAIN\user.name )

Attaching a screenshot of the issue: 

![slash](https://user-images.githubusercontent.com/4729402/44615565-81482980-a845-11e8-9576-f9f9d78da713.png)

**Comment by julsemaan** [comment]
We'd have to see how its unescaped in the RADIUS audit log section since I believe this report uses the data in RADIUS audit log.

I believe @satkunas did those reports so he's probably the best fit to fix this.

**Comment by MiCRoPhoBIC** [comment]
With raddebug I see the following:
(233) Fri Aug 24 09:45:39 2018: Debug:   User-Name = "DOMAIN\\firstname.lastname"

I don't know if that helps?

**Comment by julsemaan** [comment]
This issue was fixed by @satkunas but requires a schema change so that won't be available before the 8.2 release

@MiCRoPhoBIC

If you want the bugfix immediately, you'd need to install the following stored proc:
https://github.com/inverse-inc/packetfence/pull/3510/files#diff-9a3daa21c2b9052d5f85954a88f0592cR1271

And then adjust the reports here:
https://github.com/inverse-inc/packetfence/pull/3510/files#diff-5b83df05b5fc926c6a55756bb7babbdcR415

**Comment by MiCRoPhoBIC** [comment]
Hi, I just realized that in my previous post 

> (233) Fri Aug 24 09:45:39 2018: Debug: User-Name = "DOMAIN\firstname.lastname"

the backslash after "DOMAIN" is only one, while originally in my debug log there were two:
 'DOMAIN\ \firstname.lastname' . I guess github  removed the first one thinking it is an 'escape'. In my current post I'm putting a whitespace between the two backslashes, so it wont be striped again. I'm afraid this may  affect the fix for the issue? :-(

**Comment by julsemaan** [comment]
It shouldn't affect the issue @satkunas has resolved since he made it so all FreeRADIUS encoded characters would be adjusted whether its simple backslash, double, triple, a new line or whatever FreeRADIUS encodes

**Comment by MiCRoPhoBIC** [comment]
Phew. Great! Thanks!
