### ISSUE TITLE
Date range breaks search in nodes.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#351]
Searching for nodes with a specific date range in nodes throws up an 
“An error occured while contacting the server” in the admin.

The generated query is invalid because it refers to a table in the "where" that is not in the "from" clause.

E.g. 
SELECT 
    COUNT(*) as count
FROM
    `node`
        LEFT JOIN
    `node_category` ON `node_category`.`category_id` = `node`.`category_id`
        LEFT JOIN
    `dhcp_fingerprint` ON `dhcp_fingerprint`.`fingerprint` = `node`.`dhcp_fingerprint`
        LEFT JOIN
    `iplog` ON `iplog`.`mac` = `node`.`mac`
        AND (`iplog`.`end_time` = '0000-00-00 00:00:00'
        OR `iplog`.`end_time` > NOW ())
        LEFT JOIN
    `os_type` USING (`os_id`)
        LEFT JOIN
    (select DISTINCT
        mac, switch
    from
        locationlog) as locationlog_distinct ON `locationlog_distinct`.`mac` = `node`.`mac`

WHERE
    (`node`.`mac` LIKE '%95:f4')
        and `locationlog`.`start_time` >= '2015-01-17'
        and (`locationlog`.`end_time` <= '2015-02-16'
        or `locationlog`.`end_time` IS NULL)

Will cause an error:  "ERROR 1054 (42S22): Unknown column 'locationlog.start_time' in 'where clause'.

**Comment by jrouzierinverse** [comment]
Fixed in pull request #394

**Comment by louismunro** [comment]
Confirmed as fixed.
