### ISSUE TITLE
Should git should be a dependency?

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3511]
Since git is used for pf-maint should it be a dependency?

**Comment by satkunas** [comment]
I think so. It's also used to compare an install state with conf/git-commit-id.

**Comment by julsemaan** [comment]
@satkunas 

I don't believe it is, pf-maint.pl uses the Github API for that.

Still, would be nice to have it since I always install it to improve the pf-maint.pl patching process since using it allows to support the ignore dirs
