### ISSUE TITLE
v9-gui: Add the ability to join rejoin and unjoin domains via the api

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3561]

**Comment by extrafu** [comment]
Right now, we also don't have a visual indicator if the domain join is working. In v8, we used to display "Test join succeeded!"

**Comment by julsemaan** [comment]
I'll tackle this through an async domain join done via pfqueue + some polling to fetch the status of the job

**Comment by extrafu** [comment]
💪

**Comment by extrafu** [comment]
^--- @lzammit  muscles

**Comment by julsemaan** [comment]
:nail_care:

**Comment by julsemaan** [comment]
^---- @lzammit hand

**Comment by extrafu** [comment]
💩

**Comment by extrafu** [comment]
^--- @lzammit 's post morning's coffee gift
