### ISSUE TITLE
Add ability to search the config

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#3563]

**Comment by jrouzierinverse** [comment]
yes

**Comment by julsemaan** [comment]
We will do a simple search for 9.0, no advanced querying

**Comment by jrouzierinverse** [comment]
This is done and in devel

**Comment by extrafu** [comment]
@dondon21 Can you please test this?

**Comment by dondon21** [comment]
I still get the error : Unknown path /api/v1/config/maintenance_tasks/search

**Comment by jrouzierinverse** [comment]
fixed

**Comment by julsemaan** [comment]
just tried it and it seems to be working
