### ISSUE TITLE
Add ability to monitor the current queue for snmp traps.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#357]
pfsetvlan does not allow monitoring what is in the SNMP traps queue.
Let's add that feature when we rewrite pfsetvlan.

**Comment by julsemaan** [comment]
Didn't know that the rewrite of pfsetvlan was due for PF 5 ?
If not we should remove the milestone and just keep it as an issue with no fixed release

**Comment by louismunro** [comment]
Not necessarily 5.0.
Could be 5.5 for all I care....

**Comment by julsemaan** [comment]
I'll remove it from our packetfence-5 milestone then.

**Comment by jrouzierinverse** [comment]
pfqueue based pfsetvlan makes this unnecessary
