### ISSUE TITLE
domain rejoin: doesn't verify user input

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3580]
You can launch a domain rejoin without credentials, of course, it will fail but we need to check if user has filled the form

Steps to reproduce:
- Click on Rejoin in `Active Directory Domains`
- Click on Set Password button without filling the form

Actual result: PF try to rejoin domain

Expected result: 
- PF raise an error and warn the user with following message: "You need to enter administrative credentials to connect to the domain"
- Set password should be replace by "Rejoin" or "Rejoin domain"

Maybe we can fix that issue in new Web UI.

**Comment by nqb** [comment]
@jrouzierinverse : with your patch, I can reproduce the issue. Moreover, I always see the "Set password" label.

**Comment by jrouzierinverse** [comment]
The button text was not done I fixed that here 20b590c4278c4e65088f78485568151ed54aa5c0.
However in my environment I am not able to rejoin the domain unless I enter the username and password.
I am assuming grunt js was not re ran in /usr/local/pf/html/pfappserver/root/static directory.

**Comment by jrouzierinverse** [comment]
I also add username and password validation in the backend in addition to the front end here 66a67711359a6b0d86df242ba40826997358488c.
So now it will not happen in either case.

**Comment by nqb** [comment]
>  I am assuming grunt js was not re ran in /usr/local/pf/html/pfappserver/root/static directory.

You're right. After doing `make vendor` and `make gist`, it works as expected.
