### ISSUE TITLE
Change the popup text when deleting switch from pf

### ISSUE THREAD

**Issue by chrkoe** [inverse-inc/packetfence#3584]
I would like to ask, if it is possible to change the popup text when deleting a switch from packetfence.
When I click on the delete button, the switch is not highlighted. On a long list of switches on very wide displays, you have to follow the lines with your finger if you really delete the correct switch.

I guess it would be easier when the popup contains the switchname or IP address.
![image](https://user-images.githubusercontent.com/33380988/44905383-3d0bcc00-ad12-11e8-8728-eedbb4f86976.png)
Something like "Really delete switch 10.0.0.2?"

Just a little "feature" request. :)

**Comment by julsemaan** [comment]
sounds legit

**Comment by julsemaan** [comment]
@nqb 

You can look at this if you have time

**Comment by cgx** [comment]
Note: This behaviour will change with the new Web admin.

**Comment by cgx** [comment]
Fixed in v9.0.0.
