### ISSUE TITLE
debian postinst should install sudo commands to /etc/sudoers.d/packetfence, not /etc/sudoers

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#359]
sudo snippets for Debian can be placed in /etc/sudoers.d. It is the logical place and makes more sense than mangling /etc/sudoers.

The debian/packetfence.postinst should reference a file like:

/etc/sudoers.d/packetfence.

**Comment by rouzier** [comment]
We would need to check for the existence of the following line in the /etc/sudoers
#includedir /etc/sudoers.d

**Comment by rouzier** [comment]
Also for centos if not already done

**Comment by fdurand** [comment]
Fixed in #588
