### ISSUE TITLE
Create node

### ISSUE THREAD

**Issue by snooker52** [inverse-inc/packetfence#3591]
Hi,
can't create new node in adminweb-->nodes-->(click)create:
Message:
Error! An error occured while contacting the server. Please try again later.
httpd.admin.log:
Sep  3 13:23:03 CZSTD-PF80-P1 httpd_admin: httpd.admin(2882) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Node->create "Can't locate object method "roles" via package "pfappserver::Form::Node::Create::Import" at /usr/local/pf/lib/pfappserver/Form/Node/Create/Import.pm line 123." (pfappserver::PacketFence::Controller::Root::end)

**Comment by MuriloCalegari** [comment]
Same error in our environment!

**Comment by satkunas** [comment]
Same issue as https://github.com/inverse-inc/packetfence/issues/3440
