### ISSUE TITLE
PF 8.1.0 Installlation on Debian (Jessie) does not set up maria-db properly

### ISSUE THREAD

**Issue by magnuslidman** [inverse-inc/packetfence#3603]
This is for PF 8.1.0

I'm using a fresh installation of Debian (Jessie) and after running the recommended installation steps (using apt-get install packetfence) everything looks like it's set up properly, but the configurator does not get past step 2 (I chose 'inline' in step 1). I get errors in the UI and the logs indicate that user 'pf'@'localhost' does not have enough permissions.

Unfortunately at that point in the installation it seems like the iptables have been halfway set up, so the SSH and web ports completely shut down after a restart - very annoying as this is a server machine stashed away in the server room.

How to reproduce:
- Install Debian 8.7.1 (only select SSH server as preinstalled package, no desktop environment and no print server)
- Configure eth0 and eth1 (eth 0 is DCHP connected to the main router, eth1 is connected to the wireless AP)
- Run the recommended installation steps from the installation guide (https://packetfence.org/doc/PacketFence_Installation_Guide.html#_installing_packetfence_on_existing_linux)
- go to the configuration web site
-Choose 'inline' deployment in step 1
- Try clicking 'next' in step 2 (there are no other choices available)

At this point you will see mysql errors in the logs. Rebooting the machine will deny all incoming traffic.

**Comment by nqb** [comment]
Please try with PF 8.2.1 and give us a feedback.

**Comment by extrafu** [comment]
No feedback provided.
