### ISSUE TITLE
Show which PacketFence Cluster Node is processing RADIUS Request in AuditLog

### ISSUE THREAD

**Issue by BiasF** [inverse-inc/packetfence#3608]
Hi,

for debugging Radius requests of clients, it would be helpful if the Audit log shows the RADIUS Server which is processing the Radius-Request for a client. 

Actually we have to look ad the radius-load-balancer.log to determine the Radius Server.

Greetings
Tobias

**Comment by julsemaan** [comment]
Sounds legit

**Comment by nqb** [comment]
I received same request from a customer.

**Comment by fdurand** [comment]
Added last year.
