### ISSUE TITLE
Authentication reports issue with "today" scope

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3609]
When viewing the authentication reports, if you select "Today" as the scope, then there are no entries displayed while there is data in the table.

It seems like it searches for entries between "2018-09-11 00:00:00" and "2018-09-11 00:00:00" which returns no entries. Instead it should search for between "2018-09-11 00:00:00" and "2018-09-11 23:59:59"

**Comment by satkunas** [comment]
@julsemaan The Authentication Reports don't have range selection. Do you mean Accounting Reports?

**Comment by julsemaan** [comment]
They do have a range in the prod-pf admin that runs the latest stable at least:
![image](https://user-images.githubusercontent.com/3857942/52132967-5e991880-260e-11e9-9103-d323659fdd55.png)

**Comment by julsemaan** [comment]
Close won't fix, that's in the old admin
