### ISSUE TITLE
Create local account: Ability to specify password length

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3610]
Right now, its preset to 10 characters or so which creates long passwords to remember.

We should allow the user to specify the length of the password in the source.

**Comment by nqb** [comment]
On my side, they are 12 characters long. See #3612.

I think we can reuse code that have been done for authentication sources in #3286.

**Comment by nqb** [comment]
On my side, they are 12 characters long. See #3612.

I think we can reuse code that have been done for authentication sources in #3286.

**Comment by julsemaan** [comment]
I've added a note to #3286 that it fixes this issue
