### ISSUE TITLE
API-based Web Admin: remove dependency to moment.js

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#3618]
[moment.js](https://momentjs.com/) is big and probably not necessary. We should try to replace it by [date-fns](https://github.com/date-fns/date-fns) (already integrated).

See [You don't (may not) need Moment.js](https://github.com/you-dont-need/You-Dont-Need-Momentjs).

**Comment by julsemaan** [comment]
@lzammit is big and probably not necessary but would you imagine Inverse without him?

**Comment by satkunas** [comment]
`momentjs` deprecated in https://github.com/inverse-inc/packetfence/pull/3619/commits/94541ff04c9fe4f435f448157a86597eb2235756
