### ISSUE TITLE
pfdetect-config-error-handling : configreload hard failed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3625]
When doing a `configreload hard ` after a `make devel` on sources, I get following error:
```
Can't locate object method "new" via package "pfconfig::namespaces::config::Pfdetect" at /usr/local/pf/lib/pfconfig/manager.pm line 93.
```
If I apply patch of #3607 PR in reverse order, I can run a `configreload hard`.

**Comment by jrouzierinverse** [comment]
install perl-re-engine-RE2 I will send you the link to the rpm
