### ISSUE TITLE
pfqueue: tons of interrupted system call errors in the DAL for update ip4log

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3626]
Getting a ton of FATAL errors that dead stop the update ip4log caused by the fact the pfqueue workers aren't able to connect properly to the DB although the DB and haproxy-db are available and other processes aren't complaining.

**Comment by julsemaan** [comment]
Error:
```
Sep 17 10:29:32 vpf1 pfqueue: pfqueue(11227) FATAL: [mac:00:11:22:33:44:55] unable to connect to database: Can't connect to MySQL server on '127.0.0.1' (4 "Interrupted system call") at /usr/local/pf/lib/pf/dal.pm line 70.
```

**Comment by julsemaan** [comment]
I was able to pinpoint this to TCP connections being problematic (whether it goes through haproxy-db or not).

I added the following in haproxy-db.conf:
```
frontend  unix-db
    bind /var/lib/mysql/mysql.sock
    mode tcp
    option tcplog
    default_backend             mysql
```

And, changed the following in mariadb.conf.tt
```
- socket    = /var/lib/mysql/mysql.sock
+ socket    = /var/lib/mysql/mysql-server.sock
```

And the messages are gone. So it seems that the issue is when pfqueue has to initiate the connection to the DB using a TCP socket

Also the rights of /var/lib/mysql/mysql.sock were adjusted:
```
chown mysql: /var/lib/mysql/mysql.sock
chmod 777 /var/lib/mysql/mysql.sock
```

**Comment by julsemaan** [comment]
Update to this, its been 5 hours since there wasn't a single error using the UNIX socket so the issue does seem to be related to TCP connections + pfqueue in particular since no other process exhibits this behavior

**Comment by julsemaan** [comment]
I was able to find 4 other environments (4 out of 4 checked) running in cluster that have the exact same error.

This seems extremely critical and causes occasional failures in recording the IP/MAC (not all tasks fail only a small percentage).

We will need to get this fixed ASAP as all clusters are affected from what I can tell whether its 8.0 or 8.1

**Comment by julsemaan** [comment]
Additional observations:
- This seems to occur multiple times in the lifetime of a process (so non-startup/stopping related)
- This seems to happen for IP related tasks, including at least but potentially not limited to: process_dhcpv4 and update_ip4log - to note that the latest composes 99.9% of the issues
- Taking into consideration the point above, the problem seems to be coming from here: https://github.com/inverse-inc/packetfence/blob/c1e11a55945bed3bd465caa2be3af6702401c20b/lib/pf/dhcp/processor.pm#L162

**Comment by julsemaan** [comment]
Tried:
- Replacing `$self->apiClient->notify` with `$self->apiClient->call`
- Replacing `$self->apiClient->notify('update_ip4log', %iptasks_arguments);` with `pf::api->update_ip4log(%iptasks_arguments)`
- Commenting out https://github.com/inverse-inc/packetfence/commit/13ecb763e4ea95bf35d2864e54f47b880551ce15#diff-ce7ef769acce2b166cced8b59e2394f3R60
- Using the most recent version of pf::db::CLONE https://github.com/inverse-inc/packetfence/blob/13ecb763e4ea95bf35d2864e54f47b880551ce15/lib/pf/db.pm#L57
- Removed `mysql_auto_reconnect` in the DBI options

All without success

So the issue seems unrelated to `pf::api::can_fork` and more to how the pfqueue processes connect/reconnect to the DB

**Comment by julsemaan** [comment]
Was able to get it to work by adding a retry logic to the DB connection:
```
sub db_connect {
    if (is_old_connection_good($DBH)) {
        return $DBH;
    }
    my $logger = get_logger();
    $logger->debug("(Re)Connecting to MySQL (pid: $$)");
    my ($dsn, $user, $pass) = db_data_source_info();
    my $try = 1;
    while($try <= 3) {
        # make sure we have a database handle
        if ( $DBH = DBI->connect($dsn, $user, $pass, { RaiseError => 0, PrintError => 0, mysql_auto_reconnect => 1 })) {
            if($try > 1) {
                $logger->info("Successfully connected to DB after $try attempt(s)");
            }
            else {
                $logger->debug("Successfully connected to DB after $try attempt(s)");
            }
            $logger->debug("connected");
            return on_connect($DBH);
        }
        $logger->warn("Tried $try time(s) to connect to database and was unable: " . $DBI::errstr);
        $try++;
    }

    $logger->logcroak("unable to connect to database: " . $DBI::errstr) unless $NO_DIE_ON_DBH_ERROR;
    $logger->error("unable to connect to database: " . $DBI::errstr);
    $pf::StatsD::statsd->increment(called() . ".error.count" );
    return ();
}
```

We'll have to see if @jrouzierinverse can pinpoint the exact issue which seems related specifically to pfqueue. Otherwise, that will be our workaround for now in the maintenance.

**Comment by julsemaan** [comment]
Possible fix:
https://github.com/jrouzierinverse/packetfence/commit/b63eb6d6756bf4e16e337b87167a0e19aab4b83b

**Comment by extrafu** [comment]
And we can blame @lzammit for the original bug: https://github.com/jrouzierinverse/packetfence/commit/f38ebbde0087f9178cda3231b4e2235f2223f907#diff-1d12a913e92ba087342db9ce59f4dcc8

**Comment by julsemaan** [comment]
That commit message sounds like @dwlfrth

**Comment by julsemaan** [comment]
No issue to report since yesterday, so I'd say this works

**Comment by dwlfrth** [comment]
@julsemaan Unfortunately, no :'(

**Comment by jrouzierinverse** [comment]
Fixed by f4b77ec7c942e7f40fc8d5f8ed8c8520bf8c591c

**Comment by julsemaan** [comment]
![image](https://user-images.githubusercontent.com/3857942/45972793-aaa5d200-c00a-11e8-9f81-0be4c6da3663.png)

**Comment by extrafu** [comment]
@julsemaan Is that a Zammitdog?
