### ISSUE TITLE
CSV export : switch_description column is empty 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3629]
In Nodes menu, when using "Export to CSV" after a search, I noticed that `switch_description` is empty in export.

I also noticed that `Switch description` column is the only one that can't be use for sorting nodes. Maybe related to the empty export.

**Comment by julsemaan** [comment]
The sorting issue is because this column is not in the database, its a virtual column.

So the sorting issue is normal, the rendering in CSV is not
