### ISSUE TITLE
pfstats hammers pfdhcp and the API frontend with requests

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3634]
I have a deployment where there are 549 routed networks.

The way the API call for leases statistics is designed, this results in 549 individual API calls every 24 seconds (https://github.com/inverse-inc/packetfence/blob/devel/lib/pfconfig/namespaces/config/Stats.pm#L51)

This results in high disk usage since httpd.api-frontend.access is ginormous and with high load on api-frontend, pfdhcp and rsyslog.

We should optimize this so that it performs a single API call to fetch all the leases information in one shot

**Comment by extrafu** [comment]
@fdurand Let's move to a strategy where we only show alerts for subnets running out of IPs.

**Comment by extrafu** [comment]
Let's not show graphs anymore for DHCP pools.

**Comment by julsemaan** [comment]
It seems the API endpoint already does exist but is undocumented, its '/api/v1/dhcp/stats' which returns stats for all the pools

So as discussed in the meeting, we should collect all the metrics in a single API call and then store it in statsd and show alerts for scopes with low amount of leases but stop showing the graphs
