### ISSUE TITLE
ha-proxy stats file not available

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#3640]
Right now, we use /tmp/proxystats for ha-proxy stats file.

The problem is that we use the same file for both processes (portal and DB) - so we don't know which one is providing the stats as it gets overwritten.

I suggest we move those files in /usr/local/pf/var/run/ha-proxy-db.stats and /usr/local/pf/var/run/ha-proxy-portal.stats

The change should be cherry-picked in the maintenance.

**Comment by extrafu** [comment]
@julsemaan Validate the idea + filename suggestions.

**Comment by julsemaan** [comment]
@extrafu's idea sounds legit, it would be a matter of adjusting the haproxy .example files to have the new socket path and to do a quick grep for the previous socket paths to make sure they're not referenced anywhere else

**Comment by nqb** [comment]
> The change should be cherry-picked in the maintenance.

If we want to apply it on current setups, we need to apply it manually because change will not be push in .conf files but in .conf.example.file.

**Comment by extrafu** [comment]
Yep, I am aware of this - we should push it nonetheless.

**Comment by fdurand** [comment]
This has already been fixed in devel. https://github.com/inverse-inc/packetfence/commit/0a834c8dc3a49fbf7daffd3aecd5ae5b0a0b12f2

**Comment by extrafu** [comment]
I think they should be moved to /usr/local/pf/var nonetheless. The stats file could even be used by in the dashboard in the future.

**Comment by fdurand** [comment]
Yes we can change the path, buut right now we use the port 1025 and 1026 to have stats of haproxy.
But we can use the stat file to control haproxy, like define a backend in maintenance mode.

**Comment by nqb** [comment]
> I suggest we move those files in /usr/local/pf/var/run/ha-proxy-db.stats and /usr/local/pf/var/run/ha-proxy-portal.stats

I prefer:
- `haproxy-db.stats` in place of `ha-proxy-db.stats`
- `haproxy-portal.stats` in place of `ha-proxy-portal.stats`

It's more consistent in comparison of config files: `haproxy-db.conf` and `haproxy-portal.conf`

**Comment by jrouzierinverse** [comment]
This can not be +1 release since we are updating .example files not the real config.

**Comment by nqb** [comment]
@jrouzierinverse: we can put it in maintenance, then we could upgrade real config files with tools like Ansible.

**Comment by jrouzierinverse** [comment]
No problem just ensure the file contents of that config was not change from the last install in the Ansible script.

In rpm you can do it like this.

```
rpm  -fV /usr/local/pf/conf/haproxy-db.conf 
rpm -fV  /usr/local/pf/conf/haproxy-portal.conf
```

**Comment by nqb** [comment]
Of course ;-)
