### ISSUE TITLE
DELETE /config/role/<id>

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#3644]
1. When trying to delete one of the default roles ([roles.conf.default](https://github.com/inverse-inc/packetfence/blob/devel/conf/roles.conf.defaults)), the server returns a 204 success code but the role is not deleted. The return code/payload should be adjusted.

2. We should add an attribute to the items of the `/config/roles` endpoint so the user knows which role can't be deleted.

3. Deleting a role should not be possible unless no node is associated to it.

**Comment by jrouzierinverse** [comment]
Fixed by 7d69679 and 72cb9b0a
