### ISSUE TITLE
API endpoint pf::config::util::is_inline_configured

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#3647]
We need an API endpoint that aggregates some computed boolean attributes. The first candidate would be  [pf::config::util::is_inline_configured](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/config/util.pm#L246-L248).

**Comment by jrouzierinverse** [comment]
Closed fixed by ef7bc85b637a23310b98d932e2b21874d23e73b4
