### ISSUE TITLE
backups: pf user can't backup DB

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3652]
Due to following commit: 7fe7c61, pf user, in standalone setup without percona, is no longer able to dump DB:

```
# ./addons/database-backup-and-maintenance.sh 
[..]
mysqldump: pf has insufficent privileges to SHOW CREATE FUNCTION `FREERADIUS_DECODE`!
```
If I remove `--routines` option here: https://github.com/inverse-inc/packetfence/blob/7fe7c6111b6178b1442b7ca284bb13192099cee9/addons/database-backup-and-maintenance.sh#L136

DB backups as pf user work again.

**Comment by nqb** [comment]
Same issue on a standalone setup with percona tools.

**Comment by julsemaan** [comment]
This has been introduced by the new strategy where we dump the stored procs.

We should see with the original committer of that (@satkunas) if we should leave the full dump and adjust PF's user rights in the DB or remove it and go back to what we had before

**Comment by nqb** [comment]
Solutions to solve that issue:
* revert parts of 7fe7c61 commit: pf user will dump DB without routines, will cause issue when doing a restore.
* keep 7fe7c61 commit:
  * grant more privileges to pf user (and pfcluster?) in configurator
  * grant more privileges to pf user (and pfcluster?) in db/upgrade-X.X.X-X.Y.Z.sql
  * update docs (Installation and Clustering Guide and UPGRADE.asciidoc)

I will check with pfcluster user.

**Comment by nqb** [comment]
`pfcluster` with percona tools can dump stored procs. So if we want to keep previous commit, we need to add more rights to `pf` user.

**Comment by satkunas** [comment]
We should do both for `pf` user.

- grant more privileges to pf user (and pfcluster?) in configurator
- grant more privileges to pf user (and pfcluster?) in db/upgrade-X.X.X-X.Y.Z.sql

We should also add a test-unit for the backups

**Comment by nqb** [comment]
Agree.
What additional privileges will need pf user to dump stored procs ? They seem to be store in the mysql DB.

**Comment by nqb** [comment]
As seen with @satkunas, following commands will do the job:
```
GRANT SELECT ON mysql.proc to 'pf';
FLUSH PRIVILEGES;
```

I will prepare a PR.

**Comment by nqb** [comment]
Sum up of my talk with @jrouzierinverse, @satkunas and @fdurand:
1. We have two run two SQL queries to be consistent:

```
GRANT SELECT ON `mysql`.`proc` TO 'pf'@'%';
GRANT SELECT ON `mysql`.`proc` TO 'pf'@'localhost';
```

2. We can't put `GRANT` statements in `db/upgrade-X.X.X-X.Y.Z.sql` because in some setups, people don't use `pf` user to dump DB. 

=> I will write a one-liner to do that task. It will get correct user by seaching in `pf.conf`. Then, I will put it in UPGRADE.asciidoc
