### ISSUE TITLE
webadmin: disabling default connection profile not take into account

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3668]
Steps to reproduce:
1. Go in Configuration -> Connection profiles
2. Edit `default` connection profile
3. Uncheck `Enable profile`
4. Save changes
=> PF says that changes were applied. Current page show an unchecked box for `Enable profile`
5. Go in Configuration -> Connection profiles
=> default connection profile still enabled

I notice that there is no changes in `conf/profiles.conf`. In `httpd_admin` logs, all seems right.

**Comment by jrouzierinverse** [comment]
You cannot disable the default profile.
That is an error in display.

**Comment by nqb** [comment]
We also need to specify this in your documentation.

**Comment by jrouzierinverse** [comment]
Fixed by 67f34672932742b42fa7b7a120daf3902088a6b4
