### ISSUE TITLE
sponsor guest registration: unexpected strings in email subject 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3669]
To reproduce:

Create a sponsor request by visiting captive portal with a web browser configured in **French**
=> Sponsor will receive an email with following subject: `example.lan : RequXte d'accXs invitX`

If I dump `%info` at https://github.com/inverse-inc/packetfence/blob/devel/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm#L185, it contains:
```
[..]
$VAR7 = 'subject';
$VAR8 = "example.lan : Requ\x{ea}te d'acc\x{e8}s invit\x{e9}";
[..]
```
Subject seems well encoded in UTF-8 but we need to send it correctly.

**Comment by nqb** [comment]
@jrouzierinverse,

As we discussed together, if I put UTF8 content directly in sponsor HTML templates, I get following behaviors:
* accented characters well displayed if PF runs on Debian 8
* accented characters bad displayed if PF runs on CentOS 7

The only difference in emails is `X-Mailer` attribute:


CentOS 7 stable
```
X-Mailer: MIME::Lite 3.030 (F2.84; T1.38; A2.12; B3.13; Q3.13)
```

Debian 8.11 stable
```
X-Mailer: MIME::Lite 3.030 (F2.85; T2.09; A2.13; B3.14; Q3.13)
``` 

Important thing to have in mind, sponsor HTML templates are now UTF8 files in place of ASCII text.

**Comment by nqb** [comment]
See also https://github.com/inverse-inc/packetfence/issues/3503

**Comment by extrafu** [comment]
Show me the full email headers.

**Comment by nqb** [comment]
@jrouzierinverse,

As seen with @extrafu, CentOS encodes email in ISO-8859:
```
# file deb-stable.eml
deb-stable.eml: SMTP mail, UTF-8 Unicode text

# file centos-stable.eml
centos-stable.eml: SMTP mail, ISO-8859 text
```

**Comment by nqb** [comment]
Still presents in 8.3

**Comment by nqb** [comment]
@jrouzierinverse : any updates ?

**Comment by nqb** [comment]
Still presents in v9 for CentOS.

**Comment by luizluca** [comment]
Normally the subject must be encoded as in:

"This is a test ç á ã ° ¿ = ?"

became

=?UTF-8?B?VGhpcyBpcyBhIHRlc3Qgw6cgw6Egw6MgwrAgwr8gPSA/?=

https://www.sendblaster.com/utf8-email-subject-encoder/

**Comment by nqb** [comment]
It works as expected on my side. 

Using `pl_PL` on captive portal, I got following Subject received: `example.lan: prośba o dostęp gościnny`

I will backport to maintenance.
