### ISSUE TITLE
Configurator: Safari can not display interface modal during the configurator

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3672]
I can not click on my interface name using Safari Version 12.0 (14606.1.36.1.9) and the other hand works on Canary chrome.

PacketFence package version: packetfence-8.1.9-0.201810110000.el7.noarch

<img width="1163" alt="screen shot 2018-10-11 at 3 56 26 pm" src="https://user-images.githubusercontent.com/5261214/46830469-b1547900-cd6e-11e8-983a-23452ee1ff65.png">

**Comment by extrafu** [comment]
Still relevant?

**Comment by extrafu** [comment]
@lzammit Please re-test and update if necessary.

**Comment by lzammit** [comment]
Working!
