### ISSUE TITLE
Configurator: Does not use the right command to start packetfence-mariadb in the configurator

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3673]
![screen shot 2018-10-11 at 4 10 39 pm](https://user-images.githubusercontent.com/5261214/46831021-3ab87b00-cd70-11e8-9d87-cadd05129101.png)

Apr 23 17:22:52 cluster1 httpd_admin: httpd.admin(3560) WARN: [mac:unknown] Problem trying to run command: LANG=C setsid sudo service mariadb start 2>&1 called from pfappserver::Model::Config::System::start_mysqld_service. Child exited with non-zero value 1 (pf::util::pf_run)

**Comment by nqb** [comment]
One of [your best practices](https://packetfence.org/doc/PacketFence_Clustering_Guide.html#_the_others_servers_configuration) is to disable MariaDB in systemd.

If you do this before starting configurator, you will not get this issue.

**Comment by jrouzierinverse** [comment]
The problem will still exists even if we disable the MariaDB service.
The configurator is manually calling 'service mysqld start'.
Even if the service is disabled systemd will start the service if you ask it to.

**Comment by jrouzierinverse** [comment]
It would be a better practice to mask mariadb instead of disabling.
It is a higher degree of safety than just disabling it.

https://fedoramagazine.org/systemd-masking-units/

```bash
systemctl mask mariadb.service
```

```bash
systemctl start mariadb
Failed to start mariadb.service: Unit is masked.
```

**Comment by jrouzierinverse** [comment]
This got me thinking should we mask mariadb when installing packetfence?

**Comment by nqb** [comment]
> This got me thinking should we mask mariadb when installing packetfence?

I think you find your answer.

**Comment by nqb** [comment]
So I wonder, why we get this issue ?

**Comment by jrouzierinverse** [comment]
The problem is the configurator was trying to start mariadb instead of packetfence-mariadb
