### ISSUE TITLE
Configurator: Can't validate the Fingerbank key during the configurator

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3674]
The ping and a curl work on api.fingerbank.org

![screen shot 2018-10-11 at 4 16 08 pm](https://user-images.githubusercontent.com/5261214/46831653-fcbc5680-cd71-11e8-9d38-fd49ab6caa1f.png)

**Comment by julsemaan** [comment]
Using a proxy ?

**Comment by lzammit** [comment]
No, normal internet connection.

**Comment by extrafu** [comment]
Still relevant?

**Comment by satkunas** [comment]
No issues for me using 8.1.9 through multiple configurations over the last couple of days
.

**Comment by lzammit** [comment]
Worked after the configurator, maybe not relevant anymore.
