### ISSUE TITLE
No authentication context provided at /usr/local/pf/lib/pf/authentication.pm When using Null source and "Email Required"

### ISSUE THREAD

**Issue by abel408** [inverse-inc/packetfence#3676]
This problem occurs when using Packetfence 8.1 with the null authentication source and "Email Required" enabled. When a user registers using the following source, they are prompted with the following error:

Caught exception in captiveportal::Controller::Root->dynamic_application "No authentication context provided at /usr/local/pf/lib/pf/authentication.pm line 226."

If I comment out lines 226 and 228 in /usr/local/pf/lib/pf/authentication.pm the problem is resolved and the user is able to register their device. Unfortunately, I'm not sure what other repercussions this may have.

Null source works fine if "Email Required" is not enabled.

Issue seems related to https://github.com/inverse-inc/packetfence/issues/3250

**Comment by nqb** [comment]
As I said on [mailing-list](https://www.mail-archive.com/packetfence-users%40lists.sourceforge.net/msg15837.html):

> On a fresh CentOS 7 install with PF 8.1.0 and your null source configuration, I didn't reproduce the issue.

So, issue seems related to your setup. I will reply to your last post on mailing-list.

**Comment by nqb** [comment]
@abel408,

I reopened issue because you can reproduce it on a fresh install of CentOS 7. Please provide exact steps to reproduce issue (be very precise).

**Comment by abel408** [comment]
Reproduced using the following:

- Clean Install of CentOS 7.5 minimal ISO
- Install Packetfence using documentation here: https://packetfence.org/support/faq/how-to-install-packetfence-with-yum.html
- Configure Packetfence with VLAN enforcement
- Enabled "Require Email" in Null Authentication Source
- Go to Connection Profiles
- Select the Default Profile
- Configure the Null Source as an authentication source
- Restart Packetfence with /usr/local/pf/bin/pfcmd service pf restart
- Select preview on the default Connection Profile
- Use any valid email address to register

**Comment by nqb** [comment]
> Use any valid email address to register

On that specific point, do you try with an email associated to an already created account in PF DB ?

**Comment by abel408** [comment]
Happens with both unregistered and registered email addresses.

**Comment by nqb** [comment]
Will try to reproduce it, maybe I do a mistake first time.

**Comment by nqb** [comment]
@abel408,

Did you apply last maintenance patches with `pf-maint.pl` ?

**Comment by nqb** [comment]
Hello @abel408,

On CentOS 7 up-to-date with latest maintenance patches, I didn't reproduce this issue.
I try with the default null source and with another null sources.

Try to apply maintenance patches and then restart `pfconfig`.

**Comment by abel408** [comment]
@nqb,

Applying the maintenance patches resolved this issue. This can be closed. Thanks

**Comment by nqb** [comment]
That was the reason why I didn't reproduce. Sorry if I missed to speak about.
