### ISSUE TITLE
Bug with setting Tenant ID in web admin

### ISSUE THREAD

**Issue by DanSheps** [inverse-inc/packetfence#3681]
After creating a tenant with the pfcmd tenant add <name> command, it is not possible to set the tenantid using the web interface.  The Tenant ID always reverts to tenant id 1.

**Comment by DanSheps** [comment]
I can provide logs if needed, provided you can tell me what logs you need.

**Comment by nqb** [comment]
Same issue on 8.2.1.

If I create a user from web admin with `Set tenant ID` equal to `2`, user is created but `tenant_id` in `person` table is set to `1`.

I try to change tenant ID with following API call:
```
curl -X PATCH "https://127.0.0.1:9999/api/v1/user/myuser" \
-H  "accept: application/json" \
-H  "Authorization: MY_TOKEN" \
-H  "Content-Type: application/json" \
-d "{\"tenant_id\":\"2\"}" \
--insecure | python -m json.tool
```
I got a 200 return code but `tenant_id` is not updated in DB.

**Comment by nqb** [comment]
@jrouzierinverse: could you take a look on this ?

**Comment by nqb** [comment]
Same issue when trying to use PATCH on `api/v1/node/mynode` to update `tenant_id`.

**Comment by nqb** [comment]
Also see #4340

**Comment by jrouzierinverse** [comment]
This can be closed since we are adding greater support for tenants.
