### ISSUE TITLE
Admin sneak peak: Node details role dropdown doesn't display more than 25 roles

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3696]
In the new admin sneak peak on 8.1, if you have more than 25 roles, then only the first 25 roles are shown when you're selecting a new role for the node.

Guessing this issue comes from the fact that the nextCursor is not followed when present in the API response

**Comment by cgx** [comment]
The API backend for the collections under `/config` is missing the search capabilities. @jrouzierinverse is on it.

**Comment by jrouzierinverse** [comment]
The node roles are retrieved from the database not from the config.
If you want all the roles the do the following.

GET /api/v1/node_categories?limit=18446744073709551614
