### ISSUE TITLE
Fingerbank: does not start and block PacketFence services

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3699]
Oct 22 10:02:39 cluster3.zammit.corp packetfence[19497]: FATAL set-env-fingerbank-conf.pl(19497): Undefined subroutine &fingerbank::Util::get_proxy_url called at /usr/local/fingerbank/collector/set-env-fingerbank-conf.pl line 52.

**Comment by julsemaan** [comment]
I've uploaded v4.1.2 of the Fingerbank package in the devel repo.

Try either reinstall from scratch or:
`yum clean all --enablerepo=* && yum update fingerbank --enablerepo=packetfence-devel`

**Comment by julsemaan** [comment]
actually the package is still uploading, so this will be online in about 10 mins

**Comment by julsemaan** [comment]
@lzammit 

Can you close this if its fixed with the newest package

**Comment by lzammit** [comment]
Works!
