### ISSUE TITLE
Installation Step 3 to Step 4

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3708]
Immediately after successfully "Creating a Packetfence account", clicking the "Continue" button produces the following "Please verify your configuration" error - while MySQL is quietly restarting in the background. This leads the user to believe that the current form is invalid - where no fields are marked with an error - thus leading to some confusion about the real source of the error and the form stop. My first instinct was to hit the back button and start-over from Step 2, thus subsequently leading to the same issue again-and-again.

![screenshot from 2018-10-24 16-30-11](https://user-images.githubusercontent.com/3904468/47459551-6e50c780-d7aa-11e8-907c-89900f7b304c.png)

After the "Continue button is pressed".... we should either rework the error message, and/or introduce a page-blocker (overlay) to prevent the user from leaving while invoking a javascript interval to poll the endpoint and reload the next page automatically.

**Comment by julsemaan** [comment]
don't forget your milestone, otherwise this will get lost

**Comment by jrouzierinverse** [comment]
This looks related to #3673

**Comment by julsemaan** [comment]
@satkunas

Want to take care of the fix for that issue ?

**Comment by extrafu** [comment]
@dondon21 Can you please that one again?

Close it if resolved.
