### ISSUE TITLE
Sponsor registration: Issue sending sponsor email in french

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3713]
It looks like that the locale set on the Connection Profile is not used for the email.

As @jrouzierinverse said, it's using the Packetfence langage of communication instead of the locale set on the portal.

I have that error:

Oct 26 17:36:40 srv-packetfence packetfence_httpd.portal: httpd.portal(4182) ERROR: [mac:00:11:22:33:44:55] Can't send email to 'test@test.com' :'Wide character in syswrite at /usr/share/perl5/vendor_perl/Net/Cmd.pm line 212.' (pf::c
onfig::util::send_mime_lite)

PF version: 8.0.1

Also similar to #3669 and #3670

**Comment by nqb** [comment]
Steps to reproduce:
- Set advanced.language to fr_FR
- Use sponsor with web browser in French and captive portal with only french locale

**Comment by jrouzierinverse** [comment]
This has been fixed in devel by fix/i18n_translation_utf8

**Comment by fdurand** [comment]
Reappear in devel:
Nov 13 15:35:50 localhost packetfence_httpd.portal: httpd.portal(15241) ERROR: [mac:9c:b6:d0:8b:e5:db] Can't send email to 'bob@bob.bob' :'Wide character in syswrite at /usr/share/perl5/vendor_perl/Net/Cmd.pm line 212.' (pf::config::util::send_mime_lite)

**Comment by fdurand** [comment]
retested and works now.
