### ISSUE TITLE
PF8.2: Device Registration: Registered MAC under another owner

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3715]
Went to https://MGMT_IP/device-registration to register a device, logged in as "inverse" user, but after registering the device, in the Nodes tab of the PF web interface, it is registered under a different user.

**Comment by atran-inverse** [comment]
![devreg](https://user-images.githubusercontent.com/36165527/47584399-53a45d00-d928-11e8-9bc7-ed0791b419bb.PNG)

**Comment by extrafu** [comment]
@jrouzierinverse Please investigate this one.

**Comment by extrafu** [comment]
@jrouzierinverse Bump - what's the status on this?

**Comment by julsemaan** [comment]
I've just tested this with a local user and an LDAP user and wasn't able to replicate the issue

**Comment by julsemaan** [comment]
@jrouzierinverse will try to replicate like I did, if he can't, we'll ask @atran-inverse to buy less powerful crack

**Comment by julsemaan** [comment]
@jrouzierinverse 

Did you look into this yesterday?
If not, can you look into it this morning ASAP?

**Comment by jrouzierinverse** [comment]
Was not able to replicate this

**Comment by julsemaan** [comment]
Lets close this then
