### ISSUE TITLE
Inline L3 DHCP option for DNS server is wrong

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3719]
When configuring an L3 inline network, instead of returning PF via DHCP for DNS, it returns the DNS server that was inputed for the network

**Comment by jrouzierinverse** [comment]
Update description please

**Comment by fdurand** [comment]
Inline l3 or l2 use the attribute dns_vip and it has been reworked in https://github.com/inverse-inc/packetfence/commit/c3252379db4a0e4babad8ae1955cd54aae398768#diff-2ae38d1aaa665428c60a14a2267fb630

My dirty patch is this one:

`
diff --git a/lib/pfconfig/namespaces/resource/network_config.pm b/lib/pfconfig/namespaces/resource/network_config.pm
index cef1804e31..4bba970d8c 100644
--- a/lib/pfconfig/namespaces/resource/network_config.pm
+++ b/lib/pfconfig/namespaces/resource/network_config.pm
@@ -56,7 +56,7 @@ sub build {
                my $ip = new NetAddr::IP::Lite clean_ip($self->{networks}{$network}{'next_hop'});
                if ($net_addr->contains($ip)) {
                    $ConfigNetwork{$network}{'cluster_ips'} = join(',', map { $_->{"interface ".$interface{'int'}}->{ip}} @{$self->{cluster_resource}->{_servers}->{$self->{cluster_name}}});
-                    if(isenabled($self->{config_pf}->{active_active}->{dns_on_vip_only})) {
+                    if(isenabled($self->{config_pf}->{active_active}->{dns_on_vip_only})||pf::config::is_network_type_inline($network)) {
                        $ConfigNetwork{$network}{'dns_vip'} = $self->{cluster_resource}->{cfg}->{CLUSTER}->{'interface '. $interface{'int'}}->{ip} || $interface{'ip'};
                    }
                    $ConfigNetwork{$network}{'vip'} = $self->{cluster_resource}->{cfg}->{CLUSTER}->{'interface '. $interface{'int'}}->{ip} || $interface{'ip'};
@@ -66,7 +66,7 @@ sub build {
                my $ip = new NetAddr::IP::Lite clean_ip($self->{networks}{$network}{'gateway'});
                if ($net_addr->contains($ip)) {
                    $ConfigNetwork{$network}{'cluster_ips'} = join(',', map { $_->{"interface ".$interface{'int'}}->{ip}} @{$self->{cluster_resource}->{_servers}->{$self->{cluster_name}}});
-                    if(isenabled($self->{config_pf}->{active_active}->{dns_on_vip_only})) {
+                    if(isenabled($self->{config_pf}->{active_active}->{dns_on_vip_only})||pf::config::is_network_type_inline($network)) {
                        $ConfigNetwork{$network}{'dns_vip'} = $self->{cluster_resource}->{cfg}->{CLUSTER}->{'interface '. $interface{'int'}}->{ip} || $interface{'ip'};
                    }
                    $ConfigNetwork{$network}{'vip'} = $self->{cluster_resource}->{cfg}->{CLUSTER}->{'interface '. $interface{'int'}}->{ip} || $interface{'ip'};
`

But i will provide a better one.

**Comment by julsemaan** [comment]
You can't use pf::config in pfconfig
