### ISSUE TITLE
Configurator: Impossible to configure only a registration network

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3724]
When selecting VLAN enforcement, it is mandatory to select an isolation interface although its not necessary and only a registration interface is necessary to get PF working

**Comment by julsemaan** [comment]
Since things have worked this way since version 4.0, before changing it, I'd like to know if any of the elders have an issue with this.

I've personally always found it annoying since you have to do a bunch of workarounds in the configurator to get it to pass without isolation

**Comment by extrafu** [comment]
@julsemaan See with @cgx if any issue.
