### ISSUE TITLE
Missing constants module pf::constants::pfconf

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3728]
After the merge of #3663 that just occured, it seems a module was forgotten in the PR:
https://github.com/inverse-inc/packetfence/pull/3663/files#diff-e2d66d92ca9c5ebd5b69da0d535804e3R36

Result is admin interface is unable to start on latest devel

**Comment by jrouzierinverse** [comment]
Fixed by 621f6ba39bbd066f2f0e3660d8036a9d40552610
