### ISSUE TITLE
web admin: errors at startup

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3747]
With `packetfence-8.1.9-0.201811020000.el7` on CentOS7, I get following errors (in `httpd_admin_err`) when I restarted `httpd.admin` daemon:

```
Nov  5 09:49:04 centos-devel httpd_admin_err: (process:2693): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed    ┤
Nov  5 09:49:04 centos-devel httpd_admin_err:                                                                                                         ┤
Nov  5 09:49:04 centos-devel httpd_admin_err: (process:2693): GLib-GObject-WARNING **: cannot register existing type 'LassoNode'                      ┤
Nov  5 09:49:04 centos-devel httpd_admin_err:                                                                                                         ┤
Nov  5 09:49:04 centos-devel httpd_admin_err: (process:2693): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
```
with 2693 pid of `httpd.admin`

**Comment by julsemaan** [comment]
Does it still start or does it die ?

Also provide:
```
# rpm -qa | grep -i lasso
```

**Comment by nqb** [comment]
It starts.

```
lasso-perl-2.5.1-100.el7.centos.x86_64
lasso-2.5.1-100.el7.centos.x86_64
```

**Comment by julsemaan** [comment]
I'm guessing if it starts, there isn't that much of a problem.

Lasso has always been a pain with mod_perl and its almost impossible to troubleshoot since we can't create simple scripts to replicate the issue and open bugs with the Lasso team

**Comment by nqb** [comment]
I saw same messages on a PF 8.1.0 running on CentOS 7 up-to-date with identical lasso libraries.

**Comment by nqb** [comment]
Is it possible that issue could have been caused by a commit in maintenance branch ?

I'm almost sure that we have not this issue before last week on devel machines.

**Comment by julsemaan** [comment]
Then it would be caused by a commit in devel (not maintenance) since last week.

But I doubt anybody touched lasso, it could be doing that because of another package not being at the same version as your deployment last week

**Comment by nqb** [comment]
I think you're right, you can reproduce with a CentOS 7 up-to-date.

**Comment by julsemaan** [comment]
@jrouzierinverse will check the import strategy for the Lasso constants after his PR from last week

**Comment by julsemaan** [comment]
@jrouzierinverse 

Have you looked into this yesterday ?
Since httpd.admin starts, I think we shouldn't consider this a show stopper and can always address this in the maintenance
