### ISSUE TITLE
Dashboard: portal metrics are all empty

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3749]
It seems the portal metrics are all empty in the dashboard.

The metric prefix they are pointing to (web_log_*) doesn't seem to exist anymore when looking in the full netdata dashboard

**Comment by julsemaan** [comment]
@fdurand 

Anything changed for the collection part of the portal metrics in netdata ?

**Comment by fdurand** [comment]
It looks that it's a issue with the permissions on the http.portal.access file.

**Comment by julsemaan** [comment]
So I guess this will need to be fixed via packaging right ?

**Comment by julsemaan** [comment]
Little bad from @fdurand 

Pointing to wrong issue in the commit

**Comment by julsemaan** [comment]
It seems this is caused by invalid permissions of the file when created by the rsyslog daemon.

Performing the following fixed it:
```
chmod a+r /usr/local/pf/logs/*
systemctl restart packetfence-netdata
```

Seems it affects previous versions of PF but it won't be possible to backport via the maintenance since this will be packaging.
