### ISSUE TITLE
POTD: Rotate on a precise day instead of duration

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3761]
Instead of rotating on a duration, it would be useful to be able to rotate every sunday or every 1st of the month, etc for better control of the password change

**Comment by extrafu** [comment]
Pretty much how @lzammit rotates for shower time?

**Comment by julsemaan** [comment]
I think @lzammit showers only happen on leap years so we have another year and a half before the next one

**Comment by lzammit** [comment]
![](https://www.images-booknode.com/book_cover/416/gros-degueulasse-415944-264-432.jpg)

**Comment by fdurand** [comment]
We should just change in the form the "Password Rotation Period" by the access duration list since it's possible to define an access duration relative to the bigining of the period.
