### ISSUE TITLE
Allow on registration opens udp ports 88 and 389 instead of tcp

### ISSUE THREAD

**Issue by pfpedini** [inverse-inc/packetfence#3769]
Pfdns opens the wrong ports if "Enable on registration" is enabled for a domain: I noticed that I couln't jojn a workstation to domain from the registration network. Inspecting the ipsets I noticed that there ports 88 and 389 were configured for udp, not tcp.
Kerberos needs both tcp and udp, while ldap only needs tcp afaik

**Comment by julsemaan** [comment]
This is fixed in devel and will be part of the maintenance binaries for 8.0 to 8.2 tomorrow.

You can get the patch by executing:
```
# /usr/local/pf/addons/pf-maint.pl
```
