### ISSUE TITLE
configreload race condition

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3771]
If you perform a configreload at the same time on more than one server, there is a race condition for the process of refreshing the radius_nas table.

The process inserts new clients with the starting timestamp as an identifier of the new batch (both servers have different timestamp for the identifier)

Assuming server 1 starts at 13:00:00 and server 2 starts at 13:00:02 and the process takes 5 seconds.

Server 1 will insert its clients normally, then 2 seconds later server 2 starts inserting clients.
Server 1 finishes 2 seconds before server 2 and deletes all the clients server 2 has inserted between 13:00:02 and 13:00:05
Then server 2 finishes the process and deletes all the clients server 1 inserted
We then end up with only the clients server 2 inserted between 13:00:05 and 13:00:07

**Comment by julsemaan** [comment]
It seems that adding a health check that retries on failure of detection of all the clients will not be efficient since that will likely create a never ending loop on both servers.

So the best thing would likely be to logcroak and print to STDERR when the insertion process fails with a meaningful error message so that the admin can redo his configreload.

This above though would be only guaranteed to work if the admin looks at the output of all configreloads as server 1 isn't guaranteed to fail in the event server 2 didn't insert a new client in between the delete and the count.

Still better then no output at all on all servers

I'm opened to other ideas also before implementing this

**Comment by satkunas** [comment]
We may be able to use MySQL's `SELECT ... FOR UPDATE` here which provides row-level locking. I'm not sure of it's behavior through galara clustering, but the lock *should* propagate to all members as expected.

https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html

**Comment by julsemaan** [comment]
@satkunas 

The thing is the insert is made in batches to reduce the amount of necessary locking (we can have many thousands of clients to insert at the same time and locking has to be reduced to the absolute minimum here).

My personal opinion is to not change the origin algorithm written by @jrouzierinverse that has been doing its job for about 4 years to workaround a very corner case bug that occurs when the command is misused (at least misused in the mindset of the algo). 

For me, dying + warning the user he misused the command would be enough so that we don't have to come up with a newer algorithm for that core piece of PacketFence that might itself introduce a new very corner case bug we'll discover in 4 years (PacketFence 12 FTW). So for me adjusting what we have and works is the best path to offering stability of this specific code path.

**Comment by satkunas** [comment]
@julsemaan what about adding a new column in `radius_nas` for soft-locking (application level) along with an index on this column. Configreload would `UPDATE` this column with its own PID (or another random uuid) at the start of the reload, and only `DELETE ... WHERE uuid=[mine]` at the end. Any parallel processes would overwrite this column with its own uuid thus deprecating the first process from `DELETE`ing?

**Comment by extrafu** [comment]
PID+hostname would be better because the PID could be identical across multiple servers. Even better, PID+GUID if hostname resolves to "localhost" on all cluster members.

**Comment by satkunas** [comment]
@extrafu keep the columns `INT` based. `VARCHAR` indexes are much slower than `INT` and `BINARY`. 

We could md5(uuid + guid) with a `BINARY(16)` column for fast indexes.

**Comment by julsemaan** [comment]
The thing is if a process of configreload is broken in the middle of the insert, then restarted afterwards, the old clients will be left there and then you end up with duplicate clients in the table.

And that logic implies that you'll have duplicate clients (a row for each server in the cluster)

**Comment by julsemaan** [comment]
And also, rewriting this algorithm isn't very maintenance friendly so rewriting it would imply having a solution for 8.2 and below, and then a new solution for 8.3 and above

**Comment by satkunas** [comment]
@julsemaan in this case we could use a timestamp (with milliseconds) instead of a uuid. `DELETE ... WHERE tsms=[mine] OR tsms < [1 minute ago]`. Then add an `EVENT ... WHERE tsms < [1 minute ago]` to handle unexpected broken configreload's (or a `pfmon` schedule).

https://dev.mysql.com/doc/refman/5.7/en/event-scheduler.html

**Comment by julsemaan** [comment]
you can't delete at the beginning though, you need to delete at the end or otherwise you empty the clients while you're updating it so that query won't work since you'll need an identifier for your new batch.

Also, I know that there are solutions and new algos possible, but I think we need to keep in mind that the solution shouldn't require a rewrite of this proven logic for such a corner case. Simply handling the corner case in the existing algo would be enough IMO.

Starting the rewrite of this core piece to handle this little corner case would be overkill IMO

**Comment by satkunas** [comment]
> you can't delete at the beginning though, you need to delete at the end or otherwise you empty the clients while you're updating it so that query won't work since you'll need an identifier for your new batch.

Yes, it's the same logic as my first suggestion where configreload would use `tsms` instead of a `uuid`. It stores `tsms` at the beginning and carries it until the end `DELETE ... WHERE tsms=[mine]`

The MySQL `EVENT` can be setup to run only once, and initiated at the beginning of configreload, so if it breaks mid-process, the event is still cached to run once at a later time.

I'm all for another solution that's easier to implement. Just my $0.02

**Comment by julsemaan** [comment]
For me the key isn't in "fixing" the algo but more in directing the usage and warning misuse of the tool to stay safe.

Still, if everyone believes we should rewrite this and I'm the only one against it, then we can do the 2 implementations (warning for maintenance, fixing for devel)

**Comment by satkunas** [comment]
@julsemaan I'm not for or against either of our proposals. I'm only making a suggestion from a MySQL perspective. I agree that directing the usage would be most ideal.

**Comment by jrouzierinverse** [comment]
Here is an approach that is similar to ours current one that will also work in a cluster environment.

* Get an increasing 64 bit integer that is unique # across all workers updating radius_nas
* Every worker inserts their copy of switches.conf with the unique #
* Delete all that is less than their unique #
* Perform the following checks if they fail report an error
  * The number of entries match what has been inserted.
  * Also the number of entries that are greater than my unique # is zero

The hardest part is getting the unique #

I propose to use the current time in mysql server in microseconds * 100 + @@server_id

This guarantees that every worker gets a 64 bit unique number (for clusters less than 100)

If we really want to ensure this will work for clusters greater than hundred the we can replace 100 with the number of members in the clusters. 

```sql
SELECT CAST( (UNIX_TIMESTAMP(NOW(6)) * 100000000) AS SIGNED) + @@server_id AS uniq;
```

```sql
SELECT CAST( (UNIX_TIMESTAMP(NOW(6)) * 1000000 * COALESCE((SELECT IF(variable_value > 0,variable_value, 1) from information_schema.global_status where variable_name='wsrep_cluster_size' limit 1), 1)) AS SIGNED) + @@server_id AS uniq;
```

Things that could cause issues.
* switches.conf is not the same across the servers. (This is an issue now that we cannot solve)
* A misconfigured cluster where more that two servers have the same id. 
* (Using the cluster size as the multiplier) If there is a server id that is greater than the number of cluster members. (This could be solved by using the biggest server-id as the multiplier)
* (Using 100 as the multiplier) If there two servers that have the ids 100 and 0
* If the system clock if really off between two servers.

Most of these cases will be caught by the error check in the end.
