### ISSUE TITLE
use pf::util; missing in /usr/local/pf/lib/pf/pfmon/task/populate_ntlm_redis_cache.pm

### ISSUE THREAD

**Issue by cmammoli** [inverse-inc/packetfence#3775]
Tried to enable redis ntlm cache for a domain but I got in pfmon.log

"ERROR: [mac:unknown] Error running task populate_ntlm_redis_cache: Undefined subroutine &pf::pfmon::task::populate_ntlm_redis_cache::isenabled called at /usr/local/pf/lib/pf/pfmon/task/populate_ntlm_redis_cache.pm line 38."

In line 38 isenabled sub is called, which is provided by the afore mentioned pf::util

Regards

**Comment by nqb** [comment]
Hello @cmammoli,

Thanks for the report.

Already fixed by 4b738b4, I push fix to maintenance/8.2 branch.
