### ISSUE TITLE
NTLM cache does not work if authentication source uses comma separated DCs IP

### ISSUE THREAD

**Issue by cmammoli** [inverse-inc/packetfence#3776]
I was trying out ntlm cache and couldn't get it to work. Enabled debug and noticed secretsdump gets called this way:

/usr/local/pf/addons/AD/secretsdump.py 'packetfence':'password'@192.168.0.7,192.168.0.76 -just-dc-ntlm -output /tmp/J54dtYqiAA -usersfile /usr/local/pf/var/cache/ntlm_cache_users/APRA.valid-users.txt

which running manually returns:

Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

[-] RemoteOperations failed: [Errno Connection error (192.168.0.7,192.168.0.76:445)] [Errno -2] Name or service not known
[*] Cleaning up...

I'm using 2 DCs in the authentication source:

[apra-user-auth-dc01]
cache_match=0
realms=apra,apra.it,default,null
basedn=dc=apra,dc=it
password=password
set_access_level_action=
scope=sub
email_attribute=mail
usernameattribute=sAMAccountName
connection_timeout=5
binddn=cn=packetfence,cn=Users,dc=apra,dc=it
encryption=starttls
port=389
description=Apra User authentication
host=192.168.0.7,192.168.0.76
type=AD
read_timeout=10
write_timeout=5
monitor=1
dynamic_routing_module=AuthModule
shuffle=0

**Comment by julsemaan** [comment]
The NTLM cache code was written without considering multiple IP addresses would be used in the host value of LDAP.

If you want a quick fix, use a DNS record for your LDAP host, I'll create a fix that picks the first LDAP server and put it in the maintenance when I have a moment.

Thanks for the really detailed troubleshooting
