### ISSUE TITLE
Endpoints needed to test LDAP/AD password

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3791]
We need 2 API endpoints to test the LDAP and AD authentication source passwords.

**Comment by julsemaan** [comment]
Technically, I think it could be the same endpoint since an AD source is an LDAP source with different default attributes

**Comment by jrouzierinverse** [comment]
We already have such endpoint.

/api/v1/config/sources/test
You send the same payload as you would send to create a source.
This works for any source that supports testing
