### ISSUE TITLE
API - Config Source Actions returns a named role

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3800]
The endpoint at `/api/v1/config/source/:name` returns a _named_ role, it should instead return the _category_id_.

In the following example _default_ should be _1_.

```{
    "item": {
        "authentication_rules": [{
            "actions": [..., {
                "type": "set_role",
                "value": "default"
            }],
            ...
```

**Comment by julsemaan** [comment]
Its actually a named role in the configuration file itself so it wouldn't make sense to make it an ID in the API IMO

**Comment by satkunas** [comment]
@julsemaan this makes sense, but it's not consistent with the roles category_id used in the remainder of the admin specifically within the database. Should we look at making its use consistent, or support the 2 different ways of using it?

**Comment by jrouzierinverse** [comment]
Since you eventually get allowed values/defaults for config items through the API via the config/<name>/defaults endpoint.
Just use the name for the moment.

**Comment by julsemaan** [comment]
Making the use consistent would require us to rewrite how the backend stores the role and would make the raw configuration file less clear
