### ISSUE TITLE
email templates: make them more flexible

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3804]
Related to #3664 

Currently, email templates use a static list of variables. If you use Root Portal Modules and you add new mandatory fields, it would be nice to have them automatically integrated in the resulting emails.

### Example

You add a "company" mandatory field for a sponsor-based registration in a Root Portal Module, you will see this field and associated value in resulting emails.

**Comment by nqb** [comment]
Reopening: issue still presents.

In order to replicate:
1. Create a sponsor user with foo@foo.com as email
1. Create a portal module like this:
```
[default_registration_policy]
modules=default_login_policy,default_guest_policy,default_oauth_policy,default_billing_policy,default_saml_policy,default_blackhole_policy,sponsor
actions=
template=content-with-choice.html
show_first_module_on_default=disabled

[sponsor]
source_id=sponsor
actions=
fields_to_save=custom_field_1,company
custom_fields=custom_field_1,company
description=sponsor
with_aup=1
signup_template=signin.html
pid_field=email
aup_template=aup_text.html
type=Authentication::Sponsor
```
1. Try to register using this portal module on default connection profile

=> Sponsored user received following email:

![Capture d’écran de 2021-02-01 08-21-37](https://user-images.githubusercontent.com/10830260/106426800-86721f80-6466-11eb-866a-a0ac0a32aa97.png)

Fields are correctly saved in DB for sponsored user.

**Comment by nqb** [comment]
@jrouzierinverse, did you finish to work on that issue ?

**Comment by fdurand** [comment]
If we can also add the context of the device in the stash, like the SSID, mac, switchport ...
