### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by jaishan** [inverse-inc/packetfence#3806]
Hi Team,

I am trying to install packet fence on ubuntu 16.04. However after following the instruction I am stuck at unable to locate package.

jdas@jdas-desktop:~$ sudo echo 'deb http://inverse.ca/downloads/PacketFence/debian jessie jessie'     > sudo /etc/apt/sources.list.d/packetfence.list
jdas@jdas-desktop:~$ 
jdas@jdas-desktop:~$ 
jdas@jdas-desktop:~$ sudo apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys 0x810273C4
Executing: /tmp/tmp.fv2WhAUOvR/gpg.1.sh --keyserver
hkp://keys.gnupg.net:80
--recv-keys
0x810273C4
gpg: requesting key 810273C4 from hkp server keys.gnupg.net
gpg: key 810273C4: "Inverse Support (package signing) <support@inverse.ca>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
jdas@jdas-desktop:~$ sudo apt-get install packetfence
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package packetfence

Please let me know how to resolve the issue

**Comment by julsemaan** [comment]
We only support CentOS7 and Debian 8

Ubuntu isn't supported anymore.

**Comment by jaishan** [comment]
Thats sad to hear...is there any other way of implementing it???

**Comment by julsemaan** [comment]
You have the choice between installing on a supported distro or using the ZEN virtual machine

**Comment by dmiyyy** [comment]
how to build it for ubuntu? 
I can help, if you have any problem.

**Comment by hisashiyamaguchi** [comment]
I have the same issue - any workarounds?

```
$ uname -r
4.19.0-16-cloud-amd64

$ sudo apt-get install packetfence
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package packetfence
```
