### ISSUE TITLE
iptables: port 22222 is opened in iptables

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3812]
Port 22222 (pfdhcp API) is opened in iptables and offers unauthenticated access to the pfdhcp API.

This should instead be closed and requests should go through the API frontend.

**Comment by julsemaan** [comment]
Just need confirmation with @fdurand that things won't start breaking if we block this port

**Comment by fdurand** [comment]
It listen on 127.0.0.1:22222 so yes we can block it.

**Comment by julsemaan** [comment]
I'll lower the level then since even though its opened, its not accessible

**Comment by julsemaan** [comment]
not cherry picking since its in an example file anyway

**Comment by julsemaan** [comment]
fixed by c8c798c3ccef90ecfde46c97140381c9761cbcf3
