### ISSUE TITLE
Improved validation for PF domain name

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3817]
Right now, you can enter any text as the PF hostname and domain name.

We should validate:

* Names only contain 0-9 A-Z a-z and an hyphen and cannot start with an hyphen
* While we're there, deny .local domains since they don't work with the ios portal popup

**Comment by satkunas** [comment]
> Names only contain 0-9 A-Z a-z and an hyphen and cannot start with an hyphen

... and dots `.`

**Comment by julsemaan** [comment]
Forgot the obvious :)

**Comment by nqb** [comment]
> While we're there, deny .local domains since they don't work with the ios portal popup

Not agree, just warn users don't deny.

**Comment by julsemaan** [comment]
@nqb 

This generated numerous useless support calls. This is like people putting their portal domain name in the passthrough. Before we denied it we had to dig for 30 minutes to pinpoint the issue.

Then, if you only warn, the user who configures sees the warning, but the guy who debugs it will not see it so he has to debug his way through to that. Worse than that, people not used to PacketFence will not think of it right away so that can lead to a long and painful call before he calls out for help of the elders and they point the obvious.

If the person really wants to work his way around this, he can go in pf.conf directly and put whatever he wants, but the admin should protect the novices for these kind of mistakes

**Comment by fdurand** [comment]
I am agree to deny .local, we just wasted our time to debug this issue.

**Comment by nqb** [comment]
I prefer following approach: deny configuring IOS portal to users who use a .local domain.

**Comment by julsemaan** [comment]
How do you deny configuring an IOS portal...?
