### ISSUE TITLE
pf-maint.pl : Unable to get Terminal Size

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3818]
If I try to apply maintenance patches on v8.2 installations through Ansible, I get following error:

`Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment variables didn't work. The resize program didn't work. at /usr/lib64/perl5/vendor_perl/Term/ReadKey.pm line 362.`

I didn't have this issue with 8.1. Seems to be related to bfeaf35.

CentOS packages for 8.1 and 8.2
```
perl-TermReadKey.x86_64                    2.30-20.el7              @base
```
Ansible version: 2.7.2

**Comment by nqb** [comment]
@jrouzierinverse: could you cherry-pick in maintenance/8.2 ?

**Comment by jrouzierinverse** [comment]
Done!

**Comment by nqb** [comment]
Thanks a lot !
