### ISSUE TITLE
refactor getNormalVLAN

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#382]
The code smells are so bad it makes me want to throw up.
Il will take care of it unless someone else feels as strongly about it.

**Comment by fdurand** [comment]
I reworked it a little bit in #330

**Comment by louismunro** [comment]
Right. We can use that as a basis for more work.

**Comment by dwlfrth** [comment]
I have some work done on my end. Will verify if still accurate regarding PR #330 and will push in a separate branch.

**Comment by louismunro** [comment]
Closed as outdated.
