### ISSUE TITLE
Web interface stuck after DB creation

### ISSUE THREAD

**Issue by diedriko** [inverse-inc/packetfence#3822]
Hi
After I've installed packetfence on a Centos 7 machine, the configuration through the web interface gets stuck on step 3.
After creating root password, creating tables and user for packetfence, which all give a succesfull message, I try to get to step 4 but the continue button doesn't give a reaction.
Afterwards the same ip page gets unresponsive and becomes unaccessible.
When I check through the terminal, I see the httpd service is dead.
This service I'm able to restart, but the Haproxy service is also dead and this one I'm unable to restart because the haproxy.cfg gives a fatal error.
I have been able to reproduce the same error on 2 trials.
Please advice,
Thanks,
D.

**Comment by satkunas** [comment]
Could be similar to https://github.com/inverse-inc/packetfence/issues/3708

Some details about your specific setup, the haproxy.cfg error(s) - and any other error logs - would help.

**Comment by diedriko** [comment]
haproxy.cfg error=> can't handle unexpected argument *:5000
research shows syntax has changed for cfg file, should use bind command 
not related to db creation, these steps are succesfull, on webinterface and when verifying on terminal

**Comment by nqb** [comment]
@diedriko: could you provide us the exact steps to reproduce this issue ?
1. Step 1 of configurator
2. Step 2 of configurator
3. Step 3 of configurator

Thx.

**Comment by diedriko** [comment]
step1 web auth
step 2 configured server with one ethernet interface as trunk with a management vlan and a registration vlan (here additional daemon portal)
step 3 creating root password, creating tables and user for packetfence, which all give a succesfull message
Then continue button freezes
when I verify in terminal httpd service, it's down, but I'm able to restart
but haproxy service is also down and this 1 I'm unable to start, with error haproxy.cfg error=> can't handle unexpected argument *:5000

**Comment by nqb** [comment]
Are you able to reproduce this issue using [PacketFence ZEN image](http://sourceforge.net/projects/packetfence/files/PacketFence%20ZEN/8.2.1/PacketFence-ZEN-8.2.1.zip/download) ?

PacketFence don't use a `haproxy.cfg` file, I suppose you have a conflict with another haproxy program on your machine.

**Comment by diedriko** [comment]
did clean install packetfence on newly created centos 7, same issue, after step 3 , contunue button unresponsive
will try the zen

**Comment by diedriko** [comment]
did manage to configure pf, configured physical interface as trunk, no problems then, wasn't mentionned in manual
