### ISSUE TITLE
Make redirection initial delay and retry delay configurable.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#383]
Right now they are not in pf.conf.

**Comment by julsemaan** [comment]
This is tricky too since not all network activation have the same delays. For example sponsor activation doesn't have the same delay as release since the access is not activated but is being activated. It should be granular so that you can specify it for scanning, sponsor (pending) and release

**Comment by julsemaan** [comment]
The "initial_delay" and "retry_delay" in html/captive-portal/templates/release.html are currently not configurable via pf.conf versus the "timer" variable that is controlled by fencing.redir_timer in pf.conf

Both of those settings should be configurable via pf.conf instead of being code constants
