### ISSUE TITLE
dhcp in cluster about get ip 

### ISSUE THREAD

**Issue by ChengcQR** [inverse-inc/packetfence#3833]
I have configured it according to the PacketFence_Clustering_Guide document. You can also see that the three server services are normal in Cluster Page, but the IP address of the registered domain obtained by the client access switch in VLAN Enforcement is the gateway and DNS configured for each server.could you provide us the exact steps to configure reg and isolation network ,Thanks!

**Comment by AIChanYM** [comment]
@danpoltawski @louismunro

**Comment by AIChanYM** [comment]
> I have configured it according to the PacketFence_Clustering_Guide document. You can also see that the three server services are normal in Cluster Page, but the IP address of the registered domain obtained by the client access switch in VLAN Enforcement is the gateway and DNS configured for each server.could you provide us the exact steps to configure reg and isolation network ,Thanks!
