### ISSUE TITLE
Too complex password prevent RADIUS to start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3836]
If you install PF and use `jF>")wY*pk"tLtq` as a password for `pf` user, RADIUS will not start due to unescaped quotes in `/usr/local/pf/conf/radiusd/sql.conf`.

**Comment by nqb** [comment]
We could prevent this by checking `pf` user password in configurator.

**Comment by nqb** [comment]
@jrouzierinverse,

c61743d should fix this issue ?

**Comment by jrouzierinverse** [comment]
Yes

**Comment by jrouzierinverse** [comment]
@julsemaan should this fix be placed in maintenance?

**Comment by julsemaan** [comment]
IMO I don't think its needed that much since the maintenance is usually applied on environments that were already built so they already have their passwords setup.
