### ISSUE TITLE
Config API list limit has no effect

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3849]
Right now in the new admin, the list of configuration sections is paginated and uses a limit of 10 items per page using the following HTTP request:

```
GET /api/v1/config/violations?cursor=0&limit=10&fields=id,desc&sort=id HTTP/1.1
Host: 172.20.20.109:1443
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/plain, */*
Accept-Language: en
Accept-Encoding: gzip, deflate, br
Referer: https://172.20.20.109:1443/admin/alt
Authorization: Bearer d07e3e388665e60acd4c1acb0e4e5dabd70ff70052c033b05a43c77a3f32688d
Connection: keep-alive
Cookie: CGISESSION=9c5898dd55d7c157ae10a22395575b851303ecfe; pfappserver_session=312c8e3ff826bcd1fd843ed12fbf335292740efe
```

But this returns more than the 10 items that are requested

The spec is unclear as to whether or not its supported as cursor, limit don't appear as acceptable query fields but nextCursor and previousCursor appear in the response fields

@jrouzierinverse, can you shed some light on this

**Comment by jrouzierinverse** [comment]
Fixed by 397d59d5d144beaacb7401b7215def3b404d913f
