### ISSUE TITLE
/conf/switch_groups listed in conf/switches

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3859]
Manually added resources from `conf/switch_groups` are listed in `conf/switches`, where the `id` is prefixed with "group[space]".

Example: resource in `switch_groups` as `Group Id: "TestGroup"`, is listed in `switches` as `Id: "group TestGroup"`.

**Comment by jrouzierinverse** [comment]
Fixed by 35fdf7ee05230634a124ba8dd90e0fa22ba965d3
