### ISSUE TITLE
Printing Wifi ticket is useless in Pf 8.2

### ISSUE THREAD

**Issue by BiasF** [inverse-inc/packetfence#3860]
Hi,

if you create a bunch of users in PF 8.2 and want to print the access details you got a PDF with wifi tickets 
the Headline of the Page is printed too, that leads to that the tickets extend over a second page.

![image](https://user-images.githubusercontent.com/5191818/50148320-83cd0400-02b8-11e9-9cd7-6f3294bf7bf7.png)

If you don't print the AUP, you also have wifi tickets which extends over 2 pages ;)
![image](https://user-images.githubusercontent.com/5191818/50148601-3735f880-02b9-11e9-85b6-178793a00eb2.png)

Maybe it would be better to create a PDF than just printing the page :D 
As it is now, the feature is a bit useless if you want to create a bunch of users. 

Greetings
Tobias

**Comment by julsemaan** [comment]
It seems like the print style isn't being applied as its trying to print the page directly and not applying the special CSS rules as it was in the past.

I'll look into this

**Comment by julsemaan** [comment]
Seems that the regression is here:
20e9ae9bbbb14d82efce11fd78a22b9680fed65f

Where the CSS is being loaded as a script

**Comment by julsemaan** [comment]
Fixed an cherry-picked up to maintenance/7.4 which is when the regression was made

You can get the fix by running:
```
/usr/local/pf/addons/pf-maint.pl
```

And then restarting PacketFence completely
