### ISSUE TITLE
Track specific changes in the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3862]
As an example, right now we track that an admin changed a switch but we don't display what he has changed in that switch configuration for additional finger pointing fun when someone does a breaking change.

This mainly applies to configuration so adding this in the config CRUD stack would be enough, although there are other uses like when admins modify nodes or users but configuration seems to be the most critical to track.

**Comment by jrouzierinverse** [comment]
Which is better to store.
The difference between the old and new config items
```json
   {
     "changes": [
         { "name1" : "field", "old" : "old_val", "new" : "new_val"},
         { "name2" : "field", "old" : "old_val", "new" : "new_val"}
      ]
   }
```
Or simply the old and new value
```json
   {
     "changes": {
         "old" : {"f1" : "v1"},
         "new" : {"f1" : "v2"},
      }
   }
```

**Comment by julsemaan** [comment]
2nd looks better to me personally

**Comment by julsemaan** [comment]
This will need to be addressed in the API if we want this since doing it in the old admin isn't relevant anymore

**Comment by nqb** [comment]
@jrouzierinverse, is Admin Audit Log (see #4834) feature solves this issue ?

**Comment by jrouzierinverse** [comment]
Yes
