### ISSUE TITLE
E-mail source not being sent - emails.css not found

### ISSUE THREAD

**Issue by MuriloCalegari** [inverse-inc/packetfence#3865]
Hi everyone, we've been applying pf-maint regularly and we didn't notice that e-mail source had stopped working; when someone tries to register in PacketFence, the following error is thrown:

> Project-Id-Version: PacketFence POT-Creation-Date: YEAR-MO-DA HO:MI+ZONE PO-Revision-Date: 2018-05-10 21:07+0000 Last-Translator: Rogério Moura <rogeriosims@gmail.com> Language-Team: Portuguese (Brazil) (http://www.transifex.com/inverse/packetfence/language/pt_BR/) MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit Language: pt_BR Plural-Forms: nplurals=2; plural=(n > 1);

Which is actually the text found in packetfence.po. In packetfence.log, we see:

> Dec 19 11:52:53 prometeu packetfence_httpd.portal: httpd.portal(47114) INFO: [mac:00:11:22:33:44:55] User XXXXXXXXX@gmail.com has authenticated on the portal. (Class::MOP::Class:::after)
> Dec 19 11:52:53 prometeu packetfence_httpd.portal: httpd.portal(47114) INFO: [mac:00:11:22:33:44:55] new activation code successfully generated (pf::activation::create)
> Dec 19 11:52:53 prometeu packetfence_httpd.portal: httpd.portal(47114) INFO: [mac:00:11:22:33:44:55] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
> Dec 19 11:52:53 prometeu packetfence_httpd.portal: httpd.portal(47114) ERROR: [mac:00:11:22:33:44:55] file error - emails.css: not found (captiveportal::PacketFence::Controller::Root::end)

No error is registered in httpd.portal.error.

**Comment by julsemaan** [comment]
Is it possible you have modified the email templates that are shipped by default with PacketFence?

**Comment by MuriloCalegari** [comment]
It is possible; where can I find the original one?

**Comment by julsemaan** [comment]
The templates are in html/captive-portal/templates/emails/ so you'd have to ensure you didn't change them directly or overrode them in your connection profile by running this:

`ls -la html/captive-portal/profile-templates/*/emails/`

You'll find the original templates here:
https://github.com/inverse-inc/packetfence/tree/devel/html/captive-portal/templates/emails

**Comment by MuriloCalegari** [comment]
That was the problem exactly, thank you!

Question: should PacketFence updates handle these types of modifications?

**Comment by julsemaan** [comment]
Currently it is the responsibility of the administrator to ensure he migrates any changes to the templates (HTML or email) manually whether the upgrade is done via yum or via the maintenance

**Comment by MuriloCalegari** [comment]
That was clarifying, you can close this issue now.

Thank you.
