### ISSUE TITLE
rsyslog config broken

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3876]
Commit  722a96a try to fix #3847 but after a fresh install on CentOS 7, I get following error message for `rsyslog` daemon:
```
Dec 24 09:14:49 centdev-83.example.lan rsyslogd[27918]: error during config processing: STOP is followed by unreachable statements!  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]
```
If I revert 722a96a and do:
```
/usr/local/pf/bin/pfcmd generatesyslogconfig
systemctl restart rsyslog
```
`rsyslog` is working again.

**Comment by julsemaan** [comment]
I wasn't able to get the same error message as you but the config was indeed broken on my machine too.

I've pushed a commit for this, try it out and let me know if that works

**Comment by nqb** [comment]
For sure !

**Comment by nqb** [comment]
Works as expected:
```
cat /etc/rsyslog.d/packetfence.conf
[..]
# haproxy_db.log
if $programname == "haproxy" and ($msg contains "mysql" or $msg contains "backend has no server available") then
  -/usr/local/pf/logs/haproxy_db.log
& stop
[..]
```
