### ISSUE TITLE
Wireless Mac-Auth: Access accept but reason in audit log is weird 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3880]
I test the Wireless Mac authentication, everything works as expected but the radius audit log show:

Module-Failure-Message = "Failed retrieving values required to evaluate condition"

**Comment by fdurand** [comment]
It can be because PacketFence return an access-accept without any vlan id.

**Comment by julsemaan** [comment]
@fdurand 

The issue @lzammit has seems unrelated to a missing VLAN since there is a VLAN in the reply

I'll try to dig into it

**Comment by julsemaan** [comment]
Seems to be failing due to a new variable that was introduced recently in our unlang config:

```
(5358) Fri Jan  4 11:15:50 2019: Debug:     if (&control:PacketFence-Proxied-From == "True") {
(5358) Fri Jan  4 11:15:50 2019: ERROR:     Failed retrieving values required to evaluate condition
```
