### ISSUE TITLE
Radius Accounting: Stop procedure bug 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3881]
Fresh PacketFence 8.2.9 install on CentOS:

Dec 27 14:13:38 testing-c7 acct[2290]: (164) sql: ERROR: rlm_sql_mysql: ERROR 1318 (Incorrect number of arguments for PROCEDURE pf.acct_stop; expected 23, got 21): 42000

**Comment by julsemaan** [comment]
@fdurand, would you be able to look into this?
