### ISSUE TITLE
LDAP source: search attributes is required but not handled in upgrade

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3884]
Either this should be non-required and have no impact on the authentication in FreeRADIUS, or an upgrade script should be provided to upgrade the configuration to the appropriate values

**Comment by nqb** [comment]
Agree with @julsemaan.

**Comment by nqb** [comment]
I also notice that `Username attribute` field is now a dropdown list in place of a string. Consequently, PF will not accept any strings in this field (should be put in `ldap_attributes` in pf.conf)
