### ISSUE TITLE
webadmin: default password length is 4 for created users

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3887]
If you create user(s) without password, size of password generated is 4.

Related to #3879 and ec40e22

Having a password of 4 characters is not acceptable, need to be at least 8 (like before).

**Comment by julsemaan** [comment]
I think 4 is acceptable, perhaps not as a default, but it is acceptable to have a password of a length of 4

So what should be done instead is make the default length 8 characters long but let people choose intentionally lengths that are lower than 8

**Comment by julsemaan** [comment]
I've adjusted the default password length and tested it in the admin

@nqb, let me know if this causes issues, otherwise this is all fixed

**Comment by nqb** [comment]
@julsemaan,

Behavior with your fix when creating users from web admin:
* no password defined: password length of 8
* password defined with 3 characters: password length of 3

On a source with "Create Local Account" checked and a password length of 3, I got a password of 4 characters.

Fine for me. When creating a user with a pre-defined password, we don't call `_generate_password()` method.

**Comment by julsemaan** [comment]
I've removed options 1,2 and 3 from the local account password length as they're useless

**Comment by nqb** [comment]
> I've removed options 1,2 and 3 from the local account password length as they're useless

In this commit: https://github.com/inverse-inc/packetfence/commit/c20382c8892065f0c3195b707d6bc9189b988fd7 ?

**Comment by nqb** [comment]
Ok, I just saw the missing fix for other sources than Potd: https://github.com/inverse-inc/packetfence/commit/7709cd41ea9e0e84f297587862254a05f07deb48

All is fine.
