### ISSUE TITLE
Admin login via AD

### ISSUE THREAD

**Issue by wifispray** [inverse-inc/packetfence#3898]
Hi All,

I believe there is a problem with the way AD based Administrator logins are handled/ managed.

In the AD source you have to specify the attribute being used. For example you might specify "UserPrincipleName". This will allow you to login with someone@example.com. However, if the same user was to try to login with just the username it would not work.

For admin logins could you not specify the attribute being used, but query based on what is inputted?

So... If you get a username formatted as an NAI, you should query the UserPrincipalName. If you get a username formatted as a NtDomain, you use the sAMAccountName. This would be a better logic.

Best Regards,
Wi-Fi Spray

**Comment by fdurand** [comment]
Fixed when introduced search attributes
