### ISSUE TITLE
firewall SSO: less logs by default

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3909]
Following line is very verbose in a setup with firewall SSO: https://github.com/inverse-inc/packetfence/blob/094efae91759c0392741d973b7763cea1a710664/lib/pf/firewallsso.pm#L53

I would like to replace `$logger->info()` by `$logger->debug()`. Agree ?

**Comment by julsemaan** [comment]
Its pretty useful to keep this line for troubleshooting when a user reports that the SSO hasn't been performed

**Comment by nqb** [comment]
I thought there was a `log.conf.d/firewallsso.conf` so I understand your answer.

Would be a nice to have.

**Comment by julsemaan** [comment]
That specific logging line is created by pfqueue so its controlled through that.

And for the pfsso log level, its controllable through conf/caddy-services/pfsso.conf
