### ISSUE TITLE
pfmon: remove useless errors in pfmon.log

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3910]
In `pfmon.log`, there are two errors each 10 minutes:
```
logs/pfmon.log:Jan  8 11:36:07 pfcenstandalone pfmon: pfmon(16271) ERROR: [mac:unknown] error creating SNMP v1 read connection to 192.168.0.1: No response from remote host "192.168.0.1" (pf::Switch::connectRead)
logs/pfmon.log:Jan  8 11:36:03 pfcenstandalone pfmon: pfmon(16271) ERROR: [mac:unknown] error creating SNMP v1 read connection to 192.168.1.0/24: Unable to resolve the UDP/IPv4 address "" (pf::Switch::connectRead)
```
There are related to default network devices with `VoIPLLDPDetect` setting enabled.

To avoid this error, we can disable this setting in `conf/switches.conf.example` for each network device setting `VoIPLLDPDetect=N`.

There is more than one way to do it.

**Comment by julsemaan** [comment]
We could indeed disable this for the 2 example switches
