### ISSUE TITLE
Admin: FingerBank Profiling - Unexpected Error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3924]
Configuration > Compliance > Fingerbank Profiling > General Settings

The administration panel gives the following error even if API Key is provided:

> Error! API Key field is required

Screenshot (Key is masked, but valid during form submission):

![selection_001](https://user-images.githubusercontent.com/3904468/51000131-22383800-14fa-11e9-8cd8-65dacbc67326.png)

**Comment by satkunas** [comment]
This error was generated by opening the config page in 2 separate tabs (identical).

- Step 1 - w/ Tab A: The API Key was cleared and the form was saved.
- Step 2 - w/ Tab B: Attempt to re-enter the API Key using the previously loaded page (not reloaded).

It appears that the error is misguided. In this case th ebackend is expecting onboarding, but receives the form data from post-onboarding. This a stale form is sending the "API Key" with the field name set as `upstream.api_key` while expecting the field name to be only `api_key`. 

IMO the onboarding process and the form after onboarding is completed should use the same field name `upstream.api_key` to avoid this confusion.

**Comment by julsemaan** [comment]
Is it really worth fixing knowing that the next release will deprecate this admin interface?

**Comment by satkunas** [comment]
@julsemaan I just post 'em as I see 'em. That's not my call.

**Comment by julsemaan** [comment]
The new admin is not official, this shall be closed

**Comment by extrafu** [comment]
Just in case we hit some zealots:  is not -> is now
