### ISSUE TITLE
Admin: Profiling Combination User Agent Display

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3925]
When adding a new Compliance > Fingerbank Profiling > Combination the **user_agent** requires the `value`:

![selection_002](https://user-images.githubusercontent.com/3904468/51042077-66264e00-1589-11e9-81d7-7d7747588715.png)

The `user_agent`:
```
sqlite> .schema user_agent
CREATE TABLE "user_agent" (
  "id" varchar(11) NOT NULL,
  "value" varchar(1000) DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  PRIMARY KEY ("id")
);
sqlite> select * from user_agent;
0|Windows||
```

However, when editing the Combination, **user_agent** is displayed as the `id` instead of the `value`:

![selection_003](https://user-images.githubusercontent.com/3904468/51042157-9837b000-1589-11e9-8825-9d4be7c9bc28.png)

**Comment by julsemaan** [comment]
@satkunas 

Can you check if this is still relevant in the new admin ?

**Comment by satkunas** [comment]
@julsemaan no longer relevant. Closing.
