### ISSUE TITLE
Eduroam pfstats test should be eap-peap, eap-tls or eap-ttls

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#3926]
Right now in pfstats we use pap to test eduroam and the password appear in clear text and always fail.
We should use eap-peap, eap-tls or eap-ttls to test the authentication.

**Comment by julsemaan** [comment]
I'm guessing with the ability to specify the username and password to use for testing. That would be even better.

**Comment by fdurand** [comment]
The problem is that the eduroam server can't do pap/chap so we will send some credential in clear text but never able to test the authentication.

**Comment by fdurand** [comment]
I will probably call eapol_test from pfstats.

**Comment by fdurand** [comment]
replaced by status-check
