### ISSUE TITLE
Moving machine account post-creation into a different OU breaks AD  join.

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#3945]
When joining an AD Domain, PacketFence defaults to the 'Computers' OU. Additionally, it is pretty typical for Windows Server admins to move machine accounts between OUs using Active Directory Users and Computers. However, if the machine account for PacketFence is moved outside of the OU it was placed in by winbindd, the join relationship is broken and ntlm auth fails with:

NT_STATUS_NO_TRUST_SAM_ACCOUNT

**Comment by julsemaan** [comment]
This is how samba/winbind behaves when performing this operation.

If you want to have the account in a different OU, you need to specify it during the creation.

After that, the account must stay where it is.
