### ISSUE TITLE
Activation guest e-mail click not available PF8.3

### ISSUE THREAD

**Issue by lukasnasc** [inverse-inc/packetfence#3948]
Guest user receive email, but button not available to click

**Comment by lukasnasc** [comment]
![image](https://user-images.githubusercontent.com/4173100/51489093-78c13400-1d8e-11e9-91e3-a4a35248dc67.png)

**Comment by lukasnasc** [comment]
Log httpd_portal_err show errors:
Use of uninitialized value in string ne at /usr/local/pf/lib/captiveportal/PacketFence/DynamicRouting/Application.pm line 137
and
Use of uninitialized value in concatenation (.) or string at /usr/local/pf/lib/captiveportal/PacketFence/DynamicRouting/Module/Root.pm line 89

**Comment by jrouzierinverse** [comment]
Thank you for reporting.
This has been fixed by 8ba34547471646b1fde6ccec887b68568e310f46.
You can use addons/pf-maint.pl to get the latest fixes.
