### ISSUE TITLE
packetfence-winbindd: infinite chroot command 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3950]
On PF 8.2.1 or PF 8.3 running on CentOS 7.6, I see following messages in `/var/log/messages`:

```
Jan 22 17:43:21 pf systemd: Started Session c17965440 of user root.
Jan 22 17:43:21 pf winbindd[12428]: [2019/01/22 16:43:21.858193,  0] ../lib/util/pidfile.c:197(pidfile_create)
Jan 22 17:43:21 pf winbindd[12428]:  ERROR: winbindd is already running. File /usr/local/pf/var/run/domain/winbindd.pid exists and process id 15493 is running.
```

in `journalctl` of `packetfence-winbindd`:
```
Jan 22 17:44:38 pf.domain.local sudo[17501]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/chroot /chroots/domain /usr/sbin/winbindd -s /etc/samba/domain.conf -l /var/log/sambadomain --foreground
```

These messages appear each second and congest disk space on servers. 

Samba packages have been upgraded in CentOS 7.6, I suspect that PF's code doesn't take care of a change to manage processes.

**Comment by nqb** [comment]
It looks like if I stop `packetfence-winbindd` through `systemd`, I kept following process:
```
root     16040  0.0  0.0 243112   320 ?        S     2018   0:00 sudo chroot /chroots/domain /usr/sbin/winbindd -s /etc/samba/domain.conf -l /var/log/sambadomain --foreground
root     16047  0.0  0.0 398160  1088 ?        Ss    2018   0:31 /usr/sbin/winbindd -s /etc/samba/domain.conf -l /var/log/sambadomain --foreground
root     16138  0.0  0.0 425052  2536 ?        S     2018   0:10 /usr/sbin/winbindd -s /etc/samba/domain.conf -l /var/log/sambadomain --foreground
```

File `/usr/local/pf/var/run/domain/winbindd.pid` still presents with `16047` value.

**Comment by julsemaan** [comment]
Same kind of loop happens when the join isn't valid anymore.

Will relax the loop to have a delay between attempts and I'll see why the process isn't detected as running.

**Comment by julsemaan** [comment]
I've upgraded all available packages while the winbindd processes were running and they stayed managed by systemd and kept working. Then I restarted packetfence-winbindd and everything restarted as it should.

Have you upgraded PacketFence at the same time as the OS? Or is there something you did other than a simple OS update before this started showing up?

**Comment by jrouzierinverse** [comment]
My guess on this issue one of the two.
*  Since the child restart is being done by the unsafe signal handler the parent is getting stuck.
*  When restarting child the child handler is not being blocked.

My suggestion is to use the child management pattern that is in the other perl daemons.
The child handler only records the child death.
Then in the main loop of the parent a new child is created.

**Comment by julsemaan** [comment]
@jrouzierinverse 

Since you initially wrote the winbindd-wrapper and you're more used to the service pattern for the perl services, would you be able to do the fix for this?

**Comment by jrouzierinverse** [comment]
@julsemaan the history says otherwise
https://github.com/inverse-inc/packetfence/commits/devel/sbin/winbindd-wrapper

**Comment by jrouzierinverse** [comment]
yes I am able to provide the fix.

**Comment by julsemaan** [comment]
My goodness I completely forgot I wrote that. I guess it explains why it behaves incoherently

**Comment by extrafu** [comment]
Yup, a true arborescence of bugs.

**Comment by julsemaan** [comment]
@nqb 

Can you provide more details around replicating the bug.

I already attempted the samba upgrade during a normal OS update like you've described with no problem so I'd need more details to be able to replicate this issue

**Comment by nqb** [comment]
@julsemaan,

I didn't find how to reproduce this bug for now. What I can say is: this bug is present on all new PF installs I did under 8.2.1 or 8.3 with CentOS 7.6. Consequently, this bug doesn't seem related to an OS upgrade because I got it after a fresh install on CentOS 7.6.

**Comment by nqb** [comment]
To reproduce: fresh install of PF 8.3 (stable, standalone) under CentOS 7.6 with a first attempt to do a domain join that failed.

Process tree if I run several times: `ps -eo pid,cmd --forest`
```
[..]
11202 winbindd-wrapper
 1250  \_ sudo chroot /chroots/inverse /usr/sbin/winbindd -s /etc/samba/inverse.conf -l /var/log/sambainverse --foreground
 1251      \_ /usr/sbin/winbindd -s /etc/samba/inverse.conf -l /var/log/sambainverse --foreground
[..]
11202 winbindd-wrapper
 1420  \_ sudo chroot /chroots/inverse /usr/sbin/winbindd -s /etc/samba/inverse.conf -l /var/log/sambainverse --foreground
[..]
11202 winbindd-wrapper
[..]
11202 winbindd-wrapper
 1729  \_ sudo chroot /chroots/inverse /usr/sbin/winbindd -s /etc/samba/inverse.conf -l /var/log/sambainverse --foreground
```

**Comment by nqb** [comment]
In `/var/log/messages`:
```
Jan 28 13:08:59 pfcenstable systemd: Started Session c17834 of user root.                                                                             │
Jan 28 13:08:59 pfcenstable winbindd[16169]: [2019/01/28 12:08:59.400874,  0] ../source3/winbindd/winbindd_cache.c:3160(initialize_winbindd_cache)    │
Jan 28 13:08:59 pfcenstable winbindd[16169]:  initialize_winbindd_cache: clearing cache and re-creating with version number 2                         │
Jan 28 13:08:59 pfcenstable winbindd[16169]: [2019/01/28 12:08:59.403331,  0] ../source3/winbindd/winbindd_util.c:1264(init_domain_list)              │
Jan 28 13:08:59 pfcenstable winbindd[16169]:  Could not fetch our SID - did we join?                                                                  │
Jan 28 13:08:59 pfcenstable winbindd[16169]: [2019/01/28 12:08:59.403407,  0] ../source3/winbindd/winbindd.c:1360(winbindd_register_handlers)         │
Jan 28 13:08:59 pfcenstable winbindd[16169]:  unable to initialize domain list
```

**Comment by nqb** [comment]
@chifu1234,

Same behavior with your patch.

**Comment by nqb** [comment]
I see this bug under two situations:
- the first I reported: domain join successful
- the second I reported: domain join failed

**Comment by julsemaan** [comment]
@nqb 

Is it possible that your domain join is just getting corrupted because you're joining 2 servers with the same account name in the AD ?

**Comment by nqb** [comment]
Hello @julsemaan,

I don't think so. I notice this behavior on several customers/installations.

**Comment by julsemaan** [comment]
You'll then need to troubleshoot why the domain join is failing in the winbindd logs that are in the chroots.

The issue for the domain join failure is external to the winbindd-wrapper so @jrouzierinverse's fix will correct the "fill the disk" issue but the join will still fail

**Comment by nqb** [comment]
@julsemaan, of course.

I just want to mention that I got same behavior with a failed domain and a successful domain join but error messages are different.

**Comment by jrouzierinverse** [comment]
@nqb have you used the new pull request as of yet? https://github.com/inverse-inc/packetfence/pull/3959/

**Comment by nqb** [comment]
@jrouzierinverse,

Your PR fixed this issue. I didn't have winbindd messages in syslog. 

However, I notice that when I try to do a domain join/rejoin from the web admin, `perl` and `pfcmd.pl` use an important quantity of CPU time during the domain join/rejoin. I don't know if it's related to your PR. If I start/stop `winbindd` with `pfcmd service winbindd start/stop`, I don't get this behavior.

**Comment by julsemaan** [comment]
@nqb 

It has always been the case. Doing a rejoin requires the creation of many configuration files and many commands outside of winbindd restart are ran

**Comment by nqb** [comment]
Ok @julsemaan. So we can merge and cherry-pick in maintenance if @jrouzierinverse agrees.

**Comment by jrouzierinverse** [comment]
@julsemaan were you able to test it also?
