### ISSUE TITLE
Portal displays latin characters incorrectly

### ISSUE THREAD

**Issue by MuriloCalegari** [inverse-inc/packetfence#3952]
Hi,

Since updating to v8.3, portal isn't displaying all characters correctly, as seen in these images:

![image](https://user-images.githubusercontent.com/38005452/51598964-c3a18f80-1ee5-11e9-9354-7ae336ea38f8.png)

![image](https://user-images.githubusercontent.com/38005452/51599010-d74cf600-1ee5-11e9-8a6f-f28974d33c88.png)

![image](https://user-images.githubusercontent.com/38005452/51599056-ed5ab680-1ee5-11e9-9ff9-2bb66017f6db.png)

**Comment by julsemaan** [comment]
Likely related to the UTF-8 migration @jrouzierinverse has led

@jrouzierinverse, can you look into this?

**Comment by MuriloCalegari** [comment]
I've got some custom code in /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Form/Authentication.pm with some hardcoded strings, if I save the file in Windows 1252 encoding, everything works fine. Prior to that it was utf-8.

**Comment by lukasnasc** [comment]
I try command:

 iconv -f US-ASCII -t WINDOWS-1252 Authentication.pm > AuthenticationII.pm

file -i AuthenticationII.pm
AuthenticationII.pm: text/plain; charset=us-ascii

Not work

**Comment by nqb** [comment]
I updated priority cause many users report this issue.

@jrouzierinverse, have you a fix or a workaround ?

**Comment by julsemaan** [comment]
The conversion script *should* have taken care of that so its clearly something missing from it.

@jrouzierinverse I guess we should revisit this script to perform the encoding conversion for the custom files as well.
