### ISSUE TITLE
Portal e-mail registration pt-br accented words with strange characters

### ISSUE THREAD

**Issue by lukasnasc** [inverse-inc/packetfence#3956]
After run the comand "/usr/local/pf/addons/pf-maint.pl" accented words with strange characters like below:

**Se vocÃª tem perguntas sobre esta pÃ¡gina, contate sua equipe de suporte local para ter assistÃªncia. Por favor forneÃ§a a seguinte informaÃ§Ã£o:**

**Comment by lukasnasc** [comment]
Default language: Portuguese

**Comment by MuriloCalegari** [comment]
Same as #3952
