### ISSUE TITLE
Ubiquiti::Unifi switch type is incompatible with UniFi Switches

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#3957]
I have had success with using the "Ubiquiti::Unifi" switch type for UniFi APs. Is there any immediate reason why this switch type won't also work for UniFi Switches? If there is, it might be better to change the GUI to reflect that "Unifi Controller" is only applicable when defining UniFi APs.

I am getting the following error when using "Unifi Controller" switch type and a UniFi Switch.

```
Module-Failure-Message = "rest: Server returned:"
Module-Failure-Message = "rest: {\"Reply-Message\":\"Network device does not support this mode of operation\",\"control:PacketFence-Eap-Type\":4,\"control:PacketFence-Authorization-Status\":\"allow\",\"control:PacketFence-Mac\":\"00:25:64:f8:21:7b\",\"control:PacketFence-Switch-Ip-Address\":\"192.168.10.61\",\"control:PacketFence-Request-Time\":1548357628,\"control:PacketFence-IfIndex\":\"4\",\"control:PacketFence-UserName\":\"002564F8217B\",\"control:PacketFence-Connection-Type\":\"Ethernet-NoEAP\",\"control:PacketFence-Switch-Id\":\"192.168.10.61\",\"control:PacketFence-Switch-Mac\":\"f0:9f:c2:1a:23:ab\"}"
```

**Comment by julsemaan** [comment]
I believe that their firmware is very different, at least that was true last time we checked.

**Comment by rcmcdonald91** [comment]
Firmware is nearly identical, sans some lite Layer3 capabilities. UniFi Switches also have read-only SNMP. UniFi switches seem to work fine with the EdgeSwitch switch type class.

**Comment by julsemaan** [comment]
The UniFi module is made for wireless controller. Perhaps if Ubiquiti is starting to brand wired equipment with that name, the wireless module could be renamed but for Ubiquiti wired switches, the edge switch module should be used like you described
