### ISSUE TITLE
"Switch is not managed by PacketFence" when using MAC switch identifier

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#3960]
When defining switches using MAC addresses (instead of IP addresses), PacketFence returns "Switch is not managed by PacketFence".

I'm using Ubiquiti UniFi APs and Switches.

**Comment by julsemaan** [comment]
Please provide the content of all tabs of an audit log entry for a RADIUS request

**Comment by julsemaan** [comment]
no info provided, closing
