### ISSUE TITLE
French configurator not working

### ISSUE THREAD

**Issue by Dataclic** [inverse-inc/packetfence#3964]
Please note
-----------
Github issues are for reporting/tracking DEVELOPMENT ISSUES. For anything related to getting help in running PacketFence, or anything else not related to DEVELOPMENT, please use the mailing-list (https://lists.sourceforge.net/lists/listinfo/packetfence-users).

Any issues not related to DEVELOPMENT - WILL BE CLOSED -

How to properly file an issue
-----------------------------
* TITLE: Use a title that globally describes the issue but ease future lookup for reference. ie: (web admin): Not able to delete Zayme admin account.
* DESCRIPTION: No need for a novel but it should explain how to replicate if required to, otherwise gives the big picture. Also explain impacted services and possible resolution (if any).
* ASSIGNEES: Set the approprite assignee(s) (if applicable).
* LABELS: Use appropriate(s) labels. Make sure to have a "Type" (GREEN) and a "Priority" (RED).
* MILESTONE: Set the appropriate milestone (if applicable, and most of the time IT IS applicable).

* If the issue needs to be discussed internally in a meeting, add the "Status: Question" label.

**Comment by Dataclic** [comment]
Hello,

When accessing https://ipadress:1443 on a french computer i can't pass trough the configurator when i clic next button. The first page is every time reloaded.

I fix it in changing language of the os.

**Comment by nqb** [comment]
Hello @Dataclic,

Under which OS ?
Did you apply maintenance patches with `pf-maint.pl` ?

**Comment by Dataclic** [comment]
PacketFence-ZEN-8.3.0.zip on a vm
and
Version 8.3.0 on centos 7 

no, i did not apply "pf-maint.pl"

**Comment by nqb** [comment]
This bug has been already fixed in maintenance/8.3 branch. Just run: `/usr/local/pf/addons/pf-maint.pl` and restart PF services.
