### ISSUE TITLE
Portal not encoding latin characters correctly on user info

### ISSUE THREAD

**Issue by MuriloCalegari** [inverse-inc/packetfence#3965]
![image](https://user-images.githubusercontent.com/38005452/51900991-bed55380-239d-11e9-9b62-9e8b69acbd89.png)

![image](https://user-images.githubusercontent.com/38005452/51901035-de6c7c00-239d-11e9-9f99-abce6dc82a02.png)

**Comment by nqb** [comment]
Hello @MuriloCalegari,

Did you get this behavior only when you edit fields ?

**Comment by MuriloCalegari** [comment]
Both editing fields and populating from AD

**Comment by nqb** [comment]
A user report to me that fields are correct in web admin but when editing, there is always an encoding issue. He tested on Portal Modules, portal_modules.conf is in UTF-8.

@jrouzierinverse, could you fix this issue ?

**Comment by MuriloCalegari** [comment]
After applying `/usr/local/pf/addons/upgrade/to-8.3-conf-latin1-to-utf8.sh` portal_modules.conf is in UTF-8 (which results in incorrect display in web gui);

After editing through web admin, it is being saved as iso-8859-1 (which is being displayed correctly).

**Comment by julsemaan** [comment]
This has been addressed by @jrouzierinverse in 6a443f1891450621e730abea50e0e14cb9e587d4

Not sure why that wasn't cherry picked in the maintenance as previously discussed.

I'll check this out with him for the issue around saving, this should fix the issue of saving the portal modules.

Now as for the issue of populating fields from the AD and editing the person, we'll have to check this out separately as the commit above only addresses configuration and not the database

**Comment by jrouzierinverse** [comment]
This requires multiple changes that cannot fit into a +1 release.

**Comment by extrafu** [comment]
Similar to #4514
