### ISSUE TITLE
dashboard: graphs not draw under 8.3

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3973]
On 8.3, I notice this display on several customers after an upgrade to 8.3 **or** after a fresh install on 8.3 (CentOS 7 or Debian).

![screenshot from 2019-01-29 08-35-48](https://user-images.githubusercontent.com/10830260/52041615-38567880-253b-11e9-9291-b6c810e4c916.png)

Netdata version is 1.10.0.

On all situations, I'm able to get data in DB with following SQL requests:
```sql
; registered_per_role
select name, count(distinct node.mac) from node_category left join node on node.category_id=node_category.category_id and node.status='reg' group by node_category.category_id;
; connected_per_connection_type
select connection_type, count(distinct mac) from locationlog where end_time is null group by connection_type;
```

On a fresh install, I have:
 * data under `/var/cache/netdata/packetfence.devices.registered_per_role/` but not upgraded since install
 * no dir called `/var/cache/netdata/packetfence.devices.connected_per_connection_type/`

If I run following commands (in this order):
```shell
pfcmd service netdata restart # nothing change
pfcmd service pfstats restart
```
I got graphs on dashboard. Dir `/var/cache/netdata/packetfence.devices.connected_per_connection_type/` has been created and data under `/var/cache/netdata/packetfence.devices.registered_per_role/` has been refreshed.

Before running this two commands, I restart PF services with `pfcmd service pf restart` many times without effect.

**Comment by julsemaan** [comment]
Is this still relevant for 9.0 ?

**Comment by nqb** [comment]
Not for CentOS on new admin.

**Comment by julsemaan** [comment]
Lets close this then since the efforts are now focused on the new admin

**Comment by nqb** [comment]
Not for Debian too.
