### ISSUE TITLE
AD source: updating a password don't update ldap_packetfence.conf

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3974]
On 8.3, if I update the `Password` field for a LDAP source and save my changes, I need to run: 
```
pfcmd service radiusd generateconfig
``` 
to update password in `/usr/local/pf/raddb/mods-enabled/ldap_packetfence`.

Before running the `generateconfig` command, I ran: 
```
pfcmd pfconfig show 'resource::authentication_config_hash()'
```
The password field has been updated.

**Comment by fdurand** [comment]
If you change the password of something else you need to restart radius and when you restart radius it generate the file ldap_packetfence.
