### ISSUE TITLE
AD source: wrong bind password prevent RADIUS to start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3975]
On 8.3, if you specify an incorrect password (for your binddn) in a LDAP/AD source and restart `radiusd`, FreeRADIUS will not start due to a wrong bind:
```
# /usr/sbin/radiusd -d /usr/local/pf/raddb -n auth -fm -X
rlm_ldap (AD_source): Opening additional connection (0), 1 of 10 pending slots used
rlm_ldap (AD_source): Connecting to ldap://10.0.0.10:389
rlm_ldap (AD_source): Waiting for bind result...
rlm_ldap (AD_source): Bind credentials incorrect: Invalid credentials
rlm_ldap (AD_source): Server said: 80090308: LdapErr: DSID-0C090334, comment: AcceptSecurityContext error, data 52e, vece. 
rlm_ldap (AD_source): Opening connection failed (0)
rlm_ldap (AD_source): Removing connection pool
/usr/local/pf/raddb/mods-enabled/ldap_packetfence[5]: Instantiation failed for module "AD_source"
```
FreeRADIUS should start.

**Comment by fdurand** [comment]
It's like FreeRADIUS works, test your ldap bind in the authentication source first.
Or open an issue on the FreeRADIUS github project.

**Comment by nqb** [comment]
We should **at least** warn users to restart their RADIUS services after editing a LDAP source.

Before 8.3, you could modify your LDAP source without any effect on RADIUS. Now, any change in a LDAP source can break RADIUS services when they will be restarted. From my point of view, it's a big change for users not mentioned in NEWS or UPGRADE guide for 8.3.

Moreover, it's should be possible to disable this behavior if you don't want to use this kind of RADIUS features.

**Comment by fdurand** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/39d214132e05d1dd9c340fd6fa979b6c6d5df6b6

**Comment by nqb** [comment]
Due to #4114, LDAP configuration for FreeRADIUS is generated only if a `Search Attribute` is defined.
