### ISSUE TITLE
Can we Please add a new Role Rule "Condition" for EAPTLS authentication source, many thanks. is:open label:"Type: Bug" 

### ISSUE THREAD

**Issue by centrasupport** [inverse-inc/packetfence#3984]
Hi Team,

I am currently doing a Wireless BYOD project, and we need to let PF set a role rule based on a certificate Extended Key Usage. We are using MSPKI so a new user certificate template was duplicated and this certificate template name is "BYOD", a new custom Application Policies was added to this certificate template. Hence, any cert that is issued based this certificate template will be added a new OID on the EKU filed.  But the OID is very long in length, so it cannot be shown in the Role Rule Condition", for example, the correct OID is " "1.3.6.1.4.1.311.21.8.16348877.10593049.7950239.4591926.10573679.100.5535905.13363818", but if only show as "1.3.6.1.4.1.311.21.8.16348877.10593049.7950239.4591926.10573679.100.5535905.133", it lost come digits. When I check the Audit log, it can be found that the filed "TLS-Client-Cert-X509v3-Extended-Key-Usage-OID" contains the correct value. 
Therefore, can someone please to add a new field in the role rule condition of "TLS-Client-Cert-X509v3-Extended-Key-Usage-OID", so we can let PF give the clients device a correct role by using this field.

Or if PF could check a certificate template value or OID that would be perfect.
Or, it is can be solved if PF could show the correct OID to the "TLS-Client-Cert-X509v3-Extended-Key-Usage".

Thanks in advance!

Kind Regards,

Louis

**Comment by fdurand** [comment]
Simply add the attribute here: https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Authentication/Source/EAPTLSSource.pm#L37

**Comment by julsemaan** [comment]
I think you can even add it in the PF configuration as well:
https://github.com/inverse-inc/packetfence/blob/devel/conf/pf.conf.defaults#L1126

Unless that config parameter doesn't do what I think it does
