### ISSUE TITLE
patched maintenance pfdns not working in inline mode: returning MAC 00:00:00:00:00:00

### ISSUE THREAD

**Issue by caralo** [inverse-inc/packetfence#3985]
Debian 8.11, PF 8.1 with latest patches from pf-maint.pl including golang binaries.
After updating pfdns, inline connections don´t work anymore. **It always returns MAC 00:00:00:00:00:00**
pfdns.log:
Feb  5 13:29:19 pf1 pfdns[11695]: 192.168.18.212 - [05/Feb/2019:13:29:19 +0100] 
"A IN detectportal.firefox.com. udp 42 false 512" NOERROR qr,aa,rd 58 4.863659ms
Feb  5 13:29:19 pf1 pfdns[11695]: Returned portal for MAC 00:00:00:00:00:00 with
 IP 192.168.18.212"

If we go back to the original pfdns binary, then a real mac is returned and the inline dns works.
pfdns.log:
"Feb  5 13:42:18 pf1 pfdns[13694]: 192.168.18.212 - [05/Feb/2019:13:42:18 +0100] 
"A IN detectportal.firefox.com. udp 42 false 512" NOERROR qr,aa,rd 58 2.727052ms
Feb  5 13:42:18 pf1 pfdns[13694]: Returned portal for MAC 00:26:9e:a2:44:95 with
 IP 192.168.18.212"

**Comment by fdurand** [comment]
Fixed in maintenance/8.1 https://github.com/inverse-inc/packetfence/commit/04551db85ef2a7e8de93e04bb6e902edce6cd961
What tomorrow to apply the maintenance.

**Comment by caralo** [comment]
Working great now.
