### ISSUE TITLE
config/syslog_parser lines and loglines ambiguity 

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3989]
The endpoint GET `api/config/syslog_parsers` returns both `lines` and `loglines`. This is ambiguous. It appears that they have a similar purpose, but we should only require one (not both).
```
{
  "items": [
    {
      "id": "regex",
      "lines": null,
      "loglines": null,
      ...
    }
  ]
}
```
* Should `lines` or `loglines` be used?
* If `lines` is used, does it need to be a String, or a Javascript Array for each line?
* If `loglines` is used, does it need to be a String, or a Javascript Array for each line?

**Comment by jrouzierinverse** [comment]
Fixed by 163f187c17f1ebcbf6a4e22c8372b9acd477ae03
