### ISSUE TITLE
API Endpoint - config/syslog_forwarders missing fields

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3990]
APi Endpoint at GET `config/syslog_forwarders` and `config/syslog_forwarder/:id` missing fields:
 * proto
 * host
 * port

**Comment by satkunas** [comment]
Endpoints are also not documented in OpenAPI spec.

**Comment by julsemaan** [comment]
@satkunas 

It seems that this is only missing from the local syslog forwarder

If the only issue with this is the missing spec now, lets change the title or open a new issue

**Comment by julsemaan** [comment]
After discussion with @satkunas, its not missing since the local source doesn't have these fields.

He will adjust accordingly

Will change this issue to talk about the spec only and push to 9.1

**Comment by julsemaan** [comment]
Actually will close and open a new issue for the spec
