### ISSUE TITLE
Config Domains API Endpoint requires additional fields

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3997]
The domains endpoint at `config/domains` and `config/domain/:id` requires the join success boolean and string error message as shown in the following screenshot.

![selection_011](https://user-images.githubusercontent.com/3904468/52571964-af65f980-2de4-11e9-881b-1afa9cb0f970.png)

**Comment by julsemaan** [comment]
Did the code in 4480ab60d56ddd51b8b3a23b2f0469713e4ef53e

Its another API endpoint that is called on the domain resource and its not included in the listing so that all domains can be done individually and we don't block listing while waiting for communication with the domain

Ex:
```
sbin/pfperl-api get /api/v1/config/domain/inverse/test_join
```

**Comment by julsemaan** [comment]
Leaving open since we're missing the spec but this is solved

**Comment by julsemaan** [comment]
@satkunas, you can have fun with the new API call
