### ISSUE TITLE
User Agents Share Unknown User Agents not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#400]
When you try to share a new user agent, you get : 

"Error! An error condition has occured. See server side logs for details."

Tested on debian 7 and Packetfence 4.6.2

**Comment by whitx** [comment]
Tested on Centos 6.6, works fine

**Comment by lzammit** [comment]
Mar 02 15:56:09 httpd.admin(11412) ERROR: Caught exception in pfappserver::Controller::Config::UserAgents->upload "Can't locate PHP/Serialization.pm in @INC (@INC contains: /usr/local/pf/lib /usr/local/pf/html/pfappserver/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl . /etc/apache2) at /usr/local/pf/html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/UserAgents.pm line 48." (pfappserver::PacketFence::Controller::Root::end)

**Comment by jrouzierinverse** [comment]
Reassigning to @fdurand
