### ISSUE TITLE
Can't assign role via API for a user

### ISSUE THREAD

**Issue by Alsheyra** [inverse-inc/packetfence#4000]
Hello !

We try to assign a role to a user via the packetfence's API.

Command used:

curl -X PUT -k -H 'Authorization: [token]' -i 'https://[linkpacketfence]/api/v1/user/Test-API/password' --data '{"access_duration":"8h","category":"default","expiration":"2019-09-09","password":"Example","pid":"Test-API","valid_from":"2019-05-05"}'

Also tested in PATCH.

We also tried to create a user via the API and assigned a password and role with a POST but no role is assigned. We didn't see the field "role" in the webadmin.

Even though the command gives us a result of 200, the role field is not displayed in the webadmin of packetfence.

![2019-02-12 11_48_41-restclient](https://user-images.githubusercontent.com/39260915/52630848-98470a80-2ebd-11e9-8560-20e9ff04fbbf.png)

If we assign via the webadmin and try to update via the API, the field also disappears.

Assigned by Webadmin : 

![2019-02-12 12_01_03-administrateur - packetfence](https://user-images.githubusercontent.com/39260915/52631002-fd9afb80-2ebd-11e9-9354-7e762c9dd58f.png)

Put or Patch from API : 

![2019-02-12 11_59_43-administrateur - packetfence](https://user-images.githubusercontent.com/39260915/52631012-01c71900-2ebe-11e9-958d-e5c0e14a5eb4.png)

We tried different roles: default, guest, voice and some role created by us as Test.

All other fields work perfectly via user/password's API (access_duration,expiration,..).

We are on packetfence 8.2 under CentOS and clustered with 3 nodes.

**Comment by nqb** [comment]
Hello,

Provide us **exact** steps to reproduce the issue.
Did you apply maintenance patchs on your 8.2 version ?

**Comment by Alsheyra** [comment]
Yes I applied maintenance patch.

Step is simple. 

- Try to update a role for a user via API (PATCH or PUT)

`curl -X PATCH "https://[IP PACKETFENCE]/api/v1/user/[USER-ID]/password" -k -H "Authorization: TOKEN" -H "accept: */*" -H "Content-Type: application/json" -d "{"access_duration":"8h","access_level":"NONE","category":"default","expiration":"2019-09-09","login_remaining":0,"password":"string","pid":"[USER-ID]","sponsor":false,"valid_from":"2019-05-05"}"`

- Or create a new user and create password (with a role) via API (POST)

```
curl -X POST "https://[IP PACKETFENCE]/api/v1/users" -k -H "Authorization: TOKEN" -H "accept: */*" -H "Content-Type: application/json" -d "{ "company": "Test-API", "email": "Test-API", "firstname": "Test-API", "lastname": "Test-API", "nickname": "Test-API", "notes": "Test-API", "pid": "[USER-ID]", "sponsor": "admin"}"

curl -X POST "https://[IP PACKETFENCE]/api/v1/user/[USER-ID]/password" -k -H "Authorization: TOKEN" -H "accept: */*" -H "Content-Type: application/json" -d "{"access_duration":"8h","access_level":"NONE","category":"default","expiration":"2019-09-09","login_remaining":0,"password":"string","pid":"[USER-ID]","sponsor":false,"valid_from":"2019-05-05"}"
```

For define a role the name's field is "category" and in the documentation we should put a string.

![2019-02-12 14_00_41-window](https://user-images.githubusercontent.com/39260915/52637113-a6515700-2ece-11e9-9083-e4d1bbd6cb82.png)

I tried with "default", "voice", "guest", "REJECT" but nothing work. It's the same with role created by us.

**Comment by Alsheyra** [comment]
After some research we need to use role's ID (example : default is 1, guest is 2, ...).

I found also that in my database new role created by an administrator isn't a continuos id (like 6,7,8).
![2019-03-01 13_51_04-keybox - composite terms](https://user-images.githubusercontent.com/39260915/53639310-1f6be080-3c29-11e9-84b7-ea3b269df5dc.png)

Can you add the functionality to display "id role" into webadmin.
And change the documentation about this. It's not a string but an integer or add a user's role from the role's name via API.

**Comment by julsemaan** [comment]
its actually the same issue that @cgx raised 2 days ago (#4304) already assigned to @jrouzierinverse 

When #4304 gets addressed by @jrouzierinverse, this will be fixed

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by julsemaan** [comment]
We've made the GET consistent with the POST/PUT and displaying the ID of the category field

The spec has also been updated in de9efff
