### ISSUE TITLE
New Unified API needs an auditlog

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4004]
The new Unified API needs to have an audit log since the new admin will consume it so if we want to keep the feature of the admin audit log, the Unified API needs to be adjusted.

We'll have to discuss on whether this should be on the API frontend layer and be pretty generic or should be in the backends themselves (Perl only for now since it does most if not all the admin tasks) with a format that resembles more what we currently have.

**Comment by jrouzierinverse** [comment]
Are you talking about logs/httpd.admin.audit.log?

**Comment by julsemaan** [comment]
Yes that is correct

**Comment by jrouzierinverse** [comment]
Questions.

* Should this be a new database table instead of a file?
* Do we only care about actions that modifies a resource? (I assume yes)

Thoughts
* Does caddy provide a way to inspect the response?
* If we are to do this at the pfperl-api level. 
  Then the user in the TokenInfo needs to be passed down.

**Comment by extrafu** [comment]
I think it should be in a database table similar to the RADIUS Audit Log and should be exposed in the Auditing tab from the Web GUI.

**Comment by julsemaan** [comment]
> Should this be a new database table instead of a file?

As long as its not a key/value table and that its searchable easily, I'd say we could go in the DB

> Do we only care about actions that modifies a resource? (I assume yes)

That could be argued. I had customers that explicitly requested all actions in the admin to be logged. That could be configurable

> Does caddy provide a way to inspect the response?

Caddy itself no but nothing prevents us from extending the authorization layer to be able to inspect the action and record it

> If we are to do this at the pfperl-api level. Then the user in the TokenInfo needs to be passed down.

Should be fairly easy to do if we decide this

**Comment by jrouzierinverse** [comment]
> > Should this be a new database table instead of a file?
> 
> As long as its not a key/value table and that its searchable easily, I'd say we could go in the DB
> 
> > Do we only care about actions that modifies a resource? (I assume yes)
> 
> That could be argued. I had customers that explicitly requested all actions in the admin to be logged. That could be configurable
> 
> > Does caddy provide a way to inspect the response?
> 
> Caddy itself no but nothing prevents us from extending the authorization layer to be able to inspect the action and record it
> 

If we do it at the authorization layer it seems that we do not have access to the status code.

> > If we are to do this at the pfperl-api level. Then the user in the TokenInfo needs to be passed down.
> 
> Should be fairly easy to do if we decide this

**Comment by julsemaan** [comment]
Why wouldn't we have the access to the status code?

The API frontend terminates the SSL connection so everything in the HTTP headers along with the body of both the request and the response can be seen

**Comment by jrouzierinverse** [comment]
This has been taken care of by feature/admin_api_audit_log
