### ISSUE TITLE
Wrix Location schema

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4005]
Wrix Locations currently use Title_Case.

(https://github.com/inverse-inc/packetfence/blob/devel/db/pf-schema-8.3.0.sql#L1001)

We'll need to change this to snake_case in:
 * Pfappserver
 * Perl 
 * Database schema

**Comment by jrouzierinverse** [comment]
The naming was done this way to match the schema from the Wrix specification.

**Comment by julsemaan** [comment]
IMO this is a non-issue since I think we should follow WRIX's standard for field naming
