### ISSUE TITLE
API Endpoints not url decoding %2F

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4008]
Switches and Switch Groups allow a CIDR identifier (eg: 192.168.0.1/24). This includes a '/' which needs to be escaped when using the identifier in the API path. The API does not url decode.

```
# /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/source/switch/192.168.1.24%2F24 | jq
{
  "errors": [],
  "message": "Unknown path /api/v1/config/source/switch/192.168.1.24%2F24",
  "status": 404
}
```

**Comment by jrouzierinverse** [comment]
Wrong path /api/v1/config/source/switch/192.168.1.24%2F24 -> /api/v1/switch/192.168.1.0%2F24

```bash
sbin/pfperl-api get -M OPTIONS /api/v1/config/switch/192.168.1.0%2F24
```

**Comment by satkunas** [comment]
Issue still exists w/ haproxy.

Request:
```
Request URL: https://packetfence:1443/api/v1/config/switch/192.168.1.0%2F24
Request Method: GET
```
Response Body:
```json
{"errors":[],"message":"Unknown path \/api\/v1\/config\/switch\/192.168.1.0\/24","status":404}
```

**Comment by jrouzierinverse** [comment]
Combination of proxies rewrites and restful URLs with special characters has the potential to make our API brittle.

If companies ever put a proxy in front of the PacketFence Admin the api can break.

**Comment by jrouzierinverse** [comment]
The problem is also with caddy
@julsemaan the commit from caddy to fix that https://github.com/mholt/caddy/commit/faa5248d1f1c73a1b5ed61a5a321319adae04f5f 
Cannot be simply patched on our version of caddy.

**Comment by julsemaan** [comment]
@jrouzierinverse raised a point were a proxy between the client and the server could also cause this issue.

So, should we change the identifier for switch ranges so they don't have a slash in them or should we adjust caddy to support it properly.

I'm fine with both, its just that I don't want to jump into a caddy update unless that is the route everyone is happy with

**Comment by julsemaan** [comment]
@satkunas @cgx @jrouzierinverse 

What are we doing we this based on my previous comment?

**Comment by jrouzierinverse** [comment]
The quickest way to handle this is to escape in the frontend while we are figuring out the best solution for caddy.
I can add support in the API convert a '-' to a '/'  for the id.
Also fix up the location header on create.

However we should either fix caddy or upgrade it.

**Comment by jrouzierinverse** [comment]
We now convert a '-' to a '/' for the id.
@satkunas can you do that in the front end?

**Comment by jrouzierinverse** [comment]
We now convert a '~' to a '/' for the id per request of @satkunas

**Comment by extrafu** [comment]
@satkunas Have you updated the GUI part of it?

**Comment by julsemaan** [comment]
@satkunas has addressed this in devel
