### ISSUE TITLE
AD authentication problem - Logon Workstation

### ISSUE THREAD

**Issue by amiirrmm** [inverse-inc/packetfence#4013]
Hi

I have pf joint to my active directory. everything works well but when on my AD I set a logon workstation for a user, that user cannot get authenticated on pf.

I mean on my AD, the user properties, account, Logon To, the logon Workstations should be set to all computers and if I set a computer name, the packetfence says the user name/password is incorrect.

Is this a bug or I should define something special in this section? I have used my server's name: "packetfence" and/or the uses's computer name, with no luck. 

Thanks! 

![ad](https://user-images.githubusercontent.com/45257636/53080223-69f4ab00-350d-11e9-9f58-d30d582a82c5.JPG)

**Comment by nqb** [comment]
Hello @amiirrmm,

I suppose this is caused by the `ntlm_auth` performed by FreeRADIUS which did not use the `--workstation` option of `ntlm_auth`

With an account that has the LDAP userWorkstations attributes, try following command from PF server:
```
ntlm_auth --request-nt-key --domain=MY_DOMAIN --username=testaccount1
ntlm_auth --request-nt-key --domain=MY_DOMAIN --username=testaccount1 --workstation=NAME_OF_WORKSTATION
```
Second command should work.

**Comment by amiirrmm** [comment]
Thank you @nqb for your quick reply.

I constantly receive this reply. what am I doing wrong? 


`could not obtain winbind separator!
Reading winbind reply failed! (0x01)
:  (0x0)
`

I also run wbinfo -p and receive this: "could not ping winbindd!"

**Comment by nqb** [comment]
Please send an email on the mailing list for this kind of issue.

We keep this bug tracker for bugs and feature requests.
