### ISSUE TITLE
integration fingerbank packetfence

### ISSUE THREAD

**Issue by diedriko** [inverse-inc/packetfence#4014]
Hi,
We do not wish to integrate fingerbank with our packetfence installation.
Install and config is succesfull, but fingerbank keeps putting errors in the packetfence.log.
Example of errors, in fact there are only 2 of them, but constantly:
 pfqueue: pfqueue(14128) ERROR: [mac:unknown] Error while communicating with the Fingerbank collector
pfqueue: pfqueue(14128) ERROR: [mac:unknown] Unable to fetch query arguments for Fingerbank query
We would like to disable these errors if possible, so our logs doesn't become cluttered.
Thanks for advice

**Comment by julsemaan** [comment]
I've just fixed it by skipping the Fingerbank lookups and processing if you don't have an API key configured.

The fix is in the maintenance for all 8.x versions, you can apply it using:
```
/usr/local/pf/addons/pf-maint.pl
```

**Comment by diedriko** [comment]
script gives an error
Step 1: Patching of text based codefiles
Currently at 63d1e05162ccfd92dc4408e23c375f8eb9ebd373
** GET https://api.github.com/repos/inverse-inc/packetfence/branches/maintenance/8.3 ==> 500 Can't connect to api.github.com:443
500 Can't connect to api.github.com:443

**Comment by diedriko** [comment]
LWP::Protocol::https::Socket: getaddrinfo: Name or service not known at /usr/share/perl5/LWP/Protocol/http.pm line 51.

**Comment by diedriko** [comment]
nevermind the above, mistake on my part

**Comment by antonc42** [comment]
I was having this same issue and the fixes worked for me. Thanks!
