### ISSUE TITLE
Missing ipfilter entries for Samsung captive portal fix

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#4024]
When applying the fix for issue #3419 I noticed that the pffilter config includes a hard-coded IP address. (172.217.13.99)  But both when testing in my region (south america) and looking at the code, I don't see the specific IP being added to the "passthrough"  IPSET list that would allow the devices to reach the proper server.

I guess when testing or in other regions, dns queries of other phones for "connectivitycheck.gstatic.com" will probably populate the IPSET list but in my region, the DNS entries are returning different IPs and thus the IPSET list was never getting populated with the IP 172.217.13.99. 

So far I added the ip:port combination manually but this won't survive a reboot or a service restart. Not entirely sure which would be the "correct" way to make this persistent?

To be honest, it would be great if there would be a way to avoid hardcoded IPs but not sure I can thuink of many options. Maybe returning a cname to "samsungconnectivity.inverse-inc.com" which in turn then replies with the most up-to-date A record for "connectivitycheck.gstatic.com"? maybe im overcomplicating things though...

**Comment by restrok** [comment]
seems like this was solved in https://github.com/inverse-inc/packetfence/commit/1132e48f59174f03229acf82978f32470898e50f
