### ISSUE TITLE
API OPTIONS config/base/guest_admin_registration

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4037]
meta > default_access_duration > allowed (is empty).

Should echo back allowed items from access_duration_choices.

**Comment by jrouzierinverse** [comment]
This is a tricky one since we could use the access_duration_choices for the allowed for default_access_duration.

However since the allowed values could changed when you add a new one in the GUI is it worth doing?

**Comment by jrouzierinverse** [comment]
Closing as this since the value of the default_access_duration is depends on access_duration_choices which could also be modified in the GUI.
Reopen if needed.
