### ISSUE TITLE
API OPTIONS base/fencing requires proxy_passthroughs

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4042]
Need to expose the `proxy_passthroughs` from conf/pf.conf.defaults in `OPTIONS config/base/fencing`

`
proxy_passthroughs=crl.geotrust.com,ocsp.geotrust.com,crl.thawte.com,ocsp.thawte.com,crl.comodoca.com,ocsp.comodoca.com,crl.incommon.org,ocsp.incommon.org,crl.usertrust.com,ocsp.usertrust.com,mscrl.microsoft.com,crl.microsoft.com,ocsp.apple.com,ocsp.digicert.com,ocsp.entrust.com,srvintl-crl.verisign.com,ocsp.verisign.com,ctldl.windowsupdate.com,crl.globalsign.net,pki.google.com,www.microsoft.com,crl.godaddy.com,ocsp.godaddy.com,certificates.godaddy.com,crl.globalsign.com,secure.globalsign.com,cacerts.digicert.com,crt.comodoca.com,crl.incommon-rsa.org,crl.quovadisglobal.com,cert.incommon.org,crt.usertrust.com,crl.verisign.com,crl.starfieldtech.com,developer.apple.com,ts-crl.ws.symantec.com,certificates.intel.com
`

**Comment by jrouzierinverse** [comment]
Fixed by ab83ac74e9262d788fd2e0f0498e298e475927ee
