### ISSUE TITLE
Mulitple scan engine in one conneciton profile

### ISSUE THREAD

**Issue by prasertsook** [inverse-inc/packetfence#4046]
Refer to the screen shot attached, please help advice whether we can scan multiple engine in one connection profile.  Or this tools limited to scan only one engine but i can see the engine can be added more that one.

Below is the profile config file and log file when tried to scan multiple engines.  The log file say the scan finished only the first engine "OpenVAS-Post" but not "WMI-Post-Scan".

/usr/local/pf/conf/profiles.conf
[HANALPN-Post]
filter=vlan:1,vlan:30
description=HANALPN-Post
scans=OpenVAS-Post,WMI-Post-Scan
-----------
/usr/local/pf/logs/packetfence.log
Mar 11 11:11:00 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Instantiate profile HANALPN-Post (pf::Connection::ProfileFactory::_from_profile)
Mar 11 11:11:01 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] grace expired on violation 1200004 for node 50:00:00:03:00:00 (pf::violation::violation_add)
Mar 11 11:11:01 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] violation 1200004 added for 50:00:00:03:00:00 (pf::violation::violation_add)
Mar 11 11:11:01 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] executing action 'log' on class 1200004 (pf::action::action_execute)
Mar 11 11:11:01 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] /usr/local/pf/logs/violation.log 2019-03-11 11:11:01: Post Reg System Scan (1200004) detected on node 50:00:00:03:00:00 (192.168.1.10) (pf::action::action_log)
Mar 11 11:11:02 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Instantiate profile HANALPN-Post (pf::Connection::ProfileFactory::_from_profile)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] New ID generated: 1552277463220000 (pf::util::generate_id)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Creating a new scan target named 15522774632200001552277463.06797 for host 192.168.1.10 (pf::scan::openvas::createTarget)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Scan target named 15522774632200001552277463.06797 successfully created with id: 56cfc33b-db64-46d2-8ec5-b2f643c5f623 (pf::scan::openvas::createTarget)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Creating a new scan task named 15522774632200001552277463.06797 (pf::scan::openvas::createTask)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Scan task named 15522774632200001552277463.06797 successfully created with id: 45c7826f-f938-4b37-ba83-f36e418ac82d (pf::scan::openvas::createTask)
Mar 11 11:11:03 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Starting scan task named 15522774632200001552277463.06797 (pf::scan::openvas::startTask)
Mar 11 11:11:04 PacketFence-ZEN pfqueue: pfqueue(13952) INFO: [mac:50:00:00:03:00:00] Scan task named 15522774632200001552277463.06797 successfully started (pf::scan::openvas::startTask)
Mar 11 11:11:05 PacketFence-ZEN packetfence_httpd.webservices: httpd.webservices(9399) INFO: [mac:50:00:00:03:00:00] violation 1200004 closed for 50:00:00:03:00:00 (pf::violation::violation_close)
Mar 11 11:18:27 PacketFence-ZEN packetfence_httpd.portal: httpd.portal(13676) INFO: [mac:[undef]] Will analyze OpenVAS report for task 15522774632200001552277463.06797 (pf::web::openvashook::handler)
Mar 11 11:18:27 PacketFence-ZEN packetfence_httpd.portal: httpd.portal(13676) INFO: [mac:[undef]] Getting the scan report for the finished scan task named 15522774632200001552277463.06797 (pf::scan::openvas::processReport)
Mar 11 11:18:29 PacketFence-ZEN packetfence_httpd.portal: httpd.portal(13676) INFO: [mac:[undef]] Report id e0a4bca2-6caa-4156-878e-e5744a2ce609 successfully fetched for task named 15522774632200001552277463.06797 (pf::scan::openvas::processReport)
-----------
<img width="1393" alt="Screen Shot 2562-03-11 at 11 39 18" src="https://user-images.githubusercontent.com/11386532/54100708-7aa08e80-43f2-11e9-8eeb-da09e5f91874.png">

**Comment by julsemaan** [comment]
This bug tracker is for development tracking and bugs

Please use the mailing list for configuration related questions
