### ISSUE TITLE
Use Unicode characters like Chinese/Arabic not are not correctly shown in web admin

### ISSUE THREAD

**Issue by amiirrmm** [inverse-inc/packetfence#4049]
Hi

I am using ZEN vm version. I get my users and authentication from my active directory and in the AD my users have Unicode characters.   It is not correctly shown in web admin and maybe in the database. Is there any solution to this problem now or in the future? 

![Capture](https://user-images.githubusercontent.com/45257636/54189460-18658d80-44c7-11e9-8de7-1eb48a671e04.JPG)

**Comment by julsemaan** [comment]
@jrouzierinverse 

Do you recall working on supporting different encodings when fetching users via LDAP?

I thought it was already addressed but that may just be my memory failing me

**Comment by jrouzierinverse** [comment]
Bad memory
![](https://media.giphy.com/media/mYttD81qQ6vLi/giphy.gif)

**Comment by amiirrmm** [comment]
So this is a bug, or at least a feature request, please.

Is there any temporary solution to this until an official fix ?

**Comment by julsemaan** [comment]
That would be a feature request if it has never been part of PF

Will mark it for 9.1 and we'll see about addressing this in a future R&D meeting
