### ISSUE TITLE
OPTIONS /api/v1/config/<..>/oses → lookup definition

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4058]
For some fields that expect a Fingerbank OS ID, we currently add the complete list of allowed values in the OPTION response which makes the payload ridiculously huge.

When querying Fingerbank for OSes (or any field restricted to one of an utterly large number of values), the OPTION API endpoint should return the appropriate information to perform a dynamic lookup when validating the field.

**Comment by jrouzierinverse** [comment]
@cgx fixed by 287629a0f6364838f254ebd28d482a994fd97cb6 

Added 'allowed_lookup' to meta 
It has two fields search_path and field_name
The search path is the path to send the search query.
The field_name is the name of the field for the query.
Let me know if this is enough.

```json
{
    "allowed_lookup" : {
      "search_path" : "/api/v1/fingerbank/local/devices/search",
      "field_name" : "name"
      }
}
```
