### ISSUE TITLE
Nothing happening when floating device is connected

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/packetfence#407]
I've configured a floating device and started to change the ProCurve 2920 switch module to support floating devices, but i never got any messages in the log from the functions that should have been called when a floating devices mac was seen on a port.

I've then changes the switch capabilities back to not support floating devices in which case i expected to get a log entry that my device does not support floating devices, but that did not happen either...

I'm still on 4.5.1

**Comment by louismunro** [comment]
Please use the mailing list for support questions. 
Issues are for reporting actual, reproductible bugs.

**Comment by erSitzt** [comment]
ok
