### ISSUE TITLE
monitoring of Redis processes on all pf versions

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4076]
Hello,

Commit https://github.com/inverse-inc/packetfence/commit/96f76d81c09f440166c455577c87c2551064003f updated Redis monitoring scripts for all PF versions.

However, Redis listens only on localhost **since** [8.3](https://github.com/inverse-inc/packetfence/commit/2f88ac1f322c94451cc4662c63ee097768785ab8).

On PF 8.2.1 with up-to-date monitoring scripts, `monit` is not able to check correctly Redis processes causing infinite restart of processes.

@fdurand, did you got same behaviour on 8.3 version before doing your change ?

**Comment by nqb** [comment]
For me, any change to monit scripts should be approve by a PR. It's too critical.

**Comment by nqb** [comment]
https://mmonit.com/monit/documentation/monit.html#Process

**Comment by julsemaan** [comment]
The monitoring scripts that are on inverse.ca and in devel are made for the latest version of PacketFence.

You have access to the right monit configuration that is built for your specific release through the package install in /usr/local/pf/addons/monit/

Also, not that sure all changes to the monit configuration should go through a PR given its not something that is automagically installed on a server and while installing, issues are detected easily. Not to be confused with the monitoring scripts repo that does get scripts pulled down automatically which does require PRs with double reviews.
