### ISSUE TITLE
Set the source nullauth if you check the reuse dot1x credentials

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#408]
If you check the reuse dot1x credentials, only the nullauth source should be available.

Now we display all the sources installed on the portal profile.

reuse dot1x credentials checked + facebook = not working correctly.

**Comment by jrouzierinverse** [comment]
Reuse dot1x credentials can be used with AD,LDAP and other internal sources.
Maybe only allow internal sources and exclusive sources with reuse dot1x credentials?

**Comment by jrouzierinverse** [comment]
Team should what sources should we allow to be used with Reuse dot1x credentials.

**Comment by lzammit** [comment]
Actual behaviour since PF 5.0
