### ISSUE TITLE
AD Domains: impossible to add new domain

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4084]
Fresh install on 8.3.9 under CentOS 7.6
![Screenshot from 2019-03-18 17-20-37](https://user-images.githubusercontent.com/10830260/54545603-4739a300-49a2-11e9-8691-2490f5260655.png)

I supposed this is cause by https://github.com/inverse-inc/packetfence/pull/4016

**Comment by nqb** [comment]
To get back the usual view, I need to check "Disable OS AD join check" in System configuration -> Advanced.

**Comment by julsemaan** [comment]
@fdurand 

That is fixed now right ?

**Comment by fdurand** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/a2efcda8f8085c9984d8f515d511e4cc5b80f74e
