### ISSUE TITLE
Validate email address fields

### ISSUE THREAD

**Issue by Dan-eh3** [inverse-inc/packetfence#4085]
When configuring SMTP settings, the Sender and Recipient address fields are not validated.  Users can input an impreperly formatted address without warning or validation. 

Please improve these fields to validate that an email address is inputted, in example name@domain.com

**Comment by julsemaan** [comment]
This needs to go in maintenance/9.0 and maintenance/9.1

**Comment by satkunas** [comment]
@julsemaan alternative adjustments will be needed since the admin was reworked after these releases. Proceed anyway?

**Comment by julsemaan** [comment]
Let's leave it as-is for now since these are fairly old releases by now
