### ISSUE TITLE
Implementing update engine

### ISSUE THREAD

**Issue by simbazad** [inverse-inc/packetfence#4086]
Hi All,
Would you consider merging implementation of an update engine? 
Something like https://github.com/mendersoftware/mender

**Comment by julsemaan** [comment]
Like as a provisioner or scan engine you mean ?

**Comment by simbazad** [comment]
> Like as a provisioner or scan engine you mean ?

No, i mean implementing an update engine which will update packetfence to a new version when available without the current complication (migrate scripts , database migration , configuration migration ...)

**Comment by julsemaan** [comment]
Although we'd be interested in doing easier updates, I believe that this work should be done by the Inverse team and not an external contributor given the very complex nature of it especially when considering the clusters.

I don't think we'll use something as complex as what you suggested and we'll probably adjust our packaging to do the upgrade steps during the "yum update" process

**Comment by simbazad** [comment]
@julsemaan Sure ! , Just keep in mind that implementing something like https://github.com/mendersoftware/mender isn't that hard and its definitely worth it (they even implemented quite clever rollback logic)
