### ISSUE TITLE
GET /api/v1/switches/bulk_{action}

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4091]
We need some bulk action for switches, the most important would be to change the switch group. See #1095.

**Comment by jrouzierinverse** [comment]
I will provide a bulk_{update|delete} for config all items as this will be useful for config items.
The only question is for update if the id does not exists should we return an error for that config item or attempt to create it?

**Comment by julsemaan** [comment]
since #4212 is tagged for 9.1 and this looks more like a feature than a bug, I'll push this to 9.1

@cgx feel free to bring this back to 9.0 if needed
