### ISSUE TITLE
API PATCH config/base/services error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4093]
Receiving 502 Bad Gateway

**Comment by satkunas** [comment]
`api-frontend.log`

Mar 20 17:19:18 packetfence api-frontend[1737]: t=2019-03-20T17:19:18-0400 lvl=eror msg="Couldn't acquire lock for pfconfig pool" pid=1737 request-uuid=5feded78-4b50-11e9-881d-080027d5be68

`packetfence.log`

Mar 20 17:19:18 packetfence pfhttpd: 2480 Timeout obtaining or releasing lock that came from:
Mar 20 17:19:18 packetfence pfhttpd: github.com/inverse-inc/packetfence/go/timedlock.(*RWLock).handleTimeout
Mar 20 17:19:18 packetfence pfhttpd: /root/gospace/src/github.com/inverse-inc/packetfence/go/timedlock/rw_lock.go:147
Mar 20 17:19:18 packetfence pfhttpd: github.com/inverse-inc/packetfence/go/timedlock.(*RWLock).Lock
Mar 20 17:19:18 packetfence pfhttpd: /root/gospace/src/github.com/inverse-inc/packetfence/go/timedlock/rw_lock.go:109
Mar 20 17:19:18 packetfence pfhttpd: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).acquireWriteLock
Mar 20 17:19:18 packetfence pfhttpd: /root/gospace/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/pool.go:135
Mar 20 17:19:18 packetfence pfhttpd: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).Refresh
Mar 20 17:19:18 packetfence pfhttpd: /root/gospace/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/pool.go:151
Mar 20 17:19:18 packetfence pfhttpd: github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP.func1.1
Mar 20 17:19:18 packetfence pfhttpd: /root/gospace/src/github.com/inverse-inc/packetfence/go/caddy/pfconfig/pool.go:47
Mar 20 17:19:18 packetfence pfhttpd: runtime.goexit
Mar 20 17:19:18 packetfence pfhttpd: /usr/lib/golang/src/runtime/asm_amd64.s:1333

@julsemaan

**Comment by satkunas** [comment]
Works fine via CLI, but not via API.

```
/usr/local/pf/sbin/pfperl-api get -M PATCH -c '{"api-frontend":"enabled","fingerbank-collector":"enabled","haproxy-db":"enabled","haproxy-portal":"enabled","httpd_aaa":"enabled","httpd_admin":"enabled","httpd_collector":"disabled","httpd_dispatcher":"enabled","httpd_parking":"enabled","httpd_portal":"enabled","httpd_proxy":"enabled","httpd_webservices":"enabled","id":"services","iptables":"enabled","keepalived":"enabled","netdata":"enabled","not_deletable":true,"pfbandwidthd":"disabled","pfdhcp":"enabled","pfdhcplistener":"enabled","pfdhcplistener_packet_size":null,"pfdns":"enabled","pffilter":"enabled","pfipset":"enabled","pfmon":"enabled","pfperl-api":"enabled","pfqueue":"enabled","pfsso":"enabled","pfstats":"enabled","radiusd":"enabled","radsniff":"enabled","redis_cache":"enabled","redis_ntlm_cache":"disabled","redis_queue":"enabled","routes":"enabled","snmptrapd":"disabled","tc":"enabled","winbindd":"enabled"}' /api/v1/config/base/services | jq
```

**Comment by julsemaan** [comment]
It doesn't really "work fine" through the CLI. 

This API call takes an enormous amount of time to complete, and on my dev machine it times out on the CLI as well:
```
# /usr/local/pf/sbin/pfperl-api get -M PATCH -c '{"api-frontend":"enabled","fingerbank-collector":"enabled","haproxy-db":"enabled","haproxy-portal":"enabled","httpd_aaa":"enabled","httpd_admin":"enabled","httpd_collector":"disabled","httpd_dispatcher":"enabled","httpd_parking":"enabled","httpd_portal":"enabled","httpd_proxy":"enabled","httpd_webservices":"enabled","id":"services","iptables":"enabled","keepalived":"enabled","netdata":"enabled","not_deletable":true,"pfbandwidthd":"disabled","pfdhcp":"enabled","pfdhcplistener":"enabled","pfdhcplistener_packet_size":null,"pfdns":"enabled","pffilter":"enabled","pfipset":"enabled","pfmon":"enabled","pfperl-api":"enabled","pfqueue":"enabled","pfsso":"enabled","pfstats":"enabled","radiusd":"enabled","radsniff":"enabled","redis_cache":"enabled","redis_ntlm_cache":"disabled","redis_queue":"enabled","routes":"enabled","snmptrapd":"disabled","tc":"enabled","winbindd":"enabled"}' /api/v1/config/base/services 
Removed symlink /etc/systemd/system/packetfence.target.wants/packetfence-redis_ntlm_cache.service.
Created symlink from /etc/systemd/system/packetfence.target.wants/packetfence-routes.service to /usr/lib/systemd/system/packetfence-routes.service.
Created symlink from /etc/systemd/system/packetfence.target.wants/packetfence-tc.service to /usr/lib/systemd/system/packetfence-tc.service.
Inactivity timeout at /usr/local/share/perl5/Mojolicious/Command/get.pm line 66.
```

I can make the proxy timeout longer in the api-frontend to give more time to pfperl-api to answer so you don't get a 502 bad gateway but that will not make the backend call faster and the browser could still timeout since the call takes an enormous amount of time to complete.

**Comment by julsemaan** [comment]
@jrouzierinverse 

Are we able to make that UnifiedAPI call faster so that we don't have to increase the proxy timeout in the API frontend?

Increasing the allowed time for API calls isn't the right solution IMO since that opens the door to the backends taking a lot of time to answer and keeping too many connections opened.

A solution would be to make the systemd adjustments (the main consumer of this request) occur asynchronously and making this API call much faster resulting in @satkunas not getting a 502 because the pfperl-api takes too much time to answer to the request for the api-frontend

According to caddy's doc the default timeout for a request is 30 seconds after which a 502 is sent. IMO going higher than this is not something we should consider and we should instead aim to fix the backend to be faster

**Comment by jrouzierinverse** [comment]
Yes we can we just have to fork off a process handle the slowness.
No forking
```
time ./sbin/pfperl-api get -M PUT -c '{}' /api/v1/config/base/services
{"message":"services replaced","status":200}
real    0m12.554s
user    0m8.161s
sys     0m1.770s
```
With forking
```
time ./sbin/pfperl-api get -M PUT -c '{}' /api/v1/config/base/services
{"message":"services replaced","status":200}
real    0m5.600s
user    0m4.753s
sys     0m0.665s
```

However we should set that timeout higher.
At the moment we have a 10 minute database query timeout for queries in the admin.
The timeout in api-frontend should reflect that reality.

**Comment by julsemaan** [comment]
We can't have API queries that are allowed to run for 10 minutes for all endpoints.

Some of the API endpoints are called dozens of times per second

I could make the timeout different for the unified API only though.

One of the good solutions for long running queries like special reports or domain joins would be to use an asynchronous job that the user would poll to check if it completed. That way it keeps API calls fast even for calls that are long.

I think we talked about the solution above for domain joins
