### ISSUE TITLE
pfstats queries /api/v1/dhcp/stats a lot of times

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4096]
In a cluster, I checked the usage of /api/v1/dhcp/stats and it seems its being called dozens of times although the configuration states that it should be called 4 times.

After checking, it seems its not configured to be done only for the management node and done for all nodes. Maybe that would explain the issue.

**Comment by julsemaan** [comment]
@fdurand 

Did this get fixed via one of the pfdhcp PRs we merged?

**Comment by fdurand** [comment]
We should set the management variable to True but if the VIP move to another server then we will lost the stats.

**Comment by julsemaan** [comment]
We could make pfstats aware of whether or not the server has the VIP at this very moment which would allow to workaround the issue and would make much more sense IMO since management doesn't mean 1st node, it means the current management
