### ISSUE TITLE
API PATCH config/connection_profile/default issue

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4103]
Payload: 
* id: `default`
* status: `disabled`

This request returns a status 200 OK. However, the `status` on the resource is not modified. If this is because it is `not_deletable`, then an error with a 4xx should be returned instead.

**Comment by julsemaan** [comment]
Actually, I think its because the default connection profile cannot be disabled, otherwise there would be no catchall if no other profile matches.
