### ISSUE TITLE
API token expiration improvement

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4109]
As discussed with @julsemaan, we could improve the token expiration algorithm so the token validity can be extended upon each request but can't lasts longer than a certain amount of hours (8? 12? 24?).

**Comment by julsemaan** [comment]
It seems that a token lasts 10 minutes

Here is my suggestion on timings:
- A token should be valid for 15 minutes
- Everytime a token is used, it extends the expiration to now+15 minutes
- A token will not be valid after 12 hours of usage

I'll start implementing this unless someone disagrees today

**Comment by jrouzierinverse** [comment]
Send back the expiration date for the token so it can be properly refreshed.

**Comment by julsemaan** [comment]
@jrouzierinverse 

Should that be in the token_info API call or in a header included in every response ?

**Comment by jrouzierinverse** [comment]
token_info API call.
