### ISSUE TITLE
it is not possible to go through the configuration wizard

### ISSUE THREAD

**Issue by mickaelidf** [inverse-inc/packetfence#4118]
[Packetfence_First_Installation_Error.pdf](https://github.com/inverse-inc/packetfence/files/3004081/Packetfence_First_Installation_Error.pdf)

Hi,

I've stumbled upon some issues when trying to install and run PacketFence 8.3 on Red Hat 7.6 (Maipo).

First of all, package installation when through without errors. But after installation the packetfence it impossible to go through the Configurator.
By checking configuration sanity , I've found that PF Could not write namespace config. I was unable to fix that problem

But I can access admin panel at port 1443 but it is not possible to go through the configuration wizard : From step 1, it is not possible to go to next step(2)

I don't have pf user and database yet because I wasn't able to run the configuration wizard yet.

Thanks for your help.

**Comment by extrafu** [comment]
Use the mailing list for such problems.

**Comment by mickaelidf** [comment]
Please can you describe how to Use the mailing list for such problems?

**Comment by extrafu** [comment]
1. boot your computer
1. open your web browser
1. open https://packetfence.org/support.html#/community
1. read the page
1. open your MUA
1. subscribe to the mailing list
1. post your email

**Comment by mickaelidf** [comment]
Hi,
I sent my email to the mailing list.
 thank you again for your  reply.
