### ISSUE TITLE
Security events: have useragent and user_agent in the code

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4120]
In the security events, we have user_agent in the pfappserver controller and in the conf while the trigger is useragent.

We need to adjust this to be only useragent as it is in the factory

Should be adjusted in at least:
 * html/pfappserver/lib/pfappserver/PacketFence/Controller/SecurityEvent.pm
 * conf/security_events.conf.example
 * conf/security_events.conf.defaults

**Comment by julsemaan** [comment]
While doing this, we should go through lib/pf/factory/condition/security_event.pm so that it uses the constants in lib/pf/constants/trigger.pm and ensure the latest is consistent with what is in the factory

**Comment by cgx** [comment]
In your rework of the violations concept, you mentioned that useragent triggers need to be deprecated as they are useless. Time to remove them?

**Comment by julsemaan** [comment]
They aren't 100% useless but I've never seen someone use them given the very dynamic nature of the user agents and the very static matching ability we have for matching time.

I'd say its time to deprecate them unless someone from the team opposes to it
