### ISSUE TITLE
Pfappserver utils/api response w/ interceptor mutates after request is made

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4121]
In reference to the request `response` parameter below. 

https://github.com/inverse-inc/packetfence/blob/ef273599599b13bd95717d0fdc2da14b0f851b25/html/pfappserver/root/static.alt/src/utils/api.js#L43

The response from `apiCall.interceptors.response.use((response)=>{})` includes the properties `baseURL` and `url`. The response from `apiCall.interceptors.request.use((response)=>{})` also include a `baseURL` and `url` field (). This is also the same for errors `apiCall.interceptors.response.use((response)=>{}, (error)=>{})`. 

However the `apiCall.interceptors.request.use` response differs from `apiCall.interceptors.response.use`, where the `url` contains the full URL (therefore redundantly including `baseURL`), thus leading to 2 different code paths when determining the full URL by appending `baseURL` and `url` together.
 * `apiCall.interceptors.request.use`: fullURL = baseURL + url
 * `apiCall.interceptors.response.use`: fullURL = url

**Comment by cgx** [comment]
I would assume this is a bug in the Axios library. Maybe the upcoming [getUri](https://github.com/axios/axios/pull/1712) method will help.

**Comment by cgx** [comment]
Axios v0.19.0 released, `getUri` doesn't help.
