### ISSUE TITLE
v9-gui: switch editing roles mapping

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4126]
When editing an existing switch (coming from v8.3 configuration), you cannot tell if you're using Role by VLAN ID, Role by Switch Role, etc. because all the toggles are in 'disabled state'.

When you toggle on something, existing data is shown.

We should toggle on the stuff that has data in it.

**Comment by satkunas** [comment]
@jrouzierinverse re-assigning to you.

There's a discrepancy in the *Map values returned when GETting the resource.

```json
{
  AccessListMap: "Y"
  RoleMap: 0
  UrlMap: "N"
  VlanMap: 0
}
```

I'm expecting 'Y' or 'N'. Sometime recently RoleMap and VlanMap switched to INT. Let me know if you'd rather use INTs (or BOOLs) and I'll adjust the front-end.

**Comment by satkunas** [comment]
Moved to #4257
