### ISSUE TITLE
v9-gui: RADIUS audit log doesn't show all information

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4131]
When clicking on a RADIUS log entry, the 3 tabs show very very little information about the actual RADIUS log entry.

**Comment by extrafu** [comment]
<img width="1333" alt="Screen Shot 2019-03-26 at 1 44 35 PM" src="https://user-images.githubusercontent.com/1616141/55020518-5b4a5980-4fcd-11e9-858d-1d3d0bc844fb.png">

**Comment by extrafu** [comment]
<img width="1337" alt="Screen Shot 2019-03-26 at 1 44 40 PM" src="https://user-images.githubusercontent.com/1616141/55020521-5edde080-4fcd-11e9-844d-be06ee84c6f7.png">

**Comment by extrafu** [comment]
<img width="1336" alt="Screen Shot 2019-03-26 at 1 44 45 PM" src="https://user-images.githubusercontent.com/1616141/55020528-62716780-4fcd-11e9-88f6-c635735971a4.png">

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/pull/4226/commits/70f51719b09efd0869e3f3ffcbb23c251e92426f
