### ISSUE TITLE
v9-gui: nodes import from CSV - missing import options

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4136]
All the import options from v8 are missing when importing nodes from a CSV file.

<img width="1182" alt="Screen Shot 2019-03-27 at 3 30 32 PM" src="https://user-images.githubusercontent.com/1616141/55106424-4b05ad80-50a5-11e9-9010-0dd74cb73d32.png">

**Comment by extrafu** [comment]
Same applies when importing users:

<img width="1182" alt="Screen Shot 2019-03-27 at 3 37 22 PM" src="https://user-images.githubusercontent.com/1616141/55106838-455c9780-50a6-11e9-98d6-7c2628cf7f9a.png">

**Comment by cgx** [comment]
Nothing is missing. It's a more UX issue if you haven't found the options. I'll try to improve the GUI.

**Comment by cgx** [comment]
@extrafu Still relevant?

**Comment by extrafu** [comment]
Looks good now, closing.
