### ISSUE TITLE
v9-gui: Missing actions button from Users page

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4138]
The Actions button is missing from the Users page.
<img width="204" alt="Screen Shot 2019-03-27 at 3 42 24 PM" src="https://user-images.githubusercontent.com/1616141/55107142-f6fbc880-50a6-11e9-93ed-3d1c57d76f89.png">

**Comment by cgx** [comment]
Related to issue #3564.

**Comment by extrafu** [comment]
Code has been merged in this morning to offer the missing features. It can now be added to the GUI.

**Comment by satkunas** [comment]
Depends on #4244

**Comment by satkunas** [comment]
Depends on #4248

**Comment by satkunas** [comment]
Depends on #4251

**Comment by satkunas** [comment]
Added in #4226
