### ISSUE TITLE
API PATCH config/fingerbank_setting/:id 500 error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4140]
Same issue with all ID's
 * upstream
 * collector
 * query
 * proxy

Example request URI: `PATCH /api/v1/config/fingerbank_setting/upstream`
Example request payload: `{"api_key":"[snipped]","db_path":"/api/v2/download/db","host":"api.fingerbank.org","not_deletable":true,"port":"443","sqlite_db_retention":"2","use_https":"enabled","id":"upstream"}`

Example response code: 500
Example response body: 
```html
<!DOCTYPE html>
<html>
  <head><title>Server error</title></head>
  <style>
      body { background-color: #caecf6 }
      #raptor {
        background: url(/mojo/failraptor.png);
        height: 488px;
        left: 50%;
        margin-left: -371px;
        margin-top: -244px;
        position:absolute;
        top: 50%;
        width: 743px;
      }
    </style>
  <body><div id="raptor"></div></body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

Also same result with plural `PATCH /config/fingerbank_settings` with an Array in the request payload containing all 4 individual sections.

**Comment by jrouzierinverse** [comment]
Fixed by 471c3afd21531666b66e8a905674f688c4103a57
