### ISSUE TITLE
portal modules: help when no source selected

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4148]
When no source are selected on a portal module, we got this message:
![sources](https://user-images.githubusercontent.com/10830260/55165323-84095500-516d-11e9-90da-8cc4a48ec374.png)

We should have: 

> The sources to use in the module. If no sources are specified, all the sources on the Connection Profile will be used

See https://github.com/inverse-inc/packetfence/pull/3827#issuecomment-476207616

**Comment by extrafu** [comment]
BTW, I tagged v9-gui the stuff related to the *new* GUI - not the old one.

**Comment by nqb** [comment]
This was to have this thing in mind for the new GUI.
