### ISSUE TITLE
Centos7 Installation

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#415]
When we install Packetfence from devel repo on centos, we must specify radius version else he is trying to install 3.0.1 and we need something < 3.0 for the installation. The install process is trying to install freeradius from base repo where we need it to install from pf repo.

**Comment by louismunro** [comment]
s/he/it/g;
Please be explicit about what you mean by "he". 
Are we talking about the package? The user? The platonic form of PacketFence?

**Comment by whitx** [comment]
Fixed in Feature/Ubuntu14.04
