### ISSUE TITLE
v9-gui: Policies and Access Control global issues. (keep it open until the list is empty)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4151]
Global Section:
- [x] Clicking on sub-menu always collapse the main menu.

Roles Section:
- [x] New admin permit to delete a role.

Active Directory Domains:
- [x] Missing predefined values on create (like OU, Sticky DC, server name)

Realms:
- [ ] RADIUS ACCT still empty even if there is some radius authentication sources defined.

Authentication sources
- [x] ALL : No able to save {"errors":[{"id":"id field is required"}],"message":"Unable to validate","status":422}
- [x] ALL: Amount of logins for the local account shoulb be a int.
- [x] Sources not sortabled (it's important)
- [x] No choice for Access duration 
- [x] Empty Acces duration is allowed
- [x] AD/LDAP : Username Attribute should be a predefined field
- [x] AD/LDAP : No search attributes
- [x] AD/LDAP : Scope subtree by default (or list empty undefined)
- [x] AD/LDAP : Encryption None by default (or list empty undefined)
- [x] Sources in general : After creating a source the next windows is empty or when you edit it
![image](https://user-images.githubusercontent.com/1553962/55187292-00506800-516f-11e9-8b17-326dfda4a5ad.png)
- [x] htpasswd : Need to show an error when the file doesn't exist.
- [x] HTTP : host is not saved
- [x] POTD : Password Rotation Period is not saved in the file.
- [x] Email : Email activation Timeout set 10 minutes by default
- [x] Email/Sponsor : Error when saving: ERROR pfperl-api(7770): HFH: param clash for email_activation_timeout.interval
- [x] Oauth sources : Authorized domains
- [x] SMS : Missing hash password method attribute.
- [x] Sponsor : Email Activation Timeout unit list is empty
- [x] Sponsor: Sponsor Validation should be enabled
- [x] Twillio/SMS : Pin length is not a string
- [x] Eduroam on create: ERROR pfperl-api(30838): Attribute (local_realm) does not pass the type constraint because: Validation failed for 'ArrayRef[Str]' with value "" at constructor pf::Authentication::Source::EduroamSource::new (defined at /usr/local/pf/lib/pf/Authentication/Source/EduroamSource.pm line 121) line 89
- [x] Authorized.net on create: ERROR pfperl-api(30836): Attribute (transaction_key) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24
- [x] authorized.net/Mirapay/Paypal/Stripe: Currentcy list is empty
- [x] Mirapay: Iframe Base URL empty
- [x] Paypal on create: ERROR pfperl-api(30836): Attribute (cert_id) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24 
- [ ] Stripe on create: ERROR pfperl-api(30838): Attribute (publishable_key) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24

Switches:
- [x] New switch group: the form is to create a switch, it miss switch group name and we need to remove switch ip/mac/...
Edit Switch: 
- [x] IP Address/MAC Address/Range is empty
- [x] All list are empty (Type mode Switch group)
- [x] Role by ... doesn't show the role
- [x] Inline Whatever is set as value in the trigger the value is required, not able to save
- [x] Sometimes i need to fight with No-Default-Yes button (like Use CoA)
- [ ] SNMP version list is empty and should be v2c by default
- [x] SNMP predefined field are missing (Community read: public)
- [x] SNMP Version Trap is empty
- [x] CLI Transport list is empty
- [x] Web services TRansport list is empty

Connection profiles:
- [x] Preview not working
- [x] Not able to clone, Connection profile exist
- [x] Profile Description : Description required
- [x] Enable profile should be enabled by default
- [x] Root portal module is empty
- [x] Filters is empty, should be any or all
- [x] All the lists are empty
- [x] Missing default values
- [ ] Locale required when we try to add one
- [x] Files tab not available.

**Comment by julsemaan** [comment]
Looks like someone wants to challenge @lzammit for the Chief Testing Officer position

**Comment by satkunas** [comment]
> RADIUS ACCT still empty even if there is some radius authentication sources defined.

@fdurand @julsemaan can I get a sample config from either of you so I can create and test a local RADIUS auth source?


> ALL : No able to save {"errors":[{"id":"id field is required"}],"message":"Unable to validate","status":422}
> ALL: Amount of logins for the local account shoulb be a int.
> Sources not sortabled (it's important)

Unable to replicate. Need retest/more info.


> Sometimes i need to fight with No-Default-Yes button (like Use CoA)

Moved to https://github.com/inverse-inc/packetfence/issues/4223

> POTD : Password Rotation Period is not saved in the file.

Moved to https://github.com/inverse-inc/packetfence/issues/4222


> Email : Email activation Timeout set 10 minutes by default
> Sponsor : Email Activation Timeout unit list is empty

@jrouzierinverse defaults missing from meta
```json
"email_activation_timeout": {
            "default": null,
            "placeholder": null,
            "properties": {
                "interval": {
                    "allowed": null,
                    "allowed_lookup": null,
                    "default": null,
                    "min_value": 0,
                    "placeholder": null,
                    "required": false,
                    "type": "integer"
                },
                "unit": {
                    "allowed": [{
                        "text": "seconds",
                        "value": "s"
                    }, {
                        "text": "minutes",
                        "value": "m"
                    }, {
                        "text": "hours",
                        "value": "h"
                    }, {
                        "text": "days",
                        "value": "D"
                    }, {
                        "text": "weeks",
                        "value": "W"
                    }, {
                        "text": "months",
                        "value": "M"
                    }, {
                        "text": "years",
                        "value": "Y"
                    }],
                    "default": null,
                    "placeholder": null,
                    "required": false,
                    "type": "string"
                }
            },
            "required": true,
            "type": "object"
        },
```

> authorized.net/Mirapay/Paypal/Stripe: Currentcy list is empty

Likely due to the perl errors. Was working on MiraPay for me.


> Mirapay: Iframe Base URL empty

same as above


> Preview not working

Added in https://github.com/inverse-inc/packetfence/commit/eecb4c1f4ddda24ed3985d5ba818e80e06b74a13


> Not able to clone, Connection profile exist

Unable to replicate. Retest/more info needed.


> Root portal module is empty
> Filters is empty, should be any or all
> All the lists are empty

All working. Likely due to a perl error. Retests needed.


> Locale required when we try to add one

Unsure of what this means. I assume an error was shown when trying to add, but I was unable to replicate. More info needed.

**Comment by satkunas** [comment]
> htpasswd : Need to show an error when the file doesn't exist.

@jrouzierinverse Do we have an endpoint available for this? Or will it be returned as an error when attempting to PATCH or POST through config/sources?

**Comment by satkunas** [comment]
@jrouzierinverse 

**The left-over issues that are due to missing or incorrect meta:**

Realms:
- RADIUS ACCT still empty even if there is some radius authentication sources defined.

Authentication sources:
- No choice for Access duration
- AD/LDAP : Scope subtree by default (or list empty undefined)
- AD/LDAP : Encryption None by default (or list empty undefined)
- Email : Email activation Timeout set 10 minutes by default
- Sponsor: Sponsor Validation should be enabled

Switches:
- All list are empty (Type mode Switch group)
- SNMP version list is empty and should be v2c by default
- SNMP predefined field are missing (Community read: public)

Connection profiles:
- Enable profile should be enabled by default
- Missing default values

**Comment by satkunas** [comment]
Moved to #4257
