### ISSUE TITLE
v9-gui: "Configuration > Integration" issues (keep it open until the list is empty)

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4153]
- [x] Firewall SSO: Missing "$pf_username" default value for "Username format"
- [x] Firewall SSO: When cloning an existing firewall SSO entry, the "Hostname or IP Address" has the value of the cloned entry, instead of being empty
- [x] Firewall SSO: Search does not work
- [x] Cisco Mobility Services Engine: When saving settings, it says "mse_tab updated" - needs to be prettier for users
- [x] Web Services: When saving settings, it says "webservices updated" - needs to be prettier for users
- [x] Syslog Parsers:  When cloning an existing syslog parser entry, the "Detector" has the value of the cloned entry, instead of being empty
- [x] Syslog Parsers:  When editing an existing syslog entry, you can change the detector which leads to an error on save. We should make the field non-editable.
- [x] Syslog Parsers: Search does not work
- [x] Syslog Forwarding:  When cloning an existing syslog entry, the "Syslog Name" has the value of the cloned entry, instead of being empty
- [x] Syslog Forwarding:  When editing an existing syslog entry, you can change its name which leads to an error on save. We should make the field non-editable.
- [x] Syslog Forwarding: Search does not work
- [ ] WRIX: Missing filtering options on all criteria (Id, Location identifier, etc.)

**Comment by satkunas** [comment]
> Firewall SSO: When cloning an existing firewall SSO entry, the "Hostname or IP Address" has the value of the cloned entry, instead of being empty

> Syslog Parsers: When cloning an existing syslog parser entry, the "Detector" has the value of the cloned entry, instead of being empty

> Syslog Forwarding: When cloning an existing syslog entry, the "Syslog Name" has the value of the cloned entry, instead of being empty

This is intentional. However the validators will present a warning to the user that the field is in use and it needs to be unique. This helps fwd the information to the user of which record they are cloning.

**Comment by satkunas** [comment]
> Syslog Parsers: When editing an existing syslog entry, you can change the detector which leads to an error on save. We should make the field non-editable.

>  Syslog Forwarding: When editing an existing syslog entry, you can change its name which leads to an error on save. We should make the field non-editable.

The field is locked and readonly. Unable to reproduce.

**Comment by satkunas** [comment]
Moved to #4257

**Comment by satkunas** [comment]
> WRIX: Missing filtering options on all criteria (Id, Location identifier, etc.) 

Moved to #4454
