### ISSUE TITLE
v9-gui: Issues for compliance

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4157]
- [x] cannot change fingerbank settings
- [x] HTTP code 500 on the nessus scan engine
- [ ] cannot select os on all the scan engines
- [x] cannot delete scan engine on the engine lists
- [ ] empty lists on the rapid7 scan engine
- [x] error "unable to validate invalid no valid formater" on the rapid7 scan engine
- [x] error "unable to validate" on the WMI scan engine
- [x] cannot see and add WMI rules
- [x] cannot see and add security events

**Comment by satkunas** [comment]
> empty lists on the rapid7 scan engine

https://github.com/inverse-inc/packetfence/issues/4221

> error "unable to validate invalid no valid formater" on the rapid7 scan engine

What criteria was used to generate this error?

> error "unable to validate" on the WMI scan engine

What criteria was used to generate this error?


> error "unable to validate invalid no valid formater" on the rapid7 scan engine
> error "unable to validate" on the WMI scan engine

These are likely due to missing meta, and should be resolved once meta is available.

**Comment by satkunas** [comment]
@jrouzierinverse the following is caused by missing meta:
- cannot select os on all the scan engines
- empty lists on the rapid7 scan engine

**Comment by dondon21** [comment]
error "unable to validate invalid no valid formater" on the rapid7 scan engine.
I cannot reproduce this error now, the params was the localhost IP with the 20 min duration.
Now i have an API error : Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pfappserver/Form/Config/Scan/Rapid7.pm line 128. 

error "unable to validate" on the WMI scan engine.
I was able to reproduce the error with the localhost IP, admin credentials, 20 min of scan, guest role and with all the buttons checked.
