### ISSUE TITLE
v9-gui: "Configuration > Advanced access configuration" issues (keep it open until the list is empty)

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4160]
- [x] it's possible to add text in the IP field of the captive portal tab
- [x] the reset button don't delete the text in the IP field on the captive portal tab
- [x] HTTP code 500 on the new billing tier tab
- [x] The error is not clear when a wrong path is set on the PKI provider path
- [ ] The locality list is empty in the SCEP PKI option in the PKI provider tab
- [x] Cannot add OS in the provisioner tab
- [x] Cannot reset conf of the portals modules
- [x] Cannot add new portals modules
- [x] Cannot reset configuration on new device registration tab
- [x] Cannot add OS in the new device registration tab
- [ ] Cannot delete the previous device registration created in the alt GUI in the old GUI

# Filter Engines
- [x] Tab names are different from old GUI and new GUI and not in the same order

**Comment by satkunas** [comment]
@jrouzierinverse the following are due to missing meta:
- The locality list is empty in the SCEP PKI option in the PKI provider tab
- Cannot add OS in the provisioner tab
- Cannot add OS in the new device registration tab

**Comment by satkunas** [comment]
> The error is not clear when a wrong path is set on the PKI provider path

Moved to #4224


>  Cannot delete the previous device registration created in the alt GUI in the old GUI

May be related, or not... Moved to #4225

**Comment by satkunas** [comment]
@cgx these are yours:
- Cannot reset conf of the portals modules
- Cannot add new portals modules

This looks similar to cache poisoning to/from the store. See https://github.com/inverse-inc/packetfence/pull/4220/commits/cdee0b79a5b90d3f3e151ba137622eb9378518dc for my fix using JSON to dereference in/out.

**Comment by jrouzierinverse** [comment]
The issue 'Cannot delete the previous device registration created in the alt GUI in the old GUI'
May not be an issue.
If a device registration is defined in a profile then it cannot be deleted.
This need better error handling.

**Comment by satkunas** [comment]
>  Tab names are different from old GUI and new GUI and not in the same order

Filters are dynamic and sorted in the backend. The best I can do is alphabetize them.

**Comment by satkunas** [comment]
Remainder moved to #4257
