### ISSUE TITLE
v9-gui: Issues for network configuration

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4161]
- [x] Cannot manage interfaces
- [x] Cannot manage inline traffic shaping policy
- [x] HTML tag visible in the title : generate signing request for certificate

**Comment by satkunas** [comment]
@dondon21 please retest the first 2 items.

**Comment by dondon21** [comment]
Cannot manage interfaces - fixed
HTML tag visible in the title : generate signing request for certificate - fixed
Cannot manage inline traffic shaping policy - I can add a rule but i cannot search it on my side.
