### ISSUE TITLE
v9-gui: "Audit > RADIUS Audit Log" issues (keep it open until the list is empty)

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4168]
- [x] RADIUS audit log doesn't show all information #4131
- [x] RADIUS audit log missing many search options #4132
- [x] Missing pre-configured searches (Switch groups, Roles, Status, etc.)
- [x] Inconsistent name between left panel (RADIUS Audit Log) and frame (Search RADIUS Audit Log**s**)
- [x] Icon for RADIUS Audit Log is missing 
- [x] `Search by .. username` must be `Search by .. Username`
- [x] Missing block to filter by date (Last 30 minutes, 1 hour, etc.)
- [x] Missing `Export to CSV`
- [x] Missing columns: request_time, NAS IP Address, NAS Port Type
- [x] MAC Address on each row are not clickable (to  directly display view from `Nodes` menu)
- [x] Missing colors to distinguish Accept/Reject auth status
- [x] Results are sorted on `Create at` column in reverse order (starting by oldest result)

**Comment by satkunas** [comment]
> Icon for RADIUS Audit Log is missing

No icon is needed

**Comment by satkunas** [comment]
> Search by .. username must be Search by .. Username

Capitalization is only needed on the first word or abbreviations.

**Comment by satkunas** [comment]
> Missing block to filter by date (Last 30 minutes, 1 hour, etc.)

Moved to advanced search, select "Created", then "greater than", and finally click -1H...-1Y (or CTRL+click to compound).

**Comment by satkunas** [comment]
Remainder moved to #4257
