### ISSUE TITLE
Debian 9: systemd-resolved prevent pfdns to start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4173]
When I start PF services, `pfdns` doesn't want to start with following message:
```
Apr  1 11:49:30 pfdeb pfdns: 2019/04/01 11:49:30 listen udp :53: bind: address already in use
```

Socket is in use by `systemd-resolved`:
```
root@pfdeb:/usr/local/pf# ss -nlup|grep :53                                        
[..]
UNCONN     0      0      127.0.0.53%lo:53                       *:*                   users:(("systemd-resolve",pid=95,fd=15))
[..]
```

Workaround:
```
systemctl stop systemd-resolved 
systemctl restart packetfence-pfdns
```

**Comment by nqb** [comment]
I got this behavior in a LXC container where `systemd-resolved` is enabled. Not the case in a default installation of Debian 9 in a Docker container or in a virtual machine.

**Comment by ehtishammubarik** [comment]
> I got this behavior in a LXC container where `systemd-resolved` is enabled. Not the case in a default installation of Debian 9 in a Docker container or in a virtual machine.

can you please share instructions on How can I download packetfence with Docker ?? 
I'm trying since last 3 days but no luck
