### ISSUE TITLE
v9-gui: columns selection

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4175]
In old GUI, it was possible to add several columns at same time by clicking on their names.

In new GUI, you can only add **one** column at same time.

**Comment by satkunas** [comment]
@nqb I don't understand. Which section are you referring to?

**Comment by nqb** [comment]
I spoke about usage of this button:

![Screenshot from 2019-04-08 07-55-23](https://user-images.githubusercontent.com/10830260/55701507-af910880-59d3-11e9-9bba-2c3ee0281f34.png)

If you want to add several new colums, you need to do:
1. Click on "Visible columns" button
2. Select your **first** new column name
3. Wait you new column has been added to your display
4. Click again on "Visible columns" button
5. Select your **second** new column name
..

In old GUI, at step 2, you can select several columns.
