### ISSUE TITLE
v9-gui: background-color between two rows

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4176]
In new GUI, there is no difference on background-color between two rows:

Old GUI:
![Screenshot from 2019-04-01 15-26-19](https://user-images.githubusercontent.com/10830260/55330968-a1eaf880-5492-11e9-8b51-1ba72e354639.png)

New GUI:
![Screenshot from 2019-04-01 15-26-27](https://user-images.githubusercontent.com/10830260/55330979-a6171600-5492-11e9-8a53-6f2124480c1e.png)

**Comment by satkunas** [comment]
Will be fixed in https://github.com/inverse-inc/packetfence/pull/4226
