### ISSUE TITLE
v9-gui: missing labels next to "Actions" and "Visible columns" buttons

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4177]
There is no label next to buttons "Actions" and "Visible columns":

![Screenshot from 2019-04-01 15-39-42](https://user-images.githubusercontent.com/10830260/55331811-62251080-5494-11e9-8e47-00be018cbd82.png)

**Comment by satkunas** [comment]
I think this was left out intentionally. 

@cgx do you think they need labels?

**Comment by cgx** [comment]
No, but a tooltip could be nice.

**Comment by nqb** [comment]
Current behavior:

![Untitled](https://user-images.githubusercontent.com/10830260/55701415-4e693500-59d3-11e9-9662-42deb0b3fd58.png)

**Comment by satkunas** [comment]
Will adjust the tooltip placement.

**Comment by nqb** [comment]
"Actions" has been set to "Bulk Actions".

Not tooltip for MsEdge.

**Comment by extrafu** [comment]
I don't see anything wrong in changing Actions to Bulk Actions. Moving to v9.1 for now.
