### ISSUE TITLE
v9-gui: Issues for system configuration

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4185]
- [x] Its possible to enter text in the ftp port field
- [x] Its possible to enter text in the PFDNS processes field
- [x] Its possible to enter text in the PFilter processes field
- [x] Cannot change maintenance flag buttons (need to clear each time)
- [x] Unauthorized access on the search field of the maintenance tab
- [x] Cannot manage radiusd service in the active active tab
- [x] Cannot manage radiusd service in the radius config tab
- [x] It's possible to create a user with the role ALL and the role NODE combined

**Comment by satkunas** [comment]
>  Its possible to enter text in the ftp port field

I don't see an FTP port in System Config. I added a port validator on SMTP server.


> Its possible to enter text in the PFDNS processes field

I don't see this field in System Config.


> Unauthorized access on the search field of the maintenance tab

We still need to show/hide specific elements depending on your admin roles. Currently everything is shown even if you don't have rights.


> Cannot manage radiusd service in the active active tab
> Cannot manage radiusd service in the radius config tab

Currently open at https://github.com/inverse-inc/packetfence/issues/4092


> It's possible to create a user with the role ALL and the role NODE combined

Please demo this to me

**Comment by dondon21** [comment]
I don't see an FTP port in System Config. I added a port validator on SMTP server.
In the Alerting tab, fixed now.

I don't see this field in System Config.
Sorry, i meant PFfilter, fixed now.

Please demo this to me
Fixed also.

**Comment by nqb** [comment]
I checked this items in initial description:
- Its possible to enter text in the ftp port field
- Its possible to enter text in the PFDNS processes field
- It's possible to create a user with the role ALL and the role NODE combined
