### ISSUE TITLE
API PATCH fingerbank/local/combination/:id not working

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4195]
Receiving 404 http response code with all of (resource update):

- PATCH fingerbank/all/combination/:id
- **PATCH fingerbank/local/combination/:id**
- PATCH fingerbank/remote/combination/:id

I assume it's only the `local` scope that should work.

**Comment by satkunas** [comment]
Also receiving a 404 with (resource creation):

- POST fingerbank/local/combination

**Comment by jrouzierinverse** [comment]
What is the exact response JSON response?


fingerbank/remote/combination route does not exists.
It is fingerbank/upstream/combination

**Comment by jrouzierinverse** [comment]
Patch is only allowed on local

**Comment by jrouzierinverse** [comment]
POST fingerbank/local/combination route does not exists
POST fingerbank/local/combinations is what you want.

**Comment by jrouzierinverse** [comment]
Fixed in 786793f6333ad196fdd2534cf5e3dc25d5902e2b please verify

**Comment by satkunas** [comment]
> What is the exact response JSON response?
> fingerbank/remote/combination route does not exists.
> It is fingerbank/upstream/combination

My bad @`remote`, but we shouldn't POST or PATCH to `upstream`, this should be `local` only.

I'll verify your other comments above.

**Comment by satkunas** [comment]
> What is the exact response JSON response?
POST /api/v1/fingerbank/local/combination

```json
{"errors":[],"message":"Unknown path \/api\/v1\/fingerbank\/local\/combination","status":404}
```

**Comment by satkunas** [comment]
@jrouzierinverse POST and PATCH now working.
