### ISSUE TITLE
POST fingerbank/local/combinations returns empty response

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4197]
```json
{"status":200}
```

Needs `message`, and `id` field returned in response.

**Comment by satkunas** [comment]
Same with DELETE fingerbank/local/combination/:id

```json
{"status":200}
```

Needs `message` in response.

**Comment by jrouzierinverse** [comment]
Like all create endpoints the id is in the location header.

**Comment by jrouzierinverse** [comment]
the delete message was added in 70bd30c86ea165834be6f1437b27b54529b20ada

**Comment by jrouzierinverse** [comment]
This is done
