### ISSUE TITLE
GET fingerbank/:scope/combinations requires not_deletable flag

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4198]
Need `not_deletable` key/value column in all responses to determine if a combination can be deleted (or not).

**Comment by satkunas** [comment]
Same with fingerbank/:scope/devices

**Comment by jrouzierinverse** [comment]
This is true for all fingerbank endpoints

**Comment by satkunas** [comment]
@jrouzierinverse It would be nice to also have a `not_updatable` flag in the collection so the front-end doesn't need to make an extra API call to determine if the resource is available `local`-lly when viewing via `all`. Or we can simply use the `scope` and calculate on the front-end. 

I realize that doing so might be redundant with `not_deletable` within this context, but I think we should separate them so the front-end can use them independently.
