### ISSUE TITLE
Multiple instances of pfconfig,pfdhcplistener,pfdetect and pfsetvlan can be started

### ISSUE THREAD

**Issue by rouzier** [inverse-inc/packetfence#420]
Multiple instances of pfconfig can be started.

**Comment by julsemaan** [comment]
Not sure it's really an issue. All the non binding pf services can (like pfdhcplistener).

It's the responsability of the init scripts to ensure only one process runs by managing the PID files.

We'll obviously see problems in our dev environments or if the PID file is lost.

We could use pidof to manage the process detection in the start/stop in the init script but (for good or bad reasons) all our services behave the way you describe.

I guess it's a subject opened for discussion to see whether this needs fixing or not

**Comment by rouzier** [comment]
No not all of our services behave in this way.
pfmon only allows one instance to run at a time.

It is also our responsibility to reduce mistakes from happening.
If we can add protection to prevent this mistake from happening we should do it.

**Comment by julsemaan** [comment]
I see this responsability belonging to the init script. 

If the user is starting instances of pfconfig by hand, he should know he could break something.

And then if we decide to apply the principle that services should control themselves then this needs to be integrated with the global handling of services (though pf::util::daemonize i think) since pfdhcplistener behaves this way. We should be fixing it once and for all for all services if this is really a problem.

**Comment by jrouzierinverse** [comment]
I agree it should be done for all services.
We should apply the same logic for all the services.

**Comment by julsemaan** [comment]
I'm not entirely conviced if the responsability belongs to the init script or the binary. We can quickly discuss that during the next meeting

**Comment by louismunro** [comment]
Either way, we don't have time to rewrite all services. 
That should be an item in the v5-v6 timeline.
I think this is good enough for now. 
Done is better than perfect.

**Comment by jrouzierinverse** [comment]
It does not require any major rewrite of all the services.
It will be handled in the daemonize function and change the how we delete the pid file

**Comment by julsemaan** [comment]
Do we do it for v5 ? @jrouzierinverse do you want to take ownership to do it ?

**Comment by jrouzierinverse** [comment]
I will take ownership of this

**Comment by julsemaan** [comment]
systemd fixed that
