### ISSUE TITLE
Need endpoint for Fingerbank Profiling -> Device Change Detection

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4200]
AKA https://packetfence:1443/admin/configuration#configuration/profiling/device_change

**Comment by julsemaan** [comment]
That is part of the base API call I believe since its part of pf.conf

**Comment by jrouzierinverse** [comment]
That is under /api/v1/config/base/fingerbank_device_change

**Comment by jrouzierinverse** [comment]
Reopen if you cannot find it.
