### ISSUE TITLE
API fingerbank/:scope/devices mobile/tablet cast discrepancy

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4205]
When using the GET :scope/devices the `mobile` and `tablet` are INTs.
```json
{"items":[{"approved":1,"created_at":"2014-09-09 15:09:50","id":1,"mobile":0,"name":"Windows OS","tablet":0,"updated_at":"2018-11-09 14:52:53"},...],"nextCursor":100,"prevCursor":0,"scope":"all","status":200}
```
When using POST ./search, the `mobile` and `tablet` is `null`.
```json
{"items":[{"approved":1,"created_at":"2015-04-16 19:42:07","id":6521,"mobile":null,"name":"Ubiquiti Android","tablet":null,"updated_at":"2015-04-16 19:42:07"}],"prevCursor":0,"scope":"all","status":200}
```

These should be casted to the same data types.

**Comment by jrouzierinverse** [comment]
This could be because of bad data in the sqlite db.
Since sqlite use the field types as a suggestion and not as a hard and fast rule.
Different rows can have different data types for the same column.

**Comment by jrouzierinverse** [comment]
I will cast every non null field as a string.

**Comment by satkunas** [comment]
Also cast those (non-null) INTs as strings too, so we have only strings on all endpoints.

**Comment by jrouzierinverse** [comment]
Done
