### ISSUE TITLE
Importing CSV with bypass_vlan skips all the nodes unconditionally 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4208]
Since 7.3, when you import a CSV with a bypass_vlan, it will skip the nodes since it needs the VLAN to be in the allowed roles for the user.

Since a VLAN is not a role, this results in all the nodes being skipped

Perhaps it was meant to be filtering on bypass_role and not bypass_vlan?

Problematic code was introduced here:
https://github.com/inverse-inc/packetfence/blame/packetfence-7.3.0/html/pfappserver/lib/pfappserver/Model/Node.pm#L401

Now that code is in import.pm and still has an impact on the command line import and the old+new admin

We should determine whether this should be bypass_role instead of bypass_vlan or just be removed completely since it doesn't seem to make sense. No sense, like a sandwich with more than 3 ingredients.

**Comment by lzammit** [comment]
Logs:
```
Apr  4 08:25:23 rsrinac001 httpd_admin: httpd.admin(64271) INFO: [mac:unknown] Category 'undef' (pf::import::nodes)
Apr  4 08:25:23 rsrinac001 httpd_admin: httpd.admin(64271) WARN: [mac:unknown] Ignored 00:11:22:33:44:55 since bypass_vlan 382 is not allowed for user (pf::import::nodes)
```

Import file:
```
00:11:22:33:44:55;yes hello;382
```

Import configuration
![image](https://user-images.githubusercontent.com/5261214/55556047-a0991600-56b4-11e9-82b5-9ffd044494f5.png)

**Comment by satkunas** [comment]
Nonsense. My sandwiches always have more than 3 ingredients.
