### ISSUE TITLE
v9-gui: Fingerbank sections issues/bugs

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4215]
- [x] Browsing devices allows to go in devices that have no childs and it shows an empty list (ex: Operating System/Linux OS/Generic Linux)
- [x] Devices should be ordered by name and not by ID
- [x] The index page of the devices should show the top level parents (parent_id IS NULL) and not all devices
- [x] Browsing the DHCP fingerprints doesn't show the upstream DHCP fingerprints
- [x] Clicking on "ADD DHCP FINGERPRINT" gets me to an empty page and a sh*tload of JS errors in the console
- [x] Impossible to create a new combination because its impossible to set a device. Tried the name "Windows OS" and the ID '1' and none of them were accepted, it doesn't allow me to press create
- [x] There are no typeaheads for the values of a combination
- [x] Combination values can be anything, we need to make sure that if a DHCP fingerprint that isn't in the local DB or upstream DB is POSTed, then it either fails or automagically create the DHCP fingerprint in the local DB. This applies to all attributes
- [x] Accessing a Fingerbank section (tried with DHCP fingerprints) throws a ton of errors about a missing API call named "TODO": 
![image](https://user-images.githubusercontent.com/3857942/55641558-2fcd2900-579c-11e9-886b-808443778305.png)

**Comment by satkunas** [comment]
@julsemaan all issues have been addressed.
