### ISSUE TITLE
Feature/SSO for Smoothwall Firewall

### ISSUE THREAD

**Issue by wifispray** [inverse-inc/packetfence#4218]
Would it be possible to add Smoothwall as a firewall SSO? I have tested this with the Fortinet SSO profile and this works when used with a Smoothwall firewall.

avr 05 14:44:10 HGSA3CLU03 packetfence_httpd.aaa[105848]: httpd.aaa(105756) INFO: [mac:[undef]] Sending a firewall SSO 'Update' request for MAC '08:e6:89:bf:6a:5d' and IP '10.1.208.19' and Username 'dwheeldon@gmail.com' (pf::firewallsso::do_sso)                             
avr 05 14:44:10 HGSA3CLU03 pfsso[89928]: t=2019-04-05T14:44:10+0000 lvl=info msg="Processing SSO Start" pid=89928 request-uuid=45c1771f-57b1-11e9-93e1-506b8dcd0c98 username=dwheeldon@gmail.com ip=10.1.208.19 mac=08:e6:89:bf:6a:5d role=HGS_Guest firewall-id=10.1.60.2

![image](https://user-images.githubusercontent.com/28165635/55652996-12707d00-57e5-11e9-97cc-4bc4c952679b.png)

**Comment by fdurand** [comment]
Added in PacketFence
