### ISSUE TITLE
v9-gui: question mark button is missing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4227]
In old GUI, when you click on question mark (`/admin/help`) on the left, you got this:
![Screenshot from 2019-04-08 11-09-55](https://user-images.githubusercontent.com/10830260/55712381-ea546a00-59ee-11e9-8f16-70b24a97c3f9.png)

This button is pretty useful.

API endpoint `/admin/help` doesn't seems to exist. Moreover, I didn't see any `doc` directory under `static.alt` to display embedded docs.

**Comment by nqb** [comment]
@jrouzierinverse: can you take care of the API endpoint ?

**Comment by jrouzierinverse** [comment]
I am not sure this is useful.
Help links are static I don't see the need to add this functionality.

**Comment by cgx** [comment]
No need for an API endoint, except for the PacketFence version.
