### ISSUE TITLE
v9-gui: missing button to go to embedded docs

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4228]
In old GUI, we have links to embedded docs in specific menu. For instance:

![Screenshot from 2019-04-08 10-59-31](https://user-images.githubusercontent.com/10830260/55712946-fb51ab00-59ef-11e9-89bf-f32e97173ffe.png)

I didn't find this feature on new GUI.

**Comment by satkunas** [comment]
@cgx and I spoke about adding an embedded asciidoc viewer, and reworking the inline `(?)`'s to utilize this. Alas, it won't make it in this release, so I'm marking it for 9.1.

**Comment by satkunas** [comment]
Moving to #4257
