### ISSUE TITLE
v9-gui: new admin not reachable through IE11

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4230]
With latest version of IE11, I got a blank page and following error when I go on `/admin/alt`:
![Screenshot from 2019-04-08 16-35-10](https://user-images.githubusercontent.com/10830260/55732470-513c4800-5a1c-11e9-91be-55503c6af6cb.png)

**Comment by cgx** [comment]
How about Edge?

**Comment by nqb** [comment]
It works !

**Comment by extrafu** [comment]
This is a low-priority item, moving to v9.1 and we'll see if we care about this. Chrome, Firefox and Safari are now dominating. Perhaps what we could do is show the user his/her browser is not supported instead of bailing out with an ugly error.
