### ISSUE TITLE
API - Could not connect to Redis server...

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4235]
I'm running minimal services for admin.  This does not include redis. But this is only context and not the real issue here...

When I try to add a new resource (eg: node) I get the following response:
```json
{"message":"Could not connect to Redis server at 127.0.0.1:6380 at \/usr\/lib64\/perl5\/vendor_perl\/Redis\/Fast.pm line 194.\n","status":500}
```

However the node was created successfully, because on the next attempt I get the response:
```json
{"errors":[],"message":"There's already a node with this MAC address","status":409}
```

We should either:
1) suppress this error message
2) prevent the resource from being created if this error occurs.

I'd prefer #1 since the resource was created successfully.

**Comment by jrouzierinverse** [comment]
Fixed by 5b99d7e76a772aecb6f4edbf4220269cd2bffe17
