### ISSUE TITLE
/usr/local/pf/lib/pf/config/util.pm comma missing

### ISSUE THREAD

**Issue by sealsgit** [inverse-inc/packetfence#4249]
Hello there,

I am using packetfence 8.3.0. 
I found a little bug with the guest email activation. The mail sent does not contain the correct activation link.
The problem is generated inside the util.pm at line 185
        i18n_format => \&pf::web::i18n_format
at the end of line a comma is missing it should be 
        i18n_format => \&pf::web::i18n_format,
othewise the following  %$data
is not appended and no link is generated.

Thanks.
     Gabriele

**Comment by jrouzierinverse** [comment]
That you for reporting.
This has been fixed by 8ba34547471646b1fde6ccec887b68568e310f46.
