### ISSUE TITLE
API GET /api/v1/user/<pid> → doesn't support PID with parentheses

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4267]
The API server can't retrieve a user with a parenthesis in the PID:

```bash
/usr/local/pf/sbin/pfperl-api get '/api/v1/user/(555) 123-1234' | jq
{
  "errors": [],
  "message": "Unable to get resource with this identifier",
  "status": 404
}
```

**Comment by satkunas** [comment]
If you need to use URI encoding, please extend https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js#L4
