### ISSUE TITLE
Reevaluate access is not called when autoregistering with a violation

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#427]
Not sure whether it's normal or not. IMO it should reevaluate the access.

**Comment by jrouzierinverse** [comment]
Can you create a pull request with the code you already have done?

**Comment by julsemaan** [comment]
@lzammit can you extract action_autoregister in action.pm from the setup it was made on

**Comment by louismunro** [comment]
What's the status on this? 
Please close if fixed.

**Comment by julsemaan** [comment]
fixed in 9688993668df9c345292c50103ad0429e30df6e4
