### ISSUE TITLE
Unifi multi-site external portal

### ISSUE THREAD

**Issue by mofm** [inverse-inc/packetfence#4280]
I have tested external portal with Unifi Controller Default site. Ok. It works perfectly. But I have 20 sites on Unifi Controller. 
Packetfence doesn't authorize clients different site other than default site. Because packetfence API works only default site.

```
-- in lib/pf/Switch/Ubiquiti/Unifi.pm:

   151 sub _deauthenticateMacWithHTTP {
   152     my ( $self, $mac ) = @_;
   153     my $logger = $self->logger;
   154 
   155     my $node_info = node_view($mac);
   156 
   157     my $controllerIp = $self->{_controllerIp};
   158     my $transport = lc($self->{_wsTransport});
   159     my $username = $self->{_wsUser};
   160     my $password = $self->{_wsPwd};
   161 
   162     my $site = 'default';     ===> here, 

--

```
162. line : 'my $site' variable is static and only 'default'. How can we change this? ( for multi sites)

**Comment by fdurand** [comment]
The code fetch all the sites and try to deauth until it succeed.

https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Ubiquiti/Unifi.pm#L202

**Comment by mofm** [comment]
@fdurand  Yes, you are right. But It isn't a solutions for multi-sites controller.  

Packetfence logs : https://gist.github.com/mofm/c9f6be45a5ffc4943d47a443ea33d2fe
Unifi logs: https://gist.github.com/mofm/328d9ae3feec1c389457da774f8002eb

**Comment by fdurand** [comment]
In your case "Deauth on site: default" mean that the mac address has been found on the default site so it's suppose to not be on another site.
If you want to deauth on all sites then remove this line: https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Ubiquiti/Unifi.pm#L216
And retry, maybe it's a bug on ubiquiti.

**Comment by mofm** [comment]
I have tested it. It works. Thank you @fdurand .
