### ISSUE TITLE
v9-gui: Policy and Access Control

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4282]
Sources
- [x] in general in the rule having Conditions before Action
- [x] Role/access duration empty list in authentication rule
- [x] Access Level is empty in administration rule
- [x] External Sources :
- {"errors":[{"field":"hash_passwords","message":"Database passwords hashing method field is required"}],"message":"Unable to validate","status":422}
- Missing in the form  : "Database passwords hashing method" "Password length"

- [x] Sources not sortabled (it's important)

Radius Source :
- [x] Missing Options in the form

EAPTLS Source:
- [x] Missing all specific attributes in condition  (Related to TLS)

Htpasswd Source:
- [x] we should see "It must be a valid path The file is not readable by the user 'pf'." as an error instead of unable to validate

SAML Source:
- [x] Attribute (authorization_source_id) is required at constructor pf::Authentication::Source::SAMLSource::new (defined at /usr/local/pf/lib/pf/Authentication/Source/SAMLSource.pm line 265) line 30
- [x] Authorization source is empty
- [x] {"errors":[],"message":"Unable to validate invalid no valid formater","status":422} when i try to save

Email Source / Oauth / Sponsor / Twilio / AuthorizeNet / Mirapay / Paypal / Stripe
- [x] Missing "Database passwords hashing method" and "Password length" in the form

Twitter Source
- [x] no create local account

Roles
- [x] Traffic shapping should be visible only if you have a inline config

Realms
- [x] Missing Radius Authentication and Radius Accounting column

Active Directory Domains
- [x] Missing status if the domain is joigned

Switches
- [x] Adding a switch propose twice the default group
![image](https://user-images.githubusercontent.com/1553962/56823765-c8e2e300-6822-11e9-8a05-b25e02573492.png)
- [x] SNMP version should be v2c by default 
- [x] SNMP public community should be public by default 
- [x] SNMP private community should be private by default 

Connection profiles
- [x] not sortabled (it's important)
- [x] Unknown path /api/v1/config/connection_profiles/search 
- [x] editor : {message: "Can't locate object method "file" via package "Moj…ontroller/Config/ConnectionProfiles.pm line 138.
- [x] Action type fqdn is not valid, ignoring
- [x] Creating a connection profile doesn't create the directory in the file system.

**Comment by jrouzierinverse** [comment]
The item 
```
editor : {message: "Can't locate object method "file" via package "Moj…ontroller/Config/ConnectionProfiles.pm line 138
```
Is this on debian or centos?

**Comment by jrouzierinverse** [comment]
Creating and viewing sources should be ok now.

**Comment by jrouzierinverse** [comment]
Twitter Source has no 'no create local account' at the moment

**Comment by fdurand** [comment]
editor : {message: "Can't locate object method "file" via package "Moj…ontroller... is on Debian

**Comment by jrouzierinverse** [comment]
This may be a packaging issue.

**Comment by satkunas** [comment]
@julsemaan can you test the following (if it's needed)?

>  Creating a connection profile doesn't create the directory in the file system.

**Comment by julsemaan** [comment]
@satkunas 

Its not technically needed since in the old admin when you do it in a cluster, it creates the directory only on the first server

But there is a warning about it in pfcmd checkup when it doesn't exist, IMO this should go and we shouldn't care if the directory is created unless there are some override files in it

**Comment by satkunas** [comment]
> But there is a warning about it in pfcmd checkup when it doesn't exist, IMO this should go and we shouldn't care if the directory is created unless there are some override files in it

@julsemaan should I open an issue on 9.1 to suppress the pfcmd checkup warning?

**Comment by julsemaan** [comment]
I'll remove the checkup warning of the empty directory

**Comment by nqb** [comment]
Can we close this case ?

**Comment by julsemaan** [comment]
On my side we're all good
