### ISSUE TITLE
v9-gui: Node manager admin role

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4285]
As a user with "Node Manager" role, I got unexpected behaviors:

# General
- [ ] a user with "Node Manager" role can't show version of PF (next to its name)

# Nodes - Read

- [ ] After clicking on a node, following informations is not displayed to user:
* Current role of node
* Info tab -> IP4 address field
* IPv4 tab
* Location tab
* Security Events tab
- [ ] When I click on owner of a node, user is disconnected without any error message

# Nodes - Create

# Nodes - Update

# Nodes - Delete

**Comment by julsemaan** [comment]
We'll review the built-in admin roles and add what is necessary

Related to #4335
