### ISSUE TITLE
v9-gui: Nodes menu: results by page and browsing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4286]
In Nodes menu, as admin user, I got unexpected behaviors:
- [ ] Number of results by page is empty and display 10 results by default:
![Screenshot from 2019-04-25 11-20-17](https://user-images.githubusercontent.com/10830260/56724937-35d77980-674c-11e9-85f9-6d571b7f93e2.png)
- [ ] When I want to go to page 2:
1. I click on "2" or ">" : page is updated and didn't change.
2. I click again on "2" or ">": second page is correctly displayed

**Comment by julsemaan** [comment]
@cgx will check if its still relevant and fix if necessary

**Comment by julsemaan** [comment]
@cgx, is this relevant ?

**Comment by satkunas** [comment]
> I click on "2" or ">" : page is updated and didn't change.
> I click again on "2" or ">": second page is correctly displayed

These were fixed this morning in https://github.com/inverse-inc/packetfence/commit/17384290b3b49b16fd7f40f0e2b2a58a087e1fdd (the page number was rubber-banding back to page 1)

**Comment by satkunas** [comment]
> Number of results by page is empty and display 10 results by default:

Likely due to a change after you manually selected 10 items/page. Clear your localStorage to reset.

Open Debugger > Application > Local Storage > [Choose PF admin host] > In the filter on top of the right-pane type "limit" > Highlight key/values in the right-pane and click [Delete]

**Comment by satkunas** [comment]
No outstanding issues here. Closing.
