### ISSUE TITLE
Changing "Redirection delay" value has no effect (window.waitTime)

### ISSUE THREAD

**Issue by alkalinelito** [inverse-inc/packetfence#4287]
Hi, I think this is bug and as instructed in PacketFence-users mailing list, I'm posting here. 

When you try to change "Redirection delay" in Configuration -> Advanced Access Configuration -> Captive portal   . It has no effect, it always takes the same time.

I think the problem lies here:

/usr/local/pf/html/captive-portal/content/timerbar.js

Line 6:

`var time = window.waitTime || 25;`

window.waitTime is undefined , so it always sets time to 25

Thank you.

**Comment by julsemaan** [comment]
fix merged and added to maintenance/9.0 and maintenance/8.3 (8.2 and below don't cherry-pick cleanly)
