### ISSUE TITLE
Filters getting replace by hash in portal profile (centos 7)

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#429]
In devel, if you add a portal profile and setup filters for it, the filters you add are gonna be replace by a hash value of it.
![profiles](https://cloud.githubusercontent.com/assets/9321079/6711401/3e481f9e-cd5d-11e4-903c-4a9b10b5a1a3.png)

**Comment by louismunro** [comment]
In 4.7?  
Surely you mean devel on Centos7, or have you been able to reproduce this on 4.7.0 ?

## 

LM

**Comment by jrouzierinverse** [comment]
Yes devel on crack Centos7

James Rouzier
jrouzier@inverse.ca :: +1.514.755.3630  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by whitx** [comment]
Yeah I meant devel my bad

**Comment by whitx** [comment]
This is not an issue anymore
