### ISSUE TITLE
Dashboard is empty because of redis

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4297]
Apr 29 09:38:05 daybiane admin_catalyst[21781]: httpd.admin(21129) ERROR: [mac:unknown] Couldn't render template "graph/dashboard.tt: undef error - Could not connect to Redis server at 127.0.0.1:6380 at /usr/lib/x86_64-linux-gnu/perl5/5.24/Redis/Fast.pm line 194.
                                                " (Catalyst::View::TT::_rendering_error)
Apr 29 09:38:05 daybiane admin_catalyst[21781]: httpd.admin(21129) ERROR: [mac:unknown] Couldn't render template "graph/dashboard.tt: undef error - Could not connect to Redis server at 127.0.0.1:6380 at /usr/lib/x86_64-linux-gnu/perl5/5.24/Redis/Fast.pm line 194.
                                                " (Catalyst::finalize)

**Comment by fdurand** [comment]
Debian and Centos

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by fdurand** [comment]
it's only on the old admin.

**Comment by extrafu** [comment]
Ok so that issue isn't reproducible in v9?

**Comment by jrouzierinverse** [comment]
FIxed by 1b302c0a6944b8ab564310b5d0f0b65124823725
