### ISSUE TITLE
API user/:id/close_security_event method needed

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4299]
Missing `close_security_event` method in lib/pf/UnifiedApi/Controller/Users.pm (only has `bulk_close_security_event`)

Like `close_security_event` from lib/pf/UnifiedApi/Controller/Nodes.pm

**Comment by jrouzierinverse** [comment]
Fixed by e8f19e4d94b3b2ee43762863c9b5426bef14099c
POST /api/v1/user/:user_id/close_security_events
