### ISSUE TITLE
PacketFence-PKI Installation for Debian is broken

### ISSUE THREAD

**Issue by pokmis** [inverse-inc/packetfence#4300]
The PacketFence-PKI installation package for Debian is broken.

Test environment:
Debian 8.11 
PacketFence 8.3

Steps to reproduce:
Following 3.1.4 from the installation instructions (https://packetfence.org/doc/PacketFence_PKI_Quick_Install_Guide.html) the following error messages when running the apt-get command:

command: 
sudo apt-get install packetfence-pki

errors:
Err http://inverse.ca/downloads/PacketFence/debian/ wheezy/wheezy python-django-bootstrap3 all 5.4.0-1
  404  Not Found [IP: 192.95.20.194 80]
Err http://inverse.ca/downloads/PacketFence/debian/ wheezy/wheezy packetfence-pki all 1.0.4
  404  Not Found [IP: 192.95.20.194 80]
Unable to correct missing packages.
E: Failed to fetch http://inverse.ca/downloads/PacketFence/debian/pool/wheezy/d/django-bootstrap3/python-django-bootstrap3_5.4.0-1_all.deb  404  Not Found [IP: 192.95.20.194 80]

E: Failed to fetch http://inverse.ca/downloads/PacketFence/debian/pool/wheezy/p/packetfence-pki/packetfence-pki_1.0.4_all.deb  404  Not Found [IP: 192.95.20.194 80]

E: Aborting install.

this post that discusses a similar issue but it doesn't appear to have been resolved: https://sourceforge.net/p/packetfence/mailman/message/35907472/

**Comment by nqb** [comment]
PacketFence PKI is now part of PacketFence starting from v10.
