### ISSUE TITLE
Configuration/Provisioner unable to create Accept provisioner

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4306]
When i try to create an accept provisioner i get this issue : 

DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: no such column: me.text [for Statement "SELECT me.id, me.name, me.mobile, me.tablet, me.created_at, me.updated_at, me.parent_id, me.inherit, me.submitter_id, me.approved FROM device me WHERE ( ( me.text = ? AND me.value = ? ) )"] at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 237 

Moreover I can't delete the value in the OS tab when only one entry is set.

**Comment by extrafu** [comment]
It is a GUI issue since it is not sending the proper value for OSes.

**Comment by satkunas** [comment]
May be fixed with https://github.com/inverse-inc/packetfence/commit/6f4130fc984ecc8eb7d236ec4c98f63f3dbfe8e5

@dondon21 Please re-test

**Comment by satkunas** [comment]
@dondon21 Please re-test

**Comment by dondon21** [comment]
Fixed
