### ISSUE TITLE
Admin: Add ability to configure OCSP + CRL in admin interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4308]
Would be good to be able to configure the OCSP and CRL of FreeRADIUS through the admin

**Comment by extrafu** [comment]
Indeed, I spoke about it to @fdurand last week.

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/7b06d2f5f4bd1aeedecefed0c4f37ce887b0cd38

**Comment by satkunas** [comment]
Example added in https://github.com/inverse-inc/packetfence/commit/c3be3bee384ca976d02e8493d4b1410644309d01

**Comment by julsemaan** [comment]
Code was made and is in devel
