### ISSUE TITLE
v9-gui: Cluster state not present in the new admin (Status > Cluster State)

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4313]
Old Admin:

![](https://lh3.googleusercontent.com/-sf1CoWuqteQ/XMojwZ_xzpI/AAAAAAAACF8/n1LYlSvgAXk7A6weRzsNhZjQ1aymod8LQCK8BGAs/s0/2019-05-01.png)

**Comment by nqb** [comment]
See also #4324

**Comment by nqb** [comment]
Cluster > Services is now visible in new GUI but it should be hide when running in standalone (current behavior in old GUI).
