### ISSUE TITLE
Configuration/connection_profile error

### ISSUE THREAD

**Issue by dondon21** [inverse-inc/packetfence#4317]
When I try to create a new connection profile with a valid source I get this error : 

Server Error - "sources.0": This field does not take multiple values
#/configuration/connection_profiles/new

**Comment by fdurand** [comment]
Already repported in https://github.com/inverse-inc/packetfence/issues/4257 (Sources/Billing/Provisioners/Scanners form issue, the field should only accept one value (sms should not be allowed in the example))
