### ISSUE TITLE
CHI Memcached should be moved to a binary protocol to avoid an injection attack

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#432]
Currently we are using the ascii protocol which could lead to some keys not being saved in memcached

**Comment by louismunro** [comment]
Just because, I disagree.
More seriously I worry about premature optimisation. 
Textual protocols are much easier to debug.

**Comment by rouzier** [comment]
It is causing a bug where we cannot save data in memcached. 
Derek hit it while testing his fingerbank integration.
