### ISSUE TITLE
v9-gui: Missing Fingerbank account information

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4320]
In the previous admin, you could see the username + API usage of the current API key in the top of the Fingerbank settings, right now nothing displays other than the header "Account information on api.fingerbank.org"

**Comment by julsemaan** [comment]
I've added the API endpoint (GET /api/v1/fingerbank/account_info)

All that is left is for @cgx or @satkunas to work their magic in the frontend to populate the data

**Comment by satkunas** [comment]
added in https://github.com/inverse-inc/packetfence/commit/7543f91fc85993bf5e2e9b5308bfe99116b294b5
