### ISSUE TITLE
v9-gui: Fingerbank OS select box doesn't contain common choices

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4321]
In the previous admin (ex: Provisioner OS configuration), the OS selection had a select box prepopulated with the common choices you could make (Windows OS, Apple OS, etc) so that its easier for someone to figure out what to select if they want to make common choices.

The new admin currently just shows all devices sorted alphabetically and common choices have to be searched and aren't as easy to select as before

I discussed with @cgx and adding the common choices to the top of the select box in a group would be good

**Comment by satkunas** [comment]
@cgx were you going to rework the search function, or should I?

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/0e36d405cd4c65d20f32a4bbbc3e921e88920474
