### ISSUE TITLE
PF v9 update on dev environment

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4322]
I'm not sure if it's legit or not:

Failed to open /usr/local/fingerbank/conf/fingerbank.conf: Permission denied at /usr/local/pf/lib/pfconfig/namespaces/config.pm line 59.
cannot create a tied pf::IniFiles at /usr/local/pf/lib/pf/IniFiles.pm line 413.

**Comment by extrafu** [comment]
@lzammit  Who should take care of this? Please assign.
