### ISSUE TITLE
API endpoint needed to check if file exists

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4332]
Required to check if file exists when setting up htpasswd source. Would be nice if we could check any path and return the owner/group/and file mode bits.

**Comment by jrouzierinverse** [comment]
This error is returned when saving or updating the Htpasswd just reuse the error given when saving.

In the future we should allow people to upload the file they want to use for certs to make it easier for them to man.

**Comment by julsemaan** [comment]
Please ensure you put the appropriate milestone when opening issues for 9.0, otherwise this will be lost

**Comment by jrouzierinverse** [comment]
This is a low priority as this would be an enhancement not fixing any bug.
I will move this to 9.1 unless anyone has any objections.

**Comment by julsemaan** [comment]
I agree with @jrouzierinverse 

If an error is thrown when saving on the server and its displayed to the user, then its good enough for 9.0

**Comment by jrouzierinverse** [comment]
I think we should close this issue.
I would prefer not to have an API call to check the existence of a file.
It only provides very little improvements and can open ourselves to leaking information.
