### ISSUE TITLE
API usage: missing information in ConfigBase model

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4338]
Hello,

When you browse https://github.com/inverse-inc/packetfence/blob/devel/docs/api/spec/components/schemas/configbase.yaml, you can't get **id** of each ConfigBase object (like `general`, `network`, `fencing`, etc.) which is really helpful when you want to use API.

However, when you query API, you got this information:
```console
# /usr/local/pf/sbin/pfperl-api get -M GET /api/v1/config/bases |  jq '.[] | .[0]'
{
  "dhcpservers": "127.0.0.1",
  "domain": null,
  "hostname": null,
  "id": "general",
  "not_deletable": true,
  "timezone": ""
}
```

Just tell me if I need to edit `docs/api/spec/components/schemas/configbase.yaml` and I will do it.

**Comment by satkunas** [comment]
@nqb you can consume each base individually with the URL:

`/api/v1/config/base/:id`

Example:

`/usr/local/pf/sbin/pfperl-api get -M GET /api/v1/config/base/general`

This was added later, and probably why the spec missed it.

**Comment by nqb** [comment]
hey @satkunas,

Thanks for your answer. I agree with you and I was aware of this. Sorry if my question was unclear.

In fact, I would like to know where can I get a list of all ids available for `/api/v1/config/base/`. I understand you, you mean this information is missing from the specs ?

**Comment by satkunas** [comment]
There's no endpoint for just the ID's, but you can consume the collection `bases` to list them

`/usr/local/pf/sbin/pfperl-api get -M GET /api/v1/config/bases |  jq '.items[].id'`

**Comment by nqb** [comment]
Thanks @satkunas
