### ISSUE TITLE
v9-gui: automatically set LDAP port in LDAP source 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4339]
Currently, when you create a LDAP source, you got 389 as destination port.

When you select SSL, port should change to 636. 

"Port" field should be replace by a dropdown list. "Secure" field should be put **before** "Port" field.

**Comment by satkunas** [comment]
Some confirmation is needed before I attempt to make these changes:

> When you select SSL, port should change to 636.

@nqb - if we automatically populate the port number, then you are comfortable if the port is overwritten everytime the dropdown is touched, even if it is user-defined? 

> "Port" field should be replace by a dropdown list. 

@nqb - so we will remove the ability to use non-standard ports?

**Comment by julsemaan** [comment]
IMO limiting ourselves to the standard LDAP ports could backfire

If we really want to address this, we could do have a dropdown like @nqb suggests but that also contains an option named 'custom'. So selecting between 'plain', 'ssl', 'start_tls' would configure the port accordingly, but selecting custom would allow you to configure the protocol and the port manually for the times when its needed

An easier option that is less intrusive would be to hint the user to put the port to 636 when the type is SSL without auto-magically performing the change for him

**Comment by satkunas** [comment]
Helper added:

![Selection_031](https://user-images.githubusercontent.com/3904468/58502866-6a788f80-8155-11e9-9204-ff01e0a0e7df.png)
