### ISSUE TITLE
v9-gui: Tenant different from default are not display

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4340]
Nightly builds.

I create a tenant ID through command line:
```bash
# pfcmd tenant add 20
```

API is aware of this new tenant:
```console
# /usr/local/pf/sbin/pfperl-api get -M GET /api/v1/tenants | jq '.[] | .[2]'
{
  "domain_name": null,
  "id": 3,
  "name": "20",
  "portal_domain_name": null
}
```
but I can assign this tenant to a user in new GUI (only `default` tenant appears)

**Comment by julsemaan** [comment]
The new GUI will not be tenant aware AFAIK for 9.0 given the tight deadline we have so that might be a 9.1 issue

**Comment by nqb** [comment]
Moving to 9.1

**Comment by julsemaan** [comment]
GUI is now tenant aware
