### ISSUE TITLE
v9-gui - Old gui radius audit log doesn't work anymore

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4345]
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in addition (+) at /usr/local/pf/html/pfappserver/root/auditing/radiuslog/search.tt line 21.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in numeric le (<=) at /usr/local/pf/html/pfappserver/root/macros.inc line 35.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in subtraction (-) at /usr/local/pf/html/pfappserver/root/macros.inc line 35.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in addition (+) at /usr/local/pf/html/pfappserver/root/auditing/radiuslog/search.tt line 58.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in numeric le (<=) at /usr/local/pf/html/pfappserver/root/macros.inc line 35.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin_err[30968]: [Mon May  6 11:28:19 2019] -e: Argument "" isn't numeric in subtraction (-) at /usr/local/pf/html/pfappserver/root/macros.inc line 35.
mai 06 11:28:19 facketfence.barriereapaquet.org httpd_admin[30974]: httpd.admin(30963) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Auditing::RadiusLog->index "Can't locate object method "members" via package "pf::ConfigStore::SwitchGroup" at /usr/local/pf/lib/pfappserver/PacketFence/Controller/Auditing/RadiusLog.pm line 59." (pfappserver::PacketFence::Controller::Root::end)

**Comment by jrouzierinverse** [comment]
Fixed by 393c9784342ab0a4f0f1c095103f481809f4dce7
