### ISSUE TITLE
Security Event GUI: empty select boxes / no typeahead for some triggers

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4349]
Currently missing values in the select boxes or a typeahead field for the following values:

* Switch
* Switch group
* All device profiling (Device, DHCP fingerprint, MAC Vendor, etc)
* Nexpose contains + starts with

**Comment by julsemaan** [comment]
@cgx will check if the OPTIONS contain the good stuff, if not he'll reassign to @jrouzierinverse

**Comment by cgx** [comment]
- [x] *Switch*: works for me.
- [x] *Switch group*: missing from the Web admin, but working with `pfperl-api`. ACL issue?
- [x] *Device*: works for me (lookup).
- [x] *DHCP(6) fingerprint*: missing lookup definition.
- [x] *MAC vendor*: missing lookup definition.
- [x] *Nexpose event starts with*: fixed.
- [x] *Nexpose event contains*: missing allowed values.

**Comment by cgx** [comment]
Can either @julsemaan or @jrouzierinverse take care of the API endpoints?

**Comment by julsemaan** [comment]
I'll dive into what is missing in the API endpoints and reach out to @jrouzierinverse in case I start drowning

**Comment by julsemaan** [comment]
@cgx, the lookup API endpoints are there for all the Fingerbank data points so they can be implemented as far as I can tell like with the devices:
```
sbin/pfperl-api get -M POST -c '{"query":{"op":"and","values":[{"op":"or","values":[{"field":"name","op":"contains","value":"dell inc"}]}]},"fields":["name","id"],"sort":["name"],"cursor":0,"limit":100}' /api/v1/fingerbank/all/mac_vendors/search
```

As for my comment about devices that was missing, I was actually wrong

**Comment by julsemaan** [comment]
Switch group works on my end now so I guess all is good on that side too

**Comment by julsemaan** [comment]
And for nexpose event contains, there is no widget to help select it in the previous admin although I thought there was one so this is fixed too

**Comment by julsemaan** [comment]
Seems just the lookup needs to be adjusted for all the Fingerbank data points to use the existing search API endpoint and we'll be good

**Comment by jrouzierinverse** [comment]
Fixed the lookup

**Comment by julsemaan** [comment]
All is done here then, closing the issue
