### ISSUE TITLE
Just getting started - no email or sms working.. phone providers in the UK are missing

### ISSUE THREAD

**Issue by sussedtoy** [inverse-inc/packetfence#435]
Hi 

New to packet fence
This looks awesome!
Loving the captive portal - just installing some strawberry perl to get me going.. hope i can change it so it looks a bit more simple..
I don't receive any sms's, is there any specific config for this? There are no UK mobile phone providers listed, can I update this?
for emails - do I need to start and SMTP service on the packetfence server? I'm using the zero effort 4.7.. the captive portal is working..

**Comment by extrafu** [comment]
Please use the mailing list for questions about the project.
