### ISSUE TITLE
SSL Certificates GUI: No CA certificate field required for HTTP

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4353]
The CA certificate field shouldn't be there for the HTTP type in the SSL certificate configuration

**Comment by cgx** [comment]
The API endpoint should not return a *ca* attribute for the HTTP certificate. Reassigning to @jrouzierinverse.

**Comment by julsemaan** [comment]
I can take care of this one actually, less on @jrouzierinverse's plate
