### ISSUE TITLE
Missing WMI tab in new admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4357]
The WMI tab in the node details is currently missing

**Comment by julsemaan** [comment]
@satkunas, can we aim to make this a thing for 9.1 ?
This is a regression from pre-9.0

**Comment by nqb** [comment]
Hello,

Is it something that has been forgotten since 9.1 ?

**Comment by extrafu** [comment]
API endpoints are missing. @jrouzierinverse will need to add them first.

**Comment by satkunas** [comment]
Bumping release to revisit.

**Comment by extrafu** [comment]
Closing, we dropped WMI support.
