### ISSUE TITLE
Configuration: Message when saving a base section

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4359]
When saving a base section, the success message is "$section_name updated" where $section_name is the raw section name which isn't friendly.

We should just change this to something more generic like "Settings updated"

**Comment by julsemaan** [comment]
Not sure if this is in the backend or frontend so I'm assigning @jrouzierinverse and @satkunas

**Comment by jrouzierinverse** [comment]
Fixed by 0f9ccd32c1d94bc4f3a5d456b3900207a021f373
