### ISSUE TITLE
Need to be able to print a user when creating it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4360]
When creating one or multiple users, we should be able to print the details of the account(s) for use as vouchers. Also to send the details in an email

Requires #4355

**Comment by julsemaan** [comment]
The necessary API endpoint is there

Example:
```
sbin/pfperl-api get -M POST -c '{"template":"guest_local_account_creation", "args":{"pid":"bob-pas-de-bobette", "password":"pain-dinde-moutarde"}}' /api/v1/email/preview | jq -r .body > /tmp/email.html
```

**Comment by cgx** [comment]
We also need an endpoint to actually send the mail.

**Comment by julsemaan** [comment]
I'll open another issue for that

**Comment by cgx** [comment]
Would it be easy to also return the subject and the sender?

**Comment by julsemaan** [comment]
For the preview I didn't support the subject so its currently a dummy subject

The subject is only supported when sending an email
