### ISSUE TITLE
Security events tab is empty for nodes and users

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4361]
The security events tab for user and node details is currently empty.

We need an API endpoint to expose these to the frontend since the standard search currently has a limitation for that type of search.

@jrouzierinverse will do the API endpoint, @satkunas adjust the frontend

**Comment by satkunas** [comment]
Front end completed in https://github.com/inverse-inc/packetfence/commit/7b1d848ad12a8eb32268cea075bcc6395d7993da
