### ISSUE TITLE
Custom reports: add node+user clickable support

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4364]
In the new GUI, the node + user fields defined in the custom report declaration aren't honored like in the old admin to have it so clicking on the data of the field would open the details of the node or the user

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/53a855865b0d15a82bab1d9a8261b5148ce21d4d

@julsemaan Should we attempt to linkify the standard report columns as well?

**Comment by julsemaan** [comment]
@satkunas, we could but it would be using statically defined stuff since the server side won't expose it.

I'd say for now its enough with the dynamic reports only which makes us on par with the previous admin
