### ISSUE TITLE
V9 Radius Audit log status color

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4367]
Disconnect-ACK and COA-AcK should be green

![image](https://user-images.githubusercontent.com/1553962/57251869-e5e49680-7018-11e9-90ee-5aabd3553016.png)

**Comment by satkunas** [comment]
@fdurand should be fixed in https://github.com/inverse-inc/packetfence/commit/cd9cbfb2f30fee39e9a8b5721343be04fba23b7c

Please test or send me your dataset so I can test.

**Comment by jrouzierinverse** [comment]
You check the logic here.
https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/auditing/radiuslog/search.tt#L32
More simply if auth_status is Reject show red everything else is green.

**Comment by fdurand** [comment]
Fixed
