### ISSUE TITLE
Fortigate SSO - no acct_session_id on accounting start

### ISSUE THREAD

**Issue by slaggi** [inverse-inc/packetfence#4369]
For the Fortigate SSO:

There is no session id sent in the Radius Accounting Start packet. Though, it is added to the Accounting Stop. This is not a problem for the Fortigate, but it does create an issue if it is used with the FortiAuthenticator which expects a session id and creates an error on the missing session id.

go/firewallsso/fortigate.go 
+40      rfc2866.AcctSessionID_AddString(r, "acct_pf-"+info["mac"])

**Comment by julsemaan** [comment]
Easy enough, we'll take care of that after the 9.0 rush

**Comment by julsemaan** [comment]
fixed in 6182e190db and cherry-picked up to maintenance/8.0
