### ISSUE TITLE
v9-gui: Connection profiles

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4374]
# Create

- [x] When I try to create a new connection profile, profile name is auto-filled to "default". Should be empty.
- [x] Enable profile button is not display
- [x] It's not possible to create filters
- [x] Filter: width of select type select box is too narrow

# View
- [x] Default connection profile is disabled

**Comment by nqb** [comment]
Ok, I change "default" to "test" and all looks good but this behavior is a bit confusing.

**Comment by satkunas** [comment]
@jrouzierinverse `status` field is missing in response for only `default`.

**Comment by jrouzierinverse** [comment]
The status field is not editable for the default profile.
How do you want to handle this in the options

**Comment by jrouzierinverse** [comment]
Fixed by 645fa4a45aa9a0459f1af8dfdf0edc51d80dd244 please verify

**Comment by jrouzierinverse** [comment]
Can you clear the id field after cloning.

**Comment by satkunas** [comment]
> Fixed by 645fa4a please verify

@jrouzierinverse fixed

**Comment by satkunas** [comment]
> Can you clear the id field after cloning.

It helps indicate which item is being cloned. The user only needs to add a prefix.
