### ISSUE TITLE
Debian 9: error when going to Provisioners menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4377]
Nightly builds of Debian 9

When going to Provisioners menu or trying to create a new provisioner, I got this error message:
```
May  7 13:26:12 1cfd437ff0c3 packetfence: ERROR pfperl-api(21175): Attempt to bless into a reference at /usr/share/perl5/Moo/Object.pm line25.(Mojolicious::Plugin::DefaultHelpers::_development)
May  7 13:26:12 1cfd437ff0c3 packetfence: ERROR pfperl-api(21175): Attempt to bless into a reference at /usr/share/perl5/Moo/Object.pm line 25.(Mojolicious::Plugin::DefaultHelpers::_development)         
```
Issue is not present on CentOS nightly builds (0.201905060736.el7).

**Comment by jrouzierinverse** [comment]
Is this only on Debian?

**Comment by nqb** [comment]
@jrouzierinverse: yes, exactly.

**Comment by jrouzierinverse** [comment]
I know why this is happening but I need to find out where.

**Comment by nqb** [comment]
@jrouzierinverse: tell me if I can help.

**Comment by fdurand** [comment]
I am not able to replicate on debian, can you retry with the new package ?

**Comment by extrafu** [comment]
What's the status on this? If @fdurand you can't replicate, close it and it'll get re-opened if @nqb has the issue again.

**Comment by fdurand** [comment]
Just did a test and worked
