### ISSUE TITLE
New admin allows to multi-click the save button while the API is saving stuff

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4387]
Some of the API calls to save settings (like the certificate PUT) take a lot of time to occur and the GUI doesn't give feedback that the API call is currently being made allowing to multi-click the Save button and fire many API calls

The button should be disabled while the call is happening and provide feedback that magic is happening

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/ced5b48cc13442c1828e18f7f03ed1a6d9b849be
