### ISSUE TITLE
Connection profile default values during creation

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4391]
When creating a new connection profile, the default values are the ones of the default section meaning it auto-selects some provisioners and some sources

It should instead take the defaults of the pfappserver form

Not sure if the issue lies in the API or the frontend

@satkunas and @jrouzierinverse, can you check this out

**Comment by satkunas** [comment]
I just confirmed that defaults are populated from OPTIONS. This is a back-end change for @jrouzierinverse

**Comment by jrouzierinverse** [comment]
This has been fixed by 78ce3b2bd185109e18bd9f1c5ed46d1815f193fa please verify

**Comment by julsemaan** [comment]
works now
