### ISSUE TITLE
Debian 9: rights on server.key

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4393]
Nightly builds.

Rights on server.key differs on Debian and CentOS:

Rights on Debian:
```
root@b09f89d101bb:/home/kitchen# ls -rtl $SSL
total 16
drwxrwxr-x 2 pf   pf   4096 May  8 04:40 acme-challenge
-rw------- 1 root root 1679 May  8 09:06 server.key
-rw-r--r-- 1 root root 3318 May  8 09:06 server.pem
-rw-r--r-- 1 root root 1639 May  8 09:06 server.crt
root@b09f89d101bb:/home/kitchen# ls -ld $SSL
drwxrwxr-x 3 pf pf 4096 May  8 09:06 /usr/local/pf/conf/ssl
```

Rights on CentOS:
```
[root@0d1a99eaa2cd kitchen]# ls -rtl $SSL/
total 16
-rw-r--r-- 1 root root 1679 May  7 10:23 server.key
-rw-r--r-- 1 root root 1639 May  7 10:23 server.crt
-rw-r--r-- 1 root root 3318 May  7 10:23 server.pem
drwxr-xr-x 2 pf   pf   4096 May  7 21:09 acme-challenge
[root@0d1a99eaa2cd kitchen]# ls -rtl $SSL/ -d
drwxr-xr-x 3 pf pf 4096 May  7 21:09 /usr/local/pf/conf/ssl/
```

**Comment by nqb** [comment]
When you want to configure SSL Certificates from new GUI, you got an error message.

**Comment by cgx** [comment]
Please add the error message from the GUI and from the logs.

**Comment by nqb** [comment]
@cgx: I will do it but it's just an error related to rights.

**Comment by nqb** [comment]
We got this issue because `make conf/ssl/server.key` which use `openssl genrsa -out /usr/local/pf/conf/ssl/server.key 2048` on both distros doesn't set right the same way. Debian is more restrictive.

**Comment by nqb** [comment]
Doing a `chown pf /usr/local/pf/conf/ssl/server.pem` fix the issue.
