### ISSUE TITLE
v9-gui: sponsor field for Users

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4395]
# Lost from old GUI

- [x] Start date field in "Registration window" was set to current day
- [x] Access Level was automatically selected as Action
- [x] "Access Level" was mandatory when creating a user
- [x] PSK warning on number of characters
- [ ] When a new user was created, its `sponsor` field was populated with `pid` of current user. This will cause issue in new GUI (for users created on old GUI) because `Sponsor` field need to be an email address.

# Issues
- [x] Sometimes some users are created in password table with `tenant_id = 0` (not able to reproduce)
- [x] In order to have correct display for users, i.e:
* hiding passwords just set
* displaying "Tenant ID" in "Actions" menu

It looks like it's necessary to get a new token (I did a CTRL+F5)
- [x] Unassign nodes displayed on Security Events tab 
- [x] Mark as sponsor didn't set `sponsor` value in `password` table at `1`

**Comment by nqb** [comment]
@jrouzierinverse,

>     * Mark as sponsor didn't set `sponsor` value in `password` table at `1`

Seems to be cause by frontend. If I set `can_sponsor` at `1` or `sponsor` at `true` when doing API calls, nothing happens in DB.

**Comment by satkunas** [comment]
>  "Access Level" was mandatory when creating a user

I'm able to create a new user without `access_level` in the old admin. Not implementing in new.

**Comment by satkunas** [comment]
> PSK warning on number of characters

`psk` character limit is based on database schema. Ignoring.

```sql
CREATE TABLE `person` (
  ...
  `psk` varchar(255) DEFAULT NULL,
  ...
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

**Comment by satkunas** [comment]
> When a new user was created, its sponsor field was populated with pid of current user. This will cause issue in new GUI (for users created on old GUI) because Sponsor field need to be an email address.

@jrouzierinverse this will need to be populated in the back-end.

**Comment by satkunas** [comment]
First 2 points fixed in https://github.com/inverse-inc/packetfence/commit/c7c6e4c21ca498969b0a94e6c349e8a84e0f442e

The remainer is for @jrouzierinverse

**Comment by julsemaan** [comment]
@jrouzierinverse: Adjust the backend to auto-fill the sponsor field during POST on user creation (only creation)

**Comment by julsemaan** [comment]
@nqb, can you verify the fix @jrouzierinverse did for the auto-fill of the sponsor

**Comment by julsemaan** [comment]
fix by @jrouzierinverse in a41709bb645602313490eb604c2d30a3f17bcb06

**Comment by julsemaan** [comment]
@satkunas will add a note saying if nothing is put into that field, it gets autopopulated with the current user

**Comment by nqb** [comment]
@satkunas and @jrouzierinverse 

On latest builds in new GUI, sponsor field is not populated with current user. Moreover, take care of the fact that new GUI now checks if sponsor field is an email address (not the case in old GUI).

**Comment by satkunas** [comment]
> @satkunas will add a note saying if nothing is put into that field, it gets autopopulated with the current user

Note added in https://github.com/inverse-inc/packetfence/commit/11da915a56113c7f0b71f7a89df6fcec3039eb10

![Selection_027](https://user-images.githubusercontent.com/3904468/57717072-65411e00-7648-11e9-8c94-d936f3a1cec7.png)

**Comment by extrafu** [comment]
Is that bug still relevant?

**Comment by nqb** [comment]
Hello,

Current status:
* If I create a new user from **new** GUI, I got note added by @satkunas. However, after creation `Sponsor` field is still empty.
* If I create a user from API call, `Sponsor` field is set to **pid** of user used to do creation. Consequently, you can edit your new user in new GUI because you get "Invalid email address" for `Sponsor` field.

**Comment by julsemaan** [comment]
@satkunas will make this the default in the frontend

**Comment by extrafu** [comment]
Workaround added, moving to v9.0.1.

**Comment by satkunas** [comment]
Workaround added in https://github.com/inverse-inc/packetfence/commit/31a4dc3419989312de0b22273c5e7a2e60e0af06

Remove workaround once backend applies default sponsor.

**Comment by jrouzierinverse** [comment]
Just tested this and it works when no sponsor is set.

**Comment by julsemaan** [comment]
Works for now, lets readdress this in 9.1

**Comment by jrouzierinverse** [comment]
I think this can be closed. @nqb can you verify?

**Comment by nqb** [comment]
@jrouzierinverse, 

I only see 31a4dc3 commit which is a workaround related to this issue.
Did you make other changes to fix this issue ?

**Comment by jrouzierinverse** [comment]
commit a41709bb Automatically fills in the sponsor with current_user.

**Comment by extrafu** [comment]
@nqb Can we close this?

**Comment by nqb** [comment]
> Can we close this?

@extrafu, I suppose @satkunas wants to remove its workaround added by 31a4dc3 before.

**Comment by nqb** [comment]
@satkunas, yet another for you that can certainly be quick closed.

**Comment by julsemaan** [comment]
@satkunas, please provide input on this issue based on @nqb's comments
