### ISSUE TITLE
v9-gui - Lack of admin permission in radius audit log (Sometimes)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4397]
Unauthorized access, lacking the AUDITING_READ_READ administrative role (/api/v1/dhcp_option82s/search)

**Comment by cgx** [comment]
Must [blame](https://github.com/inverse-inc/packetfence/commit/3015531899f56d4d03967426733abae738bddb6a) @julsemaan.

**Comment by julsemaan** [comment]
https://youtu.be/ynMk2EwRi4Q?t=145
