### ISSUE TITLE
V9-gui - Network configuration is not available for local network

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4398]
![image](https://user-images.githubusercontent.com/1553962/57389438-36c6cd00-7188-11e9-9af8-7be5fa85bae5.png)

![image](https://user-images.githubusercontent.com/1553962/57389477-49410680-7188-11e9-8926-46351c3e4ed2.png)

As you can see there is no way to edit 172.20.135.0

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/cf6618c60cd28899f67ab20f61cccdd62043b5bb
