### ISSUE TITLE
v9-gui - Firewall sso page just spinning

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4400]
![image](https://user-images.githubusercontent.com/1553962/57400946-a0ec6b80-71a2-11e9-91bd-546ea00d4f2b.png)

**Comment by julsemaan** [comment]
Loads on my end, errors in the JS console?

**Comment by fdurand** [comment]
nop

**Comment by satkunas** [comment]
Not able to reproduce. Closing.

**Comment by satkunas** [comment]
Moved to #4404
