### ISSUE TITLE
admin roles: Index displays ALL and ALL_PF_ONLY

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4401]
The admin roles listing (/admin/alt#/configuration/admin_roles) displays ALL and ALL_PF_ONLY but these aren't viewable nor editable and they should be hidden from that list

**Comment by julsemaan** [comment]
Also displays NONE which shouldn't be displayed

**Comment by cgx** [comment]
See #3646.

**Comment by extrafu** [comment]
@julsemaan Who should take care of this? Please assign.
