### ISSUE TITLE
Adjust the amount of pfperl-api workers

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4402]
Right now we have 4 pfperl-api workers

I believe this number is static so heavy usage of the admin by multiple users won't make more processes spawn which will likely require us to just bump up the amount of workers to be safe

Probably 8 would be enough

**Comment by jrouzierinverse** [comment]
Should we make it configurable?

**Comment by julsemaan** [comment]
@jrouzierinverse 

Would be good to have it configurable, probably in pf.conf's services section

Or somewhere else if you have a better idea

**Comment by cgx** [comment]
Shall we expose this parameter in the Web admin?

**Comment by extrafu** [comment]
I would suggest to not do so for v9 at least.

**Comment by julsemaan** [comment]
@cgx, it depends how much time it takes. If its a 5 minutes thing, then I'd say it would be good to have it there

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/e343bdeb2da2a0e2ea0bf35aa4d4590aa0a2ee6a
