### ISSUE TITLE
API GET config/firewalls error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4404]
When using the following in `firewalls_sso.conf`
```
[172.20.20.1]
categories=
port=8443
username=pf
cache_updates=0
password=pf
username_format=$pf_username
type=JuniperSRX
```

The API response is malformed:

```json
{"items":[null],"nextCursor":1,"prevCursor":0,"status":200}
```

From #4400

**Comment by fdurand** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/d60cf52a321dbeb5c2f75fe0d0483da2e90f7fb1
