### ISSUE TITLE
v9-gui: Security Event autoreg

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4406]
The clone button does not auto-increment the ID of the security event.

Once I create the violation it does not display in the new admin but works on the old admin.

[1100055]
priority=1
trigger=mac::d8:1c:79:85:dd:3b
actions=log,autoreg,email_admin
max_enable=3
desc=Auto-register Device example
enabled=Y
access_duration=12h
template=generic
auto_enable=Y
delay_by=0s
grace=120m
button_text=Enable Network
target_category=default
whitelisted_roles=

The Autoreg violation works properly.

**Comment by extrafu** [comment]
@lzammit  Who should take care of this? Please assign.
