### ISSUE TITLE
v9-gui: syslog parser does not display that you need to restart pfdetect  / pfqueue

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4409]
It would be nice to have pfqueue and pfdetect restart/start button within the Parser creation

**Comment by jrouzierinverse** [comment]
This is a new feature move to 9.1

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/54cbea8e775650d12ebeb2080417787b9fe88ec8

**Comment by lzammit** [comment]
Fixed
