### ISSUE TITLE
Nodes view: unable to view all selected columns

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4413]
In the node view (guessing this applies to other places as well), if I add enough columns so that the data overflows on the right, there is no way to scroll right to view it

In my case, I only had to add a single column so that my screen was too narrow to display all the data:
![image](https://user-images.githubusercontent.com/3857942/57451641-dbe8b080-722f-11e9-8e1b-c56202871588.png)

**Comment by cgx** [comment]
I'm able to scroll the entire table to the right.

Scroll down to the last row and you'll see the horizontal scrollbar.

**Comment by julsemaan** [comment]
yes indeed, we've had a fine case of semaan blindness
