### ISSUE TITLE
Reevaluate access button always disabled

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4415]
I have a node that has a valid location and the "Reevaluate access" button in the node details is still grayed out and disabled

**Comment by satkunas** [comment]
Please include the nodes data.

Here's the logic behind enable/disable w/ this button:

```js
(node.locations && node.locations.length > 0 && ((node.ip4 && node.ip4.ip) || (node.ip6 && node.ip6.ip)))
```

It requires at least 1x location, and (at least 1x ip4 or ip6)

**Comment by julsemaan** [comment]
We don't need to have a node IP for reevaluate access and restart switchport so that is likely the issue.

Only the location is necessary

**Comment by satkunas** [comment]
Changed in https://github.com/inverse-inc/packetfence/commit/d8da32b8a198f62358f82118d57f13e839443663
