### ISSUE TITLE
New admin doesn't differentiate builtin dynamic reports from user defined ones

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4417]
The old admin separates the builtin dynamic reports (type=builtin) from the ones defined by the user since PF ships with dynamic reports defined by us

Old:
![image](https://user-images.githubusercontent.com/3857942/57452419-b78dd380-7231-11e9-87d2-f68fb0f809e9.png)

New:
![image](https://user-images.githubusercontent.com/3857942/57452435-c5435900-7231-11e9-9888-4590fb31128f.png)

**Comment by satkunas** [comment]
Split in https://github.com/inverse-inc/packetfence/commit/d64b5f0bc8f92ad64db25e697bde1933a61c3519

**Comment by satkunas** [comment]
More fixes in https://github.com/inverse-inc/packetfence/commit/d1ff4af71d40ef45ff2215295fbcf46c88308c14

**Comment by nqb** [comment]
Right now, in the new web admin "Custom reports" (defined by user) are called "Dynamic reports". From my point of view, we should keep "Custom reports". On top of that, documentation still refer to "Custom reports".
![Screenshot from 2019-08-31 08-43-51](https://user-images.githubusercontent.com/10830260/64060350-79933180-cbcb-11e9-9fca-00ff1da47a35.png)
