### ISSUE TITLE
Virtual 'pf' service is listed in the services list

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4419]
The virtual 'pf' service that regroups all the PacketFence managed services is displayed in the services page (/admin/alt#/status/services)

Since that services is not manageable, it should simply be hidden from that list

**Comment by satkunas** [comment]
@julsemaan Can it be removed from `GET /services` instead?

**Comment by julsemaan** [comment]
There is a use case for having it available through the API to execute an action on all the services so I'd say it would be better to adjust the frontend

**Comment by satkunas** [comment]
> There is a use case for having it available through the API to execute an action on all the services so I'd say it would be better to adjust the frontend

@julsemaan such an endpoint would never be able to return a response when it's stopped or restarted. What case could make use of this?

**Comment by julsemaan** [comment]
You could use it to restart pf which would restart all the managed services (that's at least the theory)

**Comment by satkunas** [comment]
This won't work. `httpd.admin`, `pfperl-api` and `api-frontend` will restart with this, which will cancel the request and never return a response, thus leaving the app in a dead state, and even worse - making it impossible to remedy via the dead admin. A similar dependency issue as restarting all interfaces while connected remotely. This was the idea behind "Protected" services, making them untouchable. I don't wish to allow any avenue for a user to shoot themselves in the foot.

I argue again, that the `pf` service should not be listed, nor even manageable via the API. Even if we find a way to fork the service command so the API response isn't interrupted, there's nothing that can be done after it has been stopped and the 3 services listed above are no longer listening to requests. Any valid use-case to manage `pf` should require the CLI.

**Comment by julsemaan** [comment]
In this case, let me remove that service from the API

CLI FTW!
