### ISSUE TITLE
Multiple entries for the same mac address in 'node' tab

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#442]
A same node (MAC address) will be displayed more than once in the 'node' tab if more than one iplog entry is opened for that same MAC.

With the new way iplog works, it may occurs and it is a 'normal' behavior to have 'more than one iplog entry for a same MAC'.

The only thing that is different in the listing is the 'current IP' which refers to each opened iplog entries.

Expected behavior:
- We shouldn't have more than one entry in the 'Node' tab for a MAC, even if there's more than one iplog entry opened.

**Comment by dwlfrth** [comment]
The actual SQL query looks like this:

```
SELECT 
    `node`.`mac`, `node`.`pid`, `node`.`voip`, `node`.`bypass_vlan`, `node`.`status`, `node`.`category_id`, `node`.`bypass_role_id`, `node`.`user_agent`, `node`.`computername`, `node`.`last_arp`, `node`.`last_dhcp`, `node`.`notes`, IF(lastskip = '0000-00-00 00:00:00', '', lastskip) as lastskip, IF(detect_date = '0000-00-00 00:00:00', '', detect_date) as detect_date, IF(regdate = '0000-00-00 00:00:00', '', regdate) as regdate, IF(unregdate = '0000-00-00 00:00:00', '', unregdate) as unregdate, IFNULL(node_category.name, '') as category, IFNULL(node_category_bypass_role.name, '') as bypass_role, IFNULL(device_class, ' ') as dhcp_fingerprint, `iplog`.`ip` as last_ip 

FROM 
    `node` 

LEFT JOIN 
    `node_category` on `node_category`.`category_id` = `node`.`category_id` 

LEFT JOIN 
    `node_category` as node_category_bypass_role on `node_category_bypass_role`.`category_id` = `node`.`bypass_role_id` 

LEFT JOIN 
    `iplog` on `iplog`.`mac` = `node`.`mac` AND ( `iplog`.`end_time` = '0000-00-00 00:00:00' OR `iplog`.`end_time` > NOW() ) 

ORDER BY `node`.`mac` ASC LIMIT 0 , 25;
```

The way to resolve the issue is to do an 'ORDER BY ... LIMIT 1' on the last LEFT JOIN (iplog) but that requires a subselect which may increase the query time.... The query would look like this...

```
SELECT 
    `node`.`mac`, `node`.`pid`, `node`.`voip`, `node`.`bypass_vlan`, `node`.`status`, `node`.`category_id`, `node`.`bypass_role_id`, `node`.`user_agent`, `node`.`computername`, `node`.`last_arp`, `node`.`last_dhcp`, `node`.`notes`, IF(lastskip = '0000-00-00 00:00:00', '', lastskip) as lastskip, IF(detect_date = '0000-00-00 00:00:00', '', detect_date) as detect_date, IF(regdate = '0000-00-00 00:00:00', '', regdate) as regdate, IF(unregdate = '0000-00-00 00:00:00', '', unregdate) as unregdate, IFNULL(node_category.name, '') as category, IFNULL(node_category_bypass_role.name, '') as bypass_role, IFNULL(device_class, ' ') as dhcp_fingerprint, `iplog`.`ip` as last_ip 

FROM 
    `node` 

LEFT JOIN 
    `node_category` on `node_category`.`category_id` = `node`.`category_id` 

LEFT JOIN 
    `node_category` as node_category_bypass_role on `node_category_bypass_role`.`category_id` = `node`.`bypass_role_id` 

LEFT JOIN
    `iplog` on `iplog`.`ip` = 
        ( SELECT `ip` FROM `iplog` WHERE `mac` = `node`.`mac` 
        AND ( `iplog`.`end_time` = '0000-00-00 00:00:00' OR `iplog`.`end_time` > NOW() )
        ORDER BY `start_time` DESC LIMIT 1 )

ORDER BY `node`.`mac` ASC LIMIT 0 , 25;
```

**Comment by dwlfrth** [comment]
Change should be made in 'html/pfappserver/lib/pfappserver/Model/Search/Node.pm'

Need to adapt the 'make_builder' accordingly

**Comment by jrouzierinverse** [comment]
This query does not work.

+-------------------+-------+------+-------------+--------+-------------+----------------+------------+--------------+---------------------+---------------------+-------+----------+---------------------+---------------------+-----------+----------+-------------+------------------+-------------+
| mac               | pid   | voip | bypass_vlan | status | category_id | bypass_role_id | user_agent | computername | last_arp            | last_dhcp           | notes | lastskip | detect_date         | regdate             | unregdate | category | bypass_role | dhcp_fingerprint | last_ip     |
+-------------------+-------+------+-------------+--------+-------------+----------------+------------+--------------+---------------------+---------------------+-------+----------+---------------------+---------------------+-----------+----------+-------------+------------------+-------------+
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
| 00:00:3c:b1:5c:b8 | admin |      | NULL        | reg    |           1 |           NULL |            |              | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | NULL  |          | 2014-03-28 23:54:46 | 2014-11-20 13:03:52 |           | default  |             |                  | 192.168.0.2 |
+-------------------+-------+------+-------------+--------+-------------+----------------+------------+--------------+---------------------+---------------------+-------+----------+---------------------+---------------------+-----------+----------+-------------+------------------+-------------+

**Comment by dwlfrth** [comment]
It does work. Need to make sure to use the latest schema with a UNIQUE PRIMARY KEY on the 'ip' column
