### ISSUE TITLE
API POST dynamic_report/:id/search

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4424]
A workaround (see "sort": [null]) is needed to dynamically set the fields when they are not exposed with `GET /dynamic_report/:id`, therefore `sort` and `fields` are not initially known. 

`POST /dynamic_report/:id/search`  currently generating a 500 with the following payload.

```json
{"cursor":0,"limit":25,"fields":[],"sort":[null],"start_date":null,"end_date":null,"query":{"op":"and","values":[{"op":"or","values":[]}]}}
```

**Comment by julsemaan** [comment]
I've tried it and it works fine on the built-in ip4log history report:
```
sbin/pfperl-api get -M POST -c '{"cursor":0,"limit":25,"fields":[],"sort":[null],"start_date":null,"end_date":null,"query":{"op":"and","values":[{"op":"or","values":[]}]}}' /api/v1/dynamic_report/ip4log-history/search
```

Let me know more precisely in which context it doesn't work

**Comment by satkunas** [comment]
Based on:

```conf
[survey1]
description=My first survey report
base_table=survey_survey1
columns=firstname as "Firstname", lastname as "Lastname", prefered_sandwich as "Prefered Sandwich", gender as "Gender"
```

```
sbin/pfperl-api get -M POST -c '{"cursor":0,"limit":25,"fields":[],"sort":[null],"start_date":null,"end_date":null,"query":{"op":"and","values":[{"op":"or","values":[]}]}}' /api/v1/dynamic_report/survey1/search
```

```
{"errors":[],"message":"Failed executing search on report. Check server-side logs for details.","status":500}
```

```
May  9 13:19:12 packetfence packetfence: ERROR pfperl-api(20834): Database query failed with non retryable error: Table 'pf.survey_survey1' doesn't exist (errno: 1146) [SELECT firstname as "Firstname", lastname as "Lastname", prefered_sandwich as "Prefered Sandwich", gender as "Gender" FROM survey_survey1 LIMIT ? OFFSET ?]{25, 0} (pf::dal::db_execute)
```

**Comment by julsemaan** [comment]
you most probably don't have the table survey_survey1 which is specific to my environment

I suggest testing with the builtin reports

**Comment by satkunas** [comment]
All builtin reports are working. I'm attempting to get the non-builtin ones working ATM.

**Comment by julsemaan** [comment]
They might not work if you don't have the necessary data, some of those reports are specific to my own environment and aren't distributed with PF

**Comment by satkunas** [comment]
Then can we either improve the error response, or add some backend checks to prevent these silent errors from occurring?

**Comment by julsemaan** [comment]
i'm not passing down the exact SQL error down so we'll have to stick with that generic error and have the user look at the log for the moment like the message describes

**Comment by satkunas** [comment]
Please fwd me the data needed for the [radius_accounting] section. I'm attempting to post-calc columns from the columns=* directive.

I'm currently getting an empty response.
