### ISSUE TITLE
v9-gui: When creating local account, the registration window start date doesn't set to today

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4428]
The field is empty.

**Comment by satkunas** [comment]
![Selection_020](https://user-images.githubusercontent.com/3904468/57479325-250a2600-726b-11e9-93c5-a7f28d79b644.png)

This was added to devel yesterday.

**Comment by lzammit** [comment]
Fixed on the latest build

[root@cluster1 pf]# rpm -qa packetfence
packetfence-8.3.9-0.201905091301.el7.noarch
