### ISSUE TITLE
API POST fingerbank/local/combinations

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4429]
In some cases form data includes meta information received from GET. This is carried forward when cloning. The following error was received when creating a new item based on data received from an existing item (a clone).

```json
{"message":"DBIx::Class::Row::store_column(): No such column 'not_deletable' on fingerbank::Base::Schema::Combination at constructor fingerbank::Base::Schema::Combination::new (defined at \/usr\/local\/pf\/lib\/fingerbank\/Base\/Schema\/Combination.pm line 40) line 27\n","status":500}
```

Fingerbank endpoints should silently ignore any unknown fields.

**Comment by julsemaan** [comment]
I'm not sure I'm the best one to do this since that may be hidden in @jrouzierinverse's magic when he wrote those API endpoints.

I can try to look at it though and I'll see what I can do

**Comment by jrouzierinverse** [comment]
Two issues
* You are passing in not_deletable which is virtual field.
* We are not cleaning our data before passing it in to fingerbank API.

**Comment by julsemaan** [comment]
@jrouzierinverse sent me a PM saying he'll be taking care of it, reassigning
