### ISSUE TITLE
v9-gui: DHCP option 82 error when clicking on a Mac address

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4430]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/5261214/57480054-c5147f00-726c-11e9-94c8-10d47735ff90.png">

**Comment by satkunas** [comment]
Related to admin roles. Re-assigning.

**Comment by cgx** [comment]
@lzammit: which admin role was assigned to the current user? Node Manager?

@julsemaan: shall we update the `adminroles.conf` defaults?

**Comment by lzammit** [comment]
@cgx admin user with ALL access.

Thanks.

**Comment by cgx** [comment]
That's a backend issue. @julsemaan ?

**Comment by julsemaan** [comment]
There is no adminroles.conf defaults unfortunately, I've updated the example file

This is probably just an issue where the package was updated but packetfence-config + all PF services weren't restarted so the new admin roles constants weren't loaded so they aren't applied to the ALL role

@lzammit: Try restarting everything + configreload

**Comment by lzammit** [comment]
Seems fixed now.
