### ISSUE TITLE
CentOS 7: How do I install perl dependencies ？

### ISSUE THREAD

**Issue by webliuxiang** [inverse-inc/packetfence#4432]
I want to use the 8.3.0 version of packetFence code to compile and run, but I haven't found the specific operation process, and I don't know how to install the dependent project, how to run the project, and how to package the project.

**Comment by julsemaan** [comment]
This is not the place where you'll get answers. Use the mailing list for such questions.

BTW, the install process is all documented in the installation guide on packetfence.org
