### ISSUE TITLE
Old GUI: some sources didn't have any rules

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4436]
Nightly builds.

If I create a new Htpasswd source through API or new webadmin, source didn't have `Authentication rules` or `Administration rules`. Same for POTD, sms, email, sponsor, null.

@jrouzierinverse, I suppose this is caused by c9c5ede

**Comment by jrouzierinverse** [comment]
Can you provide me with API content you used?

**Comment by jrouzierinverse** [comment]
I think the problem is here 8a9916881dcfb6964a40789445f10e69e5f01b65.
@satkunas for the sources how do you handle the cases where some have rules while others don't?

**Comment by jrouzierinverse** [comment]
As mentioned before Billing/Blackhole/SAML/HTTP sources do not have rules.
All other source needs rules.

**Comment by nqb** [comment]
@jrouzierinverse,

Sorry if it was unclear: issue is in **old GUI**.

What I did:
```
touch /usr/local/pf/conf/admin.conf
/usr/local/pf/sbin/pfperl-api get -M POST /api/v1/config/sources -c '{"id": "htpasswd_source", "description": "htpasswd source", "type":"Htpasswd", "path":"/usr/local/pf/conf/admin.conf"}'
```
Source is created but when I go to **old GUI**, this source doesn't display "Authentication" or "Administration" rules section. Same behavior for new sources created like "Null".

Same behavior if I create source with `administration_rules` or `authentication_rules` in API content.

Issue seems to be only on Debian.

**Comment by nqb** [comment]
@fdurand: are you able to reproduce under Debian (latest nightly builds) ?

**Comment by fdurand** [comment]
The issue is when there is no authentication or administration rules defined in the source then the form doesn't appear.
