### ISSUE TITLE
v9-gui: editing a current network interface

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4441]
Since 8e97e7d, it's not possible to edit a current network interface from Network configuration > Interfaces in the new GUI if interface has a `ifindex` which is not equal to its `iflink` (see [this thread on stackoverflow](https://unix.stackexchange.com/questions/444892/what-does-if1if2-mean-in-interface-name-in-output-of-ip-address-command-on#444911)).

My setup:
```console
# ip link
[..]
105: eth0@if106: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb state UP mode DEFAULT group default
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
# cat /sys/class/net/eth0/ifindex
105
# cat /sys/class/net/eth0/iflink
106
```
If I try to edit `eth0`, from new GUI, I got this display:
![Screenshot from 2019-05-10 16-07-24](https://user-images.githubusercontent.com/10830260/57533304-ba75ea80-733d-11e9-9136-20eb33ab5031.png)

New GUI is trying to create a new VLAN interface on eth0.

I didn't get such issue from old GUI.

**Comment by nqb** [comment]
Related to #4264

**Comment by nqb** [comment]
I got this behavior in a Docker container running Debian or CentOS.

**Comment by julsemaan** [comment]
I will need to have details on how to create such an interface

Also, its not because it used to work that it should have worked

If this is a twisted use case we might postpone the fix after 9.0

**Comment by nqb** [comment]
I will see if this issue is still presents.

**Comment by julsemaan** [comment]
@nqb, what are we doing with this, move to 10.1 ?

**Comment by extrafu** [comment]
No feedback in almost a year, let's reopen if we see it and we can reproduce it in a constant manner.
