### ISSUE TITLE
DB password in configurator is not apply 

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#445]
Install devel version on centos6, try to use the configurator and when you reach 'Change the admin password' it won't work.

The database password of the user pf is set to his default 'packet', change pf password from configurator do not apply.

**Comment by julsemaan** [comment]
Most probably dued to cluster overlaying recently merged in devel. 

Should be fixed in 1f3a1488a32bfa353f4eac2b2dd42e1ec138af12

Test tomorrow with the newest builds

**Comment by whitx** [comment]
Fixed with 1f3a148
