### ISSUE TITLE
Improve search criteria on config/search

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4454]
Configuration search (POST config/.../search) will need to be extended to support complex operators so we can re-implement the WRIX Location search tools.

From: https://github.com/inverse-inc/packetfence/issues/4153

**Comment by jrouzierinverse** [comment]
This has been done @satkunas was anything else needed for this?

**Comment by jrouzierinverse** [comment]
@satkunas was anything else needed for this?

**Comment by jrouzierinverse** [comment]
Can this be closed?

**Comment by satkunas** [comment]
Improved search deployed in various recent UI improvements. Closing
