### ISSUE TITLE
Connection profile "default" can be reordered

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4455]
The default connection profile can be reordered in the list although it should always be the first like in the previous admin

**Comment by satkunas** [comment]
@jrouzierinverse please add a `not_sortable` boolean to the connection profiles payload.

**Comment by julsemaan** [comment]
Just to make it clear, the profiles are sortable by ID but the default section should not be sortable.

Not sure if that can be handled in the OPTIONS or if we should make it a special case in the frontend

**Comment by jrouzierinverse** [comment]
not_sortable boolean is done
