### ISSUE TITLE
Error when editing a connection profile file

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4456]
Edit error.html on the default connection profile and you get this little gift:
```
{"message":"Can't locate object method \"file\" via package \"Mojolicious::Renderer::Helpers::057f0bea32d76c0c463e49f25626f293\" at \/usr\/local\/pf\/lib\/pf\/UnifiedApi\/Controller\/Config\/ConnectionProfiles.pm line 139.\n","status":500}
```

**Comment by fdurand** [comment]
Update perl Mojoliciuos from the devel repo.

**Comment by julsemaan** [comment]
Is the dependency added to the packetfence.spec ?

@lzammit got this in a machine that uses packaging

**Comment by fdurand** [comment]
not the version

**Comment by extrafu** [comment]
Fixed?

**Comment by julsemaan** [comment]
not in my envrionment, I'll try it with a packaged version, not from sources to see if it makes a difference

**Comment by julsemaan** [comment]
works on a packaged version, no need to invest time in my machine running the sources
