### ISSUE TITLE
Can't install packetfence - debian 8.11.0

### ISSUE THREAD

**Issue by tech62** [inverse-inc/packetfence#4457]
I've encountered the message "Dependency not satisfied", any idea ?
 packetfence : Dépend: libmojolicious-perl (>= 7.74) mais ne sera pas installé
               Dépend: libmojox-log-log4perl-perl mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

**Comment by fdurand** [comment]
Wrong libmojolicious-perl version in the repo.
Fixed
