### ISSUE TITLE
Packetfence 8.3 not showing Device Manufacturer in Nodes

### ISSUE THREAD

**Issue by auxmatto** [inverse-inc/packetfence#4458]
Hello,

I recently setup Packetfence 8.3.0 with the ZEN deployment. I setup the Fingerbank API with github, and shows successfully connected. I have a switch connected to the Packetfence, and it is working correctly, including accounting. However, in the Node view, I see my nodes listed, with mac address, switch ip, switchport, but I cannot seem to figure out how to show Device Manufacturer. The column is there, and showing, but all the entries are blank. Any advice you can offer is much appreciated. 
Thanks,
Matt

**Comment by julsemaan** [comment]
That is a question that should be asked on the PacketFence mailing list

This bug tracker is reserved for confirmed bugs and development issues
