### ISSUE TITLE
enabling/disabling pfmon task doesn't provide immediate feedback

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4467]
If you enable/disable a task in the pfmon index (#/configuration/maintenance_tasks), there is no feedback that the task is enabling/disabling while the API is performed which leads you to multi-click the toggle and generate multiple API calls

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/9303b15106ab9a47cb426813fc8cbb80135a6473
