### ISSUE TITLE
Add suffix or prefix to cloned configuration

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4468]
When cloning a piece of configuration (lets say a source), the name in the clone is the same as the source you're cloning which results in a warning right when you get onto the page

Let's say the initial source name is "@lzammit's sexy LDAP server", cloning it could make the ID of the new source "@lzammit's sexy LDAP server (copy)"

Not sure if its decided in the frontend or backend so assigning @satkunas and @jrouzierinverse

**Comment by jrouzierinverse** [comment]
It would be just simpler to blank out the old ID as this is the current behavior in the old admin.

**Comment by jrouzierinverse** [comment]
This is frontend since we have not knowledge of how cloning is implemented in the backend.

**Comment by satkunas** [comment]
@julsemaan keep in mind that this will lead us to the following new issue(s): 

![Screenshot from 2019-05-21 09-49-52](https://user-images.githubusercontent.com/3904468/58102132-ce77e280-7bae-11e9-9b83-ffa82fc2ce9a.png)

**Comment by julsemaan** [comment]
I guess its fine since I think its the only place where there is a length limitation

Unless we don't apply the 'copy' logic to domains

**Comment by satkunas** [comment]
@julsemaan your call. It's easy to cherry-pick this out of domains.
