### ISSUE TITLE
V9-Gui: Network: named configuration parameter is unset

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4470]
When i create a remote network then the named and domain-name parameters are not set in the configuration file:

```
Checking configuration sanity...
Use of uninitialized value $net{"named"} in pattern match (m//) at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 458.
WARNING - networks.conf: Incomplete DHCP information for network 172.21.138.0
```

**Comment by jrouzierinverse** [comment]
Either this not sent from the frontend or the backend is not saving it.
@julsemaan since you are more familiar with this code can you look it?

**Comment by julsemaan** [comment]
The frontend seems to be sending the field named as 'dns' instead of 'named' so that's very likely to be a frontend issue

Assigning @satkunas

**Comment by satkunas** [comment]
@julsemaan, can either you or @fdurand give me steps (for the old admin) so I can see where this field is missing?

In the screenshot below, the field "DNS Server" is keyed as "dns".  There appears to be no field "named". 

![Selection_023](https://user-images.githubusercontent.com/3904468/57655843-e34be900-75a4-11e9-9edc-6a0bd6eb59c6.png)

**Comment by fdurand** [comment]
It's implicit in the old admin when you create a remote network:
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/ConfigStore/Network.pm#L147
True for domain-name and named configuration parameter.
Btw i don't know how the new remote network is added in the new admin through the api.

**Comment by satkunas** [comment]
If that's the case then it should also be implicit in the new admin as well. If agreed please re-assign to @jrouzierinverse  for back-end changes.

**Comment by julsemaan** [comment]
@satkunas, you're right, I'll look into that
