### ISSUE TITLE
Need to be able to test SMTP settings from the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4471]
The API endpoint for testing SMTP settings was done (#4043) but was never implemented in the admin interface so we can't test the SMTP settings in the admin by sending an email like before

That might be a 9.0.1 unless its a quickie so I've put it in the 9.0 pipe for now

**Comment by satkunas** [comment]
Waiting on @jrouzierinverse to fix the following error on `/test_smtp` before commiting this addition.

```json
{"message":"Modification of a read-only value attempted at \/usr\/share\/perl5\/vendor_perl\/HTML\/FormHandler.pm line 605.\n","status":500}
```

**Comment by satkunas** [comment]
Test added in https://github.com/inverse-inc/packetfence/commit/d4e889917eb671ca521839f3a6df9433a46cb250

Unable to generate a successful test locally. @julsemaan please test.

```json
{"errors":[],"message":"SMTP auth() command not supported on 10.0.0.6\n","status":400}
```

**Comment by jrouzierinverse** [comment]
That is a valid error

**Comment by nqb** [comment]
I work on my side for CentOS and Debian.

**Comment by extrafu** [comment]
"I work" or "It works" ?

**Comment by nqb** [comment]
Sorry, it works.

**Comment by extrafu** [comment]
If it works, let's close it.
