### ISSUE TITLE
Creating a domain doesn't join it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4474]
When you create a new domain, it doesn't initiate the join process and you have to manually go back to the domain index and initiate the join process

We should initiate the join process during the creation (but not during the update) of a domain

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/6429323000c5f59b8c21b50e5257af96e5f4d96b

Auto Join is trigger on both Create and on Update. The [CTRL] changes the behaviour of the [Save] button to allow the user to Save & Join (default), or just Save (w/ CTRL key pressed)
