### ISSUE TITLE
API OPTIONS config/provisioning eap_type missing "No EAP" option

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4480]
`/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/provisioning/ios | jq '.meta.eap_type.allowed'`

```json
[
  {
    "text": "PEAP",
    "value": "25"
  },
  {
    "text": "EAP-TLS",
    "value": "13"
  }
]
```

**Comment by satkunas** [comment]
![Selection_021](https://user-images.githubusercontent.com/3904468/57651186-a3800400-759a-11e9-9c84-b9ea9899ef77.png)

**Comment by jrouzierinverse** [comment]
No EAP is just an empty field.
As per your request all fields that are empty are removed from the allowed values

**Comment by jrouzierinverse** [comment]
@satkunas I am closing this as this is not an issue on my side.
