### ISSUE TITLE
SSO with two devices under the same owner

### ISSUE THREAD

**Issue by slaggi** [inverse-inc/packetfence#4482]
I got some weird behaviour of SSO if there are 2 or more devices active under the same owner.
The first device comes online and the SSO (Fortigate SSO) gets triggered correctly. 

In the moment a second device comes up of the same owner, both SSO’s get cancelled out via 
Radius accounting – stop messages (Fortigate SSO).

Now if I look in the packetfence.log, it gets even more weird as at some stage logging for these nodes
get done under totally unrelated mac-addresses …

This is on PF 8.3.0 installed from the VM image. Tried to reinstall and configure from scratch and got to the same problem. Hope am not doing something wrong here ...

I tried this with local and AD users. The only user where it works 100% is with Default ...

The logs: 

8c:9f:3b:eb:8e:bb is already active before the log starts and is owned by ‘lkleynhans’
34-8a-7b-e0-78-98 is the second node which is coming online … 

The other two mac-addresses are registered but totally unrelated, they were active around the time:

> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] handling radius autz request: from switch_ip => (172.16.119.21), connection_type => Ethernet-NoEAP,switch_mac => (Unknown), mac => [34:8a:7b:e0:78:98], port => external, username => "34-8a-7b-e0-78-98" (pf::radius::authorize)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] Instantiate profile NmillsDefault (pf::Connection::ProfileFactory::_from_profile)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] Connection type is Ethernet-NoEAP. Getting role from node_info (pf::role::getRegisteredRole)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] Username was defined "34-8a-7b-e0-78-98" - returning role 'guest_management' (pf::role::getRegisteredRole)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] PID: "lkleynhans", Status: reg Returned VLAN: (undefined), Role: guest_management (pf::role::fetchRoleForNode)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:34:8a:7b:e0:78:98] Returning ACCEPT (pf::Switch::Fortinet::FortiGate::returnRadiusAccessAccept)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:3c:57:6c:12:6f:be] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:3c:57:6c:12:6f:be] Unable to extract MAC from Called-Station-Id: 172.16.119.21 (pf::radius::extractApMacFromRadiusRequest)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) WARN: [mac:3c:57:6c:12:6f:be] Firewall SSO Notify (pf::api::firewallsso_accounting)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:3c:57:6c:12:6f:be] Sending a firewall SSO 'Update' request for MAC '34:8a:7b:e0:78:98' and IP '172.16.119.8' (pf::firewallsso::do_sso)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:3c:57:6c:12:6f:be] Request to /api/v1/firewall_sso/update is unauthorized, will perform a login (pf::api::unifiedapiclient::call)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:3c:57:6c:12:6f:be] Unable to extract MAC from Called-Station-Id: 172.16.119.21 (pf::radius::extractApMacFromRadiusRequest)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Instantiate profile NmillsDefault (pf::Connection::ProfileFactory::_from_profile)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Instantiate profile NmillsDefault (pf::Connection::ProfileFactory::_from_profile)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) WARN: [mac:70:1c:e7:79:5c:4d] Firewall SSO Notify (pf::api::firewallsso_accounting)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Sending a firewall SSO 'Stop' request for MAC '34:8a:7b:e0:78:98' and IP '172.16.119.8' (pf::firewallsso::do_sso)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Request to /api/v1/firewall_sso/stop is unauthorized, will perform a login (pf::api::unifiedapiclient::call)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) WARN: [mac:70:1c:e7:79:5c:4d] Firewall SSO Notify (pf::api::firewallsso_accounting)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Unable to extract MAC from Called-Station-Id: 172.16.119.21 (pf::radius::extractApMacFromRadiusRequest)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Sending a firewall SSO 'Stop' request for MAC '8c:9f:3b:eb:8e:bb' and IP '172.16.119.13' (pf::firewallsso::do_sso)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Request to /api/v1/firewall_sso/stop is unauthorized, will perform a login (pf::api::unifiedapiclient::call)
> May 12 13:42:08 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Unable to extract MAC from Called-Station-Id: 172.16.119.21 (pf::radius::extractApMacFromRadiusRequest)

Just for interest sake, the login of the actual 70:1c:xx node from a different devie:

> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] handling radius autz request: from switch_ip => (172.16.0.2), connection_type => Ethernet-NoEAP,switch_mac => (04:09:73:f7:b9:cf), mac => [70:1c:e7:79:5c:4d], port => 49, username => "70:1c:e7:79:5c:4d" (pf::radius::authorize)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) WARN: [mac:70:1c:e7:79:5c:4d] VoIP is not supported on this network module (pf::Switch::isVoIPEnabled)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Connection type is Ethernet-NoEAP. Getting role from node_info (pf::role::getRegisteredRole)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Username was defined "70:1c:e7:79:5c:4d" - returning role 'guest_restricted' (pf::role::getRegisteredRole)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] PID: "default", Status: reg Returned VLAN: (undefined), Role: guest_restricted (pf::role::fetchRoleForNode)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) WARN: [mac:70:1c:e7:79:5c:4d] No parameter guest_restrictedVlan found in conf/switches.conf for the switch 172.16.0.2 (pf::Switch::getVlanByName)
> May 12 13:42:16 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2855) INFO: [mac:70:1c:e7:79:5c:4d] Match rule 1:macauth (pf::access_filter::radius::test)

**Comment by julsemaan** [comment]
we'll look into this once the 9.0 release rush passes.

I'll tag this as a +1 patch so it hits maintenance if its a bug

**Comment by julsemaan** [comment]
Do you have SSO on accounting enabled ?

From what I can tell it is

So we'd need to have a packet capture of the RADIUS packets (port 1813) while you're trying it out along with the packetfence.log so this can be troubleshooted

**Comment by slaggi** [comment]
I did a little more testing, it only happens when the nodes have different roles set. With the same role it works fine ... 

Attached is a Wireshark trace with both, the actual Radius access requests as much as the SSO Accounting requests from PF ... and the matching logs from packetfence.log

To the trace:
192.168.1.220 = PF
10.10.1.10 = authenticating Firewall
172.16.9.15 = different firewall receiving the SSO Accounting request

0-30 seconds: that is a working one with both nodes same role
>30 sec: that is the non-working part with nodes on different roles, accounting stop is sent for both nodes

Sorry for the duplicates in the trace, was watching on several interfaces at the same time ... 

[putty_pfsso_log.txt](https://github.com/inverse-inc/packetfence/files/3221069/putty_pfsso_log.txt)
[pfsso.zip](https://github.com/inverse-inc/packetfence/files/3221070/pfsso.zip)

Only customization here:
I want PF to always return the 'Fortinet-Group-Name' attribute in any Radius Access Request, hence a Radius Filter:

[macauth]
filter = connection_type
operator = is
value = Ethernet-NoEAP

[1:macauth]
scope = returnRadiusAccessAccept
merge_answer = yes
answer1 = Fortinet-Group-Name => $user_role

**Comment by lyubomirtraykov** [comment]
You can close this. It is Fortigate RSSO configoration issue. You have to set `sso-attribute-value-override disable` in RSSO Agent settings. You can read more [here.](https://docs.pulsesecure.net/WebHelp/PPS/9.1R5/AG/pps_admin_guide/PPS_L3Enforcement/Enforcement_FortiGate/Configuring_FortiGate_Firewall.htm)
