### ISSUE TITLE
v9-gui: email activation timeout incorrectly set

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4483]
If you click on **current** value in dropdown list of "Email activation timeout" setting on a source, drop-down list disappear and `email_activation_timeout` is unset in `authentication.conf`.

### Steps to reproduce

Environment: Chromium | 74.0.3729.131 (Official Build) snap (64-bit)

1. Create a new Email source
2. Click on "minutes" choice in drop-down list

**Comment by satkunas** [comment]
Clicking on the email activation timeout units to remove the current option does make the chosen element narrower, but it does not "disappear" . The dropdown arrow is still visible and selectable.

![Selection_026](https://user-images.githubusercontent.com/3904468/57703853-d673d780-762e-11e9-9b2b-1d9a93cc4cfb.png)

>  email_activation_timeout is unset in authentication.conf

It only commits the changes after you click "Save". Changes are not automatically committed. 

Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by satkunas** [comment]
@jrouzierinverse Meta for `units` should be required when the parent is required. This will disallow the chosen from being emptied/cleared.

`/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/sources?type=Email | jq '.meta.email_activation_timeout.properties.unit.required'`

I'll manually override this attribute until the backend is modified.

**Comment by satkunas** [comment]
Issue re-worked in https://github.com/inverse-inc/packetfence/issues/4492
