### ISSUE TITLE
v9-gui: security events display on a node

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4484]
After a security event has been opened for a node (Lost or stolen), I got following display:

![Screenshot from 2019-05-14 10-42-16](https://user-images.githubusercontent.com/10830260/57684018-38cfd680-7635-11e9-8293-e05c3fb2f0da.png)

Column Security Event will never display "Lost or stolen", " Release Date" should be empty (like in old GUI). If I trigger a new security event, this one is correctly displayed.

"Lost or stolen" security event has been opened by owner of node (local account created from an email source) from `/status` page.

What I got from API after new security event has been triggered:
```json
{"items":[{"id":"2","mac":"00:11:22:33:44:55","notes":"","release_date":"2019-05-14 08:45:58","security_event_id":"1100009","start_date":"2019-05-14 08:45:57","status":"closed","tenant_id":"1","ticket_ref":""},{"id":"1","mac":"00:11:22:33:44:55","notes":"","release_date":"0000-00-00 00:00:00","security_event_id":"1300005","start_date":"2019-05-14 08:28:06","status":"open","tenant_id":"1","ticket_ref":""}],"prevCursor":0,"status":200}
```
130005 = id of "Lost or Stolen" security event.

I got same behaviour if I try to display security event from the Users menu.

**Comment by satkunas** [comment]
@nqb Not able to reproduce. 

Patience is required for the GET config/security_events to complete. Check the debugger and wait for this

![Selection_025](https://user-images.githubusercontent.com/3904468/57703355-e212ce80-762d-11e9-8a2d-2105127745ce.png)

to become this

![Selection_024](https://user-images.githubusercontent.com/3904468/57703366-e808af80-762d-11e9-8193-6af13ad8e779.png)

After the endpoint returns, check if the security event descriptions are populated. If not, include the contents of the console errors here.

**Comment by nqb** [comment]
@satkunas: you're right. It works.
