### ISSUE TITLE
Embedded doc not available

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4488]
On CentOS nightly builds (old and new GUI), `doc` is missing from `$PF/html/pfappserver/root/static/` causing embedded doc to be unavailable.

**Comment by nqb** [comment]
I don't understand why. 

`doc` dir is part of latest builds (in RPM) with HTML files needed.

**Comment by extrafu** [comment]
@fdurand Can you please take care of this one?

**Comment by fdurand** [comment]
Just installed a fresh centos 7 with devel and the doc is there.
But https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/views/Help/index.vue#L43 it miss the prefix PacketFence_

**Comment by nqb** [comment]
@fdurand: thanks. I just find why: in CentOS Docker images, yum is configured to no install `%doc` files from RPM (setting `tsflags=nodocs` in `yum.conf`).

Sorry !
