### ISSUE TITLE
Security Events: cannot remove ignored role after adding one

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4489]
If you add one (just a single one) ignored role to a new security event, you can't clear it anymore to have no ignored role

**Comment by cgx** [comment]
@julsemaan Works for me. I click on "New Security Event", add a role to the ignored roles, and I can remove it from the pulldown or by clicking on the "x" of the chip.

**Comment by julsemaan** [comment]
yes it works now after I visited the following link:
https://semaan.needed.to.recompile.com/he-should-double-check-that-before-opening-an-issue.html
