### ISSUE TITLE
Security Events: MAC vendor trigger doesn't have type-ahead

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4490]
The MAC vendor field of the device profiling trigger sub-section doesn't have auto complete via a search lookup.

Inspected the console and there was no call made to '/search' like with the other attributes

**Comment by cgx** [comment]
Must fix the backend first:

```bash
$ /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/security_events | jq '.meta.triggers.item.properties.mac_vendor'
{
  "default": null,
  "placeholder": null,
  "required": false,
  "type": "string"
}
```

**Comment by cgx** [comment]
@julsemaan can you validate that this is the lookup we want?

```bash
$ /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/security_events | jq '.meta.triggers.item.properties.mac_vendor.allowed_lookup'
{
  "field_name": "mac",
  "search_path": "/api/v1/fingerbank/all/mac_vendors/search",
  "value_name": "id"
}
```

**Comment by julsemaan** [comment]
We should be able to search by name or MAC prefix if that is possible

Then the display could be "$NAME ($MAC)', ex: "Dell Inc. (001122)"
