### ISSUE TITLE
Shouldn't be able to toggle 'defaults' of security events

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4499]
We shouldn't be able to toggle the 'defaults' section of the security events

**Comment by satkunas** [comment]
@julsemaan currently in the old admin the status can be enabled/disabled in the item. It saves fine and when reloaded displays the last saved state.

![Selection_028](https://user-images.githubusercontent.com/3904468/57729084-4ef48b80-7663-11e9-9515-8f7c51d74fd0.png)

Should this be inhibited in the view as well? If so, should it be enabled or disabled by default?

**Comment by satkunas** [comment]
Inhibited status on **list** for `defaults` added in https://github.com/inverse-inc/packetfence/commit/2fd6ce8ff83ebbda64384d9d386686e45277b420

View not modified.

**Comment by julsemaan** [comment]
Lets leave view as is and readdress in 9.1, at least we have parity now
