### ISSUE TITLE
'defaults' section of security events should appear first

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4500]
The 'defaults' section of the security events should appear first in the default ordering view

**Comment by jrouzierinverse** [comment]
The default sorting (unsorted) always has the default section first.
However as soon as any sort is defined we should not this is no longer the case.

**Comment by Aluzion** [comment]
The id is used as the default sort. A custom sort function should be used to place default. Agree that once any other sort column is used it's no longer pinned.

**Comment by jrouzierinverse** [comment]
Is it possible to have no sorting by default?

**Comment by extrafu** [comment]
@Aluzion looks like the happy version of @satkunas

**Comment by julsemaan** [comment]
@satkunas, I guess the frontend would have to not send a sort according to @jrouzierinverse

**Comment by satkunas** [comment]
@julsemaan sort will still be sent as many columns can be sorted, where pagination needs to be calculated on the backend. All perl needs to to intercept the `sort: ['id']` and apply a custom sort function only on this key/column. All other keys can use natural sorting.

**Comment by julsemaan** [comment]
@satkunas will remove the sorting by id by default for the security events section
