### ISSUE TITLE
v9-gui: If we clicked on the ? we were able to see which packetfence server hosts the admin

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4504]
we were able to see which packetfence cluster node hosted the packetfence httpd.admin.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/5261214/57726928-38980100-765e-11e9-9c69-f24b31f533f0.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/5261214/57726944-42b9ff80-765e-11e9-844b-3f32d1c79d7d.png">

**Comment by nqb** [comment]
On Debian 9, I got this behavior:
```console
# pfperl-api get  '/api/v1/system_summary' | jq
{
  "hostname": "bdf90cca7ea1",
  "is_inline_configured": false,
  "readonly_mode": false,
  "status": 200,
  "version": "9.0.0"
}
```
![Screenshot from 2019-05-22 11-56-46](https://user-images.githubusercontent.com/10830260/58165758-b5436480-7c88-11e9-9704-a3b16297ce0e.png)
