### ISSUE TITLE
v9-gui: Adjust SMTP test function

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4511]
- `SMTP test` field should allow several email addresses comma-separated
- `SMTP test` field should have `alerting.emailaddr` has default value

**Comment by jrouzierinverse** [comment]
This looks like 9.1 feature not a 9.0.1

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/b748b1d560e823fb09c0cbc6e98425192e487c77
