### ISSUE TITLE
v9-gui: impossible to assign modules to a Root Portal Module

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4513]
After creating a Root Portal Module from **new** GUI, I can't link other modules (like Authentication:: modules) to this module. Same behavior in **old** GUI:

### New GUI

![Screenshot from 2019-05-15 12-14-04](https://user-images.githubusercontent.com/10830260/57767995-f37dd880-770a-11e9-9d68-630ba0b61510.png)

### Old GUI
![Screenshot from 2019-05-15 12-13-40](https://user-images.githubusercontent.com/10830260/57767964-e5c85300-770a-11e9-9d1b-49a6b87c875a.png)

**Comment by cgx** [comment]
Fixed for new GUI via e63d6f9.

**Comment by nqb** [comment]
Not able to test this quickly. I let you do it.

**Comment by fdurand** [comment]
Works in the new admin.
