### ISSUE TITLE
v9-gui: display of UTF8 strings

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4514]
Incorrect display of UTF8 strings in new GUI.

### Steps to reproduce

CentOS 7.6 running nightly builds

```console
# cat user_with_utf8.json
{"pid":"emilie","email":"emilie@foo.fr","firstname":"émilie"}

# file user_with_utf8.json
emilie_user.json: UTF-8 Unicode text

# cat user_with_utf8.json | pfperl-api get -M POST /api/v1/users | jq
{
  "id": "emilie",
  "message": "'emilie' created",
  "status": 201
}
```
### Actual results

In DB:
```
> select firstname from person where pid="emilie"\G;
*************************** 1. row ***************************
firstname: émilie
```

From API:
```console
# pfperl-api get /api/v1/user/emilie | jq .item.firstname
"Ã©milie"
```

In webadmin:
![Screenshot from 2019-05-15 14-20-18](https://user-images.githubusercontent.com/10830260/57775116-95f28780-771c-11e9-8386-2dca4f5c35f7.png)

### Expected results

Correct display of strings in new GUI.

### Additional notes

On Debian 9, I got wrong encoding in DB:
```
MariaDB [pf]> select firstname from person where pid="emilie"\G;
*************************** 1. row ***************************
firstname: Ã©milie
```

**Comment by satkunas** [comment]
>On Debian 9, I got wrong encoding in DB:

This may be just due to your `character_set_client` (server encoding may be fine). What's the encoding of your debian 9 client?

`MariaDB [pf]> SHOW VARIABLES LIKE  'char%';`

**Comment by nqb** [comment]
### Debian

```
MariaDB [(none)]> SHOW VARIABLES LIKE 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

```

### CentOS
```
MariaDB [pf]> SHOW VARIABLES LIKE 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

**Comment by satkunas** [comment]
`person` table uses `latin1` encoding. Either only latin characters should be used, or the table collation will need to be changed to utf8.

```SQL
CREATE TABLE `person` (
...
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

**Comment by extrafu** [comment]
@satkunas I don't see that in the default v9.1 script.

I think everything should be in/out UTF8. The node_category table is hard-coded in latin1 right now in the SQL creation script.

We should review this thoroughly and offer a migration path from latin1 to UTF8.

**Comment by nqb** [comment]
From what I see all `pki` tables use `latin1` as default charset like `node_category` table.

**Comment by extrafu** [comment]
I think we should make sure the PKI tables are NOT using latin1 but UTF8 and re-run the full tests on the PKI to make sure it doesn't break anything.

**Comment by lzammit** [comment]
Installed from scratch right now:
````
[root@pf-testing ~]# rpm -qa packetfence
packetfence-9.3.9-20200403114946.132565811.0007.devel.el7.x86_64
````

````
MariaDB [(none)]> SHOW VARIABLES LIKE 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
````

**Comment by lzammit** [comment]
I will re-test the PKI

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/commit/377ca97ef6ad5475df3eec708f4709766f879b7d

**Comment by extrafu** [comment]
@lzammit retest the PKI *after* the schema change - which @fdurand just did.

**Comment by lzammit** [comment]
Looks good to me:

![image](https://user-images.githubusercontent.com/5261214/78401127-03720580-75c6-11ea-8f30-d113f909b12a.png)

**Comment by extrafu** [comment]
Moving that "issue" to v10.1 for anything else to do in this. If somebody doesn't agree, voice up and move it back to v10.

**Comment by nqb** [comment]
On Debian 9, if I dump my DB, I see that all tables have a `CHARSET=latin1` statement except `sms_carrier` and `admin_api_audit_log` tables. Certainly because table collation is explicilty mentioned in DB schema for these two tables.

**Comment by extrafu** [comment]
Also make sure to handle bidi chars, large chars, etc.
