### ISSUE TITLE
POTD Email is Empty

### ISSUE THREAD

**Issue by Roer** [inverse-inc/packetfence#4515]
After creating a POTD Authentication source, the email is sent without Username, Password, or Expire information.

PacketFence-ZEN 8.3.0

Running `$PF/addons/pf-maint.pl` did not solve the issue.

Last ticket was closed without resolution. #4384

**Comment by nqb** [comment]
Not able to reproduce your issue after installing a fresh CentOS 7.6 with PF running 8.3.

**Comment by Roer** [comment]
I reloaded Packetfence-ZEN and started fresh. It's working fine now. Not sure what the issue was.
