### ISSUE TITLE
POTD: conflict with local source

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4516]
When you want to use a POTD source with a local source (for example on default connection profile without modification), your POTD user will match the local source before POTD causing following message:
![Screenshot from 2019-05-15 14-53-41](https://user-images.githubusercontent.com/10830260/57777070-41054000-7721-11e9-97bc-14fe808fd935.png)

In this context, local source should be able to detect a POTD user (based on `potd: yes` in DB) and fail (in order to have POTD source matching).

**Comment by julsemaan** [comment]
@jrouzierinverse will implement a skip in the SQL source so that it doesn't attempt to authenticate POTD creds

**Comment by jrouzierinverse** [comment]
Please retest

**Comment by jrouzierinverse** [comment]
What is the output of the following command.

```bash
curl -XOPTIONS localhost:22224/api/v1/config/sources?type=Potd | jq .meta.password_rotation
```

**Comment by nqb** [comment]
> Please retest

It works as expected. 

> What is the output of the following command.

```json
{
  "allowed": [
    {
      "text": "10 minutes",
      "value": "10m"
    },
    {
      "text": "20 minutes",
      "value": "20m"
    }
  ],
  "default": "12h",
  "placeholder": null,
  "required": false,
  "type": "string"
}
```

**Comment by jrouzierinverse** [comment]
Can we close this?
