### ISSUE TITLE
packetfence can't use non-English in USERS/ Source/AD's Base DN

### ISSUE THREAD

**Issue by djbdjb00djb** [inverse-inc/packetfence#452]
I'm use packetfence in china, the version is packetfence 4.4.0;

1:I can't input non-Englishin create user dialog for firstname and lastname
etc. in chinese and can save correct, ;
2: I can't use non-English in USERS/ Source/AD's Base DN;
3: I can't use non-English in Rule's condition;

**Comment by louismunro** [comment]
Patches welcomed.

**Comment by louismunro** [comment]
Not to say that we will not do it, but if you can provide patches or help it will definitely make it faster.

**Comment by julsemaan** [comment]
No need for Chinese rules

We already have enough to handle with @atran-inverse
