### ISSUE TITLE
Unable to create switch using MAC address

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4525]
In the new admin, its impossible to create a switch that has a MAC address as the ID

**Comment by julsemaan** [comment]
Code 12

**Comment by extrafu** [comment]
You have damn short arms.

**Comment by cgx** [comment]
Or you're too close to your monitor.

**Comment by jrouzierinverse** [comment]
Why not Both?

**Comment by julsemaan** [comment]
I was actually at 12 feet of my screen configuring PF through a Palm Pilot

**Comment by jrouzierinverse** [comment]
Actual footage of Julien configuring Packetfence
https://www.youtube.com/watch?v=Znxfv8x91K0

**Comment by julsemaan** [comment]
Actual footage of what happens at ZammitCorp when I'm angry:
https://www.youtube.com/watch?v=vY82ZYtOHVw

We can see me fighting with @lzammit in the video above
