### ISSUE TITLE
v9-gui: (debian) edit an HTML file in a new connection profile

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4526]
### Steps to reproduce

1. Create a new connection profile in new GUI
2. Edit layout.html in this connection profile

### Actual results

![Screenshot from 2019-05-15 16-51-17](https://user-images.githubusercontent.com/10830260/57785331-d7416200-7731-11e9-8659-f771b935950c.png)

### Expected results

HTML file displayed

**Comment by fdurand** [comment]
What is your version of libmojolicious-perl ?

**Comment by jrouzierinverse** [comment]
This is a packaging issue.

**Comment by fdurand** [comment]
Uploaded the version is use in the debian repo , if you can make a try.

**Comment by extrafu** [comment]
We'll try with v9.0 packages (all deps) - if all is fine, we'll close that issue.

**Comment by fdurand** [comment]
Fresh debian 9 install with  libmojolicious-perl=7.87-1 works perfectly
