### ISSUE TITLE
v9-GUI: Portal module "This field does not take multiple values"

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4528]
In portal module where you are able to select a authentication source (like Authentication:SMS) then when you try to save it this error appear:

![image](https://user-images.githubusercontent.com/1553962/57793646-d992c480-770f-11e9-8cba-6dfd60da90f7.png)

**Comment by julsemaan** [comment]
quickly tested and it works

**Comment by fdurand** [comment]
same for me
