### ISSUE TITLE
v9-gui: display user with REALM in pid

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4531]
When I try to display a user from Users menu with following pid: `MYDOMAIN\myname`, I got following error:

```json
message: "Unknown path /api/v1/user/MYDOMAIN/myname"
status: 404
```

Backslash doesn't seems to be handle correctly

### Steps to reproduce

```console
# pfperl-api get -M POST '/api/v1/users/' -c '{"pid":"MYDOMAIN\\myname","email":"foo@foo.ca"}' | jq
# pfperl-api get '/api/v1/user/MYDOMAIN\myname/' | jq .item.pid
"MYDOMAIN\\myname"

```
### Actual results

Impossible to display information for such users.

### Expected results

Display information for this users.

**Comment by cgx** [comment]
Related to #4008.

**Comment by julsemaan** [comment]
It seems like MYDOMAIN\myname works fine

Its MYDOMAIN/myname that doesn't get handled right from what I can tell

**Comment by julsemaan** [comment]
Then I've just tried MYDOMAIN/myname and it worked fine, it properly encoded the slash into %2F and got handled correctly for viewing it

**Comment by julsemaan** [comment]
That's on the official 9.0.0 package

**Comment by julsemaan** [comment]
Hold on, it seems that when I refresh the page it doesn't work anymore so it must have been displaying the data from the admin cache after it created the users

**Comment by julsemaan** [comment]
One thing that is weird is that viewing bob\bob or bob/bob results in GET /api/v1/user/bob/bob and the username doesn't seem to be URL encoded

**Comment by satkunas** [comment]
Backend fixes from @jrouzierinverse  in 
- https://github.com/inverse-inc/packetfence/commit/ff71715c1d2cc42ded25241903211e513437f8de
- https://github.com/inverse-inc/packetfence/commit/005c6c588b8b88846002fe37ab928609dcb5363f
