### ISSUE TITLE
v9_gui: admin role issue.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4536]
Let's create a admin role hotel:
![image](https://user-images.githubusercontent.com/1553962/57939441-61a3d600-7898-11e9-97f7-14750d205e0a.png)

with the following user options:
![image](https://user-images.githubusercontent.com/1553962/57939510-80a26800-7898-11e9-953f-d38e67416648.png)

If i assign a local user to this admin role, connect to the admin gui with that user and i try to create a user then the access duration list is empty and the role list contain all the role available.

**Comment by julsemaan** [comment]
Pushing to 9.0.2 so we can get a full fix for the issue
