### ISSUE TITLE
v9-gui: username and password fields to join domain

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4544]
When you want to join a domain, you can't specify username and password in the form. You have to create your domain waiting a failure **then** you can click on "Join" and specify your username and password.

**To Reproduce**
1. Create a new domain

**Additional context**
It was possible in old GUI.

**Comment by julsemaan** [comment]
I thought @satkunas made it so the username/password would prompt right after the creation of the domain so that it would join through the creation process.

Reassigning to 9.0.1 since that seems like a regression to something that should have been in 9.0

**Comment by julsemaan** [comment]
Just tested and although the button says "Create and join", it only creates the domain and never starts the join process on creation

The issue in #4474 is still alive

**Comment by satkunas** [comment]
I missed the redirection on new/clone on my last fix. This has been added in https://github.com/inverse-inc/packetfence/commit/f76998604547cf9eaac83da585ee37e11257f606
