### ISSUE TITLE
v9-gui: label on netdata graphs truncated

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4548]
**Describe the bug**
Labels on Netdata graphs are truncated (see below). Not the case in old GUI.

**Screenshots**
![Screenshot from 2019-05-20 16-24-15](https://user-images.githubusercontent.com/10830260/58029006-05e97f00-7b1c-11e9-8485-a71f847b517b.png)

**Expected behavior**
Wireless-802.11-NoEAP and Wireless-802.11-EAP labels should not be truncated.

** Additional context**
I got this behavior for all Netdata Graphs displayed on "Status" page

**Comment by julsemaan** [comment]
Its the netdata rendering that is problematic, we'll push forward
