### ISSUE TITLE
v8.3 to v9 (pfconfig): Could not send all bytes the client.

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4549]
**Describe the bug**
When `pfstats` is running, `pfconfig` display each ten seconds in `pfconfig.log` following error message:
```
May 20 16:33:45 nac pfconfig: pfconfig(8759) ERROR: [mac:[undef]] Could not send all bytes the client. 1137 of 1141 sent (main::send_output)
```

**Comment by julsemaan** [comment]
Tried it with the latest version of pfstats and I'm not getting this behavior.

Can you provide more details around the environment?

Also, can you confirm if things are working nonetheless, if its the case, we'll move this to +1 patch so we can release 9.0.1 without it

**Comment by nqb** [comment]
> Can you provide more details around the environment?

v8.3 CentOS 7.6 upgraded to v9, following UPGRADE guide.

> Also, can you confirm if things are working nonetheless, if its the case, we'll move this to +1 patch so we can release 9.0.1 without it

`pfstats` is running, it doesn't display erros.
How to check `pfstats` is working as expected in dashboard ?

**Comment by julsemaan** [comment]
> How to check pfstats is working as expected in dashboard ?

All the different metrics described in the stats configuration appear with data. You could do:

tcpdump -nlp -i any port 8125 -w-|strings| grep 'source.packetfence.redis.queue_stats_count'

And do this with the different namespaces in stats.conf.defaults to validate that they are being pushed correctly to statsd

You can also check in the netdata dashboard (the one on 19999) that for the different statsd namespaces, there are regular events in the graphs

**Comment by nqb** [comment]
Thanks @julsemaan.

`pfstats` is working as expected.
