### ISSUE TITLE
Violation 1100004 is ignored

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#455]
WARNING - Violation 1100004 is ignored: Invalid trigger id: DEVICE:28 at /usr/local/pf/lib/pf/trigger.pm line 194.

The comments in conf/violations.conf states : 

```
Example config to block an OS based on their dhcp fingerprint
Trigger format: an id (defined as os_id in os_type table)
Right now the only way to find the os id is to query the database but it should be feasible
from the pfcmd tool or the web gui in the future.
From a MySQL prompt, a 'select * from os_type;' will give you what you need. Just put in 
the os_id next to DEVICE::. In exemple to block Windows 95 you would use: DEVICE::30
```

Only problem is, there is no os_type table.

**Comment by jrouzierinverse** [comment]
The ignore was fixed the trigger type was badly formatted. 
I will update the comment in the conf/violations.conf.example

**Comment by jrouzierinverse** [comment]
This was fixed by @dwlfrth
