### ISSUE TITLE
API OPTIONS meta missing ID constraints 

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4554]
Additional meta for `id`entifiers required, so the front-end can catch these errors first.

![Screenshot from 2019-05-21 09-49-52](https://user-images.githubusercontent.com/3904468/58102339-20b90380-7baf-11e9-9f9a-3b3a27c93388.png)

**Comment by jrouzierinverse** [comment]
Which constraints?
```bash
./sbin/pfperl-api get -M OPTIONS /api/v1/config/domains | jq .meta.id
{
  "default": null,
  "max_length": 10,
  "placeholder": null,
  "required": true,
  "type": "string"
}
```

**Comment by satkunas** [comment]
@jrouzierinverse can we include a `pattern`?

**Comment by jrouzierinverse** [comment]
will do also it seems like max_length is not being checked before submitting.

**Comment by satkunas** [comment]
@jrouzierinverse max_length is working

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/domain/Inverse | jq '.meta.server_name'
{
  "default": "%h",
  "max_length": 14,
  "placeholder": null,
  "required": true,
  "type": "string"
}
```

![Selection_030](https://user-images.githubusercontent.com/3904468/58182669-0bf67180-7c7c-11e9-9771-cefd0b0e6e57.png)

**Comment by jrouzierinverse** [comment]
It is missing when doing the clone
