### ISSUE TITLE
v9-gui WMI Scanner won't accept values

### ISSUE THREAD

**Issue by WallaPF** [inverse-inc/packetfence#4559]
When configuring WMI scanner in PFv9 (Compliance -> Scans -> New Scan Engine -> WMI, values are not accepted:

** To Reproduce **
1. Form input screenshot:
![2019-05-22 10_07_53-Administrator - PacketFence](https://user-images.githubusercontent.com/45529653/58154933-778c0f00-7c7b-11e9-933b-1f71d77b6669.png)
2. OS pick list is not populated.
3. After filling the form error messages: "Unable to validate". two more errors are attached as screenshot:
![2019-05-22 10_06_29-Administrator - PacketFence](https://user-images.githubusercontent.com/45529653/58154895-575c5000-7c7b-11e9-96c7-387607602f3a.png)

**Expected Behavior**
Form input to be accepted and added as a scan engine for compliance.

**Comment by satkunas** [comment]
@jrouzierinverse `oses` has no meta, so there's no `allowed_lookup` to search.

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/scans?type=wmi | jq '.meta.oses'
```
[empty response]

**Comment by jrouzierinverse** [comment]
WMI has no oses

**Comment by satkunas** [comment]
`oses` removed from WMI scans in https://github.com/inverse-inc/packetfence/commit/7222370400692ed3bfc85af9f6d42ce2768d24ed

**Comment by julsemaan** [comment]
@dondon21 can you test you can save a WMI scan engine in the next build

**Comment by julsemaan** [comment]
This is still happening on the latest build

**Comment by jrouzierinverse** [comment]
This is a frontend issue.
wmi_rules is being sent as an array of array of string instead of an array of strings

```json
{
   "wmi_rules" : [
      [
         "Software_Installed",
         "logged_user"
      ]
   ],
   "duration" : {
      "unit" : "s",
      "interval" : 20
   },
   "categories" : [
      "default"
   ],
   "username" : "asas",
   "registration" : null,
   "domain" : "asas",
   "password" : "asasa",
   "post_registration" : null,
   "pre_registration" : null,
   "wmi_policy" : null,
   "type" : "wmi",
   "id" : "asasa"
}
```

**Comment by satkunas** [comment]
Flattened in https://github.com/inverse-inc/packetfence/commit/f8c443cf0084e95b7581858879f8021fcf80f667

**Comment by julsemaan** [comment]
tested and it works fine, the source config looks the same in the old and new admin as well
