### ISSUE TITLE
Nothing happens buttom configurator

### ISSUE THREAD

**Issue by ghost** [inverse-inc/packetfence#4564]
Hi, 
I'm on the last version of ZeroEffort NAC and when I go on the adress on my webpage (configurator page) When I clic on buttom "continue" on step 1, nothing happens, I can't pass step 1 ahah. And I can navigate menu at the top. 

I tried : 
Clear cache
Use other web navigator
Reboot VM
Give more ressource to VM
Install it my self with my debian (work but have another problem...)
Try USB version (same problem)
Change OS (Redhat to Debian)

I haven't tried (but I will do quickly) : 
Try another version of PacketFence.

I'm sorry for my bad english and thanks in advance !

![2019-05-23_00h14_30](https://user-images.githubusercontent.com/20617722/58213128-57973280-7cf1-11e9-85a2-f5e79ba26427.png)
![2019-05-23_00h23_18](https://user-images.githubusercontent.com/20617722/58213129-57973280-7cf1-11e9-9c24-7f5ec4321969.png)
![2019-05-23_00h23_52](https://user-images.githubusercontent.com/20617722/58213130-582fc900-7cf1-11e9-8ee1-ecca13799c37.png)
![2019-05-23_00h25_08](https://user-images.githubusercontent.com/20617722/58213131-582fc900-7cf1-11e9-8236-522b3ac92674.png)

**Comment by ghost** [comment]
Have find solution : 
1°/Go to setting of your browser
2°/Language
3°/Change French (or any other language) by English

I think they are problem with Jquerry for the french version.

But now have another problem... When I'm at step 4, the process just crash. Maybe bad information like domain? But I'm on local network, just my host, 1 switch et my virtual machine on my host with Oracle VM. 
I close this issue and open new or can I continue here?
Thanks in advance. 
![2019-05-23_10h27_27](https://user-images.githubusercontent.com/20617722/58237519-8b9c4300-7d45-11e9-93dd-d290a9e92660.png)
![2019-05-23_10h05_42](https://user-images.githubusercontent.com/20617722/58237530-922aba80-7d45-11e9-99af-0a22cb981ed1.png)

**Comment by nqb** [comment]
Hello,

Don't put an IP address in "Hostname" field. Also, if possible:
* use PacketFence v9 in place of ZEN 8.3.
* use packetfence-users mailing list for this kind of issue
