### ISSUE TITLE
v9-gui: default columns in RADIUS audit logs

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4569]
The default columns in RADIUS audit logs are not the same between old GUI and new GUI.

**Screenshots**

New GUI
![Screenshot from 2019-05-24 11-52-25](https://user-images.githubusercontent.com/10830260/58319699-6af1ed00-7e1a-11e9-8f66-1674d0bb8a5d.png)

Old GUI
![Screenshot from 2019-05-24 11-52-19](https://user-images.githubusercontent.com/10830260/58319708-6d544700-7e1a-11e9-8b1a-1d36b84084de.png)

**Expected behavior**
NAS Port Type should be present by default.

**Comment by julsemaan** [comment]
Lets postpone this to 9.0.2 since its not a showstopper for 9.0.1

**Comment by nqb** [comment]
> Lets postpone this to 9.0.2 since its not a showstopper for 9.0.1

you're right.

**Comment by satkunas** [comment]
Added in https://github.com/inverse-inc/packetfence/commit/b5a9249e78676d7e430d2ff3c1066e3f9adda9ce
