### ISSUE TITLE
Redirect to login screen on token expiration

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4571]
**Is your feature request related to a problem? Please describe.**
Right now when the token expires, you are allowed to browse the admin and you get redirected to the login when the next API call is done

**Describe the solution you'd like**
It would be good to redirect the user to the login screen when the token expires in the frontend (available in token_info)

**Additional context**
Zammit said it would be nice

**Comment by satkunas** [comment]
![](https://memegenerator.net/img/instances/84512665/if-you-could-redirect-me-when-my-token-expires-that-would-be-nice.jpg)
