### ISSUE TITLE
pf-maint: patching of the administration frontend causes issue

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4574]
**Describe the bug**
After an upgrade from 9.0 to 9.0.1, I ran `pf-maint.pl` and restart all PF services.

I got 404 to get some files under: `$PF/html/pfappserver/root/static/alt/js`. My web browser is trying to reach old JS files (before patching).

**To Reproduce**
1. Set up a fresh installation with PF 9.0.1
2. Run `pf-maint.pl` and restart all PF services
3. Try to reach webadmin => it failed

Due to web browser cache, it's possible you will be able to reach webadmin after patching.

**Expected behavior**
Webadmin should be reachable

**Additional context**
* A `GET` to `/admin/alt` returns path to old JS files (example: `app.*.css` and `app.*.js`)
* Files under `$PF/html/pfappserver/root/static/alt/js` are the ones from patching

**Comment by julsemaan** [comment]
If the issue is the browser cache my guess would be we should add no cache headers to the index page.

That means it will be reloaded every time but my expectation is that it won't be too much since the biggest data chunks are in the assets

@cgx, can you confirm the idea above is good ?

**Comment by nqb** [comment]
@julsemaan: I clear all my cache, issue still presents.

**Comment by cgx** [comment]
`root/admin/v-index.tt` must be updated.

**Comment by nqb** [comment]
@cgx is right, this file still contains path to old JS files.

**Comment by julsemaan** [comment]
working on pf-maint.pl so that it patches v-index.tt as well

**Comment by julsemaan** [comment]
Patched pf-maint.pl and added the creation of v-index.tt in the repo

af13b3393309d8b29ff703a0fd5b780c9d4104ef

@nqb, give it another try and let me know how it goes, you'll need to run pf-maint.pl twice (first to patch pf-maint.pl itself, second to run it with the new code)

**Comment by nqb** [comment]
It works, well done @julsemaan !
