### ISSUE TITLE
Interface up/down not working in the web admin

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4576]
Putting down an interface does not disable it from the system.

It works in the config.

````
{
    "message": "Interface ens192.147 disabled",
    "status": 200
}
````

**Comment by jrouzierinverse** [comment]
This looks like a display issue aa itt works in the backend.
How did you determine it was not disabled?

**Comment by lzammit** [comment]
The status is down but it does not take out the IP address for inline split network:

````
ip a 

7: ens192.147@ens192: <BROADCAST,MULTICAST> mtu 1500 qdisc htb state DOWN group default qlen 1000
    link/ether 00:0c:29:ae:b6:8c brd ff:ff:ff:ff:ff:ff
    inet 172.22.147.2/24 brd 172.22.147.255 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.1/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.33/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.65/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.97/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.129/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.161/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.193/27 scope global ens192.147
       valid_lft forever preferred_lft forever
    inet 172.22.147.225/27 scope global ens192.147
       valid_lft forever preferred_lft forever
````

It shows down but the address are there, if I do:

[root@unicorn pf]# ifdown ens192.147

The interface is not there anymore.

**Comment by julsemaan** [comment]
@lzammit 

Not sure we need the IP addresses to disapear. If the interface is down, IMO its fine.

**Comment by satkunas** [comment]
@julsemaan Is this a front-end issue? If not, this should be re-assigned.

**Comment by julsemaan** [comment]
I think this is a non-issue, if the interface is set to down and appears as down then we're good.

The fact that the IP addresses are left on the interface is the same behavior as the old admin and should be fine since they're inactive due to the down state of the interface
