### ISSUE TITLE
v9-gui: bad display of role without description

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4578]
If a role has no description, new GUI display "null" next to role's name when selecting a role in a dropdown list (from Nodes menu).

**To Reproduce**
1. Create a role without description
2. Try to assign this role to a node

**Screenshots**
![Screenshot from 2019-05-28 13-59-41](https://user-images.githubusercontent.com/10830260/58476374-dc9aa580-8150-11e9-93ef-d835d22d88b6.png)

**Comment by satkunas** [comment]
fixed in https://github.com/inverse-inc/packetfence/commit/83278c6e1570642d584c4a4c2dba42b4cbca0fe0

**Comment by julsemaan** [comment]
This needs to be cherry-picked in the maintenance branch

**Comment by satkunas** [comment]
@julsemaan done

**Comment by cgx** [comment]
dewscription fixed! thanks to *big-fingers* @satkunas.
