### ISSUE TITLE
v9 Fingerbank empty set

### ISSUE THREAD

**Issue by WallaPF** [inverse-inc/packetfence#4579]
**bug description**
Fingerbank "Combination" and "User_Agent" tables return an empty value

**To Reproduce**
Get these tables from the API

**packetfence.log errors**
May 29 13:04:31 PacketFence-ZEN packetfence: INFO pfperl-api(24632): Searching for 'Combination' entries in schema(s) returned an empty set (fingerbank::Base::CRUD::search)
May 29 13:04:31 PacketFence-ZEN packetfence: INFO pfperl-api(24633): Searching for 'Combination' entries in schema(s) returned an empty set (fingerbank::Base::CRUD::search)
May 29 13:04:31 PacketFence-ZEN packetfence: INFO pfperl-api(24633): Searching for 'User_Agent' entries in schema(s) returned an empty set (fingerbank::Base::CRUD::search)
May 29 13:04:32 PacketFence-ZEN packetfence: INFO pfperl-api(24639): Fetched user account information successfully (fingerbank::API::account_info)

**Expected behavior**
Get Fingerbank's response from these tables

**Comment by julsemaan** [comment]
These tables aren't shipped anymore from PF 8.0 and above as the database is only used for creating local combinations but not for discovery anymore as it goes through the API at 100% now

**Comment by WallaPF** [comment]
@julsemaan Note that it did work in ver 8.3

**Comment by julsemaan** [comment]
Not sure how that ever worked unless you had an outdated database version or pointing to the wrong API server since its stripped from the DB since the launch of Fingerbank v2

**Comment by WallaPF** [comment]
**Refining the case**
When a node is identified, Its fingerprint won't populate in the in the node tab.
These are the relevant packetfence.log errors:

Jun  2 15:44:44 PF-9 packetfence: WARN pfperl-api(13318): Can't find scan engine for 68:f7:28:bd:95:17 since we don't have it's OS (pf::Connection::Profile::findScan)
Jun  2 15:44:50 PF-9 packetfence: INFO pfperl-api(13319): Could not find any 'Device' entry with ID '31' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Jun  2 15:44:50 PF-9 packetfence: ERROR pfperl-api(13319): Unable to read device 31 (Class::MOP::Class:::after)

Manual "Refresh Fingerbank" in the node tab will return the correct values.
So, in the scanning a node process (especially WMI) the fingerprinting is broken.

**Comment by julsemaan** [comment]
Device 31 doesn't exist anymore in Fingerbank v2

This really looks like a deployment (or database) that was pre-8.0 then upgraded to 8.0+ without applying the proper Fingerbank upgrade scripts

Try applying:
```
/usr/local/pf/addons/upgrade/to-8.0-fingerbank-db-data.pl
```

Note that after this, PacketFence will need to learn the data again from your endpoints meaning it will need to see DHCP/HTTP/TCP packets for the device in order for the information to populate again

Also, if you can provide your scan.conf for further analysis

**Comment by WallaPF** [comment]
@julsemaan 
Applied the DB command you provided.

Note that it's a clean fresh v9 install, not an upgrade.
I use SNMP trap to assign VLAN with Cisco 3760G switch.
The node is Windows 10 with Symantec endpoint protection.

**Logs**
Jun  3 17:40:35 PF-9 packetfence: INFO pfperl-api(13310): Could not find any 'Device' entry with ID '31' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Jun  3 17:40:35 PF-9 packetfence: ERROR pfperl-api(13310): Unable to read device 31 (Class::MOP::Class:::after)
Jun  3 17:40:35 PF-9 packetfence: INFO pfperl-api(13310): Could not find any 'Device' entry with ID '32' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Jun  3 17:40:35 PF-9 packetfence: ERROR pfperl-api(13310): Unable to read device 32 (Class::MOP::Class:::after)

Why does it use Device 31 or 32 at all?
DHCP fingerprint is OK...OS is not showing.

Scan.conf attached:
[scan.zip](https://github.com/inverse-inc/packetfence/files/3247759/scan.zip)

**Comment by julsemaan** [comment]
Device 31 and 32 are outdated devices.

Could you provide an archive containing /usr/local/pf/conf/ so I can take a look at everything

You can send this directly to jsemaan@inverse.ca so its not published online

**Comment by ghost** [comment]
> 
> 
> @julsemaan
> Applied the DB command you provided.
> 
> Note that it's a clean fresh v9 install, not an upgrade.
> I use SNMP trap to assign VLAN with Cisco 3760G switch.
> The node is Windows 10 with Symantec endpoint protection.
> 
> **Logs**
> Jun 3 17:40:35 PF-9 packetfence: INFO pfperl-api(13310): Could not find any 'Device' entry with ID '31' in schema 'Upstream' (fingerbank::Base::CRUD::read)
> Jun 3 17:40:35 PF-9 packetfence: ERROR pfperl-api(13310): Unable to read device 31 (Class::MOP::Class:::after)
> Jun 3 17:40:35 PF-9 packetfence: INFO pfperl-api(13310): Could not find any 'Device' entry with ID '32' in schema 'Upstream' (fingerbank::Base::CRUD::read)
> Jun 3 17:40:35 PF-9 packetfence: ERROR pfperl-api(13310): Unable to read device 32 (Class::MOP::Class:::after)
> 
> Why does it use Device 31 or 32 at all?
> DHCP fingerprint is OK...OS is not showing.
> 
> Scan.conf attached:
> [scan.zip](https://github.com/inverse-inc/packetfence/files/3247759/scan.zip)

I have the same issue. Fingerbank process doesn't start at the initialization of a new connection profile. I'm sure of this because the process timestamp does not match the system time when a new device is detected.
