### ISSUE TITLE
mysql is not started at boot after PF install

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#458]
Looks like mysqld is not added to the services to be started by default after installing the packetfence package on centos 6.

This is with packetfence-4.7.1-0.20150410.el6.noarch

**Comment by louismunro** [comment]
Doh. Forget it.

**Comment by extrafu** [comment]
Zammitbug?

**Comment by louismunro** [comment]
You could say that....
It looks like its on purpose.
