### ISSUE TITLE
Web admin: smart close

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4580]
Some pages allow to route to a *closable* view. Examples:

* from the RADIUS search, one can visit a node;
* from the nodes search, one can visit a user.

When closing such a view, we should be smart and return the previous context. Currently, we always route to the search page of the visited component.

**Comment by satkunas** [comment]
Using `router.go(-1)` should suffice

https://router.vuejs.org/guide/essentials/navigation.html#router-go-n
