### ISSUE TITLE
web admin (security events): add an internal trigger 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4581]
In new GUI, it's not possible to add an internal trigger on a security event.
Still possible from old GUI.

**To Reproduce**
1. Create a new security event
2. Add a trigger
3. Click on "Any event"

=> You can select built-in triggers but you can't **create** a new trigger.

**Expected behavior**
You should be able to create a new trigger with an ID.

**Screenshot**
In old GUI:
![Screenshot from 2019-06-03 14-55-09](https://user-images.githubusercontent.com/10830260/58803420-bf158200-860f-11e9-933d-a8d87d07c4c0.png)

**Comment by cgx** [comment]
Custom internal triggers should be now defined as *custom* triggers. v9.0.2 will provide the *custom* trigger in the Web admin, and v9.1 will provide a migration script (to be developed) to migrate custom internal triggers to custom triggers.

**Comment by julsemaan** [comment]
We need to update the examples to use the new 'custom' trigger
