### ISSUE TITLE
Fingerbank MAC vendor lookup doesn't search for mac (only name)

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4585]
**Is your feature request related to a problem? Please describe.**
When creating a Fingerbank local combination (#/configuration/fingerbank/local/combinations/new) and assigning a MAC vendor it only searches by the MAC vendor name and not the MAC vendor mac field which is a pain when you want to filter by a specific MAC OUI since you have to guess the name of the OUI

**Describe the solution you'd like**
Lookup should be on name and mac fields

**Additional context**
This can be especially useful if the name of the MAC vendor follows the convention in this video: https://www.youtube.com/watch?v=9HuTKuMCUpU

**Comment by julsemaan** [comment]
It would be good if the MAC OUI would be included in brackets after the name

Example:
Searching for 00112 shows the names of the vendors but not the OUI.

So it would be good to display the MAC OUI (mac attribute) in brackets after the name at all times making it '${mac_vendor.name} (${mac_vendor.mac})' so that we know what we're searching for

**Comment by satkunas** [comment]
@julsemaan added in https://github.com/inverse-inc/packetfence/commit/de66d82309b7a180f71e90132ea50d27bdef38bc

**Comment by julsemaan** [comment]
all good now!
