### ISSUE TITLE
Modifying the local database in the new admin doesn't sync the cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4586]
**Describe the bug**
When you CRUD a Fingerbank local attribute (like creating a combination), the cluster isn't being synced since the API doesn't call pf::fingerbank::sync_local_db() like the previous admin did

**To Reproduce**
1. Go to '#/configuration/fingerbank/combinations'
2. Click "Local"
3. Create a new local combination with some valid data

**Expected behavior**
The database should be synced and the Fingerbank cache be cleared (both done by pf::fingerbank::sync_local_db())

**Comment by julsemaan** [comment]
Missing the maintenance

**Comment by jrouzierinverse** [comment]
Done
