### ISSUE TITLE
Unable to delete a switch in new admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4588]
**Describe the bug**
Unable to delete a switch in the new admin

**To Reproduce**
1. Go in the switches, select delete
2. It expands and show confirmation
3. Click on the delete
4. Cry because the switch is still there

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/58980818-2281ea00-879f-11e9-9f98-a16383aa1d26.png)

**Expected behavior**
The switch is deleted

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 67.0

**Comment by julsemaan** [comment]
That applies to switch groups as well

**Comment by extrafu** [comment]
Shouldn't that go in the maintenance?
