### ISSUE TITLE
Search for a mac address doesn't accept all format. (New admin)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4593]
**Describe the bug**
In nodes tab , search for 605718E1F0F0 doesn't work, search for 60:57:18:E1:F0:F0 works.

**To Reproduce**
In nodes tab , search for 605718E1F0F0 doesn't work, search for 60:57:18:E1:F0:F0 works.

**Expected behavior**
Find something

**Comment by julsemaan** [comment]
@jrouzierinverse 

Can we get this fixed, its a PITA and all customers where I did upgrades complained about the MAC format issue in the search
