### ISSUE TITLE
It's not possible to create a Source action "mark as sponsor" in PF 9.0.1

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#4597]
**Describe the bug**
If you try to create a AD Source with "mark as sponsor" action, you get the following message:
administration_rules.1.actions.0.value: Value field is required

**To Reproduce**
1. Go to your AD Source
2. Create a Administration Rule
3. Use "Mark as sponsor" as Actions
4. click save

In pf 8.3 it worked as expected

**Comment by nqb** [comment]
As a workaround, you can use old web admin.
