### ISSUE TITLE
v9-gui: Other Reports display issue

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#4601]
**Describe the bug**
It seems the SMS Registration and the Email Registration reports displays records ordered by Code expiration in reverse order -- and you can not sort per column.  So, to see the most recent Email/SMS Registrations, I have to page through each page to get to the end.  In regards to that, it seems both the single page > and the last page >> icons only advance a single page.

**To Reproduce**
1. Go to 'Other Reports'
2. Click on 'SMS Registration'
3. Notice Code expiration column

**Expected behavior**
The page should either display the most recent Code expirations on page 1 and/or allow to reverse the order of the Code expiration and/or the >> (go to last page) arrows should work properly.

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: Chrome
 - Version: 75

**Comment by cgx** [comment]
Concerning pagination, see issue #3342.

**Comment by julsemaan** [comment]
The frontend is likely not sending the sort during its query which is available in `order_fields`
