### ISSUE TITLE
CSV Node import only accepts single MAC format

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4602]
CSV Node import currently only accepts `00:11:22:33:44:55` MAC address format.

Also needs to accept formats:

- `001122334455`
- `00-11-22-33-44-55`

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Comment by jrouzierinverse** [comment]
I believe this was fixed in the front end by @satkunas.

**Comment by extrafu** [comment]
@satkunas Is that the case? If so let's close that issue.

**Comment by extrafu** [comment]
@lzammit Please retry and update (or close) this ticket accordingly. Please also review all import related issues.

**Comment by lzammit** [comment]
Works for both format mentioned.
