### ISSUE TITLE
pfsetvlan starts even when disabled

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#461]
In multimaster mode:

the status shows up as 
    pfsetvlan|0|27500

pfsetvlan, the daemon that just won't quit. It's like the energizer bunny.

**Comment by julsemaan** [comment]
You're right. I know why. I forgot to 'un-code' something before the multimaster merge. I'll fix it monday

**Comment by julsemaan** [comment]
Adding zammitbug label anyway just because it's funny

**Comment by louismunro** [comment]
Fixed.
