### ISSUE TITLE
Impossible to select empty role (no role) for device registration entry

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4617]
**Describe the bug**
When configuring a device registration policy its not possible to select an empty value for the role (meaning compute role dynamically) because the OPTIONS for the device registration strip the empty values from the allowed options of the select

**To Reproduce**
1. Edit the default registration policy and try to assign an empty role

**Comment by satkunas** [comment]
@julsemaan does https://github.com/inverse-inc/packetfence/commit/b9991af59800e67ab2b6ce4d3d70b6ed739752c2 address this issue?

**Comment by julsemaan** [comment]
@satkunas, if it allows to select no role in the default device registration policy then it does but from our previous discussion, @jrouzierinverse had to send back the right OPTIONS for this to work

**Comment by julsemaan** [comment]
@jrouzierinverse 

Can you look into this so we can get this in maintenance ?

**Comment by julsemaan** [comment]
fixed in maintenance
