### ISSUE TITLE
webadmin: translation not persistent

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4622]
After setting language to French in webadmin, preference is lost when I quit my web browser and open a new one.

**To Reproduce**
1. Login as "admin"
2. Change language to French
3. Quit your web browser
4. Re-open your web browser and go back to web admin

=> Web admin is translated in English

**Expected behavior**
Web admin is still translated in French

**Informations*
I notice that when I re-opened my web browser there is following API calls:
* GET /api/v1/token_info (with current token)
* GET /api/v1/translation/en

My preferred language in web browser is set to French.

**Comment by julsemaan** [comment]
![image](https://user-images.githubusercontent.com/3857942/59848706-d359be80-9333-11e9-9ff0-85af311ea01c.png)

**Comment by extrafu** [comment]
@julsemaan Clearly looks like @nqb

**Comment by nqb** [comment]
:baguette_bread:

**Comment by satkunas** [comment]
@cgx should we use the browsers `Accept-Language` header to automagically set the default lang?

**Comment by cgx** [comment]
@satkunas The backend should already be consuming the `Accept-Language` header. On the frontend, we should look at `window.navigator.language`.

**Comment by nqb** [comment]
@cgx, @satkunas should we postpone to 9.2 ?

**Comment by julsemaan** [comment]
@cgx will use the browser defined language
