### ISSUE TITLE
Ubiquiti Support

### ISSUE THREAD

**Issue by izzie88** [inverse-inc/packetfence#4624]
Is there packet fence support for Ubiquiti UniFi controller and AP?

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of question.

> Is there packet fence support for Ubiquiti UniFi controller and AP?

https://packetfence.org/doc/PacketFence_Network_Devices_Configuration_Guide.html#_ubiquiti_2
