### ISSUE TITLE
Google auth with local account creation not showing during captive portal.

### ISSUE THREAD

**Issue by jacac** [inverse-inc/packetfence#4625]
With the Google authentication source and create local account enabled, the local account information is not available to the user. No email is send to the user and the page show local account is not displayed during captive portal registration.

**To Reproduce**
1. Add `Google` authentication source with `Create Local Account` selected.
![image](https://user-images.githubusercontent.com/422293/60040677-5baacd00-966e-11e9-9937-8c2ba1975c3c.png)

2. In `Advanced  Access Configuration` -> `Portal Modules' edit `Root` and add another Module 'default_show_local_account'.
![image](https://user-images.githubusercontent.com/422293/60040473-f35beb80-966d-11e9-911d-48de616fdfa3.png)

![image](https://user-images.githubusercontent.com/422293/60040496-fce55380-966d-11e9-92c5-e167633a9b00.png)

![image](https://user-images.githubusercontent.com/422293/60040516-08387f00-966e-11e9-9c8e-7fd91f25b2c9.png)

**Expected behavior**
During the captive portal signup using Google Oauth the local account information should be displayed and an email should be send out to the user with the local account information.

**Additional context**
Logs in packetfence.log show `Can't create account since there is no user e-mail in the session.` The account is still created and personal information exist in the database. Comparing to other modules is looks like `$self->app->session->{email} = $email;` is not set during the `handle_callback` function in `html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/OAuth.pm`

**Comment by julsemaan** [comment]
If you check the user entry that got created through that registration (Users tab of the admin) and provide me a screenshot of the entry when you view the details of the user

If there is no user, try to perform the process without the local account creation and check if the entry gets created

**Comment by jacac** [comment]
The issue is that the email with the account information is not send to the user. Neither is the `default_show_local_account` page displayed during the captive portal registration process.

If I add 
`if($info->{email}) {
        $self->app->session->{email} = $info->{email};
}`

to https://github.com/inverse-inc/packetfence/blob/c52ef3e013d5e0cab94de83551edc7528f42a7d3/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/OAuth.pm#L171

The email is getting send and the local account information is shown. But I'm not sure if this is the right approach.

**Comment by julsemaan** [comment]
The fix there seems to make sense. I'll test it in lab and add it to devel + maintenance

**Comment by julsemaan** [comment]
fixed and added to the maintenance, thanks for the pointer

**Comment by jacac** [comment]
Thanks for fixing it.
