### ISSUE TITLE
Adding a search attribute removes the username attribute from the auth lookup

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4626]
**Describe the bug**
When using search attributes, it performs the auth lookup only on the attributes in searchattributes and not on the username attribute plus the search attributes like one would expect since we're adding attributes that can be used as the username.

**To Reproduce**
1. Create an LDAP source with sAMAccountName as the username attribute and homePhone as the search attribute
2. add a catchall rule
3. Perform a pftest with both values and only the homePhone will provide a match to the source+rule

**Expected behavior**
lookups should be done on the username attribute AND the search attributes

**Comment by nqb** [comment]
As a workaround, you can set username attribute in the list of search attributes.
