### ISSUE TITLE
The timestamp validation on configstore write conflicts with synching

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#463]
The timestamp validation makes the admin block and refuse to save when using a sync script that writes the files. The only way out is the command line.

Affected version is : 4.7

We should either remove that check or offer an option in the admin to force the current write or a global option that would ignore this bringing back the behavior before 4.7

4.7 should be patched in the maintenance script

**Comment by louismunro** [comment]
Looks like it may be more than 4.7.
The client we’re thinking of is running 4.5.1.

## 

LM
