### ISSUE TITLE
v9 GUI - SAML: Path to Service Provider Cert (x509) missing field

### ISSUE THREAD

**Issue by jose-duarte** [inverse-inc/packetfence#4631]
Missing field makes it not possible to create a SAML source using the new GUI.

1. Go to Authentication Source
2. Click on new Internal Source - SAML
3. Fill in all the fields
4. See API error noticing the Cert field is missing

pf 9.0.1, debian stretch

**Comment by julsemaan** [comment]
@satkunas 
Can you check for any missing fields in the SAML source in the new admin and add them

@jose-duarte 
Just in case you don't know, you can still access the old admin to configure this source in the meanwhile (accessible in the top right menus)
![image](https://user-images.githubusercontent.com/3857942/60266451-0f51ce00-98b6-11e9-911b-31c60b6eea2d.png)

**Comment by jose-duarte** [comment]
@julsemaan thanks for the tip, actually found the old admin panel just before your reply and was able to set it up correctly. 
Just for reference, another thing missing in the new panel is the metadata download button after creating the SAML source.
