### ISSUE TITLE
DNS Clients not 8.8.8.8

### ISSUE THREAD

**Issue by lukasnasc** [inverse-inc/packetfence#4632]
Pfdns is enabled

/etc/resolv.conf
8.8.8.8

Interface LAN PacketFence
DHCP: active
DNS: 8.8.8.8

Although, the client get do DNS IP from packetfence (example: 192.168.1.1)

I want the clients get DNS 8.8.8.8.  How I do that?

Thanks

**To Reproduce**

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by extrafu** [comment]
Use the mailing list for such question.
