### ISSUE TITLE
MikroTik - Necessary changes to get this working (Solved)

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4635]
The following changes fix MikroTik RADIUS support and RADIUS disconnect for wireless clients to be re-evaluated.

Changes:
- FreeRADIUS now includes MikroTik vendor attributes, renamed those in the module to avoid having to define custom vendor attributes.
- RADIUS disconnect uses the MAC address with colons, not dashes
- RADIUS disconnect expects the MAC address in the User-Name attribute
- RADIUS disconnect Username needs to returned with quoted MAC
- RADIUS VLAN ID on authorisation needs to be quoted (otherwise gets sent as 666.0 instead of 666)

<pre>--- Mikrotik.pm.orig    2019-06-29 07:05:09.785209758 +0200
+++ /usr/local/pf/lib/pf/Switch/Mikrotik.pm     2019-07-01 06:58:03.834805113 +0200
@@ -175,7 +175,7 @@

 =item radiusDisconnect

-Sends a RADIUS Disconnect-Request to the NAS with the MAC as the Calling-Station-Id to disconnect.
+Sends a RADIUS Disconnect-Request to the NAS with the MAC as the User-Name to disconnect.

 Has been tested with 6.18 Mikrotik OS version and doesn´t work yet

@@ -221,13 +221,13 @@
             LocalAddr => $self->deauth_source_ip($send_disconnect_to),
         };

-        # transforming MAC to the expected format 00-11-22-33-CA-FE
+        # transforming MAC to the expected format 00:11:22:33:CA:FE
         $mac = uc($mac);
-        $mac =~ s/:/-/g;
+        #$mac =~ s/:/-/g;

         # Standard Attributes
         my $attributes_ref = {
-            'Calling-Station-Id' => $mac,
+            'User-Name' => "$mac",
         };

         # merging additional attributes provided by caller to the standard attributes
@@ -257,8 +257,8 @@

 Don't forget to fill /usr/share/freeradius/dictionary.mikrotik with the following attributes:

-ATTRIBUTE       Mikrotik-Wireless-VlanID                26      integer
-ATTRIBUTE       Mikrotik-Wireless-VlanIDType            27      integer
+ATTRIBUTE       Mikrotik-Wireless-VLANID                26      integer
+ATTRIBUTE       Mikrotik-Wireless-VLANID-Type           27      integer

 =cut

@@ -277,8 +277,8 @@
     my $role = "";
     if ( (!$args->{'wasInline'} || ($args->{'wasInline'} && $args->{'vlan'} != 0) ) && isenabled($self->{_VlanMap})) {
         $radius_reply_ref = {
-            'Mikrotik-Wireless-VlanID' => $args->{'vlan'},
-            'Mikrotik-Wireless-VlanIDType' => "0",
+            'Mikrotik-Wireless-VLANID' => "$args->{'vlan'}",
+            'Mikrotik-Wireless-VLANID-Type' => "0",
         };
     }

</pre>

**Comment by julsemaan** [comment]
I'm guessing the module must have worked previously for the RADIUS disconnect so IDK if we'll maybe need 2 modules, one for the newest version/hardware, one for the oldest.

From what I recall, @fdurand did the support for that equipment so I'll defer to him for how we'll handle that

**Comment by julsemaan** [comment]
I addressed the part about the VLAN being a number, left out the disconnect part so @fdurand can provide feedback on the proper resolution

**Comment by bbs2web** [comment]
Wow, super impressed with the quick feedback!
MikroTik provide free software update to all their products and the highly publicised vulnerability in RouterOS prior to v6.42.1 should have most users running a revision which works with the changes suggested above.
MikroTik do however provide CAPsMAN, as centrally managed AP infrastructure, where the RADIUS disconnect messages may require a different format. I however do not see anything in the MikroTik Wiki (https://wiki.mikrotik.com/wiki/Manual:CAPsMAN) indicating this.

Our deployment was tested to be fully functional with dynamic VLAN assignment, RADIUS disconnect and Firewall SSO integration with Check Point's Identity Awareness blade. Not sure if it's standard, but the MikroTik devices transmit the inner EAP username (EAP-TLS with MS-CHAPv2) with the IP in RADIUS accounting packets so single sign in is working perfectly.

**Comment by bbs2web** [comment]
Comments pertaining to the RADIUS disconnect functionality in Mikrotik.pm indicates that this was tested with RouterOS v6.18 and not working. Most people are most probably using the SSH method of disconnecting users.

Sending the MAC address with colons as the 'User-Name', instead of 'Calling-Station-Id', kicks users off when established using either EAP or MAC based authentication.
