### ISSUE TITLE
[PF 9.0.1] Firewall "SSO on access reevaluation" not working

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4638]
Enabling the option to send a RADIUS accounting packet to a Check Point firewall on access re-evaluation is not working. Only the "SSO on accounting" is working as expected.

Have temporarily set our wireless APs to send accounting information every minute, so that the firewall is informed of the association between the IP and MAC address.

**Comment by julsemaan** [comment]
We'll need the content of packetfence.log while you're expecting the packet to be sent

Also, we'll need the pf.conf and firewall_sso.conf from /usr/local/pf/conf/

**Comment by julsemaan** [comment]
Just tested in devel and it did work fine so we'll wait on the data requested above

**Comment by bbs2web** [comment]
Apologies about the long delay, trying to obtain debug logs during the day was frustrating due to the amount of chatter in the logs. The attached should be a clean log records detailing:

- Node changed to be unregistered without role (device kicked off WiFi)
- Device reconnects to 'Syrex WiFi' and gets placed in registration VLAN 666.
- Accept AUP which re-uses dot1x credentials to register device.
- Device kicked off registration VLAN so that it reconnects to staff VLAN

[packetfence.log](https://github.com/inverse-inc/packetfence/files/3374502/packetfence.log)

**Comment by bbs2web** [comment]
Herewith log entries when I simply cycle wireless on a mobile device:

<pre>
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] handling radius autz request: from switch_ip => (100.127.255.10), connection_type => Wireless-802.11-EAP,switch_mac => (6e:3b:6b:18:bc:0e), mac => [64:a2:f9:1c:32:de], port => 0, username => "davidh", ssid => Syrex WiFi (pf::radius::authorize)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] handling radius autz request: from switch_ip => (100.127.255.10), connection_type => Wireless-802.11-EAP,switch_mac => (6e:3b:6b:18:bc:0e), mac => [64:a2:f9:1c:32:de], port => 0, username => "davidh", ssid => Syrex WiFi (pf::radius::authorize)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Instantiate profile Wireless_802.1x (pf::Connection::ProfileFactory::_from_profile)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Found authentication source(s) : 'syrexad_users' for realm 'null' (pf::config::util::filter_authentication_sources)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Using sources syrexad_users for matching (pf::authentication::match2)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) ERROR: [mac:64:a2:f9:1c:32:de] Error binding: 'Broken pipe' (pf::LDAP::log_error_msg)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) WARN: [mac:64:a2:f9:1c:32:de] [syrexad_users] Unable to connect to ad.lair.co.za (pf::Authentication::Source::LDAPSource::_connect)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) ERROR: [mac:64:a2:f9:1c:32:de] [syrexad_users] Unable to connect to any LDAP server (pf::Authentication::Source::LDAPSource::_connect)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Username was NOT defined or unable to match a role - returning node based role 'staff' (pf::role::getRegisteredRole)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] PID: "davidh", Status: reg Returned VLAN: (undefined), Role: staff (pf::role::fetchRoleForNode)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) WARN: [mac:64:a2:f9:1c:32:de] No parameter staffVlan found in conf/switches.conf for the switch 100.127.255.10 (pf::Switch::getVlanByName)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] (100.127.255.10) Returning ACCEPT with VLAN 0 and role  (pf::Switch::Mikrotik::returnRadiusAccessAccept)
Jul  9 21:31:46 packetfence2 pfqueue: pfqueue(2360) INFO: [mac:unknown] undefined source id provided (pf::lookup::person::lookup_person)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:1c:ae:5d:d6:d0] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Instantiate profile Wireless_802.1x (pf::Connection::ProfileFactory::_from_profile)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Found authentication source(s) : 'syrexad_users' for realm 'null' (pf::config::util::filter_authentication_sources)
Jul  9 21:31:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Using sources syrexad_users for matching (pf::authentication::match2)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) ERROR: [mac:64:a2:f9:1c:32:de] Error binding: 'Broken pipe' (pf::LDAP::log_error_msg)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) WARN: [mac:64:a2:f9:1c:32:de] [syrexad_users] Unable to connect to ad.lair.co.za (pf::Authentication::Source::LDAPSource::_connect)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) ERROR: [mac:64:a2:f9:1c:32:de] [syrexad_users] Unable to connect to any LDAP server (pf::Authentication::Source::LDAPSource::_connect)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] Username was NOT defined or unable to match a role - returning node based role 'staff' (pf::role::getRegisteredRole)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] PID: "davidh", Status: reg Returned VLAN: (undefined), Role: staff (pf::role::fetchRoleForNode)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) WARN: [mac:64:a2:f9:1c:32:de] No parameter staffVlan found in conf/switches.conf for the switch 100.127.255.10 (pf::Switch::getVlanByName)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:a2:f9:1c:32:de] (100.127.255.10) Returning ACCEPT with VLAN 0 and role  (pf::Switch::Mikrotik::returnRadiusAccessAccept)
Jul  9 21:31:46 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:64:1c:ae:5d:d6:d0] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)
Jul  9 21:31:46 packetfence2 pfqueue: pfqueue(2360) INFO: [mac:unknown] undefined source id provided (pf::lookup::person::lookup_person)</pre>

**Comment by julsemaan** [comment]
It looks like when the device gets reevaluated it switches VLAN, if that is the case the SSO cannot occur correctly because PacketFence doesn't know about the new IP address. That mode is made for cases where you're doing inline or web-auth. If you're doing VLAN enforcement you'll either want to get PacketFence to see the DHCP traffic of your network or enable 'SSO on Accounting' and 'Update the iplog using the accounting'. That should probably do what you expect including handling the case where you disconnect and reconnect a device from the wireless. Should you choose this option, make sure to disable 'SSO on access reevaluation' so it doesn't interfere with the accounting triggered SSO

**Comment by bbs2web** [comment]
Many thanks and apologies for wasting your time. I incorrectly assumed that 'SSO on access reevaluation' would trigger when devices connected to the network and their role was evaluated.
