### ISSUE TITLE
Web Admin: Can't open the Captive portal section

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4646]
The logs show:

````
ERROR pfperl-api(303): Can't use string ("20s") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 787.
                                                            (Mojolicious::Plugin::DefaultHelpers::_development)
````

**Comment by tech62** [comment]
I've encountered the bug `packetfence: ERROR pfperl-api(10413): Can't use string ("5s") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 787.
`
PacketFence 9.0.1

I've tried /usr/local/pf/bin/pfcmd configreload hard and test with a reboot, no effect the bug persist

**Comment by tech62** [comment]
I've remove the value of "network_detection_initial_delay" in the /usr/local/pf/conf/pf.conf.default.
Do a  /usr/local/pf/bin/pfcmd configreload hard and the api error disappeared
