### ISSUE TITLE
[PF 9.0.1] Unable to enable Fingerbank device change detection

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4648]
Compliance, Device change detection does not alter any files in /usr/local/pf/conf nor /usr/local/fingerbank/conf/fingerbank.conf.

Moving the slider to enable the function and then saving initially appears to work but refreshing the page shows it still being disabled.

Fingerbank API profile shows statistics so it itself appears to be functional. For example:
483 total number of requests
1 hourly request
343 monthly requests
20 contributed combinations

**Comment by julsemaan** [comment]
Could you provide the content of pf.conf after enabling the flag in "Device change detection"

If you say that its not being taken into consideration after refreshing I'm guessing it won't be enabled there but I just want to confirm that so it can be assigned to the right person

**Comment by bbs2web** [comment]
Nothing changes in pf.conf when I try to change the option via the web interface. I manually added the following in to pf.conf but it still shows as disabled in the GUI:

<pre>[fingerbank_device_change]
enable=enabled</pre>

Got the structure from pf.conf.default:
<pre>[fingerbank_device_change]
#
# fingerbank_device_change.enable
#
# Whether or not the Fingerbank device change feature is enabled
enable=disabled</pre>

Refreshing the GUI after trying to manually enable it still has it showing as being disabled though.

**Comment by bbs2web** [comment]
The functionality is however working, I have a closed 'Fingerbank device class change' security event.

**Comment by julsemaan** [comment]
@satkunas, can you look at why the parameter isn't sticking when enabling it?

**Comment by julsemaan** [comment]
This needs to go in maintenance/9.0 and maintenance/9.1
