### ISSUE TITLE
WMI security events not trigger in Pf 9.0.1

### ISSUE THREAD

**Issue by lazypaul** [inverse-inc/packetfence#4649]
Problem 1 : Packetfence 9.01 can  show wmi tab in wmi rule (old admin, new ui not show) , but not trigger any security events?  

On the wmi tab, I can see the who is loggin , what software install, what processes running, but can't trigger any security events. How to trigger security events auto ? 
 

[3000006]
priority=9
actions=email_admin,reevaluate_access,log
window=
max_enable=0
desc=Team viewer
enabled=Y
access_duration=12h
grace=1s
button_text=Enable Network again
trigger=internal::789123

[3000007]
priority=9
trigger=internal::789124
actions=email_admin,reevaluate_access,log
window=
max_enable=0
desc=IPG
enabled=Y
access_duration=12h
grace=1s
button_text=Enable Network again

[3000008]
priority=9
trigger=internal::789125
actions=email_admin,reevaluate_access,log
window=
max_enable=0
desc=Antivirus Not Run
enabled=Y
access_duration=12h
grace=1s
button_text=Enable Network again

For Packetfence 9.0.1 not work , then I install packetfence pf 8.3,  there comes  
Problem 2:  Packetfence not show wmi tab on noed wmi rules , it is a windows os device, not like 9.0.1 show wmi tab on wmi rules , and also not trigger and security events. 
Violations not trigger ? why 
 

[3000006]
priority=1
trigger=internal::789123
actions=email_admin,reevaluate_access,log
window=
desc=teamviewer installed
enabled=Y
access_duration=12h
max_enable=30

[3000007]
priority=1
trigger=internal::789124
actions=email_admin,reevaluate_access,log
window=0s
desc=IPG not running
access_duration=12h
delay_by=
grace=
enabled=Y

[3000008]
priority=1
trigger=internal::789125
actions=email_admin,reevaluate_access,log
window=
desc=AntiVirus Not install
enabled=Y
access_duration=12h
delay_by=
grace=120s
~

**Comment by julsemaan** [comment]
That's more a configuration question for the mailing list than a bug

**Comment by lazypaul** [comment]
> 
> 
> That's more a configuration question for the mailing list than a bug

But, had already difined the security events, nothing trigger , not a bug ?

**Comment by nvyao** [comment]
> > That's more a configuration question for the mailing list than a bug
> 
> But, had already difined the security events, nothing trigger , not a bug ?

Hi man，Have you solved the problem yet？

**Comment by lazypaul** [comment]
no do not slove


发自我的iPhone

在 2020年7月14日，19:00，nvyao <notifications@github.com> 写道：

﻿

That's more a configuration question for the mailing list than a bug

But, had already difined the security events, nothing trigger , not a bug ?

Hi man，Have you solved the problem yet？
