### ISSUE TITLE
registration.range parameter does not exist anymore

### ISSUE THREAD

**Issue by canepan** [inverse-inc/packetfence#465]
I followed UPGRADE.asciidoc, from 4.1.0 to 4.7.0
(it worked up to 4.6.1, which I did about 1 month ago).
Upon starting service, I get:

> FATAL - unknown configuration parameter registration.range if you added the parameter yourself make sure it is present in conf/documentation.conf
> I commented out the line, and everything works now (I did not find an alternative configuration option).
> I think it should be mentioned in the upgrade manual

**Comment by julsemaan** [comment]
This parameters doesn't exist anymore. Also these questions should be posted to the PacketFence mailing list : https://lists.sourceforge.net/lists/listinfo/packetfence-users

**Comment by canepan** [comment]
This was not a question: I solved my problem, but UPGRADE.asciidoc should be updated

Nicola

-----Original Message-----

**Comment by julsemaan** [comment]
Good point, just added a note for the 4.1.0 -> 4.2.0 upgrade
