### ISSUE TITLE
[PF 9.0.1] Nodes location summary date format inconsistent

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4652]
The start and end times display dates in different formats, when reviewing a node's location history.

ie:
Start Time: 2019-07-03 07:35:40
End Time: 07/03/19 07:37 am

**Comment by julsemaan** [comment]
@satkunas, can you look into that ?

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/96cce93d4db30376acebd8e9f2f3cb9b76c155d7
