### ISSUE TITLE
[PF 9.0.1] Reviewing devices for DOMAIN\user shows 'no devices found'

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4654]
Viewing nodes' details shows it being owned by eg DOMAIN-01\davidh but viewing the user's device tab displays an error that no devices could be found.

Perhaps the domain separator '\\' isn't escaped out on the query?

PS: This works fine on users where the mobile devices connected using WPA2 Enterprise (eg Android) using just the username. Going to nodes and searching for eg davidh shows 4 nodes , 1 Android owned by 'davidh' and 3 Windows workstations owned by 'DOMAIN-01\davidh'. Viewing devices for user 'davidh' shows the Android node but no devices appear when reviewing the 'DOMAIN-01\davidh' user.

**Comment by julsemaan** [comment]
Can you try applying the maintenance patches (/usr/local/pf/addons/pf-maint.pl)

You may have to run it twice if you're running a pristine 9.0.1 since that script will get patched through the first call

**Comment by bbs2web** [comment]
Many thanks, I ran the update thrice and then restarted the system as a whole. Restarted my laptop which initially reconnects using machine authentication and thereafter using my Windows login credentials.
When I navigate to users, search for my account and view devices associated with DOMAIN-01\davidh it displays 'No devices found' although I can search for my username in the nodes view and can then find my laptop.

Owner: DOMAIN-01\davidh
Machine account: host/Laptop-DavidH.ad.lair.co.za

**Comment by julsemaan** [comment]
Seems like the escaping was fixed for when a user is being viewed but not when we query the nodes of the user. Will investigate

**Comment by julsemaan** [comment]
Should be fixed now if you run pf-maint.pl again and restart pfperl-api

Let me know if it doesn't work and we'll reopen this

**Comment by bbs2web** [comment]
Working perfectly, many thanks!

**Comment by bbs2web** [comment]
It appears the '/' in queries may also not be getting escaped. If I search for 'david' in nodes it shows a device registered using the AD machine account 'host/Laptop-DavidH.ad.lair.co.za' but displaying devices for this user reports no devices having been found.

Node information also shows no computer name:

Owner: host/Laptop-DavidH.ad.lair.co.za
Computer Name: <blank>
Machine Account: host/Laptop-DavidH.ad.lair.co.za
