### ISSUE TITLE
[PF 9.0.1] RADIUS accounting generates 'fingerbank-collector: Couldn't extract IP/MAC from packet'

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4658]
We are using RADIUS accounting for SSO (Single Sign On) with a Check Point firewall and it's working perfectly. We however observe the following messages being logged in packetfence.log:

<pre>
Jul 10 14:25:09 packetfence2 fingerbank-collector[1787]: Couldn't extract IP/MAC from packet
Jul 10 14:25:09 packetfence2 fingerbank-collector: Couldn't extract IP/MAC from packet
</pre>

WiFi APs are generating RADIUS accounting packets which are being sent to Packet Fence and this is correctly sending subsequent RADIUS accounting packets to the firewall to associate IPs with AD accounts. We have the following options enabled:
- SSO on accounting
- Update the iplog using the accounting
- Close locationlog on accounting stop

The errors recorded above correlate to the following RADIUS accounting packet having been received by the WiFi AP, Packet Fence transmitting a RADIUS accounting packet to the firewall and the relevant acknowledgements of those packets.

<pre>
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000       192.168.4.26          192.168.20.3          RADIUS   321    Accounting-Request id=208

Frame 1: 321 bytes on wire (2568 bits), 321 bytes captured (2568 bits)
Ethernet II, Src: ba:65:72:7e:65:bd (ba:65:72:7e:65:bd), Dst: 5e:03:75:21:e3:09 (5e:03:75:21:e3:09)
Internet Protocol Version 4, Src: 192.168.4.26, Dst: 192.168.20.3
User Datagram Protocol, Src Port: 42995, Dst Port: 1813
RADIUS Protocol
    Code: Accounting-Request (4)
    Packet identifier: 0xd0 (208)
    Length: 279
    Authenticator: 464d8418164c78b2704fbcdfb0b2655d
    [The response to this request is in frame 4]
    Attribute Value Pairs
        AVP: t=Service-Type(6) l=6 val=Framed(2)
        AVP: t=NAS-Port-Id(87) l=15 val=wlan2 - 5 GHz
        AVP: t=NAS-Port-Type(61) l=6 val=Wireless-802.11(19)
        AVP: t=User-Name(1) l=8 val=Leenuv
        AVP: t=Acct-Session-Id(44) l=10 val=8200134c
        AVP: t=Acct-Multi-Session-Id(50) l=61 val=CC-2D-E0-C5-2C-1A-C8-D0-83-36-43-45-82-00-00-00-00-00-0F-EF
        AVP: t=Calling-Station-Id(31) l=19 val=C8-D0-83-36-43-45
        AVP: t=Called-Station-Id(30) l=30 val=CC-2D-E0-C5-2C-1A:Syrex WiFi
        AVP: t=Acct-Authentic(45) l=6 val=RADIUS(1)
        AVP: t=Acct-Status-Type(40) l=6 val=Interim-Update(3)
        AVP: t=Acct-Session-Time(46) l=6 val=4440
        AVP: t=Acct-Input-Octets(42) l=6 val=840742
        AVP: t=Acct-Input-Gigawords(52) l=6 val=0
        AVP: t=Acct-Input-Packets(47) l=6 val=4505
        AVP: t=Acct-Output-Octets(43) l=6 val=2405779
        AVP: t=Acct-Output-Gigawords(53) l=6 val=0
        AVP: t=Acct-Output-Packets(48) l=6 val=5029
        AVP: t=Framed-IP-Address(8) l=6 val=192.168.5.73
        AVP: t=NAS-Identifier(32) l=32 val=Projects Office - Temporary AP
        AVP: t=Acct-Delay-Time(41) l=6 val=0
        AVP: t=NAS-IP-Address(4) l=6 val=192.168.4.26

No.     Time           Source                Destination           Protocol Length Info
      2 0.077796       192.168.20.3          100.127.254.1         RADIUS   143    Accounting-Request id=245

Frame 2: 143 bytes on wire (1144 bits), 143 bytes captured (1144 bits)
Ethernet II, Src: 5e:03:75:21:e3:09 (5e:03:75:21:e3:09), Dst: ba:65:72:7e:65:bd (ba:65:72:7e:65:bd)
Internet Protocol Version 4, Src: 192.168.20.3, Dst: 100.127.254.1
User Datagram Protocol, Src Port: 53921, Dst Port: 1813
RADIUS Protocol
    Code: Accounting-Request (4)
    Packet identifier: 0xf5 (245)
    Length: 101
    Authenticator: 90e17f50485b55bb867d90c1d55322bf
    [The response to this request is in frame 3]
    Attribute Value Pairs
        AVP: t=Calling-Station-Id(31) l=14 val=PACKETFENCE2
        AVP: t=Acct-Status-Type(40) l=6 val=Start(1)
        AVP: t=Acct-Session-Id(44) l=22 val=acct_pf-PACKETFENCE2
        AVP: t=User-Name(1) l=8 val=Leenuv
        AVP: t=Session-Timeout(27) l=6 val=2587560
        AVP: t=Called-Station-Id(30) l=19 val=00:11:22:33:44:55
        AVP: t=Framed-IP-Address(8) l=6 val=192.168.5.73

No.     Time           Source                Destination           Protocol Length Info
      3 0.079506       100.127.254.1         192.168.20.3          RADIUS   62     Accounting-Response id=245

Frame 3: 62 bytes on wire (496 bits), 62 bytes captured (496 bits)
Ethernet II, Src: ba:65:72:7e:65:bd (ba:65:72:7e:65:bd), Dst: 5e:03:75:21:e3:09 (5e:03:75:21:e3:09)
Internet Protocol Version 4, Src: 100.127.254.1, Dst: 192.168.20.3
User Datagram Protocol, Src Port: 1813, Dst Port: 53921
RADIUS Protocol
    Code: Accounting-Response (5)
    Packet identifier: 0xf5 (245)
    Length: 20
    Authenticator: 4b29964d190aa243a73c94a1f9c82f69
    [This is a response to a request in frame 2]
    [Time from request: 0.001710000 seconds]

No.     Time           Source                Destination           Protocol Length Info
      4 0.095861       192.168.20.3          192.168.4.26          RADIUS   77     Accounting-Response id=208

Frame 4: 77 bytes on wire (616 bits), 77 bytes captured (616 bits)
Ethernet II, Src: 5e:03:75:21:e3:09 (5e:03:75:21:e3:09), Dst: ba:65:72:7e:65:bd (ba:65:72:7e:65:bd)
Internet Protocol Version 4, Src: 192.168.20.3, Dst: 192.168.4.26
User Datagram Protocol, Src Port: 1813, Dst Port: 42995
RADIUS Protocol
    Code: Accounting-Response (5)
    Packet identifier: 0xd0 (208)
    Length: 35
    Authenticator: aff8a94665826c3675a72c6930ea97be
    [This is a response to a request in frame 1]
    [Time from request: 0.095861000 seconds]
    Attribute Value Pairs
        AVP: t=Reply-Message(18) l=15 val=Accounting ok
[radius_accounting_generates_fingerbank-collector_error.txt](https://github.com/inverse-inc/packetfence/files/3377583/radius_accounting_generates_fingerbank-collector_error.txt)
</pre>

**Comment by julsemaan** [comment]
Looks like an issue in the RADIUS handler of the collector.

@fdurand would you be able to look into that ?

**Comment by fdurand** [comment]
fingerbank-collector doesn't log the correct error, i fixed it in the code, we need to have a new binary.
