### ISSUE TITLE
[PF 9.0.1] RADIUS accounting iplog updates start and end with each update

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#4659]
We are using RADIUS accounting for SSO (Single Sign On) with a Check Point firewall and it's working perfectly. We have the following options enabled:
- SSO on accounting
- Update the iplog using the accounting
- Close locationlog on accounting stop

The IPv4 node history however starts and ends with each accounting update (interval: 1m):
<pre>
IP Address    | Start Time        | End Time
192.168.5.179 | 07/10/19 03:00 pm | Never
192.168.5.179 | 07/10/19 02:59 pm | 07/10/19 03:00 pm
192.168.5.179 | 07/10/19 02:58 pm | 07/10/19 02:59 pm
192.168.5.179 | 07/10/19 02:57 pm | 07/10/19 02:58 pm
</pre>

I presume this is due to the Check Point firewall integration module not supporting updates and subsequently calling a start/stop action each time (although the accounting update to the firewall is actually an update). The following from packetfence.log indicates updates not being authorized:
<pre>
Jul 10 07:58:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) WARN: [mac:60:30:d4:8b:18:96] Firewall SSO Notify (pf::api::firewallsso_accounting)
Jul 10 07:58:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:60:30:d4:8b:18:96] Sending a firewall SSO 'Update' request for MAC '60:30:d4:8b:18:96' and IP '192.168.5.49' (pf::firewallsso::do_sso)
Jul 10 07:58:45 packetfence2 packetfence_httpd.aaa: httpd.aaa(1775) INFO: [mac:60:30:d4:8b:18:96] Request to /api/v1/firewall_sso/update is unauthorized, will perform a login (pf::api::unifiedapiclient::call)
</pre>

**Comment by julsemaan** [comment]
You can enable the cache timeout in the firewall configuration in PacketFence so that it isn't sent every time we receive a packet and you can control the frequency.

BTW, I don't suggest using an interim update of 1 min for accounting, PF will simply not scale for a large deployment with that setting.

A setting of ~1 hour is preferable

**Comment by bbs2web** [comment]
We do have firewall sso caching enabled of 30 minutes. Should the IPv4 history be updated with each accounting update though?
The most recent record always show no end date so shouldn't the RADIUS accounting update then ignore updating the IPv4 history until it changes?

ie: If accounting ip = last history ip, then skip ?

**Comment by julsemaan** [comment]
The ip4log was initially made to track leases so a new record gets created even if it doesn't change so that you can track the beginning and the end of a device leases.

The accounting update of the ip4log mimics the reception of a DHCP packet so uses the same logic currently
