### ISSUE TITLE
Switch group can't open 

### ISSUE THREAD

**Issue by lazypaul** [inverse-inc/packetfence#4661]
add a switch group name 2960, description 2960 , then after save in the old admin, it can't open, but can be opened in the new admin

2960 | 2960 | Cisco::Catalyst_2960 | Production

showing :  Error! error reading 2960 from the configuration

**Comment by julsemaan** [comment]
Try applying the maintenance branch using '/usr/local/pf/addons/pf-maint.pl'

I believe this has already been fixed in the latest patches
