### ISSUE TITLE
Missing Custom LDAP/RADIUS attributes in the authentications rules.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4665]
Adding custom attributes for RADIUS/LDAP doesn't allow you to use them in authentications rules 

**To Reproduce**
1. Go to 'Configuration -> System Configuration->Advanced'
2. Click on 'LDAP Attributes'
3. Add Zamattr
4. Go in 'Policies and access control->Authentication Sources->New internal source->LDAP'
5. Create a rule and search for Zamattr.

**Expected behavior**
We should be able to see the custom attribute Zamattr in the list.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version Version 75.0.3770.100 (Build officiel) (64 bits)

**Comment by julsemaan** [comment]
@satkunas 

Can you look at this, it makes some LDAP/AD source uneditable if they contain the custom LDAP attributes defined in pf.conf

**Comment by jrouzierinverse** [comment]
The Additional LDAP attribute are in the OPTIONS in the condition this seems to be a GUI issue.
