### ISSUE TITLE
Incorrect encoding in the db.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4669]
**Describe the bug**
Let's say you want to create a user João Conceição then in the db it will be encoded like this: JoÃ£o ConceiÃ§Ã£o

**To Reproduce**
1. Go to USer create
2. Create user : João Conceição
3. Go back in users tab
4. See the wrong encoding

**Expected behavior**
Should be encoded correctly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version Latest one

**Comment by jrouzierinverse** [comment]
To support this would need to move to use uf8mb4 encoding.
I would suggest doing this for the 11.0 release.
Since this requires a lot of database changes.

**Comment by jrouzierinverse** [comment]
This was fixed
