### ISSUE TITLE
Better upgrade sql for iplog

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#467]
Remove duplicate iplog entries in upgrade script.

**Comment by louismunro** [comment]
Better be careful with that.
Depending on the size of the iplog it might lock the table for a long time.

**Comment by jrouzierinverse** [comment]
Would it better to do a rename the old table create a new one.
The populate the new with the data from the old iplog.

rename iplog to iplog_old;
create iplog;
insert into iplog SELECT \* FROM iplog_old GROUP BY ip ORDER BY start_time DESC LIMIT 1;

**Comment by dwlfrth** [comment]
I'd simply go with truncate the table... it is not like we'd never done that...

**Comment by louismunro** [comment]
Agreed.  
What is there that we care about keeping in that table anyway?  

## 

LM

**Comment by dwlfrth** [comment]
We can move the existing table to some "temp" ones if someone wants to keep history, but outside than that... no need to hurt your brain on finding a solution to an issue we doesn't have.

**Comment by jrouzierinverse** [comment]
Works for me.
RENAME TABLE iplog to iplog_temp;
CREATE TABLE iplog ();

**Comment by louismunro** [comment]
Test it thoroughly first.  
There are limitations on names of things such as indexes in mysql that could mean we have to either delete them or rename them before we can create a new iplog table.

## 

LM
