### ISSUE TITLE
Cannot set dynamic unreg date in authentication source

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4672]
**Describe the bug**
Its impossible to set an action of "Unregistration date" with value "0-08-01" which would have the unreg date be August 1st of the current year. This works fine in the old admin

**To Reproduce**
1. Create an authentication source
2. Add an authentication rule with "Unregistration date" "0-08-01"
3. Attempt to save and you're not allowed

**Expected behavior**
Having 0 as the year in an unreg date should be valid

**Comment by satkunas** [comment]
There's currently an open issue with the flatpickr component used for the date/time input.

https://github.com/flatpickr/flatpickr/issues/1878

**Comment by julsemaan** [comment]
Can we get a workaround in place, seems the issue @satkunas opened on the @flatpickr repo didn't get any attention

**Comment by satkunas** [comment]
I bumped the issue. I'll wait patiently for another 24 hours. 

It looks like my issue w/ tail.datetime was addressed in their latest release. I'll attempt to revert back to this if flatpickr isn't resolved ASAP.

https://github.com/pytesNET/tail.DateTime/issues/35

**Comment by satkunas** [comment]
Moving milestone for future reevaluation.

**Comment by julsemaan** [comment]
@satkunas 
Can c811f36 be applied in maintenance/9.0+

**Comment by satkunas** [comment]
@julsemaan done

**Comment by extrafu** [comment]
@julsemaan and @satkunas we close it, we push it to v10.1 or we fix it in v10?

**Comment by julsemaan** [comment]
Pushed to 10.1, @satkunas can see if the upstream fix has been done, he did a workaround which is all we need for now I guess

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/93a56bae8c60d55c86b32844a7fe085fb0c6b42c
