### ISSUE TITLE
Allow to configure expiration of the API frontend token

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4677]
Currently, token expires after 15 minutes of inactivity which is more secure but also much different than what people were used to.

We should still have the more secure setting in place but also allow to override it in the configuration

**Comment by cgx** [comment]
Could also be useful to be able to change the *max expiration*, currently hardcoded to [12 hours](https://github.com/inverse-inc/packetfence/blob/devel/go/caddy/api-aaa/api-aaa.go#L76).
