### ISSUE TITLE
web admin: display a switches doesn't contain all roles

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4680]
In a setup with more than 20 roles (user defined) when you go in `Policies and Access Control -> Switches`, select a switch and go in tab `Roles`, only first 25 roles are displayed (user defined + defaults).

New web admin calls `api/v1/roles` only once even if response contains a `nextCursor` information.

**To Reproduce**
1. Use [roles.txt](https://github.com/inverse-inc/packetfence/files/3416234/roles.txt) file
2. `pfcmd configreload hard`
3. Go in `Roles` menu: you see all roles
4. Go in `Switches` menu, tab `Roles`: you didn't see the `role-21`, only the first 25 roles.

**Expected behavior**
All roles should be display in `Roles` tab of a switch.

**Additional context**

**Comment by satkunas** [comment]
Limit increased to 1000 with https://github.com/inverse-inc/packetfence/commit/9148ce399a622195e555c5f0018eb58f977f9085

**Comment by satkunas** [comment]
@nqb please test and close this issue if all OK.

**Comment by nqb** [comment]
On my side it works after `pf-maint`. Waiting feedback from a customer.

**Comment by nqb** [comment]
Work as expected, thanks @satkunas
