### ISSUE TITLE
Password of the day generates same password each time

### ISSUE THREAD

**Issue by smorhun** [inverse-inc/packetfence#4682]
**Describe the bug**
The "password of the day" is configured for password rotation of 24 hrs. Each day the email is sent with a generated password but it always the same.   

**To Reproduce**
1. Configure "Password of the Day" authentication source to rotate the password often.
2. Receive an email with a generated password

**Expected behavior**
Each time the password is generated and email is sent password should be different, but it stays the same.

** Server
PacketFence 9.0.1
CentOS 7

**Comment by nqb** [comment]
has been fixed see #4728
