### ISSUE TITLE
"Update Fingerbank DB" option is missing in New Admin UI

### ISSUE THREAD

**Issue by smorhun** [inverse-inc/packetfence#4683]
**Describe the bug**
In OLD Admin UI every Fingerbank configuration page includes "Update Fingerbank DB" under "Actions" dropdown.
That option is not available anywhere in New Admin UI 

**To Reproduce**
in Old Admin UI
1. Go to 'Configuration' -> 'Compliance' -> 'General settings'
2. Click on 'ACTION' dropdown
3. Select  'Update Fingerbank DB'

in New Admin UI
1. Go to 'Configuration' -> 'Compliance' -> 'General settings'
'Update Fingerbank DB' option is missing

**Expected behavior**
'Update Fingerbank DB' should be available in New Admin UI

**Server**
 - OS: CentOS 7
 - PacketFence 9.0.1

**Comment by julsemaan** [comment]
@jrouzierinverse will confirm the call exists, then assign @cgx or @satkunas to the issue when its done

**Comment by jrouzierinverse** [comment]
The new endpoint is POST /api/v1/fingerbank/update_upstream_db.
@satkunas have funn

**Comment by satkunas** [comment]
Button added in https://github.com/inverse-inc/packetfence/commit/e7e24481ab37dac0bfdb400c964f5de9ce4142be
