### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by gmcmpe** [inverse-inc/packetfence#4685]
**Describe the bug**
fingerbank-collector get pid=0 while its status seems disabled
haproxy-portal get pid=0 and its status seems stopped

**To Reproduce**
1-Set up packetfence via yum install -y https://packetfence.org/downloads/PacketFence/RHEL7/x86_64/RPMS/packetfencerelease-
1.2-7.el7.noarch.rpm
yum install --enablerepo=packetfence packetfence
2-Change Interfaces
![interfaces](https://user-images.githubusercontent.com/50031345/61854732-5f2cb080-aec7-11e9-8914-245c85f49a03.PNG)
3-Try to activate Fingerbank
Result: it doesnt get activated
4-Systemctl start packetfence-fingerbank-collector
Result:It doesnt start 
5-Restart the centos 7
6-Rest is described below
**Screenshots**
![PFSTA](https://user-images.githubusercontent.com/50031345/61796612-65228300-ae2e-11e9-9787-e1dd50580d21.PNG)
![wi1](https://user-images.githubusercontent.com/50031345/61796855-ef6ae700-ae2e-11e9-9f0d-0bf5619af3ff.PNG)
![wi2](https://user-images.githubusercontent.com/50031345/61796857-ef6ae700-ae2e-11e9-8b41-45b33b838228.PNG)

**Expected behavior**
Work the services below properly and in a healthy manner.
packetfence-haproxy-portal.service 
packetfence-fingerbank-collector.service

**Desktop (please complete the following information):**
OS: Centos 7
Browser: any 
Version : PacketFence 9.0.1

**Smartphone (please complete the following information):**

**Additional context**
![fingerbankerr](https://user-images.githubusercontent.com/50031345/61797118-7750f100-ae2f-11e9-8554-307b3d1af8fc.PNG)
![portal](https://user-images.githubusercontent.com/50031345/61797119-7750f100-ae2f-11e9-9d4b-5eb76c9ae9e3.PNG)

**Comment by nqb** [comment]
Hello,

In order to be able to reproduce, please provide us a [Minimal, Complete, and Verifiable example (MCVE)](https://stackoverflow.com/help/mcve)
