### ISSUE TITLE
Node import: Missing "Import all" option

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4687]
**Describe the bug**
There is no way to import all the nodes of a file through a simple button like there was before

**To Reproduce**
1. Try to import nodes with a large file (~1000 nodes)

**Expected behavior**
There should be an option to import all the nodes at once

**Comment by satkunas** [comment]
Dynamic page size added in https://github.com/inverse-inc/packetfence/commit/4077173b2e3e9a07992292e1f26e72b82ea75d98

**Comment by julsemaan** [comment]
Tried to import more than 1000 users (3800) and it made the page use 3GB of memory and eventually get killed. Didn't even get the chance to import the nodes, it crashed while I was selecting them

We'll definitely need an option to import the whole file that is more lightweight

**Comment by julsemaan** [comment]
Tried with 1000 and it got through some of it but eventually froze the whole page so it seems like although we can import more at the same time, you'd need to run your browser on this to get through it: https://www.itinstock.com/dell-poweredge-r810-4-x-8-core-xeon-l7555-512gb-ram---32-cores-in-2u-rack-server-34516-p.asp

**Comment by extrafu** [comment]
@lzammit Please test and close if all fine.

**Comment by lzammit** [comment]
Imported 10 000 nodes, works.
