### ISSUE TITLE
MAC addresses aren't cleaned during node import

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4688]
**Describe the bug**
The MAC addresses aren't cleaned in the node import which results in a PATCH on the uncleaned MAC (which fails), then a POST using the uncleaned MAC which can succeed but will fail if the MAC already exists.

**To Reproduce**
1. Go to node import
2. Import a file with uncleaned MACs (like 001122334455)

**Expected behavior**
The MAC addresses should be cleaned by the frontend while importing the CSV so that the API calls will all succeed

**Comment by satkunas** [comment]
Should be fixed with https://github.com/inverse-inc/packetfence/commit/57b51dc75549816609deb93de601de4c796058ca

**Comment by julsemaan** [comment]
Works fine on the latest maintenance
