### ISSUE TITLE
pfconfig db password

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#469]
change manually pf user db password in conf/pfconfig.conf

**Comment by rouzier** [comment]
Can you provide more detail?

**Comment by whitx** [comment]
When you upgrade, the db password of the user pf is not apply in conf/pfconfig.conf.
So if you start packetfence after an upgrade ReleaseVersion/DB, pfconfig is not connecting to the db.
For now we have to manually change pf's user password in conf/pfconfig.conf(after upgrade).

**Comment by extrafu** [comment]
try to boot.. woah! zammitbug!

**Comment by julsemaan** [comment]
This IMO is not a bug. It should be part of the upgrade guide 4.7.0 -> 5.0

Or as @extrafu said the solution would be to reboot

**Comment by louismunro** [comment]
It is going to be part of the guide.
I asked whit to add an issue so I don’t forget it  

## 

LM

**Comment by julsemaan** [comment]
Was added to upgrade guide, closing
