### ISSUE TITLE
Problem with deploy ZEN (9.0.1) with ESXi 6.7

### ISSUE THREAD

**Issue by soilsk** [inverse-inc/packetfence#4692]
Hi. When i deploy ZEN version of PF (v 9.0.1) in ESXi 6.7 (via web client) i get message: The provided manifest file is invalid: Invalid OVF manifest entry: .

SOLUTION for somebody with similiar problem: 
1. with OVFTool convert OVA to OVF
2. edit OVF with these steps: https://www.techcrumble.net/2018/04/vcenter-server-6-5-ovf-deployment-error-value_illegal-value-3-of-parent-element-does-not-refer-to-a-ref-of-type-diskcontrollerreference/
3. save
4. deploy

:)

**Comment by julsemaan** [comment]
I will check to adjust our OVF template and get this in our next ZEN release

**Comment by julsemaan** [comment]
I've adjusted the OVF template in our nightly ZEN. Could you try installing it from here:
https://sourceforge.net/projects/packetfence/files/PacketFence%20ZEN/nightly/PacketFence-ZEN-nightly.zip/download

I tested it on ESXi 6.0.0 and it worked fine as before

SIDE NOTE: It grew in size for a reason I'm still investigating but should work fine

If you confirm this works then I can include the fix in the next ZEN (likely 9.1)

**Comment by soilsk** [comment]
I think ESX 6.0 - 6.5 is fine with, but we use ESXi 6.7 and there is "something" different :)
Btw A few minutes ago i have download nightly ZEN from your link and the same error: The provided manifest file is invalid: Invalid OVF manifest entry: .

**Comment by julsemaan** [comment]
I've adjusted the OVF file to match the procedure you provided in the description

Could you validate that the OVF now matches the one you had that was valid after modifying it?

**Comment by soilsk** [comment]
In nightly version ? Because i tested and still the same message ...

**Comment by enkidushane** [comment]
Here's a diff of the changes I made to the box.ovf from today's nightly and it imports successfully into vcenter 6.7.  I didn't test to see if some subset of these changes were sufficient.
```
50c50
<         <rasd:Caption>SCSIController</rasd:Caption>
---
>         <rasd:Caption>SCSIController0</rasd:Caption>
52c52
<         <rasd:ElementName>SCSIController</rasd:ElementName>
---
>         <rasd:ElementName>SCSIController0</rasd:ElementName>
54,55c54,55
<         <rasd:ResourceSubType>PIIX4</rasd:ResourceSubType>
<         <rasd:ResourceType>5</rasd:ResourceType>
---
>         <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
>         <rasd:ResourceType>6</rasd:ResourceType>
59c59
<         <rasd:Caption>SCSIController</rasd:Caption>
---
>         <rasd:Caption>SCSIController1</rasd:Caption>
61c61
<         <rasd:ElementName>SCSIController</rasd:ElementName>
---
>         <rasd:ElementName>SCSIController1</rasd:ElementName>
63,64c63,64
<         <rasd:ResourceSubType>PIIX4</rasd:ResourceSubType>
<         <rasd:ResourceType>5</rasd:ResourceType>
---
>         <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
>         <rasd:ResourceType>6</rasd:ResourceType>
219c219
< </Envelope>                   
\ No newline at end of file
---
> </Envelope>
```

Note that this still doesn't boot (I think because the initrd doesn't support SCSI Controllers).  I got it to work by following steps 5 & 6 and then 10 and later from https://github.com/inverse-inc/packetfence/issues/2306#issuecomment-459933298 (that is, you don't strictly have to install the vmware tools and drivers).

And, even then, unless you're attaching this to a network with a DHCP server, it won't have an IP address (you'll have to manually edit /etc/sysconfig/network-scripts/ifcfg-eth0)

**Comment by soilsk** [comment]
Ok. Thanks.

**Comment by julsemaan** [comment]
A new way to build the ZEN is now used. I'll close this and reopen if you still fail to open ZEN 10.0.1 and above
