### ISSUE TITLE
No way to delete local combination in new GUI

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4693]
**Describe the bug**
There is no way to delete a local combination in the new GUI, only clone is available

**To Reproduce**
1. Create a local combination
2. Try to delete it

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/62052290-32d4a500-b1e3-11e9-904e-ee92cc5a37b0.png)

**Expected behavior**
Should be able to delete a local combination

**Comment by julsemaan** [comment]
This is on 9.0.1 with latest patches

**Comment by satkunas** [comment]
Due to scope not being `local`.

@julsemaan recommends that we deprecate scope and statically use `local` in combinations and user agents.
