### ISSUE TITLE
Enabling "register" action in the new security events GUI doesn't enable it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4694]
**Describe the bug**
If you enable the "Register" action in a security event, it doesn't add it to the list of actions.

**To Reproduce**
1. Create a new security event with action "Register"
2. View the security event and the action isn't enabled anymore
3. View the conf file and the action isn't there (action list is empty)

**Expected behavior**
Enabling this should enable the action in the list

**Comment by julsemaan** [comment]
This is 9.0.1 with latest patches

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/7ee12de4bc302665550467dbf9a2fd9ae81f4b15

**Comment by julsemaan** [comment]
Works!
