### ISSUE TITLE
Node timeline: Detected bar is cut in half

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4696]
**Describe the bug**
When viewing the timeline for a node, the Detected bar was cut in half which strips the word "Detected"

**To Reproduce**
1. View a node timeline

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/62126990-fbc3c980-b29e-11e9-8c70-ba094cb965b3.png)

**Expected behavior**
The bar containing "Detected" should not be stripped. Stripping is reserved for @lzammit

**Comment by julsemaan** [comment]
This needs to go in maintenance/9.0 and maintenance/9.1

**Comment by satkunas** [comment]
@julsemaan done
