### ISSUE TITLE
Creating a new switch shows wrong 'Role by VLAN ID' value

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4699]
**Describe the bug**
When creating a new switch on a brand new PF install 'Role by VLAN ID' shows as disabled when creating the switch but its actually enabled (through the inheritance of the default value). After saving if you refresh the switch you actually see the right value (enabled)

**To Reproduce**
1. Create a new switch with default values (I had to set IP and description)
2. Before saving, validate 'Role by VLAN ID' is disabled
3. Save the switch
4. Reload the page
5. The switch will now have 'Role by VLAN ID' which is the value its inheriting from default

**Expected behavior**
During creation the field should display the inherited value (enabled) using a 3 state checkbox like the other fields (ex: External Portal Enforcement)

**Comment by satkunas** [comment]
Meta options `default` value is `null`. Changing this to `'Y'` in the payload will fix this problem. Reassigning.

`/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/switches | jq '.meta.VlanMap.default'`

**Comment by jrouzierinverse** [comment]
The inherited value is in placeholder not the default.

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/a1531719e7c4da3893def35ab0efae81a07402c0
