### ISSUE TITLE
Add note/button to restart service(s) after editing a cert

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4700]
**Describe the bug**
When we update an HTTP or RADIUS cert there is no note to restart the appropriate services

**Expected behavior**
Should have a note on restarting the services:
- HTTP: httpd.admin + haproxy-portal
- RADIUS: radiusd

**Comment by cgx** [comment]
Looks like this was [fixed](b6b3088e3c834972543182bfcee0deb8b99bf76b).
