### ISSUE TITLE
Error when viewing user in new admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4703]
**Describe the bug**
Tried to view a user with a fancy name on a PF deployment and got an error with the user not being found

**To Reproduce**
1. Have a user named `$weed$#@gmail.com`
2. Try to view him
3. Get a not found error when the details open

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/62226519-54bb5c80-b388-11e9-8ca6-4331ef0104e0.png)

**Expected behavior**
Any user should be viewable

**Comment by jrouzierinverse** [comment]
Related to #4710
