### ISSUE TITLE
Admin - Login modal retains previous password

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4705]
**Describe the bug**
When the session expires on the the web admin it produces a login modal on top of the current page instead of redirecting the user to a separate login screen. When the session expires a 2nd time the password from the previous login is retained and not cleared, thus only requiring a button-press to re-login.

**Expected behavior**
The password field should be cleared as soon as the form is submitted - whether the login was successful or not.

**Comment by cgx** [comment]
Are you sure this is not the result of your browser's password manager?

**Comment by cgx** [comment]
@satkunas Is this issue still relevant?
