### ISSUE TITLE
Auto-register overwrites note for nodes

### ISSUE THREAD

**Issue by joachimtingvold** [inverse-inc/packetfence#4718]
**Describe the bug**
If you register a node manually (by entering MAC-address and assigning role) via the web-GUI, and set a note in the `Notes` field, that will be overwritten next time that node connects via MAB when having auto-register enabled.

**To Reproduce**
1. Register node manually. Add note.
2. Connect the node, authenticated via MAB.
3. `Notes` field now just says `AUTO-REGISTERED`, and has overwritten the previous value.

**Expected behavior**
`AUTO-REGISTERED` should only be written in the `Notes` field if the field is empty. The field should not be touched for already registered nodes.

If need be, the text can be added to whatever value the field has, or similar, but the original value needs to be kept.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Browser: Chrome, Firefox, Safari
 - Version: Chrome 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

PF version (ZEN);
```
[root@packetfence1 ~]# /usr/local/pf/bin/pfcmd version
PacketFence 9.0.1
```

**Comment by joachimtingvold** [comment]
This also seems to be the case with the `role` field sometimes (i.e. set the role upon first registration, and when the device connects, the `role` field gets set to `No Role`). Have to do some more testing to confirm that.

**Comment by julsemaan** [comment]
We should simply remove the note AUTO-REGISTERED, this was a hack for when we didn't have the autoreg column AFAIK
