### ISSUE TITLE
Setting snmp bounce duration in main GUI does not work

### ISSUE THREAD

**Issue by apkt** [inverse-inc/packetfence#4724]
PF9.0.0 - Standalone.

Adding a bounce duration under SNMP settings in GUI yields a NULL value in the pf.conf file and consequently the 'sleep' function does not work ands the port is bounced too quickly for a wired connected device (Windows 10) to register and perform a new DHCP request on the newly assigned VLAN:-

Aug 15 13:43:09 PacketFence-ZEN pfqueue: pfqueue(29330) WARN: [mac:10:7d:1a:18:71:33] Argument "" isn't numeric in sleep at /usr/local/pf/lib/pf/Switch.pm line 1333.
Aug 15 13:43:09 PacketFence-ZEN pfqueue: Argument "" isn't numeric in sleep at /usr/local/pf/lib/pf/Switch.pm line 1333.

Adding a value manually (10) in the pf.conf file fixes the issue.

**Comment by apkt** [comment]
System 'checkup' complains at not having a qualifier in the bounce field (ie you have to put 10s):-

[root@PacketFence-ZEN logs]# pfcmd checkup
Checking configuration sanity...
WARNING - pf.conf value snmp_traps.bounce_duration does not explicity define interval (eg. 7200s, 120m, 2h) - please define it before running packetfence
[root@PacketFence-ZEN logs]# 

but if you do this then the port reset call fails:-

Aug 16 08:07:56 PacketFence-ZEN packetfence: WARN pfperl-api(4655): Argument "" isn't numeric in sleep at /usr/local/pf/lib/pf/Switch.pm line 1333.

The two sections seem to be demaning mutually exclusive requirements.

**Comment by julsemaan** [comment]
Tried to replicate and all is good now. Reopen if necessary.
