### ISSUE TITLE
Switch port is no longer shown in Location tab

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#4731]
**Describe the bug**
Switch port is shown in the old GUI, but not new in the Location tab (or the Info tab) (old GUI shows something like Port: 294 (J6))

**To Reproduce**
1. Search for a MAC address
2. Click Location tab
3. Notice switch port information is not shown

**Screenshots**
![new](https://user-images.githubusercontent.com/382007/63469734-8cba3a80-c430-11e9-89de-f4742fb35e8c.JPG)
![old](https://user-images.githubusercontent.com/382007/63469736-8cba3a80-c430-11e9-9114-7f1fcf42222c.JPG)
![old1](https://user-images.githubusercontent.com/382007/63469737-8cba3a80-c430-11e9-8338-6de800098eec.JPG)

**Expected behavior**
Switch port should be shown in new GUI on Location tab (and possibly Info tab)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809

**Comment by extrafu** [comment]
@satkunas Please have a look at this.

**Comment by satkunas** [comment]
Added in `devel` w/ https://github.com/inverse-inc/packetfence/commit/899efcac037e5fb02f65296b8edac329f9479418

Added in `maintenance/9.0` w/ https://github.com/inverse-inc/packetfence/commit/06fbcf33f8796b9eb264d6424d9cb8e29f17af26 and https://github.com/inverse-inc/packetfence/commit/a5babef1b16662e66cf4310dfd35d297a1689a36
