### ISSUE TITLE
pfhttpd not working on RedHat 7.7

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4732]
After a fresh install on a RedHat 7.7, we noticed that some services are stopped:
- packetfence-api-frontend.service
- packetfence-httpd.dispatcher.service
- packetfence-pfipset.service
- packetfence-pfsso.service

**To Reproduce**
1. Install a RedHat 7.7
2. Install PacketFence
3. `pfcmd service pf status`

=> See services stopped.

**Expected behavior**
Services started.

**Additional context**
Issue is caused by the fact that `pfhttpd` use `libipset.so.11` and this file is missing on RedHat 7.7 ([ipset has been upgraded to 7.1](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.7_release_notes/index#BZ-1649080)):

```console
# ldd /usr/local/pf/sbin/pfhttpd 
	linux-vdso.so.1 =>  (0x00007fff891a0000)
	libipset.so.11 => /lib64/libipset.so.11 (0x00007fe3f9971000)
[..]
# ls -rtl /usr/lib64/libipset.so.*
-rwxr-xr-x. 1 root root 186336 Feb 25 12:42 /usr/lib64/libipset.so.13.1.0
lrwxrwxrwx. 1 root root     18 Aug 21 17:00 /usr/lib64/libipset.so.13 -> libipset.so.13.1.0
```

Same issue as https://github.com/inverse-inc/packetfence/issues/3830

**Comment by nqb** [comment]
@fdurand, after installing `ipset-symlink-1.0.0-19.1` on RedHat 7.7, I got following files:

```console
# ls -rtl /lib64/libipset.so.*
-rwxr-xr-x 1 root root 186336 Feb 25 12:42 /lib64/libipset.so.13.1.0
lrwxrwxrwx 1 root root     18 Aug 23 07:47 /lib64/libipset.so.13 -> libipset.so.13.1.0
lrwxrwxrwx 1 root root     14 Aug 23 07:47 /lib64/libipset.so.3 -> libipset.so.11
lrwxrwxrwx 1 root root     14 Aug 23 07:47 /lib64/libipset.so.11 -> libipset.so.13
```
All services previously mentioned are started.

**Comment by extrafu** [comment]
@fdurand Check if it's in stable.

**Comment by extrafu** [comment]
@fdurand Have you been able to check if the package is in stable?

**Comment by fdurand** [comment]
Yes it is http://www.inverse.ca/downloads/PacketFence/CentOS7/x86_64/RPMS/ipset-symlink-1.0.1-3.1.x86_64.rpm
