### ISSUE TITLE
api-frontend won't start if api_inactivity_timeout isn't set

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4735]
From the Web admin, it is possible to unset the **API inactivity timeout** since it's not a required field. Even though the placeholder shows it will default to **15 minutes**, *pfhttpd* will complain about the missing value:

    Aug 22 13:42:28 localhost.localdomain pfhttpd[25906]: panic: json: cannot unmarshal string into Go struct field PfConfAdvanced.api_inactivity_timeout of type int

**Comment by julsemaan** [comment]
It seems that the widget for time duration is not sending null but instead a null interval with a unit when we empty out the field:
```
api_inactivity_timeout: {interval: null, unit: "m"}
```

Will speak with @satkunas about it

**Comment by julsemaan** [comment]
Seems like the frontend would expect null for this parameter if its value is inherited from pf.conf.defaults. That will trigger the right display on the frontend. That way the placeholder interval and unit will be shown correctly.

Will check with @jrouzierinverse for how to handle this specific case

**Comment by extrafu** [comment]
@julsemaan Any updates? Should @satkunas work on this?
