### ISSUE TITLE
webadmin: unable to display SSL certificates menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4739]
When you try to display SSL certificates from webadmin, you didn't get any information even if API call work.

**To Reproduce**
1. Go in `Configuration -> System configuration -> SSL certificates`

=> Page is loading indefinitely

**Expected behavior**
Should display SSL certificates.

**Desktop (please complete the following information):**
 - Browser: Chrome and Firefox

**Additional context**
Tested on Debian and CentOS with PF 9.0.1 and latest maintenance patches. I'm pretty sure issue has been caused by a patch in maintenance branch because this feature was working one month ago.

In Web browser console:
```
TypeError: "e.isModified is undefined"
    i CertificatesView.vue:1
    Ht VueJS
    i CertificatesView.vue:1
    VueJS 7
        _render
        r
        get
        run
        Kn
        pt
        lt
vue.runtime.esm.js:1888
    VueJS 10

**Comment by lzammit** [comment]
Getting an error too on the latest patches:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'http' of undefined
    at CertificatesView.vue?496c:1
    at a.Ht [as _l] (vue.runtime.esm.js:2630)
    at a.i (CertificatesView.vue?496c:1)
    at a.e._render (vue.runtime.esm.js:3542)
    at a.r (vue.runtime.esm.js:4060)
    at nr.get (vue.runtime.esm.js:4473)
    at nr.run (vue.runtime.esm.js:4548)
    at Kn (vue.runtime.esm.js:4304)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at lt (vue.runtime.esm.js:1906)
```

**Comment by cgx** [comment]
Issue was related to the maintenance branch only. It's fixed.
