### ISSUE TITLE
The id of a source cannot contain a space or a dot

### ISSUE THREAD

**Issue by joachimtingvold** [inverse-inc/packetfence#4744]
**Describe the bug**
If you register an authentication source contain a dot ("."), there's a warning during startup or restart;

```
WARNING - The id of a source cannot contain a space or a dot 'source.with.dot'
```

However, I was able to create the source just fine, and it also works. Another thing is that you cannot change the name after it's created, so you cannot change it without re-creating it.

**To Reproduce**
1. Create authentication source containing dot

**Expected behavior**
You should not be able to create authentication source containing a dot. If the warning is no longer relevant (i.e. you can actually use sources that contains a dot), the warning should be removed.

You should probably also be able to edit the name of the authentication source after it's created?

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Browser: Chrome, Firefox, Safari
 - Version: Chrome 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

PF version (ZEN);
```
[root@packetfence1 ~]# /usr/local/pf/bin/pfcmd version
PacketFence 9.0.1
```

**Comment by joachimtingvold** [comment]
Seems like the "no dot" was introduced via #925 and 6b5cc8f.

**Comment by julsemaan** [comment]
Seems like when the sources were reworked the validator was omitted and then the standard validator was added instead of migrating the old one.

Will fix this in the maintenance

**Comment by julsemaan** [comment]
You can get this fix by applying the patch manually or running `/usr/local/pf/addons/pf-maint.pl`
