### ISSUE TITLE
Switch x.x.x.x references a non existent group 'default'

### ISSUE THREAD

**Issue by joachimtingvold** [inverse-inc/packetfence#4745]
**Describe the bug**
Warning during startup or restart;

```
WARNING - switches.conf | Switch x.x.x.x references a non existent group 'default'
```

The group exists, though. Even if I edit the switch and re-apply the default group, it still complains.

Everything works as it should, and the settings from the group is actually applied.

![dump_2019-08-27_13 07 07](https://user-images.githubusercontent.com/359918/63766864-64b55600-c8cc-11e9-974b-64206d00b167.png)
![dump_2019-08-27_13 07 13](https://user-images.githubusercontent.com/359918/63766878-6a12a080-c8cc-11e9-81b8-1ea1924721a0.png)
![dump_2019-08-27_13 07 24](https://user-images.githubusercontent.com/359918/63766882-6da62780-c8cc-11e9-9c3e-d48194b94de3.png)
![dump_2019-08-27_13 07 30](https://user-images.githubusercontent.com/359918/63766884-6f6feb00-c8cc-11e9-8c33-ce502b44f687.png)

**To Reproduce**
1. Start or restart PF
2. Observe warning in logs

**Expected behavior**
Warning should not be there? Not sure why it complains.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Browser: Chrome, Firefox, Safari
 - Version: Chrome 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

PF version (ZEN);
```
[root@packetfence1 ~]# /usr/local/pf/bin/pfcmd version
PacketFence 9.0.1
```

**Comment by julsemaan** [comment]
Seems to be because the default group is not a "real" group per say in the configuration and the switches declare `group=default` when edited/created in the new admin

I'll add a skip in the checkup for when the group is default

**Comment by julsemaan** [comment]
You can get this fix by applying the patch manually or running `/usr/local/pf/addons/pf-maint.pl`
