### ISSUE TITLE
Connection type choices for node search are wrong

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4746]
**Describe the bug**
The connection types you can select when searching nodes are wrong and don't match the values in the DB

**To Reproduce**
1. Go in Nodes
2. Search in advanced for "Connection Type"
3. Check the listed options for the values, they do not match the values that are stored in the locationlog (and displayed in that page)

**Expected behavior**
The available options should match what is stored in the locationlog

**Comment by cgx** [comment]
Can we rely on this [list](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/constants/config.pm#L167-L178)?

**Comment by julsemaan** [comment]
> Can we rely on this [list](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/constants/config.pm#L167-L178)?

Yes we can rely on the keys of this list
