### ISSUE TITLE
Uplink value mandatory for switch group

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4757]
When I create a switch group, I need to put a Uplink port value in order to save the switch group.

It does not make any sense since I was creating it for a wireless controller.

We should use a default value or check the switch module capabilities?

**Comment by nqb** [comment]
IIRC, it was not necessary in the old admin because we got this value from defaults.

**Comment by lzammit** [comment]
So do we add it back to the default config ?

**Comment by jrouzierinverse** [comment]
This validation is done in the frontend @satkunas or @cgx can you look?

**Comment by satkunas** [comment]
New issue introduced/found https://github.com/inverse-inc/packetfence/issues/4797 while addressing this. This issue causes an incorrect value in the "Use CoA" default value (inherited from default switch group). This will be addressed separately.
