### ISSUE TITLE
web admin: default access duration choices are not visible

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4758]
Default access duration choices are not visible in new web admin even if API call works as expected:

```console
{"meta":{"access_duration_choices":{"default":"1h,3h,12h,1D,2D,3D,5D","placeholder":"1h,3h,12h,1D,2D,3D,5D","required":false,"type":"string"},"default_access_duration":{"default":null,"placeholder":"12h","required":false,"type":"string"},"default_access_duration_add":{"default":null,"placeholder":{"example":"<span id=\"extendedFrom\">YYYY-MM-DD hh:mm:ss<\/span> <i class=\"icon-arrow-right\"><\/i> <strong><span id=\"extendedTo\">YYYY-MM-DD hh:mm:ss<\/span><\/strong>"},"properties":{"day_base":{"default":null,"placeholder":null,"required":false,"type":"string"},"duration":{"default":null,"placeholder":null,"properties":{"interval":{"default":null,"min_value":0,"placeholder":null,"required":false,"type":"integer"},"unit":{"allowed":[{"text":"seconds","value":"s"},{"text":"minutes","value":"m"},{"text":"hours","value":"h"},{"text":"days","value":"D"},{"text":"weeks","value":"W"},{"text":"months","value":"M"},{"text":"years","value":"Y"}],"default":null,"placeholder":null,"required":false,"type":"string"}},"required":false,"type":"object"},"example":{"default":"<span id=\"extendedFrom\">YYYY-MM-DD hh:mm:ss<\/span> <i class=\"icon-arrow-right\"><\/i> <strong><span id=\"extendedTo\">YYYY-MM-DD hh:mm:ss<\/span><\/strong>","placeholder":"<span id=\"extendedFrom\">YYYY-MM-DD hh:mm:ss<\/span> <i class=\"icon-arrow-right\"><\/i> <strong><span id=\"extendedTo\">YYYY-MM-DD hh:mm:ss<\/span><\/strong>","required":false,"type":"string"},"extended_duration":{"default":null,"placeholder":null,"properties":{"interval":{"default":null,"min_value":0,"placeholder":null,"required":false,"type":"integer"},"operator":{"allowed":[{"text":"add","value":"add"},{"text":"subtract","value":"subtract"}],"default":null,"placeholder":null,"required":false,"type":"string"},"unit":{"allowed":[{"text":"days","value":"D"},{"text":"weeks","value":"W"},{"text":"months","value":"M"},{"text":"years","value":"Y"}],"default":null,"placeholder":null,"required":false,"type":"string"}},"required":false,"type":"object"},"period_base":{"default":null,"placeholder":null,"required":false,"type":"string"}},"required":false,"type":"object"}},"status":200}
```

**To Reproduce**
1. Go in Access duration menu
=> All default choices are missing.

**Expected behavior**
Default choices displayed

**Comment by nqb** [comment]
![Screenshot from 2019-08-30 14-50-24](https://user-images.githubusercontent.com/10830260/64022009-836a5580-cb35-11e9-9f8e-4e360aaafd1c.png)

**Comment by nqb** [comment]
It's seems to be an API issue.

Stable setup, 9.0.1, default and new access duration are listed:
```console
# pfperl-api get /api/v1/config/base/guests_admin_registration | jq
{
  "item": {
    "access_duration_choices": "1h,3h,12h,1D,1DF+1s,2D,3D,5D,2M,3MF+1s,3M,1Y",
[..]
```

Devel setup, if I defined new access duration choices, they replaced default access duration choices:
```console
# pfperl-api get /api/v1/config/base/guests_admin_registration | jq
{
  "item": {
    "access_duration_choices": "10m,12h",
```

**Comment by nqb** [comment]
@cgx and @jrouzierinverse, could you take a look ?

**Comment by nqb** [comment]
The PATCH request made when you create a new access duration (for example: 10m) contains following payload on a devel setup:
```json
access_duration_choices: "10m"
```
versus a stable setup
```json
access_duration_choices: "1h,3h,12h,1D,2D,3D,5D,10m"
```

**Comment by julsemaan** [comment]
@nqb try to replicate and close or bump

**Comment by nqb** [comment]
Still presents.

**Comment by jrouzierinverse** [comment]
Unable to replicate please check again.

**Comment by nqb** [comment]
I'm able to replicate this issue on a Debian fresh install with latest builds.

**Comment by nqb** [comment]
@julsemaan or @lzammit could you check on side if you get same behavior ?

**Comment by julsemaan** [comment]
Unable to replicate so this must be a Debian specific bug then since on CentOS 7 its all good on my end

**Comment by nqb** [comment]
I realized that when you add a new access duration choice, frontend send a PATCH request with all default access duration choices + new access duration choice in `access_duration_choices` item. Consequently, if your PATCH request only contains new access duration choice, default access duration choice will be overrided. 

I'm surprised by this behavior. From my point of view, a PATCH request is used to make a "merge" not a replacement of an item (like a PUT will do). API specs for `guests_admin_registration` doesn't seems to be written for now.

**Comment by jrouzierinverse** [comment]
PATCH is working as it should.
That behavior you are describing has an edge case that makes the API more complicated.
For example, How do you determine when to delete an access duration choice vs keeping it?

I move to close this issue.

**Comment by nqb** [comment]
@jrouzierinverse, I see, thanks for your explanation.
