### ISSUE TITLE
web admin: display of images in subdirectories

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4761]
When you browse documentation in web admin on a CentOS host, all images located in a subdirectory (ex: `rapid7`) of `static/images/` are missing.

**To Reproduce**
1. Display embedded documentation in web admin
2. Try to see images related to Rapid7 topic

**Expected behavior**
Images should appear.

**Additional context**
Files have not been installed:
```console
# find /usr/local/pf/html/pfappserver/root/static/images/* -type d
# 

```

**Comment by cgx** [comment]
We should add an alias in the Apache configuration or define a symlink.

**Comment by nqb** [comment]
I just understand that files are under `images/` dir without subdirectories.

@cgx, why not fixing this issue directly in packaging ? Reading `install` man page, it seems possible to copy whole directory under `images/`

**Comment by cgx** [comment]
@nqb You're right. Simply adjust the [spec file](https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L578-L581) and [Debian rules](https://github.com/inverse-inc/packetfence/blob/devel/debian/rules#L155-L158).
