### ISSUE TITLE
web admin: display access duration help is not working

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4763]
When I click on help button in Access Duration menu, web admin displays Installation Guide without going to a specific anchor even if anchor is configured.

**To Reproduce**
1. Go to Access Duration menu
2. Click on help button

**Expected behavior**
Should go to access duration menu in documentation (https://packetfence.org/doc/PacketFence_Installation_Guide.html#_access_duration)

**Additional context**
Access duration section in documentation has been removed by https://github.com/inverse-inc/packetfence/commit/3e0cb4c74bb573bcff26450e91e672045d7432c9

@extrafu, do you plan to move "Access duration" section in another place in the documentation or leave it removed ?

**Comment by nqb** [comment]
@extrafu: could you give me answer ?

**Comment by extrafu** [comment]
Wipe the link.

**Comment by nqb** [comment]
Fixed by https://github.com/inverse-inc/packetfence/commit/9e14f844d36388c243fa26361f2ef6663a28b9cd and https://github.com/inverse-inc/packetfence/commit/74093c517765416bf090786bc271464b274dc75b
