### ISSUE TITLE
web admin: wrong display for services in Main configuration

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4764]
When you go in System configuration -> Main configuration -> Services, all services have same state (see screenshot).

**Screenshots**
![Screenshot from 2019-08-30 17-35-53](https://user-images.githubusercontent.com/10830260/64033495-df8ca400-cb4c-11e9-88eb-43953e88c83b.png)

**Expected behavior**
![Screenshot from 2019-08-30 17-39-37](https://user-images.githubusercontent.com/10830260/64033633-27133000-cb4d-11e9-8b38-aad272de8c3e.png)

Button should be in blue to reflect that a service is managed by PacketFence and vice versa.

**Comment by cgx** [comment]
I can't reproduce this issue. What's your output of `/usr/local/pf/sbin/pfperl-api get /api/v1/config/base/services`?

**Comment by julsemaan** [comment]
@nqb will try to replicate and close or bump

**Comment by nqb** [comment]
Sounds good.
