### ISSUE TITLE
Node with empty unregdate (0000-00-00 00:00:00) has error when editing it in the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4765]
**Describe the bug**
If you edit a node that has an unregdate set to '0000-00-00 00:00:00' then editing this node shows an error with the field

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/64044267-523d5580-cb34-11e9-9c2c-c89d7f9cb8e4.png)

**Comment by cgx** [comment]
Should be fixed by 1ddb71e. Can you try *devel*?

**Comment by nqb** [comment]
@cgx: still presents in latest CentOS builds.
