### ISSUE TITLE
API: some timezones values are missing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4768]
In webadmin, when you want to configure your timezone as UTC, you can't.

**Screenshots**
![Screenshot from 2019-09-03 09-51-22](https://user-images.githubusercontent.com/10830260/64154191-98dec880-ce30-11e9-8398-4b42ce1fce6a.png)

**Expected behavior**
All allowed timezones should appear in the list (`UTC` included)

**Additional context**
According to documentation of [DateTime::TimeZone module](https://metacpan.org/pod/DateTime::TimeZone), `UTC` is an allowed value.

I noticed that answer from API return 345 results but `DateTime::TimeZone->all_names()` contain 357 results. Explanation:

`timezone.pl`
```perl
use DateTime;
use DateTime::TimeZone;
 
my @all_tz = DateTime::TimeZone->all_names();
foreach my $tz (@all_tz) {
  print "$tz\n";
}
```
```console
# perl timezone.pl | grep -v "/"
CET
CST6CDT
EET
EST
EST5EDT
HST
MET
MST
MST7MDT
PST8PDT
UTC
WET
```
All these abbreviations are missing.

**Comment by jrouzierinverse** [comment]
We only display the timezones that have a slash in the name.
@cgx do you know if there was any reason that was the case?

**Comment by cgx** [comment]
@jrouzierinverse I guess we could add them all without side effect.
