### ISSUE TITLE
Blackhole source is not exclusive anymore

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4774]
If you add multiple sources and it includes the Blackhole source it just displays it as a normal source.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/5261214/64195787-54fbbb80-ce50-11e9-9db4-820dfdbad47f.png">

**Comment by jrouzierinverse** [comment]
This was previously handled on the frontend.
I would need to also add the check on the back end.

**Comment by lzammit** [comment]
Please don't close it, let me close it after testing. It's easier for me to keep track of my opened issues.

**Comment by lzammit** [comment]
Fix does not work.

It does not seem to be handled in the front end (Can save the connection profile without any error)

The portal still displays the source on the portal as "Refuse Login"

**Comment by jrouzierinverse** [comment]
Did you remove it manually from your profiles.conf?

**Comment by lzammit** [comment]
No.

Here's my configuration:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5261214/64359089-a5505600-cfd5-11e9-87f3-fb482bc8adbb.png">

Preview and portal:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/5261214/64359125-bb5e1680-cfd5-11e9-9740-975db1354f36.png">

**Comment by jrouzierinverse** [comment]
I pushed a fix on the backend please try again.

**Comment by lzammit** [comment]
Works:

![image](https://user-images.githubusercontent.com/5261214/64639294-97377680-d3d5-11e9-9904-518615babf4d.png)

![image](https://user-images.githubusercontent.com/5261214/64639308-9dc5ee00-d3d5-11e9-8adb-c33ef3a0deea.png)
