### ISSUE TITLE
ipset upgrade cause issues when installing PacketFence

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4776]
When you try to install latest builds of PacketFence under CentOS 7:
```
    Error: Package: ipset-symlink-1.0.1-3.1.x86_64 (packetfence-devel)                                                                         
               Requires: ipset >= 7.1                                                                                            
               Installed: ipset-6.38-3.el7_6.x86_64 (@koji-override-1)                                                        
                   ipset = 6.38-3.el7_6                                                                                                
               Available: ipset-6.38-2.el7.x86_64 (base)                                                                             
                   ipset = 6.38-2.el7
```

**Expected behavior**
It should be possible to install latest builds with ipset-6.38-3

**Comment by nqb** [comment]
Related to #4732, same issue if you try to install PF 9.0.1 on CentOS 7.

**Comment by nqb** [comment]
@fdurand is building a new package. Will be uploaded in a few minutes.

**Comment by nqb** [comment]
I still got an issue with new package:
```
Transaction check error:
  file /usr/lib64/libipset.so.11 from install of ipset-symlink-1.0.1-4.1.x86_64 conflicts with file from package ipset-libs-6.38-3.el7_6.x86_64

Error Summary
```

**Comment by nqb** [comment]
CentOS 7.7 has been released today with new version of ipset. Something to have in mind for our 9.1 release.

**Comment by julsemaan** [comment]
I'm tired of this ipset bull***t, I'm adding ipset to our repos and pinning it

**Comment by shanehull** [comment]
Yep, I'm getting:

```
Error: Package: packetfence-9.1.0-1.el7.noarch (packetfence)
           Requires: ipset = 6.38
           Installed: ipset-7.1-1.el7.x86_64 (@anaconda)
               ipset = 7.1-1.el7
           Available: ipset-6.38-3.el7_6.x86_64 (packetfence)
               ipset = 6.38-3.el7_6
```

And 6.38 doesn't appear to be available.

**Comment by nqb** [comment]
Issue presents in nightly builds too.

**Comment by nqb** [comment]
### Current state

#### CentOS 7.6 with PF 9.1
Only `ipset-symlink` has been installed from packetfence repo:
```console
# yum list ipset*
[..]
Installed Packages
ipset.x86_64                                                                                         6.38-3.el7_6                                                                                  @koji-override-1
ipset-libs.x86_64                                                                                    6.38-3.el7_6                                                                                  @koji-override-1
ipset-symlink.x86_64                                                                                 1.0.0-19.1                                                                                    @packetfence 

Available Packages
ipset.x86_64                                                                                         7.1-1.el7                                                                                     base            
ipset-devel.i686                                                                                     7.1-1.el7                                                                                     base            
ipset-devel.x86_64                                                                                   7.1-1.el7                                                                                     base            
ipset-libs.i686                                                                                      7.1-1.el7                                                                                     base            
ipset-libs.x86_64                                                                                    7.1-1.el7                                                                                     base            
ipset-service.noarch                                                                                 7.1-1.el7                                                                                     base

# ls -rtl /lib64/libipset*
-rwxr-xr-x. 1 root root 161160 Nov 28  2018 /lib64/libipset.so.11.1.0
lrwxrwxrwx. 1 root root     18 Jun  1 17:14 /lib64/libipset.so.11 -> libipset.so.11.1.0
lrwxrwxrwx. 1 root root     14 Sep 19 05:26 /lib64/libipset.so.3 -> libipset.so.11

# ldd $PF/sbin/pfhttpd
        linux-vdso.so.1 =>  (0x00007ffec4904000)
        libipset.so.11 => /lib64/libipset.so.11 (0x00007f40ac8bf000)
[..]
```

#### CentOS 7.7 without PF installed
```console
# yum list ipset*
Paquets installés
ipset.x86_64                                                                                                7.1-1.el7                                                                                         @base
ipset-libs.x86_64                                                                                           7.1-1.el7                                                                                         @base

Paquets disponibles
ipset-devel.i686                                                                                            7.1-1.el7                                                                                         base 
ipset-devel.x86_64                                                                                          7.1-1.el7                                                                                         base 
ipset-libs.i686                                                                                             7.1-1.el7                                                                                         base 
ipset-service.noarch                                                                                        7.1-1.el7                                                                                         base 

# ls -rtl /lib64/libipset*
-rwxr-xr-x. 1 root root 186296  8 août  23:55 /lib64/libipset.so.13.1.0
lrwxrwxrwx. 1 root root     18 19 sept. 05:49 /lib64/libipset.so.13 -> libipset.so.13.1.0
```

**Comment by nqb** [comment]
### Issues

1. Installing PF 9.1 on a fresh CentOS 7.7 is not possible
2. Upgrading from CentOS 7.6 with PF 9.1 installed to CentOS 7.7 is not possible

```console
  msg: |-
    Error: Package: packetfence-9.1.0-1.el7.noarch (packetfence)
               Requires: ipset = 6.38
               Installed: ipset-7.1-1.el7.x86_64 (@base)
                   ipset = 7.1-1.el7
               Available: ipset-6.38-3.el7_6.x86_64 (packetfence)
                   ipset = 6.38-3.el7_6
```

# Workaround for 1.

The only way to make it working is to downgrade by hand `ipset` and `ipset-libs` with: `yum downgrade ipset ipset-libs --enablerepo=packetfence`

State after:
```console
# yum list ipset*
[..]
Paquets installés
ipset.x86_64                                                                                           6.38-3.el7_6                                                                                    @packetfence
ipset-libs.x86_64                                                                                      6.38-3.el7_6                                                                                    @packetfence
ipset-symlink.x86_64                                                                                   1.0.0-19.1                                                                                      installed

# ls -rtl /lib64/libipset*
-rwxr-xr-x. 1 root root 161160 28 nov.   2018 /lib64/libipset.so.11.1.0
lrwxrwxrwx. 1 root root     18 19 sept. 07:44 /lib64/libipset.so.11 -> libipset.so.11.1.0
lrwxrwxrwx. 1 root root     14 19 sept. 07:49 /lib64/libipset.so.3 -> libipset.so.11

```

# Workaround for 2.

Upgrade all packages except `ipset` and  `ipset-libs`: `yum --exclude=ipset,ipset-libs upgrade`

State after:
```console
# yum list ipset*
Installed Packages
ipset.x86_64                                                                                         6.38-3.el7_6                                                                                  @koji-override-1
ipset-libs.x86_64                                                                                    6.38-3.el7_6                                                                                  @koji-override-1
ipset-symlink.x86_64                                                                                 1.0.0-19.1                                                                                    @packetfence 

# ls -rtl /lib64/libipset*
-rwxr-xr-x. 1 root root 161160 Nov 28  2018 /lib64/libipset.so.11.1.0
lrwxrwxrwx. 1 root root     18 Jun  1 17:14 /lib64/libipset.so.11 -> libipset.so.11.1.0
lrwxrwxrwx. 1 root root     14 Sep 19 05:26 /lib64/libipset.so.3 -> libipset.so.11
```

**Comment by franzste** [comment]
> ### Issues
> 
>     1. Installing PF 9.1 on a fresh CentOS 7.7 is not possible
> 
>     2. Upgrading from CentOS 7.6 with PF 9.1 installed to CentOS 7.7 is not possible
> 
> 
> ```
>   msg: |-
>     Error: Package: packetfence-9.1.0-1.el7.noarch (packetfence)
>                Requires: ipset = 6.38
>                Installed: ipset-7.1-1.el7.x86_64 (@base)
>                    ipset = 7.1-1.el7
>                Available: ipset-6.38-3.el7_6.x86_64 (packetfence)
>                    ipset = 6.38-3.el7_6
> ```
> 
> # Workaround for 1.
> 
> The only way to make it working is to downgrade by hand `ipset` and `ipset-libs` with: `yum downgrade ipset ipset-libs --enablerepo=packetfence`
> 
> State after:
> 
> ```
> # yum list ipset*
> [..]
> Paquets installés
> ipset.x86_64                                                                                           6.38-3.el7_6                                                                                    @packetfence
> ipset-libs.x86_64                                                                                      6.38-3.el7_6                                                                                    @packetfence
> ipset-symlink.x86_64                                                                                   1.0.0-19.1                                                                                      installed
> 
> # ls -rtl /lib64/libipset*
> -rwxr-xr-x. 1 root root 161160 28 nov.   2018 /lib64/libipset.so.11.1.0
> lrwxrwxrwx. 1 root root     18 19 sept. 07:44 /lib64/libipset.so.11 -> libipset.so.11.1.0
> lrwxrwxrwx. 1 root root     14 19 sept. 07:49 /lib64/libipset.so.3 -> libipset.so.11
> ```
> 
> # Workaround for 2.
> 
> Upgrade all packages except `ipset` and  `ipset-libs`.
> 
> State after:
> 
> ```
> # yum list ipset*
> Installed Packages
> ipset.x86_64                                                                                         6.38-3.el7_6                                                                                  @koji-override-1
> ipset-libs.x86_64                                                                                    6.38-3.el7_6                                                                                  @koji-override-1
> ipset-symlink.x86_64                                                                                 1.0.0-19.1                                                                                    @packetfence 
> 
> # ls -rtl /lib64/libipset*
> -rwxr-xr-x. 1 root root 161160 Nov 28  2018 /lib64/libipset.so.11.1.0
> lrwxrwxrwx. 1 root root     18 Jun  1 17:14 /lib64/libipset.so.11 -> libipset.so.11.1.0
> lrwxrwxrwx. 1 root root     14 Sep 19 05:26 /lib64/libipset.so.3 -> libipset.so.11
> ```

I've spend a whole day on this ipset thing on centos 7.7.. thanks for your workaround! I will try this asap.

**Comment by nqb** [comment]
Ok @franzste, we will try to provide a more simple way to install PF under 7.7 ASAP.

**Comment by julsemaan** [comment]
I will look into compiling the ipset lib directly in our golang binaries so that the dependency on the ipset version can be softer and be independent from the version of ipset-libs installed on the system

**Comment by julsemaan** [comment]
@jrouzierinverse will look with me on statically compiling the binary with ipset or use libipset.so instead of libipset.XX.0.so (where XX is a version) so that it can use any version installed on the system

**Comment by julsemaan** [comment]
Just pushed an ipset package with an increased epoch (thanks @jrouzierinverse) and that package is able to serve as an update to ipset 7.1 although its a lower number.

Performing:
```
yum clean all --enablerepo=*
```

And retrying the install/update should now work correctly

**Comment by nqb** [comment]
> I will look into compiling the ipset lib directly in our golang binaries so that the dependency on the ipset version can be softer and be independent from the version of ipset-libs installed on the system

Does it mean that `ipset-devel` [package](https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L59) will not be a BuildRequires ?

**Comment by julsemaan** [comment]
> > I will look into compiling the ipset lib directly in our golang binaries so that the dependency on the ipset version can be softer and be independent from the version of ipset-libs installed on the system
> 
> Does it mean that `ipset-devel` [package](https://github.com/inverse-inc/packetfence/blob/devel/addons/packages/packetfence.spec#L59) will not be a BuildRequires ?

I wasn't able to statically compile libipset in our binary but if I would have been able to, ipset-devel would still be necessary for building

**Comment by nqb** [comment]
As discussed internally with @julsemaan, it seems more simple for now to release one PF version with one fixed ipset version (like we did for 9.1). Maintenance binaries for each PF version will be build using same environment as for the release. We plan to build new Docker images for each release of PacketFence to meet this requirement.

We will try to be proactive to support new ipset versions before they are released to avoid putting ipset packages in our repos. When it's not possible, we can provide ipset packages from our repo with an Epoch number increased.

**Comment by nqb** [comment]
For 9.2, @julsemaan will put `ipset-devel-6.38` in our repos.

**Comment by julsemaan** [comment]
ipset-devel was already in our packetfence-devel repo:
http://inverse.ca/downloads/PacketFence/CentOS7/devel/x86_64/RPMS/ipset-devel-6.38-3.el7_6.x86_64.rpm

**Comment by nqb** [comment]
Sorry if I missed it. I supposed we can close this issue now.
