### ISSUE TITLE
Issue when updating a local combination

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4779]
**Describe the bug**
When you attempt to update a local combination, you get the following error:
```
Sep  4 12:57:17 localhost packetfence: ERROR pfperl-api(5796): DBIx::Class::Row::get_column(): No such column 'not_deletable' on fingerbank::Base::Schema::Combination at /usr/local/pf/lib/fingerbank/Base/CRUD.pm line 319
 (Mojolicious::Plugin::DefaultHelpers::_development)
```

**To Reproduce**
1. Update an existing local combination

**Comment by jrouzierinverse** [comment]
The value is being sent from the frontend.
My question is should we fail when receiving an invalid field or should we ignore unknown fields?

**Comment by julsemaan** [comment]
We should be consistent across the API calls, i.e. making it the same as the DAL API calls and the configuration based API calls
