### ISSUE TITLE
web admin: Embed documentation still use old CSS

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4781]
**Screenshots**
![Screenshot from 2019-09-05 09-47-29](https://user-images.githubusercontent.com/10830260/64322165-52b96e80-cfc2-11e9-8365-830baf716c98.png)

**Expected behavior**
Should use new CSS like on CentOS

**Comment by nqb** [comment]
Result of `make html` target in a Debian build:
```
asciidoctor \
	-D docs/html \
	-n \
	-r ./docs/html/asciidoctor-html.rb \
	-a imagesdir=../images \
	-a stylesdir=../html/pfappserver/root/static.alt/dist/css \
	-a stylesheet= \
	docs/PacketFence_Developers_Guide.asciidoc
```
=> `stylesheet` argument is empty

**Comment by cgx** [comment]
You must generate the CSS of the Web admin first.

**Comment by extrafu** [comment]
@fdurand will look at it before flying to cheese country.
