### ISSUE TITLE
always_trigger configuration parameter

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4782]
**Describe the bug**
When you create a new switch from the new admin it set the configuration parameter always_trigger that does nothing.

1. Create a switch from the new admin
2. Edit switches.conf

**Expected behavior**
Should not have this configuration parameter

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/docs/api/spec/openapi.yaml#L9290

**Comment by jrouzierinverse** [comment]
Fixed by 2933fb506cb80ce87a9ad4ca992ae6f61236e8ee
