### ISSUE TITLE
Cannot search in Filter Engines text editor

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4787]
**Describe the bug**
If you attempt to search using Ctrl-F in the filter engine editor nothing happens

**Comment by julsemaan** [comment]
It seems the recent maintenance is also affected by this so that should likely go in maintenance/9.0 once the fix is done

**Comment by julsemaan** [comment]
Again here a +1 patch that needs to go in the maintenance

**Comment by satkunas** [comment]
@julsemaan added to `maintenance/9.0` w/ https://github.com/inverse-inc/packetfence/commit/c38e1c5fd7945ea410ea8542210dbaaf23e2a53d

Closing
