### ISSUE TITLE
Security Event: Autoreg security event does not work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4788]
Few things broken in the security events:

- When you clone a security event it does not display in the list. it displays in the old admin.
- The security event once triggered does not show up on the node Security event tab nor the Reports Security Events.
- The security event triggers correctly and assigns the correct unregdate but does not set the asked role 

config:
````
[1100007-copy]
priority=1
trigger=device::193
actions=autoreg,log
desc=Auto-register Device example
enabled=Y
access_duration=12h
target_category=default
window=
grace=45s
````
Logs:
````
2019-09-05 13:41:38: Auto-register Device example (1100007-copy) detected on node d8:2c:79:85:fd:3a (179.22.149.54)
````

**Comment by julsemaan** [comment]
I'm not 100% sure but it could be because of the '-copy' in the security event ID since they are assumed to be numbers

@lzammit Can you retry without the '-copy', if it works then we'll get @satkunas to adjust the clone in the frontend

**Comment by julsemaan** [comment]
It seems that its related to cloning 1100007

So I cloned that security event and selected a role and saved the security event and it didn't add the 'role' action to the list of actions like it usually does when creating a security event from scratch

Assigning to @cgx to investigate the frontend issue

**Comment by satkunas** [comment]
Clone appears to work via the new web admin without issue. The cloned event shows up at the bottom of the 2nd page (default sorting), and `-copy` is properly appended to the identifier.

There are some slight differences between the original config (`security_events.conf.defaults`) and the cloned config (`security_events.conf`). 

- `trigger` uppercases `device` to `DEVICE`
- `enabled` is ignored.

See below:

```
[1100007]
desc=Auto-register Device example
priority=1
trigger=DEVICE::3,DEVICE::6,DEVICE::7,DEVICE::8,DEVICE::10,DEVICE::12,DEVICE::13
actions=log,autoreg
enabled=N
```
```
[1100007-copy]
priority=1
trigger=device::3,device::6,device::7,device::8,device::10,device::12,device::13
actions=log,autoreg
desc=Auto-register Device example
target_category=gaming
```

**Comment by satkunas** [comment]
> When you clone a security event it does not display in the list.

Sorting by `id` on the Security Event index page appears to be broken.

Issue opened for this at https://github.com/inverse-inc/packetfence/issues/4810

**Comment by satkunas** [comment]
Added to `maintenance/9.0` in https://github.com/inverse-inc/packetfence/commit/eb0b27e01be2c4bfb3c483cb2536382ae52eb143
