### ISSUE TITLE
Can't remove Radius source type

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4789]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/5261214/64368554-96bf6a00-cfe8-11e9-80ca-3536c012fcdd.png">

Config:

````
[pf3]
realms=
options=type = auth+acct
monitor=1
secret=testing123
port=1812
description=pf3
host=172.290.145.23
timeout=1
type=RADIUS
set_access_durations_action=

[pf3 rule catchall]
action0=set_role=default
match=all
class=authentication
action1=set_access_duration=5D
````

**Comment by extrafu** [comment]
@lzammit Check if it's used on a connection profile.

**Comment by extrafu** [comment]
@jrouzierinverse Just make sure we have a better error when we can't delete it.

**Comment by jrouzierinverse** [comment]
A better error was given @lzammit can you look?

**Comment by lzammit** [comment]
It works.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/5261214/64720678-0f1aa500-d499-11e9-8f75-1672433038f4.png">
