### ISSUE TITLE
Wrong value is being inserted in mac_vendor_id when creating a local combination

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4791]
**Describe the bug**
When creating a local combination with a MAC vendor it puts the value of the mac field instead of the id field of the mac_vendor entry

**To Reproduce**
1. Create a local combination with a MAC vendor
2. Inspect entry in fingerbank_Local.db and you'll see the MAC instead of the ID in the table

**Additional context**
Here is the request payload sent by the browser:
```
{mac_vendor_id: "94dbc9", device_id: "264", score: "69", id: "L3"}
```

**Comment by julsemaan** [comment]
Also please check if this applies to maintenance/9.0 or was introduced between 9.0 and 9.1

**Comment by satkunas** [comment]
Search function does not currently return the `id`.

```json
{
    "items": [{
        "mac": "94dbc9",
        "name": "AzureWave Technology Inc.",
        "not_deletable": true,
        "not_updatable": true
    }],
    "prevCursor": 0,
    "scope": "all",
    "status": 200
}
```

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/0b4aa48f6e560d83ebf77eb8a4527bda1c1b8fab

**Comment by satkunas** [comment]
@julsemaan it wasn't introduced, it was an oversight during the initial design.

**Comment by julsemaan** [comment]
@satkunas, then this will need to be added in maintenance/9.0

**Comment by satkunas** [comment]
@julsemaan pushed to maint/9.0  

https://github.com/inverse-inc/packetfence/commit/080c57c730e3c3a9d070d4150a767970d9bdc6ba

**Comment by julsemaan** [comment]
Fixed, closing
