### ISSUE TITLE
customize web auth URL captive portal

### ISSUE THREAD

**Issue by diedriko** [inverse-inc/packetfence#4792]
Hi there,
We deploy packetfence as a captive portal solution combined with Cambium AP's.
For the configuration of the web auth URL the following url is proposed, https://$packetfenceserver/Cambium
Is this URL adjustable, more specifically could we change the Cambium part of the URL to something else?

**Comment by julsemaan** [comment]
No its not possible, this is how PF knows the type of AP/switch its dealing with during web-auth since they all have their specificity for that workflow
