### ISSUE TITLE
FreeRADIUS: "cache" modules aren't allowed in 'authenticate' sections

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4793]
On a fresh Debian install with latest builds, FreeRADIUS is not able to start. If you run FreeRADIUS from command line you got:
```
/usr/local/pf/raddb/sites-enabled/packetfence-tunnel[213]: "cache" modules aren't allowed in 'authenticate' sections -- they have no such method.
/usr/local/pf/raddb/sites-enabled/packetfence-tunnel[213]: Failed to parse "PacketFence-NTCacheHash" entry.
/usr/local/pf/raddb/sites-enabled/packetfence-tunnel[197]: Failed to parse "if" subsection.
```
Seems to be related to [following change](https://github.com/inverse-inc/packetfence/commit/be34215cc2397ac55e54c8acf237c82ea46cc630#diff-d113912c1724120ebaa882f4ed8c4e86).

**To Reproduce**
1. Install a fresh Debian with latest builds
2. Start services
3. See error

**Additional context**
FreeRADIUS 3.0.18.
I'm almost sure this issue is not present on CentOS with same FreeRADIUS version.

PacketFence-NTCacheHash is correctly loaded during startup of FreeRADIUS:
```console
$ /usr/sbin/freeradius -d /usr/local/pf/raddb  -n auth -Cxm -lstdout
[..]
rlm_cache (PacketFence-NTCacheHash): Driver rlm_cache_rbtree (module rlm_cache_rbtree) loaded and linked
[..]
```

**Comment by nqb** [comment]
Interesting thread: http://lists.freeradius.org/pipermail/freeradius-users/2015-August/079407.html

**Comment by fdurand** [comment]
https://github.com/fdurand/freeradius-server/commit/cac8d5b0b115fe3fa6d8e169f0710e14db1194f3

**Comment by nqb** [comment]
Thanks @fdurand, I will take a look.
