### ISSUE TITLE
'No Results' shown while Fingerbank lookup is being performed

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4794]
**Describe the bug**
When you use a Fingerbank typeahead field (Ex: MAC vendor when creating a local combination, Device when creating a security event trigger)

**To Reproduce**
1. Create a local Fingerbank combination
2. Type '000000' into the MAC vendor field
3. 'No results' will be shown for a few seconds until the results are actually loaded

**Expected behavior**
A spinning wheel (or any other indicator) should display that the results are loading

**Comment by julsemaan** [comment]
This is a +1 and needs to go in the maintenance if it can be applied there

**Comment by satkunas** [comment]
@julsemaan added to `maintenance/9.0` w/ https://github.com/inverse-inc/packetfence/commit/b4d6a01ab73fe6d2d7a7c6403f68209cd3f28b07

closing
