### ISSUE TITLE
web admin: wrong display for network interfaces menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4801]
Display of network interfaces could be better:
- Daemons column: you got `[]` character when no additional daemons have been defined
- IPv4 column: long IP addresses are splitted

**Screenshots**
![Screenshot from 2019-09-11 08-29-28](https://user-images.githubusercontent.com/10830260/64673436-740cd580-d46e-11e9-92a0-6354c2623f44.png)

**Comment by satkunas** [comment]
> IPv4 column: long IP addresses are splitted

@nqb adding nowrap to any column will cause others to overlap on lower resolutions. You'll need to either increase your screen resolution, or decrease your font-size in order to fit the entire table on-screen without word-breaks.
