### ISSUE TITLE
web admin: better handling of invalid Fingerbank key

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4802]
An invalid Fingerbank key is not correctly handle when saved.

**To Reproduce**
1. Go to `Fingerbank -> General settings`
2. Enter your API key: `Zayme`
3. Save
=> Next four API calls reply with 200 (upstream/collector/query/proxy)
4. Leave this menu and come back
=> your API key has disappeared, API call to account_info return:
```json
{"errors":[],"message":"Invalid key","status":401}
```
but `/usr/local/fingerbank/conf/fingerbank.conf` contains your API key.

**Expected behavior**
Have an error message when your key is not valid.

**Comment by nqb** [comment]
Certainly related to #4805

**Comment by julsemaan** [comment]
#4805 currently prevents me from working on this issue since the settings section is broken in the admin
