### ISSUE TITLE
web admin: security events search is case sensitive

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4804]
**To Reproduce**
1. Go to Security Events menu
2. Search on "generic"
=> No results

**Expected behavior**
Should get "Generic" security event.

**Comment by satkunas** [comment]
Collation issue in DAL. In this case `id` will need to be collated as `LATIN1_GENERAL_CI` during the query, or we change the default `security_events` table collation from `LATIN1` to `LATIN1_GENERAL_CI` or `UTF8_GENERAL_CI` (preferred).


```SQL
SELECT  *
FROM    security_events
WHERE   security_events.`id` COLLATE LATIN1_GENERAL_CI LIKE '%case-insensitive-search%'
```

Re-assigning to @jrouzierinverse

**Comment by julsemaan** [comment]
The ID isn't 'Generic' through, its another field that contains it
