### ISSUE TITLE
web admin: invalid caracter saved by file editor

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4808]
If I try to insert a "é" in an HTML file using file editor, my HTML file will be save with "Ã©" character in it causing a wrong display on captive portal.

**To Reproduce**
1. Add a "é" character in `layout.html` of the default connection profile using file editor
2. Save
3. Display your HTML file using file editor or with `less captive-portal/profile-templates/default/layout.html`

=> You got an invalid character.

**Expected behavior**
Web admin should save "é", not invalid character.

**Additional context**
Issue is not present in old web admin.

**Comment by jrouzierinverse** [comment]
I pushed a fixed @cgx or @julsemaan would you mind testing?

**Comment by extrafu** [comment]
@julsemaan Can you test please?

**Comment by julsemaan** [comment]
Still an issue

**Comment by jrouzierinverse** [comment]
Works on my machine. Did you restart pfperl-api?

**Comment by cgx** [comment]
Doesn't work for me neither.

**Comment by julsemaan** [comment]
Works now
