### ISSUE TITLE
Cannot update node in admin interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4809]
**Describe the bug**
Getting a 404 in the API when editing a node in the admin. Seems it doesn't like the URL encoded `:` that were added recently

**To Reproduce**
1. Edit a node in the admin
2. Change something
3. Save it
4. Eat your emotions while contemplating the error

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/64711519-b7c00900-d487-11e9-88e8-0b67f265d6dd.png)

**Comment by jrouzierinverse** [comment]
Please retest.

**Comment by extrafu** [comment]
@julsemaan Can you test James' fix?

**Comment by julsemaan** [comment]
golden
