### ISSUE TITLE
script is looking for httpd

### ISSUE THREAD

**Issue by blueprin4** [inverse-inc/packetfence#4812]
I am trying to install on existing centos 6 server for the past 3 days.  It hangs on error:

Error: Package: mod_wsgi-3.2-7.el6.x86_64 (base)
           Requires: httpd-mmn = 20051115
Error: Package: mod_evasive-1.10.1-10.el6.x86_64 (epel)
           Requires: httpd
Error: Package: packetfence-6.5.1-1.el6.noarch (packetfence)
           Requires: httpd
Error: Package: mod_qos-10.24-1.el6.x86_64 (epel)
           Requires: httpd-mmn = 20051115
Error: Package: mod_perl-2.0.4-12.el6_10.x86_64 (updates)
           Requires: httpd-mmn = 20051115
Error: Package: packetfence-6.5.1-1.el6.noarch (packetfence)
           Requires: mod_proxy_html
           Available: mod_proxy_html-3.1.2-6.el6.x86_64 (epel)
               mod_proxy_html = 3.1.2-6.el6
           Available: mod_proxy_html-3.1.2-6.1.x86_64 (packetfence)
               mod_proxy_html = 3.1.2-6.1
Error: Package: packetfence-6.5.1-1.el6.noarch (packetfence)
           Requires: mod_ssl
Error: Package: libapreq2-2.13-1.el6.x86_64 (epel)
           Requires: httpd-mmn = 20051115
Error: Package: mod_evasive-1.10.1-10.el6.x86_64 (epel)
           Requires: httpd-mmn = 20051115
 You could try using --skip-broken to work around the problem

I have tried to install httpd on my server but it says:
Processing Conflict: ea-apache24-2.4.41-1.1.2.cpanel.x86_64 conflicts httpd-mmn
--> Finished Dependency Resolution
Error: ea-apache24 conflicts with httpd-2.2.15-69.el6.centos.x86_64
The only thing I found on the web somewhat helpful was this post about installing it on Ubuntu:
https://www.linux.com/tutorials/install-and-configure-packetfence-ubuntu-linux/
because packetfence is looking for apache daemon in httpd.  He installed it from install.pl which is not included no longer.

thanks

**Comment by julsemaan** [comment]
We dropped support for CentOS 6 a few years ago, you won't have much success installing this on CentOS 6

Also, how about following the official documentation (https://packetfence.org/doc/PacketFence_Installation_Guide.html) instead relying on random posts that date from 2010
