### ISSUE TITLE
API GET /api/v1/config/portal_module/<id> → source_id is an array

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4814]
When fetching the `source_id` of a portal module, the value is an array while it should be a **string**.

```bash
$ /usr/local/pf/sbin/pfperl-api get /api/v1/config/portal_module/foo | jq .item.source_id
[
  "email"
]
```

**Comment by julsemaan** [comment]
You can have multiple ids in some modules and the parameter will still be called source_id so that's why its an array

**Comment by cgx** [comment]
I though it was called `multi_source_ids` in this case?

**Comment by julsemaan** [comment]
Seems you're right, I was thinking of the backend code which doesn't rely on this fields which is virtual and created for usage through the ConfigStore (and the API/admin)

I checked and `source_id` is not defined as multiple in the forms so it looks like it should be fine.

Perhaps @jrouzierinverse can quickly confirm if this change occurs in the API form magic

**Comment by julsemaan** [comment]
I guess this should go in the maintenance if possible as its marked as a +1

**Comment by jrouzierinverse** [comment]
done
