### ISSUE TITLE
Unifi: send deauthentication on specific site

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4818]
Currently, when PF try to deauthenticate a device on Unifi controller, it [sends an API call on each site](https://github.com/inverse-inc/packetfence/blob/b14a65edfd253ba1dfba275435ca4515e63fe359/lib/pf/Switch/Ubiquiti/Unifi.pm#L212-L218) found in Unifi configuration until it gets a success.

As described on [Unifi forum](https://community.ui.com/questions/authorize-guest-command-permit-to-allow-any-clients-from-any-AP-without-verification/5d9bd04c-17f5-4e57-93fd-d46131304967#answer/67861ae4-3a33-4939-bb42-13d3b6fe6ab4), this behavior is not working with an Unifi controller running 5.11.39 because default site will always reply with a 200 HTTP code.

However, site-id is part of URL sent by AP when device is redirected in captive portal (see `/usr/local/pf/logs/haproxy_portal.log`):
```
GET /guest/s/x9af53ea/?ap=AP_MAC&id=DEVICE_MAC&t=1568799501&url=http://free.fr&ssid=MY_SSID
```
with `x9af53ea` equals to site-id.

We should store this information during registration to use it during deauth.

**Comment by rcmcdonald91** [comment]
UniFi 5.12 now supports RADIUS CoA, which is probably a better solution moving forward.

**Comment by nqb** [comment]
Hello @theonemcdonald,

Thanks for point it out. I already opened a case for #4573. 

For 802.1X, we will be able to use CoA to send deauthentication but WebAuth is done using HTTP only (not RADIUS). We will need to keep same logic for WebAuth.

**Comment by fdurand** [comment]
This is what we did before:
https://github.com/inverse-inc/packetfence/commit/3ac5dee58de526db8635c1e6f21258392ca8fd13#diff-8b99f599546e7710d1df6b776d184569
We can try to reapply the same logic.
For the CoA, i will try it.

**Comment by nqb** [comment]
Hello @fdurand,

> This is what we did before:

Could you remind me (or @lzammit) why this behavior has been changed in https://github.com/inverse-inc/packetfence/commit/8fd86b943667dfd1ba5180f049cb2e74f994965b#diff-8b99f599546e7710d1df6b776d184569 ?

**Comment by nqb** [comment]
As discussed with @fdurand, behavior has been changed because sometimes Unifi controller were not yet aware of clients when it received an `authorize-guest` command (due to asynchronous exchanges between AP and Unifi controller). Consequently, on PF side, client was not link to any site.

Solution: try first to deauthenticate with old logic and use current logic if site is undef.

**Comment by fdurand** [comment]
Try that: https://github.com/inverse-inc/packetfence/commit/9ae2bd44dc78b045c531b18b5b4e91d65c46236a

**Comment by nqb** [comment]
Hello @fdurand,

Thanks for you code.

Take a look at last answers to my [Unifi post](https://community.ui.com/questions/authorize-guest-command-permit-to-allow-any-clients-from-any-AP-without-verification/5d9bd04c-17f5-4e57-93fd-d46131304967#answer/67861ae4-3a33-4939-bb42-13d3b6fe6ab4)

In short, @leonardogyn explained that we can overcome delay between AP and Unifi controller by enabling STUN protocol.
