### ISSUE TITLE
httpd.admin module not starting after upgrade from v4.7.0 to v5.0.0

### ISSUE THREAD

**Issue by aramores** [inverse-inc/packetfence#482]
Hello,

I recently upgraded packetfence in our Debian Wheezy test server from v4.7.0 to v5.0.0, following the upgrading steps of your guide, but I'm getting an error when I try to start the packetfence application, the httpd.admin module does not start. I get the following error:
![httpd admin error](https://cloud.githubusercontent.com/assets/11995542/7204153/53b924f6-e520-11e4-83ab-b317049e6654.JPG)

I've looked for the file Fingerprints.pm and it does exist:
![fingerprints pm](https://cloud.githubusercontent.com/assets/11995542/7204185/894437a0-e520-11e4-8eac-49b9e9313a69.JPG)

I've also checked the line 69 in the httpd.admin file and this is what it looks like:
![httpd admin file](https://cloud.githubusercontent.com/assets/11995542/7204354/b526645a-e521-11e4-8cd2-08fcd6ac8634.JPG)

Could there be a problem with the path in the httpd.admin file?

Thanks, and best regards.

**Comment by louismunro** [comment]
Please use the mailing list for support questions.

**Comment by louismunro** [comment]
Maybe closing this was a bit hasty.
We'll have a look at it. 
The mailing list should still be the first place to ask questions before opening an issue.

**Comment by dwlfrth** [comment]
@aramores : This can be easy fixed by removing the file. For an unknown reason, the file is being kept after an upgrade even if no longer in the sources (was removed since we now use Fingerbank).

So, simply 
rm /usr/local/pf/html/pfappserver/lib/pfappserver/Controller/Config/Fingerprints.pm

We do look at make it part of the packaging since it should be the default behavior.

**Comment by aramores** [comment]
Sorry if this wasn't the correct place to leave the bug report.

Removing the file fixed the problem, now the httpd.admin module loads properly.

Thanks.

**Comment by louismunro** [comment]
You were actually right. 
This is an issue with packaging on Debian and Ubuntu.

**Comment by fdurand** [comment]
Fixed in 22d9bed7179f64b8224550d6abd6e5dc15e415fe
