### ISSUE TITLE
web admin: unable to display role for each user in Users menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4823]
In Users menu, if you want to display the role for each of your users, you can't.

**To Reproduce**
1. Go to 'Users' menu
2. Click on 'Visible columns'
=> Role is missing.

**Expected behavior**
Visible columns should contain `Role` like for Nodes.

**Additional context**
`/api/v1/users` doesn't contain `category_name` for now.

**Comment by satkunas** [comment]
@jrouzierinverse `category_id` is an invalid field

```
/usr/local/pf/sbin/pfperl-api get -M GET "/api/v1/users?cursor=0&limit=25&fields=pid,category_id&sort=pid" |  jq ''
{
  "errors": [
    {
      "message": "category_id is an invalid field"
    }
  ],
  "message": "Invalid column(s) defined",
  "status": 422
}
```
