### ISSUE TITLE
[Packetfence 9.1] Barracuda NG firewall SSO SSH fail

### ISSUE THREAD

**Issue by centrasupport** [inverse-inc/packetfence#4828]
**Describe the bug**

The Barracuda NG firewall SSO is created in the PF section "Integration" - "Firewall SSO" - "BarracudaNG" as per the doc of packetfence.
The barracuda firewall does not receive any User information.
Checked the Barracuda NG firewall log, the PF does try to connect the firewall but it is not success connection.
The NG firewall log shows
"sshd: Connection from 192.168.10.20 port 60610 on 172.10.1.251 port 22"
"sshd: Did not receive identification string from 192.168.10.20 "

Here, 192.168.10.20  is the packetfence mgmt interface IP;
172.10.1.251 is the barracuda firewall mgmt interface IP.

The below are the logs from packetfence:

Sep 25 09:45:48 NAC-01 pfqueue: pfqueue(4882) INFO: [mac:8c:80:10:11:67:0c] Request to /api/v1/firewall_sso/update is unauthorized, will perform a login (pf::api::unifiedapiclient::call)
Sep 25 09:45:54 NAC-01 pfqueue: pfqueue(4881) INFO: [mac:8c:80:10:11:67:0c] Sending a firewall SSO 'Update' request for MAC '8c:80:10:11:67:0c' and IP '192.168.0.52' (pf::firewallsso::do_sso)
Sep 25 09:45:55 NAC-01 pfqueue: pfqueue(4881) INFO: [mac:8c:80:10:11:67:0c] Request to /api/v1/firewall_sso/update is unauthorized, will perform a login (pf::api::unifiedapiclient::call)

Hope this can be solved, thank you.

**Comment by centrasupport** [comment]
Barracuda firewall is version 7.2.4-186

**Comment by centrasupport** [comment]
Sep 27 11:00:06 NAC-01 pfsso[2470]: t=2019-09-27T11:00:06+1000 lvl=eror msg="Error while sending SSO to ssh: must specify HostKeyCallback: %!s(MISSING)172.10.1.251" pid=2470 request-uuid=2589682c-e0c2-11e9-a3fd-000c294b48a6 username=test@mail.com ip=10.79.101.209 mac=66:a7:2d:6f:30:87 role=guest

**Comment by centrasupport** [comment]
This may help fix this bug

[x/crypto/ssh: Failed to open ssh connection to the server: ssh: must specify HostKeyCallback]
https://github.com/golang/go/issues/20200

https://github.com/jilieryuyi/ssh-simple-client/blob/master/main.go

**Comment by centrasupport** [comment]
changed this file  /usr/local/pf/go/firewallsso/barracudang.go

        sshConfig := &ssh.ClientConfig{
                User: fw.Username,
                Auth: []ssh.AuthMethod{
                        ssh.Password(fw.Password),
                },
                **HostKeyCallback: ssh.InsecureIgnoreHostKey(),**

        }

And reboot the server, but it is still not good.

the log:

Cannot connect to BarracudaNG: ssh: must specify HostKeyCallback

**Comment by smilehat** [comment]
noone cares?

**Comment by julsemaan** [comment]
Did you recompile pfhttpd after changing what you changed in barracudang.go ?

Its not interpreted like perl code anymore, its a compiled binary

**Comment by centrasupport** [comment]
> Did you recompile pfhttpd after changing what you changed in barracudang.go ?
> 
> Its not interpreted like perl code anymore, its a compiled binary

sorry I don't know how to compile it ...

**Comment by nqb** [comment]
Hello @centrasupport,

Take a look at [go/README.md](https://github.com/inverse-inc/packetfence/blob/maintenance/9.1/go/README.md).

**Comment by centrasupport** [comment]
> Hello @centrasupport,
> 
> Take a look at [go/README.md](https://github.com/inverse-inc/packetfence/blob/maintenance/9.1/go/README.md).

Thxs, I will take a look.

**Comment by centrasupport** [comment]
> Hello @centrasupport,
> 
> Take a look at [go/README.md](https://github.com/inverse-inc/packetfence/blob/maintenance/9.1/go/README.md).

sorry, I still don't understand how to do this.... should I just compile the SSO module?

**Comment by julsemaan** [comment]
No, you need to recompile pfhttpd and install it as described in the README

See the following section:
https://github.com/inverse-inc/packetfence/blob/maintenance/9.1/go/README.md#building-the-code

And don't forget the 2 sections before to setup the environment and the dependencies

**Comment by thijsvdc** [comment]
Hi @julsemaan ,

I'm having the same issue. I'm quite new to "go", and I'm afraid the README is clear for me.
I'm stuck here: https://github.com/inverse-inc/packetfence/blob/maintenance/9.1/go/README.md#pulling-the-dependencies

` cd $GOPATH/src/github.com/inverse-inc/packetfence/go`
 `govendor sync`
`yum install ipset-devel`

"govendor sync" throws:

`
/go/src/github.com/inverse-inc/packetfence/go# govendor sync
Error: Vendor file at "vendor" not found.
`
Any idea what I'm missing?

**Comment by nqb** [comment]
@thijsvdc, which version of PacketFence are you running ? 

`go` version has been updated with [PacketFence v9.2](https://github.com/inverse-inc/packetfence/blob/devel/NEWS.asciidoc#version-920-released-on-2019-11-26). Check latest instructions available in our [Developers guide](https://packetfence.org/doc/PacketFence_Developers_Guide.html#_golang_environment). Link provided by @julsemaan was related to PacketFence 9.1 version.

**Comment by thijsvdc** [comment]
@nqb thanks, I'm indeed running 9.3.
I can confirm that after recompiling pfhttpd with the below changes, Barracuda firewall SSO now works correctly:

```
sshConfig := &ssh.ClientConfig{
            User: fw.Username,
            Auth: []ssh.AuthMethod{
                    ssh.Password(fw.Password),
            },
            HostKeyCallback: ssh.InsecureIgnoreHostKey(),
}
```

**Comment by nqb** [comment]
Hi @thijsvdc,

Do you want to make a PR for this change ?

**Comment by thijsvdc** [comment]
@nqb well, I think I just created my first-ever PR :)
