### ISSUE TITLE
Fingerbank only partially profiling device

### ISSUE THREAD

**Issue by aced11** [inverse-inc/packetfence#4831]
**Describe the bug**
I am running packetfence 9.0.1 and have a small issue with fingerbank's profiling capability. I have fingerbank fully configured with my API key/account and DHCP listening for forwarded requests.

When I initially plugin a device or connect over the wireless, registration/authorization occurs, and the fingerbank info is only partially filled out on the Node's profile (usually "uknown" and the fingerprint). Once I click "Refresh Fingerbank" the device is successfully profiled.

Below is what I noticed, a /endpoint_data/mac/details request is made when clicking "Refresh Fingerbank" for the node, opposed to the initial request without it. I'm not getting any errors in the packetfence.log or fingerbank.log that look out of place.

Initial fingerbank lookup (when first DHCP listener is received/registration):
Sep 25 20:03:58 pa-pfnac-01 fingerbank-collector: [GIN] 2019/09/25 - 20:03:58 | 200 | 96.28µs | 127.0.0.1 | GET /endpoint_data/00:00:00:00:00:00

Fingerbank lookup when clicking "Refresh Fingerbank" under Node page:
Sep 25 20:07:16 pa-pfnac-01 fingerbank-collector: [GIN] 2019/09/25 - 20:07:16 | 200 | 69.576µs | 127.0.0.1 | GET /endpoint_data/00:00:00:00:00:00
Sep 25 20:07:16 pa-pfnac-01 fingerbank-collector: [GIN] 2019/09/25 - 20:07:16 | 200 | 155.474µs | 127.0.0.1 | GET /endpoint_data/00:00:00:00:00:00/details

**To Reproduce**
1. Go to Nodes (after device is successfully registered)
2. Click on any registered active node
3. View Node fingerbank page
4. See lack of  populated fingerbank info
5. Click on "refresh fingerbank"
6. Reload page via browser to see updated fingerbank info

**Screenshots**
*After initial device registration/audit log entry*
<img width="749" alt="fb_initial" src="https://user-images.githubusercontent.com/53785606/65649886-63b03b00-dfd6-11e9-90d7-2fd32587f582.PNG">

*After clicking "Refresh Fingerbank" under Node -> Fingerbank*
![fb_refresh](https://user-images.githubusercontent.com/53785606/65649887-63b03b00-dfd6-11e9-8422-41615fb80a6e.png)

**Expected behavior**
Full device profiling to be performed initially instead of after manually clicking "Refresh Fingerbank" on the node. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium

**Additional context**

**Comment by nqb** [comment]
Hello, are you running PF 9.0.1 with latest maintenance patches ?

**Comment by julsemaan** [comment]
From what I recall this was a bug about DHCP filters fixed by 6a27442671a3d26f4bca3d32bfd9e6959352d097 which is in the maintenance.

Apply @nqb's suggestion and retry and it should work fine (run `/usr/local/pf/addons/pf-maint.pl` + reboot)

**Comment by julsemaan** [comment]
I'll close this for now since its already fixed, reopen if necessary

**Comment by aced11** [comment]
Thank You both, that fixed it.

Have a good day!
