### ISSUE TITLE
PacketFence 8.3.0 - Problem to add a new SAML Source

### ISSUE THREAD

**Issue by jp-morvan** [inverse-inc/packetfence#4833]
**Describe the bug**
I want to register a new SAML source and when I use it in captive portal, I've the error :

Caught exception in captiveportal::Controller::Root->dynamic_application “Can't create Single-Sign-On URL : The identifier of a provider is unknown to #LassoServer. To register a provider in a  #LassoServer object, you must use the methods lasso_server_add_provider() or lasso_server_add_provider_from_buffer().”

I followed informations here : https://packetfence.org/doc/PacketFence_Administration_Guide#_saml_authentication

It works for another SAML Source we use from a long time now.

I use this SAML Source in a captive portal

**Screenshots**
![pf](https://user-images.githubusercontent.com/286342/65697626-89435000-e07b-11e9-8b7c-e6771270971a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 68.1.0esr

**Comment by nqb** [comment]
Hello,

What is the difference between this source and the working source ?

It doesn't seem to be a bug, much more a configuration issue. 

We prefer to keep this bug tracker for bugs and feature requests  and use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for report like you did.

**Comment by jp-morvan** [comment]
Ok, sorry, here is a bug :
when I declare a new source, if I change the location and the name of the metadata file, the other source does not work anymore.
By default, the idp metadata file is located here : /usr/local/pf/conf/ssl/idp-metadata.xml
If, in the configuration, I change it to /usr/local/pf/conf/ssl/metadata.xml or /usr/local/pf/conf/ssl/anotherDirectory/idp-metadata.xml and save it, the saml source doesn't work anymore.

**Comment by jp-morvan** [comment]
And to be more specific, the configurations are exactly the same, just I change the certificate filename and the metadata filename

**Comment by nqb** [comment]
I was not able to reproduce the issue as explained by mail.
