### ISSUE TITLE
very small mac address bug in location tab

### ISSUE THREAD

**Issue by abeulink** [inverse-inc/packetfence#4844]
Hello developers,

I think I found a very small bug in Nodes - MAC Address - Location tab (in Switch/AP column).
The **fourth octet** of mac address is not identical as hardware mac address.
The seventh and eighth character of MAC Address.
After my research, this bug is only in the location tab. 

We use Packetfence version 9.1.0.

**Comment by julsemaan** [comment]
That's the MAC address your vendor provides during the RADIUS authentication. They often don't make it the same as the hardware MAC and sometimes also generate one per BSSID

That's not a PF bug, that's one of your vendor's "features"
