### ISSUE TITLE
Support ipset 7.1 version for Golang binaries

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4845]
**Is your feature request related to a problem? Please describe.**
Current CentOS 7.7 version are shipped with ipset 7.1 version. Our Golang binaries doesn't support yet this version (still on 6.38). 

**Describe the solution you'd like**
Support ipset 7.1 version in Golang binaries. We certainly need to adapt https://github.com/inverse-inc/go-ipset to support this new version like we did in the past:
* https://github.com/inverse-inc/go-ipset/commit/0a0972e5af167061ebab363a87b643dc508d9b43
* https://github.com/inverse-inc/go-ipset/commit/3b787d33ec19ef4e074fed7fb7eacb86c4744261

or take a look at https://github.com/digineo/go-ipset/tree/v2 as suggested by @salted in https://github.com/digineo/go-ipset/pull/3

**Describe alternatives you've considered**
@julsemaan has tried to "statically compiling the binary with ipset or use libipset.so instead of libipset.XX.0.so (where XX is a version) so that it can use any version installed on the system" without success (see https://github.com/inverse-inc/packetfence/issues/4776#issuecomment-534142406)

**Comment by jrouzierinverse** [comment]
Fixed by 24b38f28a8dfc8d6696375a4ea054d78dc8eeb46
