### ISSUE TITLE
Inline layer 2: Network filter on connection profil broken

### ISSUE THREAD

**Issue by Ieno77** [inverse-inc/packetfence#4849]
conf/profil.conf:
````
[inline]
locale=
sources=null
filter=network:172.21.121.0/24
````

**Comment by jrouzierinverse** [comment]
What is the setup of PacketFence server?
The network filter itself works https://github.com/inverse-inc/packetfence/blob/devel/t/unittest/Portal/ProfileFactory.t#L41 

It sounds like the locationlog for the node is incorrect or has the wrong IP address.
Can you verify the node's ip address in the locationlog.

**Comment by julsemaan** [comment]
The node's IP address should be taken from ip4log, not locationlog

**Comment by jrouzierinverse** [comment]
Can I close this?

**Comment by jrouzierinverse** [comment]
I never received any feedback on this issue.
Has this been able to be replicated anywhere?

**Comment by extrafu** [comment]
Let's close this for now.
