### ISSUE TITLE
Change of request user-agent switches node from pending back to unreg

### ISSUE THREAD

**Issue by sinusoidal-zz** [inverse-inc/packetfence#485]
Tested with PF 4.5.1, found while investigating an issue with an indefinite 'pending' state.  Since found related bug https://github.com/inverse-inc/packetfence/pull/446  Can't find any duplicate bugs in the tracker.

Once a device requests a pin code and goes into 'pending' state, if a different browser or background/tray application makes a request with a different user-agent, the 'pending' state switches back to 'unreg'.  The result is that if the browser is closed and re-opened, rather than sending the user back to the 'enter your pin' page, they are returned to the beginning of registration.

That aside, I also discovered that a user can only go to the 'enter your pin' page once, after which they are also returned to unreg state.  I'd have thought the expected behaviour after a pin has been requested is that the mac address would _always_ be returned to the 'enter your pin' page, as many times as necessary (multiple browser closes), unless they specifically click the 'I haven't received a pin' link, or unless the pin has expired in the 'activation' table (default I think is 1 hour).

Steps to reproduce:
- Enter details on registration page, receives a pin code, device switches to 'pending' state in db.  User may close browser by mistake, or their device may force a browser close to retrieve the text message (apple devices do this).
- Before the user enters the pin code, a background/tray app/windows update tries to reach web, and changes user agent in db.  Device automatically switches back to 'unreg' (incorrect behaviour)
- User opens browser to input pin code but is returned to the registration page rather than to the 'enter your pin' page.

Example anonymised log entries:

Browser request: (device browser request, state might be pending)
Apr 17 15:01:31 httpd.portal(4339) INFO: [xx:xx:xx:5b:01:e4] Updating node user_agent with useragent: 'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko' (captiveportal::PacketFence::Controller::CaptivePortal::nodeRecordUserAgent)

Background app:  (device is returned to unreg)
Apr 17 15:01:32 httpd.portal(4301) INFO: [xx:xx:xx:5b:01:e4] Updating node user_agent with useragent: 'Microsoft-CryptoAPI/6.3' (captiveportal::PacketFence::Controller::CaptivePortal::nodeRecordUserAgent)

**Comment by julsemaan** [comment]
Could you post the log following the user agent change, so we can see the device unregisering and what happens afterwards.

Thanks !

**Comment by sinusoidal-zz** [comment]
I don't believe there was a log entry in packetfence.log showing the device going to unreg.  I was watching the node table in the database at the time, and observed the 'status' field switching to 'unreg' as soon as I forced a request from a client with a different user agent (I could also observe the user agent change in the node table).  I'll check but I don't recall seeing any additional lines come up in the packetfence.log other than the detection of the user agent change above (I was tailing the packetfence.log in debug mode at the time).

**Comment by sinusoidal-zz** [comment]
Attached is an anonymised mysql debug log dump of the transaction.  The node is changed to 'pending' at line 142 with user agent 'Microsoft NCSI', and then on line 301 it reverts back to 'unreg' with user agent 'Microsoft-CryptoAPI/6.1'. all within the space of a few seconds.

**Comment by sinusoidal-zz** [comment]
Forgot I couldn't attach files here, see pastebin here http://pastebin.com/6xeXbDLu

**Comment by julsemaan** [comment]
Could you send me the output of logs/pfmon.log during the minutes after that device is in pending.

Also try to disable the device when it gets in pending and wait a few minutes to see what happens. I want to see if it's really related to the user agent change.

Thanks !

**Comment by julsemaan** [comment]
@dwlfrth has an idea of what it can be.
Re-assign me if you don't find it

**Comment by dwlfrth** [comment]
PR #501 should fix it... waiting for review
