### ISSUE TITLE
Radius Disconnect with Juniper EX2200_v15

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#4850]
Hello when I try to Reevaluate  Access on a Node on Juniper EX2200_v15, it fail with this log:

`Oct 12 16:55:45 pf pfqueue: pfqueue(1318) INFO: [mac:c4:2f:90:1e:5d:6e] deauthenticating c4:2f:90:1e:5d:6e (pf::Switch::Juniper::EX2200_v15::radiusDisconnect)`
`Oct 12 16:55:45 pf pfqueue: pfqueue(1318) WARN: [mac:c4:2f:90:1e:5d:6e] Unable to perform RADIUS Disconnect-Request: must specify key and code at /usr/local/pf/lib/pf/Switch.pm line 3203. (pf::Switch::Juniper::EX2200_v15::catch {...} )`

**Comment by jrouzierinverse** [comment]
Which version of PacketFence is this?

**Comment by jrouzierinverse** [comment]
Thank you for reporting this.

You can get this fix and all the other latest fixes by running pf-maint.pl

```bash

cd /usr/local/pf

# Get the latest fixed
./addons/pf-maint.pl

# Run it twice since pf-maint.pl was patched recently
./addons/pf-maint.pl

# Restart PacketFence
./bin/pfcmd service pf restart

```
Or you can manually apply the patch by doing the following.
```bash
cd /usr/local/pf

curl https://github.com/inverse-inc/packetfence/commit/d92ce62502b85d2c956a57c465fbf536e301bebe.diff> d92ce62502b85d2c956a57c465fbf536e301bebe.diff

# Do a dry run to make sure everything is ok.
patch -p1 --dry-run < d92ce62502b85d2c956a57c465fbf536e301bebe.diff

# If everything is good then do it for real
patch -p1 < d92ce62502b85d2c956a57c465fbf536e301bebe.diff

# Restart PacketFence
./bin/pfcmd service pf restart

```

**Comment by lyubomirtraykov** [comment]
Everything is working OK now, thanks.
I noticed that in the Audit Log on Disconnect-ACK there is no MAC address, Node Status , Computer name and User name. With EX2300 the information is available in the  Audit Log.

**Comment by jrouzierinverse** [comment]
@julsemaan do you have an idea why this is happening?

**Comment by julsemaan** [comment]
Not really, perhaps @fdurand has an idea on the Disconnect ACK audit log

My wild guess is that not all the fields of the audit log entry are populated during the Disconnect ACK, perhaps we could hide the ones we're not populating

**Comment by lyubomirtraykov** [comment]
The problem is that there is no:
Calling-Station-Id Attribute in the request.

**Comment by julsemaan** [comment]
@fdurand, could you investigate the issue with the RADIUS audit log + no Calling-Station-Id
