### ISSUE TITLE
Dots in role break switch_group and gives error httpd_admin service

### ISSUE THREAD

**Issue by mofm** [inverse-inc/packetfence#4851]
**Describe the bug**
A role with a name containing a dot ('.') gives errors in  the 'httpd_admin' service. 'switch groups' gives error in the webui.

_Note: **hld.printer** is role name. I deleted it in roles after gives errors. but I'm still getting same errors._

**To Reproduce**
1. **/usr/local/pf/bin/pfcmd version**
`PacketFence 8.3.0`

2. **cat /etc/os-release** 
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
```

3. **systemctl status packetfence-httpd.admin -l**
`admin_catalyst[17816]: httpd.admin(17164) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
 httpd_admin[17816]: httpd.admin(17164) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::SwitchGroup->begin "did not find parent for field hld.printerRole at /usr/share/perl5/HTML/FormHandler/BuildFields.pm line 239." (pfappserver::PacketFence::Controller::Root::end)
httpd_admin[17816]: httpd.admin(17164) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (pfappserver::PacketFence::Controller::Root::end)`

4. **cat /usr/local/pf/logs/httpd.admin.catalyst**
`admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(2351) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(1305) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(17164) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
admin_catalyst: httpd.admin(17164) ERROR: [mac:unknown] Couldn't render template "config/switchgroup/index.tt: file error - config/switchgroup/index.tt: not found" (Catalyst::View::TT::_rendering_error)
`
**Screenshots**
![switch_groups](https://user-images.githubusercontent.com/6769532/66716497-fd4d5a00-edd6-11e9-8843-4214f14a7f42.png)

**Additional context**
I found these issues related to this topic ( #4744 and #925 ).  But I don't think these patches contain this problem.

**Comment by nqb** [comment]
I'm able to create a role called `hld.printer` on PF 9.1.0 without any issue but I used new web admin. If I switched to old web admin and try to display Switch Groups menu, I got same issue as @mofm

**Comment by ACN-DAB** [comment]
In case you hit this bug and have to fix it:
1) Remove role "test.test" in $CONF/roles.conf
2) Remove from the pf database in mysql
   a) select * from node_category; (verify what category_id)
   b) delete from node_category where category_id=xxx;
3) /usr/local/pf/bin/pfcmd configreload hard

**Comment by nqb** [comment]
I created a new issue for this problem, see #6018

**Comment by nqb** [comment]
Has been fixed by https://github.com/inverse-inc/packetfence/commit/5e975a6049d9ac75210ebbf52fe086b836d35250
