### ISSUE TITLE
web admin: Download Service Provider metadata button is missing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4856]
In new web admin, on SAML sources, button "Download Service Provider metadata" is missing.

**To Reproduce**
1. Create a SAML source
2. Save your source

=> Button is missing.

**Expected behavior**
You should have a button "Download Service Provider metadata" after you save your source.

**Workaround**
Button still presents in old admin.

**Comment by nqb** [comment]
I assigned @jrouzierinverse and @satkunas because I supposed frontend and backend should be adjust.

**Comment by nqb** [comment]
An important thing to have in mind: 

Now we manage certificates from web admin and server.crt contains server certificate + all intermediates. Consequently, when you click on Download Service Provider metadata button, XML generated will contain full SSL chain in `<ds:X509Certificate>` tags. This seems to cause issue.

**Comment by jrouzierinverse** [comment]
@satkunas I put the new endpoint in the branch  fix/saml_metadata

**Comment by extrafu** [comment]
@satkunas We'll need that bug fixed quickly.
