### ISSUE TITLE
update asciidoctor dependencies in spec

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#4868]
In order to build the HTML documentation you need to have at least asciidoctor 2.0.10.
Our spec does not reflect this.

**Comment by nqb** [comment]
>  Our spec does not reflect this.

Yes, I know. As [I already explained for Golang](https://github.com/inverse-inc/packetfence/pull/4832#issuecomment-535984149), putting things in spec files only make sense when packages are available.

**Comment by jrouzierinverse** [comment]
The exact scenario happened that I was concerned about.
I could not reproduce the issue you were seeing.
As there is no known place for me to refer to fix the problem.
I packaged asciidoctor 2.0.10 for centos.
I will upload them to the OBS soon.

**Comment by jrouzierinverse** [comment]
No longer relevent.
