### ISSUE TITLE
Juniper EX2300 CoA Port Bounce

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#4874]
Hello, It would be nice to implement CoA Port Bounce for EX2300, because the ssh method is very poor. It is supported since 18.1
You can find more info at:
[Juniper CoA Request Port Bounce](https://www.juniper.net/documentation/en_US/junos/topics/topic-map/802-1x-authentication-switching-devices.html#jd0e423)

**Comment by fdurand** [comment]
Isn't it fixed ? or still related to https://github.com/inverse-inc/packetfence/pull/6095 ?

**Comment by lyubomirtraykov** [comment]
Yes it is fixed. It is not related to #6095.
