### ISSUE TITLE
dpsk.html appears to be missing

### ISSUE THREAD

**Issue by shanehull** [inverse-inc/packetfence#4888]
**Describe the bug**
dpsk.html appears to be missing in 9.1.0.

**To Reproduce**
1. Create a DPSK/IPSK provisioner 
2. Log in to the portal/portal preview
4. Receive the following error:

`''' Caught exception in captiveportal::Controller::Root->dynamic_application "Can't generate template provisioner/dpsk.html: file error - provisioner/dpsk.html: not foundError : file error - provisioner/dpsk.html: not found at /usr/local/pf/lib/captiveportal/PacketFence/DynamicRouting/Application.pm line 414." '''`

**Expected behavior**
dpsk.html should be found and display the page.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device:OnePlus 6T
 - OS: Android 10
 - Browser: Chrome

**Additional context**
I can't see the file anywhere under the pf/html directory either.

**Comment by nqb** [comment]
It seems you have same behavior as #3741. Commit https://github.com/inverse-inc/packetfence/commit/a51d02922176047ca26d40433d4c298d06b1938f has removed `ipsk.html`file from directory but I don't see any commit that adds `dpsk.html` back.

@julsemaan, did you want to rename `ipsk.html` to `dpsk.html` and forget to add back `dpsk.html` ?

**Comment by julsemaan** [comment]
@nqb, its very likely this is what happened

**Comment by shanehull** [comment]
@nqb no, it seems like I never had either of them. Running a find for both files in the "pf" directory returns nothing. This is a fresh install of 9.1.0.

Edit: Nevermind, I just realised you were talking to @julsemaan  :D

**Comment by julsemaan** [comment]
Added it back in 29784811ae20440c4033055f053936e3453892f3 and cherry-picked up to maintenance/8.1 (release on which DPSK it was introduced)
