### ISSUE TITLE
Multiple IPs on ZEN result in invalid output for admin interface location

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4893]
When you have more than 1 valid IP address on a ZEN machine it will display all the IPs as accessible for the admin. We should instead intelligently detect the admin network interface if possible and fallback to the first one otherwise for our output

**Comment by nqb** [comment]
> When you have more than 1 valid IP address on a ZEN machine

What does "valid" mean ?

> We should instead intelligently detect the admin network interface

Do you mean detect the default network interface ?
