### ISSUE TITLE
Error when adding/removing interface

### ISSUE THREAD

**Issue by Ieno77** [inverse-inc/packetfence#4897]
When adding or removing interface on the gui, I got this error;

````
ERROR pfperl-api(4889): Can't locate object method "id" via package "pf::UnifiedApi::Controller::Config::Interfaces" at /usr/local/pf/lib/pf/UnifiedApi.pm line 106.
    (Mojolicious::Plugin::DefaultHelpers::_development)

````
Even if the error appear, if I refresh the gui the modification appear correctly.

Packetfence version: packetfence-9.1.9-20191106084038.93997110.devel.olab.el7.x86_64

**Comment by nqb** [comment]
Able to reproduce the issue on nightly builds.

**Comment by jrouzierinverse** [comment]
fixed
