### ISSUE TITLE
Devel: Can't save rule with unregistration date

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4899]
Rule created on a AD source.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/5261214/68335462-7d9b6e00-00aa-11ea-9015-f52709f5fa1d.png">

<img width="455" alt="image" src="https://user-images.githubusercontent.com/5261214/68335518-9a37a600-00aa-11ea-9d44-74b27e8dd133.png">

**Comment by cgx** [comment]
@jrouzierinverse I can fix the frontend, but could we use a standard syntax ([set_unregdate](https://github.com/inverse-inc/packetfence/blob/devel/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module.pm#L74) vs [set_unreg_date](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Authentication/constants.pm#L162))?

**Comment by jrouzierinverse** [comment]
set_unreg_date
