### ISSUE TITLE
Default connection profile is disabled by default

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4900]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/5261214/68337738-251a9f80-00af-11ea-9c23-7153f175b881.png">

**Comment by lzammit** [comment]
Update, all connection profiles look like this:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/5261214/68403730-66f92380-014b-11ea-9eb2-3272ca50fa46.png">

But they do work as they were enabled.

**Comment by jrouzierinverse** [comment]
This seems to be an issue on the frontend.
As the profile status is set in the response.

**Comment by satkunas** [comment]
This should have been fixed in https://github.com/inverse-inc/packetfence/commit/1694b5ef43fe54c54149997453cbe01c22d5d85b

**Comment by satkunas** [comment]
@lzammit please retest and close if all-is-good.
