### ISSUE TITLE
API - Admin Audit Log - Request column not compressed

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4905]
**Describe the bug**
The table `admin_api_audit_log` should utilize either table compression, or the `request` column should be type `BLOB` and used with `COMPRESS()` and `UNCOMPRESS()`. Currently bulk CSV imports can consume a lot of unnecessary disk space. Since we don't need to query (or index) the `request` column then compression would be ideal.

If we need to keep the `request` column readable without `UNCOMPRESS()` we could use a derived virtual column for uncompressed output (see my next comment).

-----

With 645 rows of data I only use 14% of the previous disk space w/ a compressed column.

**Before**
-rw-rw---- 1 mysql mysql  4194304 Nov  7 17:58 admin_api_audit_log.ibd

**After**
-rw-rw---- 1 mysql mysql   606208 Nov  7 17:51 admin_api_audit_log.ibd

**Comment by satkunas** [comment]
Here's the statements I used to modify the table:
```sql
alter table admin_api_audit_log add column request_compressed MEDIUMBLOB after request;
update admin_api_audit_log set request_compressed=COMPRESS(request);
alter table admin_api_audit_log drop column request;
alter table admin_api_audit_log add request text GENERATED ALWAYS AS (UNCOMPRESS(request_compressed)) VIRTUAL after request_compressed;
```

The subsequent schema:
```sql
CREATE TABLE `admin_api_audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_name` varchar(255) DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `object_id` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `method` varchar(10) DEFAULT NULL,
  `request_compressed` mediumblob,
  `request` text AS (UNCOMPRESS(request_compressed)) VIRTUAL,
  `status` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `action` (`action`),
  KEY `user_name` (`user_name`),
  KEY `object_id_action` (`object_id`,`action`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=646 DEFAULT CHARSET=latin1
```

I chose MEDIUMBLOB because it gives us up to 4MB. BLOB is only 64KB, and LONGBLOB is 4GB. It seemed like the ideal size.

We'll need to ensure that the BLOB column is not corrupted when dumped to backup and subsequently restored. There are some special mysqldump flags that will ensure this.

**Comment by satkunas** [comment]
With only 645 rows I only use 14% of the previous disk space w/ the compressed column.

**Before**
-rw-rw---- 1 mysql mysql  4194304 Nov  7 17:58 admin_api_audit_log.ibd

**After**
-rw-rw---- 1 mysql mysql   606208 Nov  7 17:51 admin_api_audit_log.ibd

**Comment by julsemaan** [comment]
If we want to do this, then now is the time before we release the initial version of the table in the wild

@jrouzierinverse and @satkunas, make sure you have the necessary discussions so we can do the change today (nov 8th) if necessary before we start testing 9.2 4 the realz

**Comment by satkunas** [comment]
@jrouzierinverse additionally, the `status` column should be reduced as there's no need to store anything < 0 or > 499. So a SMALLINT should suffice.

```sql
alter table admin_api_audit_log modify status smallint unsigned not null;
```

**Comment by satkunas** [comment]
@jrouzierinverse  is the `user_name` the same as the `pid` column from the `persons` table? If so, should we not utilize the same column name?

```sql
alter table admin_api_audit_log modify user_name pid varchar(255) default null;
```

**Comment by satkunas** [comment]
@jrouzierinverse since the `user_name` and `request` columns can contain utf8, the table should support this encoding/charset.

```sql
ALTER TABLE admin_api_audit_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
```

**Comment by satkunas** [comment]
Schema optimized with https://github.com/inverse-inc/packetfence/commit/c26270d64718b06daf26c6f612bf78e017d4c7af
