### ISSUE TITLE
Improve Label

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4914]
**Describe the bug**
Form label uses the key name. A more descriptive label is needed for the user.

https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationNetwork.js#L115-L127

**Screenshots**
![Selection_067](https://user-images.githubusercontent.com/3904468/68620121-d6984700-049a-11ea-8a44-2603f633a71b.png)

**Comment by cgx** [comment]
We should overwrite the string in the [source translation](https://github.com/inverse-inc/packetfence/blob/devel/conf/I18N/api/en.po#L12938).

**Comment by julsemaan** [comment]
This needs to go in maintenance/9.0 and maintenance/9.1

**Comment by satkunas** [comment]
@julsemaan done
