### ISSUE TITLE
Multiples authentication sources in Authentication::Login module issue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4918]
**Describe the bug**
Multiples authentication sources in Authentication::Login module doesn't permit to see it in the captive portal choice.

**To Reproduce**
Create a portal module root + choice + Authentication::Login (2 login sources inside)
Assign it to a connection profile and hit preview, the module is not visible.
Remove one source from the Authentication::Login module and hit one more time the preview, the choice is here.

**Expected behavior**
Supposed to see the login option

**Desktop (please complete the following information):**
Chrome - Firefox
Windows - Ubuntu

**Comment by julsemaan** [comment]
The sources are being saved as an array instead of comma separated values.

@jrouzierinverse performed some changes in the multi-source handling in the form after 9.1 for another issue. I'll check that with him

Here is what it is:
```
source_id= <<EOT
inverse
inverseinc
EOT
```
Here is what it should be:
```
source_id=inverse,inverseinc
```

**Comment by jrouzierinverse** [comment]
@julsemaan please retry.

**Comment by julsemaan** [comment]
This works now but I'm unable to clear the authentication sources in the portal module. I'll open a separate issue.

Also will let @fdurand test that his original case does work correctly now

**Comment by jrouzierinverse** [comment]
What do you mean by clear the portal modules?

**Comment by julsemaan** [comment]
Was me writing too fast, I fixed my comment and opened another issue for this (#4920)

**Comment by extrafu** [comment]
Use that to make everything crystal clear:

![image](https://user-images.githubusercontent.com/1616141/68704362-30137b00-055a-11ea-963c-029d0649d257.png)

**Comment by fdurand** [comment]
tested and worked.

**Comment by julsemaan** [comment]
Reminds me of this: https://www.youtube.com/watch?v=yPCIsIJ7nhY
