### ISSUE TITLE
Add support for Mikrotik RB751U-2HnD

### ISSUE THREAD

**Issue by qarqun** [inverse-inc/packetfence#492]
really appreciate if packetfence can support Mikrotik RB751U-2HnD (Router OS v6.28).
Right now, pf got Mikrotik module but only tested with Access Point OmniTIK U-5hnD (Router OS v6.18).

i hope that somebody can add support this ap model and provide detail config guide on this. 
i have some issue that dynamic vlan assignment doesn't work properly.

Thanks!

**Comment by qarqun** [comment]
anyone?

**Comment by SailorMercury** [comment]
having the same problem here

**Comment by julsemaan** [comment]
I believe we weren't able to get this to work properly due to a lack of functionality of the Mikrotik

Can @fdurand or @lzammit who worked on that confirm so we can close

**Comment by fdurand** [comment]
Can you test with that:
https://github.com/inverse-inc/packetfence/issues/4635
