### ISSUE TITLE
Unable to remove authentication sources in login portal module

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4920]
**Describe the bug**
I'm unable to remove all the authentication sources of a portal module

**To Reproduce**
1. Create an Authentication::Login portal module and specify a couple of authentication sources
2. Save that portal module
3. Clear the authentication sources
4. Save that portal module
5. Refresh the page and the authentication sources are still there

**Additional context**
From what I can tell the API call is correct (has multi_source_ids:[]) so I'll assign to @jrouzierinverse

**Comment by jrouzierinverse** [comment]
@julsemaan please retry.

**Comment by jrouzierinverse** [comment]
@fdurand can you test this?

**Comment by satkunas** [comment]
I'm unable to reproduce.

**Comment by jrouzierinverse** [comment]
Should we close this then?

**Comment by extrafu** [comment]
If it's not reproducible, let's close it.
