### ISSUE TITLE
Eduroam Radius in Clustermode is not listening on VIP

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#4921]
**Describe the bug**
If you run PacketFence 9.1.0 (with all Maintenance patches installed) in clustermode, radius server for edurom isn't listen on VIP. 

After upgrading from 8.3.0 to 9.1.0 we had to add a single cluster-node as radius server on our wireless infrstructure for getting it working again. 

Raddebug showes no auth informations coming in on VIP.

**Expected behavior**
Eduroam radius instance shoud listen on VIP and port 11812 too and not only on management IP of the cluster nodes.

**Comment by fdurand** [comment]
Tested and not able to replicate.
Did you restarted packetfence-radiusd-load_balancer.service ?

**Comment by Venice-89** [comment]
We will test it again, maybe its caused by an issue while migrating to 9.1 
(fixed in Support ticket 0008196)

We just applied the changes of  /usr/local/pf/raddb/policy.d/packetfence on one of our cluster nodes because we thought it's replicated to the other nodes, like files in /usr/local/pf/conf

**Comment by Venice-89** [comment]
Mhhh no success


No logs for that connection on packetfence cluster nodes (no log in radius)

**Node is listening on correct port**

```
[root@pf-1 logs]# netstat --listen | grep 11812
udp        0      0 pf.bs.fraunhofer.:11812 0.0.0.0:*
udp        0      0 pf-1.bs.fraunhofe:11812 0.0.0.0:*

```

**IP Tables rule is correct**

```
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:11812
ACCEPT     udp  --  anywhere             anywhere             udp dpt:11812

```
**Server is receiving packages from AeroHive AP**

```
[root@pf-1 logs]# tcpdump -i eth1.42 src 10.130.22.27
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1.42, link-type EN10MB (Ethernet), capture size 262144 bytes
16:47:49.037049 IP 10.130.22.27.47257 > pf.bs.fraunhofer.de.11812: UDP, length 289
16:48:05.755013 IP 10.130.22.27.47257 > pf.bs.fraunhofer.de.11812: UDP, length 289
```


But is rejecting the request:
**Log from Aerohive**

```
11/28/2019 04:35:01 PM  80B03D1CC251  C413E2120A14  ID3707       DETAIL  (8)Send message to RADIUS Server(10.130.42.40): code=1 (Access-Request) identifier=0 length=289,  User-Name=eduroam@firma.de Called-Station-Id=C4-13-E2-12-0A-14:eduroam Calling-Station-Id=80-B0-3D-1C-C2-51 NAS-IP-Address=10.130.22.27
11/28/2019 04:35:02 PM  80B03D1CC251  C413E2120A14  ID3707       BASIC   (9)Authentication is terminated (at if=wifi0.1) because it is rejected by RADIUS server

```

`Nov 28 16:50:30 pf-1 load_balancer[4191]: (114650) Login incorrect (No Auth-Type found: rejecting the user via Post-Auth-Type = Reject): [eduroam@firma.de] (from client 10.130.22.27/32 port 0 cli 80-B0-3D-1C-C2-51) - Proxied to:`

Mhhh why is it rejected on VIP and not rejected on Node-IP???
Same configuration, same endpoint, same AP..... 

I didn't see the auth request, because I filtered on MAC-Address and in this logfile, the mac syntax is different from other packetfence logs ;)

**Comment by fdurand** [comment]
Can you try that:
https://github.com/inverse-inc/packetfence/commit/4fe5bb42d9d39767dbb19b743759504943ae517c

**Comment by Venice-89** [comment]
I have applied the patch, I am out of office but a colleague will test it today.

**Comment by Venice-89** [comment]
Hi,

no, same Issue like before.
I applied all maintenance patches on all packetfence nodes and get the same message:

Dec  6 13:45:33 pf-1 load_balancer[26353]: (250) Login incorrect (No Auth-Type found: rejecting the user via Post-Auth-Type = Reject): [anonymous@ads.fraunhofer.de] (from client 10.130.22.27/32 port 0 cli A0-28-ED-83-CA-C4) - Proxied to:

**Comment by fdurand** [comment]
You need to rename conf/radiusd/eduroam-cluster.example to conf/radiusd/eduroam-cluster and restart radius.
Btw there is the PR #4982 who is a better fix.

**Comment by julsemaan** [comment]
So it should work now if you apply the maintenance and rename eduroam-cluster.example to eduroam-cluster and restart radiusd
