### ISSUE TITLE
Status page: Can't unreg a registered device

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4926]
When I click on the unreg button:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/5261214/68785369-16327080-060c-11ea-98e5-9c070b285a60.png">

````
Caught exception in captiveportal::Controller::Node::Manager->unreg "Can't use an undefined value as an ARRAY reference at /usr/local/pf/lib/captiveportal/PacketFence/Controller/Node/Manager.pm line 39."
````

**Comment by julsemaan** [comment]
Should be fixed, re-test and close using a specially formatted numbered list please

**Comment by lzammit** [comment]
Works.
