### ISSUE TITLE
Web admin: Can't assign role to local account

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4928]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/5261214/68792116-b7272880-0618-11ea-9089-b6bb391e231e.png">

I don't have any available option to add a role.

**Comment by lzammit** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/5261214/68799838-e8a6f080-0626-11ea-834e-9e8b6ffcc756.png">

**Comment by cgx** [comment]
I can't reproduce this issue. Are you running devel?

**Comment by nqb** [comment]
Not able to reproduce too running on Debian with devel packages.

**Comment by lzammit** [comment]
Magically fixed
