### ISSUE TITLE
Add #4929 once 9.2 is released

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4930]
Title says it all!

**Comment by nqb** [comment]
See #4932 before merging.

**Comment by julsemaan** [comment]
@nqb, are we safe in putting #4929 in maintenance/9.2 or something in #4932 still prevents this from happening?

**Comment by nqb** [comment]
No more messages on a clean Debian 9 install @julsemaan, you can push to maintenace.

**Comment by julsemaan** [comment]
Done in 53f7a16be9ea9297069a23d71f59519ef7fb735a
