### ISSUE TITLE
web admin: RADIUS audit log entry not clickable on Debian

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4931]
It's not possible to click on a RADIUS audit log entry to display it on Debian.

**To Reproduce**
1. Go to Auditing -> RADIUS Audit logs
2. Try to click on a line
=> Not able to display RADIUS audit log

**Expected behavior**
Open RADIUS audit log entry

**Additional context**
- Admin audit log entry works as expected
- Issue is also presents on a 9.0.1 setup

**Web browser console**
```
Unhandled promise rejection TypeError: t.replace is not a function
Stack trace:
u/<@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:202350
u@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:202306
7c15/</c[t]@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:202565
getRadiusLog@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:363526
getItem@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:366407
_/<@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:23:5559
2f62/</v.prototype.dispatch@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:23:6868
v/this.dispatch@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:23:3249
beforeEnter@https://172.17.1.20:1443/static/alt/js/app.d578e134.js:1:409007
p@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:19558
r@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:15769
r@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:15796
r/<@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:15787
p/<@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:19767
install/v.router/</<@https://172.17.1.20:1443/static/alt/js/chunk-vendors.2b047798.js:34:43146
E/</<@https://172.17.1.20:1443/static/alt/js/Configuration~Editor~Users.e5d10526.js:1:53835
E/<@https://172.17.1.20:1443/static/alt/js/Configuration~Editor~Users.e5d10526.js:1:53703
u@https://172.17.1.20:1443/static/alt/js/Configuration~Editor~Users.e5d10526.js:1:61573
 vue-multiselect.min.js:1:25564
```

**Comment by cgx** [comment]
Can you set [VUE_APP_DEBUG](https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/.env#L3) to `true`, recompile the Javascript code and generate a new stack trace?

**Comment by nqb** [comment]
![Capture d’écran de 2019-11-18 08-13-39](https://user-images.githubusercontent.com/10830260/69031865-5e221080-09db-11ea-9b3f-6c85f09c8cb4.png)

I don't see a real difference with VUE_APP_DEBUG set to `true`. @cgx, let me know if you have enough information to troubleshoot this issue.

**Comment by nqb** [comment]
As discussed, I will need to send content of `static.alt/dist/js`.

I will also check if there is an API call.

Another information: I noticed that `nodejs` is installed automatically when installing PacketFence from official Debian repositories. It seems to be a requirements from one of PacketFence dependencies.

**Comment by nqb** [comment]
@fdurand, any idea about a PF's dependency that depends on nodejs ?

**Comment by nqb** [comment]
@cgx,

I sent you my `dist/js` directory. As discussed, CentOS and Debian packages are both built using Nodejs 12.13.0 installed as distribution packages.

Able to reproduce issue with Chrome:
![Capture d’écran de 2019-11-18 20-22-09](https://user-images.githubusercontent.com/10830260/69082954-7d538900-0a41-11ea-8cb1-6266a4458aa4.png)

I'm able to see following API call: `api/v1/radius_audit_logs?cursor=0&limit=25&fields=created_at,mac,id,auth_status,radius_ip,is_phone,node_status,user_name,uuid,nas_ip_address,nas_port_type&sort=created_at+DESC` but there is no API call made when I click on an entry.

Firefox help for this error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

**Comment by nqb** [comment]
@cgx, I did a build of web admin assets on CentOS and Debian using Nodejs 12.13.0, all files listed [here](https://gist.github.com/nqb/1e39bb617c3f9928682afd3d453bf97f) have same md5sum.

**Comment by nqb** [comment]
and there is not difference between build environments when I run `npm list -g`

**Comment by satkunas** [comment]
@nqb I was unable to reproduce. However, I was missing the `radius_audit_log`.`request_time` and `radius_audit_log`.`radius_ip` columns in my schema. I caught the omission and manually added the missing columns to test. When I removed the `radius_time` column I get an error (similar to yours).

Can you check to see if your missing these column(s) as well? If so, add them and see if you still get errors.

Here's the statements needed to add them:

```sql
  ALTER table radius_audit_log ADD column IF NOT EXISTS request_time int(11) DEFAULT NULL AFTER radius_reply;
  ALTER table radius_audit_log ADD column IF NOT EXISTS radius_ip VARCHAR(45) DEFAULT NULL AFTER request_time;
```

**Comment by nqb** [comment]
Unfortunately @satkunas, these two columns were already present in my table:
```sql
MariaDB [pf]> describe radius_audit_log;
| request_time             | int(11)      | YES  |     | NULL              |                             |
| radius_ip                | varchar(45)  | YES  |     | NULL              |                             |
+--------------------------+--------------+------+-----+-------------------+-----------------------------+
```
I will try on a fresh install and see if I'm able to reproduce.

**Comment by nqb** [comment]
Same behavior under Chrome and CentOS with a fresh Debian 9 installation (9.11 with latest security patches), running today nightly builds.

You will find a RADIUS log entry here: https://gist.github.com/nqb/9c3907deabcc8e11ab517b4463a4f13d

**Comment by nqb** [comment]
@satkunas, @cgx, if you want to replicate this issue, you can follow these instructions to have exactly same environment as me:

https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Developers_Guide.asciidoc#not-so-bleeding-edge

Then in vm `pfdeb9night`: 
```
# install eapol_test
/usr/local/pf/addons/eapol_test/build_eapol_test_debian.sh

# create a eapol_test config file
cat >> tls.config << EOF
network={
ssid="CORPORATE SSID"
key_mgmt=WPA-EAP
eap=TLS
identity="inverse"
ca_cert="/usr/local/pf/raddb/certs/ca.pem"
client_cert="/usr/local/pf/raddb/certs/client.pem"
private_key="/usr/local/pf/raddb/certs/client.key"
private_key_passwd="whatever"
eapol_flags=3
}
EOF
# run a test
eapol_test -c tls.config -s testing123 -a 172.17.1.20 -A 127.0.0.1
```
