### ISSUE TITLE
Local user creation: creates the account without an access duration

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4933]
It tells you that you need to put the unreg date or an access duration but it will create the local account anyway.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/5261214/68897082-c9799300-06fa-11ea-8e1f-5e270c36dca5.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/5261214/68897128-d7c7af00-06fa-11ea-87c4-cc82de3fb37a.png">

**Comment by nqb** [comment]
Able to reproduce this issue.

Issue is not present if you edited an already created user which didn't have a Role but an Access Level

**Comment by satkunas** [comment]
I'm on this
