### ISSUE TITLE
Add an additional daemon on an interface return an error

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4941]
**Describe the bug**
Edit the management interface, add additional daemon then save produce this error:
nov 18 10:03:58 localhost.localdomain packetfence[24807]: ERROR pfperl-api(24807): Can't locate object method "id" via package "pf::UnifiedApi::Controller::Config::Interfaces" at /usr/local/pf/lib/pf/UnifiedApi.pm line 106.                                                   
                                                           (Mojolicious::Plugin::DefaultHelpers::_development)

**Comment by nqb** [comment]
Seems to be a duplicate of #4897

**Comment by jrouzierinverse** [comment]
Please test

**Comment by fdurand** [comment]
fixaid
