### ISSUE TITLE
PFDNS audit log: Does not work when pfdns loose the connection to the db

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4944]
Logs:

I enable the PFDNS audit log and can't see entries.

````
Nov 19 16:07:16 unicorn1 pfdns: [mysql] 2019/11/19 16:07:16 packets.go:112: closing bad idle connection: EOF
````

I had to restart pfdns and it worked.

**Comment by extrafu** [comment]
@fdurand We keep it for v9.2 or not? Last day for any bug fix.

**Comment by fdurand** [comment]
I think we can push it in +1 then it will be in the maintenance
