### ISSUE TITLE
Security event: Autoreg on DHCP fingerprint is not longer working 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4954]
The violation is not triggered for the DHCP fingerprint: 1,121,3,6,15,119,252

conf/security_events.conf:
````
[3000006]
trigger=dhcp_fingerprint::15728
actions=autoreg,role,role,role,role
desc=auto reg iPhones
enabled=Y
access_duration=5D
target_category=staff
````

**Comment by extrafu** [comment]
@jrouzierinverse Please have a look ASAP. It's our last day.

**Comment by jrouzierinverse** [comment]
This seemed to be fixed by f8f938b9d4db672e7ea8d4ae16160488d7ad1e19.
Please re-review

**Comment by extrafu** [comment]
@lzammit Restest ASAP.

**Comment by lzammit** [comment]
I re-tested and it does the same, it does not trigger anything.

**Comment by fdurand** [comment]
worked on my side but it's more an issue with the way to select a dhcp fingerprint in the admin gui.
