### ISSUE TITLE
MemberOf Filter not working

### ISSUE THREAD

**Issue by ev5unleash** [inverse-inc/packetfence#4957]
Hi Everyone,

I'm fairly new to PacketFence so bare with me. Everything is working for the most part except for the memberOf filter under authorization. I believe this is a bug in the current code. I have tried the exact path with equals, and just the group name with contains. I've looked over the configuration multiple times, but the system continues to skip over this rule and just hit my catch all role (checked using pftest). 

**To Reproduce**
1. Connect AD
2. Configure NULL realm with AD
3. Add AD authentication source
4. Add Authentication Rule with condition "memberOf contains <some group name>"
5. Test Authentication with pftest or an actual RADIUS request. You'll find that the rule is skipped over.

**Screenshots**

**Expected behavior**
The user should be placed in a role based upon the authentication rule which takes the memberOf attribute into consideration. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Browser [e.g. chrome, safari]: Version 78.0.3904.108 (Official Build) (64-bit)

I have attached the authentication.conf of my setup.

[authentication.conf.txt](https://github.com/inverse-inc/packetfence/files/3879742/authentication.conf.txt)

**Comment by ev5unleash** [comment]
Version: 9.1.0

**Comment by nqb** [comment]
Hello,

Switch log level from info to debug in `$PF/conf/log.conf.d/httpd.aaa.conf` and restart `httpd.aaa`, you certainly have an issue with your LDAP configuration. `memberof` is working as expected in 9.1.

I'm closing this issue because we want to keep this bug tracker for bugs and features. Feel free to send an email on mailiing list.
