### ISSUE TITLE
Cannot load required JS library: https://X.X.X.X:XXXX/netdata/127.0.0.1/lib/**

### ISSUE THREAD

**Issue by BotDW** [inverse-inc/packetfence#4959]
Hello Guys,
i'm completly new to packetfence. The appliance throws the following error as soon as i try to access the WebGUI on Status or Reports :

> Cannot load required JS library: https://X.X.X.X:XXXX/netdata/127.0.0.1/lib/**

The libary which failed to load varies from 
/perfect-scrollbar-0.6.15.min.js
/dygraph-c91c859.min.js
/d3-4.12.2.min.js

I took a look at what rpm packages are recommended, and i noticed that the perl version i'm using on my CentOS 7.7.1908 is  v5.16.3 instead of v5.6.1.

Also i was told, that there was a unlucky epel update, which probably updated the Libs.
Anyone got idea for a packetfence beginner?
If you need further information, just tell me.

Thanks in Advance!
Moritz

![2019-11-25 10_14_38-PF](https://user-images.githubusercontent.com/58166703/69527420-8b873500-0f6c-11ea-835a-e52bd90aefcd.png)

**EDIT:**

I just switch to the "old Admin view", and there it works just fine.

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of reports.
