### ISSUE TITLE
Roles missing in 'Role mapping by VLAN ID' while editing switches or switch groups (pf 9.0.1)

### ISSUE THREAD

**Issue by bklier** [inverse-inc/packetfence#4976]
**Describe the bug**
After adding a new role at 'Configuration -> Roles', most of the defined roles are missing from 'Configuration -> Policies and Access Control -> Network Devices -> Switches (or Switch Groups)' (see attached screenshot... I have about 250 defined roles... only the first 28 appear in the table...)

**To Reproduce**
1. Go to 'Configuration -> Policies and Access Control -> Network Devices -> Switches (or Switch Groups)' 
2. Select a switch or switch group
3. Click on 'Roles'
4. See (or better, don't see...) all your defined roles

**Screenshots**
Roles at selected switch group
![Roles at selected switch group](https://user-images.githubusercontent.com/1070383/69869761-15f1d080-12ae-11ea-8da3-f4fd51808164.png)

All defined roles... about 250 roles
![All defined roles... about 250 roles](https://user-images.githubusercontent.com/1070383/69870044-e8f1ed80-12ae-11ea-9561-4f92daa3b565.png)

**Expected behavior**
Seeing all defined roles and being able to work with them...

**Desktop (please complete the following information):**
 - OS: Debian Buster (10.2)
 - Browser: Chrome, Firefox, ... doesn't matter

**Comment by julsemaan** [comment]
I believe this issue has been fixed in the maintenance

Apply it running this command twice:
/usr/local/pf/addons/pf-maint.pl

And then restarting all the PF services

Reopen if it doesn't work

**Comment by bklier** [comment]
Thank you, it's working again - at least it's displaying the list again, but editing the form is painfully slow.

**Comment by supportFGT** [comment]
I've a similar issue:
After upgrade 9.2>9.3 on Debian 9 I cannot view my custom ROLES in config menu /switch menu /profiles.....    But roles are present in the database

**Comment by julsemaan** [comment]
@supportFGT 

Please open a new issue with more details instead of reusing this one. Thanks,

**Comment by supportFGT** [comment]
ok
