### ISSUE TITLE
web admin:  wrong value display for a switch after an override

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4979]
When I create a switch from a switch group and I override its `Type` field with a value different from switch group, it works. However, when I want to set back `Type` field to value from switch group, web admin shows value from switch group but `switches.conf` use value from default switch group (Generic).

**To Reproduce**
- Create a new switch group called "my_group" with:
  * description: "my_group"
  * type: `Dell::PowerConnect3424`
- Save
- Edit new switch and set type to `Accton::ES3526XA`
- Save
=> It works
- Edit new switch and remove override on `Type` field
=> Web admin displays `Dell::PowerConnect3424`
- Save
=> `switches.conf` contains `type=Generic`

**Expected behavior**
`switches.conf ` should contains `type=Dell::PowerConnect3424`

**Comment by satkunas** [comment]
Unable to reproduce

Modifying the "switch group" works:
```
[group MySwitcGroup]
description=My switch group
type=Dell::PowerConnect3424
```
Changing the Type on a "switch" from one to another works.

Removing the Type from a "switch" sets the:
```
type=Generic
```
