### ISSUE TITLE
Netgear M-Series not showing old MAC is offline

### ISSUE THREAD

**Issue by aherbach88** [inverse-inc/packetfence#498]
When a new MAC address connects to a port that a MAC previously was on, it is not removing the old MAC from being active in that port on the locationlog.

This has been found occurring on Netgear M4100-D10-POE and M4100-26-POE both running firmware version 10.0.1.28.

**Comment by aherbach88** [comment]
This is occurring on PF 4.5.1.  Also, there is no mention in the log of it checking previous MAC on that port.

**Comment by julsemaan** [comment]
This is the normal behavior of PacketFence. 
The entry in the locationlog will stay active until another mac takes it's place or until this mac moves.

**Comment by aherbach88** [comment]
This when a new MAC is taking the place of the old one.

**Comment by julsemaan** [comment]
Sorry, made a mistake in my previous comment. We now support multi-host (multiple macs on the same port) on some vendors, so even when a new MAC shows on the port, the locationlog entry stays open for the old one to allow access reevaluation of all devices on the port. The entry is only closed when the MAC moves to another port

**Comment by aherbach88** [comment]
This feature is active on 4.5.1?

Also, how are we supposed to tell if a node has actually gone offline?

**Comment by julsemaan** [comment]
PacketFence does not detect if nodes go offline. It makes sure they authenticate, then afterwards the switch manages the online/offline of the node

**Comment by louismunro** [comment]
So it looks like this is not an issue. 
PF is working as designed.
