### ISSUE TITLE
parking: /release-parking is cached

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4980]
After applying #4974 fix on a setup, I'm not able to make parking feature work as expected.
If the Parking security event is triggered on a node, I need to reach /release-parking URL twice before security event is closed. The first time I reach /release-parking URL, my web browser gets it from cache. Consequently, parking security event is not closed.

**To Reproduce**
1. Trigger a parking security event on a device
2. Open a web browser on the device
=> You get Parking portal

3. Click on "Register"
=> You should see "Restrictions have been removed" but this page is displayed from cache (you can see "cached" in web browser console)

4. Click on "Continue"
=> Portal displays again page with "Register" button.

5. Click on "Register" (again)
6. Click on "Continue"
=> You should see captive portal and be able to register

**Expected behavior**
/release-parking is not cached by web browser the first time I got parking portal.

**Comment by fdurand** [comment]
conf/caddy-services/httpdispatcher.conf.example needs to be renamed after you apply the patch.

**Comment by nqb** [comment]
@fdurand: already done !

**Comment by fdurand** [comment]
I am not able to replicate on my side.
In the http response header, can you see : Cache-Control: no-cache, no-store, must-revalidate ?

**Comment by nqb** [comment]
Cache issue on my side.
