### ISSUE TITLE
Debian: haproxy's logs missing from $PF/logs

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4985]
On Debian 9, haproxy's logs are missing from `$PF/logs`. haproxy write its logs in `/var/log/haproxy.log`.

**Expected behavior**
Two logs files `haproxy-portal.log` and `haproxy-db.log` in `$PF/logs` directory like for CentOS.

**Comment by nqb** [comment]
On Debian 11, behavior is identical. `haproxy` package installed a file `/etc/rsyslog.d/49-haproxy.conf` which take precedence over our rsyslog configuration.

We can adjust our haproxy package to remove this file.

**Comment by fdurand** [comment]
haproxy 2.2.15 repackaged
