### ISSUE TITLE
node_discovered is triggered when you create a node from API

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4987]
When security event "Node discovered" is enable and you create a node, this security event is triggered.

**To Reproduce**
1. Enable "Node discovered" security event
2. Create a node
3. Check your mail box or mail queue

**Expected behavior**
Only trigger this security event when a node has been *discovered*, not created in web admin. By 
*discovered*, I mean data comes from DHCP or RADIUS request.

**Comment by jrouzierinverse** [comment]
This has been the behavior for a while.
If a node is created it is considered discovered to the system.
Does it make sense to change this behavior?

**Comment by julsemaan** [comment]
I discussed this with @nqb and it doesn't seem like its a valid behavior.

This security event trigger was designed to alert you when a new node would come online on your network.

By applying this to the API, it makes it so importing 1000 nodes will generate 1000 security events and some devices may never actually come online on the system.

**Comment by nqb** [comment]
Completely agree with @julsemaan.

**Comment by julsemaan** [comment]
It seems we would need to skip the pf::dal::node::after_create_hook when creating the node via the API.

@jrouzierinverse, what would be the best way to do that?
