### ISSUE TITLE
security event: unable to execute a script

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4988]
When I want to execute a script when a security event is triggered, it doesn't work.

**To Reproduce**
1. Create a shell script on your PF server:
```shell
cat >> /usr/local/bin/node-discovered.sh << EOF
#!/bin/bash
echo "hello"
EOF
chmod +x /usr/local/bin/node-discovered.sh
```
2. Configure following security event
```ini
[1300004]
actions=email_admin,external
enabled=Y
access_duration=10m
external_command=/usr/local/bin/node-discovered.sh
```
3. Create a new node in web admin to trigger this security event (as reported on #4987)

**Expected behavior**
Script `/usr/local/bin/node-discovered.sh` executed.

**Additional context**
Logs in `packetfence.log`:

```
Dec  6 14:43:34 pfcen7stable pfqueue: pfqueue(5569) WARN: [mac:99:99:99:99:99:99] /usr/local/bin/node-discovered.sh  (pf::action::action_api)
Dec  6 14:43:37 pfcen7stable pfqueue: pfqueue(5569) WARN: [mac:99:99:99:99:99:99] Problem trying to run command: LANG=C sudo /usr/local/bin/node-discovered.sh  2>&1 called from action_api. Child exited with non-zero value 1 (pf::util::pf_run)
```

**Comment by nqb** [comment]
Issue is caused by the fact that scripts are run by [pf user using sudo](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/action.pm#L188) but we limit what [pf user can run using sudo](https://github.com/inverse-inc/packetfence/blob/devel/packetfence.sudoers#L1).

**Comment by nqb** [comment]
From my point of view, we should:
* remove `sudo` call in `action_api` function because it seems to be used only to run security events scripts
* improve documentation about this setting to inform user that `pf` user should have rights to read and execute these scripts

@julsemaan, does it sounds good for you ? If yes, I will make a PR

**Comment by julsemaan** [comment]
Sounds good to me

Just a small upgrade note as well on this change and that will be perfect
