### ISSUE TITLE
Debian Packages Signed by RPM Key

### ISSUE THREAD

**Issue by danpoltawski** [inverse-inc/packetfence#4993]
**Describe the bug**
The install instructions on https://packetfence.org/support/faq/how-to-install-packetfence-on-debian.html suggest importing the key 0x810273C4 but this key doesn't seem to sign the packages.

When trying to install, it seems the RPM Signing key is required.

**To Reproduce**
1. Install debian stretch
2. Follow install guide
3. Run apt update

W: GPG error: http://inverse.ca/downloads/PacketFence/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CB2D3A2AA0030E2C

This key appears to be the RPM signing key:
 key CB2D3A2AA0030E2C: public key "Inverse Support (RPM package signing) <support@inverse.ca>"

**Comment by nqb** [comment]
Hello @danpoltawski,

Thanks for your report. 

FAQ has not been updated for 9.2, I only updated [Installation guide](https://packetfence.org/doc/PacketFence_Installation_Guide.html#_debian). I will do it.
