### ISSUE TITLE
Creation of language specific files on connection profile not working

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#4997]
You can not create files like **aup_text.de.html**, because the gui doesn't allow dot's in filename.

You get the message: Alphanumeric characters only. Extension must be .html or .mjml

So if you want to create AUP files for different languages, you have to do that via CLI at the moment.

**Comment by julsemaan** [comment]
@satkunas 

Can you check if the limitation comes from the frontend or the backend ?
