### ISSUE TITLE
D-Link DES-3028 killing pfsetvlan when encountering multiple MACs on a port

### ISSUE THREAD

**Issue by aherbach88** [inverse-inc/packetfence#500]
When the module for the D-Link DES-3028 encounters a port where there are two MAC addresses in the MAC table, the module then aborts the thread and the pfsetvlan queue will then start to build regardless of the number of additional threads pfsetvlan may have available to it.

The error that will appear in the log is similar to this:
INFO: removed trap received on 10.128.176.39 ifIndex 18 for d8:cb:8a:12:f0:38 in VLAN 100 (main::handleTrap)
ERROR: Thread 13 terminated abnormally: Can't locate object method "isMacInAddressTableAtIfIndex" via package "pf::Switch::Dlink::DES_3028" at /usr/local/pf/sbin/pfsetvlan line 1006. (main::)

A restart of pfsetvlan will fix the issue until this occurs again.

**Comment by aherbach88** [comment]
This also affects the D-Link DES-3526 module.

**Comment by aherbach88** [comment]
This is occurring on PF 4.5.1

**Comment by aherbach88** [comment]
Confirmed that this is still occurring in 5.0.1

**Comment by jrouzierinverse** [comment]
The problem will happen with non Cisco switches.

**Comment by aherbach88** [comment]
I opened this like 2 years ago, at that time Inverse told me in an email they weren't going to fix it without the company I worked for paying for the development on it.  I've since left there, so I have no interest in this anymore.  If you are going to actually get this worked on, please remove me from notifications, otherwise, please just close this.

**Comment by jrouzierinverse** [comment]
Ok we are closing this item.
