### ISSUE TITLE
Debian package link - file not found

### ISSUE THREAD

**Issue by akurzawa** [inverse-inc/packetfence#5001]
https://packetfence.org/download.html

Debian Packages > Debian 9 > 

`https://packetfence.org/downloads/PacketFence/debian/pool/stretch/p/packetfence/packetfence_9.2.0+20191126134139+98674490+0009+stretch1_all.deb`

Not Found
The requested URL /downloads/PacketFence/debian/pool/stretch/p/packetfence/packetfence_9.2.0+20191126134139+98674490+0009+stretch1_all.deb was not found on this server.

Apache Server at packetfence.org Port 443

**Comment by cgx** [comment]
Fixed. Thank you for reporting this issue.
