### ISSUE TITLE
Inline L3: Can't specify multiple DNS servers

### ISSUE THREAD

**Issue by danpoltawski** [inverse-inc/packetfence#5002]
**Describe the bug**
When configuring a new routed network, it's not possible to specify multiple DNS servers in the DHCP options. 

The DHCP option description says 'Should match the IP of a registration interface or the production DNS server(s) if the network is Inline L2/L3 (space delimited list of IP addresses).'

But it's not possible to space delimiter the list of addresses. An error is returned ' Value must be an IPv4 address '

Note that in versions before the go dhcp server it seemed possible to do this.

**To Reproduce**
1. Go to Admin > Network configuration > Routed Networks > New routed network 
2. Configure DHCP options and attempt to put `1.1.1.1 8.8.8.8` in the UI
3. Error is returned  ' Value must be an IPv4 address '

**Screenshots**

![Screenshot from 2019-12-16 14-25-40](https://user-images.githubusercontent.com/533249/70914699-69834e80-2010-11ea-880a-5e87e8c73603.png)

**Expected behavior**
Ability to specify multiple dns resolvers

**Comment by fdurand** [comment]
It's a frontend issue @satkunas can you check that ?

**Comment by danpoltawski** [comment]
@fdurand are you able to tell me how to configure it in the config file?

**Comment by fdurand** [comment]
it's in conf/networks.conf

**Comment by danpoltawski** [comment]
so 
```
dns=1.1.1.1 8.8.8.8
```
?
