### ISSUE TITLE
Security Event backend/frontend discrepancies

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5014]
**Describe the bug**
There are currently 2 discrepancies between the backend and the frontend in security events.

1. `recorded_acounting` does not exist in frontend. 
  * Added to backend in https://github.com/inverse-inc/packetfence/commit/d985011d4d324429c579dfebae96234092df63ad
  * Missing in frontend https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/components/pfFormSecurityEventTrigger.vue#L96

2. `useragent` does not exist in backend.
  * Still defined in frontend https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/components/pfFormSecurityEventTrigger.vue#L110
  * Was removed in backend in https://github.com/inverse-inc/packetfence/commit/3f0cc513a7ecbe70e5f3c46c8a612d32aa2608fe

**Comment by satkunas** [comment]
@julsemaan @jrouzierinverse we should provide a list in meta OPTIONS and have the frontend consume it to prevent another future de-sync.

**Comment by satkunas** [comment]
To prevent future de-sync we may need to find a way to re-organize the meta OPTIONS so they're categorized in `endpoint`, `profiling`, `usage` and `event`. It's currently not consumable because of the missing categorization.

**Comment by julsemaan** [comment]
For #1, recorded_accounting is a virtual trigger that doesn't need to be in the frontend. The accounting trigger should be used as before.

**Comment by julsemaan** [comment]
For #2, we just need to remove it from the frontend
