### ISSUE TITLE
web admin: testing an AD source doesn't work

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5025]
On nightly builds, if I tried to test an AD source, frontend doesn't give me any feedback. 

I didn't see any API call in my web browser console or in logs.

**To Reproduce**
1. Create an AD source
2. Click on 'Test' to test credentials

**Expected behavior**
- API call to `/api/v1/config/sources/test`
- Button 'Test' with a green tick

**Additional context**
This feature worked as expected on a 9.2 setup.

**Comment by satkunas** [comment]
I've made adjustments in https://github.com/inverse-inc/packetfence/commit/733a3ea9cf60feb889adf92429d205b68f6a9c54

@nqb Please re-test.

**Comment by julsemaan** [comment]
Works now
