### ISSUE TITLE
web admin: wrong display of "Monitor" field on AD source

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5026]
When you create a new AD source, "Monitor" field appear to be disabled but API call set it to "1".

**To Reproduce**
1. Create a new AD source: Monitor field is disabled
2. Take a look at authentication.conf
=> `monitor=1`

**Expected behavior**
Monitor field should be display as "Enabled" when you create a new AD source.

**Comment by satkunas** [comment]
`monitor` uses `0` and `1`. 

See https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm#L168

Non-issue.... Closing.

**Comment by cgx** [comment]
It is really an issue, and the fix is server-side:

```bash
❯ /usr/local/pf/sbin/pfperl-api get -M OPTIONS '/api/v1/config/sources?type=AD' | jq '.meta.monitor.default'
1

❯ /usr/local/pf/sbin/pfperl-api get -M GET '/api/v1/config/source/ad' | jq '.item.monitor'
"0"
```
