### ISSUE TITLE
Unable to edit the "Bandwidth expiration" security event

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5031]
**Describe the bug**
When clicking the "Bandwidth expiration" security event to edit it, it does nothing and there is a JS error in the console

**To Reproduce**
1. Edit the "Bandwidth expiration" security event

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/72008840-ad89fd80-3222-11ea-8d86-02e108c8e98b.png)

**Comment by cgx** [comment]
Any security event with a *time_expiration* trigger will also throw an exception.
