### ISSUE TITLE
Can't configure security event bandwidth usage triggers

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5044]
**Describe the bug**
Its now impossible to configure a bandwidth usage trigger in the security event (ex: accounting::TOT1KBD)

**To Reproduce**
1. Try to create a bandwidth based security event trigger

**Comment by cgx** [comment]
I'll need more details for this one. On my side, I can define a bandwidth limit. I see the changes in `security_events.conf`.

**Comment by julsemaan** [comment]
I can select "Bandwidth limit" in the select box, but nothing below allows me to say X amount of data in Y amount of time. It just says "Bandwidth limit"

**Comment by cgx** [comment]
Strange. It works for me™.

<img width="567" alt="Screen Shot 2020-01-09 at 12 59 54 PM" src="https://user-images.githubusercontent.com/1088448/72092289-04094180-32e0-11ea-81e4-3da02d336521.png">

**Comment by julsemaan** [comment]
![image](https://user-images.githubusercontent.com/3857942/72092853-2e0f3380-32e1-11ea-867c-8c28097b1e77.png)

Doesn't for me, I'm on a RPM build based on commit a371fe64, should that be working ? Is it worth updating the package ?

**Comment by julsemaan** [comment]
Since we're getting into details, I'm using Firefox 71.0 on Ubuntu 16.04
