### ISSUE TITLE
On fingerbank combination creation most of the search criteria doesn't work.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5046]
**Describe the bug**
If you try to add a new local combination in fingerbank then most of the field doesn't return any results.
Per example in DHCP Fingerprint if you start to type 1,15,3,6, nothing is found and the set is always empty

**To Reproduce**
1. :1443/admin/alt#/configuration/fingerbank/local/combinations/new
2. Dhcp fingerprint
3. Type 1,15,3,6,
4. Nothing is found

**Screenshots**

![image](https://user-images.githubusercontent.com/1553962/72094318-2dc46780-32e4-11ea-9745-ee2638a7088b.png)

**Expected behavior**
We should see what exist

**Comment by jrouzierinverse** [comment]
This seems to be a frontend issue as I am not seeing the dhcp fingerprint being sent

**Comment by cgx** [comment]
Fixed by 58c0955.

**Comment by julsemaan** [comment]
I believe this should go in the maintenance, @cgx, is this possible ?

**Comment by cgx** [comment]
This is already in 9.3.0. To add this to 9.2.0 would require to cherry pick a few commits.
