### ISSUE TITLE
Creating a self service profile generate a blank page on save

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5047]
**Describe the bug**
Create a new self service config then save it, it's saved but there is a blank page after.

**To Reproduce**
Create a self service config and save

**Screenshots**
![image](https://user-images.githubusercontent.com/1553962/72096857-1a67cb00-32e9-11ea-9039-eaeda407598a.png)

**Expected behavior**
We should see the self service config after save

**Comment by julsemaan** [comment]
You're missing the expected behavior in your issue description.

For reference, here is what it should display when the user browser is in French

![image](https://user-images.githubusercontent.com/3857942/72153517-39636d00-337c-11ea-8fa4-5e6bb341ec92.png)
