### ISSUE TITLE
Fingerbank-collector die each 5 minutes

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5048]
**Describe the bug**
Each 5 minutes fingerbank-collector die because it's not able to detect that packetfence is running

**Comment by julsemaan** [comment]
A new collector (1.2.2) is being pushed on the devel repo right now

@fdurand, can you confirm the issue is gone on 1.2.2

**Comment by julsemaan** [comment]
We will also need 1.2.2 built for Debian

I adjusted both specs

**Comment by extrafu** [comment]
Don't forget the build for Gentoo.

**Comment by julsemaan** [comment]
And the build for Windows XP

**Comment by fdurand** [comment]
Looks good now and made the packet for Windows ME.

**Comment by extrafu** [comment]
> And the build for Windows XP

We only support ReactOS.
