### ISSUE TITLE
vlan filter modify_node category change doesn't work anymore.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5050]
**Describe the bug**
vlan filter modify_node category change doesn't work anymore.

**To Reproduce**
Create a vlan filter with an action modify_node and set the category to a defined role
The vlan filter won't change the category of the device

**Expected behavior**
If we set a category or a bypass_role then it must change it in the db.

Make node_modify great again: https://github.com/inverse-inc/packetfence/blob/packetfence-7.0.0/lib/pf/node.pm#L904

**Comment by jrouzierinverse** [comment]
I am not able to replicate

**Comment by jrouzierinverse** [comment]
Was a role and the action modify_node was defined?
Did the role override the change in modify_node.

**Comment by fdurand** [comment]
Not able to reproduce with the new filters.
