### ISSUE TITLE
Description doesn't show in portal module "modules" field

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5051]
**Describe the bug**
When you select one or more modules in a chained module (likely to happen for root and choice too), then you don't see the description of the modules, its just blank. The modules are still there and saved but you don't realize they're there

**To Reproduce**
1. Create a chained portal module with 1+ module in it

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/72180652-94fe1c80-33b5-11ea-91f2-5ae9818bfe36.png)

**Comment by extrafu** [comment]
@julsemaan Who should take care of that? @cgx or @satkunas or @jrouzierinverse

**Comment by julsemaan** [comment]
@cgx or @satkunas since it looks frontend to me as the description is well populated by the backend

**Comment by cgx** [comment]
@satkunas The problem appears for all instances of `pfFormChosen` used with group values.

**Comment by cgx** [comment]
@satkunas It's related to the new `v-slot:singleLabel` of `pfFormChosen` and the *tagCache* not being initialized in this case.

**Comment by julsemaan** [comment]
@cgx, I see there is a commit but the issue isn't closed.

Are we good for releasing Monday morning with your fix, or does this still need some @satkunas love

**Comment by cgx** [comment]
More love is required.

**Comment by julsemaan** [comment]
Then this is the only thing between us and the release.

@satkunas, can you prioritize this so that we can release today

**Comment by satkunas** [comment]
Aye! Omw.

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/3395169e4e1ee3ddaf192e2062be2e93ffde37ec
