### ISSUE TITLE
HTTP SSL certificate: configure Apache for intermediate certificates

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5053]
When you configure HTTP intermediate certificates in webadmin, `/usr/local/pf/conf/ssl/server.crt` contains server and intermediate certificates. However, it doesn't update `/usr/local/pf/conf/httpd.conf.d/ssl-certificates.conf` to specify that intermediate certificates are located into `/usr/local/pf/conf/ssl/server.crt`.

Consequently, when you check SSL certificate chain using: `openssl s_client -host MGMT_IP -port 1443 -prexit -showcerts`, you only get server certificate.

According to [this stackoverflow comment](https://serverfault.com/a/382638) and my tests, if you use following Apache configuration:
```
SSLCertificateFile %%install_dir%%/conf/ssl/server.crt
SSLCertificateKeyFile %%install_dir%%/conf/ssl/server.key
SSLCertificateChainFile %%install_dir%%/conf/ssl/server.crt
```
Certificate chain is correctly returned by Apache.

So I supposed we could simply update https://github.com/inverse-inc/packetfence/blob/devel/conf/httpd.conf.d/ssl-certificates.conf.example to uncomment `SSLCertificateChainFile` and set it to `%%install_dir%%/conf/ssl/server.crt`.

**Comment by julsemaan** [comment]
I think this is a good idea
