### ISSUE TITLE
Switch template module is missing getVoipVsa

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5059]
**Is your feature request related to a problem? Please describe.**
We need to be able to set the RADIUS attributes used when authorizing a VoIP device using a templated switch. Right now, this is missing.

**Describe the solution you'd like**
Have getVoipVsa implemented with a confidurable scope in the template

**Describe alternatives you've considered**
Going on OTBM but its offline now

**Comment by extrafu** [comment]
I prefer things to be configurable.... I hate things that are confidurable - it's too dure, too hard - like Zayme-muscle-hard.

**Comment by julsemaan** [comment]
Confidurability: Something hard-coded through configuration :smiley:
