### ISSUE TITLE
Sponsor: guest could leave captive portal waiting sponsor approval

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5064]
**Is your feature request related to a problem? Please describe.**
When a guest requests a sponsor approval, he needs to keep its web browser open on registration page to have its access granted. If guest leaves web browser and sponsor approves guest request, guest user is created in DB but no node are registered.

- Message when guest requests a sponsor approval: 

> Your registration is pending approval. Once approved you will be automatically redirected.

- Message when sponsor approves guest request: 

> Access to the guest network has been granted.

**Describe the solution you'd like**
Guest could leave web browser without having its registration canceled.

**Describe alternatives you've considered**
- Warn guest that it must keep registration page opened
- Warn sponsor that access to the guest network is granted if guest has keep its web browser opened
- When guest leaves browser, ask him if he really want to leave page

**Additional context**
Request coming from [mailing-list](https://www.mail-archive.com/packetfence-users%40lists.sourceforge.net/msg17990.html).

**Comment by julsemaan** [comment]
The thing with this is that there could be a step after the sponsor auth and all that state is stored in the session.

Also, if we just register the device when the sponsor approves the access then we miss all the steps that are after sponsor auth (provisioners or other policies that could be put in place)

A solution would be to have the behavior above (register on activation) be a parameter of the source (disabled by default to be backward compatible) to be able to handle the case above correctly.

**Comment by nqb** [comment]
Ok, thanks for your clarification

**Comment by julsemaan** [comment]
I will address this by at least making it explicit in the portal that the user shouldn't leave the page until his access is granted

**Comment by julsemaan** [comment]
I added the explicit message in devel, I'll work on creating a feature that registers the device upon activation (that will be in a PR since its a large change)
