### ISSUE TITLE
Syslog configuration is missing some field.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5066]
**Describe the bug**
Old admin:
![image](https://user-images.githubusercontent.com/1553962/72553642-27476a00-3867-11ea-9fb0-05cbe00e65de.png)

New admin:
![image](https://user-images.githubusercontent.com/1553962/72553698-40e8b180-3867-11ea-8556-7c7a6addb84d.png)

**To Reproduce**
Try to create a remote syslog config

**Comment by satkunas** [comment]
@fdurand not able to reproduce, please close if no longer an issue

![Screenshot_20200305_163914](https://user-images.githubusercontent.com/3904468/76028117-e4695080-5eff-11ea-95a0-75804e4fff97.png)

**Comment by fdurand** [comment]
Not able to reproduce.
