### ISSUE TITLE
web admin: unable to create a VLAN interface

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5067]
**Describe the bug**
It's not possible to create a VLAN interface from Interfaces menu.

**To Reproduce**
1. Go to 'Network configuration -> Interfaces'
2. Click on 'New VLAN' button on any interface

You got following screenshot (here I clicked on 'New VLAN' button on `eth2` interface:

![Capture d’écran de 2020-01-17 10-47-12](https://user-images.githubusercontent.com/10830260/72602310-5ae1cd00-3917-11ea-892d-2ce5c6324f0a.png)

**Expected behavior**
Be able to specify a VLAN ID.

**Workaround**
Use old admin.

**Comment by julsemaan** [comment]
This needs to go in maintenance/9.3 unless this was introduced post 9.3

**Comment by satkunas** [comment]
@julsemaan done

https://github.com/inverse-inc/packetfence/commit/76e920adf7cb45de75aa031d654c6ed285c94681
