### ISSUE TITLE
web admin: fingerbank account type is wrong

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5070]
**Describe the bug**
When you register a "community user" account in Fingerbank settings, web admin displays this account as "Corporate".

**To Reproduce**
1. Register a community user account using its API key.

=> Account type field equals to Corporate.

**Additional context**
In API response to `api/v1/fingerbank/account_info`, I didn't see "Corporate" keyword returned. So I don't know how web admin get this information.

**Comment by julsemaan** [comment]
Is this a local user or a Github user ?
All local users are assumed to be corporate because corporate != unlimited since not all local users are unlimited

**Comment by nqb** [comment]
Github user: @nqb-test2

**Comment by julsemaan** [comment]
It seems the frontend uses the deprecated field github_uid to detect if its a corporate (local) or github account.

Instead the frontend should use the value of the auth_type field which will be either `github` or `local` depending on the account type

**Comment by julsemaan** [comment]
This needs to go in the maintenance.

@satkunas, make sure you check the milestone when fixing issues. Anything that is "+1 patch release" needs to go in the maintenance when applicable
