### ISSUE TITLE
web admin: color of buttons for CSV import (nodes/users)

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5071]
When you import nodes or users using CSV import, color of buttons next to "MAC Address" or "PID" fields are not identical to others:

**Screenshots**

![Capture d’écran de 2020-01-20 15-00-27](https://user-images.githubusercontent.com/10830260/72732275-9f7a9c00-3b95-11ea-9579-201ab079ecc6.png)

**Expected behavior**
Same button for all rows.

**Comment by satkunas** [comment]
Color is consistent with required/optional fields that are currently selected. This causes confusion with Safari/Opera users since there is no coloring in the selectbox.

@cgx should we deprecate this coloring?

**Comment by cgx** [comment]
@satkunas Yes, it's creating too much confusion.
