### ISSUE TITLE
switch_supports feature breaks some switch modules 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5073]
**Describe the bug**
Some switch modules inherit directly or indirectly from `Cisco.pm`:
* [Catalyst_3500XL.pm](https://github.com/inverse-inc/packetfence/blob/0013c2ed92639a3a4e1399f5c3262983d358f47e/lib/pf/Switch/Cisco/Catalyst_3500XL.pm#L23)
* [Catalyst_2900XL.pm](https://github.com/inverse-inc/packetfence/blob/0013c2ed92639a3a4e1399f5c3262983d358f47e/lib/pf/Switch/Cisco/Catalyst_2900XL.pm#L20)
* [ISR_1800.pm](https://github.com/inverse-inc/packetfence/blob/0013c2ed92639a3a4e1399f5c3262983d358f47e/lib/pf/Switch/Cisco/ISR_1800.pm#L44)

It seems that since #4840 feature (introduced in 9.2.0), these switchs are considered to support only what [Cisco.pm](https://github.com/inverse-inc/packetfence/blob/0013c2ed92639a3a4e1399f5c3262983d358f47e/lib/pf/Switch/Cisco.pm#L30-L33) supports: `SaveConfig` and `Lldp`. 

Consequently, they can't handle RADIUS requests.

**To Reproduce**
1. Generate a Ethernet-EAP RADIUS request coming from a 2900XL switch (in 192.168.1.0/24 range) :
```
# cat >> /opt/tls.config << EOF
network={
ssid="CORPORATE SSID"
key_mgmt=WPA-EAP
eap=TLS
identity="inverse"
ca_cert="/usr/local/pf/raddb/certs/ca.pem"
client_cert="/usr/local/pf/raddb/certs/client.pem"
private_key="/usr/local/pf/raddb/certs/client.key"
private_key_passwd="whatever"
eapol_flags=3
}
EOF

# eapol_test -c /opt/tls.config -s testing123 -a MGMT_IP -A 127.0.0.1 -N 61:d:15 -M 11:11:11:11:11:11 -N 4:x:0xc0a80101
```
Logs:
```
Switch type 'pf::Switch::Cisco::Catalyst_2900XL' does not support WiredDot1x (pf::SwitchSupports::__ANON__) 
Sending REJECT since switch is unsupported (pf::radius::_switchUnsupportedReply) 
```

**Expected behavior**
Handle RADIUS requests like other switch modules.

**Additional context**
I'm sure it worked before #4840.

I suppose the best way to handle this issue is to track switch modules that inherit directly or indirectly from a top level switch module. Then we could add `pf::SwitchSupports` instructions in each switch module affected. However, it's hard to know which feature those switch modules supports previously.

**Comment by nqb** [comment]
I took a look on top level switch modules (`find ./lib/pf/Switch -maxdepth 1 -name "*.pm"`) and I found two cases:
1. top level switch modules doesn't contain `pf::SwitchSupports` instructions: in that case, I supposed that sublevel switch modules contain `pf::SwitchSupports` instructions. But I found exceptions, for example, `DES_3028.pm`.
1. `Cisco.pm` is the only one to support `SaveConfig` and `Lldp`. Other top level switch modules supports most of the time `WirelessDot1x` or `WiredDot1x`.

**Comment by jrouzierinverse** [comment]
Can you perform that test on a 9.10 install?
From what I see from doing a diff is that is expected behavior for that switch.

```bash
git diff packetfence-9.1.0 v9.2.0 lib/pf/Switch.pm
```
```diff
...
-=item supportsWiredDot1x - Returns 1 if switch type supports Wired 802.1X
-
-=cut
-
-sub supportsWiredDot1x {
-    my ( $self ) = @_;
-    my $logger = $self->logger;
-
-    $logger->error(
-        "Wired 802.1X is not supported on switch type " . ref($self) . ". "
-        . "Please let us know what hardware you are using."
-    );
-    return $FALSE;
-}
...
```
```bash
git diff packetfence-9.1.0 v9.2.0  lib/pf/Switch/Cisco.pm
```
```diff
-sub supportsSaveConfig { return $TRUE; }
-sub supportsCdp { return $TRUE; }
```

There were no changes done to lib/pf/Switch/Cisco/Catalyst_2900XL.pm and lib/pf/Switch/Cisco/Catalyst_3500XL.pm in 9.2.0

**Comment by jrouzierinverse** [comment]
Here is a quick to determine in 9.2.0 and above what a switch supports
```
perl -I/usr/local/pf/lib -Mpf::Switch::Cisco -e'print(join(", ", pf::Switch::Cisco->supports),"\n")'
```

**Comment by nqb** [comment]
Thanks @jrouzierinverse.

I will make a test on a 9.1.

**Comment by nqb** [comment]
@jrouzierinverse, tested on 9.1.0 and you're completely right. I didn't check correctly changes introduced in `Switch.pm` by your PR. Apologies.

Before closing this issue, I will update `switches.conf.example` to replace `Catalyst_2900XL`.
