### ISSUE TITLE
pfqueue needs to be restarted to deauthenticate on new switchs

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5074]
**Describe the bug**
If you create a switch or update a current switch with a module not already loaded by `pfqueue`, you will get following error:

```
Jan 21 11:44:28 pfcen7stable pfqueue: pfqueue(13684) ERROR: [mac:11:11:11:11:11:88] Error handling ReAssignVlan : Can't locate object method "wiredeauthTechniques" via package "pf::Switch::Cisco::SG300" at /usr/local/pf/lib/pf/api.pm line 360.
 (pf::api::can_fork::notify)

```
until you restart `pfqueue`.

**To Reproduce**
1. Create a new switch with any type
2. Send a RADIUS request coming from this switch for a node
3. Try to reevaluate access of node connected to this switch from web admin

=> You will get error message above in packetfence.log

**Expected behavior**
Reevaluate access should work.

**Additional context**
I dumped value of [$switch](https://github.com/inverse-inc/packetfence/blob/0013c2ed92639a3a4e1399f5c3262983d358f47e/lib/pf/api.pm#L348) before restarting `pfqueue` and all seems fine (see [attachment](https://gist.github.com/nqb/421c6fe2d3c2433f1be1fb147a26fab9)).

Related: #4955, 94b5707fbbf3490f59d275c75aa2eeadfde2455e and d960c4516aa447e06cfe925d438687e68a65d2ea

**Comment by jrouzierinverse** [comment]
This will be fixed by #5072

**Comment by nqb** [comment]
Ok and I've seen that this commit has been pushed to maintenance.

**Comment by jrouzierinverse** [comment]
Were you able to retry?

**Comment by nqb** [comment]
Tested and it works.
