### ISSUE TITLE
pfdhcp handing out the same ip to different clients

### ISSUE THREAD

**Issue by kkplein** [inverse-inc/packetfence#5079]
We have an inline setup, and it seems that with "algorithm=2", pfdhcp hands out the same ip to different clients. See:

> Jan 20 19:22:10 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:10+0100 lvl=info msg="DHCPDISCOVER from 80:2a:a8:56:44:98 ()" pid=3436 mac=80:2a:a8:56:44:98
> Jan 20 19:22:10 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:10+0100 lvl=info msg="DHCPDISCOVER from 80:2a:a8:56:4a:0e ()" pid=3436 mac=80:2a:a8:56:4a:0e
> Jan 20 19:22:11 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPOFFER on 10.20.255.199 to 80:2a:a8:56:44:98 ()" pid=3436 mac=80:2a:a8:56:44:98
> Jan 20 19:22:11 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPREQUEST for 10.20.255.199 from 80:2a:a8:56:44:98 ()" pid=3436 mac=80:2a:a8:56:44:98
> Jan 20 19:22:11 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPACK on 10.20.255.199 to 80:2a:a8:56:44:98 ()" pid=3436 mac=80:2a:a8:56:44:98
> Jan 20 19:22:11 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPOFFER on 10.20.255.199 to 80:2a:a8:56:4a:0e ()" pid=3436 mac=80:2a:a8:56:4a:0e
> Jan 20 19:22:11 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPREQUEST for 10.20.255.199 from 80:2a:a8:56:4a:0e ()" pid=3436 mac=80:2a:a8:56:4a:0e
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:11+0100 lvl=info msg="DHCPACK on 10.20.255.199 to 80:2a:a8:56:4a:0e ()" pid=3436 mac=80:2a:a8:56:4a:0e
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="DHCPDISCOVER from 80:2a:a8:56:49:05 ()" pid=3436 mac=80:2a:a8:56:49:05
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="80:2a:a8:56:49:05 in arp table Ip 10.20.255.199 is already own by 80:2a:a8:56:4a:0e" pid=3436 mac=80:2a:a8:56:49:05
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="80:2a:a8:56:49:05 Ip 10.20.255.199 already in use, trying next" pid=3436 mac=80:2a:a8:56:49:05
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="Temporarily declaring 10.20.255.199 as unusable" pid=3436 mac=80:2a:a8:56:49:05
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="80:2a:a8:56:49:05 10.20.255.199 Added back in the pool none on index 65469" pid=3436
> Jan 20 19:22:12 PacketFence-ZEN-pf9 pfdhcp[3436]: t=2020-01-20T19:22:12+0100 lvl=info msg="80:2a:a8:56:49:05 in arp table Ip 10.20.255.199 is already own by 80:2a:a8:56:4a:0e" pid=3436 mac=80:2a:a8:56:49:05
> 

After changing to "algorithm=1" everything works as advertised.

network.conf:

> [10.20.0.0]
> dns=192.168.2.1
> gateway=10.20.0.1
> domain-name=inlinel2.company.com
> named=enabled
> dhcp_end=10.20.255.199
> netmask=255.255.0.0
> split_network=disabled
> dhcp_start=10.20.0.10
> nat_enabled=disabled
> dhcp_max_lease_time=86400
> dhcpd=enabled
> fake_mac_enabled=disabled
> type=inlinel2
> dhcp_default_lease_time=86400
> coa=disabled
> algorithm=2

Not sure what other details I can provide. Let me know if I can help.

**Comment by kkplein** [comment]
Perhaps relevant: This was a new installation, with multiple devices booting and asking for an IP at pretty much the same time. Perhaps it would not have happened with more time between the client requests.

**Comment by julsemaan** [comment]
@fdurand, can you take a look at this, seems like a legit bug

**Comment by kkplein** [comment]
Hi Fabrice,
Just wanted to say: Thanks for fixing this!
