### ISSUE TITLE
You can still click on a user after deleting it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5085]
**Describe the bug**
After you delete a user in the admin (in users list mode), then the row becomes red but you can still click on it which opens the details of the user that was deleted and throws a bunch of errors

**To Reproduce**
1. Go in users
2. Pick a user by selecting it
3. Delete it through the actions menu
4. Click on the user again

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/72916480-163ba480-3d10-11ea-9b0d-c8eeeb3f953d.png)

**Expected behavior**
Shouldn't be able to click on the user after deleting it. Or row should disapear

**Comment by cgx** [comment]
I think it's related to the domain of the user's email.

**Comment by julsemaan** [comment]
It does that with any deleted user from my testing
