### ISSUE TITLE
WEB admin - PF 8.3.0- Unable to turn off coa if a switches belong to a group

### ISSUE THREAD

**Issue by GurvanP** [inverse-inc/packetfence#5093]
when a switch belongs to a switch group, I can't turn off the CoA by the interface.
If i set the line in the switches.conf file "useCoA=N", and do the command "pfcmd configreload hard", the CoA is off

**Comment by julsemaan** [comment]
It seems to be because the "Use CoA" parameter doesn't use a 3 state toggle like the other parameters of the switch do (which handle the inherited values)

Talked with @satkunas and he'll have a look

**Comment by julsemaan** [comment]
Didn't see the version was added to the description after the initial post.

We won't be giving anymore love to the old pre-9.0 admin interface anymore.

I'll open another bug for the 3 state toggle in the new admin
