### ISSUE TITLE
API: apply_security_event endpoint returns wrong value

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5097]
**Describe the bug**
When you trigger a security event, for the first time on a node, using `apply_security_event` endpoint, API returns `security_event_id` in JSON payload with value equals to ID of new row in `security_event` table (e.g. 9), in place of ID of security event triggered (e.g. 1300000).

**To Reproduce**
1. Create a node:
```
pfperl-api get -M POST /api/v1/node/ -c '{"mac":"22:22:22:22:22:22"}'  | python -m json.tool 
```
2. Trigger generic security event on node:
```console
# pfperl-api get -M POST /api/v1/node/22:22:22:22:22:22/apply_security_event -c '{"security_event_id":"1300000","mac":"22:22:22:22:22:22"}' | python -m json.tool 
{
    "security_event_id": "9",
    "status": 200
}
``` 
3. Check content of `security_event_table`:
```console
# mysql -u root -p pf -e 'select id,security_event_id from security_event where id="9";'
Enter password: 
+----+-------------------+
| id | security_event_id |
+----+-------------------+
|  9 |           1300000 |
+----+-------------------+
```

**Expected behavior**
API should return:
```json
{
    "id": "9",
    "security_event_id": "1300000",
    "status": 200
}
```

**Additional context**
This behavior is always true when a security event is immediately closed (ex: Node discovered - 1300004) but if you re-run same API call on a security event still open, `security_event_id` will now contain ID of security event triggered (i.e 1300000):

```console
# security event with ID 9 is still open on my node 22:22:22:22:22:22
# pfperl-api get -M POST /api/v1/node/22:22:22:22:22:22/apply_security_event -c '{"security_event_id":"1300000","mac":"22:22:22:22:22:22"}' | python -m json.tool 
{
    "security_event_id": "1300000",
    "status": 200
}
```

It mean that in GUI, if you want to trigger a security event already opened, you didn't got any error message.

**Comment by jrouzierinverse** [comment]
I would need to check with @satkunas if this breaks anything.

**Comment by nqb** [comment]
It seems that `/api/v1/security_events/search` works as expected: endpoint returns `id` and `security_event_id` with correct values.

I set milestone to +1 but I didn't test on a 9.3 install, only on devel.

**Comment by jrouzierinverse** [comment]
To keep in sync with our current internal API and command line.
If a user tries to apply a security event multiple times it will return the old id.

**Comment by jrouzierinverse** [comment]
Not and error

**Comment by nqb** [comment]
Commit 1ace4c9187e5d852502c73bf42e37e52d48c2993 fixed this issue. Now we get following behavior:
```console
# pfperl-api get -M POST /api/v1/node/10:11:12:13:14:15/apply_security_event -c '{"security_event_id":"1300000","mac":"10:11:12:13:14:15"}' | python -m json.tool
{
    "id": 21,
    "status": 200
}
# pfperl-api get -M POST /api/v1/node/10:11:12:13:14:15/apply_security_event -c '{"security_event_id":"1300000","mac":"10:11:12:13:14:15"}' | python -m json.tool
{
    "id": 21,
    "status": 200
}
# pfperl-api get -M POST /api/v1/node/10:11:12:13:14:15/apply_security_event -c '{"security_event_id":"1300004","mac":"10:11:12:13:14:15"}' | python -m json.tool
{
    "id": 22,
    "status": 200
}
# pfperl-api get -M POST /api/v1/node/10:11:12:13:14:15/apply_security_event -c '{"security_event_id":"1300004","mac":"10:11:12:13:14:15"}' | python -m json.tool
{
    "id": 23,
    "status": 200
}
```

**Comment by nqb** [comment]
However, @jrouzierinverse and @satkunas, when you try to apply a security event already opened, nothing pop-up in the GUI. 

Could we tell to users that security event is already opened ?

**Comment by jrouzierinverse** [comment]
This is really a new feature not a +1

**Comment by nqb** [comment]
> This is really a new feature not a +1

Agree.
