### ISSUE TITLE
Issue with inline network detection/redirect in 5.0.1

### ISSUE THREAD

**Issue by sinusoidal-zz** [inverse-inc/packetfence#510]
I've had a go at tracing this issue, but not quite got to the bottom of it.  This is an inline captive portal with no dot1x (just a basic captive portal but with no nat).

When I've got always_use_redirecturl=disabled in profiles.conf, after about 10 seconds of waiting on the 'timer bar' screen during activation, my client reaches the:

"Your network should be enabled within a minute or two. If it is not reboot your computer"

...rather than redirecting to the requested page, which means it's reached the 'unknownState' function in CaptivePortal.pm. Looking at the logs, there is also a line referencing 'redir.cgi' which as far as I know, is no longer used?
`re-evaluating access (redir.cgi called)` 
.. though I don't think that's related.

See log (anonymised):

http://pastebin.com/mMsj4t53

If however I set always_use_redirecturl=enabled, the redirect works as expected and I get forwarded to the correct page:

http://pastebin.com/ArXahQS5

Any ideas what could be causing this?  When redirect is disabled, it seems to be dropping right through to 'unknownState'.

Thanks,
Robin.

**Comment by sinusoidal-zz** [comment]
Hmm I just had this happen, even with redirect=enabled, so it may not be directly related to that setting, but it seems to happen far less often with it enabled.

**Comment by sinusoidal-zz** [comment]
The browser I'm testing with is chrome 40.0.02214.114 by the way, but I don't think it's a browser issue as it works most of the time.

**Comment by sinusoidal-zz** [comment]
I worked around this issue by modifying the line in networkAccessCallback to include a 5 second delay, like it does for Firefox and for IE.  This seems to suggest the problem was being caused by the network detection script attempting to get out before the network has been enabled?

```
// Other browsers, try a direct redirection
performRedirect.delay(5, destination_url);
```

}

instead of

```
// Other browsers, try a direct redirection
performRedirect(destination_url);
```

**Comment by julsemaan** [comment]
I took the liberty to put the logs out of the issue for readability.

Could you send a screenshot of the Chrome developer console network tab while the network is being activated (right-click, inspect element, then go in the network tab) 

Thanks

**Comment by julsemaan** [comment]
No feedback, closing this
