### ISSUE TITLE
Graphs are missing from dashboard when using RADIUS load balancer mode

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5100]
**Describe the bug**
If you use the RADIUS load balancer mode (i.e. first server of a cluster only does load balancing), then the RADIUS latency metrics on the dashboard don't exist on the first server (since its not doing any authentication). This makes it so you can't see some of the graphs. Mainly all the "RADIUS latency" and "NTLM" section of the "RADIUS" tab

**To Reproduce**
1. Run a cluster with a pure load balancer for RADIUS (active_active.auth_on_management=disabled)
2. View the dashboard

**Expected behavior**
Should be able to view those graphs although they don't exist on the first member of the cluster

**Additional context**
This is on 9.1.0 but I guess it applies to all v9 releases

**Comment by fdurand** [comment]
What i can do is to send ntlm_auth.time:0|ms each x minutes to statsd to  simulate a ntlm_auth call then it will create the graph.
For the RADIUS latency it's coming from radsniff , so i can probably do the same.

**Comment by julsemaan** [comment]
Looks like a good idea to me

**Comment by julsemaan** [comment]
@cgx, I would need to have a PF 9.1.0 compatible fix to provide to my customer who has reported the issue as they are unable to see a lot of the graphs that involve the cluster nodes.

I tried to cherry-pick it in in maintenance/9.1 but its impossible. Would you be able to provide a fix we can put in maintenance/9.2 and maintenance/9.1 ?

Thanks!

**Comment by cgx** [comment]
@julsemaan All set!

**Comment by julsemaan** [comment]
@cgx Thanks!
