### ISSUE TITLE
API: unable to create a switch with a MAC address as ID

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5101]
**Describe the bug**
When you want to create a switch with MAC address as ID, you can't.

**To Reproduce**
```console
# pfperl-api get -M POST /api/v1/config/switches -c '{"id":"ff:ff:ff:ff:ff:ff","description":"test"}' | python -m json.tool                                                                 
{
    "errors": [
        {
            "field": "id",
            "message": "Wrong value"
        }
    ],
    "message": "Unable to validate",
    "status": 422
}
```

**Expected behavior**
Switch creation should occur.

EDIT:
For this switch:
-  `DELETE` is working
- `PATCH` is not working
- `GET` is working

**Comment by jrouzierinverse** [comment]
This is correct behavior as 00:00:00:00:00:00 and ff:ff:ff:ff:ff:ff are not consider a valid mac.

**Comment by nqb** [comment]
Ah. I tried to reproduce a customer issue which was not using this MAC. I will update issue as soon as I'm able to reproduce.

**Comment by nqb** [comment]
@jrouzierinverse, I'm not able to reproduce this issue using a MAC different from ff:ff:ff:ff:ff:ff on a devel setup. I will wait customer feedback which run a 9.2 setup to see if it's a real issue. Otherwise, I will close it.
