### ISSUE TITLE
Web admin role rights: Can't assign REPORTS read

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5102]
![](https://lh3.googleusercontent.com/-B1SFfUEO3sM/XjNA6xHFUsI/AAAAAAAACc8/4kNPUO83jDwfKTqtx04Yuuig063_VLHXgCK8BGAsYHg/s0/2020-01-30.jpg)

It looks like it checks for the cluster status and fails.

Temporary work around: Add System READ

**Comment by cgx** [comment]
Related to this, we show the netdata dashboard to users with the `READ_REPORTS` role. Does it make sense in your use case? Should we have a specific role for the dashboard?

**Comment by julsemaan** [comment]
IMO, REPORTS_READ is fine for the dashboard
