### ISSUE TITLE
Switch type 'pf::Switch::Ruckus::SmartZone' does not support MABFloatingDevices

### ISSUE THREAD

**Issue by restrok** [inverse-inc/packetfence#5103]
Hi guys!

I have this issue, can you help me?

packetfence.log

>Jan 31 13:47:43 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Jan 31 13:47:43 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) WARN: [mac:1c:cc:d6:45:98:15] Switch type 'pf::Switch::Ruckus::SmartZone' does not support MABFloatingDevices (pf::SwitchSupports::__ANON__)
Jan 31 13:47:43 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] is of status unreg; belongs into registration VLAN (pf::role::getRegistrationRole)
Jan 31 13:47:43 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] (10.10.28.254) Added VLAN 105 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Jan 31 13:49:08 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] handling radius autz request: from switch_ip => (10.10.28.254), connection_type => Wireless-802.11-NoEAP,switch_mac => (ec:58:ea:37:0a:78), mac => [1c:cc:d6:45:98:15], port => 0, username => "1c:cc:d6:45:98:15", ssid => Tarbut (pf::radius::authorize)
Jan 31 13:49:08 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Jan 31 13:49:08 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) WARN: [mac:1c:cc:d6:45:98:15] Switch type 'pf::Switch::Ruckus::SmartZone' does not support MABFloatingDevices (pf::SwitchSupports::__ANON__)
Jan 31 13:49:08 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] is of status unreg; belongs into registration VLAN (pf::role::getRegistrationRole)
Jan 31 13:49:08 tarbut-olivos packetfence_httpd.aaa: httpd.aaa(2210) INFO: [mac:1c:cc:d6:45:98:15] (10.10.28.254) Added VLAN 105 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)

packetfence version:
`packetfence-9.2.0-20191126180126.98740132.0007.el7.x86_64`

Regards!

**Comment by julsemaan** [comment]
I don't see any issues in the logs you provided.

This tracker is for development tracking and confirmed bugs only.

To get general help, use the PacketFence mailing list.
I also suggest to be more detailed if you post there
