### ISSUE TITLE
RFC: packetfence-tracking-config service interest

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5105]
Since merge of #5095, `packetfence-tracking-config` should be enabled by default on Debian and CentOS.

Current state:
- Debian: issue #5096 
- CentOS: service is stopped because if you don't have a minimal git config, service doesn't start

As I already mentioned on [initial PR request for this feature](https://github.com/inverse-inc/packetfence/pull/4147), I'm not in favor about this feature in PF for several reasons:
- security: tracking all changes like its currently done doesn't exclude credentials from being registered.
- interest: we now have an Admin Audit logs that records all changes made by admins using GUI (not using CLI access)

So my proposal is:
- revert changes introduced by #5095 to not enable this service by default
- think about deprecate this feature from PF

**Comment by fdurand** [comment]
I think you don't understand this feature, it's not to audit what have been changed in the admin gui but a way to track the change in the conf directory and have a way to revert quickly if needed.

For the current state:
Debian: we just need to fix it
Centos: When a file is changed in the conf directory then the service is started (https://www.putorius.net/systemd-path-units.html)

If you edit manually a file in the conf directory , it won't be caught by the admin audit log and you won't be able to revert.

If you edit the authentication.conf you are able to see clear text password , so i don't see the point.

**Comment by nqb** [comment]
> I think you don't understand this feature, it's not to audit what have been changed in the admin gui but a way to track the change in the conf directory and have a way to revert quickly if needed.

That's completely clear for me. Most of the users change configuration using the GUI. If people want to track what have change in conf files, they should use GUI and restrict direct access to config file using CLI. On top of that, reading a Git history is more painful than reading Admin audit logs.

If you want a quick way to revert, you can use daily backups unless you made several changes in a day.

> If you edit manually a file in the conf directory , it won't be caught by the admin audit log and you won't be able to revert.

Yes, I'm completey aware of that.

> If you edit the authentication.conf you are able to see clear text password , so i don't see the point.

With this feature, if you read full history of Git log, you can get more credentials than just the one currently defined in config file. For example, RADIUS secrets of network devices no more managed by PacketFence.

**Comment by fdurand** [comment]
Just think that it's a advanced tool and it's for advanced administrator. I saw so many times issue when changes have been made in the admin gui and things needed to be fixed.
The admin audit log is not enough and to be able to have acces to it the db needs to be started too.
Also for the password the issue is more the way we store them in the configuration files, not because we track the change.

**Comment by nqb** [comment]
> Just think that it's a advanced tool and it's for advanced administrator.

From my point of view, it's more a feature for us than for users. If you really need it, feel free to enable it on your setups, but don't make it enabled by default.

> I saw so many times issue when changes have been made in the admin gui and things needed to be fixed. 

In this specific case, it means that change have been recorded by Admin audit logs. If web admin is not reachable, you can still connect to DB and check last records in `admin_api_audit_log` to know what have been changed.

> Also for the password the issue is more the way we store them in the configuration files, not because we track the change.

I agree but this feature emphasize the problem like I previously mentioned.

I would like to hear voice of other Inverse guys on this feature.

On my side, I don't want such a feature be enabled by default on setups I deploy. So if you don't want to deprecate it, please consider to revert last commit that auto-enable it.

**Comment by julsemaan** [comment]
My 2 cents after discussion with Fabraize

- Its fine to me that we track this even if there are credentials in the files. They're in clear on the disk anyway.
- Where I do see a problem is that in domain.conf, the admin user/pass is there temporarily and we don't want that. This file should be excluded from the tracking.
- Then to make everyone happy, we should add the ability to enable/disable this service in the new configurator. We're rewriting this from scratch anyway and we'd just need an API call to enable/disable this.
- To make everyone conscious about this change, we put a note in the UPGRADE guide that this is be enabled by default going forward and tell people about the change and how to disable it.

To me, this is very useful to track changes admins do manually on files and having it on by default is the way to go for me as its often after a breaking change that we want to see this info and if it wasn't enabled before that change, then enabling it afterwards won't do any good.

**Comment by nqb** [comment]
Ok, it sounds good for me.

@fdurand, could you exclude domain.conf from tracking ? I will update UPGRADE.asciidoc

**Comment by nqb** [comment]
- @cgx and @julsemaan, is configuator part done on that part ?
- @fdurand, is `domain.conf ` excluded from tracking ?

**Comment by julsemaan** [comment]
The API endpoint is there so that it can be done so nothing to add on my end

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/conf/.gitignore.example
