### ISSUE TITLE
8.3.0: pfstats stops populating management metrics in cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5108]
**Describe the bug**
On PF 8.3.0, I got a case where all the management metrics would stop populating although the VIP was there. I saw there was quite a bit of work done around the VIP detection in pfstats between 8.3.0 and 9.0.0. Perhaps some stuff could go in the maintenance to fix it. Otherwise, we need to figure out the fix.

**Comment by fdurand** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/0a7072fcb9dd554db589975bb25113c66fbde91f
