### ISSUE TITLE
Routes service: does not send alertes or display error when the routes disappear from the system 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5110]
It would be nice to have a way to check if the routes configured in the configuration matches the ones installed on the system.

It would show right away if the routes properly set.

**Comment by fdurand** [comment]
The fact that the routes are not active on the system is because the test doesn't work correctly and pfcmd think that it's ok.
I did a PR in order to manage the routes with keepalived and deprecate the routes service.
