### ISSUE TITLE
Allow users to select a different role in Self Service Portal

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#5114]
We have certain scenarios where it would be nice for users to be able to 'self select' a new role from the /status page.  Currently, all devices get a generic _Gaming_ role through the self service portal.  This works very well 90% of the time, but, because all devices on our network are behind a firewall and NAT'd, users end up getting strict NAT errors when trying to game.

We have created a _NoNAT_ role (and corresponding VLAN) to deal with this where NAT is not used and gamers are happy.  For now, users have to open a ticket with us, and we have to apply the new role to their specific device.

If PacketFence admins could maintain a list of which roles are 'self selectable' and users could go to /status to modify their roles as needed (and only choose a role from the 'special' list), that would helpful to us.

For now, having the _NoNat_ role be the default role for our self service portal is not an option as we don't have enough IP space.

**Comment by Venice-89** [comment]
+1 thats exactly what I also need.
I want to allow particular users to register devices in different vLANs.

That's something which will be important in times where more and more IOT devices will be used in the industry. Especially in a research company like I am working for.
