### ISSUE TITLE
Bypass role to multiple nodes in admin

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#512]
You cannot change the bypass_role to a single or a multiple selection of nodes in the admin interface.

You select 1 or more nodes in the admin node page, you try to change their bypass_role via Action -> Apply Bypass Role, you have the message (x) nodes have been modified (in the admin), but nothing happen. See error message in comment.

Tested on PF5 and PF 4.7 on Centos 6.x

**Comment by whitx** [comment]
ERROR: Argument "" isn't numeric in numeric ne (!=) at /usr/local/pf/html/pfappserver/lib/pfappserver/Model/Node.pm line 793.

**Comment by louismunro** [comment]
Provide at least 4 Ws please.
What is happening. 
When does it happen.
Where?
If possible, Why?

Otherwise your comment is meaningless.

**Comment by jrouzierinverse** [comment]
This has been fixed
