### ISSUE TITLE
Inline in cluster 9.1/2

### ISSUE THREAD

**Issue by danielerosatidast** [inverse-inc/packetfence#5126]
Hi guys, i'm looking for a step by step guide for a cluster inline deployment.
I deloyed several cluster radius e single inline servers. As i read from 8.x PF is able to be set in inline throw a cluster active active, i need now a setup like that. 
Not able to find any documentation about it.

I tried to give one more nick to each node (a-b-c) with same network: 172.25.255.1/24
At the first reboot of one node i do get error for keepalived service and httpd.portal. Once all the nodes are rebooted, one by one, the cluster is no more working.
Can some one help me with this?
I'm running a 9.1.0 triple server on same l2 metwork.

**Comment by julsemaan** [comment]
Use the mailing list for configuration questions.

This tracker is for confirmed bugs and feature requests
