### ISSUE TITLE
URL portal module: improve documentation

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5142]
**Describe the bug**
When you use URL portal module on a captive portal, you're redirected to URL defined in this module. However, redirection seems persistent and unless you remove `session:MAC` key from cache, you're always redirected to URL. It's not possible to reach again the captive portal.

**To Reproduce**
1. Create a URL portal module called `url` with http://www.cnn.com as URL
2. Add this portal module to default registration policy portal module
3. Preview captive portal from default connection profile
4. Click on your URL portal module

=> You're redirected to http://www.cnn.com

5. Leave your web browser, clear your cache and try to reach again captive portal

=> You're redirected to http://www.cnn.com

**Expected behavior**
Captive portal should be display after step 5 in place of URL.

**Additional context**
If I dump `session:MAC` key using `pfcmd cache httpd.portal dump session:001122334455`, I got following value **after** step 4:
```perl
'module_default_policy+default_registration_policy' => {
    'current_module' => 'default_policy+default_registration_policy+url'
},
``` 
This value is kept in cache so it's seems normal that PF always redirect to URL defined in portal module. However, if user is redirected to captive portal using `http://YOUR_PORTAL_HOSTNAME/captive-portal?next=next`, captive portal workflow continue.

I already noticed this behavior on PF 8.3.0.

**Comment by julsemaan** [comment]
When you close and reopen your browser, the captive portal resumes where it was.

We could have a different logic in the URL module that tries to detect if you're reopening your browser and not do it in this case.

When using the URL module, its the responsibility of the place you redirect to to bring the user back to the captive portal. Perhaps the destination page should be designed better to allow the user to come back to the beginning (redirecting to /logout on the captive-portal)

**Comment by nqb** [comment]
Thanks for your feedback.

> Perhaps the destination page should be designed better to allow the user to come back to the beginning (redirecting to /logout on the captive-portal)

Not sure to understand what you mean here.

**Comment by julsemaan** [comment]
The URL module is made so that you redirect to a page which has an impact on the portal workflow, not to a random URL like cnn.com. Its made so that you can integrate the portal with another system.

See the following example in the doc:
https://packetfence.org/doc/PacketFence_Installation_Guide.html#_calling_an_external_website

With that in mind, the page where you are redirecting the user should have the proper mechanism in place to allow the user to restart the authentication process at the beginning if that is necessary.

**Comment by nqb** [comment]
Yes I understand, I will improve documentation on that part.
