### ISSUE TITLE
portal captive with switch Extreme x440G2 EXOS 22.7 

### ISSUE THREAD

**Issue by SimonUniv** [inverse-inc/packetfence#5144]
Hello, I'm coming to you because I can't configure the auth web with an Extreme X440G2 switch on a particular VLAN. I know that switches from Extreme are not compatible with web auth but I wanted to know if it was possible to configure it with a UPM script or with a policy web-redirect portal (which is available since EXOS 22.7), j follow your documentation. I manage to do the redirection thanks to the redirect portal on the portal but when I connect with a registered account that puts me as an error 502 bad gateway, do you have an explanation? I would really like to be able to configure packetfence for my student project because I find it the most complete.

Switch
 - Device:  Switch Extreme x440G2-48p
 - OS:  EXOS 22.7

**Comment by julsemaan** [comment]
Use the mailing list for such questions
