### ISSUE TITLE
PF 9.3 computer host authentication issue against AD Domain

### ISSUE THREAD

**Issue by frkrak** [inverse-inc/packetfence#5156]
**Describe the bug**
PF 9.3 cluster of 3 host
All of them joined to the domain
ntlm_auth tested and working 

Two of the members authenticating machine accounts correctly but the third one failing every time.

the radius log just showing :
Feb 20 17:21:38 nac9-1 auth[17507]: (253)   Invalid user: [host/FV004665.kabi.ads.fresenius.com] (from client pf port 40 cli 10:65:30:aa:bb:cc via TLS tunnel)
Feb 20 17:21:38 nac9-1 auth[17507]: (253)   Login incorrect: [host/FV004665.kabi.ads.fresenius.com] (from client pf port 40 cli 10:65:30:aa:bb:cc via TLS tunnel)
Feb 20 17:21:38 nac9-1 auth[17507]: [mac:10:65:30:aa:bb:cc] Rejected user: host/FV004665.kabi.ads.fresenius.com

I turned freeradius in debug mode :
raddebug -f /usr/local/pf/var/run/radiusd.sock

And found out this in the log :
(253) Thu Feb 20 17:21:38 2020: Debug:       [packetfence-multi-domain] = fail

And a few lines above there was this:
(253) Thu Feb 20 17:21:38 2020: Debug: packetfence-multi-domain: perl_embed:: module = /usr/local/pf/raddb/mods-config/perl/packetfence-multi-domain.pm , func = authorize exit status= hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /usr/local/pf/lib/pfconfig/cached.pm line 182.

Asking "my friend google" here is the result seeming to be close to the issue
https://stackoverflow.com/questions/33738849/strange-behavior-of-a-tied-hash-in-perl-when-asking-for-an-arrayref

apparently an issue with the way the libjson-xs-perl 3.030-1 on debian 9 handles the realm

in cached.pm line 182
$payload = encode_json( \%info );

As I have 2 nodes with the same version of Debian and PF working as expected, I compared the libs so I added only this one :

ii  libcpanel-json-xs-perl                                   3.0225-1                                             amd64        module for fast and correct serialising to JSON
And it solved my issue

It seems to be  packaging issue to me, either one lib missing or the wrong one in the dependencies, I can't say

Hope this will help correcting the Debian package.

Best regards

**Comment by frkrak** [comment]
HI ,
It seems we are not very numerous encountering this radius authentication issue on PF9.2 or 9.3 
but it seems that Jeff (on the PF users list found a patch to correct this issue

[PacketFence-users] RADIUS authentication failure , his mail dated 27 Feb 2020

```

> "I’ve made the following modification to cached.pm:
>
> Old Version: 
>     179     my %info;
>     180     my $payload;
>     181     %info = ( ( method => $method, key => $what, tenant_id => pf::config::tenant::get_tenant() ), %additionnal_info );
>     182     $payload = encode_json( \%info );
> New Version:
>     179     my $newvariable = JSON->new->allow_nonref;
>     180     my %info;
>     181     my $payload;
>     182     %info = ( ( method => $method, key => $what, tenant_id => pf::config::tenant::get_tenant() ), %additionnal_info );
>     183     #$payload = encode_json( \%info );
>     184     $payload = $newvariable->encode( \%info );
> This change has corrected the problem.  My authentication is now successful.

```
B.R.

**Comment by denis-b** [comment]
Hello, I upgraded my PF 8.1 to 10, and had the same problem. 
The patch resolved the problem. Please apply it upstream.
