### ISSUE TITLE
Netdata dashboard: restrict access

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5161]
**Is your feature request related to a problem? Please describe.**
When you installed a PF server, Netdata dashboard can be display without any credential by going to http://PF_MGMT_IP:19999

**Describe the solution you'd like**
Restrict access to Netdata dashboard.

If possible, I would like to disable direct access to Netdata dashboard and provide a link on PF dashboard. That's way an authenticated user with access to PF dashboard can view Netdata dashboard.

Reference: https://docs.netdata.cloud/docs/netdata-security/#netdata-viewers-authentication

**Comment by nqb** [comment]
Since v12, using https://PF_MGMT_IP:19999 doesn't work anymore but it's still possible to access Netdata dashboard using https://PF_MGMT_IP:1443/netdata/SERVER_IP_ADDRESS/ **without** any authentication. On a standalone, `SERVER_IP_ADDRESS=127.0.0.1`

We need to restrict this access.

**Comment by satkunas** [comment]
TODO:

* Remove reverse-proxy from haproxy-admin
* Move reverse-proxy to api_frontend
  * Re-use aaa middleware, produce 404 when auth is missing or invalid
    * Instead of using the `token` header for aaa, the cookie will used instead
      * The cookie should be automatically set from the backend with a successful /api/v1/login
      * The cookie lifetime should be >= the session timeout
      * The frontend will delete the cookie when the user logs out manually 
  * Use same path `https://[host]:1443/netdata/*`
  * If possible use `SYSTEM_READ` ACL
* Restrict access to port 19999
