### ISSUE TITLE
Debian: haproxy-portal doesn't start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5162]
**Describe the bug**
`haproxy-portal` is not able to start on Debian 9 using nightly builds.

Related to #5086, it seems that packaging for Debian is not ready:

```
# dpkg -l | grep keepalive
ii  keepalived                                               1:1.3.2-1 
```

Versus keepalived 2.X on CentOS 7.

See [@julsemaan's comment](https://github.com/inverse-inc/packetfence/pull/5086/files#r379098332)

**Comment by fdurand** [comment]
Just pushed keepalived 2.0.20 in debian devel repository. (http://inverse.ca/downloads/PacketFence/debian-devel/pool/stretch/k/keepalived/keepalived_2.0.20-1_amd64.deb)
Can you test it and if it's ok close the issue.

**Comment by nqb** [comment]
Hi @fdurand,

keepalived is correctly installed from our repo but if file `/usr/local/pf/var/conf/keepalived.conf` has execution permissions, `keepalived` will not start.

**Comment by nqb** [comment]
Debian spec file need to be adjust for keepalive version.

**Comment by fdurand** [comment]
The permission on the file looks to come from the packaging.

**Comment by fdurand** [comment]
Fixed by https://github.com/inverse-inc/packetfence/commit/15f31366ea920e464eab91d98d653f7b57aa29f9
