### ISSUE TITLE
Switch template GUI: Empty RADIUS attributes

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5165]
**Describe the bug**
Currently, when you try to edit an existing switch template, you get empty fields.

![Capture d’écran de 2020-02-27 17-22-23](https://user-images.githubusercontent.com/10830260/75463276-dd819180-5985-11ea-80ef-bdbf9526fd0c.png)

Web admin is doing a POST to an inexistent endpoint (api/v1/radius_attributes) when you click on an existing switch template.

I didn't find this endpoint:
```
# pfperl-api routes|grep radius
  +/radius_audit_logs                                      *        "api.v1.RadiusAuditLogs"
  +/radius_audit_log/#radius_audit_log_id                  *        "api.v1.RadiusAuditLogs.resource"
```

**Comment by satkunas** [comment]
@nqb open the debugger and while loading the page see what contents are returned with the `POST /api/v1/radius_attributes` endpoint.

I suspect that the response is empty, in which case you'll need to recompile pfhttpd and restart the api services.

**Comment by nqb** [comment]
Hi @satkunas,

I already did this test yesterday, the answer is: `Unknown path` and it makes sense because radius_attributes seems missing from API routes when dumping routes using `pfperl-api routes`

**Comment by nqb** [comment]
@satkunas, you're right, it seems to work now. `/api/v1/radius_attributes` is certainly not managed by `pfperl-api`.

Did you fix this issue with https://github.com/inverse-inc/packetfence/commit/2910a7d8aaf4acc5ba0aa2f52088d54fe8ada67e and https://github.com/inverse-inc/packetfence/commit/f8fd3b6cfcec5091980d1e4969d4f5c0ecc632ab ?

If yes, I will let you close this issue.

**Comment by satkunas** [comment]
> not managed by pfperl-api.

It's a golang based service
