### ISSUE TITLE
Expose the freeradius dictionary in perl

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#5168]
The internal perl radius dictionary is incomplete compared to the free radius one.
Provided a way to generate a perl dictionary from the freeraidus dictionary.

**Comment by nqb** [comment]
@jrouzierinverse, should we re-generate the FreeRADIUS dictionnary each time we upgrade FreeRADIUS ?

**Comment by jrouzierinverse** [comment]
More precisely it should run every time we update the freeradius dictionary.

**Comment by nqb** [comment]
We should automate this regeneration. Otherwise, I'm sure we will forget to run this script.
