### ISSUE TITLE
Switch template GUI: Tunnel-Private-Group-ID is not display correctly

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5174]
**Describe the bug**
If you edit `PacketFence::Standard` switch template, `Tunnel-Private-Group-ID` field and its value (`$vlan`) is not display correctly in `accetpVlan` and `VOIP` scopes even if API returns correctly this information.

**To Reproduce**
1. Go to Switch Templates menu
2. Click on `PacketFence::Standard` switch template

**Screenshots**
![Capture d’écran de 2020-02-28 14-28-13](https://user-images.githubusercontent.com/10830260/75552626-9dc2b480-5a2e-11ea-8671-8a18eaebd2e1.png)

**Expected behavior**
Field and value should be display like others.

**Additional context**
`Tunnel-Private-Group-ID` is available in dropdown list of RADIUS attributes.

**Comment by nqb** [comment]
Issue is related to case. If I use Tunnel-Private-Group-*Id* in place of Tunnel-Private-Group-*ID* in my switch template, it works.

**Comment by nqb** [comment]
@satkunas, @jrouzierinverse, what is the best way to deal with this issue ?

From my point of view, this issue will only concern users that try to create their switch templates from CLI. 

@jrouzierinverse could you add a validation on syntax ?

**Comment by jrouzierinverse** [comment]
We should use the standard name from the freeradius dictionary.
This is related to #5168

**Comment by jrouzierinverse** [comment]
Once 5168 is done then adding that validation will work.

**Comment by jrouzierinverse** [comment]
We were able to fix this without 5168.
Can you please retest?

**Comment by jrouzierinverse** [comment]
Can you please retest this?

**Comment by nqb** [comment]
It works.
