### ISSUE TITLE
Active Directory Domains Issue

### ISSUE THREAD

**Issue by cjiwonder** [inverse-inc/packetfence#5178]
When I tried to add "Active Directory Domains" under " Policies and Access Control", it joined successfully with error, but unfortunately, it automatically moved my "Domain Controller Name" to the OU mentioned in the OU filed, and entire my Active Directory Server collapsed with the error "The Domain Controller is not available"

**Comment by julsemaan** [comment]
Perhaps you put your DC machine account name in the 'This server's name' field.

Or the value of the hostname of your PF server is the same as the DC machine account

**Comment by cjiwonder** [comment]
Thanks for your reply. Yes, I put my DC account name in the "This Server's name " field. I will correct it.
