### ISSUE TITLE
Missing RADIUS attributes in RADIUS replies

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5182]
**Describe the bug**
On devel builds, it seems that PF is not able to return RADIUS attributes configured in switch templates or in switch modules.

**To Reproduce**
1. Create a switch and forge a RADIUS request
```
pfperl-api get -M POST /api/v1/config/switches -c '{"id":"192.168.0.8","description":"bar", "type":"PacketFence::Standard"}' | python -m json.tool
eapol_test -c /opt/tls.config -s testing123 -a 172.17.1.18 -A 127.0.0.1 -N 61:d:15 -M 77:77:77:77:77:77 -N 4:x:0xc0a80008 -N 5:x:0x00000001
```
2. Check RADIUS Audit log
=> RADIUS reply only contain RADIUS attributes returned by FreeRADIUS.

Following RADIUS attributes are missing:
```
Tunnel-Medium-Type
Tunnel-Type
Tunnel-Private-Group-Id
```

Same behavior with Ethernet-NoEAP. Same behavior if I use "Generic" as switch type.

**Expected behavior**
Return expected RADIUS attributes.

**Additional context**
Certainly related to recent commits related to switch supports.

**Comment by jrouzierinverse** [comment]
Can you provide the logs?

**Comment by nqb** [comment]
Apologies, it's a mistake on my side. I was sure `guest` role was mapped to a VLAN by default in default switch configuration but that's not the case.
