### ISSUE TITLE
Sponsor: associated sources only display local and LDAP sources

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5186]
**Describe the bug**
When you want to configure "Associated sources" on a sponsor source, you can only select local and LDAP sources in dropdown. It doesn't make sense because other sources like Htpasswd allow you to define rules to Mark as sponsor users.

**To Reproduce**
1. Click on "Associated sources" on a Sponsor source
=> Only local and LDAP sources are available, default file1 source can't be selected.

Same behavior on old web admin.

**Expected behavior**
All sources that permit to define administration rules should be display in dropdown list.

**Additional context**
I opened this issue after a discussion with @jrouzierinverse on this topic. But, for me, it seems to be a correct behavior because associated sources are use, for example, when a user specify a sponsor email address on captive portal. In that case, trying to use a Htpasswd source to check if sponsor email is valid doesn't make sense: email address can't be lookup using this source, using local and LDAP sources is possible.

**TODO**
- [X] Adjust description of Associated sources in GUI based on fix (see 10d72c825582c5d15cf3c2286cfccea572f2f3b4)

**Comment by fdurand** [comment]
Not all internal authentication sources make sense.

I propose:
LDAP
AD
Htpasswd
RADIUS
SQL
