### ISSUE TITLE
Interface with type=other is invalid

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5187]
**Describe the bug**
When you create an interface with `type=other`, you get following behavior:
- a block is created in `conf/networks.conf`:
```
[1.1.1.0]
gateway=1.1.1.1
domain-name=other.example.lan
named=enabled
dhcp_end=1.1.1.246
netmask=255.255.255.0
split_network=disabled
dhcp_start=1.1.1.10
nat_enabled=disabled
dhcp_max_lease_time=86400
dhcpd=disabled
fake_mac_enabled=disabled
type=other
dhcp_default_lease_time=86400
coa=disabled
```
- a `pfcmd checkup` command ends with:
```
Use of uninitialized value in split at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 419.
FATAL - invalid network type other for interface eth0.100
```
Consequently, PF services are not able to start when you use `pfcmd service pf start` because `pfcmd checkup` is running before.

**To Reproduce**
1. Create a new interface in `pf.conf`:
```
[interface eth0.100]
ip=1.1.1.1
type=other
mask=255.255.255.0
```
2. Run:
```
pfcmd configreload hard
pfcmd checkup
```

**Screenshots**

**Expected behavior**
- Defining an new interface with `type=other` should not create a block in `networks.conf` file.
- Type=other should not be considered as invalid

**Additional context**
I tested this on a 9.3 setup with maintenance patches.

If I removed configuration in `conf/networks.conf` for my interface, I still gets `FATAL - invalid network type other for interface eth0.100`

**Comment by nqb** [comment]
@jrouzierinverse, it needs to be cherry-pick to maintenance.

**Comment by jrouzierinverse** [comment]
Done
