### ISSUE TITLE
Default connection profile: filters section is missing in web admin

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5188]
**Describe the bug**
On 9.3+patches, if you edit default connection profile, filters section is missing. 

`OPTIONS` API call to `/api/v1/config/connection_profile/default` doesn't return `advanced_filter` and `filter` items.

**To Reproduce**
1. Edit default connection profile

**Expected behavior**
Filters section should be available on default connection profile.

**Additional context**
That's not the case on other connection profiles.

**Comment by julsemaan** [comment]
The filters shouldn't be on the default connection profile, its the catch all profile to ensure a node/user will always match a profile
