### ISSUE TITLE
Can't search switch module per vendor name

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5190]
````
[root@unicorn pf]# ll lib/pf/Switch/Ubiquiti
total 16
-rw-r--r-- 1 pf pf 7355 Mar  4 08:58 EdgeSwitch.pm
-rw-r--r-- 1 pf pf 7986 Mar  4 08:58 Unifi.pm
````

If I want to search all the ubiquiti switch module:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/5261214/75916496-756bf900-5e26-11ea-82ed-ed49b9946e2e.png">

I will have to look them up individually:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/5261214/75916591-9fbdb680-5e26-11ea-96c4-b0a5172e6623.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/5261214/75916609-ac420f00-5e26-11ea-91e5-3755da974a3e.png">

**Comment by extrafu** [comment]
@satkunas and @jrouzierinverse backend or frontend issue? Pick one and let's fix it.

**Comment by jrouzierinverse** [comment]
the search is done 100% on the frontend.

**Comment by satkunas** [comment]
Search now works with group labels:

![Screenshot_20200403_112734](https://user-images.githubusercontent.com/3904468/78377831-24266500-759e-11ea-82d4-c7f857f0ba7a.png)

It also supports compound statements:

![Screenshot_20200403_112933](https://user-images.githubusercontent.com/3904468/78378032-66e83d00-759e-11ea-8463-7cc9167420e4.png)
