### ISSUE TITLE
pfdhcp: Restarting in a loop

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5204]
When you upgrade from a previous PF 10 version, PFDHCP restart in a loop.

Missing parameter ?

**Comment by fdurand** [comment]
Missing pool_backend=memory in networks.conf , i will provide a fix.

**Comment by nqb** [comment]
@fdurand, is bcfe687 your fix ?

**Comment by fdurand** [comment]
no, restarting pfconfig is suppose to fix it but i need to add a default value in the pfdhcp code.
