### ISSUE TITLE
Many 403 Unauthorized access errors when User Manager role login in Packetfence 9.3

### ISSUE THREAD

**Issue by chencairong** [inverse-inc/packetfence#5214]
There are many 403 Unauthorized access errors when User Manager role login in Packetfence 9.3
![image](https://user-images.githubusercontent.com/8074797/77176143-9d35af00-6afe-11ea-934b-579c45733b8c.png)
I think the UI should send the correct API before privilege checking by the role.

**Comment by chencairong** [comment]
![image](https://user-images.githubusercontent.com/8074797/77531163-73e59c00-6ecd-11ea-946c-204f25fa20d1.png)
More API returned 403 Unauthorized access errors

**Comment by nqb** [comment]
Hello,

In order to be able to reproduce, please provide us a [Minimal, Complete, and Verifiable example (MCVE)](https://stackoverflow.com/help/mcve)

Also attach your `adminroles.conf`.

**Comment by chencairong** [comment]
Hi, @nqb I created new ticket https://github.com/inverse-inc/packetfence/issues/5256 with the reproducible steps.

**Comment by nqb** [comment]
Thanks, closing.
