### ISSUE TITLE
v10 remaining items in core features

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5220]
# feature/pfacct

- [x] Make primary key smaller using a 64 bit hash of the tenant ID, the MAC and other parameters already in the unique_session_id. Should also have the time_bucket in the PK
- [x] (JRZ) Online/offline handling needs to be taken care of
- [x] (JRZ) Random issue with DB under load: see https://github.com/inverse-inc/packetfence/pull/5181#issuecomment-602839607

# feature/configurator_api

- [x] A management interface has to be implicitly defined for the user. This should be the first interface with an IP in order to ease configuration. Item 2.1 of the decision list in our wiki
- [x] DNS servers can't be configured on the configurator. Item 2.3 of the decision list in our wiki
- [x] (FLE) A server with a completely empty DB can't be configured through 1-click, we still have to go through the root password field, pf DB name and pf user credentials. The simple mode should be a 1 click installation and generate passwords automatically

# feature/filter_engines

- [x] Need to fix the bin/pfcmd checkup for vlan_filters.conf.default. see https://github.com/inverse-inc/packetfence/issues/5234

**Comment by jrouzierinverse** [comment]
I was not able to get the same issues as you on my setup.
I made some changing to the chi_cache cleanup job and chi.conf.
As that it seemed to be causing issues with IO for that table.
Can you please retest in your environment.

**Comment by jrouzierinverse** [comment]
do we close this?

**Comment by extrafu** [comment]
Let's wait for now.
