### ISSUE TITLE
Maintenance adjustments for new admin index template

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5222]
With the index template changing in the new admin in https://github.com/inverse-inc/packetfence/commit/3cf09f4e918f12a5930e0055033e5f4e2d8ca0c8, we need to adjust the maintenance branch for v10 and forward.

This includes

- [x] The build of the maintenance branch assets
- [x] pf-maint.pl to use the new template path

**Comment by nqb** [comment]
Tested, it works. I got a `dist/index.html` with references to JS files under `dist/js` directory.
