### ISSUE TITLE
Escaping needed on Admin page title

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5224]
```html
<title>[% l('Administrator') %] - PacketFence</title>
```
![Screenshot_20200324_165801](https://user-images.githubusercontent.com/3904468/77476348-cc933700-6df0-11ea-8f1f-adec522dcdb6.png)

**Comment by cgx** [comment]
Already fixed with 1a610334f0c49fdcf57433c36fecc2c36ccb5565.
