### ISSUE TITLE
Error throwned when accessing page 2 of configurator with no DB

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5229]
**Describe the bug**
When you don't have a DB, the 2nd page of the configurator throws an error about the admin user

**To Reproduce**
1. Access page 2 of the configurator with no DB

**Expected behavior**
The admin user should be configured after the schema is loaded

**Comment by extrafu** [comment]
Both 5248 and 5229 are closed but I don't see any commits fixing it.

**Comment by cgx** [comment]
#5229 is not closed.

**Comment by extrafu** [comment]
Indeed, I got confused with the last update on this one with the CLOSED stamp on it, but it was referring to the other issue, not this one.

**Comment by lzammit** [comment]
Works!
