### ISSUE TITLE
SSL error on the captive portal

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5233]
It looks like chrome and firefox do not accept our self signed certificate:

![](https://lh3.googleusercontent.com/-1_zxEsqIij4/Xnt4Pno7c-I/AAAAAAAACkk/79g_rulJWoIBM5GFt4izOURrk315I5QJgCK8BGAsYHg/s0/2020-03-25.jpg)

Microsoft Edge still works.

**Comment by julsemaan** [comment]
Well f*ck them, we'll use Edge from now on

**Comment by fdurand** [comment]
The only workaround i can see are the following:

- Ask the user to clisk on the page and type : dGhpc2lzdW5zYWZl
- Detect that the portal use a self signed certificate and disable secure redirect.

**Comment by extrafu** [comment]
How about if the user tries to set a self-sign certificate for the portal through the admin, we give him a BIG FAT WARNING about this and call it a day?

**Comment by julsemaan** [comment]
I think we may just need to add the Subject Alternative Name in our self gen cert. 
The invalid CA may still be bypassable

**Comment by fdurand** [comment]
The certificate is generated from the packaging and i did the test with Subject Alternative Name but still not able to see the portal.

**Comment by fdurand** [comment]
or use Edge

**Comment by julsemaan** [comment]
From now on, the only browser PacketFence supports is Edge

Jokes aside, I think we may have to disable the secure redirect if we detect we use a self-signed
