### ISSUE TITLE
pfacct bring new requirements to run Golang unit tests

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5238]
**Describe the bug**
- `pf_smoke_test` needs to be up and running. Currently, DB is configured only for Perl unit tests (because it's part of smoke.t)
~~- `TestFilters/FilterVlan` need to be able to start `sbin/pffilter` service~~

I will adapt test scripts and documentation.

**Comment by jrouzierinverse** [comment]
TestFilters/FilterVlan has always started the sbin/pffilter service from the beginning.
This is not a new requirement.
