### ISSUE TITLE
Filter engines: Editing large filter is painfully slow

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5240]
**Describe the bug**
Similarly to how the switches GUI was slow in the past, editing a filter with a large condition is very painful and slow.

**To Reproduce**
1. Edit the built-in `pfdns` DNS filter

**Comment by satkunas** [comment]
Minor improvements made in https://github.com/inverse-inc/packetfence/commit/ab34094898abbe22a3d9edea306e03bbdec6fba8 and https://github.com/inverse-inc/packetfence/commit/ea5f83a8f632f9351e10670ff9d4d37a21b8b892.

More work is needed as the core issue is a VueJS problem with "Flush calbacks", similiar to: https://forum.vuejs.org/t/performance-issue-with-reactivity-in-a-long-list-flushcallbacks-taking-long/45838/7

Possible solutions:
 * Sandbox pfFormBoolean into its own formStore namespace and allow modifications that are detached from the base formStore with a Commit button.

**Comment by extrafu** [comment]
@julsemaan Do you see improvements with the two commits made by @satkunas ? Enough to push this to v10.1?

**Comment by julsemaan** [comment]
I am going to be performing the test during the afternoon

**Comment by julsemaan** [comment]
Although its slow, its usable so yes its enough to push this to 10.1

**Comment by satkunas** [comment]
Another possible improvement is to break down and deprecate the global forms' view() function, and move meta scope into the individual components and out of the global form scope, so reflows only affect a single element rather then the entire form.

https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue

**Comment by extrafu** [comment]
I moved it to v11 as it'll be our next big release which will include the GUI performance improvements.

**Comment by satkunas** [comment]
Please retest with new admin ui.

**Comment by julsemaan** [comment]
Mas rapido
