### ISSUE TITLE
Configurator: Can't create the pf user

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5243]
````
Mar 26 08:53:52 pf-testing.inverse.ca packetfence[6684]: WARN pfperl-api(6684): DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TABLE ON `pf`.* TO 'pf'@'%' IDENTIFIED BY 'pf'' at line 1 at /usr/local/pf/lib/pfappserver/Model/DB.pm line 49.
                                                          (pfappserver::Model::DB::assign)
Mar 26 08:53:52 pf-testing.inverse.ca packetfence[6684]: WARN pfperl-api(6684): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TABLE ON `pf`.* TO 'pf'@'%' IDENTIFIED BY 'pf'' at line 1 (pfappserver::Model::DB::assign)
Mar 26 08:53:52 pf-testing.inverse.ca pfperl-api[6663]: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TABLE ON `pf`.* TO 'pf'@'%' IDENTIFIED BY 'pf'' at line 1 at /usr/local/pf/lib/pfappserver/Model/DB.pm line 49.
```

![image](https://user-images.githubusercontent.com/5261214/77649338-18082b00-6f40-11ea-880a-ea842a2b11f6.png)

**Comment by lzammit** [comment]
![image](https://user-images.githubusercontent.com/5261214/77649346-1b9bb200-6f40-11ea-9d67-72db641aba4f.png)

**Comment by julsemaan** [comment]
@jrouzierinverse, it looks like the grant "CREATE TEMPORARY TABLE" that you added for pfacct is breaking. 

Do we need really it ? Its not in the upgrade script either if its really needed

**Comment by jrouzierinverse** [comment]
It is needed

**Comment by julsemaan** [comment]
@jrouzierinverse, can you fix the grant then, it doesn't pass the syntax

**Comment by julsemaan** [comment]
As discussed I have removed the grant for now, @jrouzierinverse will add it again with the right syntax and we can then close this

**Comment by lzammit** [comment]
````
[root@pf-testing pf]# rpm -qa packetfence
packetfence-9.3.9-20200327103704.130318959.0007.devel.el7.x86_64
````


MariaDB [(none)]> select * from information_schema.user_privileges where PRIVILEGE_TYPE='CREATE TEMPORARY TABLES';
+--------------------+---------------+-------------------------+--------------+
| GRANTEE            | TABLE_CATALOG | PRIVILEGE_TYPE          | IS_GRANTABLE |
+--------------------+---------------+-------------------------+--------------+
| 'root'@'localhost' | def           | CREATE TEMPORARY TABLES | YES          |
| 'root'@'127.0.0.1' | def           | CREATE TEMPORARY TABLES | YES          |
| 'root'@'::1'       | def           | CREATE TEMPORARY TABLES | YES          |
+--------------------+---------------+-------------------------+--------------+

**Comment by lzammit** [comment]
MariaDB [(none)]> SHOW GRANTS FOR pf@localhost;
+-------------------------------------------------------------------------------------------------------------------+
| Grants for pf@localhost                                                                                           |
+-------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'pf'@'localhost' IDENTIFIED BY PASSWORD '*7695DB01B550AE4DDF5E423C5E9B7387774F5253'         |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE ON `pf`.* TO 'pf'@'localhost' |
| GRANT SELECT ON `mysql`.`proc` TO 'pf'@'localhost'                                                                |
| GRANT DROP ON `pf`.`radius_nas` TO 'pf'@'localhost'                                                               |
+-------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
