### ISSUE TITLE
The database configuration API are exposed after the configurator has been closed.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#5246]
The API endpoints

/api/v1/configurator/config/database/{test,secure_installation,create,assign}
Are also exposed here
/api/v1/config/database/{test,secure_installation,create,assign}
So this means you can perform these actions after the fact.

They should be moved to thier own namespace suggested.
/api/v1/configurator/database/{test,secure_installation,create,assign}

**Comment by jrouzierinverse** [comment]
You could also avoid creating a new module by just using the pf::UnifiedApi::Controller::Configurator.

The new endpoints could be.
/api/v1/configurator/database_{test,secure_installation,create,assign}

**Comment by julsemaan** [comment]
Not sure its really critical to do this, we could always leverage them to reconfigure the DB from scratch after the initial configuration. If they don't get called they won't do anything so I don't see the absolute necessity to hide these after the configurator. Unless we implement features that use it or people call these API endpoints directly it won't do anything

**Comment by extrafu** [comment]
Should we then close this issue?

**Comment by extrafu** [comment]
@jrouzierinverse and @julsemaan let's agree on what we do with this one. Push it to v10.1? call it a day and close it?

**Comment by julsemaan** [comment]
For me its a non-issue as I see these API calls being useful post-configurator for people implementing external tools or if we decide to have a way to configure an external DB directly in the admin post-configurator. They don't hurt being there.

**Comment by cgx** [comment]
Their access should be limited to specific admin roles.

**Comment by jrouzierinverse** [comment]
I agree it is useful to be exposed.

But given the destructive nature of the API calls, having it exposed post configurator can be problematic since there is no separate admin role action permission level to control it.

**Comment by jrouzierinverse** [comment]
If you have CONFIGURATION_MAIN_CREATE you can access these APIs

**Comment by jrouzierinverse** [comment]
For now, we can just disable /api/v1/config/base/database/{test,secure_installation,create,assign} until we need them.

**Comment by nqb** [comment]
Agree with @jrouzierinverse
