### ISSUE TITLE
Configurator: Can't create the web admin username and password

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5248]
Looks like the default "admin" account is not populated and I can't put any.

I can't generate the password, if I click on generate nothing happens and I don't have any error.

![image](https://user-images.githubusercontent.com/5261214/77681678-15bbc600-6f6c-11ea-9a67-c867d8f0dda0.png)

**Comment by julsemaan** [comment]
Duplicate of #5229
