### ISSUE TITLE
"Can't re-evaluate access because no open locationlog entry was found"

### ISSUE THREAD

**Issue by johnnyb357** [inverse-inc/packetfence#525]
PacketFence v5.0.1 using inline mode only. 

I see a lot of this in my log since the upgrade. Guest users register but never get inserted in ipset. The error is sporadic and usually clears after a restart but not always. 

May 05 08:50:08 httpd.portal(32014) INFO: [5c:97:f3:c4:75:83] shouldn't reach here. Calling access re-evaluation. Make sure your network device configuration is correct. (captiveportal::PacketFence::Controller::CaptivePortal::unknownState)
May 05 08:50:08 httpd.portal(32014) INFO: [5c:97:f3:c4:75:83] re-evaluating access (redir.cgi called) (pf::enforcement::reevaluate_access)
May 05 08:50:08 httpd.portal(32014) WARN: [5c:97:f3:c4:75:83] Can't re-evaluate access because no open locationlog entry was found (pf::enforcement::reevaluate_access)

The error message came in between this in the system log. 

May  5 08:50:06 larry dhcpd: DHCPREQUEST for 172.20.10.3 from 5c:97:f3:c4:75:83 via vlan6: wrong network.
May  5 08:50:06 larry dhcpd: DHCPNAK on 172.20.10.3 to 5c:97:f3:c4:75:83 via vlan6
May  5 08:50:09 larry dhcpd: DHCPREQUEST for 172.16.2.222 from 5c:97:f3:c4:75:83 (Barrys-iPad) via vlan6
May  5 08:50:09 larry dhcpd: DHCPACK on 172.16.2.222 to 5c:97:f3:c4:75:83 (Barrys-iPad) via vlan6

**Comment by louismunro** [comment]
This would be better addressed using the mailing list.
We try to keep the Github Issues for confirmed bugs or requests for enhancements.

**Comment by johnnyb357** [comment]
Well I first tried the issue there and was ignored and it's pretty clearly a bug.
