### ISSUE TITLE
SNMP Tab in switch config is wrong

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5251]
**Describe the bug**
There is only the shared secret in the snmp switch tab.

![image](https://user-images.githubusercontent.com/1553962/77690202-4b1ae080-6f79-11ea-8035-5ba13ab883ff.png)

**Comment by fdurand** [comment]
Update, when i select advanced i have the option, it looks that the simple view map the snmp tab to the radius view.
![image](https://user-images.githubusercontent.com/1553962/77690742-30953700-6f7a-11ea-9df4-d6bab805f942.png)

**Comment by satkunas** [comment]
Exception is interrupting rendering, related to: https://github.com/inverse-inc/packetfence/issues/5253
