### ISSUE TITLE
Dashboard not showing after the configurator

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5252]
````
[root@pf-testing pf]# rpm -qa packetfence
packetfence-9.3.9-20200327103704.130318959.0007.devel.el7.x86_64
````

![image](https://user-images.githubusercontent.com/5261214/77758366-3423cf00-7009-11ea-8b56-892c296ffde8.png)
![image](https://user-images.githubusercontent.com/5261214/77758407-4bfb5300-7009-11ea-9ad6-8b4f6cc4b1bc.png)

````
[root@pf-testing pf]# journalctl -u packetfence-netdata
-- Logs begin at Fri 2020-03-27 08:08:55 EDT, end at Fri 2020-03-27 08:57:19 EDT. --
Mar 27 08:55:08 pf-testing.inverse.ca systemd[1]: Started Real time performance monitoring
```

**Comment by fdurand** [comment]
haproxy-admin needs to be restarted too since it generate a new configuration based on what you did in the configurator.

**Comment by cgx** [comment]
@fdurand — The last step of the configurator is a *pf start*. Should I replace it by a *pf restart*?

**Comment by fdurand** [comment]
Yes probably or pf start and haproxy-admin restart

**Comment by nqb** [comment]
@fdurand and @cgx,

Just to clarify, because I will need to update instructions to provision virtual machines used in CI.
After configuration has been done, we need to run:

 `pfcmd service pf restart`

or

```
pfcmd service haproxy-admin restart
pfcmd service pf restart
```

Thanks.

**Comment by nqb** [comment]
@fdurand and @cgx,

Just to clarify, because I will need to update instructions to provision virtual machines used in CI.
After configuration has been done, we need to run:

 `pfcmd service pf restart`

or

```
pfcmd service haproxy-admin restart
pfcmd service pf restart
```

Thanks.

**Comment by nqb** [comment]
Currently, `pfcmd service pf restart` is restarting `haproxy-admin`.

**Comment by cgx** [comment]
In the configurator, we restart `haproxy-admin` and *start* `pf`.

**Comment by lzammit** [comment]
Works!
