### ISSUE TITLE
API - Switch Meta 'type' has empty group

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5253]
Bug in meta for switches, there's an empty group causing an exception in a 3rd party component.

OPTIONS /config/switch/1.1.1.1

```js
meta.type.allowed = [
   {group: "", options: [{text: "", value: ""}]},
   ...
]
```
The empty (first) group should be omitted from the allowed options.

Switches conf
```
[1.1.1.1]
description=Temp
group=Test
uplink_dynamic=0

[group Test]
RoleMap=N
voiceRole=voice
mode=production
SNMPCommunityRead=public
VlanMap=Y
VoIPCDPDetect=Y
VoIPDHCPDetect=Y
AccessListMap=N
description=Switches Default Values
SNMPVersionTrap=1
cliAccess=N
VoIPEnabled=N
cliTransport=Telnet
REJECTVlan=-1
inlineRole=inline
SNMPCommunityTrap=public
UrlMap=N
registrationVlan=2
inlineVlan=6
inlineTrigger=
useCoA=Y
SNMPCommunityWrite=private
ExternalPortalEnforcement=N
wsTransport=http
always_trigger=1
type=Generic
VoIPLLDPDetect=Y
isolationVlan=3
SNMPVersion=1
uplink=dynamic
macSearchesMaxNb=30
voiceVlan=5
macSearchesSleepInterval=2
```

**Comment by jrouzierinverse** [comment]
An empty type is allowed for switches.

**Comment by satkunas** [comment]
@jrouzierinverse use `allowEmpty` meta attribute for that. This empty item in the array is causing an excpetion in a 3rd party component which I cannot control. The only other option is to add some overhead in the meta processing and filter out the empty result manually.

**Comment by satkunas** [comment]
@jrouzierinverse use `allowEmpty` meta attribute for that. This empty item in the array is causing an excpetion in a 3rd party component which I cannot control. The only other option is to add some overhead in the meta processing and filter out the empty result manually.

**Comment by jrouzierinverse** [comment]
no need for a new attribute when we already have required.
Which is false for type in groups.
I will remove the empty type but you would need to respect the required flag if you don't already.

**Comment by jrouzierinverse** [comment]
@satkunas I removed the empty type and group. Just verify if the frontend respects the required option.
