### ISSUE TITLE
Perl and Golang unit tests in error

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5258]
**Perl unit tests**
https://gitlab.com/inverse-inc/packetfence/-/jobs/489588804#L433

**Golang unit tests**
https://gitlab.com/inverse-inc/packetfence/-/jobs/489588823#L517

@jrouzierinverse, it seems caused by commits added on last Saturday.

**Comment by jrouzierinverse** [comment]
Fixed by 28a4b4f
