### ISSUE TITLE
API - 503 response from POST /login has wrong mime

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5263]
When logging in a 503 response code should have a javascript response:
```html
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

400 response code works:
```json
{"token":"[snipped]"}
```

**Comment by jrouzierinverse** [comment]
Is this a +1 (patch release) or just for v10

**Comment by jrouzierinverse** [comment]
How can replicate this?

**Comment by jrouzierinverse** [comment]
I am not able to replicate this.

**Comment by jrouzierinverse** [comment]
I believe fc26479421e174e67adf6e08287922e57242ab14 should take care of this.

**Comment by jrouzierinverse** [comment]
Is this an issue in 9.3?

**Comment by satkunas** [comment]
> I believe fc26479 should take care of this.

Issue still exists in devel.

**Comment by jrouzierinverse** [comment]
d937205 fixed some issues with improper usage of the 'errorfile' directive

**Comment by satkunas** [comment]
Issue still exists
POST :1443/admin/login
payload: `username=test&password=test`

```html
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

Note that `test` is a local person that has limited admin roles.
