### ISSUE TITLE
Configurator: Can't clone VLAN interface

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5264]
Source of the clone:
![image](https://user-images.githubusercontent.com/5261214/77944308-bbcd4000-728c-11ea-845a-3e613b1b0372.png)

Cloned configuration: 

![image](https://user-images.githubusercontent.com/5261214/77944257-a0facb80-728c-11ea-9eb6-f6d9d56b5d8e.png)

![image](https://user-images.githubusercontent.com/5261214/77944211-8cb6ce80-728c-11ea-954e-4072101c2862.png)

![image](https://user-images.githubusercontent.com/5261214/77944200-8294d000-728c-11ea-81bc-c14ce8d87d82.png)

**Comment by cgx** [comment]
I have this error in my logs:

```
ERROR pfperl-api(13151): Modification of a read-only value attempted at /usr/share/perl5/vendor_perl/HTML/FormHandler.pm line 605.
```
