### ISSUE TITLE
API OPTIONS /api/v1/config/switch/<name> → one empty switch type

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#5266]
If I use `pfperl-api` to fetch allowed types for a switch, I have a valid response. Ex:

```
pfperl-api get -M OPTIONS '/api/v1/config/switch/192.168.0.1' | jq .meta.type
{
  "allowed": [
    {
      "group": "Accton",
      "options": [
        {
          "supports": [
            "RadiusDynamicVlanAssignment"
          ],
          "text": "Accton ES3526XA",
          "value": "Accton::ES3526XA"
        },
        {
          "supports": [
            "RadiusDynamicVlanAssignment"
          ],
          "text": "Accton ES3528M",
          "value": "Accton::ES3528M"
        }
      ]
    },
...
```

But when doing the same call from the Web admin, the first allowed type is empty:

<img width="411" alt="Screen Shot 2020-03-30 at 5 17 47 PM" src="https://user-images.githubusercontent.com/1088448/77963018-a404b480-72aa-11ea-8250-563ead48857a.png">

**Comment by jrouzierinverse** [comment]
Is this an issue in 9.3?

**Comment by cgx** [comment]
I don't the problem anymore with the latest code and after restarting the services.
