### ISSUE TITLE
pfacct doesn't report metrics to dashboard

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5267]
**Describe the bug**
I don't see any RADIUS accounting metrics in the RADIUS graph in the dashboard

**To Reproduce**
1. Send some accounting to pfacct
2. Look at dashboard

**Expected behavior**
RADIUS metrics should be displayed

**Comment by fdurand** [comment]
We probably needs to add statsd in the pfacct and add new graph on the dashboard.

**Comment by jrouzierinverse** [comment]
The problem is you had no nodes in the database.
I was able to view the metric reports once I had a matching node.

**Comment by julsemaan** [comment]
Do we really need matching nodes for the graphs ?

I'm not talking about the reports, I'm talking about the graphs in the dashboard in the RADIUS tab

**Comment by jrouzierinverse** [comment]
You are right.
I will look into that.
