### ISSUE TITLE
web admin: unable to create a new switch or switch group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5270]
**Describe the bug**
Trying to create a new switch or switch group: nothing happens.

I'm testing on latest devel packages.

**To Reproduce**
1. Go to Switches menu
2. Click on 'New switch'

**Expected behavior**
Should display a window to create a new switch

**Additional context**
All API calls return 200.

**Comment by jrouzierinverse** [comment]
It seems to be created but it does not show up until after you refresh the page.
