### ISSUE TITLE
Creating node via API with missing MAC address field

### ISSUE THREAD

**Issue by andreweinkoetz** [inverse-inc/packetfence#5285]
**Describe the bug**
Creating a new node via REST-API without providing a MAC address is possible and does not result in an error. Results in errors when trying to view details making it impossible to delete the entry using the admin UI.

**To Reproduce**
1. Create a new node via calling /api/v1/nodes (POST) without providing a MAC address
2. Login to admin console (URL:1443/admin/alt#/login)
3. Click on node entry with empty MAC address field

**Screenshots**
![image](https://user-images.githubusercontent.com/14924669/78344836-3eac0e80-759d-11ea-8bcc-4641ef2c1779.png)
![image](https://user-images.githubusercontent.com/14924669/78344864-48ce0d00-759d-11ea-9910-af88118d9731.png)

**Expected behavior**
Trying to add a new node without providing a MAC address results in 4XX HTTP Error Response.

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version 9.0.1

**Comment by jrouzierinverse** [comment]
Thank you for reporting this.

**Comment by nqb** [comment]
Need to go in maintenance
