### ISSUE TITLE
Allowed to type while the DB is auto-configuring in the configurator

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5289]
**Describe the bug**
In the configurator, while the DB is automagically being configured,I'm able to type in the fields that haven't yet been processed. This means that while its happening I could try to name my pf DB user `pf_julien` but then while I'm typing its going to process the field when I just typed `pf_jul`

Also, there is no way to stop that automated setup. I think this should be user triggered and not just happening when the page loads. That will fix the issue of the user typing in the fields not expecting the stuff happening automatically.

**Comment by julsemaan** [comment]
The idea would be:

When the page loads, all the fields appear as empty.

There is a button in the database section that says "Configure database automatically"

When the user presses that button, it does what the page is currently doing on page loads which is attempting to configure all the fields of the database automatically.

The key here IMO is that it doesn't happen on page load and the user can pick to configure the DB automatically or not.

**Comment by cgx** [comment]
I'll use a toggle button instead of a standard button. When enabled, clicking *Next step* will trigger the automatic database configuration.
