### ISSUE TITLE
Netgear M Series update locationlog from accounting data

### ISSUE THREAD

**Issue by aherbach88** [inverse-inc/packetfence#529]
Add feature on M Series switches to update locationlog from RADIUS accounting data.  According to packetfence log, feature is not implemented on M Series.

**Comment by julsemaan** [comment]
This feature was made for wireless access points to support roaming since we do not receive a RADIUS request when the device roams (due to caching of the controller). 

The switches do not need this feature since they send a RADIUS request whenever the device moves.
