### ISSUE TITLE
CoA/Disconnect is not recorded in RADIUS audit log

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5291]
**Describe the bug**
I performed an access reevaluation and it wasn't logged into the RADIUS audit log

**To Reproduce**
1. Connect a device to Meraki::MR_v2 
2. Perform access reevaluation

**Additional context**

In my case the CoA timed out and didn't work, I'd still expect it to be logged. I don't yet have CoA working in my lab so can't know for sure right now if it will be there in the event it does work.

My logs:
```
Apr  3 14:51:10 test-fresh pfqueue: pfqueue(21739) INFO: [mac:94:db:c9:38:85:5b] [94:db:c9:38:85:5b] DesAssociating mac on switch (192.168.0.209) (pf::api::desAssociate)
Apr  3 14:51:10 test-fresh pfqueue: pfqueue(21739) INFO: [mac:94:db:c9:38:85:5b] deauthenticating (pf::Switch::Meraki::MR_v2::radiusDisconnect)
Apr  3 14:51:18 test-fresh packetfence_httpd.portal: httpd.portal(23246) INFO: [mac:00:11:22:33:44:55] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Apr  3 14:51:20 test-fresh pfqueue: pfqueue(21739) WARN: [mac:94:db:c9:38:85:5b] Unable to perform RADIUS CoA-Request on (192.168.0.209): Timeout waiting for a reply from 192.168.0.209 on port 3799 at /usr/local/pf/lib/pf/util/radius.pm line 184. (pf::Switch::Meraki::MR_v2::catch {...} )
Apr  3 14:51:20 test-fresh pfqueue: pfqueue(21739) ERROR: [mac:94:db:c9:38:85:5b] Wrong RADIUS secret or unreachable network device (192.168.0.209)... (pf::Switch::Meraki::MR_v2::catch {...} )
```

**Comment by julsemaan** [comment]
Making CoA working was faster than I thought, so I can confirm now that the record is there if the Meraki AP replies to the CoA, it **will not** be there if there is no reply from the equipment

**Comment by nqb** [comment]
Already seen this behavior in the past, I agree that we need to have timeout records in Audit logs.

**Comment by jrouzierinverse** [comment]
Question How should we show an error happened when recording in the audit log.

**Comment by fdurand** [comment]
Something like "Error - Timeout"
