### ISSUE TITLE
New Network Behavior Policy - Devices Included broken

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#5303]
When trying to search for devices to include (or exclude), we get 404 errors and it simply does not work. See screenshot.

<img width="1795" alt="Screen Shot 2020-04-06 at 3 18 28 PM" src="https://user-images.githubusercontent.com/1616141/78596941-a02ce100-781a-11ea-8a82-a03e29f49123.png">

**Comment by satkunas** [comment]
I'm going to revert https://github.com/inverse-inc/packetfence/commit/09d49c4266e2f1fa702761b0ed96c9d7ee407a05

Which was a workaround for a previous issue, but it was incorrectly categorized. Reverting this opens another issue that the patch above was meant to fix: https://github.com/inverse-inc/packetfence/issues/5307
