### ISSUE TITLE
Admin API audit log: entries are created with invalid date

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5304]
**Describe the bug**
The date in the API admin audit log entries is invalid

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/78598343-277b5400-781d-11ea-9a33-ba693565cf73.png)

Unless I went back in time to year 1

**Comment by julsemaan** [comment]
![image](https://user-images.githubusercontent.com/3857942/78598397-3eba4180-781d-11ea-952d-d678dfbb914f.png)

**Comment by extrafu** [comment]
I think we'll start fresh at Year 1 once COVID-19 is over.
