### ISSUE TITLE
Filter Engines meta - do not urlencode allowed_lookup

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5307]
OPTIONS /api/v1/config/filter_engines/radius_filters

Meta -> answers -> item -> properties -> type -> allowed_lookup is URL encoded as `"\/api\/v1\/radius_attributes"`. The front-end applies URL encoding to these paths, causing this to be double encoded and passing the baseURL check without a hit, finally causing the url to be prefixed with /api/v1 twice as: `/api/v1/api/v1/radius_attributes`. 

To conform to search_path used elsewhere, this search path should not be url encoded as just "/api/v1/radius_attributes"

**Comment by jrouzierinverse** [comment]
This happening at another level.
Everything is fine on the backend.

```
./sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/radius_filters | jq .meta.answers.item.properties.type.allowed_lookup.search_path 

```
```
"/api/v1/radius_attributes"
```
