### ISSUE TITLE
Configurator: Automatic configuration of the DB should be enabled by default

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5309]
To make it simpler for the common case, the automatic configuration of the DB should be enabled by default

Seems pretty simple to do but I prefer to let @cgx or @satkunas do it since toggling the default value on page load may have unexpected side effects

**Comment by lzammit** [comment]
I think it was enabled by default before and created the db and root and pf accounts automatically. If you enable it by default, it would required a "run" button.

**Comment by julsemaan** [comment]
There is a toggle now but the toggle is disabled by default, it wouldn't run it automatically AFAIK, it will run when you click next from what I understood
