### ISSUE TITLE
configurator: unable to detect management interface on Debian

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5313]
**Describe the bug**
On Debian 9, at first step of configurator, my first interface is not detected as management.

**Screenshots**
![Capture d’écran de 2020-04-07 07-47-51](https://user-images.githubusercontent.com/10830260/78664963-5a811e80-78d5-11ea-9b1d-b4144ae56aca.png)

**Expected behavior**
First interface autoconfigured as management.

**Comment by cgx** [comment]
Any error in your JavaScript console?

**Comment by cgx** [comment]
What's the result of the API call to `/api/v1/configurator/config/interfaces`?

**Comment by nqb** [comment]
@cgx: sorry I missed to provide you these results.
- Screenshot of console web browser
![Capture d’écran de 2020-04-08 07-52-52](https://user-images.githubusercontent.com/10830260/78749211-168e2800-796e-11ea-9b21-1353f64add9b.png)

- [API response](https://gist.github.com/nqb/2312c10ea3622db5624ae6b88b606f99)

**Comment by nqb** [comment]
It seems to work now.

EDIT: in fact, no.

Some details about my setup, my first interface is in DHCP.

**Comment by nqb** [comment]
It works.
