### ISSUE TITLE
Error setting admin password during step 2

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5315]
**Describe the bug**
If you pick to auto-configure the database in step 2, it attempts to set the admin password before the database has finished to be setup which causes an error and prevents you from moving forward

**To Reproduce**
1. Pick DB auto-configuration at step 2
2. Click on next step

![image](https://user-images.githubusercontent.com/3857942/78691548-bbedc100-78c6-11ea-923d-504afd9a72cd.png)

**Comment by julsemaan** [comment]
My build version (latest AFAIK):
packetfence-9.3.9-20200407150050.133709354.0007.devel.el7.x86_64

**Comment by drthiruna** [comment]
Error setting admin password during step 2. This issue is still noticed in my fresh installation with ZEN on ESXi 6
I tried with auto DB and manual DB settings 
Both time it shows the error.
