### ISSUE TITLE
Delay security event is not delayed.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5318]
**Describe the bug**
Create a security event with delayed value then trigger this security event, i will be imediate.
 

**To Reproduce**
Create this security event:
```
[3000006]
trigger=
actions=autoreg,role
desc=evenement 2000
enabled=Y
access_duration=12h
delay_by=2m
target_category=guest
```
Then trigger it on a node, you will see that the security event is triggered right away.

**Comment by jrouzierinverse** [comment]
Darren you are stripping off the ':' in the value.

**Comment by jrouzierinverse** [comment]
Nope this is on me let me fix it.

**Comment by jrouzierinverse** [comment]
If this was added from the GUI the delay will not happen.
This was the behavior from the old admin.
So how can I replicate this?

**Comment by fdurand** [comment]
Ok it has been made from the admin gui.
Just tried with dhcp traffic and the security event is delayed.
