### ISSUE TITLE
Some DHCP settings are required although DHCP is disabled

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5319]
**Describe the bug**
If you create a routed network and you disable the DHCP server on it, you still have to pick a backend and an algorithm

**Expected behavior**
Either it should have the default settings or not be required to select a value when DHCP is disabled

**Comment by julsemaan** [comment]
There are also a lot of other settings that are required when saving:
![image](https://user-images.githubusercontent.com/3857942/78699170-74b8fd80-78d1-11ea-8091-64ed195ef945.png)

**Comment by extrafu** [comment]
@julsemaan Who should be assigned to this one? @satkunas ?

**Comment by julsemaan** [comment]
Yes @satkunas should be able to fix this without any problem

**Comment by satkunas** [comment]
Another issue may cause inconsistencies until fixed: https://github.com/inverse-inc/packetfence/issues/5344

**Comment by satkunas** [comment]
@julsemaan please re-test and close this issue if all is good

**Comment by julsemaan** [comment]
Its still missing all the adjustments in the backend to prevent these from happening:
![image](https://user-images.githubusercontent.com/3857942/78912322-73184280-7a55-11ea-95ba-f9632120bf53.png)

**Comment by extrafu** [comment]
@jrouzierinverse Take care of the backend part.
