### ISSUE TITLE
Error when you try to save an already created radius filter.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5320]
**Describe the bug**

A radius filter with:

![image](https://user-images.githubusercontent.com/1553962/78701542-358cab80-78d5-11ea-88a1-ad98c9a3208b.png)

Save it then edit it:

![image](https://user-images.githubusercontent.com/1553962/78701629-594ff180-78d5-11ea-87e9-22cc41890aed.png)

As you can see the reply is in lower case and it in the request.

![image](https://user-images.githubusercontent.com/1553962/78701901-c499c380-78d5-11ea-9f86-8a6f98903eb9.png)

**Comment by jrouzierinverse** [comment]
This maybe on me I will look at it later.

**Comment by fdurand** [comment]
If i set in the form Reply then is the request it's in lower case, not sure it's a backend issue.

**Comment by jrouzierinverse** [comment]
There was a serialization issue on the backend.
I fixed it with 2fd7dedada65c1670242c562eb544759db5fa3dd
 can you retry?

**Comment by fdurand** [comment]
It works.
