### ISSUE TITLE
Setting an empty login remaining value sets 0 when editing user

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5322]
**Describe the bug**
When editing a user, if you select login remaining and put an empty value (empty means unlimited), it actually saves 0 which is no more logins remaining

**To Reproduce**
1. Go in the admin, edit a local user, go in the password tab
2. Set login remaining to an empty value
3. Save it
4. Refresh the user, it has 0 login remaining

**Expected behavior**
Password entry should be NULL meaning unlimited logins

This is the payload the admin is sending:
```
{"pid":"bob","login_remaining":""}
```

I don't know if the problem is the frontend sending the empty string instead of null or the backend not handling it correctly. Assigning @jrouzierinverse for confirmation.

**Comment by jrouzierinverse** [comment]
If login_remaining is an empty string MariaDB converts it to a zero.

Options:
* Send a null from the frontend. (Works right now)
* Give an error when login_remaining is non-numeric or not null
* Change login_remaining to a null value when an empty string is given.

**Comment by julsemaan** [comment]
The logic would be that the frontend sends `null` since its the actual value that represents the unlimited logins. @satkunas, can this be easily adjusted?

**Comment by satkunas** [comment]
I've modified the forms to default to `null` instead of an empty string "" when a value is empty or is not set. Warning, there could be dragons here.
