### ISSUE TITLE
configurator: missing favicon on Debian

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5325]
**Describe the bug**
Favicon is not found when reaching `https://IP_MGMT:1443/admin/alt#`

**To Reproduce**
1. Install a fresh Debian 9
2. Try to reach configurator

**Expected behavior**
Favicon should be visible. Added recently by @cgx in https://github.com/inverse-inc/packetfence/commit/76195fe8fc65d19dd5cf3db8c83a0d82ad65474c

**Additional context**
When I reach `/admin/alt`, I got:
```html
<link rel=icon href=/admin/alt/favicon.ico>
```
but `/usr/local/pf/html/pfappserver/root/static.alt/dist` doesn't contains `favicon.ico`.

**Comment by nqb** [comment]
@cgx, my idea is to adapt packaging to not include `static.alt/public` directory in packages because it seems useless: `index.html` seems generated during `npm` build.

So copy `favicon.ico` to `dist` directory should be enough. Let me know what you think about that.

**Comment by cgx** [comment]
@nqb Yes. When generating the static JS/CSS files, the favicon is copied from `public` to `dist`. The packages must include everything under `dist`.

**Comment by nqb** [comment]
>  When generating the static JS/CSS files, the favicon is copied from `public` to `dist`. The packages must include everything under `dist`

Ok, so in fact `favicon.ico` already work but not on Debian. Current code of this PR need to be adapt.
