### ISSUE TITLE
configurator: step 1 try to replace default route without any action

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5327]
**Describe the bug**
When I go on the configurator for the first time, I noticed that PF try to replace my current default route without any action on my side.

**To Reproduce**
1. Have your first network interface configured in DHCP and default route reachable through this interface (on Debian)
1. Open configurator for the first time
1. Check your route table

**Screenshots**
#### Before going to configurator
```
root@pfdeb9dev:/usr/local/pf# ip r
default via 192.168.121.1 dev ens5 proto dhcp src 192.168.121.155 metric 1024
172.17.17.0/24 dev ens6 proto kernel scope link src 172.17.17.12
192.168.121.0/24 dev ens5 proto kernel scope link src 192.168.121.155
192.168.121.1 dev ens5 proto dhcp scope link src 192.168.121.155 metric 1024
```
#### After
```
root@pfdeb9dev:/usr/local/pf# ip r
default via 192.168.121.1 dev ens5
default via 192.168.121.1 dev ens5 proto dhcp src 192.168.121.155 metric 1024
172.17.17.0/24 dev ens6 proto kernel scope link src 172.17.17.12
192.168.121.0/24 dev ens5 proto kernel scope link src 192.168.121.155
192.168.121.1 dev ens5 proto dhcp scope link src 192.168.121.155 metric 1024
``` 

**Expected behavior**
Configurator should only try to detect default route if no action have been done on user side. A GET API call must not do any change on system.

**Additional context**
Not tested on CentOS.

Logs:
```
Apr  8 08:44:25 pfdeb9dev pfhttpd: api-frontend-access 127.0.0.1 - - [08/Apr/2020:08:44:25 +0000] "GET /api/v1/configurator/config/interfaces HTTP/1.1" 200 2179 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr  8 08:44:25 pfdeb9dev packetfence: FATAL -e(8756): unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at -e line 1.
 (pf::db::db_connect)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): New default gateway successfully injected (pfappserver::Model::Config::System::setDefaultRoute)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Instantiate a new object of type Debian (pfappserver::Model::Config::SystemFactory::getSystem)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Interface creation successfull (pfappserver::Model::Config::System::Debian::writeNetworkConfigs)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Persistent network configurations successfully written (pfappserver::Model::Config::System::write_network_persistent)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): New default gateway successfully injected (pfappserver::Model::Config::System::setDefaultRoute)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Instantiate a new object of type Debian (pfappserver::Model::Config::SystemFactory::getSystem)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Interface creation successfull (pfappserver::Model::Config::System::Debian::writeNetworkConfigs)
Apr  8 08:44:26 pfdeb9dev packetfence: INFO pfperl-api(8782): Persistent network configurations successfully written (pfappserver::Model::Config::System::write_network_persistent)
```

**Comment by nqb** [comment]
After troubleshooting, I noticed that this change occur when I set any interface as management.

I was thinking it was automatic, certainly because when auto configuration works, API patch my first interface and trigger this change.

Edited steps to reproduce:
- Have several interfaces with the first one configured in DHCP
- Set any interface as management
- Check your route table

**Comment by julsemaan** [comment]
If you set your interface as management and save it, it also sets the interface in static IP and has it managed by PF so its normal that it performs modifications.

Also the route is also perhaps added by the fact the gateway is being set on step 1 and saved when you go to step 2. The user needs to ensure the gateway is right before proceeding as even if its not changed, it will be saved to match the "PF" standard way of managing interfaces

**Comment by nqb** [comment]
> If you set your interface as management and save it, it also sets the interface in static IP and has it managed by PF so its normal that it performs modifications.

I agree.

> Also the route is also perhaps added by the fact the gateway is being set on step 1 and saved when you go to step 2

No, I didn't go to step 2. I only saved interface configuration.

**Comment by julsemaan** [comment]
To me the fact this changes is normal since we're saving the interface associated to management.
Also, the route that is being saved AFAIK, its just saying that the default gateway is statically assigned versus before it was obtained via DHCP so it makes sense that this happens if you just set the interface statically

**Comment by nqb** [comment]
See with @julsemaan, we will not try to fix this issue.
