### ISSUE TITLE
AeroHive AP roles dont work for unregistered devices

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/packetfence#533]
AeroHive.pm is overloading returnRadiusAccessAccept and uses this line to get the role for a node
my $role = $roleResolver->getRoleForNode($mac, $self);
...which only returns roles for registered nodes i think.

This should be the correct way to determine the role:

$role = $self->getRoleByName($user_role);

PF 5.0.2

**Comment by fdurand** [comment]
Yes you are true, Aerohive.pm use the old way to determine a role. Feel free to do a patch and a pull request.

**Comment by erSitzt** [comment]
#534

**Comment by fdurand** [comment]
You can use the same logic than here : https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Aruba.pm#L402

**Comment by erSitzt** [comment]
Ok, will do !

**Comment by erSitzt** [comment]
PR was merged,
