### ISSUE TITLE
API POST /api/v1/config/base/database/test → return different message when MariaDB is down

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#5345]
When testing the database access in the configurator, it would useful to have a different error message when the database is not accessible:

```bash
$ /usr/local/pf/sbin/pfperl-api get -M POST -c '{"username":"root"}' '/api/v1/configurator/config/base/database/test' | jq
{
  "message": "Error in connection to the database mysql with user root",
  "status": 500
}
```

**Comment by satkunas** [comment]
@cgx would this be better as a `/service` endpoint instead?

**Comment by julsemaan** [comment]
You can check the status of the DB using /api/v1/system_service/packetfence-mariadb/status before firing this call

**Comment by cgx** [comment]
@julsemaan Good point. I forgot about `system_service`.
