### ISSUE TITLE
Devices detected via pfdhcplister show an invalid unregdate

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5349]
**Describe the bug**
Devices detected via pfdhcplister show an invalid unregdate

**To Reproduce**
1. Go edit a node that have been detected via pfdhcplistener

**Screenshots**

![image](https://user-images.githubusercontent.com/1553962/79011141-68cb7680-7b31-11ea-96dd-1b00793286bf.png)

**Expected behavior**
Should be empty.

**Comment by nqb** [comment]
Same on my side but it occurs on a node that has been registered using captive portal.
