### ISSUE TITLE
Portal profile "Mandatory fields" should be renamed to "Custom fields"

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#535]
Exposed "Mandatory Fields" of portal profiles should be renamed to "Custom Field".

**Comment by jrouzierinverse** [comment]
Renaming "Mandatory fields" to "Custom fields" could cause confusions between the custom fields in the person table.

custom_field_1 custom_field_2 custom_field_3 custom_field_4 custom_field_5 custom_field_6 custom_field_7 custom_field_8 custom_field_9

**Comment by dwlfrth** [comment]
I difficultly see how it can cause confusion... I can explain you later....

Cheers!
dw.

## 

Derek Wuelfrath
dwuelfrath@inverse.ca :: +1.514.447.4918 (x110) :: +1.866.353.6153 (x110)

**Comment by dwlfrth** [comment]
*hardly (damn phone)

Cheers!
dw.

## 

Derek Wuelfrath
dwuelfrath@inverse.ca :: +1.514.447.4918 (x110) :: +1.866.353.6153 (x110)

**Comment by jrouzierinverse** [comment]
Having "Optional Fields" and "Mandatory fields" make more sense.
So we can have fields that are not required also displayed.

Name and Email to mandatory.
But Address, City, Postal Code to optional
Would do the following

`*` Name
`*` Email
`o` Address
`o` City
`o` Postal Code

**Comment by julsemaan** [comment]
We should decide whether we want mandatory and optional fields or stick to only mandatory fields

**Comment by jrouzierinverse** [comment]
This should be closed since custom fields were moved to the PortalModules.
