### ISSUE TITLE
PFAcct : Fails to trigger security event based on 3Gb quota

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5354]
security event:
````
[1100012]
desc=Device based Bandwidth Limit example (Android, 2GB/month)
trigger=accounting::TOT3GBM
grace=10m
access_duration=12h
enabled=Y
````
![image](https://user-images.githubusercontent.com/5261214/79152642-8d765700-7d9a-11ea-8187-65f53e5d28bf.png)

**Comment by julsemaan** [comment]
I managed to get it to work, but that was with a single session that was never closed and still active. Not sure if past sessions are properly taken into account

**Comment by julsemaan** [comment]
I think it may be related to the accounting window, a security event can only be opened once in the trigger window (so if its X GB per month, the security event won't reopen for another month)

So things are likely working as designed from what I can tell in the logs.

@lzammit, try truncating the security_event table and see if it triggers fine

**Comment by lzammit** [comment]
It triggers correctly after cleaning the security event.

**Comment by extrafu** [comment]
So we can close the issue?

**Comment by julsemaan** [comment]
Yes!
