### ISSUE TITLE
configurator: changing management interface is not possible

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5356]
**Describe the bug**
When I started to use configurator, my first interface is auto-configured as management interface but I don't want this one to be selected. So I tried to set it to "none" and save. But when I go back to interfaces listing, my first interface is reconfigured as management by API call.

**To Reproduce**
1. Open configurator with your first interface auto-configured as management
2. Edit your first interface and set type to "None" in place of "Management"
3. Save
4. Go back to interface display

A new API call is sent to change type of first interface.

**Expected behavior**
Auto-configuration should occur only once.

**Comment by nqb** [comment]
In fact, this issue occurs if you don't have any other interfaces configured as management and you want to achieve this scenario:
1. unconfigure your current management interface
2. configure a new management interface

**Comment by cgx** [comment]
Instead of automatically setting a management interface, I propose to have a button titled **Detect Management Interface**.
