### ISSUE TITLE
API: /configurator/config/interfaces let you configure several management interfaces

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5357]
**Describe the bug**
When you configure your interfaces, it's possible to set several interfaces with `type=management`. Considering #5356 issue, you can have a setup broken at end of configurator.

**To Reproduce**
1. Have at least two network cards
2. Open configurator page and see that your first network card is auto-configured as management
3. Configure your second network card as management
4. Save

=> You got two network cards configured as management in `pf.conf`.

**Expected behavior**
Only one network card can be configured as management.

**Comment by julsemaan** [comment]
This is fixed in ec25c3ff1ba570ecb6f7ab9da41f9757190f565a

I don't know if the configurator will be impacted by the following bug though: #5363
