### ISSUE TITLE
Switch template: snmpDisconnect setting is not handle by frontend

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5360]
**Describe the bug**
If you display a switch template that have `snmpDisconnect` setting enabled, frontend doesn't show this state.

**To Reproduce**
1. Go to 'Switch template' menu
2. Click on HP::Switch

=> SNMP Disconnect appear as disabled (default)

**Expected behavior**
SNMP Disconnect should appear as **enabled**

**Additional context**
API returns correct `snmpDisconnect` setting.

**Comment by jrouzierinverse** [comment]
In the backend, snmpDisconnect is disabled by default.
The frontend represents this do we want to change this behavior?

**Comment by nqb** [comment]
@jrouzierinverse, in HP::Switch template module, `snmpDisconnect=enabled` but frontend doesn't show this state.
