### ISSUE TITLE
DHCP Filter error in condition

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5365]
**Describe the bug**
Create a dhcp filter like that (from the admin gui):
```
[leaseTime]
run_actions=disabled
status=enabled
answer.0=51 = 31
description=Extend lease time
scopes=Discover,Request
condition=node_info.mac == "78:f8:82:9f:11:9d"
```
edit it back then you will have that:

![image](https://user-images.githubusercontent.com/1553962/79241170-b18c7380-7e40-11ea-8040-96ea094cf9ec.png)

**Comment by jrouzierinverse** [comment]
The problem is the ```top_op=and``` is not in the config.
Was this created by hand or via the GUI?

**Comment by fdurand** [comment]
via the gui

**Comment by jrouzierinverse** [comment]
I created it via the GUI and did not have that problem.

**Comment by fdurand** [comment]
Ok looks to be because i did and upgrade and the previous filter wasn't compatible with the new format.
