### ISSUE TITLE
The connection_type value of a VLAN filter cannot be selected (its a text input)

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5366]
**Describe the bug**
The connection_type value of a VLAN filter cannot be selected (its a text input)

**To Reproduce**
1. Edit the pf_deauth_from_wireless_secure VLAN filter
2. Look at the filter's first condition

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/79241704-6757c200-7e41-11ea-9831-6746238da565.png)

**Expected behavior**
The value of the connection type should be a select box containing the various connection types

**Comment by julsemaan** [comment]
As discussed on our private channel, we should allow custom values that are outside the selectable ones to be used. Will reopen this instead of opening another issue just for that

**Comment by julsemaan** [comment]
If you set a custom value either through the advanced mode or through the file, the value is not modified on subsequent saves unless you start editing it, so we can move this to a +1 and address it later

**Comment by extrafu** [comment]
🕺
