### ISSUE TITLE
Unit is wrong on pfacct graph in dashboard

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5370]
**Describe the bug**
It says millisecond instead of what I guess should be packets/s

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/79336423-b3fad600-7ef1-11ea-99eb-fbcf0acfcf8d.png)

**Comment by fdurand** [comment]
It's because we use some timer in pfacct.

**Comment by julsemaan** [comment]
It seems it would be just as simple as adding `data-units="packets/s"` on the graph but the Dashboard.vue file is a bit too abstract for me to know where to add this in the graph.

@cgx, @satkunas, any guidance on how to add this ?
