### ISSUE TITLE
About WMI Rules Issue

### ISSUE THREAD

**Issue by nvyao** [inverse-inc/packetfence#5378]
Hello,
I want to achieve access to terminal machines through WMI check; The judgment conditions are as follows:
If the terminal machine does not run the abc.exe process, it is not allowed to connect to the network。But not right

My conf:
1、Request：select Name from Win32_Process
2、Rules Actions：
[DingTalk]
attribute = Name
operator = match
value = DingTalk.exe

[1:DingTalk]
action=trigger_violation
action_param = mac = $mac, tid = 888888, type = INTERNAL

**Comment by julsemaan** [comment]
You should post on the mailing list for help with this.
