### ISSUE TITLE
v10 Filter Engines is only displaying 25 filters

### ISSUE THREAD

**Issue by cdcrawford** [inverse-inc/packetfence#5379]
**Describe the bug**
I have a large number of filters in my PacketFence install due to the switch infrastructure that we're using. I have ~150 Filters. I can only see 25 Radius Filters in the Web UI. 

**To Reproduce**
1. Have over 26 Filters. I'm using radius Filters. I suspect it can also be done using any of the types of filters
1. Go to 'Configuration -> Advanced Access Configuration'
2. Click on 'Filter Engines'
3. Only see 25 Filters listed per type.

**Attachments**
1. Screenshot of the error. ![PacketFence-v10-DisplayError](https://user-images.githubusercontent.com/3090648/80001939-5ccaa780-8495-11ea-916f-ab3831879236.png)
2. Filter Config File [PacketFence-v10-Filters-BugReport.txt](https://github.com/inverse-inc/packetfence/files/4517094/PacketFence-v10-Filters-BugReport.txt)

**Expected behavior**
- Paginated display of filters, similar to nodes, roles, etc.
- Ability to edit all Filters in the Web UI.

**Other Information**
- Going to: https://packetfence/admin/alt#/configuration/filter_engines/radius_filters/WiredVLAN%2051 Yeilds a page.
- Also, changing the URL to: https://packetfence:1443/admin/alt#/configuration/filter_engines/radius_filters/WiredVLAN%201248 also yields the same page.
- Filters also work as they should. They are just not able to be changed VIA the Web UI. Changes currently are required to be done through the CLI followed by a pfcmd configreload hard, and a restart of services.

**Comment by julsemaan** [comment]
Pretty sure this is a couple line fix for @satkunas, its the API that returns 25 items by default when listing items, just need to get that adjusted

**Comment by jrouzierinverse** [comment]
The ideal solution is to have a way to paginate for the filter engines.
However, The quick fix is to increase the size of the items returned.

**Comment by julsemaan** [comment]
The thing with pagination is that reordering of the filters will be painful

**Comment by jrouzierinverse** [comment]
Then we must show them all then.
