### ISSUE TITLE
SMS email has "Bare Line Feed Characters" Status code: 550 5.6.11 

### ISSUE THREAD

**Issue by rdm128** [inverse-inc/packetfence#5380]
**Describe the bug**
SMS to email failing for certain MTA's because the message body ends with \n and needs to be \r\n /lib/pf/Authentication/Source/SMSSource.pm

**To Reproduce**
1. added sms.clicksend.com as SMS Gateway to db
2. Sent a test SMS through the new gateway
3. Received a bounce message

**Screenshots**
No screenshot, but here's text from the bounce.
"This error occurs when the email program or device used to create or send an email message adds bare line feed characters into the message. When bare line feed characters are included in a message, the SMTP protocol chunking feature is required to transmit the message between email servers. Chunking uses the SMTP protocol BDAT command, but the recipient's email server doesn't support the BDAT command."

**Expected behavior**
Message should have been received by clicksend MTA and delivered to SMS carriers

**Comment by nqb** [comment]
I found this: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online

It seems to be specific to Office 365 server but I'm not sure it's a standard.

**Comment by nqb** [comment]
@cgx and @extrafu, in SOGo, do you send a LF or CRLF at end of emails ?

**Comment by F5Brewery** [comment]
I upgraded to 11.3, I noticed that this is still an issue.  Indeed it is connected to O365, but it was a feature disabled for security reasons, could be others will follow suit.  It would seem that all LF need to be changed CRLF.  I would go in and fix this, but I am not sure where or how the message is constructed.

**Comment by nqb** [comment]
@F5Brewery, I create a PR for this issue see #6950

**Comment by F5Brewery** [comment]
Thank you for this.  I tested this fix on my system and it resolved the issue!

Jeremy Yoke

________________________________
