### ISSUE TITLE
MariaDB constraint allow a node to be save in DB with status=reg on failure

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5381]
**Describe the bug**
When you do a 802.1X registration against a connection profile with `autoregister=enabled` using a unknown node (not present in DB) and a *known* pid (present in DB), if authorization step failed, node is saved in DB with `status=reg` because following MariaDB constraint seems to be met:
https://github.com/inverse-inc/packetfence/blob/584a15f0593c755c8020ba9c16f91c50b37ad9ef/db/pf-schema-X.Y.Z.sql#L187

Node is registered without role and RADIUS reply is REJECT.

However, if you run an identical RADIUS request few seconds after, your node is registered without role and RADIUS reply is ACCEPT due to this condition:

https://github.com/inverse-inc/packetfence/blob/584a15f0593c755c8020ba9c16f91c50b37ad9ef/lib/pf/registration.pm#L51

Consequently, it means that even if you failed authorization step two times, your network device received a RADIUS ACCEPT message and can give you access to network.

**To Reproduce**
1. Create a `eapol_test` config to forge EAP-TLS RADIUS request
```
cat > /opt/tls.config << EOF
network={
ssid="CORPORATE SSID"
key_mgmt=WPA-EAP
eap=TLS
identity="inverse"
ca_cert="/usr/local/pf/raddb/certs/ca.pem"
client_cert="/usr/local/pf/raddb/certs/client.pem"
private_key="/usr/local/pf/raddb/certs/client.key"
private_key_passwd="whatever"
eapol_flags=3
}
EOF
```
2. Create a EAPTLS source that will always fail when using client certificate defined at step 1
```ini
[eaptls]
realms=
type=EAPTLS
set_access_durations_action=
description=eaptls

[eaptls rule dont_match]
description=dont_match
class=authentication
action1=set_access_duration=12h
condition0=TLS-Cert-Serial,equals,3
action0=set_role=guest
match=all
```
3. Enable autoregistration and use EAPTLS source on default connection profile:
```ini
[default]
autoregister=enabled
sources=eaptls
```
4. Run a first `eapol_test` that will failed due to unmatched rule on eaptls source:
```
eapol_test -c /opt/tls.config -s testing123 -a MGMT_IP -A 127.0.0.1 -N 61:d:19 -M 10:11:12:13:14:15 -N 4:x:0xc0a80101  -N 5:x:0x00000001
```
=> node 10:11:12:13:14:15 created in DB with `status=unreg`, logs report error on MariaDB constraint

5. Create pid `user@example.org` (PID that will be extracted from client certificate) in DB:
```
pfperl-api get -M POST /api/v1/users -c '{"pid":"user@example.org"}' 
```

6. Run a new `eapol_test` with a new node that will failed due to unmatched rule on eaptls source:
```
eapol_test -c /opt/tls.config -s testing123 -a 172.17.17.12 -A 127.0.0.1 -N 61:d:19 -M 20:21:22:23:24:25 -N 4:x:0xc0a80101  -N 5:x:0x00000001
```
=> node 20:21:22:23:24:25 created in DB with `status=reg` and `pid=user@example.org`, logs doesn't report error on MariaDB constraint.

7. Run same `eapol_test` as previous step

=> node 20:21:22:23:24:25 updated in DB with a valid `regdate`, RADIUS reply is ACCEPT

**Expected behavior**
Step 6 should not save node with `status=reg` in DB if PID exists in DB.

**Additional context**
At the same time, it would be nice to improve error log when MariaDB constraint failed (see https://github.com/inverse-inc/packetfence/issues/5202)

**Comment by fdurand** [comment]
What we can do here https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/role.pm#L637

```
        if (($args->{'connection_type'} & $EAP) == $EAP ) {
            if ( isenabled($profile->dot1xRecomputeRoleFromPortal) ) {
                if (!(exists($node_info{'category'})) || $node_info{'category'} eq '') {
                    $logger->info("No rules matches or no category defined for the node, set it as unreg." );
                    $node_info{'status'} = 'unreg';
                }
            }
        }
```
it prevent the case if there is no role in the db (or the node doesn't exist) , we autoreg but the source return nothing and the category is not defined then keep it as unreg

**Comment by jrouzierinverse** [comment]
If you enable dot1xRecomputeRoleFromPortal on the profile this should not happen.

**Comment by jrouzierinverse** [comment]
The question is this the approach we want to go with?

**Comment by jrouzierinverse** [comment]
Are there other scenarios other than EAP where we would want this behavior?

**Comment by nqb** [comment]
@jrouzierinverse, just to understand, why behavior is different if a `pid` already exists in DB ?

I'm sorry but `dot1xRecomputeRoleFromPortal` setting doesn't make sense for me when you're doing 802.1X with autoregistration (no portal)

**Comment by fdurand** [comment]
dot1xRecomputeRoleFromPortal mean that use the source to try to compute a role (if enabled) or use the role that is already defined in the db (if disabled).
So what happen is dot1xRecomputeRoleFromPortal is enabled , so packetfence try to compute a role fom the source but no role is returned. So with the code we keep the device unreg if it's the case.

**Comment by nqb** [comment]
@jrouzierinverse,  @fdurand, how do you want to solve that issue ?

**Comment by jrouzierinverse** [comment]
@julsemaan @fdurand When reviewing this issue.
I noticed in ```pf::radius::authorize``` the user is not created when autoreg is not set.
Is this a desired behavior in the workflow or is this a bug?

**Comment by julsemaan** [comment]
I think that's intended behavior since the user is not registering during that request

**Comment by nqb** [comment]
Solution:
- @fdurand will provide code to reject a node when there is no role in DB and you don't match any authentication rules in sources (with `autoregister=enabled`)
- We should have a specific message when we meet this condition 
- We should provide:
  * a default VLAN filter disabled by default to keep old behavior
  * an upgrade note
