### ISSUE TITLE
configurator: MariaDB doesn't use timezone setting until reboot

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5390]
**Describe the bug**
When you set a timezone in configurator, MariaDB is not configured with that timezone until you reboot.

Consequently, admin user created in DB is created with a `valid_from` value based on **default** timezone. Depending on your timezone, it means that your account could be not valid after you reboot.

**To Reproduce**
1. Install a PacketFence ZEN
2. Set timezone to EST at step 2 of configurator
3. Set admin password
4. Check value in DB:
```sql
SELECT valid_from FROM password where pid='admin'\G;
```
5. Finish configurator
6. Log in on web admin with `admin` user

=> It works.

7. Reboot
8. Log in on web admin with `admin` user

=> It fails because account is not yet valid.

**Expected behavior**
MariaDB should be configured using timezone defined at step 2.

**Comment by julsemaan** [comment]
The fix will more likely need to come from @cgx where he can perform a restart of the packetfence-mariadb service after setting the timezone

**Comment by nqb** [comment]
Hello @julsemaan, it seems possible to do it during `mysqld_safe` execution.

https://mariadb.com/kb/en/time-zones/#system-time-zone

**Comment by julsemaan** [comment]
The instructions on changing it during runtime:
https://mariadb.com/kb/en/time-zones/#global-server-time-zone

**Comment by julsemaan** [comment]
The admin password needs to be set after the timezone is set and the service is restarted so that @nqb's bug is fixed

Currently that isn't the case:
```
May  1 09:04:25 localhost pfhttpd: api-frontend-access 127.0.0.1 - - [01/May/2020:09:04:25 -0400] "PATCH /api/v1/configurator/user/admin/password HTTP/1.1" 200 42 "https://172.20.155.47:1443/admin/alt" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
May  1 09:04:26 localhost pfhttpd: api-frontend-access 127.0.0.1 - - [01/May/2020:09:04:26 -0400] "PATCH /api/v1/configurator/config/base/alerting HTTP/1.1" 200 43 "https://172.20.155.47:1443/admin/alt" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
May  1 09:04:26 localhost pfhttpd: api-frontend-access 127.0.0.1 - - [01/May/2020:09:04:26 -0400] "PATCH /api/v1/configurator/config/base/general HTTP/1.1" 200 43 "https://172.20.155.47:1443/admin/alt" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
May  1 09:04:30 localhost pfhttpd: api-frontend-access 127.0.0.1 - - [01/May/2020:09:04:30 -0400] "POST /api/v1/configurator/system_service/packetfence-mariadb/restart HTTP/1.1" 200 53 "https://172.20.155.47:1443/admin/alt" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
```

Which means the password is created with a valid_from that doesn't reflect the selected timezone

**Comment by julsemaan** [comment]
Just tested this and it also needs to happen prior to the schema being loaded

**Comment by cgx** [comment]
> Just tested this and it also needs to happen prior to the schema being loaded

You mean before the database is created? What happen if the database exists and the user changes the timezone? This scenario can also happen if automatic database configuration is *disabled*.

**Comment by julsemaan** [comment]
True, in that case we could PATCH the admin password entry after changing the timezone + restarting packetfence-mariadb to set valid_from to the current date.

This could be done right after the restart of packetfence-mariadb and at the same time as setting the admin password and would ensure the entry would be valid and doesn't require an additionnal API call, just an additional parameter to the call that is already being made

**Comment by cgx** [comment]
Would it make sense to unconditionally set the `valid_from` date to the current date, no matter if we are updating or creating the admin user and regardless of a timezone change?

**Comment by julsemaan** [comment]
@cgx, yes that's right, my comment was very unclear but the same recipe should be used whether or not we change the timezone, that way its consistent during the install

**Comment by julsemaan** [comment]
I cherry-picked the 3 commits that are listed here (b7f7967, 2ae8ef5, 5fed3bf). All 3 have picked cleanly.

@cgx, let me know if other commits need to be cherry-picked in the maintenance for this issue.
