### ISSUE TITLE
tests: missing dependencies for freeradius-ldap

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5394]
**Describe the bug**
Tests are not run in pipeline for CentOS because `freeradius-ldap` has a missing dependency in devel `openldap-ltb`.

**Comment by nqb** [comment]
@fdurand, do you plan to fix this ASAP or should we edit RPM spec file to only use 3.0.18 version of FreeRADIUS ?

**Comment by fdurand** [comment]
it should be ok

**Comment by nqb** [comment]
Still an issue with `openldap-ltb` dependencies now: https://gitlab.com/inverse-inc/packetfence/-/jobs/530949319#L315

**Comment by nqb** [comment]
Signing issue of RPM now: https://gitlab.com/inverse-inc/packetfence/-/jobs/532711505#L310

**Comment by nqb** [comment]
Fixaid
