### ISSUE TITLE
Improve ldap authentication rules

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5397]
**We have sometimes some complex conditions for an authentication rule, like:**

> ($(|(cn=$username)(samaccountname=$radius.username))(|(memberof=student)(memberof=staff)))

and it's not possible to do it right now.

We should have something like a filter engine that generate the ldap filter (in a perfect world) and have condition in the authentication rule (like advanced ldap filter) where we can select the filter we created in the filter engine.

Or have a text area where we can fill the request like the rule above.

**Comment by jrouzierinverse** [comment]
I am going to split this into two different PR (I will split this issue also).
1) not_found_set_role.
2) Advanced LDAP query.
