### ISSUE TITLE
Security events Fingerbank NBA triggers don't show the specified policy

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5402]
**Describe the bug**
When you set a specific policy on a Fingerbank NBA based trigger in the security events, it doesn't show the policy in the display of the trigger so you have to click the details to see if it applies to all or a specific policy

**To Reproduce**
1. Edit security event 1300008
2. Edit one of the triggers and specify a policy
3. Doesn't display that the trigger is for a specific policy
4. Save and refresh
5. Still doesn't display the trigger is for a specific policy

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/80803110-4bf9f000-8b7f-11ea-9327-2095f505f5ca.png)

**Expected behavior**
The trigger should display that its for a specific policy even when not viewing the details of the trigger

**Comment by cgx** [comment]
How should the description be formatted? It would be nice to first translate the internal event name. Shall we remove the "internal:" prefix?

  `internal: <event> (<policy>)`

or

 `<event> (<policy>`

or something else?
