### ISSUE TITLE
radsniff3 refusing to start without host entry

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#541]
Either we find a way to have it computed dynamically or packaging should add an entry in /etc/hosts

For now stock PF refuses to fully start without a manual intervention and thus breaks the configurator

**Comment by jrouzierinverse** [comment]
Why not just use localhost?

**Comment by julsemaan** [comment]
If it works with radsniff3, sure

**Comment by julsemaan** [comment]
1fae6ff640e345d0a2c4dec1afc5d862e1683816 brings a solution that should be reworked if possible

**Comment by fdurand** [comment]
Changed the code of collectd.c (freeradius 3) to avoid this error.
