### ISSUE TITLE
When loading a big switch configuration got the following error

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#542]
DBD::mysql::db do failed: Got a packet bigger than 'max_allowed_packet' bytes at /usr/local/pf/lib/pfconfig/backend/mysql.pm line 90.

**Comment by jrouzierinverse** [comment]
This should be added to the best practices guide for mysql

**Comment by julsemaan** [comment]
Indeed, and this also brings the question on whether or not PacketFence should manage the MySQL configuration since it now needs additionnal parameters for it to work properly

**Comment by dwlfrth** [comment]
@jrouzierinverse document big thing

**Comment by julsemaan** [comment]
We manage the MySQL configuration now and push the parameter by default so its fixed
