### ISSUE TITLE
web admin: add a button to copy to clipboard notifications

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5425]
**Is your feature request related to a problem? Please describe.**
When you have notifications on PacketFence, you can click on bell to display them. However, it's not easy to copy text displayed. 

**Describe the solution you'd like**
Would be nice to have a "Copy to clipboard" button to easily copy text.

**Describe alternatives you've considered**
Simplify selection of text of notifications

**Comment by satkunas** [comment]
You can now click on the notification item in the list. This will silently copy the url and the message to the clipboard.
