### ISSUE TITLE
Admin doesn't listen on server IP anymore in a cluster

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5427]
**Describe the bug**
When you are in a cluster, the admin only listens on the virtual IP. It makes it impossible to access a specific server without going through the VIP which is especially useful when doing an upgrade

**Comment by fdurand** [comment]
Already in devel, i will put in maintenance.

**Comment by julsemaan** [comment]
Added 8680cc2a2c71ff1b850105f6ddd12084109f975c and f93cccc413a06ac76507f41bcb6323d73a5f3cde in the maintenance
