### ISSUE TITLE
Mandatory value for not_defined operator

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5431]
**Describe the bug**
I'm forced to select a value for the not_defined operator in the VLAN filters although this operator shouldn't have any value

**To Reproduce**
1. Create the following filter:
![image](https://user-images.githubusercontent.com/3857942/81571048-6d24c280-936f-11ea-83c0-96522f2103c1.png)

**Comment by satkunas** [comment]
@jrouzierinverse The date operators don't require a field, so to handle these cases the operator will have to be chosen first. Thus, the user will only be presented with the choice to choose an operator (while field and value are locked or hidden). This seems non-intuitive for the user having to choose an operator, without the ability to choose a field first.

![Screenshot_20200514_112544](https://user-images.githubusercontent.com/3904468/81953440-a9595c80-95d5-11ea-8cdc-fc7f64cd7f4e.png)

**Comment by jrouzierinverse** [comment]
I will require a field for (not_|)time_period then.

**Comment by satkunas** [comment]
If we decide to leave the field open, I can simply omit locking/hiding the field in all cases, and only handle the value.

**Comment by jrouzierinverse** [comment]
Make sense

**Comment by julsemaan** [comment]
Forgot the milestone, this is a +1 patch release, @satkunas, can this go easily in the maintenance ?

**Comment by satkunas** [comment]
@julsemaan should be easy, I'll try to put it in `maintainance/10.0` shortly.

**Comment by satkunas** [comment]
@julsemaan @jrouzierinverse  The meta appears to differ.in `maintenance/10.0` than in `devel`. Some perl will need to be cherry picked as well in order for this to work.

Maint/10.0: 

![Screenshot_20200514_152933](https://user-images.githubusercontent.com/3904468/81977507-21d11500-95f8-11ea-87fc-5e6a91481533.png)


Devel: 

![Screenshot_20200514_153246](https://user-images.githubusercontent.com/3904468/81977530-2a295000-95f8-11ea-8486-7037c6caaee4.png)

**Comment by satkunas** [comment]
Re-opening until `maintenance/10.0` is resolved.

**Comment by jrouzierinverse** [comment]
Fixed by 0dafcdf8183390c6756b023e0c724e58208137e7

**Comment by julsemaan** [comment]
@satkunas, is your commit in maintenance/10.0 too ?

**Comment by satkunas** [comment]
@julsemaan yes it is
