### ISSUE TITLE
key SNMP-isPhoneAtIfIndex could be empty (in place of undef) 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5443]
**Describe the bug**
When auto-register IP phones using `VoIPLLDPDetect` and `VoIPCDPDetect`, I noticed that key `SNMP-isPhoneAtIfIndex` related to MAC address in `switch_distributed` cache can be set to `''` value when IP phone is not detected correctly. 

It means that if detection has failed for the first time, VoIP phone will not be detected again before key expires (48h by default).

**To Reproduce**
1. Configure a switch with `VoIPLLDPDetect` and `VoIPCDPDetect` set to `Y` on PF side + SNMP
3. Trigger a RADIUS request for MAC `11:22:33:44:55:66`
4. Check value of cache entry:
```
# pfcmd cache switch_distributed dump 10.0.0.1-SNMP-isPhoneAtIfIndex-10106-11:22:33:44:55:66
$VAR1 = ''; 
``` 

**Expected behavior**
Cache entry should keep value of `undef` if VoIP detection has failed.

**Workaround**
Remove key from cache using: `pfcmd cache switch_distributed remove KEY_ID`

**Comment by julsemaan** [comment]
This was on purpose. If you don't do that then the cache will never hit for workstations and you end up doing SNMP requests for every RADIUS requests for all workstations

**Comment by nqb** [comment]
Ok @julsemaan, makes sense.

However, when it occurs, I remembered we had an option in old GUI to invalidate this cache but it seems missing in new GUI. [API call](https://github.com/inverse-inc/packetfence/blob/9ca933aaadb92acc895d27935aa663db616a7561/lib/pf/UnifiedApi/Controller/Config/Switches.pm#L34) seems present.

@cgx, @satkunas any idea why this button is missing ?
