### ISSUE TITLE
web admin: frontend only display built-in roles on a switch group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5445]
**Describe the bug**
When you go in `Roles` tab on a switch group, only built-in roles are displayed (registration, isolation, macDetection, inline) . Even if you toggle `Advanced` button. 

API correctly returns roles.

**To Reproduce**
1. Create a new role `myrole`
2. Display roles on `default` switch group

=> `myrole` is missing

**Expected behavior**
Like on a switch, Roles tab should display all roles available.

**Workaround**
Edit `switches.conf` by hand.

**Comment by nqb** [comment]
I got same issu when I try to display roles for a switch.

**Comment by nqb** [comment]
@satkunas

**Comment by satkunas** [comment]
@nqb please add additional information to reproduce the issue if it is still present. I closed the issue because AFAIK it is fixed.
