### ISSUE TITLE
pf-maint.pl doesn't ignore ci/ directory

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5446]
**Describe the bug**
Causes pf-maint.pl to pull and attempt to apply files in the ci/ directory which doesn't exist when installing from the RPM

**Comment by nqb** [comment]
I pushed a [fix](https://github.com/inverse-inc/packetfence/commit/8b3a63719ab5aee84c01f0ec5fbb8739f59780e4) to devel but missed maintenance. I will backport to maintenance.
