### ISSUE TITLE
SAML authentication with GoogleSuite didn't work

### ISSUE THREAD

**Issue by acc4all** [inverse-inc/packetfence#5449]
**Describe the bug**
Hi, I got this error when setup SAML Authentication with GoogleSuite  
###  ### _"ERROR: [mac:e4:b9:7a:6e:a0:99] Caught exception in captiveportal::Controller::Root->dynamic_application "Can't use string ("Can't call method "Attribute" on"...) as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/Authentication/Source/SAMLSource.pm line 197." (captiveportal::PacketFence::Controller::Root::end)"_

**To Reproduce**
1. Setup LAB following "Adding VLAN Enforcement to Existing
Installation" of Installation Guide v10
2. Setup SAML following "SAML Authentication" of Installation Guide v10
3. Enable ip2mac_lookup
 [pfdhcp]
ip2mac_lookup=enabled 

**Screenshots**
https://drive.google.com/drive/folders/1DmnfXNMFcbVLkE4RsZe8CN3yKIcJAFCc?usp=sharing

- PacketFence - Configuration.rtf => capture SAML configuration
- Login Steps.rtf => capture login steps and final error.
- packetfence.log => /usr/local/pf/logs/packetfence.log

**Expected behavior**
User devices can be authenticated with GoogleSuite, then the Cisco 2960G Switch will change port-vlan to 104.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : MS Edge, Firefox 76.0.1, Chrome 81.0.4044.138
 - Packetfence v10.0.1

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
