### ISSUE TITLE
PF 10.0.1 Cannot disable Galera-Autofix

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5451]
I'm using external Database galera cluster and don't need galera-autofix.
I disabled in GUI services and done systemctl stop|disable packetfence-galera-autofix,
but every service pf restart symlink is created and galera auto-fix is started again.

**Comment by julsemaan** [comment]
Should be fixed in the maintenance now, you can apply it using:
```
/usr/local/pf/addons/pf-maint.pl
/usr/local/pf/bin/pfcmd service pf restart
```
