### ISSUE TITLE
Add function to replace character in template switches

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5455]
**Is your feature request related to a problem? Please describe.**
Right now there is no function to replace a character with another one in the template switches (at least in the doc). It would be nice to have this.

**Describe the solution you'd like**
A function that replaces a character with another

**Describe alternatives you've considered**
We can use `${join('-', split(':', $mac))}` to do the same thing but it would be cleaner to have a replace

**Comment by jrouzierinverse** [comment]
Something like ```replace($str, $old, $new)```

**Comment by julsemaan** [comment]
Yes exactly
