### ISSUE TITLE
Connection profile sorting issue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5458]
The order in the admin gui is not the same that we have in the configuration file.

On reordering a javascript error appear:

![image](https://user-images.githubusercontent.com/1553962/82474123-955fa000-9a98-11ea-89ca-e41224b57f39.png)

**Comment by fdurand** [comment]
Fixed by https://github.com/inverse-inc/packetfence/commit/9bdd17a619e9cb679770035673c4eb884e7624a0 and https://github.com/inverse-inc/packetfence/commit/3dcea494a01b0a29ef759ea055e48eec9a9012c1

**Comment by julsemaan** [comment]
Should this go in the maintenance ?

**Comment by satkunas** [comment]
@julsemaan I'll check to see which maint branches this can be merged with.

**Comment by satkunas** [comment]
Was already in `10`. Added to `9.3`, `9.2` and `9.1`.
