### ISSUE TITLE
PF10 GUI shows only 25 routed networks

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5461]
GUI is showing only first 25 routed networks at administration > network configuration > interfaces

**Comment by julsemaan** [comment]
@satkunas, can you take a look into this. Pretty sure this is a 2 minutes fix

**Comment by satkunas** [comment]
The API does not respect the `?limit=x` query variable and appears to be statically limiting the response. Re-assigning.

@jrouzierinverse let me know if you chose to consume the `limit` query var and I'll include it with the requests from the front-end.

**Comment by jrouzierinverse** [comment]
Which route are you consuming?

**Comment by satkunas** [comment]
GET /config/interfaces?limit=26

**Comment by jrouzierinverse** [comment]
Limit is not supported for interfaces so we should be displaying all of them.
and in my quick test none are being cutoff.
```
./sbin/pfperl-api get /api/v1/config/interfaces | jq -r .items[].id | sort | wc -l
31
```

**Comment by jrouzierinverse** [comment]
I created a bunch of dummy interfaces to test
```
for i in $(seq 0 25);do ip link add "dummy$i" type dummy;done
```

**Comment by olmanolsztyn** [comment]
When i request directly to api (/config/interfaces) i got response with all routed networks but not in GUI.

**Comment by julsemaan** [comment]
The routed networks are not in /api/v1/config/interfaces, they're in /api/v1/config/routed_networks

**Comment by olmanolsztyn** [comment]
Sorry my bad. request /api/v1/config/routed_networks returned the same result as GUI.

**Comment by jrouzierinverse** [comment]
Darren can you look at increasing the limit or check the pagination for /api/v1/config/routed_networks

**Comment by olmanolsztyn** [comment]
25 result per page would be good solution.
