### ISSUE TITLE
web admin: only default roles are available when configuring a scan engine

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5470]
**Describe the bug**
When you configure a scan engine, only default roles are available.

**To Reproduce**
1. Create a new role
1. Create a new scan engine
2. Try to select your new role

=> Role is missing.

**Expected behavior**
Should be able to select all roles available.

**Additional context**
I didn't see any API calls to get list of roles when I create a new scan engine

**Comment by satkunas** [comment]
Unable to reproduce. A (cold or warm) reload of the page produces all custom roles:

![Screenshot_20200525_112624](https://user-images.githubusercontent.com/3904468/82826195-a6cef080-9e7a-11ea-8597-9bc043939fa9.png)

**Comment by julsemaan** [comment]
@satkunas 

Would there be a way to expire the roles cache in the admin when a user creates a role ?

Not talking about multi-page or multi-user context, just on a single page, you create a role and it expires the cache

**Comment by nqb** [comment]
Issue was on my side. Sorry.

**Comment by satkunas** [comment]
> Would there be a way to expire the roles cache in the admin when a user creates a role ?

@julsemaan Yes, this is already the case for some sections. It's not difficult to implement.

**Comment by julsemaan** [comment]
> > Would there be a way to expire the roles cache in the admin when a user creates a role ?
> 
> @julsemaan Yes, this is already the case for some sections. It's not difficult to implement.

I understand but from a user perspective it will seem like a bug. I get the comment in the majority of my deployments. Its not a big issue but its an "issue" that comes over and over. Perhaps we could refresh the page when a role is created. That could be a workaround.
