### ISSUE TITLE
web admin: not able to scroll in some menus

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5472]
**Describe the bug**
In several menus, I noticed that I'm not able to scroll correctly like before. Issue seems to be random.

**To Reproduce**
1. Go in RADIUS audit logs
2. Enable your web browser console and place it at bottom of your web page
3. Try to scroll

=> You can't.

**Screenshots**
When I got the issue, it seems that there is a useless block:
![Capture d’écran de 2020-05-26 09-44-42](https://user-images.githubusercontent.com/10830260/82881559-21ae0f00-9f40-11ea-98a5-808ce8b6b555.png)

**Expected behavior**
Be able to scroll correctly.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser: Firefox
 - Version: 68.7.0esr (64 bits)

**Additional context**
I assigned @cgx because I assumed it's related to 11ce462ffb245fa41692ef163514eda8e556b87a

**Comment by nqb** [comment]
@cgx, are you able to reproduce this issue ? Still presents on my side.

**Comment by lzammit** [comment]
Hmm. I got the same thing and I was thinking that was my shitty browser. If I refresh the web page it works again. It's random as well.

**Comment by julsemaan** [comment]
> Hmm. I got the same thing and I was thinking that was my shitty browser. If I refresh the web page it works again. It's random as well.

The browser that takes 19GB of RAM to open a dozen of tabs right ?

**Comment by nqb** [comment]
I still have this issue on latest build, running on Debian when I go in Auditing menu.

**Comment by cgx** [comment]
I can't reproduce the issue anymore on my side.

**Comment by nqb** [comment]
Not able to reproduce on Chrome but I got issue on Firefox 68.7.0esr

**Comment by cgx** [comment]
I've pushed another fix. If you still have the issue @nqb , try to describe how to reproduce it. Thanks!

**Comment by nqb** [comment]
Thanks @cgx, no more issues on my side on Firefox.
