### ISSUE TITLE
Ergonomy problem at services page in configurator

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#548]
We have so much services now that on screens with normal resolutions, we need to scroll down to start PacketFence.

We should bring the button at the top or place it at another place

**Comment by cgx** [comment]
We could easily display the services on multiple columns (at least 2).

We could also group similar services together.

**Comment by jrouzierinverse** [comment]
I would have the start/stop/restart pf button on the top and bottom.
So if are you scrolling down you do not have to scroll back up

**Comment by julsemaan** [comment]
I'd go with James idea IMO, putting them on 2 columns would be obsolete whenever we decide to add even more services.

**Comment by cgx** [comment]
@julsemaan Obsolete? Why? I was thinking about using a [grid](http://getbootstrap.com/css/#grid) inside a fluid container. We could even have more columns on very large screens. And the colums would simply stack on smaller devices.

**Comment by julsemaan** [comment]
@cgx @zammitbug True, still not sure about the looks of it but I'll give it a try

**Comment by jrouzierinverse** [comment]
The start/stop/restart buttons are now on top.
Let create a separate issue for group and multiples columns so we can have it for 5.2.0

**Comment by jrouzierinverse** [comment]
Fixed in commit #ab5b7c75b7fc28dc71063b9495940b6d91ff8774
