### ISSUE TITLE
Switchs become completely independent if you redefine one setting of switch group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5482]
**Describe the bug**
If you change one setting on a switch, part of a switch group, your switch become completely independent regarding all other settings defined in switch group.

**To Reproduce**
1. Create a switch group with a specific config (settings different than defaults) and a switch attached to this switch group:
```
pfperl-api get -M POST /api/v1/config/switch_groups -c '{"id":"bar","description":"bar","voiceVlan": "500","voiceRole": "voix"}' | python -m json.tool
pfperl-api get -M POST /api/v1/config/switches -c '{"id":"10.1.1.1","group":"bar","description":"bar1"}' | python -m json.tool
``` 
Resulting config:
```ini
[group bar]
voiceRole=voix
uplink_dynamic=0
description=bar
voiceVlan=500

[10.1.1.1]
group=bar
uplink_dynamic=0
description=bar1
```
1. Change a setting defined in switch group on **switch** (not switch group):
```
pfperl-api get -M PATCH /api/v1/config/switch/10.1.1.1 -c '{"id":"10.1.1.1","voiceVlan":"501"}' | python -m json.tool
```
Resulting config:
```ini
[10.1.1.1]
group=bar
description=bar1
voiceRole=voix
voiceVlan=501
``` 

=> Now, it means that switch is completely independent from switch group for all settings different than defaults redefined in switch group (example: `voiceRole`) even if we never modified this element on switch.

Example:
```
pfperl-api get -M PATCH /api/v1/config/switch_group/bar -c '{"id":"bar","voiceRole":"zammit"}' | python -m json.tool
```
Resulting config:
```ini
[10.1.1.1]
group=bar
description=bar1
voiceRole=voix
voiceVlan=501

[group bar]
voiceRole=zammit
description=bar
voiceVlan=50
always_trigger=1
```
We can see that `voiceRole` is still defined to `voix` on switch.

**Expected behavior**
Switch should only inherit change on `voiceVlan`, not on `voiceRole`.

**Comment by nqb** [comment]
I got another unexpected behavior when I change switch group of a switch. Not sure it's related to this issue. If that's not the cas, I will open a separate issue.

Steps to reproduce:
```
# create two switch groups
pfperl-api get -M POST /api/v1/config/switch_groups -c '{"id":"swg1","description":"bar","voiceVlan": "1","voiceRole": "voix1"}' | python -m json.tool
pfperl-api get -M POST /api/v1/config/switch_groups -c '{"id":"swg2","description":"bar","voiceVlan": "2","voiceRole": "voix2"}' | python -m json.tool

# create a switch part of swg1 group
pfperl-api get -M POST /api/v1/config/switches -c '{"id":"10.0.0.1","group":"swg1","description":"10.0.0.1"}' | python -m json.tool
```

Resulting config
```ini
[10.0.0.1]
group=swg1
uplink_dynamic=0
description=10.0.0.1

[group swg1]
voiceRole=voix1
uplink_dynamic=0
description=bar
voiceVlan=1

[group swg2]
voiceRole=voix2
uplink_dynamic=0
description=bar
voiceVlan=2
```
```
# change group of switch to swg2
pfperl-api get -M PATCH /api/v1/config/switch/10.0.0.1 -c '{"id":"10.0.0.1","group":"swg2"}' | python -m json.tool
```

Resulting config
```ini
[10.0.0.1]
group=swg2
description=10.0.0.1
voiceRole=voix1
voiceVlan=1
```
=> switch is now member of swg2 but with values from swg1

**Comment by julsemaan** [comment]
@jrouzierinverse, in the initial implementation of the switch groups in the configstore, that was working. I think we must have regressed when we brought the API in and you had to rework the switch group configstore

**Comment by julsemaan** [comment]
Maintenance seems to be missing

**Comment by nqb** [comment]
I applied maintenance on my customer setup.

My switch still becomes independent if I changed its description.

Steps to reproduce:
1. Create a switch part of a switch group
1. Change switch description
1. Check `switches.conf`

Your switch is now independent from switch group. If you modified a setting in switch group, you didn't got this change on switch.
