### ISSUE TITLE
Not able to save Access Level for a user

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5483]
![image](https://user-images.githubusercontent.com/1553962/83181564-13542480-a0f3-11ea-9968-3e784ad859e3.png)

Try to save, then in the logs:

```
mai 28 14:54:49 packetfence1 packetfence[28580]: ERROR pfperl-api(28580): Database query failed with non retryable error: called with 13 bind variables when 12 are needed (errno: -1) [UPDATE `password` SET `access_duration` = ?, `access_level` = User Manager, `category` = ?, `expiration` = ?, `login_remaining` = ?, `pid` = ?, `sponsor` = ?, `tenant_id` = ?, `unregdate` = ?, `valid_from` = ? WHERE ( ( `password`.`tenant_id` = ? AND `pid` = ? ) ) LIMIT ?]{NULL, Node Manager, NULL, 2025-01-18 00:00:00, NULL, byod_help, admin, 1, NULL, 2018-12-14 00:00:00, 1, bobey, 1} (pf::dal::db_execute)
```

**Comment by fdurand** [comment]
|         1 | byod_helpo | {bcrypt}$2a$08$pUyw9Fp4KVUr6XTuIGy.i.C0Y2XNfKAdiomCKysxcNc0YPsfeIFvW | 2020-05-28 00:00:00 | 2020-05-30 12:00:00 | NULL            | ARRAY(0x107c38c8) |     NULL |       0 | 0000-00-00 00:00:00 |            NULL |

**Comment by julsemaan** [comment]
@jrouzierinverse, make sure these go in the maintenance/10.0 if needed

**Comment by olmanolsztyn** [comment]
Access level is saving but is not displaying after reload page.
