### ISSUE TITLE
PF10.0.1 ZEN Error while setting locale

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5485]
When connection profile is set to language different than en_US i got those messages:
`Error while setting locale to pl_PL.utf8. Is the locale generated on your system? (captiveportal::PacketFence::Controller::Root::setupLanguage)`
Translations doesnt work on captive portals.

**Comment by olmanolsztyn** [comment]
locale -a shows only en_* locales
Solved issue reinstalling glibc-common.
`sudo yum reinstall -y glibc-common --enablerepo=packetfence`

**Comment by olmanolsztyn** [comment]
locale -a shows only en_* locales
Solved issue reinstalling glibc-common.
`sudo yum reinstall -y glibc-common --enablerepo=packetfence`

**Comment by julsemaan** [comment]
@nqb, what should we do about this ?

**Comment by nqb** [comment]
Hello @julsemaan, we can certainly installed all locales in the ZEN image to avoid these issues.

I will check now if can provide a fix.
