### ISSUE TITLE
Order of the servers in the cluster services isn't right.

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5487]
**Describe the bug**
Order of the servers in the cluster services isn't right.

As seen in the screenshot below, the order of the servers isn't right (should follow the same order as in cluster.conf)

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/83256025-a8046400-a17f-11ea-8e3b-9d0eb4e9e83b.png)

**Comment by satkunas** [comment]
@julsemaan please send me (email) the full API output for the cluster endpoint in this example. With this I'll be able to replicate the issue.

**Comment by julsemaan** [comment]
sent via DM
