### ISSUE TITLE
Review categorisation of admin config menu

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#549]
ex : Right now Provisioners are placed under 'Users'

We should create an 'Authentication' section that contains 'Portal profiles', 'Admin access' and other related sections.

Suggestions are welcome, but we need to rework those sections

**Comment by jrouzierinverse** [comment]
From @extrafu in an email

Main
    - ...
    - Self Registration
    - Billing
    - ...
    - Captive portal
    - Portal Profiles
Users
    - ..
    - Provisioners
    - ..

Je suggere pour 5.1 de regrouper les éléments relatifs au portail captif dans une section "Portal"

Portal
    - Detection and Redirect (était "Captive portal")
    - Billing
    - Profiles
    - Provisioners
    - Self Registration

**Comment by julsemaan** [comment]
As defined in the v7 tasks, this will be @extrafu and @whitx job

**Comment by julsemaan** [comment]
Done via PR #2108
