### ISSUE TITLE
RFC: use "PacketFence::Standard" in place of "Generic" for default Switch Group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5490]
**Describe the bug**
Currently, default switch group still use `Generic` as default switch (old switch module). We should move to `PacketFence::Standard` (template module). That's way, all new switches created from default switch group will use `PacketFence::Standard` (template module).

Is there is some limitations ?

I saw two functions in `Generic.pm` related to CLI access to switches (https://github.com/inverse-inc/packetfence/blob/5ba7bf9d8863837d8c81013bf443237fd8691a70/lib/pf/Switch/Generic.pm) and I wonder if we can handle those things in `PacketFence::Standard`.

From my point of view, that's the case.

**Comment by jrouzierinverse** [comment]
Let's move this to 10.2

**Comment by nqb** [comment]
I can confirm that using the PacketFence::Standard switch template module will not work when you use CLI login.

Another different behavior between Generic module and PacketFence::Standard switch template module is that the first will always use SNMP to deauthenticate when the second will try to use RADIUS Disconnect.
