### ISSUE TITLE
API: a role is not mandatory to create a node in web admin 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5491]
**Describe the bug**
When you create a node in web admin, a role is not mandatory. 

**To Reproduce**
1. Create a node in web admin

=> node is created without role.

**Expected behavior**
Role is mandatory to avoid unexpected behavior.

**Comment by extrafu** [comment]
@jrouzierinverse Make the backend use the default role when that happens.

**Comment by jrouzierinverse** [comment]
Fixed by d799e822808faa392d3b4f2ca2dbf79eb9ae8cd7
