### ISSUE TITLE
Fingerbank api connection issue (certificate verify failed)

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5494]
I faced fingerbank api connection. It seems to be a certificate problem.
I don use proxy. Logs i see below:
`
Error while communicating with the Fingerbank API to check if device 7406 is linked to device 81. 500 Can't connect to api.fingerbank.org:443 (certificate verify failed) (fingerbank::Model::Device::__ANON__)`

**Comment by olmanolsztyn** [comment]
I have 8.1.0 version too where in Configuration > Compliance > General settings is:
`Impossible to fetch Fingerbank account information: Can't connect to api.fingerbank.org:443 (certificate verify failed) SSL connect attempt failed error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed at /usr/share/perl5/vendor_perl/LWP/Protocol/http.pm line 41. `

**Comment by julsemaan** [comment]
Can you try again, this has been adjusted in the last minutes

**Comment by olmanolsztyn** [comment]
Seems to work now. Thank You
