### ISSUE TITLE
Regex condition is escaped in the configuration

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5502]
**Describe the bug**
If you create a radius filter and do a condition with a regex then the regex is escaped in the radius_filters.conf file.

Let's say you define a condition that in the admin gui:

switch._ip =~ "^(172\.24\.237\.112|172\.24\.237\.114|172\.24\.237\.128)$"

Then it will appear like that in the configuration file:

condition=switch._ip =~ "^(172\\.24\\.237\\.112|172\\.24\\.237\\.114|172\\.24\\.237\\.128)$"

We should store it as is.

**Comment by jrouzierinverse** [comment]
Is this happening in devel or in 10.1.x?

**Comment by fdurand** [comment]
devel

**Comment by jrouzierinverse** [comment]
I am unable to replicate. 
``` switch._ip =~ "^(172.24.237.112|172.24.237.114|172.24.237.128)$" ```

Can you provide me the steps to replicate?

**Comment by fdurand** [comment]
ah ah, edit the issue , it looks like github unescape the text ....

**Comment by jrouzierinverse** [comment]
That is how it is saved.
```\"``` are escaped since it is in a string.

The regex itself works fine when being used.
