### ISSUE TITLE
Fingerbank collector 401 Unauthorized

### ISSUE THREAD

**Issue by Ieno77** [inverse-inc/packetfence#5510]
**Describe the bug**
If you put the Fingerbank key after going through the configurator, it seems that packetfence act like the key is not here. A lot of message in packetfence.log 

**To Reproduce**
1. On a fresh PacketFence installation while in the configurator, don't put your Fingerbank key
2. Add your key after going through the configurator

**Screenshots**
![fingerbank](https://user-images.githubusercontent.com/56310726/83573017-ac6eab00-a4f8-11ea-89c9-268cad0f8fe3.png)

**Expected behavior**
Fingerbank collector should not get an error 401 Unauthorized

**Desktop (please complete the following information):**
 - OS: Centos 7.8
 - Version: packetfence-10.0.9-20200602192132.152127593.0007.devel.el7.x86_64

**Comment by julsemaan** [comment]
You need to restart the Fingerbank collector after installing your key. We should make this more explicit in the Fingerbank configuration section

**Comment by julsemaan** [comment]
I checked and the field states to restart the fingerbank-collector.

@Ieno77, can you confirm if you restarted the service after configuring the key

**Comment by Ieno77** [comment]
Yes, its good after restarting pf-config and cleared fingerbank cache

**Comment by julsemaan** [comment]
After checking with @Ieno77 the time on the server was wrong which causes issues with pfconfig + the fingerbank config cache
