### ISSUE TITLE
Have the interface and each network type on it's own tab

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#5518]

**Comment by julsemaan** [comment]
IMO that isn't really necessary.

I think we should get some feedback from some other members of the team before doing this change.

**Comment by satkunas** [comment]
A split view would regress the network highlighting (see blue highlights).

![Screenshot_20200604_120130](https://user-images.githubusercontent.com/3904468/83780541-4c444a00-a65b-11ea-94ce-fdd91435f2cd.png)
