### ISSUE TITLE
ZEN OVA import fails

### ISSUE THREAD

**Issue by IncompleteString** [inverse-inc/packetfence#5522]
**Describe the bug**
When attempting to import the ZEN .ova file to VMware vSphere the import fails with the following errors.

`Issues detected with selected template. Details: - 48:7:VALUE_ILLEGAL: Value ''PIIX4'' of ResourceSubType element not found in []. - 57:7:VALUE_ILLEGAL: Value ''PIIX4'' of ResourceSubType element not found in [].`

**To Reproduce**
1. Click on deploy OVA template
2. Select the OVA template
3. Name the virtual machine and hit next

**Screenshots**

<img width="862" alt="Screen Shot 2020-06-03 at 4 49 13 PM" src="https://user-images.githubusercontent.com/17124269/83713520-9bd33900-a5bb-11ea-9b1d-776dc55adfb2.png">

vSphere version: 6.7.0
vSphere build: 14792544 

I tried just editing the ova file and changing the IDE controllers to SCSI but could not get that to work.

**Comment by IncompleteString** [comment]
I extracted the OVA file and edited the OVF and MF files. There is no need for those PIIX4 based IDE controllers as there is only 1 virtual hard drive that's attached to an SCSI controller.

Updated files follow

PacketFence-ZEN-v10.0.1.ovf
`<?xml version="1.0" encoding="UTF-8"?>
<Envelope ovf:version="1.0" xml:lang="en-US" xmlns="http://schemas.dmtf.org/ovf/envelope/1" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vbox="http://www.virtualbox.org/ovf/machine" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <References>
    <File ovf:href="PacketFence-ZEN-v10.0.1-disk1.vmdk" ovf:id="file1" ovf:size="1902492160"/>
  </References>
  <DiskSection>
    <Info>List of the virtual disks used in the package</Info>
    <Disk ovf:capacity="40000" ovf:capacityAllocationUnits="byte * 2^20" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" ovf:populatedSize="4156030976" vbox:uuid="677d376f-5bea-457f-a6b3-e1f1d9cde1c4"/>
  </DiskSection>
  <NetworkSection>
    <Info>Logical networks used in the package</Info>
    <Network ovf:name="NAT">
      <Description>Logical network used by this appliance.</Description>
    </Network>
  </NetworkSection>
  <VirtualSystem ovf:id="PacketFence-ZEN">
    <Info>A virtual machine</Info>
    <OperatingSystemSection ovf:id="101">
      <Info>The kind of installed guest operating system</Info>
      <Description>RedHat_64</Description>
      <vbox:OSType ovf:required="false">RedHat_64</vbox:OSType>
    </OperatingSystemSection>
    <VirtualHardwareSection>
      <Info>Virtual hardware requirements for a virtual machine</Info>
      <System>
        <vssd:ElementName>Virtual Hardware Family</vssd:ElementName>
        <vssd:InstanceID>0</vssd:InstanceID>
        <vssd:VirtualSystemIdentifier>PacketFence-ZEN</vssd:VirtualSystemIdentifier>
        <vssd:VirtualSystemType>vmx-07</vssd:VirtualSystemType>
      </System>
      <Item>
        <rasd:Caption>4 virtual CPU</rasd:Caption>
        <rasd:Description>Number of virtual CPUs</rasd:Description>
        <rasd:ElementName>4 virtual CPU</rasd:ElementName>
        <rasd:InstanceID>1</rasd:InstanceID>
        <rasd:ResourceType>3</rasd:ResourceType>
        <rasd:VirtualQuantity>4</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:AllocationUnits>MegaBytes</rasd:AllocationUnits>
        <rasd:Caption>12288 MB of memory</rasd:Caption>
        <rasd:Description>Memory Size</rasd:Description>
        <rasd:ElementName>12288 MB of memory</rasd:ElementName>
        <rasd:InstanceID>2</rasd:InstanceID>
        <rasd:ResourceType>4</rasd:ResourceType>
        <rasd:VirtualQuantity>12288</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:Address>0</rasd:Address>
        <rasd:Caption>scsiController0</rasd:Caption>
        <rasd:Description>SCSI Controller</rasd:Description>
        <rasd:ElementName>scsiController0</rasd:ElementName>
        <rasd:InstanceID>5</rasd:InstanceID>
        <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
        <rasd:ResourceType>6</rasd:ResourceType>
      </Item>
      <Item>
        <rasd:AddressOnParent>0</rasd:AddressOnParent>
        <rasd:Caption>disk1</rasd:Caption>
        <rasd:Description>Disk Image</rasd:Description>
        <rasd:ElementName>disk1</rasd:ElementName>
        <rasd:HostResource>/disk/vmdisk1</rasd:HostResource>
        <rasd:InstanceID>6</rasd:InstanceID>
        <rasd:Parent>5</rasd:Parent>
        <rasd:ResourceType>17</rasd:ResourceType>
      </Item>
      <Item>
        <rasd:AutomaticAllocation>true</rasd:AutomaticAllocation>
        <rasd:Caption>Ethernet adapter on &apos;NAT&apos;</rasd:Caption>
        <rasd:Connection>NAT</rasd:Connection>
        <rasd:ElementName>Ethernet adapter on &apos;NAT&apos;</rasd:ElementName>
        <rasd:InstanceID>7</rasd:InstanceID>
        <rasd:ResourceSubType>E1000</rasd:ResourceSubType>
        <rasd:ResourceType>10</rasd:ResourceType>
      </Item>
    </VirtualHardwareSection>
    <vbox:Machine OSType="RedHat_64" lastStateChange="2020-05-08T14:26:51Z" name="PacketFence-ZEN" ovf:required="false" snapshotFolder="Snapshots" uuid="{a57528dc-d267-4c43-a1a6-bc0b2de2d589}" version="1.16-linux">
      <ovf:Info>Complete VirtualBox machine configuration in VirtualBox format</ovf:Info>
      <Hardware>
        <CPU count="4">
          <PAE enabled="true"/>
          <LongMode enabled="true"/>
          <X2APIC enabled="true"/>
          <HardwareVirtExLargePages enabled="false"/>
        </CPU>
        <Memory RAMSize="12288"/>
        <Boot>
          <Order device="HardDisk" position="1"/>
          <Order device="DVD" position="2"/>
          <Order device="None" position="3"/>
          <Order device="None" position="4"/>
        </Boot>
        <VideoCapture file="." fps="25"/>
        <RemoteDisplay enabled="true">
          <VRDEProperties>
            <Property name="TCP/Address" value="127.0.0.1"/>
            <Property name="TCP/Ports" value="5946"/>
          </VRDEProperties>
        </RemoteDisplay>
        <BIOS>
          <IOAPIC enabled="true"/>
        </BIOS>
        <Network>
          <Adapter MACAddress="0800275D0EB0" enabled="true" slot="0" type="82540EM">
            <NAT/>
          </Adapter>
        </Network>
        <AudioAdapter driver="ALSA" enabledIn="false" enabledOut="false"/>
      </Hardware>
      <StorageControllers>
        <StorageController Bootable="true" PortCount="16" name="SCSI Controller" type="LsiLogic" useHostIOCache="false">
          <AttachedDevice device="0" hotpluggable="false" port="0" type="HardDisk">
            <Image uuid="{677d376f-5bea-457f-a6b3-e1f1d9cde1c4}"/>
          </AttachedDevice>
        </StorageController>
      </StorageControllers>
    </vbox:Machine>
  </VirtualSystem>
</Envelope>`




PacketFence-ZEN-v10.0.1.mf
`SHA256(PacketFence-ZEN-v10.0.1.ovf)= f804a6f88c061135ef7553e5d3d12d19c811ad68cb242a9797762276791bde43
SHA256(PacketFence-ZEN-v10.0.1-disk1.vmdk)= 4ff821b2cb5c20763c3492d85f08159bedd1ae3461dac7f64ff0c741ddf5d3de
`

**Comment by nqb** [comment]
According to a user on mailing-list, fix provided by #5606 (removal of useless IDE controller) is not enough to make ZEN 10.1.0 work on VMware 7.

**Comment by nqb** [comment]
@IncompleteString, could you make a try on latest ZEN and see if you got same error ?

**Comment by IncompleteString** [comment]
Yes I can try it on VMware 6.7.0 in a bit.

**Comment by IncompleteString** [comment]
PacketFence-ZEN-v10.1.0.ova imports properly on vSphere 6.7.0.

**Comment by nqb** [comment]
Thank you so much @IncompleteString for your feedback and bug report.

It seems issue is different and concern VMware 7.
