### ISSUE TITLE
advanced filter keeps being populated with 'var'

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5524]
**Describe the bug**
I tried configuring an advanced filter and failed due to another bug. Then I truncated the value but everytime I refresh the page, it populates it with 'var'

**To Reproduce**
1. Use the following connection profile:
```
[zammitcorp-open]
locale=
description=zammitcorp-open
advanced_filter=
filter=tenant:2,ssid:Boulette
filter_match_style=all
sources=email-zammitcorp
top_op=and
self_service=default
```
2. Reload hard and load the profile

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/83767876-25324c00-a64c-11ea-944c-bf2dbe13b61d.png)

**Comment by jrouzierinverse** [comment]
Let me check
