### ISSUE TITLE
Advanced filter in connection profile are not usable

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5530]
**Describe the bug**

Upgraded to the latest devel version, click on a previously created connection profile and you will see that:

![image](https://user-images.githubusercontent.com/1553962/83789597-f5437280-a664-11ea-968c-4dfaa2d5b557.png)

**Comment by satkunas** [comment]
@fdurand the fix from @jrouzierinverse appears to have worked. Can you please retest?

**Comment by fdurand** [comment]
i will test with the next devel package.
