### ISSUE TITLE
cert checkup warning on devel

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5531]
**Describe the bug**
Not sure if I should be worrying about this, just wanted to throw this out here:
```
WARNING - Cannot open the following certificate /usr/local/pf/conf/certmanager/radius_default_tls-eap-fast.crt
```

**Comment by fdurand** [comment]
It's just because the file is not yet generated.
Maybe i can add a check in pfcertmanager to check to see if the certificate is still valid.
