### ISSUE TITLE
X-PacketFence-Tenant-Id header isn't honored when value is set to 0

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5532]
**Describe the bug**
When the frontend sends X-PacketFence-Tenant-Id:0, I still see the users of the first tenant of the DB

**To Reproduce**
1. Login as the global tenant
2. Switch to the users tab

**Comment by jrouzierinverse** [comment]
This is fixed by c9d919ad46b95252838f1e80d58ef8fc0c7aec26
