### ISSUE TITLE
Radius config bug

### ISSUE THREAD

**Issue by jvwjgames** [inverse-inc/packetfence#5541]
When I edit /use/local/pf/raddb/auth.conf and restart radiusd using pfcmd the auth.conf file gets rewritten back to default. How do I stop this behavior? Thanks in advance. Also I am using Packet Fence V10.0.1

**Comment by fdurand** [comment]
Use the mailing list for that, it's not a bug.
https://sourceforge.net/projects/packetfence/lists/packetfence-users
