### ISSUE TITLE
web admin: unable to access Audit logs, Nodes and users

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5545]
**Describe the bug**
On a clean install, if I log as "admin", I'm unable to see users, nodes or logs.

**To Reproduce**
1. Install latest builds
2. Go on Users menu

=> Frontend report "no users"

**Expected behavior**
We should be able to see some users, nodes and logs.

**Additional context**
With my admin user, it seems that I'm connected to the "default" tenant.

An important thing: I used Venom to create a node (using API) and doesn't have any issue. My node is present in DB with `tenant_id=1`. However, if I try to do the same using frontend, I'm unable to create a node.

I set priority to "Critical" because it has large impacts on PacketFence which prevent to test correctly.

**Comment by julsemaan** [comment]
Is your webservices user/pass admin/admin ?
And your local admin user admin/admin ?

If so webservices takes precedence and you'll be logged in as tenant ID 0

**Comment by nqb** [comment]
> Is your webservices user/pass admin/admin ?

I didn't change this value so I assume yes.

>  And your local admin user admin/admin ?

Yes.

**Comment by julsemaan** [comment]
If this is really an issue for us to have this behavior, then the best option is to change the default password of the webservices or in the DB.

**Comment by nqb** [comment]
I tested after changing webservices password and it works as it should.

Anyway I pushed c820c62 because right now we don't change admin password during integration tests because we skip configurator. It's a workaround because #5484 will take care of this.
