### ISSUE TITLE
Switching from a tenant to another should reset the URL

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5548]
**Describe the bug**
When you switch from a tenant to another in the admin, the URL should reset, otherwise you may be viewing a node or a user that doesn't exist in the other tenant and that throws an error and leaves you in the 'Resetting view' state until you navigate somewhere else

**Comment by satkunas** [comment]
@julsemaan  I intentionally left it so the same URL is reloaded, so a user can easily switch between tenants without having to navigate back to same page/section each time they switch. If a user is viewing a specific resource that isn't available after switching tenants they should be self-aware of the reason why the page isn't loading. 

Perhaps it would be better for us to review the navigation guards and ensure failover redirects are being used in places where errors are being generated?

**Comment by julsemaan** [comment]
Redirect on error loading resource sounds like a good plan for me if its not too much of a pain to implement for you

**Comment by satkunas** [comment]
@julsemaan I added some navigation guards to Users and Nodes with https://github.com/inverse-inc/packetfence/commit/198d860e1f4f22b0934c182d684a0614f9f5a8a4

Let me know if this works as you expect and I'll continue deploying guards throughout the rest of the admin GUI.
