### ISSUE TITLE
Syslog parsers aren't tenant aware

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5549]
**Describe the bug**
The syslog parsers (pfdetect) aren't tenant aware which makes it impossible to trigger a security event for a node of a specific tenant

**To Reproduce**
1. Setup multi-tenancy
2. Setup a suricata syslog parser
3. Send an alert `echo "Apr 18 10:48:17 pfdetect(6716) INFO: alert received: 04/18/2018-10:48:17.643084 [**] [1:2002878:7] ET POLICY iTunes User Agent [**] [Classification: Potential Corporate Privacy Violation] [Priority: 1] {TCP} 172.20.20.169:52801 -> 165.254.0.105:80" > /usr/local/pf/var/run/suricata_alert`
4. The alert is always triggered for tenant 1

**Expected behavior**
We should have a tenant parameter for the syslog parsers to trigger events for different tenants

**Comment by jrouzierinverse** [comment]
For the regex parser should it be per rule?

**Comment by julsemaan** [comment]
I'd say per syslog configuration for all of them, that way its always at the same place for all of them

**Comment by jrouzierinverse** [comment]
Since each log can only have one regex parser.

If there is ever mixed tenant info in a log (which can be detected via a regex).

We would need to split it ahead of time into different logs (with Syslog).

Each regex parser would have to duplicate the regex of Syslog for processing the log lines.

Or have a single parser with multiple rules with no duplication.

**Comment by extrafu** [comment]
IMO, if there are two (or more) bogus rules that are being matched between tenants, they should be disabled and the tenant admin should refine his shit.

**Comment by julsemaan** [comment]
I don't think we should be handling the case where the same log is used by 2 tenants.

If data would come from a suricata sensor for example, then each tenant would usually have his own sensor and the syslog config could send it to different files
