### ISSUE TITLE
Live logs log himself

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5559]
**Describe the bug**
in logviewer when you track packetfence.log the tracking produce log of himself.

**To Reproduce**
1. Go to 'log viewer'
2. choose packetfence.log'
4. See logs

**Screenshots**
![image](https://user-images.githubusercontent.com/1553962/84190358-c9f5c480-aa64-11ea-82e7-7955c11d675c.png)

**Expected behavior**
We will need to filter that.

**Comment by julsemaan** [comment]
I can disable the GIN request logging (which appears there)

Would that be a good enough solution ?

**Comment by fdurand** [comment]
yes it should be enough

**Comment by julsemaan** [comment]
with GIN I'd have to disable logging of these lines for all the requests in the api-frontend

I'll try to use rsyslog to exclude these
