### ISSUE TITLE
Web admin: API auditing should be enable by default

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5561]
````
No logs found
Admin API Audit Audit Logs not found or setting is disabled in configuration. You can enable this setting in Configuration → System Configuration → Admin API Audit Configuration.
````

I'm unable to find that section in the admin.

**Comment by nqb** [comment]
It's certainly related to tenant. When I opened #5545, I got exactly same behavior.

**Comment by nqb** [comment]
On Debian, latest build, I don't have this issue using `admin` user with default password and with a webservices password different than `admin`.

**Comment by jrouzierinverse** [comment]
did you check what is in the DB?

**Comment by lzammit** [comment]
I don't understand what I should check ? Thanks.

**Comment by nqb** [comment]
> I don't understand what I should check ? Thanks.

If you have entries in admin_audit_api_log table

**Comment by jrouzierinverse** [comment]
I updated the text is that enough?

**Comment by jrouzierinverse** [comment]
> > I don't understand what I should check ? Thanks.
> 
> If you have entries in admin_audit_api_log table

```select * from admin_audit_api_log;```

**Comment by lzammit** [comment]
I re-did my db and it works.
