### ISSUE TITLE
Not able to create or save "mark as sponsor" for a user

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5564]
When try to create or save user with mark as sponsor option `Create` or `Save` button is inactive and showing errors

1. Go to 'Users'
2. Click on 'Create' or click on user for edition
3. Click on Actions
4. Set `mark as sponsor` and `sponsor access durations`

**Screenshots**
![mark_as_sponsor](https://user-images.githubusercontent.com/22956491/84255643-316a4d80-ab13-11ea-81f9-40279c0a967a.png)

**Expected behavior**
No errors and active `Save` or `Create` buttons.

**Comment by olmanolsztyn** [comment]
`Sponsor access duration` seems not to save too.

**Comment by julsemaan** [comment]
Re-opening this due to last comment.

@satkunas, can you investigate this?

**Comment by olmanolsztyn** [comment]
By the way could you investigate why Access Level `ALL` and `ALL_PF_ONLY` etc. doesnt display?

**Comment by satkunas** [comment]
> By the way could you investigate why Access Level `ALL` and `ALL_PF_ONLY` etc. doesnt display?

Check to ensure that "Allowed user access levels" is not empty in the users admin roles. See Configuration -> System Configuration -> Admin Access -> [Admin Role] -> User Options

**Comment by olmanolsztyn** [comment]
I ment in User > user settings > actions > access level settings are saving but after reload page doesnt display.

**Comment by olmanolsztyn** [comment]
Today after apply patches `Access-Level` started to dispay but still doesn't save (or display) `Sponsor access duration`. I noticed that `Tenant ID` is not changing and display after page reload too.
Before click `Save` button
![before_save](https://user-images.githubusercontent.com/22956491/84745969-9d3a3380-afb5-11ea-9817-c443e2440a9a.png)
After save and reload page
![after_save](https://user-images.githubusercontent.com/22956491/84746058-b6db7b00-afb5-11ea-86a8-63fdbcd5846f.png)

**Comment by julsemaan** [comment]
The tenant ID action shouldn't be displaying anymore as it shouldn't have been an available action in the first place.

Are you using devel for multi-tenancy ?
If not, multi-tenancy in the admin will only be there in 10.1

**Comment by olmanolsztyn** [comment]
`Are you using devel for multi-tenancy ?
If not, multi-tenancy in the admin will only be there in 10.1`
I'm not using i will wait for 10.1.
Anyway Sponsor access duration still not save/display in user actions.
