### ISSUE TITLE
CSP Headers prevent stripe authentication to succeed 

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5566]
**Describe the bug**

Not able to authenticate if csp header is activated

![image](https://user-images.githubusercontent.com/1553962/84310894-620cb000-ab30-11ea-9c61-f5e4da8e3604.png)

**Comment by cgx** [comment]
@fdurand This is configurable in the advanced section. But I noticed yesterday that even if you disable CSP headers they are still added, even after restarting `httpd.portal` and `haproxy-portal`. Any idea why?

**Comment by fdurand** [comment]
Yes i disable CSP yesterday and i was able to authenticate with stripe just after.
So it looks to me that it disabled CSP header.
I will have a look on my side.

**Comment by cgx** [comment]
@fdurand Actually I was customizing a connection profile and previewing it from the Web admin. That could help you in diagnosing this specific issue where the CSP headers are added even when disabled in the configuration.

**Comment by fdurand** [comment]
I am able to enable and disable them and it works as expected.
Can we do something for https://js.stripe.com ?

**Comment by cgx** [comment]
@fdurand You should add it to the `default-src` or add a new `frame-src` [directive](https://github.com/inverse-inc/packetfence/blob/devel/html/captive-portal/lib/captiveportal.pm#L145).
