### ISSUE TITLE
Configure a tier for 20.00$ will bill 2000$

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5567]
**Describe the bug**
Configure a tier for 20$ then the bill is set to 2000

**To Reproduce**

billing_tiers.conf

```
[Super_Access]
access_duration=20h
name=Super PAW access
price=20.00
role=guest
description=Bob est super
```
Request received by stripe:

```
{
  "source": "tok_1GsZaxIHkusDcikdEsaY4yDG",
  "currency": "USD",
  "amount": "2000",
  "description": "Bob est super"
}
```

**Comment by julsemaan** [comment]
seems like a reasonable margin of error to me

**Comment by lzammit** [comment]
Stripe needs their cut. A reasonable share.

**Comment by jrouzierinverse** [comment]
The amount must be an integer.
https://stripe.com/docs/api/charges

> amount
positive integer or zero
Amount intended to be collected by this payment. A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency). The minimum amount is $0.50 US or equivalent in charge currency. The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).

**Comment by fdurand** [comment]
20,00 $ is set from the admin gui

**Comment by jrouzierinverse** [comment]
The amount is in cents.

**Comment by jrouzierinverse** [comment]
$20.00 is 2000 cents

**Comment by fdurand** [comment]
ok so you can close it.
