### ISSUE TITLE
Missing use_time_balance configuration parameter on billing tier creation

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5568]
**Describe the bug**

Missing use_time_balance configuration parameter on billing tier creation

**To Reproduce**
1. Create a billing tier and save it
2. pfcmd checkup
3. WARNING - Missing parameter use_time_balance for billing tier Super_Access

**Comment by jrouzierinverse** [comment]
This is not a required field. So we can either make it required or skip the check.

**Comment by jrouzierinverse** [comment]
My suggestion is to skip the check.

**Comment by fdurand** [comment]
let's skip it.
