### ISSUE TITLE
Authentication rule passes when LDAP query is invalid

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#557]
Title says it all

**Comment by jrouzierinverse** [comment]
How is the LDAP query invalid? The query returns nothing or has a syntax error?
Under which circumstances does it happen?

**Comment by jrouzierinverse** [comment]
@julsemaan can you provide an example on the bug?
At minimum the invalid query that was produced.

**Comment by julsemaan** [comment]
Example was provided externally.

For the record. Using any LDAP source, create the following rule.
memberOf - isMemberOf - CN=Pain, DN=Dinde, DN=Moutarde
