### ISSUE TITLE
Upgrade from 10.0.1 to 10.1.0 fails with missing RADIUS private key file

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5574]
**Describe the bug**
Upgrading from 10.0.1 to 10.1.0 using the instructions currently in the upgrade guide doesn't allow to generate the right files for radiusd-auth to start

**To Reproduce**
1. Upgrade from 10.0.1 to 10.1.0 using instructions in the upgrade guide
2. At the pf restart stage, radiusd-auth doesn't start

**Additional context**

The error in FreeRADIUS:
```
Jun 11 14:19:07 packetfence radiusd[29296]: Unable to check file "/usr/local/pf/conf/certmanager/radius_default_tls-common.key": No such file or directory
Jun 11 14:19:07 packetfence radiusd[29296]: /usr/local/pf/raddb/mods-enabled/eap[481]: Failed parsing configuration item "private_key_file"
```

**Comment by fdurand** [comment]
do you have the pfcertmanager running ?
do you have something in /usr/local/pf/conf/certmanager directory ?

**Comment by julsemaan** [comment]
> do you have the pfcertmanager running ?
   The pfcertmanager was running at the end of the pfcmd service pf start

> do you have something in /usr/local/pf/conf/certmanager directory ?
   There was nothing in that directory

I did a second pfcmd service pf restart and it worked at that moment.
Is the pfcertmanager service expecting another service to be up to generate the right config?

**Comment by fdurand** [comment]
except pfconfig no.
I introduced partOf in systemd, it mean that if you restart pfcertmanager it will stop radius-auth first restart pfcertmanager and start radius-auth. But i don't think it cause the issue.(https://github.com/inverse-inc/packetfence/blob/devel/conf/systemd/packetfence-radiusd-auth.service#L10)
The only thing i can see if when the ./conf/certmanager mounting point hasn't been unmounted correctly. Maybe i can add in the systemd script an unmount before trying to start it.

**Comment by julsemaan** [comment]
happy to try the fix if you think that can help

**Comment by fdurand** [comment]
I have pushed the patch who try to unmount ./conf/certmanager reopen if it doesn't fix the issue.

**Comment by julsemaan** [comment]
Seems to have done the trick!

**Comment by fdurand** [comment]
it looks to be because the pfconfig resource::eap_config is not ready when it start the first time.

**Comment by julsemaan** [comment]
It worked this time for me. Seems like a "problème intempestif, n'importe quand, des fois" I guess

**Comment by fdurand** [comment]
Do you think it can be because i am using pfconfigdriver.FetchDecodeSocketCache instead of 
 pfconfigdriver.FetchDecodeSocket to fetch the config when the service start ? https://github.com/inverse-inc/packetfence/blob/devel/go/certmanager/main.go#L243

**Comment by julsemaan** [comment]
If the resource isn't loaded, it fetches it from pfconfig and fetches it if it was changed so I highly doubt this is the problem.

Perhaps a restart of packetfence-config is not made in your case so its not aware of the new namespaces. When I redid my test I made sure I did it right after my "yum update"

**Comment by fdurand** [comment]
Yes looks to be because pfconfig wasn't restarted on my side.
