### ISSUE TITLE
The service restart widget in the admin only restarts the service on a single node

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5576]
**Describe the bug**
When you use the service restart widget (like in the SSL certs section) and you restart a service from there, it only restarts it on the server you're on, not for the whole cluster.

**To Reproduce**
1. Go in SSL certificates section on a cluster
2. Restart one of the listed services
3. Only restarted on a single node

**Expected behavior**
We should either block this option when in cluster and instruct the user to use the command line, or better call each cluster member to restart the service.

**Comment by nqb** [comment]
@cgx or @satkunas, do you think we could have the first option mentioned by @julsemaan as +1 ?

**Comment by satkunas** [comment]
Export has been moved to row selection. We will be adding additional bulk actions here.

![Screen Shot 2021-08-05 at 8 26 23 AM](https://user-images.githubusercontent.com/3904468/128349706-2051a62c-b48f-4680-b0e0-b3e89268c11f.jpg)

**Comment by nqb** [comment]
I'm reopening this issue because @satkunas want to provide an answer on #5956

**Comment by nqb** [comment]
IMHO, we really need this feature. Several customers shared my opinion.

Once you have a cluster with more than 3 servers, it's painful to go through CLI to each of them to restart a service.

I'm updating milestone.
