### ISSUE TITLE
Portal sessions should be unified

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#558]
Right now, pf::web::dispatcher pf::web::externalportal use a different "Portal sessions" than the captive portal 
They should be using the same one to facilitate data sharing between the mod_perl modules and the Catalyst controllers.

**Comment by julsemaan** [comment]
@jrouzierinverse , can we aim that for 5.2 ?

**Comment by jrouzierinverse** [comment]
Yes

**Comment by jrouzierinverse** [comment]
Where are we still using CGI scripts?

**Comment by julsemaan** [comment]
not cgi scripts but the dispatcher and the external portal detection still use the old cgi sessions

**Comment by julsemaan** [comment]
"Fixed" by having the dispatcher session available inside the Catalyst session model
