### ISSUE TITLE
Logs files not generated after installing PacketFence

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5588]
**Describe the bug**
When I installed PacketFence on Debian or CentOS, I need to restart `rsyslog` by hand after I passed configurator. Otherwise, I have only these files in `/usr/local/pf/logs` directory and they have zero size:
```console
# ls -rtl /usr/local/pf/logs
total 0
-rw-rw-r--. 1 pf pf 0 Jun 15 14:17 packetfence.log
-rw-rw-r--. 1 pf pf 0 Jun 15 14:17 redis_cache.log
-rw-rw-r--. 1 pf pf 0 Jun 15 14:17 security_event.log
-rw-rw-r--. 1 pf pf 0 Jun 15 14:17 httpd.admin.audit.log
```

**To Reproduce**
1. Install PacketFence on Debian and CentOS without going through configurator

=> You got files mentioned below

2. Pass configurator

=> You got files mentioned below

3. Restart `rsyslog`

=> New files are created.

**Expected behavior**
Logs files should be present.

**Additional context**
This is what I seen during installation of `packetfence` package
```console
# journalctl -u rsyslog 
Jun 15 14:17:56 pfcen7night systemd[1]: Stopped System Logging Service.
Jun 15 14:17:56 pfcen7night systemd[1]: Starting System Logging Service...
Jun 15 14:17:56 pfcen7night packetfence[1652]: pfcmd.pl(1652) WARN: Failed to open /usr/local/pf/conf/pf.conf: No such file or directory at /usr/local/pf/lib/pf/CHI/db.pm line 29.
                                                (Carp::carp)
Jun 15 14:17:56 pfcen7night rsyslogd[1653]:  [origin software="rsyslogd" swVersion="8.24.0-52.el7" x-pid="1653" x-info="http://www.rsyslog.com"] start
Jun 15 14:17:56 pfcen7night systemd[1]: Started System Logging Service.
Jun 15 14:20:53 pfcen7night rsyslogd[1653]: imjournal: journal reloaded... [v8.24.0-52.el7 try http://www.rsyslog.com/e/0 ]

```

Excerpt of `yum history info`:
```
 151 Adding PacketFence config startup script
 152 packetfence-config service will be started by packetfence-httpd.admin service later
 153 Disabling emergency error logging to the console
 154 Warning: rsyslog.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 155 Restarting journald to enable persistent logging
 156 Setting packetfence.target as the default systemd target.
 157 Removed symlink /etc/systemd/system/default.target.
 158 Created symlink from /etc/systemd/system/default.target to /etc/systemd/system/packetfence.target.
 159 Restarting rsyslogd
```

**Comment by julsemaan** [comment]
It seems the restart of rsyslog is made before pf.conf is in place and the hook to generate the PF config doesn't work right. I'll see if I can move it

**Comment by julsemaan** [comment]
Try with commit 5ca7a2f69246315b61aac5097016eadb2cc0ec44

rsyslog is already restarted at the end of the install process so I removed the duplicate restart I put in place to disable the emergency logging to the console

**Comment by nqb** [comment]
Issue still presents @julsemaan. Same files mentioned below after passing through configurator.

No more error message in `rsyslog` logs.

In fact, `packetfence.conf` is missing from `/etc/rsyslog.d` before I restarted it by hand.

From my point of view, when we restarted `rsyslog` for the first time, it's new `systemd` configuration has not been taken into account. This is why we don't have a `packetfence.conf`in place.

**Comment by julsemaan** [comment]
I removed what I changed related to rsyslog that could have broken the build.

There must be something else that breaks it. 
From what I can tell its the missing pf.conf during the restart of rsyslog to generate the packetfence.conf

Are you still getting the error related to `pf.conf` in rsyslog ?

**Comment by nqb** [comment]
> Are you still getting the error related to `pf.conf` in rsyslog ?

No more error. I will investigate now.

**Comment by nqb** [comment]
I did a try on #5599.

@julsemaan, I will retest on Debian with fix 5ca7a2f you provided. Issue should not be present.

**Comment by nqb** [comment]
@julsemaan, your fix did the job for Debian. Mine is not working:
```
  84 Restarting rsyslogd
  85 Warning: rsyslog.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

**Comment by julsemaan** [comment]
I will try to install a fresh PF on the latest CentOS 7 and see

**Comment by julsemaan** [comment]
I'm unable to get this behavior on CentOS

What I did:
- Took a CentOS box
- Did a `yum update`
- Reboot
- Installed PF using `yum install packetfence --enablerepo=packetfence-devel`
- Got some stuff in my logs:
```
[root@localhost pf]# ll logs/
total 1196
-rw-r-----. 1 root pf   2321 Jun 16 10:59 api-frontend.log
-rw-r-----. 1 root pf     77 Jun 16 10:59 haproxy_admin.log
-rw-rw-r--. 1 pf   pf      0 Jun 16 10:58 httpd.admin.audit.log
-rw-r-----. 1 root pf   5552 Jun 16 10:59 mariadb_error.log
-rw-rw-r--. 1 pf   pf 538102 Jun 16 11:11 packetfence.log
-rw-r-----. 1 root pf 215241 Jun 16 10:59 pfconfig.log
-rw-rw-r--. 1 pf   pf   1470 Jun 16 10:58 redis_cache.log
-rw-r-----. 1 root pf   1662 Jun 16 10:58 redis_server.log
-rw-rw-r--. 1 pf   pf      0 Jun 16 10:58 security_event.log
```

**Comment by nqb** [comment]
It works now.
