### ISSUE TITLE
Unregistration date shouldn't be in the user response if it contains a zero value

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5591]
**Describe the bug**
Currently in the password table, an unset unregistration date (unregdate field) contains the zero date (0000-00-00 00:00:00). This makes the frontend think that an 'Unregistration date' action is set for that entry with the zero date.

After discussions with Darren, he needs the field to be completely omitted from the GET /api/v1/user/:user_id so that the action doesn't appear

This is to fix the bug when editing a user that has an access duration:
![image](https://user-images.githubusercontent.com/3857942/84681038-9356f880-af01-11ea-9c2b-dc1faae02911.png)

**Comment by jrouzierinverse** [comment]
Does this behavior also happen in 10.0 or 9.3?

**Comment by julsemaan** [comment]
This is devel, probably applies to older versions but I only investigated devel right now

**Comment by julsemaan** [comment]
This is still an issue.

Instead of having the zero date in the action field, I have an empty value in the value field but the action is still there although it shouldn't be

**Comment by satkunas** [comment]
Backend appears to ignore all actions. The following payload does not mutate the user at all (except `address`).

```
/usr/local/pf/sbin/pfperl-api get -M PATCH -c '{"address":"test","actions":[{"type":"set_unreg_date","value":"2022-01-01"},{"type":"set_role","value":"1"},{"type":"set_access_level","value":["ALL"]}]}' /api/v1/user/testUser
```

**Comment by satkunas** [comment]
>Instead of having the zero date in the action field, I have an empty value in the value field but the action is still there although it shouldn't be

@julsemaan I've address this with my last commit.

I re-opened for @jrouzierinverse to have a look at my last comment.

**Comment by julsemaan** [comment]
@satkunas, I guess we can close this now right ?

**Comment by jrouzierinverse** [comment]
Should we close this?

**Comment by julsemaan** [comment]
Darrent already did it yesterday
