### ISSUE TITLE
Admin account can be created with a valid_from date in the future

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5594]
**Describe the bug**
When you pass through configurator without changing timezone (because your server is already configured with timezone on system) and your web browser uses a timezone different from the server, `admin` account will be created in DB with a `valid_form` date that uses web browser timezone. 

It's a problem because PF will check `valid_from` date using timezone configured on the server and your account could be considered as invalid.

Related to #5390

**To Reproduce**
1. Install PF on a server with UTC timezone
2. Pass through configurator without changing timezone server (with web browser configured in UTC+2 timezone)
3. Check `valid_from` field of `admin` account in DB

```sql
SELECT valid_from FROM password where pid='admin'\G;
```
=> `valid_from` field is set to your web browser value.

**Expected behavior**
`valid_from` field should always be set using timezone configured on server.

**Comment by nqb** [comment]
@cgx and @julsemaan, what do you think about configuring timezone at step 1 ? 

That's way, if timezone has been changed, we restart MariaDB to take new timezone into account. If no change occur, we assumed timezone is correct.

Then when configuring admin account, we use server timezone in place of web browser timezone.

We could also disallow users to go at step 2 if they didn't reboot after they changed timezone. IIRC, rebooting a PF server at this step will not cause issue.

**Comment by julsemaan** [comment]
We can just make the valid_from be the smallest date @cgx can do in Javascript.

There is no need to set this to a specific date.

I'll try to see if I can find where that is

**Comment by nqb** [comment]
> We can just make the valid_from be the smallest date @cgx can do in Javascript.

You mean set `valid_from` to the lower date (by doing a comparison between web browser date and system date) ?

**Comment by julsemaan** [comment]
> > We can just make the valid_from be the smallest date @cgx can do in Javascript.
> 
> You mean set `valid_from` to the lower date (by doing a comparison between web browser date and system date) ?

No, I'll just set it to `1970-01-01 00:00:00`
