### ISSUE TITLE
Incorrect timezone check regex on debian

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/packetfence#5595]
I'm getting lots of the following warnings when using pfcmd and in most log files

```
WARNING: The timezone is being changed from /usr/share/zoneinfo/Europe/Berlin to Europe/Berlin on the system. It is advised to reboot the server so that all services start with the correct timezone.
```
I think its related to the regex not working

`$lt =~ s/..\/usr\/share\/zoneinfo\///g;`

if i print out `$lt` its value is `/usr/share/zoneinfo/Europe/Berlin`

changing it to `$lt =~ s/\/usr\/share\/zoneinfo\///g;` works

**To Reproduce**
Clean install on debian-9
Timezone set to Europe/Berlin

**Comment by julsemaan** [comment]
The `../` will need to be conditional in the regex as on CentOS that's the regex that works
