### ISSUE TITLE
Fingerbank device class change even device is the same

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5596]
**Describe the bug**
I got notification that Fingerbank detected device change even device is the same.

**Fingerbank change notification**
Previous profiling
```
Detect  : Fingerbank device class change Previous device detected: Windows OS
MAC Address    : 7c:b2:7d:e4:cf:d2
IP Address     : 10.156.10.200 (active)
IP Info        : IP active since 2020-06-16 12:51:18 and DHCP lease valid until 2020-06-17 12:51:18
```
Next profiling
```
DEVICE PROFILING INFORMATION
Device: Gaming Console/Microsoft Gaming Console/Xbox One Device version: 
Device profiling confidence level: 79
```
**Expected behavior**
The device should always be profiled in the same way.

**Comment by olmanolsztyn** [comment]
Profiling has changed again:
```
Detect  : Fingerbank device class change Previous device detected: Gaming Console
MAC Address    : 7c:b2:7d:e4:cf:d2
IP Address     : 10.156.10.200 (active)
IP Info        : IP active since 2020-06-16 13:21:21 and DHCP lease valid until 2020-06-17 13:21:21
```
```
DEVICE PROFILING INFORMATION
Device: Operating System/Windows OS/Microsoft Windows Kernel 10.0 Device version: 10 Device profiling confidence level: 98
```

**Comment by julsemaan** [comment]
It can happen that the device profiling of a device changes as we learn information about it since we're not receiving all of the data points of the device all at the same time

I will try to investigate if this could have been better and if there are some bad profiling rules related to these

**Comment by julsemaan** [comment]
I looked into it and it was mis-profiled as an Xbox One due to one of the destination hosts in the request

The rulesets have been adjusted and will be deployed in production soon
