### ISSUE TITLE
Creating a switch from a template containing a dash in the identifier fails with "invalid module name"

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/packetfence#5597]
**Describe the bug**
I created a switch template with the identifier `Aruba::2930M-DennisTemplate` and got no validation error.
When i try to create a  new switch using this template i get this error in the log
```
Jun 16 12:59:25 srv-pf packetfence: ERROR pfperl-api(12265): invalid module name 'pf::Switch::Aruba::2930M-DennisTemplate' at /usr/local/pf/lib/pfappserver/Form/Config/Switch.pm line 769.
```

**To Reproduce**
1. Create two switch templates with one containing a dash
2. Try to create new switches from those templates

**Comment by erSitzt** [comment]
Btw. my name is a result of the clone-Button which creates an identifier like this

`Aruba::ArubaSwitchNG-copy` and i just replaced `copy`

**Comment by julsemaan** [comment]
The frontend should clone these and add `_copy` instead of `-copy`

And there should be validation that there are no `-` in the switch template module name

**Comment by satkunas** [comment]
Hyphen changed to underscore in https://github.com/inverse-inc/packetfence/commit/e1e9c68f2680894bb1013b8987596986be7f24db

@jrouzierinverse the backend will still need to validate the identifier to ensure no hyphen is used. It can also optionally send a regex pattern in the meta for the identifier to catch these invalid chars on the front-end.
