### ISSUE TITLE
Frontend fails to validate a date equal to '2038-01-01 00:00:00'

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5598]
**Describe the bug**
The maximum date we allow '2038-01-01 00:00:00' fails to validate on the frontend

**To Reproduce**
1. Import the schema
2. Edit the admin user
3. Go in the 'Actions' tab

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/84772900-9c030980-afa9-11ea-813f-67572b293b77.png)

**Expected behavior**
2038-01-01 00:00:00 is a valid date, anything after it isn't

**Comment by satkunas** [comment]
Date validation was removed in https://github.com/inverse-inc/packetfence/issues/5592

Validation can not be re-enabled until after we deprecate zero dates.

[Edit] The validator shown above should also be removed.

**Comment by julsemaan** [comment]
Well the validation seems to still be there because its blocking me from saving with that value
