### ISSUE TITLE
Impossible to set dynamic unregdate in auth source

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5601]
**Describe the bug**
Its currently impossible to set an unreg date as a dynamic unreg date (dynamic year)

Values `0-01-01` and `0000-01-01` are not valid although they should be valid (that was fixed in the new admin at some point)

**To Reproduce**
1. Create an auth source
1. Create a catchall rule
1. Set the action to "Unregistration date"->"0000-01-01"

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/84812680-c326fe80-afdc-11ea-90ba-0630a977fd10.png)

**Comment by julsemaan** [comment]
@satkunas, can you also see if this needs to be cherry-picked into maintenance/10.0

**Comment by satkunas** [comment]
Temporary workaround with https://github.com/inverse-inc/packetfence/commit/5e74de6aeebd28a1370cfe01f44d0c6f2e8a447d

@julsemaan also picked into `maintenance/10.0`
