### ISSUE TITLE
Perl unit tests report error

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5602]
Perl unit tests report [error](https://gitlab.com/inverse-inc/packetfence/-/jobs/598523940#L691), seems to be related to 1e197b63532c14fd939134363dd991e582562ab9

**Comment by jrouzierinverse** [comment]
I cannot replicate I pushed additional logging can you retry?

**Comment by nqb** [comment]
Pipeline failed due to changes related to `impacket`, I will try to fix it and re-run pipeline.

**Comment by extrafu** [comment]
Can we close this?

**Comment by jrouzierinverse** [comment]
The issue with impacket is still there.

**Comment by nqb** [comment]
Issue with impacket has been fixed by @fdurand and I didn't see initial error anymore.
