### ISSUE TITLE
web admin: using Switch Groups in Nodes menu take a while

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5603]
**Describe the bug**
Since 54c8ca3ba7c47b949e7e49e75c49db8b869bd959, web admin displays all switch groups in Nodes menu (in place of 25 in the past).

I noticed that API call (`/api/v1/config/switch_groups?limit=1000`) can take a while because we request all the configuration elements for switch groups but we don't really use it at this moment.

On top of that, once we got all switch groups, we do a new query to get members of all switch groups (`/api/v1/config/switch_group/default/members`). Again, we got all configuration information for each switch which is not necessary at this point.

I could be wrong but from my point of view, we only need to get:
- switch groups names
- switch groups members with their description and IP address

**Expected behavior**
Only request needed informations on switch and switch groups to speed up loading of Nodes menu.

**Comment by jrouzierinverse** [comment]
@satkunas can you use ```/api/v1/config/switch_groups?raw=1```

**Comment by satkunas** [comment]
Improved fix in #5762
