### ISSUE TITLE
Unreg date is not completely honored when doing registration on portal

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5611]
**Describe the bug**
When you register a node using a user which has an unregistration date or a source which defined an unregistration date, I noticed that time saved in DB doesn't take seconds into account.

It means that if you want to register a node until `2020-06-22 11:00:00`, it will not works because unregistration date saved in DB will be `2020-06-22 00:00:00`. Consequently, your device will be deregistered at the beginning of the day.

**To Reproduce**
1. Create a local user with following actions:
* Role: `gaming`
* Unregistration date: `2020-06-22 11:00:00`
2. Try to register a device on captive portal using Username/Password login with local user

=> You got "Role gaming has been assigned to your device with unregistration date: 2020-06-22"

Node saved in DB:
```sql
select unregdate from node where mac LIKE "00:%"\G;
*************************** 1. row ***************************
unregdate: 2020-06-22 00:00:00
```

**Expected behavior**
Unregistration date saved in DB should be the one defined on user or in authentication rule.

**Additional context**
After I put `httpd.portal` in debug, I got following logs in `packetfence.log`:
```
Jun 18 09:36:01 pfcen7stable packetfence_httpd.portal: httpd.portal(23401) DEBUG: [mac:00:11:22:33:44:55] [null] Returning '2020-06-22 11:00:00' for action 'set_unreg_date' for username default (pf::authentication::match)
[..]
Jun 18 09:36:01 pfcen7stable packetfence_httpd.portal: httpd.portal(23401) DEBUG: [mac:00:11:22:33:44:55] new_node_info after auth module actions : $VAR1 = {
          'pid' => 'default',
          'time_balance' => undef,
          'category' => 'guest',
          'bandwidth_balance' => undef,
          'unregdate' => '2020-06-22'
        };
 (captiveportal::PacketFence::DynamicRouting::Module::Authentication::execute_actions)
```
It seems that last part of `unregdate` is truncated in the captive portal code.

**Comment by jrouzierinverse** [comment]
I think this is a frontend issue cutting off the time.
Let me verify the payload being sent for creation.

**Comment by jrouzierinverse** [comment]
Which version of packetfence is this?

**Comment by nqb** [comment]
v10.1.0

**Comment by nqb** [comment]
@jrouzierinverse, I'm not able to put a debug at correct place to pinpoint the issue. I will let you troubleshoot that.

**Comment by jrouzierinverse** [comment]
The issue is not the frontend.
The issue seems to else where.

**Comment by jrouzierinverse** [comment]
We never supported time for unregdate.
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/config.pm#L471-L510
But now we are allowing to enter the time even though we don't support it.
@julsemaan @satkunas how do you want to proceed?

**Comment by julsemaan** [comment]
The time should be removed, but before that we need proper handling of zero dates without time in the admin so we don't get other issues related to that change

**Comment by nqb** [comment]
Ok got it. @satkunas is the best to do adjustements right ?

**Comment by nqb** [comment]
> The time should be removed, but before that we need proper handling of zero dates without time in the admin so we don't get other issues related to that change

I'm not sure it is the case right now.

**Comment by nqb** [comment]
@satkunas, there is an issue with your fix.

When I create a node, I'm able to only provide a date (without HH:MM:SS) using calendar provided by frontend. Node creation works, entry is saved in DB like this: `unregdate: 2021-08-25 00:00:00`.

Consequently, when I edit this node, frontend displays `unregdate` as it is in DB: `2021-08-25 00:00:00` and complain about format: 

![Capture d’écran de 2021-08-05 10-28-18](https://user-images.githubusercontent.com/10830260/128318211-0895b282-a2c0-46a4-8576-c075373f575d.png)

**Comment by satkunas** [comment]
@nqb the frontend doesn't alter the values returned from the backend, except through user interaction. We'll need to backend to strip the time off of the value.

**Comment by satkunas** [comment]
Changes also affect #5516

**Comment by nqb** [comment]
I'm reopening this one due to unexpected behavior.

Things I noticed:
- I received a DHCP request for an unknown node: 
  * unregdate equals to `0000-00-00 00:00:00` in DB
  * frontend displays `0000-00-00`
  * registration of node through captive portal
  * unregdate equals to `2021-08-06 10:23:26`
  * frontend displays  `2021-08-06 10:23:26` => consequently frontend reports an error.

**Comment by nqb** [comment]
To summarize:
- unregdate on node should be date time
- unregdate on user and authentication rules should be date because we never support it.

@jrouzierinverse will revert changes
@nqb too
@satkunas will adjust frontend and revert changes.
