### ISSUE TITLE
web admin: display current admin role of a user

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5612]
**Is your feature request related to a problem? Please describe.**
Currently, frontend doesn't display admin roles assigned by administration rules when you log in on web admin. It's a problem because it could be hard to know which admin roles a user had.

For example, if you use a LDAP source to dynamically assign admin roles, the only way to know admin roles of a user is to check logs because LDAP users are not created in person table.

**Describe the solution you'd like**
I have seen that admin roles are returned by API in token_info response. It would be nice to display them somewhere in web admin next to name of logged user and tenants.

**Comment by satkunas** [comment]
Moving milestone due to time contraints.

**Comment by nqb** [comment]
Has been partially fixed by #6311.

@satkunas, do you think it's possible to display **name** of current admin role ?

From what I see in API response of `token_info`, information is available.
