### ISSUE TITLE
Multitenancy web admin missing Configuration Tab for admin user

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5614]
**Describe the bug**
When admin login to default tenant there is configuration tab missing.
Admin is in default tenant and has access-level `ALL`

**Screenshots**
![admin_no_configuration](https://user-images.githubusercontent.com/22956491/85127397-a1718580-b22f-11ea-922a-f211b5557270.png)

**Expected behavior**
Configuration tab should be visible when local user has Access-Level `ALL`

**Additional context**
That happened after i added radius authentication source used to login admin user to another tenant.

**Comment by olmanolsztyn** [comment]
Does the system admin need to be in `global` tenant to have access to server configuration?

**Comment by julsemaan** [comment]
If you have more than 1 tenant, only the global tenant can modify the configuration

**Comment by olmanolsztyn** [comment]
So to configure realms i need to move to global tenant?

**Comment by julsemaan** [comment]
Please move configuration related questions to the mailing list

For your question, realms can only be configured in the configuration file (realm.conf) for now (its the only config piece missing). In the identifier of the configuration section, first digit is the tenant ID, then a space, then the realm
