### ISSUE TITLE
Failed executing search on report.

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5620]
**Describe the bug**
After update to 10.1.0 version user is unable to see any of `Other Reports`.
PF response with log `Failed executing search on report.`

**To Reproduce**
1. Go to `Reports` > `Other Reports`
2. Click on `All Authenctications` or any other report
3. See error `Failed executing search on report. Check server-side logs for details.
dynamic_report/authentications/search`

**Screenshots**
![report_error](https://user-images.githubusercontent.com/22956491/85282298-ce21d900-b48b-11ea-9459-7d85338881df.png)

**Expected behavior**
User should see logs.

**Comment by julsemaan** [comment]
Can you post the server side logs that contain the error please

**Comment by olmanolsztyn** [comment]
Where can i find this logs?

**Comment by olmanolsztyn** [comment]
I found in packetfence.log db query error:
`packetfence: pfperl-api(19881) ERROR: Database query failed with non retryable error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Name, auth_log.attempted_at DESC LIMIT 25 OFFSET 0' at line 1 (errno: 1064) [SELECT auth_log.process_name as "Process Name", auth_log.mac "MAC Address", auth_log.pid as "Owner", auth_log.status as "Status", auth_log.attempted_at as "Attempted at", auth_log.completed_at as "Completed at", auth_log.source as "Source", auth_log.profile as "Connection Profile" FROM auth_log WHERE ( ( auth_log.process_name LIKE ? OR auth_log.mac LIKE ? OR auth_log.pid LIKE ? OR auth_log.status LIKE ? OR auth_log.source LIKE ? ) ) ORDER BY Process Name, auth_log.attempted_at DESC LIMIT ? OFFSET ?]{%%, %%, %%, %%, %%, 25, 0} (pf::dal::db_execute)
`

**Comment by julsemaan** [comment]
For some reason there is a sort that is added in the report query using the first field.

In this case its adding a sort on "Process Name"

This is also the case in other reports

It seems the frontend has regressed on this since the sort wasn't (and shouldn't) be defined by the frontend

Here is the problematic payload:
```
{
    "cursor": 0,
    "end_date": null,
    "fields": [
        "Process Name",
        "MAC Address",
        "Owner",
        "Status",
        "Attempted at",
        "Completed at",
        "Source",
        "Connection Profile"
    ],
    "limit": 25,
    "query": {
        "op": "and",
        "values": [
            {
                "op": "or",
                "values": [
                    {
                        "field": "auth_log.process_name",
                        "op": "contains",
                        "value": null
                    },
                    {
                        "field": "auth_log.mac",
                        "op": "contains",
                        "value": null
                    },
                    {
                        "field": "auth_log.pid",
                        "op": "contains",
                        "value": null
                    },
                    {
                        "field": "auth_log.status",
                        "op": "contains",
                        "value": null
                    },
                    {
                        "field": "auth_log.source",
                        "op": "contains",
                        "value": null
                    }
                ]
            }
        ]
    },
    "sort": [
        "Process Name"
    ],
    "start_date": null
}
```

The backend does support sorting but the column name must be specified not its alias but for the moment there is not sorting capability on the custom reports other than the one defined in the config file so we should just find out where a sort is implicitly added on the first field of the custom report.

This is using the following report configuration (which is part of our defaults):
```
[authentications]
type=builtin
description= All Authentications
long_description=<<EOT
All the authentications (RADIUS, portal) that have occured on the server.
EOT
# The table to search from
base_table=auth_log
# The columns to select
columns=auth_log.process_name as "Process Name", auth_log.mac "MAC Address", auth_log.pid as "Owner", auth_log.status as "Status", auth_log.attempted_at as "Attempted at", auth_log.completed_at as "Completed at", auth_log.source as "Source", auth_log.profile as "Connection Profile"
searches=string:Process Name:auth_log.process_name,string:MAC Address:auth_log.mac,string:Owner:auth_log.pid,string:Status:auth_log.status,string:Source:auth_log.source
date_field=attempted_at
base_conditions_operator=any
person_fields=Owner
node_fields=MAC Address
order_fields=-auth_log.attempted_at
```

**Comment by olmanolsztyn** [comment]
Email, SMS and Sponsor reports seems not to be affected.
