### ISSUE TITLE
Missing user tenant id setting in Actions tab.

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5622]
**Describe the bug**
Missing tenant id setting in user action.

**To Reproduce**
1. Go to 'Users > "username" > Actions'
2. Click on '+' to add tenant setting
4. There is missing `tenant` setting to choose.

**Screenshots**
![missing_tenant](https://user-images.githubusercontent.com/22956491/85286719-6ff8f400-b493-11ea-935e-755e9e628565.png)

**Expected behavior**
There should be available `tenant` setting in user `Actions` tab.

**Comment by julsemaan** [comment]
The user will always be created under the current tenant
