### ISSUE TITLE
Web admin: users device list only 25 devices

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5626]
**Describe the bug**
Users device list shows only 25 devices.

**To Reproduce**
1. Go to 'Users' > `Username` > `Devices`

**Screenshots**
![users_device_list](https://user-images.githubusercontent.com/22956491/85373215-3b3c7980-b533-11ea-8cab-d510499a4c16.png)

**Expected behavior**
All user devices should be listed.

**Comment by julsemaan** [comment]
@satkunas, should we add pagination to this section or just make it very large ?

Note that for the `default` user this may reach thousands of devices

**Comment by satkunas** [comment]
@julsemaan pagination is currently not supported in the User Tabs, as the extra endpoints (nodes, security events) are pre-fetched when the pid is requested and added statically to the user object - which means the node search endpoint are currently not reactive inhibiting pagination.

I can bump the list size easily; but like you said, the default user could list thousands of devices. If we want to add pagination here much more work is needed.

**Comment by julsemaan** [comment]
@satkunas, I see another solution.

When in the nodes tab, when you scroll at the bottom, it displays a message saying something like "Only 25 nodes have been displayed, click here to view all the nodes of the user". When clicking on that, it would bring you to the node page with a search on the user PID to view all the nodes in the full node page.

What do you think ?

**Comment by satkunas** [comment]
@julsemaan great idea. I bumped the limit to 1k and added a button at the end of the table that redirects to the node search when that limit is reached.
