### ISSUE TITLE
Implement IETF CAPPORT (draft-ietf-capport-rfc7710bis-07)

### ISSUE THREAD

**Issue by danpoltawski** [inverse-inc/packetfence#5627]
**Is your feature request related to a problem? Please describe.**
Captive portal detection is somewhat fragile with interception and particularly with the increased prevalence of TLS across the internet.  it would be good to adopt the [IETF Capport](https://tools.ietf.org/html/draft-ietf-capport-architecture) architecture.

**Describe the solution you'd like**

Apple have [announced their intention](https://developer.apple.com/news/?id=q78sq5rv) their intention to ship [draft-ietf-capport-rfc7710bis-07](https://tools.ietf.org/html/draft-ietf-capport-rfc7710bis) in iOS 14 and macOS 11. It would be good to adopt this as this will improve things for real iOS/macOS users when it's released.

**Additional context**
I see this was previously added in https://github.com/inverse-inc/packetfence/pull/1265 but from what I can see this didn't survive the transition to the go DHCP server and the previous standard used an old option code. (I haven't yet tested, just from my look at the code)

https://github.com/capport-wg/architecture
https://github.com/capport-wg/7710bis/issues/1 
https://github.com/capport-wg/api

**Comment by nqb** [comment]
Hello @danpoltawski, I will close this issue in favor of #5638 (duplicate but with more information).

**Comment by danpoltawski** [comment]
I'm going to close this, as it seems you meant to but didn't press the button :-)
