### ISSUE TITLE
Multitenancy: FATAL - person user id "admin" must exist - please reinitialize your database

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5628]
**Describe the bug**
When i moved default `admin` user to global tenant (id 0) then couldnt restart packetfence services

**To Reproduce**
1. Move default admin user into global tenant
2. restart packetfence services
3. See error `FATAL - person user id "admin" must exist - please reinitialize your database`

**Expected behavior**
Default admin user should be in global tenant (id 0) as default when multitenancy is using.

**Comment by julsemaan** [comment]
don't move it, create a new admin user or use the webservices credentials
