### ISSUE TITLE
Web admin: Missing condition and is not valid value in radius auth source

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5629]
**Describe the bug**
After using `to-10.1-authentication-prefix.pl` update script value radius_request causes empty condition value in radius authentication source and trigger value is not valid when save.

**To Reproduce**
1. Go to 'Configuration' > `Policies and Access Control` > `Authentication Sources` > `Internal Sources`
2. Click on radius server
4. See there is blank condition in rule

**Screenshots**
![empty_condition](https://user-images.githubusercontent.com/22956491/85384375-61691600-b541-11ea-8138-28ae833fd29c.png)
![radius_request_is_not_valid](https://user-images.githubusercontent.com/22956491/85384387-63cb7000-b541-11ea-8ffa-2a4824da9cba.png)

**Expected behavior**
Condition should be visible as before update and saving should be successful.

**Comment by julsemaan** [comment]
@fdurand, can you take a look into this ?

**Comment by olmanolsztyn** [comment]
The same problem exists in `Exclusive Sources` > `Eduroam`

**Comment by nqb** [comment]
Reopening issue because I assume @olmanolsztyn as applied maintenance patches provided by @fdurand
