### ISSUE TITLE
EAP-TLS / PKI: PKI provider type

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#563]
Type is currently restricted to "Inverse". Either, we make it more dynamic so that we can define the types, or we hide it. For us, it can be understandable, but from a user / admin perspective, it is kind of a useless field which is not documented.

**Comment by extrafu** [comment]
No, leave it like that. Come see me for the rationale.

**Comment by dwlfrth** [comment]
After quick discussion with @extrafu, Inverse should be renamed PacketFence-PKI

**Comment by extrafu** [comment]
"PacketFence PKI" - let's drop the unnecessary dash.

**Comment by dwlfrth** [comment]
@jrouzierinverse please confirm here (by writing a comment) and close the issue once modified in the PR (#520)

**Comment by dwlfrth** [comment]
Can we reference commit id when closing issues (or reference issue number in commit so it closes it automagically and create the reference...)

**Comment by dwlfrth** [comment]
Forget about it... looks like Fixes != fixes in Github !

**Comment by jrouzierinverse** [comment]
Funny in their example it says it would work.

https://help.github.com/articles/closing-issues-via-commit-messages/

It was working before

**Comment by jrouzierinverse** [comment]
It looks like the commit has to be in the devel branch.

https://github.com/blog/1386-closing-issues-via-commit-messages
