### ISSUE TITLE
Web Admin: audit log and nodes are not tenant aware.

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5631]
**Describe the bug**
In a situation where the user is created in a tenant other than 'default', then after correct logging in and registration of the device there are no entries in the audit log (in this tenant) and the registered device appears in 'default' tenant registered for the user 'default' without assigning a role and access duration etc.
The same user in 'default' tenant registers devices correctly.

**To Reproduce**
1. Create new tenant with specified domain you will use.
2. Login as admin that have access to global tenant and move to new created tenant.
3. Go to 'Users' and create user in new created tenant.
2. Login device into dot1x network using newly created user credentials 
3. After successful logging and registering device node is missing in 'Nodes' in new created tenant (appears in `default` tenant)
4. See no entries in audit log in this tenant.

**Expected behavior**
Entries in the audit log should appear for device registration in the appropriate tenant. Registered devices per user from a given tenant should be visible in the same tenant in which the user is created.

Correct me if there is a different way that it should work.

**Comment by nqb** [comment]
Hello,

This is certainly a configuration issue. Your network device where RADIUS request is coming is certainly not assigned to your tenant different than default. On a 10.2 setup with tenant, I don't have this issue.
