### ISSUE TITLE
web admin: impossible to use Switch port filter

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5632]
**Describe the bug**
When you want to make a filter on Switch Port value in a connection profile, you should use `<SwitchId>-<Port>` like we have in [unit tests](https://github.com/inverse-inc/packetfence/blob/8202a8ed2f87fc398a0ddf6eb15a3998f2500666/t/data/profiles.conf#L20-L21) but this syntax is not allowed by frontend. If you use an integer like frontend suggests you, backend will report an error due to [validation](https://github.com/inverse-inc/packetfence/blob/8202a8ed2f87fc398a0ddf6eb15a3998f2500666/lib/pf/validation/profile_filters.pm#L156).

**To Reproduce**
1. Create a new connection profile
2. Add a basic filter on Switch Port value with value equals to 192.168.1.3-1

=> Frontend reports "Invalid port number"

**Expected behavior**
`<SwitchId>-<Port>` syntax should be allowed.

**Comment by jrouzierinverse** [comment]
The syntax for switch port is ```<SwitchId>-<Port>```
The frontend validation should just validate if the value is in that form.

**Comment by satkunas** [comment]
Is there a specific reason why we're not using the `:` separator and using `-` instead? This seems counter-intuitive as `:` is almost always used to separate an address and a port (since switch IDs must be a valid IP address).

**Comment by jrouzierinverse** [comment]
We have mac based switches in which we use the ':' so we used the '-'

**Comment by jrouzierinverse** [comment]
This is fixed by 58c10aca918f06c7b7108e0988d3c08c1d2b2afd

**Comment by nqb** [comment]
@jrouzierinverse, unless I'm missing something, 58c10ac is not in devel.
