### ISSUE TITLE
Restart Switchport with COA

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#5633]
Restart Switchport configuration can be added to Switch Templates to set the COA attributes. This way we don't need SNMP for the Switches that support port bounce with COA.

**Comment by nqb** [comment]
Hello,

From what I see, it seems possible to return specific RADIUS attributes in CoA (vendor-specific) to bounce port. I didn't see anything standard in [RFC 5176](https://tools.ietf.org/html/rfc5176)

**Comment by lyubomirtraykov** [comment]
You can also add configuration for port disable using  RADIUS attributes in CoA (vendor-specific) and send it on security event.
