### ISSUE TITLE
web admin: Advanced filter (advanced mode) on a connection profile doesn't work as expected

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5634]
**Describe the bug**
On a connection profile, when you define an Advanced filter using Advanced mode (for advanced users in an advance configuration), your filter is not saved in `profiles.conf`.

**To Reproduce**
1. Create a connection profile called `test2`
2. Switch to Advanced mode to define an Advanced filter
3. Copy following content in field: `last_connection_type == "Wireless-802.11-EAP"`
4. Save

=> Check `profiles.conf`,  `advanced_filter` value is empty.

**Expected behavior**
`advanced_filter` should be `last_connection_type == "Wireless-802.11-EAP"`

**Additional context**
I compared JSON payload sent by frontend when you create connection profile with advanced filter in :
- [basic mode](https://gist.github.com/nqb/d577190a8c3712e9ef056609526ad10f)
- [advanced mode](https://gist.github.com/nqb/acf7eeda56d5bc12104812063f08c56c)

It looks like in advanced mode, conditions are not inserted in the `values` list.

**Comment by satkunas** [comment]
Waiting on @jrouzierinverse to provide a `parse_condition` fix before I resolve this issue.
