### ISSUE TITLE
Missing quotes in the web documentation

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5636]
Open the web page: [Install Guide](https://packetfence.org/doc/PacketFence_Installation_Guide.html#_connection_profiles)
scroll down and find the following text:

Examples (Match machine authentication on secure wireless ssid)
machine_account != "" && connection_type == Wireless-802.11-EAP

This example does not work. The value should be in quotes:
machine_account != "" && connection_type == **"Wireless-802.11-EAP"**

**Comment by ZdenekPala** [comment]
![image](https://user-images.githubusercontent.com/16311452/85531812-63010f80-b60f-11ea-87d3-bfb10da9fcdd.png)

**Comment by nqb** [comment]
On which PF version did you noticed that bug ? I would like to reproduce.

**Comment by ZdenekPala** [comment]
Hi Nicolas.

It is not related to any PF version. The bug is in the documentation = on the packetfence web site!.

**Comment by ZdenekPala** [comment]
I believe the second example is also wrong as the word Secure should be also in quotes. it is also a value.

**Comment by nqb** [comment]
> I believe the second example is also wrong as the word Secure should be also in quotes. it is also a value.

Not sure. My coworkers will confirm but quotes are certainly needed because pattern contains special characters.

**Comment by jrouzierinverse** [comment]
Quotes are not needed for values if they contain a-z, A-Z, 0-9, '-', '_', '.', or ':'

**Comment by ZdenekPala** [comment]
ok, so maybe this was fixed in the latest release. This is my experience with A3 version 3.1.2:
![image](https://user-images.githubusercontent.com/16311452/85708613-a5e0e700-b6e4-11ea-89e3-b5195cc4cd30.png)

**Comment by ZdenekPala** [comment]
If the example in the documentation works in the latest version of the product then I am ok to close this ticket.
Thank you.

**Comment by nqb** [comment]
@ZdenekPala, we currently have an issue on latest version, see #5634

**Comment by nqb** [comment]
@ZdenekPala, could you tell us on which PacketFence version A3 3.1.2 is based ?

**Comment by jrouzierinverse** [comment]
In older versions of PacketFence we did not support '-' or ':' without quotes so that is most likely the issue here.

**Comment by ZdenekPala** [comment]
OK it makes sense. I will use quotes in my setup and once we upgrade to the new PF then we are good.

**Comment by ZdenekPala** [comment]
A3 3.1.2. is based on Packet Fence 9.0
