### ISSUE TITLE
Rules from authentication sources are not used after last patch

### ISSUE THREAD

**Issue by olmanolsztyn** [inverse-inc/packetfence#5637]
**Describe the bug**
After last pf-maint patching (today) devices are autoregistering from connection profile but rules from sources are not used.
**Screenshots**
![role_assign1](https://user-images.githubusercontent.com/22956491/85541071-f63e4300-b617-11ea-868c-7399c5a67ddf.png)
![role_assign2](https://user-images.githubusercontent.com/22956491/85541078-f8a09d00-b617-11ea-8bff-40fa216203ed.png)

**Comment by nqb** [comment]
Hello @olmanolsztyn,

1. Which patch was applied on your setup today (you should be able to see in `/usr/local/pf/.patches`) ?
2. Could you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) in order to replicate the issue ?

**Comment by olmanolsztyn** [comment]
1. `-rw-r--r--   1 root root  9458 Jun 24 09:54 ae52317961cf3f38aa0fc9f78b8d0594e9051eae-6c91a04915c95ea5bbff254fe3e42595a8b13cc9.diff
`
2. I just patched `/usr/local/pf/addons/pf-maint.pl` then `/usr/local/pf/bin/pfcmd configreload hard` and finally `/usr/local/pf/bin/pfcmd service pf restart`. Before patch worked fine.

How can i rollback one patch back? I could check if problem still exist after rollback?

**Comment by nqb** [comment]
1. Could you paste .diff file somewhere ?
2. I mean a MCVE to replicate this issue.

**Comment by olmanolsztyn** [comment]
1. https://213.184.0.143/own/index.php/s/GSnH0qg1SQIFfCi
2. Example that you could check with local user:
- Create role `worker `
- Create realm `domain.com` with `realm options` `ignore_null = yes
nostrip`
- Create user `test@domain.com` with role `worker` and `access duration` 1 day in default tenant
- Create Exclusive authentication eduroam source with local realm `domain.com`
- Create Portal `Login` module with authentication source `local` and assign to created root module `auth_root`
- Create connection profile `eduroam` and choose `Root Portal Module "auth_root"` then set `Automatically register devices` `Automatically deregister devices on accounting stop` with filters `all` matching `SSID` `eduroam` and `Connection Type` `Wireless-802.11-EAP` the save.
This is example and i hope i didn't miss any step.
In addition this is cluster environment.

**Comment by olmanolsztyn** [comment]
I don't know if this is the problem related log but i got in audit log:
![failed_retrieving](https://user-images.githubusercontent.com/22956491/85721078-5228ca80-b6f1-11ea-8d86-89126ec6b33f.png)

**Comment by olmanolsztyn** [comment]
Now i see is just radius authenticating but dont use rules from authentication source and devices are not registering.
When i checked authentication using `pftest` then rules are not matching when use `radius_request.username`.
When i change to `username` rules are matching but still are not affected.

**Comment by olmanolsztyn** [comment]
I solved issue. Problem was with my realms that i moved to global tenant (id 0) to configure from gui.
