### ISSUE TITLE
EAP-TLS / PKI: Unreg node w & w/o role

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#564]
Unknown end-point (never connected to PacketFence) need to be unreg and have a role in order to enter the certificate generation flow. We shouldn't have to put a role before...

**Comment by extrafu** [comment]
This is indeed stupid.

When the users authenticates, we should set the role but leave it to unreg and then, we present the EAP-TLS pages.

**Comment by dwlfrth** [comment]
@jrouzierinverse please advise on when it is solved (#520)
