### ISSUE TITLE
EAP-MS-CAPv2 is not working for VPN

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#5640]
When I try to use Packetfence for IKEv2 VPN radius server I am getting this:
<img width="1188" alt="Screen Shot 2020-06-25 at 15 21 45" src="https://user-images.githubusercontent.com/17347347/85719913-92d81200-b6f8-11ea-92d4-5d841b164d98.png">
<img width="1247" alt="Screen Shot 2020-06-25 at 15 23 38" src="https://user-images.githubusercontent.com/17347347/85720024-b0a57700-b6f8-11ea-8063-7ddfa97b1281.png">

**Comment by julsemaan** [comment]
Please use the mailing list for configuration related questions

**Comment by lyubomirtraykov** [comment]
This is not a configuration issue. As you can see the error is:
`mschap: Program returned code (1) and output 'Reading winbind reply failed! (0xc0000001)'`

**Comment by fdurand** [comment]
it's a configuration issue. Use the mailling list.
