### ISSUE TITLE
GTC freeradius module not loading after upgrade

### ISSUE THREAD

**Issue by janegilv** [inverse-inc/packetfence#5644]
GTC freeradius module not loading after upgrading from 10.0 to 10.1.

**Comment by fdurand** [comment]
Hello janegilv, thanks for the fix but it looks that you want to merge in your own devel branch, not in the inverse-inc/packetfence one.

**Comment by janegilv** [comment]
> Hello janegilv, thanks for the fix but it looks that you want to merge in your own devel branch, not in the inverse-inc/packetfence one.

I thought it was a bit weird that I did not have to agree to the license, and also had the ability to merge the pull-request myself -.-
Trying again
