### ISSUE TITLE
GUI issue when editing the switch with advance mode disabled

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5648]
**Describe the bug**
Configuration -> Policies and Access Control-> Network Devices -> Switches -> chose switch -> select CLI and stay with "Advanced off" = you will see SNMP settings instead of CLI settings. The content is shifted compare to the menu. SNMP menu and Web Services menu are also affected.

If I Enable "Advanced" then it works properly.

**To Reproduce**
Create Switch Group, device type "ExtremeNet: Summit Series", define roles, Radius, SNMP, CLI.
Create Switch and assign it to the group, define only the IP and description. Do not modify the Type. When the new switch is saved the type is copied from the Switch Group, but the menu at the top is broken for that switch.

**Screenshots**
![image](https://user-images.githubusercontent.com/16311452/86045680-38b6b400-ba4c-11ea-8c9d-87fa3a059c74.png)
![image](https://user-images.githubusercontent.com/16311452/86045713-45d3a300-ba4c-11ea-93a1-b03aec511be5.png)

**Expected behavior**
the operator can configure SNMP under the SNMP menu...

**Additional context**
The workaround is to define the Switch Type properly for the switch.

**Comment by ZdenekPala** [comment]
Packetfence Version
10.1.0

**Comment by julsemaan** [comment]
We would need either @cgx or @satkunas to check it out

**Comment by ZdenekPala** [comment]
@julsemaan I can share access to the system if it helps. Let me know.

**Comment by julsemaan** [comment]
It looks fairly simple to replicate on our end but I'll definitely reach out if we can't figure it out

**Comment by satkunas** [comment]
I'm not able to reproduce. @ZdenekPala can you forward me your conf/switches.conf (remove any sensitive information) - or email it to me at support@inverse.ca

**Comment by ZdenekPala** [comment]
Here is the file. no modification done. I just downloaded it through scp.
[switches.conf.zip](https://github.com/inverse-inc/packetfence/files/4865429/switches.conf.zip)
the 180 works fine
the 181 has gui issue

**Comment by julsemaan** [comment]
It seems 181 doesn't have a type explicitely defined but it inherits the Generic type from the default section so it should be fine but for some reason the GUI doesn't seem to realize there is a type when its the inherited default "Generic" type

No idea how to fix it in the GUI though, I'll let @satkunas do his magic

**Comment by ZdenekPala** [comment]
IMHO the 181 should inherit the type and all other settings from the group.

**Comment by julsemaan** [comment]
> IMHO the 181 should inherit the type and all other settings from the group.

It already does but the frontend seems to be unaware of it for the type
