### ISSUE TITLE
GUI issue - Search filter is persistent but not displayed when navigating out and back

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5649]
**Describe the bug**
The search filter is active when returning, but the search criteria are not displayed/indicated.

**To Reproduce**
In the top menu select Nodes
In the left menu select Search
In to the "Search by MAC or owner" type your criteria (e.g. c8)
hit Search button
now the list contains only nodes matching the criteria and the criteria are displayed = perfect
Now navigate to Users
Return to Nodes
The list of nodes is still filtered based on the criteria, but the criteria are not displayed. This is confusing.

**Screenshots**
Correct:
![image](https://user-images.githubusercontent.com/16311452/86059256-a968cb00-ba62-11ea-82aa-a2ace9d2d322.png)
Incorrect:
![image](https://user-images.githubusercontent.com/16311452/86059298-c3a2a900-ba62-11ea-810a-7c6783a82604.png)
After click the Clear button the invisible filter/search is removed:
![image](https://user-images.githubusercontent.com/16311452/86059348-dc12c380-ba62-11ea-9907-6bdeeb312f19.png)

**Expected behavior**
if the search is applied then the search criteria should be visible.

**Additional context**
PF version 10.1
The same applies to Security Events.
The same applies to Users

**Comment by satkunas** [comment]
@ZdenekPala this issue has been resolved with https://github.com/inverse-inc/packetfence/pull/6127

Searches - either basic or advanced - now persist both across page reloads and user sessions.
