### ISSUE TITLE
The Role is not displayed if the Filter does both AutoRegister and RegisteredRole

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5650]
**Describe the bug**
The Role is not displayed if both AutoRegister and RegisteredRole are used in the Vlan Filter

**To Reproduce**
1. Define Vlan Filter (/usr/local/pf/conf/vlan_filters.conf):

> [My Printers]
> run_actions=disabled
> status=enabled
> top_op=and
> description=Autoregister my printers
> scopes=AutoRegister,RegisteredRole
> role=printer
> condition=starts_with(mac, "00:1e:06")

2. Connect the device to the switch, the switch gets proper radius response 
3. Nodes - Search -> does not display the role

**Screenshots**
The Filter definition:
![image](https://user-images.githubusercontent.com/16311452/86061701-87be1280-ba67-11ea-9321-1c309798b714.png)
The Role is not displayed, the VLAN is displayed correctly:
![image](https://user-images.githubusercontent.com/16311452/86061752-a15f5a00-ba67-11ea-9ddc-7d5a7cfaa6d5.png)
![image](https://user-images.githubusercontent.com/16311452/86061842-c81d9080-ba67-11ea-81c2-0d596f10d2d6.png)

**Expected behavior**
The role should be displayed.

**Additional context**
PF version 10.1.0

**Comment by fdurand** [comment]
It's not really a bug since it's the expected behaviour.
If you want to set the role then add an action (Perform action).

**Comment by julsemaan** [comment]
@ZdenekPala 

If you put the scope NodeInfoForAutoReg that should do what you expect

**Comment by ZdenekPala** [comment]
Thank you Julien. It works as expected now.
