### ISSUE TITLE
VLAN filter action modify role can crash the system

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5652]
**Describe the bug**
I configured the VLAN filter as on the screen. When the device appears in the network and this rule trigger then the product is crashed. Reboot does not help.

**To Reproduce**
Create filter with action Update Role Configuration, as a value add: role, $role

**Screenshots**
![image](https://user-images.githubusercontent.com/16311452/86149125-d5845a80-bafb-11ea-9b37-bd8d06fa032f.png)

**Expected behavior**
it will not crash the system

**Additional context**
Actually, the $role variable isn't initialized which ends up creating an empty role (the action modifies the config itself).
if you want to get back online, edit /usr/local/pf/conf/roles.conf and try to find an empty section `[]`, remove it and do `/usr/local/pf/bin/pfcmd configreload hard`

**Comment by julsemaan** [comment]
This has been addressed in 790ddb7 with an additional safety net in f45d842

Its been cherry-picked into the maintenance, if you run `/usr/local/pf/addons/pf-maint.pl` you'll get the fix
