### ISSUE TITLE
Connection profile SSID filter should be case sensitive

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5663]
**Describe the bug**

In a connection profile if you try to set 2 SSID filter , like one with BOB and the other one with BoB then it's not possible to add the second one.

**Comment by julsemaan** [comment]
Hope its not butter in my eyes this time but the fix seems to be related to the identifier of the connection profile while the issue is for the SSID condition

**Comment by julsemaan** [comment]
Checked with @satkunas and this time my eyes were butter free

**Comment by satkunas** [comment]
@fdurand I'm not able to reproduce

![Screenshot_20200918_152345](https://user-images.githubusercontent.com/3904468/93637096-040b2680-f9c3-11ea-901c-5c10c0f69e27.png)

I'll revert the earlier commit

**Comment by fdurand** [comment]
To be more precise the SSID bob already exist (because a connection with this ssid has been made, so it appear in the list) and i want to add BOB and it's not possible.

**Comment by satkunas** [comment]
@fdurand this appears to be a limitation in the element when both internal-search and taggable are both enabled:

https://github.com/vabene1111/recipes/issues/170#issuecomment-684738576

We won't be able to get around this issue until a new select component is used.

Bumping the milestone to a later release to re-examine.

**Comment by satkunas** [comment]
@fdurand this fix won't be achievable in 10.3 Bumping milestone to revisit.
