### ISSUE TITLE
Can't rename a cloned vlan filter

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5664]
Title says it all.

**Comment by julsemaan** [comment]
@satkunas can you take a look at this, its impossible to rename any cloned filters so that makes it a pain to redo the whole config for filters that are alike

**Comment by satkunas** [comment]
`id` is missing from the meta payload. Fields are determined from meta, thus the `id` is not shown.

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/vlan_filter/pf_deauth_from_wireless_secure | jq '.meta.id'
null
```

**Comment by jrouzierinverse** [comment]
The meta for ```id``` is on the collection not the resource.
This is how all OPTIONS calls work.
It only shows the meta for ```id``` on the collection and not the resources.
This was the behavior since v9.0.0
```bash
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/vlan_filters | jq .meta.id
{
  "default": null,
  "placeholder": null,
  "required": true,
  "type": "string"
}
```

**Comment by julsemaan** [comment]
The milestone is a +1, please cherry-pick this in the maintenance

**Comment by julsemaan** [comment]
@satkunas, can you cherry-pick this in the maintenance or a 10.2 compatible fix ? I need this fix for a customer

**Comment by satkunas** [comment]
@julsemaan back ported to 10.1 and 10.2.
