### ISSUE TITLE
eap login issue sub module failed version 10.1.0

### ISSUE THREAD

**Issue by sonaligulia** [inverse-inc/packetfence#5665]
In current version 10.1.0 update there is an error in eap login  .
in eap.conf (/usr/local/pf/conf/radiusd/eap.conf) file GTC is not mentioned in else if loop . infact leap is mentioned 2 times  . i am attaching screenshot of error . after editing my config file its working fine now 

error screenshot:
![eap error](https://user-images.githubusercontent.com/33476142/86584300-529f4c00-bfa2-11ea-9428-787a89607068.png)

error resolve screenshot
![eap error resolve](https://user-images.githubusercontent.com/33476142/86584459-8da17f80-bfa2-11ea-80de-4c717733c4f4.png)

thank you

**Comment by nqb** [comment]
Hi @sonaligulia,

Thanks for your bug report. 

It has been already fixed by @janegilv in 1b2556b23ae34651c42635294a95121783bcf0c2 commit.

Fix will be available in next release.
