### ISSUE TITLE
web admin: missing RADIUS tab on switches/switch groups

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5666]
**Describe the bug**
When you try to create a new switch or switch group, all tabs are present except `RADIUS`. On switches, it seems to work when I toggle Advanced button.

**To Reproduce**
1. Create a new switch group 

=> RADIUS tab is missing

![Capture d’écran de 2020-07-06 15-52-47](https://user-images.githubusercontent.com/10830260/86600801-d5bfa280-bfa0-11ea-93d8-d5037bb12f61.png)

**Expected behavior**
RADIUS tab should be display by default when creating new switch or switch group.

**Comment by lzammit** [comment]
It's because of the generic module ? What happen if you switch to Cisco 2960 ?

**Comment by nqb** [comment]
Good catch @lzammit !

If I switch to Cisco 2960 module when creating a switch group, RADIUS tab appears.
