### ISSUE TITLE
haproxy-admin unable to start in a cluster in a RADIUS enforcement scenario

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5667]
**Describe the bug**
If you set up a cluster with only management interface (without portal daemon), `haproxy-admin` service is unable to start because `/usr/local/pf/var/conf/haproxy-admin.conf` as a syntax issue. The [portal_preview_ip function](https://github.com/inverse-inc/packetfence/blob/c74f0839a95387eea9339efe7ede600ab7bea5b5/lib/pf/services/manager/haproxy_admin.pm#L275) returns an undef value. Consequently, the [http-request set-header](https://github.com/inverse-inc/packetfence/blob/c74f0839a95387eea9339efe7ede600ab7bea5b5/lib/pf/services/manager/haproxy_admin.pm#L230) as an empty argument.

**To Reproduce**
1. Install a cluster running 10.1.0 with only a management interface
2. Try to start services

=> Web admin is unreachable.

**Expected behavior**
Web admin should start.

**Workaround**
Set your management interface as portal.

**Comment by sonaligulia** [comment]
> 
> 
> **Describe the bug**
> If you set up a cluster with only management interface (without portal deamon), `haproxy-admin` service is unable to start because `/usr/local/pf/var/conf/haproxy-admin.conf` as a syntax issue. The [portal_preview_ip function](https://github.com/inverse-inc/packetfence/blob/c74f0839a95387eea9339efe7ede600ab7bea5b5/lib/pf/services/manager/haproxy_admin.pm#L275) returns an undef value. Consequently, the [http-request set-header](https://github.com/inverse-inc/packetfence/blob/c74f0839a95387eea9339efe7ede600ab7bea5b5/lib/pf/services/manager/haproxy_admin.pm#L230) as an empty argument.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Install a cluster running 10.1.0 without only a management interface
> 
>     2. Try to start services
> 
> 
> => Web admin is unreachable.
> 
> **Expected behavior**
> Web admin should start.
> 
> **Workaround**
> Set your management interface as portal.

unable to start packetfence-haproxy-admin service even after setting managment interface as portal
