### ISSUE TITLE
Admin interface only shows the 100 oldest security events

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5668]
**Describe the bug**
The security events tab of a node only shows the 100 oldest security events associated to the node.

**To Reproduce**
1. Have a node that has more than 100 security events
2. Try to view them in the admin in the nodes details

**Expected behavior**
The limit itself isn't a problem but it should show the most recent ones

**Comment by satkunas** [comment]
@julsemaan https://github.com/inverse-inc/packetfence/commit/abd335c7f16c3aaa1a7952f7c43ee55b92c3abbf increase the limit from 100 to 1000 and attempts to sort by start_date desc.

@jrouzierinverse `POST /api/v1/security_events/search` accepts `sortBy`, but ignores `sortDesc`. Descending sort is required.

**Comment by jrouzierinverse** [comment]
Have you tried this?

```json
{
      "query": { "op": "and", "values": [ { "field": "mac", "op": "equals", "value": "00:11:22:33:44:55" } ] },
      "limit": 1000,
      "cursor": "0",
      "sort": ["start_time DESC"]
}
```

**Comment by jrouzierinverse** [comment]
@cgx or @satkunas have you tried changing the query to this?
```
{
      "query": { "op": "and", "values": [ { "field": "mac", "op": "equals", "value": "00:11:22:33:44:55" } ] },
      "limit": 1000,
      "cursor": "0",
      "sort": ["start_time DESC"]
}
```
