### ISSUE TITLE
pfcmd fixpermissions all : conf/ssl is ignored.

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#5669]
**Describe the bug**
pfcmd fixpermissions 
pfcmd fixpermissions all

Neither will fix permissions to SSL certs in $CONF/SSL.

**To Reproduce**
1. Change permissions on any file underneath $CONF/SL
2. run pfcmd fixpermissions
3. ls -l ... permissions are NOT fixed.

**Expected behavior**
fixpermissions claims to walk the ~~entire~~ pf tree... conf/ssl directory is ignored.

**Comment by julsemaan** [comment]
Its indeed something we could improve.

I checked the help though and it doesn't claim it walks `the entire pf tree`, it says `the pf tree`

Can you point me to where it says `the entire pf tree`, we need to fix this as we'll never be able to get fixpermissions to fix the permissions of all the files under `/usr/local/pf`

**Comment by rcmcdonald91** [comment]
> Its indeed something we could improve.
> 
> I checked the help though and it doesn't claim it walks `the entire pf tree`, it says `the pf tree`
> 
> Can you point me to where it says `the entire pf tree`, we need to fix this as we'll never be able to get fixpermissions to fix the permissions of all the files under `/usr/local/pf`

Eh, I might have been really tired and a bit cross-eyed when I read that. It probably doesn't make that claim. Disregard.
