### ISSUE TITLE
iptables fails to start (again)

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#5670]
**Resolution:** If running in UEFI mode, keep secure boot DISABLED.

REF: #5290 

**Describe the bug**
I'm seeing #5290 again on a fully patched CentOS 7 cluster running 10.1.0

Ran this prior to installing PF

`yum install kernel-devel-$(uname -r)`

`[root@pf1 ~]# uname -a
Linux pf1.ad.mydomain.com 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

> [root@pf1 ~]# systemctl status packetfence-iptables -l
> ● packetfence-iptables.service - PacketFence Iptables configuration
>    Loaded: loaded (/usr/lib/systemd/system/packetfence-iptables.service; enabled; vendor preset: disabled)
>    Active: active (running) since Tue 2020-07-07 21:06:38 EDT; 2min 40s ago
>  Main PID: 2482 (perl)
>    CGroup: /packetfence.slice/packetfence-iptables.service
>            └─2482 /bin/perl -I/usr/local/pf/lib -Mpf::db -Mpf::services::manager::iptables -e my $db ; while(!$db) { eval { $db = db_connect() } ; sleep 1 } ; pf::services::manager::iptables->new()->startAndCheck()
> 
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3742]: pam_systemd(sudo:session): Failed to create session: Unit is masked.
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3742]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3745]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ipset --add pfsession_passthrough 172.217.13.99,443
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3745]: pam_systemd(sudo:session): Failed to create session: Unit is masked.
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3745]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 07 21:08:49 pf1.ad.mydomain.com sudo[3745]: pam_unix(sudo:session): session closed for user root
> Jul 07 21:08:49 pf1.ad.mydomain.com packetfence[2482]: -e(2482) INFO: Adding NAT Masquerade statement. (pf::iptables::generate_passthrough_rules)
> Jul 07 21:08:49 pf1.ad.mydomain.com packetfence[2482]: -e(2482) INFO: restoring iptables from /usr/local/pf/var/conf/iptables.conf (pf::iptables::iptables_restore)
> Jul 07 21:08:49 pf1.ad.mydomain.com perl[2482]: iptables-restore: line 205 failed
> Jul 07 21:08:49 pf1.ad.mydomain.com packetfence[2482]: -e(2482) WARN: Problem trying to run command: LANG=C /sbin/iptables-restore < /usr/local/pf/var/conf/iptables.conf called from iptables_restore. Child exited with non-zero value 1 (pf::util::pf_run)

**Comment by fdurand** [comment]
Can you check if the module is loaded ?

```
lsmod | grep ipt_NETFLOW
```

And can you do (and paste the result):

```
cat /var/log/messages|grep -i netflow
```

**Comment by nqb** [comment]
I'm not able to replicate this issue on a standalone running in 10.1.0.

Process we used to always run latest Linux kernel packages:
1. Upgrade CentOS to latest version (to have latest kernel installed)
1. Reboot system (to use latest kernel)
1. Run `yum install kernel-devel-$(uname -r)`
1. Install PacketFence

@theonemcdonald, could you confirm you have follow this exact process ?

My guess is that you have install latest CentOS release (7.8) and run all steps mentioned below except the second.

**Comment by rcmcdonald91** [comment]
Edit: This seems to be a Secure Boot UEFI issue. Investigating now. 

@fdurand 

`lsmod | grep ipt_NETFLOW` doesn't return anything...module is NOT loaded.

> [root@pf1 /]# cat /var/log/messages | grep -i netflow
> Jul  6 18:03:18 localhost yum[13550]: Installed: dkms-ipt-netflow-2.4-4.1.noarch
> Jul  6 18:03:18 localhost yum[13550]: Installed: ipt-netflow-2.4-4.1.x86_64
> Jul  6 18:05:21 localhost systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 13:14:41 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 13:59:35 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 15:24:03 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 16:03:41 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 16:03:48 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 16:19:35 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 18:19:50 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 18:19:57 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 20:07:46 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 20:17:05 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 20:40:29 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 21:04:18 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 21:06:08 pf1 systemd-modules-load: Failed to insert 'ipt_NETFLOW': Required key not available
> Jul  7 21:07:28 pf1 yum[3161]: Installed: dkms-ipt-netflow-2.4-4.1.noarch

@nqb I'm pretty sure I followed the process you described. 

When I reinstall the package `yum reinstall dkms-ipt-netflow --enablerepo=packetfence` everything works fine, indicating that the correct kernel headers are present?

> [root@pf1 /]# yum reinstall dkms-ipt-netflow --enablerepo=packetfence
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: repo.miserver.it.umich.edu
>  * extras: mirrors.rit.edu
>  * updates: packages.oit.ncsu.edu
> base                                                                                                                                                                                    | 3.6 kB  00:00:00
> extras                                                                                                                                                                                  | 2.9 kB  00:00:00
> packetfence                                                                                                                                                                             |  951 B  00:00:00
> updates                                                                                                                                                                                 | 2.9 kB  00:00:00
> Resolving Dependencies
> --> Running transaction check
> ---> Package dkms-ipt-netflow.noarch 0:2.4-4.1 will be reinstalled
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ===============================================================================================================================================================================================================
>  Package                                                 Arch                                          Version                                        Repository                                          Size
> ===============================================================================================================================================================================================================
> Reinstalling:
>  dkms-ipt-netflow                                        noarch                                        2.4-4.1                                        packetfence                                         58 k
> 
> Transaction Summary
> ===============================================================================================================================================================================================================
> Reinstall  1 Package
> 
> Total download size: 58 k
> Installed size: 212 k
> Is this ok [y/d/N]: y
> Downloading packages:
> dkms-ipt-netflow-2.4-4.1.noarch.rpm                                                                                                                                                     |  58 kB  00:00:00
> Running transaction check
> Running transaction test
> Transaction test succeeded
> Running transaction
>   Installing : dkms-ipt-netflow-2.4-4.1.noarch                                                                                                                                                             1/1
> Error! DKMS tree already contains: ipt-netflow-2.4-4.1
> You cannot add the same module/version combo more than once.
> Module ipt-netflow/2.4-4.1 already built for kernel 3.10.0-1127.13.1.el7.x86_64/4
> Module ipt-netflow/2.4-4.1 already installed on kernel 3.10.0-1127.13.1.el7.x86_64/x86_64
>   Verifying  : dkms-ipt-netflow-2.4-4.1.noarch                                                                                                                                                             1/1
> 
> Installed:
>   dkms-ipt-netflow.noarch 0:2.4-4.1
> 
> Complete!

**Comment by rcmcdonald91** [comment]
Here is make.log for netflow

`DKMS make.log for ipt-netflow-2.4-4.1 for kernel 3.10.0-1127.13.1.el7.x86_64 (x86_64)
Mon Jul  6 18:01:52 EDT 2020
./gen_compat_def > compat_def.h
Compiling for kernel 3.10.0-1127.13.1.el7.x86_64
make -C /lib/modules/3.10.0-1127.13.1.el7.x86_64/build M=/var/lib/dkms/ipt-netflow/2.4-4.1/build modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/3.10.0-1127.13.1.el7.x86_64'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  CC [M]  /var/lib/dkms/ipt-netflow/2.4-4.1/build/ipt_NETFLOW.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/ipt-netflow/2.4-4.1/build/ipt_NETFLOW.mod.o
  LD [M]  /var/lib/dkms/ipt-netflow/2.4-4.1/build/ipt_NETFLOW.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-1127.13.1.el7.x86_64'`
