### ISSUE TITLE
Radius auth with host - Reply-Message = "no role computed by any sources"

### ISSUE THREAD

**Issue by danielerosatidast** [inverse-inc/packetfence#5672]
After upgrading from 9.3.0 to 10.1.0 the radius authentication with host objects is not working anymore.
I get the error: Reply-Message = "no role computed by any sources"

Any source, domain, connection profile, switch was changed after the upgrade.

Local machines do ask for credentials instead of sending their host domain\hostname

Connection profile: if connection is wireless eap - use AD_local machine source (where i get green test)
Rule are same as before, if computer object is in that group, give this role

**Comment by julsemaan** [comment]
This looks like a configuration issue, not a bug, please use the mailing list

**Comment by dmiyyy** [comment]
I have the same issue

**Comment by danielerosatidast** [comment]
I resolved the issue, after upgrading, giving the correct grants on radius file. Somehow in upgrade procedure grant side something broke.

Da: dmiyyy <notifications@github.com>
Inviato: giovedì 23 luglio 2020 15:13
A: inverse-inc/packetfence <packetfence@noreply.github.com>
Cc: Daniele Rosati <daniele.rosati@dastech.biz>; Author <author@noreply.github.com>
Oggetto: Re: [inverse-inc/packetfence] Radius auth with host - Reply-Message = "no role computed by any sources" (#5672)


I have the same issue
