### ISSUE TITLE
pfdhcp lists disabled servers in DHCP response

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5677]
**Describe the bug**
The DHCP server lists disabled servers in the DNS and gateways that are sent in its DHCP replies.
It needs to honor the disabled servers in the following places:
https://github.com/inverse-inc/packetfence/blob/6315486b1e83cd74b0e67aeb35435d2748d894b2/go/dhcp/utils.go#L193
https://github.com/inverse-inc/packetfence/blob/6315486b1e83cd74b0e67aeb35435d2748d894b2/go/dhcp/utils.go#L207

**To Reproduce**
1. Disable a server in a cluster
2. Restart pfdhcp
3. Server still in the list

**Expected behavior**
Disabled servers shouldn't be in the DNS or gateways for clients

**Comment by fdurand** [comment]
it can probably be done in resource::network_config directly.

**Comment by fdurand** [comment]
No, it must be done in the dhcp code.

**Comment by julsemaan** [comment]
> No, it must be done in the dhcp code.

Exactly, because there may not be a configreload hard after disabling a node and it may still be sharing config with another cluster member through its DB storage

**Comment by julsemaan** [comment]
Reopening to cherry-pick in the maintenance once 10.2 is released

**Comment by fdurand** [comment]
Pushed in maintenance
