### ISSUE TITLE
Optimizations on switches endpoints for better user experience on web admin

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5678]
**Is your feature request related to a problem? Please describe.**
When you deal with an important number of switches (< 300 and more), API takes really long time to give answer to frontend which result in:
* bad user experience on webadmin when you have to manage switches (a common task of PacketFence admins)
* 504 gateway timeout errors

As mentioned on #5550, it's possible to increase server timeout to avoid HTTP errors but we will not improve user experience.

**Describe the solution you'd like**
Optimize switches endpoints to have a better answering time.

**Describe alternatives you've considered**
Implement pagination on frontend.

**Comment by nqb** [comment]
@jrouzierinverse and @satkunas, could you mention here commits you pushed to improve performances ?

Also could you tell me if issue should be consider as fixed ?

Thanks

**Comment by jrouzierinverse** [comment]
There is a bit more to be done on my side.
Such as add some optimizations to the simple cases.
The next optimization I am working on is where no filter or sorting is needed.

**Comment by jrouzierinverse** [comment]
This has been fixed by c6cadf1fddb981f479b2dcd3b2d95203877d3214, 15d4c9553bc5d96187b2fddff6d64e1cb665d7c9, and 4bfa80a330049c550b59cce21ca99babad3e59d6
