### ISSUE TITLE
192.0.2.1 IP address may be used by another system

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5679]
**Describe the bug**
I just got a case where that IP was active on a network equipment that was between PF and the endpoint. It was intercepting traffic and preventing users from being on the portal.

**To Reproduce**
1. Put 192.0.2.1 on another equipment than PF that is directly connected to the endpoint (like on the WLC directly)
2. Try to use the reg VLAN

**Expected behavior**

I suggest one of the following:
 1. We buy a public IP address for the exclusive usage of this mechanism (will cost a few bucks a month)
 1. We allow the IP to be changed via configuration so that we can pick something that doesn't cause a problem if we hit similar cases

For now I've worked around by replacing the IP with another one in the code but that won't survive the maintenance (change in pfdns)

**Comment by extrafu** [comment]
I think we need to do both.

**Comment by julsemaan** [comment]
> I think we need to do both.

Agreed, that way we're sure we have a way around any potential issue

**Comment by julsemaan** [comment]
#5682 has been applied in maintenance/10.0 and maintenance/10.1
