### ISSUE TITLE
Move addons/packages/ to rh

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#568]

**Comment by extrafu** [comment]
I suggest doing what SOGo does (at root source level):

# find packaging/ -type d

packaging/
packaging/rhel
packaging/debian
packaging/debian/source
packaging/debian-multiarch
packaging/debian-multiarch/source

Debian vs. Debian-multiarch might not be needed for PacketFence.

**Comment by dwlfrth** [comment]
I second @extrafu suggestion...

**Comment by julsemaan** [comment]
It has @nqb written on it
