### ISSUE TITLE
High Availability listed as an 'additional listening daemon' when editing interface.

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#5680]
**Describe the bug**
After initially configuring HA on an interface using the checkbox, HA becomes an 'additional listening daemon' and the checkbox is not ticked.

**To Reproduce**
1. Configure an interface with HA by checking the checkbox.
2. Save the interface.
3. Edit the interface
4. Save the interface.

**Screenshots**
![habug](https://user-images.githubusercontent.com/3102039/87060645-c6c33500-c1d8-11ea-92b3-3cbdf4d533bb.PNG)
![habug2](https://user-images.githubusercontent.com/3102039/87061149-654f9600-c1d9-11ea-894b-522ca7330f94.PNG)

**Expected behavior**
HA checkbox should be checked if interface is configured for HA.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nqb** [comment]
Closing in favor of #5963
