### ISSUE TITLE
Domain Join Not Surviving Reboot "Cannot open network namespace "AD": No such file or directory"

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#5681]
**Describe the bug**
10.1.0 fully patched via ./pf-maint.pl as of 7/9/2020 (2:21PM EST)

Domain join not surviving reboot on 3 node 10.1.0 cluster (patched via ./pf-maint.pl as of 7/9/2020, 2:22pm)

"Cannot open network namespace "AD": No such file or directory" in test join.

**To Reproduce**
1. build up a cluster using the clustering guide.
2. Join each cluster to the domain
3. reboot each node one by one
4. node comes back online without being domain joined and winbindd isn't running.

**Screenshots**
![adbug](https://user-images.githubusercontent.com/3102039/87076535-e87be680-c1ef-11ea-85cd-fa188b443483.PNG)

**Expected behavior**
Nodes should stay domain joined and winbindd should be running.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

winbindd not running and disabled after rebooting.

```
[root@pf01 ~]# systemctl status packetfence-winbindd
● packetfence-winbindd.service - PacketFence SAMBA winbind Service
   Loaded: loaded (/usr/lib/systemd/system/packetfence-winbindd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

If I run 'systemctl start packetfence-winbindd' and then 'systemctl status packetfence-winbindd -l' again:

```
[root@pf01 ~]# systemctl status packetfence-winbindd -l
● packetfence-winbindd.service - PacketFence SAMBA winbind Service
   Loaded: loaded (/usr/lib/systemd/system/packetfence-winbindd.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-07-09 14:27:37 EDT; 1min 0s ago
  Process: 3994 ExecStartPre=/usr/local/pf/bin/pfcmd service winbindd generateconfig (code=exited, status=0/SUCCESS)
 Main PID: 4356 (winbindd-wrappe)
   Status: "Ready"
   CGroup: /packetfence.slice/packetfence-winbindd.service
           ├─4356 winbindd-wrappe
           ├─4368 /usr/sbin/winbindd -s /etc/samba/AD.conf -l /var/log/sambaAD --foreground
           └─4370 /usr/sbin/winbindd -s /etc/samba/AD.conf -l /var/log/sambaAD --foreground

Jul 09 14:27:34 pf01.ad.mydomain.com sudo[4352]: pam_unix(sudo:session): session closed for user root
Jul 09 14:27:34 pf01.ad.mydomain.com sudo[4354]: pam_systemd(sudo:session): Failed to create session: Unit is masked.
Jul 09 14:27:34 pf01.ad.mydomain.com sudo[4354]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 09 14:27:34 pf01.ad.mydomain.com sudo[4354]: pam_unix(sudo:session): session closed for user root
Jul 09 14:27:34 pf01.ad.mydomain.com pfcmd[3994]: winbindd|config generated
Jul 09 14:27:37 pf01.ad.mydomain.com systemd[1]: Started PacketFence SAMBA winbind Service.
Jul 09 14:27:37 pf01.ad.mydomain.com winbindd[4368]: [2020/07/09 18:27:37.809171,  0] ../../source3/winbindd/winbindd_cache.c:3166(initialize_winbindd_cache)
Jul 09 14:27:37 pf01.ad.mydomain.com winbindd[4368]:   initialize_winbindd_cache: clearing cache and re-creating with version number 2
Jul 09 14:27:37 pf01.ad.mydomain.com winbindd[4368]: [2020/07/09 18:27:37.811248,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
Jul 09 14:27:37 pf01.ad.mydomain.com winbindd[4368]:   daemon_ready: daemon 'winbindd' finished starting up and ready to serve connections
```

**Workaround**

Manually enable packetfence-winbindd after joining and prior to rebooting.

`systemctl enable packetfence-winbindd && shutdown -r now`

**Comment by julsemaan** [comment]
Are you using `%h` as the hostname value in your domain configuration ?

**Comment by rcmcdonald91** [comment]
Yes

**Comment by julsemaan** [comment]
Perhaps then we need to do: `pfcmd service pf updatesystemd` after creating a domain to ensure that it will be properly enabled

**Comment by julsemaan** [comment]
It was indeed the fact that the systemd configuration of winbindd isn't updated when manipulating domains

I've made it so whenever we generate the configuration of domains, it will adjust this

The fix is in the maintenance if you need it (apply via `/usr/local/pf/addons/pf-maint.pl`)

**Comment by dariuskoissi** [comment]
Hello when i jointed l'AD, i receive the next error :  jointed AD error mount  :/sys/ permission denied
