### ISSUE TITLE
fingerbank-collector: "Invalid MAC address provided" 

### ISSUE THREAD

**Issue by aleixdorca** [inverse-inc/packetfence#5685]
**Describe the bug**
If I enable and start the fingerbank-collector, the fingerbank.log is flooded (5-10 entries per second) with these two errors:

"Found IP/MAC (ip:192.0.2.1|mac:) on the local interface"
"Failed to update IP/MAC from local interface result. Error: Invalid MAC address provided"

It seems that this address is used by haproxy on the local (lo) interface by the captive portal.

Any way of solving this problem?

**Additional context**
This has happened since version 10.x, the latest (as of the moment of submitting this issue) 10.1 included.

**Comment by julsemaan** [comment]
What is the version of the fingerbank-collector package?
Are you running Debian or CentOS?

I have a good idea of a workaround fix for this but I just want to make sure I'm not missing something else

**Comment by aleixdorca** [comment]
fingerbank-collector: version 1.3.6-1 - amd64 (installed via apt from the deb http://inverse.ca/downloads/PacketFence/debian stretch repository)
OS version: Debian 9.12

**Comment by julsemaan** [comment]
This is addressed by the fingerbank-collector-1.3.7 which is pushed for CentOS.

I'll assigned it to @fdurand so that he can build the new collector for Debian

**Comment by fdurand** [comment]
New collector has been pushed in the debian repo.

**Comment by aleixdorca** [comment]
Updated to latest collector version (1.3.7-1) on Debian 9.12. All seems to work fine! Thanks!

**Comment by giacintocaretto** [comment]
same problem on :
OS centos 7
PF ver 10.1
fingerbank-collector 1.3.6

if i run
yum info  fingerbank-collector  --enablerepo=packetfence
I find that vesrion 1.3.8 is available

does this version solve the problem? 
 using only command 
yum update  fingerbank-collector  --enablerepo=packetfence

or using the sequence :

/usr/local/pf/bin/pfcmd service pf stop
sudo systemctl stop packetfence-config

yum update  fingerbank-collector  --enablerepo=packetfence

/usr/local/pf/bin/pfcmd fixpermissions
/usr/local/pf/bin/pfcmd pfconfig clear_backend
sudo systemctl restart packetfence-config
/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/pfcmd service pf restart

thank
