### ISSUE TITLE
The “switch port description ” on nodes page is not correct.

### ISSUE THREAD

**Issue by szhouhao** [inverse-inc/packetfence#5686]
The “switch port description ” on nodes page is not correct.
My switch  is the H3C-5120，It's port description is "slot=1;subslot=0;port=5;vlanid=1"，that isn't the correct description  on my swicth；
I can use a snmp command to catch the correct description,but it  cant  display the correct result   the packetfence.
Do  you have the correct port description on your switch? or other vendor's switches？

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
