### ISSUE TITLE
Unable to create switch group and access levels on devel

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5689]
**Describe the bug**
If I try to create switch group or access levels, I got a 500 error.

**To Reproduce**
1. Try to create a switch group or an access level

=> You got following errors:
```
Jul 14 06:48:21 pfcen7dev packetfence: pfperl-api(7218) ERROR: Not a HASH reference at /usr/local/pf/lib/pfappserver/Form/Config/AdminRoles.pm line 174.
Jul 14 06:48:23 pfcen7dev packetfence: pfperl-api(7218) ERROR: Not a HASH reference at /usr/local/pf/lib/pfappserver/Form/Config/Switch.pm line 549.
```

**Expected behavior**
It should work.

**Additional context**
I don't have this issue using build triggered by https://github.com/inverse-inc/packetfence/commit/ff4029317b40a2980f7a48c809f8e12e07a65560

**Comment by jrouzierinverse** [comment]
Fixed by 7c90ea4c2dccf6cf60b034c9de3711c2916c1adf
