### ISSUE TITLE
GUI: status/services/Manageable Services/[Start,Restart All] buttons have strange results

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#5698]
**Describe the bug**

Standalone server.

In the UI, at status/services/Manageable Services/ if you tried the button "Restart All", it will restart even disabled services.
Disabled services are running and still at "disabled" status.

In the UI, at status/services/Manageable Services/ if you tried the button "Start All", it will start some of disabled services, but not all of them.

**To Reproduce**
Example with galera-autofix and haproxy-db

These steps to reproduce the behavior:

For Restart All:
1. Go to status/services/Manageable Services
2. Check if galera-autofix and haproxy-db are disabled and not running (by default they should be disabled and not running)
(or you can stop them and disabled them)
3. Click on "Restart All"
4. galera-autofix and haproxy-db have started (have a PID and running on server) and are still disabled 

For Start All:
1. Go to status/services/Manageable Services
2. Check if fingerbank-collector is disabled and not running (by default it should be disabled and not running)
(or you can stop it and disabled it)
3. Click on "Start All"
4. galera-autofix has started and be enabled.
    haproxy-db has NOT started and is still disabled

**Expected behavior**
Only enabled services should have bee restarted, or all services need to be enabled and started.
But not a mix.

**Options**
Create buttons (stop start, restart) for only enabled services.
Buttons with "all" should also disabled/enabled services.

**Comment by julsemaan** [comment]
It seems the frontend calls the action on all the services individually, not only the enabled services.

@satkunas, can you ensure actions are taken only on the services that are enabled in that page
