### ISSUE TITLE
GUI: status/services/Manageable Services/[Stop All] button do not stop all services

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#5699]
**Describe the bug**
Standalone server.
In the UI, at status/services/Manageable Services/ if you tried the button "Stop All", it will only stop some services, but not all of them.

**To Reproduce**
1. Go to status/services/Manageable Services
2. Check if fingerbank-collector and httpd.aaa are enabled and running
3. Click on "Stop All"
4. fingerbank-collector and httpd.aaa are still enabled and running

Few other services do not stop.

**Expected behavior**
All services down.

**Comment by JeGoi** [comment]
Whoups I've just seen that there is section for Protected services (like system services).
I'll change my issue expected.

**Comment by julsemaan** [comment]
I was able to replicate on the latest devel.

The API calls that stop the services all succeeded and the frontend still shows them as started.

If I do a `pfcmd service pf status`, the services are actually stopped
