### ISSUE TITLE
GUI status/services/Manageable Services/[Protected Services] enabled option should be protected 

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#5700]
**Describe the bug**
Standalone server.
You can disabled Protected services and, if it is disabled and the server restart, the service will not restart.

**To Reproduce**
1. Go to status/services/Manageable Services
2. Click on haproxy-admin to disable it
3. Check the status service on the server
```
systemctl status packetfence-haproxy-admin -l
● packetfence-haproxy-admin.service - PacketFence HAProxy Load Balancer for the Admin GUI
   Loaded: loaded (/usr/lib/systemd/system/packetfence-haproxy-admin.service; disabled; vendor preset: disabled)
```
4. At restart, no more Admin GUI

**Expected behavior**
Protect the service to be disable like it has been made with running/stop.

**Comment by julsemaan** [comment]
Should be an easy one for @satkunas

**Comment by satkunas** [comment]
@JeGoi all fixed, thanks for the report.
