### ISSUE TITLE
AD Authentication

### ISSUE THREAD

**Issue by YLVNHAIQUACH** [inverse-inc/packetfence#5706]
Please help to fix this issue when using AD authentication.

[root@packetfence samba]# wbinfo -p
Ping to winbindd failed

MAC Address
a0:8c:fd:d5:a8:58
Auth Status
Reject
Auth Status
eap
Auto Registration
No
Calling Station Identifier
a0:8c:fd:d5:a8:58
Computer Name
N/A
EAP Type
MSCHAPv2
Event Type
Radius-Access-Request
IP Address
Is a Phone
No
Node Status
N/A
Domain
YLVNDOMAIN
Profile
N/A
Realm
nykvngrp.com.vn
Reason
chrooted_mschap_machine: Program returned code (127) and output ''
Role
N/A
Source
N/A
Stripped User Name

//

could not obtain winbind separator!
Reading winbind reply failed! (0x01)
:  (0x0)
//
![image](https://user-images.githubusercontent.com/47883565/87881338-c3bf1480-ca22-11ea-969b-0f96617d7484.png)

Thanks.

Hai

**Comment by extrafu** [comment]
This is a configuration issue, use the mailing list for that.
