### ISSUE TITLE
Pre-registration portal doesn't work anymore.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5713]
**Describe the bug**
Pre-registration portal doesn't work anymore.

**To Reproduce**
Create a connection profile where pre registration has been enabled.
Connect to it from outside and you will show the error message: "Your computer was not found in the PacketFence database. Please reboot to solve this issue."

**Screenshots**

**Expected behavior**
Should be able to register

**Comment by jrouzierinverse** [comment]
This issue is the path '/preregister' is used as the URI filter in a profile that had the preregistration enabled.
However, that was also the old global catalyst path for preregistration.
I removed '/preregister' as a catalyst path.
Should I also add b2ac085 to maintenance?

**Comment by julsemaan** [comment]
I think it doesn't hurt as it would be a common mistake we could make

On a separate note, perhaps we should prevent users from defining a URI filter with one of the paths that are defined in pf::web::constants

**Comment by jrouzierinverse** [comment]
Done
