### ISSUE TITLE
API: GET /api/v1/config/interfaces ignores sort and fields parameter

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5718]
**Describe the bug**
I tried to use API to query specific elements of network interfaces and sort results.

**To Reproduce**
1. Query API using following syntax:
- `pfperl-api get '/api/v1/config/interfaces?sort=name&fields=id' | python -m json.tool`
or
- `cat example.json | pfperl-api get /api/v1/config/interfaces | python -m json.tool` with following JSON payload:
```json
{"sort":"id","fields":"id"}
```

In both cases, I got:
- all elements for each interface, in place of only `id`
- items are not sort by `id`, I'm not able to understand which criteria is used to sort items

**Expected behavior**
Take `sort` and `fields` arguments into account.

**Comment by julsemaan** [comment]
This API endpoint doesn't support sorting and fields

For what use-case do you need this ?

**Comment by nqb** [comment]
> This API endpoint doesn't support sorting and fields

This is how frontend called the API.

> For what use-case do you need this ?

For Venom scenario, I need to get the id of the latest interface of the system.

**Comment by julsemaan** [comment]
> > This API endpoint doesn't support sorting and fields
> 
> This is how frontend called the API.
> 
> > For what use-case do you need this ?
> 
> For Venom scenario, I need to get the id of the latest interface of the system.

Even if you would sort by ID, it wouldn't be the latest interface, ex:

Begining: you have an interface eth0 and eth1, order is [eth0, eth1]
You create a VLAN eth0.156
After, order is: [eth0, eth0.156, eth1]

So it would be better for you to track what interface you created and then delete it

**Comment by nqb** [comment]
@julsemaan,

From my point of view, if we support sorting interfaces, we should rely on `ifindex` attribute in place of `id` because `ifindex` is consistent on all OS. I don't know how frontend sort interfaces currently. Any idea @satkunas  ?

**Comment by julsemaan** [comment]
I think we just shouldn't support sorting interfaces but that's my 2 cents
