### ISSUE TITLE
Create a single user without a category raise an error.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5732]
**Describe the bug**
Create a single user in the admin gui raise an error in the logs, not in the frontend.

**To Reproduce**
1. Go to 'User create'
2. Create a user
3. Save
4. Aug  4 10:25:01 bibop: pfperl-api(22616) ERROR: Database query failed with non retryable error: Column 'category' cannot be null (errno: 1048) [INSERT INTO `password` ( `access_duration`, `access_level`, `category`, `expiration`, `login_remaining`, `password`, `pid`, `sponsor`, `tenant_id`, `valid_from`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )]{NULL, Node Manager, NULL, 2020-08-30, NULL, {ntlm}6EC3AFE2B2713824EC31C89761FAB2CB, bob, inverse, 1, 2020-08-04} (pf::dal::db_execute)

**Expected behavior**
The admin gui should raise an error and/or category and access/unreg date should be mandatory

**Comment by jrouzierinverse** [comment]
This is strange as the category can be null according to the database schema.
Also created a user and did not get this error.
Which version of PacketFence did this happen on?

**Comment by fdurand** [comment]
10.1 with latest maintenance patch

**Comment by jrouzierinverse** [comment]
Can you run the following SQL "```DESC password;```"?

**Comment by jrouzierinverse** [comment]
Can you run the following SQL ```DESC password;```?

**Comment by jrouzierinverse** [comment]
For some reason, the password table category is no longer NULLABLE.
This should fix it.
```ALTER TABLE password CHANGE COLUMN category category int DEFAULT NULL;```
