### ISSUE TITLE
Deprecate Gaming Devices Registration

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#5736]
I think it is time to remove Gaming Devices Registration and all components related to it. The standard use-cases can cover the gaming registration.  Packetfence is mostly used in the enterprise and education. Seeing gaming functionality is strange and awkward.

**Comment by jrouzierinverse** [comment]
Managing Gaming Console is a common use case in education.
Also, We moved to a more generic device registration a long time ago.
What components are referring to?

**Comment by lyubomirtraykov** [comment]
Now that you are working on role deletion it would be nice if we could remove gaming role. My staff is asking what is this role for.

**Comment by jrouzierinverse** [comment]
Are roles the only component you were referring to?

**Comment by lyubomirtraykov** [comment]
Yes

**Comment by jrouzierinverse** [comment]
The gaming role is a standard PacketFence role nothing to do here.
