### ISSUE TITLE
Role field missing from the variable to import Users via CSV

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5737]
![image](https://user-images.githubusercontent.com/5261214/89640756-3f6fec80-d87e-11ea-82c6-970bfd879581.png)

It does show up at the static section:

![image](https://user-images.githubusercontent.com/5261214/89640868-79d98980-d87e-11ea-925f-3d164058d159.png)

But if I want to import:
````
PID,role,email,notes,password
````
````
801,testrole1,801@internet.com,Chromecast User room 801,rm801
802,testrole2,802@internet.com,Chromecast User room 802,rm802
```

**Comment by jrouzierinverse** [comment]
This is mostly GUI at the moment @satkunas let me know if you need anything from the backend.
