### ISSUE TITLE
web admin: SNMP version is prefixed with a useless "v"

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5751]
**Describe the bug**
When you specify a SNMP version for a switch using GUI, you have to choose between 3 values in a dropdown:
- v1
- v2c
- v3

but API call sent doesn't contain the **v** letter and value saved in `switches.conf` too.

**To Reproduce**
1. Create a new switch with SNMP Version equals to `v2c`
2. Check value sent by API call: `SNMPVersion: 2c`
3. Check value saved in `switches.conf`:  `SNMPVersion=2c`

**Expected behavior**
We should remove `v` letter in dropdown list of GUI.

**Additional context**
Issue seems on API side:
```json
# pfperl-api get -M OPTIONS /api/v1/config/switches | jq .meta.SNMPVersion
{
  "allow_custom": false,
  "allowed": [
    {
      "text": "",
      "value": ""
    },
    {
      "text": "v1",
      "value": "1"
    },
    {
      "text": "v2c",
      "value": "2c"
    },
    {
      "text": "v3",
      "value": "3"
    }
  ],
  "default": null,
  "placeholder": "1",
  "required": false,
  "type": "string"
}
```

**Comment by jrouzierinverse** [comment]
What issues did this cause?

**Comment by nqb** [comment]
No issue but my customer suspect a wrong handling of SNMP community

**Comment by jrouzierinverse** [comment]
This a very cosmetic change. Has anyone else had issues with someone being confused?

**Comment by julsemaan** [comment]
My opinion is that this is a non-issue. The display matches what people usually call them which is the goal of the display value that doesn't necessarily match the underlying backend value

**Comment by jrouzierinverse** [comment]
I move to close this issue.

**Comment by nqb** [comment]
In fact, the issue is that frontend displays a wrong value from `switches.conf` (for example `2c`) when switch inherits value from a switch group.

**Comment by jrouzierinverse** [comment]
Is this still an issue?

**Comment by nqb** [comment]
We can close it.
