### ISSUE TITLE
Create a security event that detects random MAC addresses

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5755]
With the rise in popularity of randomized MAC addresses, we should ship a security event to help administrators deal with this:

The security event would have as a trigger the different MAC patterns that define a randomized MAC.

The template should explain why the device was isolated and provide per OS instructions on how to disable this (Apple and Android should be enough for now I believe)

We can then control if users can bypass this and for how much time through the standard security events configuration

**Comment by julsemaan** [comment]
Lets note that this is possible in 10.1 through configuration and creating a custom template but shipping something built-in seems to be necessary as I can already see this request coming over and over again

**Comment by nqb** [comment]
If it's possible in 10.1, we can create a dedicated section in your documentation for version before 10.2.

**Comment by nqb** [comment]
Once we have solution, we will post it here.

**Comment by extrafu** [comment]
@lzammit As discussed in the previous meeting, take care of creating the security event for this.
