### ISSUE TITLE
Configuration Wizard: Database Creation fails 

### ISSUE THREAD

**Issue by e8ahubi** [inverse-inc/packetfence#5757]
**Describe the bug**
The Configuration Wizard fails to create the pf db with the message: Error applying the schema to the database packetfence

The following error appears in the /usr/local/pf/logs/mariadb_error.log file:
InnoDB: Cannot add field `Open_Saturday` in table `packetfence`.`wrix` because after adding it, the row size is 8215 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.

If you try to set up the database by hand and implement a work around (MyISAM instead of InnoDB), the configuration wizard doesn't accept it because:

packetfence: pfperl-api(4400) WARN: Can't create database 'packetfence'; database exists (pfappserver::Model::DB::create)

**To Reproduce**
1. Install PF (according to the offical guide)
2. Go to https://pf-ip:1443
3. Page 2 - Database
4. Enter Root PW & DB Name
5. Click "Create" 

**Expected behavior**
Creation of DB without issue.

**Server:**
 - OS: RHEL 7.8
 - PacketFence Version: 10.1
 - MariaDB Verison: 10.4.14

**Comment by julsemaan** [comment]
You shouldn't have this version of MariaDB installed.

Which repos do you have enabled during the install ?

**Comment by e8ahubi** [comment]
The default repos. I also used the following commands:
subscription-manager repos --enable rhel-7-server-optional-rpms
subscription-manager repos --enable rhel-7-server-extras-rpms

Which MariaDB version would be the correct one?

**Comment by julsemaan** [comment]
the one shipped in our repo:
http://inverse.ca/downloads/PacketFence/CentOS7/x86_64/RPMS/MariaDB-10.1.21-centos7-x86_64-server.rpm

**Comment by e8ahubi** [comment]
okay thank you, i will try this one.

MariaDB 10.1 is end of support in October 2020 tho. Are there any plans to support newer versions of MariaDB in the future?

**Comment by e8ahubi** [comment]
https://github.com/inverse-inc/packetfence/issues/5907
Upgrade of MariaDB is planned for version 11.0
