### ISSUE TITLE
Viewing the nodes page launches a lot of calls to fetch the switch group members

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5762]
**Describe the bug**
If you have 200 switch groups defined in PF and you open the node page, it triggers 200 calls to `/api/v1/config/switch_group/$group/members` to populate the searches.

Instead, it should fetch the members when we expand a switch group to view its members

This prevents the nodes from being searched because of the pending calls to get the switch members

This happens on 10.1 but very likely affects 10.0

**Comment by nqb** [comment]
Similar to https://github.com/inverse-inc/packetfence/issues/5603
