### ISSUE TITLE
PF 10.1 - User Bandwidth report shows users as 1, 2, 3, 4, etc...

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#5766]
User Bandwidth report was working in PF 9.3 but appears to be broken since upgrading to 10.1. Report sample:
![pf_10 1_user_bandwidth](https://user-images.githubusercontent.com/1456100/91409114-3ce13100-e845-11ea-828c-e0fe5c221bb0.png)

**Comment by julsemaan** [comment]
@satkunas, I recall you adjusted these reports for v10, can you take a look at this ?

**Comment by satkunas** [comment]
Back ported to `maintenance/10.0` and `maintenance/10.1`.

@bbs2web thanks for the report
