### ISSUE TITLE
Captive portal popup (CNA) doesn't work on Samsung Android 10

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5769]
**Describe the bug**
It seems the Samsung CNA saga isn't over yet. I have reports of Samsung devices running Android 10 that aren't able to open the captive portal automatically. They perform a DNS query for connectivitycheck.gstatic.com but no HTTP request reaches the server for the check to happen.

I also tried the previous workaround (returning the real IP of connectivitycheck.gstatic.com via a DNS filter) without success

We'll need to get our hands on a Samsung device running Android 10 (galaxy tab A was the one failing at a customer)

I tried googling around a bit for this without much success

**Comment by julsemaan** [comment]
Some notes on the environment where the issue was detected:
- Using DNS enforcement
- Opening the portal in the browser works fine
- No SSL chain issue as far as I can tell
- All OSCP checks are allowed to go through

**Comment by Alckiviad** [comment]
Hi i have the same issue in my project. I find some solution here https://github.com/espressif/arduino-esp32/issues/1037#issuecomment-461940147 . It helps me

**Comment by fdurand** [comment]
Did multiples test on android 10 and not able to replicate.
