### ISSUE TITLE
Should be able to bypass checkup

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#577]
There should be an option to not stop on unsuccessful checkup. 

This way advanced users could start PF with a bad DB version if they really feel the need for it (like in a complex upgrade)

Suggestion : 
pfcmd service pf start --ignore-checkup

**Comment by louismunro** [comment]
+1.

**Comment by julsemaan** [comment]
Other suggestion : 
pfcmd service pf start --zammit-mode

**Comment by jrouzierinverse** [comment]
A bit more dangerous alternative
PF_IGNORE_CHECKUP=1 pfcmd service pf start

**Comment by julsemaan** [comment]
I'd prefer an option, we're not doing ruby, we don't need to have everything put in the environment

And also an option is easier to remember and it's clearer when added in the command usage IMO

**Comment by jrouzierinverse** [comment]
I would also suggest --skip-dependencies so you do not have to start the admin or memcached.

**Comment by jrouzierinverse** [comment]
I agree that the option is better than an environmental variable.
I think you may have offended some ruby people also

**Comment by jrouzierinverse** [comment]
I will implement this enhancement during next week's discussion of the pfcmd framework.

**Comment by julsemaan** [comment]
As discussed during the meeting I'll do it now so it's part of 5.1
