### ISSUE TITLE
Admin trying to fetch cluster status when user is only a "Node Manager"

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5773]
**Describe the bug**
When someone with the admin role "Node Manager" logs in, the admin tries to fetch the cluster status and that creates an error around the user not having SYSTEM_READ. The admin shouldn't be firing this call at all since the user doesn't have access to that section

**To Reproduce**
1. Create a node with "Node Manager"
2. Log into the admin with that account
3. You will see a call to `/api/v1/cluster/servers`

**Additional context**

I'd expect only clusters to be affected by this issue

**Comment by satkunas** [comment]
Fixed with https://github.com/inverse-inc/packetfence/commit/95894c0f96d332e7b8ad7380eab5a1fec4dd81a7

Please re-test

**Comment by julsemaan** [comment]
Are you really sure you fixed this one?

Your commit checks for access to switches to fetch switches configuration while this issue is for the cluster status

**Comment by satkunas** [comment]
@julsemaan there's 2 fixes there, I experienced an other similar error as Node Manager, so I included a fix for it as well.

**Comment by julsemaan** [comment]
> @julsemaan there's 2 fixes there, I experienced an other similar error as Node Manager, so I included a fix for it as well.

Sorry, must have confused butter with my glasses and saw that wrong.

I'll test it out and let you know

**Comment by julsemaan** [comment]
I'm stuck testing this in my fake cluster because of #5810 so we'll need a real cluster to test this on during the 10.2 QA

**Comment by satkunas** [comment]
@julsemaan #5810 has been fixed. There should be nothing standing in the way of having moar butter on your glasses.

**Comment by julsemaan** [comment]
The fix works, I'll cherry-pick it into the maintenance
