### ISSUE TITLE
Using the quick search of the switch groups searches for invalid ranges

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5778]
**Describe the bug**
If you use the quick search of the switches in the left menu and search for a switch range (ex: 10.0.0.0/8), it searches for '10.0.0.0' and omits the mask which yields no results at all

**To Reproduce**
1. Create a switch with identifier '10.0.0.0/8'
1. Try to use the quick search in the left menu of the load page to search for it

**Expected behavior**
Should search for '10.0.0.0/8'

**Comment by satkunas** [comment]
Fixed with 22e0c122c1ca299a97e72bcc7bda5d6ca32ed30b

**Comment by julsemaan** [comment]
Closing this, it does fill the search properly now but it seems the backend isn't built for this type of search (see #5792)
