### ISSUE TITLE
web admin: wrong HTTP certificate display in v10

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5785]
**Describe the bug**
Starting from v10, `/usr/local/pf/conf/ssl/server.crt` is not used by default because `httpd.admin` is disabled by default (see 
https://github.com/inverse-inc/packetfence/commit/508b78a3ed8bae47e4337a2ef867d3237f0b20ec).

However, HTTP SSL certificate display in GUI (System Configuration -> SSL certificates) is still `/usr/local/pf/conf/ssl/server.crt`.

**To Reproduce**
1. Generate two different certificates in following file:
- `/usr/local/pf/conf/ssl/server.crt`
- `/usr/local/pf/conf/ssl/server.pem` (cert + key)
2. Display HTTP certificate in GUI

=> HTTP certificate is the one in `/usr/local/pf/conf/ssl/server.crt`

**Expected behavior**
Display `/usr/local/pf/conf/ssl/server.pem` certificate because now we only supported one HTTP certificate (see #5783).

**Comment by julsemaan** [comment]
This can't be a +1 though since it involves moving the admin cert+key into its own file and adding API endpoints + adjusting the admin

**Comment by nqb** [comment]
> This can't be a +1 though since it involves moving the admin cert+key into its own file and adding API endpoints + adjusting the admin

From my point of view, this is more a solution for #5783.
If we want to fix this issue for maintenance/10, we can display content of `server.pem`

**Comment by julsemaan** [comment]
server.pem should *always* be a product of server.crt unless people are editing the files manually.

In that case, my opinion is that they shouldn't expect the GUI to cope with their manual changes

**Comment by nqb** [comment]
> In that case, my opinion is that they shouldn't expect the GUI to cope with their manual changes

It's not a manual change. It's a setup upgraded from 8.3 to 10.1. Before upgrade, they have two different SSL certificates. After upgrade, they only have one (captive portal certificate) but old web admin certificate is still the one that appear in GUI.

**Comment by julsemaan** [comment]
If it wasn't done through the GUI/API, it counts as a manual change.

This means anything done prior to the GUI existing counts as a manual change
