### ISSUE TITLE
EAP-TLS / PKI: Mark a node as unregistered

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#579]
When marking a node as unregistered, and it that node was connecting using an EAP-TLS certificate, a call to the PKI should revoke the certificate for that device

**Comment by dwlfrth** [comment]
Does not apply to "user flow" (username as the cert CN)

**Comment by julsemaan** [comment]
As with #580 I see this as a PKI provider configurable option.

Didn't find a way to expire the cert with the API. Will discuss with @fdurand

**Comment by julsemaan** [comment]
Done in PF and working with the PKI.

Only piece missing is the hability to regenerate a cert with the same CN on the PKI after it's revoked
