### ISSUE TITLE
galera-autofix may take a decision too quickly

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5793]
**Describe the bug**
When a transition in the MariaDB cluster happens (losing 1 node), it may take a decision too quickly and start a quorum server although the 2 remaining servers may be Primary shortly after they realize they lost a member.

For this reason, we should wait a moment before galera-autofix attempts to start a quorum server to re-establish the nodes

**Comment by julsemaan** [comment]
Re-opening because we need to test my fix before pushing it to maintenance

**Comment by nqb** [comment]
I pushed https://github.com/inverse-inc/packetfence/commit/ff1aacdd6a72ed4c1ce0f8bd80f8db49c2702fe6 to fix [unit tests](https://gitlab.com/inverse-inc/packetfence/-/jobs/748598233#L503). https://github.com/inverse-inc/packetfence/commit/ff1aacdd6a72ed4c1ce0f8bd80f8db49c2702fe6 can go in maintenance too.

**Comment by julsemaan** [comment]
cherry-picked ca5a237 into maintenance

@nqb, ff1aacd has conflicts cherry-picking, if its needs to get into the maintenance you'll have to take care of it

**Comment by nqb** [comment]
Sure, I reopened.

**Comment by nqb** [comment]
@julsemaan,

I cherry-picked ff1aacdd6a72ed4c1ce0f8bd80f8db49c2702fe6 on maintenance/10.1 and maintenance/10.0 without any conflicts.
