### ISSUE TITLE
old web admin: breaking changes with autoprefixer 10.0

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5798]
**Describe the bug**
As mentioned in #5797, [release 10.0 of autoprefixer](https://github.com/postcss/autoprefixer/releases) broke old web admin builds because `postcss` is not a dependency anymore of `autoprefixer`.

I did a quick fix in 9d275a53e143145ea61d5b3b892030a678dbdd23.

@cgx, could you check if we can use `postcss` 8 and `autoprefixer` 10 ?

As a reminder, images used to build PacketFence packages contain [nodejs 12.8.4](https://github.com/inverse-inc/packetfence/blob/ec6ec72ceeb5701f631e743ac42a39d8b98e1ebd/ci/packer/provisionners/inventory/group_vars/devel_centos/gitlab_buildpkg_tools.yml#L9-L10) (upgraded this morning)

**Comment by cgx** [comment]
Why do you want to use release 10 of autoprefixer? It's 2 day-old .. 

I suggest to stick to v9.x until either

- grunt-postcss is updated;
- we replace grunt by gulp or something else.

**Comment by nqb** [comment]
Hi @cgx,

> Why do you want to use release 10 of autoprefixer? It's 2 day-old ..

I don't really want to use it. I opened this issue to have a long time fix. 

If we deprecate old web admin in v11, I'm not sure we still need to build that part.

**Comment by nqb** [comment]
Old web admin has been completely deprecated, issue is not relevant.
