### ISSUE TITLE
packetfence-pki: automatically get certificate using MDM software.

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5799]
**Is your feature request related to a problem? Please describe.**
When you use `packetfence-pki` to generate RADIUS certificates for EAP-TLS, you may want to configure a [MDM](https://en.wikipedia.org/wiki/Mobile_device_management) software on nodes to automatically get a certificate from `packetfence-pki`.

**Describe the solution you'd like**
Be able to automatically get a client certificate from PacketFence PKI using [SCEP](https://en.wikipedia.org/wiki/Simple_Certificate_Enrollment_Protocol) protocol. Perhaps [ACME](https://en.wikipedia.org/wiki/Automated_Certificate_Management_Environment) can be used too.

**Comment by nqb** [comment]
A [RFC](https://tools.ietf.org/html/rfc8894) regarding SCEP has been published this month \o/

**Comment by fdurand** [comment]
Related to https://github.com/inverse-inc/packetfence/tree/feature/pfpki-scep

**Comment by nqb** [comment]
#6213 has been merged. It's now possible to request certificates using SCEP to packetfence-pki. This certificate can then be used to do EAP-TLS.
