### ISSUE TITLE
EAP-TLS / PKI: Unreg date / access duration

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#580]
On registration, we are computing an unreg date / access duration... That should be used on certification generation

**Comment by whitx** [comment]
With the actual design of the PKI, the validity of certificate is set into the profile,m so each certificate client with the same profilke will have the same validity.

**Comment by dwlfrth** [comment]
Does not apply to "user flow" (username as the cert CN)

**Comment by julsemaan** [comment]
This requires the possibility to set the expire date during the call to the PKI.

Will need @fdurand to take a look at it.

I personnally consider this wishlist as it won't break anything.

With the way I build multi-flow (mac + username) that feature would become an option of the provider (ex 'Tie unreg date with certificate expiration') so the user has the choice.

I see issues with this as autoreg based flows with access duration will not have the access extended (as the cert is generated once). Another point into having it configurable.

Assigning to @fdurand to add the option in the PKI API

**Comment by julsemaan** [comment]
@fdurand 

Is this still something we want to do? (extending the PKI API to support an expiry date)

**Comment by fdurand** [comment]
We already have an option to revoke the certificate on unregistration and i think it's enough.
