### ISSUE TITLE
Perl unit tests in error

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5803]
**Describe the bug**
With merge of recent PR, we got two Perl unit tests that failed:

https://gitlab.com/inverse-inc/packetfence/-/jobs/742227468#L718

**Comment by jrouzierinverse** [comment]
Fixed by 2f350bbbb94de5a3f0df51e7ee90b7432a802ab3 and f9962fa6e3a3ca71b4878b8e24ad4fa4fea47da5
