### ISSUE TITLE
Inline Layer 2 - DNS field will not allow more than one ip address.

### ISSUE THREAD

**Issue by nbhanji** [inverse-inc/packetfence#5812]
When trying to add multiple dns servers with comma separated, I get error message:  dns: Value must be an IPv4 address and could not validate.

![Screenshot](https://user-images.githubusercontent.com/21028/93723463-b92d1280-fb6c-11ea-9f29-d5b4499581c9.png)

**Comment by fdurand** [comment]
It looks that you added a space between the 2, can you retry without the space ?

**Comment by nbhanji** [comment]
Tried the following:
10.95.0.2,8.8.8.8
10.95.0.2 8.8.8.8
10.95.0.2 ,8.8.8.8
10.95.0.2 , 8.8.8.8

Same error message

**Comment by fdurand** [comment]
Just tried on a 10.1 and the first line works on my side.
Can you refresh the page (ctrl+f5) and retry the first one ?

**Comment by nbhanji** [comment]
Resolved, Thank you.  I tried again the first option as you suggested and it worked.  Thank you.  I had made changes manually in the conf file and it showed up ok on the gui side.  But as soon as I pressed save button it showed error.

For now it is resolved.

Thank you.
Nick.
