### ISSUE TITLE
Golang and Perl unit tests in failed state

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5813]
**Describe the bug**
Commits added on 17/09 cause issue with [Golang](https://gitlab.com/inverse-inc/packetfence/-/jobs/744583642#L510) and [Perl](https://gitlab.com/inverse-inc/packetfence/-/jobs/744583634#L708) unit tests.

Certainly related to merge of #5781 or #5725

**Comment by fdurand** [comment]
Golang test fixed by https://github.com/inverse-inc/packetfence/commit/c973f25eec32efb6078a2c9354d40239152d34a9

**Comment by fdurand** [comment]
Lets keep @jrouzierinverse check for the perl unit tests.

**Comment by nqb** [comment]
Should be fix now by 5f8d31faef1a18935d55a006c72a03e8783a2f62 and 6d88a67d226ed02406f92e9121ba181448a41d2c
