### ISSUE TITLE
Device Class form Fingerbank is incorrect

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#5814]
When i refresh the fingerbank the device class is incorrect:
<img width="1172" alt="Screen Shot 2020-09-21 at 10 37 06" src="https://user-images.githubusercontent.com/17347347/93742380-ad862e00-fbf6-11ea-9548-1b2a5b097fdb.png">
The fingerbank-collector is version 1.3.10.

**Comment by julsemaan** [comment]
Investigation has been made, was due to a rule that was too loose on api.fingerbank.org.

In 24-48 hours you should be able to refresh this device and not see Linux OS anymore

Reopen if it isn't the case
