### ISSUE TITLE
Security events upgrade script doesn't rename the connection profile templates

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5815]
**Describe the bug**
The old connection profile violations templates (`html/captive-portal/profile-templates/*/violations`) aren't renamed to `html/captive-portal/profile-templates/*/security_events`

Manually renaming the directories does the trick but we should add this to the violation->security event upgrade script

**Comment by nqb** [comment]
> Manually renaming the directories does the trick but we should add this to the violation->security event upgrade script

In that case, I suggest to have a section in Upgrade Guide related to maintenance patches: we encourage users to apply maintenance patches as part of their upgrade, just after package upgrades and before restarting services.
