### ISSUE TITLE
Repeatable SQL upgrade

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5819]
**Describe the bug**
Statements in `upgrade-X.X.X-X.Y.Z.sql` need to be made repeatable using `IF NOT EXISTS` etc, so that the SQL statements can be subsequently rerun without generating any errors.

**To Reproduce**
`mysql pf < /usr/local/pf/db/upgrade-X.X.X-X.Y.Z.sql`

again...

`mysql pf < /usr/local/pf/db/upgrade-X.X.X-X.Y.Z.sql`

The 2nd+ attempt should complete without terminating.

**Comment by nqb** [comment]
Nice addition :+1:
