### ISSUE TITLE
Device Class form Fingerbank is incorrect

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#5824]
When i refresh the fingerbank the device class is incorrect:
<img width="883" alt="Screen Shot 2020-09-24 at 10 25 21" src="https://user-images.githubusercontent.com/17347347/94114874-98590b80-fe51-11ea-8ea9-30710867aa8a.png">
<img width="789" alt="Screen Shot 2020-09-24 at 10 29 22" src="https://user-images.githubusercontent.com/17347347/94114889-9db65600-fe51-11ea-887e-d07a31c4a33e.png">
The fingerbank-collector is version 1.3.10.
Here is the old issue request: #5814

**Comment by julsemaan** [comment]
Should be fixed in the next 24 hours, reopen if needed
