### ISSUE TITLE
web admin: frontend need to be refresh to display new items in PKI menus

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5827]
**Describe the bug**
When you create new items in a PKI menu, you need to refresh your next menu if you want to be able to select your previous item.

**To Reproduce**
1. Create a new template (Template menu)
2. Try to create a new certificate using "New certificate" button (Certificates menu)

=> Your template is missing.

After a refresh, it works.

**Expected behavior**
New template should be available in Certificates menu

**Comment by nqb** [comment]
@satkunas, 

I noticed that if you revoke a certificate from Certificates tab, you have to refresh your page to see change applied.

**Comment by satkunas** [comment]
Unable to reproduce original issue using recent UI build. 

Revoking a cert appears to have a backend delay before the revoked cert shows up in the search. No changes are needed in the UI at this time.
