### ISSUE TITLE
web admin: incorrect display for a date after 2038

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5828]
**Describe the bug**
If you generate a certificate for 7500 days (~20 years) using a PacketFence PKI template, frontend doesn't display correctly resulting date even if certificate contains correct date.

I assume this is because date is after 2038.

**To Reproduce**
1. Create a CA in PacketFence PKI
2. Create a template with 7500 days as Validity
3. Generate a certificate using template

**Screenshots**
![Capture d’écran de 2020-09-24 13-38-48](https://user-images.githubusercontent.com/10830260/94140304-55a42d00-fe6b-11ea-84c1-42ebac8859db.png)

**Expected behavior**
Resulting date should be display.

**Additional context**
Even if it's only a display issue, you're not sure your certificate is valid. You have to download it and verify by hand if date is correct which is painful.

5000 days works.

**Comment by satkunas** [comment]
Waiting on https://github.com/inverse-inc/packetfence/issues/5843 before resolving.

**Comment by fdurand** [comment]
The date in the db is stored as zero (valid_until: 0000-00-00 00:00:00) it looks to be an issue with the version of golang we are using (https://github.com/golang/go/issues/36654)

**Comment by fdurand** [comment]
After talking to the team , we will probably need to limit the validity of a certificate to a maximum of 825 days (https://support.apple.com/en-ca/HT210176). @satkunas is it possible to limit the validity field in the form (CA and profile) ?

**Comment by julsemaan** [comment]
@satkunas will limit the validity in the frontend for the CA and the profile
