### ISSUE TITLE
EAP-TLS / PKI: Create two distinct flows

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#583]
- Keep the existing one in which the cert CN is the device MAC address. In that case, TLS certificate identifies a machine and not a user.
  (See issue #579 and #580)
- "De-facto" flow should set the username as the cert CN. In that case, TLS certificate will act as the identity used to register a device on the network (Issues #579 and #580 does not apply to that flow)

**Comment by julsemaan** [comment]
May I suggest we move to a wiki page for in-depth feature discussions.

**Comment by dwlfrth** [comment]
You may
