### ISSUE TITLE
Reports needs pagination.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5830]
**Describe the bug**
On a big set up where you have hundred thousands of devices registered you can't see the standart reports.
The reply of the http request is truncated and the browser just spin.

**To Reproduce**
1. Go to '/admin/alt#/reports/standard/chart/registered'
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/1553962/94154858-52e60f80-fe4c-11ea-883c-8a9893fe1299.png)

**Expected behavior**
We need to have pagination for the standard report
.

**Comment by jrouzierinverse** [comment]
We would need to add support for cursor, nextCursor, and prevCursor.
There are multiple reports that would require work.
