### ISSUE TITLE
FreeRADIUS: Failed to find "eap-eap-degraded" as a module or policy

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5831]
**Describe the bug**
`radiusd-auth` is not able to start after merge of #5616. Error message when you start RADIUS by hand:

```
/usr/local/pf/raddb/sites-enabled/packetfence[569]: Failed to find "eap-eap-degraded" as a module or policy.
/usr/local/pf/raddb/sites-enabled/packetfence[569]: Please verify that the configuration exists in /usr/local/pf/raddb/mods-enabled/eap-eap-degraded.
/usr/local/pf/raddb/sites-enabled/packetfence[569]: Failed to parse "eap-eap-degraded" subsection.
/usr/local/pf/raddb/sites-enabled/packetfence[554]: Errors parsing authorize section. 


```
**To Reproduce**
1. Install fresh devel
2. Try to start `packetfence-radiusd-auth`

**Additional context**
Reported by integration tests, occurs on CentOS and Debian.

**Comment by fdurand** [comment]
I installed a fresh devel and i am not able to replicate.

**Comment by nqb** [comment]
Integration tests are still failing. I will provide more informations.

**Comment by nqb** [comment]
Issue occurs after you join a domain and configure a realm (see [config files](https://gist.github.com/nqb/19198ff108d6b711c384be744eb31d77)).
