### ISSUE TITLE
Unable to assign roles and VLANs when creating a new switch

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5832]
**Describe the bug**
When creating a new switch, its missing most of the roles to assign VLANs, roles and URLs

**To Reproduce**
1. Fresh install of PF
2. Start creating a new switch with the following parameters:
![image](https://user-images.githubusercontent.com/3857942/94174964-fdb5f800-fe63-11ea-8650-19d0126c961b.png)
3. Go in the Roles tab of that switch
![image](https://user-images.githubusercontent.com/3857942/94175044-18886c80-fe64-11ea-8fdd-84e63ddf66bb.png)

**Expected behavior**
All roles in roles.conf should be part of the list

**Comment by satkunas** [comment]
@julsemaan I've seen this happen occasionally, but I was never able to replicate it directly. It appears to be a race-condition with another API call for the roles. I've re-ordered the API calls and now wait for the roles response before loading the switch resource:  ee8a9945530c4e5ce4e3f944072446a1df8db006

Please re-test and let know if you're still experiencing this issue.

**Comment by julsemaan** [comment]
Lets close it, I'll reopen it if I see it again in my tests, for now it looks good
