### ISSUE TITLE
Allowed actions are not localized

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5834]
**Describe the bug**
Allowed actions in Admin Access configuration section are not localized.

**To Reproduce**
1. Go to 'Configuration -> System Configuration -> Admin Access -> Nw Admin Role'
2. Click on 'User Options -> Allowed  Actions'
3. You will see that the choice in the list are not localized

**Screenshots**
![image](https://user-images.githubusercontent.com/1553962/94182438-0102b100-fe6f-11ea-820d-a4e45bba5707.png)

**Expected behavior**
Should see that:

![image](https://user-images.githubusercontent.com/1553962/94182816-84240700-fe6f-11ea-9a7a-fe803757f861.png)

**Comment by satkunas** [comment]
Not able to reproduce

![Screenshot_20200925_095609](https://user-images.githubusercontent.com/3904468/94275776-64471e80-ff15-11ea-98b7-ac66d2559681.png)

**Comment by satkunas** [comment]
@fdurand please retest

**Comment by fdurand** [comment]
it's allowed action in the bottom, not allowed user access level.

**Comment by satkunas** [comment]
@jrouzierinverse can you map these on the backend?

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS "/api/v1/config/admin_roles"| jq '.meta.allowed_actions.item.allowed'`
```
```json             
[
  {
    "text": "set_access_level",
    "value": "set_access_level"
  },
  {
    "text": "mark_as_sponsor",
    "value": "mark_as_sponsor"
  },
  {
    "text": "set_tenant_id",
    "value": "set_tenant_id"
  },
  {
    "text": "set_access_durations",
    "value": "set_access_durations"
  },
  {
    "text": "set_role",
    "value": "set_role"
  },
  {
    "text": "set_role_on_not_found",
    "value": "set_role_on_not_found"
  },
  {
    "text": "set_role_from_source",
    "value": "set_role_from_source"
  },
  {
    "text": "set_access_duration",
    "value": "set_access_duration"
  },
  {
    "text": "set_unreg_date",
    "value": "set_unreg_date"
  },
  {
    "text": "set_time_balance",
    "value": "set_time_balance"
  },
  {
    "text": "set_bandwidth_balance",
    "value": "set_bandwidth_balance"
  }
]
```
