### ISSUE TITLE
Default ordering of audit logs is incorrect

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5840]
**Describe the bug**
If you view the RADIUS audit log or admin audit log, they order by created_at ASC instead of DESC so you see the oldest entries first instead of the newest

**Comment by satkunas** [comment]
@julsemaan by default the tables are ordered by `created_at DESC`. If you override this default it's saved in the application's local storage. Try clearing this storage and re-try.

**Comment by julsemaan** [comment]
This was likely fixed by another issue you closed that was related to all the index pages
