### ISSUE TITLE
Selecting an amount of security events per page doesn't work

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5842]
**Describe the bug**
If you view the security events, it defaults to 25 items per page.
You switch it to 1000, it reloads, shows there is only 1 page but still only shows 25 items

**To Reproduce**
1. Go in security events
2. Select 25 items per page
3. Select 1000 items per page
4. Only seeing 25 items

**Comment by satkunas** [comment]
This appears to have been fixed with https://github.com/inverse-inc/packetfence/commit/cc553d0d0e4dbd476822bd178667f6fdd8ef866b from https://github.com/inverse-inc/packetfence/issues/5841

@julsemaan can you please retest with latest devel?

**Comment by julsemaan** [comment]
Fixed now
