### ISSUE TITLE
PKI golang runtime exception

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5843]
**Describe the bug**
Logs indicate a runtime exception (API returns 500)

`Sep 25 10:47:23 packetfence pfhttpd: Recovered panic: runtime error: invalid memory address or nil pointer dereference.`

**To Reproduce**
`POST /api/v1/pki/profiles`

with payload:

```json
{"ca_id":"24","name":"Test2038","validity":"5000","key_usage":"","extended_key_usage":""}
```

**Comment by fdurand** [comment]
It looks that there is mandatory values that are not passed in the payload.
I did it from the admin gui and i am not able to reproduce this error.

![image](https://user-images.githubusercontent.com/1553962/94446163-462c2900-0176-11eb-9c55-1e339b48747d.png)

**Comment by satkunas** [comment]
@fdurand which fields are mandatory? I'll add some client-side validation to ensure they're populated.

**Comment by fdurand** [comment]
ca_id digest key_size key_type name validity

**Comment by julsemaan** [comment]
> ca_id digest key_size key_type name validity

@satkunas will add these fields as required
