### ISSUE TITLE
Interval input is broken in maintenance jobs section

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5848]
**Describe the bug**
The input for the interval of maintenance jobs is broken

**To Reproduce**
1. Go in Configuration->System Configuration->Maintenance->node_cleanup

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/94452041-1c2a3500-017d-11eb-9d45-403c793cd53a.png)

**Comment by satkunas** [comment]
@jrouzierinverse looks like a regression on meta interval, can you look at this?

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS "/api/v1/config/maintenance_task/node_cleanup"| jq '.meta.interval'
null
```

**Comment by satkunas** [comment]
@jrouzierinverse has implemented a new scheduling that's much more flexible than the previous intervals.

For now I will implement a dropdown that allows 1 choice from the following static schedules:

```
@every 1/2/3/5/10/15/30/45s
@every 1/2/3/5/10/15/30/45m
@every 1/2/3/4/6/8/12/16/20/24h
```

Later we will deprecate the static list for a custom component that allows more granular definition.

**Comment by satkunas** [comment]
@jrouzierinverse @julsemaan a static dropdown has been added. Please review to ensure this temporary workaround satisfies 10.2.

**Comment by jrouzierinverse** [comment]
The only thing I added is the ability to add a custom value to the list.

**Comment by julsemaan** [comment]
@julsemaan will check that the dropdown works fine

@jrouzierinverse will document the new format of the interval

**Comment by julsemaan** [comment]
@jrouzierinverse will also add validation of the interval field

**Comment by jrouzierinverse** [comment]
Validation is added, please review.

**Comment by julsemaan** [comment]
works on my end
