### ISSUE TITLE
network should be restart after step 1 of configurator

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5858]
**Is your feature request related to a problem? Please describe.**
When you configure network interfaces during Step 1 of configurator, PacketFence will start to manage network interfaces using network-scripts on CentOS and ifup/down and Debian.

It means that if NetworkManager (or another network manager daemon) managed your network settings before Step 1 of configurator, network changes will only occurs after:
* network has been restarted
or 
* interfaces modified have been restarted
or
* a reboot

**Describe the solution you'd like**
Restart network when we click on next step during Step 1 of configurator.

**Describe alternatives you've considered**
- Restart only interfaces modified during Step 1 of configurator
- Warn users they should restart after they finish configurator (network will be restarted)

**Comment by julsemaan** [comment]
I believe that our code declares the interfaces as unmanaged by NM so even if NM is enabled and started, it should all work.

Is there a specific problem that this attempts to solve ?

**Comment by nqb** [comment]
> I believe that our code declares the interfaces as unmanaged by NM so even if NM is enabled and started, it should all work.

On my side, interfaces are configured in PF, declared as unmanaged by NM but there is no IP addresses configured on interfaces until I restarted network service or reboot. A restart of NM should also do the trick.

**Comment by julsemaan** [comment]
Can you provide an example to replicate. 

When I install a fresh CentOS without touching NM I'm unable to replicate this

**Comment by nqb** [comment]
I will provide a way to replicate.

**Comment by nqb** [comment]
Hello @julsemaan,

In order to replicate, you should:
- install a fresh CentOS with NM and three interfaces in DHCP
- install PacketFence on this server without rebooting
- configure first interface as management and second one as registration with static IP addresses during Step 1 of configurator
- leave third interface as is

On my side, until NM is restarted, I got following behavior:
- `nmcli` show all interfaces as managed by NM even if `NM_CONTROLLED=no` is set in each` /etc/sysconfig/network-scripts/ifcfg- file`
- IP address has been applied on management and registration interface
- Third interface is still in DHCP and NM try to get an IP address for this card each 5 minute.

Before I restarted NM:
```
# nmcli
[..]
eth2: connected to eth2
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:3D:A9:9B, hw, mtu 1500
        inet4 172.17.2.2/24
        route4 172.17.2.0/24

eth3: connected to eth3
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:E1:AE:CB, hw, mtu 1500
        inet4 172.17.3.2/24
        route4 172.17.3.0/24

eth4: connecting (getting IP configuration) to Wired connection 3
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:9C:3D:AE, hw, mtu 1500
```

After I restarted NM:
```
# nmcli
[..]
eth2: unmanaged
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:3D:A9:9B, hw, mtu 1500

eth3: unmanaged
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:E1:AE:CB, hw, mtu 1500

eth4: unmanaged
        "Red Hat Virtio"
        ethernet (virtio_net), 52:54:00:9C:3D:AE, hw, mtu 1500
```

When I tried to replicate, I noticed that IP addresses are correctly assigned to network cards before NM is restarted but that's not always the case. Perhaps due to a conflict with NM.

Anyway, before we restarted network daemon or server, we are not in a clean configuration.

**Comment by julsemaan** [comment]
With that in mind, then I think that we should enforce the disabling of NM in our packaging and stop the service during the initial install

Its part of the install instructions to disable it so might as well do it in our packaging

**Comment by nqb** [comment]
On Debian, I noticed that if systemd-networkd is used to manage networks (in place of NM). I need to manually restart network after step 1 in order to have all changes taken into account. Even if systemd-networkd has been disabled before starting configurator.

**Comment by julsemaan** [comment]
@nqb, is this still relevant and do we need to fix this for v11 ?

**Comment by nqb** [comment]
No because we removed `NM_CONTROLLED=no` from sysconfig scripts in #6407.
