### ISSUE TITLE
Pull the wrong cert during windows provisioning

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5861]
Add a template check when PF pulls the certificate per username because if you have two RootCA it will always download the certificate from the 1st RootCA for that username

Example:

ZamRootCA -> UserZamProfile -> lzammit (cert) 

ZamRootCA2 -> UserZamProfile2 -> lzammit (cert) 

the provisioning will always push the lzammit cert issued by ZamRootCA even though the Provisioner PKI Provider points at the ZamRootCA2 user profile.

**Comment by fdurand** [comment]
When you pull the certificate it's not complicate to select the correct one since we have the profile id.
But when you will want to revoke it when you unreg the device we don't have the profile_id so we will need to keep track of the profile used to create the certificate.

**Comment by lzammit** [comment]
It's not me selecting the certificate but the PKI provisioner.
