### ISSUE TITLE
Failure in to-10.2-pfmon-maintenance.pl

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5865]
**Describe the bug**
```
[root@test-fresh pf]# addons/upgrade/to-10.2-pfmon-maintenance.pl 
Undefined subroutine &main::catfile called at addons/upgrade/to-10.2-pfmon-maintenance.pl line 24.

```

**Comment by supportFGT** [comment]
I've run the updated version, but the error is the same:
./to-10.2-pfmon-maintenance.pl
Can't call method "Sections" on an undefined value at ./to-10.2-pfmon-maintenance.pl line 43.  

On Debian 9
