### ISSUE TITLE
Allowed actions in user action in admin role is not respected.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5869]
**Describe the bug**

Have a admin role like that:

![image](https://user-images.githubusercontent.com/1553962/94607598-224a0f80-026a-11eb-8f12-de53a70f99d3.png)

Doesn't limit the actions when you create a user. (You have all the actions available)

**Comment by jrouzierinverse** [comment]
@satkunas you should be using /api/v1/current_user/allowed_user_actions to populate allowed actions for a user.

**Comment by fdurand** [comment]
Still have the complete allowed option when itry to create a user in the admin gui.

**Comment by fdurand** [comment]
The role list is empty when you select set_role.
