### ISSUE TITLE
pfmon.conf doesn't exist anymore while upgrading to 10.2

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5871]
**Describe the bug**
pfmon.conf doesn't exist anymore since it has been removed from the spec so the script addons/upgrade/to-10.2-pfmon-maintenance.pl fails with:
```
[root@test-fresh pf]# addons/upgrade/to-10.2-pfmon-maintenance.pl 
Failed to open /usr/local/pf/conf/pfmon.conf: No such file or directory at addons/upgrade/to-10.2-pfmon-maintenance.pl line 26.
Can't call method "Sections" on an undefined value at addons/upgrade/to-10.2-pfmon-maintenance.pl line 29.
```

**Comment by supportFGT** [comment]
I've run the updated version, but  the error is the same:
 ./to-10.2-pfmon-maintenance.pl
Can't call method "Sections" on an undefined value at ./to-10.2-pfmon-maintenance.pl line 43.

**Comment by supportFGT** [comment]
My pfmon.conf is empty.
Can I ignore this message?

**Comment by jrouzierinverse** [comment]
You can safely ignore this message.
