### ISSUE TITLE
Difference between regdate and unregdate could not match an access duration 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5872]
**Describe the bug**
Sometimes, integration tests will fail when we verified if a node autoregistered with an access duration has an unreg date sets to regdate+access duration . We could have one second of difference. Example of a [failed test](https://gitlab.com/inverse-inc/packetfence/-/jobs/765272764#L1273).

**To Reproduce**
1. Autoregister a node with an access duration of 5 minutes
2. Check value of regdate and unregdate in DB for this node

Unregdate value is regdate - 1second and match exactly detect_date + access duration.

**Expected behavior**
unregdate should be always equals to regdate+access duration.

**Additional context**
In a VM used for integration tests, I got this log with a log level sets as TRACE:

```sql
    INSERT 
    INTO
        `
        node` (
            `autoreg`, `bandwidth_balance`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_manufacturer`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `last_seen`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `tenant_id`, `time_balance`, `unregdate`, `user_agent`, `voip`
        ) 
    VALUES
        ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) 
            ON DUPLICATE KEY UPDATE
                `autoreg` = ?,
            `category_id` = ?,
            `last_seen` = NOW(),
            `pid` = ?,
            `regdate` = ?,
            `status` = ?,
            `tenant_id` = ?,
            `unregdate` = ? with bind (yes,
            (undef),
            (undef),
            (undef),
            16,
            (undef),
            2020-09-30 12:53:47,
            (undef),
            (undef),
            (undef),
            (undef),
            (undef),
            (undef),
            (undef),
            (undef),
            (undef),
            0000-00-00 00:00:00,
            0000-00-00 00:00:00,
            0000-00-00 00:00:00,
            00:03:00:11:11:01,
            (undef),
            (undef),
            packetfence,
            2020-09-30 12:53:47,
            (undef),
            reg,
            1,
            (undef),
            2020-09-30 12:58:46,
            (undef),
            no,
            yes,
            16,
            packetfence,
            2020-09-30 12:53:47,
            reg,
            1,
            2020-09-30 12:58:46)
 at /usr/local/pf/lib/pf/dal.pm line 1150.
```
2020-09-30 12:53:47 is regdate, 2020-09-30 12:58:46 is unregdate.

**Comment by jrouzierinverse** [comment]
I move to close this.
The access duration calculation usually uses the current time + access duration.
@julsemaan @fdurand thoughts?

**Comment by julsemaan** [comment]
It would make sense for unregdate to be equal to regdate + the duration but AFAIK it would be a bit painful to implement just to get rid of the 1 second difference that will occur.

Could we adjust the integration test to allow for a 5 seconds tolerance which would be more than enough ?
Or perhaps use something else than the regdate for that check ?

The regdate is an informative field so I don't think its an absolute necesity to make it consistent with unregdate

**Comment by julsemaan** [comment]
Will wait for @nqb for feedback

**Comment by nqb** [comment]
> Could we adjust the integration test to allow for a 5 seconds tolerance which would be more than enough ?

Yes, I will do it. It seems possible to use an assertion like ShouldHappenBetween
