### ISSUE TITLE
Cluster: pfcron not falling over other node

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5874]
Step to reproduce:

systemctl stop packetfence-pfcon  on pf1 then tail the logs on pf2 and pf3.

Stop pfcron on pf2 then check the pfcron logs.

**Comment by jrouzierinverse** [comment]
That will not cause it to failover.
It will only failover if a pf2 becomes the new master.

**Comment by lzammit** [comment]
Oh, I see, pfcron follow the management VIP ?

**Comment by lzammit** [comment]
stopping keepalived make pfcron fail over.
