### ISSUE TITLE
Switch filters are unusable in the admin interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5875]
**Describe the bug**
The switch filters cannot be used because you can define the condition but cannot set the parameters and type override so you're just matching conditions but can't perform any actions for modifying the switch

**To Reproduce**
1. Navigate to the switch filters

**Comment by jrouzierinverse** [comment]
It looks like a frontend issue.
The following fields in OPTIONS were not implemented.
  log
  params
  status
  switch

@satkunas @cgx can you look at it?
Let me know if you need anything.

**Comment by julsemaan** [comment]
@satkunas will start looking at it

**Comment by cgx** [comment]
```
❯ /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/switch_filters | jq '.meta.params'
{
  "default": [],
  "item": {
    "default": null,
    "placeholder": null,
    "properties": {
      "type": {
        "default": null,
        "placeholder": null,
        "required": true,
        "type": "string"
      },
      "value": {
        "default": null,
        "placeholder": null,
        "required": true,
        "type": "string"
      }
    },
    "required": false,
    "type": "object"
  },
  "placeholder": null,
  "required": false,
  "type": "array"
}
```

@julsemaan would it be possible to have static list of values for `type`?

**Comment by julsemaan** [comment]
I'm not really familiar with switch filters and the forms of the filter engine but I guess @jrouzierinverse can populate something there that looks like the form of the RADIUS filters but with the attributes for the switch

**Comment by jrouzierinverse** [comment]
Done
