### ISSUE TITLE
Switch is not managed by PacketFence

### ISSUE THREAD

**Issue by rwwest77** [inverse-inc/packetfence#5890]
**Describe the bug**
No matter what I changed, the PacketFence always responds with "Switch is not managed by PacketFence", even though the IP is listed under Switches.

**To Reproduce**
1. Connect a client to an SSID with MAC filtering turned on
2. See error in live audit log

**Screenshots**

**Expected behavior**
Packetfence allows the request instead of rejecting

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 20

**Additional context**
![PacketFence](https://user-images.githubusercontent.com/37301899/95249370-8d559200-07e6-11eb-945e-7b3d332caba3.JPG)

**Comment by julsemaan** [comment]
Use the mailing list for configuration related questions
