### ISSUE TITLE
SNAT interface for passthroughs doesn't work as expected

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5894]
**Describe the bug**
If you want to use a specific SNAT interface for passthroughs in a VLAN enforcement scenario, you have to set `SNAT interface` to value of your specific interface in `Network configuration -> Network settings` and restart `packetfence-iptables`.

By default, `SNAT interface` for passthroughs is management interface. If you change this value, PF add new rules but keep rules related to management interface in place. In new rules added, `-o interface` used management interface in place of `SNAT interface` value.

Consequently, traffic is not NATed.

**To Reproduce**
1. Configure PF with:
  * an interface (eth0) (used as default gateway)
  * a management interface (eth1)
  * a registration interface (eth2)
2. Configure SNAT interface for passthrough with `eth0` value
3. On registration VLAN, try to reach a passthrough and capture traffic send to eth0

=> Source IP address of traffic routed to eth0 match IP address on registration network.

**Expected behavior**
New iptables rules should be added with value of SNAT interface for passthrough setting

**Comment by fdurand** [comment]
Can you try that:
https://github.com/inverse-inc/packetfence/commit/07ec21553faabb7b3d15b316247fb7e33209b67a

**Comment by nqb** [comment]
It works !
