### ISSUE TITLE
packetfence-pki: configure Organisation, Country, State, etc. fields on Templates

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5896]
**Is your feature request related to a problem? Please describe.**
When you create a certificate template, you don't have possibility to set Organisation, Country, State, etc. fields.

Consequently, you have to set this field each time you generate a certificate based on template.

**Describe the solution you'd like**
Inherit Organisation, Country, State, etc. fields from template when creating certificate with possibility to override with certificate values. 

**Describe alternatives you've considered**
Configure Organisation, Country, State, etc. fields on Templates in place of Certificates.

**Comment by fdurand** [comment]
https://github.com/inverse-inc/packetfence/commit/6109aff5f2330524924d75ab928f6b8f9d12cb8d
