### ISSUE TITLE
Missing upgrade scripts from the upgrade notes of 10.2

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5901]
**Describe the bug**
There are 4 upgrade scripts in the directory, only 2 in the instructions

**Comment by julsemaan** [comment]
@jrouzierinverse seems the missing instructions are related to features you've made, can you adjust the upgrade guide so it includes what is necessary please

**Comment by rcmcdonald91** [comment]
Is something missing here that is causing the PFCRON_READ Administrative role error when upgrading from 10.1?

**Comment by nqb** [comment]
It's the second time it occurs. I added a check in your release procedure to be sure we don't miss any script in the future.

**Comment by julsemaan** [comment]
This was addressed
