### ISSUE TITLE
Support for Ruckus DPSK

### ISSUE THREAD

**Issue by jacac** [inverse-inc/packetfence#5913]
PF supports Cisco's iPSK and it would be nice if this could be extended to support Ruckus DPSK as well. It is documented here https://docs.ruckuswireless.com/unleashed/200.8/GUID-E0AD67EA-91EB-473D-9F14-1C7A3ADC1F1B.html.

**Comment by julsemaan** [comment]
Its coming, its in the following branch: https://github.com/inverse-inc/packetfence/tree/feature/ruckus-dpsk

**Comment by oliverpole** [comment]
Hey guys, its 2023 so i know its been a long time. Has this feature been fully supported since the branch you linked and is live in the main release? I cant seem to find any information on it other than this comment.

**Comment by fdurand** [comment]
feature in packetfence
