### ISSUE TITLE
pfpki: unable to send certificates by mail

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5917]
**Describe the bug**
When I try to send a certificate by mail, I got following error message in web admin:

```
"gomail: could not send email 1: gomail: invalid address \"\": mail: no address","status":404
```

Certificate is not sent.

**To Reproduce**
1. Configure Alerting section in PacketFence with a SMTP server, sender and recipients
1. Configure a CA 
1. Create a template
1. Generate a certificate based on template with an email address
1. Send certificate by mail

**Expected behavior**
Certificate is sent to email configured in certificate.

**Additional context**
There is no SMTP server installed on my PacketFence: nothing listens on 25. However, I'm able to send emails using my SMTP server configured in Alerting section.

**Comment by jrouzierinverse** [comment]
What is the value of alterting.smtp_encryption?

**Comment by nqb** [comment]
Hello,

Default value, I didn't change it.

**Comment by fdurand** [comment]
You probably forgot to fill the PKCS12 tab in the profile.

**Comment by nqb** [comment]
No I did it to test with all fields. Anyway, it should not prevent to send an email.

**Comment by jrouzierinverse** [comment]
Instead of handling the email sending logic in golang.
Why not just use the API to send it.
{"subject":"Here", "message" : "Hello Bob"} => POST /api/v1/email/pfmailer

**Comment by nqb** [comment]
Issue is not presents on Debian 9 with 10.3.0 but presents on CentOS 7 with 10.3.0.

On CentOS 7, it seems that alerting settings are completely ignored by process where they are honored on Debian 9.

On CentOS 7, process try to use local SMTP server whatever is configured in alerting section.

**Comment by nqb** [comment]
@fdurand, could you look at this issue ?

I still have an issue on Debian 11 with PacketFence v11 with default settings in Alerting (SMTP server = `localhost`):
![image](https://user-images.githubusercontent.com/10830260/149095460-52426bd0-5126-4247-8915-9d8c2291ff71.png)

**Comment by fdurand** [comment]
it´s because SMTP Check SSL is enable event if the SMTP encryption is none.
