### ISSUE TITLE
All Fingerbank of pagination is incorrect

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#592]
Seems the pagination is using the 'Upstream' scope since there are a lot of pages available even though there is no Local combination

![combinations-pagination](https://cloud.githubusercontent.com/assets/3857942/7800113/5fce88c2-02de-11e5-874f-75b6be1ceb96.png)

**Comment by dwlfrth** [comment]
There's an issue with pagination... not only in combination...
Pagination is always set to 9 pages, no matter what...

**Comment by jrouzierinverse** [comment]
This was caused by an api change in fingerbank that never got reworked in packetfence.
