### ISSUE TITLE
Doing a switches bulk_import in a switch DB that has 4K entries yields a 504

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5920]
**Describe the bug**
When you try to import switches in a configuration that already has a lot of entries (4K in my case), the commit takes a lot of time and that yields a 504 to the user and you get to think the import failed.

According to the logs, the browser itself is canceling the request as far as I can tell:
```
Oct 16 09:37:22 packetfence01.is.uindy.edu pfhttpd[21464]: 16/Oct/2020:09:37:22 -0400 [ERROR 499 /api/v1/config/switches/bulk_import] context canceled
```

We need to have the import process poll for the job completion as it may be long to import configuration items in sections that have a lot of them

This has been seen on 10.1.0

**Comment by satkunas** [comment]
Fixes are in #5941 

Reassigning.
