### ISSUE TITLE
Ruckus Reason: (code 2)Previous auth is not valid

### ISSUE THREAD

**Issue by nurhambali** [inverse-inc/packetfence#5935]
hi, 

I have a problem when configuring a captive portal on an Ruckus UNLEASHED device,
where the auth is successful, but cannot send user onlien info:

Node Paccketfence :
![image](https://user-images.githubusercontent.com/18512905/97124808-2f242b00-1764-11eb-8665-f543e435c22f.png)

Mobile Phone:

![image](https://user-images.githubusercontent.com/18512905/97124850-64c91400-1764-11eb-87ba-b0053a48e0c5.png)

any ide ?

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by cassiofabiano** [comment]
Olá.
Boa tarde.
Saudações do brazil.
Estou tendo o mesmo problema.
Aqui no meu ambiente utilizo ruckus unleashed.
O usuário chega ao portal , autêntica, e depois fica preso nessa tela acima e nunca fica online.

Podem me ajudar?

**Comment by cassiofabiano** [comment]
Hello.Greetings from Brazil. I'm having the same issue. Here in my environment I use ruckus unleashed. The user arrives at the portal, authentically, and then gets stuck on this screen above and never goes online. Can you help me?
