### ISSUE TITLE
Add Members in Switch Groups Menu

### ISSUE THREAD

**Issue by tolivierl1** [inverse-inc/packetfence#5939]
**Describe the bug**

With PacketFence 10.2, when you want to add members in Switch_Groups Menu the drop-down list does not contain all switches that you can found in Switch_Page. 

**To Reproduce**

1. Add many switches in Config>Policies>Network_Devices>Switches
2. Add a switch group
3. Click on 'Members' 
3. Scroll down Drop-down List near 'Add new member' button
4. The list doesn't contain all switches you added at step 1.

(Same error after a refresh)

**Screenshots**
View of the beginning of my switches menu:

![image](https://user-images.githubusercontent.com/12293136/97413416-0e460c00-1903-11eb-960e-7699cccebf7f.png)

Drop-down list:
![image](https://user-images.githubusercontent.com/12293136/97412608-0fc30480-1902-11eb-892c-78e4108a32b0.png)

![image](https://user-images.githubusercontent.com/12293136/97413670-5a914c00-1903-11eb-93ed-6d6d3558808b.png)

In this example i can't add switch with identifier 172.24.4.55

**Comment by nqb** [comment]
Thanks for your report @tolivierl1.

Is there is only 25 members listed ?

**Comment by tolivierl1** [comment]
Yes, only 25 and with a random content (?)
As you can see in my screenshots, the first identifier is CS-LILLIAD in both pages but the second is not "172.24.119.20" in Switches Menu.

**Comment by nqb** [comment]
Issue is still presents on 10.3
