### ISSUE TITLE
EAP-TLS provisioner + PacketFence PKI: email can be an invalid

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5948]
**Describe the bug**
When you generate a certificate using PacketFence PKI on captive portal, you have to enter an email that will be use as `email` attribute. This email can be an invalid like "foo".

**To Reproduce**
1. Set up a PacketFence PKI
2. Create a PKI provider
3. Configure a Provisioner (EAP-TLS + PKI provider create at previous state)
4. Configure your connection profile with provisioner
5. Enter an **invalid** email address during certificate generation on captive portal

=> Certificate is generated with an invalid email address

**Expected behavior**
Invalid email should be rejected.

**Additional context**
`email` attribute is not saved in certificate itself, only used by PacketFence PKI.

**Comment by fdurand** [comment]
It looks that the email address is not asked anymore.

**Comment by nqb** [comment]
On 2021-05-21 build, I still have "Email" field on captive portal.
