### ISSUE TITLE
SSL certificates: not_after/before fields in reverse order

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5949]
**Describe the bug**
When you display SSL certificates in GUI, `not_after` field is displayed **before** `not_before` field which is contre-intuitive.

**Screenshots**
![Capture d’écran de 2020-11-02 11-45-13](https://user-images.githubusercontent.com/10830260/97859456-e8ed3f80-1d00-11eb-8628-0ff27d235473.png)

**Expected behavior**
We should reverse field to have same display as when you use `openssl x509` command:

```
# openssl x509 -in /usr/local/pf/conf/ssl/server.crt -noout -dates
notBefore=Oct 29 14:00:08 2020 GMT
notAfter=Nov 18 14:00:08 2022 GMT
```

**Comment by nqb** [comment]
In fact, fields are sorted alphabetically in GUI. 

API returns results sorted alphabetically too but they are [saved in a hash in correct order](https://github.com/inverse-inc/packetfence/blob/d3dc35827e682c8b53798f587b22de41fa6a1243/lib/pf/ssl.pm#L368-L375). Frontend seems to [only iterate](https://github.com/inverse-inc/packetfence/blob/d3dc35827e682c8b53798f587b22de41fa6a1243/html/pfappserver/root/static.alt/src/views/Configuration/_components/CertificatesView.vue#L132) on values return by API.

So I suppose code needs to be adjusted on backend to avoid returning items sorted.

**Comment by nqb** [comment]
https://perldoc.perl.org/perlfaq4#How-can-I-make-my-hash-remember-the-order-I-put-elements-into-it?

**Comment by julsemaan** [comment]
I think we should just have the frontend display them in the order that we deem appropriate like we do with all the other sections.

**Comment by nqb** [comment]
You're right.

**Comment by nqb** [comment]
I will assign @satkunas because I'm not sure what is the better way to do that. I didn't see a `certificate.js` file under `html/pfappserver/root/static.alt/src/views/Configuration/_config/` so I suppose there is everything to write from scratch.

I will also change labels: it's much more a nice to have than a bug.

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/a29e1786f1b358e2e2f43ab66922b11818f51b95
