### ISSUE TITLE
web admin: CSV export of switches doesn't contain switch group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5956]
**Describe the bug**
When you export your switches using "Export CSV" button, Switch Group column is empty in CSV file generated.

**To Reproduce**
1. Go to Configuration -> Switches
1. Click on Export CSV

**Expected behavior**
Switch group should be present in CSV file generated.

**Additional context**
Reported by @tolivierl1

**Comment by nqb** [comment]
@satkunas and @jrouzierinverse, could you look into this ?
Issue is still presents on 10.3.

I don't see any API call when clicking on "Export CSV" so I don't know if issue is on frontend or backend.

**Comment by satkunas** [comment]
No longer able to reproduce. Issue recently fixed in Config Search refactor.

**Comment by nqb** [comment]
@satkunas, I don't see any "Export CSV" button on latest devel builds for Switch or Switch groups menu.

**Comment by nqb** [comment]
As mentioned by @satkunas on #5576, we now need to select rows to be able to export.

Work as expected.
