### ISSUE TITLE
web admin: high-availability setting is not display correctly when editing an interface

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5963]
**Describe the bug**
When you edit an interface with `type=high-availability`, web admin doesn't display correct setting.

**To Reproduce**
1. Configure your management interface as `high-availability` 
2. Save
3. Leave current view
![Capture d’écran de 2020-11-03 11-26-21](https://user-images.githubusercontent.com/10830260/97974145-772bf900-1dc7-11eb-8b23-2913ae14b64c.png)

=> `high-availability` appears as an additional daemon which is wrong

4. Click on your interface

![Capture d’écran de 2020-11-03 11-27-55](https://user-images.githubusercontent.com/10830260/97974284-a6db0100-1dc7-11eb-85c4-056036c1ec3b.png)

=> `high-availability` appears as an additional daemon but not as a setting enabled.

**Expected behavior**
`high-availability` should:
- not appear as an additional daemon
- appear as enabled when that is the case

**Additional context**
`pf.conf` after I enabled `high-availability` on my interface:

```ini
[interface eth1]
ip=172.17.17.10
type=management,portal,high-availability
mask=255.255.255.0
```

When I try to display my interface (step 4), I see following return from API:
```json
    "item": {
      "additional_listening_daemons": [
        "portal",
        "high-availability"
      ],
      "address": "172.17.17.10/24",
[..]
      "high_availability": 1,
[..]
```

**Comment by nqb** [comment]
Additional note: on a setup with no `portal` daemon listening on management interface, `high-availability` appears as disabled and doesn't appear as additional daemon.

**Comment by nqb** [comment]
@jrouzierinverse, I opened #5964 and push a fix to see if frontend can't display correctly value return by frontend.

Could you check on your side why `high-availability` appears as additional daemon and push to `fix/5963` ?

Thanks

**Comment by rcmcdonald91** [comment]
#5680 I reported this back in July.

**Comment by nqb** [comment]
Thanks @theonemcdonald

**Comment by nqb** [comment]
Fix pushed to maintenance.
