### ISSUE TITLE
Switch defined by mac address are not processed by pfacct

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5969]
**Describe the bug**
lots of : load_balancer[71064]: (148097) ERROR: Failing proxied request for user "b0-34-95-93-90-6e", due to lack of any response from home server 10.201.33.40 port 1813 

This is due to accounting request from switches defined by mac addresses.
It looks that pfacct is not able to recognise the swicth and doesn't reply anything.

**Comment by nqb** [comment]
I suppose it's only related to a cluster environment because `pfacct` is able to process accounting requests in CI environment sent by a Cumulus switch which is defined by MAC address in `switches.conf`.

**Comment by fdurand** [comment]
The issue is pfacct check the secret of the switch but the request is coming from the load-balancer, so the share secret is not correct and the packet is discard. We talk about that with @jrouzierinverse yesterday and he will provide a fix.
