### ISSUE TITLE
web admin: unable to assign a specific tenant to a user

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5976]
**Describe the bug**
In a multi-tenant scenario, when logged as `system`, you may want to create a local `admin` user in a specific tenant. Using GUI, you have an error.

**To Reproduce**
1. Create a tenant
```
/usr/local/pf/bin/pfcmd tenant add example example.com portal.example.com
systemctl restart packetfence-config
/usr/local/pf/bin/pfcmd service pf restart
```
2. Log in on web admin as `system` with password in `/usr/local/pf/conf/unified_api_system_pass`
3. Users -> Create -> Actions:
* Access level: ALL
* Tenant ID: select 'example'

=> Frontend complains about errors.

**Screenshots**
![Capture d’écran de 2020-11-12 11-57-46](https://user-images.githubusercontent.com/10830260/98931439-4ee67d80-24de-11eb-8bde-f7f5feb95e23.png)

**Expected behavior**
We should be able to select a tenant and user should be created in correct tenant.

**Additional context**
I see a lot of errors once I select a tenant in web browser console:
```
TypeError: "right-hand side of 'in' should be an object, got undefined"
    value pfActions.js:122
    b pfActions.js:120
    b pfActions.js:49
    y index.js:174
    validations form.js:63
    children index.js:632
    VueJS 3
    refs index.js:224
    VueJS 3
    $v index.js:664
    VueJS 3
    vuelidateNS form.js:81
    stateNS form.js:97
    formStoreState pfMixinForm.js:61
    VueJS 3
    inputState pfMixinForm.js:68
    VueJS 3
    r pfFormRangeToggle.vue:1
    VueJS 7
```
**Workaround**
Switch to example tenant and create user without "Tenant ID" field => user is created in correct tenant.

**Comment by nqb** [comment]
@satkunas, issue is still presents on 10.3, could you look into this ?

**Comment by nqb** [comment]
Even if you select a Tenant ID for your user, Tenant ID is ignored and user is created in tenant where you create user.

**Comment by satkunas** [comment]
@nqb this UI issue is no longer reproducible on latest devel. Can you please re-test?

![Screen Shot 2021-08-04 at 1 34 49 PM](https://user-images.githubusercontent.com/3904468/128227713-c7255189-d3f6-43c4-834b-2c82d0337aed.jpg)

**Comment by nqb** [comment]
No more frontend error.

However, I noticed that my user is created with `tenant_id` equals to `0` in `password` table and with `tenant_id` equals to targeted `tenant_id` in `person` table.

If I switch to a specific tenant and create a user in that tenant, `tenant_id` is identical between both tables.

I look at API calls: `/api/v1/users` and  `/api/v1/user/USERNAME/password` boths contain following actions:

```json
{
  "access_duration": null,
  "access_level": "NONE",
  "actions": [
    {
      "type": "set_access_level",
      "value": [
        "NONE"
      ]
    },
    {
      "type": "set_tenant_id",
      "value": 2
    }
  ],
 [..]
```

For these two API calls, `X-PacketFence-Tenant-Id` has a value of `0`.

**Comment by nqb** [comment]
Action "Tenant ID" doesn't work on the backend so @satkunas will comment it for the release.

We will follow-up after the release.

**Comment by satkunas** [comment]
`set_tenant_id` source rule action disabled in https://github.com/inverse-inc/packetfence/commit/3a52da91f3b7fe04d92ae713f68231b790d77672

We will discuss the issues with this action with @julsemaan post-release and provide a workable solution.

**Comment by nqb** [comment]
I'm moving milestone, no more actions needed for 11.0

**Comment by satkunas** [comment]
@jrouzierinverse will need to alter the `/api/v1/current_user/allowed_user_actions` endpoint and omit the `{"action":"set_tenant_id"}` in order to remove this action from the Users.

**Comment by satkunas** [comment]
UI changes backported to `maintenance/11.0`

**Comment by nqb** [comment]
@jrouzierinverse, could you perform actions mentioned by @satkunas on #5976 (see https://github.com/inverse-inc/packetfence/issues/6568#issuecomment-916085537)

**Comment by satkunas** [comment]
Multi-tenancy is deprecated. Closing.
