### ISSUE TITLE
"overloadable" configuration field type

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#598]
Introduce a new configuration field type (let's call it overloadable for the moment) that will act as the following (alway as a list context):
- In pf.conf.default, we have some value for a configuration parameter:
  Let's say we have captive_portal.detection_url:http://steak1.com, http://steak2.com,...
- Currently, when configuring the value for a configuration field in pf.conf, it is overwritting the defaults value... in that case, it would ADD to it... 

Possible usage: 
- Incoming captive-portal detection URLs
- Proxy passthrought
- CRL
- ...

That would let the user configure some without removing the ones we consider "necessary" to PacketFence and remove the hardcoding part actually used.

**Comment by jrouzierinverse** [comment]
Using constants will solve the hard coding issue.

Added a new type may be more work than necessary.

**Comment by dwlfrth** [comment]
Yes and the purpose of this "feature" is to make it more "dynamic" and easier to maintain...

**Comment by jrouzierinverse** [comment]
My main concern it changes the concept of what is a default value in pf.conf.default 

Looking at the code in lib/pfconfig/namespaces/config/Pf.pm

It will not be useful for trapping.proxy_passthroughs since we disable any user defined proxy passthrough if trapping.passthrough is disabled.

So this would mean more code not less in this case.

However putting the standard proxy passthroughs in a constant is useful since it will reduce duplication.

**Comment by jrouzierinverse** [comment]
The only way to get this to work is to either.
- override the val function in Config::IniFiles module.
- Or do not use the -import functionality of Config::IniFiles and manually merge the pf.conf.default and pf.conf just for this particular case.

It is not worth the effort in my opinion.

**Comment by julsemaan** [comment]
I personally think it's a good idea to have this feature. It's not a lot of code as these special fields will have a different type in documentation.conf. It's then easy in pfconfig to manipulate these fields after the Config::Inifiles merge.

I think that having this type of field will allow us to move some selected constants closer to the user if they (or us when deploying) need to override some PacketFence features.

A good example would be the custom LDAP attributes #587 where the attributes could be moved to pf.conf.defaults and the ones in pf.conf add to this list. Where it can be useful is if the user wants to remove some attributes that he finds useless. In the current implementation he'd have to modify code. With what Derek asks it would be a matter of modifying pf.conf.defaults

I agree with you that we don't absolutely need this as we can define constants in perl but I find it neat to move these closer to the user as some constants may require a change in some environments.

**Comment by jrouzierinverse** [comment]
If a constant may require changes then it is not a constant anymore.
We should then take the time and create a proper way to configure those attributes.

**Comment by jrouzierinverse** [comment]
I consider pf.conf.defaults as "code" and constants they are not meant to be modified by a customer.
Any changes that a we or a customer does it will be blown out with the next install.
Also any changes done must be maintained between upgrades.

**Comment by julsemaan** [comment]
We can discuss that in a team meeting. I still think this is useful and centralizes data. I'll let others give their opinion

**Comment by dwlfrth** [comment]
We are not modifying constant or anything..
PacketFence is shipped with some defaults values that are needed but sometimes (I do have some cases in head) it is needed to keep these values and add some others...
I agree it is simplest with constant in the code, but it is better if moved closer to the user as Julien said...

**Comment by jrouzierinverse** [comment]
Julien in your example if a user upgrades their install wouldn't that reintroduce the values they removed in pf.conf.default?

How do you propose to stop that from happening?

**Comment by julsemaan** [comment]
It would reintroduce them like it would in a constants file. The main point for the overridable values is that the added values will be tied with the pf defined one allowing easier reference (for example in the admin we'll show the pf defined ones and yours, this is harder with a perl constants file)

**Comment by jrouzierinverse** [comment]
The name overridable is not clear on the purpose. 
list_merged_with_defaults would be a clearer name
