### ISSUE TITLE
SSL certificates: adjust settings for CSR

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5990]
**Is your feature request related to a problem? Please describe.**
At the moment, the way we generate CSR for HTTP and RADIUS certificates doesn't match [requirements for trusted certificates in iOS 13 and macOS 10.15](https://support.apple.com/en-ca/HT210176). From what I see, we don't meet following requirements:

- TLS server certificates must present the DNS name of the server in the Subject Alternative Name extension of the certificate. DNS names in the CommonName of a certificate are no longer trusted.
- TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.

**Describe the solution you'd like**
Implement new requirements for CSR and also check if packetfence-pki meet these requirements.

**Comment by nqb** [comment]
I generated a CSR by hand like this that match Apple requirements:

```
( _fd="/usr/local/pf/raddb/certs/server.key" ; _fd_csr="/usr/local/pf/raddb/certs/server.csr" ; openssl req -new -sha256 -key ${_fd} -out ${_fd_csr} -config <(
cat <<-EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C=FR
ST=Radius
L=Somewhere
O=Example Inc.
CN=pf.example.lan

[ req_ext ]
subjectAltName = @alt_names
extendedKeyUsage = serverAuth

[ alt_names ]
DNS.1 = pf.example.lan
DNS.2 = packetfence.example.lan
EOF
))
```

**Comment by fdurand** [comment]
I started to work on it last week.
https://github.com/inverse-inc/packetfence/commit/ab802010a93b8c3fd737574094d2d1c74a156868

**Comment by nqb** [comment]
`packetfence-pfki` is impacted by this issue too.

**Comment by fdurand** [comment]
Yes but i won't do it for packetfence-pki , it's deprecated.

**Comment by julsemaan** [comment]
I guess this issue is relevant but won't be addressed for v11 given the commit @fdurand referred to isn't in devel right now

Let just confirm that and shovel this to 11.1

**Comment by nqb** [comment]
Two limitations has been fixed in 10.3 by @fdurand, certainly in #6213.
Remaining part is related to "CSR generation" on webadmin and also to display Subject Alternative Name extension in web admin.

**Comment by julsemaan** [comment]
So do we call this good enough for 11.0 and shovel that to 11.1 for the CSR generation and SAN in the admin ?

**Comment by nqb** [comment]
I would say yes. Users who need to generate CSR can use workaround provided above.

**Comment by nqb** [comment]
According to https://www.chromestatus.com/feature/4981025180483584#details and to my tests, Chrome has removed fallback to CN. I'm not sure what is the behavior when you only have a CN in your SSL certificate but we should definitely update the way we generate CSR.

**Comment by nqb** [comment]
https://support.apple.com/en-us/HT211025

**Comment by julsemaan** [comment]
https://github.com/inverse-inc/packetfence/pull/6714 makes it so that our CSRs have a SAN in them now so this should fix it

As for the default certificates we ship, they are self-signed or signed by a dummy CA so I'm not sure if its really worth adding the SAN into them since they have very little chances of being used to establish a valid TLS connection

**Comment by fdurand** [comment]
@nqb can this be closed with the latest work done on the pki ?

**Comment by nqb** [comment]
No, we still need to adjust generation of CSR related to PacketFence certificates itself (SSL certificates in web admin)

**Comment by satkunas** [comment]
@fdurand @nqb CSR support is was added in 9d1f9f2d20fb1124cc4836a4cdea34aa7549334b

please revisit next steps
