### ISSUE TITLE
pfdhcplistener is not tenant aware

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5991]
**Is your feature request related to a problem? Please describe.**
When you are in a multi-tenant setup and you use a DHCP sensor, `pfdhcplistener` will process DHCP packets and create/update all nodes in **default** tenant even if nodes already exist in other tenants.

**Describe the solution you'd like**
1. Update nodes already created in DB in correct tenant
1. Create node in correct tenant when node is unknown: we could create a mapping between subnets declared in DHCP and tenants

**Comment by julsemaan** [comment]
You should use accounting instead which is tenant aware. Not sure we should go through all the pain of having a declaration of all the production networks

**Comment by nqb** [comment]
> You should use accounting instead which is tenant aware

I agree with you.

Another solution could be to only allow updates of **existing** nodes like `pfacct` do: when we received an accounting request for a node that doesn't exist, we don't create node in DB. Of course, we should keep current behavior as default but we can enable this behavior in a multi-tenant setup.

**Comment by jrouzierinverse** [comment]
A simpler approach could be to configure a tenant per interface.
Makes it a one to one mapping and less to configure.

**Comment by julsemaan** [comment]
I don't think it will be possible to have 1 tenant per interface, perhaps 1 tenant per network definition but since we don't define production networks on PF then we'd have to go through all that implementation.

I don't see any reason for using DHCP instead of RADIUS, most multi-tenant instances will be deployed online where DHCP traffic can't even be forwarded

**Comment by extrafu** [comment]
I agree with @julsemaan - using DHCP when handling multiple tenants doesn't make much sense.

**Comment by nqb** [comment]
In fact, it depends how your multi-tenant setup is deployed.

As discussed with @julsemaan, current tenant implementation is designed with one PacketFence server in a central location that handle tenants which are completely different (domain names, company)

But you can deploy a tenant setup inside a wide organization where tenant can be branches. 
In that situation, DHCP server can be:
- shared by all branches
- on same private network than PacketFence server

In this situation, it's more simple to add a DHCP sensor on DHCP server to get IP addresses of nodes but you got issue reported here.

As a reminder, if you rely on accounting to get IP addresses, you need: 
- to be sure IP addresses is part of accounting data sent by **all** network devices managed by PF
- to rely on RADIUS which is not always the case when doing Web Auth (for example: Unifi controller)

**Comment by nqb** [comment]
This issue prevents us to use security events based on DHCP fingerprinting in a multi-tenant setup
