### ISSUE TITLE
web admin: allow to select Tenant ID as available columns for switches and switch groups

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5992]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I browse switches or switch groups in a multi-tenant setup and I have to click on each switch to get Tenant ID.

**Describe the solution you'd like**
Be able to display Tenant ID when browsing switches and switch groups.

**Comment by nqb** [comment]
At the moment, it looks like API doesn't return Tenant ID of switches or switch groups when frontend uses `api/v1/config/switches `and `api/v1/config/switch_groups`

**Comment by nqb** [comment]
Just tested again: API doesn't return Tenant ID.
How do you want to handle this @jrouzierinverse and @satkunas ?

**Comment by satkunas** [comment]
@nqb I will proceed with UI changes if/when API includes tenant_id.

**Comment by jrouzierinverse** [comment]
The Tenant Id is returned the field is ```TenantId``` not ```tenant_id```
```/usr/local/pf/sbin/pfperl-api get  /api/v1/config/switches | jq -r .items[].TenantId```
