### ISSUE TITLE
packetfence requires freeradius-ldap that requires openldap-ltb, conflicting with openldap-servers

### ISSUE THREAD

**Issue by luizluca** [inverse-inc/packetfence#5999]
**Describe the bug**

I'm using zen with pkf 10.2.0.

I don't know the reason to use openldap-ltb but, AFAIK, freeradius-ldap only uses client-side of an ldap server.
However, openldap-ltb provide it all together, including slapd.service. This generate a file conflict:

```
Transaction check error:
  file /usr/lib/systemd/system/slapd.service from install of openldap-servers-2.4.44-22.el7.x86_64 conflicts with file from package openldap-ltb-2.4.49-1.el7.x86_64
```

If the OS openldap is not suitable, packetfence should not use a package that prevents the user to use OS openldap server. It could simply rename slapd.service or split the package into client/server/devel variants. The slapd offered with openldap-ltb is not suitable for my needs.

**Comment by nqb** [comment]
Hello @luizluca,

From what I see in this [thread](http://freeradius.1045715.n5.nabble.com/openldap-ltb-conflicts-with-package-symas-openldap-servers-td5757355.html), [upstream](https://github.com/FreeRADIUS/freeradius-server/blob/38a85bbaa997f112930018de310547f9ab2030be/redhat/freeradius.spec#L199-L204) as a dependency to `openldap-ltb`.

@fdurand can certainly explain why we need to have `openldap-ltb` and not just a library.

> The slapd offered with openldap-ltb is not suitable for my needs.

I'm curious to know why ? AFAIK, `openldap-ltb` comes with OpenLDAP server with additional features.

**Comment by luizluca** [comment]
> I'm curious to know why ? AFAIK, `openldap-ltb` comes with OpenLDAP server with additional features.

In my network, wireless net is considered insecure and does not touch corporate network. 
One of the ways to grant access is using an internal sponsor email. That requires some form of authentication source, even though it is only used to get authorized sponsors email addresses. As packet fence portal is exposed in an open wireless network, it is potentially a target for an attack. Considering a possible vulnerability in packet fence portal, an attacker could get control over packet fence OS. This way, it would also have access to whatever is accessible as authentication source. In my case, my users are in a AD. So, the attacker would have a clear connection to AD LDAP, expanding the exposed attack surface.

In order to avoid AD connection, I created a local LDAP server inside packet fence that uses slapd-shell. It uses a script that reads a file with our sponsors' email addresses inserted into packet fence by an internal server. This local LDAP is used as the authentication source for sponsor email authentication source.

Openldap-ltb does not provide slapd-shell.

**Comment by julsemaan** [comment]
Why not use the PacketFence internal database along with our API for automated creation/update of users?

Hosting anything else that is not a PacketFence service on a PacketFence box isn't officially supported.

Although this doesn't mean you can't do it, it means its not recommended to do it since we assume the OS will be for the exclusive usage of PF since we have dozens of components and services.

**Comment by luizluca** [comment]
Was it fixed?

**Comment by nqb** [comment]
Hello @luizluca,

> Was it fixed?

No.

Did you try solution proposed in previous comment ?

**Comment by luizluca** [comment]
> Did you try solution proposed in previous comment ?

The issue is about not being able to install a ldap server without conflicts because openldap-ltb ships an unused slapd. I don't see how a "don't use a ldap server" is a solution.
I know that it might be an upstream issue but I don't have the deep knowledge of how to packetfence interacts with these requirements to report the issue.

I didn't use packetfence REST API. I only needed a source of sponsors email. The only authentication source that could provide an email is ldap or internal database. I didn't want to mix portal registered users with sponsors in the same database. I didn't want them to authenticate locally. That's why I opted for an ldap database. I would gladly replace it with any other simple source of sponsors, like a txt file and that's what my ldap shell backend is doing: converting a txt file into a fake ldap server. Anyway, the original issue will persist.

**Comment by julsemaan** [comment]
> > Did you try solution proposed in previous comment ?
> 
> The issue is about not being able to install a ldap server without conflicts because openldap-ltb ships an unused slapd. I don't see how a "don't use a ldap server" is a solution.
> I know that it might be an upstream issue but I don't have the deep knowledge of how to packetfence interacts with these requirements to report the issue.
> 
> I didn't use packetfence REST API. I only needed a source of sponsors email. The only authentication source that could provide an email is ldap or internal database. I didn't want to mix portal registered users with sponsors in the same database. I didn't want them to authenticate locally. That's why I opted for an ldap database. I would gladly replace it with any other simple source of sponsors, like a txt file and that's what my ldap shell backend is doing: converting a txt file into a fake ldap server. Anyway, the original issue will persist.

As I initially said: "Hosting anything else that is not a PacketFence service on a PacketFence box isn't officially supported"

Just host your LDAP server on another machine instead of installing it on the PF machine. Its a better separation of concerns and will prevent weird packaging issues like you're hitting
