### ISSUE TITLE
unreg_node_locked_account.ps1 issue

### ISSUE THREAD

**Issue by djbdjb00djb** [inverse-inc/packetfence#600]
while when use unreg_node_locked_account.ps1, the locke event id must be 4740;
and this powershell will exec all lock event each run, and this should be exec just event who trigger a shell run;

**Comment by lzammit** [comment]
I fixed the Event ID for that script.

Thanks,

**Comment by julsemaan** [comment]
@bigzaym

Close your issues when you fix them
