### ISSUE TITLE
Constantly Poll InTune Devices for Compliance

### ISSUE THREAD

**Issue by derelict** [inverse-inc/packetfence#6001]
**Is your feature request related to a problem? Please describe.**
No. It looks like the sentinelone Provisioner supports constant polling for "compliance". With the intune provisioner, device compliance is only checked during registration. If an intune device gets not compliant anymore, no actions can be taken because devices are not checked/validated anymore.

**Describe the solution you'd like**
Constantly Poll intune devices for compliance.If not compliant anymore, put them back to "STATUS_PENDING" and show the portal with the reason.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by julsemaan** [comment]
The Intune provisioner does support that. Note that there has been fixes around this provisioner. Make sure you run 10.2.0 and have the latest patches applied via `/usr/local/pf/addons/pf-maint.pl`

If that doesn't work, then you'll likely have to open a bug report with logs and steps to replicate

**Comment by derelict** [comment]
i did a pf-maint.pl (however ... no provisioner and/or intune related files have been patched)

I have almost no perl knowhow ... but looking at intune.pm i can see no evidence about polling being implemented.

according to this lib/pf/pfcron/task/provisioning_compliance_poll.pm part :

`
=head2 run

Polls each provisioner to enforce compliance

=cut

sub run {
    my ($self) = @_;
    foreach my $id (@{pf::ConfigStore::Provisioning->new->readAllIds}) {
        my $provisioner = pf::factory::provisioner->new($id);
        if($provisioner->supportsPolling){
            $provisioner->pollAndEnforce($self->interval);
        }
    }
`

each provisioner is checked for "supportsPolling" ... and i can find no evidence this being the case for intune.pm ?

**Comment by julsemaan** [comment]
Even if pollAndEnforce is not defined, you'll get a check everytime the device authenticates if the grace time in security event 1300002 is over.

That will allow for constant checks everytime the device authenticates. If you wish to have support for pollAndEnforce, I can reopen this issue but I doubt we'll add this to our short/medium term R&D pipeline unless you're willing to sponsor the feature (i.e. pay for it)

**Comment by derelict** [comment]
Ok. i did not know about that Security Event 1300002  (i'm quite new to packetfence) let me check/learn and verify it.

i think/guess i could hack something myself in order to get pollandenforce working ... i just thought, that this feature might be of interest for future versions.

besides i think constant polling/checking device for compliance violations makes sense.
