### ISSUE TITLE
Translations file are missing i18n strings.

### ISSUE THREAD

**Issue by luizluca** [inverse-inc/packetfence#6003]
**Describe the bug**

I was trying to translate "Do not close this page until your access has been approved". However, there is no mention about it in po files. I guess there is some kind of i18n("") string collection process that has not happened for a long time.

**Comment by nqb** [comment]
Hello,

Thanks for the report. I checked on Transifex and string is missing.

We add a new feature in #5642 which comes with new strings on captive portal. They have not been pushed to Transifex to allow translations.

I will take care of that.

**Comment by luizluca** [comment]
Trere are more strings missing like "Activate Access". I didn't see what #5642 has to do with the missing string in po file I cited. It was not introduced by that PR.

Normally i18n strings are collected in an automatic process.

**Comment by nqb** [comment]
Hello @luizluca,

We have a script to extract i18n strings but we run it manually. It looks like we missed to extract new strings from captive portal for at least 10.2 version which explain why you don't have "Do not close this page until your access has been approved" on Transifex.

@cgx will run the script shortly and you be able to translate new strings on Transifex. Then you will have to export new .po file on your PacketFence server.

**Comment by nqb** [comment]
> Trere are more strings missing like "Activate Access"

I don't understand what you mean here. 

Do you mean that "Activate your network access" string is missing from your .po file ?
It should not be the case if you use [pt_BR locale](https://github.com/inverse-inc/packetfence/blob/088794560b9721705fe2df7e3317e260bfb304f3/conf/locale/pt_BR/LC_MESSAGES/packetfence.po#L106-L108).

**Comment by luizluca** [comment]
> > Trere are more strings missing like "Activate Access"
> 
> I don't understand what you mean here.

I mean this string:

https://github.com/inverse-inc/packetfence/blob/abe03c2ca4e92cb588e489e252187139e3f941e8/html/captive-portal/templates/emails/emails-guest_email_activation.mjml#L29

Yes, I'm trying to translate to pt_BR. However that string is missing for every language.

**Comment by luizluca** [comment]
> Hello @luizluca,
> 
> We have a script to extract i18n strings but we run it manually. It looks like we missed to extract new strings from captive portal for at least 10.2 version which explain why you don't have "Do not close this page until your access has been approved" on Transifex.
> 
> @cgx will run the script shortly and you be able to translate new strings on Transifex. Then you will have to export new .po file on your PacketFence server.

Thanks! I'll try to complete the translation ASAP in Transifex. I'm already manually adding and translating some missing strings in my ZEN installation. However, it is just a workaround as it will be overwritten with the next update.

**Comment by luizluca** [comment]
I got a regression. The commit https://github.com/inverse-inc/packetfence/commit/82a54303ad019b934e23b7992aad3ab2b356a6d5 seems to have broken whatever automatic process is used to generate the packetfence.po file. This string is not in po file:

https://github.com/inverse-inc/packetfence/blob/82a54303ad019b934e23b7992aad3ab2b356a6d5/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm#L183

And I diff both old and new po file and also found this missing strings (I don't know why this one is missing...):
https://github.com/inverse-inc/packetfence/blob/541c6c8545195881b136bc55edb7cd531594061d/html/captive-portal/templates/saml.html#L4

**Comment by nqb** [comment]
Hello @luizluca,

@cgx has pushed a new patch 4020102, could you test it ?

**Comment by cgx** [comment]
I've just pushed the strings to Transifex.

**Comment by luizluca** [comment]
Perfect! Thanks. The only old missing string is the one I refer in #6012 .
