### ISSUE TITLE
Tenant: implement update and delete operations

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6005]
**Is your feature request related to a problem? Please describe.**
At the moment, you can create tenant using `pfcmd tenant add` and get a list of tenants in web admin. However, it's not possible to update settings related to tenant (portal_domain_name and domain_name) using `pfcmd` or GUI. Also I don't see any possibility to delete a tenant.

**Describe the solution you'd like**
- Implement update and delete operations on backend
- Manage tenants from web admin (Create, Read, Update and Delete)

**Comment by julsemaan** [comment]
We need a proper GUI for the tenants and be able to CRUD them like we do with Nodes and Users

This section should only be available to the master tenant (global)

@jrouzierinverse would be better placed to expose the API to CRUD the tenants (if it doesn't exist already)

**Comment by jrouzierinverse** [comment]
The API is already there.

**Comment by jrouzierinverse** [comment]
I would need to restrict it to the Global Tenant.

**Comment by satkunas** [comment]
@jrouzierinverse are all API endpoints exposed? Should I proceed with ui?
