### ISSUE TITLE
POTD email is not translated

### ISSUE THREAD

**Issue by luizluca** [inverse-inc/packetfence#6012]
**Describe the bug**
Although I have complete the packetfence.po translation (and generated the .mo file), POTD still send me an english message.
It seems the POTD modules does not have a language option (as Sponsor does) and POTD is also not respecting "Language of communication" settings at "Main Configuration/Advanced". Maybe pfcron job is not loading/setting something.

Also, "New password of the day" is not in any po file. Maybe because it is breaking lines:
https://github.com/inverse-inc/packetfence/blob/55baa6ae46b6845b1224d12ff54f1c21abeb9b94/lib/pf/pfcron/task/password_of_the_day.pm#L72-L74

Other strings from the template seems to be in po file and I got them translated. However, the user still gets the english email.

I'm using packetfence-10.2.0-20201007132254.199263253.0007.v10.2.0.el7.x86_64 in ZEN with an updated packetfence.po/mo file.

**Comment by luizluca** [comment]
> Also, "New password of the day" is not in any po file. Maybe because it is breaking lines:
> https://github.com/inverse-inc/packetfence/blob/55baa6ae46b6845b1224d12ff54f1c21abeb9b94/lib/pf/pfcron/task/password_of_the_day.pm#L72-L74

I tried but I might not have the access to reopen #6003. The new po file removed an existing string. I added a new comment there.

**Comment by nqb** [comment]
@jrouzierinverse, I see a couple of fixes in devel which seems related to this issue.

Do you want me to push new strings to Transifex ? I suppose that "New password of th day" string will be part of new strings.

**Comment by luizluca** [comment]
> Do you want me to push new strings to Transifex ?

It will only be relevant when POTD job started to use i18n, which means, it the best case, the next release. However, It would be nice to push it sooner than later to improve the chance of being translated before the release for pt_BR and any other languages.

**Comment by cgx** [comment]
The new string has been pushed to Transifex.
