### ISSUE TITLE
packetfence online/offline status unkown

### ISSUE THREAD

**Issue by sonaligulia** [inverse-inc/packetfence#6016]
Hi all
 
In pf 10.2 cluster i am receiving radius accounting start and stop . My location log also updating but online offline status is unkown 
I check 
raddebug -t 300 -f /usr/local/pf/var/run/radiusd-acct.sock

(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Expanding URI components
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: EXPAND http://127.0.0.1:7070
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:    --> http://127.0.0.1:7070
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: EXPAND //radius/rest/accounting
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:    --> //radius/rest/accounting
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Sending HTTP POST to "http://127.0.0.1:7070//radius/rest/accounting"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "User-Name"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "NAS-IP-Address"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "NAS-Port"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Framed-IP-Address"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Called-Station-Id"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Calling-Station-Id"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Proxy-State"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "NAS-Port-Type"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Status-Type"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Delay-Time"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Input-Octets"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Output-Octets"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Session-Id"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Input-Packets"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Output-Packets"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Event-Timestamp"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "NAS-Port-Id"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Cisco-AVPair"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Stripped-User-Name"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Realm"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "Acct-Unique-Session-Id"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "FreeRADIUS-Client-IP-Address"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Encoding attribute "PacketFence-KeyBalanced"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Processing response header
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:   Status : 100 (Continue)
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Continuing...
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Processing response header
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:   Status : 200 (OK)
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:   Type   : json (application/json)
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Parsing attribute "control:PacketFence-Authorization-Status"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: EXPAND allow
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:    --> allow
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: PacketFence-Authorization-Status := "allow"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Parsing attribute "Reply-Message"
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: EXPAND Accounting ok
(11368) Wed Dec  2 10:56:13 2020: Debug: rest:    --> Accounting ok
(11368) Wed Dec  2 10:56:13 2020: Debug: rest: Reply-Message := "Accounting ok"
(11368) Wed Dec  2 10:56:13 2020: Debug:       [rest] = updated
(11368) Wed Dec  2 10:56:13 2020: Debug:     } # if !( ("%{client:shortname}" =~ /eduroam_tlrs/)  || (&request:PacketFence-ShortName && &request:PacketFence-ShortName =~ /eduroam_tlrs/))  = updated
(11368) Wed Dec  2 10:56:13 2020: Debug:   } # accounting = updated
(11368) Wed Dec  2 10:56:13 2020: Debug: Sent Accounting-Response Id 225 from first_server_ip:1813 to managment_vip:59664 length 0
(11368) Wed Dec  2 10:56:13 2020: Debug:   Reply-Message = "Accounting ok"
(11368) Wed Dec  2 10:56:13 2020: Debug:   Proxy-State = 0x3732
(11368) Wed Dec  2 10:56:13 2020: Debug: Finished request
(11369) Wed Dec  2 10:56:13 2020: Debug: Received Accounting-Request Id 188 from managment_vip:59664 to first_server_ip:1813 length 237
(11369) Wed Dec  2 10:56:13 2020: Debug:   User-Name = "username"

**Comment by julsemaan** [comment]
pfacct should be used to handle RADIUS accounting on version 10.2 if you want online/offline to work

**Comment by julsemaan** [comment]
i.e. disable radiusd-acct and enable pfacct
