### ISSUE TITLE
web admin: creating a role with a dot in name prevent access to switches menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6018]
**Describe the bug**
If you create a role with a dot ('.') in name, you're not able to access your Switches or Switch Groups anymore.

I create a different issue than https://github.com/inverse-inc/packetfence/issues/4851 because it's quite old but it looks to be the same.

This issue has been seen on a 10.1.0 setup.

**To Reproduce**
1. Create a role called "USR_HR_107.0"
2. Try to display Switches or Switch Groups

=> You got an error

In packetfence.log:

```
Dec  7 07:14:56 pfcen7dev packetfence: pfperl-api(1923) ERROR: did not  find parent for field USR_HR_107.0Role at  /usr/share/perl5/vendor_perl/HTML/FormHandler/BuildFields.pm line 239.  (Mojolicious::Plugin::DefaultHelpers::_development)
```

**Expected behavior**
Access Switches or Switch groups as usual 
or 
prevent creation of a role with a dot in name.

**Additional context**
Role is correctly created in DB and in `roles.conf`.

If I query API, I got a correct answer.

**Comment by jrouzierinverse** [comment]
It is happening for the same reason as #4851 this is a limitation of the HTML::FormHandler.

**Comment by nqb** [comment]
@jrouzierinverse, perhaps we can workaround this issue by checking value of role name before we create it (on backend) ?
