### ISSUE TITLE
Too much log action in Fingerbank

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#602]
We like logs but these seem to trigger whenever there is a DHCP packet in.

Everything except the last line belongs in DEBUG IMO

```
May 27 08:29:06 httpd.webservices(7493) INFO: Found 'Device' entry with ID '33' in schema 'Upstream' (fingerbank::Base::CRUD::read)
May 27 08:29:06 httpd.webservices(7493) INFO: Device ID '33' have at least 1 parent. Building parent(s) list (fingerbank::Model::Device::read)
May 27 08:29:06 httpd.webservices(7493) INFO: Found 'Device' entry with ID '1' in schema 'Upstream' (fingerbank::Base::CRUD::read)
May 27 08:29:06 httpd.webservices(7493) INFO: Device 'Microsoft Windows Vista/7 or Server 2008 (Version 6.0)' is a Windows based device (fingerbank::Query::isWindows)
```

**Comment by julsemaan** [comment]
These disapear if we reset the log configuration.

I'll open another issue for the management of these type of config

**Comment by abel408** [comment]
How can I reset my log configuration? I'm getting a bunch of these:

Oct 04 21:44:55 httpd.webservices(6904) INFO: Device ID '38' have at least 1 parent. Building parent(s) list (fingerbank::Model::Device::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '38' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '2' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Device ID '38' have at least 1 parent. Building parent(s) list (fingerbank::Model::Device::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '2' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '38' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Device ID '38' have at least 1 parent. Building parent(s) list (fingerbank::Model::Device::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '2' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Device 'Mac OS X' is a MacOS based device (fingerbank::Query::isMacOS)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '38' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Device ID '38' have at least 1 parent. Building parent(s) list (fingerbank::Model::Device::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Found 'Device' entry with ID '2' in schema 'Upstream' (fingerbank::Base::CRUD::read)
Oct 04 21:44:55 httpd.webservices(6904) INFO: Device 'Mac OS X' is a MacOS based device (fingerbank::Query::isMacOS)

Is this related?

**Comment by dwlfrth** [comment]
@abel408: It depend of a lot of factors (ie, version of PacketFence you are running, version of Fingerbank, ...)
Since that question is not really related to the status of this issue, I'd ask you to post on the mailing list and we can continue that discussion.

Thanks
