### ISSUE TITLE
Tenant: Deletion of REALM is not possible for tenant other than global

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6032]
**Describe the bug**
After you create REALMS for several tenant and try to remove them, it doesn't work.

API returned: item not found

**To Reproduce**
1. Create a new tenant
2. Create a REALM in that tenant, for example: `test`
3. Try to delete REALM connected as a user in global tenant

=> You got following error:
``` 
config/realm/test: Item (test) not found
```

**Expected behavior**
A user in global tenant should be able to remove all REALMS.

**Additional context**
It looks like the path to delete tenant is wrong. In logs:

```
Dec 10 08:45:29 pfcen7dev packetfence: pfperl-api(1857) DEBUG: Setting current tenant ID to 0 (pf::dal::set_tenant)                                                                                               │
Dec 10 08:45:29 pfcen7dev packetfence: pfperl-api(1857) DEBUG: DELETE "/api/v1/config/realm/test" (346695bc) (Mojolicious::dispatch)                                                                              │
Dec 10 08:45:29 pfcen7dev packetfence: pfperl-api(1857) DEBUG: Routing to controller "pf::UnifiedApi::Controller::Config::Realms" and action "resource" (Mojolicious::Routes::_controller)                        │
Dec 10 08:45:29 pfcen7dev packetfence: pfperl-api(1857) DEBUG: cache get for namespace='configfiles', key='/usr/local/pf/conf/realm.conf', cache='Redis:l1_cache', time='0ms': HIT (CHI::Driver::_log_get_result) │
Dec 10 08:45:29 pfcen7dev packetfence: pfperl-api(1857) DEBUG: 404 Not Found (0.002461s, 406.339/s) (Mojolicious::Controller::rendered) 
```

**Comment by nqb** [comment]
In fact, `X-PacketFence-Tenant-Id` is always set to 0 (global tenant) in HTTP header when we try to remove a REALM.

If I change value in my web browser, deletion work as expected.

**Comment by jrouzierinverse** [comment]
This happening because the frontend is not sending the proper X-PacketFence-Tenant-Id when deleting.
