### ISSUE TITLE
Tenant: REALMS declared in tenants different than default are not present in proxy.conf.inc

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6033]
**Describe the bug**
If you create a REALM in a tenant different than default, REALM is not created in `proxy.conf.inc`. It means that FreeRADIUS doesn't lookup on that REALM when receiving a RADIUS request for a specific tenant.

**To Reproduce**
1. Create a tenant
2. Create a REALM in that tenant
3. Restart `radiusd-auth`
4. Check content of `/usr/local/pf/raddb/proxy.conf.inc`

=> New realm is missing.

**Expected behavior**
All REALMS created should be present in `/usr/local/pf/raddb/proxy.conf.inc`

**Comment by nqb** [comment]
As discussed with @fdurand, FreeRADIUS will only match REALMs declared in default tenant BUT FreeRADIUS will be able to compute tenant ID. It means that if you declared same REALMs in default tenant and in other tenants, FreeRADIUS will use REALMs settings configure on tenant matched using packetfence-multi-domain code.

**Comment by fdurand** [comment]
I did the code in https://github.com/inverse-inc/packetfence/tree/feature/radius_multi_tenant .
I would like to see it in packetfence since it cover a need for some setup but i don´t know if it will be the direction we want to follow  to deal with multi-tenant. @extrafu any opinion ?

**Comment by extrafu** [comment]
You might want to create a PR from that branch to see what are all the changes. I don't know about including that in 11.2 if it's not considered as a bug fix.

We need to rethink entirely how we handle tenants in v12 and we that in mind, we should minimize the time we spend on the current code.
