### ISSUE TITLE
Not able to create a rapid7 scanner from the admin gui

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6034]
**Describe the bug**
Not able to create a rapid7 scanner from the admin gui

**To Reproduce**
1. Go to 'configuration/scans/scan_engines/new/rapid7'
2. Set a Name
3. it return that the name exist
4. No way to save

**Comment by danyroma80** [comment]
**Describe the bug**
When I try to configure a new rapid7 scan engine, I get the following
two errors in the gui:
"Unable to validate config/scans"
"host: Please specify the hostname or IP of the scan engine"

**To Reproduce**
- 'configuration/scans/scan_engines/new/rapid7'
- Set a Name  (e.g.  rapid7-test)
- Set an IP Address (e.g. 1.1.1.1)
- Set an Username and password
- click on Create

**Comment by satkunas** [comment]
@jrouzierinverse I'm able to reproduce 

```
POST /api/v1/config/scans

{
  "id": "rapid7-test",
  "isClone": false,
  "isNew": true,
  "scanType": "rapid7",
  "categories": [],
  "duration": {
    "interval": 20,
    "unit": "s"
  },
  "engine_id": null,
  "host": null,
  "oses": [],
  "password": "admin",
  "port": 3780,
  "post_registration": null,
  "pre_registration": null,
  "registration": null,
  "site_id": null,
  "template_id": null,
  "type": "rapid7",
  "username": "admin",
  "verify_hostname": "enabled",
  "ip": "1.1.1.1"
}
```

```
{
  "errors": [
    {
      "field": "host",
      "message": "Please specify the hostname or IP of the scan engine"
    }
  ],
  "message": "Unable to validate",
  "status": 422
}
```

**Comment by jrouzierinverse** [comment]
ip should be host.
