### ISSUE TITLE
Locationlog entry is not updated when Called-Station-Id changed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6045]
**Describe the bug**
If a node has a locationlog opened on a network device and network device sends a new RADIUS request with an updated Called-Station-Id attribute, locationlog is not updated.

For Unifi AP, we need to send a disconnect request to AP using BSSID as NAS-Identifier. If node roams between two BSSIDs on same AP, locationlog is not updated and PF can send disconnect request with wrong NAS-Identifier to AP. Consequently, we received a Disconnect-NAK with Session-Context-Not-Found.

**To Reproduce**
1. Create a MAC Auth RADIUS request using: 
```console
# cat /opt/mac_auth
User-Name = "77:77:77:77:77:77"
User-Password = "77:77:77:77:77:77"
NAS-IP-Address = 172.17.17.201
NAS-Port = 1
NAS-Port-Type = Ethernet
Service-Type = Call-Check
Called-Station-Id = "00:1a:1e:01:68:f8"
Calling-Station-Id = "77:77:77:77:77:77"
Called-Station-SSID = "Yeah"

# cat /opt/mac_auth | radclient -x 172.17.17.10:1812 auth `cat /usr/local/pf/conf/local_secret`
```
2. Create a second MAC Auth RADIUS request by updating `Called-Station-Id` attribute
3. Check locationlog: it has not been updated with new `Called-Station-Id` value.

**Expected behavior**
`switch_mac` should be updated in `locationlog` table.

**Comment by jrouzierinverse** [comment]
Can you provide the switches.conf?

**Comment by jrouzierinverse** [comment]
I am unable to replicate this in my setup.
I created a test that simulates that workflow here 0c8b051e8210fff3d61484c3f8a2ce26ed621a7e.
Can you provide the exact radius request and switch configuration so I can test with it.
My assumption is the cache for getAccessPointMACIP is returning the wrong value or the configuration is causing some conflicts.

**Comment by nqb** [comment]
Hello @jrouzierinverse,

In fact, in your test, you don't need to change IP address of switch, only Called-Station-Id.
It means that second RADIUS request is:

```
# cat /opt/mac_auth
User-Name = "77:77:77:77:77:77"
User-Password = "77:77:77:77:77:77"
NAS-IP-Address = 172.17.17.201
NAS-Port = 1
NAS-Port-Type = Ethernet
Service-Type = Call-Check
Called-Station-Id = "00:1a:1e:01:68:f9"
Calling-Station-Id = "77:77:77:77:77:77"
Called-Station-SSID = "Yeah"
```

and `switches.conf` only contains an entry with 172.17.17.201 as switch. There is no switch declared by MAC address.
