### ISSUE TITLE
multiple radius audit log for each request in cluster

### ISSUE THREAD

**Issue by sonaligulia** [inverse-inc/packetfence#6050]
hi all,

whenever a user get rejected due to any reason multiple radius audit log generated for each request in cluster.sometimes 10 logs generated sometimes 5. while its working fine in single server. 
In cluster gui setting RADIUS authentication on management enabled also not working  , only proxy requests to other servers. enabled or disabled behaving same.
it was working fine with previous versions

**Comment by nqb** [comment]
Hello,

In order to be able to reproduce, please provide us a [Minimal, Complete, and Verifiable example (MCVE)](https://stackoverflow.com/help/mcve)

**Comment by sonaligulia** [comment]
we use wrong password and multiple reject logs generated for single request rather than one

### **Here are radius.log(we change ip address, username ,mac)**

Dec 21 15:25:42 pf3 auth[193922]: (314)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:42 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:42 pf3 auth[193922]: (315) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC6)
Dec 21 15:25:45 pf3 auth[193922]: (325)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:45 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:45 pf3 auth[193922]: (326) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:25:47 pf3 auth[193922]: (335)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:47 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:47 pf3 auth[193922]: (336) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC6)
Dec 21 15:25:50 pf3 auth[193922]: (345)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:50 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:50 pf3 auth[193922]: (346) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:25:52 pf3 auth[193922]: (355)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:52 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:52 pf3 auth[193922]: (356) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:25:54 pf3 auth[193922]: (365)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:54 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:54 pf3 auth[193922]: (366) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:25:56 pf3 auth[193922]: (375)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:56 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:56 pf3 auth[193922]: (376) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:25:59 pf3 auth[193922]: (385)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:25:59 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:25:59 pf3 auth[193922]: (386) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:01 pf3 auth[193922]: (396)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:01 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:01 pf3 auth[193922]: (397) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:03 pf3 auth[193922]: (406)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:03 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:03 pf3 auth[193922]: (407) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:05 pf3 auth[193922]: (416)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:06 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:06 pf3 auth[193922]: (417) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:08 pf3 auth[193922]: (426)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:08 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:08 pf3 auth[193922]: (427) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:10 pf3 auth[193922]: (436)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:10 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:10 pf3 auth[193922]: (437) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:12 pf3 auth[193922]: (446)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:12 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:12 pf3 auth[193922]: (447) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:15 pf3 auth[193922]: (456)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:15 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:15 pf3 auth[193922]: (457) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:17 pf3 auth[193922]: (467)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:17 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:17 pf3 auth[193922]: (468) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)
Dec 21 15:26:19 pf3 auth[193922]: (477)   Login incorrect (pap: SSHA digest does not match "known good" digest): [CLIENT_UID] (from client pf port 50132 cli CLINET_MAC via TLS tunnel)
Dec 21 15:26:19 pf3 auth[193922]: [mac:CLINET_MAC] Rejected user: anonymous
Dec 21 15:26:19 pf3 auth[193922]: (478) Login incorrect (eap_peap: The users session was previously rejected: returning reject (again.)): [anonymous] (from client pf port 50132 cli CLINET_MAC)


**### here are radius-loadbalancer log** 

Dec 21 15:25:43 pf1 load_balancer[159386]: (1630) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:43 pf1 load_balancer[159386]: (1630) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:46 pf1 load_balancer[159386]: (1643) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:46 pf1 load_balancer[159386]: (1643) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:48 pf1 load_balancer[159386]: (1654) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:48 pf1 load_balancer[159386]: (1654) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:51 pf1 load_balancer[159386]: (1665) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:51 pf1 load_balancer[159386]: (1665) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:53 pf1 load_balancer[159386]: (1680) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:53 pf1 load_balancer[159386]: (1680) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:55 pf1 load_balancer[159386]: (1692) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:55 pf1 load_balancer[159386]: (1692) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:57 pf1 load_balancer[159386]: (1704) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:25:57 pf1 load_balancer[159386]: (1704) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:00 pf1 load_balancer[159386]: (1715) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:00 pf1 load_balancer[159386]: (1715) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:02 pf1 load_balancer[159386]: (1729) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:02 pf1 load_balancer[159386]: (1729) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:04 pf1 load_balancer[159386]: (1739) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:04 pf1 load_balancer[159386]: (1739) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:07 pf1 load_balancer[159386]: (1751) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:07 pf1 load_balancer[159386]: (1751) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC6) - Proxied to: pf3_ip
Dec 21 15:26:09 pf1 load_balancer[159386]: (1763) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:09 pf1 load_balancer[159386]: (1763) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:11 pf1 load_balancer[159386]: (1773) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:11 pf1 load_balancer[159386]: (1773) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:13 pf1 load_balancer[159386]: (1784) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:13 pf1 load_balancer[159386]: (1784) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:16 pf1 load_balancer[159386]: (1796) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:16 pf1 load_balancer[159386]: (1796) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:18 pf1 load_balancer[159386]: (1807) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:18 pf1 load_balancer[159386]: (1807) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:20 pf1 load_balancer[159386]: (1818) Login incorrect (Home Server says so): [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip
Dec 21 15:26:20 pf1 load_balancer[159386]: (1818) Login incorrect: [anonymous] (from client SWITCH_IP port 50132 cli CLIENT_MAC) - Proxied to: pf3_ip

**Comment by nqb** [comment]
This is still not a MCVE. We need a way to replicate your issue from scratch using a minimal example.

**Comment by fdurand** [comment]
Even if you try to authenticate one time, the switch send multiple attempts and for each attempt packetfence log the request.
So it's the normal behaviour and if you want to have only one entry then configure the switch to send only one radius request.
