### ISSUE TITLE
krb5.tt set INVERSE.LOCAL as default_realm

### ISSUE THREAD

**Issue by hopatzel** [inverse-inc/packetfence#606]
the krb5.tt file in /usr/local/pf/addons/AD includes the line
default_realm = INVERSE.LOCAL
which is not part of any substitution and thus ends up being part of /etc/krb5.conf 
please correct that.

(and removing files instead of patching them is not such a good style, too)
so please let the migrate.pl script save the former krb5.conf under some other name. Doing so, one can easily compare any (unwanted) changes. (for example, MIT or other "special" features, one had deleted before the update....)

**Comment by julsemaan** [comment]
Both suggestions were applied in the devel branch and maintenance/5.1

You can apply those using /usr/local/pf/addons/pf-maint.pl
