### ISSUE TITLE
NetData Needs to be Updated

### ISSUE THREAD

**Issue by royord** [inverse-inc/packetfence#6061]
Installing on newer versions of Ubuntu just isn't possible due to outdated versions of package dependency.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**To Reproduce**
`sudo apt-get install packetfence`

produces

> Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 packetfence : PreDepends: libnet-wmiclient-perl but it is not going to be installed
               PreDepends: netdata (< 1.11) but 1.19.0-3ubuntu1 is to be installed
               Depends: packetfence-golang-daemon (>= 10.2.0+20201007132254+199263253+0009+v10.2.0+stretch1) but it is not going to be installed
               Depends: freeradius (>= 3.0.21) but 3.0.20+dfsg-3build1 is to be installed
               Depends: freeradius-ldap but it is not going to be installed
               Depends: freeradius-mysql but it is not going to be installed
               Depends: freeradius-rest but it is not going to be installed
               Depends: freeradius-redis but it is not going to be installed
               Depends: libsystemd-daemon-perl but it is not going to be installed
               Depends: python-impacket but it is not installable
               Depends: iproute but it is not installable
               Depends: sscep but it is not going to be installed
               Depends: libposix-atfork-perl but it is not going to be installed
               Depends: keepalived (>= 2.0) but it is not going to be installed
               Depends: python-mysqldb but it is not installable
               Depends: python-twisted-bin but it is not installable
               Depends: python-twisted-core but it is not installable
E: Unable to correct problems, you have held broken packages.

**Expected behavior**
Packet fence would install.

**Comment by fdurand** [comment]
It's just that ubuntu is not supported anymore. Try with centos 7 or debian 9.

**Comment by royord** [comment]
May want to remove the documentation from the website then.
