### ISSUE TITLE
Support for Debian 10

### ISSUE THREAD

**Issue by royord** [inverse-inc/packetfence#6062]
Please upgrade this wonderful package to work with Debian 10, currently I'm getting the following when attempting to do an install on a fresh Debian 10 install.

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  packetfence : PreDepends: libnet-wmiclient-perl but it is not going to be installed
>                PreDepends: netdata (< 1.11) but 1.12.0-1+deb10u1 is to be installed
>                Depends: packetfence-golang-daemon (>= 10.2.0+20201007132254+199263253+0009+v10.2.0+stretch1) but it is not going to be installed
>                Depends: freeradius (>= 3.0.21) but 3.0.17+dfsg-1.1 is to be installed
>                Depends: freeradius-ldap but it is not going to be installed
>                Depends: freeradius-mysql but it is not going to be installed
>                Depends: freeradius-rest but it is not going to be installed
>                Depends: freeradius-redis but it is not going to be installed
>                Depends: libsystemd-daemon-perl but it is not going to be installed
>                Depends: iproute but it is not installable
>                Depends: sscep but it is not going to be installed
>                Depends: libposix-atfork-perl but it is not going to be installed
>                Depends: keepalived (>= 2.0) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by 7meis** [comment]
is there a rough plan when Debian 10 will be officially supported? Or is there a useful workaround for this? thanks.

**Comment by fireblade-nz** [comment]
Yes would like to see Buster supported also.

**Comment by nqb** [comment]
We support Debian 11 (bullseye) since PF v11.
