### ISSUE TITLE
Packetfence ZEN should include e2fsprogs package

### ISSUE THREAD

**Issue by aruberutsu** [inverse-inc/packetfence#6064]
Version: 10.2.0

**Describe the bug**
The PacketFence ZEN image comes with a root disk formatted in ext4, but the fsck.ext4 utility is not included.
Should the root filesystem become corrupt, there would be no way for the system to repair it at boot.

This was observed when our ZEN deployment was accidentally shut down uncleanly, when starting it up again the system was unable to mount the root filesystem in read-write, allowing only read-only.

It was only recovered when we booted the machine with a CentOS CD and manually ran fsck on it.

**To Reproduce**
1. Deploy PacketFence ZEN
2. Experience root disk issue, leaving the filesystem corrupt
3. ZEN becomes inoperative until fsck is run from third party media

**Expected behavior**
The system would detect at boot that the root filesystem wasn't clean, and fsck.ext4 would run to attempt to fix it. 

**Additional context**
e2fsprogs is the pacakge providing fsck.ext4 in CentOS.

**Comment by nqb** [comment]
Hello,

Thanks for the report. Completely legit. I will also add `cloud-utils-growpart` to simplify extension of disk.
