### ISSUE TITLE
Only enable netflow in iptables if you have inline networks with accounting enabled.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#6076]
Only enable netflow if you have inline networks with accounting enabled.

**Comment by julsemaan** [comment]
IMO this is more a bug fix we need to address sooner than later since I'm getting constant problems during deployments.

Lets make it a +1 in high priority

**Comment by nqb** [comment]
Is the problem caused by the fact that installation doesn't have kernel-header installed ?

**Comment by julsemaan** [comment]
perhaps, I'm not the one deploying the machines, we can try to replicate it in lab to see if that's exactly the problem

**Comment by jrouzierinverse** [comment]
This cannot be a +1 patch since this touches an example file.
