### ISSUE TITLE
packetfence startup fails after upgrade to 5.1 using winbind

### ISSUE THREAD

**Issue by hopatzel** [inverse-inc/packetfence#608]
starting packetfence after using the Migration.pl script Ends with:
[....] Restarting packetfence:Use of uninitialized value $binary in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager/winbindd.pm line 52.
Use of uninitialized value $binary in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager/winbindd.pm line 52.
. ok
and there is no Apache running to Change/undo the AD config ... :-(

**Comment by julsemaan** [comment]
Make sure you restarted packetfence-config and did pfcmd configreload hard.

I'll close this issue as questions of this matter belong in the mailing list

**Comment by hopatzel** [comment]
Ok, but I would appreciate right this hint in the Upgrade.ascii right next to the  migrate.pl hints.  … thanks

## 

DEUTSCHE TELEKOM HEALTHCARE AND SECURITY SOLUTIONS GMBH

Holger Patzelt
Pascalstr. 11, 10587 Berlin
Telefon: +49 30 8353 84591  Telefax: +49 30 8353 84429 (Tel)
E-Mail: Holger.Patzelt@t-Systems.commailto:Holger.Patzelt@t-Systems.com

Die gesetzlichen Pflichtangaben finden Sie unter: http://www.telekom-healthcare.com/pflichtangabenhttp://www.telekom-healthcare.com/footer/impressum/1224744

Hinweis: Diese E-Mail und/oder die Anhänge sind vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Die Weitergabe oder Kopieren dieser E-Mail ist strengstens verboten. Wenn Sie diese E-Mail irrtümlich erhalten haben, informieren Sie bitte unverzüglich den Absender und vernichten Sie die Nachricht und alle Anhänge. Vielen Dank.
