### ISSUE TITLE
Duplicate entries in logs

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6086]
On debian , the log lines are duplicated.

We need to set ForwardToSyslog=no in /etc/systemd/journald.conf and restart journald

**Comment by nqb** [comment]
@fdurand, I can confirm your proposal work as expected.

**Comment by nqb** [comment]
Do you know why we need to set this option ?

Currently, we don't install a specific journald configuration on Debian 9.

On CentOS 7, we install https://github.com/inverse-inc/packetfence/blob/020224f1d4e62644047c73e26637d3b51f005c06/packetfence.journald
