### ISSUE TITLE
Remove extra fields when importing users from AD

### ISSUE THREAD

**Issue by chrisbalmer** [inverse-inc/packetfence#6087]
**Describe the bug**
When importing a list of users via CSV from AD, a registration window has to be set, an ~~role~~ Access Level has to be set and a password is generated.

- Registration window: By default, AD accounts don't appear to have one if you're logging in for the first time via 802.1x.
- Same for the ~~role~~ Access Level field, if I log in with a new user via 802.1x from AD, the user is created and no ~~role~~ Access Level is listed.
- Password: The users are imported with the AD source so they should not require a password to be generated and emailed out. Looking at the password table, no passwords exist for users that show up after logging in for the first time with 802.1x, just imported AD users.

Since these fields are not needed when using 802.1x with AD, they should be optional when importing users with a source set to AD.

**To Reproduce**
1. Go to Users -> Import -> Open CSV File
2. Map the fields from the CSV file to the PF fields
3. Select source and assign it to your AD source

**Expected behavior**
No registration window, password or ~~role~~ Access Level filled in.

**Additional context**
Perhaps I am going about this the wrong way, but I am trying to assign some nodes (populated via DHCP) to AD users that have not logged in via 802.1x in advance and I am also trying to assign IPSKs to users so they can auth with that instead of using 802.1x. Both of these requires the users to show up in the users page before they login for the first time. PacketFence is not showing AD users unless they login for me and I can't find anything in the documentation on having AD users show up in this list prior to login so I am using the CSV import to get them listed.

This is on PacketFence 10.2

**Comment by julsemaan** [comment]
This page is made to import local accounts so that they can be authenticated directly from the PF local database so this is why you are required to add those.

Why would you import your AD users through that page in the first place ?
FYI, all users will appear in that page when they make their first authentication (either through 802.1x or through the portal)

**Comment by chrisbalmer** [comment]
That makes sense. I am trying to prepopulate the AD users so I can get service accounts from AD in PacketFence for IoT devices. I'm using DPSK which means I have to provide the PSK to the user, and assign the node to the user. For a guest device this is done via a portal. But for an IoT device, I need to script the process since it won't be able to go through the portal. I can't find a way to get an AD user to show up before an 802.1x login or portal registration though.

**Comment by julsemaan** [comment]
With DPSK, the device must be assigned to the existing user by manually registering the MAC address through the status page or some other mecanism. Only exception to that is Ruckus unbound DPSK for which there is no official support in PF yet.

This goes out of the scope of this bug tracker though, I suggest using the mailing list to discuss your deployment
