### ISSUE TITLE
MariaDB triggers are removed when doing a restore from backup

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6092]
**Describe the bug**
If you do a complete restore of your DB using a backup taken with `./addons/backup-and-maintenance.sh`, triggers are removed by restore.

**To Reproduce**
1. PacketFence server up and running with a recent DB backup
2. Apply following process:
```
mysql -e "drop database pf;"
mysql -e "create database pf;"
mysql pf < /usr/local/pf/db/pf-schema.sql 
mysql pf -e "show triggers;"
```

=> Triggers are present.

3. Restore your DB backup using:
```
mysql pf < /root/backup/packetfence-db-dump-2021-01-12_15h09.sql 
mysql pf -e "show triggers;"
```

=> Triggers have been removed.

**Expected behavior**
Triggers should be present after a restore.

**Additional context**
Only tested on a standalone environment

After some tests, triggers are not present in SQL file generated by backup script certainly because `pf` user doesn't have `TRIGGER` [privilege](https://mariadb.com/kb/en/show-triggers/). Using `root`, TRIGGERS are included into SQL file.

**Comment by nqb** [comment]
I can confirm that missing TRIGGER privilege is the root cause of the issue.

**Comment by nqb** [comment]
I suppose it's caused by the fact that when restoring, we destroy tables if they exists and triggers are certainly destroy too.

**Comment by nqb** [comment]
If you take a dump as `root` triggers are present but when you restore there is a conflict because triggers are part of `pf-schema.sql `

I suggest to remove triggers from backup.

**Comment by julsemaan** [comment]
The thing with that is that if you import the schema and then import the dump, it drops the tables before recreating them which drops the triggers too (at least on MariaDB 10.5)

The import/export scripts have workaround to cope with this, the solution to this issue may just be that we'll have proper import/export scripts in the future

**Comment by nqb** [comment]
I updated documentation to avoid confusion between backups taken as MariaDB user `root` or `pf`.

All backups should now be done using backup script and should not contain triggers and procedures (because they are made by  MariaDB user `pf`). Import script has been adjusted by @julsemaan to handle both cases.
