### ISSUE TITLE
ZEN live install 10.2.0 failed on create DB schema.

### ISSUE THREAD

**Issue by skydiablo** [inverse-inc/packetfence#6098]
**Describe the bug**
ZEN live install 10.2.0 failed on create DB schema.

**To Reproduce**
1. just follow the installer, create DB schema will fail

**Additional context**
log output:
row to long, greater 8k

this occured by trying to `CREATE TABLE wrix` https://github.com/inverse-inc/packetfence/blob/2701ff99cb22905d5b4a707abb4188be29d7f952/db/pf-schema-10.2.0.sql#L1075

IMHO: some of this fields can reduced in size, so a MAC-adress will never be greater that 17 chars?

volker.

**Comment by jrouzierinverse** [comment]
By any chance did you upgrade the Mariadb version on the Zen machine?

**Comment by jrouzierinverse** [comment]
The problem is the version of Mariadb that was installed was not the correct version I will bring this up to the appropriate person.

**Comment by nickmaleao** [comment]
> The problem is the version of Mariadb that was installed was not the correct version I will bring this up to the appropriate person.

Can you please share what is the correct Mariadb version? I'm testing Packetfence for the first time and got the same error :(

**Comment by fdurand** [comment]
Just replicate the issue and it's because of innodb_strict_mode=ON, if we set it OFF then we can create the schema.

What i can probably do is to set it to off in the mariadb configuration when creating the usb key.

**Comment by fdurand** [comment]
Uploaded a new usb key.
