### ISSUE TITLE
Default ordering of the RADIUS Audit log is wrong

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6101]
**Describe the bug**
When navigating to the RADIUS Audit log, the entries are not ordered by 'created_at DESC'

**To Reproduce**
1. Have a few RADIUS audit log entries
2. Navigate to Auditing

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/105045153-91c05680-5a35-11eb-8631-07a8924f91cf.png)

**Expected behavior**
Entries should appear from the most recent to the oldest

**Comment by nqb** [comment]
Related to #6090

**Comment by satkunas** [comment]
@julsemaan #6090 is resolved. Please retest to confirm fix.

**Comment by nqb** [comment]
Issue is not present anymore, closing.
