### ISSUE TITLE
web admin: switches view is horribly slow with many roles

### ISSUE THREAD

**Issue by ptrrkssn** [inverse-inc/packetfence#6104]
**Describe the bug**
The web admin switches view (Configuration - Policies -> Switches) is horribly slow / unusable if you have many role -> VLAN mappnings defined. Current we have around 90 xxxVlan=VLAN lines under "default" and them some overridden rules per switch.
Trying to open the Switches web page is horribly slow.

**To Reproduce**
Put many rules into conf/switches.conf and try to access the web UI.

**Screenshots**
It eventually loads, after giving a couple of warnings about slow web pages.

**Expected behavior**
It should be usable...

**Desktop (please complete the following information):**
 - Linux
 - Firefox
 - Version 84.0
(also tried other browsers)

PacketFence version: 10.2.0

**Comment by julsemaan** [comment]
Hi, thanks for the report, this is a known issue of the v10.x release.

There is unfortunately no easy fix for this and @satkunas is currently refactoring all the configuration section to improve the speed (especially for the switches)

This will get done for version 11.0 which will be out shortly

**Comment by satkunas** [comment]
Performance was improved in #6397
