### ISSUE TITLE
Documentation missing for pf-maint.pl

### ISSUE THREAD

**Issue by BenB196** [inverse-inc/packetfence#6107]
**Describe the bug**
Currently pf-maint.pl exists and is used to to update PF stuff outside of versioned releases. However, this script isn't really documented on how to properly use.

Looking at:
- https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html
- https://www.packetfence.org/doc/PacketFence_Clustering_Guide.html
- https://www.packetfence.org/doc/PacketFence_Installation_Guide.html

pf-maint.pl is not mentioned within any of these docs, however, it would greatly help to include them as running the script is actually required in some in some cases.

A few things that I think would be good to have documentation around:

- When should pf-maint.pl be run during an upgrade?
- How do you go about running pf-maint.pl in a cluster to not result in down time, and when not doing a version upgrade.
- Where is pf-maint.pl located?
- Where can one find the changes the pf-maint.pl receives (changelog)?

The only documentation I've been able to find regarding this script is in the script [itself](https://github.com/inverse-inc/packetfence/blob/devel/addons/pf-maint.pl) and it doesn't really answer any of the questions I've posed.

**Comment by nqb** [comment]
Hello @BenB196,

Thanks for your detailed report.

I add some documentation related to pf-maint.pl in #5995. This PR should be merged for v11. I will take your notes into account.

**Comment by nqb** [comment]
In fact, some [documentation](https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Upgrade_Guide.asciidoc#maintenance-patches) were added in another PR but I plan to adjust things related to pf-maint.pl in #5995
