### ISSUE TITLE
Golang unit tests failed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6108]
**Describe the bug**
Since merge of #6083 and after upgrade to Golang 1.15 (see #6044).

Golang unit tests in failed state.

Latest pipeline: https://gitlab.com/inverse-inc/packetfence/-/jobs/988996303#L285

**Comment by nqb** [comment]
There is still some issues with Golang unit tests: https://gitlab.com/inverse-inc/packetfence/-/jobs/991459167#L898

I also noticed an additional Golang unit test that failed on Debian (go/caddy/wgorchestrator) and not on CentOS: https://gitlab.com/inverse-inc/packetfence/-/jobs/991459176#L545

**Comment by jrouzierinverse** [comment]
This is fixed by dee02f460c407f77830cc03cb114667a692b3812 647a2fb638a0aca886549e6ee60cb70eea045d05 b8caaa8b40a59800725947996d59b688faa74917

**Comment by nqb** [comment]
Issue is fixed on CentOS 7 but one Golang unit test on Debian is still in failed state (go/caddy/wgorchestrator). See https://gitlab.com/inverse-inc/packetfence/-/jobs/998286330#L547

**Comment by nqb** [comment]
@jrouzierinverse: still failing on Debian.

**Comment by nqb** [comment]
No more relevant since merge of #6161
