### ISSUE TITLE
Web - SSL configuration

### ISSUE THREAD

**Issue by jcz1** [inverse-inc/packetfence#6122]
Hello.

wget https://www.packetfence.org on up-to-date Debian stable with all system certs had "ERROR: The certificate of ‘www.packetfence.org’ is not trusted" so i run test on ssllabs and results are:

This server's certificate chain is incomplete. Grade capped to B. 
This server supports TLS 1.0 and TLS 1.1. Grade capped to B.
...
https://www.ssllabs.com/ssltest/analyze.html?d=packetfence.org

**Comment by cgx** [comment]
Fixed.

**Comment by jcz1** [comment]
Thumbs up :)
