### ISSUE TITLE
ZEN for XEN (and others)

### ISSUE THREAD

**Issue by jcz1** [inverse-inc/packetfence#6123]
Please is there any plan to support ZEN (Virtual Appliance) for other virt. platforms than VMWare, for example XEN? It would be great to run opensource on opensource virtualization platform :)
Thanks.

**Comment by nqb** [comment]
Hello @jcz1,

What do you need to run ZEN on a Xen platform ? OVA should work with minor adjustements.

**Comment by jcz1** [comment]
Do you mean some conversion tool? And what about future, updates etc? Why not support Xen if it is almost the same image.

**Comment by nqb** [comment]
> Do you mean some conversion tool? And what about future, updates etc? Why not support Xen if it is almost the same image.

Sorry if I was unclear. 

In fact, my question is: did you already try to install PacketFence_ZEN.ova on a XEN platform ? Because we package it as a [virtual appliance](https://en.wikipedia.org/wiki/Virtual_appliance) so I suppose you can directly use it on Xen platform.

**Comment by jcz1** [comment]
OK, what i did with official image:

1. unzip
2. untar (because ova is a tar archive)
3. convert vmdk to cow2:
  qemu-img convert -p PacketFence-ZEN-v10.2.0-disk1.vmdk -c -O qcow2 pf.qcow2

PVH in xen (Deb10) not working at all:
  image not capable of booting inside a HVM container: Invalid kernel

PV is working (booting), but without pty. There is no dhcp, so no network.

packetfence.cfg:
name = 'packetfence'
bootloader = 'pygrub'
vcpus = 2
memory = 2048
disk = [ '.../pf.qcow2,qcow2,sda,rw' ]
vif = [ 'mac=..., bridge=brX' ]
type = 'pv'

**Comment by nqb** [comment]
Hello, with #6803 (ISO installer), you should be able to install PacketFence on any hypervisor.
