### ISSUE TITLE
Pfqueue polling needed for system service API endpoints

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#6128]
**Describe the bug**
We currently use a timer and limited polling when restarting `haproxy-admin` during the final setup step in the configurator. This should be changed to pfqueue polling to ensure requests that take longer than expected are handled gracefully.

example: `POST /api/v1/configurator/service/haproxy-admin/restart`

Ensure that when `haproxy-admin` terminates that the response code from the pfqueue poll differs than other errors so the UI can handle the difference between a service interrupt (to self) and a regular exception. I assume a service interrupt will generate a 404, so we should avoid using a 404 for other reasons.

**Comment by jrouzierinverse** [comment]
This has been fixed in 279fc946947a59351dbdb8c74c6c19346b7d3890
