### ISSUE TITLE
pfcmd test mysql tuner is outdated

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6130]
**Describe the bug**
The MySQL tuner shipped with PF is old and outdated. 

Also it doesn't work correctly when the value in pf.conf is 127.0.0.1

We should refresh this pfcmd tool and ensure it works correctly in cluster too

**Comment by jrouzierinverse** [comment]
The issue with the 'mysql tuner' command is when it is not localhost defined it expects the memory of the machine you are tuning.
To future proof the 'mysql tuner' command it should be a simple wrapper to the mysqltuner.pl.
This will make updating it easier in the future.

**Comment by extrafu** [comment]
Out of curiosity do we still use it? If it has so bitrotted, most likely no-one uses it and I don't see why we should keep this.

We have been generating the MySQL (MariaDB) configuration on the fly for a little while now so I don't think hand-tuning is necessary. Anyway if someone is skilled enough to tune manually MariaDB, they are skilled enough to get and run that tool. That's my 2 cents.

**Comment by julsemaan** [comment]
This was coming from one of the customers that tried to use it and it was broken.

I'm fine with either removing it or updating it personally as long as we don't ship something broken.

I think @jrouzierinverse already did the work to refresh the integration anyway

Also, @jrouzierinverse, did you ensure that the tool will work in a cluster. As this issue states, the tool doesn't work when the DB in pf.conf points to 127.0.0.1 (i.e. in cluster mode)

**Comment by extrafu** [comment]
IMO, we should drop it - less thing to include and maintain.

But you guys decide :)

**Comment by julsemaan** [comment]
I'd personally be happy to drop it since I agree that we won't have to keep maintaining it and if someone needs it, he just needs to get the tool himself, its not rocket science anyway

**Comment by jrouzierinverse** [comment]
I made maintaining this as "easy" as running a script https://github.com/inverse-inc/packetfence/pull/6132/files#diff-25900f3888dc00e3a2be35ccd84612c321961aa43a05f81b8b045261aa4157adR1

Would could add running that script to our pre-release process.

I did not test this in a cluster however the newer versions have support for Galera replication.
https://github.com/major/MySQLTuner-perl/blob/master/README.md
