### ISSUE TITLE
Need to publish the Zero Trust clients

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6142]
**Describe the bug**
The Zero Trust clients aren't currently bundled in the PacketFence installation which prevents download of the agent from the portal. We need to either bundle the installers in the PF install or make the agents available publicly somewhere and adjust the provisioner configuration to point to them

A good place to host them would be: https://inverse.ca/downloads/PacketFence/Zero-Trust-Clients/...

**Comment by fdurand** [comment]
Maybe more https://packetfence.org/downloads/PacketFence/Zero-Trust-Clients/...

**Comment by fdurand** [comment]
We should probably offer the internet link by default.
Then if you want to have a custom client then you can upload it on the pf server itself and change the link to download it.

**Comment by extrafu** [comment]
> We should probably offer the internet link by default.
> Then if you want to have a custom client then you can upload it on the pf server itself and change the link to download it.

I agree on this - and we should also use packetfence.org in the URL, not inverse.ca

**Comment by extrafu** [comment]
Closing for now.
