### ISSUE TITLE
Cisco 9300

### ISSUE THREAD

**Issue by pavit04** [inverse-inc/packetfence#6157]
When implementing dot1x authentication on cisco9300 catalyst switches, PacketFence assigns the role to node but it not gets assigned.
But when debugging dot1x events, we came across a message 

%SESSION_MGR-5-FAIL: Switch 1 R0/0: sessmgrd: Authorization failed or unapplied for client (XXXX.XXXX.XXXX) on Interface GigabitEthernet1/0/28 AuditSessionID 1180FC0A00000047DE238CC2. Failure reason: Authc fail.

What does this event indicate ?

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
