### ISSUE TITLE
API endpoint /locationlog/{locationlog_id} doesn't seem to exist

### ISSUE THREAD

**Issue by tgBryanBailes** [inverse-inc/packetfence#6168]
Using PacketFence 10.2.0

[GET /locationlog/{locationlog_id}](https://www.packetfence.org/doc/api/#/default/api.v1.Locationlogs.get) doesn't seem to exist. Digging through the source, it looks like the primary_key was recently changed to use the mac field, but attempting this always results in the following, even when confirming that a locationLog does exist for the mac:
```
{
    "errors": [],
    "message": "Unknown path /api/v1/locationlog/{mac}",
    "status": 404
}
```

Is there any known fix or workaround for this?

**Comment by jrouzierinverse** [comment]
You could use the /api/v1/locationlogs/search endpoint as a work around.

POST   /api/v1/locationlogs/search ```{ "query" : { "op" : "equals", "field" : "mac", "value" :  "01:02:03:04:05:06"} }```

```
{
  "items": [
    {
      "connection_sub_type": "test connection_sub_type",
      "connection_type": "test connection_type",
      "dot1x_username": "test dot1x_username",
      "end_time": "0000-00-00 00:00:02",
      "ifDesc": "test ifDesc",
      "mac": "01:02:03:04:05:06",
      "port": "73",
      "realm": "test realm",
      "role": "test role",
      "session_id": null,
      "ssid": "test ssid",
      "start_time": "0000-00-00 00:00:01",
      "stripped_user_name": "test stripped_user_name",
      "switch": "0.0.0.1",
      "switch_ip": "0.0.0.2",
      "switch_ip_int": "2",
      "switch_mac": "06:07:08:09:0a:06",
      "tenant_id": "1",
      "vlan": "6",
      "voip": "no"
    }
  ],
  "prevCursor": 0,
  "status": 200
}
```

In the next version of PacketFence we will add that endpoint.
