### ISSUE TITLE
Caught Exception in Captive Portal::Controller::CaptivePortal>Unknown state

### ISSUE THREAD

**Issue by Sletheren** [inverse-inc/packetfence#617]
![screenshot_1](https://cloud.githubusercontent.com/assets/12659402/7882558/9cce29be-0606-11e5-86b4-473394bac429.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12659402/7882559/9cdb964e-0606-11e5-88d7-343e31a6689f.png)

After Setting up the Inline mode and registering a test user I tried to access my own Web server, but I got this Error! Anyone can help please?

**Comment by julsemaan** [comment]
PF version ?

**Comment by Sletheren** [comment]
it's the latest 5.1.0

**Comment by julsemaan** [comment]
Not sure how this can happen on 5.1 as it was fixed previously and I double checked the code to make sure

Do you have any custom code in `html/captive-portal/lib/captiveportal/Controller/CaptivePortal.pm` ?

Please post the content of `html/captive-portal/lib/captiveportal/Controller/CaptivePortal.pm` and `html/captive-portal/lib/captiveportal/PacketFence/Controller/CaptivePortal.pm` here using pastebin or another tool that you prefer

**Comment by Sletheren** [comment]
I've solved the error by turning the DNS server on!
I guess the problem was when I try to access the web page on my web server using the FQDN while the dns server is down
Thanks a lot!

**Comment by Sletheren** [comment]
I've solved the error by turning the DNS server on!
I guess the problem was when I try to access the web page on my web server using the FQDN while the dns server is down
Thanks a lot!
