### ISSUE TITLE
configurator: GUI doesn't start PacketFence services

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6174]
**Describe the bug**
At end of configurator, when you click on "Start PacketFence", GUI doesn't start services.

**To Reproduce**
1. Go at end of configurator
2. Click on 'Start PacketFence'

Two API calls are sent:
- POST | https://pfdeb9dev.example.lan:1443/api/v1/configurator/system_service/packetfence-config/restart
- POST | https://pfdeb9dev.example.lan:1443/api/v1/configurator/service/pf/update_systemd

But there is no API call to restart `pf` service.

**Expected behavior**
PacketFence services are restarted, configurator disabled, redirect to login page.

**Comment by satkunas** [comment]
Partial fix in c74ee00ae981a607b8468fa81d66ad84b68d8682

**Comment by nqb** [comment]
At the moment, when calling `/poll` for `haproxy-admin` restart task, we don't get any answer from backend.

**Comment by fdurand** [comment]
Looks to be because haproxy-admin is restarting, so https://172.20.21.57:1443/api/v1/configurator/pfqueue/task/ApiTask:35B77C0C-8B12-11EB-BCEC-2367369DD453/status/poll is not available 

![image](https://user-images.githubusercontent.com/1553962/111997106-13de0180-8af1-11eb-96ae-fdff037a5c6a.png)

**Comment by nqb** [comment]
@jrouzierinverse and @satkunas, how do you want to solve that issue ?

Is there any way to call directly API for use case mentioned by @fdurand ?

**Comment by satkunas** [comment]
@jrouzier pfqueue poll endpoint is returning an error on /api/v1/configurator:

1:
```
>>>
POST /api/v1/configurator/service/haproxy-admin/restart 
{async: true}

<<<
202
{"status":202,"task_id":"ApiTask:0137BF6C-914F-11EB-B708-A9D08C87560F"}
```

2:
```
>>>
GET /api/v1/configurator/pfqueue/task/ApiTask:0137BF6C-914F-11EB-B708-A9D08C87560F/status/poll

<<<
[empty response] / error
```
