### ISSUE TITLE
web admin: when creating a user valid_from date is set to 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6175]
**Describe the bug**
When you create a user, there is no value for `valid_from` field.

GUI will send `0000-00-00 00:00:00` date to backend. It's a problem because GUI will complain about that date when you edit your user.

**To Reproduce**
1. Create a user without `valid_from` date
2. Edit your user

=> You got following warning: `Date must be today or later.`

**Expected behavior**
`valid_from` is auto-filled when creating a user.

**Comment by satkunas** [comment]
@nqb changes made in 39815b5c045af1e0846d7c2b6277f2eb0f5381a8

**Comment by satkunas** [comment]
@nqb please retest

**Comment by nqb** [comment]
Works as expected.
