### ISSUE TITLE
web admin: import users using a CSV doesn't work

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6176]
**Describe the bug**
I tried to import a list of users using a CSV. All goes well but my users are not created.

**To Reproduce**
1. Create a CSV files with 100 users:
```
for number in $(seq 1 100); do echo "testimport$number;pwd$number;$number@inverse.ca;$number;Inverse;" >> testimport.csv; done
```
2. Import this file 
3. Check User menu or DB

=> Users not created.

**Expected behavior**
100 users created

**Additional context**
Frontend is calling API like this: 

- API call: `POST https://pfdeb9dev.example.lan:1443/api/v1/users/bulk_import`
- JSON payload
```json
{"ignoreInsertIfNotExists":true,"ignoreUpdateIfExists":false,"items":[],"stopOnFirstError":true}
```

Answer:
```json
{"items":[],"status":200}
```

=> It looks like `items` doesn't contain data in JSON payload

**Comment by satkunas** [comment]
| `{"ignoreInsertIfNotExists":true, ... }`

Rows are being ignored

```json
{
    "items": [{
        "isNew": true,
        "item": ...,
        "message": "Skip does not exists",
        "status": 404
    }
```

**Comment by satkunas** [comment]
The import option toggles were inverted. Changed in d1a5cf71b4a9729f82ce83eb16f050a2b3f33bea
