### ISSUE TITLE
web admin: roles doesn't exist when importing nodes or users

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6178]
**Describe the bug**
If you try to import a list of nodes using a CSV and you want to assign a fixed role to each node, you can't.

**To Reproduce**
1. Create a CSV file with 90 nodes:
```
for number in $(seq 10 99); do echo "9c:b6:d0:fe:69:$number;default;guest;`date +'%Y-%m-%d %H:%M:%S' --date='next Sunday'`;node$number" >> testimport_nodes.csv; done
```
2. Try to import this file with:
- third column ignored
- Role as a static field

You got this result:

![Capture d’écran de 2021-03-17 15-31-45](https://user-images.githubusercontent.com/10830260/111484806-5e98fb80-8736-11eb-9794-3d65c0607d12.png)

**Expected behavior**
Role can be assigned.

**Additional context**
I see an API call to `node_categories` in web browser console before I enter in Import menu.

If I tried to import nodes using a role name or ID from my CSV file, it doesn't work:
- with ID of role in CSV file: frontend says roles doesn't exist
- with name of role in CSV file: backend returns a 404 for all nodes with message: "Skip does not exists"

**Comment by satkunas** [comment]
Unable to reproduce. Working in Users/Nodes import, both csv mapped and static. More info needed.

**Comment by nqb** [comment]
Looks ok now.

**Comment by nqb** [comment]
Reopening because issue is still presents.

Now, I'm able to create users or nodes if role is defined in CSV file as a string (not an ID). However, if I defined role as a static field in GUI, I got same result as in screenshot (see above).

**Comment by satkunas** [comment]
Re-tested. I'm still not able to reproduce.

**Comment by satkunas** [comment]
@jrouzierinverse There's appears to be a difference in the in the `/api/v1/current_user/allowed_node_roles` response between CentOS and Debian. CentOS casts `category_id` as a string, where Debian casts it as an integer.

We'll need to ensure that `category_id` is sent as a string on Debian with all Roles endpoints to address the issue above.

CentOS:
```
{
    "items": [
        {
        "category_id": "1",
        ...
        },
        ....
    ]
}       
```

Debian:
```
{
    "items": [
        {
        "category_id": 1,
        ...
        },
        ....
    ]
}       
```

**Comment by nqb** [comment]
@jrouzierinverse, let me know if you need me to send output from Debian.

**Comment by jrouzierinverse** [comment]
The issue is most likely caused by the different version of the perl DBD::mysql between CentOS and Debain.

**Comment by jrouzierinverse** [comment]
@satkunas at the moment what are you expecting?

**Comment by satkunas** [comment]
@jrouzierinverse  we need a consistent JSON type-cast for `category_id` on CentOS and Debian.

**Comment by jrouzierinverse** [comment]
@satkunas this is done what else needs to be done?

**Comment by satkunas** [comment]
@nqb please retest w/ Debian.

**Comment by nqb** [comment]
Issue still presents on Debian.

JSON payload returned by `/api/v1/current_user/allowed_node_roles`:
```json
{
  "items": [
    {
      "acls": "",
      "category_id": 1,
      "fingerbank_dynamic_access_list": "disabled",
      "include_parent_acls": "disabled",
      "inherit_role": null,
      "inherit_vlan": null,
      "inherit_web_auth_url": null,
      "max_nodes_per_pid": 0,
      "name": "default",
      "notes": "Placeholder role/category, feel free to edit"
    },
    {
      "acls": "",
      "category_id": 3,
      "fingerbank_dynamic_access_list": "disabled",
      "include_parent_acls": "disabled",
      "inherit_role": null,
      "inherit_vlan": null,
      "inherit_web_auth_url": null,
      "max_nodes_per_pid": 0,
      "name": "gaming",
      "notes": "Gaming devices"
    },
    {
      "acls": "",
      "category_id": 2,
      "fingerbank_dynamic_access_list": "disabled",
      "include_parent_acls": "disabled",
      "inherit_role": null,
      "inherit_vlan": null,
      "inherit_web_auth_url": null,
      "max_nodes_per_pid": 0,
      "name": "guest",
      "notes": "Guests"
    },
[..]
  ],
  "status": 200
```

**Comment by jrouzierinverse** [comment]
They are all now returned as strings

**Comment by nqb** [comment]
Issue is solved on Debian. `category_id` and `max_nodes_per_pid` are returned as strings by API for ` /api/v1/current_user/allowed_node_roles`

@jrouzierinverse, I will let you create an issue related to upgrade of perl-DBD::mysql driver for v11 release.
