### ISSUE TITLE
WebAdmin: Error in realm

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6183]
**Describe the bug**
When i try to create a realm this message appear:

![image](https://user-images.githubusercontent.com/1553962/111508408-0d7f0c80-8722-11eb-8159-3317187d3687.png)

**Comment by satkunas** [comment]
Not a JS error. perl @jrouzierinverse?

**Comment by jrouzierinverse** [comment]
This is a api-frontend error.
Check if the X-PacketFence-Tenant-Id is being sent.
