### ISSUE TITLE
WebAdmin: choice box in general

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6186]
**Describe the bug**

Not really a bug but can we do something with the bar ?

![image](https://user-images.githubusercontent.com/1553962/111511137-d3fbd080-8724-11eb-8796-8ac68f7d499d.png)

**Comment by cgx** [comment]
I can't reproduce this issue with neither Chrome, Firefox, nor Safari. What's your browser?

**Comment by fdurand** [comment]
chrome

**Comment by fdurand** [comment]
firefox too
