### ISSUE TITLE
WebAdmin: switch group selection when creating a switch group

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6187]
**Describe the bug**
We should remove the switch group selection when you create/edit a switch group

![image](https://user-images.githubusercontent.com/1553962/111516653-86826200-872a-11eb-8021-278482753905.png)

**Comment by satkunas** [comment]
@fdurand IIRC we support inheritance. @jrouzierinverse can you verify?

**Comment by jrouzierinverse** [comment]
No switch group for switch groups.

**Comment by fdurand** [comment]
Also the first field (IP Address/MAC Address/Range (CIDR) should be switch group name
