### ISSUE TITLE
WebAdmin: Switch group create add always_trigger=1 in the configuration

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6188]
**Describe the bug**
When you create a new switch group and save it , the configuration parameter always_trigger=1  is added in the configuration file.

![image](https://user-images.githubusercontent.com/1553962/111517736-c6961480-872b-11eb-87f6-be8dc299543c.png)

**Comment by jrouzierinverse** [comment]
Is always_trigger still used?
