### ISSUE TITLE
graphite db host is always 127.0.0.1 in cluster mode

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#619]
This means when in clustering we can't use an external database.

We should always use monitoring db host and add a note in the cluster guide to configure it to 127.0.0.1 when configuring the cluster

**Comment by louismunro** [comment]
Would we not want to be using HA-proxy anyway? 
In any case, yes corners were cut to get this tested and out in time for 5.1.
There is room for improvements. I will target 5.3 for this.

**Comment by julsemaan** [comment]
Fixed in 55e26d6dceeb1b638df82db6293391fb47ac91c4

**Comment by louismunro** [comment]
I like it when someone does my work for me...
