### ISSUE TITLE
WebAdmin: PKI Certificate authority

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6192]
**Describe the bug**

On create the page after the is empty. We should have the CA we just created.

![image](https://user-images.githubusercontent.com/1553962/111524510-e3821600-8732-11eb-9658-b1865214c48a.png)

**Comment by JeGoi** [comment]
I can confirmed.
The ca is created but it return undefined.
You can reopen it from the list without problem.

**Comment by satkunas** [comment]
Issue appears to have been resolved, not able to reproduce. Please re-test.

**Comment by cgx** [comment]
I had this error when the `pki_cas` table was missing. I've created it and it fixed the problem.

I think we can close this issue.
