### ISSUE TITLE
WebAdmin: PKI profile unable to create

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6194]
**Describe the bug**
i can't create a pki profile, there is a javascript error:

![image](https://user-images.githubusercontent.com/1553962/111528332-66a56b00-8737-11eb-99fd-1fee57df78f4.png)

**Comment by satkunas** [comment]
I'm not able to reproduce this error. I did fix one issue on this page in a2d0347cb6b2ab37537dfe08d82eb407a2874a30

Please retest

**Comment by fdurand** [comment]
Confirmed fixed
