### ISSUE TITLE
WebAdmin: Default ghost values

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6195]
**Describe the bug**
Advanced Access Configuration -> Captive portal -> Captive Portal detection mechanism URLs should be emtpy.

![image](https://user-images.githubusercontent.com/1553962/111530066-3f4f9d80-8739-11eb-82b8-026f566fab37.png)

**Comment by satkunas** [comment]
This is a placeholder coming from meta.


```
# /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/base/captive_portal | jq '.meta.detection_mecanism_urls.placeholder'
"http://www.gstatic.com/generate_204,http://clients3.google.com/generate_204,http://www.apple.com/library/test/success,http://connectivitycheck.android.com/generate_204,http://connectivitycheck.gstatic.com/generate_204,http://www.msftncsi.com/ncsi.txt,http://www.appleiphonecell.com,http://captive.apple.com,http://captive.roku.com/ok,http://detectportal.firefox.com/success.txt,http://www.msftconnecttest.com/connecttest.txt,http://fireoscaptiveportal.com/generate_204,http://connectivitycheck.cbg-app.huawei.com/generate_204,http://connect.rom.miui.com/generate_204,http://freetimecaptiveportal.com/generate_204,http://gateway.zscalerthree.net/generate_204,http://gateway.zscloud.net/generate_204,http://g.cn/generate_204,http://play.googleapis.com/generate_204,http://speedtest-global.spatialbuzz.net/generate_204,http://tabletcaptiveportal.com/generate204,http://www.google.cn/generate_204"
```

If we want to avoid populating the placeholder with defaults, we'll need to move this to a new meta property.

**Comment by satkunas** [comment]
@fdurand @jrouzierinverse how do we want to proceed?

**Comment by jrouzierinverse** [comment]
What should be the name of the field instead of placeholder?

**Comment by satkunas** [comment]
@jrouzierinverse and I agree to utilize a new key in order to communicate additional context - such as this one - from the backend. Since this bug is cosmetic and doesn't "break" the ui, but making the proposed change may introduce regressions I am moving the milestone post 10.3.
