### ISSUE TITLE
WebAdmin: DHCP Filter options are empty

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6196]
**Describe the bug**

Answer can't be defined:

![image](https://user-images.githubusercontent.com/1553962/111531103-7bcfc900-873a-11eb-9ed5-564077ed2f36.png)

**Comment by satkunas** [comment]
@jrouzierinverse allowed options are empty in `dhcp_filters`:

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/dhcp_filters | jq '.meta.answers.item.properties.prefix.allowed'
null
```

However, present in other collections like `radius_filters`:

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/radius_filters | jq '.meta.answers.item.properties.prefix.allowed'
[
  {
    "text": "Request",
    "value": "request"
  },
  ...
]
```

**Comment by satkunas** [comment]
@jrouzierinverse disregard my last comment. I see that there's some ui work needed to hide/show the `prefix` in these cases and rely on `type` and `value` only.
