### ISSUE TITLE
WebAdmin Configurator: Automatic DB Issues

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6199]
**Describe the bug**
Select Automatic for setting DB Go to next step. Come back. Fields are empty.
If you add a new password for the db, clic verify. 
You restart from step1. Go to step 2, DB informations are here.

**To Reproduce**
1. At step2 select auto for db
2. At step3 go back to step2
3. Try to add password for db because it is empty, and clic verify
4. Go back on step 1
5. Now on step2, DB info are filled 

**Expected behavior**
From step3 to step2, if Automatic Configuration is selected, I should have DB fields filled when i come back to that step.

**Comment by jrouzierinverse** [comment]
I think this is on @satkunas

**Comment by JeGoi** [comment]
Ok James. Thanks.
Hum, it looks like the admin field is also back to empty field.

**Comment by JeGoi** [comment]
With back and forth, at the last step, the root password is missing.
