### ISSUE TITLE
WebAdmin: configurator enable, not redirect to the configurator.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6202]
**Describe the bug**
When i enable the configurator and going on the root of the admin :1443/ i am redirected to the admin gui and not the configurator.

Just not sure that was the case before.

**Comment by fdurand** [comment]
Looks to be related to a cache /timeout

**Comment by cgx** [comment]
Make sure to logout first to access the configurator.

**Comment by fdurand** [comment]
yes you are true.
