### ISSUE TITLE
pfacct doesn't start if ipt_netflow is not loaded

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6205]
**Describe the bug**
Device are not unregistered based on Acct-Stop message (during integration tests) since 19/03.

It seems to be caused by https://github.com/inverse-inc/packetfence/commit/1d60b1378cc8a8fe14464c5a12057e50f9aaedda

See following job: https://gitlab.com/inverse-inc/packetfence/-/jobs/1116036577#L2028

**Comment by nqb** [comment]
In fact, issue seems to be caused by merge of #6139 because I see following messages in logs:

```console
# journalctl -u packetfence-pfacct
mars 22 04:21:52 pfcen7dev systemd[1]: Starting PacketFence GO Accounting Server Daemon...
mars 22 04:21:53 pfcen7dev packetfence[27063]: pfcmd.pl(27063) DEBUG: invalid IP:  from cluster::__ANON__ (pf::util::valid_ip)
mars 22 04:21:53 pfcen7dev packetfence[27063]: pfcmd.pl(27063) ERROR: sysctl: cannot stat /proc/sys/net/netflow/destination: No such file or directory
                                               kernel module ipt_NETFLOW is not configured or loaded (pf::cmd::pf::confignetflow::_run)
mars 22 04:21:53 pfcen7dev pfcmd[27063]: sysctl: cannot stat /proc/sys/net/netflow/destination: No such file or directory
mars 22 04:21:53 pfcen7dev pfcmd[27063]: kernel module ipt_NETFLOW is not configured or loaded
mars 22 04:21:53 pfcen7dev systemd[1]: packetfence-pfacct.service: control process exited, code=exited status=255
mars 22 04:21:53 pfcen7dev systemd[1]: Failed to start PacketFence GO Accounting Server Daemon.
mars 22 04:21:53 pfcen7dev systemd[1]: Unit packetfence-pfacct.service entered failed state.
mars 22 04:21:53 pfcen7dev systemd[1]: packetfence-pfacct.service failed.
mars 22 04:21:53 pfcen7dev systemd[1]: packetfence-pfacct.service holdoff time over, scheduling restart.
mars 22 04:21:53 pfcen7dev systemd[1]: Stopped PacketFence GO Accounting Server Daemon.
```

**Comment by nqb** [comment]
`ipt_netflow` was correctly built during PacketFence installation. When I boot again this VM, `pfacct` started correctly because module was loaded.

**Comment by jrouzierinverse** [comment]
The issue most likely caused by ipt_NETFLOW not loading properly and not 1d60b13.
Should we allow pfacct to run if sysctl returns a failure.

**Comment by nqb** [comment]
@jrouzierinverse,

Current issue is: `ipt_netflow` is not loaded until your reboot your machine or load module directly using `insmod`. It prevents `pfacct` to start because `/usr/local/pf/bib/pfcmd confignetflow` command failed.

In the past, `ipt_netflow` was loaded directly after PacketFence installation but it seems that it's not the case anymore. Certainly due to #6080.

To be consistent, we should:
- try to modify `netflow` address only if netflow is enabled in PacketFence config. As suggested by @fdurand, we can reuse [neflow_enabled function](https://github.com/inverse-inc/packetfence/blob/f0a83e2cb82722b80fda70ad6c451b2288fb5f05/lib/pf/iptables.pm#L814) function
- ensure `ipt_netflow` module is loaded in kernel before running `sysctl` command
