### ISSUE TITLE
WebAdmin: save unreg node twice produce an error.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6207]
**Describe the bug**

Edit a node, set it as unreg, save it twice.

![image](https://user-images.githubusercontent.com/1553962/112034843-50bbef80-8b15-11eb-8df4-e8ca6b2417d1.png)

packetfence.log:

Mar 22 13:48:12 localhost packetfence: pfperl-api(7526) WARN: Warning: 1265: Data truncated for column 'unregdate' at row 1 (pf::dal::db_execute)

**Comment by jrouzierinverse** [comment]
I am unable to replicate this.

**Comment by fdurand** [comment]
I still have it on the latest devel, i can show you if needed.

**Comment by jrouzierinverse** [comment]
Can you post the payload?

**Comment by nqb** [comment]
As @fdurand mentioned on #6243, I'm able to replicate like this:

1. Create a registered node with guest role (without unreg date)
2. Save
3. Unregistered your device and save
