### ISSUE TITLE
WebAdmin: Missing button in node

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6218]
**Describe the bug**
It miss some button when you edit a role:

Before:

![image](https://user-images.githubusercontent.com/1553962/112196103-10c23e80-8be1-11eb-92b8-ca6d1dc4d4c8.png)

After:

![image](https://user-images.githubusercontent.com/1553962/112196144-1fa8f100-8be1-11eb-8526-5a5b09f6f776.png)

**Comment by cgx** [comment]
The buttons are now placed under the proper tab.

**Comment by fdurand** [comment]
At least can we have "Reevaluate Access" back or duplicate in the first tab ?
