### ISSUE TITLE
web admin: a password defined in a switch group is not hidden when browsing a member

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6235]
**Describe the bug**
If you defined a RADIUS shared secret in a switch group and create a member of this switch group without redefining shared secret, shared secret will not be hidden when you browse switch group.

**To Reproduce**
1. Create a switch group with a RADIUS shared secret
2. Create a switch based on switch group created at previous step (don't define RADIUS shared secret)
3. Browse switch

=> Password is not hidden by stars

**Expected behavior**
Password hidden by stars.

**Comment by satkunas** [comment]
@jrouzierinverse can you please mask this on the backend?

```
/usr/local/pf/sbin/pfperl`-api get -M OPTIONS /api/v1/config/switch/1.2.3.4%2F24 | jq '.meta.radiusSecret.placeholder'
"supersecretpassword"
```
