### ISSUE TITLE
Webadmin configuration: Failure when manually configuring DB settings

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6236]
**Describe the bug**
When you try to configure the DB manually, it refreshes the page in the middle of the process

**To Reproduce**
1. Go through Step 1
2. Unselect Automatic configuration for the DB
3. Set a root password (I used `inverse`)
4. Click "Create" under the DB name
5. It will refresh the page and bring you back to step 1

**Expected behavior**
Should allow me to create the DB and continue instead of refreshing the page

**Comment by satkunas** [comment]
Not able to reproduce. There's no redirect after verifying the root password.

![Screen Shot 2021-03-30 at 4 07 38 PM](https://user-images.githubusercontent.com/3904468/113049857-2354ee80-9172-11eb-9f53-de63bee5279e.jpg)

**Comment by julsemaan** [comment]
Its when you click create under the database:

> Click "Create" under the DB name

**Comment by satkunas** [comment]
Still not able to reproduce. There's no redirect after clicking Create database button.

**Comment by julsemaan** [comment]
And you're trying on a fully fresh install right ? Because if your DB exists like in the screenshot above, you're unlikely to hit the same issue I did hit

**Comment by satkunas** [comment]
Tested again with fresh install through yum - nightly build, no existing db (rm'd /var/lib/mysql), brand new MariaDB install, brand new config (rm'd /usr/local/pf), no git. Still no redirect after clicking Create.
