### ISSUE TITLE
time_period doesn't work in filter engine (at least radius)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6238]
**Describe the bug**
Create a radius filter:

```
[Bozo]
status=enabled
description=Bozo
scopes=returnRadiusAccessAccept
merge_answer=no
condition=mac == "cc:c0:79:f6:6c:aa" && time_period(time, "wd {Mon Tue Wed Thu Fri} hr {8am-2pm}")
top_op=and
```
then connect with the mac cc:c0:79:f6:6c:aa in the period wd {Mon Tue Wed Thu Fri} hr {8am-2pm} , the rule doesn't trigger.

After investigation, it looks that $arg->{time} is missing in lib/pf/condition/key.pm in match funtion.

```
sub match {
    my ($self,$arg,$args) = @_;
    use pf::log;
    use Data::Dumper;
    if (!(defined($args))) {
        $args = $arg
    }

    return $FALSE unless defined $arg && reftype ($arg) eq 'HASH';
    my $key = $self->key;
    return $FALSE unless exists $arg->{$key};
    return $self->condition->match($arg->{$key},$args);
}
```
Adding $arg->{time} = localtime(); in this function fix the issue.
Just not sure that it's the correct place to fix.

**Comment by jrouzierinverse** [comment]
Fixed by e252e2ce38fc8e8ca39dc8297b7d819e81f721b7
