### ISSUE TITLE
Web Admin: NULL Realm has stripping config

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6241]
I don't think we could strip a null realm.

Maybe those are irrelevant.

![image](https://user-images.githubusercontent.com/5261214/113040300-a40ded80-9166-11eb-9015-fd9074cd8eeb.jpeg)

**Comment by satkunas** [comment]
@lzammit they were available in 10.2. Should we remove all strip fields from NULL?

**Comment by satkunas** [comment]
@lzammit and I agree this isn't a regression. Closing.
