### ISSUE TITLE
pfperl-api: Data truncated for column 'unregdate' at row 1

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6243]
**Describe the bug**
When you modify a node without setting an unreg date, you got following error from GUI:

`node/00%3A03%3A00%3A11%3A11%3A01: Cannot update '00:03:00:11:11:01'`

In logs:
```
│Mar 31 07:58:57 pfdeb9dev packetfence: pfperl-api(18407) WARN: Warning: 1265: Data truncated for column 'unregdate' at row 1 (pf::dal::db_execute) 
```

**To Reproduce**
1. Create a registered node with guest role 
2. Save
3. Unregistered your device and save

=> You got an error.

**Expected behavior**
No error.

**Comment by fdurand** [comment]
close to #6207

**Comment by nqb** [comment]
Thanks @fdurand, I'm closing this in favor of #6207
