### ISSUE TITLE
URI filter no longer working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6245]
conf/profiles.conf
````
[device-registration]
locale=
sources=AD
advanced_filter=
filter=uri:/status/login,uri:/device-registration
self_service=default
````

**Comment by jrouzierinverse** [comment]
Can you tell me the output of the following command?

```./bin/pftest profile_filter 00:00:00:00:00:00 last_uri=/device-registration```

**Comment by lzammit** [comment]
````
[root@cluster1 pf]# bin/pftest profile_filter 00:00:00:00:00:00 last_uri=/device-registration
Found 'device-registration' profile for 00:00:00:00:00:00
````

**Comment by lzammit** [comment]
Talking with Fabrice, it looks like it's a session/ cookie related issue

**Comment by jrouzierinverse** [comment]
Every time you create a new uri filter you need to restart https.portal in order for it to match.

**Comment by lzammit** [comment]
systemctl restart packetfence-httpd.portal
