### ISSUE TITLE
pfpki: default key usage and extended key usage

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6248]
**Describe the bug**
When you use `pfpki` with SCEP support, you generate a CSR and send it to `pfpki` using a PKI profile as a reference.

Currently, even if profile has key usage attributes or extended key usage attributes, they are ignored by `pfpki` and generated certificate contains:
```console
#  openssl x509 -in client.crt -noout -text
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Subject Key Identifier:
```

According to @fdurand, it's related to [SCEP Golang library](https://github.com/micromdm/scep/blob/fa847cef3c453edee9fd4a519defa2befb94b676/depot/signer.go#L76).

**Expected behavior**
Generate a certificate based on key usage attributes or extended key usage attributes defined in PKI profile.

**Additional context**
Most of the settings related to generated certificate comes from CSR. IMHO, we should only send CSR to a CA without any reference to profile and sign certificate with that CA.

**Comment by fdurand** [comment]
It will be fixed when this branch will be merged https://github.com/inverse-inc/packetfence/tree/feature/intune

**Comment by fdurand** [comment]
Also fixed with that: https://github.com/inverse-inc/scep/commit/4016f0ecaf940b7bbe5b3b3da42c554fe66cfb02

**Comment by nqb** [comment]
Extended key usage and Key usage are taken from PKI template and not from CSR.
