### ISSUE TITLE
Web Admin: Refresh node info button missing

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6251]
Missing button at the top right corner of the card.

PacketFence v10.2:
![image](https://user-images.githubusercontent.com/5261214/113346968-85445e00-9302-11eb-9064-c7c9538cfab8.jpeg)

PacketFence v10.2.9:

![image](https://user-images.githubusercontent.com/5261214/113347017-942b1080-9302-11eb-8505-8b4023e6ed40.jpeg)

**Comment by satkunas** [comment]
The Reset button at the bottom of the form now serves the same function.
