### ISSUE TITLE
Web Admin: Can't save default switch group

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6261]
![image](https://user-images.githubusercontent.com/5261214/113605785-1d00bf80-9615-11eb-968b-d0b65b93e127.jpeg)
![image](https://user-images.githubusercontent.com/5261214/113605817-2b4edb80-9615-11eb-976c-7fba7484171b.jpeg)

To fix it, I need to specify the Type as Standard and the Production and I can save it.

![image](https://user-images.githubusercontent.com/5261214/113606897-98af3c00-9616-11eb-88ad-4b78132612df.jpeg)

**Comment by lzammit** [comment]
I can't even save now.

I should not be forced to re-select the default settings.

![image](https://user-images.githubusercontent.com/5261214/114217260-edfc8d80-9935-11eb-9d1d-63e064894d45.jpeg)

**Comment by jrouzierinverse** [comment]
@satkunas I will relax the backend to not require this to be sent as we have defaults for these values.
Can you remove the checks in the frontend thank you.
