### ISSUE TITLE
Web Admin: Let's encrypt name broken

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6262]
![image](https://user-images.githubusercontent.com/5261214/113607104-d44a0600-9616-11eb-832a-1a8eab92f7d9.jpeg)

**Comment by julsemaan** [comment]
This guy's name is probably more broken: https://youtu.be/W85F-UmnbF4?t=38

**Comment by lzammit** [comment]
![image](https://user-images.githubusercontent.com/5261214/114216978-9c540300-9935-11eb-852a-99fcd86afdf1.jpeg)
