### ISSUE TITLE
Webadmin: OpenID attributes field is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6265]
**Describe the bug**
The OpenID attributes field seems to be of the wrong type (single value instead of multi)

**To Reproduce**
1. Go in System Configuration->Advanced
2. Set the value of "OpenID attributes" to `nickname,test,hello`
3. Save
4. Refresh the page
5. The value is now `nicknametesthello` (commas have disappeared)

**Expected behavior**
Multi-values should be fine in that field

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Firefox
 - Version 85.0.2

**Comment by satkunas** [comment]
@julsemaan changes pushed, pleae te-test.

**Comment by julsemaan** [comment]
Still broken

I have the following in pf.conf:
```
[advanced]
openid_attributes=nickname,firstname,given_name
```

And when viewing the advanced section in the admin, it displays nothing in the field

**Comment by julsemaan** [comment]
And this also broke the authentication sources section with the following error:
```
Apr  8 15:01:15 packetfence packetfence: pfperl-api(22955) ERROR: Can't use string ("nickname,firstname,given_name") as an ARRAY ref while "strict refs" in use at /usr/local/pf/lib/pf/Authentication/Source/OpenIDSource.pm line 44.
```

**Comment by jrouzierinverse** [comment]
Retry

**Comment by julsemaan** [comment]
this only fixes half of the problem, the OpenID attributes are still broken in the advanced section

**Comment by jrouzierinverse** [comment]
@satkunas would have to look into that.

**Comment by julsemaan** [comment]
The attributes cannot be used anymore when configuring authentication rules in an OpenID source

Before the data in the screenshot below was "given_name" equals "Julien", now its unrecognized:
![image](https://user-images.githubusercontent.com/3857942/114206153-0f0ab180-9929-11eb-9007-0526dbb2718e.png)

All the attributes defined in OpenID attributes (nickname,firstname,given_name) are not in the list either

**Comment by satkunas** [comment]
@jrouzierinverse can we get the openid attributes added to the meta?

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/source/OpenIDTest | jq '.meta.authentication_rules.item.properties.conditions.item.properties.attribute.allowed[].value'
"SSID"
"current_time"
"current_time_period"
"connection_type"
"computer_name"
"mac"
"realm"
"switch_id"
"switch_group"
"username"
"stripped_user_name"
"username"
```

Re-use the openid attribute key in text and value:

`{attributes: {data-type: "substring"}, text: "given_name", value: "given_name"}`

Attribute source: https://github.com/inverse-inc/packetfence/issues/6265#issuecomment-816060356

**Comment by satkunas** [comment]
@jrouzierinverse we'll need to remove ambiguity. In the following case "username" appears twice.

My suggestion is to prefix with "OpenID::":


![Screen Shot 2021-04-12 at 10 28 23 AM](https://user-images.githubusercontent.com/3904468/114411117-e75e5800-9b79-11eb-9f60-1fb3d4ca4ec4.jpg)
