### ISSUE TITLE
web admin(RADIUS filters): connection_sub_type is not available as value for advanced filter 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6268]
**Describe the bug**
When you create a RADIUS filter, `connection_sub_type` value is not available in dropdown list.

**To Reproduce**
1. Create a new RADIUS filter
2. Search `connection_sub_type` as value for your advanced filter

=> Not available.

**Expected behavior**
`connection_sub_type` is available

**Additional context**
I didn't see this attribute returned in JSON payload from API (`OPTIONS /api/v1/config/filter_engines/radius_filters`)

**Comment by jrouzierinverse** [comment]
Fixed by 821dd75ce3fa6b484bd6d94b8c5aa780f7f017fd
