### ISSUE TITLE
web admin: improvements on interfaces menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6270]
**Describe the bug**
To be more consistent, we should change minor things in Interfaces menu.

#### Interfaces and networks
- Netmask should be just after IPv4 address

#### L3 networks
- Order of fields should be: Network, Netmask, Description and Type (like in form)

#### Available buttons
When we change some settings in this menu, it's sometimes necessary to restart `keepalived`. I suggest to add `keepalived` restart button next to others.

**Additional context**
It seems that API doesn't return `netmask` informations for L3 networks ATM.

**Comment by satkunas** [comment]
We'll need to add the L3 netmask to the API before I add the column to the table. Re-assigning to @jrouzierinverse for API.

**Comment by jrouzierinverse** [comment]
The netmask should be there already for network types.

**Comment by jrouzierinverse** [comment]
I found the bug.

**Comment by jrouzierinverse** [comment]
@satkunas Can you look at the GUI changes now?
