### ISSUE TITLE
mariadb-upgrade:  Plugin 'unix_socket' is not loaded

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6272]
**Describe the bug**
Since merge of #6149, database setup doesn't work on Debian during configurator.

**To Reproduce**
1. Install a fresh Debian 9
2. Try to create your database

=>` {"message":"Error in connection to the database mysql with user root","status":500}`

**Expected behavior**
Configurator passed correctly.

**Additional context**
In CLI:

```
root@pfdeb9dev:/src/t/venom/results# mysql
ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded

```

**Comment by nqb** [comment]
Path to load plugins have changed since 10.2.

```
# in 10.2
 /usr/sbin/mysqld --defaults-file=/usr/local/pf/var/conf/mariadb.conf --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/x86_64-linux-gnu/mariadb18/plugin --pid-file=pfdeb9stable.pid --socket=/var/run/mysqld/mysqld.sock --port=3306

# now
 /usr/sbin/mysqld --defaults-file=/usr/local/pf/var/conf/mariadb.conf --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --pid-file=pfdeb9dev.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
```

**Comment by nqb** [comment]
After I started MariaDB like this:
```
/usr/bin/mysqld_safe --defaults-file=/usr/local/pf/var/conf/mariadb.conf --skip-grant-tables &
```
I can connect as `root` and I see following config:

```sql
MariaDB [(none)]> select Host,User,Plugin from mysql.user;
+-----------+------------------+-------------+
| Host      | User             | Plugin      |
+-----------+------------------+-------------+
| localhost | root             | unix_socket |
| localhost | debian-sys-maint |             |
+-----------+------------------+-------------+
``` 
which explain why I got this issue.

**Comment by nqb** [comment]
[Workaround ](https://github.com/inverse-inc/packetfence/blob/821dd75ce3fa6b484bd6d94b8c5aa780f7f017fd/debian/packetfence.postinst#L164)is already present in postinstall script for Debian but it doesn't work in this version because it's not possible to connect as `root`.

I'm rebuilding `pfdeb9dev` image with new runtime dependencies because my tests were done against an image which has previous MariaDB dependencies installed.

**Comment by fdurand** [comment]
I did a test on a fresh debian 9 and i was able to create the database.
I will try another time.

**Comment by fdurand** [comment]
Did it a least 3 times from fresh install and don't have this issue.
I did an apt install packetfence, during the install it ask me to set the mysql password then after in the configurator i use the same to create the pf db and the pf user.

**Comment by nqb** [comment]
As mentioned in my latest comment, issue was caused by the fact that image already have MariaDB 10.1 pkgs installed.

I [rebuilt](https://gitlab.com/inverse-inc/packetfence/-/jobs/1159956724) image with MariaDB 10.2 and everything looks good regarding configurator.
