### ISSUE TITLE
mariadb: Got an error reading communication packets when pfcron and iptables are started

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6276]
**Describe the bug**
On Debian (standalone), I noticed following messages in `mariadb_error.log`:

```
Apr  8 12:05:03 pfdeb9stable mysqld: 2021-04-08 12:05:03 140510194689792 [Warning] Aborted connection 2755 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets)                  │
Apr  8 12:05:03 pfdeb9stable mysqld: 2021-04-08 12:05:03 140511337453312 [Warning] Aborted connection 2756 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets)                  │
Apr  8 12:06:03 pfdeb9stable mysqld: 2021-04-08 12:06:03 140510192846592 [Warning] Aborted connection 2757 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets)                  │
Apr  8 12:06:03 pfdeb9stable mysqld: 2021-04-08 12:06:03 140510464886528 [Warning] Aborted connection 2758 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets)                  │
Apr  8 12:06:03 pfdeb9stable mysqld: 2021-04-08 12:06:03 140510192846592 [Warning] Aborted connection 2757 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets)                  │
Apr  8 12:06:03 pfdeb9stable mysqld: 2021-04-08 12:06:03 140510464886528 [Warning] Aborted connection 2758 to db: 'pf' user: 'pf' host: 'localhost' (Got an error reading communication packets) 
```

when `pfcron` and `iptables` run.

**To Reproduce**
1. Install a Debian 9 with latest devel
2. Start all services
3. Look into /usr/local/pf/logs/mariadb_error.log

**Expected behavior**
No errors

**Desktop (please complete the following information):**

**Additional context**
- `pfcron` messages occured each minute
- `iptables` messages occured each minute (certainly related to `ExecStart` statement in `packetfence-iptables` service)

Related to #6149

**Comment by nqb** [comment]
I will check if issue was already present before MariaDB upgrade because I see that #6149 enabled `log_warnings` setting in configuration:

https://github.com/inverse-inc/packetfence/blob/464c6d3272e6ba0def8fb0f387960a5d223ee086/conf/mariadb/mariadb.conf.tt.example#L47

**Comment by nqb** [comment]
@fdurand doesn't have this issue on a fresh Debian 9 installed with latest nightly build. In my case, I upgraded a PF running 10.2 to latest nightly build.

On PF 10.2 with MariaDB 10.1.45, `log_warnings` were already enabled:

```sql
# mysql -e "show variables where variable_name='log_warnings';"
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| log_warnings  | 1     |
+---------------+-------+
```

**Comment by nqb** [comment]
`iptables` error was related to a misconfiguration after my upgrade.

Regarding `pfcron`, I'm able to replicate issue for example with `provisioning_compliance_poll` task like this:

```
http -v --verify=no POST https://172.17.17.16:1443/api/v1/login username='admin' password='secret'
http -v --verify=no POST https://172.17.17.16:1443/api/v1/config/maintenance_task/provisioning_compliance_poll/run Authorization:TOKEN_ID
```

It generates each time an error message in `mariadb_error.log` like mentioned above.

I don't see specific error in `/var/lib/mysql/hostname.log` after I set `general_log=1`, only:

```
648 Connect   pf@localhost as anonymous on pf                                                                                                                                                                             
```
when I run maintenance_task.

**Comment by julsemaan** [comment]
This is what I have in my 10.2 upgrade to 10.2.9:
```
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| log_warnings  | 2     |
+---------------+-------+
```

**Comment by nqb** [comment]
According to [MariaDB documentation](https://mariadb.com/docs/reference/mdb/system-variables/log_warnings/#mdb-system-variables-log-warnings), `log_warnings=2` is the default value. So it would mean that our MariaDB config is not taken into account after an upgrade from 10.2 to 10.2.9 in CentOS ?

On a ZEN build (with MariaDB change), `log_warnings` is set to `1`.

**Comment by jrouzierinverse** [comment]
If there is a modified ```conf/mariadb/mariadb.conf.tt``` we must make remind the user to do so.

**Comment by jrouzierinverse** [comment]
This should be moved to +1 as this is an existing issue.

**Comment by nqb** [comment]
Moving milestone.

Regarding reminder, if users follow upgrade guide, they should find a `.rpmnew` file or be warn by Debian packaging system about a change.

@julsemaan, could you confirm ?

Thanks.

**Comment by julsemaan** [comment]
if someone changed mariadb.conf.tt, they will get an rpmnew during the upgrade.

Haven't tested it for this current release but all the logic of that file seems untouched

**Comment by nqb** [comment]
Issue is not present anymore on Debian 11
