### ISSUE TITLE
web admin(switchs): improve description of switch modules

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6287]
**Describe the bug**
When you create a new switch and search for a Type, you see **description** of each switch modules (Perl and Swtich Templates).

After you select your module, Type is set to **ID** of your switch modules (like Brocade::Switch) which is different than description and doesn't speak to users.

It create some confusion about which module your are using.

**To Reproduce**
1. Go to 'Switches'
2. Create a new switch and choose "Brocade Standard Switch" as Type

=> After you select "Brocade Standard Switch", Type is set to "Brocade::Switch"

**Expected behavior**
Type is set to "Brocade::Switch (Brocade Standard Switch)"

**Additional context**
I know that value of Type is the value saved in `switches.conf`.

Perhaps we could use same tip as for `pid` of nodes where:
- in DB, `pid` equals to name of user
- in web admin, `owner` equals to `pid ("Firstname Lastname <email>")`

**Comment by satkunas** [comment]
*Note:* The following method needs to be modified to support grouped values:

https://github.com/inverse-inc/packetfence/blob/beda7d0ba8f3a6ac0bd30274eea4d6cf47ae9cab/html/pfappserver/root/src/composables/useInputMultiselect.js#L494-L510

**Comment by satkunas** [comment]
A fix for this may impact several other sections. Without E2E tests it's a gamble to make changes while already in testing. I will push the milestone and revisit post-v11.
