### ISSUE TITLE
Can't select Connection Type in Authentication Rules

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#6291]
**Describe the bug**
Can't select Connection Type in Authentication Rules for AD Authentication Source.

**To Reproduce**
1. Go to Authentication Sources
2. Configure new AD Authentication Source
3. Add new Authentication Rule
4. Use Connection Type for Condition

**Screenshots**
<img width="1012" alt="Screenshot 2021-04-15 at 16 06 58" src="https://user-images.githubusercontent.com/17347347/114874954-81860080-9e05-11eb-97fe-4cd77f058385.png">

**Expected behavior**
Be able to select Connection Type in Condition.

**Comment by julsemaan** [comment]
@lyubomirtraykov, can you confirm the PF version please?

**Comment by lyubomirtraykov** [comment]
10.3

**Comment by julsemaan** [comment]
@satkunas, can you take a look at this please?

**Comment by julsemaan** [comment]
@lyubomirtraykov, please apply the maintenance patches via /usr/local/pf/addons/pf-maint.pl and let us know if that fixes it

**Comment by LizardNerd** [comment]
@julsemaan I applyed the patch, but it doesn't work, the issue remain.

**Comment by julsemaan** [comment]
> @julsemaan I applyed the patch, but it doesn't work, the issue remain.

@satkunas, can you take a look into this?

**Comment by LizardNerd** [comment]
> > @julsemaan I applyed the patch, but it doesn't work, the issue remain.
> 
> @satkunas, can you take a look into this?

Nevermind, my bad the patch actually works well!

**Comment by satkunas** [comment]
@LizardNerd thank you for the update.
