### ISSUE TITLE
packetfence-pki: allow to enter a FQDN as CN for certificate

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6294]
**Describe the bug**
Frontend prevents you to enter a FQDN in CN field for certificates but you can do it using API.

It's a best practice to use FQDN as a CN and according to a customer it was possible in 10.1.0.

**To Reproduce**
1. Try to create a certificate with a FQDN as CN

**Expected behavior**
Frontend lets you create a certificate with CN equals to a FQDN.

**Additional context**
Unless @fdurand don't want to allow this, we should remove this limitation.

**Comment by olmanolsztyn** [comment]
There is no reason not to allow an FQDN in the CN field.
