### ISSUE TITLE
Can't select Switch Type for new switch in 10.3

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#6295]
**Describe the bug**
Can't select Switch Type for new switch in 10.3

**To Reproduce**
1. Create new Switch
2. Try to select Switch Type

**Screenshots**
<img width="1150" alt="Screenshot 2021-04-16 at 9 49 30" src="https://user-images.githubusercontent.com/17347347/114983722-9f9d4080-9e99-11eb-8678-5c8736a1c35e.png">

**Expected behavior**
Be able to select Switch Type.

**Comment by julsemaan** [comment]
@satkunas, what could be the issue here ?

**Comment by satkunas** [comment]
A regression was created in 381c84554aedcee0134017a3b5ec201eddfbb797
