### ISSUE TITLE
Upgrade from 10.1 to 10.3

### ISSUE THREAD

**Issue by WJCPacketFence** [inverse-inc/packetfence#6298]
I have tried the procedure over 5 times now.  I end up with packetfence-config and packetfence-mariadb issues.  Again I'm at version 10.1.   If I do option 15.1 to upgrade mariadb that works fine.   I then run the package upgrade.   The database schema upgrade for 10.2 step 14.6 errors out.   I can't do any of the other 14.x steps because the code to run them is not installed yet. I get a  SQL syntax is not correct.  If I try to move on I can't run the 10.3 database schema update because 10.2 never completed successfully.   

What am I missing?

**Comment by nqb** [comment]
Hello,

Could you describe more precisely which steps did you follow ?
Also could you provide which SQL syntax error you have ?

**Comment by jrouzierinverse** [comment]
Run the following command.
```mysql -uroot -p -e'SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"'```
Then try and apply the 10.2 schema

**Comment by WJCPacketFence** [comment]
I got this message from James Rouzier.(below)   I’m going to try it.   I will let you know if it works or will supply the error.


Run the following command.
mysql -uroot -p -e'SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"'
Then try and apply the 10.2 schema


Eric J. Cox
Sr. Network Engineer
757.603.6513

**Comment by WJCPacketFence** [comment]
1.  Backups of course.  They have been tested many times. 😊
  2.  Stopped PF
  3.  Stopped packetfence-config
  4.  Stopped packetfence-mariadb



 rpm -e --nodeps MariaDB-client MariaDB-common MariaDB-server MariaDB-shared

yum install --enablerepo=packetfence MariaDB-server



Complete!

***@***.***BETApktfnc ~]# systemctl unmask mariadb

Removed symlink /etc/systemd/system/mariadb.service.

***@***.***BETApktfnc ~]# systemctl start mariadb

***@***.***BETApktfnc ~]# mysql -u root -p -e "show variables where Variable_name='version';"

Enter password:

+---------------+-----------------+

| Variable_name | Value           |

+---------------+-----------------+

| version       | 10.2.37-MariaDB |

+---------------+-----------------+





mysql_upgrade -u root -p

Enter password:

Phase 1/7: Checking and upgrading mysql database

Processing databases

mysql

mysql.column_stats                                 OK

mysql.columns_priv                                 OK

mysql.db                                           OK

mysql.event                                        OK

mysql.func                                         OK

mysql.gtid_slave_pos                               OK

mysql.help_category                                OK

mysql.help_keyword                                 OK

mysql.help_relation                                OK

mysql.help_topic                                   OK

mysql.host                                         OK

mysql.index_stats                                  OK

mysql.innodb_index_stats                           OK

mysql.innodb_table_stats                           OK

mysql.plugin                                       OK

mysql.proc                                         OK

mysql.procs_priv                                   OK

mysql.proxies_priv                                 OK

mysql.roles_mapping                                OK

mysql.servers                                      OK

mysql.table_stats                                  OK

mysql.tables_priv                                  OK

mysql.time_zone                                    OK

mysql.time_zone_leap_second                        OK

mysql.time_zone_name                               OK

mysql.time_zone_transition                         OK

mysql.time_zone_transition_type                    OK

mysql.user                                         OK

Phase 2/7: Installing used storage engines... Skipped

Phase 3/7: Fixing views

Phase 4/7: Running 'mysql_fix_privilege_tables'

Phase 5/7: Fixing table and database names

Phase 6/7: Checking and upgrading tables

Processing databases

information_schema

performance_schema

pf

pf.action                                          OK

pf.activation                                      OK

pf.admin_api_audit_log                             OK

pf.auth_log                                        OK

pf.bandwidth_accounting                            OK

pf.bandwidth_accounting_history                    OK

pf.billing                                         OK

pf.chi_cache                                       OK

pf.class                                           OK

pf.dhcp_option82                                   OK

pf.dhcp_option82_history                           OK

pf.dhcppool                                        OK

pf.dns_audit_log                                   OK

pf.inline_accounting                               OK

pf.ip4log                                          OK

pf.ip4log_archive                                  OK

pf.ip4log_history                                  OK

pf.ip6log                                          OK

pf.ip6log_archive                                  OK

pf.ip6log_history                                  OK

pf.key_value_storage                               OK

pf.keyed                                           OK

pf.locationlog                                     OK

pf.locationlog_history                             OK

pf.node                                            OK

pf.node_category                                   OK

pf.password                                        OK

pf.person                                          OK

pf.pf_version                                      OK

pf.pki_cas                                         OK

pf.pki_certs                                       OK

pf.pki_profiles                                    OK

pf.pki_revoked_certs                               OK

pf.radacct                                         OK

pf.radacct_log                                     OK

pf.radius_audit_log                                OK

pf.radius_nas                                      OK

pf.savedsearch                                     OK

pf.scan                                            OK

pf.security_event                                  OK

pf.sms_carrier                                     OK

pf.tenant                                          OK

pf.user_preference                                 OK

pf.userlog                                         OK

pf.wrix                                            OK

Phase 7/7: Running 'FLUSH PRIVILEGES'

OK



***@***.***BETApktfnc ~]# systemctl stop mariadb

***@***.***BETApktfnc ~]# systemctl mask mariadb

Created symlink from /etc/systemd/system/mariadb.service to /dev/null.

***@***.***BETApktfnc ~]#


yum update --enablerepo=packetfence
Complete!

Now I start with 14.1 – 14.5 and they all work.

*********** Error **************
mysql -u root -p pf -v < /usr/local/pf/db/upgrade-10.1.0-10.2.0.sql

ERROR 1064 (42000) at line 222: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM `radreply`
      WHERE `tenant_id`='1' AND `u...' at line 3

I will run the command from James now and post results.

***@***.***BETApktfnc ~]# mysql -uroot -p -e'SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"'
Enter password:
***@***.***BETApktfnc ~]# mysql -u root -p pf -v < /usr/local/pf/db/upgrade-10.1.0-10.2.0.sql
Enter password:

Same result!


Eric J. Cox
Sr. Network Engineer
757.603.6513

**Comment by WJCPacketFence** [comment]
Here is what happened.

  1.  Backups of course.  They have been tested many times. 😊
  2.  Stopped PF
  3.  Stopped packetfence-config
  4.  Stopped packetfence-mariadb



 rpm -e --nodeps MariaDB-client MariaDB-common MariaDB-server MariaDB-shared

yum install --enablerepo=packetfence MariaDB-server



Complete!

***@***.***BETApktfnc ~]# systemctl unmask mariadb

Removed symlink /etc/systemd/system/mariadb.service.

***@***.***BETApktfnc ~]# systemctl start mariadb

***@***.***BETApktfnc ~]# mysql -u root -p -e "show variables where Variable_name='version';"

Enter password:

+---------------+-----------------+

| Variable_name | Value           |

+---------------+-----------------+

| version       | 10.2.37-MariaDB |

+---------------+-----------------+





mysql_upgrade -u root -p

Enter password:

Phase 1/7: Checking and upgrading mysql database

Processing databases

mysql

mysql.column_stats                                 OK

mysql.columns_priv                                 OK

mysql.db                                           OK

mysql.event                                        OK

mysql.func                                         OK

mysql.gtid_slave_pos                               OK

mysql.help_category                                OK

mysql.help_keyword                                 OK

mysql.help_relation                                OK

mysql.help_topic                                   OK

mysql.host                                         OK

mysql.index_stats                                  OK

mysql.innodb_index_stats                           OK

mysql.innodb_table_stats                           OK

mysql.plugin                                       OK

mysql.proc                                         OK

mysql.procs_priv                                   OK

mysql.proxies_priv                                 OK

mysql.roles_mapping                                OK

mysql.servers                                      OK

mysql.table_stats                                  OK

mysql.tables_priv                                  OK

mysql.time_zone                                    OK

mysql.time_zone_leap_second                        OK

mysql.time_zone_name                               OK

mysql.time_zone_transition                         OK

mysql.time_zone_transition_type                    OK

mysql.user                                         OK

Phase 2/7: Installing used storage engines... Skipped

Phase 3/7: Fixing views

Phase 4/7: Running 'mysql_fix_privilege_tables'

Phase 5/7: Fixing table and database names

Phase 6/7: Checking and upgrading tables

Processing databases

information_schema

performance_schema

pf

pf.action                                          OK

pf.activation                                      OK

pf.admin_api_audit_log                             OK

pf.auth_log                                        OK

pf.bandwidth_accounting                            OK

pf.bandwidth_accounting_history                    OK

pf.billing                                         OK

pf.chi_cache                                       OK

pf.class                                           OK

pf.dhcp_option82                                   OK

pf.dhcp_option82_history                           OK

pf.dhcppool                                        OK

pf.dns_audit_log                                   OK

pf.inline_accounting                               OK

pf.ip4log                                          OK

pf.ip4log_archive                                  OK

pf.ip4log_history                                  OK

pf.ip6log                                          OK

pf.ip6log_archive                                  OK

pf.ip6log_history                                  OK

pf.key_value_storage                               OK

pf.keyed                                           OK

pf.locationlog                                     OK

pf.locationlog_history                             OK

pf.node                                            OK

pf.node_category                                   OK

pf.password                                        OK

pf.person                                          OK

pf.pf_version                                      OK

pf.pki_cas                                         OK

pf.pki_certs                                       OK

pf.pki_profiles                                    OK

pf.pki_revoked_certs                               OK

pf.radacct                                         OK

pf.radacct_log                                     OK

pf.radius_audit_log                                OK

pf.radius_nas                                      OK

pf.savedsearch                                     OK

pf.scan                                            OK

pf.security_event                                  OK

pf.sms_carrier                                     OK

pf.tenant                                          OK

pf.user_preference                                 OK

pf.userlog                                         OK

pf.wrix                                            OK

Phase 7/7: Running 'FLUSH PRIVILEGES'

OK



***@***.***BETApktfnc ~]# systemctl stop mariadb

***@***.***BETApktfnc ~]# systemctl mask mariadb

Created symlink from /etc/systemd/system/mariadb.service to /dev/null.

***@***.***BETApktfnc ~]#


yum update --enablerepo=packetfence
Complete!

Now I start with 14.1 – 14.5 and they all work.

*********** Error **************
mysql -u root -p pf -v < /usr/local/pf/db/upgrade-10.1.0-10.2.0.sql

ERROR 1064 (42000) at line 222: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM `radreply`
      WHERE `tenant_id`='1' AND `u...' at line 3

I will run the command from James now and post results.

***@***.***BETApktfnc ~]# mysql -uroot -p -e'SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"'
Enter password:
***@***.***BETApktfnc ~]# mysql -u root -p pf -v < /usr/local/pf/db/upgrade-10.1.0-10.2.0.sql
Enter password:

Same result!



Eric J. Cox
Sr. Network Engineer
757.603.6513

**Comment by nqb** [comment]
Able to replicate issue.

I installed a fresh ZEN running 10.1.0. After we pushed MariaDB-common (10.2.37) and MariaDB-compat (10.2.37) to stable repository, I got following error after I try to apply SQL schema:

```console
# mysql -u root -p pf -v < /usr/local/pf/db/upgrade-10.1.0-10.2.0.sql
[..]
Adding default radreply row
--------------
INSERT INTO `radreply` (`tenant_id`, `username`, `attribute`, `value`, `op`)
SELECT '1', '00:00:00:00:00:00','User-Name','*', '=*'
WHERE NOT EXISTS (SELECT * FROM `radreply`
      WHERE `tenant_id`='1' AND `username`='00:00:00:00:00:00' AND `attribute`='User-Name' AND `value`='*' AND `op`='=*' LIMIT 1)
--------------

ERROR 1064 (42000) at line 222: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM `radreply`
      WHERE `tenant_id`='1' AND `u...' at line 3
```

As reported by @WJCPacketFence, issue is still presents after I used command proposed by @jrouzierinverse.

**Comment by nqb** [comment]
Fix will need to go in maintenance. 

If users follow upgrade procedure, they should apply maintenance patches before running database schema scripts.

**Comment by WJCPacketFence** [comment]
So,  If I do what you suggest I can move on with the upgrade or do I need to wait for maintenance fix?

**Comment by jrouzierinverse** [comment]
I placed this fix in maintenance you can run 
You can get this fix and all the other latest fixes by running pf-maint.pl

```bash

cd /usr/local/pf

# Get the latest fixed
./addons/pf-maint.pl

# Restart PacketFence
./bin/pfcmd service pf restart

```
Or you can manually apply the patch by doing the following.
```bash
cd /usr/local/pf

curl https://github.com/inverse-inc/packetfence/commit/1fb8f8d37df11c3d06ed6a2ded6e4eb7ebdb3df3.diff> 1fb8f8d37df11c3d06ed6a2ded6e4eb7ebdb3df3.diff

# Do a dry run to make sure everything is ok.
patch -p1 --dry-run < 1fb8f8d37df11c3d06ed6a2ded6e4eb7ebdb3df3.diff

# If everything is good then do it for real
patch -p1 < 1fb8f8d37df11c3d06ed6a2ded6e4eb7ebdb3df3.diff

# Restart PacketFence
./bin/pfcmd service pf restart

```

**Comment by nqb** [comment]
Tested and it works.

**Comment by WJCPacketFence** [comment]
Same here.

Thanks,
