### ISSUE TITLE
Unable to create or edit Admin Access Roles in WebUI

### ISSUE THREAD

**Issue by cdcrawford** [inverse-inc/packetfence#6302]
**Describe the bug**
I am unable to select Roles in the Admin Access Roles section in the WebUI. This prevents Admin Roles from being created. The data is being pulled from the API, just not printed to the user.

This is also present on existing roles as well.

Data Being Pulled:
![image](https://user-images.githubusercontent.com/3090648/115231183-a58a6000-a0eb-11eb-833c-5b070f037548.png)

**To Reproduce**
New Admin Role:
1. Go to Configuration -> System Configuration -> Admin Access
2. Click on "New Admin Role"
3. Nothing is being loaded in the Action Box.

Existing Admin Role:
1. Go to Configuration -> System Configuration -> Admin Access
2. Click on ex. "Node Manager"
3. Nothing is being loaded in the Action Box.

**Screenshots**
Existing Role:
![image](https://user-images.githubusercontent.com/3090648/115231622-277a8900-a0ec-11eb-8985-cd4b6c53becb.png)

New Role: 
![image](https://user-images.githubusercontent.com/3090648/115231675-34977800-a0ec-11eb-8542-8f836c94335c.png)

Clicking on Actions:
![image](https://user-images.githubusercontent.com/3090648/115231705-3e20e000-a0ec-11eb-8508-bf1eb08a1955.png)

Typing in Box:
![image](https://user-images.githubusercontent.com/3090648/115231734-4a0ca200-a0ec-11eb-8d52-e3731bd811d3.png)

**Expected behavior**
Ideally, it would act similar or better than the UI in 10.2.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Edge
 - Version: Version 89.0.774.77 (Official build) (64-bit)

**Comment by satkunas** [comment]
Related to #6291 and #6295

@cdcrawford I applied a fix for this in the 2 other issues last week. Specifically:
- 381c84554aedcee0134017a3b5ec201eddfbb797
- 3a4c8631f81cde0592a52d144078e2b61f49105c

 Please apply the maintenance patch and let us know if the issue still persists.

**Comment by cdcrawford** [comment]
That worked! Thanks so much!
