### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by northernscum** [inverse-inc/packetfence#6307]
Hi there
we are deploying packetfence and I'm running into issue with user roles. I had an employee of mine log onto my desktop but couldn't gain network or internet access. I saw his account on packetfence and it going to the default role, once I selected the bypass role it started to work. How do I properly ensure that our users when we roll out packetfence will NOT face the same issue. Thank You!
* If the issue needs to be discussed internally in a meeting, add the "Status: Question" label.

**Comment by extrafu** [comment]
This kind of question needs to be discussed in the PacketFence mailing list or directly with us if you get a support agreement.

**Comment by northernscum** [comment]
We do have a support with you :)

**Comment by extrafu** [comment]
So please don't hesitate to us it!
