### ISSUE TITLE
Unable to install wildcard SSL certificate in Web UI

### ISSUE THREAD

**Issue by fcpimenta** [inverse-inc/packetfence#6308]
**Describe the bug**
I was using version 10.2, where I can install our wildcard SSL certificate using the web UI. But after migrating to 10.3 and using the same method, the UI does not accept my .key file. After renaming the .key file to .txt, the web UI received the certificate content but presented an error message: Failed verifying chain. I've used the same files that were used in 10.2. I tested again in 10.2, and the method worked normally.

**To Reproduce**
1. Go to Configuration --> SSL Certificates
2. Click on HTTP, and EDIT
3. Upload the certificate (.crt file)
4. Upload the private key (.key file). See error:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/6945439/115453258-ca6afa00-a1f5-11eb-9532-9e4a90539d9c.png">

5. Rename .key file to .txt and retry Upload. It is accepted.
6. Enable Validate Certificate Chain option and click on SAVE
7. See error:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/6945439/115453666-42392480-a1f6-11eb-9485-f49e464f7daa.png">

**Screenshots**

**Expected behavior**
Save the certificate without errors as in the version 10.2, as can be viewed below:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/6945439/115453906-86c4c000-a1f6-11eb-9642-c5e65521e4b6.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.17
 - Browser Firefox 
 - Version 87 64Bits

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by julsemaan** [comment]
These look like 2 issues, the first one is related to the key not being accepted by the GUI unless it has the `.txt` extension. I believe @satkunas can take a look at this

The other issue is related to the chain validation which may be a user error. Regarding this, are you supplying the intermediate certs manually in the GUI or using the "find intermediates automatically" option ?

**Comment by satkunas** [comment]
What is the output from the following command? (on Catalina):

```
$ file --mime /path/to/cmbh-soluti-2020.key
```

**Comment by fcpimenta** [comment]
> These look like 2 issues, the first one is related to the key not being accepted by the GUI unless it has the `.txt` extension. I believe @satkunas can take a look at this
> 
> The other issue is related to the chain validation which may be a user error. Regarding this, are you supplying the intermediate certs manually in the GUI or using the "find intermediates automatically" option ?

I'm using the last option. My crt file is concatenated.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/6945439/115556122-af949600-a286-11eb-9e46-946f569d6f7f.png">

**Comment by fcpimenta** [comment]
> What is the output from the following command? (on Catalina):
> 
> ```
> $ file --mime /path/to/cmbh-soluti-2020.key
> ```

Hi @satkunas,

Here is the output:

`cmbh-soluti-2020.key: text/plain; charset=us-ascii`

**Comment by satkunas** [comment]
@fcpimenta I've added the mime-type which appears to be used by MacOS. This should allow you to upload without renaming.

**Comment by fcpimenta** [comment]
@satkunas I applied the patch, but the error persists.

**Comment by fcpimenta** [comment]
> @fcpimenta I've added the mime-type which appears to be used by MacOS. This should allow you to upload without renaming.

If I do it on Safari, it only enables txt loading as you can see below:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/6945439/115578519-c0033b80-a29b-11eb-9117-d5ebfb88c79d.png">

**Comment by satkunas** [comment]
@fcpimenta the error is another issue. Please follow up with @julsemaan 's question above.

**Comment by fcpimenta** [comment]
> @fcpimenta the error is another issue. Please follow up with @julsemaan 's question above.

But I was talking about the loading issue only. The validation is not solved too.

**Comment by satkunas** [comment]
@fcpimenta I'm able to replicate the Safari issue, but I'm unable to resolve it - even by omitting the `accept` attribute on the file upload - which indicates to me that it's an OS or Safari issue/limitation. 

You can still drag-and-drop files onto the Upload button. 

Safari must be >= 14.0.3

**Comment by julsemaan** [comment]
@fcpimenta, you need to apply the patch by running `/usr/local/pf/addons/pf-maint.pl`

Simply patching the file will not resolve the issue you're looking at with @satkunas

**Comment by fcpimenta** [comment]
> @fcpimenta, you need to apply the patch by running `/usr/local/pf/addons/pf-maint.pl`
> 
> Simply patching the file will not resolve the issue you're looking at with @satkunas

@julsemaan, yes, I did exactly this procedure before trying to load the key file. Now I've just test using Windows and Firefox 87 64-bit. The same load error occurs:

![image](https://user-images.githubusercontent.com/6945439/115604083-54c76280-a2b7-11eb-9b84-dac676797722.png)

**Comment by julsemaan** [comment]
One thing to note, the patch was only available in the compiled admin interface around 11:06 although @satkunas pushed it at 10:34

So applying the maintenance again may be necessary since your comment was at 11:14 which means you may not have pulled the latest compiled code

(all times above are in Montreal's timezone because I'm too lazy to convert to UTC)

**Comment by satkunas** [comment]
If you wish to try the patch before the maintenance builds are completed you can compile the web source manually. 

Requires NodeJS >= 10.24

```
cd /usr/local/pf/html/pfappserver/root/
npm install
npm run build
```

**Comment by fcpimenta** [comment]
@satkunas how can I identify the patch? When I run the maintenance, here is what I see:

`Step 1: Patching of text based codefiles
Currently at dae3f53e7482cca0fd01ce56b9c956780c21d206
** GET https://api.github.com/repos/inverse-inc/packetfence/branches/maintenance/10.3 ==> 200 OK (1s)
Already up to date for text based patches`

**Comment by nqb** [comment]
Hello @fcpimenta,

Patching of web admin interface is done at Step 3.
You can check content of `/usr/local/pf/html/pfappserver/root/dist`

**Comment by fcpimenta** [comment]
@nqb , my server is patched, but the issue with the loading of .key file and with the validation of certificate continue with errors.

**Comment by nqb** [comment]
@fcpimenta, just to be sure, did you re-patched it as requested by @julsemaan ?

Also, did you restart services to take change into account ?

**Comment by satkunas** [comment]
> @satkunas how can I identify the patch? When I run the maintenance, here is what I see:
> 
> `Step 1: Patching of text based codefiles Currently at dae3f53e7482cca0fd01ce56b9c956780c21d206 ** GET https://api.github.com/repos/inverse-inc/packetfence/branches/maintenance/10.3 ==> 200 OK (1s) Already up to date for text based patches`

Although the patch above includes the commit (https://github.com/inverse-inc/packetfence/commit/dae3f53e7482cca0fd01ce56b9c956780c21d206) the source is not necessarily built yet.  This includes the UI in my last comment above.

Maintenance builds are based off of the GIT branch with the same name. In this case `maintenance/10.3` is built nightly and then available trough the `pf-maint.pl` script afterwards. If you want to build manually before the patch is available `git checkout` the related branch (https://github.com/inverse-inc/packetfence/tree/maintenance/10.3) and build the sources manually.

**Comment by nqb** [comment]
> In this case `maintenance/10.3` is built nightly

Not anymore. We build directly any push to maintenance branches since v9.2.
It takes 10-20 minutes to make patch available to users.

**Comment by fcpimenta** [comment]
@nqb, I tried again: Re-patched and rebooted the server completely.

When I upload the .key file, the same message is presented in the UI:

`Invalid file, only "application/x-x509-ca-cert, text/*" content-type(s) are accepted.`

**Comment by julsemaan** [comment]
@satkunas, is this mime type check really necessary, we could just trust the input from the user since this is validated server side anyway

**Comment by satkunas** [comment]
@julsemaan it's meant to help usability rather than validation. The input accept attribute filters local files for the user based on mime-types and/or extension during file selection(s) for upload. We can accept `*/*` if you feel it's not necessary in this case.

**Comment by julsemaan** [comment]
I never use the file upload since I usually copy/paste it inside the field but I don't feel like that validation is necessary. It may be useful though but we can live without it if its causing problems

**Comment by fcpimenta** [comment]
Yes @julsemaan, this is only a detail. The main problem is that, even copying the content of .key file I can't save the certificate as I did with version 10.2 with the same file. In 10.3, I receive the message:

`Failed verifying chain: stdin: CN = *.cmbh.mg.gov.br error 20 at 0 depth lookup:unable to get local issuer certificate . Ensure the intermediates certificate file you provided contains all the intermediate certificate authorities in x509 (Apache) format.`

**Comment by julsemaan** [comment]
Given you're using the same GH issue for 2 different things, I want to solve them one at a time to prevent mixing the discussion

Feel free to open another issue with just that problem and we can discuss it there and leave this one focussed on the mime type filtering

**Comment by fcpimenta** [comment]
Ok @julsemaan, the new issue for the certificate validation is #6323
