### ISSUE TITLE
DELETE Tenant - Foreign Key Constraint

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#6310]
**Describe the bug**
DELETE /api/v1/tenant/:produces foreign key constraint error in `person` table

**To Reproduce**
1. Create a new Tenant
2. Delete new tenant
3. Inspect packetfence.log

**Additional context**
```
Apr 21 09:36:29 packetfence packetfence: pfperl-api(2813) ERROR: Database query failed with non retryable error: Cannot delete or update a parent row: a foreign key constraint fails (`pf`.`person`, CONSTRAINT `person_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)) (errno: 1451) [DELETE FROM `tenant` WHERE ( `tenant`.`id` = ? )]{2} (pf::dal::db_execute)
```

**Comment by nqb** [comment]
Perl unit tests failed: https://gitlab.com/inverse-inc/packetfence/-/jobs/1201417909#L559.

Related to #6239

**Comment by jrouzierinverse** [comment]
What should be the expected behavior when you attempt to remove a tenant that still has resource tied to it?

**Comment by extrafu** [comment]
@satkunas Hide the button for now. We'll handle that cleanly later.

**Comment by extrafu** [comment]
For now - if no data is tied to a tenant, we delete it. If there is, we disable it.
