### ISSUE TITLE
When saving SSL certificate in the admin gui it's doesnt return to the simple view.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6316]
**Describe the bug**
When saving SSL certificate in the admin gui it's doesnt return to the simple view and keep the edit view.

**To Reproduce**
1. Go to :1443/admin#/configuration/certificate/radius
2. Click on 'Edit'
2. Click on 'Save'
4. Still in the edit view, it should return to the read view.

**Comment by satkunas** [comment]
This form has been changed to behave the same as the other Configuration forms. It will no longer automatically redirect back to the View after Save. The action key (CTRL on PC, Command on MacOS) can be held when clicking the Save button to return to the View after saving.
