### ISSUE TITLE
switches: slow display in frontend

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6321]
**Describe the bug**
On a 10.3 with 92 switch groups and ~400 switches, if I try to browse switches or switchs groups, I have to wait ~10 seconds between each page.

Setup has 37 roles.

**To Reproduce**
1. Install a fresh 10.3
2. Install a switches.conf with a lot of entries
3. Try to display switch or switch groups

=> You will have to wait between each page

**Expected behavior**
Faster display.

**Additional context**
In the web browser, I see duplicate requests to API to get switch or switch groups information (see screenshot below):
![switches](https://user-images.githubusercontent.com/10830260/115852854-d1c61980-a428-11eb-8464-061fd9dbd933.png)

I don't know if it's expected.

JSON payload returned by API only contains 25 first switches and not all the switches.

When I used `pidstat 1`, I see that `pfperl-api` processes used 100% of all CPUs available on the machine to answer requests.

**Comment by jrouzierinverse** [comment]
How many roles do they have?
