### ISSUE TITLE
Include 3Com SS4400 (SuperStack) switch in the compatibility list

### ISSUE THREAD

**Issue by fcpimenta** [inverse-inc/packetfence#6325]
**Is your feature request related to a problem? Please describe.**
I am trying to configure many switches we have in our company to activate Captive Portal using Aruba Instant as a wi-fi AP. But we noted that the switch **3Com SS4400** is not in the list of models. When I try to configure, packetfence informs me that this switch is not supported. Is it possible to include this model?

**Describe the solution you'd like**
I want to configure the correct switch for my environment and make it work correctly.

**Describe alternatives you've considered**
I've selected generic switch and other models, but it does not work as expected.

**Additional context**
N/A

**Comment by nqb** [comment]
Hello,

1. Which RADIUS attributes need to be returned to your 3COM SS4400 ?
2. Did you try to use [switch templates](https://www.packetfence.org/doc/PacketFence_Developers_Guide.html#_creating_a_new_switch_via_a_template) to achieve your goal ?

**Comment by fcpimenta** [comment]
Hi @nqb,

For the first question, I've researched the switch documentation, and here is what it shows:

**3Com Vendor Specific Attribute**

The default user levels on the Switch (monitor, manager, admin) are supported by a 3Com Vendor Specific Attribute (VSA). The Vendor-ID for 3Com is **43**. You must configure the RADIUS server to send this attribute in the Access-Accept message in order to specify the access level required for each user account. The configurable attribute values are:
1. Monitor (1) — the user can view all manageable parameters, except special/security features, but cannot change any manageable parameters.
2. Manager (2) — the user can access and change the operational parameters but not special/security features.
3. Administrator (3) — the user can access and change all manageable parameters.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/6945439/116116932-16082280-a692-11eb-97f1-f8bcec60f542.png">

For the second question, I tried to create a template, but I'm not sure if I am sending the correct response for the switch.

Can you help me?

**Comment by nqb** [comment]
Hello @fcpimenta,

If you are trying "to activate Captive Portal using Aruba Instant as a wi-fi AP", I don't think you read the correct manual section.
Switch template should cover most of your needs and allow you to return almost all RADIUS attributes.

If you want to do WebAuth, you will have to write your own switch module in Perl.

So it's important to be sure what you want to achieve.

**Comment by fcpimenta** [comment]
Hi @nqb,

I've managed to configure a switch template and authenticate with write access to the 3Com switch.

I think I was in the wrong way.

Thanks!!
