### ISSUE TITLE
regression: configurator sets valid_from field to current time in place of 1970-01-01 00:00:00

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6329]
**Describe the bug**
When you set password for `admin` account during configurator, frontend should send `valid_from: 1970-01-01 00:00:00` due to following bugs:
- https://github.com/inverse-inc/packetfence/issues/5390
- https://github.com/inverse-inc/packetfence/issues/5594

Bugs were fixed by @cgx and @julsemaan for 10.1.0 see https://github.com/inverse-inc/packetfence/commits/54ccc203bd95b10bf310f9444f9c0a7e076abd04/html/pfappserver/root/static.alt/src/views/Configurator/_components/AdministratorView.vue

but I suppose a regression has been introduced by refactor related to 10.3 because now frontend sends current time on system.

**To Reproduce**
1. Pass step 2 in configurator without changing timezone
2. Check `valid_from` field in DB for `admin` user

**Expected behavior**
`valid_from` field should be `1970-01-01 00:00:00` for admin user.

**Comment by nqb** [comment]
I will improve integration test to check value of `valid_from` and `expiration` in DB.

**Comment by nqb** [comment]
It will not possible to add easily an integration test now because Venom is sending itself `valid_from` field with correct value.

**Comment by satkunas** [comment]
This regression is not UI borne.  Its origin is from the db setup (see `NOW()`):

https://github.com/inverse-inc/packetfence/blob/devel/db/pf-schema-10.3.0.sql#L491

**Comment by satkunas** [comment]
@nqb try the following patch. Commit these changes if you agree that no further regressions will be created:

```diff
diff --git a/db/pf-schema-10.3.0.sql b/db/pf-schema-10.3.0.sql
index 24d01b7..d1f1c5b 100644
--- a/db/pf-schema-10.3.0.sql
+++ b/db/pf-schema-10.3.0.sql
@@ -488,7 +488,7 @@ CREATE TABLE `password` (
 
 INSERT INTO `person` (pid,notes) VALUES ("admin","Default Admin User - do not delete");
 INSERT INTO `person` (pid,notes) VALUES ("default","Default User - do not delete");
-INSERT INTO password (pid, password, valid_from, expiration, access_duration, access_level, category) VALUES ('admin', 'admin', NOW(), '2038-01-01', NULL, 'ALL', NULL);
+INSERT INTO password (pid, password, valid_from, expiration, access_duration, access_level, category) VALUES ('admin', 'admin', '1970-01-01', '2038-01-01', NULL, 'ALL', NULL);
 
 --
 -- Trigger to delete the temp password from 'password' when deleting the pid associated with
 ```

**Comment by nqb** [comment]
@satkunas, I agree that we create user with `NOW()` but if I compared previous `pf-schema.sql`, we always create `admin` user like this (for example: [10.1 schema](https://github.com/inverse-inc/packetfence/blob/78b48ed629a83faa2b8b0dffa2b55a683af98f5c/db/pf-schema-10.1.0.sql)).

When frontend call API to update `admin` password (`/api/v1/configurator/user/admin/password`), it could modify `valid_from` field. See how it's done during [integration tests](https://github.com/inverse-inc/packetfence/blob/78b48ed629a83faa2b8b0dffa2b55a683af98f5c/t/venom/pfservers/configurator/20_run_configurator_step2.yml#L191-L206)

**Comment by satkunas** [comment]
@nqb just because we did it "previous"-ly doesn't make it right. Is there a need to setup the DB with the wrong value, only to change it seconds later with the right value? Why not just insert the right value in the first place during creation? What happens when the wrong value is inserted during creation and the configurator is skipped and the setup is done manually?

**Comment by nqb** [comment]
> just because we did it "previous"-ly doesn't make it right.

100% agree. My idea was just to report that something change since previous version and cause issue.

You approach makes sense. I will create a PR with your patch, adjustements on integration tests and also on ZEN (because we also create `demouser` on ZEN [like this](https://github.com/inverse-inc/packetfence/blob/78b48ed629a83faa2b8b0dffa2b55a683af98f5c/ci/packer/zen/scripts/install-pf.sh#L36))

**Comment by satkunas** [comment]
@nqb patch also needs to be applied to https://github.com/inverse-inc/packetfence/blob/devel/db/pf-schema-X.Y.Z.sql#L491

**Comment by nqb** [comment]
done.

**Comment by thedeco** [comment]
@nqb Is it correct to say that the 10.3 ZEN OVF as currently released is broken by this? I ran into the same issue while trying to configure PF for the first time and couldn't log in.

**Comment by nqb** [comment]
Hello @thedeco,

Yes that's correct. Solution:
1. Boot ZEN
2. [Apply maintenance patches](https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_maintenance_patches)
3. Start to configure PacketFence using configurator
