### ISSUE TITLE
ZEN: demouser is not visible in Users until you used it

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6331]
**Describe the bug**
During ZEN build, we add a `demouser` which can be used as a user to register devices using captive portal, 802.1X or device-registration process with "default" role.

However, I see several problems:
- `demouser` is not visible in "Users" menu after you setup a ZEN, I don't know why.
- if ZEN image is used in production, somebody can use this account to gain `default` role. Of course, role needs to be mapped to a VLAN but..

I wonder if we should keep this account. Creating a default account for testing purpose will take 1 minute and we can easily automate that part during our manual tests.

**Comment by julsemaan** [comment]
The user isn't visible because its likely in the password table but not in the person table

@extrafu, opinion on keeping `demouser` ?

I'm fine with removing it, we just need to remove that from the doc too since there is a reference to it from what I recall

**Comment by nqb** [comment]
It's on my TODO list for new ZEN image.

**Comment by extrafu** [comment]
We could remove it and in the doc, say how to create it.
