### ISSUE TITLE
configurator: high-availability is not displayed correctly by frontend

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6334]
**Describe the bug**
When you configure an interface with `high-availability` setting enabled during configurator, `high-availability` is correctly enabled in the backend but frontend displays it as disabled.

**To Reproduce**
1. Configure an interface with high-availability during first step of configurator

=> Setting appear as disabled on fronted.

Certainly related to #5964 

**Expected behavior**
`high-availability` setting displayed correctly.

**Additional context**
- Frontend receives `"high_availability": 0` when doing initial GET
- Frontend sends `"high_availability": "enabled` when doing PATCH
- Frontend receives `"high_availability": 1` when doing last GET

**Comment by nqb** [comment]
It looks like `high-availability` column is not displayed anymore during configurator.
Is it expected @satkunas ?

**Comment by satkunas** [comment]
@nqb AFAIK it never **was** displayed.

**Comment by nqb** [comment]
Work as expected, closing
