### ISSUE TITLE
web admin(preferences): language can be change in two places

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6337]
**Describe the bug**
As mentioned on #6311 by @cgx:

> I suggest we remove the _Français/English_ item from the dropdown of the top navigation bar and only keep the language option on the preferences page.

I agree with this proposal, it makes more sense. I tested on nightly build and it looks like this suggestion has not been taken into account.

Could you look into this @satkunas ?

**Comment by cgx** [comment]
From a user's perspective it would makes sense to remove the option from the navigation bar. However, as discussed with @satkunas, from a developer's perspective it  is convenient to be able to quickly switch the interface locale. My new suggestion would be to keep the option in the navigation bar in *debug* mode only.

**Comment by nqb** [comment]
It looks like there is an incompatibility between the two methods.
