### ISSUE TITLE
NTLM Auth cache: ldapsearch used in get_sync_samaccountname function is wrong

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6342]
**Describe the bug**
[LDAP search uses to find sAMAccountName of user to pass to `secretsdump.py`](https://github.com/inverse-inc/packetfence/blob/02b824046aaf21e770c79613b5a3e7bad87562bc/lib/pf/domain/ntlm_cache.pm#L210-L212) script is wrong at two places:
- binddn should be basedn, fixed by #6340 
- search is not limited to username defined in AD source used for NTLM Auth cache. So LDAP query returns all results that match the filter.

I'm not able to understand how this feature can work at the moment.

**Comment by davywan** [comment]
@nqb were you able to authenticate via AD/LDAP?

**Comment by nqb** [comment]
@davywan, not sure to understand what you mean.

**Comment by davywan** [comment]
I have been trying to set up radius authentication through LDAP and kept getting errors on authentication.

**Comment by davywan** [comment]
@nqb I thought maybe you might know how to solve it

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for such question.

**Comment by davywan** [comment]
@nqb Sure, thank you.
