### ISSUE TITLE
Provide a way to audit admin access to PacketFence

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6345]
**Is your feature request related to a problem? Please describe.**
Currently, there is no simple way to track who and when access to web admin interface to PacketFence.

Information is not recorded in Admin API Audit log, only in logs.

Unless I'm missing something, I don't see a place in DB where information is saved at the moment.

**Describe the solution you'd like**
Record access to /login in `admin_api_audit_log` table.

**Additional context**
It should include all type of accounts: local and remote (like AD accounts).

**Comment by jrouzierinverse** [comment]
Should we also log failed login?

**Comment by nqb** [comment]
I would say no because we want to audit who do what on a PacketFence server.
