### ISSUE TITLE
API: error message should be more explicit when using a .local domain

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6350]
**Describe the bug**
When you try to configure a '.local' domain during configurator (step 2), you got following error message:

`Unable to validate: An error occured while updating the general configuration.`

Which is not very explicit. You have to look into web browser console to see exact reason of issue.

**To Reproduce**
1. Start a fresh 10.3 install
2. Go to step 2 of configurator
3. Configure 'example.local' as Domain
4. Save

=> You got an error.

**Expected behavior**
Display error message returned by API (visible in web browser console)

**Additional context**
If you try to configure a '.local' domain using Configuration menu (after configurator has been disabled), you got correct message displayed by frontend.

**Comment by jrouzierinverse** [comment]
I think @satkunas would be better handle this issue if not reassign it to me.

**Comment by satkunas** [comment]
The error should be improved on the backend since the UI is not the only consumer. Reassigning.

**Comment by jrouzierinverse** [comment]
This error is coming from the frontend not the backend.

https://github.com/inverse-inc/packetfence/blob/fc25d33a27aaa4be17a04747b52e54e3d597b616/html/pfappserver/root/src/views/Configurator/packetfence/_components/FormGeneral.vue#L104

**Comment by jrouzierinverse** [comment]
```bash
./sbin/pfperl-api get -M PATCH -c '{ "domain":  "bob.local"}' /api/v1/config/base/general | jq .
```
```json
{
  "errors": [
    {
      "field": "domain",
      "message": "The domain name cannot end with '.local' as this causes issues with Apple iOS devices"
    }
  ],
  "message": "Unable to validate",
  "status": 422
}
```

**Comment by nqb** [comment]
Using /api/v1/configurator/config/base/general, I got this result:

```json
# pfperl-api get -M PATCH -c '{ "domain":  "example.local"}' /api/v1/configurator/config/base/general | jq
{
  "errors": [
    {
      "field": "domain",
      "message": "The domain name cannot end with '.local' as this causes issues with Apple iOS devices"
    }
  ],
  "message": "Unable to validate",
  "status": 422
}
```
but throug GUI, I got this:
![Capture d’écran de 2021-08-06 10-47-27](https://user-images.githubusercontent.com/10830260/128484078-df02e804-bcaf-4fa2-b374-f14a1c8634db.png)

=> Message related to domain name is not displayed to user.

**Comment by satkunas** [comment]
@nqb please test e037c815aabb91e4f1c023456c288aeaec66480e w/ the next nightly builds. If the issue persists I will follow-up early next week. I want to ensure that an error at the end of the configurator properly stops the setup-chain and the user is able to navigate back to the interface settings without issue(s).

**Comment by satkunas** [comment]
@jrouzierinverse what is preventing the above error from being returned when re-running the configurator  for a 2nd+ time?

**Comment by jrouzierinverse** [comment]
As far as I can tell there is nothing preventing this from being returned. 
Can you provide me the payload that caused this?

**Comment by nqb** [comment]
What I did:
1. Step 1: configure interfaces
2. Step 2: configure DB + domain part with `example.local` domain + admin account password

When I clicked on "Next step", I got **expected** message returned by frontend. I was able to go back to previous step (step 1). When I go back to step 2, DB configuration was done and frontend correctly detect it. Domain config has been removed and I can enter a new one.

**Comment by nqb** [comment]
Closing.

**Comment by satkunas** [comment]
The `PUT config/system/gateway` is only called on subsequent configurations when the gateway is mutated. Therefore the `hostname` warning is not produced the 2nd+ configuration if the `gateway` is left as-is.

Ref: https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/src/views/Configurator/network/_components/TheList.vue#L291-L295

 @nqb @jrouzierinverse should we alter this behaviour?

**Comment by nqb** [comment]
If the warning has been displayed the first time, user should remember it ?

**Comment by satkunas** [comment]
Direct feedback has been added to the form to show an inline warning with .local domains. This addresses the last issue mentioned above.

![Screen Shot 2021-08-10 at 9 57 25 AM](https://user-images.githubusercontent.com/3904468/128880211-b1401c5c-164a-4f2d-8ead-4ddd15c3db7e.jpg)
