### ISSUE TITLE
zen does not setup ipv6 firewall

### ISSUE THREAD

**Issue by luizluca** [inverse-inc/packetfence#6351]
**Describe the bug**

While doing a network scan, I noticed that packetfence did answered some services through IPv6.
I checked and ip6tables is clean:

```
[root@vms188l etc]# ip6tables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```      

Shouldn't packetfence be responsible to, at least, block incoming IPv6 traffic?

I'm using zen running with packetfence-10.2.0-20201007132254.199263253.0007.v10.2.0.el7.x86_64.
It is not the latest but I didn't find anything related in changelog.

**To Reproduce**
* Setup IPv6 address using packetfence web interface.
* check ip6tables

**Comment by nqb** [comment]
Same behavior on Debian running 10.3 and on ZEN running 10.3.

**Comment by jrouzierinverse** [comment]
As a patch we could just block all ipv6 traffic via sysctl.

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

```
In a future version we can handle it properly like how we handle iptables but as a separate service for ip6tables.

**Comment by luizluca** [comment]
A bad configured IPv6 is worse than no IPv6. However, I would prefer a static firewall settings that block INPUT/FORWARD. IPv6 might be used by default for some services, specially those listening at ::1 (localhost). And there is no reason to block the ZEN OS from accessing IPv6 services (active directory, NTP, DNS).

Just copy the rules (ip6tables-save) generated by any good firerall manager solution to a file and load it with the system. It would be secure, easy and harmless. It is a crude solution that should be replaced by a prober firewall support in the future.

I would suggest to integrate PF with firewalld (defacto enterprise standard) and let it do the basics. It would be cheaper. Nobody needs another firewall manager.

**Comment by luizluca** [comment]
As there is no official workaround, I installed iptables-service with a "block all incoming" policy inspired by firewalld standard rules:

<pre>
yum install iptables-services
cat > /etc/sysconfig/ip6tables <<'EOS'
# Completed on Wed Jun  2 16:41:02 2021
# Generated by ip6tables-save v1.8.7 on Wed Jun  2 16:41:02 2021
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p ipv6-icmp -m icmp6 --icmpv6-type 134 -j ACCEPT
-A PREROUTING -p ipv6-icmp -m icmp6 --icmpv6-type 135 -j ACCEPT
-A PREROUTING -m rpfilter --invert -j LOG --log-prefix "rpfilter_DROP: "
-A PREROUTING -m rpfilter --invert -j DROP
COMMIT
# Completed on Wed Jun  2 16:41:02 2021
# Generated by ip6tables-save v1.8.7 on Wed Jun  2 16:41:02 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:RFC3964_IPv4 - [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED,DNAT -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -m pkttype --pkt-type unicast -j LOG --log-prefix "STATE_INVALID_DROP: "
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 128 -j ACCEPT
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 134 -j ACCEPT
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 135 -j ACCEPT
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 136 -j ACCEPT
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 137 -j ACCEPT
-A INPUT -m pkttype --pkt-type unicast -j LOG --log-prefix "FINAL_REJECT: "
-A INPUT -j REJECT --reject-with icmp6-adm-prohibited
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED,DNAT -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -j RFC3964_IPv4
-A FORWARD -m conntrack --ctstate INVALID -m pkttype --pkt-type unicast -j LOG --log-prefix "STATE_INVALID_DROP: "
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -m pkttype --pkt-type unicast -j LOG --log-prefix "FINAL_REJECT: "
-A FORWARD -j REJECT --reject-with icmp6-adm-prohibited
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -j RFC3964_IPv4
-A RFC3964_IPv4 -d 2002:e000::/19 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:e000::/19 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002:a9fe::/32 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:a9fe::/32 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002:c0a8::/32 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:c0a8::/32 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002:ac10::/28 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:ac10::/28 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002:7f00::/24 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:7f00::/24 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002:a00::/24 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002:a00::/24 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d 2002::/24 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d 2002::/24 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d ::ffff:0.0.0.0/96 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d ::ffff:0.0.0.0/96 -j REJECT --reject-with icmp6-addr-unreachable
-A RFC3964_IPv4 -d ::/96 -j LOG --log-prefix "RFC3964_IPv4_REJECT: "
-A RFC3964_IPv4 -d ::/96 -j REJECT --reject-with icmp6-addr-unreachable
COMMIT
# Completed on Wed Jun  2 16:41:02 2021
EOS
systemctl enable --now ip6tables.service
</pre>

**Comment by nqb** [comment]
Moving milestone to 11.0.

**Comment by julsemaan** [comment]
discussed this with @extrafu and this is a bit late for v11, postponing to v11.1

**Comment by julsemaan** [comment]
I'll work on this with @nqb 

Based on our discussion:
- We will create a new ip6tables service
- The management interface will allow ports 22, 80, 443 and 1443 to be reached, other ipv6 traffic will be dropped
- There should be override files for adding your own rules without changing ip6tables.conf (like we recently added for iptables.conf)
- @nqb will setup an environment in our integration tests to assess that this new service works
- I will work on the code for the new service
