### ISSUE TITLE
DHCP Option 82 Logs Created At 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#6353]
**Describe the bug**
DHCP Option 82 Audit Log is not inserting Created At date.

** LOG **
```
May 11 14:55:18 pf-01 pfqueue: pfqueue(23287) WARN: [mac:84:a9:3e:10:28:57] Warning: 1265: Data truncated for column 'created_at' at row 1 (pf::dal::db_execute)
May 11 14:55:18 pf-01 pfqueue: pfqueue(23287) WARN: [mac:84:a9:3e:10:28:57] Warning: 1265: Data truncated for column 'created_at' at row 1 (pf::dal::db_execute)
```

**Screenshots**
<img width="604" alt="Screenshot 2021-05-12 at 7 54 06" src="https://user-images.githubusercontent.com/17347347/117920268-43daa180-b2f7-11eb-9852-4802ee8d9a99.png">

**Comment by julsemaan** [comment]
@jrouzierinverse, can you take a look?
