### ISSUE TITLE
Active Directory Authentication Source writes wrong server value to freeradius config

### ISSUE THREAD

**Issue by heiko-ma** [inverse-inc/packetfence#6354]
**Describe the bug**
When the active directory authentication source is created, the config-wizard does not correctly safe the value for the host field. Instead of the ip-address/hostname, the following value is written to the radiusd ldap config:
ARRAY(0x873b8b0)

**To Reproduce**
1. Create a new authentication source (type Active Directory or LDAP)
2. Fill out the form 
3. Click on save
4. Check the packetfence ldap-config located under **/usr/local/pf/raddb/mods-enabled/ldap_packetfence**

**Expected behavior**
The config-option server should contain the entered information from the GUI

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 90

**Additional context**
I suppose the value from the GUI option is not correctly transferred to the config file for radiusd. Because the file is created from a template, it gets overridden on each boot of radiusd, therefore editing the file manually won't work

**Comment by julsemaan** [comment]
I believe this has been fixed in the maintenance since I hit the same bug on 10.3 last week

Perform these:
```
/usr/local/pf/addons/pf-maint.pl
/usr/local/pf/bin/pfcmd service pf restart
```

And let us know if its still there

**Comment by heiko-ma** [comment]
This seems to have fixed the config itself, but now there is another problem:

> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) Auth-Type := AD
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) &Called-Station-Id !* ANY
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) &Called-Station-Id := f8:b1:56:94:ff:1a
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) # Executing group from file /usr/local/pf/raddb/sites-enabled/packetfence-tunnel
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: WARNING: You have set "Auth-Type := LDAP" somewhere
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: WARNING: *********************************************
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: WARNING: * THAT CONFIGURATION IS WRONG. DELETE IT.
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: WARNING: * YOU ARE PREVENTING THE SERVER FROM WORKING
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: WARNING: *********************************************
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) AD: ERROR: Attribute "User-Password" is required for authentication
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) # Executing group from file /usr/local/pf/raddb/sites-enabled/packetfence-tunnel
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) &request:User-Password := "******"
> May 12 14:12:54 in99sv-nws01 auth[18505]: rlm_sql (sql): Reserved connection (2)
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) sql_reject: SQL query returned: success
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) sql_reject: 1 record(s) updated
> May 12 14:12:54 in99sv-nws01 auth[18505]: rlm_sql (sql): Released connection (2)
> May 12 14:12:54 in99sv-nws01 auth[18505]: (11) &Module-Failure-Message := &request:Module-Failure-Message -> 'AD: Attribute "User-Password" is required for authentication'

Is there something wrong with my packetfence-config or this is another backend problem? I followed the Documentation while creating the Active Directory Domain aswell as the Authentication Source

**Comment by julsemaan** [comment]
That's not how you should authenticate users against an AD but that's a subject for the mailing list, not for here
