### ISSUE TITLE
Time balance subtracted when unreg

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6358]
title says it all

**Comment by lzammit** [comment]
After discussed with the world known @julsemaan we could check the registration date and if it pretty recent (ex: 5 mins) we won't decrease the time

**Comment by julsemaan** [comment]
@fdurand, do you have a better idea to detect a balance that shouldn't be substracted on a stop when switching from unreg to reg ?

Otherwise we could ask @jrouzierinverse to implement that, it should be relatively straightforward

**Comment by julsemaan** [comment]
And we'd also need to check that the status of the node is currently "reg"

**Comment by fdurand** [comment]
In fact we need to keep the interim accounting -1 and when the device register use this value as the new start.

**Comment by julsemaan** [comment]
makes it more complex than the solution above though since we have to track this value somewhere. We could always leverage the regdate to calculate the amount of time you were really reg during that session

**Comment by julsemaan** [comment]
The eye of the tiger (@fdurand) spotted that the soft query hasn't been adjusted
https://github.com/inverse-inc/packetfence/blob/devel/go/cmd/pfacct/radius.go#L554

This means that if your balance goes under 0 while unreg because of the interim updates, you'll lose all your balance.
The same unreg/reg logic needs to be there

**Comment by nqb** [comment]
`pfacct` Golang unit tests failed on CentOS 7 and Debian 9 this night: https://gitlab.com/inverse-inc/packetfence/-/jobs/1281692851#L534.

This is certainly related.

**Comment by lzammit** [comment]
What do we do for that one ?

**Comment by lzammit** [comment]
Any news @jrouzierinverse ?
