### ISSUE TITLE
uninitialized value $switch_mac at /usr/local/pf/lib/pf/locationlog.pm line 487.

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6366]
**Describe the bug**
Packetfence log show a warning with the `Use of uninitialized value $switch_mac in string ne at /usr/local/pf/lib/pf/locationlog.pm line 487.`

**To Reproduce**
I notice that there is no `Called-Station-Id` in the radius request

**Expected behavior**
No more warning

**Comment by jrouzierinverse** [comment]
Fixed by 9737a2b7bbeedc73a2c49e7179a4cc1042adc4c7

**Comment by lyubomirtraykov** [comment]
Please reopen. Now the warning:
`Use of uninitialized value in string ne at /usr/local/pf/lib/pf/locationlog.pm line 487. (pf::locationlog::_is_locationlog_accurate)`
