### ISSUE TITLE
PKI -- State should be maintained while going through the flow

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#638]
e.g. If the user closes his browser.

**Comment by julsemaan** [comment]
Opinion needed !
The original issue I wanted to point out is the fact that refreshing the page breaks the flow.
Now this is fixed

Next, should closing and reopening the browser bring back the TLS generation page or the user logs in again ? (this could get messy)

NOTE: When the user has generated the certificate the flow is restored properly (User goes to the proper provisioning page)

**Comment by louismunro** [comment]
Done.
