### ISSUE TITLE
webadmin(PKI): templates are not displayed as read-only

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6382]
**Describe the bug**
If you click on a template, you can edit some fields like Country, Organisation, etc. But you can't save your changes.

I think it's expected that you can't save but fields should be marked as read-only like on CA or Certificates tabs.

**To Reproduce**
1. Create a CA
2. Create a template associated to your CA
3. Click on your template

=> You can change some values and almost all fields are not marked as read-only.

**Expected behavior**
All fields should be marked as read-only.

**Comment by satkunas** [comment]
@fdurand does templates support UPDATE? or are they still read-only once created?

**Comment by fdurand** [comment]
we changed it to support UPDATE

**Comment by satkunas** [comment]
UI updated in e21b4af67edb9a80cf4cfea5d344b42cf2983965

However, I'm seeing the following error w/ `PATCH`:

```
{"errors":null,"message":"json: cannot unmarshal string into Go struct field Profile.ID of type uint","status":500}
```

Using payload:
```json
{
    "id": "3",
    "isClone": false,
    "isNew": false,
    "ca_id": "2",
    "ID": 3,
    "CreatedAt": "0001-01-01T00:00:00Z",
    "UpdatedAt": "0001-01-01T00:00:00Z",
    "DeletedAt": null,
    "DB": {
        "Value": null,
        "Error": null,
        "RowsAffected": 0
    },
    "Ctx": null,
    "name": "testzzz",
    "ca_name": "test",
    "validity": "365",
    "key_type": "1",
    "key_size": "2048",
    "digest": "4",
    "key_usage": "",
    "extended_key_usage": ""
}
```

**Comment by fdurand** [comment]
Not the case anymore. Close it.
