### ISSUE TITLE
Sponsor registration: notes field can't be used on captive portal

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6385]
**Describe the bug**
When doing sponsor registration on captive portal using portal modules, you can specify "notes" field as a mandatory field. It could be used to let user specify some motivations related to its registration.

However, when doing sponsor registration, PacketFence automatically write some informations into "Notes" field. Consequently, notes entered by user are lost.

**To Reproduce**
1. Create a portal module that use default sponsor source with "notes" as a mandatory field
2. Define a connection profile which use your new portal module
2. Add "Mark as sponsor" right to admin user
3. Try to register on captive portal using sponsor source with admin user 
4. Add some content into notes field
4. Check value of "notes" field in PacketFence web admin after node has been registered

=> It contains "sponsored .."

**Expected behavior**
We should keep notes entered by user.

**Comment by jrouzierinverse** [comment]
The note is used record the Date of arrival.
Maybe we should add the date the user was sponsored in the person table.
To avoid updating the note.

**Comment by nqb** [comment]
Agree @jrouzierinverse, it could make more sense.

**Comment by jrouzierinverse** [comment]
Let's add this as a new feature for 12.1
