### ISSUE TITLE
Web admin: Prevent the usage of /32 switches in the configuration

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6386]
Having a switch with 1.2.3.4/32 will break your flow and the web admin allow it.

We should either block it in the switch creation or clean it when it's imported into the radius_nas table.

**Comment by julsemaan** [comment]
@lzammit, please test and we can push this to the maintenance afterwards

**Comment by jrouzierinverse** [comment]
Do we still want this maintenance?

**Comment by jrouzierinverse** [comment]
Do we want a script to normalize all /32 to a single ip address.

**Comment by julsemaan** [comment]
I don't think the script belongs in the maintenance but the fix that ensures no `/32` gets configured in the switches.conf can go there

**Comment by jrouzierinverse** [comment]
By putting this is maintenance a person cannot use a /32 to create a new switch.

But will be able to modify any old switches that are /32.

However if they have both /32 and single ip then only the single ip switch will be taken in consideration.
