### ISSUE TITLE
web admin(pfpki): unable to create certificates with CN equal to MAC addresses

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6393]
**Describe the bug**
Web admin prevents you to create certificates with CN equal to MAC addresses.

`pfpki` supports creating certificates with CN equal to MAC addresses through PKI providers.

**To Reproduce**
1. Create a CA and a template
2. Try to create a certificate with CN equals to MAC address

=> You got "Invalid common name" error

**Expected behavior**
MAC Address as certificate CN is allowed.

**Comment by nqb** [comment]
https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/src/views/Configuration/pki/certs/schema.js#L43

**Comment by satkunas** [comment]
Fixed in 536dbf17b579de44dc03b4c6e5aa30a46db9da9e
