### ISSUE TITLE
802.1X against FreeIPA LDAP source

### ISSUE THREAD

**Issue by mvalois** [inverse-inc/packetfence#6405]
Hi,
I've installed PacketFence 10.3.0 and I would like to enable 802.1X on my network using my FreeIPA LDAP as a source of authentication using EAP if possible (computers are all debian 10 using network manager). Is that even possible, and if it is, where can I find resources to achieve such a thing?

Following the install documentation leaded me to always get authentication errors because the mschap binary failed complaining it's not in the domain.

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
