### ISSUE TITLE
PF 10.3 - Broken Reports

### ISSUE THREAD

**Issue by bbs2web** [inverse-inc/packetfence#6408]
Several of the reports are non functional after upgrading from PF 10.2 on a Debian 9 host.

The following display no data:
- Standard Reports \ Node \ Operating System
- Standard Reports \ Connections \ Type
- Standard Reports \ Connections \ SSID (All)
- Standard Reports \ Authentication \ Failures
- Standard Reports \ Authentication \ Successes

Sample view:
![image](https://user-images.githubusercontent.com/1456100/123422194-21a69580-d5be-11eb-864b-811031151d4e.png)

Other reports, such as Standard Reports \ Node \ Operating System Class, work perfectly:
![image](https://user-images.githubusercontent.com/1456100/123422323-561a5180-d5be-11eb-8f51-0865b1138bac.png)

**Comment by julsemaan** [comment]
Are you getting any errors in packetfence.log ? Or any errors in the admin interface ?

**Comment by bbs2web** [comment]
None in the UI and packetfence.log is completely silent.

It appears only 'httpd.api-frontend.access' logs anything:
```
Jun 25 17:04:34 packetfence2 pfhttpd[1763]: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/dynamic_reports?sort=id&fields=id,description,long_description,type HTTP/1.1" 200 5759 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd[1763]: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/system_summary HTTP/1.1" 200 151 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd[1763]: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/dynamic_reports?sort=id&fields=id,description,long_description,type HTTP/1.1" 200 5759 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd[1763]: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/node_categories?limit=1000 HTTP/1.1" 200 1294 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/dynamic_reports?sort=id&fields=id,description,long_description,type HTTP/1.1" 200 5759 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/system_summary HTTP/1.1" 200 151 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/dynamic_reports?sort=id&fields=id,description,long_description,type HTTP/1.1" 200 5759 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:34 packetfence2 pfhttpd: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:34 +0200] "GET /api/v1/node_categories?limit=1000 HTTP/1.1" 200 1294 "https://pf.company.com:1443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Jun 25 17:04:37 packetfence2 pfhttpd[1763]: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:37 +0200] "POST /api/v1/firewall_sso/stop HTTP/1.1" 202 0 "-" "-"
Jun 25 17:04:37 packetfence2 pfhttpd: api-frontend-access 127.0.0.1 - - [25/Jun/2021:17:04:37 +0200] "POST /api/v1/firewall_sso/stop HTTP/1.1" 202 0 "-" "-"
```

What I did however notice is that the 'Operating System' report loads when I first navigate to 'Inactive'. Not when I then refresh or first navigate to 'Operating System Class' (which itself works).
![image](https://user-images.githubusercontent.com/1456100/123448336-19a91e80-d5db-11eb-8402-4b25780e672c.png)

Running Chrome 91.0.4472.114 (latest) on Windows 10...

**Comment by julsemaan** [comment]
Can you make sure you're up to date with maintenance patches (/usr/local/pf/addons/pf-maint.pl). If it does it with the latest patches, we'll have to dig into the specific query by adding more debug

**Comment by bbs2web** [comment]
Debian 9 is as up to date as possible and again ran /usr/local/pf/addons/pf-maint.pl to apply updates. Problem continues:

If I navigate to 'Reports' it defaults to '/admin#/reports/standard/chart/os' which results in a graph with no data. If I then click on 'Inactive' and then select 'Operating System' graphs it displays but then displays again as 'no data' when I then refresh my browser.

**Comment by julsemaan** [comment]
I was able to replicate that bug on that latest maintenance/10.3 and the response from the backend API looks fine so that seems like a frontend issue.

@satkunas, can you look into it, I was able to replicate the issue using these instructions from @bbs2web:

> If I navigate to 'Reports' it defaults to '/admin#/reports/standard/chart/os' which results in a graph with no data. If I then click on 'Inactive' and then select 'Operating System' graphs it displays but then displays again as 'no data' when I then refresh my browser.

**Comment by satkunas** [comment]
I was also able to reproduce. I've reworked the report initialization.

@julsemaan @bbs2web please apply the maintenance patch and try again.
