### ISSUE TITLE
Search not working on "Nodes" page

### ISSUE THREAD

**Issue by CraftMarine** [inverse-inc/packetfence#6411]
**Describe the bug**
When on the node page, I try to search for a node, (tried by role and mac address). And the page just give me an unknown error and don't display any result.
It's a bit random, but always appear on the second search in a row. Also when using the "advanded search filter".

I didn't noticed the issue in the "Audit" tab

This is what I got in "packetfence.log" :  packetfence: pfperl-api(14361) ERROR: Not an ARRAY reference at /usr/local/pf/lib/pf/UnifiedApi/Search/Builder.pm line 213.
 (Mojolicious::Plugin::DefaultHelpers::_development)

I tried with Firefox, Chrome and Edge, all with clean cache, same issue. Even with another computer
**To Reproduce**
1. Go to 'Web interface -> Nodes'
2. Search for something
3. 
![image](https://user-images.githubusercontent.com/33558111/123642696-e0afba80-d823-11eb-8b87-56c2ea8f9fd5.png)

**Expected behavior**
Should display the items I've filtered.

**Desktop (please complete the following information):**
 - OS: Win10 
 - Browser: Firefox (89.0.2) - Opera (77.0.4054.90) - Edge (91.0.864.59)

**PacketFence version :**
 - OS: CentOS 7
 - Version: 10.2.0

**Additional context**
Happened after patch with "pf-maint.pl"

**Comment by jrouzierinverse** [comment]
Which fields are you trying to display?

**Comment by jrouzierinverse** [comment]
I cannot be replicated the error.
However I seen this happen before the packetfence-pfperl-api service was not properly restarted after applying pf-maint.pl.
Try the following please
```
systemctl restart packetfence-pfperl-api
```

**Comment by CraftMarine** [comment]
After using "systemctl restart packetfence-pfperl-api", the issues seems to be gone.
