### ISSUE TITLE
PKI - PacketFence windows agent should compute the CA fingerprint by itself

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#642]
It has all the infos to do it. It's pretty useless to have that special case directly in PF

**Comment by whitx** [comment]
https://github.com/inverse-inc/packetfence-windows-agent/commit/7afca4227a15308d44d1a762c2a7d3d8140c9c26 get_fingerprint method added
3da3ba98700acca84142560fdfea14fc28165456 new agent
