### ISSUE TITLE
login-service no SSH

### ISSUE THREAD

**Issue by luolufang** [inverse-inc/packetfence#6427]
![image](https://user-images.githubusercontent.com/4510469/125055455-ca361880-e0d9-11eb-8974-abf2ff127c1d.png)

version : PF 10.3

**Comment by nqb** [comment]
Hello,

Please provide more details or we will need to close this issue.

**Comment by luolufang** [comment]
i need add CLI Authorize Read Scope in switch templates.
but i don't find   ( Login-service = SSH ) .



![image](https://user-images.githubusercontent.com/4510469/125059925-6cf09600-e0de-11eb-98e2-1b58d73bd995.png)


i find it in windows nps 

![image](https://user-images.githubusercontent.com/4510469/125060835-54cd4680-e0df-11eb-9149-e70f00351366.png)

**Comment by fdurand** [comment]
It's because ssh is not part of the IETF RFC 2865 and it looks that NPS doesn't care of that.
So if you want to have it available, you will need to add it in the dictionary.

in /usr/share/freeradius/dictionary.rfc2865
VALUE   Login-Service                   SSH         50
