### ISSUE TITLE
mysql always lock table

### ISSUE THREAD

**Issue by luolufang** [inverse-inc/packetfence#6428]
**Describe the bug**

i run a pf cluster  with 3 nodes.
sometime  packetfence-mariadb lock tables and  any auth was reply accept-reject

and when i restart   packetfence-mariadb. pf became ok

the last happendfrom Jul 12 12:57:15  to Jul 12 1:00:00

**Screenshots**

![image](https://user-images.githubusercontent.com/4510469/125237346-1ff80400-e318-11eb-858d-40f09672a9cb.png)

**Expected behavior**

**Additional context**
 packetfence   log file
[log.zip](https://github.com/inverse-inc/packetfence/files/6798911/log.zip)

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
