### ISSUE TITLE
Network Anomaly Detection - config error? 

### ISSUE THREAD

**Issue by aziel12** [inverse-inc/packetfence#6429]
**Describe the bug**
Hello guys, I'm new to packetfence. I would like to know how anomaly detection in packetfence works, but could not find precise resources explaining what is what and how all works. I'm using community account for fingerbank and an error I'm getting is, under Network behavior policy: "Your Fingerbank account currently doesn't have access to the network behavior analysis API endpoints..". Do I have to have premium subscription for fingerbank or is my configuration somewhere wrong? 
Thanks

Error: Go to : Configuration => Compliance => Network anomaly detection
![p1](https://user-images.githubusercontent.com/87038792/125295620-b3840180-e325-11eb-9d10-b2ca8e118c7f.png)

![p3](https://user-images.githubusercontent.com/87038792/125295379-791a6480-e325-11eb-9845-4c64e877075c.png)

**Comment by julsemaan** [comment]
Hi,

Network Anomaly Detection is currently only available for customers that have a valid support contract with us.

You can get in touch with our sales team at info@inverse.ca

Thanks,
