### ISSUE TITLE
add Bypass VLAN to node

### ISSUE THREAD

**Issue by marekhrbac** [inverse-inc/packetfence#6432]
Hello,
i tried to add bypass to node. it worked perfectly when i added it through "Bulk Action"
![Pic1](https://user-images.githubusercontent.com/50436103/125620933-763195ea-673b-459b-9618-fa7dbd1d282b.PNG)

But when i tried it through specific node, nothings happened.
![Pic2](https://user-images.githubusercontent.com/50436103/125621182-ab27ad57-4fdb-45b1-8894-0da82aaf4a01.PNG)

Thank you
Marek

**Comment by nqb** [comment]
On a 10.3 with all maintenance patches applied, I'm able to set a bypass VLAN and a bypass role on a node. Fields are correctly updated in DB.

I don't think there is a bug here.

**Comment by marekhrbac** [comment]
when i set bypass vlan in the settings of the node, CoA doesnt change VLAN
because PF doesnt send CoA message to switch. When i set bypass vlan
through "Bulk Action", PF send CoA message to the switch

čt 15. 7. 2021 v 8:59 odesílatel Nicolas Quiniou-Briand <
***@***.***> napsal:
