### ISSUE TITLE
Restart switchport with CoA PortBounce

### ISSUE THREAD

**Issue by marekhrbac** [inverse-inc/packetfence#6433]
Is it possible to Restart Switchport in "Bulk Action" with CoA PortBounce?
![image](https://user-images.githubusercontent.com/50436103/125621682-5b493ba6-93d6-439d-a8cc-e3469649325b.png)

Thanks 
Marek Hrbáč

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
