### ISSUE TITLE
SAML redirect error , Always location to /protal_preview

### ISSUE THREAD

**Issue by b1cat** [inverse-inc/packetfence#6437]
**Describe the bug**
Saml redirect error , always location /protal_preview, but not redirect Idp sso .
I hope it works, but it doesn’t work no matter how I test it
Thanks you !

These proofs：
![image](https://user-images.githubusercontent.com/30470078/125885495-1202d7c0-f342-4ac0-a213-5c7c024ca7c6.png)
This follow redirect 
![image](https://user-images.githubusercontent.com/30470078/125885632-d29608f6-541b-49cb-af20-55746bc23660.png)
This response always location to /protal_preview
![image](https://user-images.githubusercontent.com/30470078/125885696-afb7d6d1-cd56-40cf-b223-118633075d49.png)

These settings：
1. Authentication Source smal-auth_source SAML:
Name
smal-auth_source

Description
smal-auth_source

Service Provider entity ID
https://192.168.28.67:1443/

Path to Service Provider key (x509)
/usr/local/pf/conf/ssl/server.key

Path to Service Provider cert (x509)
/usr/local/pf/conf/ssl/server.crt

Identity Provider entity ID
http://192.168.28.209:9501

Path to Identity Provider metadata
/usr/local/pf/conf/ssl/idp-metadata.xml

Path to Identity Provider cert (x509)
/usr/local/pf/conf/ssl/ca.pem

Path to Identity Provider CA cert (x509)
/usr/local/pf/conf/ssl/idp-ca.pem
If your Identity Provider uses a self-signed certificate, put the path to its certificate here instead.

Username Attribute
urn:oid:0.9.2342.19200300.100.1.1
Main reference attribute that contain the username.

Authorization source
local

2. Idp-metadata.xml
![image](https://user-images.githubusercontent.com/30470078/125886097-b00df171-11c3-4126-a9c8-823b4a1fce59.png)

3. Connection profiles 
Connection profiles  use the default .

**Comment by julsemaan** [comment]
The portal preview and SAML are incompatible like its the case with OAuth sources since it relies on redirect URLs that are precise

Use the real portal to test SAML and OAuth sources

**Comment by Akityo** [comment]
@julsemaan  Hello, one more question, how to access the real portal like URLs,path.  And how to modify saml redirect response page, i try to modify this file  /usr/local/pf/html/captive-portal/templates/redirect.tt  but it does't work

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
