### ISSUE TITLE
v11: Coredns Golang unit tests failed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6441]
**Describe the bug**
When running Golang unit tests on RHEL8, I got following results:

```
ok      github.com/inverse-inc/packetfence/go/coredns/request   0.396s
--- FAIL: TestMetricsSeveralBlocs (5.22s)
    metrics_test.go:165: Could not send message: read udp 127.0.0.1:44810->127.0.0.1:40015: i/o timeout
--- FAIL: TestReadme (18.95s)
    readme_test.go:80: Failed to start server with ../plugin/bind/README.md, for input "Listen: listen tcp [::1]:30062: bind: cannot assign requested address":
        . {
            bind 127.0.0.1 ::1
        }
    readme_test.go:80: Failed to start server with ../plugin/bind/README.md, for input "Listen: listen tcp [::1]:30063: bind: cannot assign requested address":
        . {
            bind 127.0.0.1
            bind ::1
        }
FAIL
FAIL    github.com/inverse-inc/packetfence/go/coredns/test      36.328s
```

**Comment by julsemaan** [comment]
I'm not getting this issue on the latest devel on my RHEL8 box

Could it be specific to running this in the docker image on the Gitlab runners ?

**Comment by nqb** [comment]
It could be a random issue. I will see if I'm able to replicate.

**Comment by nqb** [comment]
Not able to replicate on Debian 11.

**Comment by nqb** [comment]
@julsemaan, I'm able to replicate issue each time I run this Golang test on Vagrant VM in CI.

**Comment by jrouzierinverse** [comment]
Is there a way to find out what is listening to the tcp port 30062 and 30063 in the VM?

**Comment by jrouzierinverse** [comment]
I am able to replicate the error on my machine after I disabled ipv6 on my loopback device.
IPV6 needs to be enabled on the pfel8dev.

**Comment by nqb** [comment]
Good catch @jrouzierinverse, IPv6 is disabled in RHEL8 box (https://github.com/lavabit/robox/blob/cd60c607a87db17ee470d4cde92889dca9951c06/scripts/rhel8/network.sh).

I will re-enable it and check if it works.
