### ISSUE TITLE
v11: /api/v1/configurator/service/pf/update_systemd returns a HTTP 500 error

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6443]
**Describe the bug**
During configurator, when PacketFence is updating systemd, it returns a 500 HTTP error code on following API call:

`/api/v1/configurator/service/pf/update_systemd`

**To Reproduce**
1. Pass through configurator and try to start services

**Expected behavior**
Configurator should work as usual.

**Additional context**
@satkunas pushed a commit as a workaround https://github.com/inverse-inc/packetfence/commit/00d539b7d859cd937fb0caf2c4af186a9bbb7372

I'm able to replicate this issue with Venom tests.

**Comment by nqb** [comment]
Issue seems random.

**Comment by satkunas** [comment]
UI workaround also requires https://github.com/inverse-inc/packetfence/commit/296df6f9b6d5df49853331f22fa8331e9a3cff22

**Comment by nqb** [comment]
Venom logs output:

```
Failure in "/usr/local/pf/t/venom/pfservers/configurator/50_run_configurator_step4.yml:25"
In test case "update_systemd", at step 0
Assertion "result.statuscode ShouldEqual 200" failed
Expected: '200'
Actual:   '500'
(Should be equal)
Diff:     '2500'

 ------ Result: 
result.body: 500 Internal Server Error

result.bodyjson:
result.err:
result.executor.basicauthpassword:
result.executor.basicauthuser:
result.executor.body:
result.executor.bodyfile:
result.executor.headers.content-type: application/json
result.executor.ignoreverifyssl: true
result.executor.method: POST
result.executor.multipartform:
result.executor.nofollowredirect: false
result.executor.path:
result.executor.proxy:
result.executor.skipbody: false
result.executor.skipheaders: false
result.executor.unixsock:
result.executor.url: https://172.17.17.12:1443/api/v1/configurator/service/pf/update_systemd
result.headers.content-length: 26
result.headers.content-type: text/plain; charset=utf-8
result.headers.date: Thu, 22 Jul 2021 06:30:50 GMT
result.headers.server: Caddy
result.headers.x-content-type-options: nosniff
result.headers.x-frame-options: SAMEORIGIN
result.statuscode: 500
result.timehuman: 3.010867306s
result.timeseconds: 3.010867306

```

**Comment by nqb** [comment]
Issue occured again during nightly test, this time on RHEL8

**Comment by julsemaan** [comment]
@nqb has implemented a fix by delaying the update_systemd call with the restart packetfence-config call that occurs just before and told me all was fine since then.

We'll need to see if the configurator works correctly and we can then close this issue

**Comment by satkunas** [comment]
Another change was made in 53108b6fcf74d0d291ce1492c8ba35639438f100

**Comment by nqb** [comment]
I tried to remove workaround mentioned by @julsemaan after 53108b6 commit but I still got a 500 error.

**Comment by jrouzierinverse** [comment]
DO you have the logs?

**Comment by nqb** [comment]
I worked with @julsemaan on this issue. Except a 500 HTTP error code in `haproxy.log`, we don't see anything else.

It seems related to the restart of `packetfence-config` which is made just before doing `update_systemd` API call.
