### ISSUE TITLE
Packetfence does not check password vailidity when authenticating to switch/router

### ISSUE THREAD

**Issue by kalamchi75** [inverse-inc/packetfence#6444]
Hi Guys,

We have deployed PacketFence to be used as authentication server to our network devices (switches/routers, Cisco/Mikrotik). 
We are trying to achieve authentication permission based on Active Directory groups. 
So far, enabling Active Directory as authentication source, along with the conditions to check GroupMembers and assign privileges levels, seems to be working fine. 
E.g., USER1 has AD account, is a added to group ADMIN and on packetfence the condition is set to give this group full access. authenticating into a switch using USER1 account allows full privileges on the target switch. 
While USER2 has AD account, is added in MONITOR group, and on packetfence the condition is set to give this group Read Only access. When USER2 authenticates to target switch he is only allowed Read functions. 
If USER3 tries to authenticate (NOT in any AD group that's allowed in packetfence), he is gets rejected. 

This all is working as expected and required. 

The problem here is that, when authenticating, USER1 and USER2 can use any dummy password (or no password at all for that matter) and are still authenticated to the target switch. 

I would really appreciate some advise and hints on where and how to solve this issue. 

many thanks

**Comment by nqb** [comment]
Hello,

Try to apply maintenance patches (see https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_maintenance_patches ) and test again.

**Comment by kalamchi75** [comment]
> 
> 
> Hello,
> 
> Try to apply maintenance patches (see https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_maintenance_patches ) and test again.

Thanks, applying right now. 
Will test and update this thread. 

Best regards

**Comment by kalamchi75** [comment]
> 
> 
> Hello,
> 
> Try to apply maintenance patches (see https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_maintenance_patches ) and test again.

SPOT ON !!!!
The patch solved the issue and USER1 and USER2 are not authenticated unless the correct password is typed-in. 

Many thanks

**Comment by kalamchi75** [comment]
Hi again, 

another issue popped up after the patch. 
any/all authentication via packetfence to mikrotik routers do not work anymore. 
It worked before the patch, with the same password behavior described in the initial post of this thread. However, while the patch solved the password with Cisco devices, it stopped authentication completely to Mikrotik. 

Any tips please ?

Thanks
