### ISSUE TITLE
Add new members in switch group is not working out of the dropdown list

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6452]
**Describe the bug**
Add new member (a switch) in a Switch group that is not listed in the 25 switches of the dropdown list

**To Reproduce**
1. Go to 'configuration -> Policies and access control -> Switch groups'
2. Click on 'default'
3. Got to `members` tab
4. Scroll down to 'New Member'
5. Try to add an existing switch ip out of 25 switches from the list.
6. It is not possible to add the switch even if it exists

**Expected behavior**
Been able to add the switch out of the 25 listed in the dropdown

**Desktop (please complete the following information):**
 - Browser : chrome, firefox

**Comment by satkunas** [comment]
This looks like a cache-expiry issue in the UI store module. When I move a switch to a different group A -> B, cache for group A becomes stale and still shows having the old switch member. I've made changes in b3dff4690e90b1c4394969c517d5d8dc7cffdc55 to ignore the switch group member cache. @JeGoi please retest and see if this fixes your issue.

**Comment by JeGoi** [comment]
Ok it looks fine. I can see and choose any of the 220 switches from the other group.
Thanks
