### ISSUE TITLE
v11: service doesn't start at the end of the configurator.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6453]
**Describe the bug**
Go in the configurator then hit start packetfence, packetfence-config restart, updatesystemd occur but there is no start of the services.

**Comment by fdurand** [comment]
![image](https://user-images.githubusercontent.com/1553962/126805802-cb2db0d5-0ab8-4cb1-9656-f83e1d5cd21d.png)

**Comment by satkunas** [comment]
@jrouzierinverse will make `update_systemd` async

**Comment by satkunas** [comment]
Fixed in 53108b6fcf74d0d291ce1492c8ba35639438f100
