### ISSUE TITLE
packetfence-perl: install a metadata files to list version of each Perl modules

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6469]
**Is your feature request related to a problem? Please describe.**
When packetfence-perl package is installed, you have to browse `.pm` file to know at which version a module is installed.

**Describe the solution you'd like**
Add a metadata file which list all versions of Perl modules.

**Comment by fdurand** [comment]
I think it should be possible to use the rpm command to see what the packetfence-perl package provides.

**Comment by nqb** [comment]
On Debian, you have the name of Perl packages but not version number (using `apt-cache show packetfence-perl`)

`yum info packetfence_perl` doesn't provide this information ATM.

**Comment by nqb** [comment]
> I think it should be possible to use the rpm command to see what the packetfence-perl package provides.

Exactly, command is: ` rpm -qp --provides RPM_FILE.rpm`, you can get version for some Perl modules but not for all.

**Comment by nqb** [comment]
With #6869, I will dump module name and version in a CSV file which will be available in packetfence-perl on all distributions.
