### ISSUE TITLE
v11(Debian): OS network configuration is not saved if interface is down

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6477]
**Describe the bug**
If you configure an interface through PF (configurator or webadmin) which is **down** using following logic:
1. Assign IP address, netmask and type
2. Save
3. Set your interface up

On Debian, IP configuration is not saved into `/etc/network/interfaces`. Your interface is up, your PF configuration is correct but after a reboot, you lost IP assigned on interface.

**To Reproduce**
1. Put one interface down
2. Assign IP address on interface (through PF)
3. Save
4. Set your interface up
5. Reboot

=> IP address is missing on interface you configured and your interface will be down because there is no configuration for such interface in  `/etc/network/interfaces`

**Expected behavior**
Save IP configuration of interface in `/etc/network/interfaces` even if interface is down.

**Additional context**
If you did the opposite: 
1. Set interface up
2. Configure interface
3. Reboot

=> There is no issue.

**Comment by jrouzierinverse** [comment]
The interface needs to be up on Debian to get the IP address information.
Even if we save the IP address to ```/etc/network/interfaces``` the when booting.
The IP address information will not return since the interface is down.

**Comment by jrouzierinverse** [comment]
We should enable a device in order to edit it.

**Comment by nqb** [comment]
In that case, should we allow to edit an interface is this one is down ?

**Comment by nqb** [comment]
@jrouzierinverse did backend work. @satkunas will adjust frontend.
Changes will impact EL and Debian systems.

**Comment by nqb** [comment]
I'm reopening because I would like to be sure about fix added by @jrouzierinverse and @satkunas.

On latest devel build (Debian 11), if I try to edit an interface **down** at step 1 of the configurator, I can do it. I can also assign an IP address to this interface. After I save my settings, I see that this change is saved in `/etc/network/interfaces` even if my interface was down.

@jrouzierinverse and @satkunas, could you confirm that the expected behavior ? My understanding of the fix was different.

**Comment by nqb** [comment]
I think that is **not** the expected behavior.

After a reboot (I didn't continue the configurator), I noticed following thing:
- `/etc/network/interfaces` contains following content for my interface which was down:
```
iface eth4 inet static
    address 172.17.6.2
    netmask 255.255.255.0
```
=> `auto eth4` is missing which means that interface is not up after a reboot, you need to run `ifup eth4` to get correct IP configuration. For all other interfaces, we add `auto ethX` before `iface ethX inet static`
- configuration of interface has been written to `pf.conf` but configurator doesn't display it

**Comment by satkunas** [comment]
@nqb can you post the resposne the GET /config/interfaces call? The interface should include `not_editable: true` in order for the front-end to work from.

**Comment by nqb** [comment]
@satkunas, eth3 is one interface down and `not_editable` equals `true` but nothing prevents me to edit it:

```json
    {
      "additional_listening_daemons": [],
      "coa": null,
      "dhcpd_enabled": null,
      "dns": null,
      "high_availability": 0,
      "hwaddr": "52:54:00:de:86:49",
      "id": "eth3",
      "ifindex": "5",
      "ipv6_address": null,
      "ipv6_prefix": null,
      "is_running": false,
      "master": null,
      "name": "eth3",
      "nat_enabled": null,
      "network": null,
      "network_iseditable": false,
      "networks": [],
      "not_editable": true,
      "reg_network": null,
      "split_network": null,
      "tenant_id": 1,
      "type": "none",
      "vip": null,
      "vlan": null
    },
```

**Comment by satkunas** [comment]
On my RHEL build the interface should be marked w/ a yellow background, no buttons are shown on the right-most column

![Screen Shot 2021-08-19 at 9 43 53 AM](https://user-images.githubusercontent.com/3904468/130079488-35f6d17f-7c0e-4bec-806a-e443d7ba2773.jpg)

Clicking on it should avoid redirect and produce a notification

![Screen Shot 2021-08-19 at 9 43 40 AM](https://user-images.githubusercontent.com/3904468/130079462-0ee6fa3d-3525-40a6-9f04-674bb40838ee.jpg)


If this isn't the case then I'll need access to a debian build in order to troubleshoot the differences

**Comment by nqb** [comment]
I don't have this behavior on Debian 11

**Comment by satkunas** [comment]
Does it function properly in configuration (post-configurator) ?

**Comment by nqb** [comment]
Issue is not present in configuration (post-configurator), only during configurator.

**Comment by nqb** [comment]
It works as expected in the configurator.
