### ISSUE TITLE
Support both the string and integer value of EAP-Type and connection_sub_type.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#6485]
Some condition values has a integer and string respresentation.
So those conditions should be converted into from (field op 'value') to (field op 'str' || field op int).

**Comment by julsemaan** [comment]
IMO the backend should use the right type of underlying value (int or string) and the GUI should make this a select box that displays the human readable value and sets the necessary backend value

Expanding the conditions magically for some fields doesn't seem like the right thing to do for me
