### ISSUE TITLE
v11: creating a user without expiration is possible

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6487]
**Describe the bug**
Using GUI, you can create an account without expiration. It should not be possible.

On top of that, it creates an account in DB with `expiration` field sets to `$ZERO_DATE` which make account unusable after.

**To Reproduce**
1. Create an user account without expiration date
2. Try to use account later

=> Not possible.

**Expected behavior**
Frontend or backend should not permit to create an account like this.

**Comment by nqb** [comment]
@jrouzierinverse and @satkunas, not sure who should handle that bug.

**Comment by satkunas** [comment]
I assumed that when expiration is left empty that a zero-date would used for infinite expiration. @jrouzierinverse correct me if I'm wrong.

**Comment by jrouzierinverse** [comment]
If an expiration is not provided then a 31 days is given on the back end.
Do not send a zero date.

**Comment by nqb** [comment]
Frontend is sending "null" value when no expiration date is provided. @jrouzierinverse will look into the issue.
