### ISSUE TITLE
v11: OpenID attributes are not available in dropdown

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6492]
**Describe the bug**
When you create an OpenID source, OpenID attributes (configured in System Configuration -> Advanced) are not displayed.

**To Reproduce**
1. Declare OpenID attributes in System Configuration -> Advanced
2. Create a new OpenID source

=> There is nothing listed in "Username attribute" dropdown

**Expected behavior**
It should be possible to select OpenID attributes defined previously when configuring source.

**Additional context**
It looks like API correctly returned OpenID attributes (firstname, birthdate and sub):

```console
# /usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/source/yahouu | jq '.meta.authentication_rules.item.properties.conditions.item.properties.attribute.allowed[].value'
"SSID"
"current_time"
"current_time_period"
"connection_type"
"computer_name"
"mac"
"realm"
"switch_id"
"switch_group"
"username"
"stripped_user_name"
"username"
"firstname"
"birthdate"
"sub"
```

**Comment by satkunas** [comment]
Not able to reproduce. Custom defined attributes are shown:

![Screen Shot 2021-08-09 at 8 54 55 AM](https://user-images.githubusercontent.com/3904468/128709531-85ad59ee-37c4-442b-8d07-646d4f8092c1.jpg)

**Comment by nqb** [comment]
@satkunas, issue is not with "Conditions" but with "Username attribute" field.

**Comment by satkunas** [comment]
@jrouzierinverse can we get these allowed options added in meta for `username_attribute`?

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/sources?type=OpenID| jq '.meta.username_attribute'
{
  "default": "email",
  "placeholder": "email",
  "required": true,
  "type": "string"
}
```
