### ISSUE TITLE
v11: Wireless EAP TLS PacketFence PKI Windows provisioner not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6494]
After further investigation for Windows EAP TLS to work we need to change 

/usr/local/pf/html/captive-portal/templates/wireless-profile-tls.xml

From :
````
<ServerValidation>
<DisableUserPromptForServerValidation>true</DisableUserPromptForServerValidation>
<TrustedRootCA>XXXXX</TrustedRootCA>
</ServerValidation>
````

To:
````
<ServerValidation>
<DisableUserPromptForServerValidation>false</DisableUserPromptForServerValidation>
<TrustedRootCA>XXXXX</TrustedRootCA>
</ServerValidation>
````

**Comment by extrafu** [comment]
See https://github.com/inverse-inc/packetfence-windows-agent/blob/54112a26ff6faea40e59dc84ae0bbc89384a2dfb/templates.go for fixing the issue.

**Comment by julsemaan** [comment]
@lzammit, please try https://support.inverse.ca/~jsemaan/packetfence-windows-agent.exe and let us know if it works and I'll push this into devel
