### ISSUE TITLE
v11: gstatic.com passthroughs are ignored by pfdns

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6501]
**Describe the bug**
If you add `www.gstatic.com` or `*.gstatic.com` as a passthrough (globally or on a specific source), `pfdns` always returned captive portal IP address in place of real IP address.

Same behavior with `connectivitycheck.gstatic.com`.

**To Reproduce**
1. Add `*.gstatic.com` as a passthrough
2. Restart `pfdns` and `iptables`
3. As an unregistered device, query `pfdns`: `dig www.gstatic.com`

=> You got `66.70.255.147`

**Expected behavior**
`pfdns` should return real IP address because this domain has been added to passthroughs.

**Additional context**
- Issue seems to be specific to that domain because all other passthroughs work as expected (like `*.google.com`)
- I tried following things:
  * removed default passthrough on `connectivitycheck.gstatic.com`  added when `iptables` is started
  => same behavior
  * override `detection_mecanism_urls` without `gstatic` domain
  => same behavior

**Important**: if I set `detection_mecanism_bypass=enabled` in `pf.conf`, I got real IP address for `www.gstatic.com`.

=> I think there is an issue with `detection_mecanism_bypass`

**Comment by jrouzierinverse** [comment]
www.gstatic.com is preconfigured in detection_mecanism_urls as a detection url.

This may not be a bug.
Since DetectionMechanisms are checked first then passthroughs it is working as expected.
If this is a bug then it should be moved to v11.1 since I prefer not to change the current behavior this late in the game.

**Comment by nqb** [comment]
@jrouzierinverse, could you try to do what I already did:
- remove www.gstatic.com from `detection_mecanism_urls`
- restart services
- test again

=> On my side, it still returned captive portal URL but perhaps I did a bad test

**Comment by nqb** [comment]
@jrouzierinverse,

I tested again using steps provided in my last comment: resolution of `www.gstatic.com` is always `66.70.255.147`.

IMHO, it means that there is something wrong in this codepath. If we remove a domain from `detection_mecanism_urls` and this domain is added to passthrough, I don't see why we should not return real IP address of domain.

I tried on a 10.3 setup: same result.

**Comment by jrouzierinverse** [comment]
All URLs defined in captive_portal.detection_mecanism_urls in conf/pf.conf.defaults cannot be removed.
This seems to be issue where the frontend not matching the behavior of the backend.

**Comment by julsemaan** [comment]
@jrouzierinverse is right. The backend doesn't support removing entries from these type of lists (merged_list). The frontend makes this confusing by using a placeholder in those types of fields. The placeholder should be removed in the text field of merged_list

Reassigning to @satkunas

**Comment by satkunas** [comment]
@jrouzierinverse we'll need to implement a new property in meta as discussed in https://github.com/inverse-inc/packetfence/issues/6195

Reeassigning to @jrouzierinverse

**Comment by jrouzierinverse** [comment]
Fixed the meta Reeassigning to @satkunas
