### ISSUE TITLE
v11: cloning a sponsor source display a question mark in Associated sources field

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6503]
**Describe the bug**
If you clone a sponsor source which has a value in Associated Sources, frontend displays a question mark in that field (in place of source name).

If you want to change source in Associated Sources during copy, dropdown doesn't display anything.

If you save without changing anything, your new source has kept value from cloned source. 

**To Reproduce**
1. Create a sponsor source with Associated sources equals to `local`
2. Clone this source

=> You will see a question mark in Associated sources

3. Try to modify Associated sources

=> Nothing appears.

**Expected behavior**
It should be possible to modify Associated sources value when cloning source.

**Additional context**
During clone operation, I see an API call `OPTIONS` to `/api/v1/config/sources` which returned only type of all sources (not name of sources currently available).

**Comment by jrouzierinverse** [comment]
@satkunas is missing the url query parameter type=SponsorEmail from the options request
