### ISSUE TITLE
When reloading a resource that is in the database but not locally defined the reload fails

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#651]

**Comment by julsemaan** [comment]
Not sure I fully get this. Details ? Example ?

**Comment by jrouzierinverse** [comment]
If the database has a resource like interfaces::portal_ints (which was where I found this error)

However if pfconfig::namespaces::interfaces::portal_ints does not exists it would fail.

The configreload will fail.

The error was happening when switching between branches.

However I cannot replicate it anymore.

So I will close it
