### ISSUE TITLE
Switch type selection typeahead is case sensitive

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6511]
**Describe the bug**
When using the typeahead to select a switch type (ex: `AeroHIVE AP`), it doesn't ignore the case of the search like it used to before

**To Reproduce**
1. Create a new switch
2. Go in the `Type` field
3. Input `aero`
4. No types are displayed
 
**Expected behavior**
The 3 types containing `aero` should be displayed

**Additional context**
Searching for `Aero` returns the expected types

**Comment by satkunas** [comment]
Filtered searches are all now case-sensitive. Blame https://github.com/inverse-inc/packetfence/issues/5663

Will not fix.

**Comment by julsemaan** [comment]
Its not all searches that should be case sensitive...

They should be case sensitive or insensitive depending on the context

It makes no sense to have it done this way, we need this to be flexible

**Comment by nqb** [comment]
I agree with @julsemaan.
