### ISSUE TITLE
pfpki: operation=GetCACert always returns same CA certificate

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6512]
**Describe the bug**
When you have several CA configured in `pfpki` and you try to get a certificate from a CA using `sscep`, you can get certificate from another CA.

**To Reproduce**
1. Add portal daemon on your management interface
1. Create two CA (CA1 and CA2) with one profile for each of them in `pfpki`
2. Run following commands on PacketFence server:
 
```
sscep getca -u http://MGMT_IP/scep/PFPKI_PROFILE_NAME1 -c ./ca1.crt -i PFPKI_CA_NAME1  -v -d
sscep getca -u http://MGMT_IP/scep/PFPKI_PROFILE_NAME2 -c ./ca2.crt -i PFPKI_CA_NAME2  -v -d
```

=> ca1.crt and ca2.crt are identical

**Expected behavior**
=> ca1.crt and ca2.crt should be different

**Additional context**
- I noticed something in `packetfence.log`. When I request a cert using `sscep`, URL reported by PacketFence seems wrong:

sscep requests:
```
GET /scep/PFPKI_PROFILE_NAME?operation=GetCACaps
GET /scep/PFPKI_PROFILE_NAME?operation=GetCACert&message=PFPKI_CA_NAME
```

packetfence.log:
```
Aug 17 13:48:38 pfdeb11dev pfpki[935]: t=2021-08-17T13:48:38+0000 lvl=info msg="SCEP GET From GET To: /api/v1/scep/PFPKI_PROFILE_NAME?operation=GetCACapser?operation=GetCACaps" pid=935
Aug 17 13:48:38 pfdeb11dev pfpki[935]: t=2021-08-17T13:48:38+0000 lvl=info msg="SCEP GET From GET To: /api/v1/scep/PFPKI_PROFILE_NAME?operation=GetCACert&message=PFPKI_CA_NAMEGetCACert&message=PFPKI_CA_NAME" pid=935
```
=> Arguments are not correct

**Comment by julsemaan** [comment]
I ran the commands and it seems the problem may be the actual sscep command and not pfpki

I took a tcpdump and the sscep client is sending this: `GET /api/v1/scep/TTCA1?operation=GetCACert&message=CA1=GetCACert&message=CA1 HTTP/1.1`

So the malformed URL seems to be coming from there. 

Still digging deeper but will likely need feedback from @nqb

**Comment by julsemaan** [comment]
And what's weirder to add on top of my comment above is that the sscep command claims it sends this: `GET /scep/TTCA1?operation=GetCACert&message=CA1 HTTP/1.1`

**Comment by julsemaan** [comment]
Looks like the portal is called and then bridges to pfpki and its the portal piece that adds the invalid URI components but even with the right URL, its broken in pfpki :(

**Comment by nqb** [comment]
Works as expected on my side when I try to pull a PFPKI certificate using SCEP on a PacketFence server running on Debian 11.
