### ISSUE TITLE
Unable to edit an existing PKI certificate template

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6514]
**Describe the bug**
If you create and then edit a certificate template, it fails in pfpki because 2 different ID fields are included

**To Reproduce**
1. Create a certificate template in Configuration->Integration->PKI Templates
2. Edit this template and save it without changing anything
3. You get error: json: cannot unmarshal string into Go struct field Profile.ID of type uint

**Expected behavior**
Should be able to save

**Additional context**
When inspecting the request payload, 2 different id fields are sent:
```
{"id":"5","isClone":false,"isNew":false,"ca_id":"3","ID":5,"CreatedAt":"0001-01-01T00:00:00Z","UpdatedAt":"0001-01-01T00:00:00Z","DeletedAt":null,"Ctx":null,"name":"TCA2","ca_name":"CA2","validity":"365","key_type":"1","key_size":"2048","digest":"4","key_usage":"","extended_key_usage":""}
```

One is `id`, the other one is `ID`. The `ID` field contains the right value (integer) but the `id` field is a string. The right field to use is `ID` with the integer value

**Comment by julsemaan** [comment]
This seems to apply to other sections of the PKI but templates were used as an example

**Comment by julsemaan** [comment]
@satkunas, did you validate the other sections of the PKI in the admin?

The commit only fixes the profiles

**Comment by satkunas** [comment]
@julsemaan I checked the api calls from the other 3 sections and no other section uses PUT/PATCH with a payload. So no other changes were made.
