### ISSUE TITLE
haproxy-portal doesn't rewrite scep queries correctly

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6515]
**Describe the bug**
Based on #6512 where @nqb discovered the query pfpki receives isn't valid 

**To Reproduce**
1. Do: curl `http://192.168.3.35/scep/TTCA2?operation=GetCACert&message=CA2`
2. The path that pfpki gets is: `GET /api/v1/scep/TTCA2?operation=GetCACert&message=CA2=GetCACert&message=CA2 HTTP/1.1`

The only culprit can be haproxy-portal from what I can tell as it doesn't go through any other service before getting to pfpki

Calling pfpki directly doesn't create that behavior

I checked the haproxy-portal configuration and everything looks good according to haproxy's documentation so we may be dealing with a bug in haproxy or with us misusing haproxy

Not sure what it can break for SCEP but it certainly won't help

**Comment by julsemaan** [comment]
This is on RHEL8 using `haproxy-2.2.14-1.1.x86_64`

**Comment by julsemaan** [comment]
This is also breaking URLs for the static assets: `GET /common/pf.js?.1:8889/common/pf.js? HTTP/1.1`

**Comment by nqb** [comment]
On Debian, we used `haproxy 2.2.15`

**Comment by nqb** [comment]
Identical results on Debian 11:

```
# tcpdump -nlp -i any port 8889 -w- | strings | grep GET
GET /common/pf.js?.1:8889/common/pf.js? HTTP/1.1
```

**Comment by julsemaan** [comment]
Same with the latest patch release of haproxy (2.2.16), will try the latest and greatest
