### ISSUE TITLE
Should review namespace of packages inside pf::Authentication::constants

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#652]
Actions -> pf::Authentication::constants::Actions
Conditions -> pf::Authentication::constants::Conditions ...

**Comment by jrouzierinverse** [comment]
+1

**Comment by julsemaan** [comment]
@jrouzierinverse 

Do you want to address this ? Or should this be closed ?

**Comment by jrouzierinverse** [comment]
Close
