### ISSUE TITLE
Editing the admin user provides an error about the registration window end being of the wrong format

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6528]
**Describe the bug**
With a freshly configured machine, editing the admin user says the end of the registration window has an invalid format

**To Reproduce**
1. Use a fresh machine (or freshly imported DB schema)
2. Edit the admin user
3. See the error:
![image](https://user-images.githubusercontent.com/3857942/130119079-6a311917-05c5-4072-afb1-46d46a60dc73.png)

**Comment by julsemaan** [comment]
what is weird too is that the begin datetime of the registration is fine with an hour but not the end

**Comment by satkunas** [comment]
@julsemaan The backend should be stripping off the time portion. Please see https://github.com/inverse-inc/packetfence/issues/5611

Please loop-in myself and @jrouzierinverse if this needs more discussion

**Comment by jrouzierinverse** [comment]
The expiration for the user has date and time.
The unregdate for actions (like in sources) is just a date

**Comment by julsemaan** [comment]
> The expiration for the user has date and time.
> The unregdate for actions (like in sources) is just a date

That is exactly it. The registration window of a user **must** be a datetime, as well as the unregdate of a node.
We cannot strip the time off these fields as users may have access for hours and not necessarily full days until midnight
