### ISSUE TITLE
Unable to get syslog CEF to work on RHEL8 + MariaDB 10.5.12

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6533]
**Describe the bug**
Tried to get syslog CEF to work on the latest devel and I'm unable to get it working

**To Reproduce**
1. Configure an event logger:
```
[adminauditlog]
facility=kernel
description=adminauditlog
namespaces=admin_api_audit_log
type=syslog
priority=notice
host=2.3.4.5
port=514
```
2. Restart packetfence-mariadb
3. Start a tcpdump: `tcpdump -nlp -i any host 2.3.4.5`
4. Do something in the admin to generate an admin API audit log entry. Entry appears in the table but no syslog message is sent

**Additional context**

The trigger seems to be there:
```
log_event_admin_api_audit_log                         | INSERT | admin_api_audit_log | BEGIN SET @k = pf_logger( "admin_api_audit_log", "tenant_id", NEW.tenant_id, "created_at", NEW.created_at, "user_name", NEW.user_name, "action", NEW.action, "object_id", NEW.object_id, "url", NEW.url, "method", NEW.method, "request", NEW.request, "status", NEW.status); END
```

But the pf_logger function doesn't seem to appear:
```
MariaDB [pf]> show function status;
+----+-------------------+----------+----------------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| Db | Name              | Type     | Definer        | Modified            | Created             | Security_type | Comment | character_set_client | collation_connection | Database Collation |
+----+-------------------+----------+----------------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| pf | FREERADIUS_DECODE | FUNCTION | root@localhost | 2021-08-17 07:53:15 | 2021-08-17 07:53:15 | DEFINER       |         | latin1               | latin1_swedish_ci    | latin1_swedish_ci  |
| pf | ROUND_TO_HOUR     | FUNCTION | root@localhost | 2021-08-17 07:53:15 | 2021-08-17 07:53:15 | DEFINER       |         | latin1               | latin1_swedish_ci    | latin1_swedish_ci  |
| pf | ROUND_TO_MONTH    | FUNCTION | root@localhost | 2021-08-17 07:53:15 | 2021-08-17 07:53:15 | DEFINER       |         | latin1               | latin1_swedish_ci    | latin1_swedish_ci  |
+----+-------------------+----------+----------------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
3 rows in set (0.001 sec)
```

But the pf_logger function seems to be there because it cannot be created:
```
MariaDB [pf]> CREATE FUNCTION pf_logger RETURNS INTEGER SONAME "pf_udf.so";
ERROR 1125 (HY000): Function 'pf_logger' already exists
```

**Comment by julsemaan** [comment]
I know that #6031 was tested against CentOS7 and its associated MariaDB version so perhaps this is a regression due to RHEL8 and/or the newer MariaDB version

**Comment by nqb** [comment]
@julsemaan, could you run `select * from func;`

**Comment by julsemaan** [comment]
```
MariaDB [pf]> select * from func;
ERROR 1146 (42S02): Table 'pf.func' doesn't exist
```

**Comment by julsemaan** [comment]
```
MariaDB [pf]> select * from mysql.func;
+-----------+-----+-----------+----------+
| name      | ret | dl        | type     |
+-----------+-----+-----------+----------+
| pf_logger |   2 | pf_udf.so | function |
+-----------+-----+-----------+----------+
1 row in set (0.001 sec)
```

**Comment by jrouzierinverse** [comment]
Can you send me the output of ```cat /usr/local/pf/var/conf/mariadb_pf_udf```

**Comment by julsemaan** [comment]
> Can you send me the output of `cat /usr/local/pf/var/conf/mariadb_pf_udf`

Looks empty:
```
[root@rhel8-packetfence pf]# cat /usr/local/pf/var/conf/mariadb_pf_udf
[root@rhel8-packetfence pf]# ll /usr/local/pf/var/conf/mariadb_pf_udf
-rw-r--r--. 1 root root 0 Aug 18 11:26 /usr/local/pf/var/conf/mariadb_pf_udf
```

**Comment by jrouzierinverse** [comment]
Send the config file ```/usr/local/pf/conf/event_loggers.conf``` please.

**Comment by julsemaan** [comment]
> Send the config file `/usr/local/pf/conf/event_loggers.conf` please.

Its the exact content that is in the bug description above

**Comment by jrouzierinverse** [comment]
Can you do a configreload and restart packetfence-mariadb

**Comment by julsemaan** [comment]
> Can you do a configreload and restart packetfence-mariadb

That was done before opening the issue too, did it again and no difference

But I restarted packetfence-config and packetfence-mariadb and it started working

My guess is that there must be a missing child dependency in your pfconfig namespaces because all the other pfconfig stuff works on this machine other than the event loggers

**Comment by julsemaan** [comment]
To add on top of my comment above, if I modify the existing entry in the admin and save it and restart packetfence-mariadb, the file `/usr/local/pf/var/conf/mariadb_pf_udf` becomes empty again until I restart packetfence-config and packetfence-mariadb

**Comment by jrouzierinverse** [comment]
Is this in a standalone or cluster environment?

**Comment by julsemaan** [comment]
> Is this in a standalone or cluster environment?

standalone

**Comment by julsemaan** [comment]
Also, if you restart packetfence-mariadb twice, it does work so its not related to the restart of packetfence-config

**Comment by julsemaan** [comment]
Looks like its actually a race condition issue. After saving the resource, pfconfig's in memory cache (L1) is flushed

When restarting mariadb, generatemariadb calls pfconfig to obtain the keys of config::EventLoggers

pfconfig doesn't have it in memory so it calls the DB (its L2 cache) to obtain the value

In that case, it has to read it from the file directly but I guess that for a reason I have yet to find, it doesn't build it correctly or has trouble fetching the next key in the hash

I'll reassign this to myself, I may just end up bypassing the pfconfig daemon for that in generatemariadb since pfconfig relies on MariaDB itself

**Comment by julsemaan** [comment]
For the record, the reason why it was always working with the 2nd restart of packetfence-mariadb or the restart of packetfence-config is that the resource would have been loaded in L1 in both cases during that moment so it would work when restarting packetfence-config afterwards

I ended up bypassing the pfconfig daemon and calling the pfconfig module directly in order to remove the daemon dependency during the restart of such a core service

**Comment by jrouzierinverse** [comment]
That sound like a bug in pfconfig.
