### ISSUE TITLE
Switch without Switch Group?

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6534]
**Describe the bug**
When you create a switch you need to choose a switch group
After that point, you can remove that switch group but the switch looks still linked to this group.
In the config the "group=" is not here.

**To Reproduce**
1. Create the switch
2. Renove the group
3. Show in switch group or in the tab switch, the switch is still linked to the group

**Expected behavior**
Goup empty or Remove the option to have a switch without group

**Comment by JeGoi** [comment]
It looks that "no group" = "default"

**Comment by satkunas** [comment]
AFAIK we've never enforced a group for a switch. Should a validator be added to prevent the group from being cleared/empty?

**Comment by julsemaan** [comment]
No we shouldn't, an empty group uses the default section

If we want to enforce this we need to also add a default group value in the switches.conf.defaults, not just adjust the frontend

Lets leave this aside for now IMO so that we don't introduce a regression

**Comment by jrouzierinverse** [comment]
I am not seeing that exact behavior.

After clearing the group I see the group is gone in the config (which is what is expected).

I don't see how this is a bug.

**Comment by JeGoi** [comment]
Yes, you are right. It is removed from the config file but in the GUI and as mentioned by @julsemaan, the switch is using the default section. So, at the end, the switch is still in a group (default) and a member of it. It is not without a group.

**Comment by satkunas** [comment]
@JeGoi can we close this issue?
