### ISSUE TITLE
PacketFence instantiates the profile more than once.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#654]
If the attributes of the request change during authorization this causes a different portal to be instantiated on the second instantiation and thus different sources to apply.

**Comment by julsemaan** [comment]
Still relevant ?

**Comment by jrouzierinverse** [comment]
Yes

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by jrouzierinverse** [comment]
This could be included request-cache

**Comment by julsemaan** [comment]
@jrouzierinverse 

Is this still relevant ?

**Comment by jrouzierinverse** [comment]
It is an edge case that we should not worry about.
