### ISSUE TITLE
Deprecate unused authentication sources

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6546]
**Is your feature request related to a problem? Please describe.**
After discussion in our internal meeting, we should deprecate sources that aren't being used actively.

Current list of sources:

- Authorize.NET
- Mirapay
- Pinterest
- Twitter
- Instagram

**Describe the solution you'd like**

For each of the sources, we must:

- Remove the associated test in testlink
- Remove the backend auth source code
- Remove the formhandler forms
- Remove the code in the admin interface (vue)
- Create an upgrade script to remove any sources matching these types
- Add an upgrade note in our guide that states we did deprecate these

**Comment by julsemaan** [comment]
I'm open to adding/removing sources from that list if one of your customer uses it actively and we know the integration still works

**Comment by extrafu** [comment]
@JeGoi review the associated automated tests + TestLink and @satkunas review GUI changes.

**Comment by JeGoi** [comment]
Associated tests on TestLink have been removed. ( Nothing on automated tests, like mentioned by @nqb )
