### ISSUE TITLE
Security event description becomes mandatory after enabling 300007

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6547]
**Describe the bug**
Security event description becomes mandatory after enabling 300007

**To Reproduce**
1. Clear out any security events configuration you have to go back to defaults (`: > conf/security_events.conf`)
2. Configreload hard
3. Go in the security events in the admin
4. Search for 300007
5. Enable the security event via the list view
6. Edit the security event 300007
7. Description appears as required although it is already there

**Expected behavior**
The description shouldn't be required when its already there

**Comment by julsemaan** [comment]
It looks like I'm unable to replicate this consistently though so I'm hoping @satkunas can replicate it on his setup

**Comment by julsemaan** [comment]
Here is a screenshot of how it was when it was broken: 
![image](https://user-images.githubusercontent.com/3857942/130791563-b8e3991d-e689-4299-9277-96ce0ea37916.png)

And what was in security_events.conf:
```
[3000007]
enabled=Y
recipient_template_email=security_event-triggered
```

**Comment by satkunas** [comment]
The validator has been removed on the frontend, however the backend rejects PATCH and  returns an error. It will need to be adjusted as well.

```
{"errors":[{"field":"desc","message":"Please specify a brief description of the security event."}],"message":"Unable to validate","status":422}
```

**Comment by julsemaan** [comment]
I think the issue might be larger on the backend as well. We don't see it in the screenshot I sent but the triggers and actions were empty while they are defined via the defaults overlay (there are actions and a trigger in security_events.conf) so perhaps the defaults overlay is not merging security_events.conf.defaults with security_events.conf and it then becomes placeholders instead of the value. I hope this makes sense to @jrouzierinverse

**Comment by jrouzierinverse** [comment]
I am not seeing that behavior however I did make a change in the commit 93238eef133651b45e19647562d42ae8228f4548.
Can you recheck to see if you are still seeing the issue.

**Comment by julsemaan** [comment]
It wasn't always happening and I couldn't pinpoint exactly how to replicate it every time. I only have a screenshot to prove I wasn't crazy and that it did happen. But no specific insights on how to precisely replicate it every time

**Comment by extrafu** [comment]
Lower the priority if it's random and IMO, it's not a high issue.

**Comment by julsemaan** [comment]
So I managed to be able to replicate it by reseting my security_events.conf, restarting PF, refreshing the admin and toggling 3000007

It looks like the frontend sends a PATCH request to enable/disable the security event, then when I click on it to view it, it only calls the OPTIONS with the following response: https://pastebin.com/uPWTT39z

At that moment, it displays the values with placeholders and is missing the triggers and actions

Next, if I refresh the page without changing anything in the backend, it does an OPTIONS call again with the following response: https://pastebin.com/edp9GX9Z

I performed a diff between the 2 payloads and there are no differences (other than some ordering in the hashes) so it looks like the frontend is causing the issue as far as I can tell

**Comment by julsemaan** [comment]
@satkunas, please look into what I described above, looks like a frontend issue IMO

**Comment by julsemaan** [comment]
> Lower the priority if it's random and IMO, it's not a high issue.

It isn't random, it happens consistently, just had to find a way to replicate. Also, you have the potential to break every security event with that since it will destroy your actions and triggers configuration if you save it

**Comment by satkunas** [comment]
Fix pushed in https://github.com/inverse-inc/packetfence/commit/43326432ad1077e68248f69633e3595771b082e5 (mislabeled).

**Comment by julsemaan** [comment]
Works as expected now
