### ISSUE TITLE
API Node search tenant_id null error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#6549]
**To Reproduce**
`/usr/local/pf/sbin/pfperl-api get -M POST -c '{"fields":["status","online","mac","computername","pid","ip4log.ip","device_class","category_id"],"query":{"op":"and","values":[{"values":[{"field":"tenant_id","op":"equals","value":1}]}]},"sort":["mac"],"limit":25,"cursor":0}' '/api/v1/nodes/search'`

`{"errors":[],"message":"(null) is not valid","status":422}`

**Comment by jrouzierinverse** [comment]
Your query input is invalid you have values wrapped in values
```json
{
  "fields": [
    "status",
    "online",
    "mac",
    "computername",
    "pid",
    "ip4log.ip",
    "device_class",
    "category_id"
  ],
  "query": {
    "op": "and",
    "values": [
      {
        "values": [
          {
            "field": "tenant_id",
            "op": "equals",
            "value": 1
          }
        ]
      }
    ]
  },
  "sort": [
    "mac"
  ],
  "limit": 25,
  "cursor": 0
}
```
