### ISSUE TITLE
Authentication Failures is falling

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6556]
**Describe the bug**
The page authentication failures is not working on PF v10.3.0

**To Reproduce**
1. Go to 'Reports -> Standard Reports -> Authentication -> Failures'

**Screenshots**
Show screenshot

![Screen Shot 2021-08-30 at 9 59 32 AM_cleaned](https://user-images.githubusercontent.com/13801368/131352798-78fbba87-ad6b-4884-a4c0-dd8418bd6198.jpg)

**Comment by jrouzierinverse** [comment]
The issue seems to be the API endpoint ```/api/v1/topauthenticationfailures/mac/:start/:end```  expects a start/end date and none is provided.
