### ISSUE TITLE
v11: PF ZEN admin account does not work

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6561]
It looks like it has been a fixed issue:

But it has been re-introduced or it's a regression of https://github.com/inverse-inc/packetfence/issues/6329 

![image](https://user-images.githubusercontent.com/5261214/131910881-be5b3566-ce23-47b7-8659-9ca72c791974.jpeg)

Set up:

- Fresh Debian PF ZEN installation:
````
root@packetfence:~# dpkg -l packetfence
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                                                Architecture Description
+++-==============-======================================================-============-=========================================================
ii  packetfence    11.0.0+20210902113958+364010000+0011+v11.0.0+bullseye1 all          PacketFence network registration / worm mitigation system
````

Timezone: Toronto

It looks like the admin user valid from is setup again.

Step during the screen capture in the DB:

![image](https://user-images.githubusercontent.com/5261214/131911149-844c1714-6cd0-45c0-849a-69d80b773515.jpeg)

**Comment by julsemaan** [comment]
Looks like the fix for #6329 was put in the 10.3 schema but not in X.Y so it wasn't release in 11.0 but is in maintenance/11.0

I'll add it to the X.Y schema and to maintenance/11.0 for the 11.0 schema

**Comment by nqb** [comment]
ZEN rebuild in progress.

**Comment by nqb** [comment]
Work as expected using latest ZEN build.
