### ISSUE TITLE
web admin: unable to select Tenant ID in dropdown for administration rules

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6568]
**Describe the bug**
If you want to assign a specific Tenant ID using an administration rules, `Tenant ID` choice is not available anymore in dropdown.

**To Reproduce**
1. Create an Active Directory source with one administration rule
2. Try to add `Tenant ID` as an action

=> Not possible.

**Expected behavior**
`Tenant ID` should be available in dropdown list for administration rules.

**Additional context**
`Tenant ID` is available as an action for Users.

**Comment by nqb** [comment]
See https://github.com/inverse-inc/packetfence/issues/5976

**Comment by nqb** [comment]
I can be wrong but I think the commit 3a52da9 is the culprit (mentioned in #5976).

I think we should disable "Tenant ID" action on users, not on sources.

**Comment by satkunas** [comment]
@jrouzierinverse will need to alter the `/api/v1/current_user/allowed_user_actions` endpoint and omit the `{"action":"set_tenant_id"}` in order to remove this action from the Users.

**Comment by satkunas** [comment]
UI changes backported to `maintenance/11.0`

**Comment by julsemaan** [comment]
@nqb, can we call this fixed ?

**Comment by nqb** [comment]
Yes, I think the remaining part need to be adressed on #5976
