### ISSUE TITLE
WMI: missing upgrade script to remove scan engines from connection profile

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6569]
**Describe the bug**
#6344 removed WMI feature but doesn't provide an upgrade script to remove references to WMI scan engines. Consequently, it causes issues after upgrade to 11.0.0.

**To Reproduce**
1. Configure a 10.3 setup with a WMI scan engine and a connection profile mapped to this WMI scan engine
2. Export/Import your configuration to 11.0.0
3. Restart services

=> You got error like: 
```
Sep  6 15:38:42 srvpf packetfence_httpd.aaa[2706]: httpd.aaa(2010) ERROR: [mac:00:04:11:22:37:9a] radius authorize failed with error: type is not defined for wmi_scan at /usr/local/pf/lib/pf/factory/scan.pm line 51.
 (pf::api::radius_authorize)
```

**Expected behavior**
Old WMI configurations should be removed by upgrade script.

**Additional context**
I remembered that WMI involve a lot of components, we need to be sure we remove everything using upgrade script.

**Comment by jrouzierinverse** [comment]
For maintenance I will ignore all WMI scan engines.
I will create a script for 11.1

**Comment by nqb** [comment]
Upgrade note added in #6567
