### ISSUE TITLE
Google Workspace LDAP authentication not working on PF 11.0

### ISSUE THREAD

**Issue by nathanbloemendaal78** [inverse-inc/packetfence#6570]
1. Configure the Google Workspace LDAP source as described, including certificates
2. Configure basics like switches, roles, realms, enough to be able to test auth with a client device
3. Perform authentication using EAP-TTLS /w PAP (I tested a random Chromebook and Android phone)
4. Audit log shows error: 

_Reason Config item "realm[null].oauth2.discovery" does not exist_

radius debug shows:

(7) Tue Sep  7 20:55:01 2021: Debug: server packetfence-tunnel {
(7) Tue Sep  7 20:55:01 2021: Debug:   # Executing section authorize from file /usr/local/pf/raddb/sites-enabled/packetfence-tunnel
(7) Tue Sep  7 20:55:01 2021: Debug:     authorize {
*
*
*
(7) Tue Sep  7 20:55:01 2021: Debug: suffix: Authentication realm is LOCAL
(7) Tue Sep  7 20:55:01 2021: Debug:       [suffix] = ok
(7) Tue Sep  7 20:55:01 2021: Debug: ntdomain: Request already has destination realm set.  Ignoring
(7) Tue Sep  7 20:55:01 2021: Debug:       [ntdomain] = noop
(7) Tue Sep  7 20:55:01 2021: Debug:       update control {
(7) Tue Sep  7 20:55:01 2021: Debug:       } # update control = noop
(7) Tue Sep  7 20:55:01 2021: Debug: eap: No EAP-Message, not doing EAP
(7) Tue Sep  7 20:55:01 2021: Debug:       [eap] = noop
(7) Tue Sep  7 20:55:01 2021: Debug:       policy oauth2.authorize {
(7) Tue Sep  7 20:55:01 2021: Debug:         if (&Realm && &User-Password && "%{config:realm[%{Realm}].oauth2.discovery}") {
(7) Tue Sep  7 20:55:01 2021: Debug:         EXPAND realm[****.nl].oauth2.discovery
(7) Tue Sep  7 20:55:01 2021: Debug:            --> realm[****.nl].oauth2.discovery
(7) Tue Sep  7 20:55:01 2021: ERROR:         Config item "****.nl].oauth2.discovery" does not exist
(7) Tue Sep  7 20:55:01 2021: Debug:         EXPAND %{config:realm[%{Realm}].oauth2.discovery}
(7) Tue Sep  7 20:55:01 2021: Debug:            --> 
(7) Tue Sep  7 20:55:01 2021: Debug:         if (&Realm && &User-Password && "%{config:realm[%{Realm}].oauth2.discovery}")  -> FALSE
(7) Tue Sep  7 20:55:01 2021: Debug:         else {
(7) Tue Sep  7 20:55:01 2021: Debug:           [noop] = noop
(7) Tue Sep  7 20:55:01 2021: Debug:         } # else = noop
(7) Tue Sep  7 20:55:01 2021: Debug:       } # policy oauth2.authorize = noop

However, I configured nothing related to oauth2.

**Expected behavior**
Perform authentication without reference to oauth2, as it is not being used.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Version 91

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Edge 7
 - OS: Android 10

**Additional context**

**Comment by nqb** [comment]
Hello,

Could you provide your `realm.conf` and also section related to Google Workspace LDAP in `authentication.conf` ?
Be sure to remove secrets.

**Comment by nathanbloemendaal78** [comment]
Hello Nicolas,

I have attached the requested files.

Met vriendelijke groet,

Nathan Bloemendaal

Brite Wireless
Rigtersbleek Zandvoort 10 / kantoor 1.29
7521 BE Enschede
T: 053 – 20 30 404 
E:  ***@***.******@***.***>
W: brite.nl<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.brite.nl%2F&data=04%7C01%7C%7C4d06fe19a5cc4b70651608d8b3d1cc84%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637457060951567955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CMsATUnMG%2FV6Utb3QclhKQcKNY1ue1vJ%2Bs3%2FqkvVO6c%3D&reserved=0>
[Afbeelding met tekening, stoppen, teken, rood  Automatisch gegenereerde beschrijving]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.brite.nl%2F&data=04%7C01%7C%7C4d06fe19a5cc4b70651608d8b3d1cc84%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637457060951577910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ve5KlLX2sDCks3LFUSnDdIgEXYiTMWPs5ylHCMgZxpQ%3D&reserved=0>

[Afbeelding met tekening, licht  Automatisch gegenereerde beschrijving]

Van: Nicolas Quiniou-Briand ***@***.***>
Verzonden: Wednesday, 8 September 2021 07:31
Aan: inverse-inc/packetfence ***@***.***>
CC: Nathan Bloemendaal ***@***.***>; Author ***@***.***>
Onderwerp: Re: [inverse-inc/packetfence] Google Workspace LDAP authentication not working on PF 11.0 (#6570)


Hello,

Could you provide your realm.conf and also section related to Google Workspace LDAP in authentication.conf ?
Be sure to remove secrets.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finverse-inc%2Fpacketfence%2Fissues%2F6570%23issuecomment-914929867&data=04%7C01%7C%7C0aa15db467ce4a490a1108d97289e5a3%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637666758876304925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bbBPbzo62Ia2GkdY2LpO%2FqMWI9ltqOXwhJps%2B73qtmM%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO267PTADQIJFNCNXLPM5XTUA3YKVANCNFSM5DTAMYNA&data=04%7C01%7C%7C0aa15db467ce4a490a1108d97289e5a3%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637666758876314879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AcgmDq5mrcsE6C1Uqg59c7vdGP4hk8PCRGarFSrDEaA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0aa15db467ce4a490a1108d97289e5a3%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637666758876314879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P%2BSeB5yDqAph6dUul2tVwoZQOELFbjULDBhwCXXV04c%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0aa15db467ce4a490a1108d97289e5a3%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637666758876324836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nfTDSuBoG1%2F7aooimiXsiq%2BPXfgs95piYJqLFb88Efw%3D&reserved=0>.

**Comment by nqb** [comment]
@nathanbloemendaal78, I didn't see the files attached.

**Comment by nathanbloemendaal78** [comment]
Hello Nicolas,

OK, let’s try again. Do you see them now?

Met vriendelijke groet,

Nathan Bloemendaal

Brite Wireless
Rigtersbleek Zandvoort 10 / kantoor 1.29
7521 BE Enschede
T: 053 – 20 30 404 
E:  ***@***.******@***.***>
W: brite.nl<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.brite.nl%2F&data=04%7C01%7C%7C4d06fe19a5cc4b70651608d8b3d1cc84%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637457060951567955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CMsATUnMG%2FV6Utb3QclhKQcKNY1ue1vJ%2Bs3%2FqkvVO6c%3D&reserved=0>
[Afbeelding met tekening, stoppen, teken, rood  Automatisch gegenereerde beschrijving]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.brite.nl%2F&data=04%7C01%7C%7C4d06fe19a5cc4b70651608d8b3d1cc84%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637457060951577910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ve5KlLX2sDCks3LFUSnDdIgEXYiTMWPs5ylHCMgZxpQ%3D&reserved=0>

[Afbeelding met tekening, licht  Automatisch gegenereerde beschrijving]

Van: Nicolas Quiniou-Briand ***@***.***>
Verzonden: Wednesday, 8 September 2021 15:28
Aan: inverse-inc/packetfence ***@***.***>
CC: Nathan Bloemendaal ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [inverse-inc/packetfence] Google Workspace LDAP authentication not working on PF 11.0 (#6570)


@nathanbloemendaal78<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnathanbloemendaal78&data=04%7C01%7C%7Cdc5ba0fbf8a14ac3acd208d972cc6c45%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637667044594063057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SPIVdBUAmjfIqIedVzuSOf4mfsd0FDJfoVnhU0KHy1s%3D&reserved=0>, I didn't see the files attached.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finverse-inc%2Fpacketfence%2Fissues%2F6570%23issuecomment-915238721&data=04%7C01%7C%7Cdc5ba0fbf8a14ac3acd208d972cc6c45%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637667044594073018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9hi7LEN0xc9nS5EbZa2CM%2FGc8tBdPbOQ3kxmwn170Oo%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO267PVFXCHSPQKUQSW5YDDUA5QENANCNFSM5DTAMYNA&data=04%7C01%7C%7Cdc5ba0fbf8a14ac3acd208d972cc6c45%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637667044594073018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U9sJuGqoi9I83mvvQP5IyTf9TrfCnUQiH6nFVr2sZMA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdc5ba0fbf8a14ac3acd208d972cc6c45%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637667044594073018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2A0aCiMnqT5UhkZRJ2aOlowG8ezpFt%2BhPXxZFGejV%2F8%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdc5ba0fbf8a14ac3acd208d972cc6c45%7C7684718d90df4072ac9adeda59b640b7%7C1%7C0%7C637667044594082961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KhpTUV1MdfVuDxXibk5mHzk8%2BJChGPR89AAh2VPFF%2BI%3D&reserved=0>.

**Comment by nqb** [comment]
No @nathanbloemendaal78 , I don't think GitHub takes attachment when you reply by email.
You need to add config files directly in your comment.

**Comment by nathanbloemendaal78** [comment]
Good morning Nicolas,

OK, I attached the files here.

Kind regards,

Nathan

[#6570.zip](https://github.com/inverse-inc/packetfence/files/7133959/6570.zip)

**Comment by julsemaan** [comment]
It looks like the sle-google-ldap is not configured in the realm hetstedelijklyceum.nl realm for LDAP TTLS but I just saw that the Google Workspace LDAP source cannot be used there.

Due to that missing config, it tries to find an oauth2 configuration for that realm in TTLS PAP (Azure AD) and doesn't find one (which is normal) and just stops there because no source can be used to authenticate the credentials

There are likely adjustments that are required to get the LDAP TTLS working against it in our FreeRADIUS configuration as well since it needs to setup cert based authentication against the LDAP server

**Comment by nathanbloemendaal78** [comment]
Indeed, that is exactly what I found out. I was quite looking forward to using this feature. Thanks for the update.

**Comment by julsemaan** [comment]
Fixes have been implemented, updating PacketFence using either `apt install packetfence` or `yum update packetfence --enablerepo=packetfence` should do it

Note that the maintenance package will be released tonight (unless there is any error) so hold off until tomorrow to try it

**Comment by nathanbloemendaal78** [comment]
I did some quick testing, but I still cannot select the Google LDAP Workspace source in the mentioned realm for TTLS PAP. I tried recreating both the realm and the auth source, but noting appears in the drop down list. To rule out some odd browser behaviour, I tried 2 other browsers, all the same result.
The version I'm running now: 11.0.0+20210909142142+368363258+0011+maintenance~11.0+bullseye1

**Comment by nqb** [comment]
There was issue in tests which prevent maintenance packages to be uploaded.
I will update issue when maintenance packages are available.

**Comment by nqb** [comment]
Packages available, you should get: `packetfence_11.0.0+20210911054717+369511790+0011+maintenance~11.0+bullseye1`

**Comment by nathanbloemendaal78** [comment]
I can confirm that the patch indeed fixes the issue. Had to adjust some other settings as well (stripping for example), but this looks very promising.
