### ISSUE TITLE
configurator: step 2 failed when clicking on next step

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6575]
**Describe the bug**
On v11.0.0 (Debian 11), you can't pass step 2 of configurator. With all defaults and just admin password set, you got:

`Unknown error, check server side logs for details.: An error occured while setting the administrator password.`

Tested on ZEN with latest packages available.

**To Reproduce**
1. Start a ZEN
2. Get latest packages
3. Go through configurator step 2
4. Set admin password
5. Click on next step

=> You got an error caused by API call (GET) to `https://IP_ADDR:1443/api/v1/configurator/user/admin`

**Expected behavior**
Going to step 3.

**Additional context**
- `perl -I/usr/local/pf/lib_perl/lib/perl5 -I/usr/local/pf/lib -Mpf::db -e 'print $pf::db::DB_Config->{pass}` returned default password: `packet`
- Integration tests on `maintenance/11.0` doesn't fail at this step. It seems there is something different between frontend and Venom.
- Error I see in `packetfence.log`:
`Sep 14 05:38:46 packetfence packetfence[1175]: pfperl-api(1175) ERROR: Failed to audit request: unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/pf/dal.pm line 70.     (pf::UnifiedApi::after_dispatch_cb) `
- Database steps of configurator looks good. User `root` and `pf` have passwords, `pf` table has been created

- Even after a MariaDB restart, using `root` account, it's possible to connect without password using `mysql` command

**Comment by nqb** [comment]
I tried to use Venom on ZEN to pass through configurator: I got same issue. 

The difference is when testing PacketFence on Debian 11 in CI environment using Venom: there is no issue but I even see following error message in logs:

`Sep 14 05:38:46 packetfence packetfence[1175]: pfperl-api(1175) ERROR: Failed to audit request: unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/pf/dal.pm line 70. (pf::UnifiedApi::after_dispatch_cb)`

In Venom scenario, MariaDB instance is restarted before changing admin password. This is was done by the frontend at some point.

**Comment by nqb** [comment]
According to @jrouzierinverse, after DB setup during step 2 of configurator, command `perl -I/usr/local/pf/lib_perl/lib/perl5 -I/usr/local/pf/lib -Mpf::db -e 'print $pf::db::DB_Config->{pass}'` should return DB password in `pf.conf` and not default password.

That is not what I have.

Tests done with @jrouzierinverse:
- `touch /usr/local/pf/conf/pf.conf`: I still got default password using `perl` command
- `configreload hard`: I still got default password using `perl` command
- `systemctl restart packetfence-config`: I got password from`pf.conf` and I'm able to move to next step

Something is preventing `pfconfig` to work properly.

**Comment by nqb** [comment]
After I disabled AppArmor inside ZEN image, issue is gone.

AppArmor is enabled in CI but it doesn't cause that issue.

I will provide a fix to disable AppArmor inside ZEN image and in CI.

**Comment by nqb** [comment]
As I expect, AppArmor is not the guilty, even disabled, I got same bug.

@jrouzierinverse, can you try to replicate and see if you can fix it ?

**Comment by julsemaan** [comment]
What is weird with this is that I went through the ZEN test after releasing it

Can this be replicated on the ZEN without applying the maintenance? Perhaps the maintenance itself has regressed

**Comment by nqb** [comment]
> What is weird with this is that I went through the ZEN test after releasing it

It seems to be a random issue so it could explain why you don't get it and also why we don't see it when testing configurator each night.

> Can this be replicated on the ZEN without applying the maintenance? Perhaps the maintenance itself has regressed

It's a possible approach.

**Comment by nqb** [comment]
@jrouzierinverse, could you have a look on that issue ?

I'm able to replicate this issue on ZEN 11.1.0, if I restart `packetfence-config` before clicking on "Next step", there is no issue.

**Comment by nqb** [comment]
It looks like if you go fast on step 2, you don't have the issue.

**Comment by nqb** [comment]
I found the issue, will provide details ASAP.

**Comment by nqb** [comment]
The issue is related to my environment: VirtualBox + ZEN 11 OVA + non working DNS resolution at boot of image.

When I start ZEN 11 VM, time inside VM is synchronized with my host (certainly a VirtualBox config), so I got following behavior:

```
root@packetfence:~# date
Fri 29 Oct 2021 01:59:36 PM UTC
root@packetfence:~# timedatectl
               Local time: Fri 2021-10-29 14:40:38 UTC
           Universal time: Fri 2021-10-29 14:40:38 UTC
                 RTC time: Fri 2021-10-29 14:40:38
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
              NTP service: active
          RTC in local TZ: no
```
Which is wrong because UTC time should be 2 hours before.

Once I passed step 1 of configurator, I reconfigured my DNS correctly. Consequently, `systemd-timesyncd` start to synchronize time with NTP server. I got following date/time:

```
root@packetfence:~# timedatectl
               Local time: Fri 2021-10-29 12:41:55 UTC
           Universal time: Fri 2021-10-29 12:41:55 UTC
                 RTC time: Fri 2021-10-29 12:41:56
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
```
but `packetfence-config` is still started with a wrong time so this is why it's necessary to restart it.
