### ISSUE TITLE
CoreDNS Golang unit tests failed randomly

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6581]
**Describe the bug**
Since few days, Golang unit tests failed at `github.com/inverse-inc/packetfence/go/coredns/test` test (in Debian 11 or RHEL8).

Example this night:
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1594648232#L682
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1594648223#L982
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1594522581#L680
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1594522575#L984

In the past, I fixed a CoreDNS test by enabling IPv6 inside RHEL8 images, see #6441 .

The most common issue I see is the i/o timeout.

It's important to backport fix to `maintenance/11.0` otherwise it prevents maintenance packages to be updated.

**Comment by julsemaan** [comment]
Should we disable this test **in the maintenance/11.0** branch while we're fixing this in devel?

**Comment by julsemaan** [comment]
Also IMO, this is a high priority item since it impacts the nightly maintenance release. We can't afford to not release it because of an issue like this since it delays the delivery of important fixes to the users

**Comment by nqb** [comment]
> Should we disable this test **in the maintenance/11.0** branch while we're fixing this in devel?

I agree @julsemaan.
As a workaround (used today), we can still build maintenance packages without tests.

**Comment by nqb** [comment]
`reload_test` has been disabled in maintenance, see https://github.com/inverse-inc/packetfence/commit/da73ad8dd40fd3e0e45023eeeb405e705d6202f6

**Comment by nqb** [comment]
@jrouzierinverse, I skipped CoreDNS `reload_test` in `maintenance/11.1` and in `devel` until we find a fix.

**Comment by nqb** [comment]
I didn't see any failure since my change.
