### ISSUE TITLE
VLAN filter: conditions on node_info.bypass_role are ignored

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6584]
**Describe the bug**
If you use a VLAN filter with condition on `node_info.bypass_role`, it will never match

**To Reproduce**
1. Create following VLAN filter

```
[bypass_role]
top_op=and
condition=node_info.bypass_role != "corporate"
status=enabled
scopes=RegisteredRole,RegistrationRole
run_actions=enabled
description=bypass_role
role=REJECT
```

2. Forge a RADIUS request for a new node (not registered)

=> You got a RADIUS Accept and rule is not matched (see `packetfence.log`)

**Expected behavior**
Rule must match because device doesn't have a bypass_role

**Additional context**
I try to use ID of role in conditions but it doesn't work.

**Comment by julsemaan** [comment]
I'm pretty sure I know why, its because node_info.bypass_role contains the ID but your filter contains the string representation

The frontend should abstract this from the user and make the value of node_info.bypass_role a select box with the value being the ID of the role

**Comment by jrouzierinverse** [comment]
> I'm pretty sure I know why, its because node_info.bypass_role contains the ID but your filter contains the string representation
> 
> The frontend should abstract this from the user and make the value of node_info.bypass_role a select box with the value being the ID of the role

This is not problem as bypass_role is lookup from the node_category table.
The problem is bypass_role is undefined.

The condition should be changed to
```condition=node_info.bypass_role != "corporate" || not_defined(node_info.bypass_role)```

**Comment by julsemaan** [comment]
IMO the `undef` value should make `node_info.bypass_role != "corporate"` true

**Comment by jrouzierinverse** [comment]
I don't disagree however I would prefer to change that behavior in 11.2 rather than in maintenance to avoid surprises in VLAN filters.

**Comment by nqb** [comment]
On PF 11.0.0, I tried solution provided by @jrouzierinverse with a node which doesn't have any `bypass_role` defined and the rule never matched.
Conditions tested:
- `condition=node_info.bypass_role != "corporate" || not_defined(node_info.bypass_role)`
- `condition=node_info.bypass_role != "corporate" || not_defined(node_info.bypass_role, "")` (written by the GUI)

In DB, value of `bypass_role_id` is equals to `NULL` for my node.
