### ISSUE TITLE
The git_commit_id file seems to be broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6596]
**Describe the bug**
Before 11.0, /usr/local/pf/conf/git_commit_id contained the git_commit_id for the build

Right now it contains:
```
[root@home-lab pf]# cat conf/git_commit_id
%{git_commit}
```

I'm on this package (an official 11.0 maintenance package):
```
[root@home-lab pf]# rpm -q packetfence
packetfence-11.0.0-20210922054120.374964939.0008.maintenance~11.0.el8.x86_64
```

**Comment by julsemaan** [comment]
We need to have this file working for the automated upgrade in order to obtain the pristine version when performing automated .rpmnew reconciliation

We'll have to see how we deal with this issue in #6583 for broken environments that have `%{git_commit}` inside that file

**Comment by nqb** [comment]
On Debian 11, the file is correct and updated after I get latest maintenance patches.

**Comment by nqb** [comment]
Push to maintenance/11.0, pipeline to build new packages: https://gitlab.com/inverse-inc/packetfence/-/pipelines/375795535
