### ISSUE TITLE
Wrong domain join output when attempting to join multiple times

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6598]
**Describe the bug**
When you try to join an AD domain and it fails and you retry it, it will always provide the join output and result of the first join. This means that if you fix it and the second join succeeds, it will show a failure with the output of the first one.

**To Reproduce**
1. Create a domain configuration and make a mistake by putting the wrong workgroup
2. Join the domain (it will fail)
3. Fix your mistake
4. Join the domain, check the packetfence.log, it succeeds there but the join result and output in the admin says it failed.

**Expected behavior**
We should get a success join and its output on the second join attempt

**Comment by julsemaan** [comment]
@satkunas, can you look at this when you have a moment, when you don't know that behavior we have the potential of losing a lot of time with customers

**Comment by satkunas** [comment]
@julsemaan please test

[6598.diff.txt](https://github.com/inverse-inc/packetfence/files/7226794/6598.diff.txt)

**Comment by julsemaan** [comment]
> @julsemaan please test
> 
> [6598.diff.txt](https://github.com/inverse-inc/packetfence/files/7226794/6598.diff.txt)

works!
