### ISSUE TITLE
Connection profiles: need to refresh web browser to have all Realms available

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6602]
**Describe the bug**
If you create a **new** realm and want to use it as a filter on a connection profile, you need to refresh your web browser to have new realm available in dropdown list.

**To Reproduce**
1. Create a new realm
2. Create a new connection profile with a filter on Realm

=> New realm is not available.

**Expected behavior**
New realm is available in dropdown list.

**Workaround**
Refresh your web browser after creating new realm.

**Comment by julsemaan** [comment]
bumping this to medium because that's the kind of thing users are not expecting and can lead to useless support requests
