### ISSUE TITLE
Role based vlan assignment problem after successful authentication of user in LDAP for packetfence version 10.3

### ISSUE THREAD

**Issue by subhasishhit123** [inverse-inc/packetfence#6609]
VLAN assignment problem after successful authentication of user in LDAP for  pf version 10.3

VLAN 5 should be assigned after successful authentication in LDAP.  The screen shoot for user role vlan id has been attached
![image](https://user-images.githubusercontent.com/91967983/136141429-aae3be82-66f3-486f-afad-58ff1828522b.png)

the log report has been attached for your reference:
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found authentication source(s) : 'LDAP-3' for realm 'null' (pf::config::util::filter_authentication_sources)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Authenticating user using sources : LDAP-3 (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Login::authenticate)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] [LDAP-3] Authentication successful for s.pahari (pf::Authentication::Source::LDAPSource::authenticate)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Authentication successful for s.pahari in source LDAP-3 (LDAP) (pf::authentication::authenticate)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] person s.pahari added (pf::person::person_add)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Successfully authenticated s.pahari (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Login::authenticate)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Using sources LDAP-3 for matching (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] [LDAP-3 vecc] Searching for (&(|(uid=s.pahari)(sAMAccountName=s.pahari))), from O=vecc, with scope sub (pf::Authentication::Source::LDAPSource::match_in_subclass)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] LDAP testing connection (pf::LDAP::expire_if)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Matched rule (vecc) in source LDAP-3, returning actions. (pf::Authentication::Source::match_rule)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Matched rule (vecc) in source LDAP-3, returning actions. (pf::Authentication::Source::match)
Oct  6 09:42:56 packetfence pfqueue: pfqueue(12496) INFO: [mac:unknown] User: 's.pahari' found in the directory (pf::Authentication::Source::LDAPSource::search_attributes_in_subclass)
Oct  6 09:42:56 packetfence pfqueue: pfqueue(12496) INFO: [mac:unknown] Successfully did a person lookup for s.pahari (pf::lookup::person::lookup_person)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Using sources LDAP-3 for matching (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Using sources LDAP-3 for matching (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] [LDAP-3 vecc] Searching for (&(|(uid=s.pahari)(sAMAccountName=s.pahari))), from O=vecc, with scope sub (pf::Authentication::Source::LDAPSource::match_in_subclass)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] LDAP testing connection (pf::LDAP::expire_if)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Matched rule (vecc) in source LDAP-3, returning actions. (pf::Authentication::Source::match_rule)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Matched rule (vecc) in source LDAP-3, returning actions. (pf::Authentication::Source::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) WARN: [mac:e8:d8:d1:53:ac:cc] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Using sources LDAP-3 for matching (pf::authentication::match)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:56 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Found source LDAP-3 in session. (Class::MOP::Class:::around)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12938) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] No provisioner found for e8:d8:d1:53:ac:cc. Continuing. (captiveportal::PacketFence::DynamicRouting::Module::Provisioning::execute_child)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] User s.pahari has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] security_event 1300003 force-closed for e8:d8:d1:53:ac:cc (pf::security_event::security_event_force_close)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12183) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) WARN: [mac:e8:d8:d1:53:ac:cc] locale from the URL  is not supported (captiveportal::PacketFence::Controller::Root::getLanguages)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) INFO: [mac:e8:d8:d1:53:ac:cc] Releasing device (captiveportal::PacketFence::DynamicRouting::Module::Root::release)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) INFO: [mac:e8:d8:d1:53:ac:cc] User default has authenticated on the portal. (Class::MOP::Class:::after)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) INFO: [mac:e8:d8:d1:53:ac:cc] re-evaluating access (manage_register called) (pf::enforcement::reevaluate_access)
Oct  6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599) WARN: [mac:e8:d8:d1:53:ac:cc] Can't re-evaluate access because no open locationlog entry was found (pf::enforcement::reevaluate_access)
Oct  6 09:42:57 packetfence pfqueue: pfqueue(12937) WARN: [mac:e8:d8:d1:53:ac:cc] Unable to pull accounting history for device e8:d8:d1:53:ac:cc. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)

**Comment by subhasishhit123** [comment]
I am getting packetfence.log

Oct  6 14:50:13 packetfence pfqueue: Argument "noSuchObject" isn't numeric in numeric eq (==) at /usr/local/pf/lib/pf/Switch/HP/Procurve_2500.pm line 260.
Oct  6 14:50:13 packetfence pfqueue: pfqueue(28552) INFO: [mac:] setting 10.250.250.109 port 21 to Registration VLAN (pf::task::pfsnmp::handleUpTrap)
Oct  6 14:50:14 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:14 packetfence pfqueue: pfqueue(28552) INFO: [mac:] Should set 10.250.250.109 ifIndex 21 to VLAN 153 but it is already in this VLAN -> Do nothing (pf::Switch::setVlan)
Oct  6 14:50:14 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:16 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:19 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:21 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:22 packetfence pfqueue: pfqueue(28510) WARN: [mac:e8:d8:d1:53:ac:cc] Unable to pull accounting history for device e8:d8:d1:53:ac:cc. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Oct  6 14:50:23 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:26 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:28 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:30 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:33 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:35 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:37 packetfence pfqueue: pfqueue(28482) WARN: [mac:e8:d8:d1:53:ac:cc] Unable to pull accounting history for device e8:d8:d1:53:ac:cc. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Oct  6 14:50:38 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:40 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:42 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:45 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:47 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:49 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:52 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:54 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:56 packetfence packetfence: pfperl-api(25546) INFO: getting security_events triggers for accounting cleanup (pf::accounting::acct_maintenance)
Oct  6 14:50:56 packetfence packetfence: pfperl-api(25539) INFO: Using 300 resolution threshold (pf::pfcron::task::cluster_check::run)
Oct  6 14:50:56 packetfence packetfence: pfperl-api(25539) INFO: All cluster members are running the same configuration version (pf::pfcron::task::cluster_check::run)
Oct  6 14:50:56 packetfence packetfence: pfperl-api(25541) INFO: processed 0 security_events during security_event maintenance (1633512056.06764 1633512056.07504)  (pf::security_event::security_event_maintenance)
Oct  6 14:50:56 packetfence packetfence: pfperl-api(25541) INFO: processed 0 security_events during security_event maintenance (1633512056.07649 1633512056.07939)  (pf::security_event::security_event_maintenance)
Oct  6 14:50:56 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:50:59 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:01 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:03 packetfence pfqueue: pfqueue(28451) WARN: [mac:e8:d8:d1:53:ac:cc] Unable to pull accounting history for device e8:d8:d1:53:ac:cc. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Oct  6 14:51:03 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:06 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:08 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:10 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:13 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:15 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:18 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:20 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:22 packetfence pfqueue: pfqueue(28552) WARN: [mac:] couldn't get MAC at ifIndex 21. This is a problem. (pf::Switch::_getMacAtIfIndex)
Oct  6 14:51:22 packetfence pfqueue: pfqueue(28552) WARN: [mac:] Tried to grab MAC address at ifIndex 21 on switch 10.250.250.109 30 times and failed (pf::task::pfsnmp::handleUpTrap)

Kindly suggest any configuration isues..

**Comment by extrafu** [comment]
Use the mailing list for such question.

**Comment by subhasishhit123** [comment]
Hi

role based vlan id assignment problem after successful authentication
through LDAP
It shows packetfence logs:
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
WARN: [mac:e8:d8:d1:53:ac:cc] locale from the URL is not supported
(captiveportal::PacketFence::Controller::Root::getLanguages)
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
INFO: [mac:e8:d8:d1:53:ac:cc] Releasing device
(captiveportal::PacketFence::DynamicRouting::Module::Root::release)
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
INFO: [mac:e8:d8:d1:53:ac:cc] User default has authenticated on the portal.
(Class::MOP::Class:::after)
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
INFO: [mac:e8:d8:d1:53:ac:cc] Instantiate profile default
(pf::Connection::ProfileFactory::_from_profile)
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
INFO: [mac:e8:d8:d1:53:ac:cc] re-evaluating access (manage_register called)
(pf::enforcement::reevaluate_access)
Oct 6 09:42:57 packetfence packetfence_httpd.portal: httpd.portal(12599)
WARN: [mac:e8:d8:d1:53:ac:cc] Can't re-evaluate access because no open
locationlog entry was found (pf::enforcement::reevaluate_access)
Oct 6 09:42:57 packetfence pfqueue: pfqueue(12937) WARN:
[mac:e8:d8:d1:53:ac:cc] Unable to pull accounting history for device
e8:d8:d1:53:ac:cc. The history set doesn't exist yet.
(pf::accounting_events_history::latest_mac_history)

connected switch port holding registration vlan after successful LDAP
authentication.

**Comment by extrafu** [comment]
You do not get it, don't you? You're now blocked for 30 days. Enjoy reading our documentation in the meantime.
