### ISSUE TITLE
Switch location along with connected interface information can not able to pull by packetfence-10.3 

### ISSUE THREAD

**Issue by subhasishhit123** [inverse-inc/packetfence#6610]
**Describe the bug**
Switch location along with connected interface information can not able to pull by packetfence

**To Reproduce**
1. Go to 'status'
2. Click on 'Network view'
3. put the cursor above registered node
4. It indicates unknown switch

**Screenshots**
![image](https://user-images.githubusercontent.com/91967983/136142769-d6cc2130-7eca-4676-b91a-91a4fe04d709.png)

**Comment by nqb** [comment]
Hello,

Please share location log of this node.

**Comment by subhasishhit123** [comment]
Oct  6 14:36:38 packetfence pfqueue: pfqueue(28552) INFO: [mac:] down trap received on 10.250.250.109 ifIndex 21 (pf::task::pfsnmp::handleDownTrap)
Oct  6 14:36:38 packetfence pfqueue: pfqueue(28552) INFO: [mac:] setting 10.250.250.109 port 21 to Registration VLAN (pf::task::pfsnmp::handleDownTrap)
Oct  6 14:36:38 packetfence pfqueue: pfqueue(28552) INFO: [mac:] setting VLAN at 10.250.250.109 ifIndex 21 from 1 to 153 (pf::Switch::setVlan)

**Comment by subhasishhit123** [comment]
switch port 21 
switch ip 10.250.250.109
node is connected

**Comment by nqb** [comment]
Could you provide a screenshot of "Location" tab of your node (in web admin) ?

**Comment by subhasishhit123** [comment]
![image](https://user-images.githubusercontent.com/91967983/136196224-1f091f30-2727-4900-8da5-be054efcae20.png)

**Comment by nqb** [comment]
There is no location log opened which explain why your node is not connected to any switch on the network view.

Closing this issue, use mailing list for questions related to configuration.
