### ISSUE TITLE
SSL Certificates - RADIUS / HTTPs page Simple GUI Enhancements (wording clarification)

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#6613]
**Is your feature request related to a problem? Please describe.**
It is not intuitive/unclear what information should be entered. Wording change would help a lot.

**Describe the solution you'd like**
1) Change "Certificate" to "RADIUS Server Certificate"
– this makes it easier for the customer to know this field is for the signed RADIUS server certificate

2) Change "Private Key" to "RADIUS Server Private Key
– same reasoning

3) Under Certificate Authority Certificate(s)
– there needs to be a help blurb above or below or readily visible that states something similar to the following:
"Trusted client authority certificates including root or intermediate certificates used for EAP-TLS must be added here"
– the purpose of this blurb (and its final language) is to avoid a customer who has a root, a number of intermediates and a server cert who is doing client-certificate-based EAP-TLS configuration from installing the intermediates in the Intermediate(s) section of the GUI... which will NOT WORK!

4) Group the "RADIUS Server Certificate" and "Private Key" together in the GUI.
– it is strange to have these two boxes separated by the Certificate Authority Certificate(s) section
– either move the CAC section above or below the cert and key section

5) Change "Certificate" to "HTTPs Server Certificate" in the HTTPS secrion
– this makes it easier for the customer to know this field is for the signed HTTPs server certificate

6) Change "Private Key" to "HTTPs Server Private Key in the HTTPS secrion
– same reasoning

**Describe alternatives you've considered**
The alternative is to update the documentation, but GUI change is a better approach.

**Additional context**
See attached
![image](https://user-images.githubusercontent.com/16311452/137097410-27e0e262-5ddb-4294-b6be-05ed040aa4d7.png)

**Comment by julsemaan** [comment]
I've put this in our internal 11.2 roadmap for prioritization
