### ISSUE TITLE
Support for UniFi OS-based controllers

### ISSUE THREAD

**Issue by telemachus210** [inverse-inc/packetfence#6616]
The API paths are different for UniFi OS-based controllers than the paths on the Linux\Windows based controllers. All API endpoints need to be prefixed with /proxy/network (e.g. https://192.168.0.1/proxy/network/api/s/default/self)

**Comment by nqb** [comment]
Hello,

1. What is the difference between an UniFi OS-based controller and a Linux/Windows based controller ?
2. Could you join documentation that explain difference in API paths ?

**Comment by telemachus210** [comment]
The UniFi OS runs on the CloudKey Gen2, CloudKey Gen2 Plus, and UDM Pro.
The paths to the controller for UniFi OS-based controllers a port suffix isn't required (:8443 is not required)

The attached source code from https://github.com/Art-of-WiFi/UniFi-API-client does an excellent job of documenting the differences in the URL paths and has written a class to detect which version of the controller is running.

**Comment by mpreissner** [comment]
Is this going to be added to a 12.x milestone?  Or is its removal from 12.0 a sign that PF is not planning to support UniFiOS-based consoles?

**Comment by julsemaan** [comment]
For now, this is not part of our short term roadmap and isn't assigned to any milestone.

If the changes aren't too big and you're able to test them, then you could always try perform the code change and submit us a pull request, we'll happily accept it
