### ISSUE TITLE
Filter engines upgrade script: handle configuration consistently with previous engine logic

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6618]
**Describe the bug**
In the previous filter engines configuration files, you could define twice the same rule name by mistake. The engine would just pick the first rule and ignore the second one. The upgrade script though picks the second one and not the first one which makes the upgraded file inconsistent with what it was before.

**To Reproduce**
1. Have the following file in a pre-v10 radius_filters.conf:
```
[bobettevisitor]
filter=ssid
operator=is
value=BOBETTE-VISITOR

[registration]
filter=user_role
operator=is
value=registration

[unreg_bobettevisitor:bobettevisitor&registration]
scope = returnRadiusAccessAccept
merge_answer = no
answer1 = Cisco-AVPair => url-redirect=https://packetfence.bobette.edu/Meraki::MR_v2/sid$session_id?
answer2 = Acct-Interim-Interval => 1800

[unreg_bobettevisitor:bobettevisitor&!registration]
scope = returnRadiusAccessAccept
merge_answer = no
```
2. Run the [upgrade script](https://github.com/inverse-inc/packetfence/blob/devel/addons/upgrade/to-10.0-filter_engines.pl) and you end up with
```
[unreg_bobettevisitor]
status=enabled
description=unreg_bobettevisitor
condition=ssid == "BOBETTE-VISITOR" && user_role != "registration"
merge_answer=no
scopes=returnRadiusAccessAccept
answer.1=Acct-Interim-Interval = 1800
answer.0=Cisco-AVPair = url-redirect=https://packetfence.bobette.edu/Meraki::MR_v2/sid$session_id?
```
3. As we can see it took the condition `bobettevisitor&!registration` while the filter engine in pre-v10 was using `bobettevisitor&registration`

**Expected behavior**

I know its a configuration mistake in the file before its upgraded but since the filter engine was accepting it, the upgrade script should ignore the second `unreg_bobettevisitor` and take the condition and data from the first one in order to be consistent.

**Comment by jrouzierinverse** [comment]
Why not keep both adding a suffix for each new instance.

**Comment by julsemaan** [comment]
The suffix isn't good IMO since the engine was silently ignoring the duplicate one before so the suffix will make the duplicate filter active while is was inactive before the upgrade script
