### ISSUE TITLE
EAP-TLS Server Hello Does Not Contain Root CA When Intermediates Are Present

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#6629]
**Describe the bug**
When a multi-tier RADIUS server cert is installed for use in EAP-TLS the Server Hello from PF omits the root CA certificate in the chain.

For PUBLIC CA's this is almost always a non-issue or harmless omission as it is expected client devices have a trusted root certificate store present with prior knowledge of the PUBLIC CA's root.

For PRIVATE CA's this is an issue because not all connecting clients connecting to a PEAP or EAP-TLS enabled endpoint will have prior knowledge of the PRIVATE CA chain.

As best practice, PF as the RADIUS endpoint should send back the full chain to the client:

Root -> Intermediate(s) -> Server

Currently PF only sends back:

Intermediate(s) -> Server

Attached two PDF's two PCAPS.

SCENARIO 1) root and server cert only
– PF sends both the root and server cert in the server hello
– PF sends the root in the Certificate Request section
– this is expected behavior

SCENARIO 2) root, intermediate and server cert 
– PF only sends back intermediate and server cert in the server hello
– PF sends the root in the Certificate Request section, no intermediates
– this is UNEXPECTED/UNDESIRED behavior

The behavior in both scenarios should be the same. The root CA should be included always.
The workaround for some installations is 'root CA should be installed on the client', but for some operating systems it is much easier if the root CA is always included

**Expected behavior**
The Roort CA should be included even if the intermediate is present

**Additional context**
See attached PDFs and PCAPs
[CFD-6913 - root-server-chain-A3-RADIUS-configuration.pdf](https://github.com/inverse-inc/packetfence/files/7363314/CFD-6913.-.root-server-chain-A3-RADIUS-configuration.pdf)
[CFD-6913 - multi-tier-chain-A3-RADIUS-configuration.pdf](https://github.com/inverse-inc/packetfence/files/7363315/CFD-6913.-.multi-tier-chain-A3-RADIUS-configuration.pdf)
[CFD-6913.zip](https://github.com/inverse-inc/packetfence/files/7363337/CFD-6913.zip)

**Comment by julsemaan** [comment]
I think this will be a matter of better documenting the page because the CA certificates only apply to validating client certificates during EAP-TLS and doesn't apply at all when the server cert + chain is presented.

If the root CA must be presented during the TLS handshake because its not in the client's CA store, then it must be added to the intermediates.

That's how the HTTP section works as well so things are consistent but we could change:
- Intermediates -> Chain of certification
- CA certificate -> CA certificates for EAP-TLS validation

That would make things clearer

**Comment by RHDHV-simon-sutcliffe** [comment]
Would it not be better to "create" a chain for the user and check it is complete? 

The user would than just enter the information into the New SSL Certificate pages and the application should create what was needed.

If this is not possible then maybe a comment field under the Intermediate(s) CA field telling the user they must combine the certs to make the full chain.

**Comment by julsemaan** [comment]
> I think this will be a matter of better documenting the page because the CA certificates only apply to validating client certificates during EAP-TLS and doesn't apply at all when the server cert + chain is presented.
> 
> If the root CA must be presented during the TLS handshake because its not in the client's CA store, then it must be added to the intermediates.
> 
> That's how the HTTP section works as well so things are consistent but we could change:
> 
> * Intermediates -> Chain of certification
> * CA certificate -> CA certificates for EAP-TLS validation
> 
> That would make things clearer

Has been done in #6613
