### ISSUE TITLE
FreeRADIUS packages with PacketFence v11.0.0 and after

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6631]
**Describe the bug**
We released PacketFence v11.0.0 with FreeRADIUS 3.0.23.

A user reported a segfault issue with this version of FreeRADIUS which has been fixed [upstream](https://github.com/FreeRADIUS/freeradius-server/issues/4129).
- 3.0.24 with this fix has been released in September 2021 (http://lists.freeradius.org/pipermail/freeradius-announce/2021-September/000021.html)
- 3.0.25 has been released 8 days after 3.0.24 (http://lists.freeradius.org/pipermail/freeradius-announce/2021-October/000022.html) and it seems that it adressed serious issues in 3.0.24

IMHO, we should provide latest 3.0.25 for next PacketFence version and see if we can backport that change to 11.0.0

**Comment by fdurand** [comment]
FreeRADIUS 3.0.25 has been pushed in 11.1 for RHEL 8 and Debian 11.

**Comment by julsemaan** [comment]
Reopening on +1 to put it in the maintenance after 11.1

**Comment by nqb** [comment]
Don't backport to maintenance/11.0 for now, I identified an issue. I will open an issue.

**Comment by nqb** [comment]
Related issue has been fixed by @fdurand. We can backport when ready, tests on maintenance/11.0 will occur to confirm.

**Comment by fdurand** [comment]
Cherry-picked in maintenance/11.0

**Comment by nqb** [comment]
@fdurand, I think there is an issue because all tests (Debian and EL) failed this night at package installation:
- EL8: https://gitlab.com/inverse-inc/packetfence/-/jobs/1880878414#L454
- Debian 11: https://gitlab.com/inverse-inc/packetfence/-/jobs/1880878424#L448

**Comment by nqb** [comment]
`dot1x_eap_peap` tests are still failing on `maintenance/11.0` certainly due to #6633

**Comment by nqb** [comment]
Issue fixed, closing.
