### ISSUE TITLE
Portal preview links rewrite is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6638]
**Describe the bug**
When you preview a connection profile and you click on a link in the preview, it doesn't prefix the link path with `/portal_preview`

**To Reproduce**
1. Default fresh PF configuration
2. Preview the default connection profile
3. Click `Username/password login`
4. You're sent to `/switchto/default_policy+default_registration_policy+default_login_policy` instead of `/portal_preview/switchto/default_policy+default_registration_policy+default_login_policy`

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/137956802-597e74d9-d373-4c16-8168-936203427b1f.png)

**Comment by fdurand** [comment]
Can you make a try with the latest devel ?

**Comment by julsemaan** [comment]
works as expected now!
