### ISSUE TITLE
Full-upgrade: packetfence-upgrade is upgraded during full upgrade

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6640]
**Describe the bug**
When you upgrade from one PF version to another using `packetfence-upgrade` package, the package `packetfence-upgrade` is upgraded himself which can cause unexpected behaviors.

We should exclude `packetfence-upgrade` package from full upgrade process.

**To Reproduce**
1. PacketFence 11.0.0 with `packetfence-upgrade `installed
2. Run `UPGRADE_TO=11.1 /usr/local/pf/addons/full-upgrade/run-upgrade.sh`

=> `packetfence-upgrade` is upgraded

**Expected behavior**
`packetfence-upgrade` is not upgraded, it will be upgraded next time server is upgraded through `/usr/local/pf/addons/upgrade/do-upgrade.sh`

**Comment by julsemaan** [comment]
I'm not sure how we can cleanly fix this other than excluding it from there:
https://github.com/inverse-inc/packetfence/blob/devel/addons/full-upgrade/run-upgrade.sh#L85
https://github.com/inverse-inc/packetfence/blob/devel/addons/full-upgrade/run-upgrade.sh#L74

I'll have to dig into excluding the packages from the update

**Comment by nqb** [comment]
LGTM

**Comment by julsemaan** [comment]
RHEL and Debian should be fine

**Comment by nqb** [comment]
Work as expected on Debian
