### ISSUE TITLE
Full-upgrade(EL8): change logic to update repository definition

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6642]
**Describe the bug**
When we upgrade from one version to another using full upgrade mechanism on EL8, we replace manually PacketFence release in `/etc/yum.d/packetfence.repo`

https://github.com/inverse-inc/packetfence/blob/88fa4bfe1b7a4217465506e3d77e586a35c2679f/addons/full-upgrade/run-upgrade.sh#L80-L82

IMHO, it's a problem because after this change, system has:
- `packetfence-release` provided by current version installed
- `packetfence.repo` file modified to match future version

File provided by package doesn't match what we have on the system.

It also means that during the upgrade process, `packetfence-release` will be updated and `packetfence.repo` will be replaced (again). During my tests, it creates a `packetfence.repo.rpmsave` certainly due to the manual changes made by `run-upgrade.sh`

On top of that, if we want to push a change related to repository definition using `packetfence-release` before doing package upgrades, it's not possible.

**To Reproduce**
1. PacketFence 11.0.0 on EL8 with `packetfence-upgrade` installed
2. `UPGRADE_TO=11.1 /usr/local/pf/addons/full-upgrade/run-upgrade.sh`

**Expected behavior**
My proposal is to upgrade `packetfence-release` first using its friendly name: 

```
yum localinstall http://packetfence.org/downloads/PacketFence/RHEL8/packetfence-release-PF_MINOR_VERSION.el8.noarch.rpm
```
then we can upgrade remaining packages and `packetfence-release` will not be updated.

**Comment by julsemaan** [comment]
I'm good with that but the thing is we would need packetfence-release-11.1.el8.noarch to be built on devel

Then when we release 11.1, 11.2 should be immediately published based on devel again

Otherwise we won't be able to test the upgrade process pre-release which is IMO a problem

**Comment by nqb** [comment]
`packetfence-release` is built on all branches (devel, maintenance and others) and updated on packetfence.org.

We also publish those packages using friendly names in https://www.packetfence.org/downloads/PacketFence/RHEL8/:
- `packetfence-release-11.0.el8.noarch.rpm` => packetfence-release rebuilt on maintenance/11.0, initially was built against v11.0.0 tag
- `packetfence-release-branches.el8.noarch.rpm` => packetfence-release built on latest branch different from devel
- `packetfence-release-devel.el8.noarch.rpm` => packetfence-release built on devel

IMHO, if we want to test the upgrade process pre-release, we should adapt code of `run-upgrade.sh` to perform following things:
- install `packetfence-release-PF_MINOR.el8.noarch.rpm` and allow to replace `PF_MINOR` by `devel `or `branches`
- define a function `find_latest_devel` as equivalent to `find_latest_stable` which will use:
   * https://www.packetfence.org/downloads/PacketFence/latest-devel-RHEL-8.txt
   * https://www.packetfence.org/downloads/PacketFence/latest-devel-Debian-11.txt

**Comment by julsemaan** [comment]
The thing is that things are inconsistent, we have to fetch packetfence-release-devel for EL but we have to setup the repo with 11.1 (or whatever the devel release is) for Debian

We could also have an environment flag to define to state we're upgrading against a devel which would trigger a special behavior but I'd like the devel upgrade to just be a normal upgrade just not pointing to the stable release.

We're already pushing devel to the 11.1 repo so I don't see why we can't push a packetfence-release-11.1 to match it since we're already committed to having a version for devel. That's unless I'm misunderstanding something in our CI which is 100% possible

**Comment by nqb** [comment]
> The thing is that things are inconsistent, we have to fetch packetfence-release-devel for EL but we have to setup the repo with 11.1 (or whatever the devel release is) for Debian

> I'd like the devel upgrade to just be a normal upgrade just not pointing to the stable release.

Agree on these two items. I always prefer to make no differences between stable on devel to avoid suprises.

> We're already pushing devel to the 11.1 repo so I don't see why we can't push a packetfence-release-11.1 to match it since we're already committed to having a version for devel. That's unless I'm misunderstanding something in our CI which is 100% possible

Completely doable, I think I don't it previously to avoid users trying to install the more up-to-date `packetfence-release` by hand. 
I can change that behavior and all builds on devel will upload `packetfence-release-11.1.el8.noarch.rpm` in https://www.packetfence.org/downloads/PacketFence/RHEL8/ in place of `packetfence-release-devel.el8.noarch.rpm`.

**Comment by julsemaan** [comment]
> I can change that behavior and all builds on devel will upload packetfence-release-11.1.el8.noarch.rpm in https://www.packetfence.org/downloads/PacketFence/RHEL8/ in place of packetfence-release-devel.el8.noarch.rpm.

This is the best solution in my opinion as it makes devel closer to a real release which will also be even more true in 11.2 if we remove the X.Y from the schema too

**Comment by nqb** [comment]
I will push a change now for that.

**Comment by nqb** [comment]
@julsemaan, it should be good now. I cleanup old `packetfence-{export,release}-devel` packages to avoid confusion.

**Comment by julsemaan** [comment]
I'll push adjustments to fetch the packetfence-release instead of 'sedding' the file
