### ISSUE TITLE
Logrotate - "Read-only file system" error for pf logs on Debian 11

### ISSUE THREAD

**Issue by heapdavid** [inverse-inc/packetfence#6648]
**Describe the bug**
Overnight log rotation by `logrotate` is unable to open or rename packetfence/fingerbank log files and the error message indicates a read-only filesystem on Debian 11.

**To Reproduce**
Installed PF 11.0 on Debian 11
Run `systemctl start logrotate.service`
Run `journalctl -u logrotate.service` and see the error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/88432183/137944282-82329ee8-f718-45e2-9af8-32c47a8f783b.png)

Transcription:

```
Oct 19 00:00:00 xxxx-portal logrotate[773192]: error: error renaming /usr/local/fingerbank/logs/fingerbank.log.7.gz to /usr/local/fingerbank/logs/fingerbank.log.8.gz: Read-only file system
Oct 19 00:00:00 xxxx-portal logrotate[773192]: error: error opening /usr/local/pf/logs/api-frontend.log: Read-only file system
Oct 19 00:00:00 xxxx-portal logrotate[773192]: error: error opening /usr/local/pf/logs/httpd.api-frontend.access: Read-only file system
Oct 19 00:00:00 xxxx-portal systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Oct 19 00:00:00 xxxx-portal systemd[1]: logrotate.service: Failed with result 'exit-code'.
Oct 19 00:00:00 xxxx-portal systemd[1]: Failed to start Rotate log files.
```

**Expected behavior**
PF logs to be rotated successfully as per `logrotate` config.

**Additional context**
It looks like `logrotate` on Debian 11 is using systemd's ProtectSystem feature which gives it read-only access to anything outside /var/log by default - see https://askubuntu.com/a/1275673 for more in-depth discussion.

I've added the following to an override.conf for the `logrotate` service and this seems to have resolved the issue for now:
```
[Service]
ReadWritePaths=/usr/local/pf/logs/
ReadWritePaths=/usr/local/pf/var/
ReadWritePaths=/usr/local/fingerbank/logs/
```

**Comment by nqb** [comment]
Hello @heapdavid,

Thanks for you report. I can confirm the issue.

It looks like `logrotate` service is loaded on a ZEN installation (Debian 11).
However, if I just run logrotate manually:

`/usr/sbin/logrotate -f /etc/logrotate.conf`

File rotation in `/usr/local/pf/logs` is performed. 

According to `/etc/cron.daily/logrotate`, `logrotate` is now performed by `systemd-timers` : 

```console
# systemctl list-timers
NEXT                        LEFT        LAST                        PASSED        UNIT                         ACTIVATES
Thu 2021-10-21 11:36:56 UTC 34min left  Tue 2021-10-19 13:29:29 UTC 1 day 21h ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Thu 2021-10-21 20:22:20 UTC 9h left     Thu 2021-10-21 09:41:34 UTC 1h 21min ago  apt-daily.timer              apt-daily.service
Fri 2021-10-22 00:00:00 UTC 12h left    Thu 2021-10-21 00:00:01 UTC 11h ago       logrotate.timer              logrotate.service
```

**Comment by julsemaan** [comment]
Is the fix compatible with the maintenance?

If so, it should go in IMO since this has the potential to fill up disk space on Debian 11 machines

**Comment by auqf** [comment]
I add the  ReadWritePaths=/usr/local/nginx/logs  is not effect at the end of the logrotate.service, is there some limits of it?
