### ISSUE TITLE
Meraki v2 module doesn't support RADIUS Disconnect although the equipment supports it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6649]
**Describe the bug**
Meraki v2 module doesn't support RADIUS Disconnect although the equipment supports it

Since it inherits from Cisco::WLC, we should just remove Meraki::MR_v2::radius_disconnect and it will work fine

**Comment by haikalshiddiq** [comment]
Hello, anyone can share how to config meraki to adding to packetfence as radius and captive portal redirection?

There is no clear instruction on installation and network device guide, kindly help to share for this.


Thank you
