### ISSUE TITLE
Can create connection profile with basic and advanced filter

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6650]
**Describe the bug**
Can create connection profile with basic and advanced filter

**To Reproduce**
1. Create a new connection profile
2. Name it test
3. Add basic filter SSID -> Banana
4. Add advanced filter ssid -> equals -> Banana
5. Save
6. Connection profile is created

**Expected behavior**
We should have an error to force the user to pick only one of them

**Comment by jrouzierinverse** [comment]
This is not a bug. It was designed from the beginning to use both.
However If you want to change this behavior.
We should do that in 11.2 where I write an upgrade script to merge both filters together into a single filter.

**Comment by julsemaan** [comment]
At some point they were exclusive in a recent release so its a new undocumented behavior I guess

We need to know what goes first basic or advanced and properly document this in the connection profile page

**Comment by jrouzierinverse** [comment]
Julien there were never exclusive from the beginning of the feature.

**Comment by julsemaan** [comment]
They were at some point in the GUI I forgot to mention, the backend must have accepted both but the GUI prevented you from entering both

Lets get the behavior clear in the connection profile page and we're good to go with the behavior as it is today

**Comment by jrouzierinverse** [comment]
In the GUI you must enter at least one of them.

**Comment by julsemaan** [comment]
The behavior that needs to be defined is what happens if you enter stuff in both, does it acts as an additional basic filter and respects the all/any ?

I understand it works now but we need to make it clear on what to expect when we enter data in both filters

**Comment by jrouzierinverse** [comment]
Yes it works just like that ```it acts as an additional basic filter and respects the all/any```.

**Comment by julsemaan** [comment]
Then lets get this into the page so the behavior is seen by the users

**Comment by julsemaan** [comment]
@jrouzierinverse, can you get this done ASAP

I'd add the clarifications but its still not fully clear how this behaves so we need you to describe it shortly under the advanced filter field

Thanks
