### ISSUE TITLE
Empty out apache_filters.conf.defaults to prevent redirection issues

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6652]
**Describe the bug**
The apache filters used to be in the dispatcher code path but now that its in Golang they aren't called in that context anymore, only when the HTTP call is on the portal. I'm working on an issue where they are causing problems with a Samsung device (surprise, surprise!) so removing them completely would make sense to me

**Comment by julsemaan** [comment]
I'm marking this for 11.2 and will need @fdurand's blessing too

**Comment by fdurand** [comment]
apache filters are not part anymore from the admin gui. We should remove them now.
