### ISSUE TITLE
Monit logrotate issue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6661]
Date:        Tue, 26 Oct 2021 08:41:28
Host:        cluster1
Event:       Status failed
Resource:    monitoring-check
Action:      alert

Description: status failed (1) -- awk: fatal: cannot open file `/usr/local/pf/var/logrotate.status' for reading: No such file or directory
awk: cmd. line:1: warning: regexp escape sequence `\#' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\#' is not a known regexp operator
Ignoring script /usr/local/pf/var/monitoring-scripts/.check-backups.sh because it has to run as root but it is denied on this setup.
Report for 09c8337d-6a39-4ce5-89d9-a4147b533689

/usr/local/pf/var/monitoring-scripts/.check-logrotate.sh failed
Result of /usr/local/pf/var/monitoring-scripts/.check-logrotate.sh
PacketFence logrotate script '/etc/logrotate.d/packetfence' is not up to date compared to maintenance for '11.1.0'
------------------------------------------

A copy of this alert has been sent to the PacketFence support team.

**Comment by nqb** [comment]
@fdurand:
- awk error messages can be ignored
- check-logrotate.sh error occured due to missing branch `maintenance/11.1` because you are certainly testing on `devel`

Feel free to reopen if I'm wrong.
