### ISSUE TITLE
pfpki: clarify behavior when certificates are provided using SCEP

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6671]
**Describe the bug**
In order to get a certificate using SCEP through `pfpki`, a node need to generate a CSR which contain informations to generate its own certificate. For example:

https://github.com/inverse-inc/packetfence/blob/7e16d54c250373b9ec65248066a996976fd97d7a/t/venom/nodes/wired_dot1x_eap_tls/run_sscep_on_node01.yml#L23-L41

At the moment (v11.0.0) , I noticed that only CN is taken into account. All others DN parameters are ignored.

I would like to document what is the expected behavior.
See also https://github.com/inverse-inc/packetfence/issues/6248

**Comment by fdurand** [comment]
Profile attributes winas against scep request attributes. #6767
