### ISSUE TITLE
Functionality of Anomaly Detection -  Question

### ISSUE THREAD

**Issue by aziel12** [inverse-inc/packetfence#6675]
Hello, this is a question, not a bug report. 
I would like to know how does anomaly detection through commercial APIs work? Does it use somekind of Machine learning algos or is the whole detection based on: 1) identify device X  2) download specific policy(rule) Z 3) monitor if device X in network complies with Z.
Thank you.

**Comment by extrafu** [comment]
It's both and only open to selective testers.  Stay tuned for more information.
