### ISSUE TITLE
httpd.portal "not handling requests"

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#668]
No real way to replicate, but on some setups it looks like redirection to the portal does not occur. Restarting httpd.portal service resolve the issue.
tcpdump shows requests coming in...
Need investigation

**Comment by louismunro** [comment]
This is a bona fide Zammitbug.
Will have it's own Wikipedia entry.

**Comment by dwlfrth** [comment]
Check for webauth correlation

**Comment by julsemaan** [comment]
I think we may have fixed it at the same time as with the pf::Statsd and config issue.

When closing all the dashboard services I had positive feedback that it was resolved.

May be a coincidence I'll assign it to myself so it's not lost as this is pretty major

I'll assign it to myself

**Comment by dwlfrth** [comment]
Just for the records, will you assign it to yourself ? ;)

**Comment by julsemaan** [comment]
Fixed in devel, maintenance/5.2 and maintenance/5.3
