### ISSUE TITLE
v11 Web admin: Add static route does not display properly

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6683]
When I add a static route it works on the server but when I reload the page I have that:

![image](https://user-images.githubusercontent.com/5261214/140511527-eea628f1-076f-4a69-b5a2-469bf8177e73.jpeg)

Step to reproduce:

- Add a route
- Restart keepalived
- Refresh the web admin page

**Comment by nqb** [comment]
Fixes backported to 11.1, 11.0 and 10.3
