### ISSUE TITLE
unable to connect to database: Access denied for user 'pf'@'localhost' 

### ISSUE THREAD

**Issue by coldflame-js** [inverse-inc/packetfence#6685]
Dear Guys 

Took me know hours but I still get no authentication from client with 802.1x + MAC. I'm usimg 11.1.
While looking to the log, I see a auth. Error regarding the a database query.

->->Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) FATAL: [mac:[undef]] unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/CHI/Driver/DBI.pm line 28.
(pf::CHI::db::db_connect)

The installation has now be cleaned up (reinstalled) two times. The database configuration in the setup has been done “automaticly” (by wizard). I'm using the packet fence zero effort OVA.

I’ve checked the with login “pf”@localhost and also as root manually (mysql). I was able to login and check the user-table:

MariaDB [mysql]> select user,host,authentication_string,plugin from mysql.user
    -> ;
+-------------+-----------+-------------------------------------------+-----------------------+
| User        | Host      | authentication_string                     | plugin                |
+-------------+-----------+-------------------------------------------+-----------------------+
| mariadb.sys | localhost |                                           | mysql_native_password |
| root        | localhost | *5E0316A4B8BD7B23XXXXX0580425566E5 | mysql_native_password |
| mysql       | localhost | invalid                                   | mysql_native_password |
| pf          | %         | *0861D201B2B18B1F8DBEXXXXXXXF626088E47F73 | mysql_native_password |
| pf          | localhost | *0861D201B2B1XXXXXXXXEAF626088E47F73 | mysql_native_password |
+-------------+-----------+-------------------------------------------+-----------------------+
5 rows in set (0.001 sec)

A reset of the password for pf@localhost was also successfully. I still get the error.

Could there be a bug or does anyone has a good hint for me?

thanks a log for checking for bug or giving me a hint.

sincerely

**Comment by coldflame-js** [comment]
Additionally some logs around the error (packetfencelog, mariadb-log, httpd.aaa error/auth


Nov 6 16:24:52 packetfence httpd_aaa[1462]: 127.0.0.1 - - [06/Nov/2021:17:24:52 +0100] "-" 408 0 0 19 "-" "-" "-"
Nov 6 16:24:56 packetfence auth[9610]: Adding client 10.123.252.1/32
Nov 6 16:24:56 packetfence auth[9610]: (4817) rest: ERROR: Server returned:
Nov 6 16:24:56 packetfence auth[9610]: (4817) rest: ERROR: {"control:PacketFence-Authorization-Status":"allow"}
Nov 6 16:24:56 packetfence auth[9610]: [mac:dc:a6:32:b2:5e:02] Rejected user: dca632b25e02
Nov 6 16:24:56 packetfence auth[9610]: (4817) Rejected in post-auth: [dca632b25e02] (from client 10.123.252.1/32 port 7 cli dc:a6:32:b2:5e:02)
Nov 6 16:24:56 packetfence auth[9610]: (4817) Login incorrect (rest: Server returned:): [dca632b25e02] (from client 10.123.252.1/32 port 7 cli dc:a6:32:b2:5e:02)
Nov 6 16:24:56 packetfence httpd_aaa_err[1461]: Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 48.
Nov 6 16:24:56 packetfence httpd_aaa_err[1461]: Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
Nov 6 16:24:56 packetfence httpd_aaa_err[1461]: Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
Nov 6 16:24:56 packetfence httpd_aaa_err[1461]: Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.

->->Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) FATAL: [mac:[undef]] unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/CHI/Driver/DBI.pm line 28.
(pf::CHI::db::db_connect)

Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) ERROR: [mac:[undef]] radius authorize failed with error: unable to connect to database: Access denied for user 'pf'@'localhost' (using password: YES) at /usr/local/pf/lib/CHI/Driver/DBI.pm line 28.
(pf::api::radius_authorize)
Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) WARN: [mac:[undef]] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 48.
(pf::radius::rest::format_response)
Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) WARN: [mac:[undef]] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
(pf::radius::rest::format_response)
Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) WARN: [mac:[undef]] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
(pf::radius::rest::format_response)
Nov 6 16:24:56 packetfence packetfence_httpd.aaa[10168]: httpd.aaa(1383) WARN: [mac:[undef]] Use of uninitialized value $radius_return in numeric eq (==) at /usr/local/pf/lib/pf/radius/rest.pm line 53.
(pf::radius::rest::format_response)
Nov 6 16:24:56 packetfence httpd_aaa[1462]: 127.0.0.1 - - [06/Nov/2021:17:24:56 +0100] "POST //radius/rest/authorize HTTP/1.1" 401 205 2239 3095 "-" "FreeRADIUS 3.0.25" "127.0.0.1:7070"

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by coldflame-js** [comment]
for me it dosn't look like a user issues, rather than a bug. Probably would be worth checking.
Bug as you told, I will try to ask in the users group.
Thank you anyway
