### ISSUE TITLE
Unifi: deauthentication doesn't work anymore if AP are declared by IP address

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6686]
**Describe the bug**
It looks like since #6134, deauthentication of a user doesn't work if it is connected on a Unifi access point which is declared by IP address (not by MAC address).

An AP declared by IP address will not pass `if` test:
https://github.com/inverse-inc/packetfence/blob/758bce50d9fb12c7d538745452507e16448b9d93/lib/pf/Switch/Ubiquiti/Unifi.pm#L272-L277

**To Reproduce**
1. Declared a Unifi AP by IP address
2. Authenticate on captive portal using Web Auth
3. Check logs in `packetfence.log`:

```
│Nov  5 08:58:39 pf01 pfqueue[132890]: pfqueue(132890) INFO: [mac:4c:32:75:70:0e:19] Found site: Test (pf::Switch::Ubiquiti::Unifi::_deauthenticateMacWithHTTP)                                                         │
│Nov  5 08:58:39 pf01 pfqueue[132890]: pfqueue(132890) INFO: [mac:4c:32:75:70:0e:19] Deauth on 0 access points (pf::Switch::Ubiquiti::Unifi::_deauthenticateMacWithHTTP)     
```

**Expected behavior**
Deauthentication should also work on AP declared by IP address.

**Additional context**
In this setup, AP are declared using a CIDR.

**Comment by julsemaan** [comment]
I'm open to have suggestions on how to rework this workflow since this deauth method is a complete mess in my opinion, we just keep adding layer over layer of workarounds to fix use cases.

I don't have access to a Unifi lab either so it will be hard for me to fix this the right way
