### ISSUE TITLE
Unable to access configurator on latest devel

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6695]
**Describe the bug**
Unable to access configurator on latest devel

**To Reproduce**
1. Install packetfence-11.2.0-20211109143600.405287404.0008.devel.el8.x86_64
2. Go in configurator
3. Error b0rk3n

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/141115307-188d108c-f378-4b2b-aa14-dc5fcc5cf081.png)

**Comment by satkunas** [comment]
I wasn't able to reproduce the same error, but I did push a fix that addressed a recent breaking change. Please re-test.

**Comment by satkunas** [comment]
I wasn't able to reproduce the same error, but I did push a fix that addressed a recent breaking change. Please re-test.

**Comment by julsemaan** [comment]
Works now!
