### ISSUE TITLE
Check certificate validity after generating the template.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#671]
Check if the certificate is valid after generating the config file from the template file.
Per example if we generate a certificate like pf.conf and we change the file conf/radius/eap.conf with the new cert then the chekup will test the certificate include in raddb/eap.conf (old one) and return FATAL.

**Comment by julsemaan** [comment]
Yeah that's dued to the fact that the checkup happens before the service start.

Other than initiating the config install or generating it in a temp location before the checkup, there's no  way around it the way we have things built.

Generating it before the checkup would go against it as it has (and should have) the power to stop a startup (thus the config install). :chicken: :egg:

That's partly why I added the skip checkup to workaround situations like this where you know what you're doing (and make things explode)

A possible solution it would be to have configreload regenerate the config files so then before starting the service, the config would be already in place. That would require a bit of rework of the services manager but nothing too major.

On the user end, that would require a configreload when touching these configs but would be the only clean solution I'd see.

Other opinions are more then welcome.

**Comment by julsemaan** [comment]
I believe this was addressed via a warn when it isn't comipiled so that can be closed
