### ISSUE TITLE
pfpki: editing PKI templates is possible but not taken into account

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6713]
**Describe the bug**
On PF v11.1.1, if you edit a PKI template to change settings, frontend lets you perform your operation. After you click on "Save", some fields become empty and values are not updated in DB.

**To Reproduce**
1. Create a CA and a PKI template with a Country and a Locality values
2. Change "Country" setting in your PKI template
3. Save

=> Country and Locality fields became empty

**Expected behavior**
I'm not sure what should be the expected behavior. I remembered it was not possible to edit PKI templates in the past.

**Comment by fdurand** [comment]
covert by PR #6767
