### ISSUE TITLE
Can not start freeradius in debug mode

### ISSUE THREAD

**Issue by codilimeinternal** [inverse-inc/packetfence#6720]
**Describe the bug**
After installation and upgrading packetfence on VM with Debian 11 bullseye OS can not start freeradius in debug mode. I already have connect SecureLDAP in main portal (section configuration ---> Pilicies and Access Control ---> Authentication Sources ---> New Internal Source ). I am trying to authenticate and authorize users by RADIUS (databases for users in SecureLDAP from Google.)

**To Reproduce**
1. Get access into vm via SSH port
2. From main pwd start command "freeradius -X -d /usr/local/pf/raddb -n auth"
3. Output from free radius is : 

`Failed binding to auth address MY_MANAGEMENT_ADDRESS port 1812 bound to server packetfence: Address already in use 
/usr/local/pf/raddb/auth.conf[19]: Error binding to port for MY_MANAGEMENT_ADDRESS port 1812`

4. After this Output:

`ps aux | grep freeradius` 
 
commandline is showing:

`pf         81115  0.2  1.2 433548 150060 ?       Ssl  13:05   0:01 /usr/sbin/freeradius -d /usr/local/pf/raddb -n auth -fm`

5. kill the process:
`kill -9 81115`

6. Again try to start freeradius in Debug Mode:

`freeradius -X -d /usr/local/pf/raddb -n auth`

7. Output from commandline:

`/usr/local/pf/raddb/auth.conf[26]: Threading must be enabled for TLS sockets to function properly
/usr/local/pf/raddb/auth.conf[26]: You probably need to do 'auth -fxx -l stdout' for debugging`

8. Due to reccomendation my next step is:

`freeradius -X -d /usr/local/pf/raddb -n authfreeradius -X -d /usr/local/pf/raddb -n auth -fxx -l stdout`

9. And the output from commandline:

`Thu Nov 25 13:21:10 2021 : Error: Failed binding to status address 127.0.0.1 port 18121 bound to server status: Address already in use 
Thu Nov 25 13:21:10 2021 : Error: /usr/local/pf/raddb/auth.conf[7]: Error binding to port for 127.0.0.1 port 18121`

And this steps are repeated and repeated everytime.

my auth.conf file:

![image](https://user-images.githubusercontent.com/70697205/143441226-5b771b0b-0196-4f89-912b-3b2ed79bd7a2.png)

**Expected behavior**
Start freeradius in debug mode in order to testing packetfence.

**Desktop (please complete the following information):**
-  Operating System: Debian GNU/Linux 11 (bullseye)
-  Kernel: Linux 5.10.0-9-amd64
-  Version - Packetfence 11
- VM has 12GB RAM, 100GB SSD, 2 CPU each 2 cores

**Comment by codilimeinternal** [comment]
Hello,

Can I ask for review this ticket ?

regards.

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by drthiruna** [comment]
The same issue is observed by me with same setup 
@codilimeinternal Any solutions?
