### ISSUE TITLE
PF10.2 Report Unregistred spin without results.

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6731]
**Describe the bug**
On /admin/alt#/reports/standard/chart/unregistered the request is send and return 200 but it continues to spin without data.

**To Reproduce**
1. Go to Reports -> Standard Reports -> Node -> Unregistered
2. Wait
3. Wait
4. ....

**Expected behavior**
Having the list of unregistered nodes

**Desktop (please complete the following information):**
 - Browser FireFox
 - Version 94.0.2

**Comment by satkunas** [comment]
After a closer look this appears to be a performance issue with the UI combined with the reports returning a large amount of data. I would recommend that the customer upgrade to the latest version to take advantage of the performance improvements and the new Reports UI.
