### ISSUE TITLE
Reports - Misplacing of Static IP section

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#6732]
In v11.1, Reports module, "Static IP" is misplaced under Fingerbank - that needs to be fixed.

**Comment by satkunas** [comment]
This report includes all active nodes without a known `dhcp_fingerprint`.

https://github.com/inverse-inc/packetfence/blob/devel/conf/report.conf.defaults#L606-L634

To which section should it be moved?

**Comment by satkunas** [comment]
Fix available in `fix/6732`. 

I had to merge 2 similar reports into a single report. Large dataset is needed to ensure the merge was done properly.
