### ISSUE TITLE
Installation Guide update request - firewalld.

### ISSUE THREAD

**Issue by hisashiyamaguchi** [inverse-inc/packetfence#6733]
It seems that Packet Fence requires firewalld that is not installed on EC2 instance as default. An explicit note for this on pre-requisites is mandatory.

[Installation Guide
](https://www.packetfence.org/doc/PacketFence_Installation_Guide.html)

**Comment by julsemaan** [comment]
I'm closing this in favor of fixing it in #6730 where I'll add firewalld as an explicit dependency of the packetfence package so this way there won't be an additional install step when its missing
