### ISSUE TITLE
Reintroduce logic in cf92dc81edd9d9d30461d2890d594770df59166b

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6735]
**Describe the bug**
The logic added in cf92dc81edd9d9d30461d2890d594770df59166b will return 2 rows when the Packet-Src-IP-Address and NAS-IP-Address are different and both are defined as switches in PF. This causes FreeRADIUS to refuse to process the request.

I already reverted this in devel + maintenance so this issue is for reintroducing that feature but with insurance that only 1 row can be returned

**Comment by jrouzierinverse** [comment]
This has been fixed by #6736
