### ISSUE TITLE
Only first 25 items are shown /api/v1/node_categories or /api/v1/config/roles

### ISSUE THREAD

**Issue by Xia00815** [inverse-inc/packetfence#6738]
Hi, when i try to use the Packetfence api with /api/v1/node_categories or /api/v1/config/roles. I only get back the first 25 Roles, but i have 43 Roles. 

Normaly i expect that i got all Roles which are existing in the webinterface.

**Comment by nqb** [comment]
Hello,

Which PacketFence version are you using ? Did you apply latest maintenance patches on it ?
IIRC, this issue has been already fixed since a while.

**Comment by julsemaan** [comment]
I think this is a problem of the usage of the API itself, not the admin interface.

You can increase the amount of returned items using `?limit=1000` in your API call or use scrolling

**Comment by Xia00815** [comment]
Thank you for the fast solution. I missunderstud the limit option into a curl php request. I added the limit option on my url and now its working. ty

I changed From:
/api/v1/node_categories 
to:
/api/v1/node_categories?limit=1000
