### ISSUE TITLE
Unable to edit NEW SSL Certificates within the Radius configuration section.

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6746]
**Describe the bug**
You are unable to reach the New SSL Certificates form in the Radius configuration.   Pressing the New SSL Certificate brings you to the New Fast Profile form. 

**To Reproduce**
1. Go to 'System Configuration' and expand
2. Click on 'SSL Certificates' from the side menu
3. Click on "New SSL Certificate" 
4. You will see you are directed to the "New Fast Profile" section

**Expected behavior**
I would have expected that I would have been taken to a form to create or enter information about a certificate 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge Chromium
 - Version 96.0.1054.43 (Official build) (64-bit)

**Comment by PureOxygen-Dev** [comment]
I changed this within our test platform and there was no difference to the behaviour. Still ending up at the New Fast Profile page.

**Comment by fdurand** [comment]
if you just apply the patch it's not enough, you have to recompile the admin.

**Comment by PureOxygen-Dev** [comment]
Thanks fdurand I guessed that was the case. Looking forward to 11.2 release.

**Comment by nqb** [comment]
@RHDHV-simon-sutcliffe, this fix has been pushed to maintenance/11.1 and maintenance/11.0 so you can get the fix by following instructions: https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Upgrade_Guide.asciidoc#upgrade-to-a-patch-version-xypatch

**Comment by nqb** [comment]
EDIT: fix for `11.0.0` is not yet available due to #6631

**Comment by nqb** [comment]
Fix is available for 11.0.0.
