### ISSUE TITLE
web admin: wrong display of fields for PKI templates

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6749]
**Describe the bug**
When you create a PKI template with Organisation, Organisation unit, State and Country, fields are saved in DB.
If you go back to your PKI template to enable SCEP setting and save. Then Organisation, Organisation unit, State and Country informations disappear when you switch to "General" tab.

If you close and get back to your template, you got same behavior. You need to refresh your web browser to get informations.

When I enabled SCEP setting on my PKI template, PATCH request sent by frontend doesn't contain Organisation, Organisation unit, State and Country fields.

However, the next API call to `api/v1/pki/profiles` contains this informations.

Has been noticed on PF 11.0.0, I was able to replicate on PF 11.1.0

**To Reproduce**
1. Create a CA
2. Create a PKI template with Organisation, Organisation unit, State and Country fields
3. Edit yout PKI template to enable SCEP setting
3. Save
4. Open your PKI template and check values of Organisation, Organisation unit, State and Country fields

=> They are blank.

**Expected behavior**
Frontend should display values of PKI templates in DB

**Additional context**
Organisation, Organisation unit, State and Country have never been updated in DB, only SCEP setting is updated.

Certainly related to #6713

**Comment by satkunas** [comment]
> If you go back to your PKI template to enable SCEP setting and save. Then Organisation, Organisation unit, State and Country informations disappear when you switch to "General" tab.

This is a red herring. These fields are cleared regardless of the SCEP setting.

The fields are cleared because the `PATCH /api/v1/pki/profile/:id` response doesn't return the `organisation`, `organisational_unit`, `country`, or `state`.

@fdurand is it possible to have these fields included in the PATCH response?
