### ISSUE TITLE
Dell N-Series Compatible Documentation Update

### ISSUE THREAD

**Issue by nicholaspier** [inverse-inc/packetfence#675]
This is a request to update documentation and the Packetfence website to indicate that the Dell N-Series campus switches are compatible with the software.

I've tested version: 6.2.1.6
Model: N2024P

The N-Series uses a single firmware image. So, this "should" be the same for all N20XX and N30XX switches. I used the Dell::Force10 Type for configuration with Radius set as the deauthentication method.

Configuration used both SNMP and Mac Address Bypass configuration and is as follows. Mac Address Bypass was used for switch to packetfence queries while SNMP was used to update ports after a user had registered and required a new VLAN. This was tested in out of band mode.

aaa authentication login "defaultList" local
authentication enable
dot1x system-auth-control
aaa authentication dot1x default radius
aaa authorization network default radius
dot1x dynamic-vlan enable
radius-server key "UseAStrongerKey"
radius-server host auth PF_SERVER_IP
    name "PacketFence"

End-Device ports can be configured as follows where vlan 101-103 are used for roles and vlan 200 is used for VoIP. Unauthorized devices are immediately placed in vlan 102 (registration). The port-control mac-based allows for multiple devices to be on the same port and use different vlans. This supports "dumb" switches and in my case, older Cisco 7960 phones which did not support LLDP (a role was created for these). 

interface Gi1/0/1
switchport mode general
switchport general allowed vlan add 101-103,200
dot1x port-control mac-based
dot1x unauth-vlan 102
dot1x mac-auth-bypass
authentication order mab dot1x
voice vlan 200
exit

Lastly, I'd like to thank all of the contributors to this project. This software is wonderful!

**Comment by nicholaspier** [comment]
Additionally, I'd like to note that I forced authorization on uplinks:

switchport mode trunk
dot1x port-control force-authorized

I didn't include the SNMP configuration above but it's fairly standard and would be locked down further in a production environment:
snmp-server community "private" rw
snmp-server community "public" ro

**Comment by louismunro** [comment]
Issue assigned to lzammit. We'll work on it.

**Comment by julsemaan** [comment]
@lzammit whats up with that ?
