### ISSUE TITLE
Tenant ID is not set for CLI RADIUS requests

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6750]
**Describe the bug**
On a multi-tenant setup, it's not possible to catch CLI RADIUS requests using Tenant ID in connection profile.

**To Reproduce**
1. Create a tenant (id=2)
2. Create a switch in that tenant with CLI enabled
3. Create following connection profiles:
```ini
[catch_cli_login_tenant]
locale=
advanced_filter=
filter=connection_type:CLI-Access,tenant:2
filter_match_style=all

[catch_cli_login_no_tenant]
filter=connection_type:CLI-Access
advanced_filter=
locale=
```
4. Forge a CLI login request

=> First profile doesn't match, second profile matches

**Expected behavior**
First profile should match because both conditions are met

**Comment by jrouzierinverse** [comment]
Not longer neccessary
