### ISSUE TITLE
Reading winbind reply failed! (0xc0000001) - Using RADIUS through OpenLDAP Only to Cisco Meraki v2 | Packetfence v11.0

### ISSUE THREAD

**Issue by haikalshiddiq** [inverse-inc/packetfence#6754]
**Describe the bug**
OS : Debian 11 x64 Bullseye
Packetfence : using latest patch version 11
AppArmor : disabled

Reading winbind reply failed! (0xc0000001) when tried to running this command :
tail -f /usr/local/pf/logs/radius.log

**To Reproduce**
-> Following installation guide.
-> Configure Authentication Source to LDAP -> Done, Connection Successful, capture below
-> Configure Authentication Source to RADIUS -> Done with default configuration, capture below.
-> Configure Realm on NULL template -> Done with configured on Stripping tab with all enabled option and referring to LDAP name which successful added before.
-> Adding entry which mentioned on installation guide, 16.3. EAP Authentication against OpenLDAP
-> Also following this guide to adding value on packetfence-tunnel :
-ldap
update control {
    MS-CHAP-Use-NTLM-Auth := No
}
reference : https://blog.fijs.be/2020/04/30/packetfence-authenticate-using-mschapv2-with-openldap/

**Screenshots**
![image](https://user-images.githubusercontent.com/7146943/145254365-1d361c34-dd0a-472d-b5c1-54a9cdfb3fe7.png)
![image](https://user-images.githubusercontent.com/7146943/145254433-c0af3e31-63a9-4ba2-bf68-67edefb03845.png)
![image](https://user-images.githubusercontent.com/7146943/145254525-4debd93c-c4ee-4957-b5fc-c3cedc635867.png)
![image](https://user-images.githubusercontent.com/7146943/145254622-48afd572-cef0-4cba-9547-852ae00b7dbd.png)
![image](https://user-images.githubusercontent.com/7146943/145254655-ef988c59-9708-4d54-babe-4980450325a7.png)

Please reply since no clear on installation guide or network device configuration guide!

Thanks!

Regards,

Haikal

**Comment by julsemaan** [comment]
Use the mailing list for configuration related questions
