### ISSUE TITLE
New Authentication Source - Google Workspace LDAP

### ISSUE THREAD

**Issue by drthiruna** [inverse-inc/packetfence#6759]
**Describe the bug**
There is no option to upload the certificate and key in the page
I copied the text and pasted it in the box. Not accepted...
How to resolve it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38995197/145381893-7949d6c1-820e-41d0-a286-2f9e6785a71b.png)

**Expected behavior**
Not able to Google WS LDAPs

**Comment by nqb** [comment]
You need to upload certificates on PacketFence servers then you have to specify full path to these files as mentioned in the web admin: "Path to the client certificate .."
