### ISSUE TITLE
"Domain" configuration seems not to install distro specific files 

### ISSUE THREAD

**Issue by hopatzel** [inverse-inc/packetfence#676]
hi,

if one compares what the documentation says about what "SHOULD be configured in the Samba and Kerberos files" to "what the scripts do write into these files" (for debian) there is a large difference. (for a plain new pf 5.1 installation, i'm not talking about an upgrade!!)
In my oppinion it does not make sense to list erverything here in detail. Especially as I am unable to say, which entry is correct in the installation and has to be changed in the documentation or vice versa. Just do an installation from scratch and You'll see. 
I suggest the purpose of introducing the Domain Configuration in the gui was to make it unnecessary to edit the config files. This is still not achieved for debian. Documentation and Implementation seem to have some gaps or some kind of "out of sync"-ness. 

regards,
Holger

**Comment by louismunro** [comment]
I just did a clean debian 7 install.
I configured two domains against two different AD DC, one on windows the other on samba4.
The default test domain is pftest.org (no inverse). 

It works.
I can't replicate your problem.

Note that  the default domain indicated in files such as /chroot/$DOMAIN/etc/krb5.conf is not necessarily the one used to authenticate the user so whether it is inverse.anything is not actually relevant.

I would need to know more about what behaviour you are experiencing to help you.
You are not stating whether ntlm_auth succeeds or not and for what domain.

Actual configuration files and radius debugging output would be helpful.

**Comment by louismunro** [comment]
Tested on a fresh Ubuntu 12.04. 
Works just as well.

**Comment by hopatzel** [comment]
Hi Louis,

It seems for the moment, that I have to apologize.
after a longer debuging session with our AD-Administrator it seems to become clear, that there must be some sort of AD-related DNS Problem.
The error message says, it can’t find the DNS. But one can not see, that this message seems to come from the PDC himself…
I am unsure, why PF has a Problem to join, whilst normal Workstation don’t. Maybe it’s the DNS sef-registration?
I had to leave it as an exercise to our AD Admin for a Moment. 
So sorry for wasting your time.

Besides:
If the entries aren’t relevant, why are they still in the config files? (Or not at least commented out?)
It is so much easier for newbees to differentiate between relevant or not, if everything “irrelevant” either isn’t there or is commented out, thus making it obvious. ☺

I am working on finding any helpful hints in the pf-side logs. 
(which I failed so far, thus making my search so .. so ..so … arrghhhhh $&$%/&$@!! 
:-)

Regards
Holger

##

**Comment by louismunro** [comment]
Dynamic DNS updates are probably not allowed on your AD. 
That is not relevant to authentication and will not prevent you from using AD with 802.1x.

The entries are in the config files because there has to be a default even if you don't supply one explicitly.
