### ISSUE TITLE
TLS 1.0 and 1.1 are disabled in FreeRADIUS configuration starting from PacketFence v11

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6766]
**Describe the bug**
On a PF 11.1.0 (Debian 11 or EL8), I'm not able to connect (with default configuration) a supplicant which try to use TLS 1.0 to secure EAP communication. It works on PF 10.3.0 (CentOS 7).

According to [FreeRADIUS 3.0.22 changelog](https://github.com/FreeRADIUS/freeradius-server/blob/cd8cd3719193304241cea99d853d936ab70129c5/doc/ChangeLog#L109-L121), only TLS 1.2 is enabled by default (because we don't override default configuration)

On PF 11.1.0, we are using:
- FreeRADIUS 3.0.25
- OpenSSL 1.1.1k

**To Reproduce**
1. Forge a RADIUS request with following `eapol_test `configuration:
```
network={
phase1="tls_disable_tlsv1_0=0 tls_disable_tlsv1_1=1 tls_disable_tlsv1_2=1 tls_disable_tlsv1_3=1"
ssid="CORPORATE SSID"
key_mgmt=WPA-EAP
eap=TLS
identity="inverse"
ca_cert="/usr/local/pf/raddb/certs/ca.pem"
client_cert="/usr/local/pf/raddb/certs/client.pem"
private_key="/usr/local/pf/raddb/certs/client.key"
private_key_passwd="whatever"
eapol_flags=3
}
```
=> You got following message in `/usr/local/pf/logs/radius.log`: 

`Dec  6 09:45:04 pf auth[257735]: (49670) eap_peap: ERROR: (TLS) Alert write:fatal:protocol version
`

**Expected behavior**
I'm not sure what should be the expected behavior.

We don't publish anything regarding that change so I expected this to work without any changes. However, as mentioned in #5808, it's better to keep only TLS 1.2 enabled and we don't receive so much complaint about that change. 

I suggest to keep approach mentioned in #5808 (with GUI changes to adjust configuration when it's necessary) and to add documentation related to that changes (Upgrade guide).

**Additional context**
I got that issue on a macOS running Monterey.

**Comment by lzammit** [comment]
@nqb have you tried to allow TLS 1.0  and try to connect?

**Comment by nqb** [comment]
Yes: `tls_min_version = "1.0"` with `tls_max_version = 1.2` works as expected.
