### ISSUE TITLE
Potential Security oversight with "Password of the Day" Account

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6776]
**Describe the bug**
When creating the Authentication Source "Password Of The Day" a user account is created, and a password shared to those in the mailing list.  This account I believe is designed to allow for access using the "Username\Password" combination on the Captive Portal.  

However, we have noticed that this account is also able to logon to the Self Service Portal allowing a "Guest User" to potentially generate DPSK codes that potential grant above Guest privileges to the devices and change the password of the account.

This risk is intensified if a DPSK based Wi-Fi has been configured and a provisioner in place to redirect nonregistered devices to the Self Service Portal allowing to genuine mistakes by Guests in choosing the SSID or potential hackers a simple route to the corporate network.

**To Reproduce**
1. Generate "Password of the Day" Authentication source.
2. Navigate to Self Service Portal (directly or via redirection)
3. Logon using the Password of the Day authentication credentials.
4. Register Device or Change Password.

**Expected behavior**
Password of the day users should not be able to access anything other than the Captive Portal as the role defined within the Authentication Actions for the Guest Account.

1. login to Self Service Portal
2) Change password themselves (This should only be possible by cron job or Admin user)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium
 - Version 96.0.1054.53

**Comment by julsemaan** [comment]
backported up to maintenance/10.0

You can get the latest maintenance patches which include this fix using:
https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html#_upgrade_to_a_patch_version_x_y_patch
