### ISSUE TITLE
Cisco and Alcatel Switchs

### ISSUE THREAD

**Issue by Sletheren** [inverse-inc/packetfence#678]
Hello everyone!
In my university, we're trying to set up a NAC server! we have different switch vendors: ALCATE-LUCENT and Cisco
In the devices configuration guide, the ALCATEL isn't supported although it supports 802.1X and Some oher traps!
My questions are:
=> How can I configure the Alcatel-lucent 6850?
=> Do I need to configure each Cisco and Alcatel on my LAN (we have more than 7  switches)

And Thank you very much!

**Comment by extrafu** [comment]
Use the mailing list for questions like this, not a bug tracker.
