### ISSUE TITLE
Add pfcmd checkup item to warn when a cluster is configured but the DB host is `localhost`

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6789]
**Is your feature request related to a problem? Please describe.**
Add pfcmd checkup item to warn when a cluster is configured but the DB host is `localhost`

Because its bad you know...

**Comment by julsemaan** [comment]
Result of our discussion:
- Maintenance will have this in WARN
- Devel will have this in WARN until we can discuss it with the team and bring it up to FATAL for 11.2

**Comment by julsemaan** [comment]
Reopening so that we can discuss upgrading this to FATAL for the 11.2 release

**Comment by nqb** [comment]
The checkup should check `pf.conf` and `pfconfig.conf` because both files are updated by import mechanism.

**Comment by julsemaan** [comment]
> The checkup should check `pf.conf` and `pfconfig.conf` because both files are updated by import mechanism.

Agreed, the damage of `localhost` in pfconfig.conf is much more limited (almost none) since the writes are almost always made on one server but its still meaningful to add it though. We could perhaps push it further by warning that the host in pfconfig.conf and pf.conf are different since they shouldn't be in a normal use-case
