### ISSUE TITLE
Better Scheduling Options in the Authentication Sources POTD 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6797]
Currently when you create a POTD Authentication Source the only scheduling option is the number of days for the rotation.  The rotation time is set at the time of creation (or from what we see). 

**Describe the solution you'd like**
It would be nice to be able to schedule the days and the time the rotation happens in a simple GUI option.

Sun Mon Tues Wed Thurs Fri Sat
 X               X                X

Time: 01:00

**Comment by julsemaan** [comment]
You can define durations that are relative to the beginning of a period (ex: beginning of the day)

You define these in Configuration->Advanced Access Configuration->Access Duration

Example: 
![image](https://user-images.githubusercontent.com/3857942/147240400-4e6bbf01-0fec-49a0-b116-fb0f6b68d55e.png)

After defining it there you'll be able to use it in your POTD source

**Comment by PureOxygen-Dev** [comment]
@julsemaan Thanks for that explanation that makes sense sorry I missed that.  But that is not quite what I had in mind.

For us I would like to have the POTD reset at 1am on a Sunday evening.  I can create a schedule of 7 days + 1:00 which I believe will reset it at 1:00 every 7 days but then I would need to start it on the Sunday or Saturday correct?
