### ISSUE TITLE
OVA- ZEN fresh install - not working

### ISSUE THREAD

**Issue by tal221** [inverse-inc/packetfence#6799]
fresh install
latest version downloaded from website
nothing touched, only logged in with root
checking the apache
systemctl status apache
show its not working

checking the log file show
FATAL Unable To Connect database: Access Denied for user 'pf'@localhost at -e line 1

**Comment by julsemaan** [comment]
This bug tracker is only for confirmed bugs and development tracking

This looks like a user related issue, please post this on the mailing list
