### ISSUE TITLE
Update the aerohive integration documention

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#680]
Our doc regarding PF/Aerohive seems out of date.
Let's update it:

https://community.aerohive.com/aerohive/topics/aerohive-integration-with-packetfence

**Comment by jrouzierinverse** [comment]
Move to 5.5?

**Comment by louismunro** [comment]
Yes.

**Comment by julsemaan** [comment]
@whitx is working on Aerohive I think, so assigning this to him

**Comment by julsemaan** [comment]
It was reworked
