### ISSUE TITLE
web admin: SSL certificates menu stay in Edit mode after an edition

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6806]
**Describe the bug**
When you upload new SSL certificates on a PacketFence installation, web browser stay in Edit mode on SSL certificates menu which prevent you to see if everything is ok with new uploaded certificates.

Currently, there is two workaround:
- Click on "Cancel" button at bottom of the page
- Click on another menu (on the right) then click again on SSL certificates menu. If you try to click directly on SSL certificates, it doesn't work

**To Reproduce**
1. Go in SSL certificates menu
2. Edit HTTP certificates
3. Click on Save

=> You stay in Edit mode

**Expected behavior**
I expect to be able to leave Edit mode using a cross like we have in another Edit modes (for example on Authentication sources)

**Comment by fdurand** [comment]
If you hit the control key then it´s save and view.

**Comment by nqb** [comment]
Thanks for the tip @fdurand.

@satkunas, is it a bug for you ?

**Comment by satkunas** [comment]
@nqb not a bug. The default behaviour for all sections is to remain on the page after save. As Fabrice mentioned, the action key can be held when clicking save to force navigation after a successful API call.

**Comment by nqb** [comment]
@satkunas, it is expected to not have a cross on top right corner when editing certificates like we have for other items ?
