### ISSUE TITLE
Dependencie issue when trying to install PacketFence 11.0.0 on Debian 11

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6811]
Due to a change in our Debian repositories related to `netdata`, installation of PacketFence 11.0.0 is not working on Debian 11:

https://gitlab.com/inverse-inc/packetfence/-/pipelines/445221850/failures

**Comment by fdurand** [comment]
the repo has been fixed and i did a fresh install.
just wait for the pipeline to confirm.
