### ISSUE TITLE
Fingerbank combinations page is missing the upstream/local buttons and list is empty

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/packetfence#683]
See attached screenshot
![image](https://cloud.githubusercontent.com/assets/1625376/8127256/b5a49fdc-10f5-11e5-8d72-5e1806d5c0f4.png)

I can access the combinations by adding /Local/list or /Upstream/list to the url manually.

Packetfence 5.1 on Ubuntu 12.04 (fresh install) and Centos 6

Logs:

```
==> httpd.admin.log <==
Jun 12 11:35:24 httpd.admin(3218) ERROR: Searching for 'Combination' entries in schema(s)     returned an empty set (pfappserver::Base::Model::Fingerbank::readAll)

==> httpd.admin.access <==
172.16.200.160 - - [12/Jun/2015:11:35:24 +0200] "GET /config/fingerbank/combination?_=1434101723374 HTTP/1.1" 200 5181 "https://172.16.1.165:1443/admin/configuration" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
```

Local DB is empty , Upstream DB was correctly downloaded and contains all current combinations.

**Comment by erSitzt** [comment]
Hmm i just noticed the buttons were removed in one of the last commits.
But the problem with the empty list remains, only Local Combination are listed.

Is this expected behavior ? 
No possibility to view/seach/clone Upstream combinations wihtin Packetfence ?

**Comment by dwlfrth** [comment]
We evaluate that there is no reason for listing the actual "upstream" Combinations... The only need for the "Combinations" option to be listed is really just to create some local one for custom purposes.

**Comment by erSitzt** [comment]
Ok.
