### ISSUE TITLE
[11.1.0] PacketFence locks several AD accounts when multiple login failures

### ISSUE THREAD

**Issue by mvalois** [inverse-inc/packetfence#6831]
**Describe the bug**
When an user fails to authenticate against the admin portal, PacketFence orders the AD to lock the account and serveral other accounts also get locked.

**To Reproduce**
1. have local PF accounts with the same name as in the AD
2. fail to authenticate multiple times against the admin portal
3. observe that account being locked in the AD
4. observe other accounts (those having a local account) being locked in the AD

**Expected behavior**
At most one account being locked due to bruteforce prevention, but not several.

**Additional context**
For tests purposes, admin portal authentication using AD is not enabled yet. For now, a fake AD group is filled for admin rules in the auth source (then this rule never applies).

**Comment by julsemaan** [comment]
PF doesn't order accounts to be locked in the AD so this must be a policy in your AD

I suggest reaching out to the PacketFence mailing list to discuss this matter and see if its a bug in PF or just a configuration of your AD
