### ISSUE TITLE
[11.1.0] Fail to authenticate when unregistering datetime is after January 19th 2038

### ISSUE THREAD

**Issue by mvalois** [inverse-inc/packetfence#6832]
**Describe the bug**
In user accounts, in actions tab, when the end of the registration window is after january 19th 2038 (Y2038 bug), password validation fails.

**To Reproduce**
1. Go to users > one_user > actions
2. Set end window to after january 19th 2038
3. Try to authenticate against admin portal with that account
4. Observe failure, also in logs : ```Password validation failed for petitbonum: password has expired```

**Expected behavior**
More explicit error, successful authentication or not being able to set a date after that Y2038 one.

**Comment by nqb** [comment]
Duplicate of #5937
