### ISSUE TITLE
HPE OfficeConnect Switch 1920S configuration

### ISSUE THREAD

**Issue by gbartley5385** [inverse-inc/packetfence#6837]
Question if anyone has configured an hpe office connect 1920s switch to work with Packetfence and if so do you have a guide that I could follow. Alternately is there a current switch configuration that could be used? These switches do not have a command line interface unfortunately. 

Thank you for reading and assisting.

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
