### ISSUE TITLE
web admin: update content of a HTML file created through web admin doesn't work

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6840]
**Describe the bug**
If you create an HTML file on a connection profile using web admin, you can't modify this file after creation.

**To Reproduce**
1. Create a new connection profile
2. Create a new file under `emails` directory using `New file` button
   * Define a name
   * Define a content

=> Your file is created under `/usr/local/pf/html/captive-portal/profile-templates/PROFILE_NAME/emails/FILENAME.html` with correct content

3. Try to modify content of your file

=> It's possible and you don't have any error
=> Each time you re-open your file, your changes have been lost

**Expected behavior**
- Error reported by frontend if not possible
- Edit a file is possible

**Additional context**
At the moment, API returns an error (visible in web browser console):

```
{
	"errors": [],
	"message": "Error writing to the 'emails/myfile.html'",
	"status": 422
}
```

**Comment by PureOxygen-Dev** [comment]
Hi Team 

This appears to be the same as the bug I reported #6800 

Kind Regards

Simon

**Comment by jrouzierinverse** [comment]
Is this for redhat or debian?

**Comment by nqb** [comment]
It's on Debian.
