### ISSUE TITLE
web admin: creating a node with dashes generate error messages

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6842]
**Describe the bug**
If you create a node with dashes (like AA-BB-CC-DD-EE-FF), node is created but web admin display errors until you refresh your cache.

**To Reproduce**
1. Create node `AA-BB-CC-DD-EE-FF`

=> Node is created with dashes replaced by `:`

2. Click on node 

You got an error related to node `aa:bb:cc:dd:ee:ff` not available each time you click on it in Nodes menu

3. Clean your browser cache

=> Node is available

**Expected behavior**
Nodes is created and there is no issue to view it.

**Additional context**
I was not able to test using a RADIUS request but according to a report it looks like it's possible to have node created with dashes in DB. I will open another issue if that is the case.

**Comment by satkunas** [comment]
@jrouzierinverse the backend is rewriting `mac` from `AA-BB-CC-DD-EE-FF` to `AA:BB:CC:DD:EE:FF` w/ at least the `POST` and `PATCH` methods. 

The `POST` causes a desync between the front and backends.

The `PATCH` causes a foreign key constraint error when the same mac already exists with alternative separators.

Are we now rewriting all macs to strictly use the `:` separator? If so, the validation on the front-end should be updated to reflect this. How do we handle older records still using an alternative separator?

**Comment by julsemaan** [comment]
We've always rewritten the dashes to colons since the DB exclusively stores the MAC addresses in colon delimited

If it wasn't rewritten at some point, it was a bug

**Comment by satkunas** [comment]
@nqb please retest with deb60d203934e302b121cb5680414db93b3ec84b

**Comment by nqb** [comment]
@satkunas, issue still presents. I noticed that I now have same error directly at creation of node.

**Comment by satkunas** [comment]
@nqb my previous patch caused the regression in #6894 and also addresses this issue. Please retest again.

**Comment by nqb** [comment]
Works as expected.
