### ISSUE TITLE
interfaces 'type' should no longer be separated between pf.conf and networks.conf

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#685]
That just make parsing and flow more complicated than it should be...

**Comment by dwlfrth** [comment]
Can those of you who have an opinion / concern on the subject comment ?
I'd like to get different inputs.

**Comment by julsemaan** [comment]
Well seems @dwlfrth never got his input

Closing this

**Comment by dwlfrth** [comment]
https://www.youtube.com/watch?v=7-0lV5qs1Qw
