### ISSUE TITLE
Past unreg date can provide additional 1 year access duration

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6862]
**Describe the bug**
If you use an authentication rule which assign a past unregistration date (for example: 2021-12-31) and your server is on time, PacketFence will assign an unregistration date of 2022-12-31 (+1 year).

This behavior is undocumented and I don't think users expect this behavior.

**To Reproduce**
This behavior can be easily replicate using Perl unit tests. I adjusted tests: https://github.com/inverse-inc/packetfence/commit/f429e40098bc5e942cc83a52dca20d8f384aa27c. Before my commit tests were failing with:

```
#   Failed test 'Set unreg date test'
#   at unittest/authentication.t line 152.
#          got: '2023-02-02'
#     expected: '2022-02-02'
# Looks like you failed 1 test of 58.

```
**Expected behavior**
Invalid unregistration date should result in failure.

**Additional context**
Line in logs:

`Jan 3 09:19:45 packetfence1 packetfence_httpd.portal: httpd.portal(8866) WARN: [mac:xx:xx:xx:xx:xx:xx] The year was past, null or undefined. We used current year (pf::config::dynamic_unreg_date)`

**Comment by julsemaan** [comment]
I don't think we should change this behavior since some customers rely on this behavior.

What we should do though is in the admin interface display a clear warning below the unregdate action that describes the behavior when the unregdate is in the past.

**Comment by jrouzierinverse** [comment]
We would need to update that test. I will do that.
Also maybe add a feature to turn off the dynamic reg date.

**Comment by nqb** [comment]
> I don't think we should change this behavior since some customers rely on this behavior.

@julsemaan, I can be wrong but I think it's possible to do the same using relative access durations which reflect exact behavior.
For me, even with a warning, it's still counter-intuitive to have a rule which assigned an unregistration date in the past.

@jrouzierinverse, could you cherry-pick changes to tests on `maintenance/11.0` and `maintenance/11.1` branches ?

**Comment by jrouzierinverse** [comment]
done

**Comment by julsemaan** [comment]
> > I don't think we should change this behavior since some customers rely on this behavior.
> 
> @julsemaan, I can be wrong but I think it's possible to do the same using relative access durations which reflect exact behavior. For me, even with a warning, it's still counter-intuitive to have a rule which assigned an unregistration date in the past.

If we deprecate this we will need an automated script to migrate these to dynamic access durations though. 

And I don't think dynamic access durations can pin to a date in a year (ex: August 1st of the current year if before August 1st, August 1st of next year if after August 1st). I tried to play around with the available settings in the admin and couldn't find a way to get it to work.

Also, we'll have to see what the behavior is when you set a date in the past? Do we want to just deny access?

With all these considerations, this cannot be a +1 since whatever we pick other than the warning is a change of behavior and cannot go in the maintenance.

**Comment by jrouzierinverse** [comment]
Should we close this?

**Comment by nqb** [comment]
@jrouzierinverse, I don't think so. We need at least to document that behavior with a warning in the admin.

**Comment by extrafu** [comment]
@satkunas Implement a warning in the admin.
