### ISSUE TITLE
Can't connect to fingerbank as PF needs to trust CA cert from our MITM/SSL inspector.

### ISSUE THREAD

**Issue by hendero1** [inverse-inc/packetfence#6876]
**Is your feature request related to a problem? Please describe.**
Hello.  I'm currently setting up packetfence & it sits behind a MITM/SSL inspector on our network which rewrites all SSL requests.  For most devices, we install the new root CA (import) into clients & that solves the issue.  After looking through the PKI docs I don't see a way to do this.  Right now I can't connect to fingerbank as I get:

"api_key:  Error while testing API key:
Error was 500: Can't connect to api.fingerbank.org:443 (certificate veirfy failed)
config/fingerbank_setting/upstream"

**Describe the solution you'd like**
I'd like to add a trusted CA by importing CRT.  It's possible I missed this as I'm new to Packetfence.  I've tried doing this at the OS level but it doesn't seem to work.  I've put the custom CA cert in /usr/local/share/ca-certificates and run update-ca-certificates as root, (as per https://grumpytechie.net/2020/02/25/adding-custom-root-ca-certificates-to-debian/) but this didn't fix the issue.

**Describe alternatives you've considered**
I can request a bypass so the SSL cert doesn't get re-written by the MITM/SSL inspector appliance but I'd rather just have this work by trusting the CA locally inside packetfence.

**Additional context**
![image](https://user-images.githubusercontent.com/83726067/153494181-906dc127-b5cf-4d99-85dd-6a56932b1c38.png)

**Comment by julsemaan** [comment]
You can't use Fingerbank with a MITM SSL inspection tool since the Fingerbank collector shipped with PacketFence uses certificate pinning.

You either need to allow-list this traffic to not be SSL inspected or not use Fingerbank with PacketFence (clear out the API key and save)
