### ISSUE TITLE
webadmin: static route validation is wrong

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6878]
**Describe the bug**
When you want to add a static route in Configuration -> Network configuration -> Network settings -> Static routes, syntax allowed by frontend is: `10.0.0.0/24 via 10.0.0.1 dev eth1` but it doesn't match syntax allowed by keepalived.

For example, it should be possible to add something like: `10.0.0.0/24 dev eth1`.  

As mentioned in "Static routes/addresses/rules" in [keepalived documentation](https://keepalived.org/manpage.html):

>The  syntax  for  rules  and  routes is the same as for ip rule add/ip route add (except shortened option names are not  supported  due to  ambiguities) 

**To Reproduce**
1. Try to add a static rule like: `10.0.0.0/24 dev eth1`

=> frontend reports "Invalid static route"

**Expected behavior**
Static route allowed

**Additional context**
I can be wrong but I think it will make more sense to validate if a route is correct on the backend.

**Comment by nqb** [comment]
@satkunas, on my beloved Firefox, I find text "10.0.0.0/24 dev eth1 or 10.0.0.0/24 via 10.0.0.1 dev eth1" smaller compared to screenshot you sent me yesterday.

What I have:
![image](https://user-images.githubusercontent.com/10830260/154432704-0d2f4029-1d70-46da-b8aa-a3ad77c6faf7.png)

If we can do something, let me know. Otherwise, we can close this issue.

**Comment by satkunas** [comment]
@nqb the line-height looks fine on FF 97.0.

![Screen Shot 2022-02-17 at 3 07 52 PM](https://user-images.githubusercontent.com/3904468/154562621-075dca69-0991-4554-806f-08c58351ab06.jpg)

**Comment by drthiruna** [comment]
The same issue is still present in the v13.0. 
Not able to enter any static routing as explained in the issue
https://github.com/inverse-inc/packetfence/issues/6878
