### ISSUE TITLE
Allowed/Banned domains fields corrupted after refreshing the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6882]
**Describe the bug**
When you edit a sponsor source and setup allowed/banned domains and refresh the page, the field has the array in it instead of the separated values

**To Reproduce**
1. Edit the sponsor source
2. Add 2 domains in 'Allowed domains' and 'Banned domains'
![image](https://user-images.githubusercontent.com/3857942/153631121-1c4ec8b5-b326-43ac-8a6f-8242f62a1358.png)
3. Save the source
4. Refresh the page
![image](https://user-images.githubusercontent.com/3857942/153631190-ae8eceba-68b5-4a17-8059-0ff58a455437.png)

**Comment by julsemaan** [comment]
@satkunas, please verify if this applies to previous versions too so we can backport it in the maintenance if necessary

**Comment by satkunas** [comment]
@julsemaan item-per-line differs than comma-separated-values. The backend is re-casting these items-per-line as an array. The front-end isn't expecting this.

I can either :
a) put a validator that expects CSV, but this can be tricky mixed with domain names.
b) turn the form element into a sortable array with no regex on the individual items, then expand/compress to/from an array/csv with the API endpoints until @jrouzierinverse can implements arrays the standard way.

**Comment by satkunas** [comment]
`maintenance/11.1` and `maintenance/11.0` are both affected

**Comment by julsemaan** [comment]
> @julsemaan item-per-line differs than comma-separated-values. The backend is re-casting these items-per-line as an array. The front-end isn't expecting this.
> 
> I can either : a) put a validator that expects CSV, but this can be tricky mixed with domain names. b) turn the form element into a sortable array with no regex on the individual items, then expand/compress to/from an array/csv with the API endpoints until @jrouzierinverse can implements arrays the standard way.

There shouldn't be domain names containing a comma since its not allowed as a character so that would be acceptable but the best fix would be to keep it as a line-by-line list since that's definitely cleaner

**Comment by julsemaan** [comment]
Iterating on my comment above, the same feature in the email source allows for one domain by line so in order to be consistent, the same thing should be allowed for sponsor sources

**Comment by julsemaan** [comment]
Since maintenance/11.0 and maintenance/11.1 are both affected by this bug, @satkunas, can you confirm if we can backport #6886 safely to both maintenance branches?

**Comment by satkunas** [comment]
@julsemaan yes, I tested e3a0703e0a5b007754736c69a494fc5b5ed295c0, cd895ff3dc155bb75c6ff65c0fb2b93a32aaccc0 and 0f6aad179e59612659a57cb710ec7ff0aee89e0a with both maintenance/11.0 and maintenance/11.1 without issue

**Comment by julsemaan** [comment]
cherry-picked to maintenance/11.0 and maintenance/11.1
