### ISSUE TITLE
Can't move cursor in filter engine 'time period within' value

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6883]
**Describe the bug**
The 'time period within' value will usually contain large values and its impossible to use the mouse to either select or move into that field. Moving using the keyboard left/right works

**To Reproduce**
1. Create a filter engine with a condition 'time period within' with value 'wd {Mon Tue Wed Thu Fri} hr {9am-11am}, wd {Mon Tue Wed Thu Fri} hr {2pm-4am}'
2. Try to select a part of this value with your mouse

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 96.0.3

**Comment by satkunas** [comment]
This is known bug with Firefox due to the input being within a draggable element.

https://bugzilla.mozilla.org/show_bug.cgi?id=1189486

I am examining possible workarounds with a minimal impact.

**Comment by satkunas** [comment]
Unable to fix.  Ignoring

**Comment by satkunas** [comment]
@julsemaan PR posted, please have a look to see how well the conditions behave with your awesome firefox.

**Comment by julsemaan** [comment]
happy with the fix!
