### ISSUE TITLE
security_event_maintenance closes opened security events with release_date 0000-00-00

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6885]
**Describe the bug**
security_event_maintenance closes opened security events with release_date 0000-00-00

This means that when a security event opens and the device is isolated, its being closed roughly a minute after and the device regains access to the network even if the security event doesn't allow self-enabling of access

**To Reproduce**
1. Perform test case PF-45 (Suricata violations) in testlink

**Expected behavior**
Device stays isolated

**Comment by julsemaan** [comment]
We'll have to determine if that happens on older versions of PF too since this allows unauthorized access to devices that are being isolated from the network

**Comment by julsemaan** [comment]
The problem looks to be a change of behavior with 0 dates since that statement shouldn't be returning any rows:
```
MariaDB [pf]> SELECT `id`, `mac`, `security_event_id`, `notes`, `status`, `release_date` FROM `security_event` WHERE ( ( ( ( `status` = 'open' OR `status` = 'delayed' ) AND `release_date` <= NOW() AND (release_date, id) > ('0000-00-00 00:00:00', 17) ) AND `security_event`.`tenant_id` = 1 ) ) ORDER BY `release_date`, `id`;
+----+-------------------+-------------------+-------+--------+---------------------+
| id | mac               | security_event_id | notes | status | release_date        |
+----+-------------------+-------------------+-------+--------+---------------------+
| 18 | ac:bc:32:79:82:43 |           3000010 |       | open   | 0000-00-00 00:00:00 |
+----+-------------------+-------------------+-------+--------+---------------------+
1 row in set (0.000 sec)
```

**Comment by julsemaan** [comment]
The way the statement is constructed actually breaks the logic of the query, splitting the ID filtering from the release date works as expected:

```
MariaDB [pf]> SELECT `id`, `mac`, `security_event_id`, `notes`, `status`, `release_date` FROM `security_event` WHERE ( ( ( ( `status` = 'open' OR `status` = 'delayed' ) AND `release_date` <= NOW() AND (release_date, id) > ('0000-00-00 00:00:00', 17) ) AND `security_event`.`tenant_id` = 1 ) ) ORDER BY `release_date`, `id`;
+----+-------------------+-------------------+-------+--------+---------------------+
| id | mac               | security_event_id | notes | status | release_date        |
+----+-------------------+-------------------+-------+--------+---------------------+
| 19 | ac:bc:32:79:82:43 |           3000010 |       | open   | 0000-00-00 00:00:00 |
+----+-------------------+-------------------+-------+--------+---------------------+
1 row in set (0.000 sec)

MariaDB [pf]> SELECT `id`, `mac`, `security_event_id`, `notes`, `status`, `release_date` FROM `security_event` WHERE ( ( ( ( `status` = 'open' OR `status` = 'delayed' ) AND `release_date` <= NOW() AND release_date > '0000-00-00 00:00:00' AND id > 17 ) AND `security_event`.`tenant_id` = 1 ) ) ORDER BY `release_date`, `id`;
Empty set (0.000 sec)
```

**Comment by julsemaan** [comment]
The regression was introduced here: https://github.com/inverse-inc/packetfence/commit/8d8b81eefa819483a37626707dc3b7e5ca6f44ae

So its unreleased but the security_event_maintenance test suite has failed to ensure that this job works as it should so we'll need @jrouzierinverse to look into adding a test case to validate events with a zero date will not be touched in that job

**Comment by julsemaan** [comment]
I pushed a commit to fix it, @jrouzierinverse can you double check that it still applies the logic that is expected when you rewrote that code

Also, we'll need to have proper testing of this use case either in venom or in the unit tests since this failed to be detected by our automated test suites

**Comment by nqb** [comment]
I have noticed that bug too. I checked our integration tests. They will need a slight adjustment to catch this kind of error.
IMHO, on this [test](https://github.com/inverse-inc/packetfence/blob/f363bfc20d57ee2878be4b37bd41cd3d5ba05f3d/t/venom/test_suites/inline/l2/25_trigger_violation.yml), we should wait more time to check if device is still in ipset isolation.

**Comment by nqb** [comment]
@JeGoi, could you adjust tests for that ?

**Comment by julsemaan** [comment]
@jrouzierinverse, please note there are now 2 commits to review for my fix:
[6e6817f](https://github.com/inverse-inc/packetfence/commit/6e6817fea99c3390a3a394896b30156a6b25ec2f)
[ca9e126](https://github.com/inverse-inc/packetfence/commit/ca9e126e6ec342dbe97fdf3c402db35ec6e15536)

**Comment by JeGoi** [comment]
> @JeGoi, could you adjust tests for that ?

@nqb Done. 1m and 10s

**Comment by jrouzierinverse** [comment]
@julsemaan I added both a test and reverted your commits since they undid the intent of the original rewrite.

**Comment by jrouzierinverse** [comment]
This can be closed now

**Comment by julsemaan** [comment]
So can this be closed?

**Comment by jrouzierinverse** [comment]
I reopened because I was unsure if you wanted to retest

**Comment by julsemaan** [comment]
> I reopened because I was unsure if you wanted to retest

I'll give it a try in my next series of tests and close

**Comment by julsemaan** [comment]
Works as expected, closing
