### ISSUE TITLE
Lack of feedback after saving connection profile template

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6887]
**Describe the bug**
When you save a connection profile HTML template, the admin doesn't provide clear feedback that it was saved.

There is a notification that is was saved but its behind the 
**To Reproduce**
1. Go in a connection profile
2. Edit layout.html
3. Change something
4. Save it

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/153925709-d15f4c1a-7750-4ea4-8f5a-b7c6ae77b57b.png)

**Expected behavior**
The notification should be clearly visible or we should have a success message close to the save button

**Comment by satkunas** [comment]
Notification moved **above** the modal to fix visibility.

**Comment by satkunas** [comment]
Move causes an artifact at the bottom of the page. More work is needed.

**Comment by extrafu** [comment]
More cowbell, always https://vimeo.com/257364428
