### ISSUE TITLE
Certificate generation on the portal doesn't validate the email format

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6888]
**Describe the bug**
When doing EAP-TLS provisioning on the portal via the PF PKI, you're asked for an email address but its not being validated

**To Reproduce**
1. Configure the PF PKI for cert onboarding as described in our doc
2. Go through the portal until the onboarding step
3. In the email field, write `zammitaunegrossebanane`
4. Submit and it goes through

**Expected behavior**
Invalid email shouldn't go through

**Comment by fdurand** [comment]
Duplicate to #5948
