### ISSUE TITLE
Online/offline status isn't accurate after being offline 5 minutes

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6892]
**Describe the bug**
When a node is online, the online status works perfectly. When it goes offline, the offline status is lost after 5 minutes because the records move to bandwidth_accounting_history so the node is marked 'unknown'. This used to happen after 24 hours previously.

We could:
* Adjust the admin interface query to look into bandwidth_accounting_history (could lead to a heavy unindexed query)
* A single bucket could also be left in the bandwidth_accounting table to track the online/offline for that session (eventually being moved after 24 hours like it was previously).
* 3D print the online/offline with the help of @lzammit

**Comment by julsemaan** [comment]
I assume the backported pfacct fixes in 11.1 will need adjustments too

**Comment by jrouzierinverse** [comment]
I would suggest a simpler solution and go back to a one/two hour window we had before.
Since the issue of cleaning had to do with the use of temp tables not with that 5-minute window.

**Comment by julsemaan** [comment]
As long as a device is only considered 'unknown' after being offline for 24 hours like before, I'm fine with that solution
