### ISSUE TITLE
webadmin: bell is missing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6893]
**Describe the bug**
On webadmin, bell which centralizes notifications sent by frontend is missing.

**To Reproduce**
1. Connect to webadmin

=> No bell anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/10830260/154244878-06233948-707e-4903-8c30-9a34ec3bbabe.png)

**Expected behavior**
Bell is present next to tools

**Additional context**
I'm testing on latest packages available on `devel` on Debian 11 with Firefox (fresh install from this morning)

**Comment by nqb** [comment]
I find the bell at the bottom of the page:

![image](https://user-images.githubusercontent.com/10830260/154249379-c967362e-95ff-41d1-91a0-34b92436d564.png)

**Comment by cgx** [comment]
You see a bug, I see an easter egg. Thanks @satkunas 🐰

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/issues/6887
