### ISSUE TITLE
Advanced Filters are populating when editing any filter above 25

### ISSUE THREAD

**Issue by cdcrawford** [inverse-inc/packetfence#6899]
**Describe the bug**
When I create a Radius Filter, refresh the browser, and then go back in to edit the same filter, there nothing populated in the fields. But, if I go and edit an existing filter, say 5th in the list. Everything is populated. When I go and edit another filter, say 28th in the list, nothing is populated. 

The data is present in on the CLI, and in the radius_filters.conf file. But, is not populated on the web interface.

**To Reproduce**
Steps to reproduce the behavior 1 (unable to edit existing radius filter, above 25th in the list)
1. Create Radius Filters to 25 (as long as it wraps to page 2)
2. Refresh the browser
3. Click on any filter. 
4. Issue reproduced, filters data is missing.

**Screenshots**
Page 2, see 46: 
![image](https://user-images.githubusercontent.com/3090648/154336151-52fa3698-d999-4f3b-a3e0-061929e0e99a.png)
Editing Filter 46:
![image](https://user-images.githubusercontent.com/3090648/154336270-9fa3b5b6-b509-4d0d-866e-6bf637d6c655.png)

**Expected behavior**
The radius filter to populate from the API correctly and display the contents correctly.

**Expected behavior Screen shots*
![image](https://user-images.githubusercontent.com/3090648/154336012-0231895c-204d-4fd2-8021-c035e10930af.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 98.0.1108.50

**Additional context**
Configuration File Data:
[xx-VLAN 46]
answer.2=reply:Tunnel-Medium-Type = 6
scopes=returnRadiusAccessAccept
answer.0=reply:Tunnel-Private-Group-Id = 46
answer.1=reply:Tunnel-Type = 13
description=**DESCRIPTION!!!**
status=enabled
merge_answer=no
condition=mac =~ ".*" && VLAN == "46"
answer.3=reply:Egress-VLANID = 0x3200002E

**Comment by satkunas** [comment]
@cdcrawford The space in the filter engine `Name` is what's breaking the forms. You'll need top manually edit `/usr/loca/pf/conf/radius_filters.conf` and remove the spaces from all the filters.

`[xx-VLAN 46]` -> `[xx-VLAN-46]`

Then do a `/usr/loca/pf/bin/pfcmd configreload hard`, and reload the page.

More strict validation has been added to the `Name` to prevent this from happening again.
