### ISSUE TITLE
webadmin: not possible to create a routed network with type=other

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6903]
**Describe the bug**
In order to test multi-tenant management with `pfdhcplistener` and `pfsso`, I need to create a routed network with `type=other`.

It's not possible at the moment because web admin reports a lot of errors which are certainly related to #6255 when I asked to restrict fields for this kind of network.

**To Reproduce**
1. Create a routed network with type=other

**Screenshots**
![image](https://user-images.githubusercontent.com/10830260/154446632-6a5571cd-e2a2-4997-aab7-ed0e0f2d28f4.png)

**Expected behavior**
Routed network is created with only:
  - type
  - subnet
  - netmask
  - tenant

**Additional context**
API returned a 422 when frontend is sending following payload:

```
{
	"algorithm": 1,
	"coa": "disabled",
	"description": "prod",
	"dhcp_default_lease_time": null,
	"dhcp_end": null,
	"dhcp_max_lease_time": null,
	"dhcp_start": null,
	"dhcpd": "enabled",
	"dns": null,
	"fake_mac_enabled": 0,
	"gateway": null,
	"id": "192.168.121.0",
	"ip_assigned": null,
	"ip_reserved": null,
	"isClone": false,
	"isNew": true,
	"nat_dns": 1,
	"nat_enabled": 1,
	"netflow_accounting_enabled": "disabled",
	"netmask": "255.255.255.0",
	"network": null,
	"next_hop": null,
	"pool_backend": "memory",
	"portal_fqdn": null,
	"tenant_id": 2,
	"type": "other"
}
```
I'm assigning @jrouzierinverse because it seems more a backend issue.

**Comment by jrouzierinverse** [comment]
The problem is when dhcpd is enabled
The following fields are required dhcp_default_lease_time, dns,gateway, dhcp_start, dhcp_end, dhcp_max_lease_time
