### ISSUE TITLE
'Sponsor access durations' are lost after reloading the page

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6910]
**Describe the bug**
'Sponsor access durations' are lost after reloading the page

**To Reproduce**
1. Create an AD authentication source
2. Add an administration rule like the following:
![image](https://user-images.githubusercontent.com/3857942/154990699-d1ef50dd-fd16-45ae-9010-a9d1e7fa3a60.png)
3. Save
4. Reload the page
5. There is an error that says 'Duration(s) required' and the durations have disapeared
![image](https://user-images.githubusercontent.com/3857942/154990845-2e428700-04a1-44ff-8a9f-b23d1588bdc0.png)

**Additional context**

I've checked and the durations are in authentication.conf and returned in the API response:
![image](https://user-images.githubusercontent.com/3857942/154990970-45cbf300-e9ce-455f-b5cd-ff533185b5f6.png)

**Comment by satkunas** [comment]
@jrouzierinverse will adjust to send Array from backend
