### ISSUE TITLE
Cluster setup fails after configuring the cluster.conf file and reloading

### ISSUE THREAD

**Issue by nathanbloemendaal78** [inverse-inc/packetfence#6922]
**Describe the bug**
I am setting up a 3 node cluster based on the ZEN, version 11.2. I followed the Clustering Guide to the letter, but I get stuck after creating the cluster configuration in cluster.conf (section 3.4.2 of the guide). When I try to perform the commands

/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/pfcmd checkup

I  get a lot of obvious errors related to the database being unavailable. But also:

Compilation failed in require at /usr/local/pf/lib/pf/client.pm line 23.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/client.pm line 23.
Compilation failed in require at /usr/local/pf/lib/pf/node.pm line 33.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/node.pm line 33.
Compilation failed in require at /usr/local/pf/lib/pf/action.pm line 25.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/action.pm line 25.
Compilation failed in require at /usr/local/pf/lib/pf/class.pm line 32.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/class.pm line 32.
Compilation failed in require at /usr/local/pf/lib/pf/security_event_config.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/security_event_config.pm line 21.
Compilation failed in require at /usr/local/pf/lib/pf/config.pm line 869.

(after /usr/local/pf/bin/pfcmd configreload hard) and

Compilation failed in require at /usr/local/pf/lib/pf/services/manager/haproxy_db.pm line 22.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/haproxy_db.pm line 22.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::radsniff : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/radsniff.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/radsniff.pm line 21.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::httpd_portal : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/config/util.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/config/util.pm line 21.
Compilation failed in require at /usr/local/pf/lib/pf/authentication.pm line 20.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/authentication.pm line 20.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd_portal.pm line 20.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/httpd_portal.pm line 20.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pfdhcp : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pfdhcp.pm line 17.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pfdhcp.pm line 17.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::mysql_probe : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/mysql_probe.pm line 17.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/mysql_probe.pm line 17.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pf : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pf.pm line 24.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pf.pm line 24.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pffilter : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pffilter.pm line 18.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pffilter.pm line 18.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::snmptrapd : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/snmptrapd.pm line 17.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/snmptrapd.pm line 17.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::haproxy_admin : Attempt to reload pf/authentication.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/haproxy_admin.pm line 19.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/haproxy_admin.pm line 19.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::radiusd : Attempt to reload pf/authentication.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/radiusd.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/radiusd.pm line 21.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::tc : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/client.pm line 23.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/client.pm line 23.
Compilation failed in require at /usr/local/pf/lib/pf/node.pm line 33.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/node.pm line 33.
Compilation failed in require at /usr/local/pf/lib/pf/action.pm line 25.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/action.pm line 25.
Compilation failed in require at /usr/local/pf/lib/pf/class.pm line 32.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/class.pm line 32.
Compilation failed in require at /usr/local/pf/lib/pf/security_event_config.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/security_event_config.pm line 21.
Compilation failed in require at /usr/local/pf/lib/pf/security_event.pm line 31.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/security_event.pm line 31.
Compilation failed in require at /usr/local/pf/lib/pf/iptables.pm line 65.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/iptables.pm line 65.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/tc.pm line 30.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::netdata : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/netdata.pm line 24.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/netdata.pm line 24.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pfdns : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pfdns.pm line 20.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pfdns.pm line 20.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::galera_autofix : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/galera_autofix.pm line 16.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/galera_autofix.pm line 16.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pfsso : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pfsso.pm line 18.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pfsso.pm line 18.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::httpd_webservices : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd_webservices.pm line 23.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/httpd_webservices.pm line 23.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pfipset : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pfipset.pm line 17.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pfipset.pm line 17.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::httpd_proxy : Attempt to reload pf/config/util.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd.pm line 33.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/httpd.pm line 33.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd_proxy.pm line 21.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::httpd_aaa : Attempt to reload pf/services/manager/httpd_webservices.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd_aaa.pm line 23.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::keepalived : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/keepalived.pm line 38.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/keepalived.pm line 38.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::httpd_collector : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/httpd_collector.pm line 24.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/httpd_collector.pm line 24.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::api_frontend : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/api_frontend.pm line 18.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/api_frontend.pm line 18.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::iptables : Attempt to reload pf/iptables.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/iptables.pm line 21.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::haproxy_portal : Attempt to reload pf/authentication.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/haproxy_portal.pm line 19.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/haproxy_portal.pm line 19.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
Couldn't require pf::services::manager::pfcron : Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/services/manager/pfcron.pm line 17.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/services/manager/pfcron.pm line 17.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314.
 at /usr/local/pf/lib_perl/lib/perl5/Module/Pluggable.pm line 32.
module pf::cmd::pf::checkup cannot be loaded
Attempt to reload pf/cluster.pm aborted.
Compilation failed in require at /usr/local/pf/lib/pf/freeradius.pm line 51.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/freeradius.pm line 51.
Compilation failed in require at /usr/local/pf/lib/pf/SwitchFactory.pm line 22.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/SwitchFactory.pm line 22.
Compilation failed in require at /usr/local/pf/lib/pf/validation/profile_filters.pm line 22.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/validation/profile_filters.pm line 22.
Compilation failed in require at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 21.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/pfcmd/checkup.pm line 21.
Compilation failed in require at /usr/local/pf/lib/pf/cmd/pf/checkup.pm line 23.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/cmd/pf/checkup.pm line 23.
Compilation failed in require at /usr/share/perl/5.32/Module/Load.pm line 77.
Can't locate pf/cmd/pf/checkup in @INC (@INC contains: /usr/local/pf/lib /usr/local/pf/lib_perl/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/pf/lib_perl/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl/5.32/Module/Load.pm line 77.

(after /usr/local/pf/bin/pfcmd checkup)

**To Reproduce**
See above

**Additional context**
This worked flawlessly in 11.1

**Comment by julsemaan** [comment]
Could you post the full output (including db errors, etc) just to make sure the root error isn't hiding somewhere in the middle of that output

Thanks

**Comment by nathanbloemendaal78** [comment]
I have attached the full output of both the configreload and the checkup:

[debug-cluster-1.txt](https://github.com/inverse-inc/packetfence/files/8184101/debug-cluster-1.txt)
[debug-cluster-2.txt](https://github.com/inverse-inc/packetfence/files/8184102/debug-cluster-2.txt)

But there are more commands failing, here the output of the generatemariadbconfig:

/usr/local/pf/bin/pfcmd generatemariadbconfig
module pf::cmd::pf::generatemariadbconfig cannot be loaded
Can't determine cluster name for host dc-cgd-01
Compilation failed in require at /usr/local/pf/lib/pf/cmd/pf/generatemariadbconfig.pm line 35.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/cmd/pf/generatemariadbconfig.pm line 35.
Compilation failed in require at /usr/share/perl/5.32/Module/Load.pm line 77.
Can't locate pf/cmd/pf/generatemariadbconfig in @INC (@INC contains: /usr/local/pf/lib /usr/local/pf/lib_perl/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/pf/lib_perl/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl/5.32/Module/Load.pm line 77.


Usage:
    pfcmd <command> [options]

     Commands
      cache                       | manage the cache subsystem
      checkup                     | perform a sanity checkup and report any problems
      class                       | view security event classes
      configreload                | reload the configution
      connectionprofileconfig     | query/modify connection profile configuration parameters
      fingerbank                  | Fingerbank related commands
      fixpermissions              | fix permissions on pf tree
      floatingnetworkdeviceconfig | query/modify floating network devices configuration parameters
      generatedomainconfig        | generate the domain configuration
      generatemariadbconfig       | generate the MariaDB configuration
      generatemonitconfig         | generate the monit configuration
      generatesyslogconfig        | generate the syslog configuration
      help                        | show help for pfcmd commands
      import                      | bulk import of information into the database
      ipmachistory                | IP/MAC history
      locationhistorymac          | Switch/Port history
      locationhistoryswitch       | Switch/Port history
      networkconfig               | query/modify network configuration parameters
      node                        | manipulate node entries
      pfconfig                    | interact with pfconfig
      pfcron                      | run pfcron tasks
      pfqueue                     | query/modify pfqueue tasks and counters
      reload                      | rebuild fingerprint or security events tables without restart
      service                     | start/stop/restart and get PF daemon status
      schedule                    | Nessus scan scheduling
      switchconfig                | query/modify switches.conf configuration parameters
      version                     | output version information
      security_event              | manipulate security events
      security_eventconfig        | query/modify security_events.conf configuration parameters
      tenant                      | manipulate tenants

    Please view "pfcmd help <command>" for details on each option

**Comment by julsemaan** [comment]
Please post the content of `/usr/local/pf/conf/cluster.conf`

As well as the output of the following command on all 3 servers: `hostname`

**Comment by nathanbloemendaal78** [comment]
Your request put me on the right track; I used FQDN's in the cluster.conf file, whereas the hostname command returned only a short name (without domain suffix). After modifying the cluster.conf file so that the name of the node was also a shortname, a lot started working. I will report back if it is definitely fixed.

**Comment by nathanbloemendaal78** [comment]
I will close this issue for now.
