### ISSUE TITLE
Missing "Configuration" tab in Admin UI Web

### ISSUE THREAD

**Issue by haidl1986** [inverse-inc/packetfence#6923]
**Describe the bug**
I login with admin user but the "configuration" tab is missing

**Screenshots**
![Packetfence_UI_Missing](https://user-images.githubusercontent.com/100894891/156698471-2553f0a7-93e0-4254-a9b9-f877b71d72ef.PNG)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, IE, Edge]

**Comment by nqb** [comment]
Hello,
Without more information (PF version, steps to replicate, etc.), we can't provide answer to that issue. Please provide necessary information (as requested in our issue template) if you want us to look at your issue.

**Comment by haidl1986** [comment]
Hello, 

   I would like to update information as below 
     . PacketFence-ZEN: version 11.1.0
     . Debian  SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU
     . Issue happned after I issued command apt-get update. 
![1](https://user-images.githubusercontent.com/100894891/156715686-8b5c61b0-a62e-4b86-83eb-417be5b8173c.PNG)
![2](https://user-images.githubusercontent.com/100894891/156715690-61aef27f-1976-4455-8a6f-4959717b2b57.PNG)
![3](https://user-images.githubusercontent.com/100894891/156715695-050bc475-1845-4d25-9937-49faccdd91a0.PNG)

**Comment by nqb** [comment]
Not able to replicate after I upgraded a Debian 11 with PF 11.1.0 to latest maintenance packages.
Perhaps you need to clear your cache.
I'm closing this issue.

**Comment by 4dr14nt0** [comment]
how to show missing configuration menu
