### ISSUE TITLE
pfcron: Deadlock and out of range errors when running bandwidth_maintenance* tasks

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6931]
**Describe the bug**
On a 10.3 setup with all maintenance patches applied, I see following messages in `pfcron.log` each time bandwidth_maintenance* tasks run:

```
Mar 15 14:50:08 pf-01 pfcron[2987]: t=2022-03-15T14:50:08+0430 lvl=eror msg="Database error: Error 1213: Deadlock found when trying to get lock; try restarting transaction" pid=2987
Mar 15 14:50:08 pf-01 pfcron[2987]: t=2022-03-15T14:50:08+0430 lvl=info msg="bandwidth_maintenance_session cleaned items 0" pid=2987
Mar 15 14:50:43 pf-01 pfcron[2987]: t=2022-03-15T14:50:43+0430 lvl=eror msg="Database error: Error 1690: BIGINT value is out of range in '`pf`.`bandwidth_accounting_history`.`in_bytes` + `pf`.`bandwidth_accounting_history`.`out_bytes`'" pid=2987
```

According to log entries and timing, it looks like deadlock is caused by `bandwidth_maintenance_session` task and out of range is caused by `bandwidth_maintenance` task.

**Expected behavior**
`pfcron` tasks should run without any issues.

**Additional context**
As I mentioned on #6819, out of range issue can caused backup to fail if `mysqldump` is used as backup mechanism.

**Comment by fdurand** [comment]
For ref https://github.com/inverse-inc/packetfence/compare/maintenance/10.2...feature/pfacct_pfcron_fix_for_10.2

**Comment by jrouzierinverse** [comment]
This has been fixed by getting rid of temp tables for cleanup
