### ISSUE TITLE
Issues with pf::config::cached

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#694]
The admin is still using this old module and it seems that they're still causing problems.

On a fresh 5.1 I'm getting a lot of these in the admin logs (and errors in the frontend)
I saw them happening in other circumstances too.

Jun 15 05:39:57 httpd.admin(21711) ERROR: Caught exception in pfappserver::Controller::Configuration->section "Can't call method "HasChanged" on unblessed reference at /usr/local/pf/lib/pf/config/cached.pm line 779." (pfappserver::PacketFence::Controller::Root::end)
Jun 15 05:40:13 httpd.admin(21711) ERROR: Caught exception in pfappserver::Controller::Configuration->section "Can't call method "HasChanged" on unblessed reference at /usr/local/pf/lib/pf/config/cached.pm line 779." (pfappserver::PacketFence::Controller::Root::end)

The good old 'rm -fr var/cache/\* && pkill memcached && service packetfence restart' fixes it

I propose the following patch :
https://github.com/julsemaan/packetfence/commit/6cf0202983234463cc0e536e4bd5011701cbb03a

@jrouzierinverse can you confirm the patch above is ok for 5.2

Let's keep in mind that this module is at the end of it's life and not overkill that fix.

**Comment by jrouzierinverse** [comment]
Looks good to me

**Comment by julsemaan** [comment]
Fixed in b0aaefbff4c8d2754c342af74b5f4d227c33fbcd

Cherry-picked in 5.x maintenance branches
