### ISSUE TITLE
web admin: not possible to clone a switch template without changing name

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6941]
**Describe the bug**
If you clone a switch template and keep name with `-copy` suffix, you got an error:

```json
{"errors":[{"field":"id","message":"Cannot be an existing Switch Module"}],"message":"Unable to validate","status":422}
```

=> It looks like `-copy` is ignored

**To Reproduce**
1. Go to Switch templates menu
2. Click on Clone on an existing switch template
3. Click on Create without doing any changes on Switch template

=> You got error reported above.

**Expected behavior**
I expect frontend to generate a name which can be usable directly.

**Comment by jrouzierinverse** [comment]
There are two problems here.
The first is the error is not clear because ```-copy``` is not a valid perl module name.
The real problem is the ```-copy``` in the name.
@satkunas can we change from ```-copy``` to ```_copy```
