### ISSUE TITLE
web admin(Services): Restart all button ignore services not required

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6942]
**Describe the bug**
On a standalone setup, if you use "Restart all" button in Services menu, frontend will send a restart request to all services without taking into account services not required (haproxy-db, radiusd-acct, radiusd-eduroam).

This put a lot of pressure on CPU because `systemd` recall `perl` commands to regenerate configuration of services.

**To Reproduce**
1. On a standalone setup, click on "Restart all" button in Services menu

=> In Web browser console, you can see that all services are restarted even the ones flagged as not required.

**Expected behavior**
Don't restart services which are not required.

**Additional context**
I've noticed this issue on a 11.2 and 11.1 installations.

**Comment by nqb** [comment]
@satkunas, could you look at this issue ? It's still presents on `devel`.

**Comment by satkunas** [comment]
@nqb Will be obsoleted with https://github.com/inverse-inc/packetfence/pull/6855

**Comment by nqb** [comment]
Restart All button doesn't exist anymore.

**Comment by satkunas** [comment]
@nqb it's moved

![Screen Shot 2022-08-25 at 1 15 01 PM](https://user-images.githubusercontent.com/3904468/186728514-c6425d11-58d6-45a0-aa94-a9f24f76ec30.jpg)
.
