### ISSUE TITLE
Dot1x not kicking in for Mac OS using Machine Authentication 

### ISSUE THREAD

**Issue by Virg1984** [inverse-inc/packetfence#6956]
**Describe the bug**
Packetfence is working in great in my environment; we are using PEAP with MS chapv2. 
all the windows Machines are working, but as soon as we connect MAC OS - Catalina fotr example , it put the port into registration.
we also created dot1x profile but no use. 

**To Reproduce**
1. Go to Cataline 
2. Click on connect network 
3 See error - port into registration 

**Expected behavior**
MAC OS should also work in the same way as Windows PC

**Desktop (please complete the following information):**
 - OS: MAC OS

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
