### ISSUE TITLE
v12(containers): delay of 1-2 seconds when haproxy-portal query httpd.dispatcher on port 8888 (proxy)

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6961]
**Describe the bug**
With haproxy-portal in a container, I'm able to reach httpd.portal (in container) and httpd.dispatcher (in container) for static content (port 8889) and proxy (port 8888).

However, randomly, when sending data to port 8888, there is a delay of 1 or 2 seconds before httpd.dispatcher reply correctly.

**To Reproduce**
1. Setup (RHEL or Debian) with pfconfig-container packages installed and haproxy-portal/httpd.portal/httpd.dispatcher services started
2. Run: `curl -v http://PORTAL_INTERFACE/` several times

=> You can see at some point there is wait. No difference if we use HTTP or HTTPS

**Expected behavior**
There should have no delay

**Additional context**
I took a packet capture inside `httpd.dispatcher` and I can say with confidence that delay is added by `httpd.dispatcher`.

EDIT: this is not caused by `ip2mac` request: I tried to create a fake record and delay is still here.

**Comment by julsemaan** [comment]
closing for now
