### ISSUE TITLE
Captive portal asks for username/password when Authorization source is used

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6972]
**Describe the bug**
If you configure an Authorization source on a connection profile and you use captive portal with this connection profile, captive portal will ask for username/password which doesn't make sense. Authorization sources should work as Null sources on captive portal or should be ignored.

**To Reproduce**
1. Create an Authorization with a catchall rule
2. Assign this source to default connection profile
3. Preview default connection profile

=> You will got a prompt for username/password

**Expected behavior**
Make Authorization sources work as Null source or ignore these sources.

**Comment by jrouzierinverse** [comment]
Should authorization sources be allowed to be used on the portal?
@fdurand any thoughts?

**Comment by extrafu** [comment]
@nqb Please document for now the workaround.

**Comment by julsemaan** [comment]
@jrouzierinverse, please investigate this for 12.1

**Comment by satkunas** [comment]
Ignore and/or tell the user that this auth source can't be used.

**Comment by satkunas** [comment]
Bypass auth source for this case
