### ISSUE TITLE
Reports: Authentication::All need to be refreshed to get last results

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6973]
**Describe the bug**
On PF11.2.0, I noticed that when I view a report, new records added in DB are missing until I refresh web page.

**To Reproduce**
1. Register a device on captive portal

```sql
insert into auth_log(process_name,mac,pid,status,attempted_at,completed_at,source,profile) values("httpd.portal","ff:ee:dd:cc:bb:aa","nicolas@example.lan","completed",NOW(),NOW(),"local","default");
```

2. Look at Authentication::All report for the first time

=> Your record is here

3. Register a second device on captive portal

```sql
insert into auth_log(process_name,mac,pid,status,attempted_at,completed_at,source,profile) values("httpd.portal","aa:bb:cc:dd:ee:ff","nico@example.lan","completed",NOW(),NOW(),"local","default");
```

4. Look at Authentication::All report for the first time

=> There is only one record. If you click several times on "Search", your second record doesn't appear.

=> Refresh web page: new record appear.

**Expected behavior**
When I click again on "Search", I expect to see new records.

**Comment by jrouzierinverse** [comment]
This seems to be a caching issue

**Comment by nqb** [comment]
@jrouzierinverse, I assigned you and @satkunas because when I hit "Search", I saw API requests sent to backend.

**Comment by satkunas** [comment]
this is not a cache issue

@nqb adjust the end date/time to greater than what is produced by sql `NOW()`, and the search will include the new result. Refreshing the page bumps the default start/end time using the client's current javascript Date.

**Comment by nqb** [comment]
@satkunas, I provided example using SQL requests but I tested everything using a real captive portal scenario and hit that bug.

**Comment by satkunas** [comment]
Unable to reproduce using SQL. This appears to be a usability issue, not a bug.

**Comment by julsemaan** [comment]
According to what @nqb described, it looks like it's a bug in the frontend where the frontend keeps sending the same end_date when hitting search instead of using the current datetime as the end_date. Then I assume when you refresh the page, the end_date becomes the datetime at which the page was refreshed and then the data shows.

So it does look like a bug in the frontend

**Comment by satkunas** [comment]
The UI does not differentiate an end_date that's defined by the user from one that's automatically chosen when the page is loaded.

The UI can automatically bump the end_date, but this might override a manual selection made by the user and cause alternate confusion.

**Comment by julsemaan** [comment]
If the user doesn't explicitly specify an end date, I'd expect that additional searches refresh the data and I think that's what others would expect too. 

If the user has indeed specified an end date in his report, that makes total sense to keep it though.

**Comment by satkunas** [comment]
The UI is unable to differentiate these 2 cases. We'll need a behavior that works for both.

**Comment by julsemaan** [comment]
But what if the end_date stays empty during the initial load and when it's empty it uses NOW()

When the user will fill-in a date, it will have a value and then it's made so it's not updated with NOW() on every search

**Comment by satkunas** [comment]
The UI is unable to differentiate an "initial load" with a subsequent "user-defined search".

@jrouzierinverse the UI is currently using the OPTIONS endpoint to pre-fill the end_date - not JS Date() as I originally thought. Is it possible to leave `default_start_date` and `default_end_date` empty for cases where `date_limit` is `null`? Does this change make sense for usability?

```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS "/api/v1.1/report/Authentication%3A%3AAll" | jq '.report_meta.default_end_date'
"2022-04-21 10:23:24"
```

It will fix this case, but we'll still see the same bug with reports that enforce a date_limit.
