### ISSUE TITLE
Intergration => PKI => Certificate: clone does not work, error 500

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6978]
**Describe the bug**
Try to clone a Certificate by clicking on "clone" button.
{errors: null, message: 'json: cannot unmarshal string into Go struct field Cert.ID of type uint', status: 500}

**To Reproduce**
1. Create a certificate authority
2. Create a template
3. Create a certificate
4. try to clone the certificate

**Expected behavior**
No clone option, or no issue when trying to clone

**Comment by jrouzierinverse** [comment]
This is on frontend side it is sending a a json payload that is invalid.
 @satkunas

**Comment by satkunas** [comment]
Fixed in cfea5e693ef2c80c0d755985ac7f5b77e0f2b089
