### ISSUE TITLE
v12(containers): httpd.portal container is not able to communicate with Fingerbank

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6982]
**Describe the bug**
In logs (`/var/log/syslog`), we can see these messages:

`Apr 25 13:43:21 deb11dev httpd.portal-docker-wrapper[72339]: httpd.portal(12) ERROR: [mac:00:11:22:33:44:55] Error while communicating with the Fingerbank collector. 500 Can't connect to 127.0.0.1:4723 (Connection refused) (pf::fingerbank::endpoint_attributes)`

`fingerbank-collector` is already listening on `*:4723` so it should be possible to make communication using `containers-gateway` record like we do with `redis-cache`

**Comment by julsemaan** [comment]
Fixed with upload of fingerbank-collector 1.4.0 on the devel repository

**Comment by nqb** [comment]
I rechecked this issue and I don't see such messages in `packetfence.log`. On top of that, I see requests on fingerbank-collector:

```
Aug 08 16:23:49 pfel8dev bash[2132]: [GIN] 2022/08/08 - 16:23:49 | 200 |     101.922µs |     100.64.0.11 | GET      "/endpoint_data/00:11:22:33:44:55"
Aug 08 16:23:49 pfel8dev bash[2132]: [GIN] 2022/08/08 - 16:23:49 | 200 |     168.662µs | 192.168.121.222 | GET      "/endpoint_data/00:11:22:33:44:55"
Aug 08 16:24:00 pfel8dev bash[2132]: [GIN] 2022/08/08 - 16:24:00 | 200 |      97.124µs |     100.64.0.11 | GET      "/endpoint_data/00:11:22:33:44:55"
```

Any reason you reopened this issue @julsemaan ? I will defer to you to close or not.

**Comment by julsemaan** [comment]
Forgot to close this after adjusting Fingerbank for the containerization.

Closing now.
