### ISSUE TITLE
captive portal redirect page return Caught exception in captiveportal::Controller::Root->dynamic_application "Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/enforcement.pm line 206

### ISSUE THREAD

**Issue by supportFGT** [inverse-inc/packetfence#6985]
I'm running packetfence 11.2 on debian 11- standalone server. I've update to the latest release using the script.

**the captivePortal redirection page do not work and show the error*

Caught exception in captiveportal::Controller::Root->dynamic_application "Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/enforcement.pm line 206

I think there is a missing or wrong value but I don't  was able to recognize
![Cattura](https://user-images.githubusercontent.com/44610733/165494205-8b3ddbed-35a3-425f-8f86-a4843580d208.PNG)

**Comment by julsemaan** [comment]
Although this indeed looks like a bug, we need to know the full way of replicating this issue from a bare 11.2 since it could be related to your configuration or the network equipment you use

**Comment by supportFGT** [comment]
I'm using  captive portal with ARUBA IAP

[ARUBAIAP_IP]
type=Aruba::Instant_Access
group=default
description=Aruba_IAP
deauthOnPrevious=Y
deauthMethod=RADIUS
radiusSecret=11234
SNMPVersion=2c
SNMPCommunityWrite=123
SNMPCommunityRead=12345
isolationVlan=12
guestVlan=13
UserVlan=14
DomainComputersVlan=15
DomainUsersVlan=16
registrationVlan=17
voiceVlan=18
SNMPEngineID=
coaPort=5999
SNMPAuthPasswordRead=
defaultVlan=17



[Configuration_Profile_User_wireless]
advanced_filter=
filter=connection_type:Wireless-802.11-NoEAP
locale=
sources=sponsor,AuthSource-LDAP
description=captive registration
redirecturl=https://www.redirect.com
unreg_on_acct_stop=enabled

**Comment by olmanolsztyn** [comment]
I noticed that it happens when you have enabled "Deauth on previous switch" on switch configuration
and you delete "previous switch" or change its ip address when node was connected before. 
Packetfence can't deauth on switch that is not present and error is occuring.

**Comment by julsemaan** [comment]
That makes sense and does need to be fixed

**Comment by olmanolsztyn** [comment]
It would be better to handle this case to avoid this error on captive portal to showing up.
Bypass when previous switch is not found.

**Comment by julsemaan** [comment]
Yes, agreed, as I said in my previous comment, this does need to be fixed
