### ISSUE TITLE
Add Two Factor Authentication for Admin GUI

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6996]
**Is your feature request related to a problem? Please describe.**
Add the two factor authentication available for the admin

**Describe the solution you'd like**
Would be able to use all kind of Two Factor Authentication available on PF to connect on the admin part.

**Describe alternatives you've considered**
None really exists

**Comment by PureOxygen-Dev** [comment]
As PF is a core security product having MFA to protect the admin accounts should be seen as mandatory (it is with our CISO).

I would like to suggest this is not only look at as a feature enhancement but potentially as a security issue within the product and any feature released should be back ported to other PF supported versions.

**Comment by julsemaan** [comment]
We're looking at adding all supported captive portal methods to the admin login for 12.1

However, this will not be back-ported to maintenance branches/older releases.

**Comment by PureOxygen-Dev** [comment]
Thanks for the feedback Julien. We are looking forward to this being available in 12.1 when it is released.



________________________________
