### ISSUE TITLE
webadmin: netdata charts and alarms are not available when using HTTP

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7002]
**Describe the bug**
If you reach web admin using HTTP in place of HTTPS, netdata charts and alarms are not displayed correctly because frontend is trying to use HTTPS in place of HTTP when doing netdata API calls like:
- `/netdata/X.X.X.X/api/v1/alarms`
- `/netdata/X.X.X.X/api/v1/charts`

Some netdata API calls are working correctly because they use HTTP like
- `/netdata/127.0.0.1/dashboard.js`

It's in a cluster environment with custom code to expose HTTP admin on HTTP using 8443 port.

**Additionnal context**
I think it's related to:
https://github.com/inverse-inc/packetfence/blob/b3d6dd733dc6cad2d61187cc022829c9a6f55761/html/pfappserver/root/src/utils/charts.js#L6

I suggest following patch:

```diff
diff --git a/html/pfappserver/root/src/utils/charts.js b/html/pfappserver/root/src/utils/charts.js
index 0cad972e11..1a47c20ee9 100644
--- a/html/pfappserver/root/src/utils/charts.js
+++ b/html/pfappserver/root/src/utils/charts.js
@@ -3,7 +3,7 @@ import router from '@/router'
 import store from '@/store'

 const chartsCall = axios.create({
-  baseURL: `https://${window.location.hostname}:${window.location.port}/netdata/`
+  baseURL: `${window.location.protocol}://${window.location.hostname}:${window.location.port}/netdata/`
 })

 chartsCall.interceptors.response.use((response) => {
```

according to https://www.w3schools.com/js/js_window_location.asp

@satkunas, could you share your thought on that ? Thanks !

**Comment by satkunas** [comment]
@nqb I would rather force HTTPS using a redirect on the HTTP port to prevent insecure transport of the UI. Doing so should fix this issue. I don't see any need to support non-SSL connections.

**Comment by nqb** [comment]
In my use case, customer is terminating SSL connections on cloud load-balancer then load-balancer is talking to PacketFence server using HTTP. I think it's done like this because:
- they assume cloud intra-communication are secure
- they manage all SSL certificates in one place through cloud tools

**Comment by nqb** [comment]
Changing milestone just to ensure I will check that before v12 release.
