### ISSUE TITLE
Access Duration not Working with local user Packet Fence

### ISSUE THREAD

**Issue by RenatoPereira91** [inverse-inc/packetfence#7003]
Configured the local user with Windows Duration limit and access duration, but the user can log anytime because the Packetfence not check Windows Duration and not input Access Duration.

Access Page
![image](https://user-images.githubusercontent.com/102453125/169174762-ab606cdf-e12e-4fde-92ae-19b1a7f5b67b.png)

User Configuration
![image](https://user-images.githubusercontent.com/102453125/169174832-0e898096-8b95-4798-8806-94aa0e798bd1.png)

**Comment by nqb** [comment]
This bug has already been reported (see #6925). You need to get latest maintenance patches available (see https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html#_upgrade_to_a_patch_version_x_y_patch)

**Comment by RenatoPereira91** [comment]
Hi nqb,

After upgrade the system, I get unregistration date, but the system dont check registration windows:

![image](https://user-images.githubusercontent.com/102453125/169294521-a236d76e-fe58-449b-97ee-c4a243ae0a80.png)

![image](https://user-images.githubusercontent.com/102453125/169294574-ef8f14ab-42c3-4240-ab2f-4618cd4e782b.png)

![image](https://user-images.githubusercontent.com/102453125/169294400-c6135949-aaaf-4539-bb71-dc69556fb302.png)

**Comment by nqb** [comment]
Initial issue has been solved by upgrading according to your screenshot.

Please use mailing-list for your remaining question.

**Comment by nqb** [comment]
Hi @RenatoPereira91,

According to your screenshot, access duration is now correctly applied.
What you mean is that Registration Windows is not honored ? If yes, please double-check timezone configured in PacketFence and in OS and ensure they are identical to what you configured as registration windows.

**Comment by RenatoPereira91** [comment]
Hi @nqb 

Yes the system is not honored.

I checked the timezone and same -3 GMT (PC and Packetfence), but have one difference (I dont know if have impact) my date is dd/mm/aaaa and clock is 24 hours.

**Comment by nqb** [comment]
> but have one difference (I dont know if have impact) my date is dd/mm/aaaa and clock is 24 hours.

I don't think so. I will try to replicate and let you know.

**Comment by RenatoPereira91** [comment]
@nqb 

Ok thanks

**Comment by nqb** [comment]
I'm able to replicate this issue.

Steps to replicate:
* Create a user with end of registration windows in the past (compared to time of PacketFence server), access duration and role
=> Information looks good in DB

```sql
*************************** 2. row ***************************
      tenant_id: 1
            pid: nicolas
       password: {bcrypt}$2a$08$.1n.buB7bYVxG6K2od66IOnIeyQEZXM4frMU0aNuda8yPtZC/82Ty
     valid_from: 2022-05-20 00:00:00
     expiration: 2022-05-20 08:00:00
access_duration: 1h
   access_level: NULL
       category: 2
        sponsor: 0
      unregdate: 0000-00-00 00:00:00
login_remaining: NULL
```

* Try to register on captive portal using default connection profile

=> You can register and it should not be possible because `expiration` date has been reached

MariaDB config:

```
MariaDB [pf]> SHOW GLOBAL VARIABLES LIKE 'time_zone';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| time_zone     | SYSTEM |
+---------------+--------+
1 row in set (0.001 sec)
```

System config:
```
# timedatectl
               Local time: Fri 2022-05-20 12:34:03 UTC
           Universal time: Fri 2022-05-20 12:34:03 UTC
                 RTC time: Fri 2022-05-20 12:34:03
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no
```

@jrouzierinverse, can you look at PacketFence code ?

**Comment by jrouzierinverse** [comment]
The issue was in the past we only used the date not the time for expiration of the password.
