### ISSUE TITLE
Problem with Symantec Integration

### ISSUE THREAD

**Issue by RenatoPereira91** [inverse-inc/packetfence#7007]
The packet fence can't out peding status after install Symantec and click "continue"
I following the steps to integration Symantec with PacketFence. If the device dont have anti-virus I get the message that the IP dont registered and send device to role with registration with status peding

**To Reproduce**
1. Device dont have anti-virus
2. After delay PacketFence input role registretion with status peding for instalation
3. I'm redirecto to page for download of anti-virus
4. Install anti-virus
5. Reboot machine
6. I click in continue 
7. In the Packet fance log show that device are registered in SEPM
8. The client and redirect to page Maximum amount of endpoints

![image](https://user-images.githubusercontent.com/102453125/169815952-6a975bd7-1e73-4574-afec-4dac509c069a.png)

But the client dont have device register

**Comment by nqb** [comment]
Symantec support will be remove in next PacketFence release (see #7692 and #7700)
