### ISSUE TITLE
Monit: "A copy of this alert have been sent to the PacketFence support team."

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7012]
**Describe the bug**
"A copy of this alert have been sent to the PacketFence support team." is in default emails sent by monit. But it is related to monit setting not sent by default.
Perhaps change it to something related to monit configuration, or explain where you can find the setup about it.

**To Reproduce**
1. have monit enable
2. receive a monit email and check

**Expected behavior**
change it to something related to monit configuration, or explain where you can find the setup about it.

**Comment by julsemaan** [comment]
I think it's time to get rid of this line anyway since we do not monitor alerts for all the customers anyway.

It's just a matter of deleting this line:
https://github.com/inverse-inc/packetfence/blob/416c9ec5b1d51223ecd63bdf6cc36bee3b21dd0a/addons/monit/monit_configurations/monit_general.tt#L31
