### ISSUE TITLE
web admin(Nodes): additional columns can hide Delete button

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7014]
**Describe the bug**
In Nodes menu, when you add additional columns to your search, it could prevent "Delete" button to work correctly.

There is no issue with Users menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/10830260/171118374-a1bc3217-eeb6-4b98-b1a9-c01faa2485be.png)

**To Reproduce**
1. Go to Nodes menu
2. Add 5 additional columns to display
3. Try to delete a node

=> It's not possible because Delete button is hidden.

**Expected behavior**
Same behavior as with Users menu where "Delete" button will override additional column.

**Additional context**
I noticed this behavior on a 11.1.0 version too.

**Comment by satkunas** [comment]
The overflow was fixed to address an issue in https://github.com/inverse-inc/packetfence/issues/6660

I can either revert this behavior and regress to the other issue you reported, or you can either:
 * increase your screen resolution
 * choose fewer columns

**Comment by julsemaan** [comment]
IMO having more columns should not be incompatible with deleting a node from there. There must be a way we can get a delete button to work without regressing. 

Perhaps the column could expand when the sliding effect is happening or we could use something else than the sliding effect that doesn't cause an overflow

**Comment by nqb** [comment]
> IMO having more columns should not be incompatible with deleting a node from there. There must be a way we can get a delete button to work without regressing.

100% agree with @julsemaan on that.
