### ISSUE TITLE
Wireless provisioning agent for Windows working due to DNS-issue

### ISSUE THREAD

**Issue by nathanbloemendaal78** [inverse-inc/packetfence#7016]
The Windows provisiong agent (and possibly Android too) is not working, because wireless-profiles.packetfence.org is not resolvable.
I tracked this down with a Wireshark-capture, when clicking on "configure" in the provisioner, this URL is looked up, but it doesn't resolve to an IP address. After manually editing the hosts file, with the URL pointing to 66.70.255.147, clicking on configure takes the provisioner to the next step, where you have to enter the certificate password. Then the rest of of the provisioning process runs as it should.

**Comment by julsemaan** [comment]
Are you using a registration VLAN or web-auth on your network equipment?

**Comment by nathanbloemendaal78** [comment]
I am using a registration VLAN. All other DNS resolving works fine from there (PF does the resolving), only this one URL doesn't resolve.

**Comment by julsemaan** [comment]
Could it be because you defined it as a passthrough in the Fencing configuration section?

**Comment by nathanbloemendaal78** [comment]
It is indeed configured in the passthroughs in the Fencing section, but I didn't do that, it was already there. In fact, checking multiple PF-installations I have, all contain this entry. I suppose it is there because it is indeed needed to fetch the config (XML?) from that URL/repository at wireless-profiles.packetfence.org. I suppose it fetches an XML and then loads this into the Windows 10 wireless settings.

For clarification: if I remove the entry in the hostfile of the Windows machine I am trying to onboard (to an EAP-TLS SSID) clicking the  "configure" button (in the downloaded provisioner/configurator agent for Windows), results in the error "Unable to retrieve your profile file, please contact your local support". Maybe I didn't explain this clear enough in my initial comment.
In fact, it is the exact same error as described here: https://www.mail-archive.com/packetfence-users@lists.sourceforge.net/msg18783.html.

I was able to follow the entire process using Wireshark, so I am fairly sure this is the URL that causes the problem, because it cannot be reached, and therefore the profile cannot be retrieved.

**Comment by julsemaan** [comment]
That domain name isn't part of the default configuration we ship so it must have been manually added by an administrator of PacketFence on your deployment.

The fact that this domain is there means that it will not resolve to the captive portal IP but instead attempt to be resolved as a public domain name. Since this domain name doesn't resolve publicly, then that creates the exact issue you described.

Remove this domain from the passthroughs and restart the appropriate services and it should work fine afterwards

**Comment by nathanbloemendaal78** [comment]
Hi! I stand corrected: this URL was indeed manually entered into an installation, which I cloned. It works perfectly now,
