### ISSUE TITLE
v12: fixpermissions from webadmin can break PacketFence

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7050]
**Describe the bug**
If you run "Fixpermissions" from web admin, it will work but I noticed that:
* `/usr/local/pf/var`
* `/usr/local/pf/conf`

are now owned by `polkitd` (owner) and `systemd-coredump` (group).

Also some files inside  `/usr/local/pf/conf` are owned by  `systemd-coredump` (group).

Similar to #7049

**Comment by julsemaan** [comment]
We could reuse the pf-apache-wrapper (and perhaps change its name)
Very easy to use but adds startup overhead to the service

Just changing the pfperl-api Dockerfile entrypoint should be enough, example:
https://github.com/inverse-inc/packetfence/blob/devel/containers/httpd.webservices/Dockerfile#L23

**Comment by jrouzierinverse** [comment]
We could create a pfqueue job that does the fix permission, and the results are sent back to the admin in an async manner.

**Comment by nqb** [comment]
Solved by #7073
