### ISSUE TITLE
v12: /etc/network/interfaces is not rewritten

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7054]
**Describe the bug**
On Debian, if you try to assign an IP address on an interface using web admin, it will work but IP address will be written in `/etc/network/interfaces` **inside** `pfperl-api` container in place of `/etc/network/interfaces` on host.

**Comment by nqb** [comment]
Related to #7045. `/etc/network/interfaces` inside container contains `docker0` and `veth*` interfaces where they don't appear in `/etc/network/interfaces` on host.

**Comment by julsemaan** [comment]
There is also the problematic where on a RHEL machine, pfperl-api will think it's on Debian.

We need to find a solution for this where the host will pass down an env variable to the containers to specify the OS on the host itself and we take it into consideration during our OS detection in the code
