### ISSUE TITLE
import: setup_mycnf will failed if MariaDB root password contains a #

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7056]
**Describe the bug**
If MariaDB root password of a PacketFence installation contains a #, import mechanism will failed during database upgrade because `setup_mycnf` function write following file:

```
[client]
user=root
password=Passw#ord
```
and use it to run next mysql commands. However, according to that [bug report](https://jira.mariadb.org/browse/MDEV-6177?jql=text%20~%20%22comment%20option%20files%22), a # in middle of the line is considered as a comment so all remaining characters are ignored.

Putting double quotes around the Passw#ord works. However, I'm not sure this solution can handle double quotes in password. It seems to be the case but I need to double check.

**Comment by nqb** [comment]
Test:
```sql
GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE,LOCK TABLES ON pf.* TO nqb@"%" IDENTIFIED BY 'pass"word';
GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE,LOCK TABLES ON pf.* TO nqb@"localhost" IDENTIFIED BY 'pass"word';
```

with following mycnf file:

```ini
[client]
user=nqb
password="pass"word"
```
I'm able to login using following command:

```console
mysql --defaults-file=setup_nqb_mycnf pf -v
```

So I suggest following patch:
```diff
diff --git a/addons/functions/database.functions b/addons/functions/database.functions
index d02b2cc684..682cd78e30 100644
--- a/addons/functions/database.functions
+++ b/addons/functions/database.functions
@@ -152,7 +152,7 @@ function setup_mycnf() {
   cat <<EOT > setup_mycnf
 [client]
 user=root
-password=$1
+password="$1"
 EOT
 }
```

However, I would like to perform a real test with that patch because I'm not sure how bash will behave with a double quote inside a variable.

**Comment by jrouzierinverse** [comment]
The correct behavior is to set it to ```password="pass\'"word"```

**Comment by jrouzierinverse** [comment]
We could do the following.
```password="$(echo "$1" | sed 's/"/\\"/g')"```
