### ISSUE TITLE
Web UI: Node view, select switch group broken

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7072]
In PacketFence v11.1 when you select a switch group in the Node page, it selects all the switch group all at once.

Seems to be fixed for PF v12, can it be ported back to maintenance ?

**Comment by satkunas** [comment]
d5eee3c82eb43a7d6e38bf7a5cd600478ab20c4d and 94a032a5e4466f0b05210c4fa81d9c2ec290c599 have been back-ported to `maintenance/11.1` and `maintenance/11.2`.
