### ISSUE TITLE
PF12: sync issue during cluster sync

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7086]
````
ERROR : Failed to sync file : /usr/local/pf/var/config_version . Config file /usr/local/pf/var/config_version doesn't exist at /usr/local/pf/lib/pf/api.pm line 717.
````

**Comment by satkunas** [comment]
It's Highly-Critical

**Comment by extrafu** [comment]
That means it's totally unimportant.

**Comment by julsemaan** [comment]
This commit should address it: 4961e7015cf5732dce8912aed496897845f1ee9f

Didn't have chance to test it in a cluster yet though

**Comment by julsemaan** [comment]
Worked fine on my latest cluster build based on devel
