### ISSUE TITLE
v12: hostname of server doesn't appear on Status page

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7096]
**Describe the bug**
When you login on PacketFence webadmin, hostname is missing next to uptime.

**Comment by nqb** [comment]
@satkunas, you told me:

> the Status Dashboard is missing the hostname because this endpoint is returning an empty result:

```
/usr/local/pf/sbin/pfperl-api get -M GET /api/v1/cluster/servers | jq ''
{
  "items": [],
  "status": 200
}
```

I checked on a 11.2.0 version (standalone) and I didn't see any data returned from this API call while I have an hostname correctly displayed.

From what I see, `hostname` is coming from `/api/v1/system_summary` at least on a standalone installation.

**Comment by julsemaan** [comment]
@nqb's comment seems to be right. A quick check in the code shows that this API call always returned empty items for a standalone instance.

@nqb, please prioritize this issue as well (probably a high I guess)

**Comment by nqb** [comment]
Priority updated.

I will update issue with my findings.

**Comment by nqb** [comment]
This changes has been added after 11.2 release:
https://github.com/inverse-inc/packetfence/blob/e13ff81487f494d15990a330747f2b8453c09def/lib/pf/config/cluster.pm#L80-L83

And this is what is used by `/api/v1/system_summary`:

https://github.com/inverse-inc/packetfence/blob/e13ff81487f494d15990a330747f2b8453c09def/lib/pf/UnifiedApi/Controller/SystemSummary.pm#L29

where previously we returned `hostname` without any conditions.

@julsemaan, if logic related to `host_id` need to be kept as-is, I can:
* adjust `SystemSummary.pm` to return `hostname` of the host using https://github.com/inverse-inc/packetfence/blob/e13ff81487f494d15990a330747f2b8453c09def/lib/pf/UnifiedApi/Controller/Config/System.pm#L99-L103
* replace usage of `hostname` in `cluster.pm` by https://github.com/inverse-inc/packetfence/blob/e13ff81487f494d15990a330747f2b8453c09def/lib/pf/UnifiedApi/Controller/Config/System.pm#L99-L103

**Comment by satkunas** [comment]
![Screen Shot 2022-08-12 at 10 56 39 AM](https://user-images.githubusercontent.com/3904468/184382884-f8477082-4352-42b5-bd32-65a62f3cb69b.jpg)

Confirmed to be working in #6855
