### ISSUE TITLE
Fingerbank double error message

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#711]
If you search for something not existing in fingerbank, the error message show twice.
![error-fingerbank](https://cloud.githubusercontent.com/assets/9321079/8207539/36adb8a6-14d0-11e5-9ef8-51dbf9e32d6d.png)

**Comment by jrouzierinverse** [comment]
Fixed in #a424dd6006f2175aae081d2847d8192f6024b2e8
