### ISSUE TITLE
ISO Installer GRUB path

### ISSUE THREAD

**Issue by jwillis44** [inverse-inc/packetfence#7113]
## Error at end of installer GRUB Fails

When installing using the ISO, if device is not /dev/sda grub-install fails.

![image](https://user-images.githubusercontent.com/21270623/184951004-191c23c7-19de-42ec-b980-408c141cbc5b.png)

## Using devices other then /dev/sda fails

Using XCP-NG as hypervisor, devices are enumerated as /dev/xvd[a-z] 

![image](https://user-images.githubusercontent.com/21270623/184950896-3e78d2c8-f11c-459c-88df-a762d0231ebf.png)

**Comment by julsemaan** [comment]
Not sure we can handle this without distributing 2 different ISOs. We'll have to see if the Debian preseed will allow handling multiple cases

**Comment by jwillis44** [comment]
Is the preseed file in the GitHub project? I can take a look at it.

I'm going to try it installing using UEFI and see if the first option may be enabled to automatically install to the UEFI partition.

Debian Preseed Docs: <https://www.debian.org/releases/stable/example-preseed.txt>

```
### Boot loader installation
# Grub is the boot loader (for x86).

# This is fairly safe to set, it makes grub install automatically to the UEFI
# partition/boot record if no other operating system is detected on the machine.
d-i grub-installer/only_debian boolean true

# This one makes grub-installer install to the UEFI partition/boot record, if
# it also finds some other OS, which is less safe as it might not be able to
# boot that other OS.
d-i grub-installer/with_other_os boolean true

# Due notably to potential USB sticks, the location of the primary drive can
# not be determined safely in general, so this needs to be specified:
#d-i grub-installer/bootdev  string /dev/sda
# To install to the primary device (assuming it is not a USB stick):
#d-i grub-installer/bootdev  string default

# Alternatively, if you want to install to a location other than the UEFI
# parition/boot record, uncomment and edit these lines:
#d-i grub-installer/only_debian boolean false
#d-i grub-installer/with_other_os boolean false
#d-i grub-installer/bootdev  string (hd0,1)
# To install grub to multiple disks:
#d-i grub-installer/bootdev  string (hd0,1) (hd1,1) (hd2,1)
```

**Comment by julsemaan** [comment]
This is the preseed file used for the ISO:
https://github.com/inverse-inc/packetfence/blob/devel/ci/debian-installer/preseed.cfg.tmpl

**Comment by jwillis44** [comment]
UEFI does not seem to be an option with the ISO.

I did create a pull request # 7117 if interested in testing using d-i grub-installer/bootdev  string default

**Comment by jwillis44** [comment]
I rebuilt the ISO using the "string default" in the preseed.cng installed without issue.

**Comment by trs80** [comment]
FWIW the ISO needs rebuilding to work with UEFI. Per https://wiki.debian.org/RepackBootableISO I extracted the iso to /tmp/pf, and ran the below, then I was able to boot it inside VMware with UEFI.

```bash
xorriso -as mkisofs \
  -r -V 'PF11.2JRA' \
  -o /tmp/pf-11.2-rebuild.iso \
  -J -joliet-long \
  -b isolinux/isolinux.bin \
  -c isolinux/boot.cat \
  -boot-load-size 4 -boot-info-table -no-emul-boot \
  -eltorito-alt-boot \
  -e boot/grub/efi.img \
  -no-emul-boot -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
  /tmp/pf
```
