### ISSUE TITLE
Fingerbank error when accessing combinations

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#712]
When accessing : 
https://172.20.20.109:1443/admin/configuration#config/fingerbank/combination

```
Jun 17 09:34:17 httpd.admin(13995) ERROR: Caught exception in pfappserver::Controller::Config::Fingerbank::Combination->list "Can't use string ("Could not find any 'Device' entr") as a HASH ref while "strict refs" in use at /usr/local/fingerbank/lib/fingerbank/Base/Schema/Combination.pm line 31." (pfappserver::PacketFence::Controller::Root::end)
```

**Comment by jrouzierinverse** [comment]
@dwlfrth can you look at this this a bug in fingerbank

**Comment by jrouzierinverse** [comment]
Can you check the commit I did in fingerbank for this issue

**Comment by dwlfrth** [comment]
https://s-media-cache-ak0.pinimg.com/236x/96/f7/2d/96f72d9392ec8c8df7b7270edcab8235.jpg

**Comment by jrouzierinverse** [comment]
Meanwhile in florida. 
![image](https://cloud.githubusercontent.com/assets/2727473/8211175/a91de5f6-14e3-11e5-82e3-c0d0fa410f44.png)
