### ISSUE TITLE
On upgrade the db stop in certain condition

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7125]
**Describe the bug**
When you upgrade packetfence, it happen that mariadb is stopped because pfconfig is stopped.

**To Reproduce**
1. apt update; apt upgrade
2. Check the logs and you will see that packetfence-mariadb is stopped

```
Aug 19 11:36:44 cluster2-1 packetfence[141774]: pf-mariadb(141774) FATAL: Cannot connect to service pfconfig! at /usr/local/pf/lib/pfconfig/cached.pm line 222.
                                                 (pfconfig::cached::_get_from_socket)
Aug 19 11:36:44 cluster2-1 pf-mariadb[141774]: Cannot connect to service pfconfig! at /usr/local/pf/lib/pfconfig/cached.pm line 222.
Aug 19 11:36:44 cluster2-1 systemd[1]: packetfence-mariadb.service: Main process exited, code=exited, status=111/n/a
Aug 19 11:36:44 cluster2-1 mysqld[142449]: 2022-08-19 11:36:44 0 [Note] /usr/sbin/mariadbd (initiated by: unknown): Normal shutdown

```

**Expected behavior**
The database should not stop on the upgrade (in case you are in a cluster it could cause an issue with the db)

**Proposed solution
in the begening of the upgrade we could add a flag like touch /usr/local/pf/var/upgrade_in_progress and add the logic in /usr/local/pf/lib/pfconfig/cached.pm line 222 to not die if the flag exist.

**Comment by julsemaan** [comment]
IMO, we could stop packetfence-mariadb during the upgrade process since when you upgrade a cluster, you're going to detach the nodes from the cluster anyway. Perhaps I'm missing something so I'll clarify with @fdurand but that seems like a better option if its compatible with clusters

**Comment by fdurand** [comment]
It´s not really on a upgrade but on a maintenance patch.
On an upgrade, it make sense to stop the db but just install the latest package of the same version it doesn´t make sense to stop it.

**Comment by julsemaan** [comment]
It should be fixed by 9a751d6295149fe552e5aec2184416a537609b23

Leaving it opened so we can have a confirmation of the fix across a few days of doing upgrades

**Comment by fdurand** [comment]
i am testing it right now

**Comment by fdurand** [comment]
it didn't worked yesterday but it´s because pf-mariadb was using the old code (it was not restarted). Did the test this morning with pf-mariadb started with the patch and worked successfully.
