### ISSUE TITLE
Perform checkup in admin GUI returns an error about captiveportal_modperl_require.pl won't compile.

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#713]
Seems to come from a permission issue on the /usr/local/fingerbank/logs/fingerbank.log file.

```
su - pf -c 'perl -c /usr/local/pf/lib/pf/web/captiveportal_modperl_require.pl 2>&1'
```

returns

```
Can't open /usr/local/fingerbank/logs/fingerbank.log (Permission denied) at /usr/local/share/perl5/Log/Log4perl/Appender/File.pm line 124.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/web/captiveportal_modperl_require.pl line 14.
```

Able to fix with

```
chown fingerbank.fingerbank /usr/local/fingerbank/logs/fingerbank.log
chmod g+w /usr/local/fingerbank/logs/fingerbank.log
```

Will check packaging.

**Comment by jrouzierinverse** [comment]
chmod g+s /usr/local/fingerbank/logs/
chmod g+w /usr/local/fingerbank/logs/fingerbank.log

**Comment by dwlfrth** [comment]
...

**Comment by jrouzierinverse** [comment]
You should ensure that any file created in the directory fingerbank/logs will have the group fingerbank

**Comment by julsemaan** [comment]
Is this fixed @dwlfrth ?

**Comment by dwlfrth** [comment]
Requires fingerbank new package

**Comment by julsemaan** [comment]
Was the new fingerbank package released with 5.3.1 ?

If not could we release the updated package separately ?

**Comment by louismunro** [comment]
It was not part of it. 5.3.1 is maintenance only.

**Comment by jrouzierinverse** [comment]
Has this been fixed?

**Comment by louismunro** [comment]
No. Stil present in most recent build.
To be fixed please.

**Comment by louismunro** [comment]
Not fixed. 
I have fingerbank-1.0.4-7.1.noarch and it's still there.

**Comment by dwlfrth** [comment]
Should be fixed in 1.0.4 at PacketFence 5.4 release time.
One use case might still break it, if /usr/local/fingerbank/logs/fingerbank.log is being created by root (which may be the case with some PacketFence daemons that are running as root)

**Comment by jrouzierinverse** [comment]
Just set the group to fingerbank in the log4perl config.

http://search.cpan.org/~mschilli/Log-Log4perl-1.46/lib/Log/Log4perl/Appender/File.pm

**Comment by dwlfrth** [comment]
There should not be any remaining "use cases" in which it applies...
