### ISSUE TITLE
v12: better distinction between fields and values

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7130]
**Describe the bug**
When you look at a node on RADIUS audit log using new button available (thanks @satkunas !!), distinction between field and value is not really clear:

![image](https://user-images.githubusercontent.com/10830260/186131719-b5b9fb49-aadc-422b-a657-830fdbbb1695.png)

**Expected behavior**
I would expect to have Device {Class,Manufacturer,Type}, Computer name and Owner} fields in bold to differentiate field from value.

**Additional context**
It's an enhancement so it can be postpone but I suppose it doesn't require a lot of changes.

**Comment by satkunas** [comment]
![Screen Shot 2022-08-23 at 8 07 48 AM](https://user-images.githubusercontent.com/3904468/186154109-08ac8339-193d-495a-8b1b-810f30e0e57b.jpg)

The auditing pages utilize the same fonts. Do we also need to change these as well, or is left/right easier to consume than top/bottom?

**Comment by nqb** [comment]
IMO, left/right is more easy to read.

**Comment by satkunas** [comment]
IMO, expanding this modal so that the fields are left/right will take up too much horizontal space.

**Comment by nqb** [comment]
I agree, I will let you choose the best option.
