### ISSUE TITLE
jquery-1.11.3.min.js is vulnerable to XSS

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7131]
**Describe the bug**
`html/common/jquery-1.11.3.min.js` is loaded by `html/captive-portal/templates/layout.html` when you go on captive portal and functions are used by JS files used on captive portal.

This library is vulnerable to XSS. We need to upgrade to 3.5.0 at least.

**Comment by satkunas** [comment]
See 0418b02867898a5c4a542faf2030e0e13115eff7
