### ISSUE TITLE
v12: autoregistration through a security event is failing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7132]
**Describe the bug**
I ran `security_events` scenario on a Debian 11 system and autoregistration is not working.

- Security event is correctly created
- DHCP requests are seen by PacketFence

It looks like there is an issue to look into Fingerbank database from httpd.aaa daemon (see [sec-event.log](https://github.com/inverse-inc/packetfence/files/9403666/sec-event.log))

Fingerbank packages:
```
root@pfdeb11dev:/usr/local/pf/logs# dpkg -l | grep fingerbank
ii  fingerbank                                               4.3.1+20220616184019+565822116+0011+v4~3~1+bullseye1                   all          fingerbank
ii  fingerbank-collector                                     1.4.0-4                                                                amd64        fingerbank
```

**Comment by julsemaan** [comment]
Weird, I was able to run it successfully but it was via pfqueue.

Could you post the security event config too?

I'll still fix the permission issue but I want to make sure your config works too when I test it

**Comment by nqb** [comment]
```ini
[88888888]
enabled=Y
target_category=headless_device
actions=autoreg,role
access_duration=5D
trigger=dhcp_fingerprint::276
desc=Test DHCP autoreg venom
```

**Comment by julsemaan** [comment]
It seems like it works with 'Device' == 'XYZ' but not with 'DHCP Fingerprint' == 'XYZ'. I'll dig into it

**Comment by julsemaan** [comment]
Actually, my bad, it should now be working when using the latest devel+fingerbank-4.3.2

If it's not, let me know and I'll dig deeper

**Comment by nqb** [comment]
Integration test passed.
