### ISSUE TITLE
v12: Auditing: MAC address overlay issue 

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7134]
![image](https://user-images.githubusercontent.com/5261214/186237554-dc720db0-cb10-4c1e-aca1-94738f779c71.jpeg)

**Comment by lzammit** [comment]
[root@cluster1 pf]# rpm -qa packetfence
packetfence-11.3.0-20220824155907.621927854.0008.devel.el8.x86_64

![image](https://user-images.githubusercontent.com/5261214/186489347-85710cd3-b202-44fc-b803-9e12647e41d8.jpeg)

**Comment by satkunas** [comment]
I'm not able to reproduce. Using latest devel.

There should be no text-wrap within each of the columns. Reducing the width of the table to less than the minimum required width from all the columns will cause an overflow on the right-side.

![Screen Shot 2022-08-25 at 12 51 12 PM](https://user-images.githubusercontent.com/3904468/186727533-729f640e-48a7-43aa-846d-174388e66af3.jpg)
