### ISSUE TITLE
Install/update should fail if manage-images.sh fails at any step

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7148]
**Describe the bug**
I had an upgrade fail in a weird way where manage-images.sh wouldn't be able to pull some of the images (issue with ghcr.io I think) but it did prune images at the end.

We need to make it so that if **any** step of the manage-images.sh fails, it makes the packaging install/upgrade fail immediately. Otherwise you get weird unrelated issues like pfconfig connection failures because that service fails to start.

**Comment by nqb** [comment]
On which OS did you got that issue ?
Could you provide log of upgrade (/var/log/dnf.rpm.log or /var/log/apt/term.log) ?

I already expect `manage-images.sh` to fail at first error due to `-o errexit` but perhaps Docker doesn't exit with an error code when pull timed out.

What I'm sure however it that your packaging doesn't stop at first error.
A possible solution could be to make packaging stop if only manage-images.sh failed.

**Comment by julsemaan** [comment]
AFAIK, a Debian postinst will fail if manage-images.sh fails (or any other scripts fails)

I'll retest this case by turning of internets to my machine during the pull and I'll report what happens

**Comment by nqb** [comment]
Test I did on a RHEL:
- upgrade an existing server
- shutdown interface (to simulate an Internet timeout)

Results:
```
Thu Aug 25 20:19:11 UTC 2022 - Images detected:
- api-frontend
- fingerbank-db
- haproxy-admin
- haproxy-portal
- httpd.aaa
- httpd.admin_dispatcher                                                                                                                                                - httpd.dispatcher                                                                                                                                                      - httpd.portal                                                                                                                                                          - httpd.webservices                                                                                                                                                     - pfcmd
- pfconfig                                                                                                                                                              - pfconnector
- pfcron                                                                                                                                                                - pfperl-api                                                                                                                                                            - pfpki                                                                                                                                                                 - pfqueue
- pfsso                                                                                                                                                                 - proxysql
- radiusd-acct                                                                                                                                                          - radiusd-auth
- radiusd-cli
- radiusd-eduroam
- radiusd-load-balancer
dial tcp: lookup ghcr.io on 192.168.121.1:53: dial udp 192.168.121.1:53: connect: network is unreachable
FirewallD is not running
```

=> RPM installation finished but `manage-images.sh` has stopped during pull and doesn't continue after.

I also tested this command with network shutdown:

```
# docker pull -q ghcr.io/inverse-inc/packetfence/api-frontend:latest || echo "KO"
Error response from daemon: Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.121.1:53: dial udp 192.168.121.1:53: connect: network is unreachable
KO
```

=> So `manage-images.sh` should stop correctly.

**Comment by nqb** [comment]
I will see how we can stop RPM postinstallation if `manage-images.sh` failed.

**Comment by nqb** [comment]
What I tried today on EL8:

```diff
diff --git a/rpm/packetfence.spec b/rpm/packetfence.spec
index d560d1a82ec..78204054c94 100644
--- a/rpm/packetfence.spec
+++ b/rpm/packetfence.spec
@@ -720,7 +720,8 @@ echo "Restarting rsyslogd"
 /bin/systemctl enable docker
 /bin/systemctl restart docker
 # get containers image and tag them locally
-/usr/local/pf/containers/manage-images.sh
+/usr/local/pf/containers/manage-images.sh || \
+    ( echo "Unexpected error in manage-images.sh" && exit )
 
 rm -rf /usr/local/pf/var/cache/
 /usr/bin/firewall-cmd --zone=public --add-port=1443/tcp
```

=> It doesn't help. Installation didn't stop. Once I hit `Ctrl+C`, I can see these messages:

```
[1661850717.84599] Failed to connect to config service for namespace interfaces::management_network(), retrying
Can't connect to pfconfig on containers-gateway.internal:44444 : Connection refused
[1661850717.94684] Failed to connect to config service for namespace interfaces::management_network(), retrying
Can't connect to pfconfig on containers-gateway.internal:44444 : Connection refused
```

Regarding behavior of `%post` and `%pre`, see: https://access.redhat.com/solutions/1135493
For me, it's by design that `%post` will not stop.

**Comment by julsemaan** [comment]
One thing we could do (without saying its clean) is to check for the return code of manage-images.sh in an 'if' block and put everything that depends on its success in there so that it at least completes faster

**Comment by nqb** [comment]
I will try that solution.
