### ISSUE TITLE
v12: ISO installer failed because Docker is not running

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7155]
**Describe the bug**
When you use ISO installer, `packetfence` packages are installed during ISO setup (Step: Install software). Even if Docker is installed, this service is not started. We can see following messages in `/var/log/syslog`:

```
Running in chroot, ignoring command 'restart'
```

Consequently, pull of Docker images (through `manage-images.sh`) is failing and ISO installer failed.

**Comment by julsemaan** [comment]
There is likely a way to pull without the docker daemon but it may be painful to implement.

For example, we could use podman to pull the images and then place them in /var/lib/docker.

Otherwise, perhaps the docker daemon could easily run in a chroot
