### ISSUE TITLE
v12: ipset sets are not populated

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7157]
**Describe the bug**
When I run inline L3 Venom tests, device:
* got an IP address through DHCP
* is able to communicate with PacketFence server

However, it's not present in pfsession_Unreg ipset set.

**To Reproduce**
1. Run inline/l3 Venom tests

**Expected behavior**
pfsession_Unreg should have a record for device.

**Additional context**
* pfipset is correctly started
* iptables rules looks good

**Comment by nqb** [comment]
Same on inline L2.

**Comment by nqb** [comment]
The behavior is the same on EL8 and Debian 11.

**Comment by julsemaan** [comment]
I pushed a fix related to the passthroughs and the broken communication with pfipset for passthroughs. The same fix should apply for inline

**Comment by nqb** [comment]
Thanks @julsemaan, I will retest ASAP.

**Comment by nqb** [comment]
Looks like the fix help to get ipset on L3 but there is still some issues on L2. I will look more in details.

**Comment by nqb** [comment]
Ignore my previous comment, issue solved.
