### ISSUE TITLE
API users should be based of "local" users

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#716]
Security speaking, having a unique user/pass for webservices / api calls is not "the best".
Should be able to add an "admin action" as "SET_API_ACCESS" with the different values of api access and match on theses for api access.

**Comment by dwlfrth** [comment]
Also, notion of key to avoid the usage of username / password all over the place

**Comment by extrafu** [comment]
+1

**Comment by julsemaan** [comment]
+1

**Comment by julsemaan** [comment]
This has been addressed via the API frontend
