### ISSUE TITLE
V12: Enabling 3000007  security event do nothing

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7165]
**Describe the bug**
When you enable 3000007 (random mac detection) and connect a device with a random mac address nothing happen.

**Comment by julsemaan** [comment]
I was able to get it to work on my setup with a random MAC

![image](https://user-images.githubusercontent.com/3857942/187946352-1dc697ec-0784-40e8-94d9-830b2f6c9a68.png)

**Comment by fdurand** [comment]
let´s keep the issue open, i will retest tomorrow in the HQ

**Comment by julsemaan** [comment]
Fingerbank wasn't enabled and we decided this needs Fingerbank to work
