### ISSUE TITLE
v12: DB upgrade script not repeatable

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#7171]
**Describe the bug**
The database updgrade script includes non-repeatable statements. These statements will need to be updated so they can Be replayed without error.

`INSERT INTO` => `INSERT IGNORE INTO`
`ALTER TABLE DROP` => `ALTER TABLE DROP IF EXISTS`
`ALTER TABLE ADD` => `ALTER TABLE ADD IF NOT EXISTS`

**Comment by julsemaan** [comment]
@jrouzierinverse, can you take a look at this one?
