### ISSUE TITLE
v12: pfcron cannot detect that it's the management node

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7172]
**Describe the bug**
pfcron is not doing anything in a cluster because it can't detect it has the VIP (because the VIP is outside of the container)

**Comment by julsemaan** [comment]
A simple solution is adding `--network=host` to pfcron. 

A cleaner solution would be to ask a service which has access to the host (like pfperl-api) if the current server has the VIP.

Not sure that at this stage of the release process we should go with a rework of the code

**Comment by fdurand** [comment]
for now we should use the dirty solution

**Comment by julsemaan** [comment]
Fixed via 4f9cb97c706e663d8dbfa352ee94c5c16bd7e2d8
