### ISSUE TITLE
We need to restart packetfence-mariadb during a pre-v12 upgrade

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7176]
**Describe the bug**
The path to the MariaDB UNIX socket has changed in v12. If we don't restart mariadb, no service can connect to the UNIX socket

It is a concern to restart it when applying the maintenance so we need to detect the usage of the wrong socket during the upgrade and restart it in this case (or with another approach for detection)

**Comment by julsemaan** [comment]
The socket path isn't changing on RHEL so the solution can be Debian specific

**Comment by julsemaan** [comment]
@fdurand has suggested we do a detection here: https://github.com/inverse-inc/packetfence/blob/devel/debian/packetfence.preinst#L86-L89

For that we'd need to bump the devel repo from 11.3 to 12.0. Will consult with @nqb and @fdurand on doing that bump and we can work on this fix after

**Comment by nqb** [comment]
@julsemaan,

At the moment, `packetfence-upgrade` package is build on `maintenance/11.2` and push to 11.2 repositories. So it should be possible to create a fix against `maintenance/11.2` branch to adjust `packetfence-upgrade` package. The detection related to MariaDB socket can be added directly in `devel` (11.3).

Then you can test your changes on a 11.2 setup using:

```
UPGRADE_TO=11.3 /usr/local/pf/addons/upgrade/do-upgrade.sh
```

If I'm not wrong this is how we dealt last time with such cases.
Let me know if I missed something.

**Comment by julsemaan** [comment]
This was bad and related to another issue

~~Your solution looks better than what I started (which failed). From what I can tell, we need to fix the socket in devel (that's done), and then add a `source /usr/local/pf/addons/full-upgrade/*.functions` in run-upgrade.sh after the packages are done upgrading in all maintenance/11.x~~

**Comment by nqb** [comment]
I tested an upgrade from 11.2 to 12.0 on Debian and I can confirm that fix works as expected.
