### ISSUE TITLE
11.2 -> 12.0 upgrade: Upgrade scripts use the wrong socket path for the DB

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7177]
**Describe the bug**
The socket path is changing in 12.0 but the functions in database.functions do not contain the new socket path.

We can't backport the new functions to 11.2 because that would break the import/export

One idea would be to use the hook `do-upgrade-post-package-upgrade.sh` to source the new `addons/functions/database.functions` file

**Comment by nqb** [comment]
Fix in b396a526ad4ad7fb2ec4da3aa6630135cd8cf6f9 to make builds working.

**Comment by nqb** [comment]
Fix: https://github.com/inverse-inc/packetfence/commit/e122a7b3d3236be44336875dc9f4007961fb495f

I tested an upgrade from 11.2 to 12.0 using automation of upgrades (on Debian) and DB upgrade works as expected.
