### ISSUE TITLE
v12(upgrade): bad handling of .dpkg-dist file for pfconfig.conf

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7182]
**Describe the bug**
While testing #7180 on node C (first step of the upgrade), I used `run-upgrade.sh` to upgrade packages, configuration and database on node C.

`packetfence-config` was not able to start at the end because `pfconfig.conf` was empty. Logs:

```
Handling .dpkg-dist conf/pfconfig.conf.dpkg-dist
Downloading https://raw.githubusercontent.com/inverse-inc/packetfence/e122a7b3d3236be44336875dc9f4007961fb495f/conf/pfconfig.conf.example
Moving conf/pfconfig.conf.dpkg-dist -> conf/pfconfig.conf and creating backup file conf/pfconfig.conf.upgrade-backup
Attempting a dry-run of the patch on conf/pfconfig.conf
checking file conf/pfconfig.conf
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED
Patching conf/pfconfig.conf failed. Will put the .dpkg-dist file in place. This should be addressed manually after the upgrade is completed. Press enter to continue
```

=> At the end, we got a `pfconfig.conf` which is empty (identical to `pfconfig.conf.example` installed by `packetfence-config` package) where we have kept `pfconfig.conf.upgrade-backup` 

I propose following solution: `pfconfig.conf` should not generate a `.dpkg-dist` file anymore because it's empty and everything is in `pfconfig.conf.defaults`.

**Comment by julsemaan** [comment]
I created a "dirty" patch for this in maintenance/11.2 through 5fef35a3066725095dbd87e337f68a34b247a920 and bf6281264f25e3719d9d266d5cbab65ebb12c2eb 

I noticed that the dpkg-dist behavior is there for other config files too (like authentication.conf). We should remove this behavior from the configuration files that are handled by our upgrade scripts

**Comment by nqb** [comment]
There is also this fix: https://github.com/inverse-inc/packetfence/commit/a481781d8260c955eb1a50e13cb8e966614c027c

**Comment by nqb** [comment]
`authentication.conf` currently generate a .rpmnew file.

I can add a workaround like @julsemaan did on `maintenance/11.X` by removing `.rpmnew` and `.dpkg-dist`. However, we added [new SMS providers](https://github.com/inverse-inc/packetfence/commit/a1e81876c9d63a39041ebf9d27670c379aed0722) since previous release so we need an upgrade script to add these new providers in `authentication.conf`.

@jrouzierinverse, can you prepare a script for that ? It looks like we did something similar in https://github.com/inverse-inc/packetfence/blob/devel/addons/upgrade/to-7.1-authentication-conf.pl

I would like to postpone #7183 to 12.1.0 because it's an important change.

**Comment by nqb** [comment]
@jrouzierinverse, I saw your script. However, it doesn't handle one case.
It looks like when a SMS source is created or modified through web admin, order of SMS carriers in `authentication.conf` can be reordered compared to what we have in `authentication.conf.example`. This is because SMS carriers are sorted alphabetically by frontend where in `authentication.conf.example`, they are sorted by id (like in the DB).

With current logic of your upgrade script, you will not update SMS sources which has been modified through web admin.

**Comment by nqb** [comment]
I pushed workaround for `authentication.conf` in `maintenance/11.X` branches.

**Comment by julsemaan** [comment]
@nqb, anything before we close this? Is the comment around ordering the SMS providers still relevant?

**Comment by nqb** [comment]
@jrouzierinverse should have adjusted the upgrade script.

**Comment by julsemaan** [comment]
@jrouzierinverse did the fix on the SMS carrier ordering, @julsemaan will confirm and close

**Comment by nqb** [comment]
d135b96e226c7082edee88da73a0848582cff7ef

**Comment by julsemaan** [comment]
@jrouzierinverse's script works as expecting (ordering of the values doesn't matter)
