### ISSUE TITLE
v11 & v12: build of RPM packages or http.dispatcher is broken due to a missing module

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7198]
**Describe the bug**

[Pipeline error](https://gitlab.com/inverse-inc/packetfence/-/jobs/3011612566#L373)

Results:
* v11.X maintenance packages has failed yesterday due to a missing package (`caniuse-lite/data/features/css-unicode-bidi`)
* v12 image didn't fail but it's certainly related to Docker cache

Related issues: 
* https://github.com/browserslist/caniuse-lite/issues/100
* https://github.com/postcss/autoprefixer/issues/1477

**To Reproduce**
* Rebuild packages on maintenance/11.X packages

or

* Rebuild httpd.dispatcher image without cache

**Additional context**
I will try this solution: "Verified with downgraded "caniuse-lite@1.0.30001393", builds are working."

**Comment by nqb** [comment]
Testing fix on maintenance/11.X: https://gitlab.com/inverse-inc/packetfence/-/pipelines/637564729

**Comment by nqb** [comment]
Fix is working on maintenance/11.X. I will push it to `devel` and `maintenance/11.X` branches (https://github.com/inverse-inc/packetfence/commit/30cc2f936ae8f8eae5391c7427e63daf6ce34df6)

@satkunas, could you confirm that web admin is not concerned by this issue due to presence of a `package-lock.json` ? I preferred to ask because there was no issue to build httpd.dispatcher on `devel`

**Comment by nqb** [comment]
I ran a [pipeline](https://gitlab.com/inverse-inc/packetfence/-/pipelines/637616604) with kaniko cache disabled to see if web admin build breaks.

**Comment by satkunas** [comment]
It doesn't seem right to have to add a new dev dependency. Try the following instead before building:

```
npm install -g npm
```

If this doesn't work try before building:

```
npm install -g npm
npm update
```

**Comment by nqb** [comment]
Trying to rebuild a branch, based on 11.2, without my fix: https://gitlab.com/inverse-inc/packetfence/-/pipelines/638942147

**Comment by nqb** [comment]
Changes reverted on `devel` and on `maintenance/11.X` because build is passing without that change.

I'm assigning this issue to @satkunas. He will work on having a `package-lock.json` to avoid this issue in the future.

**Comment by nqb** [comment]
@satkunas, could you check if we can backport to `maintenance/11.X` ?

**Comment by satkunas** [comment]
@nqb I don't see a need to backport this file. 

Earlier version have different dependancies, so each release would require its own unique `package-lock.json`. Since we haven't added any new npm packages in recent releases, the current `package-lock.json` in each branch should suffice. Considering this, I would wait-and-see if there are similar issues in any of the maintenance branches, and apply this recipe where we see this issue.

**Comment by julsemaan** [comment]
It looks like the commit updated the package-lock.json for the admin but not the captive-portal. Reopening.

This **should not** be pushed in devel before the 12.0 release though. Moving this to PF 12.1

**Comment by nqb** [comment]
I'm reopening to address https://github.com/inverse-inc/packetfence/pull/7215 and also to track maintenance backport.

**Comment by julsemaan** [comment]
From what I recall, I thought we said we weren't going to backport to the maintenance but I'm all good with that if @satkunas doesn't have any objections to it

**Comment by satkunas** [comment]
Package-lock rebuilt and pushed to `maintenance/11.0`, `maintenance/11.1`, `maintenance/11.2`, and `maintenance/12.0`.
