### ISSUE TITLE
Admin panel: multiple XSS vulnerabilities. 1 unauthenticated.

### ISSUE THREAD

**Issue by k3an3** [inverse-inc/packetfence#720]
There are several XSS vulnerabilities on the admin panel. Most notably:
1. An unregistered or registered client sets their hostname as HTML script tags containing a Javascript alert with text "XSS Found"
2. The host shows up under "Nodes" once served by DHCP. The script tags are correctly escaped in the list.
3. Once clicking on the MAC address of this host, a JavaScript alert message appears with text "XSS Found".

Similar XSS happens on other pages, such as violations, where a violation can be named the same as above and will cause a JS popup once the "delete" button is pressed. This is probably rampant throughout other admin menus also.

**Comment by keaneokelley** [comment]
Apparently GitHub doesn't like the fact that I put JS in my post. Just assume that it's there
