### ISSUE TITLE
Nodes with MAB get sometimes disconnected

### ISSUE THREAD

**Issue by mvalois** [inverse-inc/packetfence#7208]
**Describe the bug**
We found that devices for which MAB is enabled (they do not use 802.1X) in PacketFence get sometimes disconnect.
It appears to append when devices wake up from suspend.

Is there any settings that handle such things, like lease time or so?

How to investigate?

**Desktop (please complete the following information):**
 - OS: MacOS, snom phone
 - Browser Safari
 - Version 11.1.0

**Comment by julsemaan** [comment]
Please address configuration related questions to the PacketFence mailing list
