### ISSUE TITLE
web admin(nodes): bad display on Fingerbank tab

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7213]
**Describe the bug**
After I created a node manually, I got following display on Fingerbank tab of that node

![image](https://user-images.githubusercontent.com/10830260/191204144-762acef4-7c94-4917-865c-3bb7d2309004.png)

**To Reproduce**
1. Create a node
2. Click on 'Fingerbank' tab for that node

**Expected behavior**
Fields are correctly displayed

**Additional context**
Tested using chrome on maintenance/12.0

**Comment by satkunas** [comment]
Not able to reproduce. Was there any front-end JS errors in the console?

**Comment by nqb** [comment]
I didn't look. I'm closing and I will reopen if issue is still here.
