### ISSUE TITLE
The user name sent by SSO is not the same as the login user name

### ISSUE THREAD

**Issue by hnxtkai** [inverse-inc/packetfence#7221]
PacketFence 11.2.0+openldap+802.1x(TTLS)，Windows 10/11 or above terminals connect to wifi through 802.1X, single sign-on display login user name is "Anonymous", the actual login user name is "2022108"

- pfsso.log:
Sep 23 11:34:16 pf pfsso[1203]: t=2022-09-23T11:34:16+0800 lvl=info msg="Processing SSO Start" pid=1203 request-uuid=99947e63-3af0-11ed-8896-2a8c96a35bcc username=anonymous ip=10.8.66.32 mac=cc:f9:e4:98:b1:8d role=DianQ firewall-id=10.2.0.41
Sep 23 11:34:16 pf pfsso[1203]: t=2022-09-23T11:34:16+0800 lvl=info msg="Processing SSO Start" pid=1203 request-uuid=9a0d7895-3af0-11ed-8896-2a8c96a35bcc username=2012098 ip=10.8.86.82 mac=4c:7c:d9:ac:66:ec role=DianZ firewall-id=10.2.0.41
Sep 23 11:34:17 pf pfsso[1203]: t=2022-09-23T11:34:17+0800 lvl=info msg="Processing SSO Start" pid=1203 request-uuid=9a1bcb91-3af0-11ed-8896-2a8c96a35bcc username=2022182 ip=10.8.42.50 mac=0e:3f:f4:0b:9f:64 role=DaSJS firewall-id=10.2.0.41

- RADIUS Request:
User-Name = "2022108"
User-Password = "******"
NAS-IP-Address = 10.3.3.1
NAS-Port = 16777217
Service-Type = Framed-User
Framed-Protocol = PPP
Framed-MTU = 1450
Called-Station-Id = "44:1a:fa:67:99:80:CreatorStaff"
Calling-Station-Id = "cc:f9:e4:98:b1:8d"
NAS-Identifier = "YJF_1-26_32U_Wireless-AC_WX3510H"
NAS-Port-Type = Wireless-802.11
Acct-Session-Id = "000000042022092300461500029eab08100346"
Event-Timestamp = "Sep 23 2022 08:46:15 CST"
NAS-Port-Id = "0100000000000001"
FreeRADIUS-Proxied-To = 127.0.0.1
H3C-NAS-Startup-Timestamp = 1662553413
H3C-Ip-Host-Addr = "0.0.0.0 cc:f9:e4:98:b1:8d"
H3C-Product-ID = "H3C WX3510H"
EAP-Type = TTLS
Stripped-User-Name = "2022108"
Realm = "null"
Called-Station-SSID = "CreatorStaff"
PacketFence-UserNameAttribute = "2022108"
PacketFence-KeyBalanced = "14ad39c32f3617ebb1191f4fdcf2e3b2"
PacketFence-Radius-Ip = "10.2.0.25"
PacketFence-Outer-User = "anonymous"
PacketFence-UserDN = "cn=2022108,ou=å®æ½ï¼çµæ¸ ï¼,ou=çµå­æ¸ éäºä¸é¨,dc=chinacreator,dc=com"
Attr-26.25506.150 = 0x46239fe116f56258397da619817921ca395f545c39ec403defbd7b56bb22d25792cf87bc668710983628219e1884df1d
Attr-26.25506.133 = 0x00000001
SQL-User-Name = "2022108"

**Comment by julsemaan** [comment]
This has been fixed via this PR in PacketFence 12.0:
https://github.com/inverse-inc/packetfence/pull/7017

Upgrading to 12.0 will fix this issue
