### ISSUE TITLE
Issue with status pages on newly built cluster

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7223]
**Describe the bug**
We are seeing some strange messages on a newly built V12 cluster.

**To Reproduce**
1. Build cluster as per instructions in V12 guide.
2. Logon using primary admin
3. Select Status | System or Status | Endpoint
4. See error in pages attached screenshots
5. After some time we see the third screen shot.

**Screenshots**
![image](https://user-images.githubusercontent.com/95610834/192152705-ca712796-4f83-4052-9ac9-a0954b600ef8.png)

![image](https://user-images.githubusercontent.com/95610834/192152715-4281aa23-3fc3-4757-9704-3fc36cd5894e.png)

![image](https://user-images.githubusercontent.com/95610834/192224183-503d71d8-a7f1-40b5-b501-a7b1dbb520ea.png)

**Expected behavior**
Based on our non cluster V11.2 we expected to see something more like

![image](https://user-images.githubusercontent.com/95610834/192152742-dc091a41-b596-4991-ba29-75bc9ab4f377.png)

![image](https://user-images.githubusercontent.com/95610834/192152753-84f94ceb-44dd-4adf-a01c-91c336d88a09.png)

**Comment by julsemaan** [comment]
@fdurand, any insight on what should be checked?

**Comment by fdurand** [comment]
The better approach to troubleshoot is to use the inspect mode in chrome and see what are the errors in the network tab.

**Comment by PureOxygen-Dev** [comment]
Hi Team, we have noticed this disappeared after some time.  If I see it again I will capture some network traces..

**Comment by PureOxygen-Dev** [comment]
This has not reappeared on the current cluster.  we are building a new one in the coming weeks if we have the same issue I will raise it
