### ISSUE TITLE
Error message calling cluster maintenance using ZEN Build v12

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7225]
**Describe the bug**
We would like to activate or deactivate the node in the cluster using the maintenance script provided.

**To Reproduce**
Steps to reproduce the behaviour:
1. Logon as root
2. run /usr/local/pf/bin/cluster/maintenance
3. See error

**Output**
root@nloumfotaut001:~# /usr/local/pf/bin/cluster/maintenance
Can't locate Number/Range.pm in @INC (you may need to install the Number::Range module) (@INC contains: /usr/local/pf/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/local/pf/lib/pf/util.pm line 23.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/util.pm line 23.
Compilation failed in require at /usr/local/pf/lib/pfconfig/config.pm line 20.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfconfig/config.pm line 20.
Compilation failed in require at /usr/local/pf/lib/pfconfig/util.pm line 30.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfconfig/util.pm line 30.
Compilation failed in require at /usr/local/pf/lib/pfconfig/cached.pm line 36.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfconfig/cached.pm line 36.
Compilation failed in require at /usr/local/pf/lib/pfconfig/cached_hash.pm line 51.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfconfig/cached_hash.pm line 51.
Compilation failed in require at /usr/local/pf/lib/pf/cluster.pm line 19.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/cluster.pm line 19.
Compilation failed in require at /usr/local/pf/bin/cluster/maintenance line 39.
BEGIN failed--compilation aborted at /usr/local/pf/bin/cluster/maintenance line 39.

**Expected behavior**
Returns status of the current node maintenance or is able to put the node into or out of maintenance mode.

**Comment by nqb** [comment]
Fix backported to maintenance/12.0 and maintenance/11.X branches
