### ISSUE TITLE
Incorrect position of the restart window in SSL Certificates 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7229]
**Describe the bug**
We are using a 3 server cluster,  the popup window has lost the top when opening up to restart the haproxy-admin.

**To Reproduce**
1. Go to Configuration | System Configuration | SSL Certficates
2. Click Edit HTTP Certificate
3. Press Save
5. Wait for the settings to be rsynced
6. press the down arrow in the haproxy-admin
7. see the window has been lost under the tool bar at the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/95610834/192885347-5354fe4a-c625-47d2-b3b6-b1d64dcb7224.png)

**Expected behavior**
Window should behave like the haproxy-portal popup on the same page.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 105.0.1343.53 (Official build) (64-bit)

**Comment by julsemaan** [comment]
@satkunas, can you take a look at this issue?
