### ISSUE TITLE
Problem with MAC Auth on Extreme::Summit gear

### ISSUE THREAD

**Issue by dongreer** [inverse-inc/packetfence#724]
I have banged my head on this for a little while and figured it out when I went back to square one and spent some quality time with the Extreme docs.

XOS verions 15.2 and up, they have made a change of locking down all ports specified for MAC netlogin by default.  In order to get the old behavior, you must add the following line to the nelogin config:

configure netlogin add mac-list default ports 1-48

(I used the same port numbers for the port list as is used in the docs).

This will allow anything to connect to the port, but rely on PF to switch its vlan from the "temp" vlan to the appropriate working vlan.

**Comment by julsemaan** [comment]
Not sure I fully understand, is the line above fixing it properly.

If yes, I'll add it to the docs

**Comment by julsemaan** [comment]
Unless @dongreer answers in the next week, I'll close it
