### ISSUE TITLE
No DHCP Sensor for current supported Linux Systems

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7247]
**Describe the bug**
Within the documentation for packetfence we are looking to install the DHCP sensor to gain insight into the IP landscape of the hosts.    The documentationon only covers old versions of the CentOS.

**To Reproduce**
1. Go to https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_dhcp_remote_sensor
2. Review the options for the sensors
3. See error

**Expected Information**
A clear and concise description how to set up DHCP remote sensor based on V12 timelines.

**Additional Information**
We are unsure if this section of the documentation is still valid or something else should be done as the DHCP Sensor is so old.

**Comment by julsemaan** [comment]
It is in the roadmap to have this ability but for now if you need this, you'll have to rely on compiling it from scratch (it's in the same doc section)

Alternatively, you could use RADIUS accounting to do IP tracking instead of using the DHCP sensor

**Comment by PureOxygen-Dev** [comment]
Hi Julian,

We have enabled IP accounting but did not enable the update IPlog.  Done that now and hopefully that will solve the issue.

**Comment by julsemaan** [comment]
Double check your RADIUS secrets and also make sure 'Update iplog using the accounting' is enabled in 'System Configuration->Main Configuration->Advanced'

**Comment by PureOxygen-Dev** [comment]
Will open new issue is Accounting does not update IP info
