### ISSUE TITLE
Docker needs a specific configuration to pull images behind a proxy

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7249]
**Is your feature request related to a problem? Please describe.**
If your PacketFence server reach Internet through a proxy, installation will fail because pull of container images doesn't use system proxy.

https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

**Describe the solution you'd like**
Create a pre-start script in Docker which:
* detect if a proxy is defined on the system (through environment variables) 
* create an environment file read by Docker to use these variables

*Important*: ISO installer should also work if somebody configured a proxy on the system.

**Additional context**
Current workaround:
1. `systemctl edit docker`
2. 
```
[Service]
Environment="NO_PROXY=localhost, 127.0.0.0/8, ::1"
Environment="HTTP_PROXY=http://proxy.example.lan:9090"
Environment="HTTPS_PROXY=http://proxy.example.lan:9090"
```
3. `systemctl daemon-reload`
4. systemctl restart docker

**Comment by nqb** [comment]
It's necessary to use same recipe if you run Monit behind a proxy in order to have `update.sh` working. If you put your HTTP variables in `local-vars`, it will only work for `run-all.sh` script but not for `update.sh` itself.

**Comment by stegar123** [comment]
docker version 23.0 and bigger support   proxy env variable 

https://docs.docker.com/engine/reference/commandline/dockerd/#proxy-configuration
