### ISSUE TITLE
v11.0.0: webadmin is broken

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7254]
**Describe the bug**
A customer reported an issue after a fresh install on PacketFence 11.0.0 (latest maintenance patches: [pipeline](https://gitlab.com/inverse-inc/packetfence/-/pipelines/659644614)) on Debian 11.
I'm able to replicate issue on a EL8 system.

**To Reproduce**
1. Install a fresh Packetfence 11.0.0
2. Try to reach webadmin interface

**Screenshots**
![image](https://user-images.githubusercontent.com/10830260/194272262-7a928b35-b31f-4ec5-8aaa-a09253901be7.png)

**Expected behavior**
Web admin is working as expected

**Additional context**
I can provide an HAR if necessary.

I don't know if configurator is broken too.

**Comment by nqb** [comment]
According to my tests, 99195d47cca8d4b9337324131e897226295be0f1 (`package-lock.json` commit) is the culprit.

I installed packaged built on f8e46f6b9b648c782c63de5683e1869ec39b5641 (commit before `package-lock.json` commit) and the webadmin is working.

**Comment by nqb** [comment]
I did a quick test on `maintenance/11.1` (latest packages)
- configurator is working
- web admin is working after configurator

**Comment by satkunas** [comment]
Some npm dependencies for 11.0 are now considered "legacy".

When building on 11.0 you'll need to append  `--legacy-peer-deps` to `npm i` or `npm ci`. I've updated the package-lock.json and the Makefile target to reflect this requirement.
