### ISSUE TITLE
email authentication source not following system service restart approach 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7258]
**Describe the bug**
When configuring an email source and setting a value in the Host in activation link. The description below the text input box says changes to this will require a restart of haproxy.  Throughout the platform when service restarts are required the system offers a yellow box for the admin to restart from there.  This is not the case on this form.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Authentication Sources
2. Click New External Source and select Email 
3. Fill in details and especially fill in the "Host in activation link"
4. Press Create
5. See error as there is no warning and option to restart the service.

**Expected behavior**
As per the other areas of the application any services that needs to be restarted for an effect to happen should be presented to the administrator.

**Comment by nqb** [comment]
I'm updating labels because I see this request as an improvement, not a bug.
