### ISSUE TITLE
Packetfence ZEN v12/OpenWRT/CoovaChilli integration broken

### ISSUE THREAD

**Issue by ittsar** [inverse-inc/packetfence#7259]
Chromium 91.0.4472.124 64-bit or any browser for the matter

http://192.95.20.194/common/network-access-detection.gif?r=1665168014691 not reachable

Unable to detect network connectivity. Try restarting your web browser or opening a new tab to see if your access has been succesfully enabled.

OpenWrt 22.03.0, r19685-512e76967f
x86

root@OpenWrt:~# uci show chilli
chilli.@chilli[0]=chilli
chilli.@chilli[0].radiusnasid='192.168.1.1'
chilli.@chilli[0].radiussecret='secret123'
chilli.@chilli[0].radiusserver1='192.168.1.123'
chilli.@chilli[0].dhcpif='eth2'
chilli.@chilli[0].dns1='192.168.1.1'
chilli.@chilli[0].tundev='tun0'
chilli.@chilli[0].net='10.1.0.0/16'
chilli.@chilli[0].uamlisten='10.1.0.1'
chilli.@chilli[0].uamhomepage='http://10.1.0.1:3990/www/coova.html'
chilli.@chilli[0].wwwdir='/etc/chilli/www'
chilli.@chilli[0].uamserver='http://packetfence.lan/CoovaChilli'
chilli.@chilli[0].uamport='3990'
chilli.@chilli[0].ssid='test'
chilli.@chilli[0].swapoctets='1'
chilli.@chilli[0].interval='3600'
chilli.@chilli[0].ipup='/etc/chilli/up.sh'
chilli.@chilli[0].ipdown='/etc/chilli/down.sh'

Not seeing any RADIUS traffic in pcap nor is it redirecting back to AP's UAM page with any tokens.

Packetfence Version
12.0.0
GIT Commit ID
[a9578f5c4b3882c4dc925466a7cf3beadb2b8aa2](https://github.com/inverse-inc/packetfence/commit/a9578f5c4b3882c4dc925466a7cf3beadb2b8aa2)
Server Hostname
packetfence

**Comment by nqb** [comment]
Please use your GitHub template to open an issue (with steps to replicate) or use mailing-list if it's not a bug.

**Comment by ittsar** [comment]
What template do I need to use?

**Comment by zhiyangyang** [comment]
I also encountered the same situation in ZEN v15. May I ask if you resolved the issue at that time?
