### ISSUE TITLE
Cannot reopen edited captive portal files in the GUI PF 12.0

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7265]
**Describe the bug**
Editing the default captive portal files within the GUI is allowed but subsequent reopening the edited file shows the original unedited one.

**To Reproduce**
1. Go to A Standard Connection Profile
2. Click on Files tab and notice that there are no files edited by sliding the Show all files to show modified files only
3. unclick the slider to show all files.
3. Click on 'aup_text.html'  
4. Edit the file as required.
5. Press Save.
6. Notice the file icon now is dark gray.
7. Press the "Preview" button at the top.
8. Navigate to the AUP text.
9. You will see the updated text displayed.
10.  Click on 'aup_text.html' 
11. Error you see the original text prior to edits.

**Screenshots**
Unedited file

![image](https://user-images.githubusercontent.com/95610834/147255299-60d698a8-7305-49c9-a8c9-9fc547e205e8.png)

Edits made
![image](https://user-images.githubusercontent.com/95610834/147255432-07cd4e9f-f342-4eb3-90b9-4f8cf8d1e40d.png)

Preview
![image](https://user-images.githubusercontent.com/95610834/147255471-39a971a4-e5c6-4d82-98d9-0dfa5ae6cca0.png)

File displayed as edited
![image](https://user-images.githubusercontent.com/95610834/147255523-e2901077-9390-4b27-bb57-c20c73eb0fe1.png)

Reentered editor
![image](https://user-images.githubusercontent.com/95610834/147255573-7a03e6a1-7083-4a10-8db1-e35ecbe748fc.png)

**Expected behavior**
The edited text should be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium 
 - Version:  106

**Additional context**
This happens for all files not just the one example given.

This is a reoccurring bug #6800 and #6840

**Comment by PureOxygen-Dev** [comment]
@jrouzierinverse To my Suprise my edited files appeared today when I opened them in the editor so I saved a new edit and again yesterdays file appeared not the newly edited.

Looking at the network traffic it appears that the browser is getting the files from cache not reloading them from PF

![image](https://user-images.githubusercontent.com/95610834/195518252-a0858e96-d89e-4d14-b3dc-7ae4087b3cc2.png)

Hope this helps you with solving the issue.

**Comment by jrouzierinverse** [comment]
@satkunas can you look into this?

**Comment by satkunas** [comment]
I'm not able to reproduce on Chromium. I have a feeling that Edge has aggressive client-side caching.

I'll append a random query variable to the GET request in order to side-step the client-side cache.

**Comment by PureOxygen-Dev** [comment]
@satkunas 

I see the same behaviour on Chrome here

First Open
![image](https://user-images.githubusercontent.com/95610834/195855241-18b94174-4d41-4854-87b0-541dd7010a01.png)

Add "Test"
![image](https://user-images.githubusercontent.com/95610834/195855334-91e53427-5c0e-40da-affc-47c688c89650.png)

Check that is been server in preview
![image](https://user-images.githubusercontent.com/95610834/195855408-7070b3b7-3931-4c68-9668-78030f624a4a.png)

Reopen the aup
![image](https://user-images.githubusercontent.com/95610834/195855480-7d6a2437-c5b7-48e6-9b68-fa45becbbdac.png)

See the file is from disk
![image](https://user-images.githubusercontent.com/95610834/195855548-67e6601d-38de-40a3-88de-379cc033a799.png)

Chrome version installed.
![image](https://user-images.githubusercontent.com/95610834/195855669-cfc8238b-3e7c-42c0-a8bc-b486e5ed9c8c.png)

Not sure if it is to do with us running in a cluster not a single server. Let me know if there is something else, I need to provide, happy to help get to the bottom of it with you.

**Comment by satkunas** [comment]
@RHDHV-simon-sutcliffe I've pushed a fix to `maintenance/12.0`. It should be available to you after tonights nightly builds. Please re-test to see if this fix works. Otherwise we'll need to dig deeper to ensure there's R/W consistency in a cluster.

**Comment by PureOxygen-Dev** [comment]
Will do and let you know

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PureOxygen-Dev** [comment]
@satkunas Yep this appears to be working as designed now.  I did not want to say before giving it some testing and time.
