### ISSUE TITLE
ZEN V12 Potential Bug or misunderstanding of the Clone option within Filters. 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7266]
**Describe the bug**
Cloning a filter creates a link between the "answers" section meaning that changes within one filter and the clone is amended within both.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Configuration | Advanced Access Configuration | Filter Engines | Radius Filters
2. Click on the example filter "EXAMPLE_Ethernet-EAP-Accept"
3. Note the Answer Reply | Cisco-AVPair | url-redirect-acl=$user_role;url-redirect=${switch._portalURL}/cep$session_id
4. Press Cancel
5. On the example filter press "Clone" button
6. Change the name of the filter to "TestCloneIssue"
7. Change description to "Testing the cloning issue"
8. Add a value UserName | Equals | test
9. Update the Answers to be Reply | Cisco- AVPair | Test
10. Press "Create" then "Save" then "Close X"
11. Open "EXAMPLE_Ethernet-EAP-Accept" filter
12. See the Answer has been modified but the conditions have been unaffected.
13. Change the Answer back to Reply | Cisco-AVPair | url-redirect-acl=$user_role;url-redirect=${switch._portalURL}/cep$session_id
14. Press Save and "Close X"
15. Open Filter "TestCloneIssue"
16. Notice that the Answer has been modified to Reply | Cisco-AVPair | url-redirect-acl=$user_role;url-redirect=${switch._portalURL}/cep$session_id but the conditions have remained unaffected.

**Screenshots**

Example Filter in starting state
![image](https://user-images.githubusercontent.com/95610834/195282503-de81823b-6f65-40b0-84f6-f75d5b90319c.png)

Created Clone prior to pressing "Create" button
![image](https://user-images.githubusercontent.com/95610834/195283457-d9c008a7-2fa0-4b25-90df-c718dd86df1f.png)

Incorrectly Updated Example filter
![image](https://user-images.githubusercontent.com/95610834/195283982-47fa2ae5-4768-4201-9799-b2fc48ca5e02.png)

Updated Example filter back to be how it should be
![image](https://user-images.githubusercontent.com/95610834/195284677-d946b196-3614-434f-b701-a924cbba87cb.png)

Cloned filter changed by updated the example
![image](https://user-images.githubusercontent.com/95610834/195285229-d3db6b35-ee93-4b31-b396-5d18d07312c9.png)

**Expected behavior**
Clone should create an independent filter that is not linked to the original or these should be some visual link in the GUI to indicated this was intentional.

**Additional context**
I have only tested this with the Radius Filters, but it may also be the case with other clone actions with other filters.

**Comment by julsemaan** [comment]
@satkunas, can you take a look and see if it's expected
