### ISSUE TITLE
Non existent ip6tables-input.conf.inc.example file

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7269]
**Describe the bug**
Merge of #6970 assume that file `conf/ip6tables-input.conf.inc.example` exists (like for ip4tables) but that is not the case. We only have:

`conf/ip6tables-input-management.conf.inc.example`

#6970 has been backported to maintenance. Consequently, when using `sync` command on a cluster you got this error:

```
ERROR : Failed to sync file : /usr/local/pf/conf/ip6tables-input.conf.inc . Config file /usr/local/pf/conf/ip6tables-input.conf.inc doesn't exist at /usr/local/pf/lib/pf/api.pm line 715
```

=> Sync works even with this error.

@julsemaan, do you remember why we don't add this file with #6836 ?

If it has been done intentionally, I will remove reference to this file and backport to maintenance.

**Comment by julsemaan** [comment]
I think it's because we only support IPv6 on the management chain but I could be wrong

**Comment by nqb** [comment]
This is what I recalled too. I think I will go with the simpliest approach: remove reference to that file for now.

**Comment by nqb** [comment]
Fix backported to maintenance.
