### ISSUE TITLE
[PKI Feature request] Internal OCSP URL not reachable from external

### ISSUE THREAD

**Issue by brokoler** [inverse-inc/packetfence#7271]
I found the internal OCSP URL, but it's not reachable from my management IP (even if portal is added)
http://192.168.0.200:22225/api/v1/pki/ocsp
Is this the right syntax to reach the OCSP responder if my IP is set to 192.168.0.200?

**Is your feature request related to a problem? Please describe.**
The internal OCSP URL should be reachable from an external systems for OCSP validation, the URL scheme should be documented

**Describe the solution you'd like**
Make the OCSP URL reachable from external (if not possible already, I didn't find out the correct one)

**Comment by fdurand** [comment]
http://192.168.0.200/pki/ocsp should work.

**Comment by brokoler** [comment]
It's working! Thank you, maybe this should be documented somewhere
