### ISSUE TITLE
[PKI Feature request] Add option to generate CSR during CA creation

### ISSUE THREAD

**Issue by brokoler** [inverse-inc/packetfence#7279]
**Is your feature request related to a problem? Please describe.**
The internal PF PKI supports creating multiple Certificate Authorities, at the moment it's only possible to generate self-signed CA certificates and it's not possible to use PF PKI as a Sub CA in an existing PKI environment.

The implementation is already there for SSL Certificates used by PF for Radius and HTTP administrative access, maybe it can be achieved in a similar way.

**Describe the solution you'd like**
Adding an option to generate a CSR during creation of a CA, which can be exported and signed by a different CA, afterwards there should be an option to upload the matching certificate. Renewing the CA certificate should generate a new exportable CSR.

The feature could be added to:
Configuration -> Integration -> PKI -> Certificate Authorities -> New Certificate Authority:
Add a new formular field on the top to choose between "Self-Signed CA certificate" and "Create a Signing Request (CSR)"

**Comment by extrafu** [comment]
Related to #7284
