### ISSUE TITLE
mysql-probe service prevents pfcmd to continue during a cluster setup

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7289]
**Describe the bug**
When you follow instructions to setup a cluster in Cluster guide, at the step where it's time to start PF services on pf1 while `mariadb` is running with `--force-new-cluster` option, the `pfcmd` command seems to wait for something even if all PF services have been started.

It looks like `mysql-probe` service is not able to start in this configuration and it prevents `pfcmd` command to finish.

**To Reproduce**
1. Setup a cluster using instructions in cluster guide

=> At this [step](https://www.packetfence.org/doc/PacketFence_Clustering_Guide.html#_first_server_2), the `pfcmd` will never finish.

**Expected behavior**
`pfcmd` finishes.

**Additional context**
My current workaround is to wait start of all services then to break (using Ctrl+C) the `pfcmd` command.

**Comment by julsemaan** [comment]
Let's consider disabling mysql-probe since we use proxysql now

**Comment by nqb** [comment]
Not able to replicate issue after I setup a 12.0.0 cluster on Debian 11. Closing for now.
