### ISSUE TITLE
iptables traffic shaping per client

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#729]
Check if traffic shaping in inline is per client or per role.

**Comment by julsemaan** [comment]
So Sherlock, how was the investigation ? Can we close this ?

**Comment by dwlfrth** [comment]
Not yet Watson. I need to be able to test in some "specific" conditions (constant full speed internet connection)

**Comment by julsemaan** [comment]
inline traffic shaping is per role
