### ISSUE TITLE
do-upgrade.sh failed with a custom iptables.conf during v12.0.0 upgrade

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7298]
**Describe the bug**
If you modified your `iptables.conf` file manually, when you will upgrade to v12.0.0 using `do-upgrade.sh`, your `iptables.conf` will be kept as is and will prevent some services to start correctly during package upgrade.

This is because we force `apt` to keep existing files and we handle (later in the process) `.dpkg-dist` files. However, this logic doesn't work for v12.0.0 because we need to have iptables started before other services to permit communication with containers.

**To Reproduce**
1. Edit `iptables.conf` on a setup before v12.0.0
2. Upgrade to v12.0.0 using `do-upgrade.sh`

=> Your upgrade process will failed at some point because iptables is not started correctly.

**Expected behavior**
We should always install `iptables.conf` from packaging. Custom rules can go in `.conf.inc` files.

**Comment by nqb** [comment]
I think we just need to remove `iptables.conf` and `ip6tables.conf` from the list of configuration files.

Also I think this issue also apply on EL systems because `yum` will create a .rpmnew file with new content of new iptables.conf

**Comment by julsemaan** [comment]
I agree with that. iptables.conf and ip6tables.conf should not be modified anymore and users should be using the overrides
