### ISSUE TITLE
web admin: embedded documentation has a different look and links to sections doesn't work

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7305]
**Describe the bug**
If you try to open embedded documentation in web admin, you will notice a slight difference compared to what you have if you open HTML file (see screenshots below).

Also if you try to click to a link (on left panel) to access directly a section, nothing occured.

**To Reproduce**
1. Try to open documentation inside web admin

**Screenshots**
#### Inside web admin
![image](https://user-images.githubusercontent.com/10830260/198057542-e91abf33-be42-4879-8fe8-da3fa6b64bf1.png)

#### Outside web admin
![image](https://user-images.githubusercontent.com/10830260/198057901-c37f1587-0633-422f-86cd-a9cc90d04f26.png)

**Expected behavior**
- Display is identical
- When you click to a section in left panel, you are redirected to that section

**Additional context**
Tested on a development machine. I didn't look if it happens on a 12.0.0 release.

**Comment by nqb** [comment]
* `asciidoctor`  use to generated file **outside** web admin (on a EL system)

```
[root@172-105-93-187 pf]# asciidoctor --version
Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

* `asciidoctor`  use to generated file **inside** web admin:

```
## inside inverse-inc/packetfence/pfbuild-debian-bullseye docker image

# asciidoctor --version
Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]) (lc:US-ASCII fs:US-ASCII in:US-ASCII ex:US-ASCII)
```

**Comment by nqb** [comment]
Not the case on 11.2 (checked this morning).

**Comment by satkunas** [comment]
@nqb there are some custom CSS definitions when the documentation is loaded in the UI in order to match the current design. These rules are defined here: https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/src/components/AppDocumentation.vue#L160-L206

The issue with the guide links (href fragments) not working in FF has been fixed.

**Comment by nqb** [comment]
@satkunas, I tested https://github.com/inverse-inc/packetfence/commit/99c62e90257a3eac6f06dd277625eb76d986b952 but I'm still having an issue on Debian 11 and EL8.

In fact, the display is identical between Debian and EL8. Workaround reported by @julsemaan on #7334 works.

**Comment by satkunas** [comment]
I'm unable to reproduce this issue and it appears to work as expected on both Chrome and FF.
