### ISSUE TITLE
pfcmd fails silently on some command

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#731]
Try pfcmd node add 42:42:42:42:42:42 status="reg",pid="admin"

and it will not output a thing, which lead us to think that the command worked. Unfortunately, that's not the case. Removing the comma is giving the exact same output but it actually works.

When I don't get an output, I'm assuming it is working

**Comment by jrouzierinverse** [comment]
The example provided works. It will create a node that has a status of 'reg,pid=admin'

**Comment by jrouzierinverse** [comment]
@dwlfrth I want to close this issue because the problem stated is not what is happening.
Just to verify can do the following.

```
/usr/local/pf/bin/pfcmd node add 42:42:42:42:42:47 status="reg",pid="admin"
mysql -upf -p pf -e'select mac,status from node where mac="42:42:42:42:42:47";'
```

Let me know the results.

**Comment by dwlfrth** [comment]
I will leave it open since it is still a "bad behavior". I'll remove you from assignee so you can stop "worry" about it.

**Comment by jrouzierinverse** [comment]
What is a bad behavior?

**Comment by jrouzierinverse** [comment]
Derek can you clarify which bad behavior you are talking about there was two in this issue.

**Comment by jrouzierinverse** [comment]
The issue reported has been fixed in commit 157cc10d8faac518b41bcd89214e69365e082591

Derek can you verify if this is still an issue for you

**Comment by julsemaan** [comment]
@jrouzierinverse , is my commit about guest signup really fixing this ?

Also as @dwlfrth said, output on failure is a must.

Back in @louismunro time they could live with $? but the young guns these days require some text output

**Comment by jrouzierinverse** [comment]
Sorry the correct commit cfa56ef0

Yes I agree that should have an error message but I was stubbornly stuck on the fact that I could not replicate the fact that the we had a problem with node creation.

I was never able to replicate that issue on my side.

```
/usr/local/pf/bin/pfcmd node add 42:42:42:42:42:47 status="reg",pid="admin"
mysql -upf -p pf -e'select mac,status from node where mac="42:42:42:42:42:47";'
```

**Comment by dwlfrth** [comment]
```
Sep 28 09:57:46 pfcmd.pl(10618) WARN: database query failed with: Cannot add or update a child row: a foreign key constraint fails (`pfdevel`.`node`, CONSTRAINT `0_57` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON DELETE CASCADE ON UPDATE CASCADE) (errno: 1452), will try again (pf::db::db_query_execute)
```

**Comment by jrouzierinverse** [comment]
This has been solved I am going to close the issue and reopen another as a reminder to go through all the other pfcmd commands.

And add failure messages
