### ISSUE TITLE
How to change auth and acct port freeradius in packetfence

### ISSUE THREAD

**Issue by tetesh** [inverse-inc/packetfence#7310]
**Describe the bug**
My cisco switch is already set to a different radius and won't let me create a connection to a different radius if it has the same auth and acct ports

**To Reproduce**
`SCH21K(config-radius-server)#address ipv4  10.xx.xx.xx auth-port 1812 acct-port 1813  

%Server already exists with same address port combination.`

**Expected behavior**
How can i change the freeradius ports?

**Switch**
-  Cisco C9300-48T

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
