### ISSUE TITLE
dockerd is not started the same way on Debian and RHEL

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7316]
**Describe the bug**
### EL8
```console
[root@nqb-el8-12-1-fresh ~]# ps aux|grep dockerd
root         989  1.9  0.6 2695536 103384 ?      Ssl  12:35   0:02 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --iptables=false
```

### Debian
```console
root@localhost:~# ps aux|grep dockerd
root         552  3.8  0.6 2344664 107112 ?      Ssl  12:35   0:05 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```

=> Debian doesn't have `--iptables=false` option even if this option is defined in:

https://github.com/inverse-inc/packetfence/blob/2bcedab2ba55c774ebb964a581eeaf0ca5719b7d/packetfence.docker-drop-in.service#L13

**To Reproduce**
1. Install a fresh Debian 11 on 12.0.0
 
**Expected behavior**
dockerd is started the same way on both distributions.

**Additional context**
The `systemd` service mentioned above is not part of the `packetfence` package on Debian:

```
# dpkg -L packetfence|grep ^/lib|grep docker
/lib/systemd/system/packetfence-docker-iptables.service
```
I think we revert a change related to `packetfence-docker-iptables` service at some point but we missed to reinstall correct systemd service.

**Comment by nqb** [comment]
I missed to backport this commit to maintenance/12.0 but I don't recall if it was for a specific reason.

ATM, I don't see a reason to not backport this. Docker is restarted during postinstallation of Debian so change should be taken into account automatically.

Let me know your thoughts.

**Comment by julsemaan** [comment]
I'm good with this being cherry-picked in maintenance/12.0

**Comment by nqb** [comment]
Backport done.
