### ISSUE TITLE
Add support for Extreme EWC4110

### ISSUE THREAD

**Issue by pmcsintegra** [inverse-inc/packetfence#732]
We're having some trouble while integrating packetfence with Extreme EWC4110 (rev 09.15.03.0005). My test scenario:
-PacketFence as captive portal provider to an EWC wireless SSID;
-PacketFence as DHCP server to this connection;
-EWC sends a redirection URL to device, redirecting every URL to captive portal login screen. At this point, the username and password is provided and PacketFence performs the authentication;
-When PacketFence tries to send the approval information to EWC (change access role), we get this error on packetfence.log: "Unable to perform RADIUS Disconnect-Request: No answer from 192.168.19.251 on port 35666 at /usr/local/pf/lib/pf/util/radius.pm line 145. (pf::Switch::**ANON**)"

We've tried to use several switch types, but the most of them results in the same error.
The image below shows the EWC captive portal redirection configuration.
![image](https://cloud.githubusercontent.com/assets/13166193/8501397/5bbc46fa-217b-11e5-9d47-9b97c86cd6a2.png)

The image below shows the PF switch configuration.
![image](https://cloud.githubusercontent.com/assets/13166193/8501425/9f2dc77e-217b-11e5-896c-3d8d5c7ca49f.png)

Thanks

**Comment by pmcsintegra** [comment]
I was searching for some answers and found the EWC wireless controller integration manual (link below).
After reading this manual, I can tell you that this particular kind of wireless controller only accepts registration confirmation via post messages (not snmp or radius), calling approval.php (ref page 33 "Approving user").
Is it possible to create a new type of switch that uses this kind of confirmation?

https://extremenetworks.box.com/shared/static/de6zp0gok7ss4igu1dyf.pdf

**Comment by julsemaan** [comment]
It is indeed possible but requires the development of an additional switch module.

I'll do it in the upcoming days and post a patch here that you can test

**Comment by pmcsintegra** [comment]
Thanks a lot julsemann!

**Comment by julsemaan** [comment]
@pmcsintegra, it looks like we'll need the controller to be configured a bit differently then what you've done.

Please configure it as described in page 46 of the document as the other method is not secure as it seems to allow users to auto apply a role to themselves.

I'll work a bit more on the module and tell me if you have issues configuring your controller.

**Comment by julsemaan** [comment]
Never got any feedback
