### ISSUE TITLE
Modern Browsers rewriting network-access-detetion.gif scheme from http to https

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#7320]
**Describe the bug**
When using the captive-portal on https, the network-detection.gif uses a http scheme, which is being rewritten to https, thus causing a ERR_CERT_COMMON_NAME_INVALID.

**To Reproduce**
1. Open the Portal Preview from Admin UI -> Connection Profiles -> default
2. Complete the workflow to trigger a network detection
3. View the console debugger

**Screenshots**
In the captive portal DOM:

![Screen Shot 2022-10-28 at 4 12 39 PM](https://user-images.githubusercontent.com/3904468/198723928-03223b39-00a0-49b3-882b-9ae4f1a66cae.jpg)

http:// is being rewritten to https:// when the local scheme is https, thus causing a certificate error:

![Screen Shot 2022-10-28 at 4 10 41 PM](https://user-images.githubusercontent.com/3904468/198723647-82a7da14-d99f-4129-8e21-02f0a25cf909.jpg)

**Additional context**
This may not be a current issue with most devices that are using a stripped down webkit browser, but may become an issue in the future as these web browsers mature.

**Comment by PureOxygen-Dev** [comment]
@satkunas this also happens when you use a solution like Azure WFAS to front end PF.  HSTS is forced so the client also makes the call using HTTPS not HTTP. So I am glad your looking at tackling it.

**Comment by fdurand** [comment]
As discussed what can be done to support that:

- We could have the certificate that match the ip address 192.95.20.194 to fix the cert issue.
- We could define a fqdn for the captive portal detection and use pfdns to return the real ip address but not add it in the passthrough. So when the device will try to go on https://acme.com/... it will have a cert issue on the registration portal but it will have a answer when it will flip on the prod vlan.

**Comment by julsemaan** [comment]
The /access page uses plain HTTP specifically for that reason. If /access ends up using HTTPS, it will be problematic as described here.

When/if we decide to support HTTPS for /access, I think the cleanest solution is: 
> We could define a fqdn for the captive portal detection and use pfdns to return the real ip address but not add it in the passthrough. So when the device will try to go on https://acme.com/... it will have a cert issue on the registration portal but it will have a answer when it will flip on the prod vlan.

**Comment by satkunas** [comment]
Another possibility is to generate a valid cert for a unique fqdn specifically chosen for this purpose (eg: networkdetect.com), where we use cron to keep this cert up-to-date and give it away for free. Each PF instance would download this cert and setup DNS so networkdetect.com resolves to the management IP of the local PF instance. We could then replace the detection img src simply as `https://networkdetect.com`, and the PF admins don't need to worry about maintaining cert generation, or adding a SAN.

**Comment by dwlfrth** [comment]
Here for the zammitbug
