### ISSUE TITLE
Unable to click documentation links in admin interface

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7334]
**Describe the bug**
When I open the Installation Guide in the admin interface and try to click on section names, it doesn't jump to that section

**To Reproduce**
1. Open documentation
2. Select "Installation Guide"
3. Click on "3.1. Assumptions"

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/199484959-d6c00c1c-b9a6-42d9-8a4b-8bda70b000bf.png)

**Expected behavior**
It jumps to the right section

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version  106.0.2

**Comment by satkunas** [comment]
May be fixed in 99c62e90257a3eac6f06dd277625eb76d986b952

Please re-test and close if fixed

**Comment by julsemaan** [comment]
Didn't fix it but I'm downgrading the priority because it works when you open the doc in a new tab so there is an easy workaround for it

**Comment by nqb** [comment]
Duplicate of #7305

**Comment by julsemaan** [comment]
Closing in favor of #7305
