### ISSUE TITLE
Restarting iptables causes it to drop all INPUT+FORWARD

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7335]
**Describe the bug**
If the hostname of the server is not resolvable via /etc/hosts, then restarting iptables causes it to make it drop all of INPUT and FORWARD. Adding the hostname on the 127.0.0.1 line fixes that.

**To Reproduce**
1. Install PacketFence
2. Change the hostname during the configurator
3. Restart iptables

**Expected behavior**
iptables shouldn't misbehave because the host entry is missing

**Additional context**
This only applies when you change the hostname after installing the OS

**Comment by nqb** [comment]
Need to look into this at same time as #7403
