### ISSUE TITLE
12.1: Unable to perform email registration

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7336]
**Describe the bug**
The "Continue" button of the email registration never enables, even after inputing an email address

**To Reproduce**
1. Go in the portal
2. Select the email source
3. Input an email address
4. "Continue" button stays disabled

**Expected behavior**
Continue button enables

**Additional context**
Happens on my mobile device and also on my desktop when via the portal preview

**Comment by julsemaan** [comment]
Same thing happens with "Sponsor registration". Likely the same bug

**Comment by satkunas** [comment]
Fixed in  f5ebfcaccb47af996ba44471b7b00104bbc24184
