### ISSUE TITLE
ZEN V12 - SSID "Memory" in Connection Profiles 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7339]
**Describe the bug**
There appears to be a strange logic in the Connection Profiles when it comes to the filters and SSID.  We are unsure where the populated values comes from, you cannot remove them but adding one does not see to stick either.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Configuration | Policies and Access Control | Connection Profiles.
2. Click on "New Connection Profile" Button
3. Scroll down to Filter and Press "Add Filter" Button
4. Type = SSID (In our Case there appears to be two Populated SSID Values "One is used in another Connection Profile"
5. Option = Type TESTSSID and press "Click to Add New SSID"
6. Click the + and select Type = SSID
7. Option = drop down list you will not see the saved SSID
8. Add new value "SSIDBOB" and press "Click to Add New SSID"
9. Add Profile Name "TestSSIDBUG"
10. Profile Description "Test SSID BUG"
11. Press Create
12. Close Form
13. Click on "New Connection Profile" Button
14. Scroll down to Filter and Press "Add Filter" Button
15. Type = SSID
16. Press Dropdown we only see the two original SSID's not the additional two just saved.

**Screenshots**

SSID Values Pre Populated
![image](https://user-images.githubusercontent.com/95610834/199561297-0b1e5068-aef4-4889-8b0c-ffc553baa2ad.png)

Adding New SSID
![image](https://user-images.githubusercontent.com/95610834/199561007-df5ab747-a110-4052-926b-21029b9c355d.png)

Imaging showing saved SSID is not in the DropDown selection
![image](https://user-images.githubusercontent.com/95610834/199561600-d9bf98f7-57d6-4da8-b172-d94b52de5de2.png)

Second new connection profile filters not showing new SSID's just the old ones.
![image](https://user-images.githubusercontent.com/95610834/199562958-665bf523-cb57-45bd-a091-f598c2c8bfd6.png)

**Expected behavior**
Ability to add and remove SSID's or only have SSID's active in other profiles visible.

**Desktop (please complete the following information):**
 - OS: 
 - Browser Edge \ Chrome
 - Version 107

** We already had two so this may be a bug for the third etc **

**Comment by julsemaan** [comment]
When you add a new SSID, it's not added to the "memory", it just allows you to define any value you'd like

The pre-defined values come from the locationlog. So the moment one device connects to that SSID, it will be in the available values

**Comment by PureOxygen-Dev** [comment]
Thanks for the clarifications Jullian. Had no ideas where the values came from 😀
