### ISSUE TITLE
captive portal: some buttons are automatically pressed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7345]
**Describe the bug**
In some cases, when you need to confirm a choice using two buttons (Confirm/Cancel) on captive portal, it looks like the default button (Confirm) is automatically pressed.

**To Reproduce**
1. Enable default self service policy on default connection profile
1. Enable `portal `daemon on management interface
3. Try to reach /status on management interface
4. Trigger a lost or stolen security event on a device registered

=> Once you click on "Declare as lost or stolen", page is updated. You have two choices:
* Click on "Declare as lost or stolen",
* Click on "Cancel"

But web browser automatically select "Declare as lost or stolen".

**Expected behavior**
Let user confirm his choice.

**Additional context**
Certainly related to #7210 

EDIT: I did my tests with Firefox 106.0.5

**Comment by satkunas** [comment]
I'm seeing an error when trying to reproduce

```
Caught exception in captiveportal::Controller::LostStolen->index "Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/action.pm line 295."
```

**Comment by satkunas** [comment]
@nqb I'm not able to determine which template is used having a Cancel button. Can you send me the curl output at this point in the workflow?

`curl -k https://localhost:1443/portal_preview/loststolen/de:ad:b4:c0:ff:ee -o loststolen.html`

![Screen Shot 2022-11-08 at 3 02 38 PM](https://user-images.githubusercontent.com/3904468/200663544-cc464ef6-35d3-4dc0-8578-1c0201c7c187.jpg)
