### ISSUE TITLE
pf::Switch::Extreme::AP does not implement getVersion

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#7352]
**Describe the bug**
pf::Switch::Extreme::AP does not implement getVersion

The test network-devices/wireless.t
Do we update the test or implement getVersion?

**Comment by nqb** [comment]
I don't think getVersion is necessary here so I will go with update of the test.

**Comment by jrouzierinverse** [comment]
I looked into deeper it is used in SNMP. I just created a dummy implementation to avoid forgetting In the future.
If we ever had to add a new Switch where we had to support SNMP (I hope not)

**Comment by nqb** [comment]
Can we close this issue ?
