### ISSUE TITLE
Logging in on the status page is not possible

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7354]
**Describe the bug**
It's impossible to login on the status page due to the continue button never being enabled

**To Reproduce**
1. Go on https://yourcaptiveportal.zammitcorp.com/status
2. Put a username and password
3. Continue button never enables

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/200671490-1b5c0fdd-ff90-4921-b99c-da7160cb3411.png)

**Expected behavior**
Being able to login

**Comment by nqb** [comment]
Using Firefox 106.0.5 and EL8, it was able to use `/status`

**Comment by satkunas** [comment]
Please retry with changes from bbc6e86a76de84c8a45e3c1bd0c0f4b72578385f

**Comment by julsemaan** [comment]
Works as it should now!
