### ISSUE TITLE
Radius accounting stop doesn't end firewall sso session with dell os6 switches

### ISSUE THREAD

**Issue by heiko-ma** [inverse-inc/packetfence#7363]
The firewall session (I used the FortiGate connector) is not ended when packetfence receives an accounting stop packet. The creation of the sso session works perfectly:

**Successful sso:**
Nov 14 13:16:05 in19sv-nws18 packetfence_httpd.aaa[98374]: httpd.aaa(1902) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
Nov 14 13:16:05 in19sv-nws18 packetfence_httpd.aaa[99959]: httpd.aaa(1902) INFO: [mac:8c:04:ba:4d:7f:7e] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)
Nov 14 13:16:06 in19sv-nws18 pfqueue[99569]: pfqueue(99569) INFO: [mac:8c:04:ba:4d:7f:7e] Sending a firewall SSO 'Update' request for MAC '8c:04:ba:4d:7f:7e' and IP '10.23.81.5' (pf::firewallsso::do_sso)
Nov 14 13:16:06 in19sv-nws18 pfqueue[102059]: pfqueue(102059) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)

**Failed logout**
Nov 14 13:16:50 in19sv-nws18 packetfence_httpd.aaa[98374]: httpd.aaa(1902) INFO: [mac:8c:04:ba:4d:7f:7e] Unregistering 8c:04:ba:4d:7f:7e on Accounting-Stop (pf::api::handle_accounting_metadata)
Nov 14 13:16:50 in19sv-nws18 packetfence_httpd.aaa[98374]: httpd.aaa(1902) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
Nov 14 13:16:50 in19sv-nws18 packetfence_httpd.aaa[98374]: httpd.aaa(1902) WARN: [mac:8c:04:ba:4d:7f:7e] Use of uninitialized value $nas_port in concatenation (.) or string at /usr/local/pf/lib/pf/Switch.pm line 2468.

PacketFence receives the accounting stop packet and starts to unregister the node but the firewall session is never ended. I suppose this is due to this warning message:
Nov 14 13:16:50 in19sv-nws18 packetfence_httpd.aaa[98374]: httpd.aaa(1902) WARN: [mac:8c:04:ba:4d:7f:7e] Use of uninitialized value $nas_port in concatenation (.) or string at /usr/local/pf/lib/pf/Switch.pm line 2468.

Our Dell networking equipment (Dell N2000 series or Dell 3200 series) is running on OS6 which does not send the NAS-Port attribute on accounting requests (The NAS-Port-Id attribute is being send though). While this is normally not an issue it is when using firewall sso. We use some smaller cisco switches too, ending the sso session on accounting stop works fine there.

I'm not really sure if this is the real issue why the logout does not work but I think its worth looking into.

**Comment by julsemaan** [comment]
By default, PacketFence only performs SSO on DHCP, not accounting.

Make sure that `SSO on accounting` is enabled in in Configuration->System Configuration->Main Configuration->Advanced

![image](https://user-images.githubusercontent.com/3857942/201674755-84d7703a-8a35-447c-9b9a-4291e22f36f1.png)

If you're going to use accounting for SSO, you might as well also disabled `SSO on DHCP` while you're there

**Comment by heiko-ma** [comment]
After I configured the settings as below
![image](https://user-images.githubusercontent.com/64192965/201675965-7161a371-3b0d-4985-9ef4-4ef3c127f447.png)
the sessions is not being created anymore (so both login and logoff don't work) but on my cisco devices, it still works.

I suppose there is something wrong with the accounting request but I compared the two packages and the only differenc is the missing nas-port attribute

**Comment by julsemaan** [comment]
Make sure your accounting contains the Framed-IP-Address and the MAC address of the user in question

**Comment by heiko-ma** [comment]
Sorry for the late reply. As you suspected, the switch doesn't send the framed-ip-address due to a bug in the firmware. I'm currently working with the Dell support to resolve this issue.
