### ISSUE TITLE
Problem in configuration Cluster

### ISSUE THREAD

**Issue by RenatoPereira91** [inverse-inc/packetfence#7372]
**Describe the bug**
I following the cluster guide, but VIP IP don't work, the database replicate with success.

**To Reproduce**
Follow cluster guide, packetfence version 12.0

**Screenshots**
In the log I get the message
![image](https://user-images.githubusercontent.com/102453125/202188230-317937d7-a22b-4d2d-a4d1-83b917208164.png)

**Comment by nqb** [comment]
@RenatoPereira91, we need more details.
Could you provide:
- OS used
- At which specific step it failed (link to Cluster guide)

I will build a new cluster on v12.0.0 tomorrow so I can provide a feedback on this.

**Comment by RenatoPereira91** [comment]
Hi @nqb 

I get the error after the restart in the step 3.4.3:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/102453125/202191756-5a4a8618-76b3-4abb-ac01-d170c4eb0319.png">


I download the ISO of the web site:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/102453125/202191358-8b0815c5-d7f7-4ff4-afda-bbddcc4a7d79.png">

**Comment by nqb** [comment]
I built a 12.0.0 cluster on Debian using pristine Debian 11 without any issues.

**Comment by RenatoPereira91** [comment]
HI @nqb 

Do you have any idea because not start?

**Comment by nqb** [comment]
No. It could be plenty of things. Just follow our guide (like I did) and you should win.

**Comment by RenatoPereira91** [comment]
@nqb 

Ok, I gonna tried again but without L3 cluster.
