### ISSUE TITLE
vlan_filter overridden by fingerbank VOIP detection

### ISSUE THREAD

**Issue by lplpmc** [inverse-inc/packetfence#7384]
**Describe the bug**
Yealink device automatically set to voice role and "Voice Over IP" enabled even with vlan_filters.conf configuration

**To Reproduce**
Device initially follows vlan_filter and gets assigned to specified role but when fingerbank is refreshed on node it will revert configuration to voice/voice over ip options

Is there any other way to override this behavior?

vlan_filters.conf content:

[Detect_Yealink]
run_actions=enabled
status=enabled
description=Automatically set Yealink as ZOOM role
scopes=IsolationRole,RegistrationRole,RegisteredRole,InlineRole,AutoRegister,NodeInfoForAutoReg
role=zoom
condition=mac =~ "^(80:5e:c0).*"

**Comment by nqb** [comment]
Hello,
Could you run following command on your PF server:

```
curl -H "Authorization: Token `grep api_key /usr/local/fingerbank/conf/fingerbank.conf | awk -F '=' '{ print $2 }'`" https://localhost:4723/endpoint_data/MAC_ADDRESS_OF_DEVICE/details -k | python -m json.tool > yealink.json
```
then send yealink.json file to support AT inverse.ca with subject of email equals to "Github issue 7384".

Thanks.

**Comment by lplpmc** [comment]
[yealink.json.txt](https://github.com/inverse-inc/packetfence/files/10113786/yealink.json.txt)

@nqb file attached

I also tried the following vlan_filter in addition to the previously mentioned entry:

[Detect_Yealink_Fingerbank]
run_actions=enabled
status=enabled
description=Autoregister printers and scanners
scopes=IsolationRole,RegistrationRole,RegisteredRole,InlineRole,AutoRegister,NodeInfoForAutoReg
action.0=modify_node: mac, $mac, notes,  Yealink_Zoom_Device, role, zoom, bypass_role, zoom, voip, no
role=zoom
device_class=Android
bypass_role=zoom
node_info.voip=disabled
voip=no
condition=contains(fingerbank_info.device_fq, "VoIP Device/Yealink VoIP")

I noticed it'll set the notes and bypass role, but voice over ip checkbox remains enabled

**Comment by nqb** [comment]
Thanks.
Could you tell us what is this device (URL to the product) ?

**Comment by lplpmc** [comment]
> Thanks. Could you tell us what is this device (URL to the product) ?

@nqb - We're using the Neat Bar & Neat Pad's if I recall correctly 
https://www.yealink.com/en  and https://www.youtube.com/watch?v=DJvIhwYnmxQ  Our usecase is for zoom/microsoft teams meetings - and they are more video collaboration than 'voip' 

We do not want them to be on the same VLAN as our actual Cisco VOIP phones

Thanks,

**Comment by lplpmc** [comment]
Here is a bit more information on exact models used: 

Yealink A30 Zoom Room - https://www.yealink.com/en/product-detail/zoom-rooms-meetingbar-a30 - 
Yealink CTP18 Zoom Edition - https://www.yealink.com/en/product-detail/video-conferencing-ctp18 - 
Other models of interest: A20, A10, Roomcast

Example MAC addresses: 805e.c063.f997, 805e.c062.7eb8 

[yealink_805ec0627eb8.json.txt](https://github.com/inverse-inc/packetfence/files/10123851/yealink_805ec0627eb8.json.txt)
[yealink_805ec063f997.json.txt](https://github.com/inverse-inc/packetfence/files/10123852/yealink_805ec063f997.json.txt)

We also do have neatbars, but have recently switched to A30s and CTP18s

**Comment by lplpmc** [comment]
@nqb anything we can do here? Is there somewhere I can report misclassified fingerbank entries?

**Comment by julsemaan** [comment]
I took a look and the only data point sent to Fingerbank is the MAC address so the best educated guess it can take is that it's a Yealink VoIP device which is the most probable outcome for a MAC that is tied to that vendor.

We may have to revisit this since Yealink does seem to make more than just VoIP devices, I'll look into that

**Comment by julsemaan** [comment]
I adjusted this so that the MAC vendor is associated both to Yealink conferencing devices and VoIP. This means submitting only the MAC will provide a less precise result (hardware manufacturer) but it will not miscategorize it was VoIP

To fix this on your environment, do:
```
/usr/local/pf/bin/pfcmd cache fingerbank clear
```

Then, edit the problematic nodes and uncheck the VoIP flag and it shouldn't be coming back

**Comment by lplpmc** [comment]
So far so good! thank you!!
