### ISSUE TITLE
Online/Offline Status does not work on PacketFence 12

### ISSUE THREAD

**Issue by heiko-ma** [inverse-inc/packetfence#7386]
**Describe the bug**
When using PacketFence 12 or 12.1, the online/offline status does not work. Radius accounting messages are being sent and the same infrastructure worked with PacketFence 11.

The Log shows the following:
 **Authentication:**
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] handling radius autz request: from switch_ip => (10.23.16.33), connection_type => Ethernet-EAP,switch_mac => (f8:b1:56:94:ff:1a), mac => [8c:04:ba:4d:7f:7e], port => 1, username => "group\matthieh" (pf::radius::authorize)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Match rule autoregister_asap_devices (pf::access_filter::test)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Match rule autoregister_asap_devices (pf::access_filter::test)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Found authentication source(s) : 'group' for realm 'group' (pf::config::util::filter_authentication_sources)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Using sources group for matching (pf::authentication::match2)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Matched rule (Catch) in source group, returning actions. (pf::Authentication::Source::match)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Found authentication source(s) : 'group' for realm 'group' (pf::config::util::filter_authentication_sources)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Role has already been computed and we don't want to recompute it. Getting role from node_info (pf::role::getRegisteredRole)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Username was defined "group\matthieh" - returning role 'default' (pf::role::getRegisteredRole)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] PID: "group\matthieh", Status: reg Returned VLAN: (undefined), Role: default (pf::role::fetchRoleForNode)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] (10.23.16.33) Added VLAN 10 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
> Nov 28 17:53:27 in99sv-nws01 pfqueue[762438]: pfqueue(762438) INFO: [mac:unknown] Already did a person lookup for group\matthieh (pf::lookup::person::lookup_person)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) WARN: [mac:8c:04:ba:4d:7f:7e] No parameter defaultRole found in conf/switches.conf for the switch 10.23.16.33 (pf::Switch::getRoleByName)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] security_event 1300003 force-closed for 8c:04:ba:4d:7f:7e (pf::security_event::security_event_force_close)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
> Nov 28 17:53:27 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)

**Disconnection:**
> Nov 28 17:53:37 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Unregistering 8c:04:ba:4d:7f:7e on Accounting-Stop (pf::api::handle_accounting_metadata)
> Nov 28 17:53:37 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) INFO: [mac:8c:04:ba:4d:7f:7e] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
> Nov 28 17:53:37 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) ERROR: [mac:8c:04:ba:4d:7f:7e] Error releasing ip for 8c:04:ba:4d:7f:7e : 502 Proxy Error at /usr/local/pf/lib/pf/api/unifiedapiclient.pm line 218.
> Nov 28 17:53:37 in99sv-nws01 httpd.aaa-docker-wrapper[2741]: httpd.aaa(7) WARN: [mac:8c:04:ba:4d:7f:7e] Use of uninitialized value $nas_port in concatenation (.) or string at /usr/local/pf/lib/pf/Switch.pm line 2497.

**To Reproduce**
1. Plug in the device and let it authenticate
2. Review the node status in the web-ui

**Expected behavior**
The online/offline status is updated according to radius accounting.

**Comment by julsemaan** [comment]
This is addressed in our upgrade guide:
https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Upgrade_Guide.asciidoc#bandwidth-accounting-is-now-disabled-by-default
