### ISSUE TITLE
Problems with GUI at Configuration/Maintenance and Configuration/Expiration

### ISSUE THREAD

**Issue by istvanbernath** [inverse-inc/packetfence#739]
Most of the numeric fields can not be adjusted.

**Comment by louismunro** [comment]
We'll need more details than that.
Which version of PF? 
On what OS?

**Comment by louismunro** [comment]
Using which browser?

**Comment by istvanbernath** [comment]
Sorry about the late reply!

I've noticed this problem first after I've upgraded to 5.2.0
The two pages are fuzzy both with Firefox and Chrome.

Best Regards
Istvan

**Comment by louismunro** [comment]
Which distro? There are indications that this is not happening on RHEL and CentOS.

**Comment by istvanbernath** [comment]
I have two Debian Wheezy installations and both of them
has the same problem.

**Comment by louismunro** [comment]
All right.
We should have a fix in 5.3 which is due out in a few days.

## 

LM

**Comment by istvanbernath** [comment]
Brilliant!
Can't be any better!

Best Regards
Istvan

**Comment by julsemaan** [comment]
@louismunro or @istvanbernath 

Can the issue can be confirmed as resolved in 5.3 or 5.3.1 so we close this

**Comment by louismunro** [comment]
Fixed. Closing it.

**Comment by istvanbernath** [comment]
I've just checked it and the problem is now gone!
Thanks for your help!

Best Regards
Istvan
