### ISSUE TITLE
ZEN 12.1 Blocking Issue Captive Portal.

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7396]
**Describe the bug**
After upgrading from ZEN V12 to V12.1the captive portal for guests is not able to complete the flow. 

**To Reproduce Issue with Null Source**
1. Based on the portal design detailed below in the screen shots.
2. Get redirected the Captive Portal by the WLC
3. Click on 'Guest Access'
![image](https://user-images.githubusercontent.com/95610834/205016910-ce93163f-74a8-4200-be50-20225824ea65.png)
4. Click on Internet Day Pass (Null source)
![image](https://user-images.githubusercontent.com/95610834/205017097-bc6d7cfc-ebc4-48c6-baf8-c8c3fa9840a9.png)
5. Click on I accept the terms
![image](https://user-images.githubusercontent.com/95610834/205017270-9117d9c4-aa3a-4afa-a7c5-515eb688b8d6.png)
6. See Error (we now get this additional page) and the continue is not selectable
![image](https://user-images.githubusercontent.com/95610834/205017435-50c7ba3f-f6f3-48ba-a6b3-1583a19a6c07.png)

**To Reproduce Issue with Sponsor Source**
1. Based on the portal design detailed below in the screen shots.
2. Get redirected the Captive Portal by the WLC
3. Click on 'Sponsored Access Request'
![image](https://user-images.githubusercontent.com/95610834/205016910-ce93163f-74a8-4200-be50-20225824ea65.png)
5. Click on I accept the terms
![image](https://user-images.githubusercontent.com/95610834/205017270-9117d9c4-aa3a-4afa-a7c5-515eb688b8d6.png)
6. Complete the email and Sponsored email boxes
![image](https://user-images.githubusercontent.com/95610834/205018303-fbf749e5-1435-476b-8d35-5606ec4d5777.png)
7. See Error - Continue is not available.

**Supporting Screenshots**

* *Portal Design Images* *
![image](https://user-images.githubusercontent.com/95610834/205016002-487d7084-c999-49a8-bafb-641af409e60f.png)

* *Choice Design* *
![image](https://user-images.githubusercontent.com/95610834/205016241-a9e847fd-0722-4bf4-86f7-a3b4e14641f4.png)

**Expected behavior**
After Accepting the T&C with the Null Source the captive portal should move onto authorising access.

After entering the email and the sponsor in the Sponsored Access Request the Continue should be available and pressing should move onto authorising access.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 107.0.1418.62

**Additional context**
Both flows were fully operational prior to the update to 12.1, we have started to configure the admin-sso so I am unsure if there is any relation to this problem.

**Comment by nqb** [comment]
Hello @RHDHV-simon-sutcliffe,

Are you able to replicate this issue with Chrome or Firefox (in place of Edge) ?

**Comment by PureOxygen-Dev** [comment]
Hi @nqb same in chrome

**Comment by PureOxygen-Dev** [comment]
> Hello @RHDHV-simon-sutcliffe,
> 
> Are you able to replicate this issue with Chrome or Firefox (in place of Edge) ?

Hi @nqb did anyone get a chance to look at this, I have a call with Julian this afternoon scheduled if not?

**Comment by nqb** [comment]
Hello @RHDHV-simon-sutcliffe,

We have seen similar behaviors during our Q&A phase before 12.1 release but bugs were fixed.
Could you share your portal_modules.conf to see if we can replicate ?

@satkunas, could you look into this ?

**Comment by PureOxygen-Dev** [comment]
@nqb

**Comment by PureOxygen-Dev** [comment]
@nqb this was caused by old info in migrated portal files still referencing various libraries no longer used in 12.1.
