### ISSUE TITLE
Watch should be retired

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#740]
PF watch is worse than useless as it causes services to restart unnecessarily.
We should no longer support that feature.

People who want or need a watchdog process should use Monit or something like it.

**Comment by kkplein** [comment]
As a side note: deselecting "Send email" and "restart", clicking save, gives: "Success!". However, next time opening the same menu, nothing is actually saved.
(various browsers, pf 5.2.0 running on wheezy x64)

**Comment by julsemaan** [comment]
It has been
