### ISSUE TITLE
Captive-Portal with FortiGate does not work

### ISSUE THREAD

**Issue by heiko-ma** [inverse-inc/packetfence#7402]
When using the captive-portal functionality with FortiGates and FortiAPs, the authentication does work.
While the captive-portal auth itself does work, the fortinet specific login via http-request to fortigate leads to RADIUS rejects from packetfence.
The log message shows the following:

> Module-Failure-Message = "rest: Server returned:"
> Module-Failure-Message = "rest: {\"control:PacketFence-Request-Time\":1669912145,\"control:PacketFence-IfIndex\":\"external\",\"control:PacketFence-Connection-Type\":\"CLI-Access\",\"control:PacketFence-Switch-Id\":\"10.255.20.19\",\"control:PacketFence-Authorization-Status\":\"allow\",\"control:PacketFence-Switch-Mac\":\"d4:76:a0:d2:b9:50\",\"control:PacketFence-Switch-Ip-Address\":\"10.255.20.19\",\"Reply-Message\":\"Network device does not support this mode of operation\",\"control:PacketFence-Eap-Type\":0,\"control:PacketFence-UserName\":\"a0:51:0b:6a:47:b2\",\"control:PacketFence-Mac\":\"a0:51:0b:6a:47:b2\"}"
> SQL-User-Name = "a0:51:0b:6a:47:b2"

The output from packetfence.log is as follows:
> Dec 2 10:19:42 packetfence httpd.aaa-docker-wrapper[110944]: httpd.aaa(1855) INFO: [mac:a0:51:0b:6a:47:b2] handling radius autz request: from switch_ip => (10.255.20.19), connection_type => CLI-Access,switch_mac => (d4:76:a0:d2:b9:50), mac => [a0:51:0b:6a:47:b2], port => external, username => "group\*******" (pf::radius::authorize) Dec 2 10:19:42 packetfence httpd.aaa-docker-wrapper[110944]: httpd.aaa(1855) WARN: [mac:a0:51:0b:6a:47:b2] (10.255.20.19) Sending REJECT since switch is unsupported (pf::radius::_switchUnsupportedReply)

I looked at the corresponding file (/usr/local/pf/lib/pf/radius.pm) and found the following lines:

> sub _isSwitchSupported {
>     my ($self, $args) = @_;
>     my $logger = $self->logger;
> 
>     if ($args->{'connection_type'} == $WIRED_MAC_AUTH) {
>         return $args->{'switch'}->supportsWiredMacAuth();
>     } elsif ($args->{'connection_type'} == $WIRED_802_1X) {
>         return $args->{'switch'}->supportsWiredDot1x();
>     } elsif ($args->{'connection_type'} == $WIRELESS_MAC_AUTH) {
>         # TODO implement supportsWirelessMacAuth (or supportsWireless)
>         $logger->trace("Wireless doesn't have a supports...() call for now, always say it's supported");
>         return $TRUE;
>     } elsif ($args->{'connection_type'} == $WIRELESS_802_1X) {
>         # TODO implement supportsWirelessMacAuth (or supportsWireless)
>         $logger->trace("Wireless doesn't have a supports...() call for now, always say it's supported");
>         return $TRUE;
>     }
> }
> 
> =item * _switchUnsupportedReply - what is sent to RADIUS when a switch is unsupported
> 
> =cut
> 
> sub _switchUnsupportedReply {
>     my ($self, $args) = @_;
>     my $logger = $self->logger;
> 
>     $logger->warn("(" . $args->{'switch'}->{_id} . ") Sending REJECT since switch is unsupported");
>     $args->{'switch'}->disconnectRead();
>     $args->{'switch'}->disconnectWrite();
>     return [$RADIUS::RLM_MODULE_FAIL, ('Reply-Message' => "Network device does not support this mode of operation")]; }

As far as I can see, the FortiAP/FortiGate provides CLI-Access as connection type which is no known type to packetfence. Note that this only happens when the FortiGate tries to authenticate a user which came back through captive-portal authentication. Connections via the authentication checker in the Web-UI seem to work correctly.

**Comment by heiko-ma** [comment]
I troubleshooted this issue a bit more and found out, that the CLI-Access connection type is indeed a viable type for packetfence but gets treated as unsupported. 
The problem is that the authentication from the FortiAP/FortiGate (after the successful captive portal auth) is declared as a CLI_Access Connection.

**Comment by fdurand** [comment]
Can you paste the radius request coming from the fortigate ?

**Comment by heiko-ma** [comment]
I sniffered the traffic using tcpdump and exported the traffic as pcap:
![image](https://user-images.githubusercontent.com/64192965/206230594-20d74578-d2be-4c92-8d3d-04d7229507d8.png)

The request as how it is seen by packetfence is below:

> User-Name = "a0:51:0b:6a:47:b2"
> User-Password = "******"
> NAS-IP-Address = 10.255.20.19
> Service-Type = Login-User
> Framed-IP-Address = 10.23.87.5
> Called-Station-Id = "d4:76:a0:d2:b9:50:ASAP-Gast (Testing)"
> Calling-Station-Id = "a0:51:0b:6a:47:b2"
> NAS-Identifier = "IN19FW-0015"
> NAS-Port-Type = Virtual
> Acct-Session-Id = "0fa001b7"
> Event-Timestamp = "Dec  7 2022 11:35:52 CET"
> Connect-Info = "web-auth"
> Fortinet-Vdom-Name = "root"
> Fortinet-SSID = "ASAP-Gast (Testing)"
> Fortinet-AP-Name = "PU221ETF21002253"
> Stripped-User-Name = "a0:51:0b:6a:47:b2"
> Realm = "null"
> FreeRADIUS-Client-IP-Address = 10.255.20.19
> Called-Station-SSID = "ASAP-Gast (Testing)"
> PacketFence-KeyBalanced = "82ca871f42fbfecb44407d06a8699cd7"
> PacketFence-Radius-Ip = "10.20.10.55"
> Module-Failure-Message = "rest: Server returned:"
> Module-Failure-Message = "rest: {\"control:PacketFence-Request-Time\":1670409352,\"control:PacketFence-UserName\":\"a0:51:0b:6a:47:b2\",\"control:PacketFence-Switch-Mac\":\"d4:76:a0:d2:b9:50\",\"control:PacketFence-Connection-Type\":\"CLI-Access\",\"Reply-Message\":\"Network device does not support this mode of operation\",\"control:PacketFence-Authorization-Status\":\"allow\",\"control:PacketFence-Switch-Ip-Address\":\"10.255.20.19\",\"control:PacketFence-IfIndex\":\"external\",\"control:PacketFence-Switch-Id\":\"10.255.20.19\",\"control:PacketFence-Eap-Type\":0,\"control:PacketFence-Mac\":\"a0:51:0b:6a:47:b2\"}"
> SQL-User-Name = "a0:51:0b:6a:47:b2"

> Switch Identifier
> N/A
> Switch MAC
> N/A
> Switch IP Address
> N/A
> Called Station Identifier
> d4:76:a0:d2:b9:50:ASAP-Gast (Testing)
> Connection Type
> N/A
> IfIndex
> N/A
> NAS Identifier
> IN19FW-0015
> NAS IP Address
> 10.255.20.19
> NAS Port
> NAS Port Identifer
> NAS Port Type
> Virtual
> RADIUS Source IP Address
> 10.255.20.19
> Wi-Fi Network SSID
> ASAP-Gast (Testing)

**Comment by fdurand** [comment]
It's probably there and you have to remove the else section:
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/Fortinet/FortiGate.pm#L243

Try that: (do a `docker ps` to get the correct image name like packetfence/httpd.aaa:maintenance-12-1)
```
docker exec -it  `docker inspect --format="{{.Id}}" httpd.aaa` bash
apt install vim
vim /usr/local/pf/lib/pf/Switch/Fortinet/FortiGate.pm
exit
docker commit `docker inspect --format="{{.Id}}" httpd.aaa` packetfence/httpd.aaa:maintenance-12-1
systemctl restart packetfence-httpd.aaa
```

**Comment by heiko-ma** [comment]
Instead of editing the file in the image and committing it, i changed the docker-wrapper file _/usr/local/pf/sbin/httpd.aaa-docker-wrapper_ and mounted the _/usr/local/pf/lib/_ folder inside the container

Removing the section didn't work, I suppose this is because the attribute isCLI is true by default. I changed the lines like below:
else {
        $connection->isVPN($FALSE);
        $connection->isCLI($FALSE);
    }

after restart httpd.aaa this seemed to work.

Edit: After changing those lines, reevaulating access doesn't work, because the connection doesnt get any connection-type assigned:
![image](https://user-images.githubusercontent.com/64192965/206395134-049ad4ab-c8be-46da-8933-9c04af70901b.png)
