### ISSUE TITLE
Zen 12.1 - ESXi - No interfaces found in Step 1

### ISSUE THREAD

**Issue by Sheepy911** [inverse-inc/packetfence#7403]
**Describe the bug**
After importing the OVA into vSphere and Launching the Machine, when trying to run the initial setup no interfaces can be found.
This stops the installation, as it cannot be progressed without a management interface.
After a short while, a notification is given stating a 504 error.

When directly going API, all other call's function, providing the initial hostname, gateway and DNS.
However the same error is seen when calling:
`https://xxx.xxx.xxx.xxx:1443/api/v1/configurator/config/interfaces?sort=id&fields=is_running,id,ipaddress,netmask,ipv6_address,ipv6_prefix,network,type,additional_listening_daemons,high_availability,buttons&limit=1000`

Restarting or Changing Network adapter types does not make a difference.
When trying Zen 12.0 - same issue is seen

**To Reproduce**
Import Packetfence Zen 12.1 on ESXi
Start the appliance and go to https://ipaddress:1443

**Screenshots**
![image](https://user-images.githubusercontent.com/1337193/205361345-055e232a-4e27-4645-b602-4490d6439365.png)
![image](https://user-images.githubusercontent.com/1337193/205361515-f6ec50d7-66b9-4028-8395-da39d0cf8e43.png)
![image](https://user-images.githubusercontent.com/1337193/205363071-20890deb-6a28-46a8-9591-42ea475a4354.png)

**Expected behaviour**
Interfaces are populated in the configurator and can be selected to progress installation of the appliance

**Comment by Sheepy911** [comment]
To test - I have just attempted to build the VM from the 12.1 ISO.
This gave the same error, for reference the specs of the machine used are below.

4 Cores (Xeon CPU E5-2690 v3)
256gb disk (NVMe)
16gb RAM
VMXNet3

**Comment by nqb** [comment]
Hello @Sheepy911,

During our Q/A phase for 12.1, we tested several times ZEN and ISO and never got that issue.
I think there is something badly configured in your environment.
It's possible that your first interface which got an IP address using DHCP is not configured like PacketFence expects.

Could you look into /usr/local/pf/logs/packetfence.log to see if you see something when you use API call to get interfaces ?

**Comment by Sheepy911** [comment]
Hi @nqb,

I was just also testing that now as had been thinking over the weekend.
I've moved the VM to another cluster with completely different hardware and networking setup and got the same results.
To fully confirm, we deployed Zen into a third environment that is fully isolated and has a completely different DNS/DHCP setup, same results again.
This was also across completely different ESXi Versions, Standard and Distributed switches.

Manually configuring the interface (also tested disabling ipv6), I get the same error.
Interface output below:

```
 eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
     link/ether 00:50:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
     altname enp3s0
     altname ens160
     inet XX.XX.XX.XX/23 brd XX.XX.XX.XX scope global eth0
        valid_lft forever preferred_lft forever
```

We are just setting up a test to run ZEN and the ISO within the same networks but using VMWare Workstation/Hyper V to test for environment configuration errors.

When checking the log output of /usr/local/pf/logs/packetfence.log I can only see database connection errors, nothing else.

**Comment by nqb** [comment]
Could you provide output of following commands:

```
cat /etc/network/interfaces

/usr/local/pf/sbin/pfperl-api get /api/v1/config/interfaces | jq

ip -br a

docker container ls
```

**Comment by Sheepy911** [comment]
Just had word back, within the same enviroment (although in a nested VM) HyperV is working 

Outputs Below from ESXi:

```
root@XXXXXXXXXX:~# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet static
 address XX.XX.XX.XX/23
 netmask 255.255.254.0
 gateway XX.XX.XX.XX
 dns-nameservers XX.XX.XX.XX XX.XX.XX.XX
```

```
root@XXXXXXXXXX:~# /usr/local/pf/sbin/pfperl-api get /api/v1/config/interfaces | jq
{
  "items": [
    {
      "additional_listening_daemons": [],
      "address": "XX.XX.XX.XX/23",
      "coa": null,
      "dhcpd_enabled": null,
      "dns": null,
      "high_availability": 0,
      "hwaddr": "00:50:XX:XX:XX:XX",
      "id": "eth0",
      "ifindex": "2",
      "ipaddress": "XX.XX.XX.XX",
      "ipv6_address": null,
      "ipv6_prefix": null,
      "is_running": true,
      "master": null,
      "name": "eth0",
      "nat_enabled": null,
      "netmask": "255.255.254.0",
      "network": "XX.XX.XX.XX",
      "network_iseditable": false,
      "networks": [],
      "not_editable": false,
      "reg_network": null,
      "split_network": null,
      "type": "none",
      "vip": null,
      "vlan": null
    }
  ],
  "status": 200
}
```
```
root@XXXXXXXXXX:~# ip -br a
lo               UNKNOWN        127.0.0.1/8
eth0             UP             XX.XX.XX.XX/23
docker0          UP             100.64.0.1/24
veth1f8fb8b@if5  UP
veth1d99659@if7  UP
veth88cb469@if9  UP
veth9571b7c@if11 UP
```
```
root@XXXXXXXXXX:~# docker container ls
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED         STATUS         PORTS                                                     NAMES
ec8c6f3f4e83   packetfence/haproxy-admin:maintenance-12-1            "/bin/sh -c '/usr/sb…"   7 minutes ago   Up 7 minutes   0.0.0.0:1027->1027/tcp, 0.0.0.0:1443->1443/tcp            haproxy-admin
f22a9b720edb   packetfence/httpd.admin_dispatcher:maintenance-12-1   "/bin/sh -c '/usr/lo…"   7 minutes ago   Up 7 minutes   0.0.0.0:8890-8891->8890-8891/tcp                          httpd.admin_dispatcher
08b2df22194e   packetfence/api-frontend:maintenance-12-1             "/bin/sh -c '/usr/lo…"   7 minutes ago   Up 7 minutes   0.0.0.0:9999->9999/tcp                                    api-frontend
c7ff32140b8f   packetfence/pfperl-api:maintenance-12-1               "/bin/sh -c '/usr/lo…"   7 minutes ago   Up 7 minutes                                                             pfperl-api
36228b3398c2   packetfence/pfconfig:maintenance-12-1                 "/bin/sh -c /usr/loc…"   8 minutes ago   Up 8 minutes   100.64.0.1:44444->44444/tcp, 127.0.0.1:44444->44444/tcp   pfconfig
```

For reference, outputs from HyperV:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:XX:XX:XX:XXbrd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/24 brd XX.XX.XX.XX scope global dynamic eth0
       valid_lft 4493sec preferred_lft 4493sec
    inet6 fe80::215:5dff:fe6f:4b08/64 scope link
       valid_lft forever preferred_lft forever
```

![image](https://user-images.githubusercontent.com/1337193/205662546-633d75f4-0519-435e-9093-1d117abac028.png)

![image](https://user-images.githubusercontent.com/1337193/205663950-d0d537bf-d024-4376-96ae-e881f9dd4f04.png)

![image](https://user-images.githubusercontent.com/1337193/205663255-bac50c69-22e3-457e-80b6-90c5484da787.png)

![image](https://user-images.githubusercontent.com/1337193/205662440-1557c410-2fc1-450f-bccd-c606fcd49aec.png)

**Comment by joeselway** [comment]
I had the exact same issue today on VMware 7.0u3 with v12.1.0. I have already blown it away in favour of a manual install so I can't provide logs, merely a +1. My VM specs along with /etc/network/interfaces looked the same as OP, although I did try changing allow-hotplug to auto before I gave up.

**Comment by nqb** [comment]
I will see if I can replicate this issue using ISO 12.1.0

**Comment by nqb** [comment]
Hello @Sheepy911 

Just tried to replicate issue on VirtualBox using 12.1 ISO, I didn't get behavior you have.

I think the issue is caused by pfperl-api taking too much time to answer to `/api/v1/config/interfaces` (in your environment).

In my environment, I have seen several messages like this:
```
/var/log/syslog:Dec  8 12:34:26 packetfence pfperl-api-docker-wrapper[4369]: sudo: unable to resolve host packetfence: Name or service not known
/var/log/syslog:Dec  8 12:34:27 packetfence pfperl-api-docker-wrapper[4369]: sudo: unable to resolve host packetfence: Name or service not known
/var/log/syslog:Dec  8 12:34:27 packetfence pfperl-api-docker-wrapper[4369]: sudo: unable to resolve host packetfence: Name or service not known
/var/log/syslog:Dec  8 12:34:27 packetfence pfperl-api-docker-wrapper[4369]: sudo: unable to resolve host packetfence: Name or service not known
/var/log/syslog:Dec  8 12:34:27 packetfence pfperl-api-docker-wrapper[4369]: sudo: unable to resolve host packetfence: Name or service not known
```
which can generate a delay. I think this messages are caused by the fact that /etc/hosts inside `pfperl-api` container doesn't contain a `packetfence` entry.

What you can do to pin point issue is to look at `journalctl -u packetfence-pfperl-api -f` while you call  `/api/v1/config/interfaces`. Also, you can increase log level by editing `/usr/local/pf/conf/log.conf.d/pfperl-api.conf` (switch INFO to DEBUG) and restart `pfperl-api` services.

**Comment by Sheepy911** [comment]
Hi @nqb,

Cheers for the help on this. 
Just run through the the above and get the following output.
Looking through, I cant see anything that caches my eye.

```
Dec 12 13:18:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(8) DEBUG: [mac:[undef]] GET "/api/v1/configurator/config/interfaces" (Mojolicious::dispatch)
Dec 12 13:18:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(8) DEBUG: [mac:[undef]] Routing to controller "pf::UnifiedApi::Controller::Configurator" and action "allowed" (Mojolicious::Routes::_controller)
Dec 12 13:18:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(8) DEBUG: [mac:[undef]] Routing to controller "pf::UnifiedApi::Controller::Configurator" and action "allowed" (Mojolicious::Routes::_controller)
Dec 12 13:18:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(8) DEBUG: [mac:[undef]] Routing to controller "pf::UnifiedApi::Controller::Config::Interfaces" and action "list" (Mojolicious::Routes::_controller)
Dec 12 13:18:14 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:14 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:18:18 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:18 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache get for namespace='configfiles', key='/usr/local/pf/conf/pf.conf', cache='Redis:l1_cache', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache get for namespace='configfiles', key='/usr/local/pf/conf/pf.conf', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache set for namespace='configfiles', key='/usr/local/pf/conf/pf.conf', size=1, expires='never', cache='Redis:l1_cache', time='0ms' (CHI::Driver::_log_set_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache get for namespace='configfiles', key='/usr/local/pf/conf/networks.conf', cache='Redis:l1_cache', time='0ms': MISS (not in cache) (CHI::Driver::_log_get_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache get for namespace='configfiles', key='/usr/local/pf/conf/networks.conf', cache='Redis', time='0ms': HIT (CHI::Driver::_log_get_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] cache set for namespace='configfiles', key='/usr/local/pf/conf/networks.conf', size=1, expires='never', cache='Redis:l1_cache', time='0ms' (CHI::Driver::_log_set_result)
Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] 200 OK (78.867063s, 0.013/s) (Mojolicious::Controller::rendered)
Dec 12 13:18:25 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:25 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:18:31 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:37 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:37 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:18:43 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:48 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:18:48 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:18:55 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:19:01 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:19:01 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
Dec 12 13:19:07 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:19:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: sudo: unable to resolve host XXXXXXXXXX: No address associated with hostname
Dec 12 13:19:13 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(15) DEBUG: [mac:[undef]] LAST_TOUCH_CACHE is more than 5 seconds old. Considering config::Pf() as invalid to reload it. (pfconfig::cached::is_valid)
```

Looking - I cant see anything within here that would indicate any issues.
Though Checking the DNS API call, this does seem off to me. Checking, even though only two DNS servers are set statically, it still returns three (these look to be from DHCP).
When removing the the third DNS server from DHCP, Packetfence still returns this as a DNS server (after multiple reboots and waiting), is there a cache somewhere?

**Comment by nqb** [comment]
> Dec 12 13:18:20 XXXXXXXXXX pfperl-api-docker-wrapper[1407]: pfperl-api(17) DEBUG: [mac:[undef]] 200 OK (78.867063s, 0.013/s) (Mojolicious::Controller::rendered)

78.867063s is too high. This is why you got a 504 when using configurator.
Could you check if you see some errors related to network cards in /var/log/syslog or using `dmesg -T` ?

**Comment by julsemaan** [comment]
I'm guessing the sudo errors have something to do with that (they seem multiple seconds apart for the same request). That means the DNS servers are slow to reverse resolve the name of the server.

Solution to that would be adding an entry in /etc/hosts like the following:

```
127.0.0.1 XXXXXXXXXX
```

Where `XXXXXXXXXX` is the actual hostname of the machine. Then see if it helps.

I think that we should setup that entry in `/etc/hosts` if we change the hostname during the configurator. If the administrator changes it using `hostnamectl`, then it will be his responsibility to update the hosts file but we could at least handle the case in the configurator

**Comment by nqb** [comment]
If I add an entry like `MGMT_IP HOSTNAME` in `/etc/hosts` on the **host** (not inside the container), I didn't see anymore sudo errors. 

If I look at `/etc/hosts` inside `pfperl-api` container (started with [--network=host](https://docs.docker.com/engine/reference/run/#network-settings)), `/etc/hosts` is not identical to `/etc/hosts` on the host: `MGMT_IP HOSTNAME` is not here.

@Sheepy911, could you try to add an entry like @julsemaan suggested?

**Comment by nqb** [comment]
> If I add an entry like MGMT_IP HOSTNAME in /etc/hosts on the host (not inside the container), I didn't see anymore sudo errors.

In fact, this is not correct.
The behavior described is what I got when I used: ` /usr/local/pf/sbin/pfperl-api get /api/v1/config/interfaces` on the host.

However, when using frontend, I still see errors related to sudo even if I modified `/etc/hosts` on the host (doesn't seem to have an effect on container).

Once I added my `/etc/hosts` entry inside pfperl-api container, I didn't see sudo messages anymore.
I modified `/usr/local/pf/sbin/pfperl-api-docker-wrapper` like this
```
[..]
args="$args -v /etc/resolv.conf:/etc/resolv.conf"
args="$args --network=host"
args="$args --add-host=packetfence:127.0.0.2"                                  <<< added
[..]
```
then I restarted `packetfence-pfperl-api` service. Result:

```
root@packetfence:~# docker exec pfperl-api cat /etc/hosts
[..]
100.64.0.1      containers-gateway.internal
127.0.0.2       packetfence
```

**Comment by Sheepy911** [comment]
@nqb Sorry in the delay of reply here.
Just tested this through over the last couple of days across multiple installs, this has resolved the issue.

Only having issues connecting it into AD now, though I think this is me not fully understanding how to.

Cheers for the help.

**Comment by nqb** [comment]
Moving milestone to 12.2 for that issue because it could require important changes which I'm not sure we will be to handle in +1

**Comment by hawke114** [comment]
> I had the exact same issue today on VMware 7.0u3 with v12.1.0. I have already blown it away in favour of a manual install so I can't provide logs, merely a +1. My VM specs along with /etc/network/interfaces looked the same as OP, although I did try changing allow-hotplug to auto before I gave up.

I have run into the same issue on a bare metal server and ProxMox VM. After the initial install from ISO on both, there are no interfaces found in the configurator.
