### ISSUE TITLE
12.1 LDAP and Active Directory Authentication source -Blocking Issue

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7411]
**Describe the bug**
Within the certificates tab of the authentication source Client Certificate File and Client Key File has become mandatory.  This is the case for the following authentication sources (which appear to use the same template).

Active Directory
LDAP

The side effect is when creating either a new source that does not need to use certificates or needing to modify an existing source the create button or save button is disabled.

**To Reproduce**
1. Go to Configuration | Policies and Access Control | Authentication Sources
2. Click on "New Internal Source"
3. Select LDAP
4. See error with red 2 next to certificates

**Screenshots**
![image](https://user-images.githubusercontent.com/95610834/206173609-a62e97fb-3873-4092-a5d2-29b577655939.png)

**Expected behavior**
Able to create or save the authentication source without the need for applying a certificate.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Edge and Chrome
 - Version 107
 
**Additional context**
I also noticed that there may be a second bug in this area.  If you add a fake crt file to get passed the saving it gets uploaded but the path to it does not get displayed when reentering the certificates tab.

**Comment by julsemaan** [comment]
This was tested during the 12.1 QA cycle so it could be a regression introduced while fixing https://github.com/inverse-inc/packetfence/issues/7392

**Comment by satkunas** [comment]
This appears the be the same issue as #7392. The fix for that issue should also apply here.

**Comment by PureOxygen-Dev** [comment]
@satkunas I patched the servers this morning and I noticed it.  All nodes are on [0d0810c7cbed817f72a8694f6497cbf6580acef9](https://github.com/inverse-inc/packetfence/commit/0d0810c7cbed817f72a8694f6497cbf6580acef9) 

Is the above mentioned fix included in this release?

**Comment by satkunas** [comment]
The excessive validation has been reverted. Also, back-ported to maintenance/12.1.

**Comment by nqb** [comment]
@RHDHV-simon-sutcliffe, if you want to be sure a fix is available through maintenance patches, check commits on maintenance branch on GitHub and look at icon :
![image](https://user-images.githubusercontent.com/10830260/206380429-7de4a327-eb56-4947-b3e2-bdac06c5dd0a.png)

In this example, only "apply #7405 to maintenance" is available.

**Comment by PureOxygen-Dev** [comment]
@nqb Thanks for coming back on this, I am no gibhub expert but then I think I am not getting it.

When I applied the maint patches yesterday I received the following item 

![image](https://user-images.githubusercontent.com/95610834/206382249-49fd0893-3c98-40e9-9abd-b991328030d4.png)

This caused a regression issue for us in our LDAP and AD Authentication Sources.  Based what I think you are telling me as it has a red cross not a tick then is not included any longer, correct?

What is then the status of a item without a cross or a tick? For Example

![image](https://user-images.githubusercontent.com/95610834/206383340-4e7ec358-915e-487c-8046-e574c5ee0d83.png)

Sorry to be a pain but understanding this will help me explain to our release management teams when they need to patch and when not.

Thanks in advance for your time.

**Comment by nqb** [comment]
@RHDHV-simon-sutcliffe,

Sorry my explanation was not clear. 

Red cross next to a commit means a pipeline failed for this specific commit. However, if a more recent commit had a green tick, it means that packages have been uploaded in PF repositories so obviously it contains all previous commits.

**Comment by PureOxygen-Dev** [comment]
@nqb OK that is clear.  The last green tick in the list is where the process is up to.  Perfect that I can explain to the team.
