### ISSUE TITLE
galera-autofix: allow to bypass waiting time before galera-autofix start to take action

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7414]
**Is your feature request related to a problem? Please describe.**
Currently, when you have a MariaDB issue, galera-autofix will start to take action in following conditions (according to our [doc](https://www.packetfence.org/doc/12.1.0/PacketFence_Clustering_Guide.html#_automatic_clustering_resolution_service_galera_autofix)):

```
On a cluster which has an issue, once all nodes are back online, you should wait:

around 10 minutes when at least one of the nodes of the cluster is able to offer database service
around 20 minutes when there is no database service available
```

If you don't want to wait that time before resolution happened automatically, you need to:
* stop galera-autofix on all nodes
* make a manual resolution using a process which is not always clear

**Describe the solution you'd like**
Force galera-autofix using an argument or an environment variable to perform resolution directly without waiting an amount of time.

**Describe alternatives you've considered**
Improve our documentation to describe exactly which process need to be followed in each situation (with description of state of servers during each step).

**Comment by satkunas** [comment]
* Adjust docs
  * Document default behaviour
  * Document using galara-autofix
* Needs to be backported

**Comment by satkunas** [comment]
Documentation has been updated to provide an alternative fix. More work is needed to backport.

#7714

**Comment by satkunas** [comment]
Docs backported to m/12.0 m/12.1 and m/12.2
