### ISSUE TITLE
Problem MD5 Authentication

### ISSUE THREAD

**Issue by rsp1991** [inverse-inc/packetfence#7417]
**Describe the bug**
I'm trying the config MD5 authentication, but I get the message:

eap_md5: Cleartext-Password is required for EAP-MD5 authentication

**To Reproduce**
1 - Create the eap profile with MD5 set to default
2 - Linked to realm
3 - I set plaintext in Configuration --> System Configuration --> Advanced --> Database password hashing 
4 - create the new user

**Expected behavior**
Device authentication via username and password MD5

**Desktop (please complete the following information):**
 - Cisco IP Phone

**Additional context**
I'm use the PacketFence 12.0 in Cluster

**Comment by julsemaan** [comment]
That's more a message for the mailing list. Github issues are used only for actual bugs and feature requests, not for help with the configuration

**Comment by rsp1991** [comment]
@julsemaan I suspect it's a bug, because even if the user is configured as plantext, he continues with the message
