### ISSUE TITLE
Security events save don't update all the fields

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7420]
**Describe the bug**
When you create/save a security events some fields are not saved correctly in the configuration file.

**To Reproduce**
1. Create a security event
2. Change the window value and you will see that it's not saved.
3. Change the windowd value and set a unit , it's saved.

**Expected behavior**
In the api call the unit is not defined even if the default one is there (like second)

**Comment by satkunas** [comment]
With `delay_by`, `grace` and `window`, Using `{interval: ..., unit: ...}` 

Currently when `unit: null` then `interval` is ignored. Both unit and interval must provided to be saved.

It might make sense to add a validator so the user must either enter both or neither values.
