### ISSUE TITLE
ZEN 12.1 /usr/local/pf/bin/cluster/sync --as-master does not sync /usr/local/pf/html/captive-portal/profile-templates/{ConnectionName}

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7424]
**Describe the bug**
We discovered that we had inconsistent values after the upgrade of 12.0. 12.1 of our file localisations for the captive portals within the cluster.  On the primary server the files were correct, so we attempted a /usr/local/pf/bin/cluster/sync --as-master 

The sync completed without error however the captive portal modified files in the {ConnectionProfile} were unaffected and remained inconsistent.

**To Reproduce**
1. Go to Modify a file the GUI for a captive portal
2. Update the file on one server within the cluster from the terminal.
3. On that server run /usr/local/pf/bin/cluster/sync --as-master 
4. Check other servers and you should find the update did not happen.

**Expected behavior**
/usr/local/pf/bin/cluster/sync --as-master should update all modification made by the user across the servers.

**Additional context**
Updating the file on any server within the cluster succeeded in syncing to all cluster members without issue.

**Comment by nqb** [comment]
IIRC,  captive portal templates are not synchronized by default using `sync` script.

You need to use `cluster-files.txt` to synchronize it.

**Comment by PureOxygen-Dev** [comment]
Yes your right @nqb but does that make sense.  These are not per say additional files but could be seen as just config files no different to and of the other .conf files. So maybe not a bug but potentially a feature request then.

**Comment by PureOxygen-Dev** [comment]
Is as per the design so closing this open item
