### ISSUE TITLE
iOS Device Provisioning Issue with MS SCEP, EAP-TLS, WPA2

### ISSUE THREAD

**Issue by jwillis44** [inverse-inc/packetfence#7425]
# Apple Devices Provisioner Issue

When provisioner generates mobileconfig for iOS device, specifying  WPA2 as encryption type, using MSSCP and EAP-TLS, installed profile shows on device as only using WPA.

## /usr/local/pf/conf/provisioners.conf

```
[AppleWPA2]
ssid=Dot1X
eap_type=13
sync_pid=disabled
description=WPA 2 Apple Provisioner
category=
pki_provider=MSPKI
autoregister=disabled
oses=
security_type=WPA2
broadcast=1
type=mobileconfig
psk_size=8
apply_role=disabled
enforce=enabled
certificate= <<EOT
-----BEGIN CERTIFICATE-----
Sanatized
-----END CERTIFICATE-----
EOT
cert_chain= <<EOT
-----BEGIN CERTIFICATE-----
Sanatized
-----END CERTIFICATE-----
EOT
private_key= <<EOT
-----BEGIN PRIVATE KEY-----
Sanatized
-----END PRIVATE KEY-----
EOT
can_sign_profile=1
```

## Screenshots

Here is a screenshot of the resulting profile on device:

![image](https://user-images.githubusercontent.com/21270623/207352255-8c906f7c-35e2-4ee3-aa0e-a83fa0cf3299.png)

Here is a screenshot of a profile generated elsewhere showing the encryption of WPA2.

![image](https://user-images.githubusercontent.com/21270623/207352694-3893b5dc-d609-4818-b008-216369f52b7d.png)

# Devices/Packetfence

Tested on several ios devices

iPad Air 2 SW OS: 15.7.1 

iPhone 12 mini OS: 16.1.1

Packetfence v. 12.1.0

All EAP Types have been added to the EAP Profiles for testing as well as the TLS profiles.

Thanks, happy to help with more testing if needed.

**Comment by nqb** [comment]
Hello @jwillis44,

I see a similar behavior.
Does it prevent you to connect to your SSID ?

**Comment by jwillis44** [comment]
Yes. You?

**Comment by nqb** [comment]
Could you try to edit mobileconfig file you received and replaced WPA by WPA2 to see if it helps ?

**Comment by nqb** [comment]
According to our code, it's has been done on purpose: https://github.com/inverse-inc/packetfence/blame/13ba0e1caf1d657be88d616161b498d17b745967/lib/pfconfig/namespaces/config/Provisioning.pm#L51-L56

Not sure it is still accurate. 
On https://developer.apple.com/documentation/devicemanagement/wifi, I'm reading this:
![image](https://user-images.githubusercontent.com/10830260/207595624-8ffd5b4a-0186-41f8-bed8-80f90d5a389f.png)

It could make sense to use "WPA2" in place of "WPA" but we need to be sure it doesn't break Android and iOS provisioning.

**Comment by jwillis44** [comment]
I modified /usr/local/pf/lib/pfconfig/namespaces/config/Provisioning.pm,
changed line 53  to

if (defined $value && $value eq 'WPA2') {

When I do a ./pfcmd configreload hard the next time a mobile config profile
is generated, it shows up as wpa2 and I'm able to connect to the network as
expected. with the exception that the CA specified in the MSSCP
PKI_Provider config is still not trusted by the device. I'll save that for
another time.

However after a little time passes, the next mobileconfig that is generated
returns to WPA, not WPA2, I have to do the configreload hard again.

Is there another location that that setting may be getting over written by?
Also is there a place to find the mobileconfig file on the server before
the device downloads it to view or modify it's contents for testing?


Joe

**Comment by nqb** [comment]
Hello @jwillis44,

I think you need to restart `packetfence-config` after you performed your change in the code.
mobileconfig templates are under `/usr/local/pf/html/captive-portal/templates/`: wireless-profile-*

**Comment by nqb** [comment]
Changing WPA to WPA2 would involve changes in:
- [packetfence-windows-agent](https://github.com/inverse-inc/packetfence-windows-agent/blob/e2aa4c816e2af3ff75e238409e673bcd6fd39bb7/parse.go#L341-L350)
- [packetfence-android-agent](https://github.com/inverse-inc/packetfence-android-agent/blob/91e769d70457cd19c1bf78b700f8178974a83345/src/main/java/org/packetfence/agent/MainActivity.java#L500-L504). It's possible there are other places where WPA need to be replaced

To avoid a change in agents, perhaps we could handle that case in templates, only for Apple devices like:

`If it's an Apple device and security type is WPA, we use WPA2 in mobileconfig file.`

 It will be more easy to backport to maintenance branches.

**Comment by nqb** [comment]
@jwillis44, I created a PR to solve that issue, see #7428 for the fix.
