### ISSUE TITLE
v12.1 online status unknown after upgrade

### ISSUE THREAD

**Issue by RenatoPereira91** [inverse-inc/packetfence#7427]
**Describe the bug**
All devices authenticated in the cluster get unknown status

**To Reproduce**
1. Configured the accounting in the switch

**Screenshots**

tcpdump on the nodes that receive  request

![image](https://user-images.githubusercontent.com/102453125/207715609-576869b1-d716-493b-82e8-8c6e5e5bfcdd.png)

Radius pfaccount dashboard

![image](https://user-images.githubusercontent.com/102453125/207716020-3422384f-c098-4cc9-8b8c-920dd49e71ef.png)

**Switch log**
*Mar  1 00:30:06.427: RADIUS(0000000C): Send Accounting-Request to 10.55.43.63:1813 id 1646/16, len 237
*Mar  1 00:30:06.427: RADIUS:  authenticator F3 BC F2 C2 31 AE 02 FB - AD C5 C9 8D 9F 52 CC 63
*Mar  1 00:30:06.427: RADIUS:  Acct-Session-Id     [44]  10  "0000000C"
*Mar  1 00:30:06.427: RADIUS:  Vendor, Cisco       [26]  49  
*Mar  1 00:30:06.427: RADIUS:   Cisco AVpair       [1]   43  "audit-session-id=AC12140200000006001AD90E"
*Mar  1 00:30:06.427: RADIUS:  User-Name           [1]   14  "4cd98ffbd738"
*Mar  1 00:30:06.427: RADIUS:  Vendor, Cisco       [26]  32  
*Mar  1 00:30:06.427: RADIUS:   Cisco AVpair       [1]   26  "connect-progress=Call Up"
*Mar  1 00:30:06.427: RADIUS:  Acct-Authentic      [45]  6   RADIUS                    [1]
*Mar  1 00:30:06.427: RADIUS:  Acct-Status-Type    [40]  6   Start                     [1]
*Mar  1 00:30:06.427: RADIUS:  NAS-Port-Type       [61]  6   Ethernet                  [15]
*Mar  1 00:30:06.427: RADIUS:  NAS-Port            [5]   6   50101                     
*Mar  1 00:30:06.427: RADIUS:  NAS-Port-Id         [87]  22  "GigabitEthernet1/0/1"
*Mar  1 00:30:06.427: RADIUS:  Called-Station-Id   [30]  19  "00-1D-E5-45-37-81"
*Mar  1 00:30:06.427: RADIUS:  Calling-Station-Id  [31]  19  "4C-D9-8F-FB-D7-38"
*Mar  1 00:30:06.427: RADIUS:  Service-Type        [6]   6   Framed                    [2]
*Mar  1 00:30:06.427: RADIUS:  NAS-IP-Address      [4]   6   172.18.20.2               
*Mar  1 00:30:06.427: RADIUS:  Unsupported         [151] 10  
*Mar  1 00:30:06.427: RADIUS:   35 44 33 38 44 32 44 46          [ 5D38D2DF]
*Mar  1 00:30:06.427: RADIUS:  Acct-Delay-Time     [41]  6   0                         
*Mar  1 00:30:06.427: RADIUS(0000000C): Started 10 sec timeout
*Mar  1 00:30:06.469: RADIUS: Received from id 1646/16 10.55.43.63:1813, Accounting-response, len 35
*Mar  1 00:30:06.469: RADIUS:  authenticator 14 AB 62 02 B2 72 82 73 - 6A 7D 65 10 50 33 CB A7
*Mar  1 00:30:06.469: RADIUS:  Reply-Message       [18]  15  
*Mar  1 00:30:06.469: RADIUS:   41 63 63 6F 75 6E 74 69 6E 67 20 4F 4B     [ Accounting OK]
*Mar  1 00:30:10.655: RADIUS/ENCODE(0000000C):Orig. component type = DOT1X
*Mar  1 00:30:10.655: RADIUS(0000000C): Config NAS IP: 0.0.0.0
*Mar  1 00:30:10.655: RADIUS(0000000C): sending
*Mar  1 00:30:10.655: RADIUS/ENCODE(0000000C):Orig. component type = DOT1X
*Mar  1 00:30:10.655: RADIUS(0000000C): Config NAS IP: 0.0.0.0
*Mar  1 00:30:10.655: RADIUS(0000000C): sending
*Mar  1 00:30:10.655: RADIUS/ENCODE: Best Local IP-Address 172.18.20.2 for Radius-Server 10.55.43.63
*Mar  1 00:30:10.655: RADIUS(0000000C): Send Accounting-Request to 10.55.43.63:1813 id 1646/17, len 273
*Mar  1 00:30:10.655: RADIUS:  authenticator 66 19 5F A6 6B F4 9A 96 - 2C 57 6E AE 8A 1A 6C 6E
*Mar  1 00:30:10.655: RADIUS:  Acct-Session-Id     [44]  10  "0000000C"
*Mar  1 00:30:10.655: RADIUS:  Vendor, Cisco       [26]  49  
*Mar  1 00:30:10.655: RADIUS:   Cisco AVpair       [1]   43  "audit-session-id=AC12140200000006001AD90E"
*Mar  1 00:30:10.655: RADIUS:  Framed-IP-Address   [8]   6   172.18.20.4               
*Mar  1 00:30:10.655: RADIUS:  User-Name           [1]   14  "4cd98ffbd738"
*Mar  1 00:30:10.655: RADIUS:  Vendor, Cisco       [26]  32  
*Mar  1 00:30:10.655: RADIUS:   Cisco AVpair       [1]   26  "connect-progress=Call Up"
*Mar  1 00:30:10.655: RADIUS:  Acct-Session-Time   [46]  6   4                         
*Mar  1 00:30:10.655: RADIUS:  Acct-Input-Octets   [42]  6   348                       
*Mar  1 00:30:10.655: RADIUS:  Acct-Output-Octets  [43]  6   448                       
*Mar  1 00:30:10.655: RADIUS:  Acct-Input-Packets  [47]  6   1                         
*Mar  1 00:30:10.655: RADIUS:  Acct-Output-Packets [48]  6   7                         
*Mar  1 00:30:10.655: RADIUS:  Acct-Authentic      [45]  6   RADIUS                    [1]
*Mar  1 00:30:10.655: RADIUS:  Acct-Status-Type    [40]  6   Watchdog                  [3]
*Mar  1 00:30:10.664: RADIUS:  NAS-Port-Type       [61]  6   Ethernet                  [15]
*Mar  1 00:30:10.664: RADIUS:  NAS-Port            [5]   6   50101                     
*Mar  1 00:30:10.664: RADIUS:  NAS-Port-Id         [87]  22  "GigabitEthernet1/0/1"
*Mar  1 00:30:10.664: RADIUS:  Called-Station-Id   [30]  19  "00-1D-E5-45-37-81"
*Mar  1 00:30:10.664: RADIUS:  Calling-Station-Id  [31]  19  "4C-D9-8F-FB-D7-38"
*Mar  1 00:30:10.664: RADIUS:  Service-Type        [6]   6   Framed                    [2]
*Mar  1 00:30:10.664: RADIUS:  NAS-IP-Address      [4]   6   172.18.20.2               
*Mar  1 00:30:10.664: RADIUS:  Unsupported         [151] 10  
*Mar  1 00:30:10.664: RADIUS:   35 44 33 38 44 32 44 46          [ 5D38D2DF]
*Mar  1 00:30:10.664: RADIUS:  Acct-Delay-Time     [41]  6   0                         
*Mar  1 00:30:10.664: RADIUS(0000000C): Started 10 sec timeout
*Mar  1 00:30:10.664: RADIUS/ENCODE: Best Local IP-Address 172.18.20.2 for Radius-Server 10.55.43.63
*Mar  1 00:30:10.664: RADIUS(0000000C): Send Accounting-Request to 10.55.43.63:1813 id 1646/18, len 273
*Mar  1 00:30:10.664: RADIUS:  authenticator 35 55 BA 41 02 FD C9 F8 - DC F1 5C 26 39 14 7B 38
*Mar  1 00:30:10.664: RADIUS:  Acct-Session-Id     [44]  10  "0000000C"
*Mar  1 00:30:10.664: RADIUS:  Vendor, Cisco       [26]  49  
*Mar  1 00:30:10.664: RADIUS:   Cisco AVpair       [1]   43  "audit-session-id=AC12140200000006001AD90E"
*Mar  1 00:30:10.664: RADIUS:  Framed-IP-Address   [8]   6   172.18.20.4               
*Mar  1 00:30:10.664: RADIUS:  User-Name           [1]   14  "4cd98ffbd738"
*Mar  1 00:30:10.664: RADIUS:  Vendor, Cisco       [26]  32  
*Mar  1 00:30:10.664: RADIUS:   Cisco AVpair       [1]   26  "connect-progress=Call Up"
*Mar  1 00:30:10.664: RADIUS:  Acct-Session-Time   [46]  6   4                         
*Mar  1 00:30:10.664: RADIUS:  Acct-Input-Octets   [42]  6   348                       
*Mar  1 00:30:10.664: RADIUS:  Acct-Output-Octets  [43]  6   448                       
*Mar  1 00:30:10.664: RADIUS:  Acct-Input-Packets  [47]  6   1                         
*Mar  1 00:30:10.664: RADIUS:  Acct-Output-Packets [48]  6   7                         
*Mar  1 00:30:10.664: RADIUS:  Acct-Authentic      [45]  6   RADIUS                    [1]
*Mar  1 00:30:10.664: RADIUS:  Acct-Status-Type    [40]  6   Watchdog                  [3]
*Mar  1 00:30:10.664: RADIUS:  NAS-Port-Type       [61]  6   Ethernet                  [15]
*Mar  1 00:30:10.664: RADIUS:  NAS-Port            [5]   6   50101                     
*Mar  1 00:30:10.664: RADIUS:  NAS-Port-Id         [87]  22  "GigabitEthernet1/0/1"
*Mar  1 00:30:10.664: RADIUS:  Called-Station-Id   [30]  19  "00-1D-E5-45-37-81"
*Mar  1 00:30:10.664: RADIUS:  Calling-Station-Id  [31]  19  "4C-D9-8F-FB-D7-38"
*Mar  1 00:30:10.664: RADIUS:  Service-Type        [6]   6   Framed                    [2]
*Mar  1 00:30:10.664: RADIUS:  NAS-IP-Address      [4]   6   172.18.20.2               
*Mar  1 00:30:10.664: RADIUS:  Unsupported         [151] 10  
*Mar  1 00:30:10.664: RADIUS:   35 44 33 38 44 32 44 46          [ 5D38D2DF]
*Mar  1 00:30:10.664: RADIUS:  Acct-Delay-Time     [41]  6   0                         

**Additional context**
The cluster is compound by 5 nodes (3 in the DC 1 and 2 DC 2) at version 12.1

**Comment by nqb** [comment]
Hello,

Look at https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html#_bandwidth_accounting_is_now_disabled_by_default
