### ISSUE TITLE
Sponsor + SMS portal conflict

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#743]
When registering through SMS then aborting the process, the SMS activation entry is left there.

Then if you register using sponsorship, we're checking for the SMS entry before we check the sponsor and redirect there instead of the sponsorship.

Possible solution, clear all open activation entries of a mac before inserting a new one, whatever the activation process selected.

**Comment by dwlfrth** [comment]
I'll assign it to myself since it is kind of part of self-registration refactoring. It will not go in 5.3 tho

**Comment by jrouzierinverse** [comment]
@dwlfrth what is the status of your work on this?

**Comment by julsemaan** [comment]
@dwlfrth 

What's up with that ?

**Comment by julsemaan** [comment]
Doesn't seem relevant in PF6+

**Comment by julsemaan** [comment]
Not relevant in 6+, closing
