### ISSUE TITLE
ZEN 12.1 - XML File Renamed on upload. 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7439]
**Describe the bug**
When using the upload feature to add the Identity Provider metadata in a SAML authentication source the .xml extension gets changes to .crt 

**To Reproduce**
1. Go to Configuration | Policies and Access Control | Authentication Sources
2. Click on New internal source and select SAML
3. Click on the upload icon next to Identity Provider metadata
4. Select the xml file
5. Fill in the rest of the required info
6. Press "Create"
7. When the page refreshes you will see the file has been renamed to .crt

**Screenshots**

Attached file
![image](https://user-images.githubusercontent.com/95610834/210363231-de422206-9c3a-440b-ac49-49b490cdea4a.png)

After Upload
![image](https://user-images.githubusercontent.com/95610834/210363770-01012b9a-b283-42ef-ab83-fca14cf828f5.png)

**Expected behavior**
FIle should retain the full name and extension

**Comment by julsemaan** [comment]
@satkunas and @jrouzierinverse 

Could you pinpoint where this is coming from and provide a fix?

Thanks

**Comment by satkunas** [comment]
> @satkunas and @jrouzierinverse 
> 
> Could you pinpoint where this is coming from and provide a fix?
> 
> Thanks

This looks like backend

**Comment by jrouzierinverse** [comment]
The rename of the file is by design, but the extention is wrong. I will fix that.
