### ISSUE TITLE
CAPTIVE PORTAL NOT WORKING

### ISSUE THREAD

**Issue by Khiljiraheel** [inverse-inc/packetfence#7442]
**Describe the bug**
Currently i am using PF12.1.0 when i got to Network Configuration->Interfaces "Management interface is not available ".

how can i enable the captive portal on my management interface while having the issue that Interface inside Network Configuration is blank.

**Comment by julsemaan** [comment]
This doesn't seem like a bug, more a configuration question. Please use the PacketFence mailing list for this.
