### ISSUE TITLE
FingerBank User Home Page

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7446]
**Is your feature request related to a problem? Please describe.**
When using fingerbank within Packet Fence you are offered a direct link to "View complete account profile".  Here you can see more information on your usage but it is unclear as to the context of the values as no time reference point is given.

**Describe the solution you'd like**
Either raise the information directly within PF admin interface with a related time value for hour and month or include this with the FB profile interface 

Suggested graphic for FB Interface
![image](https://user-images.githubusercontent.com/95610834/211264847-c786a8e6-eff0-4aca-99c7-903e4400e494.png)

**Describe alternatives you've considered**
Getting someone to figure out when the switch over happens and tell all the team that this is a starting time for hours and date of month.  Bit of a pain but possible.

**Additional context**
A history of usage might also be a nice feature to allow people to monitor the trend.

**Comment by satkunas** [comment]
Additional fields are now added.
