### ISSUE TITLE
Captive portal login by URL with credentials

### ISSUE THREAD

**Issue by GuillermoDLCO** [inverse-inc/packetfence#7452]
Hello,

I'm new in PacketFence. Currently, I have a connection profile to authenticate the user to access the network, which also uses radius. In the captive portal flow it's required to select an option to login (first web page) and then to submit username and password (second page/login page). 

I want to know:

1. Whether it is possible to disable the behavior of opening the captive portal automatically when connected to the network.
2. Start the authentication process without writing the username and password, sending them by parameters through a URL. If this url with the parameters is opened, the login process will automatically start (skip the first step of selecting the method and the second of placing the username and password on the login page)

I want to enable QR code url authentication to avoid the user the process of sending the credential manually to access the network.

**Comment by julsemaan** [comment]
Please use the mailing list for configuration related questions
