### ISSUE TITLE
Review pfconfig resources namespaces

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#746]
pfconfig resources should be organized in better namespaces

ie:
pfconfig::namespace::resource::authentication_lookup.pm -> pfconfig::namespace::resource::Authentication::Lookup.pm

pfconfig::namespace::resource::authentication_sources.pm -> pfconfig::namespace::resource::Authentication::Sources.pm

**Comment by julsemaan** [comment]
Rotted for too long, we'll close it
