### ISSUE TITLE
pfpki: email field is mandatory on a template

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7464]
**Describe the bug**
When you create a template in `PKI -> Templates`, frontend requires an email address.

Email field is important because it will be used by PacketFence to notify users that certificate will expire but it will be defined on certificate, not on template.

IMHO, we should have a check only on email field for certificate, not on template.

@fdurand, could you tell us if email is required to generate a certificate (in API) ? If yes, I think we can remove check on template at frontend level.

**Additional context**
Even if frontend requires an email at creation of template, you can remove it after creation.

**Comment by mpreissner** [comment]
Following...I did find that you can proceed with creating the template by entering an email address, and then successfully remove the email address from the template after it's created.  So this requirement to have the email field populated only exists during template creation (which it shouldn't), but the requirement isn't there during modification.
