### ISSUE TITLE
Not able to download latest version on SourceForge

### ISSUE THREAD

**Issue by hausky** [inverse-inc/packetfence#7465]
Hey community,

The latest version of PacketFence is not possible to download from SourceForge.

**Comment by j-vaughn** [comment]
Also seeing this.  Unable to find a valid source for 12.1 ISOs.

**Comment by julsemaan** [comment]
It looks like SourceForge has reverted our mirror content to a 2 year old backup.

Their website also states:
![image](https://user-images.githubusercontent.com/3857942/213488308-9a5b6f29-3f3b-4341-b78f-979133a65435.png)

So we can't rebuild+upload the ZEN at the moment. We'll monitor this and address this when their outage/maintenance will be resolved

**Comment by julsemaan** [comment]
Found this tweet which seems to confirm it:
![image](https://user-images.githubusercontent.com/3857942/213488840-579fe052-a12d-4f3c-9d02-50f92fd7d816.png)

**Comment by ThomasCr** [comment]
too bad... I also wanted to download it for testing 

![grafik](https://user-images.githubusercontent.com/226670/213491005-daadbb70-293f-40de-9fb0-8c4f29ae7ca8.png)

**Comment by julsemaan** [comment]
As a workaround, you can install Debian 11 or RHEL8 and use these instructions to install PacketFence:
https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_installing_packetfence_on_existing_linux

**Comment by ThomasCr** [comment]
Download of PacketFence-ZEN works again.

**Comment by julsemaan** [comment]
Just checked and it is there again, closing
