### ISSUE TITLE
Nortel/Avaya switch support

### ISSUE THREAD

**Issue by snmohanram** [inverse-inc/packetfence#747]
Hello Team,

In our organization 99% all Nortel/Avaya switches with different models.I would like to know if packet fence supports all Nortel/Avaya switches.

Thanks
Mohan

**Comment by extrafu** [comment]
Use the mailing list for these kind of questions - not a _bug tracker_.

**Comment by snmohanram** [comment]
Iam very new to this community, could you please share me mailing list

Thanks
Mohan
