### ISSUE TITLE
ZEN 12.1 Odd maths problem on the status page graphics

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7471]
**Describe the bug**
On the status page I expect that the total registered devices be the sum of the Registered Devices Per Role.  As you will see in the screen shot below this is not the case. 

**To Reproduce**
1. Go to Status Page
4. Potentially see error

**Screenshots**
![image](https://user-images.githubusercontent.com/95610834/214328352-f88707d5-c227-4c23-a953-75d20e7c3571.png)

**Expected behavior**
Should be the sum of the registered devices.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 109

**Additional context**
We are using a 3 node cluster.

**Comment by julsemaan** [comment]
@jrouzierinverse, can you investigate this and see where the issue could come from
