### ISSUE TITLE
verion 12.1,  Just installed, no interfaces show up on configurator

### ISSUE THREAD

**Issue by bram-martin** [inverse-inc/packetfence#7481]
**Describe the bug**
First web page  shows "At least one Interface must be of Type "management"  error and no interfaces to select.

after a while, the webpage shows an alert "Request failed with status code 504.  config/interfaces"

**To Reproduce**

1) Install Debian
   PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
   NAME="Debian GNU/Linux"
   VERSION_ID="11"
   VERSION="11 (bullseye)"
   VERSION_CODENAME=bullseye

2) Install packetfence as detailed in:  https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_installing_packetfence_on_existing_linux

** diagnose **
/usr/local/pf/logs/api-frontend.log     is full of
Jan 27 10:16:48 PacketFence api-frontend-docker-wrapper[1688]: t=2023-01-27T10:16:48-0600 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=7 request-uuid=794dbd92-9e52-11ed-bdd6-024264400005
Jan 27 10:16:49 PacketFence api-frontend-docker-wrapper[1688]: Unable to connect to DB: Error 1698: Access denied for user 'pf'@'localhost'
Jan 27 10:16:50 PacketFence api-frontend-docker-wrapper[1688]: t=2023-01-27T10:16:50-0600 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=7 request-uuid=794dbd92-9e52-11ed-bdd6-024264400005

**Comment by bram-martin** [comment]
![imagen](https://user-images.githubusercontent.com/112719378/215217475-e8ac3793-bc70-49e2-af3e-cff206c7449c.png)

**Comment by ianbmacdonald** [comment]
sounds similar to https://github.com/inverse-inc/packetfence/issues/7403

the errors you are showing are prior to the DB config, so I suspect they are likely not related

**Comment by bram-martin** [comment]
Dup of  #7403
