### ISSUE TITLE
tests: SSH access is lost on VM after configurator test suite

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7489]
**Describe the problem**
In a random way, Ansible is not able to reach PF VM after configurator test suite has been passed.

It happened on different scenario and OS.

**Mandatory informations**

 * Branch: `maintenance/12.0`
 * Scenario: `inline_deb11`
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3693333159#L607
 
**Symptoms**
How the problem can be identified if it appears again ?
- Configurator test suite passed
- Error message:
```yaml
Wednesday 01 February 2023  07:05:31 -0500 (0:00:00.850)       0:01:04.363 **** 
changed: [pfdeb11dev] => (item=configurator_inline)
fatal: [pfdeb11dev]: FAILED! => 
  msg: 'Failed to connect to the host via ssh: '
```

**Additional context**
@JeGoi has performed some investigation and it looks issue is caused by restart of `packetfence-iptables` (through API) by `global_config` test suite.

**Comment by nqb** [comment]
[Cleaning cache](https://github.com/inverse-inc/packetfence/commit/28709f5f072e2200e8b5a848ad0cc7652b2541c6) between jobs was a first attempt to solve that issue. It doesn't work.

**Comment by JeGoi** [comment]
Hum, https://gitlab.com/inverse-inc/packetfence/-/jobs/3764552460 in inline_deb11 or el8, iptables restart is done here:
https://github.com/inverse-inc/packetfence/blob/devel/t/venom/test_suites/inline/l3/10_setup_packetfence.yml#L256
And it is already a systemctl restart.

So, the only test that is restarting iptables with success until now 🤞 is https://github.com/inverse-inc/packetfence/blob/devel/t/venom/test_suites/fingerbank_proxy/setup_proxy/teardown/teardown.yml#L32 BUT I am not sure it is that relevant since it is just the default behaviors.

These are all the options:
```
./test_suites/fingerbank_proxy/setup_proxy/teardown/teardown.yml-  - type: exec
./test_suites/fingerbank_proxy/setup_proxy/teardown/teardown.yml:    script: systemctl restart packetfence-iptables
--
./test_suites/security_event_random_mac/teardown/05_deconfigure_packetfence.yml-  - type: pf_api_service_restart_async
./test_suites/security_event_random_mac/teardown/05_deconfigure_packetfence.yml:    service: "iptables"

./test_suites/security_event_random_mac/05_setup_packetfence.yml-  - type: pf_api_service_restart_async
./test_suites/security_event_random_mac/05_setup_packetfence.yml:    service: "iptables"
--
./test_suites/inline/l3/teardown/05_deconfigure_packetfence.yml-  - type: exec
./test_suites/inline/l3/teardown/05_deconfigure_packetfence.yml:    script: systemctl restart packetfence-iptables

./test_suites/inline/l3/10_setup_packetfence.yml-  - type: exec
./test_suites/inline/l3/10_setup_packetfence.yml:    script: systemctl restart packetfence-iptables
--
./test_suites/inline/l2/teardown/05_deconfigure_packetfence.yml-  - type: exec
./test_suites/inline/l2/teardown/05_deconfigure_packetfence.yml:    script: systemctl restart packetfence-iptables

./test_suites/inline/l2/05_setup_packetfence.yml-  - type: exec
./test_suites/inline/l2/05_setup_packetfence.yml:    script: systemctl restart packetfence-iptables
--
./test_suites/security_event_suricata/teardown/05_deconfigure_packetfence.yml-  - type: systemctl_service_restart
./test_suites/security_event_suricata/teardown/05_deconfigure_packetfence.yml:    service: packetfence-iptables

./test_suites/security_event_suricata/05_setup_packetfence.yml-  - type: pf_api_service_restart
./test_suites/security_event_suricata/05_setup_packetfence.yml:    service: iptables
--
./test_suites/common/restart_iptables_service.yml-  - type: pf_api_service_restart_async
./test_suites/common/restart_iptables_service.yml:    service: 'iptables'
--
./test_suites/inline_l2_and_radius/15_restart_services.yml-    - type: pf_api_service_restart
./test_suites/inline_l2_and_radius/15_restart_services.yml:      service: iptables
```
Note: global_config is using ./test_suites/common/restart_iptables_service.yml

So, yes, even the `systemctl restart packetfence-iptables` can fail.

**Comment by JeGoi** [comment]
Proposition from @fdurand : generate the config, reload the new config without restarting the service.
On teardown just reapply the backup config.
