### ISSUE TITLE
Selecting Y to OS Upgrades with do-upgrade.sh prevents Debian upgrade from 11.x to 12.x

### ISSUE THREAD

**Issue by ianbmacdonald** [inverse-inc/packetfence#7490]
**Describe the bug**
The current Debian 12.1 packages (and possibly 12.0) have a dependency on `packetfence-redis-cache` that require them to be installed prior to the main `packetfence` package.  

The upgrade process for  `packetfence-redis-cache`  includes a service restart that depends on some docker container scripts that check iptables values prior to restart, however these files are only available in the yet-to-be installed version of the main `packetfence` package. 

`packetfence` PreDepends on  `packetfence-redis-cache` and contains the `docker-minimal-rules.sh`
```
pf4:~# apt-cache depends packetfence | grep redis
  PreDepends: packetfence-redis-cache
pf4:~# dpkg -L packetfence | grep minimal
/usr/local/pf/containers/docker-minimal-rules.sh
```
`packetfence-redis-cache` has a startup script that requires the above mentioned `docker-minimal-rules.sh`
```
pf4:~# dpkg -L packetfence-redis-cache | grep service
/lib/systemd/system/packetfence-redis-cache.service
pf4:~# cat /lib/systemd/system/packetfence-redis-cache.service| grep minimal
ExecStartPre=/usr/local/pf/containers/docker-minimal-rules.sh
```
The result is that you can not upgrade from 11.x to 12.x where docker containers were introduced, due to how these files are distributed among the packages.   

The upgrade starts, and holds back packetfence due to the PreDepends
```
The following packages have been kept back:
  packetfence packetfence-upgrade
```
Then proceeds to error out installing and restarting `packetfence-redis-cache`
```
Restarting packetfence-redis-cache
Job for packetfence-redis-cache.service failed because the control process exited with error code.
```
Tested most recently with `12.1.0+20230126143508+759335432+0011+maintenance~12~1+bullseye1`
Using do-upgrade.sh from `11.2.0+20230117101740+751356317+0011+maintenance~11.2+bullseye1`

**To Reproduce**
1. Install a v11.2 packetfence from packages
2. Try to upgrade it to v12.1 
3. The upgrade script fails with the error shown below

**Output of the do-upgrade.sh script**
```
=================================================================================
Finalizing upgrade
---------------------------------------------------------------------------------
Applying fixpermissions
Fixed permissions.
---------------------------------------------------------------------------------
Restarting packetfence-redis-cache
**Job for packetfence-redis-cache.service failed because the control process exited with error code.**
See "systemctl status packetfence-redis-cache.service" and "journalctl -xe" for details.
```
Further debug shows it is from the missing PreExec script 
```
Jan 27 23:51:27 pf3 systemd[1]: Starting PacketFence Redis Cache Service...
Jan 27 23:51:27 pf3 systemd[5035]: packetfence-redis-cache.service: Failed to locate executable /usr/local/pf/containers/docker-minimal-rules.sh: No such file or directory
Jan 27 23:51:27 pf3 systemd[5035]: packetfence-redis-cache.service: Failed at step EXEC spawning /usr/local/pf/containers/docker-minimal-rules.sh: No such file or directory
Jan 27 23:51:27 pf3 systemd[1]: packetfence-redis-cache.service: Control process exited, code=exited, status=203/EXEC
Jan 27 23:51:27 pf3 systemd[1]: packetfence-redis-cache.service: Failed with result 'exit-code'.
```

**Expected behavior**
Lots of ways to solve this; It seems reasonable if docker service packages are going to exist separately, then their common support scripts would be in a common packages depended by all of them.  Somebody who knows the packetfence package dependency governance should weigh in with a proposed solution.   

**Additional context**
Created with comments from https://github.com/inverse-inc/packetfence/issues/7473

**Comment by nqb** [comment]
Hello @ianbmacdonald,

Thanks for your detailled report.
I'm able to replicate the issue but I don't think `packetfence-redis-cache` is the root cause.

**Comment by nqb** [comment]
From I saw, I think the issue happened only when you answer "y" to the question: 

`Do you wish to perform the update of the operating system to the latest available patches during that process? (y/n):`

As a workaround, you can answer "n" and upgrade would work.

**Comment by ianbmacdonald** [comment]
Interesting; So N I am guessing forces a dist upgrade process that skips over the vanilla upgrade where the PreDepends is honoured and the services are restarted;  I will stay away from it on future upgrades if it can cause unpredictable issues with apt following the dependencies that the do-upgrade.sh process is not designed to handle.  

For others that want everything upgraded before packetfence, and do not want to find themselves with this issue using the do-upgrade.sh script's OS upgrade step,  a preferred method to upgrade a Debian system beforehand, excluding a specific package, is to use apt marking to hold back packages, perform system upgrades and then proceed. 

Here is how is done with packetfence and will avoid the do-upgrade.sh script from causing these types of issues.

```
pf3:~# apt-mark hold $(dpkg --get-selections | grep packetfence | awk '{print $1}')
packetfence set on hold.
packetfence-archive-keyring set on hold.
packetfence-captive-portal-javascript set on hold.
packetfence-config set on hold.
packetfence-doc set on hold.
packetfence-golang-daemon set on hold.
packetfence-ntlm-wrapper set on hold.
packetfence-perl set on hold.
packetfence-pfappserver-javascript set on hold.
packetfence-pfcmd-suid set on hold.
packetfence-redis-cache set on hold.
packetfence-upgrade set on hold.
```
Perform your apt upgrades, dist-upgrades, whatever you need to do to bring your system to a known good pre-upgrade state.  Particularily useful, if you are running the upgrade in a test environment prior to production. 

When you are finished, use apt to un-hold packetfence and proceed with the upgrade script, safely selecting N to system package upgrades. 

```
pf3:~# apt-mark unhold $(dpkg --get-selections | grep packetfence | awk '{print $1}')
Canceled hold on packetfence.
Canceled hold on packetfence-archive-keyring.
Canceled hold on packetfence-captive-portal-javascript.
Canceled hold on packetfence-config.
Canceled hold on packetfence-doc.
Canceled hold on packetfence-golang-daemon.
Canceled hold on packetfence-ntlm-wrapper.
Canceled hold on packetfence-perl.
Canceled hold on packetfence-pfappserver-javascript.
Canceled hold on packetfence-pfcmd-suid.
Canceled hold on packetfence-redis-cache.
Canceled hold on packetfence-upgrade.
pf3:~# 
```
Now run the `do-upgrade.sh` and select N to system OS updates

This safely works around the package dependency issues triggered by the do-upgrade.sh script.   Here is how the command works. 

`dpkg --get-selections` lists all installed packages and their current status (e.g. installed, hold, deinstalled, etc.)
`grep packetfence` filters the output of the previous command to show only the packages whose name contains the string "packetfence".
`awk '{print $1}' `extracts the first field (i.e. the package name) from the output of the previous command.
Finally, the command `apt-mark hold `followed by the list of package names in parentheses marks the specified packages for hold, so that they are not updated or removed during future system updates.  The unhold version does the opposite.
