### ISSUE TITLE
pfconfig cannot connect to external db

### ISSUE THREAD

**Issue by mcaulifn** [inverse-inc/packetfence#7494]
**Describe the bug**
The pfconfig container cannot connect to the external db.

**To Reproduce**
1. Install packetfence 12.x
2. Configure pfconfig.conf to use a DB that is not on-box or w/o local socket.

```
[mysql]
host=packetfence-db.another-host
user=packetfence
pass=random_pass
db=pf
port=3306
table=keyed
```

4. Start packetfence-config service.

**Screenshots**

From pfconfig.log

```
Feb  2 21:40:32 ip-10-0-0-113 pfconfig-docker-wrapper[14925]: Running with args --sig-proxy=true --rm --name=pfconfig --add-host=containers-gateway.internal:host-gateway -h ip-10-0-0-113  -v /var/lib/mysql:/var/lib/mysql -v /etc/sudoers:/etc/sudoers -v /etc/sudoers.d/:/etc/sudoers.d/ -v /usr/local/fingerbank/conf:/usr/local/fingerbank/conf -v /usr/local/fingerbank/db:/usr/local/fingerbank/db -v /usr/local/pf/var/run:/usr/local/pf/var/run -ePF_UID=996 -e PF_GID=996 -eFINGERBANK_UID=997 -e FINGERBANK_GID=997 -eIS_A_CLASSIC_PF_CONTAINER=yes -v /etc/localtime:/etc/localtime:ro -v/usr/local/pf/conf:/usr/local/pf/conf -p 127.0.0.1:44444:44444 -p 100.64.0.1:44444:44444 -e PF_MYSQL_UNIX_SOCKET= --privileged -v /run/systemd/system:/run/systemd/system -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
Feb  2 21:40:32 ip-10-0-0-113 pfconfig-docker-wrapper[14932]: Error: No such container: pfconfig
Feb  2 21:40:32 ip-10-0-0-113 pfconfig-docker-wrapper[14932]: 1
Feb  2 21:41:13 ip-10-0-0-113 pfconfig-docker-wrapper[14944]: pfconfig(7) ERROR: [mac:[undef]] Caught error DBI connect('database=pf;host=packetfence.another-host;port=3306;mysql_socket=/var/lib/mysql/mysql.sock','packetfence',...) failed: Unknown MySQL server host 'packetfence.another-host' (-3) at /usr/local/pf/lib/pfconfig/backend/mysql.pm line 59.
Feb  2 21:41:13 ip-10-0-0-113 pfconfig-docker-wrapper[14944]: while connecting to database. (pfconfig::backend::mysql::_get_db)
Feb  2 21:41:13 ip-10-0-0-113 pfconfig-docker-wrapper[14944]: pfconfig(7) ERROR: [mac:[undef]] Couldn't connect to MySQL database to access L2. This is a major problem ! Check the MySQL section in /usr/local/pf/conf/pfconfig.conf and make sure your database schema is up to date ! (pfconfig::backend::mysql::_db_error)
Feb  2 21:41:13 ip-10-0-0-113 pfconfig-docker-wrapper[14944]: ------------------
```

**Expected behavior**
The pfconfig service should not rely on a socket to connect to the database and instead be configurable.

**Additional context**

```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

**Comment by nqb** [comment]
The `port` must be `6033` to communicate with ProxySQL.

**Comment by mcaulifn** [comment]
@nqb In `pfconfig.conf`? The DB is not listening on that port as far as I can tell.

**Comment by mcaulifn** [comment]
@nqb Can you be more specific?

**Comment by jrouzierinverse** [comment]
Can you try the following to see the error you get?
```docker exec -it pfconfig mysql --port 3306 -h packetfence-db.another-host -upacketfence -prandom_pass ```

**Comment by mcaulifn** [comment]
```
ERROR 2005 (HY000): Unknown MySQL server host
```

@fdurand was able to determine that the iptables container is not starting.

The logs from iptables:

```
Mar 10 10:28:51 ip-10-0-0-108 perl[20143]: [1678472931.31726] Failed to connect to config service for namespace config::Pf(), retrying
Mar 10 10:28:51 ip-10-0-0-108 perl[20143]: Can't connect to pfconfig on containers-gateway.internal:44444 : Invalid argument
Mar 10 10:28:51 ip-10-0-0-108 perl[20143]: [1678472931.41813] Failed to connect to config service for namespace config::Pf(), retrying
Mar 10 10:28:51 ip-10-0-0-108 packetfence[20143]: -e(19963) ERROR: [1678472931.41813] Failed to connect to config service for namespace config::Pf(), >
```

It seems like there might be a circular dependency here.

**Comment by abprasa** [comment]
@mcaulifn 
We have tried to replicate the same in our test environment with a remote MariaDB deployed on a deb11 distro along with pf v12.2 and we haven't run into any issues. 
Please follow the below steps to make sure that you have the remotedb and Packetfence server configured correctly.

# Steps for RemoteDB/MariaDB servers:

Once you have the remoteDB installed correctly please make sure of the following:   
1. Firewall is configured to allow access between pf and remoteDB on tcp port 3306 (in case of MariaDB)
2. Run mysql_secure_installation command to secure the remoteDB correctly.
3. Create a new “pf” database and a new "pf" user to access db remotely.  
```
In order to create you can run the following command:      
  Mysql> CREATE DATABASE pf;
```

Also, you need to import DB schema from the Packetfence server to the remoteDB using the below steps:
      
```
* Copy /usr/local/pf/db/pf-schema.sql from PF server to remoteDB server
* Then run: #/usr/bin/mysql -u root -p pf < pf-schema.sql
```

Then create a new user “pf” in the remoteDB and provide the necessary permissions for Packetfence version v12.2: 

```
#mysql> GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE,LOCK TABLES,CREATE TEMPORARY TABLES ON pf.* TO pf@"%" IDENTIFIED BY "password";
#mysql> GRANT DROP ON pf.radius_nas TO pf@"%" IDENTIFIED BY "password";
#mysql> GRANT SELECT ON mysql.proc TO pf@"%" IDENTIFIED BY "password";
#mysql> GRANT BINLOG ADMIN ON *.* TO pf@'%' IDENTIFIED BY 'password';

#mysql> GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE,LOCK TABLES,CREATE TEMPORARY TABLES ON pf.* TO pf@"localhost" IDENTIFIED BY "password";
#mysql> GRANT DROP ON pf.radius_nas TO pf@"localhost" IDENTIFIED BY "password";
#mysql> GRANT SELECT ON mysql.proc TO pf@"localhost" IDENTIFIED BY "password";

#mysql> GRANT RELOAD, PROCESS, SUPER, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'pf'@'%';
#mysql> FLUSH PRIVILEGES;
```

# Steps for PacketFence server:

1. Update pf.conf and pfconfig.conf with remote database IP 	
    * Also please note: that while defining the pf.conf [mysql] and pfconfig.conf [database] section default values of the entries can be ignored, as it will automatically pick the value from the default configuration file.  
    * Use the same values for pfconfig.conf as for pf.conf like <ip_of_remoteDB>  to be consistent between two files.
    * Here’s an example of how we have configured the pf.conf and pfconfig.conf.

```
root@pf:/usr/local/pf# cat conf/pfconfig.conf
[mysql]
user=pf
pass=“dbpass_for_pf_user”
host=<ip_of_remoteDB>
```
```
root@pf:/usr/local/pf# vim conf/pf.conf  ——> [database section]
[database]
# database.db
#
# Name of the MySQL database used by PacketFence.
host=<ip_of_remoteDB>
#
# database.user
user=pf
# Username of the account with access to the MySQL database used by PacketFence. Changing this parameter after the initial configuration will *not* change it in the database itself, only in the configuration.
#
# database.pass
#
# Password for the mysql database used by PacketFence. Changing this parameter after the initial configuration will *not* change it in the database it self, only in the configuration.
pass=“dbpass_for_PF_user ”
```
2. Once these files are modified it is necessary to mask and stop the local db (if running) and also perform a config hard reload using the following command: 
```
root@pf:/usr/local/pf# systemctl mask packetfence-mariadb.service
 root@pf:/usr/local/pf# systemctl stop packetfence-mariadb.service  —> if PacketFence has MariaDB running  
root@pf:/usr/local/pf# bin/pfcmd configreload hard
root@pf:/usr/local/pf# systemctl restart packetfence-config.service
```

# Checks that can be performed to validate the communication between PacketFence and RemoteDB

On the Packetfence, please execute the below command to make sure that Packetfence is able to connect to the DB remotely and the user "pf" has access to the remoteDB with the correct permissions.
```
  root@pf:/usr/local/pf# mysql -u pf -h <ip_of_remoteDB> -p pf   
```
 
On the remoteDB, please execute the following command to ensure the remoteDB can update data from the Packetfence server.

```  
* Mysql [(none)]> use pf 
* Mysql [pf]> SELECT * FROM keyed;
```

**Comment by mcaulifn** [comment]
@abprasa Thanks for getting back to me. I was able to replicate your config and it works as expected. However, if I start with using an external database before starting the services and never allowing a local database to be created, none of the services start correctly.

**Comment by mcaulifn** [comment]
It seems to be related to how the install is happening with a normal install vs using Ansible. I wonder if it has to do with #6962?
