### ISSUE TITLE
pfconnector: avoid race-condition on ports used

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7498]
**Describe the bug**
In pfconnector, a race-condition can occur when a port has been selected but it not used yet. The port could have been pick up by another session. We need to prevent this in the code.

Symptoms:

```
Feb 06 02:19:21 pf02 pfconnector-server-docker-wrapper[2980768]: t=2023-02-06T02:19:21+0430 lvl=eror msg="Error binding remote R:38723=>172.30.152.22:161/udp: server: session#1: tun: proxy#R:38723=>172.30.152.22:161/udp: listen: listen udp 0.0.0.0:38723: bind: address already in use" pid=1
```

**To Reproduce**
1. Generate a lot of traffic which involve simultaneous usage of pfconnector

**Expected behavior**
Each session must used a port available and not selected by another session.

**Comment by julsemaan** [comment]
Breakdown of the issue

Between here:
https://github.com/inverse-inc/packetfence/blob/bbd738dfacd402d12bf8b9c900839ed3d8b11aa4/go/chisel/server/server_handler.go#L258

And here:
https://github.com/inverse-inc/packetfence/blob/bbd738dfacd402d12bf8b9c900839ed3d8b11aa4/go/chisel/server/server_handler.go#L278

The port that was picked by `freeport` has been used by another process or thread which makes the bind to the remote impossible to do.

That code doesn't have any retry logic and the bind is also async which means the requests completes with success with a remote that has not been opened.

A solution could be to pass a channel to `tun.BindRemotes` that would send success/failure of the operation and then wait for its result before completing the request (and retrying the process if an error is sent through the channel)

**Comment by nqb** [comment]
I'm reopening because we will need to backport fix (if possible) to maintenance.
Is that ok to backport @jrouzierinverse and @julsemaan ?

**Comment by julsemaan** [comment]
> I'm reopening because we will need to backport fix (if possible) to maintenance. Is that ok to backport @jrouzierinverse and @julsemaan ?

I think it's worth waiting until the 12.2 release to publish this fix in maintenance since we're in QA phase. I tested the fix pretty well so it could also go in now if you guys are comfortable with it.

**Comment by nqb** [comment]
I agree to wait 12.2 release. There is no rush to deliver this fix because we have a workaround.
