### ISSUE TITLE
12.2 devel - Failed to do web-auth using Catalyst::2960 module

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7499]
**Describe the bug**
A valid configuration of web-auth on a 2960 fails to work correctly

**To Reproduce**
1. Configure web-auth on the 2960
2. Configure the 2960 in switches.conf
```
[192.168.3.11]
isolationUrl=http://172.105.29.53.nip.io/Cisco::Catalyst_2960
group=default
radiusSecret=xxx
UrlMap=Y
registrationUrl=http://172.105.29.53.nip.io/Cisco::Catalyst_2960
type=Cisco::Catalyst_2960
ExternalPortalEnforcement=Y
VlanMap=N
description=2960
registrationRole=registration
RoleMap=Y
```
3. Perform a MAB request with an unreg device
4. RADIUS reply doesn't contain web-auth URL
![image](https://user-images.githubusercontent.com/3857942/217008160-fb417bb0-37c9-4111-9802-09f037d06139.png)

**Expected behavior**
The RADIUS reply should contain attributes for performing web-auth (av-pairs with url-redirect-acl and url-redirect)

**Additional context**

The faulty line seems to be `if ( $args->{'compute_url'} && isenabled($self->{_UrlMap}) && $self->externalPortalEnforcement ) {` in the 2960 module where compute_url is not defined anywhere else but on this line.

**Comment by julsemaan** [comment]
I can confirm that reverting back the line to `if ( isenabled($self->{_UrlMap}) && $self->externalPortalEnforcement ) {` gets the attributes sent as it should but I'm unsure about what compute_url does and if it's necessary for something else so I'll let @fdurand decide on the proper fix

**Comment by jrouzierinverse** [comment]
@lzammit should we can retest this, or we can just close it?
Because after speaking to @fdurand what was left over from a previous commit caused the issue.
Also since @julsemaan said he tested removing and it worked.
