### ISSUE TITLE
12.2 devel - Sponsor activation email is sent in French although everything is in English

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#7501]
**Describe the bug**
I went through sponsor registration with all browsers and settings in English and received an access confirmation in French

**To Reproduce**
1. Go through sponsor registration 
2. Check email after gaining access to network
3. It's in French

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/217016819-8e7374e2-35d6-4ca8-8cdc-3bda0ef9b237.png)

**Expected behavior**
Matches the language of the user who registered

**Additional context**
The user entry for that user says it's locale is en_US too:
![image](https://user-images.githubusercontent.com/3857942/217016723-a0a747ac-6992-4a7d-be7a-bdf967f44bee.png)

**Comment by jrouzierinverse** [comment]
After reviewing everything, this may be a configuration issue.
Was the sponsor's language set to fr_FR or pf.conf advanced.language = fr_FR

**Comment by julsemaan** [comment]
Nope, fresh install that was all using default parameters in respect to language settings

**Comment by jrouzierinverse** [comment]
Did you happen to be in french mode at some point in time?

**Comment by julsemaan** [comment]
Perhaps the browser of my admin interface and where I enabled the sponsor could have been in French in the past, but it wasn't recently. Also, the locale in the user entry explicitly states it is en_US so I think the language was properly detected but can't be 100% sure.
