### ISSUE TITLE
Lines when doing node a node import is off

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#7503]
**Describe the bug**
Lines when doing node a node import is off

**To Reproduce**

1. Create csv file ```bash for i in $(seq 0 255);do printf "00:22:33:44:55:%02x, default\n" "$i";done &> nodes.csv```
2. Log into the Admin
3. Go to Nodes > Import
4. Click on 'Open CSV File'
5. Choose the file you created previously.

**Screenshots**

![Screen Shot 2023-02-06 at 6 39 47 PM](https://user-images.githubusercontent.com/2727473/217111872-d7146d89-c3c2-41ce-8ac2-92fb790d158a.jpg)

**Expected behavior**
Each element of the line have a better seperation.

**Desktop :**
 - OS: [Apple]
 - Browser [ chrome]

**Comment by jrouzierinverse** [comment]
The issue is also happens for Users import

**Comment by satkunas** [comment]
Not able to reproduce

Looks like a browser cache issue with the CSS for the column widths, please re-open if issue persists

**Comment by satkunas** [comment]
We will increase the node version from 12.x to 14.x for consistency.

**Comment by satkunas** [comment]
Fixed in 87848c043f9a517fd3264b2969f7586aa598323a
