### ISSUE TITLE
Access list sending to Aruba 2930M done wrong

### ISSUE THREAD

**Issue by confuseduserai** [inverse-inc/packetfence#7508]
**Describe the bug**
Packetfence seems to send them all according to log, every line as its own NAS-Filter-Rule, but it seems like it actually sends them as one line, and character limit is reached:
W 02/07/23 14:21:08 00712 radius: ACL error - entry too long, client
3448EDxxxx port 41

I can send 2 lines, without above error presenting it self, but it anyways only takes one line in to use.

**To Reproduce**
Create accesslist and try to send multiple lines to Aruba 2930M. 
Check from Aruba that only the first line is in use, or not at all.

Fix according to Aruba
"If you are using multiple attributes, you need add "+" denoting multiple attributes as below -

Nas-filter-Rule = "deny in tcp from any to any 23 ",
Nas-filter-Rule += "deny in tcp from any to any 80 ",

------------------------------
xx
Aruba
------------------------------"

**Comment by Yass737** [comment]
Error still present on version 12.2

**Comment by PejeDK** [comment]
I see same problem in 14.0
