### ISSUE TITLE
12.2: too much messages "ACL not supported for switch" when creating/updating a switch

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7510]
**Describe the bug**
When you create or update a switch which doesn't support ACL, frontend will display one warning **per role**.

So if you have 100 roles, you received 100 warnings.

**To Reproduce**
1. Create a switch group using Hostapd (template_based) module

**Screenshots**
![image](https://user-images.githubusercontent.com/10830260/217489428-2277c4cc-efbb-47c8-bd80-20fa01acd04e.png)

**Expected behavior**
Frontend displays only one warning or frontend doesn't display any warning.

IMHO, we should not display a warning message because majority of our switch modules doesn't support ACL. On top of that, it's an advanced use case, certainly used by 20% of our users.

**Additional context**
API response:

```
{
  "id": "switch_group_template_based",
  "message": "Settings updated",
  "status": 200,
  "warnings": [
    {
      "code": 10003,
      "message": "ACLs not supported for switch",
      "role_name": "Machine",
      "switch_id": "switch_group_template_based"
    },
    {
      "code": 10003,
      "message": "ACLs not supported for switch",
      "role_name": "REJECT",
      "switch_id": "switch_group_template_based"
    },
[..]
```

**Comment by nqb** [comment]
Reopening issue because @jrouzierinverse needs to adjust backend.

**Comment by jrouzierinverse** [comment]
done in 8e4c0ecd717425949974e7aceeca945f42013f16
