### ISSUE TITLE
v12.2: pfacct doesn't handle accounting requests

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7512]
**Describe the bug**
If I send accounting requests to my PacketFence server, I don't receive any response from `pfacct`.

**To Reproduce**
1. Send an accounting request from a switch defined in `switches.conf`

**Expected behavior**
Response from `pfacct` and accounting request proceed.

**Additional context**
Certainly related to recent containerization of `pfacct`

**Comment by nqb** [comment]
I will confirm but it's certainly an issue related to the fact that my network device is not sending `NAS-IP-Address`

**Comment by nqb** [comment]
So issue is related to the fact that device is not sending `NAS-IP-Address`. 

Once created by MAC address, accounting start to work. I think we already discuss about this when we try to containerize `pfacct`.

I will adjust integration tests.

IMHO, we should add an upgrade note to specify that `pfacct` has been containerized and network devices need to be created by MAC address if they don't send a NAS-IP-Address RADIUS attribute in Accounting packets.

**Comment by extrafu** [comment]
@nqb Is it common for NAS devices to NOT send the NAS-IP-Address attribute in the accounting packets?

**Comment by nqb** [comment]
According to [RFC 2866](https://freeradius.org/rfc/rfc2866.html#Accounting-Request):

> Either [NAS-IP-Address](https://freeradius.org/rfc/rfc2865.html#NAS-IP-Address) or [NAS-Identifier](https://freeradius.org/rfc/rfc2865.html#NAS-Identifier) MUST be present in a
      RADIUS Accounting-Request.
     
In my case here (Cumulus switch), NAS-Identifier is present. I don't know about other vendors. I never seen that while working on customer deployments so I suppose it's something uncommon.

**Comment by extrafu** [comment]
An upgrade note then is enough. Can you please add it? I can review the verbiage.
