### ISSUE TITLE
v12.2: online/offline status doesn't seem to work as expected

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7518]
**Describe the bug**
When PF received a RADIUS Accounting-Request (Start) for a node, I can see following data in DB:

```sql
MariaDB [pf]> select * from node_current_session;
+-------------------+---------------------+----------------------+-----------+
| mac               | updated             | last_session_id      | is_online |
+-------------------+---------------------+----------------------+-----------+
| 00:03:00:11:11:01 | 2023-02-09 07:53:50 | 13285392653917159195 |         0 |
+-------------------+---------------------+----------------------+-----------+
1 row in set (0.001 sec)
```

with `updated` equals to timestamp of RADIUS Accounting-Request (Start) message.

However, node appears as `offline` in GUI. API returned:

```
			"online": "off",
```

**To Reproduce**
1. Send a RADIUS Accounting-Request (Start) message to PacketFence
2. Check node status in GUI

=> node is offline

**Expected behavior**
node is online

**Additional context**
Setting `process_bandwidth_accounting=enabled` is enabled.

**Comment by nqb** [comment]
Behavior noticed since merge of #7527:
- accounting start: 
  - entry in `node_current_session` table is updated,  `is_online` equals `1`
  - node appears as "online" in webadmin
- accounting stop
  - entry in `node_current_session` table is **deleted**
  - node appears as "unknown" in webadmin

**Comment by jrouzierinverse** [comment]
How long between the start stop?

**Comment by jrouzierinverse** [comment]
The accounting stop does not delete the entry in the node_current_session table.
It is the cron job that deletes let me verify if the cron job is working properly.
