### ISSUE TITLE
tests: start_radius_test_service is unstable on 12.x in cli_login_el8 scenario

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7534]
**Describe the problem**
On cli_login_el8, the start_radius_test_service is failing.

**Mandatory informations**

 * Branch: 12.x
 * OS: only on EL8
 * Scenario: cli_login_el8
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3764471632
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3754309624
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3764552454

**Symptoms**
How the problem can be identified if it appears again ?
The step is failing.
Nothing in venom.log or artifacts. Perhaps need PF logs.

**Comment by nqb** [comment]
Must be solved by #7588
