### ISSUE TITLE
Having parking html files available the connexion profile

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7535]
**Is your feature request related to a problem? Please describe.**
The current files in https://github.com/inverse-inc/packetfence/tree/devel/html/parking are not available in the connexion profile.
They need to be "templated"

**Describe the solution you'd like**
Template them with the "poutine" catalyst

**Describe alternatives you've considered**
None: TINA

**Comment by julsemaan** [comment]
My 2 cents on this: the parking is made to be as lightweight as possible and run a very simple file server (except for the parking release). Introducing catalyst into the mix would defeat the purpose and would diminish the throughput the parking portal can do. A golang/caddy based approach would work though but would mean reimplementing some portal templates logic in Golang

**Comment by JeGoi** [comment]
Hum, so there is no perfect way to template it better than changing the file itself to maintain the current lightweight, correct?

**Comment by julsemaan** [comment]
Correct!
