### ISSUE TITLE
PF 12.2: Domain join check status broken

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7537]
````
Build: 12.2.0+20230214182604+777526048+0011+devel+bullseye1
````
![image](https://user-images.githubusercontent.com/5261214/219097567-373d620f-c30f-48f2-9120-f28533321aef.jpeg)

![image](https://user-images.githubusercontent.com/5261214/219098386-2e57848d-4bb3-48a9-a97f-4b62e4a4cff4.jpeg)

````
root@debian-pf1:/usr/local/pf# chroot /chroots/ZAMMIT/ ntlm_auth --username=administrator
Password:
NT_STATUS_OK: The operation completed successfully. (0x0)
````
````
root@debian-pf2:/usr/local/pf# chroot /chroots/ZAMMIT/ ntlm_auth --username=administrator
Password:
NT_STATUS_OK: The operation completed successfully. (0x0)
````
````
root@debian-pf3:/usr/local/pf# chroot /chroots/ZAMMIT/ ntlm_auth --username=administrator
Password:
NT_STATUS_OK: The operation completed successfully. (0x0)
````

**Comment by extrafu** [comment]
@lzammit Who should take care of that one?

**Comment by lzammit** [comment]
After fixing a clock issue on the windows server (bad timezone)

![image](https://user-images.githubusercontent.com/5261214/219448496-73116c0b-5cb6-432e-88e5-0c014b1f598b.jpeg)

````
user[administrator] realm[ZAMMIT.CORP]: The attempted logon is invalid. This is either due to a bad username or authentication information. gse_get_client_auth_token: gss_init_sec_context failed with [ Miscellaneous failure (see text): Clock skew too great](2529638949)
````

![image](https://user-images.githubusercontent.com/5261214/219448858-94499757-bf5f-4732-a028-1a8cdea7ea28.jpeg)


It works but stil display an error

**Comment by satkunas** [comment]
@lzammit I was unable to reproduce

Please retest with my last changes and either close or bump to 12.3 for a revisit post-release
