### ISSUE TITLE
pfqueue stuck even if there is job in the queue

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7538]
**Describe the bug**
I noticed on multiples setup that pfqueue sometime is just doing nothing even if there is job in redis.

A restart the service pfqueue fix the issue.
- `systemctl restart packetfence-pfqueue`
- `/usr/local/pf/bin/pfcmd service pfqueue restart`

You can check the pf queue status on specific a list with the following command line:
`/usr/local/pf/bin/pfcmd pfqueue list`
than check the list status
`/usr/local/pf/bin/pfcmd pfqueue count pfdhcplistener`

If the count never decrease, it means that you have the issue and you need to restart the service.

**Comment by extrafu** [comment]
@jrouzierinverse and @fdurand is it fixed? If so please close.
