### ISSUE TITLE
PF PKI Android CA certificates is failing to onboard

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7547]
**Describe the bug**
The current test for onboarding Android with PF PKI and the agent is failing at the last stage when everything is set on android and a radius request fail for "unknown CA". It looks like some certificates (or something else) are missing on the android.

NEED more tests

**To Reproduce**
1. Do the testlink test for android onboarding
2. See error

**Expected behavior**
Android is able to connect

**Comment by JeGoi** [comment]
Since https://github.com/inverse-inc/packetfence/tree/feature/pfpki_improvement is offering all CA, we think that the issue is on the PF Android Agent, where only the latest certificat is used: https://github.com/inverse-inc/packetfence-android-agent/blob/master/src/main/java/org/packetfence/agent/MainActivity.java#L685

It looks like also that it is possible since api24 to set several CA:
https://developer.android.com/reference/android/net/wifi/WifiEnterpriseConfig.html#setCaCertificates(java.security.cert.X509Certificat

Start a new branch for the android agent

**Comment by JeGoi** [comment]
NOTE: Looks like, it is also true with self signed certificates and Android13.
Need to be tested.

**Comment by JeGoi** [comment]
Let's take a look at CAs order in the radius configuration.

**Comment by JeGoi** [comment]
In fact, the problem is that the CA certificat issuer is not know or available on the android.
System certificate can not be used in the app, like the way, it can be selected in the ssid setting when you are doing it by hands.
The parallel on windows device is to select or not to trust the radius certificate. Here, android have to thrust the radius certificate by knowing it.

**Comment by nqb** [comment]
@JeGoi I've seen this new feature which can potentially help us: https://source.android.com/docs/core/connect/wifi-tofu

**Comment by satkunas** [comment]
@fdurand pleased review

**Comment by JeGoi** [comment]
Ok so for Android installation without the android agent:
Under "System security/Credential storage/Install certificates from storage", you need to install 
- as "CA certificate":
   * the CA Certificate that is under Packetfence Radius SSL certificate, 
   * the CA Certificate from the PKI (Packetfence or another)
   * all other intermediate certificates
- as "WIFI" and "VPN & AppUser": the certificate that provided by the PKI. If PF is the PKI, then it is the pkcs12 available from the admin.

**Comment by JeGoi** [comment]
> @JeGoi I've seen this new feature which can potentially help us: https://source.android.com/docs/core/connect/wifi-tofu

Thanks man, we have been able to make it work without it!
I hope you are well.
