### ISSUE TITLE
tests: domain join is failing randomly

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7552]
**Describe the problem**
Domain join is failing randomly

**Mandatory informations**

 * Branch: `devel`
 * Scenario: `dot1x_eap_peap` el8/deb11
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3827112670
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3827112662
 
**Symptoms**
How the problem can be identified if it appears again ?

- Nothing under /chroots
- `domain Timed out"` in /usr/local/pf/logs/api-frontend.log
- There is nothing related to domain join in pfperl-api logs

This problem seems to be directly related to #7403. When I checked pfperl-api logs, I see ` sudo: unable to resolve host pfel8dev: Name or service not known`

=> It makes sense because we change hostname of VM during configurator test suite but VM is not rebooted after.

**Comment by lzammit** [comment]
When you undergo the configurator, you set the hostname of the machine, is it happening for you ?

Having that issue slow down the server a lot.
