### ISSUE TITLE
12.2: VLAN role inheritance setting is ignored

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7554]
**Describe the bug**
When you define a VLAN for parent role in a switch and nothing for a child role, PacketFence doesn't return VLAN of parent role when device is registered with child role.

**To Reproduce**
1. Role config:
```
[inherit1]
inherit_web_auth_url=disabled
inherit_role=disabled
inherit_vlan=disabled
max_nodes_per_pid=0

[inherit2]
max_nodes_per_pid=0
inherit_role=enabled
inherit_vlan=disabled
inherit_web_auth_url=disabled
parent_id=inherit1
```

2. Register a device with `inherit2`
3. Configure a switch with:
  * inherit2: no VLAN
  * inherit1: VLAN 3

=> PacketFence doesn't return any VLAN when device is plugged on switch.

**Expected behavior**
PacketFence returned VLAN3 because inherit2 is a child of inherit1

**Additional context**
```
Feb 24 12:51:43 172-105-93-187 httpd.aaa-docker-wrapper[935118]: httpd.aaa(6) INFO: [mac:00:03:00:11:11:01] Username was defined "000300111101" - returning role 'inherit2' (pf::role::getRegisteredRole)
Feb 24 12:51:43 172-105-93-187 httpd.aaa-docker-wrapper[935118]: httpd.aaa(6) INFO: [mac:00:03:00:11:11:01] PID: "bob", Status: reg Returned VLAN: (undefined), Role: inherit2 (pf::role::fetchRoleForNode)
Feb 24 12:51:43 172-105-93-187 httpd.aaa-docker-wrapper[935118]: httpd.aaa(6) WARN: [mac:00:03:00:11:11:01] No parameter inherit2Vlan found in conf/switches.conf for the switch 44:38:39:00:00:12 (pf::Switch::getVlanByName)
```

**Comment by jrouzierinverse** [comment]
This is expected behavior since inherit_vlan is disabled
In the child role, enable inherit_vlan
```inherit_vlan=enabled```

**Comment by nqb** [comment]
Apologies!
