### ISSUE TITLE
Violations in DB aren't reloaded in active/active

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#756]
When adding modifying an action through the admin in a violation it doesn't hit the DB.

Should maybe call pf::violation_config::loadViolationsIntoDb(); ?

**Comment by jrouzierinverse** [comment]
That sound about right. This is related to some refactoring work I want to do let talk about the best approach.

**Comment by julsemaan** [comment]
hasn't been able to replicate it and the loadViolationsIntoDb is properly called.

Closing
