### ISSUE TITLE
PF 12.1 ZEN: Generate new cert on reboot

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7568]
Issue on the rc.local where it re-generate the cert upon reboot.

**Comment by nqb** [comment]
More details:

This issue affects ZEN 12.1 installations. If you replaced default RADIUS certificate and you reboot, `/etc/rc.local` will generate a new key under `/usr/local/pf/raddb/certs/server.key` which will prevent RADIUS service to start because certificate and key don't match.

**Comment by nqb** [comment]
### How to identify a ZEN 12.1 installation affected ?

Check if `/etc/rc.local` contains these three lines in that order:

```
    make -C /usr/local/pf conf/ssl/server.pem
    make -C /usr/local/pf conf/local_secret
    make -C /usr/local/pf/raddb/certs
```


If yes, your ZEN installation need to be patched

Important: if you didn't perform a ZEN installation using ZEN 12.1 image, you are not affected.


### To patch ZEN 12.1 installations (running 12.1 or greater)

```
cd /tmp/
wget https://github.com/inverse-inc/packetfence/files/10897043/rc-local.patch
patch /etc/rc.local /tmp/rc-local.patch
```
[rc-local.patch](https://github.com/inverse-inc/packetfence/files/10897043/rc-local.patch)
