### ISSUE TITLE
Some users cannot authenticate, error: Invalid user (rest: AVP exceeds buffer length or chunk) 

### ISSUE THREAD

**Issue by nathanbloemendaal78** [inverse-inc/packetfence#7572]
**Describe the bug**

Packetfence 11.1, Eduroam, radius filters in packetfence eduroam authorize. 
Some authentications fail with this error (got this from tcpdump):

{"error":{"message":"Cannot parse request","detail":"malformed JSON string, neither tag, array, object, number, string or atom, at character offset 1283 (before \"(end of string)\") at /usr/local/pf/lib/pf/WebAPI/REST.pm line 43.\n"}}POST //radius/rest/filter HTTP/1.1

In /usr/local/pf/logs/radius-eduroam.log:

Mar  6 14:20:41 servername eduroam[1727451]: (3081965) Invalid user (rest: AVP exceeds buffer length or chunk): [username@institute.com] (from client pf port 2 cli 11:22:33:44:55:66)
Mar  6 14:20:41 servername eduroam[1727451]: [mac:11:22:33:44:55:66] Rejected user: username@institute.com
Mar  6 14:20:41 servername eduroam[1727451]: (3081965) Login incorrect (rest: AVP exceeds buffer length or chunk): [username@institute.com] (from client pf port 2 cli 11:22:33:44:55:66)

**To Reproduce**
This ***only*** occurs with users from a specific institute (from outside this site), authenticating with the eduroam SSID at this site.

**Expected behavior**
These users should be able to authenticate as any other external eduroam user.

**Desktop (please complete the following information):**
 - OS: Windows 10/11

**Additional context**

**Comment by fdurand** [comment]
You will have to paste the output of raddebug on the radius-eduroam.sock.

raddebug -f /usr/local/pf/var/run/radiusd-eduroam.sock

**Comment by nathanbloemendaal78** [comment]
Will provide these ASAP. The issue hasn't reocurred yet, the users of the specific institute haven't been on our site since reporting this issue.

**Comment by nathanbloemendaal78** [comment]
Issue seems to have been client related
