### ISSUE TITLE
tests: PacketFence Version 12.1 - Facebook social login does not work with account without email

### ISSUE THREAD

**Issue by opr228** [inverse-inc/packetfence#7578]
**Describe the problem**
Setting up PacketFence & Captive Portal, everything is fine, the only thing that does not go is Facebook social login, provided the facebook user account does not have an email tied to it.

![photo_2023-03-08_16-45-48](https://user-images.githubusercontent.com/85174976/223956112-c782ead7-b38c-4bd0-8ff2-70400ccc72b4.jpg)

As far as I understood - the problem is because facebook sends empty value when login - if email is not bound, and in mysql - the cell where you enter email - contains primary key. But when I try to transfer it writes an error.

`MariaDB [pf]> ALTER TABLE person DROP PRIMARY KEY, ADD PRIMARY KEY (lang);
ERROR 1553 (HY000): Cannot drop index 'PRIMARY': needed in a foreign key constraint`

As far as I understand - if I change it and allow empty values: then authorization will pass. But then again - as far as this is the right solution - I do not know. I hope someone can help

**Comment by nqb** [comment]
Hello,

The template you used is to report issue on test in CI environment, that is not the correct one. Please select "Bug report" and follow template.
