### ISSUE TITLE
Create  new events logger is not possible

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7580]
**Describe the bug**
When you want to create a new Event Logger from the admin gui it's not possible "Unhandled syslog parser type"

**To Reproduce**
1. Go to https://mgmt_ip:1443/admin#/configuration/event_loggers/new/syslog
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/1553962/224163234-9117d19f-f5de-4f0a-9de1-1383d989f5ad.png)

**Comment by chri2** [comment]
Just found this issue after trying to create a new event logger on Packetfence 14.0.0+20241212210324+1586725144+0012+maintenance~14~0+bookworm1 cluster with 3 nodes.

Error is the same as described by @fdurand
