### ISSUE TITLE
Domain join: NTLM v2 only is disabled by default 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7583]
**Describe the bug**
When creating a domain, the option to use "NTLM v2 only" is disabled by default.

The default is to use NTLM v1 authentication, which is vulnerable to cryptographic attacks.

We should consider to enable NTLM v2 by default but we have to be careful about impact it has on authentications.

Also, if we use another approach than domain join to perform EAP-PEAP-MSCHAPv2, this issue will not be relevant.

**Comment by satkunas** [comment]
Need to find out if NTLMv2 is enabled by default on AD

**Comment by lzammit** [comment]
Enabling ntlmv2 by default would work. I've nothing enabled on my Windows server 2022.

![image](https://github.com/inverse-inc/packetfence/assets/5261214/3ab09ac6-69db-42b6-91af-204f1ee893bd)

![image](https://github.com/inverse-inc/packetfence/assets/5261214/7bdf44e3-6a13-4a8b-ad5f-587ad9a9523e)



![image](https://github.com/inverse-inc/packetfence/assets/5261214/75893b29-a180-4f9b-9d5c-3a9e8aa298f0)

**Comment by jrouzierinverse** [comment]
Do we still need this with the newer mechanism?

**Comment by stgmsa** [comment]
no we dont. ntlmv2 will be removed by default

**Comment by jrouzierinverse** [comment]
Do we close this then?

**Comment by satkunas** [comment]
@stgmsa close if PEAP works with both NTLM v1 and v2.
