### ISSUE TITLE
ISO doesn't boot in UEFI

### ISSUE THREAD

**Issue by trs80** [inverse-inc/packetfence#7599]
**Describe the bug**
The ISO doesn't boot in a UEFI VM (and presumably physical UEFI too)

**To Reproduce**
1. Configure VM in UEFI mode, try to boot PF ISO
2. ISO fails to boot

**Expected behavior**
PacketFence installs Debian in UEFI mode

**Desktop (please complete the following information):**
 - OS: VMware ESXi
 - Version: 7.0

**Additional context**
This also affects Hyper-V Gen 2 VMs

**Comment by trs80** [comment]
Fix based on https://github.com/inverse-inc/packetfence/issues/7113#issuecomment-1220250533 which is based on https://wiki.debian.org/RepackBootableISO
I haven't actually tested booting it, but I also didn't test building it inside docker or with your CI

**Comment by nqb** [comment]
I tested ISO built against devel with UEFI and non UEFi boots: both works.
