### ISSUE TITLE
Changing switch IP via gui is impossible

### ISSUE THREAD

**Issue by Yannik** [inverse-inc/packetfence#7601]
**Describe the bug**
Changing a switches IP via the gui results in a item not found error. It seems to erroneously write the change to the new identifier - which does not exist yet. 

**To Reproduce**
1. Create a switch with IP 10.1.1.1
2. Try to change it's ip to 10.1.1.2
3. See " Item (10.1.1.2) not found" error

(Latest packetfence 12.2)

**Comment by satkunas** [comment]
This field is the switches identifier, which is immutable.

Instead, clone the switch, choose a new id, then delete the original.
