### ISSUE TITLE
Consider deprecating snmptrapd

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7608]
**Describe the bug**
Port security use case using `snmptrapd` is something untested and not used anymore. We will deprecate it for v13.

**Comment by fdurand** [comment]
it's still used

**Comment by nqb** [comment]
@fdurand, are we sure it works on v12 ?

**Comment by fdurand** [comment]
yes it works, we have someone who is using it on a v12 version.

**Comment by nqb** [comment]
We must consider this for v13 if we don't want to continue to support these use cases. We have a poor test coverage on this between each release.

**Comment by extrafu** [comment]
We might want to keep link up/down if we secure assets on core switches.

**Comment by satkunas** [comment]
We have clients using this feature, will not remove
