### ISSUE TITLE
AD unreg powershell scripts are not working

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#761]
Unreg disabled account: ERROR: Missing argument pid for the function pf::api::unreg_node_for_pid (pf::api::validate_argv)
Unreg delete account: ERROR: Missing argument pid for the function pf::api::unreg_node_for_pid (pf::api::validate_argv)
Unreg locked account: Didnt test yet

**Comment by lzammit** [comment]
Fixed and pushed into devel
