### ISSUE TITLE
tests: pipeline timeout is ignored

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7610]
**Describe the problem**
A job has been canceled by GitLab, after 90 minutes, even if pipeline timeout (3h) was not reached.

This situation should not happen.

When a job is stopped like this on a `shell` runner , it prevents VM to be stopped correctly (due to a GitLab issue).
Consequently, next test jobs on this runner will fail because VM are still started.

It seems to be a new bug in GitLab, @JeGoi will update `gitlab-runner` software on all runners.

**Mandatory informations**

 * Branch: 12.2
 * Scenario: fingerbank_invalid_db
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/4003798515
 
**Symptoms**
How the problem can be identified if it appears again ?

A test job is canceled by GitLab **before** 3h of execution.

**Comment by JeGoi** [comment]
Following the doc but with restriction on runner2
`    Inst nodejs [14.21.1-deb-1nodesource1] (14.21.3-deb-1nodesource1 Node Source:deb.nodesource.com [amd64])`
Let's hope that `nodejs` is not an issue.
I will do it on runner 2.

**Comment by nqb** [comment]
I think `nodejs` is specific to runner2 where we do tests but this package is not installed on other runners (AFAIK).

**Comment by nqb** [comment]
`gitlab-runner` package has been updated by @JeGoi on all runners.

**Comment by nqb** [comment]
Doesn't seem to happen anymore on runners. Closing for now.
