### ISSUE TITLE
Captive Portal with single Continue button disabled

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#7615]
**Describe the bug**
Portal workflow with a single continue button is disabled.

**Screenshots**

![Screenshot 2023-03-30 at 1 39 18 PM](https://user-images.githubusercontent.com/3904468/228920741-cdcb4867-ecc4-462e-8e09-04fef09904c1.jpg)
![Screenshot 2023-03-30 at 1 39 13 PM](https://user-images.githubusercontent.com/3904468/228920749-a5b2eb31-08f7-4843-addd-6b97cdd59109.jpg)

**Expected behavior**

Continue button should be enabled

**Additional context**
No console errors

**Comment by satkunas** [comment]
```conf
[default_login_policy]
description=Username/password
aup_template=aup_text.html
with_aup=0
pid_field=username
custom_fields=
fields_to_save=
actions=
signup_template=signin.html
source_id=

[XYZ-Guest]
description=Temporary Guest [6 hours]
type=Authentication::Null
with_aup=0
aup_template=aup_text.html
signup_template=signin.html
custom_fields=
actions=
fields_to_save=
source_id=null

[XYZ-Guest-Choice]
template=content-with-choice.html
show_first_module_on_default=disabled
actions=
modules=Student-login,Staff-AAD,XYZ-Guest
type=Choice
description=XYZ-Guest-Choice

[Message]
template=message.html
message=Message
actions=
skipable=1
with_layout=1
description=My pretty message
type=Message

[XYZ-Wireless]
modules=XYZ-Guest-Choice
description=XYZ Wireless
type=Root

[Staff-AAD]
pid_field=username
custom_fields=
actions=
fields_to_save=
source_id=AAD
signup_template=signin.html
type=Authentication::Login
description=Permanent Staff Registration
aup_template=aup_text.html
with_aup=0

[Student-login]
signup_template=signin.html
actions=
type=Authentication::Login
with_aup=0
pid_field=username
source_id=XYZ-LDAP
custom_fields=
description=Student Registration
fields_to_save=
aup_template=aup_text.html
```

**Comment by lzammit** [comment]
Is it in maintenance ?

**Comment by satkunas** [comment]
@lzammit yes, backported to maintenance/12.{0,1,2}

**Comment by LizardNerd** [comment]
I applied the patch to fix captiveportal.js, but the issue is not fixed:

![ggg](https://github.com/inverse-inc/packetfence/assets/79976861/7fa1e754-eb50-4c6b-b4bb-35f1f7b03462)

PacketFence version: packetfence 12.2.0+20230515161154+870742857+0011+maintenance_12_2+bullseye1

**Comment by satkunas** [comment]
Note that the Captive Portal template `layout.html` has been modified to remove jQuery. Copying olde(er) captive portal templates into a more recent version requires manually updating the contents within the `<head>...</head>` tag so that `jquery-shim.js` is used instead of `jquery-1.11.3.min.js`

See https://github.com/inverse-inc/packetfence/pull/7210/files#diff-e060bb71de180305a01af12fea535899f4a2c58bb86974e6e22c459df322d973L8-L11
