### ISSUE TITLE
Validation failed for 'Maybe[Str]' with value

### ISSUE THREAD

**Issue by djeclemen** [inverse-inc/packetfence#7622]
**Describe the bug**
Changed smstext in ClickatellSource to contain Danish characters: æøå

**UPDATED:** Its not the danish characters that triggers the error, its actually the linebreak in the message, if the message is:
`æøåGuest access code to network: $pin Powered by XXX.`
its works, but if it is 
`æøåGuest access code to network: $pin 
<NEW LINE>Powered by XXX.`

Then it fails

**To Reproduce**
1. Go to Configuration - Authentication Sources - Edit clickatell source - Add Danish charectors to SMS text (æøå)
Afterwards when you go to authentication sources, non is shown and the error is shown 
" Unknown error, check server side logs for details. 
config/sources"

Logs shows this error:

`Apr 10 07:41:07 pf pfperl-api-docker-wrapper[150328]: pfperl-api(12) ERROR: [mac:[undef]] Attribute (message) does not pass the type constraint because: Validation failed for 'Maybe[Str]' with value [ "G steadgang til tr dl st net: $pin ", "Powered by ." ] at constructor pf::Authentication::Source::ClickatellSource::new (defined at /usr/local/pf/lib/pf/Authentication/Source/ClickatellSource.pm line 137) line 138
Apr 10 07:41:07 pf pfperl-api-docker-wrapper[150328]: pfappserver::Form::Config::Source::get_source('pfappserver::Form::Config::Source::Clickatell=HASH(0x55988a0c60d0)') called at /usr/local/pf/lib/pfappserver/Form/Field/SourceRuleAction.pm line 54`

The SMS message is shown correct with the danish characters but now the Authentication Sources page is not loading any sources at all

PF version 12.2.0

**Comment by djeclemen** [comment]
![image](https://user-images.githubusercontent.com/6986851/230835648-d5b1da95-9079-4c72-9c62-0b68db25fd4b.png)

**Comment by djeclemen** [comment]
![image](https://user-images.githubusercontent.com/6986851/230835725-994dc034-b469-4a48-8332-da97490548f3.png)

**Comment by djeclemen** [comment]
![image](https://user-images.githubusercontent.com/6986851/230836109-b8d0ad80-7964-48af-8887-b7e79e5fe998.png)

**Comment by jrouzierinverse** [comment]
Thanks for the report let me look into it.
