### ISSUE TITLE
Is it possible to authenticate login to network equipment?

### ISSUE THREAD

**Issue by bryambalan** [inverse-inc/packetfence#7626]
![image](https://user-images.githubusercontent.com/17807481/231450714-055ba857-9402-496c-8ffb-18c412210200.png)

I would like to use PacketFence as a Radius Server to authenticate devices on my network.

And use it as a database for my users.

Then I would register it:

Network equipment: Switch
Users: User
The group this user is part of: ????
And link to this group the XPTO attributes: ????

**Is it possible to do this in PacketFence? Where do I have to go to create the group and link the attribute to the group?**

**And how do I make PacketFence at the time of Access-Request, look if the user is part of my database?**

**Comment by extrafu** [comment]
Ask the mailing list, not the BTS.
