### ISSUE TITLE
tests: get_id_of_radius_audit_log_entry FAILURE

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7637]
**Describe the problem**
```
            • get_id_of_radius_audit_log_entry FAILURE
    Testcase "get_id_of_radius_audit_log_entry", step #0: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 404 (/usr/local/pf/t/venom/test_suites/wired_dot1x_eap_peap/55_check_radius_audit_log.yml:85)
    Testcase "get_id_of_radius_audit_log_entry", step #0: Assertion "result.bodyjson.items.items0 ShouldContainKey id" failed. unable to cast <nil> of type <nil> to map[string]interface{} (/usr/local/pf/t/venom/test_suites/wired_dot1x_eap_peap/55_check_radius_audit_log.yml:86)
```

**Mandatory informations**

 * Branch: Devel
 * Scenario: All scenarios that used it (fingerbank invalid db, eap peap ...)
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/4175026709 (NOTE: that pipeline is based on devel after the merge taht changed that part)
 
**Symptoms**
How the problem can be identified if it appears again ?

**Comment by JeGoi** [comment]
Still failing, need to increase or decrease time before testing.

**Comment by nqb** [comment]
I'm able to see that bug on `devel` too. The message returned by API is "no entries found". It means 

I checked timings and RADIUS request is correctly inserted in DB before we start to perform a query through API. Query through API is correct because I'm able to get results.

I think this error is specific to a period. I will see if I can catch it when it happens.

**Comment by nqb** [comment]
I was able to replicate and to understand: the `/api/v1/radius_audit_logs` API call doesn't return anything even if we have an entry created in `radius_audit_log` table. More than 5 minutes after entry has been added, that is still the case.

@jrouzierinverse  and @stgmsa, do you think it could be related to #7595 ?

**Comment by jrouzierinverse** [comment]
In my testing /api/v1/radius_audit_logs is returning something the only way.
I can see this happening is either you are not using an update pfhttpd or your api.conf config is not vaild

**Comment by nqb** [comment]
As I mentioned in my first comment @jrouzierinverse, it seems to be specific to a period. Seems to be a race condition.
