### ISSUE TITLE
Improper Access Contol

### ISSUE THREAD

**Issue by vrnsxn786** [inverse-inc/packetfence#7642]
**Describe the bug**
This bug allows us to access confidential billing folder present in source directory this folder contains various configuration settings and values regarding payment.

**To Reproduce**
1. Go to 'https://www.packetfence.org/doc'
2. Click on 'images' folder
3. Scroll down to 'billing' folder
4. Open billing folder, You will see various images, open one by one and you will see confidential details of payment configuration.
5. Final URL : https://www.packetfence.org/doc/images/billing/ 

**Screenshots**
![PACKETFENCE ORG](https://user-images.githubusercontent.com/25004906/235617810-0337d592-09f8-4fcf-92be-4ac64754ec14.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 -Google Chrome : Version 112.0.5615.137 (Official Build) (64-bit)

**Additional context**

If you find my report helpful, I would greatly appreciate it if you could recommend me on Twitter under the handle _varunsaxena. Your support would be an immense encouragement for me to continue working on security research and helping to make the online world a safer place.

**Comment by vrnsxn786** [comment]
Why is this closed @nqb  ? Is it patched ?

**Comment by nqb** [comment]
These files are images which represent example of configuration for PacketFence. All informations related to payment are fake.
