### ISSUE TITLE
cannot sudo run nano or vi/vim on debian 11 azure vm

### ISSUE THREAD

**Issue by ghost** [inverse-inc/packetfence#7648]
Hello.

On a freshly deployed Azure Debian 11 Gen2 x64 VM, just after installing packetfence with apt following the documentation, I cannot edit any files with sudo.

"sudo nano" returns "Error opening terminal: unknown."
"sudo vi" returns "
E558: Terminal entry not found in terminfo
'unknown' not known. Available builtin terminals are:
    builtin_amiga
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
"
echo $TERM returns "xterm".

Same problem with MobeXterm, RoyalTS, Putty or even Serial Console directly on Azure.

I reinstalled everything from scratch 3 times. Everything is fine before apt-get install packetfence.
without sudo, these commands run fine.

I have tried everything I could find on the Internet to solve this problem, but I am now stuck.
As I cannot edit any file, the packetfence configuration is impossible

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by heapdavid** [comment]
Hi, we came across the same issue and it look to be related to changes made to the debian sudoers file in this commit stopping the `$TERM` value from being passed to the sudo environment:

https://github.com/inverse-inc/packetfence/commit/c37b32b012a934282ecd91f10f1d09dd7e402a60

When we change it to `Defaults env_check="PF_UID PF_GID TERM", !requiretty` the error disappears and we can edit files with sudo again
