### ISSUE TITLE
Supported material: RADIUS Dynamic VLAN capability is supported on all devices

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7659]
**Describe the bug**
On https://www.packetfence.org/about.html#/material, I noticed that the column "RADIUS Dynamic VLAN" is checked for all network devices which is a bit confusing.

If I'm not wrong, the root cause is:
https://github.com/inverse-inc/packetfence/blob/04c8370560bb49a92484fdd2e9a25eb15ce8b00b/lib/pf/Switch.pm#L70-L91

**To Reproduce**
1. Search for any network device on https://www.packetfence.org/about.html#/material

**Expected behavior**
I suggest to remove that column from Supported material webpage to avoid any confusion.

**Comment by JeGoi** [comment]
Wow, except Cisco Catalyst 2950... Weird.
I will check that, thanks

**Comment by JeGoi** [comment]
Confirmed
It is there since a long time ago...

**Comment by JeGoi** [comment]
@jrouzierinverse @fdurand looks like a default It was there before. Does it make sens?
Only the "Cisco Catalyst 2950" has the opposite with the "-"

**Comment by extrafu** [comment]
@JeGoi Let's remove the column entirely and we'll regenerate the list for v13.

**Comment by extrafu** [comment]
We'll also need to add a new column to ACLs precreation.
