### ISSUE TITLE
VLAN filter: save a value from a RADIUS request doesn't work

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7671]
**Describe the bug**
If you want to save a value from a RADIUS request into a DB field of a node, you can use a VLAN filter like this:

```
[copy_mobile_iron_uuid_into_node_attributes]
status=disabled
top_op=and
run_actions=enabled
condition=ssid == "WIFI"
scopes=NodeInfoForAutoReg
description=copy_mobile_iron_uuid_into_node_attributes
action.0=modify_node: mac, $mac, computername, $radius_request.TLS-Client-Cert-Common-Name
```

However, it seems that `$radius_request.TLS-Client-Cert-Common-Name` is not handled correctly (see screenshot)

**To Reproduce**
1. Use VLAN filter mentioned above
2. Match VLAN filter using a RADIUS request
3. Check Computer Name value on your node

=> Value is: 

![image](https://github.com/inverse-inc/packetfence/assets/10830260/75a41d16-e88a-415d-81ec-0a8e961cbbab)

**Expected behavior**
The value of RADIUS attribute is saved in the node field.

**Comment by jrouzierinverse** [comment]
This is already supported just use this syntax
```
action.0=modify_node: mac, $mac, computername, ${radius_request.TLS-Client-Cert-Common-Name}
```
