### ISSUE TITLE
"Continue" button on Captive Portal is disabled, can't submit credentials

### ISSUE THREAD

**Issue by LizardNerd** [inverse-inc/packetfence#7676]
**Description**
During the authentication process of an user against captive portal, the credentials cannot be submitted because "Continue" button is disable. MAB protocol is used. Correlated to #7615

**To Reproduce**
1. Connect an endpoint to a RADIUS client;
2. Wait for RADIUS Accept-Request to be submitted;
2. Wait for Captive Portal to appear;
3. Insert the credentials and try to submit them.

**Screenshots**
![239921757-7fa1e754-eb50-4c6b-b4bb-35f1f7b03462.png](https://github.com/inverse-inc/packetfence/assets/79976861/bd775e06-4f86-4405-9fb6-1ff60de9415c)

**Expected behavior**
"Continue" button should be enable in order to submit credentials during authentication with captive portal.

**Desktop (please complete the following information):**
 - PacketFence version: packetfence 12.2.0+20230515161154+870742857+0011+maintenance_12_2+bullseye1
 - OS: Windows 10 & Ubuntu 20.04
 - Browser Chrome & Mozilla

**Comment by LizardNerd** [comment]
I solved the issue deleting the "disabled" attribute from the signin.html file, in all docker containers and packetfence's installation path, but I don't know if it is the proper way to fix it. Now I'm able to authenticate with MAB correctly.

**Comment by satkunas** [comment]
Thank you for posting this issue.

Same as https://github.com/inverse-inc/packetfence/issues/7615

The nightly build CI/CD pipelines for the maintenance branches have an unrelated issue that we are currently working on. Once these nightly build pass the patch from the issue above will be available for update.
