### ISSUE TITLE
pfdns returns real IP address in place of captive portal address to unregistered devices

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7685]
**Describe the bug**
In a VLAN enforcement setup (registration/isolation networks), `pfdns` will return real IP address of any hosts through DNS to unregistrered devices which are on registration or isolation networks.

**To Reproduce**
1. Setup a VLAN enforcement setup
2. Put a node on registration or isolation network
3. Make a DNS request to a public website from node

=> `pfdns` will return public IP address of website.

**Expected behavior**
`pfdns` will return captive portal IP address to unregistered devices.

**Additional context**
Behavior noticed on `devel`.

I set `record_dns_in_sql=enabled` in `pf.conf` but there are no records in DNS Audit logs.

I got a quick discussion with @fdurand and we think it could be related to #7197

**Comment by fdurand** [comment]
It's an issue with the order we load the plugins, We add pfdns and logger at the end but they needs to be loaded before others. There is a patch in devel https://github.com/inverse-inc/packetfence/commit/11460640a3ffeeb6fa28d11ccb59f635f0d09536 and i will test it in real and maybe i will have to specify the exact  position of the plugin.

**Comment by fdurand** [comment]
Put back the plugins in the previous position in core dns, should be working exactly the same as with the previous version of coredns. https://github.com/inverse-inc/packetfence/commit/c030aee0655a195f71129e96aff3b1201ca1b79b
