### ISSUE TITLE
Create a script to remove unused provisioners

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#7691]
Create a script to remove deprecated provisioners

**Comment by jrouzierinverse** [comment]
Fixed by 67f2eb24cbef1f1e1915c2923950df65e40313b3

**Comment by nqb** [comment]
I'm reopening this issue because script needs to be adjusted.
After I run the script, provisioners were removed from `profiles.conf` and `provisioning.conf`, however, `pfconfig` still have references to provisioners:

```console
$ pfcmd pfconfig get 'config::Profiles'
                        'wired_dot1x' => {
[..]
                                            'provisioners' => [
                                                                'android',
                                                                'ibm_prov',
                                                                'opswat_prov'
                                                              ],
[..]
```

It prevents RADIUS requests to be handle properly:

```
Jun 15 10:42:55 172-105-93-187 httpd.aaa-docker-wrapper[2806138]: httpd.aaa(8) ERROR: [mac:77:77:77:77:77:77] radius authorize failed with error: ibm is not a valid type at /usr/local/pf/lib/pf/factory/provisioner.pm line 57.
```

**Comment by nqb** [comment]
I missed to mention that I restarted `pfconfig` service several times after I run the cleanup script.

Running `pfcmd pfconfig clear_backend` doesn't work.

`pfcmd pfconfig reload` works.

**Comment by jrouzierinverse** [comment]
This is expected behavior. Was a `pfcmd configreload` ran afterwards?

**Comment by jrouzierinverse** [comment]
Also, the script is ran automatically during the upgrade process.
Afterward, a configreload is ran so as long as `pfcmd configreload` works properly then we should be good.

**Comment by nqb** [comment]
Ok, it's possible I missed that step.
