### ISSUE TITLE
configreload hard in a cluster will overwrite manual changes made on a cluster member

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7723]
**Describe the bug**
If you need to edit **manually** a file on a cluster (i.e. `report.conf`). Most of the time, you will edit this file on `pf1` then you need to run:

```
/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/cluster/sync --as-master
```
(1) to notify `pfconfig` about your change
(2) to synchronize this file with other cluster members.

On v12.X, after first command, manual changes are overwritten and your file is similar to the file on other cluster members.

**To Reproduce**
1. Make a manual change on one node in a cluster
2. Run `configreload hard`
3. Check your changes

=> Changes have been overwritten.

**Expected behavior**
Changes are kept.

**Additional context**
AFAIK, this behavior was not present before v12.

**Workaround**
1. Disable "cluster_check" maintenance task through GUI + restart pfcron service on all cluster members
1. Make manual changes on pf1
1. Run following commands on pf1:
```
/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/cluster/sync --as-master
```
1. Check manual changes have been synchronized on all cluster members
1. Re-enable "cluster_check" maintenance task through GUI + restart pfcron service on all cluster members

**Comment by satkunas** [comment]
See if this works
```
/usr/local/pf/bin/cluster/sync --as-master
/usr/local/pf/bin/pfcmd configreload hard
```

**Comment by nqb** [comment]
It works as expected. I updated documentation (see commit related)
