### ISSUE TITLE
Help for lab

### ISSUE THREAD

**Issue by ydphenix** [inverse-inc/packetfence#7727]
When a user connects to the network in question, he will be authorised to access it using his mac address, and then the pfsense, which is also located in the infra-network, will be the one to deliver the IP addresses.
Can you provide us with resources (video demos, PDF document illustrating the setup etc.) that will enable us to set up this lab?

We look forward to hearing from you.

Best regards.

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
