### ISSUE TITLE
ci: runner3 is not able to upload to sourceforge

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7731]
**Describe the bug**
In CI, runner3 is not able to upload ISO or ZEN to Sourceforge.

**To Reproduce**
1. Run a build (ISO or ZEN) with runner3 as runner

=> Upload will fail:

https://gitlab.com/inverse-inc/packetfence/-/jobs/4570649698

**Additional context**
`gitlab-runner` user is not able to connect without password to Sourceforge.

IIRC, `runner3` was never configured to perform this task because it was initially a runner used for local tests.
@JeGoi, I suppose you assigned `shell-sourceforge` tag by mistake to this runner.

**Comment by JeGoi** [comment]
Hum, I think we should have one not in ciserver-wan that is able to do so.
Runner3 was the only one started but it could be done by another runner that is not in lab access (due to restrictions).

**Comment by JeGoi** [comment]
It is working now.
https://gitlab.com/inverse-inc/packetfence/-/jobs/4590729940
