### ISSUE TITLE
PacketFence 13: Radius audit log doesn't work anymore

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7733]
**Describe the bug**
Radius Audit log is empty but the server receive radius requests.

**Error**
Jul  5 11:09:15 pf2 pfcron-docker-wrapper[3574]: t=2023-07-05T11:09:15-0400 lvl=eror msg="flush_radius_audit_log error running: ERR wrong number of arguments for 'lpop' command" pid=7

**Comment by nqb** [comment]
Related to https://github.com/inverse-inc/packetfence/issues/7637

**Comment by satkunas** [comment]
PIpeline failed: https://gitlab.com/inverse-inc/packetfence/-/jobs/4659057852
