### ISSUE TITLE
Change to debian sudoers file prevents passing of $TERM to sudo environment

### ISSUE THREAD

**Issue by heapdavid** [inverse-inc/packetfence#7738]
**Describe the bug**
Changes made to the debian sudoers file in this commit stop the `$TERM` value from being passed to the sudo environment:

https://github.com/inverse-inc/packetfence/commit/c37b32b012a934282ecd91f10f1d09dd7e402a60

When sudoing, it sets `$TERM=unknown`, which creates issues with running various commands (including `nano`, `less`, `vi`, `journalctl`) as sudo, e.g.:

```
$ sudo nano
Error opening terminal: unknown.
```

When we change the line to `Defaults env_check="PF_UID PF_GID TERM", !requiretty` the error disappears and we can run commands with sudo again, but it feels like maybe these defaults (or at least the `env_check`) should only apply to the `pf` user?

**To Reproduce**
1. Install PF 12.1+ on Debian 11
2. Try to run commands listed above as sudo

**Expected behavior**
Sudo behaviour for non-`pf` users to behave as usual, passing `$TERM` into sudo environment as expected

Edit:  https://github.com/inverse-inc/packetfence/issues/7648 - replied there initially but with the issue being closed it might not get seen

**Comment by fuomag9** [comment]
This is still present in a stock install of 13.0

```
sudo nano /etc/freeradius/mods-available/ldap
Error opening terminal: unknown.
```

**Comment by andrew-grasso** [comment]
Thanks for the writeup. I am running into the same issue on fresh installs of 13. This is really annoying to me, so I'm surprised to find only two people mentioning it in the year since the commit.
