### ISSUE TITLE
UI - Domain Unjoin shows an error

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#7761]
**Describe the bug**
Join Domain works as expected, using the same credential an Unjoin Domain succeeds, but the UI incorrectly treats it as a failure. 

**To Reproduce**
1. Go to 'Policies & Access Control > Domain'
2. Create a new Domain and Join.
3. Click Unjoin

**Comment by satkunas** [comment]
@jrouzierinverse assigning you

The backend returns success (200) on error, this needs to be adjusted for errors @ `/test_join`,`/join`, `/unjoin` and `/rejoin`. Note this is through pfqueue polling.

```
{
    "item": {
        "status": 200,
        "message": "Failed to join domain: failed to lookup DC info for domain 'ABHIAD.LAN' over rpc: The attempted logon is invalid. This is either due to a bad username or authentication information."
    },
    "message": "Completed",
    "progress": "100",
    "status": 200
}
```

**Comment by extrafu** [comment]
@satkunas @jrouzierinverse @stgmsa with the PEAP rework I think we can close that

**Comment by extrafu** [comment]
Closing since no longer relevant.
