### ISSUE TITLE
PF12.1: Preview of AUP page gives a blank response

### ISSUE THREAD

**Issue by abprasa** [inverse-inc/packetfence#7765]
**Describe the bug**
Accessing the preview page of "aup_text.html" in the "connection profiles > files" section shows a blank response. 

**To Reproduce**
1. Go to Connection profiles > Files Tab on 12.1 PF
2. Click on the preview next to the file 'aup_text.html'
3. Show a white page.

**Screenshots**
![Screenshot 2023-07-17 at 7 28 00 PM](https://github.com/inverse-inc/packetfence/assets/123509565/f8055d08-a5a4-4563-9add-c1c8e5b4d9fb)

**Expected behavior**
We should see the AUP page

**Desktop (please complete the following information):**
 - OS: Mac-OS
 - Browser: Any browser (tested on Firefox and Chrome)
 - Version: Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by jrouzierinverse** [comment]
Was this on the latest maintenance of 12.1?

**Comment by abprasa** [comment]
Thanks @jrouzierinverse, found that this behavior is fixed in the latest 12.1 maintenance patch. 

Next action: 
Need to check with the customer if he's on the latest maintenance.

**Comment by abprasa** [comment]
Advised the customer to move to the latest 12.1 maintenance patch, that fixed the issue.
