### ISSUE TITLE
PF 13: LDAP explorer not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7768]
PF version:

````
root@debian-pf1:/usr/local/pf# dpkg -l packetfence
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                                              Architecture Description
+++-==============-====================================================-============-=========================================================
ii  packetfence    13.0.0+20230717231108+934755451+0011+devel+bullseye1 all          PacketFence network registration / worm mitigation system
````

![image](https://github.com/inverse-inc/packetfence/assets/5261214/39df3267-b35b-43ac-bc80-855acb7b334b)

![image](https://github.com/inverse-inc/packetfence/assets/5261214/3c33ecb0-3988-44cf-b204-e7b423b277ae)

**Comment by extrafu** [comment]
@lzammit Is the pfldapexplorer service running? @VakarisZ what evidences (and from where) can we provide?

**Comment by VakarisZ** [comment]
I need full configuration. Is the connector enabled? Take a look at what kind of response do you get back, 400 or 500. Can the PF instance access the ldap server (maybe networking issue?)
