### ISSUE TITLE
PF 13: Domain join does not tell to restart radiusd

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7778]
I will be nice to tell users to restart radiusd once the domain is joined.

**Comment by fdurand** [comment]
For me it doesn't make sense to restart radius after a join. We do a call to ntlm_auth so if the server is joined it will work if no then it won't.

**Comment by extrafu** [comment]
Are there any changes to FreeRADIUS's realm configuration done after joining the server to an AD domain that would require a restart?
