### ISSUE TITLE
PF 13: Windows provisionner not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7782]
Windows profile wants to trust the server identity.

PerformServerValidation is set a true and need to be false.

When it's false, it works.

**Comment by JeGoi** [comment]
@lzammit please could you check this PR: https://github.com/inverse-inc/packetfence-windows-agent/pull/17

**Comment by lzammit** [comment]
Still the same after the fix, maybe wrong .exe?

![image](https://github.com/inverse-inc/packetfence/assets/5261214/7282f422-112b-44c9-aa08-ed85f900e5b0)
