### ISSUE TITLE
PFv13 Slow Performance seen during Radius load test

### ISSUE THREAD

**Issue by abprasa** [inverse-inc/packetfence#7783]
**Describe the bug**
During the load testing noticed a significant delay/slow response (~3s) from PacketFence while processing radius requests.

**To Reproduce**
1. Configure a machine for load-testing to be able to send radius requests to the PFv13 server for a fixed amount of time. (~2mins).
As shown in the below Wiki: https://wiki.inverse.ca/focus/PacketFence/Devel/LoadTesting
3. Import Mock_data.csv to import local users on PF. 
4. Enable "Authenticate against local users database" in System configuration > Radius > General
5. Perform the test from the load testing machine using the below command: 
```
root@LoadTester:~/loadtester# PATH=$PATH:`pwd` ./run_plan new-2min-peap.conf | grep '^Type' | sort -h
```

**Screenshots**
PEAP Test Config file:
![Screenshot 2023-08-01 at 1 18 59 PM](https://github.com/inverse-inc/packetfence/assets/123509565/d958d6ff-1e60-4a8b-a1cb-9a5846ac5d9b)

PEAP Test Output:
![Screenshot 2023-08-01 at 1 18 37 PM](https://github.com/inverse-inc/packetfence/assets/123509565/c1e6dc1b-521c-4bfe-b235-d6e4524616b8)

**Expected behavior**
The median for PEAP/Portal load test should be less than <1 sec, as observed previously with recent PF  releases.

**Additional context**
The same test output from v12.2 with a similar setup
```
root@LoadTester:~/loadtester# PATH=$PATH:`pwd` ./run_plan 2min-peap.conf | grep '^Type' | sort -h
Time's up. Exiting.
Time's up. Exiting.
Time's up. Exiting.
Type: acct Total: 8382 Failures: 0 Median: 0.0428074645
Type: dhcp Total: 790 Failures: 0 Median: 0.150781404
Type: radius_eap Total: 3448 Failures: 0 Median: 0.088164188
```

**Comment by Ieno77** [comment]
I upgraded my server to v13, here the results:

![loadtest13](https://github.com/inverse-inc/packetfence/assets/56310726/1d7d5128-fc1e-485a-a373-32ab732682ba)

**Comment by abprasa** [comment]
Network latency caused the overall delay as the server I was running the tests from was in CA and my PFv13 server was in IN. Re-ran the tests with servers in the same region provided a much faster response. Hence this issue can be closed.

**Comment by satkunas** [comment]
Non-issue, test setup was using different geo's
