### ISSUE TITLE
JSON error when updating SCEP portion of PKI template

### ISSUE THREAD

**Issue by carlog-stan** [inverse-inc/packetfence#7805]
**Describe the bug**
I'm trying to edit a PKI template to enable SCEP, but I keep getting a json error "json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int" when saving it.  I captured the http request, and see that it is sending a PATCH to /api/v1/pki/profile/5.  Inspecting that with Fiddler, I see the json ends with "scep_enabled":1,"cloud_enabled":1,"cloud_service":"PF_Intune".  Thinking that the values of 1 are unquoted and integers, I sent it to Fiddler Composer and changed it to "scep_enabled":"1","cloud_enabled":"1","cloud_service":"PF_Intune" and submitted it through Composer.  Instead of the 500 error I got before when submitting, it gives me a 200 and all looks good (in Fiddler).  Looking at the configuration in PacketFence, I can see that is looks like the settings have applied, including the number of days before SCEP renewal, but the checkboxes for SCEP enabled and Cloud Integration are still unchecked.

**To Reproduce**
1. Go to Configuration, Integration, PKI, Templates
2. Click on template for client certificates
3. Go to SCEP tab and enable SCEP.  Also add SCEP cloud service
4. See error: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int

**Expected behavior**
It should just save the configuration

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Tried Edge and Chrome
 - Version the latest

**Comment by gorman553** [comment]
I also encounterd this bug. Any news on this?

Thanks

gorman

**Comment by satkunas** [comment]
The `name` needs to be included in the payload for the identifier. The identifier in the URL is ignored. 

This works:

```bash
curl -X 'PATCH' \
  'https://localhost:9999/api/v1/pki/profile/3?' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/json' \
  -d '{"name":"T1", "scep_enabled": "1"}'
```

The backend is using Gorm which differs from the Perl endpoints. We will eventually update gorm endpoints to resemble the perl endpoints.
