### ISSUE TITLE
Unable to select SASL mechanism and timeout not honored

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#7813]
When configure SMTP settings in System Configuration > Alterting, it's not possible to select the SASL mechanism to use if SMTP authentication is required.

For example, if the server advertises "GSSAPI NTLM LOGIN", we'll incorrectly pick the first, GSSAPI which will lead to SMTP send failures.

We should force the user to pick between PLAIN and LOGIN, the only two we should support. PLAIN should be the default.

Also, the timeout isn't honored correctly when sending mails, especially in-between the TLS negotiation and the SMTP authentication. If it takes a couple of seconds, it'll fail independently of the timeout set in System Configuration > Alterting.

@fdurand please put the 2 lines of code you added at a customer to make it work, so anyone working on this will have some inspiration.

**Comment by fdurand** [comment]
```
$args->{Timeout} = 120;
${*$smtp}{‘net_smtp_esmtp’}->{AUTH} = ‘LOGIN’;
```
