### ISSUE TITLE
Password Of the Day wrong timezone

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7830]
**Describe the bug**
On password of the day rotation, the 2 date the code compare are not on the same timezone.

Per example:

```
Sep 26 15:26:10 packetfence pfperl-api-docker-wrapper[2531815]: pfperl-api(16) WARN: [mac:[undef]] NOW: 1695756369 (pf::pfcron::task::password_of_the_day::run)
Sep 26 15:26:10 packetfence pfperl-api-docker-wrapper[2531815]: pfperl-api(16) WARN: [mac:[undef]] Expiration: 1695798000 (pf::pfcron::task::password_of_the_day::run)
Sep 26 15:26:10 packetfence pfperl-api-docker-wrapper[2531815]: pfperl-api(16) WARN: [mac:[undef]] Expiration MYSQL: 2023-09-27T07:00:00 (pf::pfcron::task::password_of_the_day::run)
```

Now represent the time now which is "Tue Sep 26 2023 15:26:09 GMT-0400 (Eastern Daylight Time)"
Expiration represent the time that the password expire: "Wed Sep 27 2023 03:00:00 GMT-0400 (Eastern Daylight Time)"
And Expiration MYSQL represent the value we convert to epoch but it's converted to GMT+0

Normally Expiration value should be calculated on the local time zone and should be "Wed Sep 27 2023 07:00:00 GMT-0400 (Eastern Daylight Time)"

It could be a container image issue.

**Comment by satkunas** [comment]
Also merge/use https://github.com/inverse-inc/packetfence/pull/7862
