### ISSUE TITLE
Increase resources on PacketFence ZEN

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#7834]
We should increase the memory requirements for the ZEN to at least 16 GB.

We should review other resources requirements (disks, CPU, etc.) to make sure we are ok too.

**Comment by JeGoi** [comment]
Increase ram is done https://github.com/inverse-inc/packetfence/commit/51b0421fd6afbbdc77666fcead851f1a67e09213
Requirements are OK for:
* Disks
* CPU
* Network interface

BUT no SWAP. Will add 4G for swap
