### ISSUE TITLE
安装时间耗时太久

### ISSUE THREAD

**Issue by jining172** [inverse-inc/packetfence#7840]
debian 11.x  安装 12.x.x 或 13.0.0 版本时 进行到以下步骤时耗时太久，
----------------------------------------------------------------------------

Setting packetfence.target as the default systemd target.
Created symlink /etc/systemd/system/default.target -> /etc/systemd/system/packetfence.target.
Restarting journald to enable persistent logging
Restarting rsyslog
2023年 10月 03日 星期二 21:13:24 CST - Images detected:
- haproxy-admin
- haproxy-portal
- radiusd-acct
- httpd.webservices
- radiusd-load-balancer
- pfqueue
- pfcron
- pfpki
- api-frontend
- pfconnector
- httpd.portal
- pfconfig
- radiusd-auth
- radiusd-cli
- pfsso
- httpd.dispatcher
- pfcmd
- pfperl-api
- radiusd-eduroam
- httpd.admin_dispatcher
- proxysql
- fingerbank-db
- pfacct
- httpd.aaa

----------------------------------------------------------
网络抓包得出 操作系统正在访问 GitHub IP地址 ：185.199.110.154，操作系统以设置加速镜像，其它包下载速度正常。 

怀疑为安装包内有其它请求GitHub 下载内容。

**Comment by jining172** [comment]
expected EOF
dpkg: 处理软件包 packetfence (--configure)时出错：
 已安装 packetfence 软件包 post-installation 脚本 子进程返回错误状态 1
正在处理用于 man-db (2.9.4-2) 的触发器 ...
正在处理用于 dbus (1.12.24-0+deb11u1) 的触发器 ...
正在处理用于 fontconfig (2.13.1-4.2) 的触发器 ...
正在处理用于 libc-bin (2.31-13+deb11u6) 的触发器 ...
在处理时有错误发生：
 packetfence
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by extrafu** [comment]
English.

**Comment by Rocky-Jinxing** [comment]
If it is stuck in this state, it will indeed go to GitHub to download things, so just hang up a proxy and then re-run the installation program.

cmd
export http_proxy="http://your-proxy-server:port"
export https_proxy="http://your-proxy-server:port"

**Comment by Rocky-Jinxing** [comment]
![Image](https://github.com/user-attachments/assets/4844b33d-93a1-445a-bf0d-c18235e5b16f)
