### ISSUE TITLE
*to* option in Email API is not working

### ISSUE THREAD

**Issue by yananet** [inverse-inc/packetfence#7860]
**Describe the bug**
*to* option in Email API is not working.
https://www.packetfence.org/doc/api/#/Email/post_api_v1_email_pfmailer

Even though *to* is specified in the POST request,
email is only sent to recipients configured in *Alerting* configuration of System Configuration.

**To Reproduce**
1. Complete SMTP configuration in `Configuration` - `System Configuration` - `Alerting`.
2. Set a specific recipients email (user1@email.com) to verify.
3. Access email API with specifying user2@email.com as the target.
```
/usr/local/pf/sbin/pfperl-api get -M POST /api/v1/email/pfmailer -c '{"subject": "Test Title", "message": "Hello,\n Test Message\n", "to": "user2@email.com"}'
```
4. Verify that the email is sent to user1@email.com.

**Screenshots**
N/A

**Expected behavior**
Email is sent to user2@email.com

**Desktop (please complete the following information):**
 - OS: PacketFence ZEN 13.0
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] 13.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fdurand** [comment]
Should be modified here:

https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/config/util.pm#L144

like:
```
my $to = $data{'subject'} || $Config{'alerting'}{'emailaddr'};
```

**Comment by satkunas** [comment]
The endpoint [`/api/v1/email/pfmailer`](https://www.packetfence.org/doc/api/#/Email/post_api_v1_email_pfmailer) uses the `to` address defined in Alerting. This can not be overloaded.

Instead used the endopint [`/api/v1/email/send`](https://www.packetfence.org/doc/api/#/Email/post_api_v1_email_send) to send a message to a specific user using a template.

If a template is not required then send the message to the SMTP relay directly.
