### ISSUE TITLE
Captive-Portal with Cisco WLC does not work

### ISSUE THREAD

**Issue by wayne771123** [inverse-inc/packetfence#7892]
**Describe the bug**
When connecting to the WiFi ,captive porta displays "your computer was not found in the packetfence database. Please reboot to solve this issue."

I see error message  in packetfence.log:

```
httpd.portal-docker-wrapper[5682]: httpd.portal(14) WARN: [mac:unknown] Unable to match MAC address to IP '10.80.80.20' (pf::ip4log::ip2mac)
httpd.portal-docker-wrapper[5682]: httpd.portal(14) WARN: [mac:0] Unable to match MAC address to IP '10.80.80.20'(pf::ip4log::ip2mac)
httpd.dispatcher-docker-wrapper[24690]: httpd.dispatcher: Ip2Mac mac for 10.80.80.20 not found sql: no rows in result set
```

**Version information**
Packetfence V13  
oracle linux 8.8

**Additional context**
How to solve the problem?

**Comment by extrafu** [comment]
Mailing-list type material.
