### ISSUE TITLE
After upgrade from 12.1 to 13.0 mab authentication does not work

### ISSUE THREAD

**Issue by RaZer0r** [inverse-inc/packetfence#7904]
**Describe the bug**
HW: Cisco switch iOS 15.2
first could not logon with the Cisco_2960 module, switched to iOS_15.0 module, login works again.
Next issue: mab authentication (only use 802.1x for authentication on switches, not on end devices), Mac addresses to authenticate, see log below.

**Screenshots**

`Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) INFO: [mac:00:04:c4:05:31:97] handling radius autz request: from switch_ip => (192.168.101.30), connection_type => Ethernet-NoEAP,switch_mac => (54:4a:00:6e:63:a8), mac => [00:04:c4:05:31:97], port => 10140, username => "0004c4053197" (pf::radius::authorize)
Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) ERROR: [mac:00:04:c4:05:31:97] Database query failed with non retryable error: Unknown column 'node.bypass_acls' in 'field list' (errno: 1054) [SELECT `node`.`mac` AS `mac`, `node`.`pid` AS `pid`, `node`.`category_id` AS `category_id`, `node`.`detect_date` AS `detect_date`, `node`.`regdate` AS `regdate`, `node`.`unregdate` AS `unregdate`, `node`.`lastskip` AS `lastskip`, `node`.`time_balance` AS `time_balance`, `node`.`bandwidth_balance` AS `bandwidth_balance`, `node`.`status` AS `status`, `node`.`user_agent` AS `user_agent`, `node`.`computername` AS `computername`, `node`.`notes` AS `notes`, `node`.`last_arp` AS `last_arp`, `node`.`last_dhcp` AS `last_dhcp`, `node`.`dhcp_fingerprint` AS `dhcp_fingerprint`, `node`.`dhcp6_fingerprint` AS `dhcp6_fingerprint`, `node`.`dhcp_vendor` AS `dhcp_vendor`, `node`.`dhcp6_enterprise` AS `dhcp6_enterprise`, `node`.`device_type` AS `device_type`, `node`.`device_class` AS `device_class`, `node`.`device_version` AS `device_version`, `node`.`device_score` AS `device_score`, `node`.`device_manufacturer` AS `device_manufacturer`, `node`.`bypass_vlan` AS `bypass_vlan`, `node`.`voip` AS `voip`, `node`.`autoreg` AS `autoreg`, `node`.`sessionid` AS `sessionid`, `node`.`machine_account` AS `machine_account`, `node`.`bypass_role_id` AS `bypass_role_id`, `node`.`last_seen` AS `last_seen`, `node`.`bypass_acls` AS `bypass_acls`, `nc`.`name` AS `category`, `nr`.`name` AS `bypass_role` FROM node LEFT OUTER JOIN `node_category` AS `nc` ON ( `node`.`category_id` = `nc`.`category_id` ) LEFT OUTER JOIN `node_category` AS `nr` ON ( `node`.`bypass_role_id` = `nr`.`category_id` ) WHERE ( `node`.`mac` = ? )]{00:04:c4:05:31:97} (pf::dal::db_execute)
Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) ERROR: [mac:00:04:c4:05:31:97] Database query failed with non retryable error: Unknown column 'bypass_acls' in 'field list' (errno: 1054) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_acls`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_manufacturer`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `last_seen`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_acls` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_manufacturer` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `last_seen` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?]{no, NULL, NULL, NULL, NULL, NULL, NULL, 2023-11-14 01:42:52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 00:04:c4:05:31:97, NULL, NULL, default, 0000-00-00 00:00:00, NULL, unreg, NULL, 0000-00-00 00:00:00, NULL, no, no, NULL, NULL, NULL, NULL, NULL, NULL, 2023-11-14 01:42:52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 00:04:c4:05:31:97, NULL, NULL, default, 0000-00-00 00:00:00, NULL, unreg, NULL, 0000-00-00 00:00:00, NULL, no} (pf::dal::db_execute)
Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) WARN: [mac:00:04:c4:05:31:97] (192.168.101.30) Sending REJECT since switch is unsupported (pf::radius::_switchUnsupportedReply)
Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) ERROR: [mac:00:04:c4:05:31:97] Database query failed with non retryable error: Unknown column 'bypass_acls' in 'field list' (errno: 1054) [INSERT INTO `node` ( `autoreg`, `bandwidth_balance`, `bypass_acls`, `bypass_role_id`, `bypass_vlan`, `category_id`, `computername`, `detect_date`, `device_class`, `device_manufacturer`, `device_score`, `device_type`, `device_version`, `dhcp6_enterprise`, `dhcp6_fingerprint`, `dhcp_fingerprint`, `dhcp_vendor`, `last_arp`, `last_dhcp`, `last_seen`, `lastskip`, `mac`, `machine_account`, `notes`, `pid`, `regdate`, `sessionid`, `status`, `time_balance`, `unregdate`, `user_agent`, `voip`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ON DUPLICATE KEY UPDATE `autoreg` = ?, `bandwidth_balance` = ?, `bypass_acls` = ?, `bypass_role_id` = ?, `bypass_vlan` = ?, `category_id` = ?, `computername` = ?, `detect_date` = ?, `device_class` = ?, `device_manufacturer` = ?, `device_score` = ?, `device_type` = ?, `device_version` = ?, `dhcp6_enterprise` = ?, `dhcp6_fingerprint` = ?, `dhcp_fingerprint` = ?, `dhcp_vendor` = ?, `last_arp` = ?, `last_dhcp` = ?, `last_seen` = ?, `lastskip` = ?, `mac` = ?, `machine_account` = ?, `notes` = ?, `pid` = ?, `regdate` = ?, `sessionid` = ?, `status` = ?, `time_balance` = ?, `unregdate` = ?, `user_agent` = ?, `voip` = ?]{no, NULL, NULL, NULL, NULL, NULL, NULL, 2023-11-14 01:42:52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 2023-11-14 01:42:52, 0000-00-00 00:00:00, 00:04:c4:05:31:97, NULL, NULL, default, 0000-00-00 00:00:00, NULL, unreg, NULL, 0000-00-00 00:00:00, NULL, no, no, NULL, NULL, NULL, NULL, NULL, NULL, 2023-11-14 01:42:52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0000-00-00 00:00:00, 0000-00-00 00:00:00, 2023-11-14 01:42:52, 0000-00-00 00:00:00, 00:04:c4:05:31:97, NULL, NULL, default, 0000-00-00 00:00:00, NULL, unreg, NULL, 0000-00-00 00:00:00, NULL, no} (pf::dal::db_execute)
Nov 14 01:42:52 packetfence httpd.aaa-docker-wrapper[1969]: httpd.aaa(10) ERROR: [mac:00:04:c4:05:31:97] Cannot save 00:04:c4:05:31:97 error (500) (pf::radius::authorize)
`

**Expected behavior**

**Smartphone (please complete the following information):**

**Additional context**
I also have an error about radiusd-acct not being able to start, and noticed that pfacct is using port 1813.
which one of the services is needed? both state they are needed in the services overview.

**Comment by extrafu** [comment]
Mailing-list material.

**Comment by RaZer0r** [comment]
yes, it has been put on the mailing list too, I'll update once I have a maintenance window again to attempt an upgrade again
