### ISSUE TITLE
snmp_perl_trapd.pl FATAL: Illegal modulus zero

### ISSUE THREAD

**Issue by dwcoreia** [inverse-inc/packetfence#7912]
Hi,

I seen on  /usr/local/pf/logs/packetfence.log the following errors, don't know how to fix it:

"""
Nov 21 18:53:30 host packetfence[320309]: -e(320309) INFO: generating /usr/local/pf/var/conf/snmptrapd.conf (pf::services::manager::snmptrapd::generateConfig)
Nov 21 18:53:35host packetfence[320330]: snmp_perl_trapd.pl(320330) WARN: Use of uninitialized value $count in modulus (%) at /usr/local/pf/lib/pf/pfqueue/producer/redis.pm line 103.
 (pf::pfqueue::producer::redis::hashed_queue_name)
Nov 21 18:53:35 host packetfence[320330]: snmp_perl_trapd.pl(320330) FATAL: Illegal modulus zero at /usr/local/pf/lib/pf/pfqueue/producer/redis.pm line 103.

"""

Could you help me?

**Comment by jrouzierinverse** [comment]
This been fixed in

**Comment by jrouzierinverse** [comment]
The updated packages will be available tomorrow.

**Comment by JeGoi** [comment]
12.2 is released with fix.
13.0 is released with fix.
