### ISSUE TITLE
maintenance13.0 => Radius Load Balancer Issue on cluster lib issues on start

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7916]
**Describe the bug**
Unable to start Radius Load Balancer on cluster since.
Failed Loading Module rlm_json from file /usr/lib/freeradius/rlm_json.so
etc.

**To Reproduce**
Have a cluster with docker image: 42b2fac734a3

**Expected behavior**
Have the service running

**Additional context**

**Comment by jrouzierinverse** [comment]
Reopen if we see it again
