### ISSUE TITLE
pfconfig is not able to start on upgrade

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7925]
**Describe the bug**
Noticed that on packetfence upgrade sometimes pfconfig is not able to start because the port 44444 is still in use.

```
root@localhost:~# netstat -pna| grep 44444
tcp        0      0 100.64.0.1:44444        100.64.0.1:44444        ESTABLISHED 25068/perl
```
```
root@localhost:~# ps -edf|grep 25060
root       25060   25059  0 Oct13 ?        00:00:00 /bin/bash /usr/local/pf/addons/backup-and-maintenance.sh
root       25068   25060  0 Oct13 ?        00:00:00 perl -I/usr/local/pf/lib -I/usr/local/pf/lib_perl/lib/perl5 -Mpf::db -e print $pf::db::DB_Config->{db}
```

As result there is still a process who is using the port and prevent docker proxy to be able to bind.

```
Dec 08 14:09:18 localhost dockerd[740462]: time="2023-12-08T14:09:18.757757968Z" level=warning msg="Failed to allocate and map port 44444-44444: Error starting userland proxy: listen tcp4 100.64.0.1:44444: bind: address already in use"
```

Killing the process doesn't resolve the issue but kill + restart docker make it works.

**Expected behavior**
We have to find a solution in order to run the backup script without requiring the usage of pfconfig and also maybe trigger a docker restart on a upgrade.

**Comment by jrouzierinverse** [comment]
Fixed by ffedd12dc267c887879c6af1fe138877753c5612
