### ISSUE TITLE
PF 13.1: packetfence-ntlm-auth-api starts without domain config

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7931]
PF version: 13.1.0+20231212203521+1104632943+0011+devel+bullseye1

![image](https://github.com/inverse-inc/packetfence/assets/5261214/a3ac7e17-d82c-4042-afaa-0bb5b593996d)

**Comment by satkunas** [comment]
@lzammit please retest and close if fixed

**Comment by lzammit** [comment]
Version: 13.1.0+20240102222514+1125991549+0011+devel+bullseye1

![image](https://github.com/inverse-inc/packetfence/assets/5261214/497489f0-d25c-4cac-9b56-af8e3387f3b8)

![image](https://github.com/inverse-inc/packetfence/assets/5261214/446974a3-8f1c-454c-b333-b10d37ac22d5)

**Comment by satkunas** [comment]
@stgmsa reach out to @lzammit for more details

**Comment by satkunas** [comment]
Fixed in 37c7d2f777922f328ab72025d3d45627e598a838
