### ISSUE TITLE
PF 13.1: Can't install Radius Root CA certificate

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#7939]
PF version: 13.1.0+20231219145702+1113026753+0011+devel+bullseye1

![image](https://github.com/inverse-inc/packetfence/assets/5261214/4ef7dd3f-7932-4e7d-81e7-f1f8129e5cb1)

**Comment by fdurand** [comment]
i am not able to replicate.

**Comment by satkunas** [comment]
@lzammit please retest and close if N/A.

**Comment by lzammit** [comment]
Works now.
