### ISSUE TITLE
Creating a portal profile with an existing template directory overwrites it

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#794]
Should be left in place I guess, that would be more what a user expects

**Comment by jrouzierinverse** [comment]
If we would support this option I would have a checkbox (default unchecked) 
- [ ] delete templates folder also

**Comment by jrouzierinverse** [comment]
We can deal with one of the following ways
- Leave as is (as @julsemaan mentioned) 
- Give a warning that this happened
- Give an error and let them fix it manually
- Give an error with the option of override the existing files

**Comment by julsemaan** [comment]
@jrouzierinverse 

Lets pick one and address it, my opinion would be leave is as is as said before, lets just decide on something

**Comment by jrouzierinverse** [comment]
It no longer overwrite the directory when creating a profile since we have the template now.

The question now do we give warning to the user that old templates are there?

**Comment by julsemaan** [comment]
Sure, that would probably be a good thing to say it right after creating the profile

**Comment by jrouzierinverse** [comment]
@satkunas what are your thoughts on having the API return warnings.
In this scenario, if there are leftover files from a previous profile.
And if that profile name is reused I would like to give a warning to the users.
```json
{
   "status" : 200,
   "message" : "...",
    "warnings" : [
       { "message" : "Old templates detected please review", "status" : 409},
    ]
}
```

**Comment by jrouzierinverse** [comment]
When a new connection profile is added but there are old templates in the file system we should display the warnings.
given back by the API.
@satkunas or @cgx can you handle the part.
