### ISSUE TITLE
PF13.1: PacketFence logs are full of errors regarding pfqueue-backebd.sock

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7969]
**Describe the bug**

Running the latest devel version of PacketFence and the packetfencelog file is full of:

Jan 10 16:31:32 cluster2-1 pfqueue[1043093]: t=2024-01-10T16:31:32-0500 lvl=eror msg="Error Next: write unix @->/usr/local/pf/var/run/pfqueue-backend.sock: write: broken pipe" pid=1043093

**Comment by jrouzierinverse** [comment]
Please retest may be fixed by e09c7e71b678e39165e52b397c7d1ed9e8a5597d

**Comment by jrouzierinverse** [comment]
Please recheck
