### ISSUE TITLE
IS there an OVA file for VMware for Packetfence ? 

### ISSUE THREAD

**Issue by Jason-MK** [inverse-inc/packetfence#7999]
Hello, 

I'm trying to install Packetfence on Debian 12 , and I couldn't is there an OVA file which I can use to install on VMware ? I mean the latest version ?

Best Regards,

**Comment by JeGoi** [comment]
Hi @Jason-MK,
We had issues with Sourceforge https://github.com/inverse-inc/packetfence/pull/7998 and our zipped ova image size.
It has been fixed and v13.1 (and following released) will be available on Linode object now.
Packetfence website have also been updated. The zen image is now available https://www.packetfence.org/download.html#/zen.
Thanks for your patience and understanding.
Regards

**Comment by JeGoi** [comment]
NOTE: previous versions are available there: https://sourceforge.net/projects/packetfence/files/PacketFence%20ZEN/ for the ZEN
