### ISSUE TITLE
Using the wrong po file for internationalization 

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#800]
Success is for warning and warning for success

Visual only

**Comment by jrouzierinverse** [comment]
Where?

**Comment by julsemaan** [comment]
Sorry, yes in the admin under 'Configuration/Advanced'

**Comment by jrouzierinverse** [comment]
This seems to be an issue where we are using the wrong internatilization file.
We seem to be using 
html/pfappserver/lib/pfappserver/I18N/en.po
html/pfappserver/lib/pfappserver/I18N/i_default.po

**Comment by jrouzierinverse** [comment]
This may be packaging issue or process issue

**Comment by julsemaan** [comment]
Was fixed
