### ISSUE TITLE
In Authentication source, Access Level list is limited to 25 entries

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#8004]
**Describe the bug**

In a administration rule when you choose the action Access Level then the entries returned by the api are limited to 25, so you are not able to choose one who exists but is not in the list.

![image](https://github.com/inverse-inc/packetfence/assets/1553962/8b0d74a7-e91f-4ce2-bb5f-4561d31faa01)

**Comment by satkunas** [comment]
backported to maintenance/13.1, maintenance/13.0, maintenance/12.2
