### ISSUE TITLE
tests: 

### ISSUE THREAD

**Issue by sudheeraw** [inverse-inc/packetfence#8012]
packetfence service not start

OS version: debian 11
PF vision :13

error:
Feb 13 14:43:31 packetfence packetfence[1194]: pfcmd.pl(1194) ERROR: [1707835411                                                                             .85293] Failed to connect to config service for namespace config::Pf(), retrying                                                                              (pfconfig::cached::_get_from_socket)

**Comment by JeGoi** [comment]
This is not CI/CD test related issue.
Please open a PF issue or use the mailing list.
Thanks

**Comment by sudheeraw** [comment]
thanks
