### ISSUE TITLE
conf/switches.conf is cleaned after upgrade

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#8045]
**Describe the bug**
From the upgrade script:
```
Moving conf/switches.conf.dpkg-dist -> conf/switches.conf
Attempting a dry-run on the patch on conf/switches.conf
checking file conf/switches.conf
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED
Patching conf/switches.conf failed.
```
As a result, the conf/switches.conf is empty

Also reported on mailing list.

**To Reproduce**
1. Do the upgrade
2. Check the config file

**Additional context**
Looks like @nqb add a similar issue https://github.com/inverse-inc/packetfence/issues/7182 with other similar reference.

**Comment by abprasa** [comment]
**Workaround**
 Execute the following commands after the upgrade
`root@pf:/usr/local/pf# cat conf/switches.conf.upgrade-backup >> conf/switches.conf`
`root@pf:/usr/local/pf# bin/pfcmd configreload hard`
