### ISSUE TITLE
Brand-new cluster shows error when saving any changes in the UI

### ISSUE THREAD

**Issue by daniel-zook** [inverse-inc/packetfence#8059]
**Describe the bug**
After creating a cluster, when one goes to setup PacketFence (e.g., add a Network Switch), any time "create" or "saved" is clicked, the following error appears:
"Could not synchronize cluster (Failed to sync configuration on server(s) pf1 at /usr/local/pt/lib/pt/api.pm line 836."

The web page appears to not save the change, but in fact it is saved and synced to all cluster members.

Everything went smoothly, with no errors, when I setup the cluster.  All the cluster members show synced status.
(See below.)                                                                                                                    

(If you want to see the full results of this query, let me know.)

**To Reproduce**
1. Create a new cluster, following the Clustering Quick Installation Guide
https://www.packetfence.org/doc/PacketFence_Clustering_Guide.html
2. Login to the cluster web UI
3. Go to  Configuration / Policies and Access Control / Switches
4. Click "New Switch" / "default"
5. Enter a value in the "IP Address/MAC Address/Range (CIDR)" field, e.g. 192.168.0.0/24
6. Click "Create"

**Screenshots**
![image](https://github.com/inverse-inc/packetfence/assets/102061371/e0f1f2f8-136c-4b6a-82e8-b753128187be)
![image](https://github.com/inverse-inc/packetfence/assets/102061371/74cccffb-0cbd-4d99-966e-9173bc624651)

Note: The exact same error also appears when saving a change on an existing record, or deleting a record.

**Expected behavior**
I expect the the page to show the message " '192.168.0.0/24' created" and the "Create" button to change to "Save".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 123.0.6312.105 (Official Build) (64-bit)

**Additional context**
"Server hostname" in the help pane shows "pf2"
Version: 13.1.0
All cluster members are running in a VM on VMWare vSphere 7
All cluster members are in the same VLAN, vSphere hosts are in the same physical location

MariaDB [(none)]> show status like 'wsrep%';
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name                 | Value                                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| wsrep_local_state_uuid        | d0f14982-f127-11ee-a2a3-be1ae0a20146                                                                                                           |
| wsrep_protocol_version        | 10                                                                                                                                             |
| wsrep_last_committed          | 37848                                                                                                                                          |
| wsrep_replicated              | 67                                                                                                                                             |
| wsrep_replicated_bytes        | 352128                                                                                                                                         |
| wsrep_repl_keys               | 254                                                                                                                                            |
| wsrep_repl_keys_bytes         | 3640                                                                                                                                           |
| wsrep_repl_data_bytes         | 343981                                                                                                                                         |
| wsrep_repl_other_bytes        | 0                                                                                                                                              |
| wsrep_received                | 12209                                                                                                                                          |
| wsrep_received_bytes          | 22396480                                                                                                                                       |
| wsrep_local_commits           | 67                                                                                                                                             |
| wsrep_local_cert_failures     | 0                                                                                                                                              |
| wsrep_local_replays           | 0                                                                                                                                              |
| wsrep_local_send_queue        | 0                                                                                                                                              |
| wsrep_local_send_queue_max    | 2                                                                                                                                              |
| wsrep_local_send_queue_min    | 0                                                                                                                                              |
| wsrep_local_send_queue_avg    | 0.00609756                                                                                                                                     |
| wsrep_local_recv_queue        | 0                                                                                                                                              |
| wsrep_local_recv_queue_max    | 3                                                                                                                                              |
| wsrep_local_recv_queue_min    | 0                                                                                                                                              |
| wsrep_local_recv_queue_avg    | 0.00884593                                                                                                                                     |
| wsrep_local_cached_downto     | 1                                                                                                                                              |
| wsrep_flow_control_paused_ns  | 0                                                                                                                                              |
| wsrep_flow_control_paused     | 0                                                                                                                                              |
| wsrep_flow_control_sent       | 0                                                                                                                                              |
| wsrep_flow_control_recv       | 0                                                                                                                                              |
| wsrep_flow_control_active     | false                                                                                                                                          |
| wsrep_flow_control_requested  | false                                                                                                                                          |
| wsrep_cert_deps_distance      | 49.26                                                                                                                                          |
| wsrep_apply_oooe              | 0                                                                                                                                              |
| wsrep_apply_oool              | 0                                                                                                                                              |
| wsrep_apply_window            | 1                                                                                                                                              |
| wsrep_apply_waits             | 0                                                                                                                                              |
| wsrep_commit_oooe             | 0                                                                                                                                              |
| wsrep_commit_oool             | 0                                                                                                                                              |
| wsrep_commit_window           | 1                                                                                                                                              |
| wsrep_local_state             | 4                                                                                                                                              |
| wsrep_local_state_comment     | Synced                                                                                                                                         |
| wsrep_cert_index_size         | 53                                                                                                                                             |
| wsrep_causal_reads            | 0                                                                                                                                              |
| wsrep_cert_interval           | 110.662                                                                                                                                        |
| wsrep_open_transactions       | 0                                                                                                                                              |
| wsrep_open_connections        | 0                                                                                                                                              |
| wsrep_incoming_addresses      | 10.3.20.99:3306,10.3.20.97:3306,10.3.20.98:3306                                                                                                |
| wsrep_cluster_weight          | 3                                                                                                                                              |
| wsrep_desync_count            | 0                                                                                                                                              |
| wsrep_evs_delayed             |                                                                                                                                                |
| wsrep_evs_evict_list          |                                                                                                                                                |
| wsrep_evs_repl_latency        | 0.000322972/0.000324153/0.000325335/1.1815e-06/2                                                                                               |
| wsrep_evs_state               | OPERATIONAL                                                                                                                                    |
| wsrep_gcomm_uuid              | a69cadf5-f1cc-11ee-8ff8-3b7fbf81f7b6                                                                                                           |
| wsrep_gmcast_segment          | 0                                                                                                                                              |
| wsrep_applier_thread_count    | 1                                                                                                                                              |
| wsrep_cluster_capabilities    |                                                                                                                                                |
| wsrep_cluster_conf_id         | 13                                                                                                                                             |
| wsrep_cluster_size            | 3                                                                                                                                              |
| wsrep_cluster_state_uuid      | d0f14982-f127-11ee-a2a3-be1ae0a20146                                                                                                           |
| wsrep_cluster_status          | Primary                                                                                                                                        |
| wsrep_connected               | ON                                                                                                                                             |
| wsrep_local_bf_aborts         | 0                                                                                                                                              |
| wsrep_local_index             | 1                                                                                                                                              |
| wsrep_provider_capabilities   | :MULTI_MASTER:CERTIFICATION:PARALLEL_APPLYING:TRX_REPLAY:ISOLATION:PAUSE:CAUSAL_READS:INCREMENTAL_WRITESET:UNORDERED:PREORDERED:STREAMING:NBO: |
| wsrep_provider_name           | Galera                                                                                                                                         |
| wsrep_provider_vendor         | Codership Oy <info@codership.com>                                                                                                              |
| wsrep_provider_version        | 26.4.11(r67341d07)                                                                                                                             |
| wsrep_ready                   | ON                                                                                                                                             |
| wsrep_rollbacker_thread_count | 1                                                                                                                                              |
| wsrep_thread_count            | 2                                                                                                                                              |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
69 rows in set (0.001 sec)

**Comment by JeGoi** [comment]
Hi there,
This is a configuration/network issue.
Please use the support community https://www.packetfence.org/support.html#/community or buy a support contract https://www.packetfence.org/support.html#/commercial
