### ISSUE TITLE
Packetfence Captive Portal

### ISSUE THREAD

**Issue by Hajar-bht** [inverse-inc/packetfence#8063]
The URL found in the installation guide is http://172.20.100.2/Cisco::Catalyst_2960
When I replace it with my IP address, it redirects me to this link, but it displays

Not Implemented
GET not supported for current URL.

**Comment by fdurand** [comment]
The radius reply will return an attribute with this value http://172.20.100.2/Cisco::Catalyst_2960?sid012345
It looks to be a configuration issue and not a code issue, please use the mailing list for this problem.

Thanks
Fabrice
