### ISSUE TITLE
Packetfence web auth

### ISSUE THREAD

**Issue by Hajar-bht** [inverse-inc/packetfence#8070]
I followed the installation guide for the captive portal using this link for redirection: http://172.20.100.2/Cisco::Catalyst_2960 with my PF IP address. When I tested it in Firefox, it redirected me to the following page. 
![Capture](https://github.com/inverse-inc/packetfence/assets/165664048/2f2212c5-f8aa-4977-861f-1de7c7d6cf0d)
 I tried clearing the cache and cookies, as well as using Firefox in debug mode, but with no success.

**Comment by JeGoi** [comment]
Hi there,
It looks like more a config issue.
Please use the community to ask your question: https://www.packetfence.org/support.html#/community
or ask for commercial support https://www.packetfence.org/support.html#/commercial
If I am wrong fill free to reopen that issue with more informations.
Thank you
