### ISSUE TITLE
Session Not Timing Out

### ISSUE THREAD

**Issue by Hajar-bht** [inverse-inc/packetfence#8071]
I managed to authenticate with Active Directory, but the issue is that the session isn't timing out to redirect back to the authentication page, even though I configured the access duration and deregistration time in the authentication source.

**Comment by JeGoi** [comment]
Hi there, could you provide more information.
Like PF version, config, files, etc.

**Comment by JeGoi** [comment]
No info and old, I am closing it.
Fill free to reopen if needed or create a new issue.
Thanks for using PacketFence
