### ISSUE TITLE
Configure docker daemon.json

### ISSUE THREAD

**Issue by phlbrz** [inverse-inc/packetfence#8095]
Hello all,

After install packetfence, I'm unable to ssh to the VM, because daemon.json has network (e.g: bip, base) default value.

It would be better to set a customized value before install or, if not possible, after install change the values in the UI.

Default example from docker daemon.json at /etc/docker/daemon.json:

```
{
    "debug": true,
    "bip": "192.169.1.1/24",
    "default-address-pools": [{
      "base": "192.169.0.0/16",
      "size": 16
    }],
    ...
}
```

Customized example:

```
{
    "debug": true,
    "bip": "10.1.0.1/24",
    "default-address-pools": [{
      "base": "10.1.0.0/16",
      "size": 16
    }],
    ...
}
```

Alternative:

It's simple to do after installation if you're at the VM already, I have less than 30 seconds window to ssh before systemd docker go up.

**Comment by JeGoi** [comment]
Hi there,
Sorry but I do not get your point, we already have custom config for PF:
https://github.com/inverse-inc/packetfence/blob/devel/containers/daemon.json
Results:
```
cat /etc/docker/daemon.json
{
  "log-driver": "none",
  "bip": "100.64.0.1/24",
  "default-address-pools": [
    {
      "base": "100.64.0.0/10",
      "size": 24
    }
  ]
}
```
