### ISSUE TITLE
The system update is stuck at 98%.

### ISSUE THREAD

**Issue by linkiofo** [inverse-inc/packetfence#8103]
What is the problem that the PacketFence-ZEN-v13.1.0.OVF image is stuck at 98% when updating the system using the "apt upgrade -y" command?
![1](https://github.com/inverse-inc/packetfence/assets/156993166/c99b103d-738c-4e3c-a506-5093c937ded3)

**Comment by JeGoi** [comment]
Hi, At this step, it is trying to download images from https://github.com/orgs/inverse-inc/packages
If it is not working open a new ssh access and check on logs.
This is not a bug please use the the mailing list for this kind of questions.
Thank you

**Comment by sinankizar** [comment]
Hello, 

I have experienced same issue here and it took a hefty 5 hours to complete. I have checked our firewall and saw there is no hindrance. Anyway it started to download those very slow from 12.2 update. Is there any suggestions that we can check?

Thanks in advance.

**Comment by JeGoi** [comment]
Hi @sinankizar,

I am sorry to read that, and as I wrote please continue that discussion on the mailing list.

That been wrote.

You can check the `journalctl -f` or `top` and see what is happening on the VM.
At that point you should have docker in top first processes and seeing downloads in journal entry.

Basically, two steps of the "docker pull image" can have an impact:
1) Downloading Image Layers (network related)
2) Assembling the Image (hardware related)

You can test by downloading images by hand like:
```
docker pull ghcr.io/inverse-inc/packetfence/httpd.dispatcher:maintenance-14-0
```
And see what is happening.

You can predownload all images first. If the images are there and up to date, the installation will use them directly.
Remember that almost all our images are based on one image, so lost of layers are shared across our images, so the first image to download takes always more time time than the next one.

If you need support please use the community channel (https://www.packetfence.org/support.html#/community) or ask for consulting at https://www.packetfence.org/support.html#/commercial

Thank you for using Packetfence

**Comment by sinankizar** [comment]
Thanks for your detailed explanation and support. Will try those. You may close this thread, I will continue on mailing list if I need more on this. 

Thanks and have a nice one..
