### ISSUE TITLE
PF 13.2 - Unable to create provisioner rule

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#8115]
**Describe the bug**
Try to create a provisioner rule, the type is locked

![image](https://github.com/inverse-inc/packetfence/assets/1553962/a9ea735e-e589-4b86-9fa5-48b5cddf6779)

**Comment by satkunas** [comment]
Fixed in 74983f8810d767d2d7419feb6c391ec7a445f88e
