### ISSUE TITLE
Unable to detect network connectivity 

### ISSUE THREAD

**Issue by jbryan211** [inverse-inc/packetfence#8116]
Hello,

I'm dealing with a PF issue when users connect to a guest network. Once they connect, the status bar for establishing a connection takes about 2 mins to finalize and they receive the "Unable to detect network connectivity Try restarting your web browser or opening a new tab to see if your access has been successfully enabled".

When they open a browser they are able to navigate to the web and are issued the correct guest VLAN network, what steps should be performed to troubleshoot?

Thanks

**Comment by JeGoi** [comment]
Hi there, This is more a question for Community support: please take a look at https://www.packetfence.org/support.html
Thanks
