### ISSUE TITLE
PF 13.2: ntlm api log normal ?

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#8125]
![image](https://github.com/inverse-inc/packetfence/assets/5261214/c5f87094-5d74-4536-9bcd-56e85f5ae2c2)

Two questions:

- Is that normal ?
- does the ntlm api should have its own log file ?

**Comment by stgmsa** [comment]
yes. it's from the monitor script.
the monitor will "ping" the backend nodes for each domain every few seconds.

**Comment by stgmsa** [comment]
fixed by commit 74048f06 and a1739394
