### ISSUE TITLE
Unable to create a Authentication source

### ISSUE THREAD

**Issue by nvmike** [inverse-inc/packetfence#8142]
**Describe the bug**
After joining to the AD - and add teh new domain to realm local and Null as explain in hte documentation. Trying to add the AD to authetication source - I am getting a form with list of host empty.
INstalation from ZEN

**To Reproduce**
1. New Authentication SourceActive Directory
2. Click on 'host'
3. Scroll down to 'emty list'
4. Dead end!

**Screenshots**
![Screenshot 2024-05-10 at 14 00 37](https://github.com/inverse-inc/packetfence/assets/19436894/96fc7cc5-7220-4256-8a30-e4f86275be17)
![Screenshot 2024-05-10 at 14 01 18](https://github.com/inverse-inc/packetfence/assets/19436894/10b75c3a-de8f-4cea-97c9-a7e831064081)
![Screenshot 2024-05-10 at 14 00 02](https://github.com/inverse-inc/packetfence/assets/19436894/33bf4aa5-641c-4c99-a614-f4932c539d9c)

**Comment by nerf69** [comment]
Manually type in the DNS name or the IP Address. I noticed this with my configuration but it works fine by typing it in!

**Comment by nvmike** [comment]
OMG!!! it's indeed working
