### ISSUE TITLE
Create / Save swith settings failed after a fresh installation

### ISSUE THREAD

**Issue by stgmsa** [inverse-inc/packetfence#8144]
**Describe the bug**
After a fresh install of PF v13.2, saving switch settings failed with a 500 response code from backend API

**To Reproduce**
1. prepare a Rocky linux environment
2. install packetfence using the suggested steps
3. after the installation is done, go throught the configurator
4. in mysql configuration during configurator, keep default settings (auth root and pf password)
5. at last step of configurator, click "start packetfence" 
6. login in to the admin UI and select "configuration" -> "Policy and access control" -> "switches"
7. create a new switch or click on any existing switch, and save. 
8. hit the 500 error.

**Screenshots**
Here's the errors: 
It's probably due to a bad mysql password / connection. 
<img width="1463" alt="image" src="https://github.com/inverse-inc/packetfence/assets/6135404/28a9c576-9a98-4bc8-8d27-dd4227400796">

waiting for quite a long time (to make sure all the required services are ready) after going through configurator won't help. 

This error can be avoided if we manaully restart pfperl-api after configurator. 

**Expected behavior**
after a fresh installation, all api calls that read / writes database works properly. 

**Desktop (please complete the following information):**
 - OS: Mac / independent 
 - Browser: chrome / independent
 - Version: any

**Comment by satkunas** [comment]
@stegar123 check if this is needed in 14, or if we can do post-release?

**Comment by JeGoi** [comment]
Fixed in 14.0
