### ISSUE TITLE
The client browser prompts "Unable to detect network connectivity."

### ISSUE THREAD

**Issue by changliangrock** [inverse-inc/packetfence#8168]
HI, 
When the client connects to PacketFence, it is necessary to restart the switch port to switch the VLAN. 

If not restarted, the browser will prompt "Unable to detect network connectivity. Try restarting your webbrowser or opening a new tab to see if your access has been successfully enabled", and the VLAN will not be switched. why ？

On the switch, by running "display arp", the MAC address corresponding to the IP can be seen to be always there. After disabling the network card and waiting until the MAC table times out, and then reconnecting, the VLAN can be switched. I don't know if the MAC update can be actively triggered.

Thanks

**Comment by extrafu** [comment]
Wrong place for such questions.
