### ISSUE TITLE
tests: wired_radius_extract_certificates: extract p12 is not working on debian12

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#8172]
**Describe the problem**
```
root@pfdeb12dev:/usr/local/pf/t/venom# openssl pkcs12 -in /tmp/tmp.Gi06uWU66w/InverseCA1_radius_cert.p12 -cacerts -nokeys -out /tmp/tmp.Gi06uWU66w/InverseCA1.crt -passin pass:secret
Error outputting keys and certificates
40171651867F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
root@pfdeb12dev:
```

**Mandatory informations**

 * Branch: debian12
 * Scenario: eap tls
 * Pipelines URL:
   * 
 
**Symptoms**
How the problem can be identified if it appears again ?

**Comment by lzammit** [comment]
The command is working, so it means that it could be openssl libraries issue or the file is bad.

I think it's the file.

Thanks,

**Comment by JeGoi** [comment]
https://github.com/openssl/openssl/discussions/23089#discussioncomment-7895826
I added the -legacy. CI tests in progress.
