### ISSUE TITLE
Remove build for proxysql container and use an existing one

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#8180]
**Is your feature request related to a problem? Please describe.**
We are building proxysql with some patch that we do not really use.
It is machine consuming for nothing.

**Describe the solution you'd like**
Use an official container for that service

**Describe alternatives you've considered**
None

**Additional context**
It also increases time in CI/CD

**Comment by satkunas** [comment]
@fdurand try official docker image, see if it works without patch.
