### ISSUE TITLE
PF 13.2.0 AD Join

### ISSUE THREAD

**Issue by oLuciaZo** [inverse-inc/packetfence#8187]
I have try to join PF to my AD but there is error
 **Post "http://containers-gateway.internal:5000/ntlm/connect": dial tcp 100.64.0.1:5000: connect: connection refused
ntlm/test**

**Comment by stgmsa** [comment]
You'll need
1. join the AD first (create a valid domain config entry)
2. start / restart `ntlm-auth-api` service: `systemctl restart packetfence-ntlm-auth-api` 
3. get back and check again to check if it passed the tests.

**Comment by oLuciaZo** [comment]
> You'll need
> 
> 1. join the AD first (create a valid domain config entry)
> 2. start / restart `ntlm-auth-api` service: `systemctl restart packetfence-ntlm-auth-api`
> 3. get back and check again to check if it passed the tests.

Issue has resolved
Thank you
