### ISSUE TITLE
The packetfence-ntlm-auth-api.service failed to start

### ISSUE THREAD

**Issue by dark-age** [inverse-inc/packetfence#8209]
With a newly installed Packetfence VM on Proxmox the ntlm-auth-api service does not want to start successfully. 
Unable to join active directory domains 

Configuration -> Policies and Access Control  -> Active Directory Domains

![Capture](https://github.com/inverse-inc/packetfence/assets/55591793/d94b4649-16f0-4509-a715-714cb8b4dc0a)

![Capture2](https://github.com/inverse-inc/packetfence/assets/55591793/222b1659-fa58-4db5-bb14-fe714b602efa)

**Comment by stgmsa** [comment]
to start ntlm auth api, you'll first have a valid entry in domain.conf ("join" the domain first).
