### ISSUE TITLE
Upgrade to FreeRADIUS 3.2.5

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#8212]
Upgrade to the latest stable version of FreeRADIUS

**Comment by jamesaepp** [comment]
For greater certainty, I assume the closure/completion of this issue would be a remediation to BlastRADIUS?

**Comment by mickaelidf** [comment]
As all know, freeradius.org  released BlastRADIUS Vulnerability on 2024.07.09.

Please  when the patch fixing  this issue will be released ? 

Warm regards,

**Comment by mickaelidf** [comment]
Hello Inverse team,

Regarding the case  [#8212,](https://github.com/inverse-inc/packetfence/issues/8212) could you help to have a schedule of the upgrade of freeRADIUS to the latest version ? 
The goal is to fix the  BlastRADIUS Vulnerability. 

My server is running Packetfence 13.2.0 which is released with freeradius 3.2.2.

Thanks for your feedback.

**Comment by fdurand** [comment]
Updated in devel , will be ready for 14.1
