### ISSUE TITLE
Empty RADIUS Audit Logs

### ISSUE THREAD

**Issue by ArnaudL75** [inverse-inc/packetfence#8216]
Hi team,

For some time, I have no entries in the RADIUS Audit Logs tab.

In terms of pagination, I have 2 pages, but when I click on "2", I return to the first page.
In reality I have many more pages, but the pagination only shows 2.

If I do a research in the search field, no entries are found.

Everything worked very well for many months. Then overnight, without any action on my part and without any update, the logs are empty.

I was in version 13.0, I just upgraded today to version 13.2, I still have the same problem.

Is this a display problem? Database?

Thanks :)

![Capture d'écran 2024-07-15 180508](https://github.com/user-attachments/assets/ed1df35e-f56c-4e4b-a384-df37eb2d6ad0)

** SERVER **
 - OS: Debian 11 up to date
 - Kernel : 5.10.0-30

Statistics and other indicators work well : 

![Capture d'écran 2024-07-15 181230](https://github.com/user-attachments/assets/19d69ae4-d14f-4dd0-94dd-e3f3414a7646)

![Capture d'écran 2024-07-15 181157](https://github.com/user-attachments/assets/da31d185-991d-4902-a505-2919071b2257)

![Capture d'écran 2024-07-15 181322](https://github.com/user-attachments/assets/b74b67f8-962a-4048-967a-739128d40b76)

**Comment by ArnaudL75** [comment]
Like another topic, if I send the command:
`redis-cli --raw LRANGE RADIUS_AUDIT_LOG 0 -1`

I have few lines like:

> ["Reject",{"State":"0xf3e05707f3e84d967357306bd5378a2c","Framed-MTU":1500,"MS-CHAP-Challenge":"0x4fee8457251496de6f7fd4a1da1a316b","PacketFence-KeyBalanced":"df925a49793138aa2d56db7436115fb6","Event-Timestamp":"May 14 2024 20:45:17 CEST","EAP-Message":"0
x020800591a02080054318110dd7cf70656714ed9c4680ea11f8300000000000000008e930e8605cd6598db45302c4f67ab7cb7c19f3c889dc8f300686f73742f41524e4155442d4f505449504c45582e4c504c2e494e545241","NAS-Port":50002,"MS-CHAP-User-Name":"host\\/ARNAUD-OPTIPLEX.MYCOMPANY.INTRA","
User-Name":"host\\/ARNAUD-OPTIPLEX.MYCOMPANY.INTRA","Service-Type":"Framed-User","MS-CHAP2-Response":"0x086f8110dd7cf70656714ed9c4680ea11f8300000000000000008e930e8605cd6598db45302c4f67ab7cb7c19f3c889dc8f3","NAS-Port-Id":"GigabitEthernet0\\/2","PacketFence-Doma
in":"AD","PacketFence-Outer-User":"host\\/ARNAUD-OPTIPLEX.MYCOMPANY.INTRA","PacketFence-Radius-Ip":"10.10.254.30","Cisco-AVPair":["service-type=Framed","audit-session-id=0A0AFE35000011A53D54FD9F"],"Calling-Station-Id":"0c:0e:76:90:03:3f","NAS-IP-Address":"10.1
0.254.53","EAP-Type":"MSCHAPv2","PacketFence-NTLMv2-Only":"--allow-mschapv2","NAS-Port-Type":"Ethernet","FreeRADIUS-Proxied-To":"127.0.0.1","Called-Station-Id":"00:64:40:bf:d5:02","Realm":"LPL.INTRA","Module-Failure-Message":["chrooted_mschap_machine: Pr
ogram returned code (1) and output The
attempted
logon
is
invalid.
This
is
either
due
to
a
bad
username
or
authentication
information.
(0xc000006d)","chrooted_mschap_machine: External script says: The attempted logon is invalid. This is either due to a bad username or authentication information. (0xc000006d)","chrooted_mschap_machine: MS-CHAP2-Response is incorrect"],"User-Password":"**
****"},{"MS-CHAP-Error":"\bE=691 R=0 C=22016234be96a9181f1b5f5810c4697a V=3 M=Authentication rejected","EAP-Message":"0x04080004","Message-Authenticator":"0x00000000000000000000000000000000"},{"Auth-Type":"eap"}]

The return line are very weird.

**Comment by prolicht-at** [comment]
on a fresh 14.0 install, the radius audit logs are empty as well. any ideas how to fix this?

**Comment by Toxa** [comment]
I have the same problem in 13.2 and 14.0. Sometimes, for a very short period of time, messages with incorrect date like 01/01/0001 02:30 AM appear (regardless of the current time)

**Comment by Eure-IT** [comment]
Ticket:[1]2024092010000178    
 Hallo -,

Viele Grüße
Torsten

 [2]   IP Dynamics GmbH | Billstraße 103 – 20539 Hamburg  

   ***@***.***   

Geschäftsführer: Christian Stölken, Dr. Michael Stölken, Sitz: Hamburg,
Registergericht Hamburg HRB 95850, Umsatzsteuer-Identifikationsnummer gemäß § 27a,
USt-IdNr.: DE 247583025 IPD Klassifizierung: Intern

09/20/2024 10:00 - Стариков Антон wrote: > 
> I have the same problem in 13.2 and 14.0. Sometimes, for a very short period of
> time, messages with incorrect date like 01/01/0001 02:30 AM appear (regardless of
> the current time)
> 
> —
> Reply to this email directly, [4]view it on GitHub, or [5]unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID:
> ***@***.***>
> 
>  



[1] https://service.ipdynamics.de/otrs/customer.pl?Action=CustomerTicketZoom&amp;TicketID=533587
[2] https://www.ipdynamics.de/
[3] ***@***.***
[4] https://github.com/inverse-inc/packetfence/issues/8216#issuecomment-2363075475

**Comment by satkunas** [comment]
Fixed in latest version.
