### ISSUE TITLE
PacketFence 12.x/13.x install fails due to ipt-netflow-2.5.1 no longer builds linux-image-5.10.0-31-amd64/5.10.221-1

### ISSUE THREAD

**Issue by nathanbloemendaal78** [inverse-inc/packetfence#8219]
**Describe the bug**
PacketFence 12.x/13.x install fails due to ipt-netflow-2.5.1 no longer builds linux-image-5.10.0-31-amd64/5.10.221-1:

Loading new ipt-netflow-2.5.1 DKMS files...
Building for 5.10.0-31-amd64
Building initial module for 5.10.0-31-amd64
Error! Bad return status for module build on kernel: 5.10.0-31-amd64 (x86_64)
Consult /var/lib/dkms/ipt-netflow/2.5.1/build/make.log for more information.
dpkg: error processing package iptables-netflow-dkms (--configure):
 installed iptables-netflow-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of packetfence:
 packetfence depends on iptables-netflow-dkms; however:
  Package iptables-netflow-dkms is not configured yet.

dpkg: error processing package packetfence (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 iptables-netflow-dkms
 packetfence
E: Sub-process /usr/bin/dpkg returned an error code (1)

This seems to be caused by [this](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1980551.html) bug.

**Expected behavior**
PacketFence install should finish without errors.

**Comment by satkunas** [comment]
Tracking in #8221

**Comment by jrouzierinverse** [comment]
This has been fixed.
