### ISSUE TITLE
PacketFence-ISO-v13.2.0 service not starting after new install

### ISSUE THREAD

**Issue by llovvoll** [inverse-inc/packetfence#8222]
I downloaded the latest iso from the official website and installed it. After the installation was completed, I wanted to connect to https://ip:1443 and found that I could not connect. After checking, the service was not started. I tried to use pfcmd to start and got an error... Did I miss something? Please advice, thanks

![image](https://github.com/user-attachments/assets/fd8d533d-d587-4074-be13-6150f3fadb8e)

**Comment by pdlove** [comment]
I'm having the same issue. It looks like the packetfence package isn't configuring because the dependent package "iptables-netflow-dkms" is failing to compile. Related to https://github.com/inverse-inc/packetfence/issues/8221

**Comment by Vineees** [comment]
I'm currently having the same problem

**Comment by jrouzierinverse** [comment]
This has been fixed
