### ISSUE TITLE
error restart api-frontend in web-ui

### ISSUE THREAD

**Issue by stegar123** [inverse-inc/packetfence#8223]
**Describe the bug**
When we  restart api_frontend from web-ui, the user token use is lost and is giving the error that cannot restart the service, but the service is  restarted successfully.

**To Reproduce**
1. Go to 'Configuration -> Admin login .-> made some changes'
2. restart the service api_frontend

**Screenshots**
![error_login_api_frontend](https://github.com/user-attachments/assets/7049a32c-d8d7-46e3-b7eb-6b3a2149e5cf)

**Expected behavior**
At least return login page

**Comment by jrouzierinverse** [comment]
Please retest with newer version

**Comment by jrouzierinverse** [comment]
This was fixed with 9b336eed1033a7a1082a7766d200c1d52e800b76

**Comment by satkunas** [comment]
closing, @stegar123 reopen if necessary
