### ISSUE TITLE
Configurator Interface high_availability type

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#8224]
**Describe the bug**
Backend uses integer `1`,  UI uses string `"1"`, causing toggle to turn-off when enabled.

**To Reproduce**
1. Fresh Install on Debian12
2. Enable Debugger
3. Edit `eth0`
4. Enable High Availability
5. Click Save
6. Compare `PATCH` payload and `GET` response

**Comment by jrouzierinverse** [comment]
How much work does it take to change it on the frontend?

**Comment by satkunas** [comment]
@jrouzierinverse just a few minutes
