### ISSUE TITLE
proxy configuration for PacketFence

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#823]
Some clients do need a specific proxy configuration for the internal devices to access outside world (Internet).

Would be interesting to have a way to configure proxy configuration in PacketFence so that PacketFence itself can easily access Internet without having to configure environment variables.

**Comment by erSitzt** [comment]
+1

**Comment by julsemaan** [comment]
I like environment variables and we don't seem to get that demand very often
