### ISSUE TITLE
layered "profile-templates"

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#824]
To ease modification and management of "profile-templates" files, the following changes should be considered:
- /usr/local/pf/html/captive-portal/templates now becomes the 'original' files where no modifications are made. This is in fact packaged by the PacketFence packages / sources.
- /usr/local/pf/html/captive-portal/profile-templates contains the different portal-profiles templates directories, but instead of each holding a copy of the original files, they will only contains copy of a modified file (a folder can be empty, which will lead to use default files)
- Installation / upgrade / source installation process would create a 'default' portal profile under /usr/local/pf/html/captive-portal/profile-templates which will stays empty. Modified file that will now become default ones can be copied over from the origin folder and modified.
- Creating a new portal profile would create an empty folder which may allow customization of files if needed.
- Rendering the templates from a portal perspective will behave the following: portal-profile folder, default folder, origin folder. If a template is found in the first folder, it uses it, otherwise it continues in the tree.
- Managing the files from the web admin GUI will behave as for the rendering. Listing will list all the files depending on the tree and will allow modification and create a copy in the appropriate folder

**Comment by julsemaan** [comment]
+1 million

**Comment by dwlfrth** [comment]
That should be a v6 feature
