### ISSUE TITLE
Syslog parser regex

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#8246]
**Describe the bug**
When you add a rule in a regex syslog parser there is a rate_limit configuration parameter set in the rule that is useless in in the wrong format.

```
[Custom_dhcp_Syslog]
status=enabled
path=/usr/local/pf/var/dhcp
type=regex

[Custom_dhcp_Syslog rule Machine_Name]
action0=modify_node: mac, $mac, computername, $computername
action1=update_ip4log: mac, $mac, ip, $ip
rate_limit=HASH(0x55fc88c81c10)
regex=(DHCPDISCOVER|DHCPOFFER|DHCPREQUEST|DHCPACK|DHCPRELEASE|DHCPINFORM|DHCPEXPIRE) on (?P<mac>[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+) to (?P<ip>[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}) \((?P<computername>\w+)\)
ip_mac_translation=enabled
last_if_match=enabled

```

**Comment by fdurand** [comment]
In fact the issue is more because there is no rate_limit parameter in the action sent to the backend
![image](https://github.com/user-attachments/assets/076a0c78-e1de-46b1-babd-38486f4adbbb)

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/commit/b78fd76186349252f7b4882c54dcb8a27ec2849c
