### ISSUE TITLE
haproxy-portal doesn't start

### ISSUE THREAD

**Issue by Analistagit** [inverse-inc/packetfence#8247]
I instaled ISO packetfence.
haproxy-portal doesn't start.
How fix it ?
Already see /var/log/syslog but doesn't see nothing about haproxy-portal.

**Comment by Analistagit** [comment]
I found in /usr/local/pf/logs/haproxy_portal.log:
Error: No such container: haproxy-poError: No such container: haproxy-portal

parsing [/usr/local/pf/var/conf/haproxy-portal.conf:98]: 'option httpchk' : hiding headers or body at the end of the version string is deprecated. Please, consider to use 'http-check send' directive instead.

**Comment by JeGoi** [comment]
> I found in /usr/local/pf/logs/haproxy_portal.log: Error: No such container: haproxy-poError: No such container: haproxy-portal

That one make sens since https://github.com/inverse-inc/packetfence/blob/devel/containers/systemd-service#L130

**Comment by Analistagit** [comment]
This can be closed, it has been resolved.
Thank you.
