### ISSUE TITLE
Registration Window reset when changing Unregistration date

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#8253]
**Describe the bug**
Registration Window reset when changing Unregistration date

**To Reproduce**
1. Edit a local user
2. Go in actions tab
3. Change the Registration Window end date
4. Change the Unregistration date
5. The Registration Window end date revert automatically

**Screenshots**
![image](https://github.com/user-attachments/assets/d9018f19-2528-43c5-b789-9dc3e4a8fdac)

**Expected behavior**
Should not reset the Registration Window end date

**Comment by satkunas** [comment]
Unable to reproduce
