### ISSUE TITLE
Since httpd.aaa.access httpd.webservices.access httpd.portal.access have been merged in httpd.apache.access, NETDATA is not happy

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#8258]
**Describe the bug**
Netdata is returning errors 
which did not make sens.

So Netdata needs to but update with that merge.

**To Reproduce**
1. Go to on the first page see the error

**Screenshots**
![Screenshot from 2024-08-22 13-54-24](https://github.com/user-attachments/assets/da1a40cd-41f2-444a-b555-7ce6f10a0233)

**Expected behavior**
Do not see that "fake error"

**Comment by fdurand** [comment]
It has been fixed by https://github.com/inverse-inc/packetfence/commit/23918345e7c43ae65d820cca956fadfc3fc481c9
