### ISSUE TITLE
User does not receive email with access credentials.

### ISSUE THREAD

**Issue by Analistagit** [inverse-inc/packetfence#8275]
User does not receive email with access credentials.
The Portal work, i put name, e-mail, celular, but I don't receive an email with access credentials.

**Comment by Analistagit** [comment]
I use INLINE mode.

**Comment by fdurand** [comment]
Please use the Mailing list for that, it looks to be a configuration issue.  https://sourceforge.net/projects/packetfence/lists/packetfence-users

**Comment by Analistagit** [comment]
This has already been resolved. Thank you.
