### ISSUE TITLE
PF 5.3.1 - VLAN Enforcement Configuration getting corrupted in configurator

### ISSUE THREAD

**Issue by karlkennedy01** [inverse-inc/packetfence#828]
When I try to configure VLAN Enforcement the following happens:
1. set eth0 to management - works fine
2. create and set eth0.2 to 10.10.2.1 as registration vlan - initially works fine
3. create and set eth0.3 to 10.10.3.1 as isolation vlan - sets both eth0.2 and eth0.3 to isolation vlan, sets bcast to 10.10.3.255 for both eth0.2 and eth0.3
4. try to change eth0.2 to registration vlan - sets both eth0.2 and eth0.3 to registration vlan
5. will not let me proceed with configuration
6. tried with ZEN OVA, Debian and Ubuntu with all giving the same issue.
7. editing the files to correct does not allow me to continue with the configurator - any workarounds??

Edit: added networks.conf screenshot - 10.10.2.0 interface dhcp_end is wrong, 10.10.3.0 interface does not even get created
![networksconf](https://cloud.githubusercontent.com/assets/13582055/9068664/a098ab10-3ab2-11e5-9b9e-b754410909c0.PNG)

![pfconf](https://cloud.githubusercontent.com/assets/13582055/9068459/99a0db30-3ab1-11e5-8ce8-ea64f77b1704.PNG)
![ifconfig](https://cloud.githubusercontent.com/assets/13582055/9068458/98c2eee2-3ab1-11e5-8a6c-4d33ff503708.PNG)

**Comment by julsemaan** [comment]
Your 2 VLAN interfaces are in the same network (and they shouldn't) which is the cause of your issue.

This subject should be continued in the mailing list as this is a configuration issue

**Comment by karlkennedy01** [comment]
Thanks you are correct and my bad. The .254.0 should have been .255.0. corrected and works
