### ISSUE TITLE
PF 14.0 ISO - APT PublicKey Missing 

### ISSUE THREAD

**Issue by MarioSpenc** [inverse-inc/packetfence#8302]
After fresh installation of PF14.0 apt is broken with following error:

root@xxxxx:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://inverse.ca/downloads/PacketFence/debian/14.0 bookworm InRelease
Err:4 http://inverse.ca/downloads/PacketFence/debian/14.0 bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CB2D3A2AA0030E2C
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://inverse.ca/downloads/PacketFence/debian/14.0 bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CB2D3A2AA0030E2C
W: Failed to fetch http://inverse.ca/downloads/PacketFence/debian/14.0/dists/bookworm/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CB2D3A2AA0030E2C
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by JeGoi** [comment]
Thanks for reporting, I will check/fix that.

**Comment by JeGoi** [comment]
Branch created: https://github.com/inverse-inc/packetfence/tree/fix/8302
We currently have issues on packaging.
As soon as it is fixed on Devel, I will test it, if well, merge it and backport to maintenance/14.0.
Thanks
At the same you should be able to fix it by using the following cli:
https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_debian_based_systems_2
