### ISSUE TITLE
radius audit log timestamp is restored to 0000

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#8314]
**Describe the bug**

**To Reproduce**
1. Go to to see a radius entry
2. See the year cleaned to 0000

**Screenshots**
![image](https://github.com/user-attachments/assets/3380410c-2959-4524-9fb0-bbbc9741ba47)

**Expected behavior**
Having the real date.

**Additional context**
Zammitbug related

**Comment by satkunas** [comment]
```
ALTER TABLE radius_audit_log MODIFY created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

**Comment by Shahzaib-Akhtar-khan** [comment]
hi i have same issue i am working on clustering when i sync the time of all 3 servers i get audit log issue as i didnt see new add device and the time stamp is also incorrect

**Comment by JeGoi** [comment]
@Shahzaib-Akhtar-khan Please, could you add your Packetfence version? Thank you
