### ISSUE TITLE
Cell number in captive portal

### ISSUE THREAD

**Issue by Analistagit** [inverse-inc/packetfence#8318]
My friends,  how I can configure to the phone number field in captive portal so that an user can only use digit numbers and not other characters?
Additionally, I need to set a maximum and minimum character limit for the cell number.

**Comment by JeGoi** [comment]
Hi @Analistagit It looks like more a question for https://www.packetfence.org/support.html#/community (or https://www.packetfence.org/support.html#/commercial) than an issue.
Please reopen it if it is an issue.
Thanks
