### ISSUE TITLE
Improper HTML escape in rule_read.tt

### ISSUE THREAD

**Issue by raywolfe** [inverse-inc/packetfence#832]
Version 5.3.1 
read_rule.tt 
Line 12 is not escaping HTML correctly.

<dt>[% l('If [_1] of the following conditions are met:', [ form.field('match').render_element ]) | none %]</dt>

**Comment by raywolfe** [comment]
Temporarily corrected with

<dt>If [% form.field('match').render_element | none %] of the following conditions are met:</dt>

**Comment by julsemaan** [comment]
This has already been fixed and is available through the PacketFence maintenance which you can apply using : `/usr/local/pf/addons/pf-maint.pl` 

Cheers !
