### ISSUE TITLE
Role Name Change loses settings for rules and vlan-id

### ISSUE THREAD

**Issue by CrazedMagician** [inverse-inc/packetfence#833]
Changing a role name causes rules and Source/Switch Vlan-ID to lose settings. So you have to go re-setup the rules and switch vlan-id
Can Roles be changed to a guid based system where this will not happen.
This way a change to a role name doesn't cause verification of all setting that might have used it.

**Comment by louismunro** [comment]
Fair point. For consideration in PF6.

**Comment by julsemaan** [comment]
We addressed it by preventing users to rename a role

**Comment by CrazedMagician** [comment]
I am now using the 7.4 but I am not certain that removing the ability to rename a role was the best solution.
What I see now is that I cannot also delete a role and if I cannot rename it then I can’t do any type of cleanup/reuse things that have no real meaning. This will cause the roles list to grow indefinitely.
