### ISSUE TITLE
Captive Portal and CoA-ACK on Apple Devices

### ISSUE THREAD

**Issue by stoffl89** [inverse-inc/packetfence#8363]
Hi all,

i have a Packetfence Installion Version 13.2. Everything is working fine except Apple devices in Guest Environment ...
When i connect an Apple device (Doesn't matter if iPhone, iPad or MAC) the Captive Portal opens as expected, i can login with my Authentication Sources, but then the Network Detection is not working. The Captive Portal does not disappear and i got the message, that the network connection could not be established. 
And here's the thing. If i disconnect the device and reconnect it, i got a working Connection. Network Detection works great on multiple Android Devices and Windows, but not on Apple.
In the Audit Logs i got an CoA-ACK and Accept Message. Even if i try with Disconnect instead of CoA, Apple does not understand what to do.

Has anyone else this behavior?

Thanks in advance!
Chris

**Comment by satkunas** [comment]
It's a known behaviour for Apple Devices.
