### ISSUE TITLE
Dynamic access duration choice

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#837]
When creating two 'dynamic access duration' with the same number of hour (could be same number of seconds, minutes, hours, days, weeks, years), only the last one is being offered in access duration of rules in authentication sources.

Example:
- 5hF+1D
- 5hF+1W

Only 5hF+1W will be offered

**Comment by dwlfrth** [comment]
Issue with unix timestamp being computed with only part of the value and being the same. (Used as the hashkey)

**Comment by louismunro** [comment]
What do we do with this one?
Fix, close or move to 5.7?

**Comment by fdurand** [comment]
Not relevant anymore in the new admin
