### ISSUE TITLE
Button to enable ACL in Switch Group dont show

### ISSUE THREAD

**Issue by rsp1991** [inverse-inc/packetfence#8374]
**Describe the bug**
When I try enable ACL in switch group the button dont show

**To Reproduce**
1. Go to Switch Group
2. Click on Roles
3. Click on Access List
![image](https://github.com/user-attachments/assets/6c8bd006-c512-4b15-8dcd-14ca289fad18)

**Expected behavior**
One button to enable the fields

I inspected the HTML code and in the DIV is empty:

![image](https://github.com/user-attachments/assets/aba85968-40b9-4651-a9ea-99b80ea41488)

**Comment by JeGoi** [comment]
On a fresh installation of pf 14.0.0.
![Screenshot from 2024-11-04 13-32-43](https://github.com/user-attachments/assets/f9c85239-7150-45ff-8d60-e2354552d9c2)
and
![Screenshot from 2024-11-04 13-34-19](https://github.com/user-attachments/assets/a8b9fe9c-9be4-4376-825a-6480d5a9bc88)

I am not able to reproduce.
We need more info on how you have been able to make it.
Please, we need more information.

**Comment by satkunas** [comment]
Switch Features depend on the `Type` chosen and its supported features. It appears that the Type chosen does not support this feature, thus the input is disabled.
