### ISSUE TITLE
Admin Roles Issue

### ISSUE THREAD

**Issue by jkoch22** [inverse-inc/packetfence#8375]
**Describe the bug**
404 error in console when clicking on built-in NONE, ALL, ALL_PF_ONLY admin roles 

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'System Configuration'
3. Click on 'Admin Roles'
4. Click on "ALL"
5. Page doesn't load and requires a refresh.

**Expected behavior**
Either show an error stating the role isn't editable or load the page to modify the role.

**Additional context**
14.0.0

**Comment by JeGoi** [comment]
I guess it is under "Admin Access" for 14.0.0
The rest is valid and I am able to reproduce.
```
Request URL:
https://PI:1443/api/v1/config/admin_role/ALL
Request Method:
GET
Status Code:
404 Not Found
```
![Screenshot from 2024-11-04 13-28-05](https://github.com/user-attachments/assets/7025e9b4-39d0-4273-9b4a-ba42e56c744f)
