### ISSUE TITLE
PF 14.0 and 14.1 upgrade script runs upgrades before stopping services - while downloading "packetfence-upgrade"

### ISSUE THREAD

**Issue by E-Thang** [inverse-inc/packetfence#8389]
**Describe the bug**
PF 14.0 and 14.1 is installing all pending packetfence* upgrades immediately after the $ADDS/upgrade/do-upgrade.sh command is executed. It's installing them at the point where only packetfence-upgrade is intended to be installed.

After the upgrades complete it stops services and asks if you also want to upgrade the OS and what version of PF you want to upgrade to. But it's already installed the latest upgrade in the current release train at this point.

**To Reproduce**
1. On a PF 14.0 or 14.1 server use the upgrade script `$ADDS/upgrade/do-upgrade.sh` or just issue the command `apt install packetfence-upgrade`
2. All pending PacketFence upgrades are installed.

**Workaround**
1. Use apt-mark hold to hold the pending upgrades except packetfence-upgrade prior to starting the upgrade script. 
2. `apt-mark hold packetfence-archive-keyring packetfence-config packetfence-golang-daemon packetfence-ntlm-wrapper packetfence-perl packetfence-pfcmd-suid packetfence-redis-cache packetfence-upgrade packetfence`
3. $ADDS/upgrade/do-upgrade.sh
4. When packetfence-upgrade is installed and the script beings stopping services, suspend execution (CTRL-Z)
5. Unhold the upgrades, `apt-mark unhold packetfence-archive-keyring packetfence-config packetfence-golang-daemon packetfence-ntlm-wrapper packetfence-perl packetfence-pfcmd-suid packetfence-redis-cache packetfence-upgrade packetfence`
6. Use `fg` to resume execution.

**Expected behavior**
Fix the underlying issue with the Debian 12 OS or APT scripts that is resulting in this behavior.

**Comment by E-Thang** [comment]
Any idea why this is happening? I spent all day digging in to this, didn't find anything that seemed out of place. I dug through dpkg preinst/postinst scripts and dependencies. If there's an issue there, it eluded me.

**Comment by JeGoi** [comment]
What you are trying to do is installing devel branch.

I am not sure this is that mature.
Most of CI tests are failing in our ci.

If I recall correctly since it is Devel, it is not the classical upgrade path. It should take care of the current db upgrade versions for example. We are not at that point for now. It will be tested during frozen test for next version.

Please, wait until this version is out or wait until we are starting testing phase.

**Comment by E-Thang** [comment]
14.0 isn't devel though. Are you referring to my other issue about the db upgrade in 14.1? That's a separate bug report

**Comment by JeGoi** [comment]
14.1 is devel.
Trying to upgrade to devel, so from 14.0 to 14.1, is not something we recommend until the official version is out.

**Comment by JeGoi** [comment]
Are you referring to that: 
https://github.com/inverse-inc/packetfence/blob/devel/addons/upgrade/do-upgrade.sh#L10-L19 ?

If yes, then it is there since a long time ago, ex: https://github.com/inverse-inc/packetfence/blob/maintenance/12.0/addons/upgrade/do-upgrade.sh
It is there since 12.0. So not related to any version you mentioned

It is installing the latest packetfence-upgrade package. It is not related to the packetfence upgrade itself, It is a package.
As RPM and for exemple, it is build from there: https://github.com/inverse-inc/packetfence/blob/maintenance/12.0/rpm/packetfence-upgrade.spec

It needs to be done  before the installation since package and dependencies are used in the second script: https://github.com/inverse-inc/packetfence/blob/maintenance/13.0/addons/upgrade/do-upgrade.sh#L24

So, sorry but I do not see your point...

**Comment by E-Thang** [comment]
You've misunderstood the issue.

This isn't about upgrading from 14.0 to 14.1. Just updating 14.0 with the periodic patches.  Maybe I shouldn't have used the word upgrade and should have said update or patching? The process is named upgrade though. The same issue exists in 14.1, which is devel, that's fine. Both of the Debian 12 versions behave the same.

Regardless of the version. It shouldn't install the update prior to the phase in the script where it's ready to do so. do-upgrade.sh is **supposed** to install the packetfence-upgrade package. Once that's installed the script calls run-upgrade.sh to actually perform the upgrade. The issue is that installing the version 14.0 packetfence-upgrade package installs all of the updates prior to calling run-upgrade.sh. 

The script do-upgrade.sh calls "apt update" and "apt install packetfence-upgrade", and that's what's broken. It doesn't only install that one package. It installs every packetfence package that apt has a pending update for.

**Comment by E-Thang** [comment]
The issue can be demonstrated from the CLI, without the upgrade script. This is 14.1, but it's identical in 14.0. The behavior below happens when the upgrade script is run, installing packetfence-upgrade installs everything

```

root@boomer:/usr/local/pf# apt list --upgradable
Listing... Done
packetfence-archive-keyring/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 all [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-config/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 all [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-golang-daemon/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 amd64 [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-ntlm-wrapper/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 amd64 [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-pfcmd-suid/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 amd64 [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-redis-cache/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 all [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence-upgrade/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 all [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
packetfence/unknown 14.1.0+20241126162152+1561322518+0012+devel+bookworm1 all [upgradable from: 14.1.0+20241125220414+1559967716+0012+devel+bookworm1]
root@boomer:/usr/local/pf#
root@boomer:/usr/local/pf#
root@boomer:/usr/local/pf#
root@boomer:/usr/local/pf#
root@boomer:/usr/local/pf#
root@boomer:/usr/local/pf# apt install packetfence-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  packetfence packetfence-archive-keyring packetfence-config packetfence-golang-daemon packetfence-ntlm-wrapper packetfence-pfcmd-suid packetfence-redis-cache
The following packages will be upgraded:
  packetfence packetfence-archive-keyring packetfence-config packetfence-golang-daemon packetfence-ntlm-wrapper packetfence-pfcmd-suid packetfence-redis-cache packetfence-upgrade
8 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.8 MB of archives.
After this operation, 1,024 B of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
root@boomer:/usr/local/pf#

```

**Comment by JeGoi** [comment]
Ok Now I got it.
Thanks for clarification.
I will test and check.

**Comment by JeGoi** [comment]
https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html#_apply_maintenance_patches
Is to apply patches.
https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html#_upgrade_to_another_version_major_or_minor is to upgrade.
Not the same way.
Are you trying to apply patches with the upgrade script?

**Comment by JeGoi** [comment]
> The script do-upgrade.sh calls "apt update" and "apt install packetfence-upgrade", and that's what's broken. It doesn't only install that one package. It installs every packetfence package that apt has a pending update for.

I will check why packetfence-upgrade looks like have dependencies.

**Comment by E-Thang** [comment]
Ugh, Yes! There's my mistake! I was using the upgrade script to apply weekly patches. I was thinking that the patches changed the minor version and that the minor version is the 3rd number, like 14.0.x to 14.0.y. 

(－‸ლ)    <- Facepalm!

That also explains why I was so confused about the db upgrade logic in 14.1. The upgrade script is only for changing to some other version.

That doesn't change the issue with apparent dependencies with packetfence-upgrade package. But makes it a non-issue until I intend to change versions.

**Comment by JeGoi** [comment]
And I think that it is a normal behavior.

First, there is no dependencies,
```
root@PF14-Deb12-pf:/usr/local/pf# apt-cache rdepends packetfence-upgrade
packetfence-upgrade
Reverse Depends:
```
BUT, if you are not at the latest version of PF available, the apt update will update infos from the repo, then if you try to install any related PacketFence package.
```
root@PF14-Deb12-pf:/usr/local/pf# apt-cache madison packetfence
packetfence | 14.0.0+20241125134753+1561793836+0012+maintenance~14~0+bookworm1 | http://inverse.ca/downloads/PacketFence/debian/14.0 bookworm/bookworm amd64 Packages
root@PF14-Deb12-pf:/usr/local/pf# apt update
root@PF14-Deb12-pf:/usr/local/pf# apt list --upgradable
Listing... Done
[...]
packetfence/unknown 14.0.0+20241125134753+1561793836+0012+maintenance~14~0+bookworm1 all [upgradable from: 14.0.0+20240815114421+1414575349+0012+devel+bookworm1]
[...]
```
So, a new version is available.
When we are doing an upgrade (changing the version, we are going it from the latest of a branch to the latest of the new branch. That means, if there is a new version, apply it first then, do the upgrade.
For me, it make completely sense.
