### ISSUE TITLE
Problem when running ubiquiti_ap_mac_to_ip. 

### ISSUE THREAD

**Issue by oscarvdcr** [inverse-inc/packetfence#8393]
A couple of days ago i installed a new PacketFence with the ZEN option in a VM from a vCenter that i have. When i was configuring everything i gave me the error Can't locate object method "populateAccessPointMACIP" via package "pf::Switch" at /usr/local/pf/lib/pf/pfcron/task/ubiquiti_ap_mac_to_ip.pm line 65. 
No idea why it happens or how to fix it. I'm in desperate need of help because i'm very lost and can't continue the configuration without fixing this.

**Comment by fdurand** [comment]
I pushed the change in the maintenance branch so the packages should be available tomorrow.

apt update
apt upgrade
