### ISSUE TITLE
Fingerbank library logs are not rotated

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#841]
With the verbosity of the library, I saw one at 25G.

Should be added to the logrotate of PacketFence or the library should install it's own logrotate filee

**Comment by dwlfrth** [comment]
Closing this one since it is Fingerbank related.
Will open same in Fingerbank project

**Comment by dwlfrth** [comment]
See https://github.com/inverse-inc/fingerbank/issues/21
