### ISSUE TITLE
Official Docker container

### ISSUE THREAD

**Issue by thecreativeone91** [inverse-inc/packetfence#8415]
**Is your feature request related to a problem? Please describe.**
No Problem. Enhancement only

**Describe the solution you'd like**

I would like to see an official docker container for Packet-fence, with easy updating and maintenance along with support for mapping data paths properly outside of the container, and minimally external database support. Internal DB support may a good option to support as well for a quick and dirty test environment or small deployment.

**Comment by satkunas** [comment]
All features already supported:
- Dockerized services
- external database support, with host volume mounts
- internal database support
