### ISSUE TITLE
unable to locate python3-impacket examples

### ISSUE THREAD

**Issue by stgmsa** [inverse-inc/packetfence#8420]
**Describe the bug**
After a fresh installation of PF v14.1, the impacket is not fully installed on pfperl-api container.
Which will eventually cause domain join related feature to fail.

**To Reproduce**
1. install PacketFence v14.1 on debian 12 following the official instructions
2. go through the configurator and then login to admin panel
3. try to do a domain profile creation and hit a 422 error
4. look into the pfperl-api container and impacket examples python scripts are missing.

**Screenshots**
Not necessary

**Expected behavior**
python3-impacket is properly installed and the example scripts are available.

**Additional context**
python3-impacket is installed on the host machine of PacketFence, all the examples are there and usable.
when trying to install python3-impacket inside pfperl-api container, the expected example files does not appear.
Maybe it's a version issue, or dpkg repo source issue.

**Comment by E-Thang** [comment]
IMO it would be ideal if the examples weren't used. If they must be used, they should be copied to the PacketFence code base and attributed (as long as the license permits).
