### ISSUE TITLE
Debian Logrotate permission errors

### ISSUE THREAD

**Issue by David-B55** [inverse-inc/packetfence#843]
Hi we seem to be having an issue with some of the log files not being rotated. 

A dump of the directory.

> $ ls -lah /usr/local/pf/logs/ 
> total 180K
> drwxrwsr-x  2 pf   pf 4.0K Aug 17 12:05 .
> drwxr-xr-x 14 pf   pf 4.0K Aug 12 11:26 ..
> -rw-rw----  1 pf   pf    0 Aug 17 12:05 cache.log
> -rw-rw----  1 pf   pf   20 Aug 17 12:01 cache.log.1.gz
> -rw-r--r--  1 pf   pf    0 Aug 17 12:05 clients.log
> -rw-r--r--  1 pf   pf  129 Aug 17 12:00 clients.log.1.gz
> -rw-r-----  1 root pf 1.2K Aug 17 12:00 collectd.log
> -rw-r-----  1 root pf 7.4K Aug 17 12:07 console.log
> -rw-rw----  1 pf   pf    0 Aug 17 12:05 exception.log
> -rw-rw----  1 pf   pf   20 Aug 17 12:01 exception.log.1.gz
> -rw-rw----  1 root pf 3.8K Aug 17 12:07 httpd.aaa.access
> -rw-rw----  1 root pf  158 Aug 17 12:00 httpd.aaa.error
> -rw-rw----  1 root pf    0 Aug 17 12:00 httpd.admin.access
> -rw-rw-r--  1 root pf  318 Aug 17 12:00 httpd.admin.catalyst
> -rw-rw----  1 root pf  184 Aug 17 12:00 httpd.admin.error
> -rw-rw-r--  1 root pf    0 Aug 17 12:00 httpd.admin.log
> -rw-rw----  1 root pf    0 Aug 17 12:00 httpd.graphite.access
> -rw-rw----  1 root pf  154 Aug 17 12:00 httpd.graphite.error
> -rw-rw----  1 root pf 3.8K Aug 17 12:07 httpd.portal.access
> -rw-rw-r--  1 root pf  320 Aug 17 12:01 httpd.portal.catalyst
> -rw-rw----  1 root pf    0 Aug 17 12:01 httpd.portal.error
> -rw-rw----  1 root pf 3.8K Aug 17 12:07 httpd.webservices.access
> -rw-rw----  1 root pf  158 Aug 17 12:01 httpd.webservices.error
> -rw-rw----  1 pf   pf    0 Aug 17 12:05 info.log
> -rw-rw----  1 pf   pf  197 Aug 17 12:01 info.log.1.gz
> -rw-r--r--  1 pf   pf 6.0K Aug 17 12:07 listener.log
> -rw-r--r--  1 pf   pf  380 Aug 17 12:05 listener.log.1.gz
> -rw-rw----  1 pf   pf    0 Aug 17 12:05 metricaccess.log
> -rw-rw----  1 pf   pf   20 Aug 17 12:01 metricaccess.log.1.gz
> -rw-rw-r--  1 root pf  58K Aug 17 12:01 packetfence.log
> -rw-rw-r--  1 pf   pf    0 Aug 17 12:05 pfconfig.log
> -rw-rw-r--  1 pf   pf   20 Aug 17 12:01 pfconfig.log.1.gz
> -rw-rw-r--  1 root pf 1.0K Aug 17 12:01 pfdhcplistener.log
> -rw-rw-r--  1 root pf  135 Aug 17 12:01 pfdns.log
> -rw-rw-r--  1 root pf 1.6K Aug 17 12:06 pfmon.log
> -rw-rw----  1 root pf 1.1K Aug 17 12:01 portal_error_log
> -rw-r-----  1 pf   pf    0 Aug 17 12:05 radius.log
> -rw-r-----  1 pf   pf  336 Aug 17 12:01 radius.log.1.gz
> -rw-rw----  1 pf   pf    0 Aug 17 12:05 rendering.log
> -rw-rw----  1 pf   pf   20 Aug 17 12:01 rendering.log.1.gz
> -rw-rw----  1 root pf  110 Aug 17 12:01 statsd.log

Forcing a logrotate to occur

> $ logrotate -f /etc/logrotate.d/packetfence 
> error: error opening /usr/local/pf/logs/collectd.log: Permission denied
> error: error opening /usr/local/pf/logs/console.log: Permission denied
> error: error opening /usr/local/pf/logs/httpd.admin.log: Permission denied
> error: error opening /usr/local/pf/logs/packetfence.log: Permission denied
> error: error opening /usr/local/pf/logs/pfdhcplistener.log: Permission denied
> error: error opening /usr/local/pf/logs/pfdns.log: Permission denied
> error: error opening /usr/local/pf/logs/pfmon.log: Permission denied
> error: error opening /usr/local/pf/logs/portal_error_log: Permission denied
> error: error opening /usr/local/pf/logs/statsd.log: Permission denied
> error: error opening /usr/local/pf/logs/httpd.aaa.access: Permission denied
> error: error opening /usr/local/pf/logs/httpd.admin.access: Permission denied
> error: error opening /usr/local/pf/logs/httpd.graphite.access: Permission denied
> error: error opening /usr/local/pf/logs/httpd.portal.access: Permission denied
> error: error opening /usr/local/pf/logs/httpd.webservices.access: Permission denied
> error: error opening /usr/local/pf/logs/httpd.aaa.error: Permission denied
> error: error opening /usr/local/pf/logs/httpd.admin.error: Permission denied
> error: error opening /usr/local/pf/logs/httpd.graphite.error: Permission denied
> error: error opening /usr/local/pf/logs/httpd.portal.error: Permission denied
> error: error opening /usr/local/pf/logs/httpd.webservices.error: Permission denied
> error: error opening /usr/local/pf/logs/httpd.admin.catalyst: Permission denied
> error: error opening /usr/local/pf/logs/httpd.portal.catalyst: Permission denied

This is after removing all files within the logs dir, and then restarting PF

**Comment by David-B55** [comment]
A bit of additional information. This is happening with PF version 5.3.1 installed from the PF debian repo https://inverse.ca/downloads/PacketFence/debian/

**Comment by julsemaan** [comment]
This should have been fixed already.

Please re-open if you experience the issue with the latest version
