### ISSUE TITLE
EU Cyber Resilience Act (CRA) normative

### ISSUE THREAD

**Issue by LizardNerd** [inverse-inc/packetfence#8449]
Hello everyone. In Europe, CRA normative has been approved, and due to this, I was wondering if PacketFence will be affected by CRA in the near future. Any thoughts on this? The CRA will be applied only after 11 December 2027 anyway.

**Comment by satkunas** [comment]
Please discuss in our mailing list https://sourceforge.net/p/packetfence/mailman/packetfence-users/
