### ISSUE TITLE
_should_we_reassign_vlan should see if roles/acls will change

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#845]
Or add an option to always reevaluate as this breaks roles + acls enforcement that are coupled with VLANs

**Comment by jrouzierinverse** [comment]
Should this be moved 5.5?

**Comment by julsemaan** [comment]
@fdurand what is the status on this ?

**Comment by fdurand** [comment]
#1032

**Comment by julsemaan** [comment]
Was fixed via #1032
