### ISSUE TITLE
SMS 

### ISSUE THREAD

**Issue by hooray4me** [inverse-inc/packetfence#847]
I have a "workflow" problem regarding SMS pin registration. Scenario: An iphone user signs up and selects sms registration. It takes them to the screen to enter the pin they receive via SMS. When they switch over to their text message to view the code, they get disconnected from the captive portal wifi network (This is by design with apple devices) 
When they rejoin to the wifi network, there is not a place for them to "complete" their registration, they can only sign in or sign up.

Is there a way to link to the pin code entry page?

**Comment by julsemaan** [comment]
This was a bug where the state of the node was lost.

Applying the following patch on your server should do it
https://github.com/inverse-inc/packetfence/commit/157cc10d8faac518b41bcd89214e69365e082591.patch

It will also be included in the next PacketFence release

**Comment by hooray4me** [comment]
forgive my ignorance, but how do I go about applying this patch?

**Comment by hooray4me** [comment]
nevermind, google told me... thanks!

**Comment by hooray4me** [comment]
how would you recommend I "patch" my setup if I installed on ubuntu  NOT using git?
http://www.packetfence.org/support/faqs/article/how-to-install-packetfence-on-ubuntu.html?no_cache=1&cHash=555ea3ede132b946571f92babdfd0081

**Comment by julsemaan** [comment]
You can still apply it using the following commands

```
cd /usr/local/pf
curl https://github.com/inverse-inc/packetfence/commit/157cc10d8faac518b41bcd89214e69365e082591.patch | patch -p1
```

To test it before you really patch it add `--dry-run` at the end of the command (i suggest you do)
