### ISSUE TITLE
Creating a node in IE asks to save response

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#848]

**Comment by jrouzierinverse** [comment]
@julsemaan do you remember which version of IE?

**Comment by julsemaan** [comment]
The best one, IE8

**Comment by jrouzierinverse** [comment]
On XP or win7

**Comment by jrouzierinverse** [comment]
The only way to fix this is to set the content-type header for json data to 'text/plain'.

I will move this to 5.5 so we can do a full test on all the browsers.

http://stackoverflow.com/questions/6114360/ie-prompts-to-open-or-save-json-result-from-server

http://blog.degree.no/2012/09/jquery-json-ie8ie9-treats-response-as-downloadable-file/
