### ISSUE TITLE
Create a local account work but display an error message

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#860]
Setup an external source, tick "Create Local Account", an error appear: (the email is still sent and the local account is created but without any password)

```
ERROR: Caught exception in captiveportal::Controller::Authenticate->createLocalAccount "Attribute (value) does not pass the type constraint because: Validation failed for 'Str' with value undef at constructor pf::Authentication::Action::new (defined at /usr/local/pf/lib/pf/Authentication/Action.pm line 43) line 41
    pf::Authentication::Action::new('pf::Authentication::Action', 'HASH(0x7ff3dccbdbb8)') called at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Authenticate.pm line 386
    captiveportal::PacketFence::Controller::Authenticate::createLocalAccount('captiveportal::Controller::Authenticate=HASH(0x7ff3e26ed870)', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'HASH(0x7ff3e3b6c498)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x7ff3e277d2f8)', 'captiveportal::Controller::Authenticate=HASH(0x7ff3e26ed870)', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'HASH(0x7ff3e3b6c498)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    Catalyst::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Authenticate', 'Catalyst::Action=HASH(0x7ff3e277d2f8)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Authenticate', 'Catalyst::Action=HASH(0x7ff3e277d2f8)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7ff3e277d2f8)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'forward', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7ff3e3b71758)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7ff3e3b71758)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
    Catalyst::forward('captiveportal=HASH(0x7ff3ded2e9e8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7ff3e3b71758)') called at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm line 323
    captiveportal::PacketFence::Controller::Activate::Email::doSponsorRegistration('captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x7ff3e27a2db0)', 'captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    Catalyst::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a2db0)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a2db0)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7ff3e27a2db0)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'forward', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'doSponsorRegistration', 'ARRAY(0x7ff3e3b579e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'captiveportal=HASH(0x7ff3ded2e9e8)', 'doSponsorRegistration', 'ARRAY(0x7ff3e3b579e8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
    Catalyst::forward('captiveportal=HASH(0x7ff3ded2e9e8)', 'doSponsorRegistration', 'ARRAY(0x7ff3e3b579e8)') called at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm line 82
    captiveportal::PacketFence::Controller::Activate::Email::code('captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x7ff3e27a2b40)', 'captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    Catalyst::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a2b40)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a2b40)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7ff3e27a2b40)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Controller.pm line 125
    Catalyst::Controller::_ACTION('captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x7ff3e279e810)', 'captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    Catalyst::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e279e810)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e279e810)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7ff3e279e810)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'forward', 'captiveportal=HASH(0x7ff3ded2e9e8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
    Catalyst::forward('captiveportal=HASH(0x7ff3ded2e9e8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst/Controller.pm line 99
    Catalyst::Controller::_DISPATCH('captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x7ff3e27a0468)', 'captiveportal::Controller::Activate::Email=HASH(0x7ff3e26f2578)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '132fdd612a5ff4204fa69ec92a0dfdf9') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
    Catalyst::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a0468)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7ff3ded2e9e8)', 'captiveportal::Controller::Activate::Email', 'Catalyst::Action=HASH(0x7ff3e27a0468)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7ff3e27a0468)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'forward', 'captiveportal=HASH(0x7ff3ded2e9e8)', '/activate/email/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'captiveportal=HASH(0x7ff3ded2e9e8)', '/activate/email/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
    Catalyst::forward('captiveportal=HASH(0x7ff3ded2e9e8)', '/activate/email/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 105
    Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x7ff3dbe79738)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1637
    Catalyst::dispatch('captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/Static/Simple.pm line 76
    Class::MOP::Class:::around('CODE(0x7ff3e0734d18)', 'captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 162
    Class::MOP::Method::Wrapped::__ANON__('captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 91
    captiveportal::dispatch('captiveportal=HASH(0x7ff3ded2e9e8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1987
    Catalyst::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 76
    eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x7ff3e3968838)', 'Try::Tiny::Catch=REF(0x7ff3e3968208)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1993
    Catalyst::handle_request('captiveportal', 'env', 'HASH(0x7ff3dd7714b0)', 'response_cb', 'CODE(0x7ff3e39051f8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50
    Class::MOP::Method::Wrapped::__ANON__('captiveportal', 'env', 'HASH(0x7ff3dd7714b0)', 'response_cb', 'CODE(0x7ff3e39051f8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 91
    captiveportal::handle_request('captiveportal', 'env', 'HASH(0x7ff3dd7714b0)', 'response_cb', 'CODE(0x7ff3e39051f8)') called at /usr/share/perl5/vendor_perl/Catalyst/Engine.pm line 682
    Catalyst::Engine::__ANON__('CODE(0x7ff3e39051f8)') called at /usr/share/perl5/vendor_perl/Plack/Handler/Apache2.pm line 67
    Plack::Handler::Apache2::call_app('Plack::Handler::Apache2=HASH(0x7ff3dd9f8780)', 'Apache2::RequestRec=SCALAR(0x7ff3e3904640)', 'CODE(0x7ff3e3905720)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 2687
    captiveportal::handler('Apache2::RequestRec=SCALAR(0x7ff3e3904640)') called at -e line 0
    eval {...} called at -e line 0" (captiveportal::PacketFence::Controller::Root::end)
```

**Comment by whitx** [comment]
Caught exception in captiveportal::Controller::Authenticate->createLocalAccount "Attribute (value) does not pass the type constraint because: Validation failed for 'Str' with value undef at constructor pf::Authentication::Action::new (defined at /usr/local/pf/lib/pf/Authentication/Action.pm line 72) line 33
	pf::Authentication::Action::new('pf::Authentication::Action', 'HASH(0x7f59a14a7f60)') called at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Authenticate.pm line 394
	captiveportal::PacketFence::Controller::Authenticate::createLocalAccount('captiveportal::Controller::Authenticate=HASH(0x7f59a0b67390)', 'captiveportal=HASH(0x7f599e335fa8)', 'HASH(0x7f59a15cdfb8)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x7f59a0c95a98)', 'captiveportal::Controller::Authenticate=HASH(0x7f59a0b67390)', 'captiveportal=HASH(0x7f599e335fa8)', 'HASH(0x7f59a15cdfb8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	Catalyst::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Authenticate', 'Catalyst::Action=HASH(0x7f59a0c95a98)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
	Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Authenticate', 'Catalyst::Action=HASH(0x7f59a0c95a98)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7f59a0c95a98)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'forward', 'captiveportal=HASH(0x7f599e335fa8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7f59a15ce348)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'captiveportal=HASH(0x7f599e335fa8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7f59a15ce348)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
	Catalyst::forward('captiveportal=HASH(0x7f599e335fa8)', 'Authenticate', 'createLocalAccount', 'ARRAY(0x7f59a15ce348)') called at /usr/local/pf/html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Sms.pm line 76
	captiveportal::PacketFence::Controller::Activate::Sms::index('captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x7f59a0c99420)', 'captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	Catalyst::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0c99420)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
	Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0c99420)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7f59a0c99420)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Controller.pm line 125
	Catalyst::Controller::_ACTION('captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x7f59a0cb7128)', 'captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	Catalyst::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0cb7128)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
	Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0cb7128)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7f59a0cb7128)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'forward', 'captiveportal=HASH(0x7f599e335fa8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'captiveportal=HASH(0x7f599e335fa8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
	Catalyst::forward('captiveportal=HASH(0x7f599e335fa8)', '_ACTION') called at /usr/share/perl5/vendor_perl/Catalyst/Controller.pm line 99
	Catalyst::Controller::_DISPATCH('captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x7f59a0cbc650)', 'captiveportal::Controller::Activate::Sms=HASH(0x7f59a0b6c6d0)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	eval {...} called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1691
	Catalyst::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0cbc650)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/StackTrace.pm line 22
	Catalyst::Plugin::StackTrace::execute('captiveportal=HASH(0x7f599e335fa8)', 'captiveportal::Controller::Activate::Sms', 'Catalyst::Action=HASH(0x7f59a0cbc650)') called at /usr/share/perl5/vendor_perl/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x7f59a0cbc650)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 257
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'forward', 'captiveportal=HASH(0x7f599e335fa8)', '/activate/sms/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 237
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'captiveportal=HASH(0x7f599e335fa8)', '/activate/sms/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 358
	Catalyst::forward('captiveportal=HASH(0x7f599e335fa8)', '/activate/sms/_DISPATCH') called at /usr/share/perl5/vendor_perl/Catalyst/Dispatcher.pm line 105
	Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x7f599d10daf8)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1637
	Catalyst::dispatch('captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst/Plugin/Static/Simple.pm line 76
	Class::MOP::Class:::around('CODE(0x7f599a37e458)', 'captiveportal=HASH(0x7f599e335fa8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 162
	Class::MOP::Method::Wrapped::__ANON__('captiveportal=HASH(0x7f599e335fa8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 91
	captiveportal::dispatch('captiveportal=HASH(0x7f599e335fa8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1987
	Catalyst::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 76
	eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
	Try::Tiny::try('CODE(0x7f59a1227938)', 'Try::Tiny::Catch=REF(0x7f59a12bd2e8)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 1993
	Catalyst::handle_request('captiveportal', 'env', 'HASH(0x7f59a1483ab8)', 'response_cb', 'CODE(0x7f59a12d13d8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 50
	Class::MOP::Method::Wrapped::__ANON__('captiveportal', 'env', 'HASH(0x7f59a1483ab8)', 'response_cb', 'CODE(0x7f59a12d13d8)') called at /usr/lib64/perl5/vendor_perl/Class/MOP/Method/Wrapped.pm line 91
	captiveportal::handle_request('captiveportal', 'env', 'HASH(0x7f59a1483ab8)', 'response_cb', 'CODE(0x7f59a12d13d8)') called at /usr/share/perl5/vendor_perl/Catalyst/Engine.pm line 682
	Catalyst::Engine::__ANON__('CODE(0x7f59a12d13d8)') called at /usr/share/perl5/vendor_perl/Plack/Handler/Apache2.pm line 67
	Plack::Handler::Apache2::call_app('Plack::Handler::Apache2=HASH(0x7f599f4b1b98)', 'Apache2::RequestRec=SCALAR(0x7f59a13b4cf0)', 'CODE(0x7f59a12b8e58)') called at /usr/share/perl5/vendor_perl/Catalyst.pm line 2687
	captiveportal::handler('Apache2::RequestRec=SCALAR(0x7f59a13b4cf0)') called at -e line 0

**Comment by jrouzierinverse** [comment]
The issue seems to be that the unregdate is not being set
