### ISSUE TITLE
Registering by SMS can give default PID

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#862]
To reproduce : 
Registering by SMS, then being on the SMS PIN page
Waiting 10 minutes for it to expire
enter the PIN

The session is not there anymore and it uses the default PID instead of showing an error or taking the one from the activation record

**Comment by jrouzierinverse** [comment]
DIdn't you fix this?

**Comment by julsemaan** [comment]
yes was just about to close it :P

It's in dfd8c598a7458376fbbf6fed30da6b95c76b7a92
