### ISSUE TITLE
Bulk change on the web admin interface

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#865]
When you do bulk role changes from the search then action menu the message just says that it successfully changed the role but it doesn't say what the role was changed to. There was a few times that i thought that maybe i changed it to the wrong role this would just be a good way to confirm you did what you wanted to do.

**Comment by julsemaan** [comment]
Fixes via 1a3ac2b604373aec29f96ebd20d6cf66fbacde88
