### ISSUE TITLE
Locationlog entry is opened even when sending an access-reject

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#890]
Doesn't seem like a good behavior as the client was not technically connected to the network but only attempting to connect

**Comment by louismunro** [comment]
Still seems useful though.
When troubleshooting it is often useful to know where a connection attempt was coming from.

**Comment by julsemaan** [comment]
Yes but let's say you use it to look at where that device was connected then the admin tells you it connected to a forbidden SSID, you can't be sure about what happened unless you know PF very well.

One solution could be to flag them in the locationlog and display them in red in the admin so they appear as failed attempts

**Comment by louismunro** [comment]
Right. But then we need to deal with the added complexity and UX issues.
Good points on both sides. 
Do we have a simple way of tracking those failed connection attempts and mark them as such? 
How much more complex would it make the SQL to display that field?

**Comment by julsemaan** [comment]
We usually send VLAN -1 to the locationlog_synchronize but it doesn't seem to save it in the row.

We could save it and use it as a reject flag

**Comment by julsemaan** [comment]
Dug through the code and we don't actually open a locationlog entry during an access reject but we open one during the autoreg flow (which then gets closed when returning the accept).

This is the entry that gives confusion as if you are not autoreg no locationlog is opened in a reject.
If you are autoreg, the entry is opened

We seriously need to reconsider lib/pf/radius.pm +181
