### ISSUE TITLE
Configure remote syslog server

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#903]
Add the ability to configure a remote syslog server to which PacketFence sends the logs

Options that would be nice to have:
- Select if we keep a local copy;
- Select which logs to send;

**Comment by julsemaan** [comment]
+1 Getting asked that a lot

**Comment by louismunro** [comment]
I think we should send everything to syslog by default.
Then we can save a copy locally and optionally send one to a second server.

This way there is a single place to configure logging.  

## 

LM

**Comment by piellick** [comment]
hi , this feature is still on dev ?

**Comment by dwlfrth** [comment]
Almost there

**Comment by jrouzierinverse** [comment]
Things to deal with
 - [ ] In a cluster contact the api to restart syslog service after changes syslog config
 - [x] Use a config generation script that has the minimum dependencies (no pfconfig).
 - [x] Use a systemd unit file override config for rsyslog
 - [ ] The config will consist of the ability to add multiple servers and select which logs are sent at which log level.
 - [x] The generated config file is placed in /etc/rsyslog.d/
 - [ ] Generate the available services/logs names from the services in pf::services::manager::* (auto gen module done via packaging)

**Comment by jrouzierinverse** [comment]
After updating the config should we.
* Warning the users they need to restart their syslog services in order for changes to take place.
* Should we have the rsyslog service be automatically across the cluster.

**Comment by julsemaan** [comment]
I'd go with warning users to restart the rsyslog service as its usually how we proceed right now.
