### ISSUE TITLE
Machine Auth

### ISSUE THREAD

**Issue by hooray4me** [inverse-inc/packetfence#906]
User authentication against Active Directory has been working fine. Machine Auth has never worked. I have a Cisco WLC configured to for radius auth against packetfence. The WLC give
**AAA Authentication Failure for UserName:host/Robs-Laptop.XXXXXXXXX.local User Type: WLAN USER**
I'm assuming its because the username for the machine is not being rewritten somehow from host/Robs-Laptop.XXXXXXXXX.local to Robs-Laptop.XXXXXXXXX.local, which is what the look lookup against AD is looking for... 
Any suggestions?

**Comment by fdurand** [comment]
Yes check that: https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Administration_Guide.asciidoc#example

**Comment by hooray4me** [comment]
Not sure why this was closed... This doesn't help me. I've been thru this documentation many times and configured as such.  
Am I missing something
![image](https://cloud.githubusercontent.com/assets/12399138/10064178/606ed4dc-623b-11e5-8b2c-fbcda0e4d666.png)

**Comment by fdurand** [comment]
i closed it because it's a configuration issue, not a bug.
Can you use the mailling list for that ?
packetfence-users@lists.sourceforge.net
