### ISSUE TITLE
Machine Auth continued

### ISSUE THREAD

**Issue by hooray4me** [inverse-inc/packetfence#907]
User authentication against Active Directory has been working fine. Machine Auth has never worked. I have a Cisco WLC configured to for radius auth against packetfence. The WLC give
AAA Authentication Failure for UserName:host/Robs-Laptop.XXXXXXXXX.local User Type: WLAN USER
I'm assuming its because the username for the machine is not being rewritten somehow from host/Robs-Laptop.XXXXXXXXX.local to Robs-Laptop.XXXXXXXXX.local, which is what the look lookup against AD is looking for... 
Any suggestions?

---

**(this provided me no information I didn't already have)**
Yes check that: https://github.com/inverse-inc/packetfence/blob/devel/docs/PacketFence_Administration_Guide.asciidoc#example

---

Issue Closed Without Resolution

---

Not sure why this was closed... This doesn't help me. I've been thru this documentation many times and configured as such.

Am I missing something
![image](https://cloud.githubusercontent.com/assets/12399138/10064468/3f11ded0-623e-11e5-84ef-8f970fc7b368.png)

**Comment by louismunro** [comment]
Use the mailing list for support questions please.

**Comment by hooray4me** [comment]
No one has responded _to me_ on the mailing list :( :-1: and for the record, a mailing list is a horrible method for "support"

**Comment by louismunro** [comment]
Really? So the archives are all just lies?
