### ISSUE TITLE
Portal profiles are not configurable.

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#911]
Portal profiles cannot be saved.
The error returned is "Error! Type field is required". 

This is on a fresh install.

**Comment by whitx** [comment]
Also if you have portal profile already existing, it will select 'ConnectionType' as your filter, no matter what you have selected.

**Comment by jrouzierinverse** [comment]
This has been fixed by commit e026880aedf848cb86cb43f16dae17cc5e9d2a0b
