### ISSUE TITLE
Dots in authentication sources break templating

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#925]
A source with a name containing a dot ('.') breaks the admin.

Looks like TT is not properly escaped or otherwise able to handle that case.

**Comment by louismunro** [comment]
The error in the logs will look like 
`==> ./httpd.admin.log <==
Sep 29 17:05:19 httpd.admin(3808) ERROR: Caught exception in pfappserver::Controller::Config::Switch->begin "did not find parent for field maastrichtuniversity.nlVlan at /usr/share/perl5/HTML/FormHandler/BuildFields.pm line 239." (pfappserver::PacketFence::Controller::Root::end)
Sep 29 17:05:19 httpd.admin(3808) ERROR: Argument "" isn't numeric in subtraction (-) at /usr/local/pf/html/pfappserver/root/config/switch/list.tt line 2.
 (pfappserver::__ANON__)`

**Comment by jrouzierinverse** [comment]
The problem is that HTML::FormHandler uses "." as namespace a field/namespace separator.

**Comment by louismunro** [comment]
Right. That is not entirely unexpected.
Still, should we prevent users from saving sources with dots in their names from the GUI?
This question popped up on the mailing list, so someone somewhere has already done it.

**Comment by julsemaan** [comment]
IMO, we should prevent dots

The specials characters other than dashes and underscores should not be trusted in our ids

![image](https://cloud.githubusercontent.com/assets/3857942/10178049/84894e08-66cb-11e5-91ea-fced66da2234.png)

**Comment by extrafu** [comment]
Are we affected with usernames with dot?

**Comment by jrouzierinverse** [comment]
No it should not be it is only affects the form field names.

In the case of switches we uses role names to compute some dynamic fields.
So for the roles role1, role2 and leroy the following fields are created

role1Vlan
role2Vlan
leroyVlan

So if there is a role named bob.marley

A field bob.marleyVlan will be created.

As mentioned before HTML::FormHandler uses the dot to separate subfield.

So the form handler will look for a compound field named bob with a sub field marleyVlan.

Which does not exists.

So the FormHandler will fail to be created

**Comment by julsemaan** [comment]
@jrouzierinverse 
What is the status on this ?
IMO simply preventing to use dots in auth source would be enough
