### ISSUE TITLE
two small gui suggestions

### ISSUE THREAD

**Issue by heupink** [inverse-inc/packetfence#926]
- The init script on debian says "stoping" instead "stopping"

On the node search page:
- The pull down menu has a choice to search on "person name" and it
  seems to search in the column called "owner". Perhaps the pulldown
  should also use "owner".

**Comment by julsemaan** [comment]
I'll take care of the second

**Comment by jrouzierinverse** [comment]
The first was fixed by 6005814181519180d72524123699c5cd06318352

**Comment by julsemaan** [comment]
yay less work for me :dancer:

**Comment by extrafu** [comment]
We close it?

**Comment by julsemaan** [comment]
I still have to fix:

 * The pull down menu has a choice to search on "person name" and it
seems to search in the column called "owner". Perhaps the pulldown
should also use "owner".

Will take me 2 minutes, I'll try to do a bug blitz today

**Comment by kkplein** [comment]
Thanks for fixing! :-)
