### ISSUE TITLE
Centos download RPM is not available - broken link

### ISSUE THREAD

**Issue by maxeaves** [inverse-inc/packetfence#940]
Hello PacketFence chaps

Can you fix the URL issues or lack of RPM on the website for downloading the 5.4.0-1 file.  It is currently very broken - and trying to build from source....is proving to be interestingly difficult!

Thanks

Max

**Comment by extrafu** [comment]
We'll fix the path, the proper one for now is:

http://inverse.ca/downloads/PacketFence/RHEL6/x86_64/RPMS/packetfence-5.4.0-1.el6.noarch.rpm

The error comes from the fact we not build anymore the i386 version.

You should nonetheless never just install just that RPM as it has a lot of dependancies.

**Comment by cgx** [comment]
Thank you for reporting the issue. The website has been updated.
