### ISSUE TITLE
Inline: Node not being removed from 'reg' set if iplog entry is closed

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#943]
Example:
A node is set to be unreg by pfmon at midnight. That node gets an ip during the day and the lease is of 3 hours. The node does not renew the lease so the iplog entry is closed at the end of lease time.

On pfmon run, it 'isInlineEnforcementRequired' calls 'get_mangle_mark_for_node' which check if there's an active iplog entry. If not (which is the case in the example), 'get_mangle_mark_for_node' return 'UNREG' and 'isInlineEnforcementRequired' is supposed to mark the node UNREG. 

It creates a true condition where the new status is equals to the expected status, then, no action taken.

**Comment by julsemaan** [comment]
@fdurand 

Is this still relevant with the new pfipset ?

**Comment by fdurand** [comment]
Not still revelant.
