### ISSUE TITLE
Support markdown for email templates

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#945]
To render them in html afterwards.

Working in the template just feels like we're in 1995

**Comment by louismunro** [comment]
Hey!
That was a very good year...

**Comment by jrouzierinverse** [comment]
If you were OJ Simpson

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by julsemaan** [comment]
The templates were reworked in HTML by @whitx (probably helped by OJ)
