### ISSUE TITLE
Meraki with Packetfence

### ISSUE THREAD

**Issue by silasnamenya** [inverse-inc/packetfence#946]
Hello,

I am new to packetfence and i am configuring a setup with Meraki APs to work with packetfence using Webauth. In the first enforcement screen, i chose WebAuth and created 2 interfaces (management and portal). In Meraki i redirect all requests to the portal IP. Do i need to add the Meraki devices under the Networks portion in configuration and if so what the exact settings for this such as IP of cloud controller. Any assistance on how to setup Meraki with packetfence will be appreciated.

Thanks and Kind Regards,
Sanya

**Comment by extrafu** [comment]
Use the mailing list - the bug tracker is for _bug reports_.
