### ISSUE TITLE
FreeRADIUS accepts clients that do not send the Message-Authenticator attribute

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#955]
And then replies with his secret ending in a reply drop of the equipment if the secret is mismatched

**Comment by rouzier** [comment]
Can you provide more detail?
Is it for mac/ip or network based switches?

**Comment by julsemaan** [comment]
Any of them.
I'm looking into it now but if you want to join in, please do

**Comment by jrouzierinverse** [comment]
There was no assignee so I assumed nobody was looking into it.
I will be right there in about 10 minutes.

**Comment by julsemaan** [comment]
Will have to determine right behavior when no Message-Authenticator is sent

**Comment by louismunro** [comment]
I believe this to be configurable.
see raddb/clients.conf:

```
    #  Old-style clients do not send a Message-Authenticator                                                                                                                     
    #  in an Access-Request.  RFC 5080 suggests that all clients
    #  SHOULD include it in an Access-Request.  The configuration
    #  item below allows the server to require it.  If a client
    #  is required to include a Message-Authenticator and it does
    #  not, then the packet will be silently discarded.
    #
    #  allowed values: yes, no
    require_message_authenticator = no
```

**Comment by julsemaan** [comment]
The thing is that the big winner for not including the attribute is.... the WLC

So we can't force it

I think I'll just end up documenting it under the WLC as a troubleshooting step

**Comment by alandekok** [comment]
That's how RADIUS works.  It's not a bug in FreeRADIUS.  It's a bug in the underlying RADIUS protocol.
