### ISSUE TITLE
Admin : Cloning a switch breaks RADIUS secret field when credentials are saved in browser

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#956]

**Comment by jrouzierinverse** [comment]
Please provide more details on what exactly is happening.
I tried to replicate this but could not.

**Comment by julsemaan** [comment]
With the additionnal details provided verbally, is it ok ?

Also do you want to get it assigned to you ?

**Comment by jrouzierinverse** [comment]
Yup

**Comment by julsemaan** [comment]
Did you test it with the use case we have ?
Because we will need to put this in the maintenance as it corrupts switch configurations

**Comment by julsemaan** [comment]
maintenance branches....
