### ISSUE TITLE
Update documentation Opswat gears

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#957]
- Change the link to download the agent
- Change Client ID for Clien Key for the provisioner configuration

**Comment by julsemaan** [comment]
Screenshots for adjustements

![image](https://cloud.githubusercontent.com/assets/3857942/10525929/87af510e-7355-11e5-8ab2-94cbd29eb01e.png)

![image](https://cloud.githubusercontent.com/assets/3857942/10525927/84457264-7355-11e5-9530-f5d7fb6f3c44.png)

**Comment by julsemaan** [comment]
Fixed via f49aa30a00781cd173c87ffb5428a7c728dcaa26 and 5c29ad9176185fd72ebb666f433efd74e37f2c20
