### ISSUE TITLE
getBitAtPosition is buggy

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#964]
Let's say that we have a phone that is only telephone capable (LLDP values) , the snmpget will return:
iso.0.8802.1.1.2.1.4.1.1.12.0.10.29 = Hex-STRING: 04 00 (0000100000000000)

getBitAtPosition is suppose to test the bit at position 5 and return 1, but it return 0.

Proposed fix:

``` perl
diff --git a/lib/pf/Switch.pm b/lib/pf/Switch.pm
index efada56..d15b5da 100644
--- a/lib/pf/Switch.pm
+++ b/lib/pf/Switch.pm
@@ -1758,7 +1758,8 @@ The input must be the untranslated raw result of 
an snmp g
 # TODO move out to a util package
 sub getBitAtPosition {
    my ($this, $bitStream, $position) = @_;
-   return substr(unpack('B*', $bitStream), $position, 1);
+   my $bin = unpack("B*", pack("N", hex $bitStream));
+   return substr(substr ($bin, length($bin)/2), $position, 1);
 }

 =item modifyBitmask
```

**Comment by erSitzt** [comment]
Thats because you are wrong i think...

04 00
is
0000 0100 0000 0000
isnt it ?

And the lldpremcap-map starts at bit 0 from the left, so telephone should be the sixth bit
other(0)
repeater(1)
bridge(2)
wlanAccessPoint(3)
router(4)
telephone(5)
docsisCableDevice(6)
stationOnly(7)

This is how it looks for my switch ( HP ProCurve 2620 )
snmpwalk -v2c -c public 172.16.4.16 1.0.8802.1.1.2.1.4.1.1.12
iso.0.8802.1.1.2.1.4.1.1.12.0.7.2 = Hex-STRING: 04

**Comment by fdurand** [comment]
So what is the return of this function in your case ?

``` perl
print substr(unpack('B*', "0x04"), 5, 1);
```

**Comment by erSitzt** [comment]
It returns 0.
But did you check what 
`unpack('B*', "0x04")` 
returns ?

It returns this for me  :
00110000011110000011000000110100

**Comment by fdurand** [comment]
Yes, the wrong value : 00110000011110000011000000110100
It should be : 0000 0100

So getBitAtPosition is buggy

**Comment by erSitzt** [comment]
In my case unpack returns 00000100 for the value returned by snmp.
And getBitAtPosition returns 1

Your changes cause this

Illegal hexadecimal digit '' ignored at test2_snmp.pl line 202.
00000000000000000000000000000000 (print unpack(... )
Illegal hexadecimal digit '' ignored at test2_snmp.pl line 203.
0 ( print substr(unpack(...)

**Comment by erSitzt** [comment]
Hmm.. ok i remember something.
It had something to do with the settings of Net::SNMP
With
 -translate     => [-octetstring => 0],
it works.

Sorry i was confusing things between my test-environment  :(
But still your version does not work for me.

This works for me;
return substr(unpack('B*', pack("C", hex $bitStream)), $position, 1);

**Comment by fdurand** [comment]
But not for "0x0400" (Cisco return)

**Comment by erSitzt** [comment]
Yeah just saw that...

**Comment by erSitzt** [comment]
Sorry for wasting your time ;) next time i'll not answer before going to sleep :)

**Comment by erSitzt** [comment]
For  "0x04" returned by HP switches this does not work
`substr(substr ($bin, length($bin)/2), $position, 1);`

**Comment by fdurand** [comment]
Let's try that:

``` perl
 sub getBitAtPosition {
    my ($this, $bitStream, $position) = @_;
    my $bin;
    my @bitStream = split('0x', $bitStream);
    while (my $tmp = substr($bitStream[1], -2, 2, undef))
        {
        $bin = unpack("B8", pack("H2", $tmp)) . $bin;
        }
    return substr($bin, $position, 1);
}
```

**Comment by erSitzt** [comment]
Looks good. :+1:

**Comment by erSitzt** [comment]
With that change the following line needs to be changed, because thats how i corrected the old behavior for my HP-Switches

https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/Switch/HP/Procurve_2920.pm#L92
