### ISSUE TITLE
Users or nodes Web UI pages don't load in IE11 with version 5.4.0

### ISSUE THREAD

**Issue by idnahacks** [inverse-inc/packetfence#972]
I have two PF environments, my 5.0.1 environment has no problem in IE11, however my newer environment running 5.4.0 will not load the nodes or users tabs in the web UI. It jsut sits there with the 3 dots flashing as if loading.

I was previously running 5.3.1 in this environment and upgraded to see if this fixed the issue, but it didn't. I have tried running the /usr/local/pf/addons/pf-maint.pl script to grab all the latest patches, but this is still happening.

I don't see this happen in Firefox, Chrome, or MS Edge browsers, but typically 50% of my users here use IE11.
![ie11 v5 4](https://cloud.githubusercontent.com/assets/12153311/10643610/a38b8c38-781b-11e5-8ff6-4835337c6a96.JPG)

Please let me know if there's anything you want me to do to test this at this end.

**Comment by julsemaan** [comment]
Are we going to fix this and take care of IE ?

Otherwise, lets close that...
