### ISSUE TITLE
dhcpd.pm unable to detect inline for domain-name-server configuration in clustered mode

### ISSUE THREAD

**Issue by simongottschlag** [inverse-inc/packetfence#975]
Hi,

I've got a cluster up and running with inline mode and it seems like dhcpd.pm is configuring dhcpd.conf to use the cluster nodes as dns servers and not the nodes configured in the networks.conf-file.

Any idea how we can resolve this?

Thanks!

**Comment by fdurand** [comment]
Can you try that:

``` perl
diff --git a/lib/pf/services/manager/dhcpd.pm b/lib/pf/services/manager/dhcpd.pm
index f4c3e37..af3b402 100644
--- a/lib/pf/services/manager/dhcpd.pm
+++ b/lib/pf/services/manager/dhcpd.pm
@@ -113,7 +113,7 @@ EOT
                     }
                     if ($members) {
                         if ($current_network->contains($ip)) {
-                            $dns = $members;
+                            $dns = $members if ( !pf::config::is_network_type_inline($network) );
                         $active = defined($net{next_hop}) ? 
                                  NetAddr::IP::Lite->new($net{'next_hop'}, $cfg->{'mask'}) :
                                  NetAddr::IP::Lite->new($cfg->{'ip'}, $cfg->{'mask'});
```

**Comment by simongottschlag** [comment]
Hi,

Yes, that fixed the issue! I've tried changing the DNS-servers in networks.conf and the changes are now present in the dhcpd.conf.

Thanks!

**Comment by julsemaan** [comment]
I don't think we support inline in active/active though.

Losing a node will be problematic for the ipsets

@dwlfrth can confirm

**Comment by fdurand** [comment]
on registration it should work (ipset add), but on unregistration we will probably have issue (pfmon to remove ipset on both)

**Comment by simongottschlag** [comment]
Hi,

active/passive is fine with us. Do I have to configure anything to get it to work in active/passive?

**Comment by dwlfrth** [comment]
As @julsemaan and @fdurand both said, inline mode may have some issues with active/active mode.

**Comment by dwlfrth** [comment]
Since, for the moment, inline mode in active/active is a "more than risky" road, this issue will be closed.
