### ISSUE TITLE
SCEP PKI failing to request certificates

### ISSUE THREAD

**Issue by slm4996** [inverse-inc/packetfence#976]
We have a MS SCEP server configured as per the 5.4 docs. Following the SCEP troubleshooting guide everything works as expected. When a user generates a certificate throught the portal they make it to click ing the "generate" button and then get the following message

```
Caught exception in captiveportal::Controller::TLSProfile->get_bundle "Use of uninitialized value in subroutine entry at /usr/local/pf/lib/pf/pki_provider/scep.pm line 111."
```

From what I can tell the issue lies in the fact that the certificate never gets created. When inserting extra debugging the read_file($cert_path); throws an exception of "File not found".

What further information do you need to investigate?
Packetfence version 5.4.0 running from the ZEN image on vmware.

**Comment by fdurand** [comment]
Hello,
it sounds like a miss configuration and not a bug.
Can you use the mailling list instead. (PacketFence-users@lists.sourceforge.net)
Thanks
Fabrice
