### ISSUE TITLE
RADIUS: rpc_config values

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#981]
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/services/manager/radiusd.pm#L73

Takes some values that are meant to be used for webservices.

We kind of use "two rpc clients" with one-ish configuration.

It may break when, per example, I want to run webservices over https but RADIUS, since it is authenticating locally, runs over http...

**Comment by julsemaan** [comment]
Not sure if its really relevant anymore.

I'll close this
