### ISSUE TITLE
site-enabled/inner-tunnel prevent starting radiusd

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#989]
Wed Oct 28 15:04:49 2015 : Error: Failed binding to authentication address 127.0.0.1 port 18120 as server inner-tunnel: Address already in use 
Wed Oct 28 15:04:49 2015 : Error: /usr/local/pf/raddb//sites-enabled/inner-tunnel[32]: Error binding to port for 127.0.0.1 port 18120

**Comment by louismunro** [comment]
Looks like that file (sites-enabled/inner-tunnel) is no longer part of PacketFence.
Removing it has to be added to the upgrade guide.
Remove sites-enabled/default at the same time.

**Comment by louismunro** [comment]
Please don't commit to devel without a PR.
