### ISSUE TITLE
pairmap is not in List::Util 1.21

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#996]
Thus the auth sources using it (Stripe, Mirapay, Paypal) don't compile

**Comment by jrouzierinverse** [comment]
Install perl-Scalar-List-Utils from packetfence-devel

**Comment by louismunro** [comment]
Packaging issue then?

**Comment by jrouzierinverse** [comment]
Yes taken care of

**Comment by julsemaan** [comment]
The packaging hasn't been taken care of.

It doesn't specify the minimal version.

Should someone do a simple upgrade like 'yum update packetfence' the perl-Scalar-Util will NOT be upgraded

**Comment by jrouzierinverse** [comment]
In this case yes it will.
List::Util is a core perl module so it is installed with the perl package.
This package simply overrides the module provided by the standard perl module.
Since there was no previous perl-Scalar-List-Utils installed when a 'yum update' is done it will grab this package.
